SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC


SELECT LING.ESTADO,LING.NOINGRESO,LING.TIPOINGRESO,LING.FECHA,LING.AMBITOTR,LING.CCOSTO,LING.NOADMISION,LING.NOPRESTACION,HHAB.SECTOR,AFI.IDAFILIADO,AFI.DIRECCION,AFI.SEXO,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,AFI.FNACIMIENTO,AFI.EDAD,AFI.PNOMBRE,AFI.SNOMBRE,AFI.PAPELLIDO,AFI.SAPELLIDO,AFI.CIUDAD,AFI.CELULAR,COALESCE(AFI.CELULAR, AFI.TELEFONORES) TELEFONORES,(SELECT COUNT(*) FROM LORD WHERE  LORD.NOINGRESO = LING.NOINGRESO AND LORD.ESTADO <> 'R' AND COALESCE(LORD.REALIZADO,0) = 0 ) SIN_RESULTADO,AFI.EMAIL,AFI.TIPOAFILIADO,AFI.NIVELSOCIOEC,EDADN = floor((CONVERT([int], CONVERT([varchar](8), getdate(), (112))) - CONVERT([int], CONVERT([varchar](8), AFI.FNACIMIENTO, (112)))) / (10000)),TER.IDTERCERO,TER.RAZONSOCIAL,PLN.IDPLAN,PLN.DESCPLAN,(SELECT GRUPOABO FROM DBO.FNK_GRUPOSANG_AFI(AFI.IDAFILIADO)) GRUPOABO,(SELECT GRUPORH FROM DBO.FNK_GRUPOSANG_AFI(AFI.IDAFILIADO)) GRUPORH, AFI.GRUPO_SANG,PRESTACION = (SELECT LORD.NOINGRESO, LORD.IDSERVICIO , SER.DESCSERVICIO, LORD.NOITEM,LORD.USUARIORES, LORD.ESTADO, LORD.NORDEN, CAST(LORD.REALIZADO AS BIT) REALIZADO                         , LORD.USULIBERA, LORD.USUARIOTRAE, LORD.MARCA, SER.AMBITO, LING.AMBITOTR,LORD.OBSERVACION, LORD.FECHARES, LORD.RESPMUESTRA, LORD.FECHAMUESTRA, LING.IDAFILIADO, AFI.NOMBREAFI                         , CAST( COALESCE(LORD.MUESTRA,0) AS BIT) MUESTRA, LORD.IDMEDICO, MED.NOMBRE, SER.IDPLANILLA, LPLA.DESCRIPCION [LPLA_DESC], RESULTADO = COALESCE(LORD.RESULTADO,'')                         FROM LORD                           INNER JOIN SER ON LORD.IDSERVICIO = SER.IDSERVICIO                           LEFT JOIN MED ON LORD.IDMEDICO = MED.IDMEDICO                           LEFT JOIN LPLA ON SER.IDPLANILLA = LPLA.IDPLANILLA                         WHERE LORD.NOINGRESO = LING.NOINGRESO                         ORDER BY LORD.NOITEM ASC                         FOR JSON PATH)  FROM [dbo].[LING] INNER JOIN AFI ON LING.IDAFILIADO = AFI.IDAFILIADO LEFT JOIN  TER ON LING.IDTERCERO = TER.IDTERCERO LEFT JOIN  PLN ON LING.IDPLAN = PLN.IDPLAN LEFT JOIN  HADM ON LING.NOADMISION = HADM.NOADMISION LEFT JOIN  HHAB ON HADM.HABCAMA = HHAB.HABCAMA WHERE (NOMBREAFI LIKE '%%%%' OR DOCIDAFILIADO LIKE '%%%%') AND  1 = 1  AND  LING.TIPOINGRESO = 'A' AND CONVERT (DATE,LING.FECHA) >= CONVERT(DATE,'2024-07-01') AND CONVERT (DATE,LING.FECHA) <= CONVERT(DATE,'2024-08-05') AND ( 1=1 AND (AFI.NOMBREAFI LIKE '%1068814492%' OR AFI.DOCIDAFILIADO LIKE '%1068814492%' OR LING.NOADMISION LIKE '%1068814492%' OR LING.NOINGRESO LIKE '%1068814492%') ) AND  LING.AMBITOTR = 'TG'  ORDER BY LING.FECHA DESC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


select FCXC.CNSCXC, FCXC.IDTERCERO,TER.RAZONSOCIAL, FCXC.F_RECIBIDO, FCXC.VALORCXC, FCXCD.N_FACTURA, FCXCD.VALORFACTURANETO, FCXCD.IDPLAN FROM FCXC 
INNER JOIN FCXCD ON FCXCD.CNSCXC=FCXC.CNSCXC
INNER JOIN TER ON TER.IDTERCERO=FCXC.IDTERCERO
WHERE CONVERT(date,F_RECIBIDO)  BETWEEN '20240721' AND '20240821' AND FCXC.INDRECIBIDO=1


SELECT CNSGLOI,  * FROM FGLO WHERE N_FACTURA='CFAS102986'

SELECT * FROM FGLOID WHERE CNSGLO='0100052634'

SELECT  * FROM FGLOID WHERE CNSGLOI='0100002433'

SELECT  * FROM FGLOI WHERE CNSGLOI='0100002629'

UPDATE FGLO SET CNSGLOI=NULL, ASIGNADAIMP=0 WHERE CNSGLOI='0100002659'

INSERT INTO FGLOID
SELECT CNSGLOI,CNSGLO,N_FACTURA,1  FROM FGLO WHERE NOT EXISTS(SELECT  * FROM FGLOID 
WHERE FGLO.CNSGLO=FGLOID.CNSGLO AND FGLOID.CNSGLOI='0100001958')
AND CNSGLOI='0100001958'