

SELECT  DBO.FNK_FECHA_GRINGA()+''+CONVERT(VARCHAR,,108)


SELECT  * FROM USGRUH WHERE GRUPO='JEFFACT'
SELECT  * FROM KPRUEBAS.DBO.USGRUH WHERE GRUPO='JEFFACT'

DELETE USGRUH WHERE GRUPO='JEFFACT'

INSERT INTO USGRUH
SELECT  * FROM KPRUEBAS.DBO.USGRUH WHERE GRUPO='JEFFACT'