

SELECT SUM(VLRITEM- (COALESCE(VLRLEGALIZADO,0)+COALESCE(VLRAJUSTE,0))) 
FROM BMOVD WHERE RECAUDO=1 
AND VLRITEM- (COALESCE(VLRLEGALIZADO,0)+COALESCE(VLRAJUSTE,0))>0

SELECT * FROM VWK_VCTOS WHERE CLASEINFO='SINGLO' AND IDTERCERO='0100000019'