
EXEC DBO.SPK_GEN_TRAMAS_PERU '000002'


SELECT  * FROM TRAMA_DFAC
SELECT  * FROM TRAMA_DATE
SELECT  * FROM TRAMA_DSER
SELECT  * FROM TRAMA_DFAR


SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC


EXEC SPQ_JSON '{"MODELO":"RIPS_COL","METODO":"ENVIAR_RIPS","PARAMETROS":{"ENVIO":"000002","IDTERCERO":"20523470761"},"USUARIO":"JJIMENEZ"}'