IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPKJ_24H' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPKJ_24H
END

GO
CREATE PROC DBO.SPKJ_24H (
	@PORSECTOR BIT=0,
	@SEDE VARCHAR(5)='01'
)
WITH ENCRYPTION
AS 
DECLARE 
    @HOY DATETIME = CONVERT(SMALLDATETIME,GETDATE())
   ,@HOY_SINH DATE = CONVERT(DATE,GETDATE())
   ,@HORA TIME = CONVERT(TIME,GETDATE())
DECLARE 
	@CNSIZSOLM VARCHAR(20), @ESTADO SMALLINT
   ,@I INT, @I_TO INT, @HABCAMA VARCHAR(10), @HORARIO TIME
DECLARE @SECTORES TABLE (I INT IDENTITY, HABCAMA VARCHAR(10), HORARIO TIME)
BEGIN
	SELECT @CNSIZSOLM=CNSIZSOLM, @ESTADO=ISNULL(ESTADO,0) FROM IZSOLM WHERE CONVERT(DATE,FECHA)=@HOY_SINH

    IF @ESTADO=1
	BEGIN 
		PRINT 'Ya se genero el día de hoy y se cerró'
		RETURN
	END

	IF ISNULL(@CNSIZSOLM,'')=''
	BEGIN
		EXEC SPK_GENDIA_OME24 @HOY_SINH, @SEDE, 'Automatico'
		SELECT @CNSIZSOLM=CNSIZSOLM FROM IZSOLM WHERE CONVERT(DATE,FECHA)=@HOY_SINH
	END
	PRINT 'CNSIZSOLM='+@CNSIZSOLM

	IF @PORSECTOR=0
		EXEC SPK_IZSOL_OME24 @CNSIZSOLM, @SEDE, 'Automatico'
	ELSE
	BEGIN
		PRINT 'Recorró los sectores'

		INSERT INTO @SECTORES (HABCAMA, HORARIO)
		SELECT HABCAMA, HORARIO FROM HHAB 
		WHERE CLASE='Sector' AND HABCAMA<>'TODOSECTOR' AND ESTADOHAB NOT IN ('Inhabilitada') AND HORARIO IS NOT NULL AND HORARIO<=@HORA
			AND EXISTS (SELECT 1 FROM HHAB C WHERE C.SECTOR=HHAB.HABCAMA AND C.CLASE='Cama' AND C.ESTADOHAB='Ocupada')
			AND NOT EXISTS (SELECT 1 FROM IZSOL WHERE IZSOL.CLASE='24HORAS' AND IZSOL.CNSIZSOLM=@CNSIZSOLM AND COALESCE(IZSOL.SECTOR,'')=HHAB.HABCAMA)

		SELECT @I=1, @I_TO=MAX(I) FROM @SECTORES

		IF ISNULL(@I_TO,0)=0
		BEGIN
			IF NOT EXISTS (SELECT HABCAMA, HORARIO FROM HHAB WHERE CLASE='Sector' AND HABCAMA<>'TODOSECTOR' 
							AND ESTADOHAB NOT IN ('Inhabilitada') AND HORARIO IS NOT NULL AND HORARIO>@HORA
							AND EXISTS (SELECT 1 FROM HHAB C WHERE C.SECTOR=HHAB.HABCAMA AND C.CLASE='Cama' AND C.ESTADOHAB='Ocupada'))
			BEGIN
				EXEC SPK_IZSOL_OME24 @CNSIZSOLM, @SEDE, 'Automatico'
			END
		END
		ELSE
		BEGIN
			WHILE @I<=@I_TO
			BEGIN
				SELECT @HABCAMA=HABCAMA, @HORARIO=HORARIO FROM @SECTORES WHERE I=@I
				EXEC SPK_IZSOL_OME24 @CNSIZSOLM, @SEDE, 'Automatico', 2, @HABCAMA
				SET @I+=1
			END
			DELETE @SECTORES
		END
	END
END

