IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_NIEPEG' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_NIEPEG
END
GO
CREATE PROCEDURE DBO.SPK_NIEPEG @CONSECUTIVO VARCHAR(6), @TIPONOTA TINYINT=NULL, @CNSNIEPEG_BASE INT=NULL
WITH ENCRYPTION
AS
/* 
Fecha:		 2021-09-20
Descripción: Procedimiento que permite generar la tabla NIEPEG para nómina electrónica
*/
SET NOCOUNT ON
DECLARE @CNSNIEPEG INT
BEGIN
    PRINT CONCAT('EXEC SPK_NIEPEG ',''''+@CONSECUTIVO+'''')

    IF ISNULL(@TIPONOTA,0)<>0
    BEGIN
        INSERT INTO NIEPEG (CONSECUTIVO, NUMDOC, FECHA, CNSNIEPEG_BASE, TIPONOTA, ESTADODIAN)
        SELECT CONSECUTIVO, NUMDOC, CONVERT(SMALLDATETIME,GETDATE()), CNSNIEPEG, @TIPONOTA, 1
        FROM NIEPEG WHERE CNSNIEPEG=@CNSNIEPEG_BASE

        SET @CNSNIEPEG=@@IDENTITY

        UPDATE NIEPEG 
        SET ANULADO=1, OBS=CONCAT('Registro ',IIF(@TIPONOTA=1,'remplazado','eliminado'),' por el registro CNSNIEPEG=',@CNSNIEPEG)
        WHERE CNSNIEPEG=@CNSNIEPEG_BASE
    END
    BEGIN
        INSERT INTO NIEPEG (CONSECUTIVO, NUMDOC, FECHA)
        SELECT CONSECUTIVO, NUMDOC, FECHA
        FROM DBO.VWK_NIEPE V
        WHERE CONSECUTIVO=@CONSECUTIVO
            AND NOT EXISTS (SELECT 1 FROM NIEPEG WHERE NIEPEG.CONSECUTIVO=V.CONSECUTIVO AND NIEPEG.NUMDOC=V.NUMDOC AND ISNULL(NIEPEG.ANULADO,0)=0)
    END
END

