

SELECT TIPOTTEC,CUENTACXC,IDTERCERO,CUENTACXC_RAD,IDPLAN, * FROM FTR WHERE N_FACTURA='FV11326'

SELECT IDPLAN,  * FROM FTRD WHERE N_FACTURA='FV11326'

UPDATE FTRD SET IDPLAN='SAT01C' WHERE N_FACTURA='FV11326'

SELECT  * FROM PPT WHERE IDTERCERO='0100000007' AND IDPLAN='SAT01C'

UPDATE FTR SET TIPOTTEC='EPS' WHERE N_FACTURA='FV11326'

UPDATE FTRD SET PREFIJO='AC' WHERE N_FACTURA='FV11424'

UPDATE USUSU SET IDDEPURAR=0 WHERE USUARIO='JJIMENEZ'

BEGIN TRAN 
EXEC SPK_NC_CONTAB_FTR 'FV11326','01','JJIMENEZ','CAJA COPAGOS VIRTUALES','06','0612400000028846'
ROLLBACK


                  SELECT 'DB' TIPO, TTEC1.CUENTA, '', '', 0 AS VLR_TOTAL, 
                    SUM(FTRD.VLR_SERVICI) AS VLR_SERVICI, ROUND(CASE WHEN COALESCE(FTR.COPAPROPIO,0)=1 THEN CP_VLR_COPAGOS ELSE SUM(FTRD.VLR_COPAGOS) END,0) VLR_COPAGOS, 
                    FTR.CP_VLR_PAGCOMP, 0 AS VLR_DESCUENTO, 0 AS VLR_ABONOS, FTRD.IDPLAN, SUM(COALESCE(FTRD.VIVA,0)), 0, '',
                    COALESCE ( FTRD.CODUNG,''), COALESCE( FTRD.CODPRG,'')
                  FROM   FTR INNER JOIN FTRD ON FTR.CNSFCT=FTRD.CNSFTR 
                              LEFT JOIN PPT ON FTR.IDTERCERO = PPT.IDTERCERO AND FTRD.IDPLAN = PPT.IDPLAN 
                              LEFT JOIN TTEC TTEC1 ON TTEC1.TIPO = PPT.TIPOTERCONTABLE
                  WHERE  FTR.N_FACTURA = 'FV11326'
                  GROUP BY TTEC1.CUENTA, FTRD.IDPLAN, COALESCE ( FTRD.CODUNG,''), COALESCE( FTRD.CODPRG,''),COALESCE(FTR.COPAPROPIO,0),FTR.CP_VLR_COPAGOS,
                            FTR.CP_VLR_PAGCOMP 


SELECT  * FROM ISAL WHERE CNSMOV='0700006503'

SELECT * FROM IMOVH WHERE IDARTICULO='RX04-1'

SELECT  * FROM ISAL WHERE IDARTICULO='RX05-1' AND COALESCE(PCOSTO,0)<1

UPDATE  ISAL SET PCOSTO=1 WHERE IDARTICULO='RX04-1' AND COALESCE(PCOSTO,0)<1

DELETE MCPE WHERE NROCOMPROBANTE='0622000000026258'


SELECT  * FROM NEDIA WHERE NUMDOC='0600013099'