

SELECT * FROM FTRSX WHERE N_FACTURA='UV20183'


SELECT * FROM FTRDC WHERE CNSFTR='0200013116'

SELECT X.*,MDX.DESCRIPCION FROM (
SELECT PPT.NROCONTRATO,FTRDC.NOADMISION,CIU.NOMBRE,COALESCE(CIT.FECHA,HADM.FECHA)FECHAATE,AFI.TIPO_DOC,
AFI.DOCIDAFILIADO,AFI.SEXO,DATEDIFF(YEAR,AFI.FNACIMIENTO,COALESCE(CIT.FECHA,HADM.FECHA))EDAD,FTR.N_FACTURA,
FTRDC.IDSERVICIO,SER.DESCSERVICIO,FTRDC.CANTIDAD,FTRDC.FECHA,CASE WHEN FTRDC.PROCEDENCIA='CIT' THEN FTRDC.FECHA ELSE
CASE  WHEN HADM.FECHAALTAMED IS NULL THEN  FTR.FECHACAP_FIN  WHEN HADM.FECHAALTAMED>FTR.FECHACAP_FIN THEN FTR.FECHACAP_FIN ELSE HADM.FECHAALTAMED END  END F_EGRESO,
CASE WHEN FTRDC.PROCEDENCIA='CIT' THEN 0 ELSE DATEDIFF(DAY,CASE WHEN HADM.FECHA<FTR.FECHACAP_INI THEN FTR.FECHACAP_INI ELSE HADM.FECHA END,
CASE  WHEN HADM.FECHAALTAMED IS NULL THEN  FTR.FECHACAP_FIN  WHEN HADM.FECHAALTAMED>FTR.FECHACAP_FIN THEN FTR.FECHACAP_FIN ELSE HADM.FECHAALTAMED END) END DIAS,
CASE WHEN FTRDC.PROCEDENCIA='CIT' THEN CASE WHEN  CIT.IDDX IS NULL THEN (SELECT IDDX FROM HCA WHERE CONSECUTIVOCIT=FTRDC.NOADMISION) ELSE CIT.IDDX END 
ELSE COALESCE(HADM.DXEGRESO,HADM.DXINGRESO,(SELECT TOP 1 IDDX FROM HCA WHERE NOADMISION=FTRDC.NOADMISION AND IDDX IS NOT NULL ORDER BY FECHA DESC)) END IDDX,CIU.NOMBRE CIU_AFI,DEP.NOMBRE DEPARTAMENTO
FROM FTR INNER JOIN FTRD ON FTR.N_FACTURA=FTRD.N_FACTURA
         INNER JOIN FTRDC ON FTRD.CNSFTR=FTRDC.CNSFTR AND FTRD.N_CUOTA=FTRDC.N_CUOTA
         LEFT JOIN PPT ON FTR.IDPLAN=PPT.IDPLAN AND FTR.IDTERCERO=PPT.IDTERCERO
         LEFT JOIN CIT ON FTRDC.NOADMISION=CIT.CONSECUTIVO AND FTRDC.PROCEDENCIA='CIT'
         LEFT JOIN HADM ON FTRDC.NOADMISION=HADM.NOADMISION AND FTRDC.PROCEDENCIA='HADM'
         LEFT JOIN AFI ON COALESCE(CIT.IDAFILIADO,HADM.IDAFILIADO)=AFI.IDAFILIADO
         LEFT JOIN CIU ON AFI.CIUDAD=CIU.CIUDAD
         LEFT JOIN DEP ON CIU.DPTO=DEP.DPTO
         LEFT JOIN SER ON FTRDC.IDSERVICIO=SER.IDSERVICIO
WHERE FTR.N_FACTURA='UV20183' ) X LEFT JOIN MDX ON X.IDDX=MDX.IDDX
