USE KESPERANZA

SELECT LEFT(N_FACTURA,2),CONVERT(INT,COALESCE(REPLACE(N_FACTURA,'CE',''),0)) N FROM FCXP WHERE DOCEQUIVALENTE=1
ORDER BY 1,2 DESC

SELECT * FROM FCXP WHERE N_FACTURA='CE218'

UPDATE FCXP SET CNSRESOL='18764088248633',ESTADODIAN=1,ZIPKEY=NULL,F_FACTURAREF=DBO.FNK_GETDATE(),FECHA=DBO.FNK_GETDATE() WHERE CNSFCXP='01SR001403'

SELECT  * FROM FDIANR WHERE CNSDOCUMENTO='01SR001403'


SELECT *  FROM KMCOM WHERE IDTIPOCONT='NOMINA' AND PREFIJO='I034'

UPDATE #A SET CUENTA='5105030601' WHERE  TIPO='DB'

INSERT INTO KMCOM
SELECT  * FROM #A


