IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_CONSULTA_DOCUMENTO_ELECTRONICA' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_CONSULTA_DOCUMENTO_ELECTRONICA
END
GO
CREATE PROCEDURE DBO.SPK_CONSULTA_DOCUMENTO_ELECTRONICA 
@N_FACTURA  VARCHAR(20),
@CNSFNOT     VARCHAR(20)=NULL
WITH ENCRYPTION
AS 
DECLARE @JSON VARCHAR(MAX)
DECLARE @TOKEN VARCHAR(100)
DECLARE @NITEMISOR VARCHAR(20)
DECLARE @URLFACT VARCHAR(256)
DECLARE @TIPODOC   VARCHAR(2)
DECLARE @PREFACT VARCHAR(4)
DECLARE @CORRELATIVO VARCHAR(20)
DECLARE @F_EMISION VARCHAR(10)
DECLARE @sUrl VARCHAR(MAX) 
DECLARE @obj INT
DECLARE @valorDeRegreso INT
DECLARE @response VARCHAR(8000)
DECLARE @src VARCHAR(255)
DECLARE @desc VARCHAR(255)
DECLARE @BODY VARCHAR(MAX)
DECLARE @FACTEP VARCHAR(20)
DECLARE @CODQR VARCHAR(100)
DECLARE @CODHASH VARCHAR(50)
DECLARE @ESTDOC  VARCHAR(10)
DECLARE @URLFACTEP VARCHAR(256)
DECLARE @DESCSUNAT VARCHAR(MAX)
DECLARE @ERRORES VARCHAR(MAX)
BEGIN
   IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='MIFACT'
   BEGIN
      IF DB_NAME()=DBO.FNK_VALORVARIABLE('BDATA_PRODUCCION')
      BEGIN
         SELECT @URLFACT=DBO.FNK_VALORVARIABLE('URLFACT_ELE_PRODJSON')
         SELECT @TOKEN=dbo.FNK_VALORVARIABLE('TOKEN_FACTU_ELE_PERU')
         SELECT @NITEMISOR=dbo.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
      END
      ELSE
      BEGIN
         SELECT @URLFACT=DBO.FNK_VALORVARIABLE('URLFACT_ELE_PRUEJSON')
         SELECT @TOKEN='gN8zNRBV+/FVxTLwdaZx0w=='
         SELECT @NITEMISOR='20100100100'
      END
   
      IF LEN(COALESCE(@TOKEN,''))<20
      BEGIN
         PRINT 'No existe el token de seguridad'
         RETURN
      END
      IF COALESCE(@CNSFNOT,'')=''
      BEGIN
         PRINT 'ES FACTURA'
         SELECT @TIPODOC= CASE WHEN TIPOFIN='N' THEN '03' ELSE '01' END,@PREFACT=LEFT(N_FACTURA,4), @CORRELATIVO= RIGHT(N_FACTURA,8), 
         @F_EMISION=REPLACE(CONVERT(VARCHAR,F_FACTURA,102),'.','-') ,@FACTEP=FACTEP
         FROM FTR WHERE N_FACTURA=@N_FACTURA
      END
      ELSE
      BEGIN
          SELECT @TIPODOC= CASE FNOT.CLASE WHEN 'C' THEN '07' WHEN 'D' THEN '08' ELSE '' END,@PREFACT=LEFT(CNSDIANFE,4), @CORRELATIVO=RIGHT(CNSDIANFE,8),
          @F_EMISION=REPLACE(CONVERT(VARCHAR,F_NOTA,102),'.','-') 
          FROM FNOT WHERE N_FACTURA=@N_FACTURA AND CNSFNOT=@CNSFNOT
      END
      SELECT @JSON=' { '
      SELECT @JSON=@JSON+'"TOKEN":"'+@TOKEN+'",'
      SELECT @JSON=@JSON+'"NUM_NIF_EMIS": "'+@NITEMISOR+'",'
      SELECT @JSON=@JSON+'"COD_TIP_CPE": "'+@TIPODOC+'",'
      SELECT @JSON=@JSON+'"NUM_SERIE_CPE": "'+@PREFACT+'",'
      SELECT @JSON=@JSON+'"NUM_CORRE_CPE": "'+@CORRELATIVO+'",'
      SELECT @JSON=@JSON+'"FEC_EMIS": "'+@F_EMISION+'" '
      SELECT @JSON=@JSON+' }    '

      IF LEN(@JSON)<10
      BEGIN
         PRINT 'NO TENGO DATOS'
         RETURN
      END
      IF LEN(@URLFACT)<30
      BEGIN
         PRINT 'No existe api valida para el envio '
         RETURN
      END

     PRINT 'DEFINITIVO'
     PRINT @JSON
     SELECT @sUrl=REPLACE(@URLFACT,'SendInvoice','GetEstatusInvoice')
     SELECT @BODY=@JSON

     PRINT '@sUrl='+@sUrl

      EXEC sys.sp_OACreate 'MSXML2.ServerXMLHttp', @obj OUT
      EXEC sys.sp_OAMethod @obj, 'Open', NULL, 'POST', @sUrl, false
      Exec sp_OAMethod @obj, 'setRequestHeader', null, 'Content-Type', 'application/json'
      Exec sp_OAMethod @obj, 'send', null, @body
      Exec sp_OAMethod @obj, 'responseText', @Response OUTPUT
      Exec sp_OADestroy @obj

      SELECT @CODQR=CODQR,@CODHASH=CODHASH,@ESTDOC=ESTDOC,@URLFACTEP=URLFACTEP,@DESCSUNAT=DESCSUNAT,@ERRORES=ERRORES
      FROM OPENJSON(@Response)
      WITH(
             CODQR       VARCHAR(100) '$.cadena_para_codigo_qr'
            ,CODHASH    VARCHAR(50) '$.codigo_hash'
            ,ESTDOC     VARCHAR(10) '$.estado_documento'
            ,URLFACTEP  VARCHAR(256) '$.url'
            ,ERRORES    VARCHAR(MAX) '$.errors'
            ,DESCSUNAT  VARCHAR(MAX) '$.sunat_description'
      )
      IF @ESTDOC IN('101','102','103')
      BEGIN
         IF COALESCE(@CNSFNOT,'')=''
         BEGIN
            IF @FACTEP IN('','ERROR','PEND')
            BEGIN
               UPDATE FTR SET FACTEP= CASE WHEN @ESTDOC IN('102','103') THEN 'OK' ELSE 'PEND' END,RAZONANULACION='' WHERE N_FACTURA=@N_FACTURA
               IF NOT EXISTS(SELECT * FROM FTRE WHERE FTRE.FTRN_FACTURA=@N_FACTURA)
               BEGIN
                  IF COALESCE(@CODQR,'')=''
                  BEGIN                  
                     SELECT @CODQR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')+'|'+CASE WHEN TIPOFIN='N' THEN '03' ELSE '01' END+'|'+LEFT(N_FACTURA,4)+'|'+RIGHT(N_FACTURA,8)+'|'+CONVERT(VARCHAR(20),CONVERT(decimal(14,2),COALESCE(VIVA,0)))+'|'+'' 
                     +CONVERT(VARCHAR(20),CONVERT(decimal(14,2),COALESCE(VR_TOTAL,0)))+'|'+ REPLACE(CONVERT(VARCHAR,F_FACTURA,102),'.','-')+'|'+CONVERT(VARCHAR(1),CONVERT(INT,COALESCE(TGEN.VALOR1,0)))+'|'+TER.NIT+'|'+@CODHASH
                     FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
                              LEFT JOIN TGEN ON TER.TIPO_ID =TGEN.CODIGO AND TGEN.TABLA='General' AND TGEN.CAMPO='TIPOIDSUNAT'
                     WHERE N_FACTURA=@N_FACTURA
                  END
                  INSERT INTO FTRE(N_FACTURA,FTRN_FACTURA,PREFIJO,RESPUESTA,FECHA,CUFE,NOMBREARCHIVO,CNSRESOL,SOLICITUDJSON) 
                  SELECT CNSFCT,N_FACTURA,@PREFACT,@response,GETDATE(),@CODQR,@CODHASH,CNSRESOL,@JSON FROM FTR
                  WHERE N_FACTURA=@N_FACTURA
               END
            END
         END
         ELSE
         BEGIN
            IF EXISTS(SELECT * FROM FNOT WHERE FACTEP<>'OK' AND CNSFNOT=@CNSFNOT AND N_FACTURA=@N_FACTURA)
            BEGIN
               UPDATE FNOT SET FACTEP='OK',RAZONANU='',RESPUESTAJSON=@Response WHERE CNSFNOT=@CNSFNOT AND N_FACTURA=@N_FACTURA
            END
         END
      END
      ELSE
      BEGIN
         IF COALESCE(@CNSFNOT,'')=''
         BEGIN
            UPDATE FTR SET FACTEP='ERROR',RAZONANULACION=SUBSTRING(@ERRORES,1,255) WHERE N_FACTURA=@N_FACTURA
         END
         ELSE
         BEGIN
            UPDATE FNOT SET FACTEP='ERROR',RAZONANU=SUBSTRING(@ERRORES,1,255) WHERE N_FACTURA=@N_FACTURA AND CNSFNOT=@CNSFNOT
         END
      END
   END
END



