use KNUEVAVIDA


SELECT IDFORMATO, * FROM FTR WHERE N_FACTURA='FV1'

INSERT INTO USUSU 
SELECT  * FROM CEM.DBO.USUSU WHERE USUARIO='JJIMENEZ'

SELECT  * FROM UBEQ

UPDATE USUSU SET SYS_COMPUTERNAME='EPIMIENTA' WHERE USUARIO='JJIMENEZ'

UPDATE FTR SET IDFORMATO='03G'