use PASOCAMAICAO
UPDATE USUSU SET IDDEPURAR=1-IDDEPURAR WHERE USUARIO='JJIMENEZ'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC


SELECT  HADMF.N_FACTURA,DBO.FNK_FECHA(FTR.F_FACTURA)FECHA,FTR.ESTADO,FTR.VR_TOTAL   FROM [dbo].[HADMF] INNER JOIN  FTR ON HADMF.CNSFCT=FTR.CNSFCT  WHERE ( FTR.N_FACTURA  LIKE '%%%%') AND  1 = 2   ORDER BY HADMF.N_FACTURA OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


EXEC SPK_RPT_ANEXO '0200317925','ASFE93790','1', 'SOAT', 'AX0221741181', 'FA'
EXEC SPK_RPT_ANEXO '0200317925','ASFE93790','1', 'SOAT', 'AX0221741188', 'FC'
EXEC SPK_RPT_ANEXO '0200317925','ASFE93790','1', 'SOAT', 'AX0221741192', 'FB'

SELECT  * FROM HADMF WHERE N_FACTURA='ASFE93790'

SELECT ID2 PREFIJO ,STRINGMEDIO1 NOM_PREFIJO,ID3 IDSERVICIO,STRINGGRANDE2 DESCSERVICIO,COALESCE(NOMBRE,'') AS CODCUM,CANTIDAD,VALOR1 AS VALOR,
VALOR2 AS VALOREXCEDENTE
FROM RPDX WHERE CNS='AX0221741181'

SELECT *
FROM RPDX WHERE CNS='AX0221741181'




EXEC SPQ_JSON '{"MODELO":"ANEXOS_HADMFTR","METODO":"IMPRIMIR_ANEXO","PARAMETROS":{"TAB":"Facturadas","TANEXO":"Admision","ANEXO":"CUMS","NOADMISION":"0200317925","IDTERCERO":null,"IDPLAN":null,"N_FACTURA":"ASFE93790","CNSRPDX":"020000371502","ITEM":null},"USUARIO":"JJIMENEZ"}'


SELECT  * FROM FTR WHERE TIPOFAC='M' AND F_FACTURA>'01/09/2024'


SELECT * FROM FTR WHERE N_FACTURA='ASFE93483'

SELECT * FROM FTRD WHERE N_FACTURA='ASFE93483'


SELECT 'OK'OK,TER.NIT,TER.RAZONSOCIAL,VALORSERVICIOS,VALORCOPAGO,VR_TOTAL,
CONCAT(FORMAT(F_FACTURA,'dd'),'.',UPPER(LEFT(FORMAT(F_FACTURA,'MMM'),1)),RIGHT(FORMAT(F_FACTURA,'MMM'),3),FORMAT(F_FACTURA,'yyyy'))F_FACTURA,
CONCAT(FORMAT(F_VENCE,'dd'),'.',UPPER(LEFT(FORMAT(F_VENCE,'MMM'),1)),RIGHT(FORMAT(F_VENCE,'MMM'),3),FORMAT(F_VENCE,'yyyy'))F_VENCE
FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
         INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
WHERE N_FACTURA='ASFE93483'

SELECT FTRD.NOADMISION, DBO.FNK_FECHA_DDMMAA(CIT.FECHA)FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,
       FTRD.CANTIDAD,FTRD.VALOR,FTRD.VLR_COPAGOS,FTRD.VLR_SERVICI,FTRD.REFERENCIA,FTRD.ANEXO,
       COALESCE(CIT.IDDX,HCA.IDDX),CASE WHEN COALESCE(FTRD.IDPROVEEDOR,'')<>'' THEN  ('PROVEEDOR='+TER.NIT+' - '+TER.RAZONSOCIAL) ELSE '' END PROVEEDOR
FROM FTRD INNER JOIN CIT ON FTRD.NOADMISION=CIT.CONSECUTIVO
          INNER JOIN AFI ON CIT.IDAFILIADO=AFI.IDAFILIADO
          LEFT  JOIN MDX ON CIT.IDDX=MDX.IDDX
          LEFT  JOIN TER ON FTRD.IDPROVEEDOR=TER.IDTERCERO
          LEFT  JOIN HCA ON CIT.CONSECUTIVO=HCA.CONSECUTIVOCIT
WHERE FTRD.N_FACTURA='ASFE93483'
AND FTRD.PROCEDENCIA='CI'
UNION ALL
SELECT FTRD.NOADMISION, DBO.FNK_FECHA_DDMMAA(AUT.FECHA)FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,
       FTRD.CANTIDAD,FTRD.VALOR,FTRD.VLR_COPAGOS,FTRD.VLR_SERVICI,FTRD.REFERENCIA,FTRD.ANEXO,
       AUT.DXPPAL,CASE WHEN COALESCE(AUT.IDPROVEEDOR,'')<>'' THEN  ('PROVEEDOR='+TER.NIT+' - '+TER.RAZONSOCIAL) ELSE '' END PROVEEDOR
FROM FTRD INNER JOIN AUT ON FTRD.NOADMISION=AUT.NOAUT
          INNER JOIN AFI ON AUT.IDAFILIADO=AFI.IDAFILIADO
          LEFT  JOIN MDX ON AUT.DXPPAL=MDX.IDDX
          LEFT  JOIN TER ON AUT.IDPROVEEDOR=TER.IDTERCERO
WHERE FTRD.N_FACTURA='ASFE93483'
AND FTRD.PROCEDENCIA='CE'




EXEC SPQ_JSON '{"MODELO":"ANEXOS_HADMFTR","METODO":"ANEXO_MASIVA","PARAMETROS":{"TAB":"FTR","TANEXO":"Masiva","ANEXO":"Masiva","NOADMISION":"VARIOS","IDTERCERO":"839000356","IDPLAN":"CLIMAI","N_FACTURA":"ASFE93483","CNSRPDX":null,"ITEM":null},"USUARIO":"JJIMENEZ"}'