use PALTASALUD2

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

UPDATE HADM SET FACTURABLE=1 WHERE FACTURABLE IS NULL

<i class="fa-solid fa-user-secret"></i>

ROLLBACK
BEGIN TRAN 
EXEC SPQ_JSON '{"MODELO":"FTR_COL","METODO":"FE_FECHAFTR","PARAMETROS":{"N_FACTURA":"UV19918"},"USUARIO":"JJIMENEZ"}'

UPDATE FTR SET F_FACTURA=F_FACTURA-2 WHERE N_FACTURA='UV19924'