IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_NC_CONTAB_INV' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_NC_CONTAB_INV
END

GO
CREATE PROCEDURE  DBO.SPK_NC_CONTAB_INV   
	@CNSMOV            VARCHAR(20),   
	@USUARIO           VARCHAR(12),  
	@SYS_COMPUTERNAME  VARCHAR(254),  
	@COMPANIA          VARCHAR(2),   
	@SEDE              VARCHAR(5),  
	@NROCOMPROBANTE    VARCHAR(20)  
WITH ENCRYPTION
AS  
DECLARE @COM             VARCHAR(6) 
 
DECLARE @NOREFERENCIA    VARCHAR(20)  
DECLARE @ANO             VARCHAR(4)  
DECLARE @MES             INT  
DECLARE @IDMODELOCONT    VARCHAR(2)  
DECLARE @IDPLAN          VARCHAR(6)   
DECLARE @TIPOTERCONTABLE VARCHAR(10)   
DECLARE @PREFIJO_USCXS   VARCHAR(10)  
DECLARE @CERRADO         VARCHAR(6)
DECLARE @FECHATRA        DATETIME
DECLARE @VALOR_IMOV      DECIMAL(18,6)
DECLARE @CERRADOINV      SMALLINT 
DECLARE @TIPOMOV         VARCHAR(10) --SELECT * FROM ITMO
DECLARE @IDTIPOMOV		 VARCHAR(3) 
DECLARE @MTERCERO	       SMALLINT
DECLARE @SUM_DB          DECIMAL(18,6)
DECLARE @SUM_CR          DECIMAL(18,6)
DECLARE @CONCEPTOMOV    VARCHAR(255)
DECLARE @CONCETOART     VARCHAR(255)
DECLARE @SECONTABILIZA  INT
BEGIN 
	SELECT @TIPOMOV=ITMO.TIPO,@IDTIPOMOV=IMOV.IDTIPOMOV,@MTERCERO=ITMO.MPROVEEDOR,
	@CONCEPTOMOV= CASE WHEN LEN(IMOV.OBSERVACION)>10 THEN IMOV.OBSERVACION ELSE ' MOVIMIENTO:'+LTRIM(RTRIM(ITMO.DESCRIPCION))+' IDBODEGA: '+IMOV.IDBODEGA END,
	@CONCETOART=ITMO.DESCRIPCION, @SECONTABILIZA=IIF(ISNULL(IBOD.NOCONTABILIZA,0)=1,0,ISNULL(ITMO.SECONTABILIZA,0))
	FROM IMOV 
        INNER JOIN ITMO ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
        INNER JOIN IBOD ON IBOD.IDBODEGA=IMOV.IDBODEGA
	WHERE IMOV.CNSMOV=@CNSMOV 					

	PRINT '@CONCEPTOMOV='+@CONCEPTOMOV
	PRINT '@CONCETOART='+@CONCETOART
    
	IF @SECONTABILIZA=0
	BEGIN
		RAISERROR('Este movimiento no se contabiliza', 16, 1)
		RETURN			
	END

	EXEC SPK_PRI

	SELECT @ANO = YEAR(FECHACONF), @MES = MONTH(FECHACONF) FROM IMOV WHERE CNSMOV=@CNSMOV
	
	IF @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDINVDEVPROVEEDOR') 
	BEGIN
		--RAISERROR('SE CONTABILIZA LA NOTA DE DEVOLUCION', 16, 1) SE RETIRA RAISERROR PORQUE ESTO PROVOCABA QUE ENVIARA ERROR EN DEVOLUCION OSOLANO 20231024
		PRINT 'SE CONTABILIZA DESDE LA NOTA DE DEVOLUCION'
		RETURN			
	END

	IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)  
	BEGIN
		RAISERROR('Período Contable No Existe', 16, 1)
		RETURN 
	END  
	ELSE 
	BEGIN
		SELECT @CERRADO = CERRADO, @CERRADOINV=CERRADO_INV FROM PRI WHERE ANO= @ANO AND MES=@MES
		print 'cerrado='+convert(varchar,@cerrado)+'//@CERRADOINV='+convert(varchar,@CERRADOINV)
		IF @CERRADO = 1
		BEGIN
			RAISERROR('Periodo Del Movimiento de Inventario y Periodo Actual Cerrados',16,1)
			RETURN
		END
		IF @CERRADOINV = 1  
		BEGIN
			RAISERROR('Periodo Del Movimiento de Inventario y Periodo Actual Cerrados',16,1)
			RETURN
		END
	END
		
	SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')  
  
	PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- AGREGADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
	IF ISNULL(@NROCOMPROBANTE,'') = '' -- AGREGADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
	BEGIN  
		SET @NROCOMPROBANTE=SPACE(20)  
		EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT     
		SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- AGREGADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
		PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- AGREGADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
		--SE REVISA SI LOS COMPROBANTES SE TOMAN DE ACUERDO A SEDE
		IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
		BEGIN
			SET @COM =  RTRIM(LTRIM( CASE WHEN EXISTS ( SELECT COMMS.COMPROBANTE
												FROM   IMOV INNER JOIN COMMS ON IMOV.IDTIPOMOV = COMMS.TIPO
												WHERE  IMOV.CNSMOV  = @CNSMOV
												AND    COMMS.IDSEDE = @SEDE
												AND    COMMS.CLASE  = 'INV') 
									THEN ( SELECT COMMS.COMPROBANTE
											FROM   IMOV INNER JOIN COMMS ON IMOV.IDTIPOMOV = COMMS.TIPO
											WHERE  IMOV.CNSMOV  = @CNSMOV
											AND    COMMS.IDSEDE = @SEDE
											AND    COMMS.CLASE  = 'INV')
									ELSE ( SELECT (CASE WHEN EXISTS   
															(SELECT COM.COMPROBANTE 
															FROM   ITMO,COM,IMOV 
															WHERE  ITMO.IDTIPOMOV   = IMOV.IDTIPOMOV 
															AND    ITMO.COMPROBANTE = COM.COMPROBANTE 
															AND    COM.COMPANIA     = @COMPANIA 
															AND    IMOV.CNSMOV      = @CNSMOV)   
																	THEN (SELECT COM.COMPROBANTE 
															FROM   ITMO, COM, IMOV 
															WHERE  ITMO.IDTIPOMOV   = IMOV.IDTIPOMOV 
															AND    ITMO.COMPROBANTE = COM.COMPROBANTE 
															AND    COM.COMPANIA     = @COMPANIA 
															AND    IMOV.CNSMOV      = @CNSMOV)   
																	ELSE  DBO.FNK_VALORVARIABLE('IDCON_TCOM_INV') 
																END)
											) 
								END))                   
		END
		ELSE
		BEGIN
			SET @COM=RTRIM(LTRIM((SELECT (CASE WHEN EXISTS   
														(SELECT COM.COMPROBANTE 
														FROM   ITMO,COM,IMOV 
														WHERE  ITMO.IDTIPOMOV   = IMOV.IDTIPOMOV 
														AND    ITMO.COMPROBANTE = COM.COMPROBANTE 
														AND    COM.COMPANIA     = @COMPANIA 
														AND    IMOV.CNSMOV      = @CNSMOV)   
														THEN (SELECT COM.COMPROBANTE 
													FROM   ITMO, COM, IMOV 
													WHERE  ITMO.IDTIPOMOV   = IMOV.IDTIPOMOV 
													AND    ITMO.COMPROBANTE = COM.COMPROBANTE 
													AND    COM.COMPANIA     = @COMPANIA 
													AND    IMOV.CNSMOV      = @CNSMOV)   
															ELSE  DBO.FNK_VALORVARIABLE('IDCON_TCOM_INV') 
													END
										)
								)))  
		END
		IF @COM='' OR @COM IS NULL  
		BEGIN
					SET @COM=DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT')  
		END
		IF @COM='' OR @COM IS NULL  
		BEGIN
			SET @COM='IX'  
		END
		SET @PREFIJO_USCXS='@COM'+@COM  
		SET @NOREFERENCIA=SPACE(20)  
		EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT     
		SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)  
		PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA  
						
		PRINT 'Comprobante Contable (MCP)'  
		INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,  
										TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,  
												COMPROBANTE, IDTERCERO)  
		SELECT @NROCOMPROBANTE, @COMPANIA, 'INV', @NOREFERENCIA, @ANO, @MES,dbo.FNK_FECHA_SIN_HORA(FECHAMOV),   
									0, 0, CNSMOV, IDBODEGA, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, @CONCEPTOMOV, @SEDE, 0,  
								@COM, COALESCE(IDTERCERO,'')    
		FROM IMOV  
		WHERE CNSMOV=@CNSMOV
	END  
	ELSE  
	BEGIN  
		IF (SELECT COUNT(*) FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)>0
		BEGIN
			INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
						REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
						RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
			SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
						REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
						RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
			FROM   MCP
			WHERE  NROCOMPROBANTE = @NROCOMPROBANTE
			--se borran de mcp, mch
			DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
			DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE   
		END
		ELSE
		BEGIN
			DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
		END  
	END  
	UPDATE MCPE SET OBSERVACION=@CONCEPTOMOV FROM IMOV INNER JOIN MCPE ON MCPE.NROCOMPROBANTE=IMOV.NROCOMPROBANTE   
	WHERE MCPE.NROCOMPROBANTE=@NROCOMPROBANTE 
	AND MCPE.PROCEDENCIA='INV'
	AND IMOV.CNSMOV=@CNSMOV   
	IF @TIPOMOV='Credito' --Entradas a Almacen ej. devoluciones Clientes  
	BEGIN  
		PRINT 'Contabilizando Entradas'  
		SELECT @VALOR_IMOV = SUM((CONVERT(decimal(18, 2),IMOVH.PCOSTO) * CONVERT(decimal(18, 2),IMOVH.CANTIDAD) ) ) FROM IMOVH WHERE CNSMOV = @CNSMOV
		PRINT '@VALOR_IMOV=' + CONVERT(VARCHAR(30), @VALOR_IMOV)
		PRINT 'Insetardo Asiento del Concepto de INV. (DB)'   
		PRINT ' -Insertando Registro MCH.'  
		IF DBO.FNK_VALORVARIABLE('IDCON_IMOVDBENT_COMP') = 'MOV_INVENTARIO'
		BEGIN
			INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE, VALOR,
							REFERENCIA1,  REFERENCIA2,REFERENCIA3,ITEMREF, USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
							PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG, N_FACTURA, F_FACTURAREF, F_VENCE)   
			SELECT @NROCOMPROBANTE,@COMPANIA,'DB',  
				DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'MOV_INVENTARIO','DB',IMOV.IDTIPOMOV, IMOV.CCOSTO,'P',IART.IDITAR,0),  
				IMOV.IDTERCERO,IMOV.CCOSTO, @CONCETOART+' '+IART.DESCRIPCION,           
																SUM( (CONVERT(decimal(14, 2),IMOVH.PCOSTO) * CONVERT(decimal(14, 2),IMOVH.CANTIDAD) ) ),
				IMOV.IDBODEGA,IMOV.CNSMOV,IART.IDITAR,NULL,@USUARIO,   
				DBO.FNK_FECHA_SIN_MLS(GETDATE()),IART.IDITAR,IMOV.IDAREA,'S',1 ,'MOV_ENT_DB', 'Movimiento','INV',@CNSMOV,  
				IMOV.CODUNG, IMOV.CODPRG, IMOV.NODOCUMENTO, IMOV.F_FACTURA, IMOV.F_VENCE
			FROM   IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV 
						INNER JOIN IART ON IMOVH.IDARTICULO=IART.IDARTICULO
						INNER JOIN ITAR ON IART.IDITAR=ITAR.IDITAR
			WHERE IMOV.CNSMOV=@CNSMOV
			GROUP BY IMOV.IDTERCERO,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,IART.IDITAR, IMOV.IDBODEGA,  
					IMOV.CODUNG, IMOV.CODPRG, IMOV.NODOCUMENTO, IMOV.F_FACTURA, IMOV.F_VENCE,IMOV.IDTIPOMOV,IART.DESCRIPCION
		END
		ELSE
		BEGIN
			INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,
							VALOR,
							REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
							PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG, N_FACTURA, F_FACTURAREF, F_VENCE)   
			SELECT @NROCOMPROBANTE,@COMPANIA,'DB',DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'CXP_COMPRAS','DB',IART.IDITAR, IMOV.CCOSTO,'P',IART.IDARTICULO,0),  
				IMOV.IDTERCERO,IMOV.CCOSTO,@CONCETOART+' '+IART.DESCRIPCION ,  
				SUM( (CONVERT(decimal(14, 2),IMOVH.PCOSTO) * CONVERT(decimal(14, 2),IMOVH.CANTIDAD) ) ),-- CAMADO - 14/11/2008
				IMOV.IDBODEGA,IMOV.CNSMOV,IART.IDARTICULO,NULL,@USUARIO,  
				DBO.FNK_FECHA_SIN_MLS(GETDATE()),IART.IDITAR,IMOV.IDAREA,'S',1 ,'MOV_ENT_DB', 'Movimiento','INV',@CNSMOV,  
				IMOV.CODUNG, IMOV.CODPRG, IMOV.NODOCUMENTO, IMOV.F_FACTURA, IMOV.F_VENCE 
			FROM   IMOV INNER JOIN IMOVH  ON IMOV.CNSMOV=IMOVH.CNSMOV 
					LEFT JOIN IART ON IMOVH.IDARTICULO = IART.IDARTICULO 
									WHERE IMOV.CNSMOV=@CNSMOV 
			GROUP BY IMOV.IDTERCERO,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,IART.IDARTICULO, IMOV.IDBODEGA,  
					IART.IDITAR, IMOV.CODUNG, IMOV.CODPRG, IMOV.NODOCUMENTO, IMOV.F_FACTURA, IMOV.F_VENCE,IART.DESCRIPCION
		END
      
		INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
						REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
						PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG, N_FACTURA, F_FACTURAREF, F_VENCE)  
		SELECT @NROCOMPROBANTE,@COMPANIA,'CR',DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'MOV_INVENTARIO','CR',IMOV.IDTIPOMOV, IMOV.CCOSTO,'P',IART.IDITAR,0),  
				IMOV.IDTERCERO,IMOV.CCOSTO,@CONCETOART+' '+IART.DESCRIPCION, 
				SUM( (CONVERT(decimal(14, 2),IMOVH.PCOSTO) * CONVERT(decimal(14, 2),IMOVH.CANTIDAD) ) ), -- CAMADO - 14/11/2008
				IMOV.IDBODEGA,IMOV.CNSMOV,IMOVH.IDARTICULO,NULL,@USUARIO,  
				DBO.FNK_FECHA_SIN_MLS(GETDATE()),IMOV.IDTIPOMOV,IMOV.IDAREA,'S',1 ,'MOV_ENT_CR', 'Movimiento','INV',@CNSMOV,  
				IMOV.CODUNG, IMOV.CODPRG, IMOV.NODOCUMENTO, IMOV.F_FACTURA, IMOV.F_VENCE 
		FROM   IMOV INNER JOIN IMOVH  ON IMOV.CNSMOV      = IMOVH.CNSMOV 
					LEFT JOIN IART ON IMOVH.IDARTICULO = IART.IDARTICULO 
						WHERE IMOV.CNSMOV=@CNSMOV   
		GROUP BY IMOV.IDTERCERO, IMOV.CCOSTO, IMOV.OBSERVACION, IMOV.IDAREA, IMOV.CNSMOV, IMOVH.IDARTICULO, IMOV.IDBODEGA,   
				IMOV.IDTIPOMOV, IART.IDITAR, IMOV.CODUNG, IMOV.CODPRG, IMOV.NODOCUMENTO, IMOV.F_FACTURA, IMOV.F_VENCE,IART.DESCRIPCION 
      
		SELECT @SUM_DB = SUM(VALOR) FROM MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND TIPO = 'DB'
		SELECT @SUM_CR = SUM(VALOR) FROM MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND TIPO = 'CR'
		PRINT '@SUM_DB = '+CONVERT(VARCHAR(30),@SUM_DB )
		PRINT '@SUM_CR = '+CONVERT(VARCHAR(30),@SUM_CR )
		IF @SUM_DB <> @SUM_CR
		BEGIN
			UPDATE MCHE SET VALOR = CONVERT(decimal(14, 2),MCHE.VALOR)  + ( CONVERT(decimal(14, 2),@VALOR_IMOV) - CONVERT(decimal(14, 2),C.VALOR))
			FROM (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCHE 
				WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='CR' AND PROCESO='MOV_ENT_CR' AND REFERENCIA_PRO=@CNSMOV) AS B,
				(SELECT SUM(CONVERT(decimal(14, 2),VALOR)) AS VALOR FROM MCHE 
				WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='CR' AND PROCESO='MOV_ENT_CR' AND REFERENCIA_PRO=@CNSMOV) AS C,
				IMOV
			WHERE MCHE.NROASIENTO=B.NROASIENTO AND (@VALOR_IMOV-C.VALOR)<>0 AND IMOV.CNSMOV=@CNSMOV
			UPDATE MCHE SET VALOR = CONVERT(decimal(14, 2),MCHE.VALOR)  + ( CONVERT(decimal(14, 2),@VALOR_IMOV) - CONVERT(decimal(14, 2),C.VALOR))
			FROM (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCHE 
									WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' AND PROCESO='MOV_SAL_DB' AND REFERENCIA_PRO=@CNSMOV) AS B,
						(SELECT SUM(CONVERT(decimal(14, 2),VALOR)) AS VALOR FROM MCHE
									WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' AND PROCESO='MOV_SAL_DB' AND REFERENCIA_PRO=@CNSMOV) AS C,
						IMOV 
			WHERE MCHE.NROASIENTO=B.NROASIENTO AND (@VALOR_IMOV-C.VALOR)<>0 AND IMOV.CNSMOV=@CNSMOV 
		END
	END    
	IF @TIPOMOV='Debito' --Salidas de Almacen ej. Ventas a Clientes  
	BEGIN    
		IF DBO.FNK_VALORVARIABLE('CONTAB_INV_IVA_ITAR')<>'SI'
		BEGIN
			SELECT @VALOR_IMOV = SUM((CONVERT(decimal(18, 2),ISAL.PCOSTO) * CONVERT(decimal(18, 2),ISAL.CANTIDAD) ) ) FROM ISAL WHERE CNSMOV = @CNSMOV
			PRINT '@VALOR_IMOV=' + CONVERT(VARCHAR(30), @VALOR_IMOV)
			PRINT 'Salidas de Inventario'
			IF (SELECT COALESCE(MPROVEEDOR,0) FROM ITMO INNER JOIN IMOV ON ITMO.IDTIPOMOV = IMOV.IDTIPOMOV
				WHERE IMOV.CNSMOV=@CNSMOV)= 0 AND (SELECT COALESCE(IDTERCERO,'') FROM IMOV WHERE CNSMOV=@CNSMOV)=''
			BEGIN
			UPDATE IMOV SET IDTERCERO = DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO') WHERE CNSMOV=@CNSMOV
			END
			INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
							REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
							PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
			SELECT NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO, CCOSTO,DETALLE,SUM(VALOR),REFERENCIA1,  
				REFERENCIA2,NULL,ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
				PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
			FROM(
				SELECT NROCOMPROBANTE=@NROCOMPROBANTE, COMPANIA=@COMPANIA, TIPO='DB',  
							CUENTA=DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'MOV_INVENTARIO','DB',IMOV.IDTIPOMOV, IMOV.CCOSTO,'P',IART.IDITAR,0),  
							IDTERCERO=CASE WHEN @MTERCERO=1  THEN CASE WHEN DBO.FNK_VALORVARIABLE('IDINVMOV_PRESTAMOS')=IMOV.IDTIPOMOV THEN IMOV.IDTERCERO ELSE   COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) END
                     ELSE IMOV.IDTERCERO END, IMOV.CCOSTO,
						DETALLE= @CONCETOART+' '+ITAR.DESCRIPCION,
							VALOR = SUM(CONVERT(decimal(14, 2),ISAL.PCOSTO) * CONVERT(decimal(14, 2),ISAL.CANTIDAD)),
							REFERENCIA1=IMOV.IDBODEGA, REFERENCIA2=IMOV.CNSMOV, REFERENCIA3=IART.IDITAR, ITEMREF=NULL,
							USUARIO=@USUARIO, FECHA=DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO=IMOV.IDTIPOMOV, IMOV.IDAREA, 
							CLASECONT='S', ESTADO=1 , PROCESO='MOV_SAL_DB',GENERA='Movimiento', PROCEDENCIA='INV', REFERENCIA_PRO=@CNSMOV,
							IMOV.CODUNG, IMOV.CODPRG  
					FROM   IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV
									INNER JOIN IART ON ISAL.IDARTICULO = IART.IDARTICULO
							INNER JOIN ITAR ON IART.IDITAR=ITAR.IDITAR
									LEFT  JOIN ICBU ON ISAL.NOLOTE=ICBU.CODIGOBARRA
									LEFT JOIN  FCOM ON ICBU.CNSFCOM=FCOM.CNSFCOM
					WHERE IMOV.CNSMOV=@CNSMOV 
					GROUP BY CASE WHEN @MTERCERO=1 THEN CASE WHEN DBO.FNK_VALORVARIABLE('IDINVMOV_PRESTAMOS')=IMOV.IDTIPOMOV THEN IMOV.IDTERCERO ELSE   COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) END ELSE IMOV.IDTERCERO END,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,ISAL.IDARTICULO, IMOV.IDBODEGA,   
														IMOV.IDTIPOMOV, IART.IDITAR, IMOV.CODUNG, IMOV.CODPRG, IART.IDITAR ,ITAR.DESCRIPCION 
												) X
			GROUP BY NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,REFERENCIA1,  
					REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
					PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
						
			PRINT 'Insetardo Asiento del Concepto de INV. (CR)'
			IF DBO.FNK_VALORVARIABLE('IDCON_IMOVDBENT_COMP') = 'MOV_INVENTARIO'
			BEGIN
				PRINT 'IDCON_IMOVDBENT_COMP=MOV_INVENTARIO'
				INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
																			REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
																			PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
				SELECT NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,SUM(VALOR),REFERENCIA1,  
										REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
										PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
				FROM   (
							SELECT NROCOMPROBANTE=@NROCOMPROBANTE, COMPANIA=@COMPANIA, TIPO='CR',  
													CUENTA=DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'MOV_INVENTARIO','CR',IMOV.IDTIPOMOV,IMOV.CCOSTO,'P',IART.IDITAR,0),  
													IDTERCERO=CASE WHEN @MTERCERO=1 THEN   COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE IMOV.IDTERCERO END, IMOV.CCOSTO, DETALLE= @CONCETOART+' '+ITAR.DESCRIPCION, 
													VALOR =SUM(CONVERT(decimal(14, 2),ISAL.PCOSTO) * CONVERT(decimal(14, 2),ISAL.CANTIDAD)),
													REFERENCIA1=IMOV.IDBODEGA, REFERENCIA2=IMOV.CNSMOV, REFERENCIA3=IART.IDITAR,ITEMREF=NULL, 
													USUARIO=@USUARIO, FECHA=DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO=IART.IDITAR, IMOV.IDAREA, CLASECONT='S', ESTADO=1 , PROCESO='MOV_SAL_CR', 
													GENERA='Movimiento', PROCEDENCIA='INV', REFERENCIA_PRO=@CNSMOV, IMOV.CODUNG, IMOV.CODPRG  
							FROM   IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV 
										INNER JOIN IART ON ISAL.IDARTICULO = IART.IDARTICULO
								INNER JOIN ITAR ON IART.IDITAR=ITAR.IDITAR
										LEFT  JOIN ICBU ON ISAL.NOLOTE=ICBU.CODIGOBARRA
										LEFT JOIN  FCOM ON ICBU.CNSFCOM=FCOM.CNSFCOM
							WHERE  IMOV.CNSMOV=@CNSMOV
							GROUP BY CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE IMOV.IDTERCERO END,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,IART.IDITAR, IMOV.IDBODEGA,  
																IMOV.CODUNG, IMOV.CODPRG, IMOV.IDTIPOMOV, IMOV.IDAREA, IMOV.CCOSTO,ITAR.DESCRIPCION  
							) X
				GROUP BY NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,REFERENCIA1,  
						REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
						PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
			END
			ELSE
			BEGIN
				INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
																				REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
																				PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
				SELECT NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,SUM(VALOR),REFERENCIA1,  
													REFERENCIA2,NULL,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
													PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
				FROM   (
													SELECT NROCOMPROBANTE=@NROCOMPROBANTE, COMPANIA=@COMPANIA, TIPO='CR',  
						  												CUENTA=DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'CXP_COMPRAS','DB',IMOV.IDTIPOMOV, IMOV.CCOSTO,'P',IART.IDITAR,0),  
																				IDTERCERO=CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE '' END, IMOV.CCOSTO, DETALLE=IMOV.OBSERVACION, 
																				VALOR = SUM(CONVERT(decimal(14, 2),ISAL.PCOSTO) * CONVERT(decimal(14, 2),ISAL.CANTIDAD)),
																				REFERENCIA1=IMOV.IDBODEGA, REFERENCIA2=IMOV.CNSMOV, REFERENCIA3=IART.IDITAR,ITEMREF=NULL, 
																				USUARIO=@USUARIO, FECHA=DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO=IART.IDITAR, IMOV.IDAREA, CLASECONT='S', ESTADO=1 , PROCESO='MOV_SAL_CR', 
								 											GENERA='Movimiento', PROCEDENCIA='INV', REFERENCIA_PRO=@CNSMOV, IMOV.CODUNG, IMOV.CODPRG  
													FROM   IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV 
									 							INNER JOIN IART ON ISAL.IDARTICULO = IART.IDARTICULO
																LEFT  JOIN ICBU ON ISAL.NOLOTE=ICBU.CODIGOBARRA
																LEFT JOIN  FCOM ON ICBU.CNSFCOM=FCOM.CNSFCOM
													WHERE  IMOV.CNSMOV=@CNSMOV
													GROUP BY CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE '' END,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,IART.IDITAR, IMOV.IDBODEGA,  
										 									IMOV.CODUNG, IMOV.CODPRG, IMOV.IDTIPOMOV, IMOV.IDAREA, IMOV.CCOSTO   
												) X
				GROUP BY NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,REFERENCIA1,  
																REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
																PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
			END
		END
		ELSE
		BEGIN
			PRINT 'Voy a contabilizar el valor del iva en otras cuentas'
			SELECT @VALOR_IMOV = SUM((CONVERT(decimal(18, 2),(ISAL.VR_ANTESIVA)) * CONVERT(decimal(18, 2),ISAL.CANTIDAD) ) ) 
			FROM ISAL WHERE CNSMOV = @CNSMOV
			PRINT '@VALOR_IMOV=' + CONVERT(VARCHAR(30), @VALOR_IMOV)
			PRINT 'Salidas de Inventario'
			--IF (SELECT COALESCE(MPROVEEDOR,0) FROM ITMO INNER JOIN IMOV ON ITMO.IDTIPOMOV = IMOV.IDTIPOMOV
			--	WHERE IMOV.CNSMOV=@CNSMOV)= 0 AND (SELECT COALESCE(IDTERCERO,'') FROM IMOV WHERE CNSMOV=@CNSMOV)=''
			--BEGIN
			--   UPDATE IMOV SET IDTERCERO = DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO') WHERE CNSMOV=@CNSMOV
			--END
			INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
							REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
							PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
			SELECT NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO, CCOSTO,DETALLE,SUM(VALOR),REFERENCIA1,  
				REFERENCIA2,NULL,ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
				PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
			FROM(
				SELECT NROCOMPROBANTE=@NROCOMPROBANTE, COMPANIA=@COMPANIA, TIPO='DB',  
							CUENTA=DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'MOV_INVENTARIO','DB',IMOV.IDTIPOMOV, IMOV.CCOSTO,'P',IART.IDITAR,0),  
							IDTERCERO=CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE IMOV.IDTERCERO END, IMOV.CCOSTO,
						DETALLE= @CONCETOART+' '+ITAR.DESCRIPCION,
							VALOR = SUM(CONVERT(decimal(14, 2),(ISAL.VR_ANTESIVA)) * CONVERT(decimal(14, 2),ISAL.CANTIDAD)),
							REFERENCIA1=IMOV.IDBODEGA, REFERENCIA2=IMOV.CNSMOV, REFERENCIA3=IART.IDITAR, ITEMREF=NULL,
							USUARIO=@USUARIO, FECHA=DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO=IMOV.IDTIPOMOV, IMOV.IDAREA, 
							CLASECONT='S', ESTADO=1 , PROCESO='MOV_SAL_DB',GENERA='Movimiento', PROCEDENCIA='INV', REFERENCIA_PRO=@CNSMOV,
							IMOV.CODUNG, IMOV.CODPRG  
					FROM   IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV
									INNER JOIN IART ON ISAL.IDARTICULO = IART.IDARTICULO
							      INNER JOIN ITAR ON IART.IDITAR=ITAR.IDITAR
									LEFT  JOIN ICBU ON ISAL.NOLOTE=ICBU.CODIGOBARRA
									LEFT JOIN  FCOM ON ICBU.CNSFCOM=FCOM.CNSFCOM
					WHERE IMOV.CNSMOV=@CNSMOV 
					GROUP BY CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE IMOV.IDTERCERO END,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,ISAL.IDARTICULO, IMOV.IDBODEGA,   
														IMOV.IDTIPOMOV, IART.IDITAR, IMOV.CODUNG, IMOV.CODPRG, IART.IDITAR ,ITAR.DESCRIPCION 
												) X
			GROUP BY NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,REFERENCIA1,  
					REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
					PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
						
			PRINT 'Insetardo Asiento del Concepto de INV. (CR)'
			IF DBO.FNK_VALORVARIABLE('IDCON_IMOVDBENT_COMP') = 'MOV_INVENTARIO'
			BEGIN
				PRINT 'IDCON_IMOVDBENT_COMP=MOV_INVENTARIO'
				INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
																			REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
																			PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
				SELECT NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,SUM(VALOR),REFERENCIA1,  
										REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
										PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
				FROM   (
							SELECT NROCOMPROBANTE=@NROCOMPROBANTE, COMPANIA=@COMPANIA, TIPO='CR',  
													CUENTA=DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'MOV_INVENTARIO','CR',IMOV.IDTIPOMOV,IMOV.CCOSTO,'P',IART.IDITAR,0),  
													IDTERCERO=CASE WHEN @MTERCERO=1 THEN   COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE IMOV.IDTERCERO END, IMOV.CCOSTO, DETALLE= @CONCETOART+' '+ITAR.DESCRIPCION, 
													VALOR =SUM(CONVERT(decimal(14, 2),ISAL.VR_ANTESIVA) * CONVERT(decimal(14, 2),ISAL.CANTIDAD)),
													REFERENCIA1=IMOV.IDBODEGA, REFERENCIA2=IMOV.CNSMOV, REFERENCIA3=IART.IDITAR,ITEMREF=NULL, 
													USUARIO=@USUARIO, FECHA=DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO=IART.IDITAR, IMOV.IDAREA, CLASECONT='S', ESTADO=1 , PROCESO='MOV_SAL_CR', 
													GENERA='Movimiento', PROCEDENCIA='INV', REFERENCIA_PRO=@CNSMOV, IMOV.CODUNG, IMOV.CODPRG  
							FROM   IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV 
										INNER JOIN IART ON ISAL.IDARTICULO = IART.IDARTICULO
								INNER JOIN ITAR ON IART.IDITAR=ITAR.IDITAR
										LEFT  JOIN ICBU ON ISAL.NOLOTE=ICBU.CODIGOBARRA
										LEFT JOIN  FCOM ON ICBU.CNSFCOM=FCOM.CNSFCOM
							WHERE  IMOV.CNSMOV=@CNSMOV
							GROUP BY CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE IMOV.IDTERCERO END,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,IART.IDITAR, IMOV.IDBODEGA,  
																IMOV.CODUNG, IMOV.CODPRG, IMOV.IDTIPOMOV, IMOV.IDAREA, IMOV.CCOSTO,ITAR.DESCRIPCION  
							) X
				GROUP BY NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,REFERENCIA1,  
						REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
						PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG

				PRINT 'IDCON_IMOVDBENT_COMP IVA'
            IF (SELECT IDTIPOMOV  FROM IMOV WHERE CNSMOV=@CNSMOV)<>COALESCE(DBO.FNK_VALORVARIABLE('IDINVMOVVENTAFACTURA'),'')
            BEGIN
				   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
																			   REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
																			   PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
				   SELECT NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,SUM(VALOR),REFERENCIA1,  
										   REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
										   PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
				   FROM   (
							   SELECT NROCOMPROBANTE=@NROCOMPROBANTE, COMPANIA=@COMPANIA, TIPO='CR',  
													   CUENTA=ITAR.CUE_IVA,  
													   IDTERCERO=CASE WHEN @MTERCERO=1 THEN   COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE IMOV.IDTERCERO END, IMOV.CCOSTO, DETALLE= @CONCETOART+' '+ITAR.DESCRIPCION, 
													   VALOR =SUM(CONVERT(decimal(14, 2),ISAL.VR_IVA ) * CONVERT(decimal(14, 2),ISAL.CANTIDAD)),
													   REFERENCIA1=IMOV.IDBODEGA, REFERENCIA2=IMOV.CNSMOV, REFERENCIA3=IART.IDITAR,ITEMREF=NULL, 
													   USUARIO=@USUARIO, FECHA=DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO=IART.IDITAR, IMOV.IDAREA, CLASECONT='S', ESTADO=1 , PROCESO='MOV_SAL_CR', 
													   GENERA='Movimiento', PROCEDENCIA='INV', REFERENCIA_PRO=@CNSMOV, IMOV.CODUNG, IMOV.CODPRG  
							   FROM   IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV 
										   INNER JOIN IART ON ISAL.IDARTICULO = IART.IDARTICULO
								   INNER JOIN ITAR ON IART.IDITAR=ITAR.IDITAR
										   LEFT  JOIN ICBU ON ISAL.NOLOTE=ICBU.CODIGOBARRA
										   LEFT JOIN  FCOM ON ICBU.CNSFCOM=FCOM.CNSFCOM
							   WHERE  IMOV.CNSMOV=@CNSMOV
						   AND COALESCE(ITAR.MIVA,0)=1
							   GROUP BY CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE IMOV.IDTERCERO END,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,IART.IDITAR, IMOV.IDBODEGA,  
																   IMOV.CODUNG, IMOV.CODPRG, IMOV.IDTIPOMOV, IMOV.IDAREA, IMOV.CCOSTO,ITAR.DESCRIPCION,ITAR.CUE_IVA  
							   ) X
				   GROUP BY NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,REFERENCIA1,  
						   REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
						   PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
            END
			END
			ELSE
			BEGIN
				INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
																				REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
																				PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
				SELECT NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,SUM(VALOR),REFERENCIA1,  
													REFERENCIA2,NULL,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
													PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
				FROM   (
													SELECT NROCOMPROBANTE=@NROCOMPROBANTE, COMPANIA=@COMPANIA, TIPO='CR',  
						  												CUENTA=DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'CXP_COMPRAS','DB',IMOV.IDTIPOMOV, IMOV.CCOSTO,'P',IART.IDITAR,0),  
																				IDTERCERO=CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE '' END, IMOV.CCOSTO, DETALLE=IMOV.OBSERVACION, 
																				VALOR =SUM(CONVERT(decimal(14, 2),ISAL.VR_ANTESIVA) * CONVERT(decimal(14, 2),ISAL.CANTIDAD)),
																				REFERENCIA1=IMOV.IDBODEGA, REFERENCIA2=IMOV.CNSMOV, REFERENCIA3=IART.IDITAR,ITEMREF=NULL, 
																				USUARIO=@USUARIO, FECHA=DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO=IART.IDITAR, IMOV.IDAREA, CLASECONT='S', ESTADO=1 , PROCESO='MOV_SAL_CR', 
								 											GENERA='Movimiento', PROCEDENCIA='INV', REFERENCIA_PRO=@CNSMOV, IMOV.CODUNG, IMOV.CODPRG  
													FROM   IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV 
									 							INNER JOIN IART ON ISAL.IDARTICULO = IART.IDARTICULO
													INNER JOIN ITAR ON IART.IDITAR=IART.IDITAR
																LEFT  JOIN ICBU ON ISAL.NOLOTE=ICBU.CODIGOBARRA
																LEFT JOIN  FCOM ON ICBU.CNSFCOM=FCOM.CNSFCOM
													WHERE  IMOV.CNSMOV=@CNSMOV
													GROUP BY CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE '' END,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,IART.IDITAR, IMOV.IDBODEGA,  
										 									IMOV.CODUNG, IMOV.CODPRG, IMOV.IDTIPOMOV, IMOV.IDAREA, IMOV.CCOSTO   
												) X
				GROUP BY NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,REFERENCIA1,  
																REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
																PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG

				PRINT 'IDCON_IMOVDBENT_COMP IVA'
            IF (SELECT IDTIPOMOV  FROM IMOV WHERE CNSMOV=@CNSMOV)<>COALESCE(DBO.FNK_VALORVARIABLE('IDINVMOVVENTAFACTURA'),'')
            BEGIN
				   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
																				   REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
																				   PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)  
				   SELECT NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,SUM(VALOR),REFERENCIA1,  
													   REFERENCIA2,NULL,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
													   PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
				   FROM   (
													   SELECT NROCOMPROBANTE=@NROCOMPROBANTE, COMPANIA=@COMPANIA, TIPO='CR',  
						  												   CUENTA=DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'CXP_COMPRAS','DB',IMOV.IDTIPOMOV, IMOV.CCOSTO,'P',IART.IDITAR,0),  
																				   IDTERCERO=CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE '' END, IMOV.CCOSTO, DETALLE=IMOV.OBSERVACION, 
																				   VALOR =SUM(CONVERT(decimal(14, 2),ISAL.VR_IVA) * CONVERT(decimal(14, 2),ISAL.CANTIDAD)),
																				   REFERENCIA1=IMOV.IDBODEGA, REFERENCIA2=IMOV.CNSMOV, REFERENCIA3=IART.IDITAR,ITEMREF=NULL, 
																				   USUARIO=@USUARIO, FECHA=DBO.FNK_FECHA_SIN_MLS(GETDATE()), PREFIJO=IART.IDITAR, IMOV.IDAREA, CLASECONT='S', ESTADO=1 , PROCESO='MOV_SAL_CR', 
								 											   GENERA='Movimiento', PROCEDENCIA='INV', REFERENCIA_PRO=@CNSMOV, IMOV.CODUNG, IMOV.CODPRG  
													   FROM   IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV 
									 							   INNER JOIN IART ON ISAL.IDARTICULO = IART.IDARTICULO
													   INNER JOIN ITAR ON IART.IDITAR=ITAR.IDITAR
																   LEFT  JOIN ICBU ON ISAL.NOLOTE=ICBU.CODIGOBARRA
																   LEFT JOIN  FCOM ON ICBU.CNSFCOM=FCOM.CNSFCOM
													   WHERE  IMOV.CNSMOV=@CNSMOV
										   AND COALESCE(ITAR.MIVA,0)=1
													   GROUP BY CASE WHEN @MTERCERO=1 THEN  COALESCE(FCOM.IDTERCERO,IMOV.IDTERCERO) ELSE '' END,IMOV.CCOSTO,IMOV.OBSERVACION,IMOV.IDAREA,IMOV.CNSMOV,IART.IDITAR, IMOV.IDBODEGA,  
										 									   IMOV.CODUNG, IMOV.CODPRG, IMOV.IDTIPOMOV, IMOV.IDAREA, IMOV.CCOSTO   
												   ) X
				   GROUP BY NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,REFERENCIA1,  
																   REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
																   PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG
            END
			END

		END
		UPDATE MCHE SET VALOR = CONVERT(decimal(14, 6),MCHE.VALOR)  + ( CONVERT(decimal(14, 6),@VALOR_IMOV) - CONVERT(decimal(14, 6),C.VALOR))
		FROM (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCHE 
								WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='CR' AND PROCESO='MOV_SAL_CR' AND REFERENCIA_PRO=@CNSMOV) AS B,
					(SELECT SUM(CONVERT(decimal(14, 6),VALOR)) AS VALOR FROM MCHE
								WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='CR' AND PROCESO='MOV_SAL_CR' AND REFERENCIA_PRO=@CNSMOV) AS C,
					IMOV 
		WHERE MCHE.NROASIENTO=B.NROASIENTO AND (@VALOR_IMOV-C.VALOR)<>0 AND IMOV.CNSMOV=@CNSMOV 

		UPDATE MCHE SET VALOR = CONVERT(decimal(14, 6),MCHE.VALOR)  + ( CONVERT(decimal(14, 6),@VALOR_IMOV) - CONVERT(decimal(14, 6),C.VALOR))
		FROM (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCHE 
								WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' AND PROCESO='MOV_SAL_DB' AND REFERENCIA_PRO=@CNSMOV) AS B,
					(SELECT SUM(CONVERT(decimal(14, 6),VALOR)) AS VALOR FROM MCHE
								WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' AND PROCESO='MOV_SAL_DB' AND REFERENCIA_PRO=@CNSMOV) AS C,
					IMOV 
		WHERE MCHE.NROASIENTO=B.NROASIENTO AND (@VALOR_IMOV-C.VALOR)<>0 AND IMOV.CNSMOV=@CNSMOV 
	END
	IF EXISTS(SELECT * FROM CUE INNER JOIN MCHE ON CUE.CUENTA=MCHE.CUENTA WHERE MCHE.NROCOMPROBANTE=@NROCOMPROBANTE AND COALESCE(CUE.CUEESPEJO,'')<>'')
	BEGIN
		DECLARE @CUEESPEJO VARCHAR(20)
		DECLARE @CUEESPEJO1 VARCHAR(20)
		DECLARE @NROASIENTO INT
		DECLARE @TIPOESP    VARCHAR(3)

		DECLARE CUESPEJO_CURSOR CURSOR FOR  
		SELECT NROASIENTO,CUE.CUEESPEJO,MCHE.TIPO 
		FROM MCHE INNER JOIN CUE ON MCHE.CUENTA=CUE.CUENTA 
		WHERE MCHE.NROCOMPROBANTE=@NROCOMPROBANTE
		AND COALESCE(CUE.CUEESPEJO,'')<>''
		GROUP BY NROASIENTO,CUE.CUEESPEJO,MCHE.TIPO         
		OPEN CUESPEJO_CURSOR    
		FETCH NEXT FROM CUESPEJO_CURSOR    
		INTO @NROASIENTO,@CUEESPEJO,@TIPOESP
		WHILE @@FETCH_STATUS = 0    
		BEGIN
			SELECT  @CUEESPEJO1=CUEESPEJO FROM CUE WHERE CUENTA=@CUEESPEJO 
			PRINT 'INSERTO LAS CUENTA ESPEJO' 

			INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, 
							USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
							ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP, MARCA, SYS_COMPUTERNAMEMARCA)
			SELECT NROCOMPROBANTE, COMPANIA, @TIPOESP, @CUEESPEJO, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, 
				USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
				ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP, MARCA, SYS_COMPUTERNAMEMARCA
			FROM MCHE
			WHERE NROASIENTO=@NROASIENTO

			PRINT 'CONTRAPARTIDA '+@TIPOESP

			INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, 
							USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
							ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP, MARCA, SYS_COMPUTERNAMEMARCA)
			SELECT NROCOMPROBANTE, COMPANIA,CASE WHEN  @TIPOESP='DB' THEN 'CR' ELSE 'DB' END, @CUEESPEJO1, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, 
				USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
				ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP, MARCA, SYS_COMPUTERNAMEMARCA
			FROM MCHE
			WHERE NROASIENTO=@NROASIENTO

		FETCH NEXT FROM CUESPEJO_CURSOR    
		INTO @NROASIENTO,@CUEESPEJO,@TIPOESP
		END
		CLOSE CUESPEJO_CURSOR
		DEALLOCATE CUESPEJO_CURSOR

	END

 	PRINT 'REVISO EL COMPROBANTE' 
 	EXEC SPK_NC_SUMA_DBCR @NROCOMPROBANTE 
 	PRINT 'PASO A MCPE'
	EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME 	
	EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''	
END



