
SELECT * FROM #C

ALTER TABLE #C ADD TERCEROID VARCHAR(20)

UPDATE #C SET TERCEROID=TER.IDTERCERO
FROM #C INNER JOIN TER ON #C.DOCIEMPLEADO=TER.NIT

SELECT * FROM #C WHERE NOT EXISTS(SELECT * FROM TER WHERE TER.IDTERCERO=#C.TERCEROID)

UPDATE #C SET FNACIMIENTO=REPLACE(FNACIMIENTO,'&','/'),FINGRESO=REPLACE(FINGRESO,'&','/')

SELECT  * INTO #D FROM NEMP WHERE NUMDOC='060000000160'

SELECT DBO.FNK_COLUMNAS_TABLAS('NEMP')

INSERT INTO NEMP(NUMDOC, SEXO, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR,  DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO, TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL,  FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50, ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, CODPRG, TIPOCOTIZANTE, SUBTIPOCOTIZANTE, CLASERESIDENTE, CODUNG, CIUDADEXP, GRUPOPOB,  CLASEMP, LIDER, EMAIL, IDFOTO, GRUPO_DOC, PROCESO, NROCONVOCA, TIPO_DOC, DOCIDEMPLEADO, TERCEROID)
SELECT #C.NUMDOC, #C.SEXO, #C.PNOMBRE, #C.SNOMBRE, #C.PAPELLIDO, #C.SAPELLIDO, DBO.FNK_AREADELCCOSTO(#C.CCOSTO), #C.CCOSTO, FINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, #C.BASICO, #C.CODCARGO, #C.GRADO,#C.NIVEL,  HORASDELABOR,  DIASXCARGO, NULL, TIPOSALARIO, TALLA_CALZADO, TALLA_CAMISA, TALLA_PANTALON, GRUPOSAN, LIBRETAMILITAR, #C.ESTADOCIVIL, TIPOCON, CONCAT('0',NOMI), #C.CTA_BCO, #C.BANCO, SUCURSAL,  #C.FNACIMIENTO, NULL, TIPOCESANTIAS, FLEY50, ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, CODPRG, TIPOCOTIZANTE, SUBTIPOCOTIZANTE, CLASERESIDENTE, CODUNG, #C.CIUDADEXP, GRUPOPOB,  CLASEMP, LIDER, NULL, IDFOTO, GRUPO_DOC, PROCESO, NROCONVOCA, TIPO_DOC, #C.DOCIEMPLEADO, #C.TERCEROID
FROM #C,#D


SELECT  * FROM #C WHERE EXISTS(SELECT * FROM NEMP WHERE #C.NUMDOC=NEMP.NUMDOC)

ALTER TABLE #C ADD CODPLANTA VARCHAR(20)

UPDATE #C SET CODPLANTA='07000000'+CAST((ID+104)AS VARCHAR(3))

SELECT * FROM NPLA WHERE CODPLANTA LIKE '07%'

SELECT DBO.FNK_COLUMNAS_TABLAS('NPLA')

SELECT * FROM CEN

INSERT INTO NPLA(CODPLANTA, IDAREA, CCOSTO, CODCARGO, NIVEL, GRADO, NUMDOC, IDSEDE, CODUNG)
SELECT CODPLANTA, CEN.IDAREA, #C.CCOSTO, CODCARGO, #C.GRADO, #C.NIVEL, NUMDOC, CEN.IDSEDE, '01'
FROM #C LEFT JOIN CEN ON #C.CCOSTO=CEN.CCOSTO

UPDATE NEMP SET EMAIL='soporte@soporte.com'
FROM #C INNER JOIN NEMP ON #C.NUMDOC=NEMP.NUMDOC

SELECT DBO.FNK_COLUMNAS_TABLAS('NEMPHIS')

INSERT INTO NEMPHIS (NUMDOC, FECHAMOV, SEXO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR, DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO,  TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL, FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50,  ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, USUARIOMOD, FECHAMOD, SYS_COMPUTERNAME, OPERACION)
SELECT NUMDOC, NEMP.FECHAINGRESO, SEXO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR, DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO,  TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL, FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50,  ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, 'SOPORTE', DBO.FNK_GETDATE(), 'SOPORTE', 'CAMBIA'
FROM NEMP 
WHERE EXISTS(SELECT * FROM #C WHERE NEMP.NUMDOC=#C.NUMDOC)


SELECT  * INTO #F FROM NPRFED WHERE NUMDOC='060000000160'

SELECT DBO.FNK_COLUMNAS_TABLAS('NPRFED')

INSERT INTO NPRFE (NUMDOC, CODPRF)
SELECT #C.NUMDOC, #E.CODPRF
FROM #C,#E

INSERT INTO NPRFED(NUMDOC, CODPRF, ITEM, FECHAINI, IDTERCERO)
SELECT #C.NUMDOC,#F.CODPRF,1,#C.FINGRESO,#C.ARL
FROM #C, #F
WHERE #F.CODPRF IN('AG08-1','','')
ORDER BY #C.NUMDOC

DELETE NPRFED WHERE CODPRF IN('AG05','AG06','AG07') AND NUMDOC IN(SELECT NUMDOC FROM #C)

SELECT  * INTO #G FROM NOMIE WHERE NUMDOC='060000000160' AND CODNOMINA<>'01'

SELECT  * FROM #C
SELECT  * FROM #G

INSERT INTO NOMIE(NUMDOC,CODNOMINA,ESTADO)
SELECT NUMDOC,CONCAT('0',NOMI),'Activo'
FROM #C

INSERT INTO NOMIE(NUMDOC,CODNOMINA,ESTADO)
SELECT #C.NUMDOC,#G.CODNOMINA,#G.ESTADO
FROM #C,#G