IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_FACTURACI_ESCMA' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_FACTURACI_ESCMA
END

GO
CREATE PROCEDURE  DBO.SPK_FACTURACI_ESCMA
@CNSRPDX      VARCHAR(20),
@NIT          VARCHAR(20),
@COMPANIA     VARCHAR(2),
@IDSEDE       VARCHAR(5),
@USUARIO      VARCHAR(12),
@IDTERCERO    VARCHAR(20),
@IDPLAN       VARCHAR(6),
@OBSERVACION  VARCHAR(255),
@IDTERCEROCA1 VARCHAR(20),
@F_FACTURA    DATETIME,
@TRAECONSEC   VARCHAR(20) = NULL,
@TRAECNSFTR   VARCHAR(20) = NULL,
@CLASEFACTURA VARCHAR(3) = '',
@IDAFILIADO   VARCHAR(20) = NULL,
@IDSEDEF      VARCHAR(5) = NULL
WITH ENCRYPTION
AS
DECLARE @CNSFTR           VARCHAR(20),@PRE VARCHAR(20), @CONSECFTR INT, @CNSRESOL VARCHAR(50)
DECLARE @NVOCONSEC        VARCHAR(20)
DECLARE @DATO             VARCHAR(80)
DECLARE @DATO1            VARCHAR(80) 
DECLARE @DV               INT
DECLARE @DATO3            VARCHAR(20)
DECLARE @DATO2            VARCHAR(80) 
DECLARE @VRTOTAL          DECIMAL(14,2)
DECLARE @VRSERV           DECIMAL(14,2) 
DECLARE @VRCOPA           DECIMAL(14,2)
DECLARE @VRPACO           DECIMAL(14,2)
DECLARE @OK               INT
DECLARE @DESCUENTO        DECIMAL(14,2)
DECLARE @VRDTO            DECIMAL(14,2) 
DECLARE @VRABONO          DECIMAL(14,2)
DECLARE @TTEC             VARCHAR(10)
DECLARE @IDTERCEROCA      VARCHAR(20)
DECLARE @CUENTACXC        VARCHAR(16)
DECLARE @LIBERADA         VARCHAR(2)=''
DECLARE @IDFORMATOFTR     VARCHAR(20)
DECLARE @SYS_COMPUTERNAME VARCHAR(254),  @MAXN_CUOTA INT,  @CANTAFI INT
DECLARE @VIVA             DECIMAL(14,2)
DECLARE @IDAFILIADOTER    VARCHAR(20)
DECLARE @IDAFIAUX         VARCHAR(20)
DECLARE @IDCATEGORIA       VARCHAR(20)
DECLARE @TV                VARCHAR(10)
BEGIN
   PRINT 'INGRESE POR CITAS'
   PRINT 'SEDE FILTRO '+COALESCE(@IDSEDEF,'SIN SEDE')
   SET @SYS_COMPUTERNAME = HOST_NAME()
   SELECT @DV = PPT.DIASVTO, @TTEC= PPT.TIPOTERCONTABLE, @CUENTACXC = TTEC.CUENTA
   FROM PPT INNER JOIN
        TTEC ON PPT.TIPOTERCONTABLE = TTEC.TIPO
   WHERE PPT.IDTERCERO = @IDTERCERO AND PPT.IDPLAN = @IDPLAN
   
   IF @DV IS NULL
      SELECT @DV = 30
   IF @DV = 0
      SELECT @DV = 30
   
	IF (SELECT SIIF FROM TER WHERE IDTERCERO = @IDTERCERO)=1 
	BEGIN
		SELECT @OBSERVACION='#$'+COALESCE(SIIFCODIGOPCI,'')+';'+COALESCE(SIIFCONTRATO,'')+';'+COALESCE(SIIFCORREOSUPER,'')+'#$
			'+COALESCE(@OBSERVACION,'')
		FROM TER WHERE IDTERCERO = @IDTERCERO
	END

   SELECT @DATO3 = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'     
   SELECT @DATO2 = DATO FROM USVGS WHERE IDVARIABLE = 'IDMONEDABASE'

   UPDATE CIT SET CANTIDADC=1 
   FROM CIT LEFT JOIN 
        TER ON CIT.IDTERCEROCA=TER.IDTERCERO
   WHERE CIT.IDTERCEROCA = @IDTERCERO AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND CIT.CNSFACT = @CNSRPDX
   AND   COALESCE(FACTURABLE,0)=1 
   AND   ((COALESCE(VALORTOTAL,0)>0 AND @CLASEFACTURA <> 'CUE') OR (COALESCE(VALORTOTAL,0) = COALESCE(VALORTOTAL,0) AND @CLASEFACTURA =  'CUE')) 
   AND   COALESCE(CIT.DESCUENTO,0)<CASE WHEN CIT.TIPODTO='P' THEN 100 ELSE CIT.VALORTOTAL END
   AND   (TER.IDTERCERO = (CASE WHEN @IDTERCEROCA1='' THEN TER.IDTERCERO ELSE @IDTERCEROCA1 END) OR
          (TER.IDTERCERO IS NULL AND @IDTERCERO=@IDTERCEROCA1 AND @IDTERCEROCA1<>'') OR
          (TER.IDTERCERO IS NULL AND @IDTERCEROCA1=''))
   AND   CIT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDAFILIADO ELSE CIT.IDAFILIADO END
   AND COALESCE(CANTIDADC,0)=0
   AND CIT.IDSEDE=CASE WHEN COALESCE(@IDSEDEF,'')<> '' THEN @IDSEDEF ELSE CIT.IDSEDE END
   
   CREATE TABLE #FTRD1(CNSFTR      VARCHAR(40),   N_CUOTA	     int IDENTITY,  FECHA datetime,
                       DB_CR       VARCHAR(2),    AREAPRESTACION varchar(20),   UBICACION varchar(16),
                       VR_TOTAL    FLOAT,         IMPUTACION     varchar(16),   CCOSTO varchar (20),
                       PREFIJO     VARCHAR(6),    ANEXO          varchar(1024), REFERENCIA varchar(40), 
                       IDCIRUGIA   VARCHAR(20),   CANTIDAD       smallint,      VALOR decimal(14,2),
                       VLR_SERVICI DECIMAL(14,2), VLR_COPAGOS    decimal(14,2),
                       VLR_PAGCOMP DECIMAL(14,2), IDPROVEEDOR    varchar(20),
                       NOADMISION  VARCHAR(16),   NOPRESTACION	 varchar(16),   NOITEM int,	
                       AREAFUNCONT VARCHAR(20),   N_FACTURA      varchar(16),
                       SUBCCOSTO   VARCHAR(4),    PCOSTO	     decimal(14,2), FECHAPREST datetime, IDPLAN VARCHAR(6),
                       PROCEDENCIA VARCHAR(10),  IDAFILIADO      VARCHAR(20))
   
   DECLARE CUR_FTR CURSOR FOR
   SELECT DISTINCT CASE WHEN TER.IDTERCERO IS NULL THEN @IDTERCERO ELSE CIT.IDTERCEROCA END
   FROM CIT LEFT JOIN 
        TER ON CIT.IDTERCEROCA=TER.IDTERCERO
   WHERE CIT.IDTERCEROCA = @IDTERCERO AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND CIT.CNSFACT = @CNSRPDX
   AND   COALESCE(FACTURABLE,0)=1 
   AND   ((COALESCE(VALORTOTAL,0)>0 AND @CLASEFACTURA <> 'CUE') OR (COALESCE(VALORTOTAL,0) = COALESCE(VALORTOTAL,0) AND @CLASEFACTURA =  'CUE')) 
   AND   COALESCE(CIT.DESCUENTO,0)<CASE WHEN CIT.TIPODTO='P' THEN 100 ELSE CIT.VALORTOTAL END
   AND   (TER.IDTERCERO = (CASE WHEN @IDTERCEROCA1='' THEN TER.IDTERCERO ELSE @IDTERCEROCA1 END) OR
          (TER.IDTERCERO IS NULL AND @IDTERCERO=@IDTERCEROCA1 AND @IDTERCEROCA1<>'') OR
          (TER.IDTERCERO IS NULL AND @IDTERCEROCA1=''))
   AND   CIT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDAFILIADO ELSE CIT.IDAFILIADO END
   AND CIT.IDSEDE=CASE WHEN  COALESCE(@IDSEDEF,'')<> '' THEN @IDSEDEF ELSE CIT.IDSEDE END
   
   OPEN CUR_FTR
   
   FETCH NEXT FROM CUR_FTR
   INTO @IDTERCEROCA
   
   WHILE @@FETCH_STATUS = 0  
   BEGIN 

      IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART')
         OR @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART2') OR @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART3')
         OR @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART4') OR @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART5')
      BEGIN   
		  PRINT 'ES PARTICULAR REVISION 01.02.2008' 
         SELECT @TV = 'Contado'  
         SELECT @IDAFIAUX=DOCIDAFILIADO, @IDAFILIADO=IDAFILIADO FROM AFI WHERE IDAFILIADO= @IDAFILIADO   
         SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
         PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
         EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA, 'CIT', @CNSRPDX
		 
      END
      IF (@IDTERCEROCA = dbo.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') AND EXISTS (SELECT * FROM TER WHERE ESTADO='Activo' AND NIT=@IDAFIAUX ))
		BEGIN
				SELECT @IDAFILIADOTER= IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=@IDAFIAUX 
		END 
      INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                         IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                         VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                         NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
                         FECHAPREST, IDPLAN, PROCEDENCIA, IDAFILIADO)
      SELECT @CNSFTR, GETDATE(), 'DB', CIT.IDAREA, NULL, (COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL) - COALESCE(CIT.VALORCOPAGO,0), 
             NULL, CIT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, CIT.IDSERVICIO, NULL,
             COALESCE(CIT.CANTIDADC,1) AS CANTIDAD, CIT.VALORTOTAL, COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL , COALESCE(CIT.VALORCOPAGO,0),
             0, CIT.IDMEDICO, CIT.CONSECUTIVO, CIT.CONSECUTIVO, NULL, NULL, 
             @NVOCONSEC, CIT.SUBCCOSTO, CIT.VALORTOTALCOS,CIT.FECHA, CIT.IDPLAN, 'CI', CIT.IDAFILIADO 
      FROM   CIT INNER JOIN SER ON SER.IDSERVICIO  = CIT.IDSERVICIO 
                  LEFT JOIN TER ON CIT.IDTERCEROCA = TER.IDTERCERO
      WHERE  CIT.IDTERCEROCA = @IDTERCERO AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND CIT.CNSFACT = @CNSRPDX AND COALESCE(CIT.FACTURABLE,0) = 1
         AND (TER.IDTERCERO = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCERO=@IDTERCEROCA))
	      AND CIT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDAFILIADO ELSE CIT.IDAFILIADO END
         AND CIT.IDSEDE=CASE WHEN  COALESCE(@IDSEDEF,'')<> '' THEN @IDSEDEF ELSE CIT.IDSEDE END

PRINT 'DESCUENTO'
    select @VRDTO = SUM(CASE WHEN CIT.TIPODTO='P' THEN VALORTOTAL* COALESCE(DESCUENTO,0)/100 ELSE COALESCE(DESCUENTO,0)END )
	FROM   CIT INNER JOIN SER ON SER.IDSERVICIO  = CIT.IDSERVICIO 
                  LEFT JOIN TER ON CIT.IDTERCEROCA = TER.IDTERCERO
      WHERE  CIT.IDTERCEROCA = @IDTERCERO AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND CIT.CNSFACT = @CNSRPDX AND COALESCE(CIT.FACTURABLE,0) = 1
         AND (TER.IDTERCERO = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCERO=@IDTERCEROCA))
	      AND CIT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDAFILIADO ELSE CIT.IDAFILIADO END

      SELECT @OK = COUNT(*) FROM #FTRD1
      IF @OK > 0 
      BEGIN
         IF @IDAFILIADO IS NULL AND (SELECT COUNT(DISTINCT IDAFILIADO) FROM #FTRD1)=1
            SELECT @IDAFILIADO=IDAFILIADO FROM #FTRD1 GROUP BY IDAFILIADO

         PRINT 'ENTRE A QUE SI EXISTE CITS'
         IF COALESCE(@TRAECONSEC,'') = '' -- SI TRAE ESTE PARAMETRO LLENO ES POR QUE ES UNA FACTURA UNIFICADA DE CE Y YA TRAE FACTURADO LO DE AUT
         BEGIN
            
            SELECT TOP 1 @CNSFTR=CNSFCT, @NVOCONSEC=N_FACTURA, @LIBERADA=ESTADO FROM FTR 
            WHERE IDTERCERO=@IDTERCEROCA AND ESTADO='L' AND TIPOFAC='M' AND (NOREFERENCIA='VARIOS' OR NOREFERENCIA<>'VARIOS')
            PRINT '@LIBERADA=='+COALESCE(@LIBERADA,'')+'N_FACTURA _'+@NVOCONSEC

            IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCIT,'')<>'')
            BEGIN
                SELECT @IDFORMATOFTR=IDFORFTRCIT  FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCIT,'')<>''
            END
            ELSE
            BEGIN
                SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
            END

            IF COALESCE(@LIBERADA,'') <> 'L'
            BEGIN
			PRINT 'ENTRE AQUI NO ESTA LIBERADA'
               SET @CNSFTR = SPACE(20)
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
               SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0)
        
               SET @NVOCONSEC = SPACE(20)
               EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
               PRINT ' N_FACTURA = '+ CASE WHEN @NVOCONSEC IS NULL THEN '' ELSE @NVOCONSEC END
      
               IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI'
               BEGIN
                  EXEC SPK_PREFIJOFACTURA @COMPANIA, @IDSEDE, @PRE OUTPUT  
                  SELECT @CONSECFTR = CONSECUTIVO FROM USCXS WHERE COMPANIA = '01' AND IDSEDE = @IDSEDE AND PREFIJO = @PRE
                  SELECT @CNSRESOL  = CNSRESOL FROM FDIAN WHERE IDENTIFICADOR = @IDSEDE AND VENCIDA = 0 AND PROCEDENCIA = 'FTR' AND CNSINICIAL <= @CONSECFTR AND CNSFINAL >= @CONSECFTR
               END
           
               INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
                           VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
                           IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
                           TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
                           INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
                           IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
                           MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
                           CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,IDSEDE,RDIAN, CNSRESOL, IDFORMATO) 
               SELECT @CNSFTR, @COMPANIA, 'C', CASE @IDTERCEROCA WHEN dbo.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') 
																									THEN @IDAFILIADOTER  
																								    ELSE @IDTERCERO END, @NVOCONSEC, @F_FACTURA,@F_FACTURA+@DV,
                      0, NULL, NULL, LEFT(@DATO2,2), NULL, 'P', NULL, @IDAFILIADO, @USUARIO, 'VARIOS',
                      'CI', 'M', REPLACE(COALESCE(@OBSERVACION,''),'@N_FACTURA',@NVOCONSEC) , 'Credito', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO,
                      GETDATE(), 0, 0, 0, @IDPLAN, NULL, 'C', NULL, NULL, NULL, @DATO3, @TTEC, @CUENTACXC,@IDSEDE,
                      CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''), @IDFORMATOFTR
            END
            ELSE
            BEGIN
               IF EXISTS(SELECT 1 FROM FTRD WHERE CNSFTR=@CNSFTR)
               BEGIN
                  DELETE FTRD WHERE CNSFTR=@CNSFTR
               END
               
               PRINT 'ACTUALIZO EN FTR'
               UPDATE FTR SET IDPLAN=@IDPLAN, F_FACTURA=@F_FACTURA, F_VENCE=@F_FACTURA, ESTADO='P', IDFORMATO=@IDFORMATOFTR,
                  VR_TOTAL=0, EMPLEADO=@USUARIO, TIPOTTEC=@TTEC, CUENTACXC=@CUENTACXC, IDAFILIADO=@IDAFILIADO
               WHERE N_FACTURA=@NVOCONSEC
            END
         END

         IF COALESCE(@TRAECONSEC,'') <> ''
         BEGIN
            SELECT @MAXN_CUOTA = ISNULL(MAX(N_CUOTA),0) FROM FTRD WHERE CNSFTR = @TRAECNSFTR
         END
		
         UPDATE #FTRD1 SET CANTIDAD = COALESCE(CANTIDAD,0), VALOR = COALESCE(VALOR,0), VLR_SERVICI = COALESCE(VLR_SERVICI,0),
							VR_TOTAL = COALESCE(VR_TOTAL,0), VLR_COPAGOS = COALESCE(VLR_COPAGOS,0), VLR_PAGCOMP = COALESCE(VLR_PAGCOMP,0)
           
         INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                          IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                          VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                          NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, PROCEDENCIA)
         SELECT CASE COALESCE(@TRAECONSEC,'') WHEN '' THEN @CNSFTR ELSE @TRAECNSFTR END,  
                CASE COALESCE(@TRAECONSEC,'') WHEN '' THEN N_CUOTA ELSE N_CUOTA + @MAXN_CUOTA END, 
                FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                NOPRESTACION, NOITEM, AREAFUNCONT, CASE COALESCE(@TRAECONSEC,'') WHEN '' THEN @NVOCONSEC ELSE @TRAECONSEC END, 
                SUBCCOSTO, PCOSTO, FECHAPREST, PROCEDENCIA
         FROM   #FTRD1
              
         TRUNCATE TABLE #FTRD1   
              
         SELECT @VRTOTAL = SUM(COALESCE(VR_TOTAL,0)), @VRSERV = SUM(COALESCE(VLR_SERVICI,0)), @VRCOPA = SUM(COALESCE(VLR_COPAGOS,0)),
                @VRPACO  = SUM(COALESCE(VLR_PAGCOMP,0))
         FROM FTRD WHERE N_FACTURA = CASE COALESCE(@TRAECONSEC,'') WHEN '' THEN @NVOCONSEC ELSE @TRAECONSEC END
         
         IF @VRTOTAL IS NULL SELECT @VRTOTAL = 0
         IF @VRSERV IS NULL  SELECT @VRSERV = 0
         IF @VRCOPA IS NULL  SELECT @VRCOPA = 0
         IF @VRPACO IS NULL  SELECT @VRPACO = 0		 
		 
		 IF COALESCE(@VRDTO,0)<=0
		 BEGIN 
		         SELECT @VRDTO = 0, @VRABONO = 0
		END
          
         UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = @VRCOPA, VALORPCOMP = @VRPACO,
                        DESCUENTO = @VRDTO, VR_ABONOS = @VRABONO, VR_TOTAL = @VRTOTAL
         WHERE N_FACTURA = CASE COALESCE(@TRAECONSEC,'') WHEN '' THEN @NVOCONSEC ELSE @TRAECONSEC END
         
         UPDATE FTR SET VR_TOTAL = VALORSERVICIOS - VALORCOPAGO - VALORPCOMP -DESCUENTO - VR_ABONOS
         WHERE  N_FACTURA = CASE COALESCE(@TRAECONSEC,'') WHEN '' THEN @NVOCONSEC ELSE @TRAECONSEC END      
         
         -- GENERA LA DEDUCCION DE IMPUESTOS ESPERADA
         SELECT @VRTOTAL = VR_TOTAL FROM FTR WHERE  N_FACTURA = @NVOCONSEC 
         EXEC SPK_FAC_IMPDEDUC @NIT, @CNSFTR, @NVOCONSEC, @VRTOTAL    
         
         UPDATE CIT SET FACTURADA = 1, N_FACTURA = CASE COALESCE(@TRAECONSEC,'') WHEN '' THEN @NVOCONSEC ELSE @TRAECONSEC END, 
                CNSFCT = CASE COALESCE(@TRAECONSEC,'') WHEN '' THEN @CNSFTR ELSE @TRAECNSFTR END, VFACTURAS = 0, MARCAFAC = 0
         FROM CIT LEFT JOIN 
              TER ON CIT.IDTERCEROCA=TER.IDTERCERO
         WHERE CIT.IDTERCEROCA = @IDTERCERO AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND
             (TER.IDTERCERO = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCERO=@IDTERCEROCA))
		 AND   CIT.IDAFILIADO = CASE @CLASEFACTURA WHEN 'CUE' THEN @IDAFILIADO ELSE CIT.IDAFILIADO END
      END
      FETCH NEXT FROM CUR_FTR
      INTO @IDTERCEROCA
   END
   CLOSE CUR_FTR
   DEALLOCATE CUR_FTR
   DROP TABLE #FTRD1  


IF COALESCE(@TRAECONSEC,'')<>''
BEGIN
	SELECT @NVOCONSEC=COALESCE(@TRAECONSEC,'')
END

SELECT @CANTAFI=COUNT(IDAFILIADO) 
FROM (SELECT DISTINCT IDAFILIADO FROM CIT WHERE CIT.N_FACTURA=@NVOCONSEC UNION ALL
	  SELECT DISTINCT IDAFILIADO  FROM AUTD INNER JOIN AUT ON AUT.IDAUT=AUTD.IDAUT WHERE AUTD.N_FACTURA=@NVOCONSEC) Z 


IF(DBO.FNK_VALORVARIABLE('IDFORMATOFTR'))='03F2'
BEGIN 
    IF  COALESCE(@TRAECONSEC,'') = '' 
	BEGIN
		IF COALESCE(@CANTAFI,0)>1
		BEGIN 
			UPDATE FTR SET NOREFERENCIA='VARIOS',IDAFILIADO=NULL,IDFORMATO='03F2' WHERE N_FACTURA=@NVOCONSEC
		END 
		ELSE 
		BEGIN 
			UPDATE FTR SET 
			NOREFERENCIA=(SELECT MAX(CIT.CONSECUTIVO)  FROM CIT WHERE CIT.N_FACTURA=@NVOCONSEC),
			IDAFILIADO  =(SELECT MAX(IDAFILIADO) FROM CIT WHERE CIT.N_FACTURA=@NVOCONSEC),
			IDFORMATO='03F2' 
			WHERE N_FACTURA=@NVOCONSEC
		END
	END 
	ELSE
	BEGIN
		UPDATE FTR SET 
			NOREFERENCIA=(SELECT MAX(CIT.CONSECUTIVO)  FROM CIT WHERE CIT.N_FACTURA=@TRAECONSEC)  ,
			IDAFILIADO  =(SELECT MAX(IDAFILIADO) FROM CIT WHERE CIT.N_FACTURA=@TRAECONSEC) , 
			VR_TOTAL=@VRTOTAL , VALORSERVICIOS=@VRSERV, VALORCOPAGO=@VRCOPA, VALORPCOMP=@VRPACO
		WHERE N_FACTURA=@TRAECONSEC
	END
END
ELSE
BEGIN
	IF COALESCE(@CANTAFI,0)>1
	BEGIN 
		UPDATE FTR SET IDAFILIADO=NULL WHERE N_FACTURA=@NVOCONSEC --AND COALESCE(IDAFILIADO,'')=''
	END
	ELSE 
	BEGIN 
		UPDATE FTR SET IDAFILIADO =(SELECT MAX(IDAFILIADO) FROM CIT WHERE CIT.N_FACTURA=@NVOCONSEC)
		WHERE N_FACTURA=@NVOCONSEC
	END
END 
SELECT @VRTOTAL = SUM(COALESCE(VR_TOTAL,0)), 
		@VRSERV = SUM(COALESCE(VLR_SERVICI,0)), 
		@VRPACO = SUM(COALESCE(VLR_PAGCOMP,0)), 
		@VRCOPA = SUM(COALESCE(VLR_COPAGOS,0)), 
		@VIVA = SUM(COALESCE(VIVA,0))
FROM FTRD WHERE N_FACTURA = @NVOCONSEC

UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = @VRCOPA, VALORPCOMP = @VRPACO, VIVA = @VIVA, 
		        VR_TOTAL = @VRSERV - @VRCOPA - @VRPACO - COALESCE(@VRDTO,0) - COALESCE(@VRABONO,0)
WHERE N_FACTURA = @NVOCONSEC

PRINT @NVOCONSEC
PRINT 'ENVIANDO a CONTABILIDAD'
EXEC SPK_NC_CONTAB_FTR @NVOCONSEC, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''

END

