IF EXISTS (SELECT name FROM sysobjects WHERE NAME = 'SPK_ACTUALIZA_RESAFI4505' AND type = 'P')
BEGIN
   DROP PROCEDURE SPK_ACTUALIZA_RESAFI4505
END

GO
CREATE PROC DBO.SPK_ACTUALIZA_RESAFI4505
	@ID				INT,
	@CAMPO			VARCHAR(10),
	@FECHAREAL		DATE,
	@ALFANUMERICO	VARCHAR(120),
	@CONSECUTIVO	VARCHAR(20)
WITH ENCRYPTION
AS 
SET NOCOUNT ON
DECLARE 
   @CLASEPLANTILLA   VARCHAR(8),
   @FECHA			 VARCHAR(12),
   @SQL              VARCHAR(MAX),
   @TIPOCAMPO        VARCHAR(20),
   @TIPO_NUMERICO    VARCHAR(20),
   @TIPO_DECIMAL     VARCHAR(50),
   @TIPO_FECHA       VARCHAR(12),
   @HCPLANTILLAPARTO VARCHAR(20),
   @COP VARCHAR(20)

BEGIN
   IF @CONSECUTIVO IS NOT NULL
	  SELECT @CLASEPLANTILLA=CLASEPLANTILLA FROM HCA WHERE CONSECUTIVO=@CONSECUTIVO
   ELSE
	  SET @CLASEPLANTILLA='SIN DATO'	  

   SELECT @HCPLANTILLAPARTO=LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE='HCPLANTILLAPARTO'
    
	IF (@CAMPO=76 OR @CAMPO=102)
	   BEGIN 
	   SET @COP='SI'
	   END
	   ELSE 
	    BEGIN 
	   SET @COP='NO'
	   END

   IF @FECHAREAL IS NULL
      SELECT @FECHAREAL=FECHA FROM HCA WHERE CONSECUTIVO=@CONSECUTIVO

   SET @FECHA=''''+REPLACE(CONVERT(VARCHAR(10),@FECHAREAL,102),'.','-')+''''

   SET @ALFANUMERICO = REPLACE(@ALFANUMERICO,' ','')

   IF @ALFANUMERICO = ''
      RETURN

   SELECT @TIPOCAMPO=TIPOCAMPO FROM RESCAMPOS WHERE CODRES='4505' AND CAMPO=@CAMPO
   
   --Prevalidaciones
   IF @CAMPO=30 OR @CAMPO=32 --Peso y Talla
   BEGIN
	   SET @ALFANUMERICO = REPLACE(REPLACE(@ALFANUMERICO,',','.'),'..','.')
      IF @ALFANUMERICO LIKE '%.%' AND ISNUMERIC(@ALFANUMERICO)=1
      BEGIN
         IF CONVERT(DECIMAL(14,2),@ALFANUMERICO)<3
            SET @ALFANUMERICO = CONVERT(DECIMAL(14,2),@ALFANUMERICO)*100
      END
   END

   IF @TIPOCAMPO = 'Numerico' AND  @ALFANUMERICO<>(SELECT IDALTERNA2 FROM  TER WHERE IDTERCERO=dbo.FNK_VALORVARIABLE('IDTERCEROINSTALADO')  ) AND @COP='NO'
  
   BEGIN
	  IF REPLACE(@ALFANUMERICO,',','.')='.'  
          SET @TIPO_NUMERICO = '0'
      ELSE IF ISNUMERIC(REPLACE(REPLACE(@ALFANUMERICO,'-',''),',','.'))=1
	      SET @TIPO_NUMERICO = CONVERT(SMALLINT,CEILING(REPLACE(@ALFANUMERICO,',','.')))
      ELSE IF RIGHT(@ALFANUMERICO,8)='ESVACUNA'
	      SET @TIPO_NUMERICO=CONVERT(SMALLINT,CEILING(DBO.FNK_DEJAENTERO(REPLACE(@ALFANUMERICO,',','.'))))
	  ELSE IF LEN(DBO.FNK_DEJAENTERO(@ALFANUMERICO)) BETWEEN 1 AND 6
	      SET @TIPO_NUMERICO = CONVERT(SMALLINT,DBO.FNK_DEJAENTERO(REPLACE(@ALFANUMERICO,',','.')))
      ELSE
          SET @TIPO_NUMERICO = 'NULL'
   END
   ELSE IF @TIPOCAMPO = 'Decimal'
   BEGIN
	  IF REPLACE(@ALFANUMERICO,',','.')='.'
         SET @TIPO_DECIMAL = '0'
	  ELSE IF ISNUMERIC(REPLACE(REPLACE(@ALFANUMERICO,'-',''),',','.'))=1 --AND @CAMPO NOT IN (107)
		 SET @TIPO_DECIMAL = CONVERT(DECIMAL(14,2),REPLACE(@ALFANUMERICO,',','.'))
	  ELSE IF LEN(DBO.FNK_DEJAENTERO(@ALFANUMERICO))<8 AND @CAMPO NOT IN (107)

	     SET @TIPO_DECIMAL = CONVERT(SMALLINT,DBO.FNK_DEJAENTERO(REPLACE(@ALFANUMERICO,',','.')))
      ELSE
         SET @TIPO_NUMERICO = 'NULL'
   END
   ELSE IF @TIPOCAMPO = 'Fecha'
   BEGIN
	  IF ISDATE(@ALFANUMERICO)=1 AND COALESCE(@COP,'NO')='NO'
	   BEGIN
	   PRINT 'ENTRE AQUI CAMPO: '+@CAMPO+' DATO: '+@ALFANUMERICO
		 SET @TIPO_FECHA = ''''+REPLACE(CONVERT(VARCHAR(10),(CASE WHEN ISDATE(@ALFANUMERICO)=1 THEN CONVERT(DATE,@ALFANUMERICO) ELSE @ALFANUMERICO END),102),'.','-')+''''
		END  
	  ELSE --if coalesce(@ALFANUMERICO,'1800-01-01-01')=1 AND @COP='NO'
	  BEGIN
	  
	  PRINT 'ENTRE AQUI CAMPO ' +CONVERT(VARCHAR(20),@CAMPO)
	     SET @TIPO_FECHA = ''''+REPLACE(CONVERT(VARCHAR(10),CONVERT(DATE,@FECHAREAL),102),'.','-')+''''
		   PRINT @TIPO_FECHA
		 END
		 

   END
     

	     IF @CAMPO = 14  SET @SQL='GESTACION='                  +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 15  SET @SQL='SIFILISGESTCONG='            +@TIPO_NUMERICO
	ELSE IF @CAMPO = 16  SET @SQL='HIPERINDUGEST='              +@TIPO_NUMERICO
	ELSE IF @CAMPO = 17  SET @SQL='HIPOTIROIDISMOCONGE='        +@TIPO_NUMERICO
	ELSE IF @CAMPO = 18  SET @SQL='SINTOMATICORESP='            +@TIPO_NUMERICO
	ELSE IF @CAMPO = 19  SET @SQL='TUBERCULOSISMULTIDROGORES='  +@TIPO_NUMERICO
	ELSE IF @CAMPO = 20  SET @SQL='LEPAR='                      +@TIPO_NUMERICO
    ELSE IF @CAMPO = 21  SET @SQL='OBEDESNUTPROT='              +@TIPO_NUMERICO
                              +', FECHADXDESNUT='              +(CASE WHEN @TIPO_NUMERICO IN ('2')   THEN @FECHA ELSE 'NULL' END)
	ELSE IF @CAMPO = 22  SET @SQL='VICMALTRATO='                +@TIPO_NUMERICO
                              +', CONSMUJMENORVICMALTRATO='    +(CASE WHEN @TIPO_NUMERICO IN ('1','2') THEN @FECHA ELSE 'NULL' END)
	ELSE IF @CAMPO = 23  SET @SQL='VICVIOSEX='                  +@TIPO_NUMERICO
                              +', CONSVICTVIOSEXUAL='          +(CASE WHEN @TIPO_NUMERICO IN ('1')   THEN @FECHA ELSE 'NULL' END)
	ELSE IF @CAMPO = 24  SET @SQL='INFTRANMISEXUAL='            +@TIPO_NUMERICO
	ELSE IF @CAMPO = 25  SET @SQL='ENFERMENTAL='                +@TIPO_NUMERICO 								
	ELSE IF @CAMPO = 26  SET @SQL='CANCERCERVIX='               +@TIPO_NUMERICO
	ELSE IF @CAMPO = 27  SET @SQL='CANCERSENO='                 +@TIPO_NUMERICO
	ELSE IF @CAMPO = 28  SET @SQL='FLUOROSISDENTAL='            +@TIPO_NUMERICO
	ELSE IF @CAMPO = 29  SET @SQL='FECHAPESO='                  +@TIPO_FECHA
	ELSE IF @CAMPO = 30  SET @SQL='PESO='                       +@TIPO_NUMERICO
                              +', FECHAPESO='                  +(CASE WHEN @TIPO_NUMERICO='0' THEN 'FECHAPESO' ELSE @FECHA END)
	ELSE IF @CAMPO = 31  SET @SQL='FECHATALLA='                 +@TIPO_FECHA
	ELSE IF @CAMPO = 32  SET @SQL='TALLA='                      +@TIPO_NUMERICO
                              +', FECHATALLA='                 +(CASE WHEN @TIPO_NUMERICO='0' THEN 'FECHATALLA' ELSE @FECHA END)
	ELSE IF @CAMPO = 33  SET @SQL='FECHAPROBPARTO='             +(CASE WHEN ISDATE(@ALFANUMERICO)=1  THEN ''''+REPLACE(CONVERT(VARCHAR(10),(CASE WHEN ISDATE(@ALFANUMERICO)=1 THEN CONVERT(DATE,@ALFANUMERICO) ELSE @ALFANUMERICO END),102),'.','-')+''''
                                                                       ELSE @TIPO_FECHA END)
	ELSE IF @CAMPO = 34  SET @SQL='EDADGESTNACER='              +@TIPO_NUMERICO
	ELSE IF @CAMPO = 35  SET @SQL='BCG='                        +@TIPO_NUMERICO
	ELSE IF @CAMPO = 36  SET @SQL='HEPATITISBMEN1ANO='          +@TIPO_NUMERICO
	ELSE IF @CAMPO = 37  SET @SQL='PENTAVALENTE='               +@TIPO_NUMERICO
	ELSE IF @CAMPO = 38  SET @SQL='POLIO='                      +@TIPO_NUMERICO
	ELSE IF @CAMPO = 39  SET @SQL='DPTMEN5ANOS='                +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 40  SET @SQL='ROTAVIRUS='                  +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 41  SET @SQL='NEUMOCOCO='                  +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 42  SET @SQL='INFLUENZANINOS='             +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 43  SET @SQL='FIEBREAMARILLA1ANO='         +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 44  SET @SQL='HEPATITISA='                 +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 45  SET @SQL='TRIPLEVIRALNINOS='           +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 46  SET @SQL='VPH='                        +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 47  SET @SQL='TDTTMUJER1549='              +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 48  SET @SQL='CONTROLPLACABACTERIANA='     +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 49  OR @CLASEPLANTILLA=@HCPLANTILLAPARTO
		                  SET @SQL='GESTACION='                  +(CASE WHEN @CLASEPLANTILLA=@HCPLANTILLAPARTO THEN '2' ELSE 'GESTACION' END)
                              +', FECHATENCIONPARTOCESAR='     +(CASE WHEN @CLASEPLANTILLA=@HCPLANTILLAPARTO THEN @FECHA ELSE @TIPO_FECHA END)
	ELSE IF @CAMPO = 50  OR @CLASEPLANTILLA=@HCPLANTILLAPARTO
		                  SET @SQL='GESTACION='                  +(CASE WHEN @CLASEPLANTILLA=@HCPLANTILLAPARTO THEN '2' ELSE 'GESTACION' END)
                              +', FECHASALIDAPARTOCES='        +(CASE WHEN @CLASEPLANTILLA=@HCPLANTILLAPARTO THEN @FECHA ELSE @TIPO_FECHA END)
	ELSE IF @CAMPO = 51  OR @CLASEPLANTILLA=@HCPLANTILLAPARTO
		                  SET @SQL='GESTACION='                  +(CASE WHEN @CLASEPLANTILLA=@HCPLANTILLAPARTO THEN '2' ELSE 'GESTACION' END)
                              +', FECHACONSEJLACMATERNA='      +(CASE WHEN @CLASEPLANTILLA=@HCPLANTILLAPARTO THEN @FECHA ELSE @TIPO_FECHA END)
	ELSE IF @CAMPO = 52  SET @SQL='CONTROLRECIENNACIDO='        +@TIPO_FECHA
	ELSE IF @CAMPO = 53  SET @SQL='PLANIFIFAMILIAR1VEZ='        +@TIPO_FECHA
	ELSE IF @CAMPO = 54  SET @SQL='SUMINISTROMETODOANTICONC='   +@TIPO_NUMERICO
                              +', FECHASUMMETANTICONCEP='      +(CASE WHEN @TIPO_NUMERICO IN ('0','22') THEN '''1800-01-01''' ELSE @FECHA END) 
	ELSE IF @CAMPO = 55  SET @SQL='FECHASUMMETANTICONCEP='      +@TIPO_FECHA 
	ELSE IF @CAMPO = 56  SET @SQL='CONTROLPRENAT1VEZ='          +@TIPO_FECHA
	ELSE IF @CAMPO = 57  SET @SQL='CONTROLPRENATAL='            +@TIPO_NUMERICO
		                  --SET @SQL='CONTROLPRENATAL='            +@TIPO_FECHA
	ELSE IF @CAMPO = 58  SET @SQL='ULTIMOCONTROLPRENATAL='      +@TIPO_FECHA
	ELSE IF @CAMPO = 59  SET @SQL='SUMINACIFOLICOULTCONTPRENAT='+@TIPO_NUMERICO 
	ELSE IF @CAMPO = 60  SET @SQL='SUMSULFFERROSOULTCONTPREN='  +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 61  SET @SQL='SUMCARBCALCIO='              +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 62  SET @SQL='VALAGUDEZAVISUAL='           +@TIPO_FECHA
	ELSE IF @CAMPO = 63  SET @SQL='CONSULTOFALMOLOGIA='         +@TIPO_FECHA
	ELSE IF @CAMPO = 64  OR EXISTS (SELECT * FROM TGEN WHERE TABLA='HCAPLANTILLA' AND CAMPO='NUTRICION' AND CODIGO=@CLASEPLANTILLA)
                        SET @SQL='FECHADXDESNUT='              +(CASE WHEN (SELECT COUNT(1) FROM HCA WHERE HCA.IDDX IN ('E43X','E440','E441','E45X','E46X') AND CONSECUTIVO=COALESCE(@CONSECUTIVO,''))>=1 THEN @FECHA ELSE '''1845-01-01''' END)
	ELSE IF @CAMPO = 65  SET @SQL='CONSMUJMENORVICMALTRATO='    +@TIPO_FECHA
	ELSE IF @CAMPO = 66  SET @SQL='CONSVICTVIOSEXUAL='          +@TIPO_FECHA
	ELSE IF @CAMPO = 67  SET @SQL='CONSNUTRICION='              +@TIPO_FECHA
    ELSE IF @CAMPO = 68  SET @SQL='CONSULTAPSICOLOGIA='         +@TIPO_FECHA
	ELSE IF @CAMPO = 69  SET @SQL='CONSCRECYDESA1VEZ='          +@TIPO_FECHA
	ELSE IF @CAMPO = 70  SET @SQL='SULFERROSOMENOR10='          +@TIPO_NUMERICO  
	ELSE IF @CAMPO = 71  SET @SQL='VITAMINAAMENOR10='           +@TIPO_NUMERICO  
    ELSE IF @CAMPO = 72  SET @SQL='CONSJOVEN1VEZ='              +@TIPO_FECHA
	ELSE IF @CAMPO = 73  SET @SQL='CONSADULTA1VEZ='              +@TIPO_FECHA
	ELSE IF @CAMPO = 74  SET @SQL='PRESERVITS='                 +@TIPO_NUMERICO
    ELSE IF @CAMPO = 75  SET @SQL='ASEPRETESTVIH='              +@TIPO_FECHA
	ELSE IF @CAMPO = 76  SET @SQL='ASEPSTELISAVIH='             +@TIPO_FECHA--+', IPSBACAF='+''''+@ALFANUMERICO+''''
	ELSE IF @CAMPO = 77  SET @SQL='DXANSIEDAD='                 +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 78  SET @SQL='FECHAANTIGHEPAB='            +@TIPO_FECHA
	ELSE IF @CAMPO = 79  SET @SQL='RESANTGHEPBDEST='            +@TIPO_NUMERICO
                              +', FECHAANTIGHEPAB='            +(CASE WHEN @TIPO_NUMERICO IN ('0','21') THEN 'FECHAANTIGHEPAB' ELSE @FECHA END)
	ELSE IF @CAMPO = 80  SET @SQL='FECSEROLOGSIFILIS='          +@TIPO_FECHA
	ELSE IF @CAMPO = 81  SET @SQL='RESSERSIF='                  +''''+@ALFANUMERICO+''''
                              +', FECSEROLOGSIFILIS='          +(CASE WHEN @TIPO_NUMERICO IN ('0','21') THEN 'FECSEROLOGSIFILIS' ELSE @FECHA END)
	ELSE IF @CAMPO = 82  SET @SQL='FECTOMAELISAVIH='            +@TIPO_FECHA
	ELSE IF @CAMPO = 83  SET @SQL='RESELISAVIH='                +''''+@ALFANUMERICO+''''
                              +', FECTOMAELISAVIH='            +(CASE WHEN @TIPO_NUMERICO IN ('0','21') THEN 'FECTOMAELISAVIH' ELSE @FECHA END)
	ELSE IF @CAMPO = 84  OR @CLASEPLANTILLA=@HCPLANTILLAPARTO
                        SET @SQL='FECTSHNEO='                  +(CASE WHEN @CLASEPLANTILLA=@HCPLANTILLAPARTO THEN @FECHA ELSE @TIPO_FECHA END)
	ELSE IF @CAMPO = 85  SET @SQL='RESTSHNEO='                  +@TIPO_NUMERICO
                              +', FECTSHNEO='                  +(CASE WHEN @TIPO_NUMERICO IN ('0','21') THEN 'FECTSHNEO' ELSE @FECHA END)
	ELSE IF @CAMPO = 86  SET @SQL='TAMISCANCERCUELLO='          +@TIPO_NUMERICO
    ELSE IF @CAMPO = 87  SET @SQL='CITOLCERVUTER='              +@TIPO_FECHA
	ELSE IF @CAMPO = 88  SET @SQL='CITOBETHESDA='               +@TIPO_NUMERICO
                              +', CITOLCERVUTER='              +(CASE WHEN @TIPO_NUMERICO IN ('0','21') THEN 'CITOLCERVUTER' ELSE @FECHA END)
	ELSE IF @CAMPO = 89  SET @SQL='CALIDADMUESTRACITO='         +@TIPO_NUMERICO
    ELSE IF @CAMPO = 90  SET @SQL='IPSCITO='                    +''''+@ALFANUMERICO+''''
	ELSE IF @CAMPO = 91  SET @SQL='FECCOLPOSCOPIA='             +@TIPO_FECHA
	ELSE IF @CAMPO = 92  SET @SQL='IPSCOLPOSCOPIA='             +''''+@ALFANUMERICO+''''
	ELSE IF @CAMPO = 93  SET @SQL='FECBIOPSIACERVICAL='         +@TIPO_FECHA
	ELSE IF @CAMPO = 94  SET @SQL='RESBIOPSIACERVICAL='         +@TIPO_NUMERICO 
                              +', FECBIOPSIACERVICAL='         +(CASE WHEN @TIPO_NUMERICO IN ('0','999') THEN 'FECBIOPSIACERVICAL' ELSE @FECHA END)
	ELSE IF @CAMPO = 95  SET @SQL='IPSBIOPSIACERVIAL='          +''''+@ALFANUMERICO+''''
	ELSE IF @CAMPO = 96  SET @SQL='FECMAMOGRAFI='               +@TIPO_FECHA
	ELSE IF @CAMPO = 97  SET @SQL='RESMAMOGRAFIA='              +@TIPO_NUMERICO 
                              +', FECMAMOGRAFI='               +(CASE WHEN @TIPO_NUMERICO IN ('0','999') THEN 'FECMAMOGRAFI' ELSE @FECHA END)
	ELSE IF @CAMPO = 98  SET @SQL='IPSMAMOGRAFIA='              +''''+@ALFANUMERICO+''''
	ELSE IF @CAMPO = 99  SET @SQL='FECTOMABACAF='               +@TIPO_FECHA
	ELSE IF @CAMPO = 100 SET @SQL='FECRESULTBACAF='             +@TIPO_FECHA
	ELSE IF @CAMPO = 101 SET @SQL='BIOPSIABACAF='               +@TIPO_NUMERICO 
                              +', FECRESULTBACAF='             +(CASE WHEN @TIPO_NUMERICO IN ('0','999') THEN 'FECRESULTBACAF' ELSE @FECHA END)
	ELSE IF @CAMPO = 102 SET @SQL='IPSBACAF='                   +''''+@ALFANUMERICO+''''
	ELSE IF @CAMPO = 103 SET @SQL='FECTOMAHEMOGLOBINA='         +@TIPO_FECHA
	ELSE IF @CAMPO = 104 SET @SQL='HEMOGLOBINA='                +@TIPO_DECIMAL
                              +', FECTOMAHEMOGLOBINA='         +(CASE WHEN @TIPO_DECIMAL IN ('0.00','999.00') THEN 'FECTOMAHEMOGLOBINA' ELSE @FECHA END)
	ELSE IF @CAMPO = 105 SET @SQL='FECTOMAGLICEMIABASAL='       +@TIPO_FECHA
	ELSE IF @CAMPO = 106 SET @SQL='FECCREATININA='              +@TIPO_FECHA
	ELSE IF @CAMPO = 107 SET @SQL='CREATININA='                 +@TIPO_DECIMAL
                              +', FECCREATININA='              +(CASE WHEN @TIPO_DECIMAL IN ('0.00','999.00') THEN 'FECCREATININA' ELSE @FECHA END)
	ELSE IF @CAMPO = 108 SET @SQL='FECHEMOGLICOSILADA='         +@TIPO_FECHA
	ELSE IF @CAMPO = 109 SET @SQL='HEMOGLOBINAGLICOSILADA='     +@TIPO_DECIMAL
                              +', FECHEMOGLICOSILADA='         +(CASE WHEN @TIPO_DECIMAL IN ('0.00','999.00') THEN 'FECHEMOGLICOSILADA' ELSE @FECHA END)
	ELSE IF @CAMPO = 110 SET @SQL='FECTOMAMICROALBUMINA='       +@TIPO_FECHA
	ELSE IF @CAMPO = 111 SET @SQL='FECTOMAHDL='                 +@TIPO_FECHA
	ELSE IF @CAMPO = 112 SET @SQL='FECTOMABACILODX='            +@TIPO_FECHA
	ELSE IF @CAMPO = 113 SET @SQL='BACILOSCOPIADEDX='           +@TIPO_NUMERICO 
                              +', FECTOMABACILODX='         +(CASE WHEN @TIPO_NUMERICO IN ('4','22') THEN 'FECTOMABACILODX' ELSE @FECHA END)
	ELSE IF @CAMPO = 114 SET @SQL='TRATHIPOTIROIDISMOCONGE='    +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 115 SET @SQL='TRATSIFILISGEST='            +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 116 SET @SQL='TRATSIFILISCONG='            +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 117 SET @SQL='TRATLEPRA='                  +@TIPO_NUMERICO 
	ELSE IF @CAMPO = 118 SET @SQL='FECTERMTRATLESHMANIASIS='    +@TIPO_FECHA

    --Creo Script dinamico
    IF ISNULL(LEN(@SQL),0)>=5
    BEGIN
       SET @SQL='UPDATE RESAFI4505 SET '+@SQL+' WHERE IDRESAFI4505='+CONVERT(VARCHAR,@ID)      
       --Ejecuto Script Dinamico
       --IF @CONSECUTIVO IS NOT NULL
       --BEGIN
         PRINT '
CAMPO='+@CAMPO+', TIPOCAMPO='+@TIPOCAMPO+', VALOR='+@ALFANUMERICO+' , SI ES FECHA'+@TIPO_FECHA
         PRINT @SQL
         EXEC (@SQL)
      --END
    END
    ELSE
       SET @SQL = NULL
END



