IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPQ_CONFIRMASAL_CM' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPQ_CONFIRMASAL_CM
END
GO
CREATE PROCEDURE DBO.SPQ_CONFIRMASAL_CM
@CNSMOV   VARCHAR(20),
@USUARIO  VARCHAR(12),
@SEDE     VARCHAR(5),
@SYS_COMPUTERNAME VARCHAR(50),
@PROCESO  VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @IDBODEGA VARCHAR(20), @ESTRANSITO SMALLINT, @CNSITRA VARCHAR(20), @CNSIZSOL VARCHAR(20), @SECONTABILIZA BIT=0,
		@COMPANIA VARCHAR(2),
		@DEV_CNSMOV VARCHAR(20),
		@NOLOTE VARCHAR(20),
		@NOLOTEPEDIDO VARCHAR(20),
		@IDARTICULO VARCHAR(20),
		@NOADMISION VARCHAR(16),
		@IDSERVICIO VARCHAR(16),
		@CLASEIZSDOL VARCHAR(16),
		@SECTOR VARCHAR(6),
		@CANTIZSOLDENTREGADO INT,
		@CANTIZSOLDTOTAL INT,
		@CANTIDADSOL DECIMAL(14,2),
		@VLR_UNITARIO DECIMAL(14,2),
      @IDTERCEROCA VARCHAR(20),
      @IDPLANCA    VARCHAR(6)
DECLARE @HOY DATETIME=CONVERT(SMALLDATETIME,GETDATE())
BEGIN

	SELECT 
        @ESTRANSITO=ITMO.GENTRANSITO,          
	    @IDBODEGA  =IMOV.IDBODEGA,
        @CNSIZSOL  =IMOV.NODOCUMENTO,
        @SECONTABILIZA = IIF(ISNULL(IBOD.NOCONTABILIZA,0)=1,0,ISNULL(ITMO.SECONTABILIZA,0))
	FROM   IMOV 
        INNER JOIN ITMO ON IMOV.IDTIPOMOV = ITMO.IDTIPOMOV
        INNER JOIN IBOD ON IBOD.IDBODEGA = IMOV.IDBODEGA
	WHERE  IMOV.CNSMOV=@CNSMOV
    IF EXISTS (SELECT 1 FROM IZSOLD INNER JOIN IZSOLDT ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD 
	           WHERE IZSOLD.CNSIZSOL=@CNSIZSOL AND IZSOLDT.ESTADO=0)
    BEGIN
        EXEC SPQ_PROCESA_IZSOLDT @CNSIZSOL, @CNSMOV, '01', @SEDE, @USUARIO
    END

	UPDATE IMOVH SET ESTADO = 9 WHERE CNSMOV = @CNSMOV
      
	BEGIN TRAN
		--IDXB  ACTUALIZA EXISTENCIAS
		UPDATE IDXB 
		SET    IDXB.EXISTOTAL  = IDXB.EXISTOTAL - IMOVH.CANTIDAD
		FROM   IDXB INNER JOIN IMOVH ON IDXB.IDARTICULO = IMOVH.IDARTICULO
		WHERE  IDXB.IDBODEGA   = @IDBODEGA 
		AND    IMOVH.CNSMOV    = @CNSMOV
		--IART  ACTUALIZA EXISTENCIAS
		UPDATE IART
		SET    IART.EXISTOTAL  =  IART.EXISTOTAL - IMOVH.CANTIDAD
		FROM   IART INNER JOIN IMOVH ON IART.IDARTICULO = IMOVH.IDARTICULO
		WHERE  IMOVH.CNSMOV    = @CNSMOV
	COMMIT
	UPDATE IMOV SET ESTADO = '1', USUARIOCONF = @USUARIO, FECHACONF = @HOY,
					SECONTABILIZA = @SECONTABILIZA
	WHERE  CNSMOV = @CNSMOV

	IF @ESTRANSITO=1 
	BEGIN
		PRINT 'TRANSITO'
		SET @CNSITRA = SPACE(20)
		EXEC SPK_GENCONSECUTIVO '01', @SEDE, '@ITRA', @CNSITRA OUTPUT
		SELECT @CNSITRA = @SEDE + REPLACE(SPACE(8 - LEN(@CNSITRA))+LTRIM(RTRIM(@CNSITRA)),SPACE(1),0)
		EXEC SPK_INSERTRANSITO @CNSMOV, @CNSITRA
	END

	UPDATE IMOVH SET ESTADO = 1, FECHACONF = @HOY
	WHERE  CNSMOV = @CNSMOV
   
	BEGIN TRY  
	   PRINT 'ACTUALIZA KARDEX'
	   EXEC SPK_ACTUALIZA_KARDEX @CNSMOV
	END TRY  
	BEGIN CATCH  
	    PRINT 'ERROR AL ACTUALIZAR KARDEX'
	END CATCH
	
	IF DBO.FNK_VALORVARIABLE('CONTABIMOV_JOB')='SI'
	BEGIN
		INSERT INTO IMOVC(CNSMOV, USUARIO, SYS_COMPUTERNAME, COMPANIA, SEDE, NROCOMPROBANTE)
		SELECT @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,'01',@SEDE,''  
	END
	ELSE
	BEGIN
		PRINT 'ENVIO A CONTABILIDAD'
		EXEC SPK_NC_CONTAB_INV  @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,'01',@SEDE,''  
		PRINT 'REGRESO DE CONTABILIDAD'
	END
	DECLARE @I INT, @I_TO INT, @IDITAR VARCHAR(2), @IDITARHEMODERIVADOS VARCHAR(20), @CNSIMOH VARCHAR(20)

	SELECT @CLASEIZSDOL=CLASE, @NOADMISION=NOADMISION, @SECTOR=COALESCE(SECTOR,'') FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL

	SELECT @CANTIZSOLDENTREGADO= COUNT(*) FROM IZSOLD WHERE CNSIZSOL=@CNSIZSOL and ESTADO=0
	SELECT @CANTIZSOLDTOTAL= COUNT(*) FROM IZSOLD WHERE CNSIZSOL=@CNSIZSOL
	IF @CANTIZSOLDTOTAL =  @CANTIZSOLDENTREGADO
	BEGIN
		UPDATE IZSOL SET ESTADO=2 WHERE CNSIZSOL=@CNSIZSOL
		SELECT 1 AS CERRADO
	END
	/*IF @CLASEIZSDOL <> 'PROD' AND @CLASEIZSDOL <> 'Consumo'
	BEGIN
		EXEC SPQ_GENCOBRO_INSCENTRAL @CNSMOV, @NOADMISION,@SECTOR,@USUARIO,@SEDE
	END*/

	IF @CLASEIZSDOL='ONCO'
    BEGIN
		DECLARE @CURSOR TABLE (ID INT IDENTITY, IDSERVICIO VARCHAR(20), CANTIDAD VARCHAR(20), IDARTICULO VARCHAR(20))

      SELECT @IDTERCEROCA=IDTERCEROC,@IDPLANCA=@IDPLANCA FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL

		INSERT INTO @CURSOR (IDSERVICIO, CANTIDAD, IDARTICULO)
		SELECT IMOVH.IDSERVICIO, IMOVH.CANTIDAD,IMOVH.IDARTICULO
		FROM IMOVH 
		WHERE CNSMOV=@CNSMOV
  
		SELECT @I=1, @I_TO=MAX(ID) FROM @CURSOR
		WHILE @I <= @I_TO
		BEGIN  
			SELECT @IDARTICULO=IDARTICULO, @IDSERVICIO=IDSERVICIO, @CANTIDADSOL=CANTIDAD FROM @CURSOR WHERE ID=@I

         SELECT TOP 1  @VLR_UNITARIO=ROUND(COALESCE(VALOR,0),-2) 
         FROM SERTOT1
         WHERE IDTERCERO=@IDTERCEROCA
         AND IDPLAN=@IDPLANCA
         AND IDSERVICIO=@IDSERVICIO
         AND FECHAFIN>GETDATE()
         AND FECHAFINFD>GETDATE()
         AND FECHAINI<=GETDATE()
         AND FECHAINIFD<=GETDATE()

			select @NOLOTE= NOLOTE , @NOLOTEPEDIDO=NOLOTEPEDIDO FROM ISAL WHERE IDARTICULO=@IDARTICULO and CNSMOV=@CNSMOV

			INSERT INTO HCATDIMOV (CONSECUTIVOCIT ,CNSMOV ,IDSERVICIO ,IDARTICULO ,NOLOTE ,NOLOTEPEDIDO ,CANTIDAD ,CANT_DEVUELTA ,
								DEV_CNSMOV ,USUARIO ,FECHA_CREA ,ESTADO ,OBSERVACION,VLR_UNITARIO )   
			SELECT  @NOADMISION, @CNSMOV,@IDSERVICIO, @IDARTICULO,@NOLOTE,@NOLOTEPEDIDO,@CANTIDADSOL,0,NULL,@USUARIO,@HOY,0,null,@VLR_UNITARIO
			
			SET @I += 1
			END  
		DELETE @CURSOR 
	END
END



