
SELECT CERRADA, CASE  CERRADA WHEN 0 THEN 'Admitido' WHEN 1 THEN 'AltaAdm' WHEN 2 THEN 'AltaMed' WHEN 3 THEN 'AltaEnf' END ESTADO,
             HADM.TTRIAGE,NOADMISION,FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,AFI.EDAD,
             COALESCE( HADM.DXINGRESO, (SELECT TOP 1 IDDX FROM HCA WHERE NOADMISION=HADM.NOADMISION AND COALESCE(IDDX,'')<>'' AND CLASE='HC' ))DXHC
             ,HADM.DXINGRESO,MDX.DESCRIPCION,HADM.IDPLAN,TER.NIT,TER.RAZONSOCIAL,CIU.NOMBRE,
             HADM.FECHAALTAMED,HADM.VIAINGRESO,CASE  VIAINGRESO WHEN 1 THEN 'URGRENCIAS' ELSE 'REMITIDI' END,HADM.TIPOADM,HTAD.DESCRIPCION
 FROM HADM INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO
           INNER JOIN TER ON HADM.IDTERCERO=TER.IDTERCERO
           INNER JOIN HTAD ON HADM.TIPOADM=HTAD.TIPOADM
           INNER JOIN CIU ON AFI.CIUDAD=CIU.CIUDAD
           LEFT JOIN MDX ON HADM.DXINGRESO=MDX.IDDX
WHERE NOADMISION='0500001625'
WHERE HADM.FECHA>=''
AND HADM.FECHA<''


SELECT CERRADA, * FROM HADM WHERE NOADMISION='0500001662'

           SELECT * FROM HADM


SELECT CASE  CERRADA WHEN 0 THEN 'Admitido' WHEN 1 THEN 'AltaAdm' WHEN 2 THEN 'AltaMed' WHEN 4 THEN 'AltaEnf' END ESTADO,
             HADM.TTRIAGE,NOADMISION,FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,AFI.EDAD,
             HADM.DXINGRESO,MDX.DESCRIPCION,HADM.IDPLAN,TER.NIT,TER.RAZONSOCIAL,CIU.NOMBRE,
             HADM.FECHAALTAMED,HADM.VIAINGRESO,CASE  VIAINGRESO WHEN 1 THEN 'URGRENCIAS' ELSE 'REMITIDI' END,HADM.TIPOADM,HTAD.DESCRIPCION
 FROM HADM INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO
           INNER JOIN TER ON HADM.IDTERCERO=TER.IDTERCERO
           INNER JOIN HTAD ON HADM.TIPOADM=HTAD.TIPOADM
           INNER JOIN CIU ON AFI.CIUDAD=CIU.CIUDAD
           LEFT JOIN MDX ON HADM.DXINGRESO=MDX.IDDX
WHERE HADM.FECHA>= '20240701' 
AND HADM.FECHA< '20240717'