SELECT TOP 10 * FROM API_LOG WHERE USUARIO='STORRES' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"RIPS_COL","METODO":"ENVIAR_RIPS","PARAMETROS":{"ENVIO":"100008","IDTERCERO":"839000495"},"USUARIO":"STORRES"}'