
SELECT * FROM #A WHERE NOT EXISTS(SELECT * FROM SER WHERE SER.IDSERVICIO=#A.IDSERVICIO)

DELETE #A WHERE NOT EXISTS(SELECT * FROM SER WHERE SER.IDSERVICIO=#A.IDSERVICIO)

SELECT  * INTO #B FROM CPPAF WHERE IDSERVICIO='MX140' AND IDPLAN='HGM25'

SELECT DBO.FNK_COLUMNAS_TABLAS('CPPAF')

INSERT INTO CPPAF(IDPLAN, IDSERVICIO, IDAREA, CARENCIA, CUENTAUTILP, USO, FACTOR, MANEJAPRO, MANEJAOMEX, BORRAR, COBRARA, IDTERCEROCA, IDPLANCA, REQAUTORIZACION)
SELECT IDPLAN, #A.IDSERVICIO, IDAREA, CARENCIA, CUENTAUTILP, USO, FACTOR, MANEJAPRO, MANEJAOMEX, BORRAR, COBRARA, IDTERCEROCA, IDPLANCA, REQAUTORIZACION
FROM #A, #B
WHERE #A.IDSERVICIO NOT IN('MX140')
DELETE #A WHERE IDSERVICIO=''



SELECT *
FROM FCXP WHERE CUECREDITO LIKE '%NO%' AND PROCEDENCIA='Compras'

SELECT  * FROM DBO.FNK_FTRE_COLA()

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"CONF_CONTABLE","METODO":"CRUD_SEDES","PARAMETROS":{"DATOS":{"IDSEDE":"25","DESCRIPCION":"SAN FERNANDO PLAZA FARMACIA","DIRECCION":"Cr 43a #1. Local 264 Torre 2","TELEFONOS":"6043222361","CIUDAD":"05001","CIUNOMBRE":"MEDELLIN","RESPONSABLE":null,"NIT":null,"DV":null,"REPRESENTANTELEGAL":"ANDRES MAURICIO RANGEL MARTINE","TIPO_DOC":"CC","NITREP":"91529981","IDMODELODSS":null,"IDTARIFA":null,"NIVELSEDE":1,"NIVELVISTA":1,"ATIENDEOTRASSEDES":false,"LOGO":null,"LINEA":null,"LINEA2":null,"LINEA3":null,"GRANCONT1":null,"GRANCONT2":null,"LEGAL":null,"LEGAL2":null,"LEGAL3":null,"LEGAL4":null,"HOMOLOGO":"25","IDBODEGALOG":null,"IDBODEGACM":null,"IDBODEGA24H":null,"CODHABILITA":"052661110314","IDBODHEMO":null,"IDSGSSS":null,"IPS":true,"MEFARMACIA":false,"EXTRAMURAL":false,"IDBODEGACUSTODIA":null,"DATOS":[],"PROCESO":"Editar","IDSGSS":"052661110314"}},"USUARIO":"JJIMENEZ"}'

SELECT IDSEDE,DESCRIPCION,DIRECCION,TELEFONOS,SED.CIUDAD,CIU.NOMBRE AS CIUNOMBRE,RESPONSABLE,NIT,DV,REPRESENTANTELEGAL,TIPO_DOC,NITREP,IDMODELODSS,IDTARIFA,NIVELSEDE, NIVELVISTA,ATIENDEOTRASSEDES,LOGO,LINEA,LINEA2,LINEA3,GRANCONT1,GRANCONT2,LEGAL,LEGAL2,LEGAL3,LEGAL4,HOMOLOGO,IDBODEGALOG,IDBODEGACM,IDBODEGA24H,CODHABILITA,IDBODHEMO,IDSGSSS,IPS,MEFARMACIA,SED.EXTRAMURAL,SED.IDBODEGACUSTODIA  FROM [dbo].[SED] INNER JOIN CIU ON SED.CIUDAD=CIU.CIUDAD WHERE (SED.IDSEDE LIKE '%%%%' OR  SED.DESCRIPCION LIKE '%%%%') AND 1=1 AND IDSEDE='25'  ORDER BY IDSEDE  ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 

SELECT IDSEDE,FACTE,CNSRESOL,CNSDIANFE, * FROM FTR WHERE N_fACTURA='FVSF1'

UPDATE  FTR SET CNSRESOL='18764093930995',IDFORMATO='06E' WHERE N_fACTURA='FVSF1'

UPDATE  FTR SET FACTE=1 WHERE N_fACTURA='FVSF1'

SELECT * FROM SED WHERE IDSEDE='25'

EXEC SPK_GENERAR_XML_DIAN '2500000006','FV',NULL,0,NULL,NULL,NULL


SELECT * FROM FCJ WHERE N_FACTURAPOS='FVCO3898'

SELECT FACTE, * FROM FNOT WHERE CNSFNOT='0600014671'

SELECT * FROM MCP WHERE ANOMES='202507' AND EXISTS(SELECT * FROM MCH WHERE MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE AND CUENTA='13060501')