SELECT TOP 10 * FROM API_LOG WHERE USUARIO='FRODRIGUEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FTR_PERU","METODO":"NOTIFICA_BOLETAS","PARAMETROS":{"PROCESO":"FRONTEND"},"USUARIO":"FRODRIGUEZ"}'

EXEC SPQ_JSON '{"MODELO":"LISTA_AUT","METODO":"CALCULO_COPA_AUT","PARAMETROS":{"IDAUT":"0100002298"},"USUARIO":"FRODRIGUEZ"}'

 SELECT PPTMOVI.*,*
			FROM AUT 
				INNER JOIN AFI 		ON AUT.IDAFILIADO=AFI.IDAFILIADO
				INNER JOIN PPTMOVI 	ON PPTMOVI.IDTERCERO=AUT.IDTERCEROCA 
									AND PPTMOVI.IDPLAN=AUT.IDPLAN 
									AND AFI.CIUDAD=PPTMOVI.CIUDAD 
									AND AFI.CORREGIMIENTO=PPTMOVI.DISTRITO
			WHERE AUT.IDAUT='0100002298'


         SELECT  PPTMOVI.ID,PPT.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,PPT.IDPLAN,PLN.DESCPLAN,PPTMOVI.CIUDAD,CIU.NOMBRE,PPTMOVI.DISTRITO,TGEN.DESCRIPCION,                       PPTMOVI.VALOR,PPTMOVI.ZONA,PPTMOVI.COPAVAR,PPTMOVI.PRCOPAVAR   FROM [dbo].[PPTMOVI] INNER JOIN  PPT ON PPTMOVI.IDTERCERO=PPT.IDTERCERO AND PPTMOVI.IDPLAN=PPT.IDPLAN INNER JOIN PLN ON PPT.IDPLAN=PLN.IDPLAN  INNER JOIN TER ON PPT.IDTERCERO=TER.IDTERCERO                 INNER JOIN CIU ON PPTMOVI.CIUDAD=CIU.CIUDAD INNER JOIN TGEN ON TGEN.TABLA='CORREGIMIENTOS' AND PPTMOVI.CIUDAD=TGEN.CAMPO AND PPTMOVI.DISTRITO=TGEN.CODIGO  WHERE (PLN.DESCPLAN LIKE '%%%%') AND 1=1   ORDER BY TER.NIT,PPTMOVI.IDPLAN ASC OFFSET (1-1)*20 ROWS  FETCH NEXT 20 ROWS ONLY 



         SELECT  * FROM LING WHERE NOPRESTACION='0100000261'

         SELECT * FROM LORD WHERE NOINGRESO='0100000041'

         SELECT  * FROM 