IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNK_BUSCA_DILUYENTE' AND XTYPE='FN')
BEGIN
   DROP FUNCTION FNK_BUSCA_DILUYENTE
END
GO
CREATE FUNCTION DBO.FNK_BUSCA_DILUYENTE(@JERARQUIA VARCHAR(20),@QMEZCLA DECIMAL(14,2))
RETURNS VARCHAR(20)
AS
BEGIN
   DECLARE @IDSERVICIODEF VARCHAR(20)
   IF (SELECT MAX(EQUICC) FROM SER WHERE IDJERARQUIA=@JERARQUIA)<=@QMEZCLA
   BEGIN 
      SELECT TOP 1 @IDSERVICIODEF= IDSERVICIO FROM SER WHERE IDJERARQUIA=@JERARQUIA  AND  COALESCE(EQUICC,0)<=@QMEZCLA AND ESTADO='Activo' ORDER BY EQUICC DESC
   END
   ELSE
   BEGIN
      SELECT TOP 1 @IDSERVICIODEF= IDSERVICIO FROM SER WHERE IDJERARQUIA=@JERARQUIA  AND COALESCE(EQUICC,0)>=@QMEZCLA AND ESTADO='Activo' ORDER BY EQUICC ASC
   END 
   RETURN @IDSERVICIODEF
END

