IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNK_CALCULA_HORAS_MIN_NOVEDAD' AND XTYPE='FN')
BEGIN
   DROP FUNCTION FNK_CALCULA_HORAS_MIN_NOVEDAD
END
GO
/***************************************************************************************/
CREATE FUNCTION DBO.FNK_CALCULA_HORAS_MIN_NOVEDAD(@DIAS SMALLINT,@HORAS SMALLINT,@DIASNOV SMALLINT,@PROCE VARCHAR(10))
RETURNS SMALLINT
AS
BEGIN
   DECLARE @MINUTOSNOV INT
   DECLARE @MINUTOSDIA INT
   DECLARE @MINUTOST INT
   SELECT @MINUTOSDIA=(@HORAS*60)/@DIAS
   SELECT @MINUTOSNOV=@DIASNOV*@MINUTOSDIA
   IF @PROCE='HORAS'
   BEGIN
      
      
   END

END