CREATE OR ALTER PROCEDURE DBO.SPQ_MPLCOL
@JSON  NVARCHAR(MAX)
WITH   ENCRYPTION
AS
DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
DECLARE @PARAMETROS          NVARCHAR(MAX), @MODELO                  VARCHAR(100),  @METODO         VARCHAR(100), @QUERY            VARCHAR(MAX)
DECLARE @USUARIO             VARCHAR(20),   @MARCO                   VARCHAR(100),  @FILTRO         VARCHAR(250), @ORDEN            VARCHAR(100)
		,@PAGINA              INT,           @FILASXPAG               INT,           @DEFCOLUMNS     BIT,          @NOADMISION       VARCHAR(16)
		,@CONSECUTIVO         VARCHAR(20),   @O_KRYSTALOS             VARCHAR(30),   @T_KRYSTALOS    VARCHAR(20),  @C_KRYSTALOS      VARCHAR(40)
		,@D_KRYSTALOS         VARCHAR(40),   @F_KRYSTALOS             VARCHAR(40),   @VALOR          VARCHAR(120), @A                INT
		,@IDAFILIADO          VARCHAR(20),   @SEXO                    VARCHAR(9),    @CLASEPLANTILLA VARCHAR(8),   @EDADMESES        INT
		,@TIPO_USUARIO        VARCHAR(100),  @CONSECUTIVOCIT          VARCHAR(20),   @IDPLAN		 VARCHAR(20),  @SEGUIMIENTOCOVID BIT = 0
		,@RESTRINGIR_ATENCION BIT=0,         @RESTRINGIR_ATENCION_MSG VARCHAR(1000), @AMBITO         VARCHAR(20)
		,@DEFAULT1            VARCHAR(MAX),  @SECUENCIA               INT
		,@NOMBREAFI           VARCHAR(256),  @TELEFONO                VARCHAR(20),   @FNACIMIENTO    DATE
		,@EDAD	              VARCHAR(20),   @DOCIDAFILIADO           VARCHAR(20),   @NACIONALIDAD   VARCHAR(20)
		,@DIRECCION           VARCHAR(1000), @DEPARTAMENTO            VARCHAR(100),  @PROVINCIA      VARCHAR(200)
		,@DISTRITO            VARCHAR(256),  @PAIS                    VARCHAR(100),  @NOMBRE_MEDICO  VARCHAR(100), @PLANTILLAS       VARCHAR(50)
		,@EDITAFECHA          TINYINT,       @CAMPOPERMANENTE         VARCHAR(20),   @PROCEDENCIA    VARCHAR(5)
		,@EDAD_ANO			  INT,		     @EDAD_MES				  INT,			 @EDAD_DIA		 INT
		,@IDEMEDICA			  VARCHAR(20),   @SYS_ComputerName		  VARCHAR(254),	 @CCOSTO		 VARCHAR(20)
		,@TIPO_CNS			  VARCHAR(50)   ,@ESNOTAACLARATORIA		  BIT
		,@CONSECUTIVOHCA      VARCHAR(20)	,@COPIARDATOANT           BIT = 0
		,@ITEM				  INT			,@CAMPO                   VARCHAR(12)	 ,@TEXTO         VARCHAR(MAX)
		,@IDMEDICO            VARCHAR(20)   ,@SUGERENCIA              VARCHAR(MAX)
		,@VALORLISTA          VARCHAR(256)   ,@CHECKM                  SMALLINT
		,@DESCRIPCION         VARCHAR(2048)
		,@FECHA               DATETIME      ,@HCAENIDPESP             INT            
		,@EDITARHCA           BIT = 0		 ,@IDMEDICOESP             VARCHAR(20)   ,@NUMHC         SMALLINT  
		,@GRUPAL              BIT = 0       ,@CLASEORDEN              VARCHAR(10)    ,@IDPESPECIAL   VARCHAR(5)  
		,@IDTERCEROCA         VARCHAR(100)  ,@IDCONTRATANTE           VARCHAR(20)    ,@PYM           SMALLINT
		,@CLASE			      VARCHAR(10)	,@IDPLAN2		    VARCHAR(20)			 ,@IDAREA2		    VARCHAR(20)
		,@IX				        VARCHAR(20)
      ,@COPIAHC_CUALQUIERMPL VARCHAR(20)	,@CONSECULTRIA   VARCHAR(13) 
		,@CLASE_PLANTILLA_EVOLUCION VARCHAR(20)= dbo.FNK_VALORVARIABLE('HCPLANTILLARED')
		,@EDITANDO BIT = 0
		,@OMCODHEMODERIVADOS VARCHAR(5)=DBO.FNK_VALORVARIABLE('OMCODHEMODERIVADOS')
		,@OMCODLIQUIDOSPARE VARCHAR(5)=DBO.FNK_VALORVARIABLE('OMCODLIQUIDOSPARE')
		,@OMCODNUTRICIONP VARCHAR(5)=DBO.FNK_VALORVARIABLE('OMCODNUTRICIONP')
		,@ESPROGRAMAS SMALLINT

BEGIN
	SET NOCOUNT ON
	SET LANGUAGE Spanish;  
	SET DATEFORMAT dmy
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(20)      '$.USUARIO',
		DEFCOLUMNS     BIT              '$.DEFCOLUMNS',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)
	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @DEFCOLUMNS = DEFCOLUMNS, @USUARIO = USUARIO
	FROM #JSON
	SELECT @SYS_ComputerName = SYS_ComputerName FROM USUSU WHERE USUARIO=@USUARIO
   
	IF @METODO = 'CAMPO_KRYSTALOS'
	BEGIN      
		SELECT 'OK' OK
		
		SELECT @C_KRYSTALOS = C_KRYSTALOS, @D_KRYSTALOS = D_KRYSTALOS, @F_KRYSTALOS = F_KRYSTALOS, 
				@O_KRYSTALOS = O_KRYSTALOS, @T_KRYSTALOS = T_KRYSTALOS, @VALOR       = VALOR
		FROM   OPENJSON(@PARAMETROS)
		WITH   (C_KRYSTALOS      VARCHAR(40)   '$.C_KRYSTALOS',
				D_KRYSTALOS      VARCHAR(40)   '$.D_KRYSTALOS',
				F_KRYSTALOS      VARCHAR(40)   '$.F_KRYSTALOS',
				O_KRYSTALOS      VARCHAR(30)   '$.O_KRYSTALOS',
				T_KRYSTALOS      VARCHAR(20)   '$.T_KRYSTALOS',
				VALOR            VARCHAR(120)  '$.VALOR') 

		SELECT @QUERY = 'SELECT '+@D_KRYSTALOS+' DESCRIPCION FROM '+@T_KRYSTALOS+' WHERE '+ @C_KRYSTALOS+' = '+ @VALOR + ' AND ' + @F_KRYSTALOS
		EXEC(@QUERY)
		RETURN
	END
	IF @METODO = 'CONSULTAR'
	BEGIN
		SELECT 'OK' OK

	  	SELECT
			MPL.CLASEPLANTILLA,DESCPLANTILLA,COMPANIAALTERNA,NIVELFUNCIONARIO,UNICA
			,MPL.ESTADO,PIDEDX,PIDESV,DAALTA,IMPDATOSEGRESO,SEXO,ISNULL(MEDAD,0) MEDAD,EDADINI
			,EDADFIN,MPL.CLASE,AMBITO,PIDEDXR,TEXCLUYENTES,GRAFICA,TITULOX,TITULOY,ENEPICRISIS
			,OM_ENEPICRISIS,TIENEOM,TRAESERVICIOS,TIPOSV,PROGRESIVA,INGUCI,UCI,RESTRINGEVISTA
			,MPL.IDEMEDICA,TIPOESP,M4505,isnull(NOCOPIAOM,0)NOCOPIAOM,DIASREST,MAREA
			,IMPRIMEOM,HURG,MES.DESCRIPCION ESPECIALIDAD
			,ES_EVOLUCION = CASE WHEN MPL.CLASEPLANTILLA=@CLASE_PLANTILLA_EVOLUCION THEN 1 ELSE 0 END
			,ESINICIAL = CASE WHEN EXISTS (SELECT 1 FROM TGEN WHERE TABLA='HC' AND CAMPO='ESINICIAL' AND CODIGO=MPL.CLASEPLANTILLA) THEN 1 ELSE 0 END
			,FECHA = GETDATE()
		FROM MPL --LEFT JOIN MPLXUSU ON MPL.CLASEPLANTILLA=MPLXUSU.CLASEPLANTILLA
			LEFT JOIN MES ON MES.IDEMEDICA=MPL.IDEMEDICA
		WHERE	--(@USUARIO IS NULL OR USUARIO=@USUARIO)
			MPL.ESTADO='ACTIVO'
			-- AND COALESCE(MPL.CLASE,'') IN('HC','NE','FT','TS') 
			AND MPL.CLASEPLANTILLA IN (SELECT CLASEPLANTILLA FROM MPLXUSU WHERE USUARIO=@USUARIO)

		SELECT
			CLASEPLANTILLA ,CAMPO ,SECUENCIA ,DESCCAMPO ,TIPO_CAMPO,DEFAULT1
			,MOBS ,SEXO ,ISNULL(EDADINI,0)EDADINI
			,ISNULL(EDADFIN,0)EDADFIN
			-- ,CASE WHEN TIPO_CAMPO = 'Lista' THEN 1 ELSE ISNULL(REQUERIDO,0) END REQUERIDO
			,ISNULL(REQUERIDO,0) REQUERIDO
			,ISNULL(FORMULA,0)FORMULA
			,ISNULL(CAMPOFORMULA,0) CAMPOFORMULA ,TIPO_NANDA ,IDDXNANDA
			,ENEPICRISIS ,MINREQ ,DEPENDEDE ,DEPENDECAMPO
			,T_KRYSTALOS
			,C_KRYSTALOS
			,D_KRYSTALOS
			,O_KRYSTALOS
			,F_KRYSTALOS
			,QUERY=CASE WHEN ISNULL(T_KRYSTALOS,'')<>'' AND ISNULL(C_KRYSTALOS,'')<>'' AND ISNULL(D_KRYSTALOS,'')<>'' AND OBJECT_ID(T_KRYSTALOS) IS NOT NULL THEN 'SELECT '+C_KRYSTALOS+', '+D_KRYSTALOS +' AS ['+O_KRYSTALOS+'] FROMIN '+T_KRYSTALOS+' WHERE 1=1 '+CASE WHEN ISNULL(F_KRYSTALOS,'')='' THEN '' ELSE 'AND '+F_KRYSTALOS END ELSE '' END
		FROM MPLD
		WHERE ISNULL(ESTADO,'')='Activo'
			--AND (@SECUENCIA IS NULL OR SECUENCIA = @SECUENCIA)
			--AND (@CLASEPLANTILLA IS NULL OR CLASEPLANTILLA = @CLASEPLANTILLA)
		ORDER BY CLASEPLANTILLA,SECUENCIA


		SELECT CLASEPLANTILLA ,CAMPO ,VALORLISTA ,DESCRITO ,ISNULL(VALOR,0) VALOR ,ISNULL(DESCRIPCION,'') DESCRIPCION
		FROM MPLDL

		SELECT 
		CLASEPLANTILLA,
		CODIGOSV,
		REQUERIDO,
		ORDENSV
		FROM MPLSV
		ORDER BY CLASEPLANTILLA, ORDENSV
      
		RETURN
	END
	IF @METODO = 'LISTAR'
	BEGIN
		DECLARE @AZUL AS BIT
		SELECT @IDAFILIADO			= IDAFILIADO               --
				,@CLASEPLANTILLA		= CLASEPLANTILLA
				,@SEGUIMIENTOCOVID	= SEGUIMIENTOCOVID
				,@NOADMISION			= NOADMISION
				,@CONSECUTIVO		= CONSECUTIVO                 --
				,@TIPO_CNS			= COALESCE(TIPO_CNS, 'CIT')
				,@EDITARHCA			= EDITARHCA
				,@AMBITO				= AMBITO                      --
				,@PROCEDENCIA		= PROCEDENCIA
				,@ESNOTAACLARATORIA	= ESNOTAACLARATORIA     --0
				,@CLASE			    = CLASE						--
				,@AZUL			    = AZUL						--
		FROM OPENJSON(@PARAMETROS)
		WITH (
			IDAFILIADO        VARCHAR(20) '$.IDAFILIADO',            -- 
			NOADMISION        VARCHAR(20) '$.NOADMISION',
			CONSECUTIVO		  VARCHAR(20) '$.CONSECUTIVO',           --
			TIPO_CNS		  VARCHAR(10) '$.TIPO_CONSECUTIVO',      --
			CLASEPLANTILLA    VARCHAR(8)  '$.CLASEPLANTILLA',
			SEGUIMIENTOCOVID  BIT		  '$.SEGUIMIENTOCOVID',
			AMBITO            VARCHAR(20) '$.AMBITO',                --
			PROCEDENCIA       VARCHAR(5)  '$.PROCEDENCIA',
			EDITARHCA         BIT	      '$.EDITARHCA',
			ESNOTAACLARATORIA BIT         '$.ESNOTAACLARATORIA',      --
			CLASE			  VARCHAR(10)  '$.CLASE',
			AZUL			  BIT		  '$.CODIGOAZUL'
		)

		PRINT '@TIPO_CNS='+@TIPO_CNS 
		PRINT '@CONSECUTIVO='+@CONSECUTIVO 
		IF @TIPO_CNS = 'CIT' SET @CONSECUTIVOCIT = @CONSECUTIVO
		IF @TIPO_CNS = 'HADM' AND @NOADMISION IS NULL SET @NOADMISION = @CONSECUTIVO

		SELECT @SYS_ComputerName = SYS_ComputerName 
		FROM USUSU WHERE USUARIO = @USUARIO

		SELECT @CCOSTO = CCOSTO 
		FROM UBEQ
		WHERE SYS_ComputerName = @SYS_ComputerName

		IF @NOADMISION IS NOT NULL
		BEGIN
			PRINT '@NOADMISION: '+@NOADMISION
			DECLARE @IDAFILIADO_OLD VARCHAR(20) = @IDAFILIADO
			SELECT @IDAFILIADO = IDAFILIADO FROM HADM WHERE NOADMISION = @NOADMISION

			IF @IDAFILIADO IS NULL SET @IDAFILIADO=@IDAFILIADO_OLD

			IF @RESTRINGIR_ATENCION = 0 AND @CONSECUTIVOCIT IS NULL 
				AND DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
			BEGIN
				IF EXISTS(
					SELECT 1 FROM HADM 
					WHERE NOADMISION = @NOADMISION 
					AND HADM.IDPLAN IN ('PAQ027','PAQ028')
				)
				BEGIN
					SET @RESTRINGIR_ATENCION = 1
					SET @RESTRINGIR_ATENCION_MSG = 'Esta admisión solo puede ser atendida mediante cita, no por admisiones'
				END
			END
		END
		
		DECLARE @MPL AS TABLE(
			ITEM INT IDENTITY(1,1),
			CLASEPLANTILLA VARCHAR(100), DESCPLANTILLA VARCHAR(1000),
			TIENEOM SMALLINT,
			PIDEDX SMALLINT,
			PIDEDXR SMALLINT,
			PIDESV SMALLINT,
			GRUPAL BIT DEFAULT 0,
			UNICA BIT DEFAULT 0,
			IDAREA VARCHAR(20),
			IDPLAN VARCHAR(20),
			HURG INT
		)

		SELECT @IDAFILIADO = DBO.FNK_LIMPIATEXTO(@IDAFILIADO, '0-9A-Z.,-')
		PRINT '@IDAFILIADO		='+COALESCE(@IDAFILIADO,'')
		SELECT TOP 1 @SEXO = SEXO, @FNACIMIENTO = FNACIMIENTO 
		FROM DBO.AFI WHERE IDAFILIADO = @IDAFILIADO

		SELECT @TIPO_USUARIO = m.TIPO_USUARIO, @IDEMEDICA = m.IDEMEDICA
		FROM MED m INNER JOIN USUSU u ON u.IDMEDICO = m.IDMEDICO AND USUARIO=@USUARIO

		SELECT @EDAD_ANO = ANO FROM DBO.FNK_EDAD_ANO_MES_DIA(@FNACIMIENTO,GETDATE())
		SELECT @EDAD_DIA = DATEDIFF(DAY, @FNACIMIENTO, GETDATE())
		SELECT @EDAD_MES = DATEDIFF(MONTH, @FNACIMIENTO, GETDATE())

		IF @EDAD_ANO IS NULL SELECT @EDAD_ANO = 0
		IF @EDAD_DIA IS NULL SELECT @EDAD_DIA = 0
		IF @EDAD_MES IS NULL SELECT @EDAD_MES = 0

		SELECT @ESNOTAACLARATORIA = COALESCE(@ESNOTAACLARATORIA,0)

		IF @TIPO_CNS IN ('GESTIONES','GESTADVA','GESTION','GESTSER') SELECT @AMBITO = 'GS'

		print '@TIPO_CNS    ='+@TIPO_CNS+' // @CLASEPLANTILLA='+ coalesce(@claseplantilla,'')
		print '@CONSECUTIVO ='+COALESCE(@CONSECUTIVO,'')
		PRINT '@AMBITO      ='+COALESCE(@AMBITO,'')+'//@SEXO='+COALESCE(@SEXO,'')
		PRINT '@IDEMEDICA   ='+coalesce(@IDEMEDICA,'')+'//@ESNOTAACLARATORIA='+convert(varchar,coalesce(@ESNOTAACLARATORIA,0))
		PRINT '@EDAD_ANO    ='+convert(varchar,coalesce(@EDAD_ANO,0))
		PRINT '@EDAD_DIA    ='+convert(varchar,coalesce(@EDAD_DIA,0))
		PRINT '@EDAD_MES    ='+convert(varchar,coalesce(@EDAD_MES,0))
		PRINT '@SEXO        ='+@SEXO

--		UPDATE MPL SET HURG=4 WHERE CLASEPLANTILLA='cazul'
		INSERT INTO @MPL(CLASEPLANTILLA,DESCPLANTILLA, TIENEOM, PIDEDX, PIDEDXR, PIDESV, GRUPAL, UNICA, IDAREA, IDPLAN, HURG)
		SELECT MPL.CLASEPLANTILLA, MPL.DESCPLANTILLA, MPL.TIENEOM, MPL.PIDEDX, MPL.PIDEDXR, PIDESV, MPL.GRUPAL, UNICA,NULL,NULL, COALESCE(MPL.HURG, 0)
		FROM	 DBO.MPL INNER JOIN	DBO.MPLXUSU ON	MPL.CLASEPLANTILLA = MPLXUSU.CLASEPLANTILLA
															AND MPLXUSU.USUARIO    = @USUARIO
							INNER JOIN  USUSU ON USUSU.USUARIO = @USUARIO
							LEFT JOIN  MED   ON MED.IDMEDICO  = USUSU.IDMEDICO 
		WHERE MPL.ESTADO='Activo' 
		AND   (@CLASEPLANTILLA IS NULL OR MPL.CLASEPLANTILLA = @CLASEPLANTILLA)		
		AND   (@AZUL IS NULL OR COALESCE(MPL.HURG,0) = 4)		
		AND   (@AMBITO   IS NULL OR AMBITO	= @AMBITO)
		AND   (@CLASE    IS NULL OR CLASE	= @CLASE)
		AND   (COALESCE(MPL.SEXO, 'Ambos') = 'Ambos' OR COALESCE(mpl.sexo, 'Ambos') = @SEXO)
		AND   COALESCE(MPL.IDEMEDICA, '') IN ('', @IDEMEDICA)
		AND   COALESCE(MPL.ESNOTA_ACLARA,0) = @ESNOTAACLARATORIA
		--AND  (COALESCE(MPL.MAREA, 0) = 0 OR COALESCE(@CCOSTO, '') = '' OR @CCOSTO IN (SELECT CODIGO FROM TGEN WHERE TABLA='MPL_CCOSTO' AND CAMPO = MPL.CLASEPLANTILLA))
		--Ecluir mpl de epi
		AND   MPL.CLASEPLANTILLA NOT IN (SELECT COALESCE(DATO,'') FROM USVGS WHERE IDVARIABLE LIKE '%HCPLANTILLAEPI%')
		-- Validar por la Edad Inicial del Paciente
		AND COALESCE(MPL.EDADINI,0) <= (
			CASE WHEN COALESCE(MPL.MEDAD,0)=1 THEN (
				CASE COALESCE(MPL.TEDAD,'M') 
				WHEN 'A' THEN @EDAD_ANO
				WHEN 'D' THEN @EDAD_DIA 
				ELSE @EDAD_MES END) 
			ELSE 99999999 END)

		---- Validar por la Edad Final del Paciente
		AND COALESCE(MPL.EDADFIN,0)>=(
			CASE WHEN COALESCE(MPL.MEDAD,0)=1 
			THEN (
				CASE COALESCE(MPL.TEDAD,'M') 
				WHEN 'A' THEN @EDAD_ANO 
				WHEN 'D' THEN @EDAD_DIA
				ELSE @EDAD_MES END
			) ELSE 0 END)

		
		IF @AMBITO = 'CE'
		BEGIN
			SELECT @PYM = 0

			IF @TIPO_CNS = 'CIT'
				AND @CONSECUTIVO <> ''
			BEGIN
				SELECT @IDCONTRATANTE = IDCONTRATANTE
					,@CLASEORDEN = CLASEORDEN
					,@IDPESPECIAL = IDPESPECIAL
				FROM CIT
				WHERE CONSECUTIVO = @CONSECUTIVOCIT

				SELECT @PYM = PYM
				FROM TER
				WHERE IDTERCERO = @IDCONTRATANTE

				SELECT @IDEMEDICA = MED.IDEMEDICA
				FROM CIT
				INNER JOIN MED ON CIT.IDMEDICO = MED.IDMEDICO
				WHERE CIT.CONSECUTIVO = @CONSECUTIVOCIT
			END

			SELECT @NUMHC = COUNT(*)
			FROM HCA
			WHERE CONSECUTIVOCIT = @CONSECUTIVOCIT

			

			IF @PYM = 1 --AND @CLASEORDEN='PyP'--es CE y el tercero de la cita maneja PYM
			BEGIN
				PRINT 'ES PYM'

				DELETE
				FROM @MPL
				WHERE CLASEPLANTILLA IN (
						SELECT CLASEPLANTILLA
						FROM MPL
						WHERE MPL.IDEMEDICA <> @IDEMEDICA
							AND COALESCE(MPL.IDEMEDICA, '') <> ''
						)

				IF @CLASEORDEN = 'PyP' --LA CITA ES CLASE PYP
				BEGIN
					PRINT '@CLASEORDEN=' + @CLASEORDEN

					--SABER SI YA TIENE UNA INICIAL EN ESTE PROGRAMA DE PYM
					SELECT @HCAENIDPESP = COUNT(*)
					FROM HCA
					INNER JOIN MPL ON HCA.CLASEPLANTILLA = MPL.CLASEPLANTILLA
					WHERE IDAFILIADO = @IDAFILIADO
						AND EXISTS (
							SELECT *
							FROM TGEN
							WHERE TABLA = 'HC_PYP'
								AND CODIGO = @IDPESPECIAL
								AND CAMPO = HCA.CLASEPLANTILLA
							)
						AND MPL.TIPOESP = 'I'
						AND MPL.IDEMEDICA = @IDEMEDICA
						AND COALESCE(MPL.IDEMEDICA, '') <> ''
						AND COALESCE(HCA.ANULADA, 0) = 0

					PRINT '@HCAENIDPESP: ' + CONVERT(VARCHAR, @HCAENIDPESP)
					
					

					IF @NUMHC = 0 --ES LA PRIMERA HC DE ESTA CITA 
					BEGIN
						
						----------------------------------------------------------------------------
						-- EZ 30/05/2024 Poder crear HC de morbilidad en Citas PyP Cuando ya fue atendida en PyP (STORRES)
						DELETE
						FROM @MPL
						WHERE CLASEPLANTILLA NOT IN (
								SELECT CLASEPLANTILLA
								FROM MPL
								WHERE EXISTS (
										SELECT *
										FROM TGEN
										WHERE TABLA = 'HC_PYP'
											AND CAMPO = MPL.CLASEPLANTILLA
											AND CODIGO = @IDPESPECIAL
										)
								)
						----------------------------------------------------------------------------
						DELETE
						FROM @MPL
						WHERE CLASEPLANTILLA NOT IN (
								SELECT CLASEPLANTILLA
								FROM MPL
								WHERE EXISTS (
										SELECT *
										FROM TGEN
										WHERE TABLA = 'HC_PYP'
											AND CAMPO = MPL.CLASEPLANTILLA
										)
								)
								
						IF @HCAENIDPESP = 0
						BEGIN
							DELETE
							FROM @MPL
							WHERE CLASEPLANTILLA IN (
									SELECT CLASEPLANTILLA
									FROM MPL
									WHERE EXISTS (
											SELECT *
											FROM TGEN
											WHERE TABLA = 'HC_PYP'
												AND CODIGO = @IDPESPECIAL
												AND CAMPO = MPL.CLASEPLANTILLA
											)
										AND MPL.TIPOESP <> 'I' AND COALESCE(MPL.ESNOTA_ACLARA,0) = 0
									)

						END
						ELSE
						BEGIN
							DELETE
							FROM @MPL
							WHERE CLASEPLANTILLA IN (
									SELECT CLASEPLANTILLA
									FROM MPL
									WHERE EXISTS (
											SELECT *
											FROM TGEN
											WHERE TABLA = 'HC_PYP'
												AND CODIGO = @IDPESPECIAL
												AND CAMPO = MPL.CLASEPLANTILLA
											)
										AND MPL.TIPOESP <> 'E'
									)
						END
					END
					ELSE --NO ES LA PRIMERA HC DE ESTA CITA 
					BEGIN
						DELETE
						FROM @MPL
						WHERE CLASEPLANTILLA IN (
								SELECT CLASEPLANTILLA
								FROM MPL
								WHERE EXISTS (
										SELECT *
										FROM TGEN
										WHERE TABLA = 'HC_PYP'
											AND CAMPO = MPL.CLASEPLANTILLA
										)
								)
					END
				END
				ELSE --MORBILIDAD
				BEGIN

					DELETE
					FROM @MPL
					WHERE CLASEPLANTILLA IN (
							SELECT CLASEPLANTILLA
							FROM MPL
							WHERE EXISTS (
									SELECT *
									FROM TGEN
									WHERE TABLA = 'HC_PYP'
										AND CAMPO = MPL.CLASEPLANTILLA
									)
							)
						AND CLASEPLANTILLA NOT IN (
							SELECT CLASEPLANTILLA
							FROM MPL
							WHERE EXISTS (
									SELECT *
									FROM TGEN
									WHERE TABLA = 'HC_MOR'
										AND CAMPO = MPL.CLASEPLANTILLA
									)
							)
				END
			END
			ELSE
			BEGIN

				IF DBO.FNK_VALORVARIABLE('HCEPI_SIEMPRE') <> 'SI'
				BEGIN
					DELETE
					FROM @MPL
					WHERE CLASEPLANTILLA = (
							SELECT TOP 1 DATO
							FROM USVGS
							WHERE IDVARIABLE = 'HCPLANTILLAEPI'
							)
				END

				IF DBO.FNK_VALORVARIABLE('HC_INGRESO_OBLIGA') = 'SI'  AND @TIPO_CNS<>'URGENCIA' --STORRES
				BEGIN
					IF EXISTS (
							SELECT CLASEPLANTILLA
							FROM MPL
							WHERE TIPOESP = 'I'
								AND CLASEPLANTILLA NOT IN (
									SELECT DISTINCT HCA.CLASEPLANTILLA
									FROM HCA
									INNER JOIN MPL ON MPL.CLASEPLANTILLA = HCA.CLASEPLANTILLA
										AND MPL.TIPOESP = 'I'
									WHERE IDAFILIADO = @IDAFILIADO
										AND COALESCE(HCA.ANULADA, 0) = 0
									)
							)
					BEGIN
						DELETE
						FROM @MPL
						WHERE CLASEPLANTILLA NOT IN (
								SELECT CLASEPLANTILLA
								FROM MPL
								WHERE TIPOESP = 'I'
								)

						IF (
								SELECT COUNT(1)
								FROM @MPL
								) = 0
						BEGIN
							SELECT OK = 'KO'

							SELECT ERROR
							FROM (
								SELECT ERROR = 'Para continuar la atención se debe diligenciar las plantillas marcadas como Inicial. Pero usted no tiene permiso a estas plantillas. Contacte por favor al departamento de tecnología.'
								) AS #T

							RETURN
						END
					END
				END

				IF DBO.FNK_VALORVARIABLE('HC_REVINIPORESP') = 'SI' -- EZ 12/10/2022 JEDM INDICO QUE NO SE USE ESTA VARIABLE POR AHORA
				BEGIN
					DELETE
					FROM @MPL
					WHERE CLASEPLANTILLA NOT IN (
							SELECT CLASEPLANTILLA
							FROM MPL
							INNER JOIN MED ON MED.IDEMEDICA = MPL.IDEMEDICA
							INNER JOIN USUSU ON USUSU.USUARIO = @USUARIO
							WHERE MPL.IDEMEDICA <> MED.IDEMEDICA
								AND COALESCE(MPL.IDEMEDICA, '') <> ''
							)
				END
					
				--SE DEBEN BORRAR LAS PLANTILLAS QUE NO DEBAN ESTAR
				--IF (SELECT COUNT(*) FROM HCA WHERE CONSECUTIVOCIT = @CONSECUTIVOCIT) > 0
				--   DELETE FROM @MPL WHERE CLASEPLANTILLA IN (SELECT CLASEPLANTILLA FROM HCA WHERE CONSECUTIVOCIT = @CONSECUTIVOCIT)
				IF COALESCE(@EDITARHCA, 0) = 1
					SET @RESTRINGIR_ATENCION = 0

				--DECLARE @IDPESPECIAL VARCHAR(20)
				IF COALESCE(@CONSECUTIVOCIT, '') <> ''
				BEGIN
					SELECT @IDPESPECIAL = CASE 
							WHEN CIT.CLASEORDEN = 'PyP'
								THEN CIT.IDPESPECIAL
							ELSE NULL
							END
						,@IDTERCEROCA = IDTERCEROCA
					FROM CIT
					WHERE CONSECUTIVO = @CONSECUTIVOCIT

					

					IF @IDPESPECIAL IS NULL
					BEGIN
						-- Cuando es PYM debe mostrar solo morbilidad
						IF EXISTS (
								SELECT 1
								FROM TER
								WHERE IDTERCERO = @IDTERCEROCA
									AND COALESCE(PYM, 0) = 1
								)
							DELETE
							FROM @MPL
							WHERE CLASEPLANTILLA IN (
									SELECT DATO1
									FROM TGEN
									WHERE TABLA = 'HC_PYP'
									)
					END

					-- Descarto todas las plantillas que ya se han diligenciado en la atención
					DELETE
					FROM @MPL
					WHERE CLASEPLANTILLA IN (
						SELECT CLASEPLANTILLA
						FROM HCA
						WHERE CONSECUTIVOCIT = @CONSECUTIVOCIT
						AND COALESCE(ANULADA, '') = 0
						AND HCA.CLASEPLANTILLA NOT IN ( -- Excluye todas las notas de enfermeria cuando son HCA vinculadas a Citas Oncologias
								SELECT CLASEPLANTILLA 
								FROM MPL 
								WHERE CLASE='NE'
								AND HCA.CONSECUTIVOCIT IN (SELECT CONSECUTIVOCIT FROM HCATDOD) 
							)
						
					)
				END

			

				IF @IDPESPECIAL IS NULL
				BEGIN
					IF @TIPO_USUARIO = 'Medico'
					BEGIN
						PRINT '@RESTRINGIR_ATENCION: ' + CAST(@RESTRINGIR_ATENCION AS VARCHAR)

						IF @RESTRINGIR_ATENCION = 1
							DELETE
							FROM @MPL
							WHERE CLASEPLANTILLA NOT IN (
									'CERTMED'
									,'ORIMED'
									,'AUDITMED'
									,'FORMTMP'
									,'FUAT'
									,'FAT'
									,'COVID-19'
									,'REFCREF'
									,'JUNTAMED'
									,'CATPAC'
									,'NT_ADM01'
									,'FORMED'
									,'COV19A'
									,'COVID19'
									)
					END
				END
				ELSE
				BEGIN
					PRINT 'IDPESPECIAL = ' + @IDPESPECIAL

					IF COALESCE(@CONSECUTIVOCIT, '') <> ''
					BEGIN
						IF EXISTS (
								SELECT 1
								FROM CIT
								WHERE CONSECUTIVO = @CONSECUTIVOCIT
									AND COALESCE(CUMPLIDA,0) IN (0,3)
								)
						BEGIN -- Si la cita aun no ha sido atendida
							DELETE
							FROM @MPL
							WHERE CLASEPLANTILLA NOT IN (
									SELECT CAMPO 
									FROM TGEN
									WHERE TABLA = 'HC_PYP'
										AND CODIGO = @IDPESPECIAL
									)
						END
						ELSE -- La cita ya está cumplida, mostrar solo las de morbilidad que apliquen
						BEGIN
							DELETE
							FROM @MPL
							WHERE CLASEPLANTILLA IN (
									SELECT CAMPO
									FROM TGEN
									WHERE TABLA = 'HC_PYP'
										AND CODIGO = @IDPESPECIAL
									)
						END

						-- Descarto todas las plantillas de evolución si existe aun iniciales por diligenciar
						DELETE
						FROM @MPL
						WHERE CLASEPLANTILLA IN (
								SELECT #T.CLASEPLANTILLA
								FROM @MPL AS #T
								INNER JOIN MPL ON MPL.CLASEPLANTILLA = #T.CLASEPLANTILLA
								WHERE MPL.TIPOESP <> 'I'
									AND EXISTS (
										SELECT 1
										FROM @MPL a
										INNER JOIN MPL b ON a.CLASEPLANTILLA = b.CLASEPLANTILLA
										WHERE TIPOESP = 'I'
										)
								)
					END
				END
			END

			
		END	   

		IF @TIPO_CNS='HADM' AND @CLASEPLANTILLA IS NULL
		BEGIN
			SELECT @IDPLAN = IDPLAN FROM HADM WHERE NOADMISION=@CONSECUTIVO
			SELECT TOP 1 @IDAREA2 = IDAREA FROM HHAB WHERE NOADMISION=@CONSECUTIVO
			IF COALESCE(@IDAREA2,'')=''
			BEGIN
				SELECT @IDAREA2 = IDAREA FROM UBEQ WHERE SYS_ComputerName=@SYS_ComputerName
			END
			DELETE A FROM @MPL A
			WHERE UNICA=1 
				AND EXISTS (SELECT 1 FROM HCA WHERE NOADMISION=@CONSECUTIVO AND HCA.CLASEPLANTILLA=A.CLASEPLANTILLA 
							AND HCA.PROCEDENCIA='QX' AND COALESCE(ANULADA,0)=0 )
		END	
		SELECT 'OK' OK, @CONSECUTIVOCIT AS CONSECUTIVOCIT, @NOADMISION AS NOADMISION, @IDAFILIADO AS IDAFILIADO

		SELECT CLASEPLANTILLA, DESCPLANTILLA, TIENEOM, PIDEDX, PIDEDXR, PIDESV, GRUPAL--,ATENDIDA,IDPESPECIAL,DESCPECIAL
            ,CLASEPLANTILLA value , '('+CLASEPLANTILLA+') - '+ DESCPLANTILLA  label
			,@PROCEDENCIA AS PROCEDENCIA
			,@AMBITO AS AMBITO
			,@IDAREA2 AS IDAREA
			,@IDPLAN AS IDPLAN
			,CAST(@AZUL AS BIT) ESCODIGOAZUL
			,@NOADMISION NOADMISION
			,HURG
		FROM @MPL


		IF @TIPO_USUARIO = 'Medico' AND @RESTRINGIR_ATENCION = 1 
			SELECT COALESCE(@RESTRINGIR_ATENCION_MSG,'Paciente tiene restringida la atención por su estado de admisión') AS INFO

		RETURN
	END
	IF @METODO = 'LISTAR_PYP'
	BEGIN
		SELECT @IDAFILIADO		= IDAFILIADO
			,@CLASEPLANTILLA	= CLASEPLANTILLA
			,@SEGUIMIENTOCOVID	= SEGUIMIENTOCOVID
			,@NOADMISION		= NOADMISION
			,@CONSECUTIVO		= CONSECUTIVO
			,@TIPO_CNS			= COALESCE(TIPO_CNS, 'CIT')
			,@EDITARHCA			= EDITARHCA
			,@AMBITO			= AMBITO
			,@PROCEDENCIA		= PROCEDENCIA
			,@ESNOTAACLARATORIA	= ESNOTAACLARATORIA
		FROM OPENJSON(@PARAMETROS)
		WITH (
			IDAFILIADO        VARCHAR(20) '$.IDAFILIADO', 
			NOADMISION        VARCHAR(20) '$.NOADMISION',
			CONSECUTIVO		   VARCHAR(20) '$.CONSECUTIVO',
			TIPO_CNS		      VARCHAR(20) '$.TIPO_CONSECUTIVO',
			CLASEPLANTILLA    VARCHAR(8)  '$.CLASEPLANTILLA',
			SEGUIMIENTOCOVID  BIT		  '$.SEGUIMIENTOCOVID',
			AMBITO            VARCHAR(20) '$.AMBITO',
			PROCEDENCIA       VARCHAR(5)  '$.PROCEDENCIA',
			EDITARHCA         BIT	      '$.EDITARHCA',
			ESNOTAACLARATORIA BIT         '$.ESNOTAACLARATORIA'
		)

		PRINT '@TIPO_CNS='+@TIPO_CNS

		IF @TIPO_CNS = 'CIT' SET @CONSECUTIVOCIT = @CONSECUTIVO


		SELECT @CCOSTO = CCOSTO 
		FROM UBEQ
		WHERE SYS_ComputerName = @SYS_ComputerName

		DECLARE @MPL1 AS TABLE(
			ITEM INT IDENTITY(1,1),
			CLASEPLANTILLA VARCHAR(100), DESCPLANTILLA VARCHAR(1000),
			TIENEOM SMALLINT,
			PIDEDX SMALLINT,
			PIDEDXR SMALLINT,
			PIDESV SMALLINT,
			GRUPAL BIT DEFAULT 0,
			IDPLAN VARCHAR(20),
			IDAREA VARCHAR(20)
		)

		SELECT @IDAFILIADO = DBO.FNK_LIMPIATEXTO(@IDAFILIADO, '0-9A-Z.,-')

		SELECT TOP 1 @SEXO = SEXO, @FNACIMIENTO = FNACIMIENTO 
		FROM DBO.AFI WHERE IDAFILIADO = @IDAFILIADO
		

		SELECT @TIPO_USUARIO = m.TIPO_USUARIO, @IDEMEDICA = m.IDEMEDICA
		FROM MED m INNER JOIN USUSU u ON u.IDMEDICO = m.IDMEDICO AND USUARIO=@USUARIO

		SELECT @EDAD_ANO = ANO FROM DBO.FNK_EDAD_ANO_MES_DIA(@FNACIMIENTO,GETDATE())
		SELECT @EDAD_DIA = DATEDIFF(DAY, @FNACIMIENTO, GETDATE())
		SELECT @EDAD_MES = DATEDIFF(MONTH, @FNACIMIENTO, GETDATE())

		SELECT @ESNOTAACLARATORIA = COALESCE(@ESNOTAACLARATORIA,0)

		IF @TIPO_CNS IN ('GESTIONES','GESTADVA','GESTION','GESTSER') SELECT @AMBITO = 'GS'

		print '@TIPO_CNS  ='+@TIPO_CNS+' // @CLASEPLANTILLA='+ coalesce(@claseplantilla,'')
		PRINT '@AMBITO    ='+COALESCE(@AMBITO,'')+'//@SEXO='+COALESCE(@SEXO,'')
		PRINT '@IDEMEDICA ='+coalesce(@IDEMEDICA,'')+'//@ESNOTAACLARATORIA='+convert(varchar,coalesce(@ESNOTAACLARATORIA,0))
		PRINT '@EDAD_ANO  ='+convert(varchar,coalesce(@EDAD_ANO,0))
		PRINT '@EDAD_DIA  ='+convert(varchar,coalesce(@EDAD_DIA,0))
		PRINT '@EDAD_MES  ='+convert(varchar,coalesce(@EDAD_MES,0))
		PRINT '@SEXO      ='+@SEXO

		INSERT INTO @MPL1(CLASEPLANTILLA,DESCPLANTILLA, TIENEOM, PIDEDX, PIDEDXR, PIDESV, GRUPAL)
		SELECT MPL.CLASEPLANTILLA, MPL.DESCPLANTILLA, MPL.TIENEOM, MPL.PIDEDX, MPL.PIDEDXR, PIDESV, MPL.GRUPAL
		FROM	 DBO.MPL INNER JOIN	DBO.MPLXUSU ON	MPL.CLASEPLANTILLA = MPLXUSU.CLASEPLANTILLA
															AND MPLXUSU.USUARIO    = @USUARIO
							INNER JOIN  USUSU ON USUSU.USUARIO = @USUARIO
							LEFT JOIN  MED   ON MED.IDMEDICO  = USUSU.IDMEDICO 
		WHERE MPL.ESTADO='Activo' 
		AND   (@CLASEPLANTILLA IS NULL OR MPL.CLASEPLANTILLA = @CLASEPLANTILLA)
		
		AND   (@AMBITO         IS NULL OR AMBITO=@AMBITO)

		AND   (COALESCE(MPL.SEXO, 'Ambos') = 'Ambos' OR COALESCE(mpl.sexo, 'Ambos') = @SEXO)
		AND   COALESCE(MPL.IDEMEDICA, '') IN ('', @IDEMEDICA)
		AND   COALESCE(MPL.ESNOTA_ACLARA,0) = @ESNOTAACLARATORIA
		-- Validar por la Edad Inicial del Paciente
		AND COALESCE(MPL.EDADINI,0) <= (
			CASE WHEN COALESCE(MPL.MEDAD,0)=1 THEN (
				CASE COALESCE(MPL.TEDAD,'M') 
				WHEN 'A' THEN @EDAD_ANO
				WHEN 'D' THEN @EDAD_DIA 
				ELSE @EDAD_MES END) 
			ELSE 99999999 END)
		---- Validar por la Edad Final del Paciente
		AND COALESCE(MPL.EDADFIN,0)>=(
			CASE WHEN COALESCE(MPL.MEDAD,0)=1 THEN (
				CASE COALESCE(MPL.TEDAD,'M') 
				WHEN 'A' THEN @EDAD_ANO 
				WHEN 'D' THEN @EDAD_DIA
				ELSE @EDAD_MES END
			) ELSE 0 END) 


		IF @AMBITO = 'CE'
		BEGIN
			SELECT @PYM = 0
			IF @TIPO_CNS = 'CIT' AND @CONSECUTIVO <> ''
			BEGIN
				SELECT @IDCONTRATANTE = IDCONTRATANTE ,@CLASEORDEN = CLASEORDEN , @IDPESPECIAL = IDPESPECIAL FROM CIT WHERE CONSECUTIVO = @CONSECUTIVOCIT
				SELECT @PYM = PYM FROM TER WHERE IDTERCERO = @IDCONTRATANTE
				SELECT @IDEMEDICA = MED.IDEMEDICA FROM CIT INNER JOIN MED ON CIT.IDMEDICO = MED.IDMEDICO WHERE CIT.CONSECUTIVO = @CONSECUTIVOCIT
			END   
			SELECT @NUMHC = COUNT(*) FROM HCA WHERE CONSECUTIVOCIT = @CONSECUTIVOCIT
			-- es CE y el tercero de la cita maneja PYM
			--IF @PYM = 1 -- EZ 20231222 Sander indica que en atenciones de morbilidad debe tambien hacer las validaciones que se encuentran en este bloque
			BEGIN
				--PRINT 'ES PYM'
				--SE BORRAN LAS DE ESPECIALIDADES DIFERENTES A LA DEL MEDICO DE LA CITA
				DELETE FROM @MPL1 WHERE CLASEPLANTILLA IN (
																	SELECT CLASEPLANTILLA 
																	FROM  MPL 
																	WHERE MPL.IDEMEDICA <> @IDEMEDICA
																	AND COALESCE(MPL.IDEMEDICA, '') <> ''
															)
				-- SE BORRAN LAS QUE NO PERTENEZCAN A PROGRAMAS ESPECIALES
				DELETE FROM @MPL1 WHERE CLASEPLANTILLA NOT IN (
																	SELECT CLASEPLANTILLA
																	FROM   MPL
																	WHERE  EXISTS (SELECT * FROM TGEN WHERE TABLA = 'HC_PYP' AND CAMPO = MPL.CLASEPLANTILLA)
																)
				IF @CLASEORDEN = 'PyP'  --LA CITA ES CLASE PYP
				BEGIN
					--SE BORRAN LAS DEL PROGRAMA ESPECIAL DE LA CITA YA QUE DEBIO SER ATENDIDA EN LA PRIMERA OPCION LISTAR
					DELETE FROM @MPL1 WHERE CLASEPLANTILLA IN (
						SELECT CLASEPLANTILLA
						FROM   MPL
						WHERE  EXISTS (SELECT * FROM TGEN WHERE TABLA = 'HC_PYP' AND CAMPO = MPL.CLASEPLANTILLA AND CODIGO = @IDPESPECIAL)
					)
               AND 1=2 -- EZERPA 20231220 En Asocabildos necesitan diligenciar una plantilla muchas veces y esto la quita del listado
				END
				--SE REVISA en los otros programas donde pertenece el paciente si le toca inicial o evolución
				DECLARE @IDPES VARCHAR(20)


				DECLARE REVIHC_CURSOR CURSOR FOR 
					SELECT  IDPESPECIAL
					FROM    MPE 
					WHERE   (COALESCE(MPE.SEXO, 'Ambos') = 'Ambos' OR COALESCE(MPE.SEXO, 'Ambos') = @SEXO)
					AND     ESTADO='Activo'
					AND     EDADINI<=CASE WHEN TEDAD='Años' THEN @EDAD_ANO WHEN TEDAD='Dias' THEN @EDAD_DIA WHEN TEDAD='Meses' THEN @EDAD_MES  WHEN TEDAD IS NULL THEN  EDADINI ELSE  @EDAD_DIA END
					AND     EDADFIN+1>CASE WHEN TEDAD='Años' THEN @EDAD_ANO WHEN TEDAD='Dias' THEN @EDAD_DIA WHEN TEDAD='Meses' THEN @EDAD_MES  WHEN TEDAD IS NULL THEN  EDADFIN ELSE @EDAD_DIA END
				OPEN REVIHC_CURSOR    
				FETCH NEXT FROM REVIHC_CURSOR    
				INTO @IDPES
				WHILE @@FETCH_STATUS = 0    
				BEGIN 

					--REVISAMOS SI EN ESTA MISMA CITA YA ATENDIO ESTE PROGRAMA
					IF (
							SELECT COUNT(*) 
							FROM   HCA 
							WHERE  HCA.IDAFILIADO = @IDAFILIADO 
							AND    HCA.CONSECUTIVOCIT = @CONSECUTIVOCIT
							AND    COALESCE(HCA.ANULADA,0) = 0
							AND    EXISTS (
								SELECT * 
								FROM TGEN 
								WHERE TABLA = 'HC_PYP' 
								AND CODIGO = @IDPES 
								AND CAMPO = HCA.CLASEPLANTILLA
							)
						) >0
					BEGIN
						
						IF DBO.FNK_VALORVARIABLE('UNA_SOLA_ATEN_PYP')='SI'
						BEGIN
							DELETE FROM @MPL1 
							WHERE CLASEPLANTILLA  IN (SELECT CAMPO FROM TGEN WHERE TABLA = 'HC_PYP' AND CODIGO = @IDPES ) 
						END
						ELSE
							PRINT 'DONATE 07.06.2023 NO SE DEBE BORRAR PLANTILLAS DEL MISMO PROGRAMA ASOCA'
					END                                                            
					ELSE
					BEGIN
						IF (
							SELECT COUNT(*) 
							FROM   HCA INNER JOIN MPL ON HCA.CLASEPLANTILLA = MPL.CLASEPLANTILLA
							WHERE  IDAFILIADO = @IDAFILIADO 
							AND    EXISTS (SELECT * FROM TGEN WHERE TABLA = 'HC_PYP' AND CODIGO = @IDPES AND CAMPO = HCA.CLASEPLANTILLA)
							AND    MPL.TIPOESP = 'I'
							AND    MPL.IDEMEDICA = @IDEMEDICA
								AND    COALESCE(MPL.IDEMEDICA, '') <> ''
							) = 0
						BEGIN
							DELETE FROM @MPL1 WHERE CLASEPLANTILLA  IN (
																		SELECT CLASEPLANTILLA
																		FROM   MPL
																		WHERE  EXISTS (SELECT * FROM TGEN WHERE TABLA = 'HC_PYP' AND CODIGO = @IDPES AND CAMPO = MPL.CLASEPLANTILLA)
																		AND    MPL.TIPOESP <> 'I'
																	)  
						END
						ELSE
						BEGIN
							DELETE FROM @MPL1 WHERE CLASEPLANTILLA  IN (
																		SELECT CLASEPLANTILLA
																		FROM   MPL
																		WHERE  EXISTS (SELECT * FROM TGEN WHERE TABLA = 'HC_PYP' AND CODIGO = @IDPES AND CAMPO = MPL.CLASEPLANTILLA)
																		AND    MPL.TIPOESP <> 'E'
																		)
						END
					END
					FETCH NEXT FROM REVIHC_CURSOR    
						INTO @IDPES
				END
			CLOSE REVIHC_CURSOR
			DEALLOCATE REVIHC_CURSOR
                  
			END
		END
		ELSE
		BEGIN
			DELETE @MPL1 WHERE 1=1
		END

		SELECT 'OK' OK, @CONSECUTIVOCIT AS CONSECUTIVOCIT, @IDAFILIADO AS IDAFILIADO

		--SELECT TOP 1 CCOSTOPYP=CCOSTO FROM CEN WHERE IDAREA=DBO.FNK_VALORVARIABLE('AREA_PYP') 

		SELECT TOP 1 @IDPLAN2=PLN.IDPLAN FROM PPT INNER JOIN PLN ON PLN.IDPLAN = PPT.IDPLAN 
		WHERE  PPT.ESTADO='ACTIVO' 
      AND    PLN.ESTADO='ACTIVO' 
      AND    COALESCE(PLN.RIAS,0)=1
      AND    EXISTS (SELECT * FROM CIT WHERE  CIT.IDTERCEROCA=PPT.IDTERCERO AND CONSECUTIVO=@CONSECUTIVOCIT)
		 --AND 
       

		 SELECT @IDAREA2 = DBO.FNK_VALORVARIABLE('AREA_PYP')

		SELECT CLASEPLANTILLA, DESCPLANTILLA, TIENEOM, PIDEDX, PIDEDXR, PIDESV, GRUPAL,MPE.IDPESPECIAL ,MPE.DESCESPECIAL 
            ,MPL.CLASEPLANTILLA value , '('+MPL.CLASEPLANTILLA+') - '+ MPL.DESCPLANTILLA +' // '+ MPE.DESCESPECIAL label
			,IDPLAN=@IDPLAN2, IDAREA=@IDAREA2
		FROM   @MPL1 MPL INNER JOIN TGEN ON MPL.CLASEPLANTILLA = TGEN.CAMPO
									           AND TGEN.TABLA  = 'HC_PYP'
						INNER JOIN MPE  ON TGEN.CODIGO = MPE.IDPESPECIAL AND MPE.IDPESPECIAL = COALESCE(@IDPESPECIAL,MPE.IDPESPECIAL)     
		AND     MPE.ESTADO='Activo' 
		AND     MPE.EDADINI<=CASE WHEN MPE.TEDAD='Años' THEN @EDAD_ANO WHEN MPE.TEDAD='Dias' THEN @EDAD_DIA WHEN MPE.TEDAD='Meses' THEN @EDAD_MES  WHEN MPE.TEDAD IS NULL THEN  MPE.EDADINI ELSE  @EDAD_DIA END
		AND     MPE.EDADFIN+1>CASE WHEN MPE.TEDAD='Años' THEN @EDAD_ANO WHEN MPE.TEDAD='Dias' THEN @EDAD_DIA WHEN MPE.TEDAD='Meses' THEN @EDAD_MES  WHEN MPE.TEDAD IS NULL THEN  MPE.EDADFIN ELSE @EDAD_DIA END    
		AND   (COALESCE(MPE.SEXO, 'Ambos') = 'Ambos' OR COALESCE(MPE.sexo, 'Ambos') = @SEXO) --filtro de sexo entre programas y sexo
		
		RETURN
	END
	IF @METODO = 'DILIGENCIAR'
	BEGIN
		SELECT @CLASEPLANTILLA = CLASEPLANTILLA, @NOADMISION=NOADMISION, @IDAFILIADO=IDAFILIADO
			,@CONSECUTIVO=CONSECUTIVO
			,@TIPO_CNS = TIPOCONSECUTIVO
			,@CONSECUTIVOHCA = CONSECUTIVOHCA
		FROM OPENJSON(@PARAMETROS)
		WITH (
			CLASEPLANTILLA	VARCHAR(8)  '$.CLASEPLANTILLA',
			IDAFILIADO		VARCHAR(20) '$.IDAFILIADO',
			NOADMISION		VARCHAR(20) '$.NOADMISION',
			CONSECUTIVO		VARCHAR(20) '$.CONSECUTIVO',
			CONSECUTIVOHCA	VARCHAR(20) '$.CONSECUTIVOHCA',
			TIPOCONSECUTIVO VARCHAR(40) '$.TIPOCONSECUTIVO'
		)
		PRINT '@CONSECUTIVOHCA='+@CONSECUTIVOHCA
		SELECT @IDMEDICO = IDMEDICO FROM USUSU WHERE USUARIO=@USUARIO
		SELECT @CCOSTO = CCOSTO, @IDAREA2 = IDAREA FROM UBEQ WHERE SYS_ComputerName=@SYS_ComputerName
--Query2
		IF @TIPO_CNS = 'CIT' --AND DBO.FNK_VALORVARIABLE('SOLO_UNA_HC_CIT')='SI'
		BEGIN
			SET @CONSECUTIVOCIT = @CONSECUTIVO
		
			SELECT @NOADMISION = IIF(@NOADMISION IS NULL, NOADMISION, @NOADMISION) ,@IDAFILIADO = IIF(@IDAFILIADO IS NULL, IDAFILIADO, @IDAFILIADO)
				   ,@ESPROGRAMAS = COALESCE(CIT.ESPROGRAMAS,0)
			FROM CIT WHERE CONSECUTIVO=@CONSECUTIVOCIT


			IF  DBO.FNK_VALORVARIABLE('SOLO_UNA_HC_CIT')='SI'
			BEGIN
				IF EXISTS(SELECT 1 FROM HCA WHERE IDMEDICO=@IDMEDICO AND CONSECUTIVOCIT=@CONSECUTIVOCIT AND CLASEPLANTILLA=@CLASEPLANTILLA AND COALESCE(@CONSECUTIVOHCA,'')='')
				BEGIN
					SELECT OK='KO'
					SELECT ERROR FROM (SELECT ERROR = 'No se permite diligenciar dos veces la misma plantilla en una misma cita') AS #T
					RETURN
				END
			END
		END

		IF @TIPO_CNS ='HADM' AND @NOADMISION IS NULL
			SET @NOADMISION=@CONSECUTIVO

		IF @NOADMISION IS NOT NULL
		BEGIN
			SELECT @IDAFILIADO = IDAFILIADO, @IDPLAN = IDPLAN FROM HADM WHERE NOADMISION=@NOADMISION
			SELECT TOP 1 @IDAREA2=COALESCE(IDAREA,'') FROM HHAB WHERE NOADMISION=@NOADMISION
			IF COALESCE(@IDAREA2,'')=''
				SELECT @IDAREA2 = IDAREA FROM UBEQ WHERE SYS_ComputerName=@SYS_ComputerName
		END

		SELECT @SEXO = SEXO, @EDADMESES = DATEDIFF(DAY,AFI.FNACIMIENTO,DBO.FNK_GETDATE())/30 FROM DBO.AFI WHERE IDAFILIADO = @IDAFILIADO
		
		
		DECLARE @COVID INT = 0 -- 0: No Covid, 1: Automonitoreo, 2: Seguimiento Covid

		SELECT TOP 1 @COVID = AUTOMONITOREO FROM HCSEG INNER JOIN HADM ON HADM.NOADMISION=HCSEG.NOADMISION AND HADM.IDAFILIADO=@IDAFILIADO
		WHERE CONVERT(DATE, GETDATE()) BETWEEN CONVERT(DATETIME,FECHAINI)-1 AND FECHAFIN
		
		SELECT @EDITAFECHA = 0, @FECHA = DBO.FNK_GETDATE()

		DECLARE @TIENE_PERMISO_EDITAR_FECHA AS BIT = 0

		SELECT @TIENE_PERMISO_EDITAR_FECHA = (  SELECT 1
					FROM USUSU
					INNER JOIN USGRUH ON USGRUH.GRUPO = DBO.FNK_DESCIFRAR(USUSU.GRUPO) 
					WHERE USUARIO = @USUARIO AND USGRUH.IDPROCEDIMIENTO ='CONSULTA_EXTERNA_WEB' AND USGRUH.IDCONTROL ='EditaFechaHCA' AND USGRUH.PERMISO = 1 )

		IF @TIENE_PERMISO_EDITAR_FECHA = 1 
			AND @TIPO_CNS != 'HADM' -- 'CIT' -- EZERPA 22.02.2023 A petición del cliente Solidaridad a traves de OSOLANO
		BEGIN
			SELECT @EDITAFECHA = 1, @FECHA = FECHA FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO AND @TIPO_CNS='CIT'
		END

		IF @TIENE_PERMISO_EDITAR_FECHA = 1 
			AND @TIPO_CNS = 'HADM' 
			AND DBO.FNK_VALORVARIABLE('EditaFechaHCA_SOLOCE')!='SI' -- EZ 01.12.2023 A solicitud de Proveemos para cambiar fechas de historias en diferentes dias
		BEGIN
			SELECT @EDITAFECHA = 1
			--, @FECHA = FECHA 
			FROM HADM WHERE NOADMISION = @CONSECUTIVO AND @TIPO_CNS='HADM'
		END
		
		IF COALESCE(@CONSECUTIVOHCA, '')<>''
		BEGIN
			SELECT @FECHA = FECHA FROM HCA WHERE CONSECUTIVO = @CONSECUTIVOHCA
			SELECT @EDITANDO = 1
		END

		IF COALESCE(@CONSECUTIVOHCA, '') <> ''
		BEGIN
			SELECT @FECHA = FECHA, @IDMEDICOESP = IDMEDICOESP, @IDMEDICO = IDMEDICO
				,@GRUPAL = GRUPAL
			FROM HCA 
			WHERE CONSECUTIVO=@CONSECUTIVOHCA
			
			SET @EDITARHCA = 1
		END
		print '@IDAREA='+@IDAREA2
		print '@CCOSTO='+@CCOSTO
		----------------------------------------------------------------------------------------------------------------
      --primer select 
		SELECT 'OK' OK 
      --segunso select
		SELECT MPL.CLASEPLANTILLA,MPL.DESCPLANTILLA,COALESCE(PIDEDX,0)PIDEDX,COALESCE(PIDESV,0)PIDESV,COALESCE(TIPOSV,'')TIPOSV
			,COALESCE(PIDEDXR,0)PIDEDXR,COALESCE(TIENEOM,0) TIENEOM,COALESCE(NOCOPIAOM,0)NOCOPIAOM
			,COALESCE(@COVID,0)COVID
			,FECHA = @FECHA
			,EDITAFECHA = CASE WHEN MPL.AMBITO='QX' AND COALESCE(MPL.TIENEOM,0)=1 THEN 0 ELSE @EDITAFECHA END
			,HABILITA_REVISAESP = CAST(COALESCE(MPL.REVISAESP, 0) AS BIT)
			,IDMEDICOESP = @IDMEDICOESP
			,IDMEDICO = @IDMEDICO
			,MEDICOESP = (SELECT IDMEDICO,NOMBRE
				--,DESCRIPCION AS ESPECIALIDAD 
				FROM MED 
					--INNER JOIN MES ON MES.IDEMEDICA = MED.IDEMEDICA 
				WHERE MED.IDMEDICO=@IDMEDICOESP FOR JSON AUTO)
			,CAST(COALESCE(GRUPAL,0) AS BIT) AS HABILITA_GRUPAL
			,CAST(0 AS BIT) AS GRUPAL
			,COALESCE(IDDX,'') IDDX
			,COALESCE(MPL.HURG,0) HURG
			,CAST(IIF(COALESCE(MPL.HURG,0)=4,1,0) AS BIT) CODAZUL
			,CAST(IIF(MPL.CLASEPLANTILLA=dbo.FNK_VALORVARIABLE('PLANTILLA_ALTAMEDICA') OR COALESCE(MPL.DAALTA,0)=1,1,COALESCE(DAALTA,0)) AS BIT) DAALTA
			, ALTA = CASE WHEN MPL.CLASEPLANTILLA=dbo.FNK_VALORVARIABLE('PLANTILLA_ALTAMEDICA') OR COALESCE(MPL.DAALTA,0)=1 THEN (SELECT IIF(DBO.FNK_VALORVARIABLE('IDMEDICOALTA_BLANCO')='SI', '', COALESCE(A.IDMEDICOTRA,@IDMEDICO)) IDMEDICOTRA
						,A.DXINGRESO, A.DXEGRESO, A.DXSALIDA1, A.DXSALIDA2, A.DXSALIDA3, A.CAUSABMUERTE, A.DESTINO
						,IIF(COALESCE(A.ESTADOPSALIDA,'')='','1',A.ESTADOPSALIDA) ESTADOPSALIDA
						,FECHAALTA = GETDATE(),  FECHASUSPENDE = GETDATE(), CCOSTO_ALTA = IIF(COALESCE(A.CCOSTO_ALTA,'')='',@CCOSTO, A.CCOSTO_ALTA)
						,IDAREA_ALTA = COALESCE(A.IDAREA_ALTA,@IDAREA2)						
						FROM HADM A WHERE NOADMISION=@CONSECUTIVO FOR JSON PATH) ELSE NULL END
		FROM MPL WHERE CLASEPLANTILLA=@CLASEPLANTILLA
		print 'antes de rias'
		SELECT @COPIAHC_CUALQUIERMPL = DBO.FNK_VALORVARIABLE('COPIAHC_CUALQUIERMPL')
      IF @CLASEPLANTILLA IN ('MP_RIAS' ,'PI_RIAS' ,'IN_RIAS')   -- si es plantilla de RIAS ControlPrenatal ,RIAS Primera Infancia
      BEGIN
         PRINT 'ENTRE A RIAS_CONTROLPRENATAL'
         --tercer select
         IF COALESCE(@CONSECUTIVOHCA,'')<>''
            SELECT * FROM RIAS_CONTROLPRENATAL WHERE CONSECUTIVOHCA = @CONSECUTIVOHCA
         ELSE
         BEGIN
            SELECT TOP 1 @CONSECULTRIA = CONSECUTIVO FROM HCA WHERE IDAFILIADO = @IDAFILIADO AND CLASEPLANTILLA = @CLASEPLANTILLA ORDER BY FECHA DESC
            IF COALESCE(@CONSECULTRIA,'') <> ''
            BEGIN
               SELECT * INTO #ANTRIAS FROM RIAS_CONTROLPRENATAL WHERE CONSECUTIVOHCA = @CONSECULTRIA
               UPDATE #ANTRIAS SET MOTIVOCONSULTA = NULL,ENFERMEDADACTUAL = NULL
               ,PROBPARTOFEC          = NULL
               ,PROBPARTOPOR          = NULL   ,PROBPARTOOBS          = NULL  ,OBSERVACIONES         = NULL   ,CABEZACARACUELLO      = NULL
               ,CARDIPULMONAR         = NULL   ,ABDOMINAL             = NULL  ,GENITOURINARIO        = NULL   ,EXTREMIDADES          = NULL
               ,PIELYFANERAS          = NULL   ,SISTEMANERVCENTRAL    = NULL  ,HAB_TRIMESTRE         = NULL   ,HAB_FUMADORACTIVO     = NULL
               ,HAB_FUMADORPASIVO     = NULL   ,HAB_DROGAS            = NULL  ,HAB_ALCOHOL           = NULL   ,HAB_VIOLENCIA         = NULL
               ,HAB_LEVOBJETOSPESADOS = NULL   ,CR_RIESGO             = NULL  ,CR_JUSTIFICACION      = NULL   ,PLANTRATAMIENTO       = NULL
               SELECT * FROM #ANTRIAS
            END
            ELSE
            BEGIN
               SELECT NULL MOTIVODECONSULTA ,NULL ENFERMEDADACTUAL ,NULL FULTMESTRUACION ,NULL GRUPO_SANG ,NULL GRUPO_SANGCONYUGE ,NULL PROBPARTOFEC ,NULL PROBPARTOPOR
                     ,NULL PROBPARTOOBS ,NULL OBSERVACIONES ,NULL CABEZACARACUELLO ,NULL CARDIPULMONAR
                     ,NULL ABDOMINAL ,NULL GENITOURINARIO ,NULL EXTREMIDADES ,NULL PIELYFANERAS ,NULL SISTEMANERVCENTRAL ,NULL HAB_TRIMESTRE ,NULL HAB_FUMADORACTIVO
                     ,NULL HAB_FUMADORPASIVO ,NULL HAB_DROGAS ,NULL HAB_ALCOHOL
                     ,NULL HAB_VIOLENCIA ,NULL HAB_LEVOBJETOSPESADOS ,NULL CR_RIESGO ,NULL CR_JUSTIFICACION ,NULL PLANTRATAMIENTO ,NULL AA_FRECUENCIA ,NULL AA_CANTIDAD ,NULL AA_FORMASPREPARACION
                     ,NULL AA_TIPOSDEALIMENTOS ,NULL AA_ULTIMAS24HORAS ,NULL PRACTICACRIANZA ,NULL CAPACIRECURSOS ,NULL EXPINQUITUDESSALUD ,NULL SITUACIONESRIESGO ,NULL CUELLOGLANDTIROIDEA ,NULL OROFARINGE ,NULL COLUMNA ,NULL VALSALUDSEXUAL
                     ,NULL VALSALUDBUCAL ,NULL DESARROLLOAPRENDIZAJE ,NULL EXAMENOFTALMOSCOPICO
                     ,NULL OI_PUPILAREACTIVA ,NULL OI_PERCEPCOLOR ,NULL OI_VISIONLEJANA ,NULL OI_RESPUESTAMOTORA
                     ,NULL OD_PUPILAREACTIVA ,NULL OD_PERCEPCOLOR ,NULL OD_VISIONLEJANA ,NULL OD_RESPUESTAMOTORA
                     ,NULL VIOLENCIAMALTRATO ,NULL VIOLENCIASEXUAL ,NULL HOSP_ULTIMOSDIAS ,NULL HOSP_MOTIVO
                     ,NULL FECHAPROXCONTROL ,NULL RIT_REALIZADA ,NULL RIT_CULTURALES ,NULL RIT_DESARMONIA_UM
                     ,NULL RIT_QUIENTRATO ,NULL OI_VISIONCERCANA ,NULL OD_VISIONCERCANA ,NULL GOODENOUGHHARRYS
            END
         END         
      END
      ELSE  --las demas plantillas que no son rias
      BEGIN
         --tercer select no son rias
		   SELECT MPLD.CLASEPLANTILLA, MPLD.SECUENCIA, MPLD.CAMPO, MPLD.TIPO_CAMPO, MPLD.DESCCAMPO
				   ,DEFAULT1 = 
					   CASE WHEN @TIPO_CNS='CIT' AND COALESCE(MPLD.NOCOPIA, 0)=0  AND @COPIAHC_CUALQUIERMPL='SI' THEN
						   COALESCE((SELECT TOP 1 
							   CASE TIPOCAMPO
							   WHEN 'Memo' THEN HCAD.MEMO
							   WHEN 'Alfanumerico' THEN HCAD.ALFANUMERICO
							   WHEN 'Numerico' THEN CAST(HCAD.NUMERICO AS VARCHAR)
							   WHEN 'Fecha' THEN IIF(HCAD.FECHA IS NULL, NULL, REPLACE(CONVERT(VARCHAR,HCAD.FECHA,102),'.','-'))
							   WHEN 'Lista' THEN
								   CAST((
								   SELECT TOP 1 VALOR FROM MPLDL 
								   WHERE VALORLISTA=HCAD.ALFANUMERICO
								   AND CLASEPLANTILLA=HCA.CLASEPLANTILLA
								   AND CAMPO=HCAD.CAMPO
								   ) AS VARCHAR)
							   WHEN 'RadioButton' THEN CAST(CAST(HCAD.NUMERICO AS INT) AS VARCHAR)
							   WHEN 'Krystalos' THEN
								   CASE WHEN COALESCE(HCAD.ALFANUMERICO, '')<>'' THEN
									   '{"'+MPLD2.C_KRYSTALOS+'":"'+COALESCE(HCAD.ALFANUMERICO,'')+'","'+MPLD2.D_KRYSTALOS+'":"'+COALESCE(HCAD.MEMO, '')+'"}'
								   ELSE NULL END
							   ELSE NULL END
						   FROM HCAD 
							   INNER JOIN HCA ON HCA.CONSECUTIVO=HCAD.CONSECUTIVO
							   INNER JOIN MPLD AS MPLD2 ON MPLD2.CLASEPLANTILLA=HCA.CLASEPLANTILLA AND MPLD2.CAMPO=HCAD.CAMPO AND MPLD2.SECUENCIA=HCAD.SECUENCIA
						   WHERE HCA.IDAFILIADO=@IDAFILIADO
						   AND TIPOCAMPO IN ('NUMERICO','LISTA','ALFANUMERICO','FECHA','MEMO','RadioButton','Krystalos')
						   AND COALESCE(MPLD.NOCOPIA,0)=0
						   AND HCAD.CAMPO = MPLD.CAMPO
						   AND COALESCE(HCA.ANULADA, 0)=0
						   ORDER BY HCA.FECHA DESC
					   ), MPLD.DEFAULT1)
                  ELSE MPLD.DEFAULT1 
				   END
				   , O_KRYSTALOS
				   ,mpld.C_KRYSTALOS,MPLD.D_KRYSTALOS,MPLD.T_KRYSTALOS
				   ,COALESCE(mpld.F_KRYSTALOS,'')
						   +IIF(MPLD.T_KRYSTALOS='SER' AND COALESCE(MPLD.MPLAN,0)=1,CASE WHEN TRIM(COALESCE(mpld.F_KRYSTALOS,''))<>'' THEN ' AND ' ELSE '' END
							   +' EXISTS (SELECT 1 FROM CPPAF WHERE IDPLAN='''+COALESCE(@IDPLAN,'')+''' AND IDAREA='''+COALESCE(@IDAREA2,'')+''' AND IDSERVICIO=SER.IDSERVICIO)',
							   '') F_KRYSTALOS
				   ,COALESCE(MPLD.REQUERIDO,0) REQUERIDO
				   ,COALESCE(MPLD.CAMPOFORMULA,0) CAMPOFORMULA
				   ,VALOR=NULL
				   ,COALESCE(MINREQ,0) MINREQ
				   ,IDIMAGEN
				   ,CAST(COALESCE(MPLD.IMPHORA,0) AS BIT) IMPHORA
		   INTO	#MPLD
		   FROM	dbo.MPLD
		   WHERE  MPLD.CLASEPLANTILLA =  @CLASEPLANTILLA
		   AND    MPLD.TIPO_CAMPO <> 'Grafica'
		   AND   (MPLD.SEXO  = 'Ambos' OR MPLD.SEXO = @SEXO)
		   AND   (COALESCE(MPLD.EDADINI,0) = 0 OR (COALESCE(MPLD.EDADINI,0) >0 AND @EDADMESES >= COALESCE(MPLD.EDADINI,0)))
		   AND   (COALESCE(MPLD.EDADFIN,0) = 0 OR (COALESCE(MPLD.EDADFIN,0) >0 AND @EDADMESES <= COALESCE(MPLD.EDADFIN,0)))
		   AND   MPLD.ESTADO <> 'Inactivo'
		   AND	  @CLASEPLANTILLA<>@CLASE_PLANTILLA_EVOLUCION
		   UNION ALL		
		   SELECT MPL.CLASEPLANTILLA, ROW_NUMBER() OVER(PARTITION BY HCAD.CLASEPLANTILLA ORDER BY HCAD.CLASEPLANTILLA) SECUENCIA
				   ,HCAD.CAMPO
				   ,'Memo' TIPO_CAMPO
				   ,CASE HCAD.CAMPO WHEN 'EVOLSUB' THEN 'EVOLUCION SUBJETIVA' WHEN 'EVOLUCION'  THEN 'EVOLUCION OBJETIVA'
								   WHEN 'JUSTESTANCIA' THEN 'JUSTIFICACION DE ESTANCIA' WHEN 'RESPARACLINI' THEN 'RESULTADO DE PARACLINICOS'
							   ELSE HCAD.CAMPO
						   END DESCCAMPODESCCAMPO
				   ,DEFAULT1 = COALESCE(HCANT.HISTORIA,'')
				   ,'' O_KRYSTALOS,'' C_KRYSTALOS, '' D_KRYSTALOS, '' T_KRYSTALOS, '' F_KRYSTALOS
				   ,0 REQUERIDO
				   ,0 CAMPOFORMULA
				   ,VALOR = NULL
				   ,0 MINREQ
				   ,NULL IDIMAGEN
				   ,CAST(0 AS BIT) IMPHORA
		   FROM	dbo.MPL
			   INNER JOIN (SELECT @CLASE_PLANTILLA_EVOLUCION CLASEPLANTILLA, * FROM (
									   SELECT '' EVOLSUB, '' EVOLUCION,  '' ANALISIS,  '' RESUMEN, '' JUSTESTANCIA, '' RESPARACLINI
									   ) P UNPIVOT (HISTORIA FOR CAMPO IN (EVOLSUB, EVOLUCION, ANALISIS, RESUMEN, JUSTESTANCIA, RESPARACLINI)
									   ) AS HC
								   ) HCAD ON MPL.CLASEPLANTILLA=HCAD.CLASEPLANTILLA
			   LEFT JOIN (SELECT * FROM (
							   SELECT CAST(HCA.CONSECUTIVO AS varchar(4096)) CONSECUTIVO, CAST(HCA.EVOLSUB AS varchar(4096)) EVOLSUB, CAST(HCA.EVOLUCION AS varchar(4096)) EVOLUCION, 
								   CAST(HCA.ANALISIS AS varchar(4096)) ANALISIS,  CAST(HCA.RESUMEN AS varchar(4096)) RESUMEN, CAST(HCA.JUSTESTANCIA AS varchar(4096)) JUSTESTANCIA, 
								   CAST(HCA.RESPARACLINI AS varchar(4096)) RESPARACLINI
							   FROM HCA
							   WHERE HCA.CONSECUTIVO = @CONSECUTIVOHCA	AND HCA.CLASEPLANTILLA=@CLASE_PLANTILLA_EVOLUCION
							   ) P UNPIVOT (HISTORIA FOR CAMPO IN (EVOLSUB, EVOLUCION, ANALISIS, RESUMEN, JUSTESTANCIA, RESPARACLINI)
							   ) AS HC
						   ) HCANT ON @EDITARHCA=1 AND HCANT.CONSECUTIVO=@CONSECUTIVOHCA AND HCANT.CAMPO=HCAD.CAMPO  --ESTE CARGA EL DETALLE CUANDO SE ESTA EDITANDO LA EVOLUCION
		   WHERE  MPL.CLASEPLANTILLA =  @CLASEPLANTILLA
		   AND	  @CLASEPLANTILLA=@CLASE_PLANTILLA_EVOLUCION AND @TIPO_CNS='HADM'
		   ORDER BY SECUENCIA
      END
		IF EXISTS(SELECT 1 FROM TGEN WHERE TABLA='HC' AND CAMPO='COPIARDATOANT' AND CODIGO = @CLASEPLANTILLA)
			SET @COPIARDATOANT = 1

		IF @COPIARDATOANT = 0 AND @EDITARHCA = 1 
			SET @COPIARDATOANT = 1

			--20/07/2024
      --JEDM BEGIN 2024.10.23
      IF @CLASEPLANTILLA NOT IN ( 'MP_RIAS','PI_RIAS' ,'IN_RIAS')
      BEGIN
		   IF @COPIARDATOANT = 1
		   BEGIN 
			   IF COALESCE(@CONSECUTIVOHCA, '') = ''
			   BEGIN
				   SELECT TOP 1 @CONSECUTIVOHCA=HCA.CONSECUTIVO 
				   FROM HCA 
				   WHERE CLASEPLANTILLA=@CLASEPLANTILLA AND IDAFILIADO=@IDAFILIADO
				   AND COALESCE(ANULADA,0) = 0
				   ORDER BY FECHA DESC

			   END
				
			   IF COALESCE(@CONSECUTIVOHCA,'')<>''
			   BEGIN
				   DECLARE _CURSOR CURSOR FOR   
					   SELECT HCAD.SECUENCIA--, HCAD.TIPOCAMPO,HCAD.ALFANUMERICO,HCAD.FECHA,HCAD.MEMO
					   ,DEFAULT1=CASE TIPOCAMPO
						   WHEN 'Memo' THEN HCAD.MEMO
						   WHEN 'Alfanumerico' THEN HCAD.ALFANUMERICO
						   WHEN 'Numerico' THEN CAST(HCAD.NUMERICO AS VARCHAR)
						   WHEN 'Fecha' THEN IIF(HCAD.FECHA IS NULL, NULL, REPLACE(CONVERT(VARCHAR,HCAD.FECHA,102),'.','-'))-- +' '+CONVERT(VARCHAR,GETDATE(),108)
						   WHEN 'Lista' THEN
							   CAST((
							   SELECT TOP 1 VALOR FROM MPLDL 
							   WHERE VALORLISTA=HCAD.ALFANUMERICO
							   AND CLASEPLANTILLA=HCA.CLASEPLANTILLA
							   AND CAMPO=HCAD.CAMPO
							   ) AS VARCHAR)
						   WHEN 'RadioButton' THEN CAST(CAST(HCAD.NUMERICO AS INT) AS VARCHAR)
						   WHEN 'MultiCheck' THEN (SELECT TOP 1 VALORLISTA FROM HCADL WHERE CONSECUTIVO=HCAD.CONSECUTIVO AND SECUENCIA=HCAD.SECUENCIA AND COALESCE(CHECKM, 0)=1)
						   WHEN 'Krystalos' THEN
							   CASE WHEN COALESCE(HCAD.ALFANUMERICO, '')<>'' THEN
								   '{"'+MPLD.C_KRYSTALOS+'":"'+COALESCE(HCAD.ALFANUMERICO,'')+'","'+MPLD.D_KRYSTALOS+'":"'+COALESCE(HCAD.MEMO, '')+'"}'
							   ELSE NULL END
						   ELSE NULL END
					   FROM HCAD 
					   INNER JOIN HCA ON HCA.CONSECUTIVO=HCAD.CONSECUTIVO
					   INNER JOIN MPLD ON MPLD.CLASEPLANTILLA=HCA.CLASEPLANTILLA
						   AND MPLD.CAMPO=HCAD.CAMPO AND MPLD.SECUENCIA=HCAD.SECUENCIA
					   WHERE HCA.CONSECUTIVO=@CONSECUTIVOHCA
					   AND TIPOCAMPO IN ('NUMERICO','LISTA','ALFANUMERICO','FECHA','MEMO','RadioButton','Krystalos','MultiCheck')
					   AND (COALESCE(MPLD.NOCOPIA,0)=0 OR @EDITARHCA = 1)
				   OPEN _CURSOR  
				   FETCH NEXT FROM _CURSOR INTO @SECUENCIA,@DEFAULT1
					  
				   WHILE @@FETCH_STATUS = 0  
				   BEGIN  
					   print '@DEFAULT1='+coalesce(@DEFAULT1,'')
					   UPDATE #MPLD SET DEFAULT1 = @DEFAULT1 WHERE SECUENCIA=@SECUENCIA
					  
				   FETCH NEXT FROM _CURSOR INTO @SECUENCIA,@DEFAULT1
				   END  
				   CLOSE _CURSOR  
				   DEALLOCATE _CURSOR  

			   END
		   END
		   SELECT @CLASE = CLASE FROM MPL WHERE CLASEPLANTILLA=@CLASEPLANTILLA
		   SELECT * FROM #MPLD ORDER BY #MPLD.SECUENCIA


		   DECLARE @MPLDL AS TABLE (
			   ITEM INT IDENTITY(1,1),
			   [CLASEPLANTILLA] [varchar](8) NOT NULL,
			   [CAMPO] [varchar](12) NOT NULL,
			   [VALORLISTA] [varchar](256) NOT NULL,
			   [DESCRITO] [smallint] NULL,
			   [DATOENLACE] [varchar](20) NULL,
			   [LONGENLACE] [int] NULL,
			   [XPOS] [smallint] NULL,
			   [YPOS] [smallint] NULL,
			   [XNOM] [smallint] NULL,
			   [YNOM] [smallint] NULL,
			   [NUMCAMPOCLARION] [int] NULL,
			   [W] [int] NULL,
			   [H] [int] NULL,
			   [WNOM] [int] NULL,
			   [HNOM] [int] NULL,
			   [NOMNUMCAMPOCLARION] [int] NULL,
			   [BOTNUMCAMPOCLARION] [int] NULL,
			   [WBOT] [int] NULL,
			   [HBOT] [int] NULL,
			   [XBOT] [int] NULL,
			   [YBOT] [int] NULL,
			   [VALOR] [smallint] NULL,
			   [DESCRIPCION] [varchar](2048) NULL,
			   [VALOR1] [varchar](20) NULL,
			   [TIPOCAMPO] [varchar](20) NULL,
			   [CHECK] BIT DEFAULT 0,

			   -- Campos IMAGEN DESCRITA
			   COLOR	VARCHAR(20), 
			   FORMA	VARCHAR(20), 
			   IMGSERIE INT, 
			   TITULOMAPA VARCHAR(20), 
			   TAMANO	INT
		   )


		   INSERT INTO @MPLDL (CLASEPLANTILLA, CAMPO, VALORLISTA, DESCRITO, DATOENLACE, LONGENLACE, XPOS, YPOS, XNOM, YNOM, NUMCAMPOCLARION, W, H, WNOM, HNOM, NOMNUMCAMPOCLARION, BOTNUMCAMPOCLARION, WBOT, HBOT, XBOT, YBOT, VALOR, DESCRIPCION, VALOR1, TIPOCAMPO)
		   SELECT	
			   --ROW_NUMBER() OVER(ORDER BY MPLDL.CAMPO,MPLDL.VALORLISTA,MPLDL.VALOR) AS ITEM,MPLDL.CLASEPLANTILLA, MPLDL.CAMPO, MPLDL.VALORLISTA, MPLDL.DESCRITO, MPLDL.VALOR, MPLDL.DESCRIPCION
		   --INTO	#MPLDL
			   CLASEPLANTILLA, CAMPO, VALORLISTA, DESCRITO, DATOENLACE, LONGENLACE, XPOS, YPOS, XNOM, YNOM, NUMCAMPOCLARION, W, H, WNOM, HNOM, NOMNUMCAMPOCLARION, BOTNUMCAMPOCLARION, WBOT, HBOT, XBOT, YBOT, VALOR, DESCRIPCION, VALOR1, TIPOCAMPO
		   FROM	dbo.MPLDL 
		   WHERE	MPLDL.CLASEPLANTILLA = @CLASEPLANTILLA
		   AND		EXISTS (SELECT * FROM (SELECT MPLD.CLASEPLANTILLA, MPLD.SECUENCIA, MPLD.CAMPO, MPLD.TIPO_CAMPO
									   FROM   dbo.MPLD
									   WHERE  MPLD.CLASEPLANTILLA =  @CLASEPLANTILLA
									   AND    MPLD.TIPO_CAMPO <> 'Grafica'
									   AND   (MPLD.SEXO  = 'Ambos' OR MPLD.SEXO = @SEXO)
									   AND   (COALESCE(MPLD.EDADINI,0) = 0 OR (COALESCE(MPLD.EDADINI,0) >0 AND @EDADMESES >= COALESCE(MPLD.EDADINI,0))) 
									   AND   (COALESCE(MPLD.EDADFIN,0) = 0 OR (COALESCE(MPLD.EDADFIN,0) >0 AND @EDADMESES <= COALESCE(MPLD.EDADFIN,0))) 
									   AND   MPLD.ESTADO <> 'Inactivo') X
						   WHERE  MPLDL.CLASEPLANTILLA = X.CLASEPLANTILLA
						   AND    MPLDL.CAMPO          = X.CAMPO)
		   ORDER BY COALESCE(MPLDL.VALOR,0)

		   INSERT INTO @MPLDL (CLASEPLANTILLA, CAMPO, VALORLISTA, XPOS, YPOS, VALOR, DESCRIPCION, TIPOCAMPO, COLOR, FORMA, IMGSERIE, TITULOMAPA, TAMANO)
		   SELECT CLASEPLANTILLA, CAMPO, HCADL.ITEM, XPOS, YPOS, HCADL.VALORLISTA, HCADL.DESCRIPCION, TIPOCAMPO,
			   HCADL.COLOR, HCADL.FORMA, HCADL.IMGSERIE, HCADL.TITULOMAPA, HCADL.TAMANO
		   FROM HCAD INNER JOIN HCADL ON HCADL.SECUENCIA=HCAD.SECUENCIA AND HCAD.CONSECUTIVO=HCADL.CONSECUTIVO
		   WHERE TIPOCAMPO='ImgDescrita'
		   AND HCAD.CONSECUTIVO=@CONSECUTIVOHCA

		   --ALTER TABLE #MPLDL ADD [CHECK] BIT DEFAULT 0
		   UPDATE @MPLDL SET [CHECK]=0 WHERE [CHECK] IS NULL
		
		   IF @COPIARDATOANT = 1 AND COALESCE(@CONSECUTIVOHCA,'')<>''
		   BEGIN
		
			   PRINT '@CONSECUTIVOHCA =  ' + @CONSECUTIVOHCA
			   DECLARE _CURSOR CURSOR FOR   
				   SELECT ITEM,CAMPO,VALORLISTA FROM @MPLDL
			
			   OPEN _CURSOR  
			   FETCH NEXT FROM _CURSOR INTO @ITEM,@CAMPO,@VALORLISTA
			  
			   WHILE @@FETCH_STATUS = 0  
			   BEGIN  
				   SELECT @CHECKM = CHECKM, @DESCRIPCION = DESCRIPCION 
				   FROM HCADL 
				   WHERE CONSECUTIVO=@CONSECUTIVOHCA
				   AND SECUENCIA = (
					   SELECT TOP 1 SECUENCIA FROM HCAD 
					   WHERE CONSECUTIVO = @CONSECUTIVOHCA
					   AND CAMPO=@CAMPO
				   )
				   AND VALORLISTA=@VALORLISTA

				   IF 1=2
				   PRINT '@CAMPO = ' + COALESCE(@CAMPO, '')
					   +', @VALORLISTA = ' + COALESCE(@VALORLISTA, '')
					   +', @CHECKM = ' + CAST(COALESCE(@CHECKM, 0) AS VARCHAR)
					   +', @DESCRIPCION = ' + COALESCE(@DESCRIPCION, '')

				   UPDATE @MPLDL SET 
					   [CHECK] = COALESCE(@CHECKM, 0)
					   ,DESCRIPCION=COALESCE(@DESCRIPCION, '')
				   WHERE ITEM = @ITEM

				   FETCH NEXT FROM _CURSOR INTO @ITEM,@CAMPO,@VALORLISTA
				   END  
			  
			   CLOSE _CURSOR  
			   DEALLOCATE _CURSOR  
		   END

		   SELECT * FROM @MPLDL
      END --JEDM END
		DECLARE @DXS AS TABLE(ITEM INT IDENTITY(1,1), IDDX VARCHAR(20), TIPO VARCHAR(20), DESCRIPCION VARCHAR(512), TIPODX VARCHAR(10))

		IF COALESCE(@CONSECUTIVOCIT,'')<>'' SELECT @IDPLAN=IDPLAN FROM CIT WHERE CONSECUTIVO=@CONSECUTIVOCIT
		-- La plantilla maneja Diagnósticos
		IF EXISTS (SELECT 1 FROM MPL WHERE CLASEPLANTILLA=@CLASEPLANTILLA AND COALESCE(PIDEDX,0)=1 AND COALESCE(MPL.IDDX,'')<>'')
		BEGIN
			INSERT @DXS(IDDX,TIPO,DESCRIPCION,TIPODX)
			SELECT MDX.IDDX,'Principal',MDX.DESCRIPCION, 'ImpreDx'
			FROM MDX INNER JOIN MPL ON MPL.IDDX=MDX.IDDX
			WHERE MPL.CLASEPLANTILLA = @CLASEPLANTILLA
         --SELECT 'DX 1' DX1
		END
		ELSE
		BEGIN
			IF DBO.FNK_VALORVARIABLE('TRAE_DX_HC_ANTERIOR')='SI' 
			BEGIN
				IF COALESCE(@CONSECUTIVOHCA, '')=''   --req 6336
				BEGIN
					INSERT @DXS(IDDX,TIPO,DESCRIPCION,TIPODX)
					SELECT TOP 1 IDDX,TIPO,DESCRIPCION, TIPODX 
					FROM (
						SELECT TOP 1 CIT.IDDX, 'Principal' TIPO, MDX.DESCRIPCION,'ImpreDx' TIPODX
						FROM CIT INNER JOIN MDX ON MDX.IDDX=CIT.IDDX 
						WHERE CIT.IDAFILIADO=@IDAFILIADO 
						AND COALESCE(CIT.IDDX,'')<>''
						AND COALESCE(@CONSECUTIVOCIT, '')<>''
						ORDER BY FECHA DESC
						UNION ALL
						SELECT TOP 1 MDX.IDDX,'Principal',MDX.DESCRIPCION,TIPODX 
						FROM HCA WITH(NOLOCK) INNER JOIN MDX ON MDX.IDDX=HCA.IDDX
						WHERE IDAFILIADO = @IDAFILIADO  
						AND (COALESCE(@IDPLAN, '')='' OR HCA.IDPLAN = @IDPLAN)
						-- AND NOADMISION=COALESCE(@NOADMISION,NOADMISION) 
						AND COALESCE(HCA.IDDX,'')<>'' 
						AND COALESCE(ANULADA,0)=0
						ORDER BY FECHA DESC			
					) X 
               --SELECT 'DX2' DX2
				END
				ELSE
				BEGIN
					INSERT @DXS(IDDX,TIPO,DESCRIPCION,TIPODX)
					SELECT TOP 1 MDX.IDDX,'Principal',MDX.DESCRIPCION,TIPODX 
					FROM HCA WITH(NOLOCK) INNER JOIN MDX ON MDX.IDDX=HCA.IDDX
					WHERE IDAFILIADO = @IDAFILIADO
					AND (COALESCE(@IDPLAN, '')='' OR HCA.IDPLAN = @IDPLAN)
					-- AND NOADMISION=COALESCE(@NOADMISION,NOADMISION) 
					AND COALESCE(HCA.IDDX,'')<>'' 
					AND COALESCE(ANULADA,0)=0
					ORDER BY FECHA DESC
               --SELECT 'DX3' DX3
				END

				-- La plantilla maneja Dx Relacionados
				IF EXISTS (SELECT 1 FROM MPL WHERE CLASEPLANTILLA=@CLASEPLANTILLA AND COALESCE(PIDEDXR,0)=1)
				BEGIN
					INSERT @DXS(IDDX,TIPO,DESCRIPCION,TIPODX)
					SELECT MDX.IDDX, 'Relacionado', MDX.DESCRIPCION, TIPODX 
					FROM HCADX WITH(NOLOCK) INNER JOIN MDX ON MDX.IDDX=HCADX.IDDX 
					WHERE CONSECUTIVO IN (
						SELECT TOP 1 CONSECUTIVO 
						FROM HCA 
						WHERE IDAFILIADO=COALESCE(@IDAFILIADO,'') 
						--AND NOADMISION=COALESCE(@NOADMISION,NOADMISION)
						AND (@IDPLAN IS NULL OR IDPLAN=@IDPLAN)
						AND COALESCE(ANULADA,0)=0
						ORDER BY FECHA DESC
					)
               --SELECT 'DXREL' DXREL
				END
			END
		END
      --STORRES
		IF COALESCE(@CONSECUTIVOHCA,'')<>''
		BEGIN
			IF COALESCE((SELECT COUNT(*) FROM @DXS),0) < 1
			BEGIN
				INSERT INTO @DXS(IDDX,TIPO,DESCRIPCION,TIPODX)
				SELECT HCA.IDDX, 'Principal', MDX.DESCRIPCION, HCA.TIPODX  
				FROM HCA INNER JOIN MDX ON HCA.IDDX = MDX.IDDX 
				WHERE CONSECUTIVO = @CONSECUTIVOHCA	

				INSERT @DXS(IDDX,TIPO,DESCRIPCION,TIPODX)
					SELECT MDX.IDDX, 'Relacionado', MDX.DESCRIPCION, TIPODX 
					FROM HCADX WITH(NOLOCK) INNER JOIN MDX ON MDX.IDDX=HCADX.IDDX 
					WHERE CONSECUTIVO = @CONSECUTIVOHCA
            --SELECT 'DX POR AQUI SI FUE' DXSIFUE
			END
		END
		--STORRES
      --cuarto select 
		SELECT DISTINCT IDDX, DESCRIPCION, TIPODX, TIPO FROM @DXS	
		PRINT '(1) @CONSECUTIVO='+COALESCE(@CONSECUTIVO,'')
		--SELECT @CONSECUTIVO = NULL --OMAR
		IF 1=1
		BEGIN -- HCATD
			IF @TIPO_CNS='HADM' 
			BEGIN

				IF EXISTS (SELECT 1 FROM MPL WHERE CLASEPLANTILLA=@CLASEPLANTILLA AND AMBITO='QX' AND CLASE='HC' AND COALESCE(MPL.NOCOPIAOM,0)=0 AND COALESCE(MPL.TIENEOM,0)>0)					
				BEGIN
					SELECT TOP 1 @CONSECUTIVOHCA = CONSECUTIVO 
					FROM   HCA INNER JOIN MPL ON HCA.CLASEPLANTILLA = MPL.CLASEPLANTILLA
					WHERE  NOADMISION = @CONSECUTIVO 
					AND    PROCEDENCIA = 'QX' 
					AND    HCA.CLASE = @CLASE
					AND	   COALESCE(ANULADA,0)=0
					AND    COALESCE(MPL.NOCOPIAOM,0)=0
					AND	   COALESCE(@EDITANDO,0) = 0
					AND    COALESCE(MPL.TIENEOM,0)>0
					--AND    HCA.FECHA < @FECHA
					--AND	 HCA.CONSECUTIVO=IIF(@EDITARHCA=1 AND COALESCE(@CONSECUTIVOHCA,'')<>'',@CONSECUTIVOHCA, HCA.CONSECUTIVO)
					AND	 HCA.CLASEPLANTILLA NOT IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('HCPLANTILLAEPI','HCPLANTILLAEPI_UCI'))
					
					ORDER BY FECHA DESC, CONSECUTIVO DESC
				END
				ELSE
				BEGIN
					SELECT @CONSECUTIVOHCA = NULL
				END
			END
			ELSE
			BEGIN
				SELECT TOP 1 @CONSECUTIVOHCA = CONSECUTIVO 
				FROM HCA V
				WHERE CLASEPLANTILLA=@CLASEPLANTILLA
				AND IDAFILIADO=@IDAFILIADO
				AND COALESCE(ANULADA,0)=0
				AND CONSECUTIVO=COALESCE(@CONSECUTIVOHCA, CONSECUTIVO)
				ORDER BY FECHA DESC
			END
			PRINT '(2) @CONSECUTIVO='+COALESCE(@CONSECUTIVO,'')
			PRINT '(3) @CONSECUTIVOHCA='+COALESCE(@CONSECUTIVOHCA,'')
			PRINT '@IDAFILIADO= '+COALESCE(@IDAFILIADO,'')
         --quinto select hcatd
			SELECT HCATD.IDSERVICIO
			--,HCATD.CLASE
				,SER.DESCSERVICIO
				,SER.SEXO
				,CIRUGIA=COALESCE(SER.CIRUGIA, 0)
				,SER.MEDICAMENTOS
				,SER.IDARTICULO
				,MDOSIF=CAST(COALESCE(SER.MDOSIF, 0) AS BIT)
				,SER.EQUICC
				,MULTIDOSIS=COALESCE(SER.MULTIDOSIS, 0)
				,SER.PRESUNI
				,HCATD.VIA
				,HCATD.APLICADA
				,LIBREFORMULACION=COALESCE(SER.LIBREFORMULACION, 0)
				,EXCLUYEPOSOLOGIA=COALESCE(SER.EXCLUYEPOSOLOGIA, 0)
				,BIOLOGICO=(SELECT TOP 1 CAST(COALESCE(BIOLOGICO, 0) AS BIT) FROM IART WHERE IDARTICULO = SER.IDARTICULO) 
				,T_ESTABILIDAD=COALESCE(SER.T_ESTABILIDAD, 0)
				,SER.EQUICCINF
				,HCATD.CANTIDAD
				,HCATD.TIPO
				,DURACION=CAST(COALESCE((HCATD.DURACION / CASE 
						WHEN COALESCE(HCATD.CLASE, '') = 'C'
							THEN 1
						ELSE CASE 
							WHEN COALESCE(HCATD.TIPODURACION, 'D') = 'D'
								THEN 24
							ELSE 1
							END
						END), 24) AS INT)
				,TIPOFRECUENCIA=COALESCE(HCATD.TIPOFRECUENCIA, 'H')
				,TIPODURACION=COALESCE(HCATD.TIPODURACION, IIF(@TIPO_CNS='HADM','H','D'))
				,HCATD.FRECUENCIA
				,OBSERVACION=COALESCE(HCATD.OBSERVACION, '')
				,HCATD.CODOM
				,CODOM_DESCRIPCION=HCCOM.DESCRIPCION
				,RIGHT('0'+CONVERT(VARCHAR, HCATD.HORAAM),2) HORAAM
				,RIGHT('0'+CONVERT(VARCHAR, HCATD.HORAPM),2) HORAPM
				,HCATD.QAM
				,HCATD.QPM
				,RAZONNEC=COALESCE(HCATD.RAZONNEC, 0)
				,LUNES=COALESCE(HCATD.LUNES, 0)
				,MARTES=COALESCE(HCATD.MARTES, 0)
				,MIERCOLES=COALESCE(HCATD.MIERCOLES, 0)
				,JUEVES=COALESCE(HCATD.JUEVES, 0)
				,VIERNES=COALESCE(HCATD.VIERNES, 0)
				,SABADO=COALESCE(HCATD.SABADO, 0)
				,DOMINGO=COALESCE(HCATD.DOMINGO, 0)
				,RUTA=COALESCE(HCATD.RUTA, 0)
				,TOTALUNIDADES=COALESCE(HCATD.TOTALUNIDADES, 0)
				,PRESCRIPCION=COALESCE(HCATD.PRESCRIPCION, LEFT(HCAPM.OBSERVACION, CHARINDEX('// OBSERVACIÓN:',HCAPM.OBSERVACION,1)))
				,UNIRS = (SELECT ITEM,DXUNIRS FROM IARTDX WHERE IDARTICULO=SER.IDARTICULO FOR JSON AUTO)
				,HCATD.ITEM_DXUNIRS
				,DXUNIRS = ITEM_DXUNIRS 
				,IDDXUNIRS = (SELECT IDDX,DESCRIPCION FROM MDX WHERE IDDX = HCATD.IDDX FOR JSON AUTO)
				,HCATD.IDDX
				,MDX.DESCRIPCION AS DESCDX
				,IART.ALERTA
				--,IARTDX.DXUNIRS
				,HCATD.EFECTOS
				,CASE HCA.PROCEDENCIA WHEN 'QX' THEN IIF(@EDITARHCA=1, HCATD.CLASE, 'C') ELSE 'I' END CLASE
				,HCATD.CANTIDADNOCC
				,HCATD.CANTIDADINV
				,GETDATE() FECHAINI
				,1 COPIADO
				,0 PRIMER
				,COALESCE(SER.TERAPIA,0) TERAPIA
				,HCATD.CANTIDAD CANTIDADORI
				,HCATD.FRECUENCIA FRECUENCIAORI
				,HCATD.DURACION DURACIONORI
				,COALESCE(HCATD.IDSERVICIOMEZCLA,' ') IDSERVICIOMEZCLA
				,COALESCE(HCATD.QMEZCLA,0) QMEZCLA
				,COALESCE(SER.MEZCLA,0) SEMEZCLA
				,HCATD.ORDEN
				,HCATD.AVISADOENF
				,HCATD.NOINGRESO
				,HCATD.ENCARGOS
				,HCATD.NOPRESTACION
				,SER_MEZCLA = (SELECT A.IDSERVICIOREL value, A.IDSERVICIOREL+'-'+B.DESCSERVICIO label FROM SERR A LEFT JOIN SER B ON A.IDSERVICIOREL=B.IDSERVICIO
					WHERE A.IDSERVICIO=SER.IDSERVICIO AND A.TIPO='DI' FOR JSON PATH ) 
				,COALESCE(HCATD.DOSISUNICA,0) DOSISUNICA
				,HCATDO = (
						SELECT SER.IDSERVICIO
						,SER.DESCSERVICIO
						,SER.SEXO
						,COALESCE(SER.CIRUGIA, 0) CIRUGIA
						,COALESCE(SER.MEZCLA, 0) MEZCLA
						,CASE 
							WHEN COALESCE(EXCLUYEPOSOLOGIA, 0) = 1
								THEN 0
							ELSE COALESCE(SER.MEDICAMENTOS, 0)
							END MEDICAMENTOS
						,COALESCE(HCATDO.IDARTICULO, SER.IDARTICULO, 'NA') IDARTICULO
						,CAST(CASE 
								WHEN COALESCE(EXCLUYEPOSOLOGIA, 0) = 1
									THEN 0
								ELSE COALESCE(SER.MDOSIF, 0)
								END AS BIT) MDOSIF
						,COALESCE(EQUICC, 0.0) EQUICC
						,COALESCE(SER.MULTIDOSIS, 0) MULTIDOSIS
						,SER.PRESUNI
						,VIA = COALESCE(HCATDO.VIA, SER.VIA)
						,COALESCE(LIBREFORMULACION, 0) LIBREFORMULACION
						,CAST(COALESCE(EXCLUYEPOSOLOGIA, 0) AS BIT) EXCLUYEPOSOLOGIA
						,(SELECT TOP 1 CAST(COALESCE(BIOLOGICO, 0) AS BIT) FROM IART WHERE IDARTICULO = SER.IDARTICULO) BIOLOGICO
						,CAST(COALESCE(T_ESTABILIDAD, 0.0) AS INT) T_ESTABILIDAD
						,0 RAZONNEC
						,IART.ALERTA
						,UNIRS = (SELECT ITEM,DXUNIRS FROM IARTDX WHERE IDARTICULO = SER.IDARTICULO FOR JSON AUTO)
						,HCATDO.CANTIDAD
						,HCATDO.IDTIPOCONC
						,HCATDO.OBSERVACION
						,HCATDO.TIPOFRECUENCIA
						,HCATDO.FRECUENCIA
						,HCATDO.DURACION
						,CICLO = HCATDO.CICLOS
						,HCATDO.TOTALUNIDADES
						,HCATDO.PRESCRIPCION
						,ONCOLOGIA = CAST(COALESCE(SER.ONCOLOGIA,0) AS BIT)
						,ONCOLOGICOS = CAST(COALESCE(SER.ONCOLOGIA,0) AS BIT)
					FROM HCATDO 
					INNER JOIN [dbo].[SER] ON HCATDO.IDSERVICIO=SER.IDSERVICIO
					LEFT JOIN IART ON IART.IDARTICULO=SER.IDARTICULO
					WHERE HCATDO.ID=HCATD.ID 
					FOR JSON PATH)
				,RESTRINGIR_EDICION = 
					CASE WHEN EXISTS(
						SELECT 1
						FROM HCATDO 
						INNER JOIN HCATDOD ON HCATDOD.HCATDO_ITEM=HCATDO.ITEM
						WHERE HCATDO.ID=HCATD.ID 
						AND HCATDOD.CONSECUTIVOCIT IS NOT NULL
					) THEN 'Edición de prescripción restringida. Razón: Su esquema posee citas agendadas.'
					ELSE NULL END
				,HCATDH = (SELECT A.ITEMRED, A.CODOM, A.IDSERVICIO, RIGHT('0'+CONVERT(VARCHAR, A.HORA),2) HORA, A.CANTIDAD, A.IDSERVICIOD, SER.DESCSERVICIO 
						FROM HCATDH A
							LEFT JOIN SER ON SER.IDSERVICIO=A.IDSERVICIOD AND COALESCE(A.IDSERVICIOD,'')<>''
						WHERE A.CONSECUTIVO=HCATD.CONSECUTIVO AND A.CODOM=HCATD.CODOM AND A.IDSERVICIO=HCATD.IDSERVICIO 
						FOR JSON PATH)
			FROM HCATD 
				INNER JOIN SER ON SER.IDSERVICIO=HCATD.IDSERVICIO
				INNER JOIN HCCOM ON HCCOM.CODOM = HCATD.CODOM
				INNER JOIN HCA ON HCA.CONSECUTIVO=HCATD.CONSECUTIVO
				INNER JOIN MPL ON MPL.CLASEPLANTILLA=HCA.CLASEPLANTILLA
				LEFT JOIN (SELECT CODOM, PREFIJO, SECOPIA, PIDEVIA, PIDEPRESENTACION, IDSERVICIO FROM HCCOMD
							) X ON X.CODOM=HCCOM.CODOM AND ((X.IDSERVICIO=SER.IDSERVICIO AND  X.CODOM IN (@OMCODHEMODERIVADOS, @OMCODLIQUIDOSPARE, @OMCODNUTRICIONP)) OR (X.PREFIJO=SER.PREFIJO AND  X.CODOM NOT IN (@OMCODHEMODERIVADOS, @OMCODLIQUIDOSPARE, @OMCODNUTRICIONP)))
				LEFT JOIN HCAPM ON HCAPM.CONSECUTIVO=HCATD.CONSECUTIVO AND HCAPM.CLAMED=HCATD.CODOM AND HCAPM.IDSERVICIO=HCATD.IDSERVICIO
				LEFT JOIN MDX ON MDX.IDDX = HCATD.IDDX
				LEFT JOIN IART ON IART.IDARTICULO = SER.IDARTICULO
				LEFT JOIN IARTDX ON HCATD.ITEM_DXUNIRS = IARTDX.ITEM
			WHERE HCATD.CONSECUTIVO=@CONSECUTIVOHCA
				AND (COALESCE(MPL.NOCOPIAOM, 0)=0 OR COALESCE(@EDITARHCA, 0) = 1) --GENERAL
				AND 1=CASE WHEN @TIPO_CNS='HADM' THEN 1 ELSE CASE WHEN COALESCE(PRESCRIPCION,'')<>'' THEN 1 ELSE 0 END END --PREESCRIPCION EN CONSULTA EXTERNA
				AND 1=IIF(COALESCE(@EDITARHCA,0)=1, 1,CASE WHEN COALESCE(HCATD.CLASE,'I')<>'S' THEN 1 ELSE 0 END) --CLASE SUSPENDER EN HOSP
				AND 1=CASE WHEN @TIPO_CNS<>'HADM' THEN 1 ELSE IIF(COALESCE(@EDITARHCA,0)=1,1,COALESCE(X.SECOPIA,0)) END --SOLO LOS COPIA OM HOSP
				AND 1=CASE WHEN @TIPO_CNS<>'HADM' THEN 1 ELSE IIF(COALESCE(@EDITARHCA,0)=0 AND COALESCE(HCATD.DOSISUNICA,0)=1, 0, 1) END --LOS QUE NO SEAN DOSIS UNICA EN HOSP
				AND @CONSECUTIVOHCA IS NOT NULL
				AND (@COPIARDATOANT = 1 OR @TIPO_CNS='HADM')
				--AND 1=CASE WHEN @TIPO_CNS<>'HADM' THEN 1 ELSE IIF(COALESCE(@EDITARHCA,0)=1,1,IIF(HCCOM.TIPO='OM',1,0)) END --SOLO LOS OM EN HOSP, MANUALES NO
			ORDER BY HCATD.ORDEN, SER.DESCSERVICIO
		END
		
		IF 1=1
		BEGIN
			DECLARE @HCASER TABLE (CONSECUTIVO VARCHAR(20), IDSERVICIO VARCHAR(20), CANTIDAD SMALLINT,  AUTOMATICO BIT, DIARIA SMALLINT, CANTMIN SMALLINT, CANTMAX SMALLINT)
			DECLARE @IDSERVICIO VARCHAR(20), @CANTDEFAULT SMALLINT, @AUTOMATICO SMALLINT, @DIARIAS SMALLINT, @CANTMIN SMALLINT, @CANTMAX SMALLINT

			SELECT @FECHA=CONVERT(DATE,GETDATE())
			SELECT @IX=dbo.FNK_VALORVARIABLE('IXCOUNTRY')

			SELECT @PROCEDENCIA= IIF(@TIPO_CNS='HADM','QX','IPS') 
			--@IDEMEDICA
			IF @PROCEDENCIA='QX'
				SELECT @IDTERCEROCA=IDTERCERO,@IDPLAN=IDPLAN FROM HADM WHERE NOADMISION=@NOADMISION
			ELSE
				SELECT @IDTERCEROCA=IDTERCEROCA,@IDPLAN=IDPLAN FROM CIT WHERE CONSECUTIVO=@NOADMISION

			IF @IDTERCEROCA IS NULL
			BEGIN
				SELECT @IDTERCEROCA=IDADMINISTRADORA, @IDPLAN=IDPLAN FROM AFI WHERE IDAFILIADO=@IDAFILIADO
			END


			DECLARE HC CURSOR FOR
			SELECT DISTINCT A.IDSERVICIO, CANTDEFAULT, AUTOMATICO, COALESCE(DIARIAS ,0), A.CANTMIN, A.CANTMAX
			FROM   MPLSER A INNER JOIN CPPAF B ON A.IDSERVICIO = B.IDSERVICIO
							INNER JOIN SER C ON C.IDSERVICIO=A.IDSERVICIO
			WHERE  B.IDPLAN         = @IDPLAN 
			AND    COALESCE(B.IDTERCEROCA,'') = CASE WHEN B.COBRARA = 'O' THEN COALESCE(B.IDTERCEROCA,'') ELSE @IDTERCEROCA END 
			AND    A.CLASEPLANTILLA = @CLASEPLANTILLA 
			--AND    ISNULL(C.IDEMEDICA,'')=(CASE ISNULL(C.IDEMEDICA,'') WHEN '' THEN ISNULL(C.IDEMEDICA,'') ELSE @IDEMEDICA END)
			--AND    ISNULL(REPLACE(C.ATENCION,'Todos',''),'')=(CASE ISNULL(REPLACE(C.ATENCION,'Todos',''),'') WHEN '' THEN ISNULL(REPLACE(C.ATENCION,'Todos',''),'') ELSE @ATENCION END)
			AND   COALESCE(A.SEXO,'Ambos') IN ('Ambos',@SEXO)

			OPEN HC
			FETCH NEXT FROM HC
			INTO @IDSERVICIO, @CANTDEFAULT, @AUTOMATICO, @DIARIAS, @CANTMIN, @CANTMAX
			WHILE @@FETCH_STATUS = 0
			BEGIN
				IF @DIARIAS = 0 
				BEGIN
					INSERT INTO @HCASER (CONSECUTIVO, IDSERVICIO, CANTIDAD, AUTOMATICO, DIARIA, CANTMIN, CANTMAX)
					SELECT @CONSECUTIVOHCA, @IDSERVICIO, @CANTDEFAULT, @AUTOMATICO, @DIARIAS, @CANTMIN, @CANTMAX
				END
				ELSE
				BEGIN
					IF (SELECT COUNT(*) 
						FROM   HCA INNER JOIN HCASER ON HCA.CONSECUTIVO = HCASER.CONSECUTIVO
						WHERE  HCA.NOADMISION     =  @NOADMISION
						AND    HCA.CLASEPLANTILLA =  @CLASEPLANTILLA
						AND    HCA.CONSECUTIVO    <> COALESCE(@CONSECUTIVOHCA,'')
						AND    HCASER.IDSERVICIO  =  @IDSERVICIO
						AND    CONVERT(DATE,HCA.FECHA)=@FECHA
						AND    COALESCE(HCASER.NOPRESTACION,'') <> '' ) < @DIARIAS
					BEGIN
						IF @IX='PERU'
						BEGIN
							SELECT @IDPLAN=IDPLAN FROM CIT WHERE CONSECUTIVO=@NOADMISION
							IF @IDPLAN IN ('PAQ027','PAR028')
							BEGIN
								IF NOT EXISTS (SELECT 1 FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION WHERE HPRE.NOADMISION=@NOADMISION AND HPRED.IDSERVICIO=@IDSERVICIO AND ISNULL(HPRED.ANULADO,0)=0)
								BEGIN
									INSERT INTO @HCASER (CONSECUTIVO, IDSERVICIO, CANTIDAD, AUTOMATICO, DIARIA, CANTMIN, CANTMAX)
									SELECT @CONSECUTIVOHCA, @IDSERVICIO, @CANTDEFAULT, @AUTOMATICO, @DIARIAS, @CANTMIN, @CANTMAX
								END
								END
							ELSE
							BEGIN
								INSERT INTO @HCASER (CONSECUTIVO, IDSERVICIO, CANTIDAD, AUTOMATICO, DIARIA, CANTMIN, CANTMAX)
								SELECT @CONSECUTIVOHCA, @IDSERVICIO, @CANTDEFAULT, @AUTOMATICO, @DIARIAS, @CANTMIN, @CANTMAX
							END
						END
						ELSE
						BEGIN
							INSERT INTO @HCASER (CONSECUTIVO, IDSERVICIO, CANTIDAD, AUTOMATICO, DIARIA, CANTMIN, CANTMAX)
							SELECT @CONSECUTIVOHCA, @IDSERVICIO, @CANTDEFAULT, @AUTOMATICO, @DIARIAS, @CANTMIN, @CANTMAX
						END
					END
				END
				FETCH NEXT FROM HC
				INTO @IDSERVICIO, @CANTDEFAULT, @AUTOMATICO, @DIARIAS, @CANTMIN, @CANTMAX
			END
			CLOSE HC
			DEALLOCATE HC
			--SOPORTE DE PAGO OBLIGACION TOTAL
         --sexto select hcaser
			SELECT CONSECUTIVO, A.IDSERVICIO, SER.DESCSERVICIO, A.CANTIDAD, AUTOMATICO, DIARIA, CANTMIN, CANTMAX 
			FROM @HCASER A INNER JOIN SER ON SER.IDSERVICIO=A.IDSERVICIO
		END
		
		SELECT DISTINCT CROVIGD.IDSERVICIO, SER.DESCSERVICIO, YEAR(CROVIGD.FECHAMAX) ANOMAX, DATENAME(MONTH,(CROVIGD.FECHAMAX)) MESMAX
		INTO #CROVIGD
		FROM CROVIGD
			INNER JOIN CROVIGPER ON CROVIGD.IDCROVIG = CROVIGPER.IDCROVIG AND CROVIGPER.ANIO = YEAR(GETDATE()) AND CROVIGPER.MES = MONTH(GETDATE())
			INNER JOIN SER ON CROVIGD.IDSERVICIO = SER.IDSERVICIO AND SER.PREFIJO IN(SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('PREFIJOAPOYODX','PREFIJOLABORATORIO'))
			LEFT JOIN AFIPAT ON AFIPAT.IDCROVIG=CROVIGD.IDCROVIG
			LEFT JOIN PAT ON PAT.IDPATOLOGIA=AFIPAT.IDPATOLOGIA			
		WHERE CROVIGD.IDAFILIADO = @IDAFILIADO AND YEAR(CROVIGD.FECHAMAX) <= YEAR(GETDATE()) AND MONTH(CROVIGD.FECHAMAX) <= MONTH(GETDATE())
			AND CROVIGD.CUMPLIDA = 0 AND VISIBLE=1 AND COALESCE(@ESPROGRAMAS,0)=1
		--septimo select crovigd
		SELECT * FROM #CROVIGD

      IF @CLASEPLANTILLA IN ('PI_RIAS' ,'IN_RIAS') 
      BEGIN
         --AIEPI
         --octavo select 
         SELECT CNFAIEPI.CODIGO, CNFAIEPI.CLASE, CNFAIEPI.TIPO ,CNFAIEPI.NOMBRE ,CNFAIEPI.ORDEN, AIEPIAFI.RESPUESTA 
         FROM   CNFAIEPI LEFT JOIN AIEPIAFI ON CNFAIEPI.CODIGO = AIEPIAFI.CODIGO
                                           AND AIEPIAFI.IDAFILIADO = @IDAFILIADO
         ORDER BY CNFAIEPI.CLASE,CNFAIEPI.TIPO,CNFAIEPI.ORDEN
      END
		RETURN
	END
	IF @METODO = 'AUTOSUGGEST'
	BEGIN
		SELECT 'OK' OK
		
		SELECT '' AS SUGERENCIA
		RETURN
		SELECT @NOADMISION = NOADMISION,
			@CONSECUTIVOCIT = CONSECUTIVOCIT,
			@CLASEPLANTILLA = CLASEPLANTILLA,
			@CAMPO = CAMPO,
			@SECUENCIA = SECUENCIA,
			@TEXTO = TEXTO
		FROM OPENJSON(@PARAMETROS)
		WITH (
			NOADMISION VARCHAR(20)		'$.NOADMISION',
			CONSECUTIVOCIT VARCHAR(20)	'$.CONSECUTIVOCIT',
			CLASEPLANTILLA VARCHAR(8)   '$.CLASEPLANTILLA',
			CAMPO VARCHAR(12)			'$.CAMPO',
			SECUENCIA SMALLINT			'$.SECUENCIA',
			TEXTO VARCHAR(MAX)			'$.TEXTO'
		)

		SELECT @IDMEDICO=IDMEDICO FROM USUSU WHERE USUARIO=@USUARIO
		

		SELECT ROW_NUMBER() OVER(ORDER BY WORDID ASC) AS Item, WORD INTO #PALABRAS FROM DBO.FNK_EXPLODE(@TEXTO, ' ') WHERE LEN(COALESCE(WORD,''))>2
		DECLARE @FILAS INT = @@ROWCOUNT
		DECLARE @sqlCommand NVARCHAR(MAX)='SELECT TOP 1 @MEMO = HCAD.MEMO FROM HCAD INNER JOIN HCA ON HCAD.CONSECUTIVO=HCA.CONSECUTIVO WHERE HCAD.CLASEPLANTILLA=@CLASEPLANTILLA AND HCAD.CAMPO=@CAMPO AND HCAD.SECUENCIA=@SECUENCIA AND HCA.IDMEDICO = @IDMEDICO ' 
		DECLARE @WORD VARCHAR(1000)
		
		WHILE @FILAS > 0
		BEGIN
			SELECT @WORD = WORD FROM #PALABRAS WHERE ITEM=@FILAS
			SELECT @sqlCommand+=' AND MEMO LIKE ''%'+@WORD+'%'''
			SET @FILAS = @FILAS - 1
		END
		SELECT @sqlCommand+=' ORDER BY HCA.FECHA DESC'
		PRINT @sqlCommand
		DECLARE @MEMO VARCHAR(MAX)
		EXECUTE sp_executesql @sqlCommand, N'@CLASEPLANTILLA VARCHAR(8), @CAMPO VARCHAR(12), @SECUENCIA SMALLINT, @IDMEDICO VARCHAR(20), @MEMO VARCHAR(MAX) OUTPUT', @CLASEPLANTILLA = @CLASEPLANTILLA, @CAMPO = @CAMPO, @SECUENCIA = @SECUENCIA, @IDMEDICO=@IDMEDICO, @MEMO=@MEMO OUTPUT


		DECLARE @ULTIMAPALABRA VARCHAR(1000)= (SELECT TOP 1 WORD FROM #PALABRAS ORDER BY ITEM DESC)
		SELECT @SUGERENCIA = LTRIM(RTRIM(REVERSE(SUBSTRING(REVERSE(@MEMO),1,CHARINDEX(REVERSE(@ULTIMAPALABRA),REVERSE(@MEMO))))))
		IF LEN(@SUGERENCIA)>0
			--SELECT @TEXTO+RIGHT(@SUGERENCIA,LEN(@SUGERENCIA)-1) AS SUGERENCIA
			SELECT @TEXTO+' '+RIGHT(@SUGERENCIA,LEN(@SUGERENCIA)) AS SUGERENCIA
			--SELECT @TEXTO+' '+RIGHT(@SUGERENCIA,LEN(@SUGERENCIA)) AS SUGERENCIA
		ELSE
			SELECT @TEXTO AS SUGERENCIA
		
	END
	IF @METODO = 'VALIDANECPAL'
	BEGIN
		SELECT 'OK' OK
		
		DECLARE @DXSR NVARCHAR(MAX)
		DECLARE @IDDX VARCHAR(10)
		DECLARE @OK VARCHAR(2) = 'OK'

		SELECT @IDAFILIADO = IDAFILIADO
				,@CONSECUTIVOCIT = CONSECUTIVO
				,@IDPLAN = IDPLAN
				,@NOADMISION = NOADMISION 
				,@DXSR = DXSR
				,@IDDX = COALESCE(IDDX,'')
		FROM OPENJSON(@PARAMETROS) 
		WITH(
				IDAFILIADO		VARCHAR(20)		'$.IDAFILIADO'
			,CONSECUTIVO	VARCHAR(20)		'$.CONSECUTIVO'
			,IDPLAN			VARCHAR(10)		'$.IDPLAN'
			,NOADMISION		VARCHAR(10)		'$.NOADMISION'
			,IDDX			VARCHAR(10)		'$.IDDX'
			,DXSR NVARCHAR(MAX) AS JSON
			)

		SELECT * INTO #DXSR FROM OPENJSON(@DXSR) WITH ( IDDX VARCHAR(10) '$.IDDX' )
		INSERT INTO #DXSR(IDDX) SELECT @IDDX 

		--Afiliado exista en AFIBUSAC
		IF (SELECT COUNT(1) FROM AFIBUSAC WHERE IDAFILIADO = @IDAFILIADO)>0 SELECT @OK = 'KO'
			IF (@OK='KO') BEGIN SELECT @OK OK RETURN END

		--IDPLAN no sea ninguno de los 3 siguientes: 
		IF (@IDPLAN IN ('PAQ026', 'PAQ055', 'PAQCON')) SELECT @OK = 'KO'
			IF (@OK='KO') BEGIN SELECT @OK OK RETURN END

		--Validacion de DXs
		IF ( SELECT COUNT(*) FROM #DXSR DXT INNER JOIN MDX ON DXT.IDDX = MDX.IDDX WHERE MDX.CLASIF1 = '2') = 0
		BEGIN SELECT @OK ='KO' END

		SELECT @OK OK RETURN
	END
	IF @METODO = 'CAMPOS_PERMANENTES'
	BEGIN
		SELECT 'OK' OK
		
		SELECT @CLASEPLANTILLA = CLASEPLANTILLA, @IDAFILIADO = IDAFILIADO, @CAMPOPERMANENTE = CAMPOPERMANENTE 
		FROM OPENJSON( @PARAMETROS ) WITH( CLASEPLANTILLA	VARCHAR(20) '$.CLASEPLANTILLA'
											,IDAFILIADO		VARCHAR(20) '$.IDAFILIADO'
											,CAMPOPERMANENTE	VARCHAR(20) '$.CAMPOPERMANENTE'	
										)
		--SELECT @IDAFILIADO, @CAMPOPERMANENTE, @CLASEPLANTILLA 
		SELECT NOMBRECAMPO, DESCRIPCION FROM MPLCP WHERE  NOMBRECAMPO = @CAMPOPERMANENTE

		SELECT CAMPOS = (
			SELECT M.ID, M.NOMBRECAMPO, M.CAMPO, M.TIPO_CAMPO, M.DESCCAMPO, M.ORDEN, M.CODIGOOP, M.EDITABLE
					,M.R_ID, M.R_IDAFILIADO, M.R_NOMBRECAMPO, M.R_CAMPO, M.R_ALFANUMERICO, CAST(M.R_FECHA AS DATE)R_FECHA , M.R_MEMO 
					,MPLOP.CODIGOOP, MPLOP.OPCION, MPLOP.VALOR
			FROM (
				SELECT MPLCPD.ID, MPLCPD.NOMBRECAMPO, MPLCPD.CAMPO, MPLCPD.TIPO_CAMPO, MPLCPD.DESCCAMPO, MPLCPD.ORDEN, MPLCPD.CODIGOOP, MPLCPD.EDITABLE
						,HCADCP.ID R_ID, HCADCP.IDAFILIADO R_IDAFILIADO, HCADCP.NOMBRECAMPO R_NOMBRECAMPO, HCADCP.CAMPO R_CAMPO
						,HCADCP.ALFANUMERICO R_ALFANUMERICO, HCADCP.FECHA R_FECHA, HCADCP.MEMO R_MEMO
				FROM MPLD 
				LEFT JOIN MPLCPD ON MPLD.DEFAULT1 =  MPLCPD.NOMBRECAMPO
				LEFT JOIN HCADCP ON HCADCP.NOMBRECAMPO = MPLCPD.NOMBRECAMPO AND HCADCP.CAMPO = MPLCPD.CAMPO AND HCADCP.IDAFILIADO = @IDAFILIADO
				WHERE CLASEPLANTILLA = @CLASEPLANTILLA 
					AND MPLD.DEFAULT1 = @CAMPOPERMANENTE 
			) M
			LEFT JOIN MPLOP  ON M.CODIGOOP = MPLOP.CODIGOOP
		ORDER BY M.ORDEN
		FOR JSON AUTO )
	END
	IF @METODO = 'VALIDA_ATENCION'
	BEGIN
		SELECT @CONSECUTIVOCIT = JSON_VALUE(@PARAMETROS, '$.CONSECUTIVOCIT')
		
		IF DBO.FNK_VALORVARIABLE('CIT_VALIDA_FATENCION') = 'SI'
		BEGIN

			SELECT @FECHA = FECHA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVOCIT

			IF CAST(@FECHA AS DATE)<>CAST(GETDATE() AS DATE)
			BEGIN
				SELECT 'KO' AS OK
				SELECT ERROR 
				FROM (
					SELECT 'No puede atender citas con fechas diferente a la actual' AS ERROR
				) AS #T

				RETURN
			END
		END
		ELSE
		BEGIN
			IF DBO.FNK_VALORVARIABLE('CONSUL_CIT_FANT') != 'SI'
			BEGIN
				IF EXISTS(SELECT 1 FROM CIT WHERE CONSECUTIVO=@CONSECUTIVOCIT AND CIT.FECHAATENCION IS NOT NULL)
				BEGIN
					SELECT 'KO' AS OK
					SELECT ERROR 
					FROM (
						SELECT 'Cita atendida, no puede atender citas con fechas diferente a la actual en citas atendidas.' AS ERROR
					) AS #T

					RETURN
				END
			END
		END

		IF (SELECT CUMPLIDA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVOCIT)=2
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'Paciente no asistió no puede atender esta cita.'
		END

		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END 

		SELECT 'OK' AS OK, @FECHA AS FECHA

	END
	IF @METODO = 'GET_MPL'
	BEGIN
		SELECT 'OK' AS OK
		SELECT CLASEPLANTILLA,DESCPLANTILLA FROM MPL WHERE ESTADO='Activo' ORDER BY DESCPLANTILLA
		RETURN
	END
	IF @METODO = 'CODIGO_AZUL'
	BEGIN
		SELECT 'OK' AS OK
		SELECT CASE WHEN EXISTS (SELECT 1 FROM MPL WHERE HURG=4) THEN 'SI' ELSE 'NO' END CODIGOAZUL
		RETURN
	END
	IF @METODO = 'GET_TEMPLATE'
	BEGIN
		SELECT 'OK' AS OK
		SELECT TEMPLATEID, TEMPLATE FROM KMAILT WHERE TEMPLATEID IN ('SEND_OMEDICA','SEND_RMEDICA')
		RETURN
	END
	IF @METODO = 'VALIDA_PROTOCOLO'
	BEGIN
		SELECT @IDAFILIADO = IDAFILIADO, @NOADMISION = NOADMISION, @PROCEDENCIA = PROCEDENCIA 
		FROM OPENJSON(@PARAMETROS)  
		WITH (	IDAFILIADO VARCHAR(20)		'$.IDAFILIADO',
				NOADMISION VARCHAR(16)		'$.NOADMISION',
				PROCEDENCIA VARCHAR(100)	'$.PROCEDENCIA'
			)
	END
END

