USE KPCEM

SELECT top 20* FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC



SELECT  ID = ROW_NUMBER() OVER (ORDER BY IDAFILIADO, NOADMISION, NOPRESTACION, NOITEM),                               IDAFILIADO,DOCIDAFILIADO,PACIENTE,PROCEDENCIA,NOADMISION,IDSERVICIO,DESCSERVICIO,FECHA,                               CONVERT(DECIMAL(14,2),VALORTOTAL)VALORTOTAL,CONVERT(DECIMAL(14,2),VALORCOPAGO)VALORCOPAGO,                               CONVERT(DECIMAL(14,2),VALOREXCEDENTE)VALOREXCEDENTE,MARCAFAC,USUMARCA, NOPRESTACION, NOITEM,CNSFACT,COALESCE(NOAUTORIZACION,'')NOAUTORIZACION                               ,IDTERCEROCA AS IDTERCERO,RAZONSOCIAL,IDPLAN,NOMPLAN AS DESCPLAN,CANTIDAD,TIPOCOPAGO,IDSEDE,CODUNG   FROM [dbo].[VWK_CARGOS_HADMAUTCIT] WHERE (PROCEDENCIA LIKE '%%%%' OR PACIENTE LIKE '%%%%' OR DOCIDAFILIADO LIKE '%%%%' OR  NOADMISION LIKE '%%%%') AND  COALESCE(FACTURADA,0) = 0    AND CONVERT(DATE, FECHA) >=  '2023-07-01' AND CONVERT(DATE, FECHA) <=  '2024-01-24' AND IDTERCERO=  '900156264' AND PROCEDENCIA = 'CIT'AND COALESCE(NOCOBRABLE,0)=0   ORDER BY IDAFILIADO, NOADMISION, NOPRESTACION, NOITEM  --OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 




EXEC SPQ_JSON '{"MODELO":"FTR_COL","METODO":"MARCAFACT","PARAMETROS":{"DATOS":{"ID":"1","IDAFILIADO":"0100000461","DOCIDAFILIADO":"1065911757","PACIENTE":"ROPERO ROCHA DCARD KEVEIN","PROCEDENCIA":"CIT","NOADMISION":"0100005924","IDSERVICIO":"890385","DESCSERVICIO":"CONSULTA DE CONTROL O SEGUIMIENTO POR ESPECIALISTA EN PSIQUIATRIA PEDIATRICA","FECHA":"2023-08-10T13:03:00.000Z","VALORTOTAL":0,"VALORCOPAGO":0,"VALOREXCEDENTE":0,"MARCAFAC":0,"USUMARCA":"","NOPRESTACION":"0100005924","NOITEM":1,"CNSFACT":"","NOAUTORIZACION":"","IDTERCERO":"900156264","RAZONSOCIAL":"NUEVA EPS","IDPLAN":"NSBURG","DESCPLAN":"NUEVA EPS SUBSIDIADO URGENCIAS","CANTIDAD":1,"TIPOCOPAGO":"C","IDSEDE":"01","CODUNG":""},"CNSFACT":null},"USUARIO":"JJIMENEZ"}'

'{"MODELO":"FTR_COL","METODO":"SEDFACUMASI","USUARIO":"JJIMENEZ"}'

'{"MODELO":"FTR_COL","METODO":"ASIGNAR_NROAUT","PARAMETROS":{"CNSFACT":"0200349342","NOAUTORIZACION":"23456789"},"USUARIO":"JJIMENEZ"}'