USE KPCEM

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"PRI_COL","METODO":"CERRAR_FACTURA","PARAMETROS":{"DATOS":{"ANIO":"2024","MES":12,"NOMPERIODO":"DICIEMBRE 2024","CERRADO":0,"PROCEDENCIA":"CARTERA"}},"USUARIO":"JJIMENEZ"}'

EXEC SPQ_JSON '{"MODELO":"PRI_COL","METODO":"CERRAR_FACTURA","PARAMETROS":{"DATOS":{"ANIO":"2024","MES":12,"NOMPERIODO":"DICIEMBRE 2024","CERRADO":0,"PROCEDENCIA":"CARTERA"}},"USUARIO":"JJIMENEZ"}'


SELECT CNSGLO VLRACEPTADO,VLRRECUPERAR,DBO.FNK_FECHA_DDMMAA(F_FACTURA),* FROM FGLO

SELECT FGLO.CNSGLO, FGLO.CNSCXC,FGLO.N_FACTURA,DBO.FNK_FECHA_DDMMAA(FGLO.FECHA)FECHA,TER.NIT,TER.RAZONSOCIAL,FGLO.TIPO,FGLO.VLRGLOSA,FGLO.VLRACEPTADO,FGLO.VLRRECUPERAR                          FROM [dbo].[FGLO] INNER JOIN  TER ON FGLO.IDTERCERO=TER.IDTERCERO WHERE ( TER.RAZONSOCIAL LIKE '%%%%' OR  TER.NIT LIKE '%%%%') AND 1=1   ORDER BY CNSFGLO ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


SELECT FGLO.CNSGLO, FGLO.CNSCXC,FGLO.N_FACTURA,DBO.FNK_FECHA_DDMMAA(FGLO.F_FACTURA)F_FACTURA,TER.NIT,TER.RAZONSOCIAL,
FGLO.TIPO,FGLO.VLRGLOSA,FGLO.VLRACEPTADO,FGLO.VLRRECUPERAR,
CASE 
WHEN FGLO.IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPCARTERA')  AND FGLO.CERRADA=0 THEN 'EnCartera'
WHEN FGLO.IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPAUDITORIA')  AND FGLO.CERRADA=0 THEN 'SinRespuesta'
WHEN FGLO.IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPAUDITORIA')  AND FGLO.CERRADA=1 THEN 'Respuesta'
WHEN FGLO.IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPAUDITORIA')  AND FGLO.CERRADA=1 AND COALESCE(FGLO.VLRRECUPERAR,0)> 0
     AND FGLO.CNSGLOI IN (SELECT CNSGLOI FROM FGLOI WHERE CNSGLOI = FGLO.CNSGLOI AND RADICADO = 0) THEN 'SinRadicar'
WHEN FGLO.IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPAUDITORIA')  AND FGLO.CERRADA=1 AND COALESCE(FGLO.VLRRECUPERAR,0)> 0
     AND FGLO.CNSGLOI IN (SELECT CNSGLOI FROM FGLOI WHERE CNSGLOI = FGLO.CNSGLOI AND RADICADO = 1) THEN 'Radicada'
END ESTADO
FROM [dbo].[FGLO] INNER JOIN  TER ON FGLO.IDTERCERO=TER.IDTERCERO 
WHERE ( TER.RAZONSOCIAL LIKE '%%%%' OR  TER.NIT LIKE '%%%%') AND 1=1   
ORDER BY CNSGLO ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


<i class="fa-solid fa-magnifying-glass"></i>