

SELECT ESTADO,TIPOANULACION, * FROM FTR WHERE N_FACTURA='UV17586'
SELECT  * FROM FNOT WHERE N_FACTURA='UV17586'

UPDATE FTR SET ESTADO='P' WHERE N_FACTURA='UV17586'

SELECT * FROM HADMF WHERE N_FACTURA='UV17586'

UPDATE HADMF SET ESTADO='P' WHERE N_FACTURA='UV17586'