USE PINTERNACIONAL

SELECT  * FROM FCJ

ALTER TABLE FCJ ENABLE TRIGGER  ALL
DELETE ACJD

UPDATE CAJ SET ABIERTA=0 WHERE CODCAJA='C099'

SELECT  * FROM USVGS WHERE IDVARIABLE='IDCJFPAIZIPAY'

SELECT  * FROM BCT

UPDATE USUSU SET FECHACAMBIO=DBO.FNK_GETDATE(),FECHAVENCE=DBO.FNK_GETDATE()+180 WHERE USUARIO='JJIMENEZ'


SELECT TOP 10 * FROM API_LOG WHERE USUARIO='TEST' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"CIT_VALIDA","METODO":"INFO_CITA_RECAUDAR","PARAMETROS":{"CONSECUTIVO":"010039943519","CODCAJA":"C099"},"USUARIO":"TEST"}'

USE KRENDI


SELECT TERCEROID, * FROM NEMP WHERE NUMDOC='01    54,868'



UPDATE  NEMP SET TERCEROID=REPLACE(TERCEROID,SPACE(1),0) WHERE TERCEROID='01    54,868'

UPDATE  TER SET IDTERCERO=REPLACE(IDTERCERO,SPACE(1),0) WHERE IDTERCERO='01    54,868'