IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME = 'VWK_CARGOS_HADMAUTCIT' AND XTYPE = 'V')
   DROP VIEW VWK_CARGOS_HADMAUTCIT

GO
CREATE VIEW DBO.VWK_CARGOS_HADMAUTCIT    
WITH SCHEMABINDING, ENCRYPTION    
AS    
SELECT A.NOADMISION, A.NOPRESTACION, A.NOITEM, A.PROCEDENCIA, A.FECHA,
       PACIENTE = LEFT(ISNULL(RTRIM(AFI.PAPELLIDO),'')+' '+ISNULL(RTRIM(AFI.SAPELLIDO),'')+' '+ISNULL(RTRIM(AFI.PNOMBRE),'')+' '+ISNULL(RTRIM(AFI.SNOMBRE),''),100),
		 A.IDTERCERO, A.IDPLAN, A.IDTERCEROCA, TER.RAZONSOCIAL, A.IDPLANCA, PLN.DESCPLAN NOMPLAN, A.IDAREA, AFU.DESCRIPCION NOMBREAREA, A.CCOSTO, CEN.DESCRIPCION NOMBRECCOSTO,
		 SER.PREFIJO, PRE.NOM_PREFIJO NOMPREFIJO, A.IDSERVICIO, SER.DESCSERVICIO, A.CANTIDAD, A.VALOR, (A.CANTIDAD*A.VALOR) VALORTOTAL, A.VALORCOPAGO, A.VALORPCOMP, A.VALOREXCEDENTE,
		 A.DESCUENTO, PPT.TIPOTERCONTABLE, ISNULL(PPT.CAPITADO,0) CAPITADO, A.FACTURADA, A.N_FACTURA, A.IDMEDICO, MED.NOMBRE, (A.CANTIDAD* COALESCE(SER.VLRCOSTO,0)) AS COSTOSERVICIO,
       A.CLASEORDEN, A.IDPESPECIAL, A.RIESGO, SER.CODCUPS, A.NOCOBRABLE,A.IDSEDE,AFI.IDAFILIADO,AFI.DOCIDAFILIADO,AFI.TIPO_DOC,MARCAFAC,USUMARCA,CNSFACT,NOAUTORIZACION,TIPOCOPAGO,A.CODUNG
FROM	(
		-- ADMISIONES - HAMD
		SELECT	A.FECHA, A.IDTERCERO, A.IDPLAN, A.IDTERCEROCA, A.IDPLANCA, A.IDAREA, A.CCOSTO,
				A.IDSERVICIO, A.CANTIDAD, A.VALOR, A.VALORCOPAGO, A.VALORPCOMP, A.VALOREXCEDENTE, A.DESCUENTO,
				A.NOADMISION, A.NOPRESTACION, A.NOITEM, A.FACTURADA, A.N_FACTURA, A.PROCEDENCIA, A.IDAFILIADO, A.IDMEDICO,
            A.CLASEORDEN, A.IDPESPECIAL, A.RIESGO, A.NOCOBRABLE,A.IDSEDE,MARCAFAC,USUMARCA,CNSFACT,NOAUTORIZACION,'C' TIPOCOPAGO,A.CODUNG
		FROM  (SELECT	HPRE.FECHA, HADM.IDTERCERO, HADM.IDPLAN, HPRE.CCOSTO,
						CASE WHEN HPRED.IDTERCEROCA IS NULL OR HPRED.IDTERCEROCA='' THEN HADM.IDTERCERO ELSE HPRED.IDTERCEROCA END IDTERCEROCA,
						CASE WHEN HPRED.IDPLAN IS NULL OR HPRED.IDPLAN='' THEN HADM.IDPLAN ELSE HPRED.IDPLAN END IDPLANCA,
						HPRE.IDAREA, HPRED.IDSERVICIO,
						ISNULL(HPRED.CANTIDAD,0) CANTIDAD,
						ISNULL(HPRED.VALOR,0) VALOR,
						ISNULL(HPRED.VALORCOPAGO,0) VALORCOPAGO,
						ISNULL(HPRED.VALORPCOMP,0) VALORPCOMP,
						ISNULL(HPRED.VALOREXCEDENTE,0) VALOREXCEDENTE,
						ISNULL(HPRED.DESCUENTO,0) DESCUENTO,
						HADM.NOADMISION, HPRED.NOPRESTACION, HPRED.NOITEM, ISNULL(HPRED.FACTURADA,0) FACTURADA, HPRED.N_FACTURA,
						'HADM' PROCEDENCIA, HADM.IDAFILIADO, COALESCE(HPRED.IDPROVEEDOR,HPRE.IDMEDICO) AS IDMEDICO,
                        CASE WHEN HTAD.MPE=1 AND COALESCE(HTAD.IDPESPECIAL,'')<>'' THEN 'PyP' ELSE 'Normal' END CLASEORDEN, 
						CASE WHEN HTAD.MPE=1 AND COALESCE(HTAD.IDPESPECIAL,'')<>'' THEN HTAD.IDPESPECIAL ELSE '' END IDPESPECIAL, 
						'' RIESGO, COALESCE(HPRED.NOCOBRABLE,0) AS NOCOBRABLE,HADM.IDSEDE,COALESCE(HPRED.MARCA,0) AS MARCAFAC,
                  COALESCE(HPRED.USUARIOMARCA,'') AS USUMARCA,HPRED.CNSITFC AS CNSFACT,HADM.NOAUTORIZACION,HADM.CODUNG
				FROM	DBO.HADM	INNER JOIN DBO.HPRE  ON HADM.NOADMISION = HPRE.NOADMISION
									INNER JOIN DBO.HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
                                    INNER JOIN DBO.PPT   ON HPRE.IDTERCEROCA=PPT.IDTERCERO AND HPRE.IDPLAN=PPT.IDPLAN
									INNER JOIN DBO.HTAD  ON HTAD.TIPOADM=HADM.TIPOADM
				WHERE	HADM.CERRADA = CASE WHEN (SELECT DATO FROM DBO.USVGS WHERE IDVARIABLE= 'CAPITA_HADM_ABIERTAS')<>'SI' AND (COALESCE(PPT.CAPITADO,0)=1 OR COALESCE(PPT.PGP,0)=1) THEN 1 ELSE HADM.CERRADA END AND FACTURABLE = 1 AND HADM.CLASEING = 'A') A
		UNION ALL
		-- CITAS - CIT
		SELECT A.FECHA, A.IDTERCERO, A.IDPLAN, A.IDTERCEROCA, A.IDPLANCA, A.IDAREA, A.CCOSTO,
				 A.IDSERVICIO, A.CANTIDAD, A.VALOR, A.VALORCOPAGO, A.VALORPCOMP, A.VALOREXCEDENTE, A.DESCUENTO,
				 A.NOADMISION, A.NOPRESTACION, A.NOITEM, A.FACTURADA, A.N_FACTURA, A.PROCEDENCIA, A.IDAFILIADO, A.IDMEDICO,
             A.CLASEORDEN, A.IDPESPECIAL, A.RIESGO, A.NOCOBRABLE,A.IDSEDE,A.MARCAFAC,A.USUMARCA,A.CNSFACT,NOAUTORIZACION,A.TIPOCOPAGO,A.CODUNG
		FROM   (SELECT	CIT.FECHA, CIT.IDCONTRATANTE IDTERCERO, CIT.IDPLAN, CIT.CCOSTO,
						CASE WHEN CIT.IDTERCEROCA IS NULL OR CIT.IDTERCEROCA='' THEN CIT.IDCONTRATANTE ELSE CIT.IDTERCEROCA END IDTERCEROCA,
						CIT.IDPLAN IDPLANCA, CIT.IDAREA, CIT.IDSERVICIO,
						CASE WHEN COALESCE(CANTIDADC,0)=0 THEN 1 ELSE CANTIDADC END CANTIDAD,
						ISNULL(CIT.VALORTOTAL,0) VALOR,
						ISNULL(CIT.VALORCOPAGO,0) VALORCOPAGO,
						0 VALORPCOMP,
						CASE ISNULL(CIT.VALOREXEDENTE,0) WHEN 0 THEN ISNULL(CIT.VALORTOTAL,0)-ISNULL(CIT.VALORCOPAGO,0) ELSE CIT.VALOREXEDENTE END VALOREXCEDENTE,
						0 DESCUENTO,
						CIT.CONSECUTIVO NOADMISION, CIT.CONSECUTIVO NOPRESTACION, 1 NOITEM,
						ISNULL(CIT.FACTURADA,0) FACTURADA, CIT.N_FACTURA, 'CIT' PROCEDENCIA, CIT.IDAFILIADO, CIT.IDMEDICO,
                  CIT.CLASEORDEN, COALESCE(CIT.IDPESPECIAL,'') IDPESPECIAL, COALESCE(CIT.RIESGO,'') RIESGO,CASE WHEN  COALESCE(FACTURABLE,0)=1 THEN 0 ELSE 1 END AS NOCOBRABLE,
                  COALESCE(CIT.IDSEDE,'') IDSEDE,COALESCE(MARCAFAC,0)MARCAFAC , COALESCE(USUARIONOFACTURABLE,'') AS USUMARCA,CNSFACT,NOAUTORIZACION,
                  CIT.TIPOCOPAGO,CIT.CODUNG
				FROM	DBO.CIT LEFT JOIN DBO.USVGS ON USVGS.IDVARIABLE = 'RIPS_CITSOLOCUMPLIDA'
				-- WHERE	CIT.CUMPLIDA = 1 AND NOT CIT.IDAFILIADO IS NULL) A
				WHERE	CIT.CUMPLIDA = CASE ISNULL(USVGS.DATO,'') WHEN 'SI' THEN 1 ELSE CUMPLIDA END
				AND     NOT CIT.IDAFILIADO IS NULL AND COALESCE(CIT.FACTURABLE,0)=1 
            AND IDAUTSES IS NULL
            ) A
		UNION ALL
      --ONCOLOGIA
		SELECT  A.FECHA, A.IDTERCERO, A.IDPLAN, A.IDTERCEROCA, A.IDPLANCA, A.IDAREA, A.CCOSTO,
				 A.IDSERVICIO, A.CANTIDAD, A.VALOR, A.VALORCOPAGO, A.VALORPCOMP, A.VALOREXCEDENTE, A.DESCUENTO,
				 A.NOADMISION, A.NOPRESTACION, A.NOITEM, A.FACTURADA, A.N_FACTURA, A.PROCEDENCIA, A.IDAFILIADO, A.IDMEDICO,
             A.CLASEORDEN, A.IDPESPECIAL, A.RIESGO, A.NOCOBRABLE,A.IDSEDE,A.MARCAFAC,A.USUMARCA,A.CNSFACT,NOAUTORIZACION,A.TIPOCOPAGO,A.CODUNG
		FROM   (SELECT	CIT.FECHA, CIT.IDCONTRATANTE IDTERCERO, CIT.IDPLAN, CIT.CCOSTO,
						CASE WHEN CIT.IDTERCEROCA IS NULL OR CIT.IDTERCEROCA='' THEN CIT.IDCONTRATANTE ELSE CIT.IDTERCEROCA END IDTERCEROCA,
						CIT.IDPLAN IDPLANCA, CIT.IDAREA, HCATDIMOV.IDSERVICIO,
						COALESCE(HCATDIMOV.CANTIDAD,0)-COALESCE(HCATDIMOV.CANT_DEVUELTA,0) CANTIDAD,
						VLR_UNITARIO VALOR,
						0 VALORCOPAGO,
						0 VALORPCOMP,
						VLR_UNITARIO  VALOREXCEDENTE,
						0 DESCUENTO,
						CIT.CONSECUTIVO NOADMISION, HCATDIMOV.CNSMOV NOPRESTACION, HCATDIMOV.ID NOITEM,
						ISNULL(HCATDIMOV.FACTURADA,0) FACTURADA, HCATDIMOV.N_FACTURA, 'ONCO' PROCEDENCIA, CIT.IDAFILIADO, CIT.IDMEDICO,
                  CIT.CLASEORDEN, COALESCE(CIT.IDPESPECIAL,'') IDPESPECIAL, COALESCE(CIT.RIESGO,'') RIESGO,CASE WHEN  COALESCE(FACTURABLE,0)=1 THEN 0 ELSE 1 END AS NOCOBRABLE,
                  COALESCE(CIT.IDSEDE,'') IDSEDE,COALESCE(HCATDIMOV.MARCAFAC,0)MARCAFAC , COALESCE(HCATDIMOV.USUMARCA,'') AS USUMARCA,HCATDIMOV.CNSFACT,CIT.NOAUTORIZACION,
                  CIT.TIPOCOPAGO,CIT.CODUNG
				FROM	DBO.HCATDIMOV  HCATDIMOV INNER  JOIN DBO.CIT CIT ON HCATDIMOV.CONSECUTIVOCIT=CIT.CONSECUTIVO
				WHERE 	CIT.CUMPLIDA = 1
				AND     NOT CIT.IDAFILIADO IS NULL AND COALESCE(CIT.FACTURABLE,0)=1 )A
		UNION ALL
		-- CITAS - ONCOLOGIA
		SELECT A.FECHA, A.IDTERCERO, A.IDPLAN, A.IDTERCEROCA, A.IDPLANCA, A.IDAREA, A.CCOSTO,
				 A.IDSERVICIO, A.CANTIDAD, A.VALOR, A.VALORCOPAGO, A.VALORPCOMP, A.VALOREXCEDENTE, A.DESCUENTO,
				 A.NOADMISION, A.NOPRESTACION, A.NOITEM, A.FACTURADA, A.N_FACTURA, A.PROCEDENCIA, A.IDAFILIADO, A.IDMEDICO,
             A.CLASEORDEN, A.IDPESPECIAL, A.RIESGO, A.NOCOBRABLE,A.IDSEDE,A.MARCAFAC,A.USUMARCA,A.CNSFACT,NOAUTORIZACION,A.TIPOCOPAGO,A.CODUNG
		FROM   (SELECT	CIT.FECHA, CIT.IDCONTRATANTE IDTERCERO, CIT.IDPLAN, CIT.CCOSTO,
						CASE WHEN CIT.IDTERCEROCA IS NULL OR CIT.IDTERCEROCA='' THEN CIT.IDCONTRATANTE ELSE CIT.IDTERCEROCA END IDTERCEROCA,
						CIT.IDPLAN IDPLANCA, CIT.IDAREA, CIT.IDSERVICIO,
						CASE WHEN COALESCE(CANTIDADC,0)=0 THEN 1 ELSE CANTIDADC END CANTIDAD,
						ISNULL(CIT.VALORTOTAL,0) VALOR,
						ISNULL(CIT.VALORCOPAGO,0) VALORCOPAGO,
						0 VALORPCOMP,
						CASE ISNULL(CIT.VALOREXEDENTE,0) WHEN 0 THEN ISNULL(CIT.VALORTOTAL,0)-ISNULL(CIT.VALORCOPAGO,0) ELSE CIT.VALOREXEDENTE END VALOREXCEDENTE,
						0 DESCUENTO,
						CIT.CONSECUTIVO NOADMISION, CIT.CONSECUTIVO NOPRESTACION, 1 NOITEM,
						ISNULL(CIT.FACTURADA,0) FACTURADA, CIT.N_FACTURA, 'ONCO' PROCEDENCIA, CIT.IDAFILIADO, CIT.IDMEDICO,
                  CIT.CLASEORDEN, COALESCE(CIT.IDPESPECIAL,'') IDPESPECIAL, COALESCE(CIT.RIESGO,'') RIESGO,CASE WHEN  COALESCE(FACTURABLE,0)=1 THEN 0 ELSE 1 END AS NOCOBRABLE,
                  COALESCE(CIT.IDSEDE,'') IDSEDE,COALESCE(MARCAFAC,0)MARCAFAC , COALESCE(USUARIONOFACTURABLE,'') AS USUMARCA,CNSFACT,NOAUTORIZACION,
                  CIT.TIPOCOPAGO,CIT.CODUNG
				FROM	DBO.CIT LEFT JOIN DBO.USVGS ON USVGS.IDVARIABLE = 'RIPS_CITSOLOCUMPLIDA'
				-- WHERE	CIT.CUMPLIDA = 1 AND NOT CIT.IDAFILIADO IS NULL) A
				WHERE	CIT.CUMPLIDA = CASE ISNULL(USVGS.DATO,'') WHEN 'SI' THEN 1 ELSE CUMPLIDA END
				AND     NOT CIT.IDAFILIADO IS NULL AND COALESCE(CIT.FACTURABLE,0)=1 
            AND IDAUTSES IS NOT NULL
            ) A
      UNION ALL
		-- AUTORIZACIONES - AUT
		SELECT	A.FECHA, A.IDTERCERO, A.IDPLAN, A.IDTERCEROCA, A.IDPLANCA, A.IDAREA, A.CCOSTO,
				A.IDSERVICIO, A.CANTIDAD, A.VALOR, COALESCE(Z.VALORCOPAGO,A.VALORCOPAGO) VALORCOPAGO, A.VALORPCOMP, A.VALOREXCEDENTE-COALESCE(Z.VALORCOPAGO,A.VALORCOPAGO) VALOREXCEDENTE, A.DESCUENTO,
				A.NOADMISION, A.NOPRESTACION, A.NOITEM, A.FACTURADA, A.N_FACTURA, A.PROCEDENCIA, A.IDAFILIADO, A.IDMEDICO,
            A.CLASEORDEN, A.IDPESPECIAL, A.RIESGO, A.NOCOBRABLE,COALESCE(A.IDSEDE,'')IDSEDE,MARCAFAC,USUMARCA,CNSFACT,NUMAUTORIZA,A.TIPOCOPAGO,A.CODUNG
		FROM   (  SELECT   AUT.FECHA, AUT.IDCONTRATANTE IDTERCERO, AUTD.IDPLAN, AUTD.CCOSTO,
					CASE WHEN AUTD.IDTERCEROCA IS NULL OR AUTD.IDTERCEROCA='' THEN AUT.IDCONTRATANTE ELSE AUTD.IDTERCEROCA END IDTERCEROCA,
					CASE WHEN AUTD.IDPLAN IS NULL OR AUTD.IDPLAN='' THEN AUT.IDPLAN ELSE AUTD.IDPLAN END IDPLANCA,
					AUT.IDAREA,
					AUTD.IDSERVICIO,
					ISNULL(AUTD.CANTIDAD,0) CANTIDAD,
					ISNULL(AUTD.VALOR,0) VALOR,
					CASE ROW_NUMBER() OVER(PARTITION  BY AUT.NOAUT  ORDER BY AUT.NOAUT) WHEN 1 THEN ISNULL(AUTD.VALORCOPAGO,0) ELSE 0 END VALORCOPAGO,
					0 VALORPCOMP,
					CASE ISNULL(AUTD.VALOREXCEDENTE,0) WHEN 0 THEN (ISNULL(AUTD.VALOR,0)*AUTD.CANTIDAD) ELSE VALOREXCEDENTE END VALOREXCEDENTE,
					0 DESCUENTO,
					AUT.IDAUT NOADMISION, AUT.IDAUT NOPRESTACION, AUTD.NO_ITEM NOITEM,
					ISNULL(AUTD.FACTURADA,0) FACTURADA, AUTD.N_FACTURA,
                'AUT'  PROCEDENCIA, AUT.IDAFILIADO, '' IDMEDICO,
                         COALESCE(AUT.CLASEORDEN,'Normal') CLASEORDEN, COALESCE(AUT.IDPESPECIAL,'') IDPESPECIAL, COALESCE(AUT.RIESGO,'') RIESGO,
                         COALESCE(AUTD.NOCOBRABLE,0) AS NOCOBRABLE,COALESCE(AUT.IDSEDE,'')IDSEDE,
                         COALESCE(AUTD.MARCA,0)MARCAFAC , COALESCE(USUARIOMARCA,'') AS USUMARCA,AUTD.CNSFCT AS CNSFACT ,AUT.NUMAUTORIZA,AUT.TIPOCOPAGO,AUT.CODUNG
			   FROM	DBO.AUT INNER JOIN DBO.AUTD ON AUT.IDAUT = AUTD.IDAUT
			   -- WHERE	AUTD.AUTORIZADO = 1) A
				WHERE  AUT.ESTADO = 'Pendiente') A 
				LEFT JOIN (SELECT AUT.IDAUT, AUT.VALORCOPAGO/COUNT(1) VALORCOPAGO , COUNT(1) CANTS
							  FROM DBO.AUT INNER JOIN DBO.AUTD ON AUT.IDAUT = AUTD.IDAUT 
							  WHERE COALESCE(AUT.VALORCOPAGO,0)>0
							  GROUP BY AUT.IDAUT, AUT.VALORCOPAGO
							 )Z ON Z.IDAUT=A.NOADMISION AND A.PROCEDENCIA='AUT'
	) A	LEFT JOIN DBO.TER ON A.IDTERCEROCA = TER.IDTERCERO
		LEFT JOIN DBO.PPT ON A.IDPLANCA = PPT.IDPLAN AND A.IDTERCEROCA = PPT.IDTERCERO
		LEFT JOIN DBO.SER ON A.IDSERVICIO = SER.IDSERVICIO
		LEFT JOIN DBO.AFU ON A.IDAREA = AFU.IDAREA
		LEFT JOIN DBO.CEN ON A.CCOSTO = CEN.CCOSTO
		LEFT JOIN DBO.PRE ON SER.PREFIJO = PRE.PREFIJO
		LEFT JOIN DBO.PLN ON A.IDPLANCA = PLN.IDPLAN
		LEFT JOIN DBO.AFI ON A.IDAFILIADO = AFI.IDAFILIADO
		LEFT JOIN DBO.MED ON A.IDMEDICO = MED.IDMEDICO




