SELECT DBO.FNK_COLUMNAS_TABLAS('KCEQUI')
SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC    
<i class="fa-solid fa-square-plus"></i>
SELECT DBO.FNK_COLUMNAS_TABLAS('KCEQUI')

SELECT IDEQUIPO, DESCRIPCION, ESTADO, PRUEBA1, PRUEBA2, ESTERIL                            FROM [dbo].[KCEQUI] WHERE ( IDEQUIPO LIKE '%%%%' OR  DESCRIPCION LIKE '%%%%')     ORDER BY IDEQUIPO ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 

BEGIN TRAN 
EXEC SPQ_JSON '{"MODELO":"ESTERILIZA_COL","METODO":"CRUD_KCEQUI","PARAMETROS":{"DATOS":{"PROCESO":"Editar","EQUIPO":"EQUI00002","DESCRIPCION":"AUTOCLAVE 2022","ESTADO":"Inactivo","PRUEBA1":"Fisico","PRUEBA2":"Quimica"}},"USUARIO":"JJIMENEZ"}'
SELECT * FROM KCEQUI
ROLLBACK

SELECT IDEQUIPO,DESCRIPCION  FROM [dbo].[KCEQUI] WHERE (IDEQUIPO LIKE '%%%%' OR  RESULTADO2 LIKE '%%%%' OR  RESULTADO1 LIKE '%%%%' OR  PRUEBA2 LIKE '%%%%' OR  PRUEBA1 LIKE '%%%%' OR  ESTERIL  LIKE '%%%%' OR  DESCRIPCION LIKE '%%%%') AND  ESTADO='Activo'  ORDER BY [dbo].[KCEQUI].[IDEQUIPO] OFFSET (1-1)*12 ROWS  FETCH NEXT 12 ROWS ONLY 

SELECT IDEQUIPO, DESCRIPCION, ESTADO, PRUEBA1, PRUEBA2,                         CASE COALESCE(ESTERIL,0) WHEN 0 THEN 'No' ELSE 'Si' END ESTERIL                            FROM [dbo].[KCEQUI] WHERE ( IDEQUIPO LIKE '%%%%' OR  DESCRIPCION LIKE '%%%%') AND 1=1   ORDER BY IDEQUIPO ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 