
SELECT NROCOMPROBANTE,REFERENCIA3  INTO #A FROM MCPE WHERE COMPROBANTE='06' AND LOTE='REV'

SELECT * FROM MCH WHERE NROCOMPROBANTE='0215900000009458'

SELECT  * INTO #B FROM MCH WHERE NROCOMPROBANTE IN(SELECT REFERENCIA3 FROM #A)

UPDATE #B SET NROCOMPROBANTE=#A.NROCOMPROBANTE FROM #B INNER JOIN #A ON #B.NROCOMPROBANTE=#A.REFERENCIA3

UPDATE #B SET TIPO=CASE WHEN TIPO='DB' THEN 'CR' ELSE 'DB' END

DELETE MCHE WHERE NROCOMPROBANTE IN(SELECT NROCOMPROBANTE FROM #A)

SELECT DBO.FNK_COLUMNAS_TABLAS('MCHE')

INSERT INTO MCHE (NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG,  ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP,  IDSEDE)
SELECT NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG,  ERROR, IDPROVEEDOR, ENPRESUPUESTO, IDOPERACION, ESTADOIMP,  IDSEDE
FROM #B

SELECT * FROM MCP WHERE NROCOMPROBANTE IN(SELECT  NROCOMPROBANTE FROM #A)

ALTER TABLE MCP ENABLE TRIGGER ALL
qrystalos@outlook.es
Ix.Kryst@23
UPDATE MCP SET ANO='2023',MES=12,FECHACONTABLE='31/12/2023' WHERE NROCOMPROBANTE IN(SELECT  NROCOMPROBANTE FROM #A)

UPDATE MCPE WHERE NROCOMPROBANTE='0297000000055825'


SELECT * FROM FCXC WHERE EXISTS(SELECT * FROM FPAGD WHERE FCXC.CNSCXC=FPAGD.CNSCXC) AND INDRECIBIDO=0

UPDATE FCXC SET INDRECIBIDO=1,F_RECIBIDO=FECHACXC WHERE EXISTS(SELECT * FROM FPAGD WHERE FCXC.CNSCXC=FPAGD.CNSCXC) AND INDRECIBIDO=0

