IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNK_CALCULO_VLR_NOVEDAD_NOM' AND XTYPE='TF')
BEGIN
 DROP FUNCTION FNK_CALCULO_VLR_NOVEDAD_NOM
END

GO
CREATE FUNCTION DBO.FNK_CALCULO_VLR_NOVEDAD_NOM(   
@CNSPAGO     VARCHAR(20),   
@CODCONCEPTO VARCHAR(20),   
@NUMDOC      VARCHAR(20),
@FECHAINI    DATETIME,   
@FECHAFIN    DATETIME,
@VALOR_HORA  DECIMAL(15,6))
RETURNS @TABLA  
 TABLE (VALOR_CALCULO     DECIMAL(15,6),
        CANTIDAD          DECIMAL(15,6),
        VALOR_CALCULO100P DECIMAL(15,6))
AS    
BEGIN    
 DECLARE @VALOR_CALCULO     DECIMAL(15,6)
 DECLARE @CANTIDAD          DECIMAL(15,6)
 DECLARE @VALOR_CALCULO100P DECIMAL(15,6)

 SELECT 
        @VALOR_CALCULO     = SUM((NEDIA.HORAS+((NEDIA.MINUTOS+0.00)/60))*NEDIA.FACTOR*@VALOR_HORA),
        @CANTIDAD          = SUM((NEDIA.HORAS+((NEDIA.MINUTOS+0.00)/60))),
        @VALOR_CALCULO100P = SUM((NEDIA.HORAS+((NEDIA.MINUTOS+0.00)/60))*@VALOR_HORA)
 FROM NPER INNER JOIN  
      NEDIA ON (((NPER.TIPOLIQ='PorNomina' AND NPER.CNSPAGO=@CNSPAGO AND NEDIA.FORMALIQUIDACION='PorPago' AND
                  NEDIA.CNSPAGO=NPER.CNSPAGO) OR 
                 (NPER.TIPOLIQ='PorNomina' AND NPER.CNSPAGO=@CNSPAGO AND NEDIA.FORMALIQUIDACION='PorFecha' AND 
                  NEDIA.FECHAINI>=NPER.FECHAINI AND NEDIA.FECHAINI<NPER.FECHAFIN+1)) OR 
                (NPER.TIPOLIQ='PorFechas' AND NPER.CNSPAGO=@CNSPAGO AND  NPER.FECHAINI>=@FECHAINI AND NPER.FECHAFIN<@FECHAFIN+1 AND 
                 NEDIA.FECHAINI>=NPER.FECHAINI AND NEDIA.FECHAINI<NPER.FECHAFIN+1)) INNER JOIN
      NEVE ON NEDIA.IDEVENTO=NEVE.IDEVENTO 
 WHERE NEDIA.NUMDOC=@NUMDOC AND (NEVE.CODCONCEPTO=@CODCONCEPTO or exists(select 1 from NEVEC where NEVEC.IDEVENTO=NEVE.IDEVENTO and IDCONCEPTO=@CODCONCEPTO))
 AND NEDIA.CNSPAGO=@CNSPAGO

 IF @VALOR_CALCULO IS NULL 
 BEGIN
  SET @VALOR_CALCULO100P = 0     
  SET @VALOR_CALCULO     = 0     
  SET @CANTIDAD          = 0
 END
 INSERT INTO @TABLA(CANTIDAD, VALOR_CALCULO, VALOR_CALCULO100P)
 SELECT @CANTIDAD, @VALOR_CALCULO, @VALOR_CALCULO100P
 RETURN
END



