        SELECT IDTERCERO,RAZONSOCIAL,NIT,DV,TIPO_ID,DIRECCION,NATJURIDICA
        ,TER.CIUDAD CIUDADID,CIU.NOMBRE CIUDAD
        ,CIU.DPTO, DEP.NOMBRE DEPARTAMENTO
        ,DEP.PAIS, PAIS.NOMBRE
        ,TELEFONOS,EMAIL
                ,URL_API_SMS=(SELECT TOP 1 OBSERVACION FROM USVGS WHERE IDVARIABLE='URL_API_SMS')
        FROM TER        LEFT JOIN CIU ON CIU.CIUDAD=TER.CIUDAD
            LEFT JOIN DEP ON DEP.DPTO=CIU.DPTO
            LEFT JOIN PAIS ON PAIS.IDPAIS=DEP.PAIS
        WHERE IDTERCERO=dbo.FNK_VALORVARIABLE('IDTERCEROINSTALADO')

      SELECT TER.IDTERCERO,SED.DESCRIPCION RAZONSOCIAL,SED.NIT
        ,TER.DV,TER.TIPO_ID,SED.DIRECCION,TER.NATJURIDICA,SED.CIUDAD CIUDADID
        ,CIU.NOMBRE CIUDAD, CIU.DPTO, DEP.NOMBRE DEPARTAMENTO, DEP.PAIS, PAIS.NOMBRE
        ,SED.TELEFONOS,TER.EMAIL
        ,URL_API_SMS=(SELECT TOP 1 OBSERVACION FROM USVGS WHERE IDVARIABLE='URL_API_SMS')
        ,URL_API_WHATSAPP=(SELECT TOP 1 DATO FROM USVGS WHERE IDVARIABLE='URL_API_WHATSAPP')
        ,(SELECT DATO AS APIKEY, OBSERVACION AS ENGINE FROM USVGS
          WHERE IDVARIABLE='APIKEY_OPENAI' FOR JSON AUTO) APIKEY_OPENAI
        ,IXCOUNTRY=(SELECT TOP 1 DATO FROM USVGS WHERE IDVARIABLE='IXCOUNTRY')
        ,UBEQ.IDSEDE
      FROM USUSU
      INNER JOIN UBEQ ON UBEQ.SYS_COMPUTERNAME=USUSU.SYS_COMPUTERNAME
      INNER JOIN SED ON SED.IDSEDE=UBEQ.IDSEDE
      LEFT JOIN TER ON TER.IDTERCERO=(SELECT TOP 1 IDTERCERO FROM TER WHERE NIT=SED.NIT)
      LEFT JOIN CIU ON CIU.CIUDAD=SED.CIUDAD
      LEFT JOIN DEP ON DEP.DPTO=CIU.DPTO
          LEFT JOIN PAIS ON PAIS.IDPAIS=DEP.PAIS
      WHERE USUARIO='JJIMENEZ'