SELECT TOP 10 * FROM API_LOG WHERE USUARIO='STORRES' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FTR_COL","METODO":"ANULARFAC","PARAMETROS":{"N_FACTURA":"B004-00000010","USUANULA":"AMAZA","OBSANULA":"SE ANULA PARA PRUEBAS"},"USUARIO":"STORRES"}'

{"MODELO":"FTR_COL","METODO":"CRUDFTRD","PARAMETROS":{"DATOS":{"CNSFTR":"0100000311","N_CUOTA":0,"PREFIJO":"009","NOM_PREFIJO":"CONSULTAS E INTERCONSULTAS","IDSERVICIO":"INT007","DESCSERVICIO":null,"ANEXO":"pruebas de soporte","VALOR":120,"CANTIDAD":10,"VR_TOTAL":1200,"CCOSTO":"110","N_FACTURA":"F004-00000002","IDTERCERO":"010000000038","IDPLAN":null,"DESCPLAN":null,"DESCCOSTO":"CONSULTA EXTERNA SAN ISIDRO","VLR_COPAPRO":0}},"USUARIO":"STORRES"}

BEGIN TRAN 
EXEC SPQ_JSON '{"MODELO":"FTR_COL","METODO":"CREARFTR","PARAMETROS":{"DATOS":{"CNSFTR":null,"IDSEDE":"01","N_FACTURA":"","F_FACTURA":"2024-09-06","F_VENCE":"2024-10-06","IDTERCERO":"010000000049","NIT":"70246444","RAZONSOCIAL":"ROBLES  CLAURE DIEGO","IDPLAN":null,"DESCPLAN":null,"CAPITADA":0,"ABONOS":0,"DESCUENTO":0,"TIPOFINAN":null,"OBSERVACION":"PRUEBAS DE FACTURA ADMINISTRATIVA","CONVENIO":null,"MODALIDAD":null,"MES":null,"F_INICIAL":"2024-09-06","F_FINAL":"2024-09-06","COPAGOP":false,"VALORCOPAGO":0,"CONTABILIZADA":0,"NROCOMPROBANTE":null,"ESTDIAN":0,"ESTADO":null,"VALORSERVICIOS":0,"VR_TOTAL":0,"VLRCOPAPRO":0,"PROCEDENCIA":"FINANCIERO","USUARIOFACTU":null,"CP_VLR_SERVICIOS":null,"CP_VLR_COPAGOS":null,"DOCIDAFILIADO":null,"NOMBREAFI":null,"EDAD":null,"SINCNT":true,"VALORMODERADORA":0}},"USUARIO":"STORRES"}'
ROLLBACK
SELECT IDTERCERO, IDPLAN, * FROM FTR WHERE N_fACTURA='F004-00000004'