
SELECT * FROM FIMPDV WHERE IDIMPUESTO='ANTC' AND IDCLASE='001' AND FECHAINI<GETDATE() AND FECHAFIN>GETDATE()


SELECT COUNT(*) FROM FCXCDV FIMPDV WHERE IDIMPUESTO='XX' AND IDCLASE='XX' AND FECHAINI<GETDATE() AND FECHAFIN>GETDATE()

SELECT COUNT(*) FROM FIMPDV WHERE IDIMPUESTO='XX' AND IDCLASE='XX' AND FECHAINI<GETDATE() AND FECHAFIN>GETDATE()

3126199005


SELECT CASE WHEN VALORFACTURA<>SALDONETO THEN 0 ELSE 1 END  FROM FCXCD


SELECT  * FROM FPAG WHERE CNSFPAG='0200000374'


SELECT COUNT(*) FROM FCXCDV WHERE N_FACTURA = 'UV10079'

SELECT CASE WHEN VALORFACTURA<>SALDONETO THEN 0 ELSE 1 END  FROM FCXCD WHERE N_FACTURA = 'UV10079'