IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SPK_RELIQUIDA_FTR' AND type = 'P')
   DROP PROCEDURE SPK_RELIQUIDA_FTR

GO
CREATE PROCEDURE DBO.SPK_RELIQUIDA_FTR
@CNSCXC    VARCHAR(20),
@N_FACTURA VARCHAR(16)
WITH ENCRYPTION
AS  
DECLARE @TOTALND      DECIMAL(14,2)  
DECLARE @TOTALNC      DECIMAL(14,2)  
DECLARE @TOTALNC1     DECIMAL(14,2)  
DECLARE @TOTALPAGOS   DECIMAL(14,2)  
DECLARE @DEDUCCIONES  DECIMAL(14,2)  
DECLARE @TOTALCXC     DECIMAL(14,2)
DECLARE @VLRGLOSAS_A  DECIMAL(14,2)
DECLARE @VLRGLOSAS_R  DECIMAL(14,2)
DECLARE @DEDUCCIONES1 DECIMAL(14,2)  
DECLARE @CNSGLOP      VARCHAR(20)
DECLARE @GPAGOS       DECIMAL(14,2)
DECLARE @VLREXTRA     DECIMAL(14,2)
DECLARE @ITEM         INT
DECLARE @CNSGLO       VARCHAR(20)
DECLARE @TIPO         VARCHAR(1)
DECLARE @VRNOTAS      DECIMAL(14,2)
DECLARE @VRNOTASD     DECIMAL(14,2)
DECLARE @VRPAGOS      DECIMAL(14,2)
DECLARE @VRGLOSAS     DECIMAL(14,2)
DECLARE @VRGLOSAS1    DECIMAL(14,2)
DECLARE @VRGLOSAS_R   DECIMAL(14,2)
DECLARE @VRDEDUC      DECIMAL(14,2)
DECLARE @VRNOTAS1     DECIMAL(14,2)
DECLARE @VRNOTAS2     DECIMAL(14,2)
DECLARE @VRNOTAS3     DECIMAL(14,2)
DECLARE @SALDOINICIAL DECIMAL(14,2)
DECLARE @VRCONCI      DECIMAL(14,2)
DECLARE @VLRCESIONES  DECIMAL(14,2)   --ARS
DECLARE @VLRCESION    DECIMAL(14,2)   --ARS
DECLARE @GLOCONCIACEP DECIMAL(14,2)
DECLARE @VR_CONCI     DECIMAL(14,2)=0
DECLARE @SALDONETOFCXCD DECIMAL(14,2), @SALDONETOFCXCDV DECIMAL(14,2), @SALDONETOFCXCDV_C DECIMAL(14,2)
DECLARE @VRPAGOS1 DECIMAL(14,2), @VRDEDUC1 DECIMAL(14,2), @SALDOPOS DECIMAL(14,2), @SALDONEG DECIMAL(14,2)
DECLARE @IDFCONCI VARCHAR(20),  @VLRRECUPERAR DECIMAL(14,2),@VLRLEVANTADO DECIMAL(14,2),@SALDONETO DECIMAL(14,2)
BEGIN 
   SET @VLRCESIONES=0                                                               
   SET @VLRCESION=0                                                               
   --Print 'VOLVIENDO A CEROS LA CXC = '+@CNSCXC
   UPDATE FCXC SET SALDO = 0, DEDUCCIONES = 0, VALORCXCNETO = 0, SALDONETO = 0, VLRPAGOS = 0,
          VLRNOTADB = 0, VLRNOTACR = 0, VLRGLOSAS = 0, VLRGLOSAS_R = 0, VLREXTRA = 0
   WHERE  FCXC.CNSCXC = @CNSCXC
      
   UPDATE FCXCD SET DEDUCCIONES = 0, VALORFACTURANETO = 0, VLRPAGOS = 0, VLRNOTADB = 0,
                  VLRNOTACR = 0, VLRGLOSAS = 0, SALDO = 0, SALDONETO = 0, VLRGLOSAS_R = 0,
                  VLREXTRA  = 0, VLRLEVANTADO=0
   WHERE FCXCD.CNSCXC    = @CNSCXC 
   AND   FCXCD.N_FACTURA = @N_FACTURA

   SELECT @TOTALND = SUM(FNOT.VR_TOTAL) FROM FNOT
   WHERE  FNOT.CLASE = 'D'   
   AND    FNOT.N_FACTURA = @N_FACTURA
   AND    FNOT.CNSCXC    = @CNSCXC
   AND    FNOT.CERRADA   = 1
   AND    FNOT.ESTADO    <> 'A'
      
   IF @TOTALND IS NULL  
      SELECT @TOTALND = 0  
      
   SELECT @TOTALNC = SUM(FNOT.VR_TOTAL) FROM FNOT
   WHERE  CLASE = 'C'   
   AND    FNOT.N_FACTURA = @N_FACTURA
   AND    FNOT.CNSCXC    = @CNSCXC
   AND    FNOT.CERRADA   = 1
   AND    FNOT.PROCEDENCIA <> 'CARTERA' 
   AND    COALESCE(FNOT.ESTADO,'')= 'O'
      
   IF @TOTALNC IS NULL  
      SELECT @TOTALNC = 0  
      
   --PRINT 'NOTAS DIF DE CARTERA '+ STR(@TOTALNC)      
      
   SELECT @TOTALNC1 = SUM(FNOT.VR_TOTAL) FROM FNOT
   WHERE  CLASE = 'C'   
   AND    FNOT.N_FACTURA   = @N_FACTURA
   AND    FNOT.CERRADA     = 1
   AND    FNOT.PROCEDENCIA = 'CARTERA' 
   AND    COALESCE(FNOT.ESTADO,'')= 'O'
      
   IF @TOTALNC1 IS NULL  
      SELECT @TOTALNC1 = 0  
     
   --PRINT 'NOTAS DE CARTERA '+ STR(@TOTALNC1)      
    
   SELECT @TOTALNC = @TOTALNC + @TOTALNC1
   --PRINT 'TOTAL NOTAS CREDITO '+ STR(@TOTALNC)             
      
   SELECT @TOTALPAGOS  = SUM(FPAGD.VALORPAGO) 
   FROM FPAGD INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG
   WHERE  FPAGD.N_FACTURA = @N_FACTURA
   AND    FPAGD.CNSCXC    = @CNSCXC
   AND    FPAGD.CERRADO = 1
   AND    COALESCE(FPAG.ESTADO,'')<>'Inactivo'  
   AND    COALESCE(FPAGD.ESTADO,'')<>'Retirada'
      
   IF @TOTALPAGOS IS NULL  
      SELECT @TOTALPAGOS = 0   
         
   IF  dbo.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT')='ARS'
   BEGIN 
      SELECT @TOTALPAGOS  = SUM(FLEGD.VALORPAGO) FROM FLEGD
      WHERE  FLEGD.N_FACTURA = @N_FACTURA
      AND    FLEGD.ESTADO = 1  
         
      IF @TOTALPAGOS IS NULL  
         SELECT @TOTALPAGOS = 0 
      --PRINT 'VALOR PAGO ARS='+STR(@TOTALPAGOS)   
      SELECT @VLRCESIONES  = SUM(FCESCXC.VALORCESION) FROM FCESCXC
      WHERE  FCESCXC.N_FACTURA = @N_FACTURA
      AND    FCESCXC.ESTADO = 1  
      
      IF @VLRCESIONES IS NULL  
         SELECT @VLRCESIONES = 0  
      --PRINT 'VALOR SECIONES ARS='+STR(@VLRCESIONES)             
   END
      
   --PRINT 'TOTAL PAGOS = '+ STR(@TOTALPAGOS)
   --PRINT 'VALOR SECIONES ARS = '+ STR(@VLRCESIONES)
       
   SELECT @VLREXTRA = SUM(FPAGD.VLREXTRA) 
   FROM FPAGD INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG
   WHERE  FPAGD.N_FACTURA = @N_FACTURA
   AND    FPAGD.CNSCXC    = @CNSCXC
   AND    FPAGD.CERRADO = 1  
   AND    COALESCE(FPAG.ESTADO,'')<>'Inactivo' 
   AND    COALESCE(FPAGD.ESTADO,'')<>'Retirada' 
     
   IF @VLREXTRA IS NULL  
      SELECT @VLREXTRA = 0       
      
   --PRINT 'VALOR EXTRA =' + STR(@VLREXTRA)     
    
   -- CALCULO DE GLOSAS EN AUDITORIA
   SELECT @VLRGLOSAS_A = SUM(VLRGLOSA) FROM FGLO 
   WHERE  FGLO.N_FACTURA = @N_FACTURA  
   AND    FGLO.CNSCXC    = @CNSCXC   
   AND    CERRADA        = 0
   AND    ESTADO         <> 'A'
   --AND    EXISTS (SELECT 1 FROM FGLOI INNER JOIN FGLOID ON FGLOI.CNSGLOI=FGLOID.CNSGLOI WHERE FGLOID.CNSGLO=FGLO.CNSGLO AND ISNULL(FGLOI.RADICADO,0)=0)

   IF @VLRGLOSAS_A IS NULL  
      SELECT @VLRGLOSAS_A = 0   
      
   --PRINT 'GLOSAS EN AUDITORIA = '+ STR(@VLRGLOSAS_A)
    
   DECLARE @SALDOSINEST DECIMAL(14,2)
   SELECT  @SALDOSINEST = SUM(SALDO) 
   FROM    FGLO 
   WHERE   FGLO.N_FACTURA  = @N_FACTURA
   AND     FGLO.CNSCXC     = @CNSCXC   
   AND     CERRADA         = 1
   AND     ESTADO          <> 'A'
   
   --PRINT 'SALDO EN GLOSAS CERRADAS ANTES DE CALCULO=' + STR(@SALDOSINEST)
            
   SELECT @DEDUCCIONES = SUM(FPAGD.VLRIMPUESTO) 
   FROM FPAGD INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG
   WHERE  FPAGD.N_FACTURA = @N_FACTURA
   AND    FPAGD.CNSCXC    = @CNSCXC   
   AND    FPAGD.CERRADO = 1
   AND    COALESCE(FPAG.ESTADO,'')<>'Inactivo'  
   AND    COALESCE(FPAGD.ESTADO,'')<>'Retirada' 

     IF DBO.FNK_VALORVARIABLE('ANTIPO_IMP_RESTA_FTR')='SI'
     BEGIN
        SELECT @DEDUCCIONES=COALESCE(@DEDUCCIONES,0) +SUM(VALOR) FROM FTRI WHERE N_FACTURA=@N_FACTURA
     END
   
   SELECT @DEDUCCIONES1   = SUM(COALESCE(FPAGD.VLRDTOFIN,0)+COALESCE(VLROTROSDCTOS,0)) 
   FROM FPAGD INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG
   WHERE  FPAGD.N_FACTURA = @N_FACTURA
   AND    FPAGD.CNSCXC    = @CNSCXC   
   AND    FPAGD.CERRADO   = 1  
   AND    COALESCE(FPAG.ESTADO,'')<>'Inactivo'  
   AND    COALESCE(FPAGD.ESTADO,'')<>'Retirada'
   
   IF @DEDUCCIONES IS NULL
      SELECT @DEDUCCIONES = 0 
       
   IF @DEDUCCIONES1 IS NULL
      SELECT @DEDUCCIONES1 = 0 
   
   --PRINT 'DEDUCCIONES IMP = ' + STR(@DEDUCCIONES)
   --PRINT 'DEDUCCIONES DTO FIN= ' + STR(@DEDUCCIONES1)
    
   SELECT @DEDUCCIONES = @DEDUCCIONES + @DEDUCCIONES1
   --PRINT 'ENTRO A CURSOR DE GLOSAS'

   -- BEGIN ACTUALIZACION DE SALDOS DE GLOSA
   DECLARE G_CURSOR CURSOR FOR    
   SELECT COALESCE(CNSGLO,'')  FROM FGLO
   WHERE  CERRADA = 1 AND N_FACTURA = @N_FACTURA AND CNSCXC = @CNSCXC
   OPEN G_CURSOR    
   FETCH NEXT FROM G_CURSOR    
   INTO @CNSGLOP
   WHILE @@FETCH_STATUS = 0    
   BEGIN               
      SELECT @GPAGOS = COALESCE(SUM( FPAGD.VALORPAGO + VLRGLOSA + VLRIMPUESTO + COALESCE(VLRDTOFIN,0)+COALESCE(VLROTROSDCTOS,0)) ,0) 
      FROM   FPAGD  INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG
      WHERE  N_FACTURA = @N_FACTURA      
      AND    CNSCXC    = @CNSCXC
      --AND    CLASE     = 'G' OR CLASE = 'R'
      AND    COALESCE(CNSGLO,'') = @CNSGLOP
      AND    FPAGD.CERRADO   = 1
      AND    COALESCE(FPAG.ESTADO,'')<>'Inactivo' 
      AND    COALESCE(FPAGD.ESTADO,'')<>'Retirada' 
      IF @GPAGOS IS NULL
         SELECT @GPAGOS = 0

      --valor en conciliacion de la fglo que fueron aceptados
      SELECT @GLOCONCIACEP =SUM(VLRACEPTADO) FROM FCONCID WHERE N_FACTURA = @N_FACTURA AND CNSGLO = @CNSGLOP AND ESTADO = 'Cerrada'
      IF @GLOCONCIACEP IS NULL
         SELECT @GLOCONCIACEP = 0 
      --PRINT 'PAGOS EN GLOSA ('+@CNSGLOP+')='+STR(@GPAGOS)
      UPDATE FGLO SET ABONADO = VLRACEPTADO + @GPAGOS + @GLOCONCIACEP
      WHERE  COALESCE(CNSGLO,'') = @CNSGLOP
      
      UPDATE FGLO SET SALDO = VLRGLOSA - ABONADO 
      WHERE  COALESCE(CNSGLO,'') = @CNSGLOP

      IF ( SELECT SALDO FROM FGLO WHERE  COALESCE(CNSGLO,'') = @CNSGLOP ) < 0
      BEGIN
          UPDATE FGLO SET SALDO = 0
      WHERE  COALESCE(CNSGLO,'') = @CNSGLOP
      END

      FETCH NEXT FROM  G_CURSOR    
      INTO @CNSGLOP
   END
   CLOSE G_CURSOR
   DEALLOCATE G_CURSOR
   
   -- END   ACTUALIZACION DE SALDOS DE GLOSA  
       
   -- CALCULO DE GLOSAS A RECUPERAR   
   SELECT @VLRGLOSAS_R = COALESCE(SUM(CASE WHEN SALDO<=0 THEN 0 ELSE  SALDO END),0) FROM FGLO 
   WHERE  FGLO.N_FACTURA = @N_FACTURA
   AND    FGLO.CNSCXC    = @CNSCXC   
   AND    CERRADA        = 1
   AND    ESTADO         <> 'A'
   AND    NOT EXISTS(SELECT * FROM FCONCID WHERE CNSGLO=FGLO.CNSGLO AND N_FACTURA=FGLO.N_FACTURA)
   AND    EXISTS (SELECT 1 FROM FGLOI INNER JOIN FGLOID ON FGLOI.CNSGLOI=FGLOID.CNSGLOI WHERE FGLOID.CNSGLO=FGLO.CNSGLO AND FGLOI.RADICADO=1)

   SELECT @VLRGLOSAS_R= COALESCE(@VLRGLOSAS_R,0)+COALESCE(SUM(VLRRECUPERAR),0) FROM FCONCID
   WHERE FCONCID.N_FACTURA=@N_FACTURA
   AND   FCONCID.CNSCXC=@CNSCXC
   AND   FCONCID.ESTADO='Cerrada'
   AND   EXISTS(SELECT * FROM FGLO WHERE CNSGLO=FGLO.CNSGLO AND N_FACTURA=FGLO.N_FACTURA)
   
   IF @VLRGLOSAS_R IS NULL 
   BEGIN 
      SELECT @VLRGLOSAS_R = 0   
   END
   PRINT 'BUSCO EL VALOR LEVANTADO'
   SELECT @VLRLEVANTADO=SUM(COALESCE(VLRLEVANTADO,0)) FROM FCXCDV WHERE N_FACTURA=@N_FACTURA AND CNSCXC=@CNSCXC AND TIPO<>'F'
   IF COALESCE(@VLRLEVANTADO,0)<=0
   BEGIN
      SELECT @VLRLEVANTADO=0
   END 
   PRINT 'VALOR LEVANTADADO '+STR(COALESCE(@VLRLEVANTADO,0))
   PRINT 'ACA HAGO EL UPDATE GLOSAS A RECUPERAR = '+STR(@VLRGLOSAS_R)
   
   UPDATE FCXCD SET DEDUCCIONES = @DEDUCCIONES, VLRPAGOS = @TOTALPAGOS, VLRNOTADB = @TOTALND,
                    VLRNOTACR = @TOTALNC, VLRGLOSAS = @VLRGLOSAS_A, VLRGLOSAS_R = @VLRGLOSAS_R,
                    VLREXTRA  = @VLREXTRA,
                    VLRFCES   = @VLRCESIONES,
                    VLRLEVANTADO=@VLRLEVANTADO
   WHERE FCXCD.N_FACTURA  = @N_FACTURA
   AND   FCXCD.CNSCXC     = @CNSCXC   
    
   UPDATE FCXCD SET VALORFACTURANETO = VALORFACTURA - DEDUCCIONES,
          SALDO = VALORFACTURA - VLRNOTACR - VLRGLOSAS + VLRNOTADB - VLRPAGOS-@VLRCESIONES,
          SALDONETO = VALORFACTURA - VLRNOTACR - VLRGLOSAS + VLRNOTADB - DEDUCCIONES - VLRPAGOS-@VLRCESIONES
   WHERE  FCXCD.N_FACTURA = @N_FACTURA
   AND    FCXCD.CNSCXC    = @CNSCXC   
   
   SELECT @SALDONETOFCXCD = COALESCE(SALDONETO,0)
   FROM   FCXCD
   WHERE  FCXCD.N_FACTURA = @N_FACTURA
   AND    FCXCD.CNSCXC    = @CNSCXC  

   PRINT '@SALDONETOFCXCD =='+STR(@SALDONETOFCXCD)

   IF @SALDONETOFCXCD < 0
   BEGIN
      IF DBO.FNK_VALORVARIABLE('PERMITESALDONEGATIVO')<>'SI'
      BEGIN
         SELECT @SALDONETOFCXCD = 0
         UPDATE FCXCD SET SALDONETO = 0
         WHERE  FCXCD.N_FACTURA = @N_FACTURA
         AND    FCXCD.CNSCXC    = @CNSCXC  
      END 
   END   

    IF EXISTS (SELECT 1 FROM FTR WHERE  N_FACTURA = @N_FACTURA AND ESTADO='A')
   BEGIN
     
        
         UPDATE FCXCD SET SALDONETO = 0, SALDO=0
         WHERE  FCXCD.N_FACTURA = @N_FACTURA
         AND    FCXCD.CNSCXC    = @CNSCXC  
      
   END   
            
   --PRINT 'SALDO DESP DE CALCULO=' + STR(@VLRGLOSAS_R)    
   --PRINT 'ACABO DE ACTUALIZAR FCXCD'
   SELECT @TOTALCXC    = SUM(VALORFACTURA),
          @DEDUCCIONES = SUM(DEDUCCIONES), 
          @TOTALPAGOS  = SUM(VLRPAGOS),
          @TOTALND     = SUM(VLRNOTADB),
          @TOTALNC     = SUM(VLRNOTACR),     
          @VLRGLOSAS_A = SUM(VLRGLOSAS),
          @VLRGLOSAS_R = SUM(VLRGLOSAS_R),
          @VLREXTRA    = SUM(VLREXTRA)+ SUM(VLRFCES)
   FROM   FCXCD
   WHERE  CNSCXC = @CNSCXC
 
   IF @TOTALCXC IS NULL
      SELECT @TOTALCXC = 0
   IF @TOTALPAGOS IS NULL
      SELECT @TOTALPAGOS = 0
   IF @TOTALND IS NULL
      SELECT @TOTALND = 0
   IF @TOTALNC IS NULL
      SELECT @TOTALNC = 0
   IF @VLRGLOSAS_A IS NULL
      SELECT @VLRGLOSAS_A = 0
   IF @VLRGLOSAS_R IS NULL
      SELECT @VLRGLOSAS_R = 0
   IF @DEDUCCIONES IS NULL
      SELECT @DEDUCCIONES = 0
   IF @VLREXTRA IS NULL
      SELECT @VLREXTRA = 0
   
   UPDATE FCXC SET  VALORCXC     = @TOTALCXC,
                    VALORCXCNETO = @TOTALCXC - @DEDUCCIONES  ,
                    VLRPAGOS     = @TOTALPAGOS,
                    VLRNOTADB    = @TOTALND,  
                    VLRNOTACR    = @TOTALNC,   
                    DEDUCCIONES  = @DEDUCCIONES, 
                    VLRGLOSAS    = @VLRGLOSAS_A,
                    VLRGLOSAS_R  = @VLRGLOSAS_R,   
                    VLREXTRA     = @VLREXTRA
   WHERE CNSCXC = @CNSCXC  
   
   UPDATE FCXC SET  SALDO     = VALORCXC     + @TOTALND - @TOTALNC - @TOTALPAGOS -@VLRGLOSAS_A ,  
                    SALDONETO = VALORCXCNETO + @TOTALND - @TOTALNC - @TOTALPAGOS -@VLRGLOSAS_A 
   WHERE CNSCXC = @CNSCXC  

   PRINT 'SALDOS DE PEDAZOS DE CARTERA FACTURA'
   SELECT @VRGLOSAS_R = 0   
   
   
   --PRINT 'ANTES DE CURSOR' 
   DECLARE SD_CURSOR CURSOR FOR    
   SELECT FCXCDV.N_FACTURA, FCXCDV.ITEM, FCXCDV.TIPO, COALESCE(FCXCDV.CNSGLO,'')
   FROM   FCXCDV 
   WHERE  CNSCXC    = @CNSCXC     
   AND    N_FACTURA = @N_FACTURA
   OPEN   SD_CURSOR    
   FETCH NEXT FROM SD_CURSOR    
   INTO @N_FACTURA, @ITEM, @TIPO, @CNSGLO
   WHILE @@FETCH_STATUS = 0    
   BEGIN 
      PRINT 'ENTRE ITEM='+CONVERT(VARCHAR,@ITEM)+ '@TIPO='+@TIPO
      /*SI ENTRA DESPUES DE ESTOS DOS IF SE CONVIERTE EL SALDO DE LA PARTE FCXCDV EN 0 YA QUE FUE CONCILIADA*/
      
      IF (SELECT COUNT(*) FROM FCXCDV WHERE N_FACTURA = @N_FACTURA AND CNSCXC = @CNSCXC  AND TIPO = 'C') > 0
      BEGIN
         IF (SELECT COUNT(*) FROM FCONCID WHERE  ITEM_FCXCDV = @ITEM AND ESTADO = 'Cerrada' AND TIPO = @TIPO AND TIPO<>'C') >0
         BEGIN
            IF (SELECT MAX(SALDONETO) FROM FCONCID WHERE  ITEM_FCXCDV = @ITEM AND ESTADO = 'Cerrada' AND TIPO = @TIPO AND TIPO<>'C')
              <(SELECT SALDOINICIAL FROM FCXCDV WHERE FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA  AND FCXCDV.ITEM = @ITEM)
              AND @TIPO='F'
            BEGIN
                SELECT @VR_CONCI=SALDONETO-VLRACEPTADO FROM FCONCID WHERE  ITEM_FCXCDV = @ITEM AND ESTADO = 'Cerrada' AND TIPO = @TIPO AND TIPO<>'C'
            END
            ELSE
            BEGIN
                UPDATE FCXCDV SET SALDONETO = 0
                WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
                AND    FCXCDV.ITEM = @ITEM

                FETCH NEXT FROM SD_CURSOR    
                INTO @N_FACTURA, @ITEM, @TIPO, @CNSGLO
                CONTINUE
            END
         END
      END                  
      IF @TIPO = 'F'       
      BEGIN
         PRINT 'ES TIPO FACTURA'
         PRINT 'N_FACTURA ='+@N_FACTURA  
         PRINT 'CNSCXC= '+ @CNSCXC
         SELECT @VRNOTAS = COALESCE(SUM(FNOT.VR_TOTAL),0) FROM FNOT
         WHERE  FNOT.N_FACTURA = @N_FACTURA  
         AND    FNOT.CNSCXC    = @CNSCXC   
         AND    FNOT.CERRADA   = 1 
         AND    FNOT.CLASE     = 'C'    
         AND    FNOT.PROCEDENCIA IN('NOTAS','CONCILIA')
         AND    FNOT.ESTADO      <> 'A'
         AND    COALESCE(FNOT.CNSGLO,'') =''
         PRINT  '@VRNOTAS='+CAST(@VRNOTAS AS VARCHAR(20))
            
         SELECT @VRNOTAS2 = COALESCE(SUM(FNOT.VR_TOTAL),0) FROM FNOT
         WHERE  FNOT.N_FACTURA   = @N_FACTURA  
         AND    FNOT.CERRADA     = 1 
         AND    FNOT.CLASE       = 'C'    
         AND    FNOT.PROCEDENCIA = 'CARTERA' 
         AND    FNOT.ESTADO      <> 'A'
         PRINT  '@VRNOTAS2='+CAST(@VRNOTAS2 AS VARCHAR(20))
            
         PRINT 'LE SUMO A LAS NOTAS CREDITOS LAS NOTAS GENERADAS EN AUDITORIA QUE NO PROVENGAN DE OTRA GLOSA SI NO DE LA FACTURA'
                  
         SELECT @VRNOTAS1 = COALESCE(SUM(FNOT.VR_TOTAL),0)
         FROM   FNOT, FGLO
         WHERE  FNOT.PROCEDENCIA = 'AUDITORIA'
         AND    COALESCE(FGLO.CNSGLO,'')  = COALESCE(FNOT.CNSGLO,'')
         AND    (FGLO.CNSGLO_O    IS NULL OR FGLO.CNSGLO_O = '')
         --AND    FGLO.ESTADO    <> 'A'
         AND    FNOT.N_FACTURA = @N_FACTURA  
         AND    FNOT.CNSCXC    = @CNSCXC   
         AND    FNOT.CERRADA   = 1 
         AND    FNOT.CLASE     = 'C'   
         AND    FNOT.ESTADO    <> 'A' 
         PRINT  '@VRNOTAS1 AUDITORIA='+CAST(@VRNOTAS1 AS VARCHAR(20))          
         
         SELECT @VRNOTAS =  COALESCE(@VRNOTAS,0) + COALESCE(@VRNOTAS1,0) + COALESCE(@VRNOTAS2,0) + COALESCE(@VR_CONCI,0) --+ @VRNOTAS3
         PRINT  'SUMA DE NOTAS @VRNOTAS='+CAST(@VRNOTAS AS VARCHAR(20))
         
         SELECT @VRNOTASD = COALESCE(SUM(FNOT.VR_TOTAL),0) FROM FNOT
         WHERE  FNOT.N_FACTURA = @N_FACTURA  
         AND    FNOT.CNSCXC    = @CNSCXC   
         AND    FNOT.CERRADA   = 1 
         AND    FNOT.CLASE     = 'D'
         AND    FNOT.ESTADO      <> 'A'
         AND    (FNOT.PROCEDENCIA = 'NOTAS' OR FNOT.PROCEDENCIA = 'CARTERA' OR FNOT.PROCEDENCIA='CONCILIA')
		 AND    COALESCE(FNOT.CNSGLO,'') =''
         PRINT  '@VRNOTASD='+CAST(@VRNOTASD AS VARCHAR(20))
           
         SELECT @VRPAGOS = COALESCE(SUM(FPAGD.VALORPAGO+COALESCE(VLROTROSDCTOS,0)),0), 
                @VRDEDUC = COALESCE(SUM(COALESCE(FPAGD.VLRIMPUESTO,0)+ COALESCE(FPAGD.VLRDTOFIN,0)),0)
         FROM   FPAGD  INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG
         WHERE  FPAGD.CERRADO    = 1
         AND    COALESCE(FPAG.ESTADO,'')<>'Inactivo' 
         AND    (FPAGD.CLASE      = 'F' OR FPAGD.CLASE IS NULL )
         AND    FPAGD.CNSCXC     = @CNSCXC  
         AND    FPAGD.N_FACTURA  = @N_FACTURA
         AND    COALESCE(FPAGD.ESTADO,'')<>'Retirada'   
         PRINT '@VRPAGOS='+CAST(@VRPAGOS AS VARCHAR(20))
         PRINT '@VRDEDUC='+CAST(@VRDEDUC AS VARCHAR(20))
            
         IF dbo.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT')='ARS'
         BEGIN 
            SELECT @VRPAGOS  = SUM(FLEGD.VALORPAGO) FROM FLEGD
            WHERE  FLEGD.N_FACTURA = @N_FACTURA
            AND    FLEGD.ESTADO = 1  
         
            IF @VRPAGOS IS NULL  
                 SELECT @VRPAGOS = 0 
            --PRINT 'VALOR PAGO ARS='+STR(@VRPAGOS)
            
            SELECT @VLRCESION  = SUM(FCESCXC.VALORCESION) FROM FCESCXC
            WHERE  FCESCXC.N_FACTURA = @N_FACTURA
            AND    FCESCXC.ESTADO = 1  
               
            IF @VLRCESION IS NULL  
               SELECT @VLRCESION = 0  
            
         END                      
         IF @VLRCESION IS NULL  
            SELECT @VLRCESION = 0    
         PRINT 'VALOR SECIONES ARS='+STR(@VLRCESION)             
         SELECT @VRGLOSAS      = SUM(COALESCE(FGLO.VLRGLOSA,0)) FROM FGLO 
         WHERE  FGLO.N_FACTURA = @N_FACTURA
         AND    FGLO.CNSCXC    = @CNSCXC   
         AND    FGLO.CERRADA   = 0
         AND    COALESCE(FGLO.CNSGLO_O,'')  = ''
         AND    FGLO.ESTADO    <> 'A'
         AND    PROCEDENCIA <> 'Recaudo'
         PRINT '@VRGLOSAS='    +CAST(@VRGLOSAS AS VARCHAR(20)   )
                  
         IF @VRGLOSAS IS NULL
            SELECT @VRGLOSAS = 0
         
         SELECT @VRGLOSAS1 = SUM(FGLO.VLRGLOSA) FROM FGLO 
         WHERE  FGLO.N_FACTURA = @N_FACTURA
         AND    FGLO.CERRADA   = 0
         AND    COALESCE(FGLO.CNSGLO_O,'')  = ''
         AND    FGLO.ESTADO    <> 'A'
         AND    PROCEDENCIA = 'Recaudo'
         PRINT '@VRGLOSAS1='    +CAST(@VRGLOSAS1 AS VARCHAR(20))
           
         IF @VRGLOSAS1 IS NULL
            SELECT @VRGLOSAS1 = 0
          
         SELECT @VRGLOSAS = @VRGLOSAS + @VRGLOSAS1  
         PRINT 'SUMA ANTERIORES @VRGLOSAS='+CAST(@VRGLOSAS AS VARCHAR(20))
              
         SELECT @VRGLOSAS_R    = COALESCE(SUM(FGLO.VLRRECUPERAR),0) FROM FGLO 
         WHERE  FGLO.N_FACTURA = @N_FACTURA
         AND    FGLO.CNSCXC    = @CNSCXC   
         AND    FGLO.CERRADA   = 1
         AND    COALESCE(FGLO.CNSGLO_O,'')  = ''
         AND    FGLO.ESTADO    <> 'A'

         PRINT  'GLOSAS R='+STR(@VRGLOSAS_R)

         SELECT @SALDONETO=COALESCE(SALDOINICIAL,0) - COALESCE(@VRNOTAS,0) -  COALESCE(@VRPAGOS,0) -  COALESCE(@VRGLOSAS,0) -  COALESCE(@VRGLOSAS_R,0) -  COALESCE(@VRDEDUC,0) +  COALESCE(@VRNOTASD,0) -  COALESCE(@VLRCESION,0) 
          FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
         AND    FCXCDV.ITEM = @ITEM
         AND COALESCE(CNSGLO,'')=CASE WHEN COALESCE(@CNSGLO,'')='' THEN COALESCE(FCXCDV.CNSGLO,'') ELSE @CNSGLO END

		 PRINT '@VRNOTAS='+STR(@VRNOTAS) + ', @VRPAGOS='+STR(@VRPAGOS) + ', @VRGLOSAS='+STR(@VRGLOSAS) + ', @VRGLOSAS_R='+STR(@VRGLOSAS_R) + ', @VRDEDUC='+STR(@VRDEDUC) + ', @VRNOTASD='+STR(@VRNOTASD) + ', @VLRCESION='+STR(@VLRCESION)
		 ---  COALESCE(@VRPAGOS,0) -  COALESCE(@VRGLOSAS,0) -  COALESCE(@VRGLOSAS_R,0) -  COALESCE(@VRDEDUC,0) +  COALESCE(@VRNOTASD,0) -  COALESCE(@VLRCESION,0) 

         PRINT '@SALDONETO == '+RTRIM(LTRIM(STR(@SALDONETO)))

         UPDATE FCXCDV 
         SET    SALDONETO = COALESCE(SALDOINICIAL,0) - COALESCE(@VRNOTAS,0) -  COALESCE(@VRPAGOS,0) -  COALESCE(@VRGLOSAS,0) -  COALESCE(@VRGLOSAS_R,0) -  COALESCE(@VRDEDUC,0) +  COALESCE(@VRNOTASD,0) -  COALESCE(@VLRCESION,0) + ISNULL(VLRLEVANTADO,0)
         WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
         AND    FCXCDV.ITEM = @ITEM
         --AND COALESCE(CNSGLO,'')=CASE WHEN COALESCE(@CNSGLO,'')='' THEN COALESCE(FCXCDV.CNSGLO,'') ELSE @CNSGLO END

         IF ( SELECT SALDONETO 
              FROM   FCXCDV 
              WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
              AND    FCXCDV.ITEM = @ITEM ) < 0
         BEGIN
            UPDATE FCXCDV SET SALDONETO = 0 
            WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
            AND    FCXCDV.ITEM = @ITEM
         END   
           
         SELECT @SALDONETOFCXCDV_C = SALDONETO FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
         AND    FCXCDV.ITEM = @ITEM

         IF @SALDONETOFCXCD = 0 AND @SALDONETOFCXCDV_C > 0
         BEGIN
             UPDATE FCXCDV 
             SET    SALDONETO = 0
             WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
             AND    FCXCDV.ITEM = @ITEM
         END
      END
      ELSE
      BEGIN
         SELECT @VRNOTAS = 0, @VRGLOSAS_R = 0, @VRNOTASD = 0, @VRPAGOS = 0, @VRGLOSAS = 0, @VRDEDUC = 0, @VLRCESION = 0,@VLRLEVANTADO=0                 
         IF @TIPO <> 'C'
         BEGIN 
            PRINT '@TIPO='+@TIPO+'//@CNSGLO='+@CNSGLO+'//@ITEM ='+CONVERT(VARCHAR,@ITEM)+'//@SALDONETOFCXCD='+CONVERT(VARCHAR,@SALDONETOFCXCD)

            SELECT @VRNOTAS = COALESCE(SUM(FNOT.VR_TOTAL),0)
            FROM   FNOT
            WHERE  FNOT.N_FACTURA   = @N_FACTURA  
            AND    FNOT.CERRADA     = 1 
            AND    FNOT.CLASE       = 'C'    
            AND    FNOT.PROCEDENCIA = 'CONCILIA' 
            AND    FNOT.CNSGLO      = @CNSGLO
            AND    FNOT.ESTADO      <>'A'

            SELECT @VRNOTAS =COALESCE(@VRNOTAS,0)+COALESCE(SUM(FNOT.VR_TOTAL),0)
            FROM   FNOT
            WHERE  FNOT.N_FACTURA   = @N_FACTURA  
            AND    FNOT.CERRADA     = 1 
            AND    FNOT.CLASE       = 'C'    
            AND    FNOT.PROCEDENCIA = 'AJUSTE' 
            AND    FNOT.CNSGLO      = @CNSGLO
            AND    FNOT.ESTADO      <>'A'
			
			   SELECT @VRNOTAS =COALESCE(@VRNOTAS,0)-COALESCE(SUM(FNOT.VR_TOTAL),0)-- PARA QUE CUANDO SE GENERE una nota debito la tenga encuenta de conciliacion
            FROM   FNOT
            WHERE  FNOT.N_FACTURA   = @N_FACTURA  
            AND    FNOT.CERRADA     = 1 
            AND    FNOT.CLASE       = 'D'    
            AND    FNOT.PROCEDENCIA = 'CONCILIA' 
            AND    FNOT.CNSGLO      = @CNSGLO
            AND    FNOT.ESTADO      <>'A'
			   SELECT @VRNOTAS =COALESCE(@VRNOTAS,0)-COALESCE(SUM(FNOT.VR_TOTAL),0)
            FROM   FNOT
            WHERE  FNOT.N_FACTURA   = @N_FACTURA  
            AND    FNOT.CERRADA     = 1 
            AND    FNOT.CLASE       = 'D'    
            AND    FNOT.PROCEDENCIA = 'NOTAS' 
            AND    FNOT.CNSGLO      = @CNSGLO
            AND    FNOT.ESTADO      <>'A'
         
            SELECT @VRPAGOS = COALESCE(SUM(COALESCE(FPAGD.VALORPAGO,0)+COALESCE(VLROTROSDCTOS,0)),0), @VRGLOSAS = COALESCE(SUM(COALESCE(FPAGD.VLRGLOSA,0)),0),
                   @VRDEDUC = COALESCE(SUM(COALESCE(FPAGD.VLRIMPUESTO,0) + COALESCE(FPAGD.VLRDTOFIN,0)),0)
            FROM   FPAGD INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG,FCXCDV
            WHERE  FPAGD.CERRADO    = 1
            AND    FPAGD.CLASE      = @TIPO   --- OJO : JEDM   RATIFICACION  ORIGINAL:::::      AND    FPAGD.CLASE      = 'G'
            AND    FPAGD.CNSCXC     = FCXCDV.CNSCXC   
            AND    FPAGD.CLASE      = FCXCDV.TIPO
            AND    FPAGD.N_FACTURA  = FCXCDV.N_FACTURA
            AND    FCXCDV.CNSCXC    = @CNSCXC  
            AND    FCXCDV.N_FACTURA = @N_FACTURA
            AND    COALESCE(FCXCDV.CNSGLO,'')    = COALESCE(FPAGD.CNSGLO,'')
            AND    FPAGD.CNSGLO     = @CNSGLO
            AND    COALESCE(FPAG.ESTADO,'')<>'Inactivo'
            AND    COALESCE(FPAGD.ESTADO,'')<>'Retirada'               
            PRINT 'BUSCO EL VALOR LEVANTADO'
            --SELECT @VLRLEVANTADO=COALESCE(VLRLEVANTADO,0) FROM FCXCDV WHERE N_FACTURA=@N_FACTURA AND CNSCXC=@CNSCXC AND CNSGLO=CASE WHEN COALESCE(@CNSGLO,'')='' THEN FCXCDV.CNSGLO ELSE @CNSGLO END AND TIPO=@TIPO
            --IF COALESCE(@VLRLEVANTADO,0)>0
            --BEGIN
            --   PRINT 'SE SUMA EL VALOR A REPURERAR DEL VALOR LEVANTADO'
            --    UPDATE FCXCD SET VLRGLOSAS_R =COALESCE(VLRGLOSAS_R,0)+@VLRLEVANTADO WHERE N_FACTURA=@N_FACTURA AND CNSCXC=@CNSCXC
            --END
            UPDATE FCXCDV 
            SET    SALDONETO = COALESCE(SALDOINICIAL,0) - COALESCE(@VRNOTAS,0)  - COALESCE(@VRPAGOS,0)  - COALESCE(@VRGLOSAS,0)  - COALESCE(@VRGLOSAS_R,0)  - COALESCE(@VRDEDUC,0)  +COALESCE( @VRNOTASD,0)  - COALESCE(@VLRCESION,0) +COALESCE(@VLRLEVANTADO,0) - (CASE ISNULL(LEVANTADO,0) WHEN 1 THEN ISNULL(VLRLEVANTADO,0) ELSE 0 END)
            WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
            AND    FCXCDV.ITEM = @ITEM         
            AND COALESCE(CNSGLO,'')=CASE WHEN COALESCE(@CNSGLO,'')='' THEN COALESCE(FCXCDV.CNSGLO,'') ELSE @CNSGLO END
            IF @SALDONETOFCXCD = 0
            BEGIN 
               UPDATE FCXCDV SET    SALDONETO = 0 
               WHERE  FCXCDV.CNSCXC = @CNSCXC 
               AND    FCXCDV.N_FACTURA = @N_FACTURA 
               AND    FCXCDV.ITEM = @ITEM         
            END
         END   
         ELSE -- @TIPO = 'C'
         BEGIN
		    PRINT '@TIPO = ''C'''
            SELECT @IDFCONCI = IDFCONCI, @SALDOINICIAL = SALDOINICIAL FROM FCXCDV 
            WHERE CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA AND ITEM = @ITEM 
            AND COALESCE(CNSGLO,'')=CASE WHEN COALESCE(@CNSGLO,'')='' THEN COALESCE(FCXCDV.CNSGLO,'') ELSE @CNSGLO END

            SELECT @VLRRECUPERAR = VLRRECUPERAR FROM FCONCID 
                   WHERE  CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA 
				   AND IDFCONCI = @IDFCONCI 
                   AND COALESCE(CNSGLO,'')=COALESCE(@CNSGLO,'')
				   AND ESTADO='Cerrada'
            PRINT '@IDFCONCI='+@IDFCONCI+'//@SALDOINICIAL='+CONVERT(VARCHAR,@SALDOINICIAL)+'//@VLRRECUPERAR= '+CONVERT(VARCHAR,@VLRRECUPERAR)+' //@CNSGLO'+COALESCE(@CNSGLO,'NO GLOSA')

            SELECT @VRNOTAS = COALESCE(SUM(FNOT.VR_TOTAL),0)
            FROM   FNOT
            WHERE  FNOT.N_FACTURA   = @N_FACTURA  
            AND    FNOT.CERRADA     = 1 
            AND    FNOT.CLASE       = 'C'    
            AND    FNOT.PROCEDENCIA = 'AJUSTE' 
            AND    FNOT.ESTADO='O'
            AND    FNOT.APLICADAA=CASE WHEN COALESCE(APLICADAA,'')<>'C' THEN @TIPO ELSE FNOT.APLICADAA END
            AND COALESCE(CNSGLO,'')=CASE WHEN COALESCE(@CNSGLO,'')='' THEN COALESCE(CNSGLO,'') ELSE @CNSGLO END

            --IF @VLRRECUPERAR <> @SALDOINICIAL
            --BEGIN
            --   UPDATE FCXCDV SET SALDOINICIAL = @VLRRECUPERAR WHERE CNSCXC = @CNSCXC AND N_FACTURA = @N_FACTURA 
            --   AND ITEM = @ITEM AND COALESCE(CNSGLO,'')=CASE WHEN COALESCE(@CNSGLO,'')='' THEN COALESCE(FCXCDV.CNSGLO,'') ELSE COALESCE(@CNSGLO,'') END
            --END
            PRINT 'REVISO PAGOS DE CONCILIACION '
            SELECT @VRPAGOS = COALESCE(SUM(FPAGD.VALORPAGO+COALESCE(VLROTROSDCTOS,0)),0), @VRGLOSAS = COALESCE(SUM(FPAGD.VLRGLOSA),0),
                   @VRDEDUC = COALESCE(SUM(COALESCE(FPAGD.VLRIMPUESTO,0) + COALESCE(FPAGD.VLRDTOFIN,0)),0) 
            FROM   FPAGD INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG
            WHERE  FPAGD.CNSCXC    = @CNSCXC
            AND    FPAGD.N_FACTURA = @N_FACTURA
            AND    FPAGD.CLASE     = 'C'
            AND    FPAGD.CERRADO   = 1
            AND    COALESCE(FPAG.ESTADO,'')<>'Inactivo' 
            AND    COALESCE(FPAGD.ESTADO,'')<>'Retirada'
            AND    COALESCE(FPAGD.CNSGLO,'')    = COALESCE(@CNSGLO,'')
                      
           -- SELECT @VRPAGOS = @VRPAGOS + COALESCE(@VRPAGOS1,0), @VRDEDUC = @VRDEDUC + COALESCE(@VRDEDUC1,0)
		    PRINT 'APLICO EL PAGO EN FCXCDV'
			PRINT 'VALOR DEL PAGO:'+LTRIM(RTRIM(STR(@VRPAGOS)))
            UPDATE FCXCDV 
            SET    SALDONETO = SALDOINICIAL - (@VRPAGOS + @VRDEDUC+@VRNOTAS)
            WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
            AND    FCXCDV.ITEM = @ITEM
            AND COALESCE(CNSGLO,'')=CASE WHEN COALESCE(@CNSGLO,'')='' THEN COALESCE(FCXCDV.CNSGLO,'') ELSE COALESCE(@CNSGLO,'') END

            SELECT @SALDONETOFCXCDV_C = SALDONETO FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
            AND    FCXCDV.ITEM = @ITEM

            IF @SALDONETOFCXCD = 0 AND @SALDONETOFCXCDV_C > 0
            BEGIN
                UPDATE FCXCDV 
                SET    SALDONETO = 0
                WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
                AND    FCXCDV.ITEM = @ITEM
            END
         END
      END
      SELECT @SALDONETOFCXCDV = SUM(SALDONETO) FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA 
      --   SE REVISA SI EL SALDO DE LAS PARTES ES MAYOR QUE EL DE FCXCD SI LO ES
      --   REVISAMOS QUE EN LAS PARTES (FCXCDV) SOLO HALLA UN ITEM CON SALDONETO MAYOR QUE 0
      --   Y A ESE LE IGUALAMOS EL VALORCON EL DE FCXCD
      IF @SALDONETOFCXCDV > @SALDONETOFCXCD
      BEGIN
         IF (SELECT COUNT(*) FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND SALDONETO >0 ) = 1
         BEGIN
            SELECT @ITEM = ITEM FROM FCXCDV WHERE FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND SALDONETO > 0
            UPDATE FCXCDV SET SALDONETO = @SALDONETOFCXCD WHERE FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND ITEM = @ITEM
         END
      END
      
      IF     (SELECT COUNT(*) FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND SALDONETO < 0 AND TIPO = 'C') = 1
         AND (SELECT COUNT(*) FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND SALDONETO > 0 AND TIPO <> 'C') = 1
         AND  @SALDONETOFCXCD > 0
      BEGIN
         SELECT @ITEM = ITEM FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND SALDONETO > 0 AND TIPO <> 'C'
         SELECT @SALDONEG = ABS(SALDONETO) FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND SALDONETO < 0 AND TIPO = 'C'
         SELECT @SALDOPOS = ABS(SALDONETO) FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND SALDONETO > 0 AND TIPO <> 'C'
         PRINT '@SALDONEG='+CONVERT(VARCHAR,@SALDONEG)+' // @SALDOPOS='+CONVERT(VARCHAR,@SALDOPOS)

         UPDATE FCXCDV SET SALDONETO = SALDONETO + @SALDOPOS FROM FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND SALDONETO < 0 AND TIPO = 'C'

         UPDATE FCXCDV SET SALDONETO = CASE WHEN SALDONETO > @SALDONEG THEN 0 ELSE SALDONETO - @SALDONEG END
         FROM   FCXCDV WHERE  FCXCDV.CNSCXC = @CNSCXC AND FCXCDV.N_FACTURA = @N_FACTURA AND ITEM = @ITEM
      END

	  IF EXISTS (SELECT 1 FROM FTR WHERE  N_FACTURA = @N_FACTURA AND ESTADO='A')
   BEGIN
     
        
         UPDATE FCXCDV SET SALDONETO = 0
         WHERE  FCXCDV.N_FACTURA = @N_FACTURA
         AND    FCXCDV.CNSCXC    = @CNSCXC  AND TIPO='F'
      
   END   
      
      IF @VRNOTAS IS NULL
         SELECT @VRNOTAS = 0
      IF @VRNOTASD IS NULL
         SELECT @VRNOTASD = 0
      IF @VRPAGOS IS NULL
         SELECT @VRPAGOS = 0
      IF @VRGLOSAS IS NULL
         SELECT @VRGLOSAS = 0
      IF @VRGLOSAS_R IS NULL
         SELECT @VRGLOSAS_R = 0
      IF @VRDEDUC IS NULL
         SELECT @VRDEDUC = 0
      
      FETCH NEXT FROM SD_CURSOR    
      INTO @N_FACTURA, @ITEM, @TIPO, @CNSGLO
   END
   CLOSE SD_CURSOR
   DEALLOCATE SD_CURSOR
END





