USE [CEM]
GO

/****** Object:  UserDefinedFunction [dbo].[RPT_FORMATO_NOMINA]    Script Date: 5/03/2024 9:26:28 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE    FUNCTION [dbo].[RPT_FORMATO_NOMINA] (@CNSPAGO  VARCHAR(20) )  
RETURNS TABLE  
AS  
RETURN  
  
SELECT NIEPE.CNSPAGO, NEMP.DOCIDEMPLEADO,NIEPE.NOMBRE_EMPLEADO,NCARNG.DESCRIPCION [CARGO], NEMP.HORASDELABOR,  
(SELECT CANTIDAD FROM NIEPED WHERE CNSNIEPE=NIEPE.CNSNIEPE AND NUMDOC=NIEPE.NUMDOC AND CODCONCEPTO='CN01')[HORAS_LABOR]  
,NIEPE.BASICO,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN01')+  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN26')[SALARIO],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN03')      [AUXILIO DE TRANSPORTE],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN11')      [RECARGO DOMINICAL FESTIVO DIURNO],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN12')      [RECARGO NOCTURNO],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN13')      [RECARGO DOMINICAL FESTIVO NOCTURNO],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN14')      [HORAS EXTRA DIURNA],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN15')      [HORAS EXTRA NOCTURNA],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN22')      [LICENCIA MATERNIDAD],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN23')      [LICENCIA PATERNIDAD],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN16')      [HORAS EXTRA DIURNA DOMINICAL FESTIVA ],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN18')      [VACACIONES DISFRUTADAS],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN19')      [INCAPACIDAD COMUN 2 DIAS],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN20')      [INCAPACIDAD COMUN MAYOR A 2 DIAS],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN20-1')    [INCAPACIDAD MAYOR 2 DIAS SMLV],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN21')      [INCAPACIDAD LABORAL],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN24')      [LICENCIA DE LUTO],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN26')      [LICENCIA NOREMUNERADA],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN27')      [SUSPENSION TEMPORAL],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN75')      [DIA DE LA FAMILIA],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN28')      [OTROS CONCEPTOS NO SALARIALES],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN39')      [VACACIONES COMPENSADAS],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN51')      [LIQUIDACION M CESANTIAS],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN52')      [LIQUIDACION M INTERESES DE CESANTIAS],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN53')      [LIQUIDACION M PRIMAS],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN54')      [LIQUIDACION M VACACIONES],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN57')      [AUXILIO DE RODAMIENTO],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN60')      [OTROS CONCEPTOS SALARIALES],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN25')      [LICENCIA REMUNERADA],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN17')        [HORAS EXTRA NOCTURNA DOM FEST],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN47')        [LIQ DEF PRIMAS],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN48')        [LIQ DEF CESANTIAS],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN49')        [LIQ DEF INTERESES CESAN],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN50')        [LIQ DEF VACACIONES],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN70-1')        [INDEMNIZACION LABORAL],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN70-2')        [INDENMNIZACION LABORAL MAYOR],  
--  
  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN02')      [APORTE DE SALUD EMPLEADO] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN04')      [APORTE DE SALUD EMPLEADOR + DE 10SMLV] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN05')      [APORTE DE PENSION EMPLEADO] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN06')      [APORTE DE PENSION EMPLEADOR] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN07')      [APORTE FONDO DE SOLIDARIDAD PENSIONAL] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN08')      [APORTE CAJA DE COMPENSACION FAMILIAR] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN09')      [APORTE RIESGOS LABORALES 2.433] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN09-1')    [APORTE RIESGOS LABORALES 0.522] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN10')      [RETENCION EN LA FUENTE] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN30')      [DESCUENTO PRESTAMO TRABAJADOR] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN32')      [DESCUENTO EMBARGO] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN40')      [PROVISIONES DE CESANTIAS] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN41')      [PROVISION DE  PRIMAS] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN42')      [PROVISION INTERESES CESANTIAS] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN43')      [PROVISION VACACIONES] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN45')      [APORTE SALUD EMPLEADOR SENA BASE] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN46')      [APORTES RIESGOS EMPLEADOR SENA] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN55')      [PARAFISCAL SENA] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN56')      [PARAFISCALES ICBF] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN58')      [DEDUCCION LIBRANZAS] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN61')      [DEDUCCIONES X PRESTACIONES COMITE] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN62')      [DEDUCCION GIMNASIO] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN63')      [DEDUCCION PARQUEADERO] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN73')      [DEDUCCION AFC] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN74')      [DEDUCCION FONDO EMPLEADOS] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN64')      [APORTE PENSION EMPLEADOR MEDIO SALARIO MINIMO] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN65')      [APORTE SALUD EMPLEADOR MEDIO SALARIO MINIMO] ,  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN66')      [APORTE ARL EMPLEADOR MEDIO SALARIO MINIMO],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN72')      [OTRAS DEDUCCIONES],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN33')      [DESCUENTO PRIMA],  
DBO.FNK_VALOR_CONCEPTO_NOMI_NIEPED(NIEPE.CNSNIEPE,NIEPE.NUMDOC,'CN38')      [DESCUENTO ANTICIPO],  
NIEPE.TOTAL_NOMINA,NIEPE.VALOR_EGRESOS,NIEPE.VALOR_NETO  
FROM NIEPE INNER JOIN NEMP ON NIEPE.NUMDOC=NEMP.NUMDOC  
     INNER JOIN NCARNG ON NCARNG.NIVEL=NEMP.NIVEL AND NCARNG.CODCARGO=NEMP.CODCARGO AND NEMP.GRADO=NCARNG.GRADO  
WHERE CNSPAGO= @CNSPAGO  
  AND ANO+MES >= COALESCE( CAST(YEAR(NEMP.FECHARETIRO) AS varchar(4))+ CASE WHEN LEN (CAST(MONTH(NEMP.FECHARETIRO) AS varchar(2))) = 1   
                                                                     THEN '0'+ CAST(MONTH(NEMP.FECHARETIRO) AS varchar(2))   
                                                                     ELSE      CAST(MONTH(NEMP.FECHARETIRO) AS varchar(2)) END,'')  
GO


