SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC


SELECT  * FROM FTRAPILOG WHERE N_fACTURA='F003-00000056'

SELECT TIPOVENTA,CUOTAS,  * FROM FTR WHERE N_fACTURA='F003-00000056'
UPDATE USUSU SET IDDEPURAR=1-IDDEPURAR WHERE USUARIO='JJIMENEZ'


