--SELECT  * FROM IART

--SELECT TOP 10  * FROM IHISD

SELECT ROW_NUMBER() OVER(ORDER  BY IART.DESCRIPCION,IHISD.NOLOTE),
IART.DESCRIPCION,IPAC.DESCRIPCION,ICCN.DESCRIPCION,IFFA.DESCRIPCION,IHISD.NOLOTE,IEXI.NOLOTEPEDIDO,
DBO.FNK_FECHA_DDMMAA(IEXI.FECHAVENCE)F_VENCE,TP.DESCRIPCION,TER.RAZONSOCIAL,TR.CODIGO,
SUM(CASE WHEN IHIS.DIA=1 THEN SALDOINICIAL ELSE 0 END)SI,
SUM(CASE WHEN IHIS.DIA=1 THEN MOVIMIENTOENTRADA ELSE 0 END)E01,
SUM(CASE WHEN IHIS.DIA=2 THEN MOVIMIENTOENTRADA ELSE 0 END)E02,
SUM(CASE WHEN IHIS.DIA=3 THEN MOVIMIENTOENTRADA ELSE 0 END)E03,
SUM(CASE WHEN IHIS.DIA=4 THEN MOVIMIENTOENTRADA ELSE 0 END)E04,
SUM(CASE WHEN IHIS.DIA=5 THEN MOVIMIENTOENTRADA ELSE 0 END)E05,
SUM(CASE WHEN IHIS.DIA=6 THEN MOVIMIENTOENTRADA ELSE 0 END)E06,
SUM(CASE WHEN IHIS.DIA=7 THEN MOVIMIENTOENTRADA ELSE 0 END)E07,
SUM(CASE WHEN IHIS.DIA=8 THEN MOVIMIENTOENTRADA ELSE 0 END)E08,
SUM(CASE WHEN IHIS.DIA=8 THEN MOVIMIENTOENTRADA ELSE 0 END)E09,
SUM(CASE WHEN IHIS.DIA=10 THEN MOVIMIENTOENTRADA ELSE 0 END)E10,
SUM(CASE WHEN IHIS.DIA=11 THEN MOVIMIENTOENTRADA ELSE 0 END)E11,
SUM(CASE WHEN IHIS.DIA=12 THEN MOVIMIENTOENTRADA ELSE 0 END)E12,
SUM(CASE WHEN IHIS.DIA=13 THEN MOVIMIENTOENTRADA ELSE 0 END)E13,
SUM(CASE WHEN IHIS.DIA=14 THEN MOVIMIENTOENTRADA ELSE 0 END)E14,
SUM(CASE WHEN IHIS.DIA=15 THEN MOVIMIENTOENTRADA ELSE 0 END)E15,
SUM(CASE WHEN IHIS.DIA=16 THEN MOVIMIENTOENTRADA ELSE 0 END)E16,
SUM(CASE WHEN IHIS.DIA=17 THEN MOVIMIENTOENTRADA ELSE 0 END)E17,
SUM(CASE WHEN IHIS.DIA=18 THEN MOVIMIENTOENTRADA ELSE 0 END)E18,
SUM(CASE WHEN IHIS.DIA=19 THEN MOVIMIENTOENTRADA ELSE 0 END)E19,
SUM(CASE WHEN IHIS.DIA=20 THEN MOVIMIENTOENTRADA ELSE 0 END)E20,
SUM(CASE WHEN IHIS.DIA=21 THEN MOVIMIENTOENTRADA ELSE 0 END)E11,
SUM(CASE WHEN IHIS.DIA=22 THEN MOVIMIENTOENTRADA ELSE 0 END)E22,
SUM(CASE WHEN IHIS.DIA=23 THEN MOVIMIENTOENTRADA ELSE 0 END)E23,
SUM(CASE WHEN IHIS.DIA=24 THEN MOVIMIENTOENTRADA ELSE 0 END)E24,
SUM(CASE WHEN IHIS.DIA=25 THEN MOVIMIENTOENTRADA ELSE 0 END)E25,
SUM(CASE WHEN IHIS.DIA=26 THEN MOVIMIENTOENTRADA ELSE 0 END)E26,
SUM(CASE WHEN IHIS.DIA=27 THEN MOVIMIENTOENTRADA ELSE 0 END)E27,
SUM(CASE WHEN IHIS.DIA=28 THEN MOVIMIENTOENTRADA ELSE 0 END)E28,
SUM(CASE WHEN IHIS.DIA=29 THEN MOVIMIENTOENTRADA ELSE 0 END)E29,
SUM(CASE WHEN IHIS.DIA=30 THEN MOVIMIENTOENTRADA ELSE 0 END)E30,
SUM(CASE WHEN IHIS.DIA=31 THEN MOVIMIENTOENTRADA ELSE 0 END)E31,
--SALIDAS
SUM(CASE WHEN IHIS.DIA=1 THEN  MOVIMIENTOSALIDA ELSE 0 END)E01,
SUM(CASE WHEN IHIS.DIA=2 THEN  MOVIMIENTOSALIDA ELSE 0 END)E02,
SUM(CASE WHEN IHIS.DIA=3 THEN  MOVIMIENTOSALIDA ELSE 0 END)E03,
SUM(CASE WHEN IHIS.DIA=4 THEN  MOVIMIENTOSALIDA ELSE 0 END)E04,
SUM(CASE WHEN IHIS.DIA=5 THEN  MOVIMIENTOSALIDA ELSE 0 END)E05,
SUM(CASE WHEN IHIS.DIA=6 THEN  MOVIMIENTOSALIDA ELSE 0 END)E06,
SUM(CASE WHEN IHIS.DIA=7 THEN  MOVIMIENTOSALIDA ELSE 0 END)E07,
SUM(CASE WHEN IHIS.DIA=8 THEN  MOVIMIENTOSALIDA ELSE 0 END)E08,
SUM(CASE WHEN IHIS.DIA=8 THEN  MOVIMIENTOSALIDA ELSE 0 END)E09,
SUM(CASE WHEN IHIS.DIA=10 THEN MOVIMIENTOSALIDA ELSE 0 END)E10,
SUM(CASE WHEN IHIS.DIA=11 THEN MOVIMIENTOSALIDA ELSE 0 END)E11,
SUM(CASE WHEN IHIS.DIA=12 THEN MOVIMIENTOSALIDA ELSE 0 END)E12,
SUM(CASE WHEN IHIS.DIA=13 THEN MOVIMIENTOSALIDA ELSE 0 END)E13,
SUM(CASE WHEN IHIS.DIA=14 THEN MOVIMIENTOSALIDA ELSE 0 END)E14,
SUM(CASE WHEN IHIS.DIA=15 THEN MOVIMIENTOSALIDA ELSE 0 END)E15,
SUM(CASE WHEN IHIS.DIA=16 THEN MOVIMIENTOSALIDA ELSE 0 END)E16,
SUM(CASE WHEN IHIS.DIA=17 THEN MOVIMIENTOSALIDA ELSE 0 END)E17,
SUM(CASE WHEN IHIS.DIA=18 THEN MOVIMIENTOSALIDA ELSE 0 END)E18,
SUM(CASE WHEN IHIS.DIA=19 THEN MOVIMIENTOSALIDA ELSE 0 END)E19,
SUM(CASE WHEN IHIS.DIA=20 THEN MOVIMIENTOSALIDA ELSE 0 END)E20,
SUM(CASE WHEN IHIS.DIA=21 THEN MOVIMIENTOSALIDA ELSE 0 END)E11,
SUM(CASE WHEN IHIS.DIA=22 THEN MOVIMIENTOSALIDA ELSE 0 END)E22,
SUM(CASE WHEN IHIS.DIA=23 THEN MOVIMIENTOSALIDA ELSE 0 END)E23,
SUM(CASE WHEN IHIS.DIA=24 THEN MOVIMIENTOSALIDA ELSE 0 END)E24,
SUM(CASE WHEN IHIS.DIA=25 THEN MOVIMIENTOSALIDA ELSE 0 END)E25,
SUM(CASE WHEN IHIS.DIA=26 THEN MOVIMIENTOSALIDA ELSE 0 END)E26,
SUM(CASE WHEN IHIS.DIA=27 THEN MOVIMIENTOSALIDA ELSE 0 END)E27,
SUM(CASE WHEN IHIS.DIA=28 THEN MOVIMIENTOSALIDA ELSE 0 END)E28,
SUM(CASE WHEN IHIS.DIA=29 THEN MOVIMIENTOSALIDA ELSE 0 END)E29,
SUM(CASE WHEN IHIS.DIA=30 THEN MOVIMIENTOSALIDA ELSE 0 END)E30,
SUM(CASE WHEN IHIS.DIA=31 THEN MOVIMIENTOSALIDA ELSE 0 END)E31,
SUM(MOVIMIENTOENTRADA)TOTAL_ENTRADAS,SUM(MOVIMIENTOSALIDA) TOTAL_SALIDAS,
SUM(CASE WHEN IHIS.DIA=1 THEN SALDOINICIAL+MOVIMIENTOENTRADA ELSE MOVIMIENTOENTRADA END)-SUM(MOVIMIENTOSALIDA) STOCK_FINAL,
IHISD.IDARTICULO,IART.IDSERVICIO,IHISD.IDBODEGA
FROM IHIS INNER JOIN IHISD ON IHIS.CNSIHIS=IHISD.CNSIHIS
          INNER  JOIN IEXI ON IHISD.IDARTICULO=IEXI.IDARTICULO AND IHISD.IDBODEGA=IEXI.IDBODEGA AND IEXI.NOLOTE=IHISD.NOLOTE
          INNER JOIN IART ON IHISD.IDARTICULO=IART.IDARTICULO
          LEFT  JOIN IPAC ON IART.IDPRINACTIVO=IPAC.IDPRINACTIVO
          LEFT  JOIN ICCN ON IART.IDCONCENTRA=ICCN.IDCONCENTRA 
          LEFT  JOIN IFFA ON IART.IDFORFARM=IFFA.IDFORFARM
          LEFT JOIN TGEN TR ON IART.CLASERIESGO=TR.CODIGO AND TR.TABLA='IART' AND TR.CAMPO='CLASERIESGO'
          LEFT JOIN TGEN TP ON IART.PRECOMERCIAL=TP.CODIGO AND TP.TABLA='IART' AND TP.CAMPO='PRECOMERCIAL' 
          LEFT JOIN TER ON     IART.IDFABRICANTE=TER.IDTERCERO
WHERE IHIS.ANO='2024'
AND IHIS.MES=10
AND IHISD.IDBODEGA='11'
--AND IHISD.IDARTICULO='MDP000362-1'
GROUP BY IART.DESCRIPCION,IPAC.DESCRIPCION,IFFA.DESCRIPCION,ICCN.DESCRIPCION,IEXI.FECHAVENCE,TP.DESCRIPCION,TER.RAZONSOCIAL,TR.CODIGO,
IHISD.NOLOTE,IEXI.NOLOTEPEDIDO,IHISD.IDARTICULO,IART.IDSERVICIO,IHISD.IDBODEGA
ORDER BY IART.DESCRIPCION