SELECT A.CNSFNOT,A.CLASE,A.F_NOTA,A.N_FACTURA,A.CNSCXC,PTRUB.RUBRO, 
            PTRUB.NOMRUBRO,A.VR_TOTAL,A.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,A.OBSERVACION, 
            A.ENPRESUPUESTO
FROM FNOT A INNER JOIN FTR ON FTR.N_FACTURA=FTR.N_FACTURA
            INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
            LEFT  JOIN PTRUB ON PLN.RUBRO=PTRUB.RUBRO
            INNER JOIN TER  ON A.IDTERCERO=TER.IDTERCERO 
WHERE 

SELECT  * FROM UBEQ
SELECT  * FROM USUSU WHERE USUARIO='JJIMENEZ'

UPDATE USUSU SET SYS_ComputerName='ALMACEN-PC' WHERE USUARIO='JJIMENEZ'


 SELECT A.CNSFNOT,A.CLASE,A.F_NOTA,A.N_FACTURA,A.CNSCXC,PTRUB.RUBRO, 
    PTRUB.NOMRUBRO,A.VR_TOTAL,A.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,A.OBSERVACION,   
    A.ENPRESUPUESTO  
 FROM FNOT A INNER JOIN FTR ON A.N_FACTURA=FTR.N_FACTURA  
    INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN  
    LEFT  JOIN PTRUB ON PLN.RUBRO=PTRUB.RUBRO  
    INNER JOIN TER  ON A.IDTERCERO=TER.IDTERCERO   
 WHERE  COALESCE(A.CERRADA,0)=1 AND A.ESTADO='O' AND EXISTS(SELECT * FROM FTR INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN AND PLN.RUBRO='1.1.02.05.001.09.02.01.01.01' AND FTR.N_FACTURA=A.N_FACTURA) AND EXISTS(SELECT * FROM FTR WHERE N_FACTURA=A.N_FACTURA AND COALESCE(ENPRESUPUESTO,0)=1 AND COALESCE(CONSECUTIVOPTO,'')='2024')