<i class="fa-regular fa-folder"></i>
<i class="fa-solid fa-code"></i>


SELECT IDFORMATO, * FROM FTR WHERE N_FACTURA='FV16914'

SELECT  * FROM FTRD WHERE N_FACTURA='FV16914'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"FV16914"},"USUARIO":"JJIMENEZ"}'