IF EXISTS (SELECT name FROM sysobjects WHERE NAME = 'SPK_COPAGOQX' AND TYPE = 'P')
   DROP PROCEDURE SPK_COPAGOQX

GO
CREATE PROCEDURE DBO.SPK_COPAGOQX
	@NOADMISION   VARCHAR(16),
	@NOPRESTACION VARCHAR(16),
	@ITEM         INT,
	@CARGOSENCX   SMALLINT = 0
WITH ENCRYPTION
AS            
DECLARE @IDAFILIADO       VARCHAR(20) 
DECLARE @EDAD             SMALLINT
DECLARE @TIPOAFI          VARCHAR(1)
DECLARE @TIPOAFILIADO     VARCHAR(12)
DECLARE @TIPOAFIORIGI     VARCHAR(12)
DECLARE @CLASIFPC         VARCHAR(5)
DECLARE @IDPLAN           VARCHAR(6)
DECLARE @IDMODELOPCA      VARCHAR(5)
DECLARE @NIVELSOCIOE      VARCHAR(2)
DECLARE @ALTOCOSTO        VARCHAR(2)
DECLARE @IDTERCERO        VARCHAR(20)
DECLARE @IDSERVICIO       VARCHAR(20)
DECLARE @TIPODEPAGO       VARCHAR(10)
DECLARE @COBRAR           VARCHAR(2)
DECLARE @CALCULARPOR      VARCHAR(5)
DECLARE @TIPOATENCION     VARCHAR(1)
DECLARE @EXURGENCIA       SMALLINT
DECLARE @EXALTOCOSTO      SMALLINT
DECLARE @EXPYP            SMALLINT
DECLARE @EXAREAS          SMALLINT
DECLARE @EXEDAD           SMALLINT
DECLARE @TIPOADM          VARCHAR(2)
DECLARE @MCLASIFPC        INT
DECLARE @MEDAD            INT
DECLARE @MAGS             INT
DECLARE @MNIVELSE         INT
DECLARE @FORMACOBRO       VARCHAR(10)
DECLARE @REDONDEO         VARCHAR(10)   
DECLARE @IDAGRUPACIONSER  VARCHAR(10)
DECLARE @MOCCDVALOR       DECIMAL(14,2)
DECLARE @MOCCDVALORMAXIMO DECIMAL(14,2)
DECLARE @COPAGOGLOBAL     DECIMAL(14,2)
DECLARE @PCUBRIMIENTO     DECIMAL(5,2)
DECLARE @VALORSER         DECIMAL(18,6)
DECLARE @CANTIDAD         DECIMAL(18,6)
DECLARE @VALORTOT         DECIMAL(18,6)
DECLARE @VALORCOPAGO      DECIMAL(14,6)
DECLARE @VALORPCOMP       DECIMAL(14,2)
DECLARE @VALOREXCEDENTE   DECIMAL(14,3) 
DECLARE @COPAGONOAUTORIZACION VARCHAR(20)
DECLARE @COPAGOVALOR      DECIMAL(14,2)
DECLARE @OK               SMALLINT
DECLARE @VT               DECIMAL(14,2)
DECLARE @VE               DECIMAL(14,2)
DECLARE @VC               DECIMAL(14,2)
DECLARE @VP               DECIMAL(14,2)
DECLARE @PYP              SMALLINT
DECLARE @ESEXARE          INT
DECLARE @IDAREAH          VARCHAR(20) 
DECLARE @IDAREA           VARCHAR(20)
DECLARE @COBRARA          VARCHAR(1)
DECLARE @NODTACOPAGO      SMALLINT
DECLARE @TIPOFACTURA      VARCHAR(1)
DECLARE @IDIPS            VARCHAR(20)
DECLARE @NIVELATENCION    VARCHAR(5)
DECLARE @CIRUGIA          VARCHAR(2)
DECLARE @IDCIRUGIA        VARCHAR(20)
DECLARE @AUXCX            INT
DECLARE @CNSRPDX          VARCHAR(20)
DECLARE @ANO              INT
DECLARE @MES              INT
DECLARE @DIA              INT
DECLARE @DATO             VARCHAR(20)
DECLARE @IDPLANCA         VARCHAR(6)
DECLARE @IDTERCEROCA      VARCHAR(20)
DECLARE @FECHACARGO       DATETIME
DECLARE @FECHACARGOSH       DATETIME
DECLARE @VLRSERVICIO      DECIMAL(18,6)
DECLARE @TIPODTO          VARCHAR(1)
DECLARE @TIPRECARGONOC    VARCHAR(10)
DECLARE @CONT             INT
DECLARE @VLRRECCARGONOC   DECIMAL(14,2)
DECLARE @HIRECNOC         INT
DECLARE @HFRECNOC         INT
DECLARE @DIASIGRN         SMALLINT
DECLARE @LUNES            SMALLINT 
DECLARE @MARTES           SMALLINT 
DECLARE @MIERCOLES        SMALLINT 
DECLARE @JUEVES           SMALLINT 
DECLARE @VIERNES          SMALLINT 
DECLARE @SABADO           SMALLINT 
DECLARE @DOMINGO          SMALLINT 
DECLARE @FESTIVOTOTAL     SMALLINT 
DECLARE @DOMIGOTOTAL      SMALLINT 
DECLARE @DHOY             INT
DECLARE @DESCUENTO        DECIMAL(14,2)
DECLARE @ESCIRUGIA        VARCHAR(2)    
DECLARE @NOCOBRABLE       SMALLINT
DECLARE @CODIFICACION     VARCHAR(20)
DECLARE @CODIFICACIONORI  VARCHAR(20)
DECLARE @CODIFICACIONTAR  VARCHAR(20)
DECLARE @IDSERVICIONUEVO  VARCHAR(20)
DECLARE @AUX1                INT
DECLARE @CODCUPS             VARCHAR(20)
DECLARE @IDSERVICIONV        VARCHAR(20)
DECLARE @ESTADO              VARCHAR(8)
DECLARE @MANUAL              SMALLINT
DECLARE @VLSRV               DECIMAL(18,6)
DECLARE @MOCCDVALORTOPEANUAL DECIMAL(14,2) --AQUI GUARDAMOS EL MTOPE ANUAL DE COPAGO
DECLARE @VLR_COPAGOEXTERNO   DECIMAL(14,2) --AQUI GUARDAMOS EL COPAGO EXTERNO DE LA ADMISION
DECLARE @IND_PASTOPEANUAL    SMALLINT 
DECLARE @ENCARGOS_ADX        TINYINT
DECLARE @TOPECOP_ANX6        DECIMAL(14,2) 
DECLARE @COPAGOACUM_NORMAL   DECIMAL(14,2)
DECLARE @VCOPNORMAL          DECIMAL(14,2)
DECLARE @CNSHACTRAN          VARCHAR(20)
DECLARE @COPAGOEXTERNOACUM   DECIMAL(14,2)
DECLARE @COPEXTERNO_RESTANTE DECIMAL(14,2)
DECLARE @VLRHOMOLOGO         DECIMAL(14,2)
DECLARE @FNACIMIENTO	     DATETIME
DECLARE @DEPURAR			 BIT = 0
DECLARE @COPAGOPERU          BIT = 0
DECLARE @HOY                 DATETIME=CONVERT(SMALLDATETIME,GETDATE())
DECLARE @PREFIJO             VARCHAR(20)
DECLARE @PREFIJOMEDICAMENTOS VARCHAR(20)=DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS')
DECLARE @PROCEDENCIA VARCHAR(20)
BEGIN
    SELECT @PROCEDENCIA=PROCEDENCIA FROM HPRE WHERE NOPRESTACION=@NOPRESTACION    

	--PRINT ' INGRESE A COPAGO NOPRESTACION = '+@NOPRESTACION +' -- NOITEM = ' +STR(@ITEM)
	IF (SELECT COALESCE(HPRED.FACTURADA,0) FROM HPRED WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM)=1
	BEGIN
		PRINT 'Prestacion ya Facturada'
		RETURN
	END
	IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
	BEGIN
	   IF (SELECT COALESCE(HPRED.N_FACTURAH,'') FROM HPRED WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM)<>''
	   BEGIN
		   PRINT 'Prestacion Ya Tiene Boleta'
		   RETURN
	   END
		IF EXISTS(SELECT * FROM HPRE WHERE PROCEDENCIA='CMEZCLAS' AND PREFIJO=@PREFIJOMEDICAMENTOS AND NOPRESTACION=@NOPRESTACION)
		BEGIN
			IF EXISTS(SELECT * FROM HPRED WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM AND COALESCE(VALORCOPAGO,0)>0 )
			BEGIN
				PRINT 'Tiene Copago y viene de inventario  No se puede Modificar'
				RETURN
			END
         SET @COPAGOPERU=1
         EXEC SPK_ADD_DEL_COPAGOS_HPRED @NOPRESTACION, @ITEM, 0,'01', 'Automatico'
			PRINT '@NOPRESTACION='+@NOPRESTACION
		END
      IF EXISTS(SELECT * FROM HPRED WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM AND COALESCE(NOAUTORIZACION,'')<>'' )
      BEGIN
         PRINT 'Retiro la asignacion de copago fijo ....'
         UPDATE HPRED SET NOAUTORIZACION=NULL WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM AND COALESCE(NOAUTORIZACION,'')<>''
      END
      PRINT 'Reviso no cobrables contratos especiales'
      IF EXISTS(SELECT * FROM PPTD WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLANCA AND IDSERVICIO=@IDSERVICIO AND TIPORESTRICCION='N' AND TIPOCOBRABLE='T')
      BEGIN
         UPDATE HPRED SET NOCOBRABLE=1,VALOR=0,VALORCOPAGO=0,VALOREXCEDENTE=0 WHERE NOPRESTACION=@NOPRESTACION AND NOITEM=@ITEM
      END
	END

	SELECT @OK = ISNULL(COUNT(*),0) FROM HPRED WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM 
	IF @OK = 0
	BEGIN
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- Consulta HPRED'
		SELECT @VT = SUM(HPRED.VALOR * HPRED.CANTIDAD), @VE = SUM(HPRED.VALOREXCEDENTE),
				@VC = SUM(HPRED.VALORCOPAGO), @VP = SUM(HPRED.VALORPCOMP)
		FROM   HPRED
		WHERE  HPRED.NOPRESTACION = @NOPRESTACION
      
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- Actualiza HPRED'
		UPDATE HPRE SET VALORTOTAL  = @VT,VALOREXEDENTE = @VE,
						VALORCOPAGO = @VC,VALORPCOMP    = @VP 
		WHERE  HPRE.NOPRESTACION = @NOPRESTACION
	  
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- Termina Actualizaci? HPRED'
		RETURN       
	END
	-- PRINT 'PASE SIN DETALLES'
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- REVISAMOS SI ES UN APOYO DX QUE NO SE HA REALIZADO'
	/*AQUI REVISAMOS SI ES UN APOYO DX QUE NO SE HA REALIZADO*/
	SELECT @ENCARGOS_ADX = COALESCE(ENCARGOS,0) FROM HPRED WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM
	SELECT @TOPECOP_ANX6 = COALESCE(TOPECOPAGO_ANX6,0) FROM HADM WHERE NOADMISION = @NOADMISION
	PRINT '@TOPECOP_ANX6 ==='+STR(@TOPECOP_ANX6)
	IF @ENCARGOS_ADX <> 0 AND DBO.FNK_VALORVARIABLE('SINCERRARCONVALOR')<>'SI'
	BEGIN
		UPDATE HPRED SET VALOR = 0
		WHERE  NOPRESTACION = @NOPRESTACION 
		AND    NOITEM = @ITEM
		IF @ENCARGOS_ADX = 2
		BEGIN   
			PRINT 'ESTA EN APOYODX SIN TRAER -- NO SE TOMA EN CUENTA PARA LA ADMISION'
		END
		IF @ENCARGOS_ADX = 1
		BEGIN   
			PRINT 'ESTA EN APOYODX TRAIDA PERO SIN CERRAR-- NO SE TOMA EN CUENTA PARA LA ADMISION'
		END

        IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')<>'PERU'
		    RETURN
	END
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- QUITO EL VALOR DEL COPAGO DE LA PRESTACION'

	UPDATE HPRED SET VALOREXCEDENTE = CANTIDAD*VALOR WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM  AND COALESCE(VALOREXCEDENTE,0) = 0
	UPDATE HPRE SET VALORCOPAGO = 0, VALORPCOMP = 0  WHERE NOPRESTACION = @NOPRESTACION --AND NOITEM = @ITEM --AND COALESCE(VALORCOPAGO, 0) = 0 // AGREGADO JJIMENEZ 19/11/2015
	UPDATE HPRED SET VALORCOPAGO = 0, VALORPCOMP = 0, VALORCOPAGONORMAL=0 WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM-- AND COALESCE(VALORPCOMP, 0) = 0 // COMENTARIZADO Y AGREGUE VALORCOPAGO NORMAL JJIMENEZ 19/11/2015
   
	/* 20.SEP.2005 JEDM 001 BEGIN                                       */
	/* SE COLOCA CALCULO DE VALORES QUE ANTES SE LLEVABA EN CLARION     */
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- SE COLOCA CALCULO DE VALORES QUE ANTES SE LLEVABA EN CLARION'
	SELECT @IDPLANCA        = IDPLAN,   @IDTERCEROCA = IDTERCEROCA, @IDSERVICIO = IDSERVICIO ,  @TIPODTO = TIPODTO,
			@DESCUENTO       = DESCUENTO, @NOCOBRABLE = COALESCE(NOCOBRABLE, 0),
			@CODIFICACIONORI = CODIFICACION, @CODCUPS = CODCUPS, @MANUAL = COALESCE(MANUAL,0), @VLSRV = VALOR      
	FROM   HPRED 
	WHERE  NOPRESTACION = @NOPRESTACION 
	AND    NOITEM = @ITEM

    SELECT @PREFIJO=PREFIJO FROM SER WHERE IDSERVICIO=@IDSERVICIO

	IF COALESCE(@IDPLANCA,'')=''
	BEGIN
		SELECT @IDPLANCA=IDPLAN FROM HPRE WHERE NOPRESTACION=@NOPRESTACION
	END
	IF COALESCE(@IDTERCEROCA,'')=''
	BEGIN
		SELECT @IDTERCEROCA=IDTERCEROCA FROM HPRE WHERE NOPRESTACION=@NOPRESTACION
	END
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'@VLSRV='+CAST (@VLSRV AS VARCHAR(30))
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'@CODIFICACIONORI=' + ISNULL(@CODIFICACIONORI,'')
	SELECT @IDAREA = ISNULL(IDAREA,''), @FECHACARGO = FECHA, @ESCIRUGIA = ISNULL(CIRUGIA,'NO') 
	FROM   HPRE
	WHERE  NOPRESTACION = @NOPRESTACION
   
	SET @FECHACARGOSH = DBO.FNK_FECHA_SIN_HORA(@FECHACARGO) 

	/* SE COLOCA ESTO PQ SE ENCUENTRAN IDAREA VACIAS LO CUAL NOS LLEVA A ERRORES*/
	IF @IDAREA = ''
	BEGIN
		SELECT @IDAREA = ISNULL(IDAREAEQUIPO,'')
		FROM   HPRE
		WHERE  NOPRESTACION = @NOPRESTACION
	END 
	IF @IDAREA = ''
	BEGIN
		PRINT 'ERROR EN IDAREA VACIA'
		RAISERROR('ERROR EN IDAREA VACIA', 10,1)  
		RETURN
	END      
	IF @ESCIRUGIA = 'SI'
	BEGIN
		IF @CARGOSENCX = 1
		BEGIN
			SELECT @ESCIRUGIA = 'NO'
		END
	END
   
	IF @MANUAL <> 1  
	BEGIN
		IF @ESCIRUGIA <> 'SI'
		BEGIN
			IF @NOCOBRABLE = 0 OR @NOCOBRABLE = 2
			BEGIN   
			IF DBO.FNK_VALORVARIABLE('MHOMOLOGACION_CUPS') = 'SI'
			BEGIN
				PRINT '@IDTERCEROCA='+@IDTERCEROCA
				PRINT '@IDPLANCA='+@IDPLANCA
				PRINT '@IDSERVICIO='+@IDSERVICIO
				PRINT '@IDAREA='+@IDAREA     
				PRINT '@FECHACARGO='+CAST (@FECHACARGO AS VARCHAR(30))
				SELECT @AUX1 = COUNT(*)
				FROM   SERTOT 
				WHERE  IDTERCERO   =  @IDTERCEROCA
				AND    IDPLAN      =  @IDPLANCA
				AND    IDSERVICIO  =  @IDSERVICIO
				AND    FECHAINIFD  <= @FECHACARGO
				AND    FECHAFINFD  >= @FECHACARGO
				AND    FECHAINI    <= @FECHACARGO
				AND    FECHAFIN    >= @FECHACARGO
                AND    ESTADO      = 'Activo'
				--AND    IDAREACA     = @IDAREA      
               
				IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- VECES ENCONTRADO EN SERTOT=' +CAST(@AUX1 AS VARCHAR(10))  
               
				IF @AUX1 >= 1
				BEGIN
					SELECT @VLRSERVICIO  = VLRSERVICIO, 
							@CODIFICACION = CODIFICACION   
					FROM   SERTOT 
					WHERE  IDTERCERO   =  @IDTERCEROCA
					AND    IDPLAN      =  @IDPLANCA
					AND    IDSERVICIO  =  @IDSERVICIO
					AND    FECHAINIFD  <= @FECHACARGO
					AND    FECHAFINFD  >= @FECHACARGO
					AND    FECHAINI    <= @FECHACARGO
					AND    FECHAFIN    >= @FECHACARGO
                    AND    ESTADO      = 'Activo'
					-- AND    IDAREACA     = @IDAREA     
				END
				ELSE
				BEGIN
					SELECT @VLRSERVICIO  = VLRSERVICIO, 
							@CODIFICACION = CODIFICACION,   
							@IDSERVICIONV = IDSERVICIO   
					FROM   SERTOT 
					WHERE  IDTERCERO   =  @IDTERCEROCA
					AND    IDPLAN      =  @IDPLANCA
					AND    CODCUPS     =  @CODCUPS
					AND    FECHAINIFD  <= @FECHACARGO
					AND    FECHAFINFD  >= @FECHACARGO
					AND    FECHAINI    <= @FECHACARGO
					AND    FECHAFIN    >= @FECHACARGO
                    AND    ESTADO      = 'Activo'
					-- AND    IDAREACA     = @IDAREA
   					--AND	 IDSERVICIO   = @IDSERVICIO   --ESTO DA?ABA LA HOMOLOGACION   JEDM 2010.08.23
				END
				IF @AUX1 = 0
				BEGIN
					UPDATE HPRED SET IDSERVICIO   = CASE COALESCE(@IDSERVICIONV,'') WHEN '' THEN IDSERVICIO ELSE @IDSERVICIONV END,
									CODIFICACION = CASE COALESCE(@CODIFICACION,'') WHEN '' THEN CODIFICACION ELSE @CODIFICACION END
					WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM
                   
					SELECT @ESTADO = ESTADO FROM SER WHERE IDSERVICIO = @IDSERVICIO
					IF @ESTADO = 'Inactivo'
					BEGIN
						SELECT @VLRSERVICIO = VALOR FROM HPRED WHERE NOPRESTACION = @NOPRESTACION AND NOITEM= @ITEM
					END
				END                
			END
			ELSE
			BEGIN
				IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- FECHACARGO='+ CONVERT (VARCHAR(30), @FECHACARGO)
				SELECT @VLRSERVICIO  = VLRSERVICIO, 
						@CODIFICACION = CODIFICACION   
				FROM   SERTOT 
				WHERE  IDTERCERO   =  @IDTERCEROCA
				AND    IDPLAN      =  @IDPLANCA
				AND    IDSERVICIO  =  @IDSERVICIO
				AND    FECHAINIFD   <= @FECHACARGO 
				AND    FECHAFINFD   >= @FECHACARGO 
				AND    FECHAINI     <= @FECHACARGO 
				AND    FECHAFIN     >= @FECHACARGO 
				-- AND    IDAREACA     = @IDAREA     
			END         
            
			SELECT @CONT = COUNT(*) 
			FROM   FES 
			WHERE  FECHA = @FECHACARGOSH
        
			SELECT @DHOY  = DATEPART(DW, @FECHACARGOSH)
            
			DECLARE @MIN_HI INT, @HOR_HI INT, @MIN_HID INT, @MIN_HF INT, @HOR_HF INT, @MIN_HFD INT, @FI_RN DATETIME, @FF_RN DATETIME
            
			SELECT @TIPRECARGONOC = RNXT.TIPORECARGONOC, @VLRRECCARGONOC = RNXT.VLRRECARGONOC,
					@HIRECNOC      = RNXT.HIRECNOC,       @HFRECNOC       = RNXT.HFRECNOC, 
					@DIASIGRN      = RNXT.DIASIGRN,       @LUNES          = RNXT.LUNES,
					@MARTES        = RNXT.MARTES,         @MIERCOLES      = RNXT.MIERCOLES,
					@JUEVES        = RNXT.JUEVES,         @VIERNES        = RNXT.VIERNES,
					@SABADO        = RNXT.SABADO,         @DOMINGO        = RNXT.DOMINGO,
					@FESTIVOTOTAL  = RNXT.FESTIVOTOTAL,   @DOMIGOTOTAL    = RNXT.DOMIGOTOTAL,
					@MIN_HI = (RNXT.HIRECNOC/100)/60,     @MIN_HF = (RNXT.HFRECNOC/100)/60
			FROM   RNXT INNER JOIN SER ON RNXT.PREFIJO   = SER.PREFIJO 
			WHERE  RNXT.IDTERCERO = @IDTERCEROCA
			AND    RNXT.IDPLAN    = @IDPLANCA 
			AND    SER.IDSERVICIO = @IDSERVICIO  
            
			SELECT  @HOR_HI  = @MIN_HI / 60, @HOR_HF = @MIN_HF / 60
			SELECT  @MIN_HID = @MIN_HI - (@HOR_HI * 60), @MIN_HFD = @MIN_HF - (@HOR_HF * 60)      
            
			IF @CONT > 0
			BEGIN
				IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- Es festivo'
				IF @FESTIVOTOTAL = 1
				BEGIN
					IF @TIPRECARGONOC IS NOT NULL
					BEGIN
						IF @VLRRECCARGONOC IS NOT NULL
						BEGIN
						IF @TIPRECARGONOC = 'Valor'
						BEGIN
							SELECT  @VLRSERVICIO = @VLRSERVICIO + @VLRRECCARGONOC 
						END
						ELSE
						BEGIN
							SELECT  @VLRSERVICIO = @VLRSERVICIO  * ( 1 + ( @VLRRECCARGONOC / 100 ) )
						END
						END
					END
				END   
			END
			ELSE
			BEGIN 
				IF DATEPART(HOUR, @FECHACARGO) <= 7
				BEGIN
					SELECT @DHOY = @DHOY -1 
					IF @DHOY = 0 
					BEGIN
						SELECT @DHOY = 7
					END
				END
               
				IF    (@DHOY = 1 AND @LUNES = 1)   OR (@DHOY = 2 AND @MARTES = 1) OR (@DHOY = 3 AND @MIERCOLES = 1) OR (@DHOY = 4 AND @JUEVES = 1)
					OR (@DHOY = 5 AND @VIERNES = 1) OR (@DHOY = 6 AND @SABADO = 1) OR (@DHOY = 7 AND @DOMINGO = 1)
				BEGIN
					SELECT @FI_RN = CONVERT(DATETIME, (CONVERT(VARCHAR(10),@FECHACARGOSH, 103)+' '+CAST(@HOR_HI AS VARCHAR(2))+':'+CAST(@MIN_HID AS VARCHAR(2))+':00.000'))
					IF @DIASIGRN = 1
					BEGIN
						SELECT @FF_RN = CONVERT(DATETIME, (CONVERT(VARCHAR(10),@FECHACARGOSH+1, 103)+' '+CAST(@HOR_HF AS VARCHAR(2))+':'+CAST(@MIN_HFD AS VARCHAR(2))+':59.999'))
					END
					ELSE
					BEGIN
						SELECT @FF_RN = CONVERT(DATETIME, (CONVERT(VARCHAR(10),@FECHACARGOSH, 103)+' '+CAST(@HOR_HF AS VARCHAR(2))+':'+CAST(@MIN_HFD AS VARCHAR(2))+':59.999'))
					END   
                                    
					IF @FECHACARGO >= @FI_RN AND @FECHACARGO <= @FF_RN
					BEGIN
						IF @TIPRECARGONOC = 'Valor'
						BEGIN
						SELECT  @VLRSERVICIO = @VLRSERVICIO + @VLRRECCARGONOC 
						END   
						ELSE
						BEGIN
						SELECT  @VLRSERVICIO = @VLRSERVICIO  * ( 1 + ( @VLRRECCARGONOC / 100 ) )
						END   
					END
				END
               
			END
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- valor servicio desp recnoc= '+cast(@vlrservicio as varchar(25))
			IF @TIPODTO = 'V'
			BEGIN
				SELECT  @VLRSERVICIO = @VLRSERVICIO - @DESCUENTO
			END
			IF @TIPODTO = 'P'
			BEGIN
				SELECT  @VLRSERVICIO = @VLRSERVICIO * (1 - ( @DESCUENTO /100 ) )
			END
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- valorservicio desp tipodto= '+cast(@vlrservicio as varchar(25))
			IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
			BEGIN
				PRINT 'REDONDEO EL VALOR SEVICIO PARA QUE CUADRE LAS OPERACIONES PERU'
				UPDATE HPRED SET VALOR        =@VLRSERVICIO
				WHERE  NOPRESTACION = @NOPRESTACION 
				AND    NOITEM = @ITEM
			END
			ELSE
			BEGIN
				UPDATE HPRED SET VALOR        = @VLRSERVICIO
				WHERE  NOPRESTACION = @NOPRESTACION 
				AND    NOITEM = @ITEM
			END
            
			END
			ELSE
			BEGIN
			UPDATE HPRED SET VALOR = 0
			WHERE  NOPRESTACION = @NOPRESTACION 
			AND    NOITEM = @ITEM
			END
		END
	END
	ELSE
	BEGIN
		PRINT 'ES MANUAL '+STR(@MANUAL)
	END
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- REVISION_COPAGO_PROPIO @noprestacion ='+@noprestacion+' --@noitem='+str(@ITEM)
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- VALOR DESP CALCULO='+STR(@VLRSERVICIO)
	
    SELECT @COPAGONOAUTORIZACION=HADM.COPAGONOAUTORIZACION, @COPAGOVALOR=COPAGOVALOR 
    FROM HADM WHERE NOADMISION=@NOADMISION

	IF @COPAGONOAUTORIZACION<>'' AND @COPAGOVALOR>0
	BEGIN
        IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
        BEGIN
            IF @PROCEDENCIA='HCAUT' OR @PREFIJO='016'
            BEGIN
                PRINT 'MANTENGO COPAGO Y VOY A LLORAR '
                DECLARE @NOPRESTACION_B VARCHAR(20)=NULL, @NOITEM_B INT=NULL
                SELECT @NOPRESTACION_B=HPRED.NOPRESTACION, @NOITEM_B=HPRED.NOITEM 
                FROM HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION 
                WHERE HPRE.NOADMISION=@NOADMISION AND ISNULL(HPRED.ANULADO,0)=0 
                AND HPRE.PROCEDENCIA='HADM'
                IF @NOPRESTACION_B IS NOT NULL AND @NOITEM_B IS NOT NULL
                BEGIN
                    PRINT 'ENCUENTRO PRESTACION CON POSIBLE BOLETA'
                    UPDATE HPRED SET N_FACTURAH=B.N_FACTURAH
                    FROM HPRED CROSS JOIN HPRED B 
                    WHERE HPRED.NOPRESTACION=@NOPRESTACION AND HPRED.NOITEM=@NOITEM_B
                        AND B.NOPRESTACION=@NOPRESTACION_B AND B.NOITEM=@NOITEM_B

                    UPDATE HPRED SET ANULADO=1, NOCOBRABLE=1
                    WHERE NOPRESTACION=@NOPRESTACION_B AND NOITEM=@NOITEM_B
                END
                ELSE
                BEGIN
                  IF (SELECT COALESCE(VALOREXCEDENTE,0)  FROM HPRED WHERE NOPRESTACION=@NOPRESTACION AND NOITEM=@ITEM)<0
                  BEGIN
                      SELECT @COPAGOVALOR=0
                  END
                END
            END
            ELSE
                SELECT @COPAGONOAUTORIZACION='', @COPAGOVALOR=0
        END
        ELSE
        BEGIN
		    IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- LLAMADO A SPK_COPAGOHAQX'
		    EXEC SPK_COPAGOHAQX @NOADMISION            
		    IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- Despues de LLAMADO A SPK_COPAGOHAQX'
		    RETURN
        END
	END
	---------------------------------------
	/* 20.SEP.2005 JEDM 001 END                                          */
	SELECT @COBRAR = 'SI'
	/*  30.MAY.2005 JEDM 001 BEGIN
		PARA EXCEPCION DE COBRO CUANDO ES CIRUGIA*/
	SELECT @CIRUGIA = CIRUGIA FROM HPRE WHERE NOPRESTACION = @NOPRESTACION
	IF @CIRUGIA = 'SI'
	BEGIN
		SELECT @COBRAR = 'SI'
		PRINT 'CIRUGIA'
		SELECT @IDMODELOPCA      = PPT.IDMODELOPCH
		FROM   HADM, PPT
		WHERE  HADM.NOADMISION   = @NOADMISION           
		AND    PPT.IDPLAN        = HADM.IDPLAN       
		AND    PPT.IDTERCERO     = HADM.IDTERCERO
	  
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- MODELOPCA=' + @IDMODELOPCA
      
		SELECT @IDCIRUGIA = IDCIRUGIA FROM HPRED WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM
      
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @IDCIRUGIA='+ @IDCIRUGIA
      
		SELECT @AUXCX = ISNULL(COUNT(*),0) FROM MOCPS
		WHERE  IDMODELOPC = @IDMODELOPCA 
		AND    IDSERVICIO = @IDCIRUGIA
		PRINT 'ENCONTRADO? = '+STR(@AUXCX)
         
		IF @AUXCX > 0
		BEGIN
			PRINT 'ENTRE A EXCEPCION'
			SELECT @TIPODEPAGO = TIPODEPAGO FROM MOCPS
			WHERE  IDMODELOPC = @IDMODELOPCA 
			AND    IDSERVICIO = @IDCIRUGIA
			PRINT '@TIPODEPAGO='+@TIPODEPAGO
         
			IF @TIPODEPAGO = 'EXCENTO'
			BEGIN
			SELECT @COBRAR = 'NO'
			END
			ELSE
			BEGIN
			SELECT @COBRAR = 'SI'
			END
         
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @COBRAR EN CX ='+@COBRAR
		END
	END  
	ELSE
	BEGIN
		SELECT @COBRAR = 'SI'
	END
      
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @COBRAR DESPUES = '+@COBRAR   
	--  30.MAY.2005 JEDM 001 END
	--  Esto se hace para agilizar el cobro de copagos COMENZANDO UNA transaccion
      
	--  BEGIN TRAN */Se comentariza ya que detiene el proceso  de cargos
	SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'CETIPOAUTORIZACION'
   
    SELECT @TIPOAFI = TIPOAFILIADO FROM HADM WHERE NOADMISION=@NOADMISION

	SELECT @IDAFILIADO  = HADM.IDAFILIADO,
			@EDAD        = DATEDIFF(MONTH,AFI.FNACIMIENTO,@HOY),
			@TIPOAFI     = COALESCE(HADM.TIPOAFILIADO,AFI.TIPOAFILIADO),
			@IDPLAN      = HADM.IDPLAN,
			@IDMODELOPCA = PPT.IDMODELOPCH,
			@NIVELSOCIOE = HADM.NIVELSOCIOEC,
			@IDTERCERO   = HADM.IDTERCERO,
			@TIPOADM     = HADM.TIPOADM,
			@CLASIFPC    = AFI.CLASIFPC,
			@COPAGONOAUTORIZACION = HADM.COPAGONOAUTORIZACION,
			@PYP         = HADM.PYP,        
			@TIPOFACTURA = PPT.TIPOFACTURACION,
			@IDIPS       = HADM.IDPROVEEDOR
	FROM   AFI WITH(NOLOCK) INNER JOIN HADM ON AFI.IDAFILIADO = HADM.IDAFILIADO, PPT
	WHERE  HADM.NOADMISION   = @NOADMISION           
	AND    PPT.IDPLAN        = HADM.IDPLAN       
	AND    PPT.IDTERCERO     = HADM.IDTERCERO
   
	IF @DATO = 'CEHOSP'
	BEGIN
		SELECT @IDPLAN      = HPRED.IDPLAN,
				@IDTERCERO   = HPRED.IDTERCEROCA
		FROM   HPRED
		WHERE  HPRED.NOPRESTACION = @NOPRESTACION
		AND    HPRED.NOITEM       = @ITEM
      
		SELECT @IDMODELOPCA = PPT.IDMODELOPCH,
				@TIPOFACTURA = PPT.TIPOFACTURACION
		FROM   PPT
		WHERE  PPT.IDPLAN         = @IDPLAN       
		AND    PPT.IDTERCERO      = @IDTERCERO
	END
   
	IF 1=2  -- EZERPA 19/11/2020 Para calcular la edad sin ir al procedimiento almacenado
	BEGIN
		SELECT @CNSRPDX = CAST(RAND(1)  AS VARCHAR(20))
		EXEC DBO.SPK_EDAD @IDAFILIADO, @CNSRPDX
		SELECT @ANO = CANTIDAD1, @MES = CANTIDAD2, @DIA = CANTIDAD3 FROM RPDX WHERE CNS = @CNSRPDX
		
		DELETE RPDX WHERE CNS = @CNSRPDX
	END
	ELSE
	BEGIN
		SELECT @FNACIMIENTO = FNACIMIENTO FROM AFI WHERE IDAFILIADO = @IDAFILIADO
		SELECT @ANO=0, @MES=0
		IF floor((CONVERT([int],CONVERT([varchar](8),@HOY,(112)))-CONVERT([int],CONVERT([varchar](8),@FNACIMIENTO,(112))))/(10000))>(0)
			SET @ANO = CONVERT([varchar],floor((CONVERT([int],CONVERT([varchar](8),@HOY,(112)))-CONVERT([int],CONVERT([varchar](8),@FNACIMIENTO,(112))))/(10000)))
		ELSE IF datediff(month,@FNACIMIENTO,@HOY)>(0) 
			SET @MES = CONVERT([varchar],datediff(month,@FNACIMIENTO,@HOY))
			ELSE SET @DIA = CONVERT([varchar],datediff(day,@FNACIMIENTO,@HOY))
	END
	IF @ANO = 0
	BEGIN
		IF @MES = 0
		BEGIN
			SELECT @EDAD = 1
		END   
		ELSE
		BEGIN
			SELECT @EDAD = @MES
		END
	END    
	ELSE
	BEGIN
		SELECT @EDAD = (@ANO * 12) + @MES 
	END
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- ANO= '+STR(@ANO)+ '-MES='+STR(@MES)+' -DIA='+STR(@DIA)
   
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- EDAD=' + STR(@EDAD)
	SELECT @COBRARA     = COBRARA FROM HPRED 
	WHERE  NOPRESTACION = @NOPRESTACION
	AND    NOITEM       = @ITEM  
	print 'cobrara=' + @cobrara 
                                  
	SELECT @TIPOAFILIADO = CASE @TIPOAFI
							WHEN 'C' THEN 
								'Cotizante' 
							WHEN 'B' THEN 
								'Beneficiario' 
							WHEN 'A' THEN 
								'Adicional' 
							END
   
	SELECT @IDAREAH       = HPRE.IDAREAH,
			@IDAREA        = HPRE.IDAREA,
			@NIVELATENCION = HPRE.NIVELATENCION
	FROM   HPRE
	WHERE  HPRE.NOPRESTACION = @NOPRESTACION  
   
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @tipofactura = '+@TIPOFACTURA
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @TIPOAFILIADO= '+@TIPOAFILIADO
    
	IF @TIPOFACTURA = 'E'
	BEGIN
		SELECT @NODTACOPAGO    = CTXP.EXCENTOCOPAGO FROM CTXP
		WHERE  IDTERCERO       = @IDTERCERO
		AND    IDPLAN          = @IDPLAN
		AND    IDAREAH         = @IDAREAH
		AND    IDAREAFUNCIONAL = @IDAREA
		AND    IDPROVEEDOR     = @IDIPS
		AND    NIVELATENCION   = @NIVELATENCION   
		-- AQUI SE MIRA SI SE COBRA AL AFILIADO PARA NO COBRAR COPAGO
		IF @COBRAR = 'SI'
		BEGIN
			IF @NODTACOPAGO = 1 
			BEGIN 
			SELECT @COBRAR = 'NO'   
			END
			ELSE
			BEGIN
			SELECT @COBRAR = 'SI'    
			END
		END
	END
   
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- 333. IDMODELOPCA = ' + @IDMODELOPCA
	SELECT @IDSERVICIO   = HPRED.IDSERVICIO,
			@ALTOCOSTO    = HPRE.ALTOCOSTO,
			@TIPODEPAGO   = MOCP.TIPODEPAGO,
			@PCUBRIMIENTO = HPRED.PCUBRIMIENTO,
			@VALORSER     = HPRED.VALOR, 
			@CANTIDAD     = HPRED.CANTIDAD,
			@IDAREAH      = HPRE.IDAREAH,
			@IDAREA       = HPRE.IDAREA
	FROM   HPRED,HPRE,MOCP,SER
	WHERE  HPRED.NOPRESTACION = @NOPRESTACION
	AND    HPRED.NOITEM       = @ITEM
	AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
	AND    HPRED.IDSERVICIO   = SER.IDSERVICIO
	AND    MOCP.IDMODELOPC    = @IDMODELOPCA
	AND    MOCP.PREFIJO       = SER.PREFIJO
	AND    MOCP.NIVELATENCION = SER.NIVELATENCION
   
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- VALRSER='+ STR(@VALORSER)
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- CANTIDAD='+STR(@CANTIDAD)
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- ANTES DE NULL @IDSERVICIO='+@IDSERVICIO
	IF @VALORSER IS NULL
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- VALORSER NULO'
	ELSE
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- VALORSER NO NULO='+STR(@VALORSER)
   
	IF @IDSERVICIO IS NULL OR @VALORSER IS NULL OR @CANTIDAD IS NULL
	BEGIN
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- ENTRE A SERVICIO NULO'
		SELECT @IDSERVICIO   = HPRED.IDSERVICIO,   @ALTOCOSTO = HPRE.ALTOCOSTO,
				@PCUBRIMIENTO = HPRED.PCUBRIMIENTO, @VALORSER  = HPRED.VALOR, 
				@CANTIDAD     = HPRED.CANTIDAD
		FROM HPRED,HPRE
		WHERE HPRED.NOPRESTACION = @NOPRESTACION
		AND   HPRED.NOITEM       = @ITEM
		AND   HPRE.NOPRESTACION  = HPRED.NOPRESTACION
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- VALORSER='+STR(@VALORSER)
	END
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @IDSERVICIO='+@IDSERVICIO

	SELECT @VALORTOT = @VALORSER * @CANTIDAD

	PRINT '@VALORTOT'+CONVERT(VARCHAR(20),@VALORTOT )+'   @VALORSER='+CONVERT(VARCHAR(20),@VALORSER )+ ' @CANTIDAD='+CONVERT(VARCHAR(20),@CANTIDAD)
   
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @VALORTOT='+STR(@VALORTOT)
     
	SELECT @TIPOAFIORIGI = MOCC.COBRARCOPA,
			@CALCULARPOR  = MOCC.CALCULARPOR,
			@EXURGENCIA   = MOCC.EXURGENCIA,
			@EXALTOCOSTO  = MOCC.EXALTOCOSTO,
			@MCLASIFPC    = MOCC.MCLASIFPC,
			@MEDAD        = MOCC.MEDAD,
			@MAGS         = MOCC.MAGS,
			@MNIVELSE     = MOCC.MNIVELSE,
			@FORMACOBRO   = MOCC.FORMACOBRO,
			@REDONDEO     = MOCC.REDONDEO,
			@EXEDAD       = MOCC.EXEDAD,
			@EXPYP        = MOCC.EXPYP,
			@EXAREAS      = MOCC.EXAREAS
	FROM   MOCC
	WHERE  MOCC.IDMODELOPC = @IDMODELOPCA
	AND    MOCC.TIPODEPAGO = @TIPODEPAGO 
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @IDMODELOPCA='+@IDMODELOPCA
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @TIPODEPAGO ='+@TIPODEPAGO 
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @TIPOAFIORIGI='+@TIPOAFIORIGI   
	IF (@TIPOAFILIADO = @TIPOAFIORIGI OR @TIPOAFIORIGI = 'Ambos') AND @COBRAR = 'SI'
	BEGIN
		SELECT @COBRAR = 'SI' 
	END
	ELSE
	BEGIN
		SELECT @COBRAR = 'NO'   
	END
   
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- COBRAR DESP AFI= ' +  @COBRAR
   
	SELECT @ESEXARE = COUNT(*) FROM MOCA WHERE MOCA.IDMODELOPC = @IDMODELOPCA
			AND MOCA.IDAREAH = @IDAREAH AND MOCA.IDAREA = @IDAREA
         
	IF @ESEXARE > 0
		SELECT @COBRAR = 'NO'
     
	IF @PYP = 1 AND @EXPYP = 1
		SELECT @COBRAR = 'NO'
        
	IF @COBRARA = 'A'
		SELECT @COBRAR = 'NO'
   
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- COBRAR DESP EXC ' +  @COBRAR
   
	IF @COBRAR = 'SI' 
	BEGIN
		IF @CALCULARPOR = 'Item'
		BEGIN
			SELECT @TIPOATENCION = HTAD.TIPOATENCION 
			FROM HTAD
			WHERE TIPOADM = @TIPOADM   
			IF @TIPOATENCION = 'U' AND @EXURGENCIA = 1
			SELECT @COBRAR = 'NO'  
		END
		ELSE
		BEGIN
			SELECT @TIPOATENCION = HTAD.TIPOATENCION 
			FROM HTAD
			WHERE TIPOADM = @TIPOADM   
			IF @TIPOATENCION = 'U' AND @EXURGENCIA = 1
			SELECT @COBRAR = 'NO'  
			ELSE
			SELECT @COBRAR = 'OR'
		END
	END  
   
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- COBRAR DESP CALCULARPOR ' +  @COBRAR
   
	IF @COBRAR = 'SI' 
	BEGIN  
		IF @EXALTOCOSTO =1 AND @ALTOCOSTO = 'Si'
			SELECT @COBRAR = 'NO'
		IF @COPAGONOAUTORIZACION <> ''
			SELECT @COBRAR = 'HA'
		IF @EXEDAD > 0 AND @EDAD < @EXEDAD
			SELECT @COBRAR = 'NO'
	END
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- COBRAR DESP EXALTOCOSTO ' +  @COBRAR      
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- VALOR TOT='+STR(@VALORTOT)
	IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')<>'PERU'
	BEGIN
		IF @VALORTOT > 0 AND @VALORTOT < 1
		BEGIN
			SELECT @VALORTOT = 1
		END
    END
	IF @PCUBRIMIENTO <100
	BEGIN
		SELECT @VALORPCOMP = CASE @REDONDEO
							WHEN 'Unidad' THEN ROUND((@VALORTOT * ((100-@PCUBRIMIENTO)/100)),0)          
							WHEN 'Decena' THEN ROUND((@VALORTOT * ((100-@PCUBRIMIENTO)/100)),-1)
							WHEN 'Centena' THEN ROUND((@VALORTOT * ((100-@PCUBRIMIENTO)/100)),-2)
							WHEN 'Millar' THEN ROUND((@VALORTOT * ((100-@PCUBRIMIENTO)/100)),-3)
							ELSE ROUND((@VALORTOT * ((100-@PCUBRIMIENTO)/100)),0)
							END
	END
	ELSE
	BEGIN
		SELECT @VALORPCOMP = 0
	END
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- VALORPCOMP='+STR(@VALORPCOMP)      
	SELECT @VALORCOPAGO = 0  
    --QUERY2        
	IF @COBRAR = 'SI' OR @COBRAR = 'OR'
	BEGIN
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- ENTRE A COBRAR'
		IF @MCLASIFPC = 1 AND @MEDAD = 1 AND @MAGS =1 AND @MNIVELSE = 0      
		BEGIN
			SELECT @IDAGRUPACIONSER = IDAGRUPACIONSER
			FROM AGSD
			WHERE IDSERVICIO = @IDSERVICIO
			AND   IDMODELOPC = @IDMODELOPCA
			AND   TIPODEPAGO = @TIPODEPAGO
         
			SELECT @MOCCDVALOR       = MOCCD.VALOR,
				@MOCCDVALORMAXIMO = MOCCD.VALORMAXIMO,
				@MOCCDVALORTOPEANUAL = MOCCD.VALORTOPEANUAL
			FROM MOCCD
			WHERE IDMODELOPC = @IDMODELOPCA
			AND   TIPODEPAGO = @TIPODEPAGO
			AND   CLASIFPC   = @CLASIFPC
			AND   IDAGRUPACIONSER = @IDAGRUPACIONSER          
			AND   @EDAD >= EDADINICIAL AND @EDAD < EDADFINAL 
		END
		IF @MCLASIFPC = 0 AND @MEDAD = 0 AND @MAGS =0 AND @MNIVELSE = 1      
		BEGIN   
			SELECT @MOCCDVALOR          = MOCCD.VALOR,
				@MOCCDVALORMAXIMO    = MOCCD.VALORMAXIMO,
				@MOCCDVALORTOPEANUAL = MOCCD.VALORTOPEANUAL
			FROM   MOCCD
			WHERE  IDMODELOPC = @IDMODELOPCA
			AND    TIPODEPAGO = @TIPODEPAGO
			AND    ESCALASE   = @NIVELSOCIOE        
		END
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @MOCCDVALORMAXIMO=' +cast(@MOCCDVALORMAXIMO as varchar(20))
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @COBRAR = '+ @COBRAR 
		IF @MOCCDVALOR IS NULL
			SELECT @MOCCDVALOR  = 0
		IF @COBRAR = 'SI'
		BEGIN
			SELECT @COPAGOGLOBAL = SUM(HPRE.VALORCOPAGO)
			FROM   HPRE
			WHERE  HPRE.NOADMISION = @NOADMISION
         
			SELECT @COPAGOGLOBAL = SUM(HPRED.VALORCOPAGONORMAL)
			FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
			WHERE  HPRE.NOADMISION = @NOADMISION
         
         
			--@COPAGOACUM_NORMAL
         
			-- PARA SUMAR EL COPAGO EXTERNO
			SELECT @VLR_COPAGOEXTERNO = COALESCE(VLR_COPAGOEXTERNO,0)
			FROM   HADM
			WHERE  NOADMISION = @NOADMISION
         
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @COPAGOGLOBAL='+CAST(@COPAGOGLOBAL AS VARCHAR(20))
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @VLR_COPAGOEXTERNO= '+CAST(@VLR_COPAGOEXTERNO AS VARCHAR(20))
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @TOPECOP_ANX6='+CAST(@TOPECOP_ANX6 AS VARCHAR(20))
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @VALORCOPAGO ANTES='+CAST(@VALORCOPAGO AS VARCHAR(20))
			SELECT @VALORCOPAGO = CASE @FORMACOBRO
								WHEN 'Porcentaje' THEN 
									CASE @REDONDEO
										WHEN 'Unidad' then round((@VALORTOT - @VALORPCOMP) * (@MOCCDVALOR/100),0)
										WHEN 'Decena' then round((@VALORTOT - @VALORPCOMP) * (@MOCCDVALOR/100),-1)
										WHEN 'Centena' then round((@VALORTOT - @VALORPCOMP) * (@MOCCDVALOR/100),-2)
										WHEN 'Millar' then round((@VALORTOT - @VALORPCOMP) * (@MOCCDVALOR/100),-3)
									ELSE round((@VALORTOT - @VALORPCOMP) * (@MOCCDVALOR/100),0)
									END 
								WHEN 'Valor'      THEN @MOCCDVALOR
								END
			SELECT @IND_PASTOPEANUAL = 0
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @VALORCOPAGO='+CAST(@VALORCOPAGO AS VARCHAR(20))
         
			IF @TOPECOP_ANX6 > 0
			BEGIN
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- HAY  @TOPECOP_ANX6 > 0 '
			IF (@COPAGOGLOBAL + @VALORCOPAGO /*+ @VLR_COPAGOEXTERNO*/) > @TOPECOP_ANX6
			BEGIN
				SELECT @VALORCOPAGO = COALESCE(@TOPECOP_ANX6 - @COPAGOGLOBAL /*- @VLR_COPAGOEXTERNO*/,0)             
				IF @VALORCOPAGO < 0
				BEGIN
					SELECT @VALORCOPAGO = 0
				END
			END
			END
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @COPAGOGLOBAL='+CONVERT(VARCHAR,@COPAGOGLOBAL)+'//@VALORCOPAGO='+CONVERT(VARCHAR,@VALORCOPAGO)+'//@MOCCDVALORMAXIMO='+CONVERT(VARCHAR,@MOCCDVALORMAXIMO)
			IF @VALORCOPAGO > 0
			BEGIN
			IF @MOCCDVALORMAXIMO > 0
			BEGIN            
				IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- ENTRE POR VALOR MAXIMO EVENTO'
				IF (@COPAGOGLOBAL + @VALORCOPAGO /*+ @VLR_COPAGOEXTERNO*/) >  @MOCCDVALORMAXIMO
				BEGIN
					SELECT @VALORCOPAGO = COALESCE(@MOCCDVALORMAXIMO - @COPAGOGLOBAL /*- @VLR_COPAGOEXTERNO*/,0)             
					IF @VALORCOPAGO < 0
					BEGIN
						SELECT @VALORCOPAGO = 0
					END
					IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- SI SE PASA DEL TOPE POR EVENTO EL VALOR DE COPAGO QUEDA='   +CAST (@VALORCOPAGO AS VARCHAR(20))
					SELECT @IND_PASTOPEANUAL = 1
				END
			END
			END   
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- NUEVO: PARA REVISAR EL TOPE DE COPAGO ANUAL'
			IF @VALORCOPAGO > 0 -- COBRA ALGO DE COPAGO ES DECIR NO HA LLEGADO AL MAXIMO TOPE DE LA ADMISION
			BEGIN
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- -- COBRA ALGO DE COPAGO ES DECIR NO HA LLEGADO AL MAXIMO TOPE DE LA ADMISION'
			IF @MOCCDVALORTOPEANUAL > 0
			BEGIN
				IF (/*@VLR_COPAGOEXTERNO + */@COPAGOGLOBAL + @VALORCOPAGO) > @MOCCDVALORTOPEANUAL
				BEGIN
					IF (@MOCCDVALORTOPEANUAL - (/*@VLR_COPAGOEXTERNO+*/@COPAGOGLOBAL)) < @VALORCOPAGO
					BEGIN
					SELECT @VALORCOPAGO = (@MOCCDVALORTOPEANUAL - (/*@VLR_COPAGOEXTERNO+*/@COPAGOGLOBAL))
					END  
				END  
			END
			END 
			IF @VALORCOPAGO IS NULL
			BEGIN
			SELECT @VALORCOPAGO = 0
			END
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- SALGO DE TOPES... COPAGO DEFINITIVO '+LTRIM(RTRIM(STR(@VALORCOPAGO)))
			UPDATE HPRED SET VALORCOPAGONORMAL = @VALORCOPAGO WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM
			/*AQUI SE DEBE RESTAR EL COPAGO EXTERNO*/
			IF @VLR_COPAGOEXTERNO > 0
			BEGIN
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- NUEVO' 
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @COPAGOEXTERNOACUM='+CAST (@COPAGOEXTERNOACUM AS VARCHAR(20))
            
			SELECT @COPAGOEXTERNOACUM = SUM(COALESCE(HPRED.VALORCOPAGOEXTERNO,0)) 
			FROM   HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE  HPRE.NOADMISION    = @NOADMISION
            
			IF COALESCE(@COPAGOEXTERNOACUM,0) < COALESCE(@VLR_COPAGOEXTERNO,0)
			BEGIN 
				SELECT @COPEXTERNO_RESTANTE = COALESCE(@VLR_COPAGOEXTERNO,0) - COALESCE(@COPAGOEXTERNOACUM,0)
				IF @VALORCOPAGO <= @COPEXTERNO_RESTANTE
				BEGIN
					UPDATE HPRED SET HPRED.VALORCOPAGOEXTERNO = @VALORCOPAGO WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM
					SELECT @VALORCOPAGO = 0                  
				END
				ELSE
				BEGIN
					UPDATE HPRED SET HPRED.VALORCOPAGOEXTERNO = @COPEXTERNO_RESTANTE WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM      
					SELECT @VALORCOPAGO = @VALORCOPAGO - @COPEXTERNO_RESTANTE
				END
			END
			END   
		END
	END
	if @MOCCDVALOR IS NULL
		SELECT @MOCCDVALOR = 0
	IF @MOCCDVALORMAXIMO IS NULL
		SELECT @MOCCDVALOR = 0
	IF @VALORPCOMP IS NULL
		SELECT @VALORPCOMP = 0 
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- ANTES DE VALIDACION PERU'
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @IDTERCEROCA='+@IDTERCEROCA
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @IDPLANCA='+@IDPLANCA
	IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' 
	BEGIN --Valores de copago a PERU
		PRINT 'INGRESO A PERU....'
		PRINT '@VALORTOT'+CONVERT(VARCHAR(20),COALESCE(@VALORTOT,0))
		PRINT '@VALORCOPAGO=' +CONVERT(VARCHAR(20),COALESCE(@VALORCOPAGO,0))
      PRINT '@IDTERCEROCA=' +COALESCE(@IDTERCEROCA,'')
      PRINT '@IDPLANCA='+COALESCE(@IDPLANCA,'')

        --Copago desde PPT
        IF 1=(SELECT ISNULL(COBRACOPAGO,0) FROM PPT WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLANCA)
        BEGIN
            PRINT 'SI COBRA COPAGO....'
            IF EXISTS(SELECT * FROM PPTD WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLANCA AND IDSERVICIO=@IDSERVICIO) AND COALESCE(@VALORCOPAGO,0)=0
		      BEGIN
			      SELECT @VALORCOPAGO=@VALORTOT*(COALESCE(PPTD.CANTNOCOBRABLE,0.00)/100.00) FROM PPTD 
			      WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLANCA AND IDSERVICIO=@IDSERVICIO
		      END
            IF @VALORCOPAGO = 0
               SELECT @VALORCOPAGO = CASE ISNULL(MRECARGONOCTURNO,0)
			                               WHEN 1 THEN (CASE ISNULL(TIPORECARGONOC,'')
			                               WHEN 'Porcentaje' THEN (@VALORTOT * (VLRRECARGONOC)) / 100.00
			                               WHEN 'Valor' THEN VLRRECARGONOC
			                               ELSE @VALORCOPAGO END)
			                               ELSE @VALORCOPAGO 
                                      END
			       FROM SER WHERE IDSERVICIO=@IDSERVICIO

		    IF EXISTS(SELECT * FROM SER INNER JOIN IART ON SER.IDSERVICIO=IART.IDARTICULO WHERE SER.IDSERVICIO=@IDSERVICIO AND COALESCE(IART.ENTREGA_TURNO,0)=1 AND COALESCE(IART.UTILIDAD,0)>0)
		    BEGIN
			    PRINT 'INGRSO POR DE MARCA O GENERICO'
			    SELECT @VALORCOPAGO=@VALORTOT*(COALESCE(IART.UTILIDAD,0)/100)
			    FROM   IART 
			    WHERE  IDARTICULO=@IDSERVICIO
		    END
		    
        END       
        IF 1=(SELECT ISNULL(COPAGO_PORC,0) FROM PPT WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLANCA)
        BEGIN
		    IF EXISTS(SELECT * FROM PPTD WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLANCA AND IDSERVICIO=@IDSERVICIO) AND COALESCE(@VALORCOPAGO,0)=0
		    BEGIN
			    SELECT @VALORCOPAGO=@VALORTOT*(COALESCE(PPTD.CANTNOCOBRABLE,0.00)/100.00) FROM PPTD 
			    WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLANCA AND IDSERVICIO=@IDSERVICIO
		    END
            ELSE
            BEGIN
               IF EXISTS( SELECT *  FROM HADMAUT  WHERE NOADMISION=@NOADMISION 
                        AND IDPLAN=@IDPLANCA AND ISNULL(N_FACTURA,'')=''
                        AND CONVERT(DATE,@FECHACARGO) BETWEEN F_INICIAL AND F_FINAL
                        AND COALESCE(COPAGO_PORC,0.00)>0)
               BEGIN
                   SELECT @VALORCOPAGO=@VALORTOT*(COALESCE(COPAGO_PORC,0.00)/100.00)
                   FROM HADMAUT 
                   WHERE NOADMISION=@NOADMISION AND IDPLAN=@IDPLANCA AND ISNULL(N_FACTURA,'')=''
                   AND CONVERT(DATE,@FECHACARGO) BETWEEN F_INICIAL AND F_FINAL
                   AND COALESCE(COPAGO_PORC,0.00)>0
               END
            END
        END
	END
    
	PRINT '@VALORCOPAGO'+CONVERT(VARCHAR(20),COALESCE(@VALORCOPAGO,0))
	IF @VALORCOPAGO IS NULL
	BEGIN
		SELECT @VALORCOPAGO=0
	END

   IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
   BEGIN
	  PRINT '@COPAGONOAUTORIZACION' + @COPAGONOAUTORIZACION
      IF @COPAGONOAUTORIZACION<>'' AND @COPAGOVALOR>0
         SET @VALORCOPAGO=@COPAGOVALOR / (1.0+(COALESCE((SELECT VALOR FROM FIMPDV WHERE GETDATE() BETWEEN FECHAINI AND FECHAFIN AND IDIMPUESTO IN (SELECT DATO FROM USVGS WHERE IDVARIABLE='IDIMP_IVA')),18.0)/100))

      SELECT @VALOREXCEDENTE = @VALORTOT - @VALORPCOMP - @VALORCOPAGO
   END
   ELSE
   BEGIN
	   IF UPPER(@CIRUGIA)='SI'
		  SELECT @VALOREXCEDENTE = @VALORTOT - @VALORPCOMP - @VALORCOPAGO
	   ELSE
		  SELECT @VALOREXCEDENTE = ROUND(@VALORTOT - @VALORPCOMP - @VALORCOPAGO,0)
   END

	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- 2222.VALORTOT='    + STR(@VALORTOT)
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- 2222.VALORPCOMP='  + STR(@VALORPCOMP)
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- 2222.VALORCOPAGO=' + STR(@VALORCOPAGO)      
      
   
	IF @NOCOBRABLE = 2
	BEGIN
		UPDATE HPRED SET VALOR = 0 WHERE NOPRESTACION = @NOPRESTACION AND NOITEM = @ITEM
		SELECT @VALORPCOMP = 0, @VALORTOT = 0, @VALOREXCEDENTE = 0
	END
   
	IF @VALORCOPAGO IS NULL
		SELECT @VALORCOPAGO = 0

	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- 1111.VALOR EXCEDENTE ='+STR(@VALOREXCEDENTE) 

	UPDATE HPRED SET VALORCOPAGO = @VALORCOPAGO , VALORPCOMP = @VALORPCOMP,
					VALOREXCEDENTE = @VALOREXCEDENTE
	WHERE HPRED.NOPRESTACION = @NOPRESTACION
	AND   HPRED.NOITEM = @ITEM
   

	--select * from hpred where hpred.noprestacion = @noprestacion and hpred.noitem = @item --!!
   
	SELECT @VT = ROUND(SUM(HPRED.VALOR * HPRED.CANTIDAD),0), @VE = SUM(HPRED.VALOREXCEDENTE),
			@VC = SUM(HPRED.VALORCOPAGO), @VP = SUM(HPRED.VALORPCOMP)
	FROM   HPRED
	WHERE  HPRED.NOPRESTACION = @NOPRESTACION
   
	UPDATE HPRE SET VALORTOTAL  = @VT,VALOREXEDENTE = @VE,
					VALORCOPAGO = @VC,VALORPCOMP    = @VP 
	WHERE HPRE.NOPRESTACION = @NOPRESTACION
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- SIGO.... ACA DEBERIA TERMINAR...'                    

	IF @COBRAR = 'OR'
	BEGIN
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- --- INICIALIZAR EN LOS DETALLES DE PRESTACION EL COPAGO Y EL VALOR PCOMP EN 0'
		UPDATE HPRED SET VALORCOPAGO = 0,VALORPCOMP = 0,VALOREXCEDENTE = VALOR*CANTIDAD
		WHERE HPRED.NOPRESTACION = @NOPRESTACION
		--- CALCULAR EL PAGO COMPARTIDO EN LOS DETALLES
		IF @PCUBRIMIENTO <100
			UPDATE HPRED SET VALORPCOMP = CASE @REDONDEO
							WHEN 'Unidad'  THEN ROUND(((VALOR*CANTIDAD) * ((100-@PCUBRIMIENTO)/100)),0)          
							WHEN 'Decena'  THEN ROUND(((VALOR*CANTIDAD) * ((100-@PCUBRIMIENTO)/100)),-1)
							WHEN 'Centena' THEN ROUND(((VALOR*CANTIDAD) * ((100-@PCUBRIMIENTO)/100)),-2)
							WHEN 'Millar'  THEN ROUND(((VALOR*CANTIDAD) * ((100-@PCUBRIMIENTO)/100)),-3)
							ELSE                ROUND(((VALOR*CANTIDAD) * ((100-@PCUBRIMIENTO)/100)),0)
							END
			WHERE NOPRESTACION = @NOPRESTACION       
		ELSE
			UPDATE HPRED SET VALORPCOMP = 0 WHERE NOPRESTACION = @NOPRESTACION
		--- ACTUALIZAR LOS CAMPOS TOTALES DE LA PRESTACION CON LA SUMATORIA DE LOS
		--- DETALLES          
		SELECT @VT = SUM(HPRED.VALOR * HPRED.CANTIDAD), @VE = SUM(HPRED.VALOREXCEDENTE),
				@VC = SUM(HPRED.VALORCOPAGO), @VP = SUM(HPRED.VALORPCOMP)
		FROM HPRED
		WHERE HPRED.NOPRESTACION = @NOPRESTACION
     
		UPDATE HPRE SET VALORTOTAL  = @VT,VALOREXEDENTE = @VE,
						VALORCOPAGO = @VC,VALORPCOMP    = @VP 
		WHERE HPRE.NOPRESTACION = @NOPRESTACION
		--- AVERIGUAR CUANTO VA EL COPAGO TOTAL SIN ESTA PRESTACION 
		SELECT @COPAGOGLOBAL = SUM(HPRE.VALORCOPAGO) FROM HPRE
		WHERE  HPRE.NOADMISION = @NOADMISION
		--- AVERIGUAR CUANTO SERIA EL COPAGO DE ESTA PRESTACION
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- VOY A CALCULAR EL COPAGO'
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @FORMACOBRO == '+@FORMACOBRO
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @REDONDEO =='+COALESCE(@REDONDEO,'NO TENGO')
		SELECT @VALORCOPAGO = CASE @FORMACOBRO
							WHEN 'Porcentaje' THEN 
									CASE @REDONDEO
									WHEN 'Unidad'  then round((@VT - @VP) * (@MOCCDVALOR/100),0)
									WHEN 'Decena'  then round((@VT - @VP) * (@MOCCDVALOR/100),-1)
									WHEN 'Centena' then round((@VT - @VP) * (@MOCCDVALOR/100),-2)
									WHEN 'Millar'  then round((@VT - @VP) * (@MOCCDVALOR/100),-3)
									ELSE                round((@VT - @VP) * (@MOCCDVALOR/100),0)
									END 
							WHEN 'Valor'      THEN @MOCCDVALOR
							END
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- SALI DEL REDONDEO VALOR DESPUES DE REDONDEO =='+LTRIM(RTRIM(STR(@VALORCOPAGO)))
		--- SE PREGUNTA SI ESTA ADMISION TIENE VALOR MAXIMO DEFINID0
		--- EN EL MODELO DE PAGOS COMP.
		IF @MOCCDVALORMAXIMO > 0
		BEGIN
			IF @TOPECOP_ANX6>0
			BEGIN
			SELECT @MOCCDVALORMAXIMO=@TOPECOP_ANX6
			END
			IF (@COPAGOGLOBAL + @VALORCOPAGO) > @MOCCDVALORMAXIMO
			BEGIN
			SELECT @VALORCOPAGO = @MOCCDVALORMAXIMO - @COPAGOGLOBAL 
			END
		END
		-- NUEVO: PARA REVISAR EL TOPE DE COPAGO ANUAL
		IF @VALORCOPAGO > 0 -- COBRA ALGO DE COPAGO ES DECIR NO HA LLEGADO AL MAXIMO TOPE DE LA ADMISION
		BEGIN
			IF @MOCCDVALORTOPEANUAL > 0
			BEGIN
			IF (@VLR_COPAGOEXTERNO + @COPAGOGLOBAL + @VALORCOPAGO) > @MOCCDVALORTOPEANUAL
			BEGIN
				IF (@MOCCDVALORTOPEANUAL - (@VLR_COPAGOEXTERNO+@COPAGOGLOBAL)) < @VALORCOPAGO
				BEGIN
					SELECT @VALORCOPAGO = (@MOCCDVALORTOPEANUAL - (@VLR_COPAGOEXTERNO+@COPAGOGLOBAL))
				END  
			END  
			END
		END 
		IF @VALORCOPAGO<0
		BEGIN
			SELECT @VALORCOPAGO=0
		END


		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- --- ACTUALIZO EN LA PRESTACION EL VALOR COPAGO'
		UPDATE HPRE SET VALORCOPAGO = @VALORCOPAGO 
		WHERE  HPRE.NOPRESTACION    = @NOPRESTACION
		--- REPARTIR EL COPAGO ENTRE LOS DETALLES 
		IF  (SELECT COALESCE(HPRE.VALORTOTAL,0) FROM HPRE WHERE NOPRESTACION=@NOPRESTACION)>0
		BEGIN
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- --- REPARTIR EL COPAGO ENTRE LOS DETALLES '
			
			UPDATE HPRED SET VALORCOPAGO = CASE @FORMACOBRO
										WHEN 'Porcentaje' THEN 
												CASE @REDONDEO
												WHEN 'Unidad'  then round((((HPRED.VALOR*HPRED.CANTIDAD)*HPRE.VALORCOPAGO)/HPRE.VALORTOTAL),0)
												WHEN 'Decena'  then round((((HPRED.VALOR*HPRED.CANTIDAD)*HPRE.VALORCOPAGO)/HPRE.VALORTOTAL),-1)
												WHEN 'Centena' then round((((HPRED.VALOR*HPRED.CANTIDAD)*HPRE.VALORCOPAGO)/HPRE.VALORTOTAL),-2)
												WHEN 'Millar'  then round((((HPRED.VALOR*HPRED.CANTIDAD)*HPRE.VALORCOPAGO)/HPRE.VALORTOTAL),-3)
												ELSE                round((((HPRED.VALOR*HPRED.CANTIDAD)*HPRE.VALORCOPAGO)/HPRE.VALORTOTAL),0)
												END 
										WHEN 'Valor'      THEN @MOCCDVALOR
										END          
			FROM   HPRE
			WHERE  HPRED.NOPRESTACION = @NOPRESTACION
			AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
		END


		--- CALCULAR EL VALOR EXCEDENTE DE LOS DETALLES 
		UPDATE HPRED SET VALOREXCEDENTE = CASE @REDONDEO
									WHEN 'Unidad'  then round(((VALOR * CANTIDAD)- VALORCOPAGO - VALORPCOMP),0)
									WHEN 'Decena'  then round(((VALOR * CANTIDAD)- VALORCOPAGO - VALORPCOMP),-1)
									WHEN 'Centena' then round(((VALOR * CANTIDAD)- VALORCOPAGO - VALORPCOMP),-2)
									WHEN 'Millar'  then round(((VALOR * CANTIDAD)- VALORCOPAGO - VALORPCOMP),-3)
									ELSE                round(((VALOR * CANTIDAD)- VALORCOPAGO - VALORPCOMP),0)
									END 
		WHERE  HPRED.NOPRESTACION       = @NOPRESTACION

		--- CALCULAR EL VALOR EXCEDENTE DE LA PRESTACION
		SELECT @VE = SUM(HPRED.VALOREXCEDENTE)
		FROM HPRED
		WHERE HPRED.NOPRESTACION = @NOPRESTACION

		UPDATE HPRE SET VALOREXEDENTE = @VE
		WHERE HPRE.NOPRESTACION = @NOPRESTACION
	END

	--IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND @IDPLANCA IN ('PAR001','PAR002')
	--BEGIN
	--	UPDATE HPRED SET VALORCOPAGO=VALOR*CANTIDAD WHERE  NOPRESTACION=@NOPRESTACION
		 
	--	UPDATE HPRED SET VALOREXCEDENTE = ((VALOR * CANTIDAD)- VALORCOPAGO - VALORPCOMP)
	--	WHERE  HPRED.NOPRESTACION       = @NOPRESTACION
	--END

	-- REVISO SI LA PRESTACION ES NOPOS Y DEBO DESCONTAR HOLOMOLOGO, NUEVO NO SE DEBE ESPECIFICAR EL ITEM...
	IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- REVISO SI LA PRESTACION ES NOPOS Y DEBO DESCONTAR HOLOMOLOGO, NUEVO NO SE DEBE ESPECIFICAR EL ITEM...'
	IF EXISTS(SELECT * FROM HPRED WHERE COALESCE(NPRESTACIONH,'')=@NOPRESTACION )
	BEGIN
		SELECT @VLRHOMOLOGO=SUM(VALOREXCEDENTE) FROM HPRED WHERE COALESCE(NPRESTACIONH,'')=@NOPRESTACION 
		UPDATE HPRED SET VALOREXCEDENTE = VALOREXCEDENTE-@VLRHOMOLOGO
		WHERE  HPRED.NOPRESTACION       = @NOPRESTACION
		--AND    HPRED.NOITEM=@ITEM

		UPDATE HPRED SET VLRSERVICIOH=@VLRHOMOLOGO WHERE NOPRESTACION=@NOPRESTACION --AND NOITEM=@ITEM

		SELECT @VE = SUM(HPRED.VALOREXCEDENTE)
		FROM HPRED
		WHERE HPRED.NOPRESTACION = @NOPRESTACION

		UPDATE HPRE SET VALOREXEDENTE = @VE
		WHERE HPRE.NOPRESTACION = @NOPRESTACION
	END
   
       
	--  esto se hace para agilizar el cobro de copagos terminando la transaccion
	-- COMMIT
	/*SE RELIQUIDA EL ACCIDENTE DE TRANSITO SI LA ADMISION LO ES  JEDM:2011.MAYO.12_16:45*/
	IF (SELECT TIPOADM FROM HADM WHERE NOADMISION = @NOADMISION ) = DBO.FNK_VALORVARIABLE('IDTARIFASOAT')
	BEGIN
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- SE RELIQUIDA EL ACCIDENTE DE TRANSITO SI LA ADMISION LO ES'
		SELECT @CNSHACTRAN = CNSHACTRAN FROM HADM WHERE NOADMISION = @NOADMISION
		EXEC SPK_RELIQ_HACTRAN @CNSHACTRAN
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- DESPUES DE RELIQUIDAR'
	END

   IF @COPAGOPERU=1
      EXEC SPK_ADD_DEL_COPAGOS_HPRED @NOPRESTACION, @ITEM, 0,'01', 'Automatico'
END
