
--Brw:InfoGral
FREE(QUE:GLOCON)
LOOP I# = 1 TO RECORDS(GLO::TER)
    GET(GLO::TER,I#)
    GLO:IDTERCERO = Q::IDTERCERO

    IF GLO:FECHAINICIAL <> 0 THEN
        IF GLO:N_FACTURA <> '' THEN
                LOC:CONSULTA ='SELECT T.NIT,T.RAZONSOCIAL,D.NUMFACTURA,N.CODOBS,G.DESCRICIPCION,D.VALORFACTURA,D.VALORGLOSAS,D.VALORAPAGAR FROM TER T ' &|
                              'INNER JOIN RAD R ON R.IDTERCERO = T.IDTERCERO ' &|
                              'INNER JOIN RADD D ON D.CONSECUTIVO = R.CONSECUTIVO ' &|
                              'INNER JOIN RADDFMT F ON F.CONSECUTIVO = D.CONSECUTIVO AND F.ITEM = D.ITEM ' &|
                              'INNER JOIN RADN N ON N.CONSECUTIVO = F.CONSECUTIVO AND N.ITEM = F.ITEM AND N.CUENTA = F.CUENTA ' &|
                              'INNER JOIN LCODG G ON G.CODIGLOSA = N.CODOBS ' &|
                              'WHERE T.IDTERCERO = '''& GLO:IDTERCERO &''' AND D.NUMFACTURA = '''& GLO:N_FACTURA &''' ' &|
                              'AND D.FECHAREGISTRO BETWEEN ''' & FORMAT(GLO:FECHAINICIAL,@D12) & ' 00:00:00'' AND ''' & FORMAT(GLO:FECHAFINAL,@D12) & ' 23:59:59'''

        ELSE

                LOC:CONSULTA = 'SELECT T.NIT,T.RAZONSOCIAL,D.NUMFACTURA,N.CODOBS,G.DESCRICIPCION,D.VALORFACTURA,D.VALORGLOSAS,D.VALORAPAGAR FROM TER T ' &|
                              'INNER JOIN RAD R ON R.IDTERCERO = T.IDTERCERO ' &|
                              'INNER JOIN RADD D ON D.CONSECUTIVO = R.CONSECUTIVO ' &|
                              'INNER JOIN RADDFMT F ON F.CONSECUTIVO = D.CONSECUTIVO AND F.ITEM = D.ITEM ' &|
                              'INNER JOIN RADN N ON N.CONSECUTIVO = F.CONSECUTIVO AND N.ITEM = F.ITEM AND N.CUENTA = F.CUENTA ' &|
                              'INNER JOIN LCODG G ON G.CODIGLOSA = N.CODOBS ' &|
                              'WHERE T.IDTERCERO = '''& GLO:IDTERCERO &''' ' &|
                              'AND D.FECHAREGISTRO BETWEEN ''' & FORMAT(GLO:FECHAINICIAL,@D12) & ' 00:00:00'' AND ''' & FORMAT(GLO:FECHAFINAL,@D12) & ' 23:59:59'''


        END
    ELSE
        IF GLO:N_FACTURA <> '' THEN

                LOC:CONSULTA ='SELECT T.NIT,T.RAZONSOCIAL,D.NUMFACTURA,N.CODOBS,G.DESCRICIPCION,D.VALORFACTURA,D.VALORGLOSAS,D.VALORAPAGAR FROM TER T ' &|
                              'INNER JOIN RAD R ON R.IDTERCERO = T.IDTERCERO ' &|
                              'INNER JOIN RADD D ON D.CONSECUTIVO = R.CONSECUTIVO ' &|
                              'INNER JOIN RADDFMT F ON F.CONSECUTIVO = D.CONSECUTIVO AND F.ITEM = D.ITEM ' &|
                              'INNER JOIN RADN N ON N.CONSECUTIVO = F.CONSECUTIVO AND N.ITEM = F.ITEM AND N.CUENTA = F.CUENTA ' &|
                              'INNER JOIN LCODG G ON G.CODIGLOSA = N.CODOBS ' &|
                               'WHERE T.IDTERCERO = '''& GLO:IDTERCERO &''' AND D.NUMFACTURA = '''& GLO:N_FACTURA &''' '

        ELSE
                LOC:CONSULTA ='SELECT T.NIT,T.RAZONSOCIAL,D.NUMFACTURA,N.CODOBS,G.DESCRICIPCION,D.VALORFACTURA,D.VALORGLOSAS,D.VALORAPAGAR FROM TER T ' &|
                              'INNER JOIN RAD R ON R.IDTERCERO = T.IDTERCERO ' &|
                              'INNER JOIN RADD D ON D.CONSECUTIVO = R.CONSECUTIVO ' &|
                              'INNER JOIN RADDFMT F ON F.CONSECUTIVO = D.CONSECUTIVO AND F.ITEM = D.ITEM ' &|
                              'INNER JOIN RADN N ON N.CONSECUTIVO = F.CONSECUTIVO AND N.ITEM = F.ITEM AND N.CUENTA = F.CUENTA ' &|
                              'INNER JOIN LCODG G ON G.CODIGLOSA = N.CODOBS ' &|
                              'WHERE T.IDTERCERO = '''& GLO:IDTERCERO &''' '
        END
    END

    IF GLO:N_FACTURA <> '' THEN
                LOC:CONSULTA ='SELECT T.NIT,T.RAZONSOCIAL,D.NUMFACTURA,N.CODOBS,G.DESCRICIPCION,D.VALORFACTURA,D.VALORGLOSAS,D.VALORAPAGAR FROM TER T ' &|
                              'INNER JOIN RAD R ON R.IDTERCERO = T.IDTERCERO ' &|
                              'INNER JOIN RADD D ON D.CONSECUTIVO = R.CONSECUTIVO ' &|
                              'INNER JOIN RADDFMT F ON F.CONSECUTIVO = D.CONSECUTIVO AND F.ITEM = D.ITEM ' &|
                              'INNER JOIN RADN N ON N.CONSECUTIVO = F.CONSECUTIVO AND N.ITEM = F.ITEM AND N.CUENTA = F.CUENTA ' &|
                              'INNER JOIN LCODG G ON G.CODIGLOSA = N.CODOBS ' &|
                              'WHERE D.NUMFACTURA = '''& GLO:N_FACTURA &''' '
    END

    SETCURSOR(CURSOR:WAIT)
     
    CLEAR(WDUM:RECORD)
    IF FNVALORVARIABLE('IDDEPURAR')='SI' AND GLO:GRUPO='PPAL' THEN
       SETCLIPBOARD(LOC:CONSULTA)
       STOP('SQL CONSULTA')
    END
    WDUM{PROP:SQL} = LOC:CONSULTA
    IF ERRORCODE()
        MESSAGE('ERROR')
    ELSE
        LOOP UNTIL ACCESS:WDUM.NEXT()
            Q:NIT        = WDU:C1
            Q:RAZONSOC   = WDU:C2
            Q:NUMFAC     = WDU:C3
            Q:CODGLO     = WDU:C4
            Q:DESCGLO    = WDU:C5
            Q:VRFACTURAS = WDU:C6
            Q:VRGLOSAS   = WDU:C7
            Q:VRPAGAR    = WDU:C8

            ADD(QUE:GLOCON)
        END
    END
END
SETCURSOR
DISPLAY
