  IF (SELECT COUNT(*) FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)>0
   BEGIN
      INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
      SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
      FROM   MCP
      WHERE NROCOMPROBANTE=@NROCOMPROBANTE
      --se borran de mcp, mch
      DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
      DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE   
   END
   DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   
   
   EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME
   
   
   loc:usuario = 'JMJB' AND LOC:CLAVE = 'LOCAVU20JO14'
   
