
SELECT * FROM API_LOG ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FCXC_COL","METODO":"TRAER_TTEC","USUARIO":"JJIMENEZ"}'

BEGIN TRAN 
EXEC SPQ_JSON'{"MODELO":"FCXC_COL","METODO":"ABRIR_FCXC","PARAMETROS":{"CNSCXC":"0200000181"},"USUARIO":"JJIMENEZ"}'
ROLLBACK

UPDATE FTR SET INDASIGCXC=0,INDCXC=0 WHERE N_FACTURA='UV11453'

SELECT CERRADA,INDRECIBIDO, * FROM FCXC WHERE CNSCXC='0200000181'


SELECT N_FACTURA,VALORFACTURA,DEDUCCIONES,VLRGLOSAS,VLRGLOSAS_R,VLRPAGOS,VLRNOTADB,VLRNOTACR,COALESCE(IDPLAN,'')IDPLAN FROM FCXCD



SELECT  FCXC.CNSCXC,FCXC.IDSEDE,CONVERT(VARCHAR,FCXC.FECHACXC,103)FECHACXC,COALESCE(CONVERT(VARCHAR,FCXC.F_RECIBIDO,103),'')F_RECIBIDO,TER.NIT,TER.RAZONSOCIAL,                               FCXC.VALORCXC,FCXC.VLRPAGOS,FCXC.VLRNOTACR,VLRNOTADB,VLRGLOSAS,FCXC.SALDONETO,FCXC.ESTADO,MSEDE AS REQSEDE,MODALIDAD,ATENCION,MES,ANO,REGIMEN,                               COALESCE(INDRECIBIDO,0)INDRECIBIDO,COALESCE(CERRADA,0) CERRADA  FROM [dbo].[FCXC] INNER JOIN  TER ON FCXC.IDTERCERO=TER.IDTERCERO  WHERE (RAZONSOCIAL LIKE '%%%%' OR NIT LIKE '%%%%' OR  CNSCXC LIKE '%%%%') AND 1=1 AND CONVERT(DATE,FECHACXC)>='2023-09-09'  AND CONVERT(DATE,FECHACXC)<='2023-09-09'   ORDER BY  CNSCXC DESC,IDSEDE ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


SELECT  FTR.N_FACTURA,CASE WHEN COALESCE(FTR.MARCA,0)=1 THEN 'X-'+FTR.EQUIMARCA ELSE '' END MARCA,TER.NIT AS IDTERCERO, TER.RAZONSOCIAL,CONVERT(VARCHAR,FTR.F_FACTURA,103)F_FACTURA,FTR.PROCEDENCIA,FTR.IDPLAN,PLN.DESCPLAN   FROM [dbo].[FTR] INNER JOIN  TER ON FTR.IDTERCERO=TER.IDTERCERO INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN WHERE ( FTR.N_FACTURA LIKE '%%%%') AND  FTR.ESTADO='P' AND COALESCE(CLASEANULACION,'')<>'NC' AND COALESCE(VR_TOTAL,0)>0 AND COALESCE(CONTABILIZADA,0)<>0                   AND NOT EXISTS(SELECT * FROM FXCD WHERE FCXCD.N_FACTURA=FTR.N_FACTURA)                   AND COALESCE(INDCARTERA,0)=1 AND IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPCARTERA') AND CONVERT(DATE, F_fACTURA) >=  '2023-08-01' AND CONVERT(DATE, F_fACTURA) <=  '2023-09-09' AND FTR.IDTERCERO  =  '900226715'  ORDER BY  FTR.CNSFCT  OFFSET (1-1)*7 ROWS  FETCH NEXT 7 ROWS ONLY 


FCXC