IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPK_NHC_INGRESAR_HCAT' AND TYPE = 'P')
   DROP PROCEDURE SPK_NHC_INGRESAR_HCAT
GO
CREATE PROCEDURE DBO.SPK_NHC_INGRESAR_HCAT
@CONSECUTIVO    VARCHAR(13), 
@ITEMRED        INT,
@SIN_SIGNOS     BIT=0
WITH ENCRYPTION
AS
DECLARE @CLASEPLANTILLA VARCHAR(8)
DECLARE @CLASEHC        VARCHAR(1)
DECLARE @NOADMISION     VARCHAR(16)
DECLARE @IDAREA         VARCHAR(20)
DECLARE @IDMEDICO       VARCHAR(12), @DESCSERVICIONUTP VARCHAR(80), @NOCOPIA SMALLINT
DECLARE @CONSECUTIVOANT VARCHAR(13), @IDSERVICIONUTP   VARCHAR(20), @QNUTP  DECIMAL(18,6)
DECLARE @ITEMREDANT     INT,         @ITEMREDANTCON_OM INT,         @ORDEN  INT 
DECLARE @TIPOPM         VARCHAR(20), @TIPOSV           VARCHAR(20), @CLASE VARCHAR(2)
DECLARE @TIPOHTX        VARCHAR(20), @SECOPIA          SMALLINT,    @FECHA DATETIME
DECLARE @OMCODMEDTERAPIA    VARCHAR(20)
DECLARE @OMCODLIQUIDOSPARE  VARCHAR(20)
DECLARE @OMCODHEMODERIVADOS VARCHAR(20), @IDAFILIADO VARCHAR(20)
DECLARE @OMCODNUTRICIONP    VARCHAR(20), @CLASEMPL VARCHAR(20), @AMBITO VARCHAR(20)
DECLARE @NUEVO BIT=1
BEGIN
   print '@CONSECUTIVO='+@CONSECUTIVO
   SELECT @CLASEPLANTILLA=CLASEPLANTILLA, @NOADMISION=NOADMISION, @IDAREA=IDAREA, 
      @IDMEDICO=IDMEDICO, @CLASE=CLASE, @FECHA=FECHA, @IDAFILIADO=IDAFILIADO
   FROM   HCA 
   WHERE  CONSECUTIVO = @CONSECUTIVO
   
   SELECT @NUEVO=IIF(COUNT(1)=0,1,0) FROM HCATD WHERE CONSECUTIVO=@CONSECUTIVO

   SET @OMCODMEDTERAPIA=DBO.FNK_VALORVARIABLE('OMCODMEDTERAPIA')
   SET @OMCODLIQUIDOSPARE=DBO.FNK_VALORVARIABLE('OMCODLIQUIDOSPARE')
   SET @OMCODHEMODERIVADOS=DBO.FNK_VALORVARIABLE('OMCODHEMODERIVADOS')
   SET @OMCODNUTRICIONP=DBO.FNK_VALORVARIABLE('OMCODNUTRICIONP')

   SELECT @NOCOPIA = COALESCE(NOCOPIAOM,0) FROM MPL WHERE CLASEPLANTILLA = @CLASEPLANTILLA

   --SELECT DISTINCT PROCEDENCIA FROM HCA
   SELECT TOP 1 @ITEMREDANT=ITEMRED 
   FROM HCA 
   WHERE NOADMISION=@NOADMISION AND CONSECUTIVO<>@CONSECUTIVO AND PROCEDENCIA='QX' 
      AND CLASE=@CLASE AND FECHA<@FECHA
	  AND CLASEPLANTILLA NOT IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('HCPLANTILLAEPI','HCPLANTILLAEPI_UCI'))
   ORDER BY FECHA DESC

   IF COALESCE(@ITEMREDANT,0) = 0
   BEGIN
      SELECT @ITEMREDANT = 0, @CONSECUTIVOANT = ''
   END
   ELSE
   BEGIN
      SELECT TOP 1 @ITEMREDANT=ITEMRED
      FROM   HCA INNER JOIN MPL ON HCA.CLASEPLANTILLA = MPL.CLASEPLANTILLA
      WHERE  NOADMISION = @NOADMISION 
      AND    CONSECUTIVO <> @CONSECUTIVO 
      AND    PROCEDENCIA = 'QX' 
      AND    HCA.CLASE = @CLASE
      AND    HCA.FECHA < @FECHA
      AND    COALESCE(MPL.NOCOPIAOM,0)=0
	  AND	 HCA.CLASEPLANTILLA NOT IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('HCPLANTILLAEPI','HCPLANTILLAEPI_UCI'))
      ORDER BY FECHA DESC

      IF COALESCE(@ITEMREDANT,0) = 0
      BEGIN
         SELECT @ITEMREDANT = 0, @CONSECUTIVOANT = ''
      END
      ELSE
      BEGIN
         SELECT @CONSECUTIVOANT = CONSECUTIVO 
         FROM   HCA 
         WHERE  NOADMISION = @NOADMISION 
         AND    PROCEDENCIA = 'QX' 
         AND    ITEMRED = @ITEMREDANT 
         AND    CLASE = @CLASE
		 AND	CLASEPLANTILLA NOT IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('HCPLANTILLAEPI','HCPLANTILLAEPI_UCI'))
      END
   END
   PRINT '@CONSECUTIVOANT='+@CONSECUTIVOANT+ '//@ITEMREDANT= '+CONVERT(VARCHAR(5),@ITEMREDANT)
   IF @CLASEPLANTILLA <> DBO.FNK_VALORVARIABLE('HCPLANTILLARED')
   BEGIN
      SELECT @CLASEHC = 'O'
   END
   ELSE
   BEGIN
      SELECT @CLASEHC = 'E'
   END

   SELECT @TIPOSV=TIPOSV, @AMBITO=AMBITO, @CLASEMPL=CLASE FROM MPL WHERE CLASEPLANTILLA = @CLASEPLANTILLA
   PRINT  '@CLASE='+@CLASE

   
   /*SIGNOS VITALES*/
   IF @TIPOSV='000' AND @SIN_SIGNOS=0
   BEGIN
      EXEC SPK_INSERT_HCASV @CONSECUTIVO

      --Copia signos desde triage
      EXEC SPK_TRAESV_TRIAGE @CONSECUTIVO
   END

   IF @NOCOPIA=0 AND @AMBITO='CE' AND @CLASEMPL='HC' AND EXISTS (SELECT 1 FROM TGEN WHERE TABLA='HC' AND CAMPO='COPIARDATOANT' AND CODIGO=@CLASEPLANTILLA AND ISNULL(OPCIONESLIBRES,0)=1)
   BEGIN
        DECLARE @CNSANT VARCHAR(20)=NULL

        SELECT TOP 1 @CNSANT = CONSECUTIVO
        FROM   HCA 
        WHERE  IDAFILIADO=@IDAFILIADO AND CLASEPLANTILLA=@CLASEPLANTILLA AND CONSECUTIVO<>@CONSECUTIVO
        AND    FECHA < @FECHA AND IDMEDICO=@IDMEDICO
        ORDER BY FECHA DESC

        INSERT INTO HCATD (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, CLASE, ENCARGOS, NOPRESTACION, APLICADA, CONSECUTIVONE, NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION,  TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR, CANTIDADNOCC, CNSHJNOPOS, DESCRIPTIVA, DESTINO, OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, CANTIDADORI, FRECUENCIAORI,  DURACIONORI, DOSISUNICA, FECHAINI, IDSERVICIOMEZCLA, QMEZCLA, QIMPSERVICIO, QIMPMEZCLA, DURACIONIMP, RAZONNEC, ORDEN, HORAAM, QAM, HORAPM, QPM, HORASMAX, FECHAMAX, GOTEO,  GENHORARIO, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, FFINALDOSIS, TIPOSOLBS, BSCAPACIDAD, IDBODEGA, CODPAQUETE, VERIFICA, LATERALIDAD, TIPOFRECUENCIA, DOSIF )
        SELECT @CONSECUTIVO, @ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, CLASE, ENCARGOS, NOPRESTACION, 0, CONSECUTIVONE, NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION,  TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR, CANTIDADNOCC, CNSHJNOPOS, DESCRIPTIVA, DESTINO, OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, CANTIDADORI, FRECUENCIAORI,  DURACIONORI, DOSISUNICA, CONVERT(SMALLDATETIME,GETDATE()), IDSERVICIOMEZCLA, QMEZCLA, QIMPSERVICIO, QIMPMEZCLA, DURACIONIMP, RAZONNEC, ORDEN, HORAAM, QAM, HORAPM, QPM, HORASMAX, FECHAMAX, GOTEO,  GENHORARIO, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, FFINALDOSIS, TIPOSOLBS, BSCAPACIDAD, IDBODEGA, CODPAQUETE, VERIFICA, LATERALIDAD, TIPOFRECUENCIA, DOSIF 
        FROM HCATD WHERE CONSECUTIVO=@CNSANT
   END

   IF @NOCOPIA = 0
   BEGIN
      IF @CLASE = 'HC'
      BEGIN
         PRINT 'ENTRAR A CREAR HCATD'
         INSERT INTO HCATD (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, 
                         VIA, OBSERVACION, CLASE, ENCARGOS, TIPO, FRECUENCIA, DURACION, 
                         FECHAGA, CANTIDADNOCC, CANTIDADINV, COPIADO, PRIMER,
                         CANTIDADORI, FRECUENCIAORI, DURACIONORI, IDSERVICIOMEZCLA, QMEZCLA, RAZONNEC, ORDEN,  
                         HORAAM, QAM, HORAPM, QPM, GOTEO, VERIFICA) 
         SELECT @CONSECUTIVO, @ITEMRED, HCATD.CODOM, 
                HCATD.IDSERVICIO, HCATD.CANTIDAD, HCATD.IDTIPOCONC, HCATD.VIA, 
                HCATD.OBSERVACION, 'C', 0, HCATD.TIPO, HCATD.FRECUENCIA, HCATD.DURACION, 
                HCATD.FECHAGA, HCATD.CANTIDADNOCC, HCATD.CANTIDADINV, 1, 
                CASE ROW_NUMBER() OVER(PARTITION BY HCATD.CODOM ORDER BY HCATD.CODOM) WHEN 1 THEN 1 ELSE 0 END,
                HCATD.CANTIDAD, HCATD.FRECUENCIA, HCATD.DURACION, HCATD.IDSERVICIOMEZCLA, HCATD.QMEZCLA, HCATD.RAZONNEC, HCATD.ORDEN,  
                HORAAM, QAM, HORAPM, QPM, HCATD.GOTEO, (CASE ISNULL(HCATD.AVISADOENF,0) WHEN 2 THEN 2 ELSE 0 END)
         FROM   HCATD INNER JOIN SER    ON HCATD.IDSERVICIO  = SER.IDSERVICIO 
                      INNER JOIN HCCOM  ON HCATD.CODOM = HCCOM.CODOM
                      INNER JOIN HCCOMD ON HCCOM.CODOM = HCCOMD.CODOM
                                       AND SER.PREFIJO = HCCOMD.PREFIJO
         WHERE  HCATD.CONSECUTIVO = @CONSECUTIVOANT
         AND    HCCOMD.SECOPIA    = 1 
         AND    HCATD.CLASE      <> 'S'  -- Y QUE NO HALLAN SIDO SUSPENDIDOS
         AND    1=IIF(@NUEVO=1,1,IIF(HCCOM.TIPO='OM',1,0))
         AND    COALESCE(HCATD.DOSISUNICA,0) = 0
         AND    HCATD.CODOM NOT IN (@OMCODNUTRICIONP,@OMCODLIQUIDOSPARE)
         AND    NOT EXISTS (SELECT 1 FROM HCATD A WHERE A.CONSECUTIVO=@CONSECUTIVO AND A.ITEMRED=@ITEMRED AND A.CODOM=HCATD.CODOM AND A.IDSERVICIO=HCATD.IDSERVICIO)

         --LIQUIDOS
         INSERT INTO HCATD (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, 
                         VIA, OBSERVACION, CLASE, ENCARGOS, TIPO, FRECUENCIA, DURACION, 
                         FECHAGA, CANTIDADNOCC, CANTIDADINV, COPIADO, PRIMER,
                         CANTIDADORI, FRECUENCIAORI, DURACIONORI, IDSERVICIOMEZCLA, QMEZCLA, 
                         RAZONNEC, ORDEN, VERIFICA) 
         SELECT @CONSECUTIVO, @ITEMRED, HCATD.CODOM, 
                HCATD.IDSERVICIO, HCATD.CANTIDAD, HCATD.IDTIPOCONC, HCATD.VIA, 
                HCATD.OBSERVACION, 'C', 0, HCATD.TIPO, HCATD.FRECUENCIA, HCATD.DURACION, 
                HCATD.FECHAGA, HCATD.CANTIDADNOCC, HCATD.CANTIDADINV, 1, 
                CASE ROW_NUMBER() OVER(PARTITION BY HCATD.CODOM ORDER BY HCATD.CODOM) WHEN 1 THEN 1 ELSE 0 END,
                HCATD.CANTIDAD, HCATD.FRECUENCIA, HCATD.DURACION, HCATD.IDSERVICIOMEZCLA, HCATD.QMEZCLA, 
                HCATD.RAZONNEC, HCATD.ORDEN, (CASE ISNULL(HCATD.AVISADOENF,0) WHEN 2 THEN 2 ELSE 0 END)
         FROM   HCATD INNER JOIN SER    ON HCATD.IDSERVICIO  = SER.IDSERVICIO 
                      INNER JOIN PRE    ON SER.PREFIJO = PRE.PREFIJO
                      INNER JOIN HCCOM  ON HCATD.CODOM = HCCOM.CODOM
                      INNER JOIN HCCOMD ON HCCOM.CODOM = HCCOMD.CODOM
                                       AND SER.IDSERVICIO = HCCOMD.IDSERVICIO
         WHERE  HCATD.CONSECUTIVO = @CONSECUTIVOANT
         AND    HCCOMD.SECOPIA    = 1 
         AND    HCATD.CLASE      <> 'S'  -- Y QUE NO HALLAN SIDO SUSPENDIDOS
         AND    COALESCE(HCATD.DOSISUNICA,0) = 0
         AND    HCATD.CODOM = @OMCODLIQUIDOSPARE
         AND    NOT EXISTS (SELECT 1 FROM HCATD A WHERE A.CONSECUTIVO=@CONSECUTIVO AND A.ITEMRED=@ITEMRED AND A.CODOM=HCATD.CODOM AND A.IDSERVICIO=HCATD.IDSERVICIO)

         ---NUTRICION PARENTERAL
         INSERT INTO HCATD (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, 
                         VIA, OBSERVACION, CLASE, ENCARGOS, TIPO, FRECUENCIA, DURACION, 
                         FECHAGA, CANTIDADNOCC, CANTIDADINV, COPIADO, PRIMER,
                         CANTIDADORI, FRECUENCIAORI, DURACIONORI, IDSERVICIOMEZCLA, QMEZCLA, 
                         RAZONNEC, ORDEN, GOTEO, VERIFICA) 
         SELECT @CONSECUTIVO, @ITEMRED, HCATD.CODOM, 
                HCATD.IDSERVICIO, HCATD.CANTIDAD, HCATD.IDTIPOCONC, HCATD.VIA, 
                HCATD.OBSERVACION, 'C', 0, HCATD.TIPO, HCATD.FRECUENCIA, HCATD.DURACION, 
                HCATD.FECHAGA, HCATD.CANTIDADNOCC, HCATD.CANTIDADINV, 1, 
                CASE ROW_NUMBER() OVER(PARTITION BY HCATD.CODOM ORDER BY HCATD.CODOM) WHEN 1 THEN 1 ELSE 0 END,
                HCATD.CANTIDAD, HCATD.FRECUENCIA, HCATD.DURACION, HCATD.IDSERVICIOMEZCLA, HCATD.QMEZCLA, HCATD.RAZONNEC, 
                HCATD.ORDEN, HCATD.GOTEO, (CASE ISNULL(HCATD.AVISADOENF,0) WHEN 2 THEN 2 ELSE 0 END)
         FROM   HCATD INNER JOIN SER    ON HCATD.IDSERVICIO  = SER.IDSERVICIO 
                      INNER JOIN PRE    ON SER.PREFIJO = PRE.PREFIJO
                      INNER JOIN HCCOMD ON HCATD.CODOM = HCCOMD.CODOM AND HCATD.IDSERVICIO = HCCOMD.IDSERVICIO
         WHERE  HCATD.CODOM = @OMCODNUTRICIONP
         AND    PRE.PREFIJO = DBO.FNK_VALORVARIABLE('PREFIJONUTRICIONP_OM')
         AND    HCATD.CLASE      <> 'S' --JFRANCO 18/06/2015
         AND    HCATD.CONSECUTIVO = @CONSECUTIVOANT
         AND    HCCOMD.SECOPIA    = 1 
         AND    NOT EXISTS (SELECT 1 FROM HCATD A WHERE A.CONSECUTIVO=@CONSECUTIVO AND A.ITEMRED=@ITEMRED AND A.CODOM=HCATD.CODOM AND A.IDSERVICIO=HCATD.IDSERVICIO)

         --HCATDH DETALLE
         INSERT INTO HCATDH (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, HORA, CANTIDAD, IDSERVICIOD)
         SELECT @CONSECUTIVO, @ITEMRED, CODOM, IDSERVICIO, HORA, CANTIDAD, IDSERVICIOD
         FROM   HCATDH
         WHERE  HCATDH.CONSECUTIVO = @CONSECUTIVOANT 
         --AND    HCATDH.CODOM = @OMCODNUTRICIONP
         AND    EXISTS (SELECT 1 FROM HCATD WHERE HCATD.CONSECUTIVO=@CONSECUTIVO AND HCATD.CODOM=HCATDH.CODOM AND HCATD.IDSERVICIO=HCATDH.IDSERVICIO        
                        AND NOT EXISTS (SELECT 1 FROM HCATDH A WHERE A.CONSECUTIVO=@CONSECUTIVO AND A.ITEMRED=@ITEMRED AND A.CODOM=HCATD.CODOM AND A.IDSERVICIO=HCATD.IDSERVICIO)
                        )

         --MEDICAMENTOS DE TERAPIA
         INSERT INTO HCATD (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, 
                         VIA, OBSERVACION, CLASE, ENCARGOS, TIPO, FRECUENCIA, DURACION, 
                         FECHAGA, CANTIDADNOCC, CANTIDADINV, COPIADO, PRIMER,
                         CANTIDADORI, FRECUENCIAORI, DURACIONORI, IDSERVICIOMEZCLA, QMEZCLA, 
                         RAZONNEC, ORDEN, VERIFICA) 
         SELECT @CONSECUTIVO, @ITEMRED, HCATD.CODOM, 
                HCATD.IDSERVICIO, HCATD.CANTIDAD, HCATD.IDTIPOCONC, HCATD.VIA, 
                HCATD.OBSERVACION, 'C', 0, HCATD.TIPO, HCATD.FRECUENCIA, HCATD.DURACION, 
                HCATD.FECHAGA, HCATD.CANTIDADNOCC, HCATD.CANTIDADINV, 1, 
                CASE WHEN (SELECT COUNT(*) FROM HCATD WHERE CONSECUTIVO = CONSECUTIVO) > 0 
                          THEN 0
                     ELSE 
                          CASE ROW_NUMBER() OVER(PARTITION BY HCATD.CODOM ORDER BY HCATD.CODOM) WHEN 1 THEN 1 ELSE 0 END
                END,
                HCATD.CANTIDAD, HCATD.FRECUENCIA, HCATD.DURACION, HCATD.IDSERVICIOMEZCLA, HCATD.QMEZCLA, 
                HCATD.RAZONNEC, HCATD.ORDEN, (CASE ISNULL(HCATD.AVISADOENF,0) WHEN 2 THEN 2 ELSE 0 END)
         FROM   HCATD INNER JOIN SER    ON HCATD.IDSERVICIO  = SER.IDSERVICIO 
         WHERE  HCATD.CONSECUTIVO = @CONSECUTIVOANT
         AND    HCATD.CLASE      <> 'S'  -- Y QUE NO HALLAN SIDO SUSPENDIDOS
         AND    COALESCE(HCATD.DOSISUNICA,0) = 0
         AND    HCATD.CODOM = @OMCODMEDTERAPIA
         AND    COALESCE(SER.TERAPIA,0) = 1
         AND    NOT EXISTS (SELECT 1 FROM HCATD A WHERE A.CONSECUTIVO=@CONSECUTIVO AND A.ITEMRED=@ITEMRED AND A.CODOM=HCATD.CODOM AND A.IDSERVICIO=HCATD.IDSERVICIO)

      END
   END

   /*HACER PLAN DE MANEJO AUTOMATICO*/
   SELECT @TIPOPM = TIPOPM FROM HCA WHERE CONSECUTIVO = @CONSECUTIVO
   IF @TIPOPM = 'Automatico'
   BEGIN   
      DECLARE @CODOM    VARCHAR(10), @IDSERVICIO     VARCHAR(20), @TIPOMED INT, @TIPOOM         VARCHAR(20)
      DECLARE PM_C CURSOR FOR
      SELECT IDSERVICIO, CODOM FROM HCATD WHERE CONSECUTIVO = @CONSECUTIVO
      OPEN PM_C
      FETCH NEXT FROM PM_C
      INTO @IDSERVICIO, @CODOM
      WHILE @@FETCH_STATUS = 0    
      BEGIN
         SELECT @TIPOOM = HCCOM.TIPO, @SECOPIA=ISNULL(HCCOMD.SECOPIA,0)
         FROM   HCATD 
            INNER JOIN SER ON SER.IDSERVICIO=HCATD.IDSERVICIO
            INNER JOIN HCCOM ON HCATD.CODOM = HCCOM.CODOM
            LEFT  JOIN HCCOMD  ON HCCOMD.CODOM=HCCOM.CODOM 
               AND COALESCE(HCCOMD.PREFIJO,'')=(CASE WHEN HCCOM.CODOM IN (@OMCODLIQUIDOSPARE,@OMCODHEMODERIVADOS,@OMCODNUTRICIONP) THEN COALESCE(HCCOMD.PREFIJO,'') ELSE SER.PREFIJO END)
               AND COALESCE(HCCOMD.IDSERVICIO,'')=(CASE WHEN HCCOM.CODOM NOT IN (@OMCODLIQUIDOSPARE,@OMCODHEMODERIVADOS,@OMCODNUTRICIONP) THEN COALESCE(HCCOMD.IDSERVICIO,'') ELSE HCATD.IDSERVICIO END)
         WHERE  HCATD.CONSECUTIVO = @CONSECUTIVO
         AND    HCATD.CODOM       = @CODOM
         AND    HCATD.IDSERVICIO  = @IDSERVICIO
         AND    NOT EXISTS (SELECT 1 FROM HCAPM A WHERE A.CONSECUTIVO=@CONSECUTIVO AND A.CLAMED=HCATD.CODOM AND A.IDSERVICIO=HCATD.IDSERVICIO)

         SET @TIPOMED = 0
         IF @CODOM IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('OMCODMEDICAMENTOS','OMCODMEDICAMENTOSCT','OMCODNUTRICIONP',
            'OMCODMEDICAMENTOSNP','OMCODLIQUIDOSPARE','OMCODMEDTERAPIA'))
            SET @TIPOMED = 1
         IF @CODOM = (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('OMCODMEZCLA'))
            SET @TIPOMED = 2

         SELECT @TIPOHTX=DBO.FNK_VALORVARIABLE('TIPOHTX')
         SELECT @ORDEN=COALESCE(MAX(ORDEN),0) FROM HCAPM WHERE CONSECUTIVO = @CONSECUTIVO
         SET @ORDEN=ISNULL(@ORDEN,0)+1

         IF @CODOM <> @OMCODNUTRICIONP
         BEGIN 
			IF EXISTS (SELECT 1 FROM HCATDH WHERE HCATDH.CONSECUTIVO=@CONSECUTIVO AND HCATDH.CODOM=@CODOM AND HCATDH.IDSERVICIO=@IDSERVICIO) AND DBO.FNK_VALORVARIABLE('HCATDH_CANTDIF')='SI'
			BEGIN
				DECLARE @TABLE_HCATDH TABLE (ITEM INT IDENTITY(1,1), HORA VARCHAR(3), CANTIDAD DECIMAL(14,2), IDTIPOCONC VARCHAR(20))
				DECLARE @FIX INT, @FIX_TO INT, @OBS_HCATDH VARCHAR(1024)='', @HORA VARCHAR(3), @CANTIDAD DECIMAL(14,2), @IDTIPOCONC VARCHAR(20)

				INSERT INTO @TABLE_HCATDH(HORA, CANTIDAD, IDTIPOCONC)
				SELECT A.HORA, A.CANTIDAD, LTRIM(RTRIM(COALESCE(IDTIPOCONC,'')))
				FROM HCATDH A INNER JOIN HCATD B ON A.CONSECUTIVO=B.CONSECUTIVO AND A.CODOM=B.CODOM AND A.IDSERVICIO=B.IDSERVICIO
				WHERE A.CONSECUTIVO=@CONSECUTIVO AND A.CODOM=@CODOM AND A.IDSERVICIO=@IDSERVICIO
			
				SELECT @FIX=1, @FIX_TO=COUNT(1) FROM @TABLE_HCATDH
			
				WHILE @FIX<=@FIX_TO
				BEGIN
					SELECT @CANTIDAD=CANTIDAD, @HORA=HORA, @IDTIPOCONC=IDTIPOCONC FROM @TABLE_HCATDH WHERE ITEM=@FIX
					SELECT @OBS_HCATDH+=IIF(@FIX=@FIX_TO,' y ','') + DBO.FNK_DAS(@CANTIDAD)+' '+ @IDTIPOCONC + ' a las ' + DBO.FNK_DAS(@HORA)+IIF(@FIX=@FIX_TO,' horas',' horas, ')
					SELECT @FIX+=1
				END
			END
            INSERT INTO HCAPM (CONSECUTIVO, ORDEN, CLASE, IDSERVICIO, CLAMED, SECOPIA, OBSERVACION)
            SELECT @CONSECUTIVO, @ORDEN, @TIPOOM, @IDSERVICIO, @CODOM, 0,
               CASE WHEN @TIPOHTX='HORIZONTAL' THEN LEFT(--Nombre del servicio
                  LEFT(LTRIM(RTRIM(SER.DESCSERVICIO)),100)+'.  '
                  +
                  --Iniciar, Cambiar, Suspender, Continuar
                  CASE 
                     WHEN @TIPOOM='Manual' THEN ''
                     WHEN @SECOPIA=0 AND ISNULL(HCATD.CANTIDAD,0)>1 THEN 'Realizar '+DBO.FNK_DAS(HCATD.CANTIDAD)
                     WHEN @SECOPIA=0 THEN ''
                     WHEN @TIPOMED IN (0,1) THEN 
                     CASE ISNULL(HCATD.RAZONNEC,0) 
                        WHEN 1 THEN 'Por razón necesaria '
                        WHEN 3 THEN 'Administrar ' --Por días
                           +CASE WHEN ISNULL(HCATD.LUNES,0)    =1 THEN 'Lunes '     ELSE '' END
                           +CASE WHEN ISNULL(HCATD.MARTES,0)   =1 THEN 'Martes '    ELSE '' END
                           +CASE WHEN ISNULL(HCATD.MIERCOLES,0)=1 THEN 'Miercoles ' ELSE '' END
                           +CASE WHEN ISNULL(HCATD.JUEVES,0)   =1 THEN 'Jueves '    ELSE '' END
                           +CASE WHEN ISNULL(HCATD.VIERNES,0)  =1 THEN 'Viernes '   ELSE '' END
                           +CASE WHEN ISNULL(HCATD.SABADO,0)   =1 THEN 'Sabado '    ELSE '' END
                           +CASE WHEN ISNULL(HCATD.DOMINGO,0)  =1 THEN 'Domingo '   ELSE '' END + '  '
                        ELSE
                           CASE ISNULL(HCATD.DOSISUNICA,0) WHEN 1 THEN 'Dosis única de ' ELSE 'Continuar ' END
                     END
                     WHEN @TIPOMED=2 THEN 
                        CASE WHEN COALESCE(HCATD.QIMPSERVICIO,0)>0 THEN 'Impregnación de '+ DBO.FNK_DAS(HCATD.QIMPSERVICIO) + ' ' + RTRIM(LTRIM(HCATD.IDTIPOCONC)) ELSE 'Continuar ' END
                     ELSE CASE WHEN @TIPOOM = 'Manual' THEN '' ELSE 'Realizar: '+ DBO.FNK_DAS(HCATD.CANTIDAD)+ ' ' END 
                  END 
                  + --Bolo o Impregnación
                  CASE @TIPOMED 
                     WHEN 1 THEN 
                        CASE WHEN ISNULL(HCATD.CANTIDADBOLO,0)>0 THEN
                           CASE 
                              WHEN (@CODOM=@OMCODMEDTERAPIA AND SER.TERAPIA=1) OR @CODOM<>@OMCODMEDTERAPIA THEN 'con '+DBO.FNK_DAS(HCATD.CANTIDADBOLO)+' '+RTRIM(LTRIM(HCATD.IDTIPOCONC)) --Medicamentos
                              WHEN  @CODOM=@OMCODMEDTERAPIA THEN 'ciclo de '+DBO.FNK_DAS(HCATD.CANTIDADBOLO)+' en 1 hora' --Procedimientos
                              ELSE '' END
                           ELSE ''
                        END
                     WHEN 2 THEN CASE WHEN COALESCE(HCATD.QIMPSERVICIO,0) > 0 THEN ' en '+ DBO.FNK_DAS(HCATD.QIMPMEZCLA) + ' cc de ' +  COALESCE(MEZ.DESCSERVICIO,'') + ' durante ' + DBO.FNK_DAS(HCATD.DURACIONIMP)+' minutos' ELSE '' END
                     ELSE ''
                  END
                  + --Continuación
                  CASE @TIPOMED WHEN 1 THEN
                     CASE WHEN COALESCE(HCATD.CANTIDADBOLO,0) > 0  AND  HCATD.CANTIDAD > 0 AND COALESCE(HCATD.DOSISUNICA, 0) = 0 THEN 
                              ' y continuar con '+DBO.FNK_DAS(HCATD.CANTIDAD) + ' ' +RTRIM(LTRIM(HCATD.IDTIPOCONC)) + 
                              + ' cada ' + DBO.FNK_DAS(HCATD.FRECUENCIA) + ' horas'
                          WHEN COALESCE(HCATD.CANTIDADBOLO,0) > 0  AND  HCATD.CANTIDAD > 0 AND COALESCE(HCATD.DOSISUNICA, 0) = 1 THEN
                              ' dosis única: '+DBO.FNK_DAS(HCATD.CANTIDAD) + ' ' +RTRIM(LTRIM(HCATD.IDTIPOCONC))
                          WHEN COALESCE(HCATD.RAZONNEC,0) = 1 THEN +DBO.FNK_DAS(HCATD.CANTIDAD)
                          WHEN COALESCE(HCATD.RAZONNEC,0) = 2 AND DBO.FNK_VALORVARIABLE('HCATDH_CANTDIF')<>'SI' THEN +DBO.FNK_DAS(HCATD.QAM)+' '+ 
                              RTRIM(LTRIM(HCATD.IDTIPOCONC)) + ' a las ' + DBO.FNK_DAS(HCATD.HORAAM) + ' horas y ' + 
                              DBO.FNK_DAS(HCATD.QPM)+' '+RTRIM(LTRIM(HCATD.IDTIPOCONC)) + ' a las ' +
                              DBO.FNK_DAS(HCATD.HORAPM) + ' horas' 
					      WHEN COALESCE(HCATD.RAZONNEC,0) = 2 AND DBO.FNK_VALORVARIABLE('HCATDH_CANTDIF')='SI' THEN + @OBS_HCATDH
                          ELSE
                              CASE WHEN HCATD.CANTIDAD > 0 AND COALESCE(HCATD.DOSISUNICA, 0) = 1 THEN DBO.FNK_DAS(HCATD.CANTIDAD) + ' ' +RTRIM(LTRIM(HCATD.IDTIPOCONC)) 
                                   ELSE DBO.FNK_DAS(HCATD.CANTIDAD) + ' ' +RTRIM(LTRIM(HCATD.IDTIPOCONC))+ CASE WHEN COALESCE(HCATD.RAZONNEC,0) <> 3 THEN ' cada ' + DBO.FNK_DAS(HCATD.FRECUENCIA) + ' horas' ELSE '' END
                              END
                     END
                     WHEN 2 THEN 
                          ' y continuar con infusión de '+DBO.FNK_DAS(HCATD.CANTIDAD) + '+'+ 
                          DBO.FNK_DAS(HCATD.QMEZCLA) + ' cc de ' + LEFT(COALESCE(MEZ.DESCSERVICIO,''),50) +' pasando a ' +  
                          DBO.FNK_DAS(HCATD.GOTEO)+' cc hora' 
                               
                      ELSE ''            
                  END 
                  + --Via de aplicación
                  (CASE WHEN HCATD.VIA IN ('No Aplica','') THEN '' ELSE ' vía '+COALESCE(TGEN.DESCRIPCION,HCATD.VIA,'') END)
                  + --Diluyente
                  (CASE @TIPOMED WHEN 1 THEN (CASE WHEN (SER.MEZCLA > 0  AND COALESCE(HCATD.IDSERVICIOMEZCLA,'') NOT IN ('','ENF')) THEN ' diluido en ' + DBO.FNK_DAS(HCATD.QMEZCLA) + ' cc de ' + LEFT(MEZ.DESCSERVICIO,50) ELSE '' END) ELSE ''END)
                  + --Observación
                  (CASE WHEN LEN(HCATD.OBSERVACION)>0 THEN ' // OBSERVACIÓN: '+LTRIM(RTRIM(HCATD.OBSERVACION)) ELSE '' END)
                  ,1024) --HCA.TIPOOM<>Automático
                  ELSE LTRIM(RTRIM(SER.DESCSERVICIO))+'  Posología: '+DBO.FNK_DAS(HCATD.CANTIDAD) + ' ' + RTRIM(LTRIM(HCATD.IDTIPOCONC))+ ' cada ' + DBO.FNK_DAS(HCATD.FRECUENCIA) + ' horas' + CASE WHEN LEN(RTRIM(HCATD.OBSERVACION)) > 0 THEN ' // OBSERVACIÓN: '+RTRIM(HCATD.OBSERVACION) ELSE '' END
               END
            FROM HCATD 
               INNER JOIN SER     ON HCATD.IDSERVICIO=SER.IDSERVICIO
               INNER JOIN HCCOM   ON HCCOM.CODOM=HCATD.CODOM
               LEFT  JOIN SER MEZ ON HCATD.IDSERVICIOMEZCLA=MEZ.IDSERVICIO
               LEFT  JOIN TGEN    ON TGEN.TABLA='General' AND TGEN.CAMPO='VIAAPLICACION' AND TGEN.CODIGO=HCATD.VIA
            WHERE HCATD.CONSECUTIVO=@CONSECUTIVO AND HCATD.CODOM=@CODOM AND HCATD.IDSERVICIO=@IDSERVICIO 
				AND    NOT EXISTS (SELECT 1 FROM HCAPM A WHERE A.CONSECUTIVO=@CONSECUTIVO AND A.CLAMED=HCATD.CODOM AND A.IDSERVICIO=HCATD.IDSERVICIO)
         END
         ELSE
         BEGIN
            INSERT INTO HCAPM (CONSECUTIVO, ORDEN, CLASE, OBSERVACION, IDSERVICIO, CLAMED, SECOPIA)
            SELECT @CONSECUTIVO, (SELECT COALESCE(MAX(ORDEN),0) + 1 FROM HCAPM WHERE CONSECUTIVO = @CONSECUTIVO), @TIPOOM,
                   LEFT('Continuar: NUTRICION PARENTERAL pasar a ' + CONVERT(VARCHAR(14),COALESCE(CONVERT(DECIMAL(14,2),HCATD.GOTEO),0))+' cc hora'+CHAR(13)+CHAR(10) --JFRANCO 14/05/2015'
                   ,1024),
                   @IDSERVICIO, @CODOM, 0
            FROM   HCATD INNER JOIN SER     ON HCATD.IDSERVICIO = SER.IDSERVICIO
                         LEFT  JOIN SER MEZ ON HCATD.IDSERVICIOMEZCLA = MEZ.IDSERVICIO
                         LEFT  JOIN HCCOM   ON HCATD.CODOM = HCCOM.CODOM
            WHERE  HCATD.CONSECUTIVO = @CONSECUTIVO
            AND    HCATD.CODOM       = @CODOM
            AND    HCATD.IDSERVICIO  = @IDSERVICIO    
			AND    NOT EXISTS (SELECT 1 FROM HCAPM A WHERE A.CONSECUTIVO=@CONSECUTIVO AND A.CLAMED=HCATD.CODOM AND A.IDSERVICIO=HCATD.IDSERVICIO)

            --DESDE AQUI INGRESO LOS HCATDH  
            SELECT @ORDEN = ORDEN FROM HCAPM WHERE CONSECUTIVO = @CONSECUTIVO AND CLAMED = @CODOM 
            DECLARE NUTP_C CURSOR FOR
            SELECT  HCATDH.IDSERVICIOD, HCATDH.CANTIDAD, LEFT(SER.DESCSERVICIO,80)
            FROM    HCATDH INNER JOIN SER ON HCATDH.IDSERVICIOD = SER.IDSERVICIO
            WHERE   HCATDH.CONSECUTIVO = @CONSECUTIVO
            AND     HCATDH.CODOM = @CODOM
			
			OPEN NUTP_C
            FETCH NEXT FROM NUTP_C
            INTO @IDSERVICIONUTP, @QNUTP, @DESCSERVICIONUTP
            WHILE @@FETCH_STATUS = 0    
            BEGIN
               UPDATE HCAPM SET OBSERVACION = OBSERVACION +  '     -' +@IDSERVICIONUTP + ': ' + @DESCSERVICIONUTP + ' Cant: ' +CONVERT(VARCHAR(14),COALESCE(CONVERT(DECIMAL(14,2),@QNUTP),0))+ CHAR(13)+ CHAR(10)
               WHERE  HCAPM.CONSECUTIVO = @CONSECUTIVO
               AND    HCAPM.ORDEN       = @ORDEN
               FETCH NEXT FROM NUTP_C
               INTO @IDSERVICIONUTP, @QNUTP, @DESCSERVICIONUTP
            END
            CLOSE NUTP_C
            DEALLOCATE NUTP_C
         END
         FETCH NEXT FROM PM_C
         INTO @IDSERVICIO, @CODOM
      END
      CLOSE PM_C
      DEALLOCATE PM_C
   END
END


