<i class="fa-solid fa-list"></i>

select  * from USPROH WHERE  IDPROCEDIMIENTO='MENUQ_CONFIGURACION' AND DESCRIPCION LIKE '%AGRUPA%'

SELECT  * FROM USPROH WHERE RUTA='conf.plantillashc'

Movilidad
SELECT DBO.FNK_COLUMNAS_TABLAS('USPROH')

IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_CONFIGURACION' AND IDCONTROL='CONTRATOSESPE')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_CONFIGURACION', 'CONTRATOSESPE', 'M', 'Contratos Especiales', 1, 'conf.contraEspe', 'fa-solid fa-list', 6, 0, 0, 80, 'Copogos fijos, Movilidad', NULL, NULL
END

<i class="fa-solid fa-magnifying-glass-chart"></i>
pptcnt

SELECT PPTCNT.ID,PPT.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,PPT.IDPLAN,PLN.DESCPLAN,PPTCNT.PREFIJO,PRE.NOM_PREFIJO,
PPTCNT.COPAFIJO,PPTCNT.COPAVAR,PPTCNT.PRCOPAFIJO,PPTCNT.PRCOPAVAR,PPTCNT.MOVILIDAD,PPTCNT.IDMOVILIDAD
FROM PPTCNT INNER JOIN PPT ON PPTCNT.IDTERCERO=PPT.IDTERCERO AND PPTCNT.IDPLAN=PPT.IDPLAN
            INNER JOIN PLN ON PPT.IDPLAN=PLN.IDPLAN
            INNER JOIN TER ON PPT.IDTERCERO=TER.IDTERCERO
            INNER JOIN PRE ON PPTCNT.PREFIJO=PRE.PREFIJO

