UPDATE FTR SET IDFORMATO='03GSV'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='KMONTES' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"VB5"},"USUARIO":"KMONTES"}'

UPDATE FTR SET OBSERVACION='KENINITA LA MAS BONITA' WHERE N_FACTURA='VB5'

SELECT ROW_NUMBER() OVER(ORDER  BY AUTD.IDAUT,AUTD.NO_ITEM  ASC)ID, DBO.FNK_FECHA_GRINGA(AUT.FECHA)FECHA, AUT.PREFIJO,PRE.NOM_PREFIJO,AUTD.NO_ITEM,AUTD.IDAUT,AUTD.IDSERVICIO, COALESCE(AUTD.NOCOBRABLE,0) NOCOBRABLE,                         SER.DESCSERVICIO,AUTD.CANTIDAD,AUTD.VALOR,(AUTD.VALOR*AUTD.CANTIDAD)SUBTOTAL,AUTD.VALORCOPAGO,AUTD.VALOREXCEDENTE,AUTD.N_FACTURA,                         COALESCE(PROTOCOLO,0) PROTOCOLO,CASE WHEN COALESCE(AUTD.ESDELAB,0)=1 THEN CASE WHEN COALESCE(AUTD.ENLAB,0)=2 THEN 1 ELSE 2 END ELSE                         CASE WHEN COALESCE(APOYODG_AMBITO,'')<> '' AND COALESCE(AUTD.ENLAB,0)=2                         THEN 1 WHEN COALESCE(APOYODG_AMBITO,'')<> '' AND COALESCE(AUTD.ENLAB,0)<> 2 THEN 2 ELSE 0 END END RESUL,AUT.IDFARMACIA                         IIF(AUT.CONSECUTIVOCIT <>'010000059696',0,1) AS OTRAATENCION  FROM [dbo].[AUTD] INNER JOIN  AUT ON AUTD.IDAUT=AUT.IDAUT INNER JOIN SER ON AUTD.IDSERVICIO=SER.IDSERVICIO  INNER JOIN PRE ON AUT.PREFIJO=PRE.PREFIJO WHERE (AUT.PREFIJO LIKE '%%%%') AND (AUT.CONSECUTIVOCIT='010000059696' OR AUT.IDAFILIADO='01M0001447') AND COALESCE(AUTD.FACTURADA,0)=0   ORDER BY AUTD.IDAUT,AUTD.NO_ITEM  ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 