use KSANIPERU

DELETE AFU WHERE NOT EXISTS(SELECT * FROM CPPAF WHERE AFU.IDAREA=CPPAF.IDAREA)

UPDATE CPPAF SET IDAREA=NULL

SELECT  * FROM CIT WHERE IDAFILIADO IS NOT NULL

SELECT  * FROM SER WHERE IDSERVICIO='INT001'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='STORRES' ORDER BY ITEM DESC

UPDATE CPPAF SET IDAREA='6000' WHERE IDPLAN='PAQ001' AND IDAREA='4110'


SELECT  * FROM FTRD WHERE N_FACTURA='B001-00003030'

UPDATE FTRD SET CUENTA_FIMPDV='4010101001' WHERE N_FACTURA='B001-00003030'


INSERT INTO PAR(COMPANIA)
SELECT '01'

SELECT VALORTOTAL,IDTERCEROCA,FECHA, IDPLAN,* FROM CIT WHERE CONSECUTIVO='010000000144'

UPDATE CIT SET VALORTOTAL=80,FACTURABLE=1,FACTURADA=0,N_FACTURA=NULL WHERE CONSECUTIVO='010000000144'

UPDATE FTR SET IDFORMATO='PE03'

SELECT * FROM PAR

SELECT  * FROM FCJ WHERE NROCOMPROBANTE='0111600000000186'

UPDATE PCJ SET CTA_BCO='0000001',BANCO='005' ,SUCURSAL='01',CUENTA='1210200101' WHERE CNSFACJ='00000214' AND CODCAJA='C002'

UPDATE PAR SET CTA_CAJ_REC_NOLEG='1',MCUEORDEN_CXC='No',MCUEORDEN_CXP='No',MCUEORDEN_EGRESOS='No',MCUEORDEN_GLOSAS='No',MCUEORDEN_INGRESOS='No'



EXEC SPQ_JSON '{"MODELO":"CIT_COL","METODO":"VALIDA_PREV","PARAMETROS":{"IDAFILIADO":"0100000108","CONSECUTIVO":"010000000146","IDMEDICO":"00097289"},"USUARIO":"STORRES"}'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='STORRES' ORDER BY ITEM DESC


SELECT ID = ROW_NUMBER() OVER (
		ORDER BY IDAFILIADO
			,NOADMISION
			,NOPRESTACION
			,NOITEM
		)
	,IDAFILIADO
	,DOCIDAFILIADO
	,PACIENTE
	,PROCEDENCIA
	,NOADMISION
	,IDSERVICIO
	,DESCSERVICIO
	,FECHA
	,CONVERT(DECIMAL(14, 2), VALORTOTAL) VALORTOTAL
	,CONVERT(DECIMAL(14, 2), VALORCOPAGO) VALORCOPAGO
	,CONVERT(DECIMAL(14, 2), VALOREXCEDENTE) VALOREXCEDENTE
	,MARCAFAC
	,USUMARCA
	,NOPRESTACION
	,NOITEM
	,CNSFACT
	,COALESCE(NOAUTORIZACION, '') NOAUTORIZACION
	,IDTERCEROCA AS IDTERCERO
	,RAZONSOCIAL
	,IDPLAN
	,NOMPLAN AS DESCPLAN
	,CANTIDAD
	,TIPOCOPAGO
	,IDSEDE
	,CODUNG
	,N_FACTURA
FROM [dbo].[VWK_CARGOS_HADMAUTCIT]
WHERE (
		PROCEDENCIA LIKE '%%%%'
		OR PACIENTE LIKE '%%%%'
		OR DOCIDAFILIADO LIKE '%%%%'
		OR NOADMISION LIKE '%%%%'
		)
	AND COALESCE(FACTURADA, 0) = 0
	AND CONVERT(DATE, FECHA) >= '2024-10-07'
	AND CONVERT(DATE, FECHA) <= '2024-10-07'
	AND IDTERCERO = '20523470761'
	AND IDPLAN = 'PAQ001'
	AND IDSEDE = '01'
	AND PROCEDENCIA = 'CIT'
	AND COALESCE(NOCOBRABLE, 0) = 0
ORDER BY IDAFILIADO
	,NOADMISION
	,NOPRESTACION
	,NOITEM OFFSET(1 - 1) * 10 ROWS

FETCH NEXT 10 ROWS ONLY

