

SELECT CERRADA, * FROM HADM WHERE NOADMISION='0500001835'

UPDATE HADM SET CERRADA=0 WHERE NOADMISION='0500001835'

-- consecutivo cit-- CIT ->
-- generado= 3 definido , aut.facturada=0  pendiente por factura -> AUTD. GENERDADO=1, AUTD.NFACTURA ->

--GENERADO -> 0 PENDIENTES

N_FACTURA, FTR VALORSERVCIOS, VALORCOPAGO

