USE KSUMUY

INSERT INTO USUSU
SELECT * FROM KUNIPSSAM.DBO.USUSU WHERE USUARIO='JJIMENEZ'


SELECT TOP 10  * FROM MED
SELECT  TOP 10 * FROM UBEQ

UPDATE USUSU SET IDMEDICO='1010126595', SYS_COMPUTERNAME='ADMISION' WHERE USUARIO='JJIMENEZ'
UPDATE USUSU SET FECHACAMBIO=DBO.FNK_GETDATE(),FECHAVENCE=DBO.FNK_GETDATE()+180 WHERE USUARIO='JJIMENEZ'


SELECT  * FROM RRIPS_AM WHERE ENVIO='100019'

SELECT SER.DESCSERVICIO,IDPLAN,  * FROM AUTD INNER JOIN SER ON AUTD.IDSERVICIO=SER.IDSERVICIO WHERE IDAUT='0100851993'

SELECT  * FROM AUT WHERE NOAUT='0100831877'