DECLARE @EXISTE INT
DECLARE @NUMDOC     VARCHAR(20)
DECLARE @CODCARGO   VARCHAR(20)
DECLARE @NIVEL      VARCHAR(10)
DECLARE @GRADO      VARCHAR(10)
DECLARE @FECHAING   DATETIME
DECLARE @FFINAL     DATETIME
DECLARE @FINICIAL   DATETIME
DECLARE @NPERIODOS  SMALLINT
DECLARE @ANOS       SMALLINT
DECLARE @MAX        SMALLINT
DECLARE @FECHARET   DATETIME
DECLARE @FECHACORTE DATETIME
DECLARE @F_ACTUALIZA DATETIME
DECLARE @ITEMV INT
DECLARE @DIASG DECIMAL(7,4)
DECLARE @DIASP DECIMAL(7,4)
DECLARE @DIASC DECIMAL(7,2)

   DECLARE PG_VACANOMI CURSOR FOR  
   SELECT NUMDOC,CODCARGO,NIVEL,GRADO,FECHAINGRESO,FECHARETIRO 
   FROM NEMP
   WHERE ESTADO='Activo'
  
	OPEN PG_VACANOMI    
	FETCH NEXT FROM PG_VACANOMI    
	INTO @NUMDOC,@CODCARGO,@NIVEL,@GRADO,@FECHAING,@FECHARET
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
      IF EXISTS(SELECT  * FROM NEMPV WHERE NUMDOC=@NUMDOC)
      BEGIN 
         
         DECLARE NEMPVD_CURSOR CURSOR FOR 
         SELECT ITEM,DIASG,DIASP,F_INICAL  FROM NEMPV 
         WHERE NUMDOC=@NUMDOC
         ORDER BY   ITEM
         OPEN NEMPVD_CURSOR    
         FETCH NEXT FROM NEMPVD_CURSOR    
         INTO @ITEMV,@DIASG,@DIASP,@FINICIAL
         WHILE @@FETCH_STATUS = 0    
         BEGIN 
            PRINT '@NUMDOC ='+@NUMDOC
            PRINT 'FECHAINGRESO='+CONVERT(VARCHAR,@FECHAING,103)
            IF DAY(@FECHAING)<>DAY(@FINICIAL)
            BEGIN
               UPDATE NEMPV SET F_INICAL=DATEADD(DAY,DAY(@FECHAING)-DAY(@FINICIAL),F_INICAL) WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV
            END
            FETCH NEXT FROM NEMPVD_CURSOR    
            INTO @ITEMV,@DIASG,@DIASP,@FINICIAL
         END
         CLOSE NEMPVD_CURSOR
         DEALLOCATE NEMPVD_CURSOR

      END
	FETCH NEXT FROM PG_VACANOMI    
	INTO @NUMDOC,@CODCARGO,@NIVEL,@GRADO,@FECHAING,@FECHARET
	END
	CLOSE PG_VACANOMI
	DEALLOCATE PG_VACANOMI  
