IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_LIBERAR_FACT' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_LIBERAR_FACT
END
GO
CREATE PROCEDURE DBO.SPK_LIBERAR_FACT
@N_FACTURA        VARCHAR(16),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@RAZONCAMBIO      VARCHAR(255),
@SYS_COMPUTERNAME VARCHAR(254),
@USUARIO2         VARCHAR(12)
WITH ENCRYPTION
AS
DECLARE @PROCEDENCIA    VARCHAR(10)
DECLARE @TIPOFAC        VARCHAR(1)
DECLARE @CONTABILIZADA  SMALLINT
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @NVOCONSEC      VARCHAR(20)
DECLARE @NOADMISION     VARCHAR(16)
DECLARE @IDTERCERO      VARCHAR(20)
DECLARE @IDPLAN         VARCHAR(6)
DECLARE @TIPOADM        VARCHAR(2)
DECLARE @ESTACONTAB     SMALLINT
DECLARE @AUX            INT 
DECLARE @ESTADO         VARCHAR(1)
declare @ANOFACTURA     VARCHAR(4)
DECLARE @MESFACTURA     VARCHAR(2)
DECLARE @ANOACTUAL      VARCHAR(4)
DECLARE @MESACTUAL      VARCHAR(2)
DECLARE @ESTADOPERFTR   INT
DECLARE @ESTADOPERACT   INT
DECLARE @NVOCNSFNOT     VARCHAR(20)
DECLARE @CERRADOFTR     SMALLINT
DECLARE @CERRADOINV     SMALLINT  
DECLARE @CNSFMAS        VARCHAR(20)
DECLARE @CNSCXC         VARCHAR(20)
DECLARE @NOREFERENCIA   VARCHAR(20)
DECLARE @FACTE          SMALLINT
DECLARE @FCOPA          SMALLINT
DECLARE @CNSFTR         VARCHAR(20)
DECLARE @RECO           VARCHAR(20)
DECLARE @ESTADOPPTO     VARCHAR(10)
DECLARE @CNSPPTO        VARCHAR(10)
DECLARE @ESCOPAGOPE       BIT
BEGIN
   SELECT @NOADMISION     = NOREFERENCIA,
          @IDTERCERO      = IDTERCERO,
          @IDPLAN         = IDPLAN,
          @PROCEDENCIA    = PROCEDENCIA,
          @TIPOFAC        = TIPOFAC,
          @FACTE          = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN CASE WHEN COALESCE(FACTEP,'')<>'OK' THEN 0 ELSE 1 END ELSE FACTE END,
          @CONTABILIZADA  = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN CASE WHEN COALESCE(FACTEP,'')<>'OK' THEN 0 ELSE 1 END 
                           ELSE CASE WHEN COALESCE(FTR.FACTE,0)<>0  THEN 1 ELSE COALESCE(CONTABILIZADA,0) END END, 
          @NROCOMPROBANTE = COALESCE(NROCOMPROBANTE,''),
          @ANOFACTURA     = CONVERT(VARCHAR, YEAR(FTR.F_FACTURA)),
          @MESFACTURA     = CONVERT(VARCHAR, MONTH(FTR.F_FACTURA)),
          @CNSFMAS        = CNSFMAS,
		    @NOREFERENCIA   = NOREFERENCIA,
          @FCOPA          = CASE WHEN TIPOFIN='N' THEN 1 ELSE 0 END,
          @ESCOPAGOPE     = CASE WHEN COALESCE(CP_CONVENIO,'')='Boleta' THEN 1 ELSE 0 END
   FROM   FTR 
   WHERE  N_FACTURA   = @N_FACTURA

   IF @PROCEDENCIA NOT IN ('SALUD','CE','CI') -- OR @TIPOFAC <> 'I'
   BEGIN
      RETURN
   END

   SELECT @ANOACTUAL  = CONVERT(VARCHAR, YEAR(GETDATE())), @MESACTUAL = CONVERT(VARCHAR, MONTH(GETDATE()))
   IF @ANOACTUAL > @ANOFACTURA
   BEGIN
      SELECT @AUX = CERRADO FROM PRI WHERE ANO = @ANOFACTURA AND MES = 12
      IF @AUX = 1
      BEGIN
         IF DBO.FNK_VALORVARIABLE('FTR_ANULAEJERCANT') <> 'SI' 
         BEGIN
            RAISERROR('FACTURA DE UN EJERCICIO ANTERIOR DEBE CONFIGURARSE DE ACUERDO AL ART?CULO 106 DEL DECRETO 2649',16,1)
            RETURN 
         END
      END
   END
   SELECT @ESTADOPERFTR = COALESCE(CERRADO,0),@CERRADOINV=CERRADO_INV,
          @CERRADOFTR   = CERRADO_FAC 
   FROM   PRI 
   WHERE  ANO = @ANOFACTURA AND MES = @MESFACTURA 

   SELECT @ESTADOPERACT = COALESCE(CERRADO,0) FROM PRI WHERE ANO = @ANOACTUAL AND MES = @MESACTUAL

   ---SE AGREGA CONDICIONAL EN CASO DE SE ACTIVE LA ANULACION DE FACTURAS DE AÑOS ANTERIORES

   IF @ESTADOPERFTR = 1 
   BEGIN
      RAISERROR('EL PERIODO DE LA FACTURA ESTA CERRADO.',16,1)
      RETURN
   END
   ELSE
   BEGIN
      IF @ESTADOPERACT = 1 AND  DBO.FNK_VALORVARIABLE('FTR_ANULAEJERCANT') <> 'SI' 
      BEGIN
         RAISERROR(' PERIODO ACTUAL ESTAN CERRADOS.',16,1)
         RETURN
      END
   END
   
   SELECT @ESTACONTAB = @CONTABILIZADA
   PRINT 'PROCEDENCIA= '+@PROCEDENCIA
   PRINT 'TIPOFACT= '+@TIPOFAC
   

   IF @ESTACONTAB = 1
   BEGIN
      PRINT 'ANULO EL COMPROBANTE'
      UPDATE MCP SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
	  --ESTE STORE PROCEDURE ESTA DE MAS YA QUE SE ANULA 
      --EXEC SPK_REVISAR_COMPROBANTE '01',@NROCOMPROBANTE
   END
   ELSE
   BEGIN
      IF @ESTACONTAB = 2
      BEGIN
         DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
         INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                           REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                           RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
         SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                  REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,1 ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                  RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
         FROM   MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE

         DELETE MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
      END         
   END 
   UPDATE FTR SET ESTADO = 'L', RAZONANULACION = @RAZONCAMBIO, PIVA = 0, VIVA = 0, VR_TOTAL = 0, VALORSERVICIOS = 0   WHERE  N_FACTURA = @N_FACTURA
   IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
   BEGIN
      IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
      BEGIN
         SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
         PRINT 'Retiro los recuados si Existe'
         UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
         DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
         UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
         PRINT 'Retiro los Reconocimientos...'
         UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
         DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
         UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
         UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
      END
   END 


   IF @PROCEDENCIA='SALUD'
   BEGIN    
      SELECT @TIPOADM=TIPOADM FROM HADM WHERE NOADMISION = @NOADMISION 
      UPDATE HADMF SET ESTADO = 'L' WHERE NOADMISION = @NOADMISION AND N_FACTURA = @N_FACTURA
      
      IF COALESCE(@FCOPA,0)<>1
         UPDATE HPRED SET FACTURADA=0, N_FACTURA=NULL WHERE N_FACTURA = @N_FACTURA
      ELSE
            UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
      IF EXISTS(SELECT * FROM HADMAUT WHERE N_FACTURA=@N_FACTURA  AND NOADMISION=@NOADMISION)
      BEGIN
         UPDATE HADMAUT SET N_FACTURA= NULL WHERE N_FACTURA=@N_FACTURA AND NOADMISION=@NOADMISION
      END
      IF @TIPOADM = DBO.FNK_VALORVARIABLE('IDTARIFASOAT')
      BEGIN
         DELETE HADM_S WHERE NOADMISION = @NOADMISION
         DELETE HADM_T WHERE NOADMISION = @NOADMISION
         UPDATE HADM SET FACTURADA = 0 WHERE NOADMISION = @NOADMISION
      END         
   END 
   ELSE
   BEGIN
	   IF LEFT(@NOREFERENCIA,2)='AT'
	   BEGIN
		   UPDATE AUT SET FACTURADA=0, N_fACTURA=NULL WHERE N_FACTURA=@N_FACTURA
		   UPDATE CIT SET FACTURADA=0, N_fACTURA=NULL WHERE N_FACTURA=@N_FACTURA
		   DELETE HACTRANFD WHERE N_FACTURA=@N_FACTURA
		   DELETE HACTRANF  WHERE N_FACTURA=@N_FACTURA
	   END
	   ELSE
	   BEGIN
          IF @TIPOFAC='M'
          BEGIN			
             IF @NOREFERENCIA='VARIOS' OR @NOREFERENCIA = 'CEUNIFPE' OR @NOADMISION='CEUNIFICADO' OR @NOREFERENCIA='UNIWEB'
             BEGIN
                IF  @NOREFERENCIA='UNIWEB'
                BEGIN
                   UPDATE AUTD SET FACTURADA=0, N_fACTURA=NULL, N_FACTURAORI=@N_FACTURA
                   FROM FTRD 
                      INNER JOIN AUT  ON AUT.IDAUT=FTRD.NOPRESTACION
                      INNER JOIN AUTD ON AUTD.IDAUT=AUT.IDAUT AND AUTD.NO_ITEM=FTRD.NOITEM AND AUTD.N_FACTURA=FTRD.N_FACTURA
                   WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CE'

                   UPDATE AUT SET FACTURADA=0, MARCAFAC=0, N_fACTURA=NULL 
                   FROM FTRD 
                      INNER JOIN AUT  ON AUT.IDAUT=FTRD.NOPRESTACION
                   WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CE'

                   UPDATE CIT SET FACTURADA=0, MARCAFAC=0, N_FACTURA=NULL 
                   FROM FTRD INNER JOIN CIT ON CIT.CONSECUTIVO=FTRD.NOPRESTACION AND CIT.N_FACTURA=FTRD.N_FACTURA
                   WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CI'
                END
                ELSE
                BEGIN
                   UPDATE AUTD SET FACTURADA=0, N_fACTURA=NULL, N_FACTURAORI=@N_FACTURA
                   FROM FTRD 
                      INNER JOIN AUT  ON AUT.NOAUT=FTRD.NOPRESTACION
                      INNER JOIN AUTD ON AUTD.IDAUT=AUT.IDAUT AND AUTD.NO_ITEM=FTRD.NOITEM AND AUTD.N_FACTURA=FTRD.N_FACTURA
                   WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CE'

                   UPDATE AUT SET FACTURADA=0, MARCAFAC=0, N_fACTURA=NULL 
                   FROM FTRD 
                      INNER JOIN AUT  ON AUT.NOAUT=FTRD.NOPRESTACION
                   WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CE'

                   UPDATE CIT SET FACTURADA=0, MARCAFAC=0, N_FACTURA=NULL 
                   FROM FTRD INNER JOIN CIT ON CIT.CONSECUTIVO=FTRD.NOPRESTACION AND CIT.N_FACTURA=FTRD.N_FACTURA
                   WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CI'
                END
             END
			    ELSE 
			    BEGIN 
			       UPDATE AUTD SET FACTURADA=0, N_fACTURA=NULL, N_FACTURAORI=@N_FACTURA
                FROM FTRD 
                   INNER JOIN AUT  ON AUT.NOAUT=FTRD.NOPRESTACION
                   INNER JOIN AUTD ON AUTD.IDAUT=AUT.IDAUT AND AUTD.NO_ITEM=FTRD.NOITEM AND AUTD.N_FACTURA=FTRD.N_FACTURA
                WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CE'

                UPDATE AUT SET FACTURADA=0, MARCAFAC=0, N_fACTURA=NULL 
                FROM FTRD 
                   INNER JOIN AUT  ON AUT.NOAUT=FTRD.NOPRESTACION
                WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CE'

                UPDATE CIT SET FACTURADA=0, MARCAFAC=0, N_FACTURA=NULL 
                FROM FTRD INNER JOIN CIT ON CIT.CONSECUTIVO=FTRD.NOPRESTACION AND CIT.N_FACTURA=FTRD.N_FACTURA
                WHERE FTRD.N_FACTURA=@N_FACTURA AND FTRD.PROCEDENCIA='CI'

			   END 
            SELECT  @CNSFMAS=COALESCE(CNSFMAS,'') FROM FTR WHERE N_FACTURA=@N_FACTURA
            IF @CNSFMAS<>''
            BEGIN 
               IF @PROCEDENCIA  ='CI'
               BEGIN 
                  UPDATE CIT SET FACTURADA=0, MARCAFAC=0, N_FACTURA=NULL 
                  FROM FMASD INNER JOIN CIT ON FMASD.NOADMISION=CIT.CONSECUTIVO 
                  WHERE CNSFMAS=@CNSFMAS 
               END
               UPDATE FMAS SET FACTURADA=0 WHERE CNSFMAS=@CNSFMAS
            END
          END
          ELSE
          BEGIN
		       IF @PROCEDENCIA='CE' OR @NOADMISION='CEUNIFICADO'
		       BEGIN
				   IF @NOADMISION <> 'CEUNIFICADO'
				   BEGIN
					   UPDATE AUTD SET FACTURADA=0,N_fACTURA=NULL,N_FACTURAORI=@N_FACTURA 
					    WHERE  EXISTS(SELECT * FROM AUT WHERE AUT.IDAUT=AUTD.IDAUT AND  NOAUT=@NOADMISION) AND N_FACTURA=@N_FACTURA
					   UPDATE AUT SET FACTURADA=0,N_fACTURA=NULL  WHERE NOAUT=@NOADMISION
				   END
				   ELSE
				   BEGIN
					   UPDATE AUT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL WHERE  AUT.N_FACTURA = @N_FACTURA AND FACTURADA = 1
					   UPDATE AUTD SET FACTURADA = 0, N_FACTURA = NULL WHERE  AUTD.N_FACTURA = @N_FACTURA AND FACTURADA = 1
				   END
			   END

			   IF @PROCEDENCIA='CI' OR @NOADMISION='CEUNIFICADO'
			   BEGIN
				   IF @NOADMISION <> 'CEUNIFICADO'
				   BEGIN
                  IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND COALESCE(@ESCOPAGOPE,0)=1
                  BEGIN
                     UPDATE CIT SET NfACTURA=NULL WHERE   NFACTURA  in (select  N_FACTURA from cit where CONSECUTIVO=@NOREFERENCIA)
                  END
                  ELSE
                  BEGIN
					      UPDATE CIT SET FACTURADA=0, N_fACTURA=NULL WHERE   N_FACTURA  in (select  @N_FACTURA from cit where CONSECUTIVO=@NOREFERENCIA)
                  END
				   END
				   ELSE
				   BEGIN
                  IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND COALESCE(@ESCOPAGOPE,0)=1
                  BEGIN
                     UPDATE CIT SET NFACTURA = NULL WHERE  NFACTURA = @N_FACTURA 
                  END
                  ELSE
                  BEGIN
					      UPDATE CIT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL WHERE  N_FACTURA = @N_FACTURA AND FACTURADA = 1
                  END
				   END
			   END
         END
	   END
   END 
   /* ARREGLO DE HONORARIOS*/

   DELETE FXPD 
   FROM   FXPD INNER JOIN FXP ON FXPD.N_PRESUP  = FXP.N_PRESUP
                              AND FXPD.IDTERCERO = FXP.IDTERCERO
   WHERE  FXP.NOREFERENCIA = @NOADMISION 
   AND    FXP.PROCEDENCIA  = @PROCEDENCIA
      
   DELETE FXP WHERE NOREFERENCIA = @NOADMISION AND PROCEDENCIA = @PROCEDENCIA

   IF (SELECT ESTADO FROM FTR WHERE N_FACTURA=@N_FACTURA)='L'
   BEGIN
      DELETE FTRD WHERE N_FACTURA=@N_FACTURA
   END  
   IF DBO.FNK_VALORVARIABLE('PRESUP_CXC_ACTIVADO')= 'SI'  
   BEGIN 
      IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
      BEGIN
         IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
         BEGIN
            SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
            PRINT 'Retiro los recuados si Existe'
            UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
            DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
            UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
            PRINT 'Retiro los Reconocimientos...'
            UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
            DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
            UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
            UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
         END
      END 
   END
END




