IF EXISTS (SELECT name FROM sysobjects   WHERE NAME = 'SPK_RECONSTRUIR_RESOL' AND type = 'P')
BEGIN
   DROP PROCEDURE SPK_RECONSTRUIR_RESOL
END

GO
CREATE PROC DBO.SPK_RECONSTRUIR_RESOL
	@CODRES VARCHAR(20),
	@ANO INT,
	@MES INT,
	@IDAFILIADO VARCHAR(20) = NULL
WITH ENCRYPTION
AS 
DECLARE @CURSOR TABLE (ID INT, TIPO VARCHAR(10), CNS VARCHAR(20))
DECLARE	@FIX INT, @FIX_TO INT, @TIPO VARCHAR(10), @CNS VARCHAR(20)
BEGIN
	INSERT INTO @CURSOR (ID, TIPO, CNS)
	SELECT ROW_NUMBER() OVER (ORDER BY IDAFILIADO, ITEM, FECHA, CNS ASC) AS ID, TIPO, CNS 
   FROM (
		SELECT 1 AS ITEM, 'HCA' AS TIPO, FECHA, CONSECUTIVO AS CNS, IDAFILIADO 
        FROM HCA 
		WHERE COALESCE(ANULADA,0)=0 AND YEAR(FECHA)=@ANO AND MONTH(FECHA)=@MES
			AND EXISTS (SELECT 1 FROM MPL WHERE HCA.CLASEPLANTILLA=MPL.CLASEPLANTILLA AND COALESCE(M4505,0)=1)
			AND IDAFILIADO=CASE COALESCE(@IDAFILIADO,'') WHEN '' THEN IDAFILIADO ELSE @IDAFILIADO END
		UNION ALL
		SELECT 2 AS ITEM, 'MDX' AS TIPO, FECHA, CONVERT(VARCHAR(20),CONSECUTIVO) AS CNS, V.IDAFILIADO
		FROM DBO.VWK_HCA_DX V INNER JOIN MDX ON V.DX=MDX.IDDX
		WHERE ISNULL(MDX.REPORTA,0)=1 AND YEAR(FECHA)=@ANO AND MONTH(FECHA)=@MES
		AND IDAFILIADO=CASE COALESCE(@IDAFILIADO,'') WHEN '' THEN IDAFILIADO ELSE @IDAFILIADO END
		UNION ALL
		SELECT 3 AS ITEM, 'TGSV' AS TIPO, FECHA, CONVERT(VARCHAR(20),HCASV.CONSECUTIVO) AS CNS, HCA.IDAFILIADO
      FROM HCASV INNER JOIN HCA ON HCA.CONSECUTIVO=HCASV.CONSECUTIVO
		INNER JOIN MPL ON MPL.CLASEPLANTILLA=HCA.CLASEPLANTILLA
		WHERE YEAR(FECHA)=@ANO AND MONTH(FECHA)=@MES AND M4505=1
		   AND EXISTS (SELECT 1 FROM TGSV WHERE HCASV.CODIGOSV=TGSV.CODIGOSV AND HCASV.GRUPO=TGSV.GRUPO AND COALESCE(REPORTA,0)=1)
		   AND IDAFILIADO=CASE COALESCE(@IDAFILIADO,'') WHEN '' THEN IDAFILIADO ELSE @IDAFILIADO END
		UNION ALL
		SELECT 4 AS ITEM, 'LSER' AS TIPO, LING.FECHA, NORDEN AS CNS, LING.IDAFILIADO 
        FROM LORD INNER JOIN LING ON LORD.NOINGRESO=LING.NOINGRESO 
		WHERE AMBITOTR IN ('LX','CT') AND YEAR(LING.FECHA)=@ANO AND MONTH(LING.FECHA)=@MES
			AND LORD.ESTADO='R' AND COALESCE(LORD.REALIZADO,0)=1
			AND EXISTS (SELECT 1 FROM SER WHERE LORD.IDSERVICIO=SER.IDSERVICIO AND COALESCE(SER.REPORTA,0)=1)
			AND IDAFILIADO=CASE COALESCE(@IDAFILIADO,'') WHEN '' THEN IDAFILIADO ELSE @IDAFILIADO END
		UNION ALL
		SELECT 5 AS ITEM, 'VAC' AS TIPO, FECHAAPLI AS FECHA, CONVERT(VARCHAR(20),VACD.IDVACD) AS CNS, VAC.IDAFILIADO 
        FROM VAC INNER JOIN VACD ON VAC.IDVAC=VACD.IDVAC 
		WHERE VACD.ESTADO IN ('A','C') AND YEAR(VACD.FECHAAPLI)=@ANO AND MONTH(VACD.FECHAAPLI)=@MES
			AND EXISTS (SELECT 1 FROM SER WHERE VACD.IDSERVICIO=SER.IDSERVICIO AND COALESCE(SER.REPORTA,0)=1)
			AND IDAFILIADO=CASE COALESCE(@IDAFILIADO,'') WHEN '' THEN IDAFILIADO ELSE @IDAFILIADO END
		UNION ALL
		SELECT  6 AS ITEM, 'COP' AS TIPO, HCOC.FECHA AS FECHA, CONVERT(VARCHAR(20),HCOC.CONSECUTIVO) AS CNS, HCO.IDAFILIADO 
		FROM HCOC inner join HCO on  HCO.CONSECUTIVO=HCOC.CONSECUTIVO
				INNER JOIN AFI ON AFI.IDAFILIADO=HCO.IDAFILIADO
		WHERE  YEAR(HCOC.FECHA)=@ANO AND MONTH(HCOC.FECHA)=@MES and PLACA=0
				AND HCO.IDAFILIADO=CASE COALESCE(@IDAFILIADO,'') WHEN '' THEN HCO.IDAFILIADO ELSE @IDAFILIADO END
			)X 
	
	SELECT @FIX=1, @FIX_TO=COUNT(1) FROM @CURSOR

	WHILE @FIX <= @FIX_TO
	BEGIN
		SELECT @TIPO=TIPO, @CNS=CNS FROM @CURSOR WHERE ID=@FIX
		IF @TIPO='HCA'
			EXEC SPK_ACTUALIZARESOL_HC @CNS
		IF @TIPO='LSER'
			EXEC SPK_ACTUALIZARESOL_LSER @CNS
		IF @TIPO='VAC'
			EXEC SPK_ACTUALIZARESOL_VACD @CNS
		IF @TIPO='MDX'
			EXEC SPK_ACTUALIZARESOL_MDX @CNS
		IF @TIPO='TGSV'
			EXEC SPK_ACTUALIZARESOL_TGSV @CNS
		IF @TIPO='COP'
			EXEC SPK_ACTUALIZARESOL_COP @CNS, @ANO, @MES
		SET @FIX += 1
	END
END

