use kpcem


SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FNOT_COL","METODO":"FNOT_CRUDFNOTD","PARAMETROS":{"DATOS":{"PROCESO":"Nuevo","CNSFNOT":"01C00000074","CLASE":"C","TIPO":"S","N_FACTURA":"F002-00000015","N_CUOTA":11,"IDSERVICIO":"330409","DESCRIPCION":"RECUENTO SANGUINEO COMPLETO AUTOMATIZADO (HEMOGRAMA)","PREFIJO":"005","IDAREA":"6000","CCOSTO":"0101","CANTIDAD":1,"VR_UNITARIO":"4","VR_TOTAL":4,"OBSERVACION":"SDSD","VIVA":0.6099999999999999,"PIVA":18,"TVR_TOTAL":8.82,"VLR_SALDO":8.82,"CANTORI":1}},"USUARIO":"JJIMENEZ"}'


SELECT  * FROM FNOT WHERE CNSFNOT='01C00000074'

SELECT  * FROM KMCOM 

EXEC SPQ_JSON '{"MODELO":"KMCOM_COL","METODO":"CRUD_KMCOM","PARAMETROS":{"KMCOM":{"IDMODELOCONT":"01","IDTIPOCONT":"VENTAS","DESCRIPCION":"VENTAS DE PRODUCTOS Y SERVICIOS","IDAREA":"4110","CCOSTO":"10010102","TIPO":"Todas","CLASECONT":"P","PROCESO":"Nuevo","NOMCCOSTO":"MENTE PLENA OVIEDO","NOMAREA":"CONSULTA EXTERNA","PREFIJO":"00","NOM_PREFIJO":"LIQUIDACION CIRUGIAS","CUENTADB":"11051001","NOMCUENTADB":"CAJA MENOR/ADMINISTRACION","CUENTACR":"11050507","NOMCUENTACR":"CAJA EFECTIVO URABA","CUENTAIPS":"11051003","NOMCUENTAIPS":"CAJA MENOR URABA","PGP":true,"CUENTAPGP":"11050508","NOMCUENTAPGP":"CAJA LAURELES","CAPITA":true,"CUENTACAPI":"11051003","NOMCUENTACAPI":"CAJA MENOR URABA"}},"USUARIO":"JJIMENEZ"}'

select * from dbo.FNK_CREA_TABLA_DESDEJSON('{"IDMODELOCONT":"01","IDTIPOCONT":"VENTAS","DESCRIPCION":"VENTAS DE PRODUCTOS Y SERVICIOS","IDAREA":"4110","CCOSTO":"10010102","TIPO":"Todas","CLASECONT":"P","PROCESO":"Nuevo","NOMCCOSTO":"MENTE PLENA OVIEDO","NOMAREA":"CONSULTA EXTERNA","PREFIJO":"00","NOM_PREFIJO":"LIQUIDACION CIRUGIAS","CUENTADB":"11051001","NOMCUENTADB":"CAJA MENOR/ADMINISTRACION","CUENTACR":"11050507","NOMCUENTACR":"CAJA EFECTIVO URABA","CUENTAIPS":"11051003","NOMCUENTAIPS":"CAJA MENOR URABA","PGP":true,"CUENTAPGP":"11050508","NOMCUENTAPGP":"CAJA LAURELES","CAPITA":true,"CUENTACAPI":"11051003","NOMCUENTACAPI":"CAJA MENOR URABA"}')