USE KSOLIDARIDAD

UPDATE USUSU SET FECHACAMBIO=DBO.FNK_GETDATE(),FECHAVENCE=DBO.FNK_GETDATE()+180 WHERE USUARIO='JJIMENEZ'

SELECT  * FROM MED
SELECT  * FROM UBEQ

UPDATE USUSU SET IDMEDICO='1065591225', SYS_ComputerName='ADMISIONES' WHERE USUARIO='JJIMENEZ'


SELECT  * FROM NEMPV WHERE NUMDOC='0100004943' AND ITEM=2

UPDATE NEMPV SET F_FINAL=DATEADD(DAY,-1,F_FINAL),F_INICAL=DATEADD(DAY,-1,F_INICAL) WHERE NUMDOC='0100004943' AND ITEM=2
