IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'VWK_VCTOS' AND TYPE='V')
BEGIN
   DROP VIEW VWK_VCTOS
END

GO
CREATE VIEW DBO.VWK_VCTOS 
WITH ENCRYPTION
AS                         
   SELECT VWK.ANO, VWK.MES, VWK.PROCEDENCIA, VWK.IDTERCERO, VWK.PARTICULAR, SUM(VWK.SALDONETO) AS SALDOTOT, SUM(VWK.PORVENCER) AS PORVENCER,
	    SUM(D0_30)    AS SALDO_0_30,    SUM(D31_60)   AS SALDO_31_60,   
	    SUM(D61_90)   AS SALDO_61_90,   SUM(D91_120)  AS SALDO_91_120,  
	    SUM(D121_150) AS SALDO_121_150, SUM(D151_180) AS SALDO_151_180, 
	    SUM(D181_360) AS SALDO_181_360, SUM(D361_MAS) AS SALDO_361_MAS,
	    VWK.IDPLAN,
	    SUM(NORADICADA) AS NORADICADA, RAD,VWK.TIPOTTEC AS TIPOTERCONTABLE,CLASEINFO,
       CASE WHEN VWK.CLASEINFO='SINGLO' AND VWK.RAD='SI' THEN (SELECT SUM(VLRITEM- (COALESCE(VLRLEGALIZADO,0)+COALESCE(VLRAJUSTE,0))) 
        FROM BMOVD WHERE RECAUDO=1 
         AND VLRITEM- (COALESCE(VLRLEGALIZADO,0)+COALESCE(VLRAJUSTE,0))>0
         AND BMOVD.IDTERCERO=VWK.IDTERCERO
         )ELSE 0 END VLR_SINLEGAL
   FROM VWK_CXCDIASVTO  VWK 
   GROUP BY VWK.ANO, VWK.MES, VWK.PROCEDENCIA, VWK.IDTERCERO, VWK.PARTICULAR, VWK.IDPLAN, VWK.RAD,VWK.TIPOTTEC,CLASEINFO


