CREATE OR ALTER PROCEDURE DBO.SPK_GENERAR_XML_DIAN
	@CNSDOC VARCHAR(20), -- Si TIPODOC='FV' entonces el consecutivo es CNSFCT else el consecutivo es CNSFNOT
	@TIPODOC VARCHAR(2)='FV', -- FV: Factura de Venta, NC: Nota de Crédito, ND: Nota de Débito
	@PATH_URL VARCHAR(MAX)=NULL,
	@FACTURACION_POR_SEDE BIT = 0,
	@NOMBRE_XML NVARCHAR(1000) OUTPUT,
	@AMBIENTE INT OUTPUT,
	@TESTSETID VARCHAR(100) OUTPUT

   EXEC DBO.SPK_GENERAR_XML_DIAN 