IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_CM_GENIMOV_SOL' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_CM_GENIMOV_SOL
END
GO
CREATE PROCEDURE DBO.SPK_CM_GENIMOV_SOL
@CNSIZSOL VARCHAR(16),
@SEDE     VARCHAR(5),
@USUARIO  VARCHAR(12),
@PROCESO  VARCHAR(20) = ''
WITH ENCRYPTION
AS
DECLARE @CUANTAS       INT,         @IDINVARTNA    VARCHAR(80), @NVOCONSEC  VARCHAR(20)
DECLARE @IDITAR        VARCHAR(2),  @IDTIPOMOV     VARCHAR(2),  @CCOSTO     VARCHAR(20), @IDAREAH           VARCHAR(20)
DECLARE @IDAREA        VARCHAR(20), @NA            VARCHAR(5),  @ESTRANSITO SMALLINT,    @OK                SMALLINT
DECLARE @IDPROVEEDOR   VARCHAR(20), @IDSOLICITANTE VARCHAR(20), @DATO       VARCHAR(20), @CODUNG            VARCHAR(2)
DECLARE @CODPRG        VARCHAR(2),  @IDBODEGA      VARCHAR(20), @ESTADO     VARCHAR(20), @SYS_COMPUTERNAME  VARCHAR(254)
DECLARE @IDBODEGADEST  VARCHAR(20), @PROCEDENCIA   VARCHAR(10), @SOLICITA   VARCHAR(20), @NOPROGRAMACION    VARCHAR(20)
DECLARE @IDTERCERO     VARCHAR(20), @CNSCXPS VARCHAR(20)      , @CLASE      VARCHAR(20), @IDPLAN             VARCHAR(6)
DECLARE @FACTURABLE    BIT        , @IDTERCEROC   VARCHAR(20)
BEGIN
   SELECT @SYS_COMPUTERNAME = HOST_NAME()
   SELECT @IDINVARTNA = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVARTNA'
   IF @PROCESO = ''
   BEGIN
      SELECT @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDTS'), @PROCEDENCIA = 'CM_SOL'
      SELECT @IDBODEGA  = IDBODEGAATIENDE  FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL
   END
   ELSE
   BEGIN
      IF @PROCESO = 'ENTREGAPROD'
      BEGIN
         SELECT @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDTS'), @PROCEDENCIA = 'CM_PROD'
         SELECT @IDBODEGA  = IDBODEGACM,  @IDBODEGADEST = IDBODEGALOG FROM SED WHERE IDSEDE=@SEDE
      END
      ELSE
      BEGIN
         IF @PROCESO = 'INGRESOAPROD'
         BEGIN 
            SELECT @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDINVMOVINGRESOAPROD'), @PROCEDENCIA = 'PRODUCCION'
            SELECT @IDBODEGA  = IDBODEGACM,  @IDBODEGADEST = ''FROM SED WHERE IDSEDE=@SEDE
         END
	      ELSE
	      BEGIN
            IF @PROCESO = 'ENTREGALOG'
            BEGIN 
               IF (SELECT CLASE FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL)<>'PROD'
               BEGIN 
                  SELECT @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDINVMOV_VENTAS'), @PROCEDENCIA = 'CM_SOL' 
                  IF (SELECT CLASE  FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL)='QXPGCX' 
                  BEGIN
                     SELECT @NOPROGRAMACION=NOADMISION, @CNSCXPS=CNSIZSOLM  FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL
					       IF LEN(@CNSCXPS)<10 --El verdadero CXPS
					       BEGIN
						      SELECT @IDAREA=IDAREA,@IDAREAH=IDAREAH,@CCOSTO=CCOSTO FROM CXPS WHERE NOPROGRAMACION=@NOPROGRAMACION
					       END
					       ELSE
					       BEGIN
						      SELECT @IDAREA=IDAREA,@IDAREAH=IDAREAH,@CCOSTO=CCOSTO FROM QXPCX WHERE CONSECUTIVO=@CNSCXPS
					       END
                  END
                  ELSE
                  BEGIN
                     IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND(SELECT CLASE FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL)='HTX'
                     BEGIN
                        SELECT @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDINVMOV_VENTAS'), @PROCEDENCIA = 'CM_SOL'
                        SELECT @CCOSTO=PLN.CCOSTO
                        FROM IZSOL INNER JOIN PLN ON IZSOL.IDPLAN=PLN.IDPLAN AND IZSOL.CNSIZSOL=@CNSIZSOL

                        SELECT TOP 1 @IDAREA=IDAREA
                        FROM IZSOLD INNER JOIN HTX ON IZSOLD.CNSHBALI=HTX.CNSHTX
                        WHERE IZSOLD.CNSIZSOL=@CNSIZSOL
                     END
                     ELSE
                     BEGIN
                        SELECT @CLASE=CLASE,@IDTERCEROC=IDTERCEROC,@IDPLAN=IDPLAN FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL
                        IF @CLASE='Ventas'
                        BEGIN
                           SELECT @FACTURABLE=1,@IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDINVMOVVENTAFACTURA'), @PROCEDENCIA = 'CM_SOL'
                        END
                        ELSE
                        BEGIN
                           SELECT @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDINVMOV_VENTAS'), @PROCEDENCIA = 'CM_SOL'
                        END
                        SELECT @CCOSTO=HHAB.CCOSTO,@IDAREA=HHAB.IDAREA 
                        FROM HHAB INNER JOIN IZSOL ON HHAB.NOADMISION=IZSOL.NOADMISION
                        WHERE IZSOL.CNSIZSOL=@CNSIZSOL                
                        IF COALESCE(@CCOSTO,'')=''
                        BEGIN
                           SELECT @CCOSTO=HHAB.CCOSTO,@IDAREA=HHAB.IDAREA 
                           FROM HHAB INNER JOIN IZSOL ON HHAB.HABCAMA=IZSOL.SECTOR
                           WHERE IZSOL.CNSIZSOL=@CNSIZSOL                       
                           AND HHAB.CLASE='Sector'
                        END
						      IF (SELECT CLASE FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL)='HPRE' AND COALESCE(@CCOSTO,'')=''
						      BEGIN
							      SELECT @CCOSTO=CCOSTO, @IDAREA=IDAREA FROM HPRE 
							      WHERE NOPRESTACION=(SELECT CNSIZSOLM FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL)
						      END
                     END
                  END
               END 
               ELSE
               BEGIN
                  SELECT @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDTS'), @PROCEDENCIA = 'CM_SOL' 
               END            
               SELECT @IDBODEGA=IDBODEGAATIENDE, @IDBODEGADEST=NULL,@SOLICITA=USUARIOSOL 
               FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL 
            END 
            ELSE
            BEGIN
               IF @PROCESO='Consumo'
               BEGIN
                  SELECT @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDINVMOVCONSUMO'), @PROCEDENCIA = 'Consumo'
                  SELECT @CCOSTO=SECTOR,@IDAREA=DBO.FNK_AREADELCCOSTO(SECTOR),@IDBODEGA=IDBODEGAATIENDE, @IDBODEGADEST=IDBODEGAATIENDE,
                         @SOLICITA=USUARIOSOL,@IDTERCERO=IDTERCEROC
                  FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL 
               END               
            END
	      END
      END
   END
   
   SELECT @ESTRANSITO = GENTRANSITO FROM ITMO WHERE IDTIPOMOV = @IDTIPOMOV 
   SELECT @IDITAR = DBO.FNK_VALORVARIABLE('IDINVIDITARUNICA')

   EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@MOV', @LONGITUD = 8, @NVOCONSEC = @NVOCONSEC OUTPUT
   INSERT INTO IMOV (CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, FECHAMOV, CCOSTO, IDSOLICITA, IDFUNCIONARIO,
                     ESTADO, OBSERVACION, SUBIOCOMPRA, IDAREA, CONTABILIZADA, PROCEDENCIA, USUARIO, PARCIAL, 
                     SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, IDBODEGAEXTERNA,IDTERCERO,IDPLAN,GENFACTURA,FACTURADA)
   SELECT @NVOCONSEC, @IDBODEGA, @IDTIPOMOV, @CNSIZSOL, 
      CASE WHEN DBO.FNK_VALORVARIABLE('FECHAMOVSOL')='SI' THEN (SELECT FECHASOL FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL) ELSE DBO.FNK_FECHA_SIN_MLS(GETDATE()) END, 
      @CCOSTO, @SOLICITA, @USUARIO, '0', '', 0, @IDAREA,0, @PROCEDENCIA, @USUARIO, 0, @SYS_COMPUTERNAME, 0, @IDITAR, 0, @IDBODEGADEST,CASE COALESCE(@FACTURABLE,0) WHEN 0 THEN @IDTERCERO ELSE @IDTERCEROC END,
      CASE COALESCE(@FACTURABLE,0) WHEN 0 THEN NULL ELSE @IDPLAN END,COALESCE(@FACTURABLE,0),NULL


   IF @PROCESO = 'INGRESOAPROD'
   BEGIN
      INSERT INTO IMOVH (CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO, NOLOTE, NOLOTEPEDIDO, FECHAVENCE, ESTADO, 
                         USUARIO, USUARIOCONF, FECHACONF, PRIEXI, IDARTICULOORI,
                         CANTIDADORI, TIENECAMBIO, DETALLE, CANT_EN_ACTIVOS, ENCXP, PIVA, VLRIVA, PDTO, VLRDTO, CNSHTX, COTIZADO, IDIMPUESTO,
                         IDCLASE, ITFC, CNSITFC, CUENTA_FIMPDV, IDITAR, CODCUM, CAMBIADO, PCOSTOANTESMOD, USUARIOCAMBIO, IDFABRICANTE, 
                         CUENTADB, CUENTACR, IDSERVICIO)
      SELECT @NVOCONSEC, IDARTICULO, 0, CANTIDAD, CANTIDAD, 0, @CNSIZSOL, @CNSIZSOL, FECHAVEN, 0, 
             @USUARIO, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), CANTIDAD, IDARTICULO, CANTIDAD, 0, 'INGRESO LOTE DE PRODUCCION', 0, 0, 0, 0, 0, 0, '', 0, '',
             '', 0, '', '', DBO.FNK_VALORVARIABLE('IDITARUNIDOSIS'), '', 0, 0, '', DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),
             '', '', ''
      FROM   IZOTLIBARTL
      WHERE  CNSIZOTLIBARTL = @CNSIZSOL

      EXEC SPK_CONFIRMARENTRADAS @IDBODEGA, @NVOCONSEC, @USUARIO, '01', @SEDE, @SYS_COMPUTERNAME

      --PRINT 'SACAR LOS ARTICULOS CONSUMIDOS....'
      SELECT @IDTIPOMOV = DBO.FNK_VALORVARIABLE('IDINVMOVINCONSUPROD')
      SELECT @ESTRANSITO = GENTRANSITO FROM ITMO WHERE IDTIPOMOV = @IDTIPOMOV 
      SELECT @IDITAR = DBO.FNK_VALORVARIABLE('IDINVIDITARUNICA')

	  EXEC DBO.SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@MOV', @LONGITUD = 8, @NVOCONSEC = @NVOCONSEC OUTPUT
      --SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
      --PRINT '@NVOCONSEC='+@NVOCONSEC
      INSERT INTO IMOV (CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, FECHAMOV, CCOSTO, IDSOLICITA, IDFUNCIONARIO,
                        ESTADO, OBSERVACION, SUBIOCOMPRA, IDAREA, CONTABILIZADA, PROCEDENCIA, USUARIO, PARCIAL, 
                        SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, IDBODEGAEXTERNA)
      SELECT @NVOCONSEC, @IDBODEGA, @IDTIPOMOV, @CNSIZSOL, DBO.FNK_FECHA_SIN_MLS(GETDATE()), @CCOSTO, @USUARIO, @USUARIO, '0', 'Salidas Por Consumo Produccion', 0, @IDAREA,0, @PROCEDENCIA, @USUARIO,
             0, @SYS_COMPUTERNAME, 0, @IDITAR, 0, @IDBODEGADEST

      --PRINT 'INSERTO IMOVH '
      --PRINT ' MOVIMIENTO @CNSIZSOL ==='+@CNSIZSOL
      --PRINT 'BODEGA DE SALIDA '+@IDBODEGA

      INSERT INTO IMOVH (CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, 
		PCOSTO, NOLOTE, NOLOTEPEDIDO, FECHAVENCE, ESTADO, USUARIO, USUARIOCONF, FECHACONF, 
			PRIEXI, IDARTICULOORI, CANTIDADORI, TIENECAMBIO, DETALLE, 
			CANT_EN_ACTIVOS, ENCXP, PIVA, VLRIVA, PDTO, VLRDTO, CNSHTX, 
			COTIZADO, IDIMPUESTO, IDCLASE, ITFC, CNSITFC, CUENTA_FIMPDV, IDITAR, 
			CODCUM, CAMBIADO, PCOSTOANTESMOD, USUARIOCAMBIO, IDFABRICANTE, 
			CUENTADB, CUENTACR, IDSERVICIO)
      SELECT @NVOCONSEC, IART.IDARTICULO, 0, CANTIDAD, CANTIDAD, 0, @CNSIZSOL, @CNSIZSOL, IEXI.FECHAVENCE, 0, 
               @USUARIO, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), CANTIDAD, IZOTLIBARTLC.IDARTICULO, CANTIDAD, 0, 'Salidas Por Consumo Produccion', 0, 0, 0, 0, 0, 0, '', 0, '',
               '', 0, '', '', DBO.FNK_VALORVARIABLE('IDITARUNIDOSIS'), '', 0, 0, '', '',
               '', '', ''
      FROM   IZOTLIBARTLC INNER JOIN IEXI ON IZOTLIBARTLC.IDARTICULO=IEXI.IDARTICULO
                                           AND IZOTLIBARTLC.NOLOTE=IEXI.NOLOTE
                          INNER JOIN IART  ON IZOTLIBARTLC.IDARTICULO=IART.IDARTICULO
      WHERE  CNSIZOTLIBARTL = @CNSIZSOL AND IEXI.IDBODEGA=@IDBODEGA

      --PRINT 'INSERTO EN ISAL ...'
      --INSERT INTO ISAL(CNSMOV,NOLOTE,IDARTICULO,CANTIDAD,FECHA,NOLOTEPEDIDO,FECHAVENCE,PCOSTO,IDARTICULO_IMOVH)
      --SELECT @NVOCONSEC, IZOTLIBARTLC.NOLOTE,IZOTLIBARTLC.IDARTICULO, CANTIDAD,GETDATE(),'',IEXI.FECHAVENCE,IZOTLIBARTLC.PCOSTO,
      --       IART.IDSERVICIO
      --FROM   IZOTLIBARTLC INNER JOIN IEXI ON IZOTLIBARTLC.IDARTICULO=IEXI.IDARTICULO
      --                                     AND IZOTLIBARTLC.NOLOTE=IEXI.NOLOTE
      --                    INNER JOIN IART  ON IZOTLIBARTLC.IDARTICULO=IART.IDARTICULO
      --WHERE  CNSIZOTLIBARTL = @CNSIZSOL AND IEXI.IDBODEGA=@IDBODEGA

      --PRINT 'CONFIRMO LA  SALIDA ...'

      EXEC SPK_CONFIRMASAL_CM @NVOCONSEC, @USUARIO,@SEDE,''

   END
END

