USE KUNIPSSAM

SELECT IDPLAN, * FROM FTR WHERE F_FACTURA>='20/04/2025'

EXEC SPK_GENERAR_XML_DIAN '0200018396','FV',NULL,0,NULL,NULL,NULL

SELECT * FROM TGEN WHERE TABLA='PLN' AND CAMPO='CobertuPlanBeneficio'

UPDATE PLN SET TIPOVOLUNTARIO='01' WHERE IDPLAN='ASMPP'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC