USE CEM


SELECT * FROM ISAL WHERE COALESCE(ROUND(PCOSTO,2),0)<=0 AND EXISTS(SELECT  * FROM MCPE WHERE ISAL.CNSMOV=MCPE.REFERENCIA1)

--UPDATE ISAL SET PCOSTO=VR_ANTESIVA WHERE PCOSTO<=0 AND EXISTS(SELECT  * FROM MCPE WHERE ISAL.CNSMOV=MCPE.REFERENCIA1) AND COALESCE(VR_ANTESIVA,0)>0

SELECT  MAX(COALESCE(PCOSTO,0)) FROM   IMOVH WHERE IDARTICULO='RX04-1'

--UPDATE ISAL SET PCOSTO=1000.000000  WHERE COALESCE(ROUND(PCOSTO,2),0)<=0 AND EXISTS(SELECT  * FROM MCPE WHERE ISAL.CNSMOV=MCPE.REFERENCIA1)

SELECT  * FROM ISAL WHERE CNSMOV='0100029905'

SELECT  * FROM FTRD WHERE EXISTS(SELECT * FROM MCPE WHERE FTRD.N_FACTURA=MCPE.NOREFERENCIA AND PROCEDENCIA='FACTURA') AND NOITEM=99
UPDATE FTRD SET PAQUETE=0 WHERE EXISTS(SELECT * FROM MCPE WHERE FTRD.N_FACTURA=MCPE.NOREFERENCIA AND PROCEDENCIA='FACTURA') AND NOITEM=99


SELECT CAPITADA,NROCOMPROBANTE,TIPOTTEC,CUENTACXC,CUENTACXC_RAD,IDTERCERO,IDPLAN, * FROM FTR WHERE N_FACTURA='FV14608'

UPDATE FTRD SET PAQUETE=2 WHERE N_FACTURA='FV14608'


SELECT  * FROM PPT WHERE IDTERCERO='0100000003' AND IDPLAN='SUR01P'


UPDATE USUSU SET IDDEPURAR=0 WHERE USUARIO='JJIMENEZ'

BEGIN TRAN 
EXEC SPK_NC_CONTAB_CXPFNT '06SR003647','1','JJIMENEZ','CAJAMENOR02','01','06','0622500000051672'
ROLLBACK

41950505

SELECT  * FROM FNOT WHERE CNSFNOT='06C00011587'

UPDATE MCHE SET CUENTA='41950505',ERROR='',DETALLE='credito por corrección del valor' WHERE  NROCOMPROBANTE='0628800000046261' AND TIPO='DB'


SELECT  * FROM FCXPDBCR WHERE CNSFCXP='06SR003647'


UPDATE FTRD SET PREFIJO='ALC' WHERE N_FACTURA='FV15635'