

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FNOT_COL","METODO":"FNOT_CRUD","PARAMETROS":{"DATOS":{"PROCESO":"Nueva","CNSFNOT":"","CLASE":"C","N_FACTURA":"UV10003","CNSCXC":"0200000127","IDTERCERO":"824001398","F_NOTA":"2023-11-26","OBSERVACION":"PRUEBAS DE SOPORTE","PROCEDENCIA":"NOTAS","IDCONCEPTO":"996","NIT":"824001398","RAZONSOCIAL":"DUSAKAWI EPS","DESCRIPCION":"Glosa o devolución injustificada","CONCEPTO":true,"TIPOCONCEPTO":"P","VALORCONCEPTO":"0","SALDOFACTURA":218546,"VALOR":"10"}},"USUARIO":"JJIMENEZ"}'

SELECT FNOT.CNSFNOT,FNOT.CLASE,DBO.FNK_FECHA_GRINGA(FNOT.F_NOTA)F_NOTA,TER.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,FNOT.N_FACTURA,FNOT.VR_TOTAL,FNOT.PROCEDENCIA,FNOT.IDCONCEPTO,CPNT.DESCRIPCION,FNOT.OBSERVACION,FNOT.CONTABILIZADA,COALESCE(FNOT.NROCOMPROBANTE,'')NROCOMPROBANTE,COALESCE(FNOT.FACTE,0)FACTE,FNOT.CERRADA,FNOT.ESTADO,FNOT.CONCEPTO,FNOT.TIPOCONCEPTO,FNOT.VALORCONCEPTO,FNOT.DETGENERADOS,DATOS = (             SELECT  CNSFNOT,CLASE,ITEM,IDSERVICIO,DESCRIPCION,CANTIDAD,CAST(VR_UNITARIO AS VARCHAR(20))VR_UNITARIO,CAST(VR_TOTAL AS VARCHAR(20))VR_TOTAL,COALESCE(DBO.FNK_RTF(FNOTD.OBSERVACION),'')   AS OBS FROM FNOTD             WHERE FNOTD.CNSFNOT = FNOT.CNSFNOT             FOR JSON PATH )  FROM [dbo].[FNOT] INNER JOIN TER ON FNOT.IDTERCERO=TER.IDTERCERO  LEFT JOIN CPNT ON FNOT.IDCONCEPTO=CPNT.CODIGO WHERE (TER.RAZONSOCIAL LIKE '%%%%' OR CNSFNOT LIKE '%%%%') AND  CNSFNOT='02C00000507'   ORDER BY FNOT.F_NOTA DESC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


ROLLBACK

BEGIN TRAN 
EXEC SPQ_JSON '{"MODELO":"FNOT_COL","METODO":"FNOT_APLICAR","PARAMETROS":{"CNSFNOT":"02C00000507","CLASE":"C"},"USUARIO":"JJIMENEZ"}'

SELECT  * FROM FNOT WHERE COALESCE(CUDE,'')<>''

ROLLBACK
SELECT * FROM FNOT WHERE N_FACTURA='UV10029'
SELECT  * FROM FNOT WHERE CNSFNOT='02C00000493'
SELECT 
* FROM FNOT
ORDER BY F_NOTA DESC


SELECT FNOT.CNSFNOT,FNOT.CLASE,DBO.FNK_FECHA_GRINGA(FNOT.F_NOTA)F_NOTA,TER.NIT,TER.RAZONSOCIAL,FNOT.N_FACTURA,FNOT.VR_TOTAL,FNOT.PROCEDENCIA,FNOT.IDCONCEPTO,CPNT.DESCRIPCION,FNOT.OBSERVACION,FNOT.CONTABILIZADA,COALESCE(FNOT.NROCOMPROBANTE,'')NROCOMPROBANTE,COALESCE(FNOT.FACTE,0)FACTE,FNOT.CERRADA,FNOT.ESTADO,CASE COALESCE(FNOT.CONCEPTO,0) WHEN 1 THEN 'true' ELSE 'false' END  CONCEPTO,FNOT.TIPOCONCEPTO,FNOT.VALORCONCEPTO,FNOT.DETGENERADOS,DATOS = (             SELECT  CNSFNOT,CLASE,ITEM,IDSERVICIO,DESCRIPCION,CANTIDAD,CAST(VR_UNITARIO AS VARCHAR(20))VR_UNITARIO,CAST(VR_TOTAL AS VARCHAR(20))VR_TOTAL,COALESCE(DBO.FNK_RTF(FNOTD.OBSERVACION),'')   AS OBS FROM FNOTD             WHERE FNOTD.CNSFNOT = FNOT.CNSFNOT             FOR JSON PATH )  FROM [dbo].[FNOT] INNER JOIN TER ON FNOT.IDTERCERO=TER.IDTERCERO  LEFT JOIN CPNT ON FNOT.IDCONCEPTO=CPNT.CODIGO WHERE (TER.RAZONSOCIAL LIKE '%%%%' OR CNSFNOT LIKE '%%%%') AND  CNSFNOT='02C00000508'   ORDER BY FNOT.F_NOTA DESC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 