

UPDATE PRI SET CERRADO=0 WHERE ANOMES='202309'

SELECT TIPOTTEC,  * FROM FTR WHERE N_FACTURA='UN38'

USE KPCEM

UPDATE USUSU SET IDDEPURAR=0 WHERE USUARIO='JJIMENEZ'

SELECT  * FROM ACJ WHERE CODCAJA='C001'


SELECT  * FROM UBEQ WHERE CAJA='C001'
