CREATE OR ALTER PROCEDURE DBO.SPK_CREA_FACTURA_POS_CAJA
@CNSFACJ	VARCHAR(20),
@CODCAJA VARCHAR(10),
@COMPANIA	VARCHAR(2)='01',
@SEDE		VARCHAR(5),
@USUARIO	VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)	
WITH ENCRYPTION
AS
DECLARE @CNSFCT		VARCHAR(40)
DECLARE @N_FACTURA	VARCHAR(16)
DECLARE @F_FACTURA	DATETIME
DECLARE @F_VENCE	DATETIME
DECLARE @PREFIJOFAC	VARCHAR(8)
DECLARE @IDTERCERO	VARCHAR(20)
DECLARE @IDACTIVO	VARCHAR(20)
DECLARE @IDAREA		VARCHAR(20)
DECLARE @CCOSTO		VARCHAR(20)
DECLARE @VALOR		DECIMAL(14,2)
DECLARE @PREFIJO	VARCHAR(6)
DECLARE @PCOSTO		DECIMAL(14,2)
DECLARE @OBSERVACION	VARCHAR(100)
DECLARE @N_CUOTA	INT
DECLARE @DATO           VARCHAR(80)
DECLARE @CNSIACTH       VARCHAR(20)
DECLARE @CLASEFAC  VARCHAR(10)
DECLARE @PROCEDENCIA  VARCHAR(10)
DECLARE @IDFORMATOFTR VARCHAR(10)
DECLARE @VLRFCJ DECIMAL(14,2)
DECLARE @CNSRESOL VARCHAR(20)
DECLARE @CNSCXC_AUT VARCHAR(20)
DECLARE @FECHA DATETIME
DECLARE @CUENTA VARCHAR(20)
DECLARE @ITEM_FCXCDV INT
DECLARE @MONEDA VARCHAR(10)
DECLARE @IDTERCEROAFI VARCHAR(20)
DECLARE @IDCATEGORIA VARCHAR(10)
DECLARE @ELECTRONICA BIT
BEGIN
   PRINT 'INGRESE A CREAR LA FACUTRA'
   SELECT @CLASEFAC=CLASEFAC FROM CAJ WHERE CODCAJA=@CODCAJA
   SELECT @CUENTA=CUENTA FROM TTEC WHERE TIPO=DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART')
   IF COALESCE(@CLASEFAC,'NA')='NA'
   BEGIN
      PRINT 'CAJA NO EMITE FACTURA, ME DEVUELVO'
      RETURN
   END
   PRINT 'VALIDO SI EL CONCPETO DE CAJA ES ELECTRONICO'
   SELECT @ELECTRONICA=0
   IF EXISTS(SELECT * FROM FCJD INNER JOIN MOCC ON FCJD.CONCEPTO=MOCC.CODIGOCPCJ WHERE FCJD.CODCAJA=@CODCAJA AND FCJD.CNSFACJ=@CNSFACJ)
   BEGIN 
      SELECT @ELECTRONICA=1
   END
   ELSE
   BEGIN
      IF EXISTS(SELECT * FROM FCJD INNER JOIN CPCJ ON FCJD.CONCEPTO=CPCJ.CODIGO WHERE FCJD.CODCAJA=@CODCAJA AND FCJD.CNSFACJ=@CNSFACJ AND COALESCE(CPCJ.NDIAN,0)=1)
      BEGIN 
         SELECT @ELECTRONICA=1
      END
   END
   IF COALESCE(@ELECTRONICA,0)=0
   BEGIN
      PRINT 'CONCEPTO NO VALIDO PARA ELCTRONICA'
      RETURN
   END
   PRINT 'DEBO CONTABILIZAR EL RECIBO DE CAJA'

   IF ( SELECT COUNT(1) FROM PLN WHERE IDPLAN = COALESCE(DBO.FNK_VALORVARIABLE('IDPLANPART'),'') ) =0
       OR (SELECT COUNT (1) FROM TTEC WHERE TIPO = COALESCE(DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART'),'')) =0
       OR (SELECT COUNT (1) FROM TER WHERE IDTERCERO = COALESCE(DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR'),'')) =0
   BEGIN
      RAISERROR('la fatura es de particular pero no esta configurada la variable IDPLANPART o IDTERCONTABLEPART o IDTERCEROPARTICULAR',1,16)
      RETURN
   END

      PRINT 'DEBO CONTABILIZAR EL RECIBO DE CAJA'
    IF NOT EXISTS(SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ AND COALESCE(CONTABILIZADA,0)<>0)
    BEGIN
        EXEC SPK_NC_CONTAB_CAJA_ING @CNSFACJ,@CODCAJA,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,''
    END

   SELECT @VLRFCJ=VALORTOTAL,@FECHA=FECHA,@IDTERCEROAFI=IDAFILIADO FROM FCJ WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ

   PRINT 'Crea el Afiliado como Tercero con la categoria de Afiliado'
   SET @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
       
   PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '''+@IDTERCEROAFI+''','''+@IDCATEGORIA+''''
   EXEC SPK_INSERT_TERDEAFI @IDTERCEROAFI, @IDCATEGORIA

	PRINT 'Termine de configurar AFI'

   SELECT @IDTERCERO=COALESCE(RUC,IDAFILIADO) FROM AFI WHERE IDAFILIADO=@IDTERCEROAFI

   SET @CNSFCT=SPACE(40)
   EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@CNSFTR',@CNSFCT OUTPUT   
   SELECT @CNSFCT = @SEDE + REPLACE(SPACE(8 - LEN(@CNSFCT))+LTRIM(RTRIM(@CNSFCT)),SPACE(1),0)

   IF @CLASEFAC='POS'
   BEGIN
      DECLARE @UVTMAXFACTPOS SMALLINT 
      SELECT @UVTMAXFACTPOS=CASE WHEN ISNUMERIC(DBO.FNK_VALORVARIABLE('UVT_MAX_FACTURAPOS'))= 1 THEN CONVERT(INT,DBO.FNK_VALORVARIABLE('UVT_MAX_FACTURAPOS')) ELSE 0 END
      IF @UVTMAXFACTPOS>0
      BEGIN 
         IF @VLRFCJ> (@UVTMAXFACTPOS*CONVERT(DECIMAL(14,2),DBO.FNK_VALORVARIABLE('VALOR_UVT')))
         BEGIN 
            SELECT @PROCEDENCIA='FTR'
         END
         ELSE
         BEGIN
            SELECT @PROCEDENCIA='FPOS' 
         END
      END
      ELSE
      BEGIN
         SELECT @PROCEDENCIA='FPOS'  
      END
   END
   IF @CLASEFAC='ELECTRO'
   BEGIN
      SELECT @PROCEDENCIA='FTR'
   END

   SET @N_FACTURA = SPACE(20)
   EXEC SPK_GENNUMEROFACTURA @COMPANIA, @SEDE, NULL, @N_FACTURA OUTPUT,@PROCEDENCIA  
   PRINT ' N_FACTURA = '+ CASE WHEN @N_FACTURA IS NULL THEN '' ELSE @N_FACTURA END

   SET @F_FACTURA=DBO.FNK_FECHA_SIN_HORA(GETDATE())
   SET @F_VENCE=@F_FACTURA+30
 
   SELECT @IDFORMATOFTR=COALESCE(DBO.FNK_VALORVARIABLE('IDFORMATOFTR_CAJA'),'CAJ01')
   SELECT @MONEDA = DATO FROM USVGS WHERE IDVARIABLE = 'IDMONEDABASE'

   IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
   BEGIN
      IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
      BEGIN
         SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE IDENTIFICADOR=@SEDE AND VENCIDA=0 AND PROCEDENCIA =@PROCEDENCIA
      END
      ELSE
      BEGIN
         SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE IDENTIFICADOR=@SEDE AND   VENCIDA=0 AND PROCEDENCIA = @PROCEDENCIA
      END
   END


   INSERT INTO FTR (CNSFCT,COMPANIA,CLASE,IDTERCERO,N_FACTURA,F_FACTURA,F_VENCE,VR_TOTAL,
		            COBRADOR,VENDEDOR,MONEDA,OCOMPRA,ESTADO,F_CANCELADO,IDAFILIADO,EMPLEADO,
	   	         NOREFERENCIA,PROCEDENCIA,TIPOFAC,OBSERVACION,TIPOVENTA,VALORCOPAGO,
		            DESCUENTO,VALORPCOMP,CREDITO,INDCARTERA,INDCXC,MARCA,INDASIGCXC,MARCACONT,
		            CONTABILIZADA,NROCOMPROBANTE,IMPRESO,VALORSERVICIOS,CLASEANULACION,CNSLOG,
		            USUARIOFACTURA,FECHAFAC,MIVA,PIVA,IDPLAN,VR_ABONOS,FECHAPASOCXC,TIPOFIN,
		            CNSFMAS,IDAREA_ALTA,CCOSTO_ALTA,IDDEP,TIPOCOPAGO,VLRNOTADB,VLRNOTACR,
		            TIPOTTEC,CUENTACXC,RAZONANULACION,IDFORMATO,CUENTACXC_RAD,RDIAN,CNSRESOL,IDSEDE,CODPRG,CODUNG)
   SELECT @CNSFCT,@COMPANIA,'C',@IDTERCERO,@N_FACTURA,@F_FACTURA,@F_VENCE,
	      FCJ.VALORTOTAL,'','',@MONEDA,NULL,'P',FCJ.FECHA,FCJ.IDAFILIADO,@USUARIO,@CODCAJA+@CNSFACJ,'CAJA','I',
	      FCJ.OBSERVACION+' NOADMISION: '+FCJ.NOADMISION+' RECIBO CAJA'+@CNSFACJ+' CODCAJA'+@CODCAJA,'Contado',0,0,0,0,0,0,0,0,0,0,NULL,0,
         FCJ.VALORTOTAL,NULL,NULL,@USUARIO,
	      DBO.FNK_FECHA_SIN_MLS(GETDATE()),0,0,DBO.FNK_VALORVARIABLE('IDPLANPART'),0,NULL,'C',NULL,NULL,NULL,NULL,
	      NULL,NULL,NULL,DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART'),@CUENTA,NULL,@IDFORMATOFTR,@CUENTA,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,
         COALESCE(@CNSRESOL,''),@SEDE,'',''
   FROM  FCJ 
   WHERE FCJ.CNSFACJ=@CNSFACJ
   AND FCJ.CODCAJA=@CODCAJA



     SET @N_CUOTA=1

   INSERT INTO FTRD (CNSFTR,IDPROVEEDOR,N_CUOTA,FECHA,DB_CR,AREAPRESTACION,AREAFUNCONT,
		      UBICACION,VR_TOTAL,IMPUTACION,CCOSTO,PREFIJO,ANEXO,REFERENCIA,IDCIRUGIA,
		      CANTIDAD,VALOR,VLR_SERVICI,VLR_COPAGOS,VLR_PAGCOMP,NOADMISION,
		      NOPRESTACION,NOITEM,N_FACTURA,SUBCCOSTO,PCOSTO,FECHAPREST,VLRNOTADB,
		      VLRNOTACR,TIPO)
   SELECT @CNSFCT,FCJ.IDAFILIADO,@N_CUOTA,DBO.FNK_FECHA_SIN_MLS(GETDATE()),'DB',@IDAREA,@IDAREA,
	   NULL,FCJD.VALORTOTAL,NULL,@CCOSTO,CPCJ.CODIGO,CPCJ.DESCRIPCION,FCJD.CONCEPTO,NULL,1,FCJD.VALORTOTAL,FCJD.VALORTOTAL,0,0,
	   '','','',@N_FACTURA,NULL,NULL,NULL,0,0,NULL
   FROM  FCJD INNER JOIN FCJ ON FCJD.CODCAJA=FCJ.CODCAJA AND FCJD.CNSFACJ=FCJ.CNSFACJ
              INNER JOIN CPCJ ON FCJD.CONCEPTO=CPCJ.CODIGO
   WHERE FCJD.CNSFACJ=@CNSFACJ
   AND FCJD.CODCAJA=@CODCAJA

   UPDATE FCJ SET N_FACTURAPOS=@N_FACTURA WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ

   PRINT 'VOY ACONTABILIZAR LA FACTURA '

   EXEC SPK_NC_CONTAB_FTR @N_FACTURA, @COMPANIA,@USUARIO,@SYS_COMPUTERNAME,@SEDE,''

   PRINT 'VOY A CREAR LA CXC PARA QUITAR EL SALDO DE CARTERA '
   IF NOT EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTURA)
   BEGIN
      RAISERROR('No Fue Genereada la Factura del Copago, Comuniquese con el Administrador del sistema...',16,1)
      RETURN
   END
   SET @CNSCXC_AUT=SPACE(20)
   
   
   EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@CXC',@CNSCXC_AUT OUTPUT
   SELECT @CNSCXC_AUT = @SEDE + REPLACE(SPACE(8 - LEN(@CNSCXC_AUT))+LTRIM(RTRIM(@CNSCXC_AUT)),SPACE(1),0)
                        
   EXEC SPK_ADMIN_CXC_CONTAB
         @CNSCXC_AUT,
         @IDTERCERO,
         @N_FACTURA,
         @FECHA,
         @FECHA,
         @USUARIO,
         'CXC GENERADA EN CAJA',
         @COMPANIA,
         '',
         @VLRFCJ,     
         @CCOSTO,
         @IDAREA,  
         'INSERT',
         0,
         @CUENTA    
                                                                 
      SELECT @ITEM_FCXCDV = ITEM FROM FCXCDV WHERE N_FACTURA = @N_FACTURA AND TIPO = 'F'
      DECLARE @CNSFPAG VARCHAR(20)
      SET @CNSFPAG=SPACE(20)
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FPAG',@CNSFPAG OUTPUT
      SELECT @CNSFPAG = @SEDE + REPLACE(SPACE(8 - LEN(@CNSFPAG))+LTRIM(RTRIM(@CNSFPAG)),SPACE(1),0)
                     
                       
      EXEC SPK_ADMIN_PAGOS 
            'CXC', 
            @N_FACTURA, 
            @CNSCXC_AUT,
            @CNSFPAG,
            'INSERT',
            @VLRFCJ,
            @IDTERCERO,
            @USUARIO,     
            @SYS_COMPUTERNAME,
            @COMPANIA,
            @SEDE,
            'PAGO REALIZADO EN CAJA',
            'CAJA',
            'P',
            NULL, 
            @FECHA,
            @CODCAJA,
            @CNSFACJ,
            @CUENTA,
            'F',
            NULL
      INSERT INTO FCJPCXC (CNSFACJ, CODCAJA, CNSCXC, N_FACTURA, ITEM_FCXCDV, IDTERCERO, VALOR, 
                           VLR_IMPUESTOS, ESTADO, CNSFPAG, TIPOCXC)
      SELECT @CNSFACJ, @CODCAJA, @CNSCXC_AUT, @N_FACTURA, @ITEM_FCXCDV, @IDTERCERO,@VLRFCJ,
               0, 'P', @CNSFPAG, 0

     EXEC SPK_NC_CONTAB_CXC @CNSFPAG,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,''

END


