USE KESPERANZA

SELECT FCXP.CNSFCXP,TER.NIT,TER.RAZONSOCIAL,DBO.FNK_FECHA_DDMMAA(FCXP.F_FACTURAREF) FECHA,FCXP.NOREFERENCIA,FCXP.FACCONTROL,
DBO.FNK_FECHA_DDMMAA(FCXPP.FECHACONF)FECHAORDEN,DBO.FNK_FECHA_DDMMAA(FCJ.FECHA)FECHAPAGO,DATEDIFF(DAY,FCXP.F_FACTURAREF,FCJ.FECHA)DIASDIF
FROM FCXP INNER JOIN TER ON FCXP.IDTERCERO=TER.IDTERCERO
          LEFT JOIN FCXPP ON FCXP.CNSFCXP=FCXPP.CNSFCXP
          LEFT JOIN FCJ ON FCXPP.CODCAJA=FCJ.CODCAJA AND FCXPP.CNSFACJ=FCJ.CNSFACJ
WHERE DOCEQUIVALENTE=1 AND FCXP.ESTADO<>'A'
AND FCXPP.ESTADO<>'A'
AND FCJ.CERRADA=1
AND FCJ.ESTADO='P'
AND FCXP.PROCEDENCIA <>'Nomina'
AND CONVERT(DATE,F_FACTURAREF)>=@1FECHAINI
AND CONVERT(DATE,F_FACTURAREF)<=@2FECHAFIN
      

SELECT  * FROM AUT WHERE NOAUT=''