IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_ANULA_FACT' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_ANULA_FACT
END

GO
CREATE PROCEDURE DBO.SPK_ANULA_FACT
@N_FACTURA        VARCHAR(16),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@RAZONCAMBIO      VARCHAR(255),
@SYS_COMPUTERNAME VARCHAR(254),
@USUARIO2         VARCHAR(12)
WITH ENCRYPTION
AS
DECLARE @PROCEDENCIA    VARCHAR(10)
DECLARE @TIPOFAC        VARCHAR(1)
DECLARE @CONTABILIZADA  SMALLINT
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @NVOCONSEC      VARCHAR(20)
DECLARE @NOADMISION     VARCHAR(16)
DECLARE @IDTERCERO      VARCHAR(20)
DECLARE @IDPLAN         VARCHAR(6)
DECLARE @TIPOADM        VARCHAR(2)
DECLARE @ESTACONTAB     SMALLINT
DECLARE @AUX            INT 
DECLARE @ESTADO         VARCHAR(1)
declare @ANOFACTURA     VARCHAR(4)
DECLARE @MESFACTURA     VARCHAR(2)
DECLARE @ANOACTUAL      VARCHAR(4)
DECLARE @MESACTUAL      VARCHAR(2)
DECLARE @ESTADOPERFTR   INT
DECLARE @ESTADOPERACT   INT
DECLARE @NVOCNSFNOT     VARCHAR(20)
DECLARE @CERRADOFTR     SMALLINT
DECLARE @CERRADOINV     SMALLINT  
DECLARE @CNSFMAS        VARCHAR(20)
DECLARE @CNSCXC         VARCHAR(20)
DECLARE @CNSMOV         VARCHAR(20)
DECLARE @FACTE          SMALLINT
DECLARE @FCOPA          SMALLINT
DECLARE @HOY            SMALLDATETIME=GETDATE()
DECLARE @HOY_SINH       DATE=CONVERT(DATE,@HOY)
DECLARE @CNSFTR         VARCHAR(20)
DECLARE @RECO           VARCHAR(20)
DECLARE @ESTADOPPTO     VARCHAR(10)
DECLARE @CNSPPTO        VARCHAR(10)
DECLARE @ESCOPAGOPE       BIT
BEGIN
   SET @FCOPA=0
   SELECT @NOADMISION     = NOREFERENCIA,
          @IDTERCERO      = IDTERCERO,
          @IDPLAN         = IDPLAN,
          @PROCEDENCIA    = PROCEDENCIA,
          @TIPOFAC        = TIPOFAC,
          @FACTE          = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN CASE WHEN COALESCE(FACTEP,'') NOT IN('OK','PEND') THEN 0 ELSE 1 END ELSE FACTE END,
          @CONTABILIZADA  = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN CASE WHEN COALESCE(FACTEP,'') NOT IN('OK','PEND') THEN 0 ELSE 1 END 
                           ELSE CASE WHEN COALESCE(FTR.FACTE,0)<>0  THEN 1 ELSE COALESCE(CONTABILIZADA,0) END END, 
          @NROCOMPROBANTE = COALESCE(NROCOMPROBANTE,''),
          @ANOFACTURA     = CONVERT(VARCHAR, YEAR(FTR.F_FACTURA)),
          @MESFACTURA     = CONVERT(VARCHAR, MONTH(FTR.F_FACTURA)),
          @CNSFMAS        = CNSFMAS,
          @FCOPA          = CASE WHEN TIPOFIN='N' THEN 1 ELSE 0 END,
          @CNSFTR         = CNSFCT,
          @ESCOPAGOPE     = CASE WHEN COALESCE(CP_CONVENIO,'')='Boleta' THEN 1 ELSE 0 END
   FROM   FTR 
   WHERE  N_FACTURA   = @N_FACTURA

   SELECT @ANOACTUAL  = CONVERT(VARCHAR, YEAR(@HOY)), @MESACTUAL = CONVERT(VARCHAR, MONTH(@HOY))
   IF @ANOACTUAL > @ANOFACTURA
   BEGIN
      SELECT @AUX = CERRADO FROM PRI WHERE ANO = @ANOFACTURA AND MES = 12
      IF @AUX = 1
      BEGIN
         IF DBO.FNK_VALORVARIABLE('FTR_ANULAEJERCANT') <> 'SI' 
         BEGIN
            RAISERROR('FACTURA DE UN EJERCICIO ANTERIOR DEBE CONFIGURARSE DE ACUERDO AL ART?CULO 106 DEL DECRETO 2649',16,1)
            RETURN 
         END
      END
   END
   SELECT @ESTADOPERFTR = COALESCE(CERRADO,0),@CERRADOINV=CERRADO_INV,
          @CERRADOFTR   = CERRADO_FAC 
   FROM   PRI 
   WHERE  ANO = @ANOFACTURA AND MES = @MESFACTURA 

   SELECT @ESTADOPERACT = COALESCE(CERRADO,0) FROM PRI WHERE ANO = @ANOACTUAL AND MES = @MESACTUAL

   ---SE AGREGA CONDICIONAL EN CASO DE SE ACTIVE LA ANULACION DE FACTURAS DE A?OS ANTERIORES

   IF @ESTADOPERFTR = 1 AND @ESTADOPERACT = 1 AND  DBO.FNK_VALORVARIABLE('FTR_ANULAEJERCANT') <> 'SI' 
   BEGIN
      RAISERROR('EL PERIODO DE LA FACTURA Y EL PERIODO ACTUAL ESTAN CERRADOS.',16,1)
      RETURN
   END
   
   SELECT @ESTACONTAB = @CONTABILIZADA
   PRINT 'PROCEDENCIA= '+@PROCEDENCIA
   PRINT 'TIPOFACT= '+@TIPOFAC
   PRINT 'ESTADOPERFTR='+STR(@ESTADOPERFTR)
   PRINT 'FACTE='+STR(COALESCE(@FACTE,0))
   IF @FACTE<>0 AND @ESTADOPERFTR=0
   BEGIN
      SELECT @ESTADOPERFTR=1
   END
   
   IF @PROCEDENCIA = 'SALUD' 
   BEGIN
      SELECT @TIPOADM = TIPOADM FROM HADM WHERE NOADMISION = @NOADMISION 
      IF @ESTACONTAB = 0 
      BEGIN
         UPDATE FTR SET ESTADO = 'A', RAZONANULACION=@RAZONCAMBIO WHERE  N_FACTURA = @N_FACTURA
         IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
         BEGIN
            IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
            BEGIN
               SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
               PRINT 'Retiro los recuados si Existe'
               UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
               DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
               UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
               PRINT 'Retiro los Reconocimientos...'
               UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
               DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
               UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
               UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
            END
         END

         IF COALESCE(@FCOPA,0)<>1
            UPDATE HPRED SET FACTURADA=0, N_FACTURA=NULL WHERE N_FACTURA = @N_FACTURA
         ELSE
             UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
      
         UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

         EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
         SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         
            -- el log debe mirarse donde apunta bdix revisar
         INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
         SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                  @HOY, @SYS_COMPUTERNAME          
         INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
         SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
         IF @TIPOFAC = 'I'
         BEGIN       
            UPDATE HADMF SET ESTADO = 'A' WHERE NOADMISION = @NOADMISION AND N_FACTURA = @N_FACTURA                   
            IF @TIPOADM = DBO.FNK_VALORVARIABLE('IDTARIFASOAT')
            BEGIN
               DELETE HADM_S WHERE NOADMISION = @NOADMISION
               DELETE HADM_T WHERE NOADMISION = @NOADMISION
               UPDATE HADM SET FACTURADA = 0 WHERE NOADMISION = @NOADMISION
            END         
         END
         ELSE
         BEGIN           
            UPDATE FMAS SET FACTURADA = 0 WHERE CNSFMAS =@CNSFMAS
            UPDATE HADM SET FACTURADA = 0, N_FACTURA = '' WHERE N_FACTURA = @N_FACTURA 
         END
      END
      ELSE
      BEGIN
         IF @ESTACONTAB = 1 --ESTA CONTABILIZADA
         BEGIN        
            PRINT 'ESTA CONTABILIZADA INGRESO ACA'
            --REVISAR EL PERIODO DE LA FACTURA
            IF @ESTADOPERFTR = 0  AND @CERRADOFTR=0 --ESTA ABIERTO ==> SE ANULA EL COMPROBANTE CONTABLE Y ACTUALIZA ESTADOS
            BEGIN
               UPDATE MCP SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END
               IF COALESCE(@FCOPA,0)<>1
               BEGIN
                  PRINT 'LIBERO CARGOS'
                  UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
               END
               ELSE
               BEGIN
                  PRINT 'LIBERO COPAGO'
                   UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
               END
                        
               UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               -- el log debe mirarse donde apunta bdix revisar
               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                        @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL  
         
               IF @TIPOFAC = 'I'
               BEGIN
                  UPDATE HADMF SET ESTADO = 'A' WHERE NOADMISION = @NOADMISION AND N_FACTURA = @N_FACTURA
               
                  IF @TIPOADM = DBO.FNK_VALORVARIABLE('IDTARIFASOAT')
                  BEGIN
                     DELETE HADM_S WHERE NOADMISION = @NOADMISION
                     DELETE HADM_T WHERE NOADMISION = @NOADMISION
                     UPDATE HADM SET FACTURADA = 0 WHERE NOADMISION = @NOADMISION
                  END
               END
               ELSE    --ES  MASIVA
               BEGIN
                  UPDATE FMAS SET FACTURADA = 0 WHERE CNSFMAS =@CNSFMAS
                  UPDATE HADM SET FACTURADA = 0, N_FACTURA = '' WHERE N_FACTURA = @N_FACTURA 
               END
            END
            ELSE
            BEGIN --EL PERIODO DE LA FACTURA ESTA CERRADO
               -- SE DEBE ANULAR POR NOTA CREDITO
               -- se crea el encabezado de la Nota Credito
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                        @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  
               SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
               INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                                 MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                                 CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                                 CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                                 IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                                 VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
               SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                      NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', 1, 
                      '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0
               -- se generan los detalles de la nota credito
               EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO
               IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
               BEGIN
                  UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
               END
               -- se aplica la nota credito
               EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME
               UPDATE FTR SET RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC' WHERE N_FACTURA=@N_FACTURA
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END
               IF @TIPOFAC = 'M'  --MASIVA
               BEGIN
                  UPDATE FMAS SET FACTURADA = 0 WHERE CNSFMAS =@CNSFMAS
               END
               IF COALESCE(@FCOPA,0)<>1
               BEGIN
                  PRINT 'LIBERO CARGOS'
                  UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
               END
               ELSE
               BEGIN
                  PRINT 'LIBERO COPAGO'
                   UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
               END
                        
               UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA
            END                       
         END
         ELSE
         BEGIN
            IF @ESTACONTAB = 2  --ESTA CONTABILIZADA CON ERRORES
            BEGIN
               PRINT 'ESTA CONTABILIZADA CON ERRORES'   
               UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END
               IF COALESCE(@FCOPA,0)<>1
               BEGIN
                  UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
               END
               ELSE
               BEGIN
                   UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
               END
                  
               UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               -- el log debe mirarse donde apunta bdix revisar
               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                      @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
               IF @TIPOFAC = 'I'
               BEGIN
                  UPDATE HADMF SET ESTADO = 'A' WHERE NOADMISION = @NOADMISION AND N_FACTURA = @N_FACTURA
                  IF @TIPOADM = DBO.FNK_VALORVARIABLE('IDTARIFASOAT')
                  BEGIN
                     DELETE HADM_S WHERE NOADMISION = @NOADMISION
                     DELETE HADM_T WHERE NOADMISION = @NOADMISION
                     UPDATE HADM SET FACTURADA = 0 WHERE NOADMISION = @NOADMISION
                  END         
               END
               ELSE
               BEGIN  --MASIVA
                  UPDATE FMAS SET FACTURADA = 0 WHERE CNSFMAS =@CNSFMAS
                  UPDATE HADM SET FACTURADA = 0, N_FACTURA = '' WHERE N_FACTURA = @N_FACTURA 
                  UPDATE HADMF SET ESTADO = 'A' WHERE N_FACTURA = @N_FACTURA
               END
               DELETE MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               UPDATE MCPE SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                                REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                                RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
               SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                      REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                      RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
               FROM   MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               DELETE MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
            END
            ELSE
            BEGIN -- NO DEFINIDO
               PRINT 'NO DEFINIDO @ESTACONTAB <> 0, 1, 2'
            END
         END
      END
      /* ARREGLO DE HONORARIOS*/
      IF @TIPOFAC = 'I'
      BEGIN
         DELETE FXPD 
         FROM   FXPD INNER JOIN FXP ON FXPD.N_PRESUP  = FXP.N_PRESUP
                                   AND FXPD.IDTERCERO = FXP.IDTERCERO
         WHERE  FXP.NOREFERENCIA = @NOADMISION 
         AND    FXP.PROCEDENCIA  = 'SALUD'
      
         DELETE FXP WHERE NOREFERENCIA = @NOADMISION AND PROCEDENCIA = 'SALUD'
      END
      ELSE
      BEGIN
         DELETE FXPD
         FROM   FXPD INNER JOIN FXP ON FXPD.N_PRESUP  = FXP.N_PRESUP
                                   AND FXPD.IDTERCERO = FXP.IDTERCERO
                     INNER JOIN ( SELECT NOADMISION, COUNT(*) VECES FROM FTRD 
                                  WHERE  N_FACTURA = @N_FACTURA 
                                  GROUP BY NOADMISION 
                                ) X ON FXP.NOREFERENCIA = X.NOADMISION 
                                   AND FXP.PROCEDENCIA  = 'SALUD'

         DELETE FXP 
         FROM   FXP INNER JOIN ( SELECT NOADMISION, COUNT(*) VECES FROM FTRD 
                                  WHERE  N_FACTURA = @N_FACTURA 
                                  GROUP BY NOADMISION 
                                ) X ON FXP.NOREFERENCIA = @NOADMISION 
                                   AND FXP.PROCEDENCIA = 'SALUD'
      END
      /* fin: HM*/
   END

   IF @PROCEDENCIA='CI' OR  @PROCEDENCIA='CE'
   BEGIN
      PRINT 'ES DE PROCEDENCIA = '+@PROCEDENCIA + ' // CONTABILIZADA = '+CONVERT(VARCHAR,@ESTACONTAB )
      IF @ESTACONTAB = 0 -- NO ESTA CONTABILIZADA
      BEGIN
         UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO WHERE  N_FACTURA = @N_FACTURA
         IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
         BEGIN
            IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
            BEGIN
               SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
               PRINT 'Retiro los recuados si Existe'
               UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
               DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
               UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
               PRINT 'Retiro los Reconocimientos...'
               UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
               DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
               UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
               UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
            END
         END
      END
      ELSE
      BEGIN
         IF @ESTACONTAB = 1 --ESTA CONTABILIZADA
         BEGIN        
            PRINT 'ESTA CONTABILIZADA'
            IF @ESTADOPERFTR = 0  AND @CERRADOFTR=0 --ESTA ABIERTO ==> SE ANULA EL COMPROBANTE CONTABLE Y ACTUALIZA ESTADOS
            BEGIN
               UPDATE MCP SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO   WHERE  N_FACTURA = @N_FACTURA
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END
                  
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               -- el log debe mirarse donde apunta bdix revisar
               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                        @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL  
            
            END
            ELSE
            BEGIN 
	          --EL PERIODO DE LA FACTURA ESTA CERRADO
               -- SE DEBE ANULAR POR NOTA CREDITO
               -- se crea el encabezado de la Nota Credito
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                        @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  
               SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
               INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                                 MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                                 CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                                 CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                                 IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                                 VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
               SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                      NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', 1, 
                      '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0
               -- se generan los detalles de la nota credito
               EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO
               IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
               BEGIN
                  UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
               END
               -- se aplica la nota credito
               EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME
               UPDATE FTR SET RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC' WHERE N_FACTURA=@N_FACTURA
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END
            END
         END
         ELSE
         BEGIN
            IF @ESTACONTAB = 2 --ESTA CONTABILIZADA CON ERRORES
            BEGIN        
               PRINT 'ESTA CONTABILIZADA CON ERRORES'   
               UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END
               DELETE MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE

               UPDATE MCPE SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                                 REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                                 RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
               SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                        REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                        RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
               FROM   MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               DELETE MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
            END
         END
      END
      --AQUI HACE LO MISMO LIBERAR ORIGEN ESTE SIN CONTABILIZAR O CONTABILIZADA O CONT CON ERRORES
      IF @PROCEDENCIA='CI' OR @NOADMISION='CEUNIFICADO'
      BEGIN
         IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND COALESCE(@ESCOPAGOPE,0)=1
         BEGIN
            UPDATE CIT SET NFACTURA = NULL WHERE  NFACTURA = @N_FACTURA 
         END
         ELSE
         BEGIN
            UPDATE CIT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
            WHERE  N_FACTURA =  @N_FACTURA AND FACTURADA = 1
         END
	     DELETE FXPD 
	     FROM   FXPD INNER JOIN FXP  ON FXPD.N_PRESUP  = FXP.N_PRESUP
		                          AND FXPD.IDTERCERO = FXP.IDTERCERO
                     INNER JOIN FTRD ON FXP.NOREFERENCIA = FTRD.NOADMISION
         WHERE  FXP.PROCEDENCIA  = 'CI'
         AND    FTRD.N_FACTURA   = @N_FACTURA
               
         DELETE FXP 
         FROM   FXP INNER JOIN FTRD ON FXP.NOREFERENCIA = FTRD.NOADMISION
         WHERE  FXP.PROCEDENCIA = 'CI'
         AND    FTRD.N_FACTURA   = @N_FACTURA

         DELETE HACTRANFD WHERE N_FACTURA=@N_FACTURA
		 DELETE HACTRANF  WHERE N_FACTURA=@N_FACTURA
      END

      IF @PROCEDENCIA='CE' OR @NOADMISION='CEUNIFICADO'
      BEGIN
        UPDATE AUT SET FACTURADA = 0, MARCAFAC = 0, N_FACTURA = NULL
	    WHERE  AUT.N_FACTURA =  @N_FACTURA AND FACTURADA = 1

		UPDATE AUTD SET FACTURADA = 0, N_FACTURA = NULL
        WHERE  AUTD.N_FACTURA = @N_FACTURA AND FACTURADA = 1
             
        DELETE FXPD 
		FROM   FXPD INNER JOIN FXP  ON FXPD.N_PRESUP  = FXP.N_PRESUP
		                            AND FXPD.IDTERCERO = FXP.IDTERCERO
                    INNER JOIN FTRD ON FXP.NOREFERENCIA = FTRD.NOADMISION
        WHERE  FXP.PROCEDENCIA  = 'CE'
        AND    FTRD.N_FACTURA   = @N_FACTURA
               
        DELETE FXP 
        FROM   FXP INNER JOIN FTRD ON FXP.NOREFERENCIA = FTRD.NOADMISION
        WHERE  FXP.PROCEDENCIA = 'CE'
        AND    FTRD.N_FACTURA   = @N_FACTURA
	
		DELETE HACTRANFD WHERE N_FACTURA=@N_FACTURA
		DELETE HACTRANF  WHERE N_FACTURA=@N_FACTURA
      END
   END

   IF @PROCEDENCIA = 'FINANCIERO'
   BEGIN
      IF @ESTACONTAB = 0 
      BEGIN
         UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO WHERE  N_FACTURA = @N_FACTURA
         IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
         BEGIN
            IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
            BEGIN
               SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
               PRINT 'Retiro los recuados si Existe'
               UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
               DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
               UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
               PRINT 'Retiro los Reconocimientos...'
               UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
               DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
               UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
               UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
            END
         END
         IF COALESCE(@FCOPA,0)<>1
         BEGIN
            UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
         END
         ELSE
         BEGIN
             UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
         END
      
         UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

         EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
         SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         
            -- el log debe mirarse donde apunta bdix revisar
         INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
         SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                  @HOY, @SYS_COMPUTERNAME          
         INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
         SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
      END
      ELSE
      BEGIN
         IF DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT') = 'COMER'
         BEGIN
            IF EXISTS(SELECT * FROM FCXCD WHERE N_FACTURA=@N_FACTURA)
            BEGIN
               PRINT 'Borro de fcxcdv'
               SELECT @CNSCXC=CNSCXC FROM FCXCD WHERE N_FACTURA=@N_FACTURA
               DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA
               DELETE FCXCD WHERE N_FACTURA=@N_FACTURA
               UPDATE FCXC SET ESTADO='Inactiva',CERRADA=1 WHERE CNSCXC=@CNSCXC
            END
         END
         IF @ESTACONTAB = 1 --ESTA CONTABILIZADA
         BEGIN        
            PRINT 'ESTA CONTABILIZADA'
            --REVISAR EL PERIODO DE LA FACTURA
            IF @ESTADOPERFTR = 0  AND @CERRADOFTR=0 --ESTA ABIERTO ==> SE ANULA EL COMPROBANTE CONTABLE Y ACTUALIZA ESTADOS
            BEGIN
               UPDATE MCP SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END
               IF COALESCE(@FCOPA,0)<>1
               BEGIN
                  UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
               END
               ELSE
               BEGIN
                   UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
               END
                  
               UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               -- el log debe mirarse donde apunta bdix revisar
               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                        @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL          
            END
            ELSE
            BEGIN --EL PERIODO DE LA FACTURA ESTA CERRADO
               -- SE DEBE ANULAR POR NOTA CREDITO
               -- se crea el encabezado de la Nota Credito
               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                        @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  
               SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
               INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                                 MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                                 CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                                 CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                                 IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                                 VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
               SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                      NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', 1, 
                      '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0
               -- se generan los detalles de la nota credito
               EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO
               IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
               BEGIN
                  UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
               END
               -- se aplica la nota credito
               EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME    
               UPDATE FTR SET RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC' WHERE N_FACTURA=@N_FACTURA   
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END               
            END                       
         END
         ELSE
         BEGIN
            IF @ESTACONTAB = 2  --ESTA CONTABILIZADA CON ERRORES
            BEGIN
               PRINT 'ESTA CONTABILIZADA CON ERRORES'   
               UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO   WHERE  N_FACTURA = @N_FACTURA
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END
               IF COALESCE(@FCOPA,0)<>1
               BEGIN
                  UPDATE HPRED SET FACTURADA = 0, N_FACTURA = NULL WHERE N_FACTURA = @N_FACTURA
               END
               ELSE
               BEGIN
                   UPDATE HPRED SET N_FACTURAH = NULL WHERE N_FACTURAH = @N_FACTURA
               END
               
               UPDATE HADMAUT SET N_FACTURA=NULL WHERE COALESCE(N_FACTURA,'')=@N_FACTURA

               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               -- el log debe mirarse donde apunta bdix revisar
               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                      @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
              
               DELETE MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               UPDATE MCPE SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                                REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                                RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
               SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                      REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                      RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
               FROM   MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               DELETE MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
            END
            ELSE
            BEGIN -- NO DEFINIDO
               PRINT 'NO DEFINIDO @ESTACONTAB <> 0, 1, 2'
            END
         END
      END
     
   END
--query 2
   IF @PROCEDENCIA = 'INVENTARIO'
   BEGIN      
      IF DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT') = 'COMER'  OR DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
      BEGIN
         IF EXISTS(SELECT * FROM FCXCD WHERE N_FACTURA=@N_FACTURA)
         BEGIN
            PRINT 'Borro de fcxcdv'
            SELECT @CNSCXC=CNSCXC FROM FCXCD WHERE N_FACTURA=@N_FACTURA
            DELETE FCXCDV WHERE N_FACTURA=@N_FACTURA
            DELETE FCXCD WHERE N_FACTURA=@N_FACTURA
            UPDATE FCXC SET ESTADO='Inactiva',CERRADA=1 WHERE CNSCXC=@CNSCXC
         END
         IF @ESTACONTAB = 1 --ESTA CONTABILIZADA
         BEGIN        
            PRINT 'ESTA CONTABILIZADA'
            --REVISAR EL PERIODO DE LA FACTURA
            IF @ESTADOPERFTR = 0  AND @CERRADOFTR=0 --ESTA ABIERTO ==> SE ANULA EL COMPROBANTE CONTABLE Y ACTUALIZA ESTADOS
            BEGIN
               UPDATE MCP SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO  WHERE  N_FACTURA = @N_FACTURA
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               -- el log debe mirarse donde apunta bdix revisar
               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                        @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL          
            END
            ELSE
            BEGIN 
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                        @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FNOTC',  @NVOCNSFNOT OUTPUT  
               SELECT @NVOCNSFNOT = @SEDE + 'C' + REPLACE(SPACE(8 - LEN(@NVOCNSFNOT))+LTRIM(RTRIM(@NVOCNSFNOT)),SPACE(1),0)
               INSERT INTO FNOT (CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, 
                                 MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, 
                                 CERRADA, ESTADO, USUARIOANU, USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, 
                                 CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO,
                                 IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO ,TIPOCONCEPTO, 
                                 VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS)
               SELECT @NVOCNSFNOT, 'C', @N_FACTURA, '', @IDTERCERO, @HOY, 0, @RAZONCAMBIO, 0, 0, 0 , 
                      NULL, 0, '01', @USUARIO, 0, 'O', '', '', NULL, NULL, 'FACTURA', '', 'F', 1, 
                      '', '', 0, '', '', 1, NULL, 'P', 100, NULL, 0
               -- se generan los detalles de la nota credito
               EXEC SPK_GENITEMS_NOTACR @NVOCNSFNOT, 'C', @USUARIO
               IF DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE')<>''
               BEGIN
                  UPDATE FNOT SET IDCONCEPTO=DBO.FNK_VALORVARIABLE('IDCONCEP_ANULAFTRCE'), CONCEPTO=2 WHERE CNSFNOT=@NVOCNSFNOT
               END
               -- se aplica la nota credito
               EXEC SPK_NOTASCXC @NVOCNSFNOT,'C', '', @SEDE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME    
               UPDATE FTR SET RAZONANULACION=@RAZONCAMBIO, TIPOANULACION='NC' WHERE N_FACTURA=@N_FACTURA  
               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END               
            END                       
         END
         ELSE
         BEGIN
            IF @ESTACONTAB = 2  --ESTA CONTABILIZADA CON ERRORES
            BEGIN
               PRINT 'ESTA CONTABILIZADA CON ERRORES'   
               UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO     WHERE  N_FACTURA = @N_FACTURA

               IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
               BEGIN
                  IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
                  BEGIN
                     SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
                     PRINT 'Retiro los recuados si Existe'
                     UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
                     DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
                     PRINT 'Retiro los Reconocimientos...'
                     UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
                     DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
                     UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
                     UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
                  END
               END

               EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               -- el log debe mirarse donde apunta bdix revisar
               INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
               SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                      @HOY, @SYS_COMPUTERNAME          
               INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
               SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL
              
               DELETE MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               UPDATE MCPE SET ANULADO = 1 WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               INSERT INTO MCP (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                                REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                                RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
               SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                      REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                      RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
               FROM   MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
               DELETE MCPE WHERE NROCOMPROBANTE = @NROCOMPROBANTE
            END
         END
         UPDATE FTR SET ESTADO = 'A', RAZONANULACION = @RAZONCAMBIO WHERE  N_FACTURA = @N_FACTURA

         IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'
         BEGIN
            IF EXISTS(SELECT * FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado'))
            BEGIN
               SELECT @RECO=RECO,@ESTADOPPTO=ESTADO,@CNSPPTO=CONSECUTIVO  FROM PTRECO WHERE N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND ESTADO IN('NoConfirmado','Confirmado')
               PRINT 'Retiro los recuados si Existe'
               UPDATE PTRECA SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='Confirmado'
               DELETE PTRECAD  WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO
               UPDATE PTRECA SET ESTADO='Anulado' WHERE RECO=@RECO AND CONSECUTIVO=@CNSPPTO AND ESTADO='NoConfirmado'
               PRINT 'Retiro los Reconocimientos...'
               UPDATE PTRECO SET ESTADO='NoConfirmado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='Confirmado'
               DELETE PTRECOD WHERE RECO=@RECO  AND CONSECUTIVO=@CNSPPTO
               UPDATE PTRECO SET VALOR=0,SALDO=0 WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'
               UPDATE PTRECO SET ESTADO='Anulado' WHERE RECO=@RECO AND N_FACTURA=@N_FACTURA AND CNSFTR=@CNSFTR AND CONSECUTIVO=@CNSPPTO  AND ESTADO='NoConfirmado'   
            END
         END

         SELECT  @CNSMOV=NOREFERENCIA  FROM FTR WHERE  N_FACTURA = @N_FACTURA

         UPDATE IMOV SET FACTURADA = 0, N_FACTURA=NULL,F_FACTURA=NULL,F_VENCE=NULL WHERE CNSMOV = @CNSMOV
      
         EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@LOG',  @NVOCONSEC OUTPUT  
         SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         
            -- el log debe mirarse donde apunta bdix revisar
         INSERT INTO USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName) 
         SELECT @NVOCONSEC, @COMPANIA, @N_FACTURA, 'ANULARFAC', 'PROCESS', @RAZONCAMBIO, @USUARIO, 
                  @HOY, @SYS_COMPUTERNAME          
         INSERT INTO USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
         SELECT @NVOCONSEC, 1, 'USU SOLICITA', @USUARIO2, NULL  
      END
   END 
   IF DBO.FNK_VALORVARIABLE('FTR_ENVIO_DIAN_AUTO')='SI' AND EXISTS(SELECT * FROM FTR WHERE N_fACTURA=@N_FACTURA AND COALESCE(FACTE,0)=2)
   BEGIN
      UPDATE FNOT SET FACTE=1 WHERE CNSFNOT=@NVOCNSFNOT
   END
   ELSE
   BEGIN
      UPDATE FNOT SET FACTE=0 WHERE CNSFNOT=@NVOCNSFNOT
   END
END


