use kpcem

SELECT * FROM FTR

use PUNIPSSAM

SELECT  * INTO #J FROM USUSU WHERE USUARIO='JJIMENEZ'


UPDATE #J SET USUARIO='PRUEBASJM',NOMBRE='Usuario de Pruebas'

DELETE USUSU WHERE USUARIO='PRUEBAS'

INSERT INTO USUSU
SELECT * FROM #J

UPDATE USUSU SET FECHACAMBIO=DBO.FNK_GETDATE(),FECHAVENCE=DBO.FNK_GETDATE()+180 WHERE USUARIO='PRUEBASJM'

SELECT  * FROM FTR WHERE N_FACTURA='JM0023'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FGLO_COL","METODO":"CRUD_FGLOD","PARAMETROS":{"DATOS":{"ITEM":2,"TIPO":"C","CODGLOSA":"AU0303","CODRPTA":"RE9501","VLRGLOSA":22000,"VLRACEPTADO":15000,"VLRRECUPERAR":7000,"DESCRIPCION":"CORRECCION ERRORES EN SALDOS","RESPUESTA":"La devolución no procede por haber sido generada fuera de los términos establecidos en el articulo 6 de la presente resolución","OBSERVACION":"La entidad responsable de pago emitió autorización directamente al profesional para la ejecución del procedimiento y la IPS está facturando a su nombre estos honorarios","IDSERVICIO":null,"VR_UNITARIO":22000,"CONCEPTO":"005","CANTIDAD":1,"PROCESO":"Borrar"}},"USUARIO":"JJIMENEZ"}'

SELECT  * FROM USCXS WHERE PREFIJO='@FNOTD'