

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

BEGIN TRAN
EXEC SPQ_JSON '{"MODELO":"FACT_MASI_COL","METODO":"MARCAR_AUT","PARAMETROS":{"IDAUT":"0202406166","CNSFACT":null},"USUARIO":"JJIMENEZ"}'

ROLLBACK

EXEC SPQ_JSON '{"MODELO":"FACT_MASI_COL","METODO":"MARCAR_AUT","PARAMETROS":{"IDAUT":"0202401997","CNSFACT":"0221741209"},"USUARIO":"JJIMENEZ"}'