use KCOC

UPDATE NPER SET CERRADO=1 WHERE CNSPAGO='SN202408M-1'

SELECT MunicipioCiudad = CASE WHEN COALESCE(CIU.HOMOLOGODIAN,'')='' THEN CIU.CIUDAD ELSE CIU.HOMOLOGODIAN END, DepartamentoEstado = COALESCE(DEP.COD_DIAN,DEP.DPTO), Pais = PAIS.CODISO
	,RazonSocial=DBO.FNK_LIMPIATEXTO(TER.RAZONSOCIAL,'A-Z0-9 .,-_/'), NIT=DBO.FNK_LIMPIATEXTO(NIT,'0-9A-Z') , DV=DV
	,Direccion=DBO.FNK_LIMPIATEXTO(TER.DIRECCION,'A-Z0-9 .,-_/')
FROM TER 
INNER JOIN CIU ON CIU.CIUDAD=TER.CIUDAD
INNER JOIN DEP ON DEP.DPTO=CIU.DPTO
INNER JOIN PAIS ON PAIS.IDPAIS=DEP.PAIS
WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')