SELECT * FROM FTRD WHERE EXISTS(SELECT * FROM MCPE WHERE FTRD.N_FACTURA=MCPE.NOREFERENCIA) AND NOITEM=99

UPDATE FTRD SET PAQUETE=1 WHERE EXISTS(SELECT * FROM MCPE WHERE FTRD.N_FACTURA=MCPE.NOREFERENCIA) AND NOITEM=99

SELECT  * FROM FTRD WHERE N_FACTURA='FV10467'

UPDATE  FTRD SET PREFIJO='AC' WHERE N_FACTURA='FV10467'

UPDATE USUSU SET IDDEPURAR=0 WHERE USUARIO='JJIMENEZ'
SELECT  * FROM NEMP WHERE DOCIDEMPLEADO='43972233'
SELECT  * FROM NOMIE WHERE NUMDOC='0100000369'

SELECT  * FROM NEMPV WHERE NUMDOC='0100000727' AND ITEM=4
UPDATE NEMPV SET DIASP=15 WHERE NUMDOC='0100000727' AND ITEM=5