
UPDATE USUSU SET FECHACAMBIO=DBO.FNK_GETDATE(),FECHAVENCE=DBO.FNK_GETDATE()+180 WHERE USUARIO='JIMENEZJ'
ALTER TABLE USUSU DISABLE TRIGGER TK1_PROCESOUSUSU

SELECT DBO.FNK_COLUMNAS_TABLAS('SALDOMES')