

SELECT * FROM FCXPDBCR WHERE CNSFCXP='02SR001911'

UPDATE FCXPDBCR SET ESTADODIAN=1 WHERE CNSFCXP='02SR001911' AND ITEM=1

-- RETEI -- ITEMS
   CODIGO
   DESCRIPCION
   CLASE 
-- RETUVE
   CODIGO
   DESCRIPCION
   UVTMIN
   UVTMAX
   TMARGIN
   UVTADI  
-- RETET -- TERCEROS
   IDTERCERO
   CODIRETE
   CLASE
   VALOR
-- RETEL -- LIQUIDACION
   CNSLIQRET
   PROCEDENCIA
   NOREFENCIA
   DEVENGOS--SUM CXP
   DEDUCCIONES
   RENTAEXEP
   BASERET
   VLRUVT
-- RETELD --LIQUIDETALLE
  CNSLIQRET
  CODIGO
  CLASE
  VALOR