
USE KSANIPERU
SELECT TOP 100 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC
<i class="fa-solid fa-envelope-open-text"></i>
<i class="fa-solid fa-person-military-pointing"></i>

SELECT  * FROM FTRE WHERE FTRN_FACTURA='B001-00003060'

SELECT FACTEP, * FROM FTR WHERE N_FACTURA='B001-00003060'

UPDATE FTR SET FACTE=3 WHERE N_FACTURA='UV19928'

SELECT * FROM SED

'En Cola'
'Con Errores'
'Procesando'


UPDATE FTRE SET NOTIFICADO=0,FECHA_NOTIFICADO=NULL WHERE FTRN_FACTURA='B001-00003060'

SELECT FTR.N_FACTURA,FTR.LINKFACTURA,FTR.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,FTR.F_FACTURA,FTR.F_VENCE,FTR.PROCEDENCIA,FTR.NOREFERENCIA,FTR.IDPLAN,FTR.VALORSERVICIOS,CASE COALESCE(COPAPROPIO,0) WHEN 1 THEN CP_VLR_COPAGOS ELSE VALORCOPAGO END VALORCOPAGO,VALORMODERADORA,FTR.VR_TOTAL,FTR.ESTADO,COALESCE(FTR.TIPOANULACION,'') NC,CASE COALESCE(FACTE,0) WHEN 0 THEN 'Sin Notificar' WHEN 1 THEN 'En Cola' WHEN 2 THEN 'Notificada' WHEN 3  THEN 'Con Errores' WHEN 4 THEN  'Procesando' END ESTDIAN,FTR.CONTABILIZADA,FTR.CNSFCT AS CNSFTR,FTR.VR_ABONOS AS ABONOS ,FTR.CAPITADA,CP_CONVENIO AS CONVENIO,COPAGOP = COALESCE(COPAPROPIO,0),VLRCOPAPRO = COALESCE(CP_VLR_COPAGOS,0),DESCUENTO,F_INICIAL = FECHACAP_INI,F_FINAL = FECHACAP_FIN,FTR.IDSEDE,CP_MES AS MES,MODALIDAD = CP_MODALIDAD,FTR.OBSERVACION,TIPOFINAN = TIPOFIN,PLN.DESCPLAN,USUARIOFACTURA,CP_VLR_SERVICIOS,CP_VLR_COPAGOS,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,AFI.EDAD,COALESCE(FTR.NROCOMPROBANTE,'')NROCOMPROBANTE,CASE WHEN EXISTS(SELECT 1 FROM FTRAUD WHERE FTRAUD.N_FACTURA = FTR.N_FACTURA) THEN 'Con Nota' ELSE 'Sin Nota' END AS ESTNOTAUD,FACTEP = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN CASE COALESCE(FACTEP,'') WHEN '' THEN 'Sin Notificar' WHEN 'ERROR' THEN 'Error Valida' WHEN 'Anulada' THEN 'Anulada' ELSE 'OK' END  ELSE '' END,SINCNT=COALESCE(SINCNT,0)  FROM [dbo].[FTR] INNER JOIN  TER ON FTR.IDTERCERO=TER.IDTERCERO  LEFT JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO LEFT JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN WHERE (FTR.N_FACTURA LIKE '%%%%' OR  TER.RAZONSOCIAL LIKE '%%%%') AND 1=1 AND CONVERT(DATE, FTR.F_FACTURA) >=  '2024-09-02' AND CONVERT(DATE, FTR.F_FACTURA) <= '2024-10-23'  ORDER BY  FTR.FECHAFAC DESC, FTR.N_FACTURA DESC  --OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 

 SELECT TER.IDTERCERO+';'+TER.RAZONSOCIAL+';'+''+';01;'+TER.RAZONSOCIAL FROM TER 
          WHERE  TER.NIT=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')