  {
      name: "ID",
      required: true,
      label: "ID",
      align: "left",
      field: (row) => row.ID,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "NIT",
      required: true,
      label: "NIT",
      align: "left",
      field: (row) => row. NIT,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "RAZONSOCIAL",
      required: true,
      label: "RAZONSOCIAL",
      align: "left",
      field: (row) => row. RAZONSOCIAL,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "CNSCXC",
      required: true,
      label: "CNSCXC",
      align: "left",
      field: (row) => row. CNSCXC,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "N_FACTURA",
      required: true,
      label: "N_FACTURA",
      align: "left",
      field: (row) => row. N_FACTURA,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "TIPO",
      required: true,
      label: "TIPO",
      align: "left",
      field: (row) => row. TIPO,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "SALDONETO",
      required: true,
      label: "SALDONETO",
      align: "left",
      field: (row) => row. SALDONETO,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "F_RECIBIDO",
      required: true,
      label: "F_RECIBIDO",
      align: "left",
      field: (row) => row. F_RECIBIDO,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "F_VENCE",
      required: true,
      label: "F_VENCE",
      align: "left",
      field: (row) => row. F_VENCE,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "DIASVENCE",
      required: true,
      label: "DIASVENCE",
      align: "left",
      field: (row) => row. DIASVENCE,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "PARTICULAR",
      required: true,
      label: "PARTICULAR",
      align: "left",
      field: (row) => row. PARTICULAR,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "RAD",
      required: true,
      label: "RAD",
      align: "left",
      field: (row) => row. RAD,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "NORADICADA",
      required: true,
      label: "NORADICADA",
      align: "left",
      field: (row) => row. NORADICADA,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "PORVENCER",
      required: true,
      label: "PORVENCER",
      align: "left",
      field: (row) => row. PORVENCER,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "D0_30",
      required: true,
      label: "D0_30",
      align: "left",
      field: (row) => row. D0_30,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "D31_60",
      required: true,
      label: "D31_60",
      align: "left",
      field: (row) => row. D31_60,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "D61_90",
      required: true,
      label: "D61_90",
      align: "left",
      field: (row) => row. D61_90,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "D91_120",
      required: true,
      label: "D91_120",
      align: "left",
      field: (row) => row. D91_120,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "D121_150",
      required: true,
      label: "D121_150",
      align: "left",
      field: (row) => row. D121_150,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "D151_180",
      required: true,
      label: "D151_180",
      align: "left",
      field: (row) => row. D151_180,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "D181_360",
      required: true,
      label: "D181_360",
      align: "left",
      field: (row) => row.  D181_360,
      format: (val) => `${val}`,
      sortable: false,
    },
  {
      name: "D361_MAS",
      required: true,
      label: "D361_MAS",
      align: "left",
      field: (row) => row. D361_MAS,
      format: (val) => `${val}`,
      sortable: false,
    },
