
BEGIN TRAN 
EXEC SPK_INSERT_TERDEAFI '0100000011', 'AFI'

rollback

      SELECT EMAIL = LTRIM(RTRIM(REPLACE(REPLACE(EMAIL,CHAR(13),''),CHAR(10),''))), 
      CELULAR = CELULAR, NOMBREAFI =LTRIM(TRIM(NOMBREAFI)) 
      FROM AFI WHERE IDAFILIADO = '0100000028'

SELECT * FROM TER WHERE NIT='70246444'


SELECT  * FROM KPAGE WHERE 

