SELECT TOP 10 * FROM API_LOG WHERE USUARIO='STORRES' ORDER BY ITEM DESC

UPDATE KPAGE SET ESTADO='SEND' WHERE IDKPAGE=8

SELECT * FROM KPAGE WHERE IDKPAGE=25

SELECT  IDKPAGE,KPAGE.CONSECUTIVO,KPAGE.PROCEDENCIA,DBO.FNK_FECHA_GRINGA(FECHAGEN)FECHAGEN,KPAGE.VALOR,KPAGE.ESTADO,KPAGE.USUCOBRA,KPAGE.RESPONSABLEPAGO,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,LINKPAGO,paymentOrderId,COALESCE(REF_PAGO,'')N_FACTURA   FROM [dbo].[KPAGE] LEFT JOIN  AFI ON KPAGE.RESPONSABLEPAGO=AFI.IDAFILIADO WHERE (CONSECUTIVO LIKE '%%%%' OR AFI.NOMBREAFI LIKE '%%%%' OR AFI.DOCIDAFILIADO LIKE '%%%%') AND 1=1 AND KPAGE.ESTADO='Todos'  ORDER BY [dbo].[KPAGE].[IDKPAGE] OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 

EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"F002-00000001"},"USUARIO":"STORRES"}'

SELECT * FROM BCT

EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"B001-00003002"},"USUARIO":"STORRES"}'

UPDATE FTR SET TIPOFIN='N' WHERE N_FACTURA='B001-00003002'

UPDATE FTR SET IDFORMATO='PE03'

SELECT PROCEDENCIA,NOREFERENCIA,IDSEDE, * FROM FTR WHERE N_FACTURA='B001-00003002'

SELECT  IDMEDICO, * FROM CIT WHERE  CONSECUTIVO='010000000006'

                  SELECT MED.NOMBRE,MES.DESCRIPCION,COALESCE(CIT.NOAUTORIZACION,'') NOAUTORIZACION,CONVERT(VARCHAR,FECHA,103)FECHAING,CONVERT(VARCHAR,FECHA,103)FECHAEGR,
                         CASE COALESCE(CIT.MODALIDAD,'Presencial') WHEN 'Virtual' THEN 'Virtual' ELSE 'Presencial' END MODALIDAD,
                         CASE WHEN COALESCE(COPA_VAR_PORC,0)=0 THEN '100%' ELSE CAST(COALESCE(COPA_VAR_PORC,0) AS VARCHAR(10))+'%' END COBERTURA
                  FROM CIT INNER JOIN MED ON CIT.IDMEDICO=MED.IDMEDICO
                           LEFT JOIN MES ON CASE WHEN COALESCE(CIT.IDEMEDICA,'')='' THEN MED.IDEMEDICA ELSE COALESCE(CIT.IDEMEDICA,'') END=MES.IDEMEDICA
                  WHERE CONSECUTIVO='010000000006'

SELECT  * FROM AFI

SELECT * FROM CIT WHERE N_FACTURA='F002-00000001'

SELECT * FROM VWK_CARGOS_HADMAUTCIT


SELECT * FROM CIT WHERE CONSECUTIVO='010000000294'

UPDATE CIT SET VALORTOTAL=120 WHERE CONSECUTIVO='010000000294'