SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC
EXEC SPQ_JSON '{"MODELO":"CARTERA_IMPRESION","METODO":"FGLOI","PARAMETROS":{"CNSGLOI":"0600000003"},"USUARIO":"JJIMENEZ"}'


SELECT CNSENTREGA,PROCESO,ENT_ENTREGA,A.NOMBRE,USUARIOENTREGA,DBO.FNK_FECHA_GRINGA(ENT.FECHAENTREGA)F_ENTREGA,ENT_RECIBE,B.NOMBRE,
USUARIORECIBE,DBO.FNK_FECHA_GRINGA(ENT.FECHARECIBE)F_RECIBE
FROM ENT LEFT JOIN FDEP A ON ENT.ENT_ENTREGA=A.IDDEP
         LEFT JOIN FDEP B ON ENT.ENT_RECIBE=B.IDDEP
WHERE PROCESO='GLOSAS'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC


SELECT   CNSENTREGA,PROCESO,ENT_ENTREGA,A.NOMBRE,USUARIOENTREGA,DBO.FNK_FECHA_GRINGA(ENT.FECHAENTREGA)F_ENTREGA,ENT_RECIBE,B.NOMBRE AS N_RECIBE,                         USUARIORECIBE,DBO.FNK_FECHA_GRINGA(ENT.FECHARECIBE)F_RECIBE,ESTADO,CASE COALESCE(ESTADO,0) WHERE 1 THEN 'Recibido' ELSE 'Sin Recibir' END ESTADOE       FROM [dbo].[ENT] LEFT JOIN FDEP A ON ENT.ENT_ENTREGA=A.IDDEP LEFT JOIN FDEP B ON ENT.ENT_RECIBE=B.IDDEP WHERE (USUARIOENTREGA  LIKE '%%%%' OR CNSENTREGA LIKE '%%%%') AND  ENT_ENTREGA=DBO.FNK_VALORVARIABLE('IDFDEPCARTERA')   ORDER BY  CNSENTREGA DESC  OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


SELECT CNSENTREGA,NODOCUMENTO,CASE ESTADO WHEN 0 THEN 'Sin Recibir' ELSE 'Recibido' END ESTADO,
       USUARIOVERIFICA AS USUARIO
FROM ENTD WHERE PROCESO='Glosas'


EXEC SPQ_JSON '{"MODELO":"FGLO_COL","METODO":"RECIBIR_GLOSA","PARAMETROS":{"CNSENTREGA":"0100000043"},"USUARIO":"JJIMENEZ"}'