

INSERT INTO USUSU
SELECT * FROM KSANIPERU.DBO.USUSU WHERE USUARIO='JJIMENEZ'

UPDATE USUSU SET FECHACAMBIO=DBO.FNK_GETDATE(),FECHAVENCE=DBO.FNK_GETDATE()+180 WHERE USUARIO='JJIMENEZ'

SELECT * FROM UBEQ WHERE ESTADO='Activo'

UPDATE USUSU SET  SYS_ComputerName='CAJERO_IZI' WHERE USUARIO='JJIMENEZ'


SELECT * FROM FTRAPILOG

EXEC SPK_JSON_FTR_PERU_INTERFAX 'B001-00000018'