IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_APLICA_NOTA_PPTO' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_APLICA_NOTA_PPTO 
END
GO
CREATE PROCEDURE DBO.SPK_APLICA_NOTA_PPTO  
@COMPANIA    VARCHAR(2), 
@CONSECUTIVO VARCHAR(20),
@RECO        VARCHAR(20),
@CNSNOTA     VARCHAR(20),
@ACCION      VARCHAR(10) 
WITH ENCRYPTION
AS  
DECLARE @MES INT
DECLARE @RUBRO VARCHAR(50)
DECLARE @CCOSTO VARCHAR(20) 
DECLARE @VALOR  DECIMAL(14,2) 
DECLARE @CLASE  VARCHAR(10)
DECLARE @N_FACTURA VARCHAR(20)
DECLARE @CONSEANTE VARCHAR(20)
DECLARE @CLASEN    VARCHAR(2)
BEGIN 
   PRINT 'INGRESO, CAPTURO DATOS '
   
   SELECT @MES=MONTH(FECHA),@CCOSTO=CCOSTO,@VALOR=VR_TOTAL,@RUBRO=COALESCE(RUBRON,''),@CLASE='Ingreso',@CLASEN=CLASE ,@N_FACTURA=N_FACTURA,
   @CONSEANTE=CONSECUTIVO
   FROM PTNOT WHERE COMPANIA=@COMPANIA 
   AND CONSECUTIVON=@CONSECUTIVO 
   AND RECO=@RECO 
   AND CNSNOTA=@CNSNOTA
   IF COALESCE(@RUBRO,'')=''
   BEGIN
      SELECT @RUBRO= CASE WHEN COALESCE(@RUBRO,'')='' THEN  RUBRO ELSE @RUBRO END,@CLASE=CLASE FROM  PTRECOD 
      WHERE CONSECUTIVO=@CONSECUTIVO 
      AND RECO=@RECO AND COMPANIA=@COMPANIA
   END
   IF @CLASEN='DB' OR COALESCE(@RUBRO,'')=''
   BEGIN
      RETURN
   END
   PRINT '@MES='+STR(@MES)
   PRINT '@CONSECUTIVO='+@CONSECUTIVO
   PRINT '@CLASE='+@CLASE
   PRINT '@CCOSTO='+@CCOSTO
   PRINT '@RUBRO='+@RUBRO
      
   IF @ACCION='CONF'
   BEGIN
      PRINT 'ACTUALIZO DISRECO'
      IF @CLASEN='CR'
      BEGIN
		   IF @MES = 1
			   UPDATE PTPTOI  SET DISRECO01 = COALESCE(DISRECO01,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 2
			   UPDATE PTPTOI   SET DISRECO02 = COALESCE(DISRECO02,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 3
			   UPDATE PTPTOI   SET DISRECO03 = COALESCE(DISRECO03,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 4
			   UPDATE PTPTOI   SET DISRECO04 = COALESCE(DISRECO04,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 5
			   UPDATE PTPTOI   SET DISRECO05 = COALESCE(DISRECO05,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 6
			   UPDATE PTPTOI   SET DISRECO06 = COALESCE(DISRECO06,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 7
			   UPDATE PTPTOI  SET DISRECO07 = COALESCE(DISRECO07,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 8
			   UPDATE PTPTOI  SET DISRECO08 = COALESCE(DISRECO08,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 9
			   UPDATE PTPTOI SET DISRECO09 = COALESCE(DISRECO09,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 10
			   UPDATE PTPTOI SET DISRECO10 = COALESCE(DISRECO10,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 11
			   UPDATE PTPTOI  SET DISRECO11 = COALESCE(DISRECO11,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 12
			   UPDATE PTPTOI SET DISRECO12 = COALESCE(DISRECO12,0) +@VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
      END
      ELSE
      BEGIN
		   IF @MES = 1
			   UPDATE PTPTOI  SET DISRECO01 = COALESCE(DISRECO01,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 2
			   UPDATE PTPTOI   SET DISRECO02 = COALESCE(DISRECO02,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 3
			   UPDATE PTPTOI   SET DISRECO03 = COALESCE(DISRECO03,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 4
			   UPDATE PTPTOI   SET DISRECO04 = COALESCE(DISRECO04,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 5
			   UPDATE PTPTOI   SET DISRECO05 = COALESCE(DISRECO05,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 6
			   UPDATE PTPTOI   SET DISRECO06 = COALESCE(DISRECO06,0) + @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 7
			   UPDATE PTPTOI  SET DISRECO07 = COALESCE(DISRECO07,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 8
			   UPDATE PTPTOI  SET DISRECO08 = COALESCE(DISRECO08,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 9
			   UPDATE PTPTOI SET DISRECO09 = COALESCE(DISRECO09,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 10
			   UPDATE PTPTOI SET DISRECO10 = COALESCE(DISRECO10,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 11
			   UPDATE PTPTOI  SET DISRECO11 = COALESCE(DISRECO11,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		   ELSE IF @MES = 12
			   UPDATE PTPTOI SET DISRECO12 = COALESCE(DISRECO12,0) - @VALOR
			   WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
      END
      PRINT 'ACTUALIZANDO ESTADOS'
      UPDATE PTNOT   SET ESTADO='Confirmado'  WHERE  COMPANIA=@COMPANIA AND CONSECUTIVON=@CONSECUTIVO AND  CNSNOTA=@CNSNOTA

      IF EXISTS(SELECT * FROM PTRECO INNER JOIN PTRECOD ON PTRECO.CONSECUTIVO=PTRECOD.CONSECUTIVO AND PTRECO.RECO=PTRECOD.RECO
      WHERE PTRECO.CONSECUTIVO=@CONSECUTIVO AND PTRECO.RECO=@RECO )
      BEGIN
         PRINT 'DISABLE TK'
         ALTER TABLE PTRECOD DISABLE TRIGGER TK_PTRECOD_UPDATE
         IF @CLASEN='CR'
         BEGIN
            PRINT 'AUMENTO LAS NOTAS CR'
            UPDATE PTRECOD SET SALDO=COALESCE(SALDO,0)-@VALOR,VLR_NOTAS=COALESCE(VLR_NOTAS,0)+@VALOR 
            WHERE COMPANIA=@COMPANIA 
            AND CONSECUTIVO=@CONSECUTIVO 
            AND RECO=@RECO 
            AND RUBRO=@RUBRO
         END
         ELSE
         BEGIN
            UPDATE PTRECOD SET SALDO=COALESCE(SALDO,0)+@VALOR,VLR_NOTAS=COALESCE(VLR_NOTAS,0)-@VALOR 
            WHERE COMPANIA=@COMPANIA 
            AND CONSECUTIVO=@CONSECUTIVO 
            AND RECO=@RECO 
            AND RUBRO=@RUBRO
         END   
         PRINT 'ENABLE TK'
         ALTER TABLE PTRECOD ENABLE TRIGGER TK_PTRECOD_UPDATE
         PRINT 'ACTUALIZO PETRECO'
         UPDATE PTRECO  SET SALDO=COALESCE(SALDO,0)-@VALOR 
         WHERE COMPANIA=@COMPANIA AND CONSECUTIVO=@CONSECUTIVO AND RECO=@RECO
      END
      ELSE
      BEGIN
         PRINT 'VIGENCIAS DIFERENTES'
      END
      PRINT 'ACTUALIZO FNOT'
      UPDATE FNOT SET ENPRESUPUESTO=1,CONSECUTIVOPPTO=@CONSECUTIVO,RECO=@RECO WHERE CNSFNOT=@CNSNOTA
   END
   ELSE
   BEGIN
		IF @MES = 1
			UPDATE PTPTOI SET DISRECO01 = COALESCE(DISRECO01,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 2
			UPDATE PTPTOI SET DISRECO02 = COALESCE(DISRECO02,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 3
			UPDATE PTPTOI  SET DISRECO03 = COALESCE(DISRECO03,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 4
			UPDATE PTPTOI   SET DISRECO04 =  COALESCE(DISRECO04,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 5
			UPDATE PTPTOI   SET DISRECO05 =  COALESCE(DISRECO05,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 6
			UPDATE PTPTOI   SET DISRECO06 =  COALESCE(DISRECO06,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 7
			UPDATE PTPTOI 	SET DISRECO07 =  COALESCE(DISRECO07,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 8
			UPDATE PTPTOI SET DISRECO08 =  COALESCE(DISRECO08,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 9
			UPDATE PTPTOI   SET DISRECO09 =  COALESCE(DISRECO09,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 10
			UPDATE PTPTOI  SET DISRECO10 =  COALESCE(DISRECO10,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 11
			UPDATE PTPTOI  SET DISRECO11 =  COALESCE(DISRECO11,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO
		ELSE IF @MES = 12
			UPDATE PTPTOI  SET DISRECO12 =  COALESCE(DISRECO12,0) - @VALOR
			WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO  


      IF EXISTS(SELECT * FROM PTRECO INNER JOIN PTRECOD ON PTRECO.CONSECUTIVO=PTRECOD.CONSECUTIVO AND PTRECO.RECO=PTRECOD.RECO
      WHERE PTRECO.N_FACTURA=@N_FACTURA AND PTRECO.CONSECUTIVO=@CONSECUTIVO AND PTRECO.RECO=@RECO )
      BEGIN
         PRINT 'DISABLE TK'
         ALTER TABLE PTRECOD DISABLE TRIGGER TK_PTRECOD_UPDATE
         IF @CLASEN='CR'
         BEGIN
            UPDATE PTRECOD SET SALDO=SALDO+@VALOR,VLR_NOTAS=COALESCE(VLR_NOTAS,0)-@VALOR 
            WHERE COMPANIA=@COMPANIA 
            AND CONSECUTIVO=@CONSECUTIVO 
            AND RECO=@RECO 
            AND RUBRO=@RUBRO
         END
         ELSE
         BEGIN
            UPDATE PTRECOD SET SALDO=SALDO-@VALOR,VLR_NOTAS=COALESCE(VLR_NOTAS,0)+@VALOR 
            WHERE COMPANIA=@COMPANIA 
            AND CONSECUTIVO=@CONSECUTIVO 
            AND RECO=@RECO 
            AND RUBRO=@RUBRO
         END   
         PRINT 'ENABLE TK'
         ALTER TABLE PTRECOD ENABLE TRIGGER TK_PTRECOD_UPDATE
         PRINT 'ACTUALIZO PETRECO'
         UPDATE PTRECO  SET SALDO=SALDO-@VALOR WHERE COMPANIA=@COMPANIA AND CONSECUTIVO=@CONSECUTIVO AND RECO=@RECO
      END
      ELSE
      BEGIN
         PRINT 'VIGENCIAS DIFERENTES'
      END
      PRINT 'ACTUALIZANDO ESTADOS'
      UPDATE PTNOT   SET ESTADO='Anulada'  WHERE  COMPANIA=@COMPANIA AND CONSECUTIVON=@CONSECUTIVO AND  CNSNOTA=@CNSNOTA
      PRINT 'ACTUALIZO FNOT'

      UPDATE FNOT SET ENPRESUPUESTO=0,CONSECUTIVOPPTO=NULL,RECO=NULL WHERE CNSFNOT=@CNSNOTA
                
   END
END



