
SELECT DBO.FNK_COLUMNAS_TABLAS('TSECRES')
SELECT * 
FROM TSECRES

tsecres

SELECT IDTURESUM TURESUM.PERIODO,TURESUM.USUARIO,USUSU.NOMBRE,TURESUM.TIPOPERSONAL,TURESUM.TIPO_USUARIO,HCUMP,HPEND,HNOV,HCUMP+HNOV AS TOTAL,TURESUM.ESTADO
FROM TURESUM INNER JOIN USUSU ON TURESUM.USUARIO= CASE WHEN TURESUM.TIPOPERSONAL='Asistencial' THEN USUSU.IDMEDICO ELSE USUSU.USUARIO END
WHERE TURESUM.USUARIO<>''
AND USUSU.ESTADO='Activo'


SELECT  * FROM TSECFU WHERE USUARIO='1067934355' AND FECHA>='01/07/2024' AND FECHA<'01/08/2024'

SELECT  * FROM USUSU WHERE IDMEDICO='1067934355'