

SELECT  * FROM ARCHIVOS

UPDATE USUSU SET IDFIRMA=1056 WHERE USUARIO='STORRES'
SELECT TOP 10 * FROM API_LOG WHERE USUARIO='STORRES' ORDER BY ITEM DESC

exec spq_json '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"CM1"},"USUARIO":"STORRES"}'