
SELECT * INTO #A  FROM TER WHERE IDTERCERO='02'

SELECT  * FROM #A

UPDATE #A SET IDTERCERO='04',RAZONSOCIAL='NOMINA INTERESES CESANTIAS',NIT='04'

INSERT INTO TER
SELECT * FROM #A

SELECT  * INTO #B FROM TEXCA WHERE IDTERCERO='02'

UPDATE #B SET IDTERCERO='04'

INSERT INTO TEXCA
SELECT * FROM #B
UPDATE USUSU SET IDDEPURAR=1-IDDEPURAR WHERE USUARIO='JJIMENEZ'

 A.CODNOMINA='03' AND EXISTS (SELECT 1 FROM NIEPED INNER JOIN NIEPE ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE WHERE NIEPED.NUMDOC=A.NUMDOC AND NIEPE.ANO='2024' AND NIEPE.MES>=1 AND NIEPE.MES<=12  AND NIEPED.CODCONCEPTO =(SELECT CODIGO FROM TGEN WHERE TABLA='NOMINA' AND CAMPO='ProvCesan'))