
SELECT * FROM #A WHERE EXISTS(SELECT * FROM MDX WHERE MDX.IDDX=#A.IDXX)


SELECT  * FROM MDX WHERE IDDX LIKE '%.%'


SELECT  * INTO #B FROM MDX WHERE IDDX='A00.9'

SELECT DBO.FNK_COLUMNAS_TABLAS('MDX')

INSERT INTO MDX(IDDX, DESCRIPCION, GRUPOENF, SEXO, EDADINICIAL, EDADFINAL, DIASINCAPACIDAD, ALTOCOSTO, IDCLASECUB, REPORTEOBLIGATORIO, COMENTARIOS, ATEP, IDGUIAAT, PERIODICIDAD, CATEGORIA, ESTADO,  CLASIF1, CLASIF2, VERSION, SGRUPO, POS, POSS, CLASE, CLASEPLANTILLA, PYP, DONDE, CONFIDENCIAL, REPORTA, ACTUALIZADO, TEDAD, RUTA)
SELECT #A.IDXX,UPPER(#A.DESCRIPCION), GRUPOENF, SEXO, EDADINICIAL, EDADFINAL, DIASINCAPACIDAD, ALTOCOSTO, IDCLASECUB, REPORTEOBLIGATORIO, COMENTARIOS, ATEP, IDGUIAAT, PERIODICIDAD, CATEGORIA, ESTADO,  CLASIF1, CLASIF2, VERSION, SGRUPO, POS, POSS, CLASE, CLASEPLANTILLA, PYP, DONDE, CONFIDENCIAL, REPORTA, ACTUALIZADO, TEDAD, RUTA
FROM #A,#B

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='STORRES' ORDER BY ITEM DESC


EXEC SPQ_JSON '{"MODELO":"CIT_COL_2","METODO":"DISPONIBILIDAD","PARAMETROS":{"DIA":"2024-11-18","ESPECIALIDAD":"013","MODALIDAD":"","IDSEDE":"01","DISPONIBILIDAD":"Todos","IDTERCERO":null},"USUARIO":"STORRES"}' 