IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_RIPS_CXC_ASIS_CAP' AND XTYPE='P')
BEGIN
   DROP PROC DBO.SPK_RIPS_CXC_ASIS_CAP
END

GO
CREATE PROCEDURE DBO.SPK_RIPS_CXC_ASIS_CAP
@ENVIO     VARCHAR(20),
@IDTERCERO VARCHAR(20),
@CODPREST  VARCHAR(20),
@DPRRS     VARCHAR(120),
@DPRNIT    VARCHAR(20)
WITH ENCRYPTION
AS 
DECLARE @FECHAINICIAL DATETIME
DECLARE @FECHAFINAL   DATETIME
DECLARE @IDPLAN       VARCHAR(6)
DECLARE @N_FACTURA    VARCHAR(20)
DECLARE @CNSFCT       VARCHAR(20)
DECLARE @CNS          INT
-- AP
DECLARE @NUMFACTURA         VARCHAR(20)
DECLARE @TIPO_DOC           VARCHAR(2)
DECLARE @IDUSUARIO          VARCHAR(20)
DECLARE @FECHAPROCEDIMIENTO DATETIME
DECLARE @NUMAUT             VARCHAR(15)
DECLARE @IDPROCEDIMIENTO    VARCHAR(8)
DECLARE @AMBITO             VARCHAR(1)
DECLARE @FINPROCEDIMIENTO   VARCHAR(1)
DECLARE @PERSONALA          VARCHAR(1)
DECLARE @DXPPAL             VARCHAR(4)
DECLARE @DXREL              VARCHAR(4)
DECLARE @COMPLICACION       VARCHAR(4)
DECLARE @ACTOQ              VARCHAR(1)
DECLARE @VALORPROCED        DECIMAL(14,2)
DECLARE @NOPRESTACION       VARCHAR(16)
DECLARE @NOITEM             VARCHAR(2)
DECLARE @CANTIDAD           INT
DECLARE @CANT               INT
DECLARE @TIPOBUSQUEDA       VARCHAR(10)
DECLARE @IDTARIFA           VARCHAR(5)
DECLARE @CNSFTR             VARCHAR(40)
DECLARE @N_CUOTA            INT
DECLARE @IDSERVICIO         VARCHAR(20)
DECLARE @IDDX               VARCHAR(10)
DECLARE @ESTADO             VARCHAR(2)
DECLARE @CODEVAL            VARCHAR(20)
DECLARE @PGP                SMALLINT
DECLARE @PGPX                SMALLINT
DECLARE @FORMATORIPS        VARCHAR(20)
DECLARE @RIPS_PROCESOAP     VARCHAR(20)
DECLARE @RIPS_COPAGOS       VARCHAR(20)
DECLARE @VALOR              DECIMAL(14,2)
DECLARE @IPS VARCHAR(20)
DECLARE @RRIPS_AP_TODOSCONDX VARCHAR(20)
DECLARE @RIPS_AGRUPADOS     VARCHAR(20)
BEGIN 

	SELECT @ESTADO = ESTADO FROM RIPS WHERE ENVIO = @ENVIO AND IDTERCERO=@IDTERCERO
	--IF @ESTADO <> '01'
	--BEGIN
	--   RAISERROR('ENVIO EN ESTADO DIFERENTE DE 01 ', 16,1)
	--   RETURN
	--END
	SELECT @IPS =   CASE  DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO') WHEN '839000145' THEN 'ASOCA' ELSE '' END 
  
	SELECT TOP 1 @N_FACTURA = N_FACTURA FROM RIPSD WHERE ENVIO = @ENVIO AND IDTERCERO=@IDTERCERO AND PROCEDENCIA IN ('AUT','HADM','CI')

	SELECT @IDTERCERO=(CASE WHEN @IDTERCERO IS NULL THEN IDTERCERO ELSE @IDTERCERO END), 
		@FECHAINICIAL = FECHAINICIAL, @FECHAFINAL = FECHAFINAL+1, @IDPLAN = IDPLAN
	FROM   RIPS 
	WHERE  ENVIO = @ENVIO --AND IDTERCERO=@IDTERCERO
   
	IF COALESCE(@IDPLAN,'')=''
	BEGIN
	SELECT @IDPLAN=IDPLAN FROM FTR WHERE N_FACTURA=@N_FACTURA
	END

	IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(PGP,0)=1) 
	BEGIN
		SELECT @PGP=1
		SELECT @PGPX =1
		IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(PGP,0)=1 AND COALESCE(RIPSPGP,'Evento')<>'Evento')
		BEGIN
			SELECT @PGP=0
		END
	END
	ELSE
	BEGIN
		SELECT @PGP=0
	END


	SELECT @CNSFCT = CNSFCT FROM FTR WHERE N_FACTURA = @N_FACTURA
	SELECT @FORMATORIPS=TIPORIPS FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN

	PRINT 'IDTERCERO === '+@IDTERCERO
	PRINT 'IDPLAN === '+@IDPLAN
	PRINT 'TIPORIPS === '+@FORMATORIPS

	PRINT 'CREANDO US QX'
	SET @RRIPS_AP_TODOSCONDX = COALESCE(DBO.FNK_VALORVARIABLE('RRIPS_AP_TODOSCONDX'),'NO')
	SET @RIPS_AGRUPADOS      = DBO.FNK_VALORVARIABLE('RIPS_AGRUPADOS')
   
	SET @RIPS_COPAGOS        =  DBO.FNK_VALORVARIABLE('RIPS_COPAGOS')
   
	IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(RIPSAPQX,0)=1)
		SET @RIPS_PROCESOAP='SI'
	ELSE
		SET @RIPS_PROCESOAP ='NO'

	IF (SELECT COALESCE(RIPS_VALOR_CX,'') FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN)='AP'
		SET @RIPS_PROCESOAP='SI'
	IF (SELECT COALESCE(RIPS_VALOR_CX,'') FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN)='AT'
		SET @RIPS_PROCESOAP='NO'

	INSERT INTO RRIPS_US ( ENVIO, IDTERCERO, TIPO_DOC, IDUSUARIO, CODENTIDADM, TIPOUSUARIO, PAPELLIDO, 
							SAPELLIDO, PNOMBRE, SNOMBRE, EDAD, UNMEDIDA, SEXO, DEPHABITUAL, 
							MUNHABITUAL, ZONAHABITUAL, TIPOAFILIADO )
	SELECT DISTINCT @ENVIO, @IDTERCERO, LEFT(AFI.TIPO_DOC,2) AS TIPO_DOC, AFI.DOCIDAFILIADO, LEFT(TER.IDALTERNA2,6), 
			MAX( CASE PLN.TIPOSISTEMA WHEN 'Contributivo' THEN '1' 
								WHEN 'Subsidiado'   THEN '2'
								WHEN 'Vinculado'    THEN '3'
								WHEN 'Particular'   THEN '4'
								WHEN 'Otro'         THEN '5'
								WHEN 'Prepagado'    THEN '5'
								WHEN 'Desplazado Vinc'   THEN '8'
								WHEN 'Desplazado Reg Cont' THEN '6'
								WHEN 'Desplazado Reg Subs' THEN '7'
			END), LEFT(REPLACE(AFI.PAPELLIDO,',',' '),30),  LEFT(REPLACE(AFI.SAPELLIDO,',',' '),30), LEFT(REPLACE(AFI.PNOMBRE,',',' '),20),  
			LEFT(REPLACE(AFI.SNOMBRE,',',' '),20),  
					-- Se cambia comando DATEDIFF por que estaba aproximando la edad STORRES
			CASE  
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=0 THEN 1  
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=30 THEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=365 THEN 
					CASE	WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'M')  = 12 THEN 1
							ELSE DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'M')
					END
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=54750 THEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'A')
			END,
			CASE
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=30 THEN '3'
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=365 THEN
					CASE	WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'M') = 12 THEN '1'
							ELSE '2'
					END
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=54750 THEN '1'
			END,
			-- Se cambia comando funcion FNK_EDAD_ARS para sacar edad correcta STORRES
			CASE WHEN AFI.SEXO ='FEMENINO' THEN 'F' ELSE 'M' END,  
			LEFT(AFI.CIUDAD,2),  
			SUBSTRING(AFI.CIUDAD,3,3),  
			CASE WHEN AFI.ZONA = 'R' THEN 'R' ELSE 'U' END,LEFT( AFI.TIPOAFILIADO,1)
	FROM   RIPSD INNER JOIN HPRE  ON HPRE.NOADMISION    = RIPSD.NOADMISION
				INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
				INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
					LEFT JOIN TER   ON HADM.IDTERCERO     = TER.IDTERCERO 
					LEFT JOIN AFI   ON HADM.IDAFILIADO    = AFI.IDAFILIADO
					LEFT JOIN PLN   ON HPRED.IDPLAN       = PLN.IDPLAN
	WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	AND    RIPSD.PROCEDENCIA = 'HADM'
	AND    COALESCE(HPRED.NOCOBRABLE,0)=0
	AND  COALESCE(HPRED.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRED.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 
	AND    AFI.DOCIDAFILIADO NOT IN (SELECT IDUSUARIO FROM RRIPS_US WHERE ENVIO = @ENVIO )  
	-- SE CREA AGRUPACION PARA QUE NO SALGA REPETIDO LOS USUARIOS POR EL TIPO DE SISTEMA 
	GROUP BY LEFT(AFI.TIPO_DOC,2) , AFI.DOCIDAFILIADO, LEFT(TER.IDALTERNA2,6), LEFT(REPLACE(AFI.PAPELLIDO,',',' '),30),  LEFT(REPLACE(AFI.SAPELLIDO,',',' '),30), LEFT(REPLACE(AFI.PNOMBRE,',',' '),20),  
			LEFT(REPLACE(AFI.SNOMBRE,',',' '),20),  
			CASE  
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=0 THEN 1  
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=30 THEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=365 THEN 
					CASE	WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'M')  = 12 THEN 1
							ELSE DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'M')
					END
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=54750 THEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'A')
			END,
			CASE
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=30 THEN '3'
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=365 THEN
					CASE	WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'M') = 12 THEN '1'
							ELSE '2'
					END
				WHEN DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, GETDATE(), 'D')<=54750 THEN '1'
			END,  
			CASE WHEN AFI.SEXO ='FEMENINO' THEN 'F' ELSE 'M' END,  
			LEFT(AFI.CIUDAD,2),  
			SUBSTRING(AFI.CIUDAD,3,3),  
			CASE WHEN AFI.ZONA = 'R' THEN 'R' ELSE 'U' END, AFI.TIPOAFILIADO
	PRINT 'SE CREARON EN US QX ' + CONVERT(VARCHAR,@@ROWCOUNT) + ' ITEMS'
  
	PRINT 'CREANDO AC QX'
	INSERT INTO RRIPS_AC ( ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, FECHACONSULTA, NUMAUT, IDCONSULTA,
							FINCONSULTA, CAUSAEXT, IDDXPPAL, IDDXREL1, IDDXREL2, IDDXREL3, TIPODX, VALORCONSULTA,
							VALORCUOTAM, VALORNETO, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, CANTIDAD,
							PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL)
	SELECT @ENVIO, @IDTERCERO, RIPSD.N_FACTURA, @CODPREST, LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, 
			CASE WHEN HPRE.FECHA < HADM.FECHA THEN HADM.FECHA
				WHEN HPRE.FECHA > HADM.FECHAALTA THEN HADM.FECHAALTA
				ELSE HPRE.FECHA
			END,  
			LEFT(HADM.NOAUTORIZACION,15), SER.IDALTERNA,
			CASE ISNULL(HPRE.FINALIDAD,'') WHEN '' THEN '10' ELSE HPRE.FINALIDAD END, HADM.CAUSAEXTERNA, UPPER(HADM.DXINGRESO),
			UPPER(HADM.DXSALIDA1), UPPER(HADM.DXSALIDA2), UPPER(HADM.DXSALIDA3), '1', HPRED.VALOR, HPRED.VALORCOPAGO, 
			CASE ISNULL((HPRED.VALOR * HPRED.CANTIDAD),0)WHEN 0 THEN (HPRED.VALOR * HPRED.CANTIDAD) - HPRED.VALORCOPAGO ELSE (HPRED.VALOR * HPRED.CANTIDAD) END, 
			HPRED.NOPRESTACION, HPRED.NOITEM, ISNULL(@CNSFCT,'EXTERNO'), 1, HPRED.CANTIDAD, 
			'QX', UPPER(HADM.DXINGRESO), SER.IDSERVICIO, 'CODEVAL'
	FROM   RIPSD INNER JOIN HPRE  ON HPRE.NOADMISION    = RIPSD.NOADMISION
				INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
				INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
					LEFT JOIN SER   ON HPRED.IDSERVICIO   = SER.IDSERVICIO
					LEFT JOIN AFI   ON HADM.IDAFILIADO    = AFI.IDAFILIADO
					LEFT JOIN PRE   ON SER.PREFIJO        = PRE.PREFIJO
					LEFT JOIN AFU   ON HPRE.IDAREA        = AFU.IDAREA
					LEFT JOIN QXPCXD  ON HPRED.CONSECUTIVOCX = QXPCXD.CONSECUTIVO AND HPRED.ITEMCIRUGIA = QXPCXD.ITEM
					LEFT JOIN TGEN    ON QXPCXD.TIPOCIRUGIA = TGEN.CODIGO AND TGEN.CAMPO = 'TIPOCIRUGIA' AND TGEN.TABLA ='General'
					LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS
	WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	---SE COLOCA FECHA PARA QUE TRAIGA SOLAMENTE LO PRODUCIDO EN EL MES 
	AND HPRE.FECHA >=@FECHAINICIAL AND  HPRE.FECHA<= @FECHAFINAL
	AND    RIPSD.PROCEDENCIA = 'HADM'
	AND    RIPS_CP.ARCHIVO   = 'AC' 
	AND    COALESCE(HPRED.NOCOBRABLE,0)=0
		AND  COALESCE(HPRED.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRED.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 

	PRINT 'SE CREARON EN AC QX ' + CONVERT(VARCHAR,@@ROWCOUNT) + ' ITEMS'

	DECLARE @NOADMISIONAP VARCHAR(20)
	PRINT 'CREANDO AP QX'
	DECLARE AP_CURSOR CURSOR FOR  
	SELECT LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, 
			CASE WHEN HPRE.FECHA < HADM.FECHA THEN HADM.FECHA
				WHEN HPRE.FECHA > HADM.FECHAALTA THEN HADM.FECHAALTA
				ELSE HPRE.FECHA
			END, RIPSD.N_FACTURA,
			LEFT(HADM.NOAUTORIZACION,15), SER.IDALTERNA,
			AFU.AMBITO, CASE ISNULL(HPRE.FINALIDAD,'') WHEN '' THEN PRE.FINALIDAD ELSE HPRE.FINALIDAD END,
			CASE COALESCE(SER.MPERSONAL_AT,0) WHEN 1 THEN HPRE.PERSONAL_AT ELSE '' END, 
			CASE  WHEN SER.CODIGORIPS= DBO.FnK_ValorVariable('IDPROTERQXRIPS') THEN UPPER(HADM.DXINGRESO)
				WHEN @IPS='ASOCA' THEN  UPPER(HADM.DXINGRESO) WHEN  @RRIPS_AP_TODOSCONDX='SI' THEN  UPPER(HADM.DXINGRESO) ELSE '' END,
			CASE WHEN SER.CODIGORIPS = DBO.FnK_ValorVariable('IDPROTERQXRIPS') OR @RRIPS_AP_TODOSCONDX='SI' THEN UPPER(HADM.DXSALIDA1) ELSE '' END,
			CASE WHEN SER.CODIGORIPS = DBO.FnK_ValorVariable('IDPROTERQXRIPS') OR @RRIPS_AP_TODOSCONDX='SI' THEN UPPER(HADM.COMPLICACION) ELSE '' END, 
			CASE WHEN SER.CODIGORIPS = DBO.FnK_ValorVariable('IDPROTERQXRIPS')  THEN CASE ISNULL(TGEN.DATO1,'') 
																				WHEN ''  THEN CASE WHEN @RRIPS_AP_TODOSCONDX='SI' THEN '1' ELSE '' END 
																				ELSE TGEN.DATO1
																				END
																			ELSE '' 
			END,
			CAST(ROUND(HPRED.VALOR,0)AS INT)-CAST (ROUND ( (COALESCE(HPRED.VALORCOPAGO,0)/ HPRED.CANTIDAD),0)AS INT )
			, HPRED.NOPRESTACION, HPRED.NOITEM,CAST (ROUND (  HPRED.CANTIDAD,0)AS INT )CANTIDAD , 
			ISNULL(@CNSFCT,'EXTERNO'), 1, SER.IDSERVICIO, HADM.DXINGRESO, 'CODEVAL',HPRE.NOADMISION
	FROM   RIPSD INNER JOIN HPRE  ON HPRE.NOADMISION    = RIPSD.NOADMISION
				INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
				INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
					LEFT JOIN SER     ON HPRED.IDSERVICIO    = SER.IDSERVICIO
					LEFT JOIN AFI     ON HADM.IDAFILIADO     = AFI.IDAFILIADO
					LEFT JOIN PRE     ON SER.PREFIJO         = PRE.PREFIJO
					LEFT JOIN AFU     ON HPRE.IDAREA         = AFU.IDAREA
					LEFT JOIN QXPCXD  ON HPRED.CONSECUTIVOCX = QXPCXD.CONSECUTIVO AND HPRED.ITEMCIRUGIA = QXPCXD.ITEM
					LEFT JOIN TGEN    ON QXPCXD.TIPOCIRUGIA  = TGEN.CODIGO AND TGEN.CAMPO = 'TIPOCIRUGIA' AND TGEN.TABLA ='General'
					LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS
	WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	---SE COLOCA FECHA PARA QUE TRAIGA SOLAMENTE LO PRODUCIDO EN EL MES 
	AND  HPRE.FECHA >=@FECHAINICIAL AND  HPRE.FECHA<= @FECHAFINAL
	AND    RIPSD.PROCEDENCIA = 'HADM'
	AND    RIPS_CP.ARCHIVO   = 'AP'
		AND  COALESCE(HPRE.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRE.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 

	AND ISNULL(HPRED.CANTIDAD,0)>0
	AND    COALESCE(HPRED.NOCOBRABLE,0)=0
	AND  COALESCE(HPRED.IDCIRUGIA,'') =  CASE WHEN EXISTS(SELECT * FROM QXPCXD WHERE  HPRED.CONSECUTIVOCX = QXPCXD.CONSECUTIVO AND HPRED.ITEMCIRUGIA = QXPCXD.ITEM)
												THEN CASE WHEN @RIPS_PROCESOAP='SI' 
															THEN '' 
															ELSE CASE WHEN HPRED.TIPOSERCIRUGIA='PAQUETE' THEN COALESCE(HPRED.IDCIRUGIA,'') ELSE COALESCE(HPRED.IDCIRUGIA,'XXX') END END 
											ELSE '' END 
	SET @CNS = 0
	OPEN AP_CURSOR  
	FETCH NEXT FROM AP_CURSOR  
	INTO @TIPO_DOC, @IDUSUARIO, @FECHAPROCEDIMIENTO, @N_FACTURA, @NUMAUT, @IDPROCEDIMIENTO,
		@AMBITO, @FINPROCEDIMIENTO, @PERSONALA, @DXPPAL, @DXREL, @COMPLICACION, @ACTOQ, @VALORPROCED, 
		@NOPRESTACION, @NOITEM, @CANTIDAD, @CNSFTR, @N_CUOTA, @IDSERVICIO, @IDDX, @CODEVAL,@NOADMISIONAP
	WHILE @@FETCH_STATUS = 0  
	BEGIN
		SET @CNS = @CNS + 1
		SELECT @CANT = 1
		WHILE @CANT <= @CANTIDAD
		BEGIN
			IF @RRIPS_AP_TODOSCONDX='SI' 
			BEGIN
			IF COALESCE(@DXPPAL,'')=''
			BEGIN
				SELECT @DXPPAL=IDDX FROM HCA WHERE NOADMISION=@NOADMISIONAP AND CLASE='HC' AND COALESCE(IDDX,'')<>'' AND PROCEDENCIA='QX'
			END
			IF COALESCE(@DXREL,'')=''
			BEGIN
				SELECT @DXREL=@DXPPAL
				END
				IF COALESCE(@IDDX,'')=''
				BEGIN
				SELECT @IDDX=@DXPPAL
				END
				IF COALESCE(@ACTOQ,'')=''
				BEGIN
				SELECT @ACTOQ='1'
				END
				IF COALESCE(@PERSONALA,'')=''
				BEGIN
				SELECT @PERSONALA='1'
				END
			END
			INSERT INTO RRIPS_AP (ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, FECHAPROCEDIMIENTO, 
								NUMAUT, IDPROCEDIMIENTO,
								AMBITO, FINPROCEDIMIENTO, PERSONALA, DXPPAL, DXREL, COMPLICACION, 
								ACTOQ, VALORPROCED, NOPRESTACION, 
								NOITEM, CNSFTR, N_CUOTA, CANTIDAD, PROCEDENCIA, IDDX, 
								IDSERVICIO, CODEVAL ) 
			SELECT @ENVIO, @IDTERCERO, @N_FACTURA, @CODPREST, @TIPO_DOC, @IDUSUARIO, @FECHAPROCEDIMIENTO, @NUMAUT, @IDPROCEDIMIENTO,
				@AMBITO, @FINPROCEDIMIENTO, @PERSONALA, @DXPPAL, @DXREL, @COMPLICACION, @ACTOQ, @VALORPROCED, 
				@NOPRESTACION, @NOITEM, @CNSFTR, @N_CUOTA, 1, 'QX', @IDDX, @IDSERVICIO, @CODEVAL
			SELECT @CANT = @CANT + 1
		END         
		FETCH NEXT FROM AP_CURSOR  
		INTO @TIPO_DOC, @IDUSUARIO, @FECHAPROCEDIMIENTO, @N_FACTURA, @NUMAUT, @IDPROCEDIMIENTO,
			@AMBITO, @FINPROCEDIMIENTO, @PERSONALA, @DXPPAL, @DXREL, @COMPLICACION, @ACTOQ, @VALORPROCED, 
			@NOPRESTACION, @NOITEM, @CANTIDAD, @CNSFTR, @N_CUOTA, @IDSERVICIO, @IDDX, @CODEVAL,@NOADMISIONAP
	END       
	CLOSE AP_CURSOR  
	DEALLOCATE AP_CURSOR
	PRINT 'SE CREARON EN AP QX ' + CONVERT(VARCHAR,@CNS) + ' ITEMS'

	PRINT 'CREANDO AM QX'
	INSERT INTO RRIPS_AM ( ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, NUMAUT, IDMEDICAMENTO, TIPOMEDICAMENTO, NOMBREMEDI,
							FORMAFARMA, CONCMEDI, UMEDMEDI, NUMUNIDADES, VALORUNIMEDI, VALORTOTMEDI, NOPRESTACION, NOITEM, CNSFTR, 
							N_CUOTA, PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL, FECHAMEDICAMENTO )
	SELECT @ENVIO, @IDTERCERO, RIPSD.N_FACTURA, @CODPREST, LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, LEFT(HADM.NOAUTORIZACION,15), 
			CASE WHEN SER.CODIGORIPS = DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN SER.IDALTERNA
				WHEN  SER.PREFIJO = DBO.FNK_VALORVARIABLE('PREFIJOMEDNOPOS') AND DBO.FNK_VALORVARIABLE('NOPOSRIPS')='SI' THEN SER.IDALTERNA  ELSE ''  END,
			CASE SER.CODIGORIPS WHEN DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN '1' ELSE '2' END,
			LEFT(SER.DESCSERVICIO,30),
			CASE SER.CODIGORIPS WHEN  DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN CASE WHEN DBO.FNK_VALORVARIABLE('RIPS_AM_DATOSMEDPOS')='SI' THEN ISNULL(LEFT(IFFA.DESCRIPCION,20),'') ELSE '' END  ELSE ISNULL(LEFT(IFFA.DESCRIPCION,20),'') END,
			CASE SER.CODIGORIPS WHEN  DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN CASE WHEN DBO.FNK_VALORVARIABLE('RIPS_AM_DATOSMEDPOS')='SI' THEN ISNULL(LEFT(ICCN.DESCRIPCION,20),'') ELSE '' END  ELSE ISNULL(LEFT(ICCN.DESCRIPCION,20),'') END,
			CASE SER.CODIGORIPS WHEN  DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN CASE WHEN DBO.FNK_VALORVARIABLE('RIPS_AM_DATOSMEDPOS')='SI' THEN ISNULL(LEFT(IUNI.DESCRIPCION,20),'') ELSE '' END  ELSE ISNULL(LEFT(IUNI.DESCRIPCION,20),'') END,
			SUM(CAST (HPRED.CANTIDAD AS INT)),SUM(HPRED.VALOR),SUM(CAST((HPRED.VALOR * HPRED.CANTIDAD) - HPRED.VALORCOPAGO AS DECIMAL(14,2))), 
			HPRED.NOPRESTACION, HPRED.NOITEM, ISNULL(@CNSFCT,'EXTERNO'), 1, 'QX', UPPER(HADM.DXINGRESO), 
			SER.IDSERVICIO, 'CODEVAL',MIN(HPRE.FECHA)
	FROM   RIPSD INNER JOIN HPRE  ON HPRE.NOADMISION    = RIPSD.NOADMISION
				INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
				INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
					LEFT JOIN SER   ON HPRED.IDSERVICIO   = SER.IDSERVICIO
					LEFT JOIN AFI     ON HADM.IDAFILIADO     = AFI.IDAFILIADO
					LEFT JOIN PRE     ON SER.PREFIJO         = PRE.PREFIJO
					LEFT JOIN AFU     ON HPRE.IDAREA         = AFU.IDAREA
					LEFT JOIN IART    ON SER.IDARTICULO      = IART.IDARTICULO
					LEFT JOIN IUNI    ON IART.IDUNIDAD       = IUNI.IDUNIDAD
					LEFT JOIN ICCN    ON IART.IDCONCENTRA    = ICCN.IDCONCENTRA
					LEFT JOIN IFFA    ON IART.IDFORFARM      = IFFA.IDFORFARM
					LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS
	WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	---SE COLOCA FECHA PARA QUE TRAIGA SOLAMENTE LO PRODUCIDO EN EL MES 
	AND  HPRE.FECHA >=@FECHAINICIAL AND  HPRE.FECHA<= @FECHAFINAL
	AND    RIPSD.PROCEDENCIA = 'HADM'
	AND    RIPS_CP.ARCHIVO   = 'AM' 
	AND    COALESCE(HPRED.NOCOBRABLE,0)=0
		AND  COALESCE(HPRE.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRE.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 
	GROUP BY RIPSD.N_FACTURA,  LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, LEFT(HADM.NOAUTORIZACION,15), 
			CASE WHEN SER.CODIGORIPS = DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN SER.IDALTERNA
				WHEN  SER.PREFIJO = DBO.FNK_VALORVARIABLE('PREFIJOMEDNOPOS') AND DBO.FNK_VALORVARIABLE('NOPOSRIPS')='SI' THEN SER.IDALTERNA  ELSE ''  END,
			CASE SER.CODIGORIPS WHEN DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN '1' ELSE '2' END,
			LEFT(SER.DESCSERVICIO,30),
			CASE SER.CODIGORIPS WHEN  DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN CASE WHEN DBO.FNK_VALORVARIABLE('RIPS_AM_DATOSMEDPOS')='SI' THEN ISNULL(LEFT(IFFA.DESCRIPCION,20),'') ELSE '' END  ELSE ISNULL(LEFT(IFFA.DESCRIPCION,20),'') END,
			CASE SER.CODIGORIPS WHEN  DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN CASE WHEN DBO.FNK_VALORVARIABLE('RIPS_AM_DATOSMEDPOS')='SI' THEN ISNULL(LEFT(ICCN.DESCRIPCION,20),'') ELSE '' END  ELSE ISNULL(LEFT(ICCN.DESCRIPCION,20),'') END,
			CASE SER.CODIGORIPS WHEN  DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS') THEN CASE WHEN DBO.FNK_VALORVARIABLE('RIPS_AM_DATOSMEDPOS')='SI' THEN ISNULL(LEFT(IUNI.DESCRIPCION,20),'') ELSE '' END  ELSE ISNULL(LEFT(IUNI.DESCRIPCION,20),'') END,
			HPRED.NOPRESTACION, HPRED.NOITEM,  UPPER(HADM.DXINGRESO), 
			SER.IDSERVICIO

	PRINT 'SE CREARON EN AM QX ' + CONVERT(VARCHAR,@@ROWCOUNT) + ' ITEMS'

	SELECT @FORMATORIPS=TIPORIPS FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN 
	PRINT 'TIPO DE FORMATO PARA LOS MEDICAMENTOS '+ @FORMATORIPS
	PRINT '@IDTERCERO='+@IDTERCERO
	PRINT '@IDPLAN='+@IDPLAN
		PRINT 'Busco formato de c?igos'
	IF COALESCE(@FORMATORIPS,'')='01'-- COD CUMS SOLO
	BEGIN 
		PRINT 'FORMATO RIPS CUMS' 
		UPDATE RRIPS_AM SET IDMEDICAMENTO=CASE COALESCE(D.CODIGOCUM,'') WHEN '' THEN CASE COALESCE(IART.CODCUM,'') WHEN '' THEN SER.CODCUM ELSE IART.CODCUM END ELSE D.CODIGOCUM END
		FROM RRIPS_AM A INNER JOIN HPRED D ON D.NOPRESTACION=A.NOPRESTACION AND D.NOITEM=A.NOITEM
					INNER JOIN SER ON SER.IDSERVICIO=D.IDSERVICIO
					LEFT JOIN IART ON D.IDARTICULO=IART.IDARTICULO
		WHERE A.ENVIO=@ENVIO

		UPDATE RRIPS_AM  SET IDMEDICAMENTO=CASE ISNULL(SER.CODCUM,'') WHEN '' THEN A.IDSERVICIO ELSE SER.CODCUM END
		FROM RRIPS_AM  A INNER JOIN SER ON A.IDSERVICIO=SER.IDSERVICIO
		WHERE ISNULL(IDMEDICAMENTO,'')='' OR ISNULL(IDMEDICAMENTO,'') NOT LIKE '%-%'
		AND  A.ENVIO=@ENVIO
	END
	ELSE
	BEGIN
		IF COALESCE(@FORMATORIPS,'')='02'-- COD SISPRO SOLO
		BEGIN
			PRINT 'FORMATO RIPS SISPRO'
			UPDATE RRIPS_AM SET IDMEDICAMENTO=COALESCE(SER.CODSISPRO,A.IDSERVICIO) 
			FROM RRIPS_AM A INNER JOIN SER ON A.IDSERVICIO=SER.IDSERVICIO
			WHERE A.ENVIO=@ENVIO
		END 
		ELSE
		BEGIN
			IF COALESCE(@FORMATORIPS,'')='03'
			BEGIN 
			PRINT 'FORMATO RIPS BASE DE DATOS PROPIAS'
			UPDATE RRIPS_AM SET 
				IDMEDICAMENTO=COALESCE(SERTHOM.IDALTERNA,A.IDSERVICIO), 
				NOMBREMEDI=LEFT(COALESCE(SERTHOM.DESCRIPCION,A.NOMBREMEDI),30) 
			FROM RRIPS_AM A 
				INNER JOIN FTR     ON A.NUMFACTURA=FTR.N_FACTURA
				LEFT JOIN SERTHOM ON A.IDSERVICIO=SERTHOM.IDSERVICIO AND SERTHOM.IDTERCERO=FTR.IDTERCERO
				WHERE A.ENVIO=@ENVIO
			END
			ELSE
			BEGIN
				IF COALESCE(@FORMATORIPS,'')='04'
				BEGIN 
				PRINT 'FORMATO RIPS CODCUPS PARA MEDICAMENTOS'
				UPDATE RRIPS_AM SET 
					IDMEDICAMENTO=COALESCE(SER.CODCUPS,A.IDSERVICIO), 
					NOMBREMEDI=LEFT(COALESCE(SER.DESCRIPCION_CUPS,A.NOMBREMEDI),30) 
				FROM RRIPS_AM A 
					INNER JOIN FTR     ON A.NUMFACTURA=FTR.N_FACTURA
					LEFT JOIN SER ON A.IDSERVICIO=SER.IDSERVICIO
				WHERE A.ENVIO=@ENVIO
				END
			END
		END
	END
	IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(CODBCUM,'')<>'')
	BEGIN
		DECLARE @IDGRUPOSER VARCHAR(20)
		SELECT @IDGRUPOSER=CODBCUM FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN 
		IF EXISTS(SELECT  * FROM GSSP WHERE IDGRUPOSER=@IDGRUPOSER)
		BEGIN
			UPDATE RRIPS_AM SET IDMEDICAMENTO=GSSP.CODCUM,FORMAFARMA=GSSP.FORMAFARMA,CONCMEDI=GSSP.CONCMEDI,UMEDMEDI=GSSP.UMEDMEDI
			FROM RRIPS_AM INNER JOIN GSSP ON RRIPS_AM.IDSERVICIO=GSSP.IDSERVICIO
			WHERE RRIPS_AM.ENVIO=@ENVIO
			AND GSSP.IDGRUPOSER=@IDGRUPOSER

		END
	END
	IF @RIPS_AGRUPADOS='SI'
	BEGIN
		SELECT  ENVIO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, NUMAUT, IDMEDICAMENTO, TIPOMEDICAMENTO, NOMBREMEDI, FORMAFARMA, 
				CONCMEDI,UMEDMEDI, SUM(CAST(NUMUNIDADES AS INT))NUMUNIDADES, AVG(CAST(VALORUNIMEDI AS DECIMAL(14,2)))VALORUNIMEDI, SUM(CAST(VALORTOTMEDI AS DECIMAL(14,2)))VALORTOTMEDI,MAX(NOPRESTACION)NOPRESTACION,MIN(NOITEM)NOITEM, 
				CNSFTR,MIN(N_CUOTA)N_CUOTA,MIN(IDDX)IDDX, PROCEDENCIA, IDSERVICIO, CODEVAL,MIN(FECHAMEDICAMENTO)FECHAMEDICAMENTO, IDTERCERO
				INTO #RIPSAMTEMP
		FROM RRIPS_AM WHERE ENVIO=@ENVIO
		GROUP BY ENVIO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, NUMAUT, IDMEDICAMENTO, TIPOMEDICAMENTO, NOMBREMEDI, FORMAFARMA, 
				CONCMEDI, UMEDMEDI,CNSFTR,   PROCEDENCIA, IDSERVICIO, CODEVAL,  IDTERCERO

		PRINT 'BORRAMOS EL DETALLADO'
		DELETE RRIPS_AM WHERE ENVIO=@ENVIO
		PRINT 'INSERTO EL AGURPADO'

		INSERT INTO RRIPS_AM(ENVIO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, NUMAUT, IDMEDICAMENTO, TIPOMEDICAMENTO, NOMBREMEDI, FORMAFARMA, CONCMEDI, UMEDMEDI, NUMUNIDADES, VALORUNIMEDI, VALORTOTMEDI, FECHARECIBO, 
					ESTADO, FECHAENVIO, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, IDDX, PROCEDENCIA, IDSERVICIO, CODEVAL, FECHAMEDICAMENTO, IDTERCERO)
		SELECT ENVIO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, NUMAUT, IDMEDICAMENTO, TIPOMEDICAMENTO, NOMBREMEDI, FORMAFARMA, CONCMEDI, UMEDMEDI, NUMUNIDADES, VALORUNIMEDI, VALORTOTMEDI, NULL, 
				NULL, NULL, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, IDDX, PROCEDENCIA, IDSERVICIO, CODEVAL, FECHAMEDICAMENTO, IDTERCERO
		FROM  #RIPSAMTEMP

		PRINT 'TERMINO EL NUEVO INSERT AGRUPADOS PARA CEM'
	END 
      
	PRINT 'CREANDO AT QX'
	INSERT INTO RRIPS_AT ( ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, NUMAUT, TIPOSERVICIO, IDSERVICIO,
						DESCRIPCIONSER, CANTIDAD, VLRUNITMAT, VLRTOTMAT, NOPRESTACION, NOITEM, CNSFTR, 
						N_CUOTA, PROCEDENCIA, IDDX, IDSERVICIOORI, CODEVAL, FECHAPROCEDIMIENTO)
	SELECT @ENVIO, @IDTERCERO, RIPSD.N_FACTURA, @CODPREST, LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, LEFT(HADM.NOAUTORIZACION,15), 
			CASE SER.CODIGORIPS WHEN DBO.FNK_ValorVariable('IDESTANCIASRIPS') THEN '3'
								WHEN DBO.FnK_ValorVariable('IDHONORARIOSRIPS')  THEN '4'
								WHEN DBO.FnK_ValorVariable('IDMATERIALESRIPS')  THEN '1'
								WHEN DBO.FnK_ValorVariable('IDTRASLADOSRIPS')   THEN '2'
								WHEN DBO.FnK_ValorVariable('IDDERECHOSALARIPS') THEN '3'
								WHEN DBO.FnK_ValorVariable('IDPROTESISRIPS')    THEN '1'
								ELSE '2'
			END, SER.IDALTERNA, LEFT(SER.DESCSERVICIO,60), CASE WHEN HPRED.CANTIDAD > 99999 THEN 99999
																ELSE CAST(HPRED.CANTIDAD AS INT)
															END, 
			CASE WHEN COALESCE(HADM.PAQUETE,0)=2 AND COALESCE(HPRED.PAQUETE,0) NOT IN (2,3) THEN '0' ELSE 
			CAST(CASE WHEN COALESCE (HPRED.IDCIRUGIA,'')<>'' AND @RIPS_PROCESOAP ='SI' AND COALESCE(HPRED.PAQUETE,0) NOT IN (2,3)
				AND (SER.CODIGORIPS=(SELECT DATO FROM USVGS WHERE IDVARIABLE='IDHONORARIOSRIPS') OR 
					SER.CODIGORIPS=(SELECT DATO FROM USVGS WHERE IDVARIABLE='IDDERECHOSALARIPS'))
					THEN 0 
					ELSE CONVERT(DECIMAL(14,0), HPRED.VALOR)  END AS VARCHAR(15)) END AS VLRUNITMAT, 

			CASE WHEN COALESCE(HADM.PAQUETE,0)=2 AND COALESCE(HPRED.PAQUETE,0) NOT IN (2,3) THEN '0' ELSE 
			CAST(CASE WHEN COALESCE (HPRED.IDCIRUGIA,'')<>'' AND @RIPS_PROCESOAP ='SI' AND COALESCE(HPRED.PAQUETE,0) NOT IN (2,3)
				AND (SER.CODIGORIPS=(SELECT DATO FROM USVGS WHERE IDVARIABLE='IDHONORARIOSRIPS') OR SER.CODIGORIPS=(SELECT DATO FROM USVGS WHERE IDVARIABLE='IDDERECHOSALARIPS'))
				THEN 0 
						ELSE CASE @RIPS_COPAGOS 
									WHEN 'NO' THEN CAST(HPRED.VALOR * HPRED.CANTIDAD AS DECIMAL(14,0))
									ELSE CAST((HPRED.VALOR * HPRED.CANTIDAD) - HPRED.VALORCOPAGO AS DECIMAL(14,0)) 
						END
					END AS VARCHAR(15)) END AS VLRTOTMAT,
			HPRED.NOPRESTACION, HPRED.NOITEM, ISNULL(@CNSFCT,'EXTERNO'), 1, 
			'QX', UPPER(HADM.DXINGRESO), SER.IDSERVICIO, 'CODEVAL', HPRE.FECHA
	FROM   RIPSD 
				INNER JOIN HPRE  ON HPRE.NOADMISION    = RIPSD.NOADMISION
				INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
				INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
					LEFT JOIN SER   ON HPRED.IDSERVICIO   = SER.IDSERVICIO
				LEFT JOIN AFI     ON HADM.IDAFILIADO  = AFI.IDAFILIADO
				LEFT JOIN PRE     ON SER.PREFIJO      = PRE.PREFIJO
				LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS

	WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	---SE COLOCA FECHA PARA QUE TRAIGA SOLAMENTE LO PRODUCIDO EN EL MES 
	AND  HPRE.FECHA >=@FECHAINICIAL AND  HPRE.FECHA<= @FECHAFINAL
	AND    RIPSD.PROCEDENCIA = 'HADM'
	AND    COALESCE(HPRED.NOCOBRABLE,0)=0
	AND   (RIPS_CP.ARCHIVO   = 'AT' OR RIPS_CP.ARCHIVO   = 'AH')
		AND  COALESCE(HPRED.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRED.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 

	PRINT 'SE CREARON EN AT QX ' + CONVERT(VARCHAR,@@ROWCOUNT) + ' ITEMS'

	PRINT 'CREANDO AU QX'
	INSERT INTO RRIPS_AU (ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, FECHAINGRESO, NUMAUT, CAUSAEXT,
							DXSALIDA, IDDXREL1, IDDXREL2, IDDXREL3, DESTINOSALIDA, ESTSALIDA, CBMU, FECHASALIDA, NOADMISION)
	SELECT DISTINCT	@ENVIO, @IDTERCERO, RIPSD.N_FACTURA, @CODPREST, LEFT(AFI.TIPO_DOC,2),
				CASE
				WHEN LEN(AFI.DOCIDAFILIADO) = 0
				THEN AFI.IDAFILIADO
				ELSE AFI.DOCIDAFILIADO
			END,
			HADM.FECHA,
			LEFT(HADM.NOAUTORIZACION,15), HADM.CAUSAEXTERNA, UPPER(HADM.DXEGRESO), UPPER(HADM.DXSALIDA1),
			UPPER(HADM.DXSALIDA3), UPPER(HADM.DXSALIDA3), CASE WHEN (HADM.DESTINO >= 1 AND HADM.DESTINO <= 3) THEN HADM.DESTINO ELSE '1' END,
			HADM.ESTADOPSALIDA,  UPPER(HADM.CAUSABMUERTE), COALESCE(HADM.FECHAALTA,HADM.FECHAALTAMED), HADM.NOADMISION
	FROM   RIPSD INNER JOIN HPRE  ON HPRE.NOADMISION    = RIPSD.NOADMISION
				INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
				INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
				LEFT  JOIN AFI   ON HADM.IDAFILIADO   = AFI.IDAFILIADO  
	WHERE  RIPSD.ENVIO       = @ENVIO  AND RIPSD.IDTERCERO=@IDTERCERO
	---SE COLOCA FECHA PARA QUE TRAIGA SOLAMENTE LO PRODUCIDO EN EL MES
	AND    RIPSD.PROCEDENCIA = 'HADM'   
	AND    HADM.VIAINGRESO   = 1   
	AND    COALESCE(HPRED.NOCOBRABLE,0)=0 
		AND  COALESCE(HPRED.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRED.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 

	PRINT 'SE CREARON EN AU QX ' + CONVERT(VARCHAR,@@ROWCOUNT) + ' ITEMS'

	PRINT 'CREANDO AH QX'
	IF (DBO.FNK_VALORVARIABLE('RIPSAH_CAPMODO')) = 'CARGOS'
	BEGIN
		INSERT INTO RRIPS_AH ( ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, VIAINGRESO, FECHAINGRESO, NUMAUT, CAUSAEXT,
								DXINGRESO, DXEGRESO, DXREL1, DXREL2, DXREL3, DXCOMP, ESTSALIDA, DXCBM, FECHAEGRESO, NOADMISION )
		SELECT DISTINCT @ENVIO, @IDTERCERO, RIPSD.N_FACTURA, @CODPREST, LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, HADM.VIAINGRESO, HADM.FECHA, 
				LEFT(HADM.NOAUTORIZACION,15),
				HADM.CAUSAEXTERNA, HADM.DXINGRESO, HADM.DXEGRESO, UPPER(HADM.DXSALIDA1), UPPER(HADM.DXSALIDA2), UPPER(HADM.DXSALIDA3),
				UPPER(HADM.COMPLICACION), UPPER(HADM.ESTADOPSALIDA), UPPER(HADM.CAUSABMUERTE),
				CASE WHEN HADM.CERRADA=0 THEN @FECHAFINAL ELSE COALESCE(HADM.FECHAALTAMED,@FECHAFINAL) END, HADM.NOADMISION
		FROM   RIPSD INNER JOIN HPRE  ON HPRE.NOADMISION    = RIPSD.NOADMISION
					INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
					INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
					LEFT JOIN AFI   ON HADM.IDAFILIADO    = AFI.IDAFILIADO
		WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
		AND    RIPSD.PROCEDENCIA = 'HADM'
		AND    COALESCE(HPRED.NOCOBRABLE,0)=0
		AND    EXISTS (SELECT * FROM AFU WHERE AFU.IDAREA = HPRE.IDAREA AND AFU.CE = 3)
			AND  COALESCE(HPRED.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRED.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 

	END
	ELSE
	BEGIN
		INSERT INTO RRIPS_AH ( ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, VIAINGRESO, FECHAINGRESO, NUMAUT, CAUSAEXT,
								DXINGRESO, DXEGRESO, DXREL1, DXREL2, DXREL3, DXCOMP, ESTSALIDA, DXCBM, FECHAEGRESO, NOADMISION )
		SELECT DISTINCT @ENVIO, @IDTERCERO, RIPSD.N_FACTURA, @CODPREST, LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, HADM.VIAINGRESO, HADM.FECHA, 
				LEFT(HADM.NOAUTORIZACION,15),
				HADM.CAUSAEXTERNA, HADM.DXINGRESO, HADM.DXEGRESO, UPPER(HADM.DXSALIDA1), UPPER(HADM.DXSALIDA2), UPPER(HADM.DXSALIDA3),
				UPPER(HADM.COMPLICACION), UPPER(HADM.ESTADOPSALIDA), UPPER(HADM.CAUSABMUERTE), 
				CASE WHEN HADM.CERRADA=0 THEN @FECHAFINAL ELSE COALESCE(HADM.FECHAALTAMED,@FECHAFINAL) END, HADM.NOADMISION
		FROM   RIPSD INNER JOIN HPRE  ON HPRE.NOADMISION    = RIPSD.NOADMISION
					INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
					INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
					LEFT JOIN AFI   ON HADM.IDAFILIADO    = AFI.IDAFILIADO
		WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
		AND    COALESCE(HPRED.NOCOBRABLE,0)=0
		AND    RIPSD.PROCEDENCIA = 'HADM'
			AND  COALESCE(HPRED.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRED.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 

	END
	PRINT 'SE CREARON EN AH QX ' + CONVERT(VARCHAR,@@ROWCOUNT) + ' ITEMS'

	PRINT 'CREANDO AN QX'
	INSERT INTO RRIPS_AN ( ENVIO, IDTERCERO, NUMFACTURA, CONSECUTIVO, IDPRESTADOR, TIPOIDM, IDMADRE, FNACIMIENTO, EDADGEST, CPRENATAL, 
							SEXO, PESO, DXRN, CBM, FMUERTE)
	SELECT DISTINCT @ENVIO, @IDTERCERO, RIPSD.N_FACTURA, QXRCN.CONSECUTIVO, @CODPREST, LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, QXRCN.RNFECHANACE,
			LEFT(QXRCN.CMPERIODOGES,2), CASE UPPER(QXRCN.CMCONTROLPRE) WHEN 'SI' THEN '1' ELSE '2' END, UPPER(LEFT(QXRCN.RNSEXO,1)),
			LEFT(QXRCN.RNPESO,4), UPPER(QXRCN.RNDX), UPPER(QXRCN.RNCAUSAMUERTE), QXRCN.RNFECHAMUERTE
	FROM   RIPSD INNER JOIN HPRE  ON HPRE.NOADMISION    = RIPSD.NOADMISION
				INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
				INNER JOIN HADM  ON HPRE.NOADMISION    = HADM.NOADMISION
					LEFT JOIN AFI   ON HADM.IDAFILIADO    = AFI.IDAFILIADO
				INNER JOIN QXRCN ON HADM.NOADMISION    = QXRCN.NOADMISION
	WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	AND    COALESCE(HPRED.NOCOBRABLE,0)=0
	AND    RIPSD.PROCEDENCIA = 'HADM'
		AND  COALESCE(HPRED.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRED.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 

	PRINT 'SE CREARON EN AN QX ' + CONVERT(VARCHAR,@@ROWCOUNT) + ' ITEMS'

	-- INCLUIDO POR RUTHFORD JAY 2009-05-21 15:49
	PRINT 'CREANDO AP QX CIRUGIA'
	DECLARE AP_CURSOR CURSOR FOR
	SELECT RIPSD.N_FACTURA, LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, HPRE.FECHA, LEFT(HPRE.NUMAUTORIZA,15), 
			SER.IDSERVICIO,
			AFU.AMBITO, CASE ISNULL(HPRE.FINALIDAD,'') WHEN '' THEN PRE.FINALIDAD ELSE HPRE.FINALIDAD END,
			CASE SER.MPERSONAL_AT WHEN 1 THEN HPRE.PERSONAL_AT ELSE '' END, HADM.DXINGRESO, HADM.DXSALIDA1,
			HADM.COMPLICACION, CASE ISNULL(TGEN.DATO1,'') WHEN '' THEN '1' ELSE TGEN.DATO1 END,
			SUM( CASE WHEN COALESCE(HADM.PAQUETE,0)=2 AND COALESCE(FTRD.PAQUETE,0) NOT IN (2,3) THEN 0 ELSE 
					CAST(  CASE WHEN @RIPS_PROCESOAP='SI' 
										THEN HPRED.VALOR ELSE 0 END  AS INT ) END) VALOR,
			HPRED.NOPRESTACION, HADM.IDTERCERO, HPRED.IDPLAN, ISNULL(@CNSFCT,'EXTERNO'), NULL, 'CODEVAL'
	FROM   RIPSD INNER JOIN FTRD   ON RIPSD.N_FACTURA     = FTRD.N_FACTURA
				INNER JOIN HADM    ON RIPSD.NOADMISION       = HADM.NOADMISION
				INNER JOIN HPRE    ON HADM.NOADMISION        = HPRE.NOADMISION
				INNER JOIN HPRED   ON HPRED.NOPRESTACION     = HPRE.NOPRESTACION
				INNER JOIN AFI     ON HADM.IDAFILIADO        = AFI.IDAFILIADO
				INNER JOIN QXPCXD  ON HPRED.CONSECUTIVOCX    = QXPCXD.CONSECUTIVO AND HPRED.ITEMCIRUGIA = QXPCXD.ITEM
				INNER JOIN SER     ON QXPCXD.IDSERVICIO      = SER.IDSERVICIO  
				INNER JOIN PRE     ON SER.PREFIJO            = PRE.PREFIJO  
					LEFT JOIN AFU     ON HPRE.IDAREA            = AFU.IDAREA
					LEFT JOIN TGEN    ON QXPCXD.TIPOCIRUGIA     = TGEN.CODIGO AND TGEN.CAMPO = 'TIPOCIRUGIA' AND TGEN.TABLA ='General'
					LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS
	WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	---SE COLOCA FECHA PARA QUE TRAIGA SOLAMENTE LO PRODUCIDO EN EL MES 
	AND  HPRE.FECHA >=@FECHAINICIAL AND  HPRE.FECHA<= @FECHAFINAL
	AND    RIPSD.PROCEDENCIA = 'HADM' 
	AND    RIPS_CP.ARCHIVO = 'AP'
	AND    COALESCE(HPRED.NOCOBRABLE,0)=0
	AND  COALESCE(HPRED.IDPLAN,'')= CASE WHEN  COALESCE(@IDPLAN,'')='' THEN COALESCE(HPRED.IDPLAN,'') ELSE COALESCE(@IDPLAN,'') END 

	GROUP BY RIPSD.N_FACTURA, LEFT(AFI.TIPO_DOC,2), AFI.DOCIDAFILIADO, HPRE.FECHA, LEFT(HPRE.NUMAUTORIZA,15), 
			SER.IDSERVICIO, AFU.AMBITO, CASE ISNULL(HPRE.FINALIDAD,'') WHEN '' THEN PRE.FINALIDAD ELSE HPRE.FINALIDAD END,
			CASE SER.MPERSONAL_AT WHEN 1 THEN HPRE.PERSONAL_AT ELSE '' END, HADM.DXINGRESO, HADM.DXSALIDA1,
			HADM.COMPLICACION, CASE ISNULL(TGEN.DATO1,'') WHEN '' THEN '1' ELSE TGEN.DATO1 END,
			HPRED.NOPRESTACION, HADM.IDTERCERO, HPRED.IDPLAN

	OPEN AP_CURSOR  
	FETCH NEXT FROM AP_CURSOR  
	INTO @NUMFACTURA, @TIPO_DOC, @IDUSUARIO, @FECHAPROCEDIMIENTO, @NUMAUT, @IDPROCEDIMIENTO,
		@AMBITO, @FINPROCEDIMIENTO, @PERSONALA, @DXPPAL, @DXREL, @COMPLICACION, @ACTOQ,@VALOR,
		@NOPRESTACION, @IDTERCERO, @IDPLAN, @CNSFTR, @N_CUOTA, @CODEVAL
	WHILE @@FETCH_STATUS = 0  
	BEGIN
		SELECT @IDTARIFA = SERTOT.IDTARIFA 
		FROM   SERTOT    
		WHERE  SERTOT.IDSERVICIO =  @IDPROCEDIMIENTO
		AND    SERTOT.IDTERCERO  =  @IDTERCERO
		AND    SERTOT.IDPLAN     =  @IDPLAN      
		AND    SERTOT.FECHAINIFD <= @FECHAPROCEDIMIENTO
		AND    SERTOT.FECHAFINFD >= @FECHAPROCEDIMIENTO
		AND    SERTOT.FECHAINI   <= @FECHAPROCEDIMIENTO
		AND    SERTOT.FECHAFIN   >= @FECHAPROCEDIMIENTO
        
		SELECT @TIPOBUSQUEDA = TIPOBUSQUEDA
		FROM   HGQX
		WHERE  IDTARIFA = @IDTARIFA
          
		IF @TIPOBUSQUEDA <> 'Paquete'
		BEGIN
			INSERT INTO RRIPS_AP (ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, FECHAPROCEDIMIENTO, NUMAUT, IDPROCEDIMIENTO,
								AMBITO, FINPROCEDIMIENTO, PERSONALA, DXPPAL, DXREL, COMPLICACION, ACTOQ, VALORPROCED, NOPRESTACION,
								CNSFTR, N_CUOTA, CANTIDAD, PROCEDENCIA, CODEVAL,IDSERVICIO) 
			SELECT @ENVIO, @IDTERCERO, @NUMFACTURA, @CODPREST, @TIPO_DOC, @IDUSUARIO, @FECHAPROCEDIMIENTO, @NUMAUT, IDALTERNA,
				@AMBITO, @FINPROCEDIMIENTO, @PERSONALA, @DXPPAL, @DXREL, @COMPLICACION, @ACTOQ,@VALOR,
				@NOPRESTACION, @CNSFTR, @N_CUOTA, 1, 'QX', @CODEVAL,IDSERVICIO
			FROM SER WHERE IDSERVICIO=@IDPROCEDIMIENTO
		END
      
		FETCH NEXT FROM AP_CURSOR  
		INTO @NUMFACTURA, @TIPO_DOC, @IDUSUARIO, @FECHAPROCEDIMIENTO, @NUMAUT, @IDPROCEDIMIENTO,
			@AMBITO, @FINPROCEDIMIENTO, @PERSONALA, @DXPPAL, @DXREL, @COMPLICACION, @ACTOQ,@VALOR,
			@NOPRESTACION, @IDTERCERO, @IDPLAN, @CNSFTR, @N_CUOTA, @CODEVAL
	END
	CLOSE AP_CURSOR  
	DEALLOCATE AP_CURSOR  
	PRINT 'SE CREARON EN AP QX CIRUGIA ' + CONVERT(VARCHAR,@@ROWCOUNT) + ' ITEMS'

	-- INCLUIDO POR RUTHFORD JAY 2009-02-04 09:49
	-- VALIDA LA INFORMACION DE LOS ARCHIVOS
	EXEC DBO.SPK_RIPS_QX_VAL @ENVIO, @IDTERCERO
   
	-- INCLUIDO POR RUTHFORD JAY 2009-01-26 17:20
	-- CONSOLIDA LA INFORMACION REGISTRADA EN LOS RIPS EN LOS ARCHIVOS AD, AF Y CT
	EXEC SPK_RIPS_CAPITA_CONSOLIDAR @ENVIO, @IDTERCERO, @FECHAINICIAL, @FECHAFINAL, @CODPREST, @DPRRS, 'NI', @DPRNIT

	-- INCLUIDO POR RUTHFORD JAY 2009-01-27 09:40
	-- SI LA VARIABLE RIPSCAPITADOSENCERO SE EN CUENTRA CON VALOR SI, LOS RIPS TOMARAN EL VALOR DE CERO
	IF UPPER(DBO.FNK_VALORVARIABLE('RIPSCAPITADOSENCERO')) = 'SI' AND   @PGP=0
	BEGIN
		EXEC DBO.SPK_RIPS_EN_CERO @ENVIO, @IDTERCERO
	END
	ELSE IF   UPPER(DBO.FNK_VALORVARIABLE('RIPSPGPENCERO')) = 'SI' AND   @PGPX =1
	BEGIN
		EXEC DBO.SPK_RIPS_EN_CERO @ENVIO, @IDTERCERO
	END

	--UPDATE RIPS SET ESTADO = '02' WHERE ENVIO = @ENVIO AND IDTERCERO=@IDTERCERO
END



