
SELECT * FROM #A

SELECT CNSCXC,ANOMES INTO #B FROM #A
GROUP BY CNSCXC,ANOMES


SELECT CNSCXC,ANOMES,ROW_NUMBER() OVER(PARTITION BY CNSCXC ORDER BY CNSCXC DESC)NRO INTO #D FROM #B

SELECT * FROM #C
SELECT * FROM #D

DELETE #D WHERE NRO<>1

ALTER TABLE #C ADD ID INT IDENTITY(1,1)

ALTER TABLE #C ADD CNSNUEVO VARCHAR(20)

UPDATE #C SET CNSNUEVO='02'+REPLACE(SPACE(8-LEN(ID)),SPACE(1),'0')+CAST(ID AS VARCHAR(3))

INSERT INTO #C (CNSCXC,ANOMES,NRO,CNSNUEVO )
SELECT CNSCXC,ANOMES,NRO,CNSCXC FROM #D


SELECT * FROM #C

SELECT * FROM #A

ALTER TABLE #A ADD CNSNUEVO VARCHAR(20)

UPDATE 
SELECT *
FROM #A INNER JOIN #C ON #A.CNSCXC=#C.CNSCXC AND #A.ANOMES=#C.ANOMES

SELECT  FCXC.*,#C.CNSNUEVO INTO #E
FROM FCXC INNER JOIN #C ON FCXC.CNSCXC=#C.CNSCXC
WHERE #C.NRO<>1

SELECT DBO.FNK_COLUMNAS_TABLAS('FCXC')

INSERT INTO FCXC(CNSCXC, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT,  ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA,  ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, CNSRP, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA,  NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE)
SELECT CNSNUEVO, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT,  ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA,  ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, CNSRP, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA,  NOPOS, FRADICAEPS, FENVIO, SUCURSAL, MSEDE
FROM #E

SELECT * 
FROM #A INNER JOIN FCXCDV ON #A.CNSNUEVO COLLATE Modern_Spanish_CI_AS =FCXCDV.CNSCXC AND #A.N_FACTURA COLLATE Modern_Spanish_CI_AS=FCXCDV.N_FACTURA

--UPDATE FCXCD SET CNSCXC=#A.CNSNUEVO
--FROM #A INNER JOIN FCXCD ON #A.CNSCXC COLLATE Modern_Spanish_CI_AS =FCXCD.CNSCXC AND #A.N_FACTURA COLLATE Modern_Spanish_CI_AS=FCXCD.N_FACTURA


SELECT CNSNUEVO,MAX(F_RADICA)F_RADICA INTO #F FROM #A
GROUP BY CNSNUEVO


UPDATE FCXC SET F_RECIBIDO=#F.F_RADICA 
FROM FCXC INNER JOIN #F ON FCXC.CNSCXC=#F.CNSNUEVO COLLATE SQL_Latin1_General_CP1_CI_AS

SELECT * FROM #F WHERE CNSNUEVO LIKE '02%'


SELECT  * FROM VWK_CXCDIASVTO WHERE CNSCXC='0200000165'

SELECT 'EXEC SPK_RELIQUIDACXCQX '''+CNSCXC+'''' FROM FCXC WHERE INDRECIBIDO=0

EXEC SPK_RELIQUIDACXCQX