   --  EXEC SPK_PROCESO_VACACIONES NULL,'ACTUALIZA','0600007925'
     
     DECLARE @NUMDOC VARCHAR(20)='0100000768'
      SELECT NUMDOC,CODCARGO,NIVEL,GRADO,FECHAINGRESO,FECHARETIRO 
      FROM NEMP
      WHERE ESTADO='Activo'
     -- AND COALESCE(FECHARETIRO,GETDATE()+1)>GETDATE()
      AND NUMDOC=@NUMDOC

      SELECT DIASG-DIASP, * FROM NEMPV WHERE NUMDOC='0600007925'
      UPDATE  NEMPV SET F_INICAL='17/01/2024' WHERE NUMDOC='0600007925' AND ITEM=2

      SELECT 3.3333-3.1
      SELECT  * FROM NEMP WHERE DOCIDEMPLEADO='1001478659'

      UPDATE 

      --DELETE  NEMPV WHERE NUMDOC='0100000719'
      SELECT * FROM NEMPVD WHERE NUMDOC='43109255'

      UPDATE NEMPVD SET NDIAS=NDIAS+0.2333 WHERE NUMDOC='43109255'AND CNSNEMPVD='0600001109'


            DECLARE NEMPVD_CURSOR CURSOR FOR 
      SELECT ITEM,DIASG,DIASP  FROM NEMPV 
      WHERE NUMDOC='43109255'
      ORDER BY   ITEM
      OPEN NEMPVD_CURSOR    
      FETCH NEXT FROM NEMPVD_CURSOR    
      INTO @ITEMV,@DIASG,@DIASP
      WHILE @@FETCH_STATUS = 0    
      BEGIN 
         IF @DIASP<@DIASG
         BEGIN
            SELECT @DIASC= SUM(NDIAS) FROM  NEMPVD WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV AND COALESCE(ESTADO,'')<>'Anulado'
            UPDATE NEMPV SET DIASP=COALESCE(@DIASC,0) WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV
            UPDATE NEMPV SET ESTADO=CASE WHEN DIASG>=NDIAS THEN  CASE WHEN DIASP>=DIASG THEN  'Pagado' ELSE 'Cumplidas'  END ELSE 'Proceso' END  WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV
         END

         FETCH NEXT FROM NEMPVD_CURSOR    
         INTO @ITEMV,@DIASG,@DIASP
      END
      CLOSE NEMPVD_CURSOR
      DEALLOCATE NEMPVD_CURSOR

      EXEC DBO.SPK_CALCULAR_RETIROS '02202405P30-1','0100000768'

                     SELECT NRODIAS=SUM(COALESCE(DIASG,0))-SUM(COALESCE(DIASP,0))
               FROM NEMPV WHERE NUMDOC='0100000768' AND ESTADO IN('Proceso','Cumplidas')

      UPDATE NEMPV SET F_INICAL='08/04/2024',F_FINAL='08/04/2025' WHERE  NUMDOC=@NUMDOC AND ITEM=7

      DECLARE @ITEMV INT
      DECLARE @DIASG DECIMAL(7,4)
      DECLARE @DIASP DECIMAL(7,4)
      DECLARE @DIASC DECIMAL(7,2)
      DECLARE NEMPVD_CURSOR CURSOR FOR 
      SELECT ITEM,DIASG,DIASP  FROM NEMPV 
      WHERE NUMDOC=@NUMDOC
      ORDER BY   ITEM
      OPEN NEMPVD_CURSOR    
      FETCH NEXT FROM NEMPVD_CURSOR    
      INTO @ITEMV,@DIASG,@DIASP
      WHILE @@FETCH_STATUS = 0    
      BEGIN 
         IF @DIASP<@DIASG
         BEGIN
            SELECT @DIASC= SUM(NDIAS) FROM  NEMPVD WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV AND COALESCE(ESTADO,'')<>'Anulado'
            UPDATE NEMPV SET DIASP=COALESCE(@DIASC,0) WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV
            UPDATE NEMPV SET ESTADO=CASE WHEN DIASG>=NDIAS THEN  CASE WHEN DIASP>=DIASG THEN  'Pagado' ELSE 'Cumplidas'  END ELSE 'Proceso' END  WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV
         END

         FETCH NEXT FROM NEMPVD_CURSOR    
         INTO @ITEMV,@DIASG,@DIASP
      END
      CLOSE NEMPVD_CURSOR
      DEALLOCATE NEMPVD_CURSOR


      SELECT 