<i class="fa-solid fa-pencil"></i>


SELECT  * FROM API_LOG ORDER BY ITEM DESC


BEGIN TRAN 
EXEC SPQ_JSON '{"MODELO":"FCXC_COL","METODO":"IMPRIMIR_FCXC","PARAMETROS":{"CNSCXC":"0200000183"},"USUARIO":"JJIMENEZ"}'

ROLLBACK

UPDATE SED SET LOGO='C:\DEV11.1\PKrystalosArs_11\Logo IX.jpg'

SELECT * FROM FCXC WHERE CNSCXC='0200000183'

UPDATE FCXC SET  COORFACTURACION= DBO.FNK_VALORVARIABLE('USUARIOJEFEFACTURA'),COORCARTERA=DBO.FNK_VALORVARIABLE('USUARIOJEFECARTERA')
WHERE CNSCXC='0200000181'

 SELECT COORFACTURACION= DBO.FNK_VALORVARIABLE('COORFACTURACION'),COORCARTERA=DBO.FNK_VALORVARIABLE('COORCARTERA')

SELECT * FROM FTR WHERE NOT EXISTS(SELECT * FROM FCXCD WHERE FTR.N_FACTURA=FCXCD.N_FACTURA) AND INDCARTERA=1 AND IDDEP='01'

SELECT CERRADA,INDRECIBIDO,CONTABILIZADA,NROCOMPROBANTE, *   FROM FCXC WHERE CNSCXC='0200000179'

SELECT * FROM FCXCDV  WHERE CNSCXC='0200000179'


SELECT * FROM USUSU