SELECT  CUENTAA,CUENTA AS CUENTAN,NOMCUENTA AS NOM_CUENTA INTO #C FROM #A 

SELECT * FROM CUE WHERE NOT EXISTS(SELECT * FROM #A WHERE CUE.CUENTA=#A.CUENTAA) AND TIPO='Detalle'
DROP TABLE #C
SELECT * FROM #C

SELECT  * FROM #B

SELECT * FROM CUE

DELETE CUE

UPDATE #B SET CUENTA=CUENTAN,NOMCUENTA=LEFT(NOM_CUENTA,60)

SELECT DBO.FNK_COLUMNAS_TABLAS('cue')

INSERT INTO CUE
SELECT COMPANIA, CUENTA, NOMCUENTA, TIPO, NEMONICO, CENTRO, PRODUCTO, REFERENCIA, TERCERO, RETENCION, CPTORETENCION, AJUSTE, CIERRE, CUENTAFISCAL, IMPUESTO, ESTADO, NIVEL, CUENTA_SUMA, CLASE,  RUBRO, TIPOTESORERO, BANCO, SUCURSAL, CTA_BCO, CODCAJA, DETALLEXTERCERO, RESPONSABLE, CUENTA_HOMOLOGA, CUENTANIIF, CONCEPTOEXO, FORMATOEXO, NODEDUCIBLE, ASUMIDA_PRACTICADA, CTACIERRECOSTOS,  CTACREDITOCOSTOS, CORRIENTE, CUEESPEJO, RUBRO_ID, CONCEPTO_ACREENCIA
FROM #D

SELECT * FROM #B WHERE CUENTA='1101'


SELECT  * FROM #D

SELECT * INTO #E FROM CUE WHERE TIPO='Detalle'

UPDATE #E SET CUENTA=LEFT(CUENTA,LEN(CUENTA)-2),CUENTA_SUMA=LEFT(CUENTA,LEN(CUENTA)-4)

SELECT *,ROW_NUMBER() OVER(PARTITION BY CUENTA ORDER BY CUENTA ASC)NRO INTO #F FROM #E

DELETE #F WHERE NRO>1

SELECT * FROM CUE WHERE CUENTA='15030706'

UPDATE #F SET RUBRO=CUENTA+'1'

INSERT INTO CUE
SELECT COMPANIA, CUENTA, NOMCUENTA, TIPO, NEMONICO, CENTRO, PRODUCTO, REFERENCIA, TERCERO, RETENCION, CPTORETENCION, AJUSTE, CIERRE, CUENTAFISCAL, IMPUESTO, ESTADO, NIVEL, CUENTA_SUMA, CLASE,  RUBRO, TIPOTESORERO, BANCO, SUCURSAL, CTA_BCO, CODCAJA, DETALLEXTERCERO, RESPONSABLE, CUENTA_HOMOLOGA, CUENTANIIF, CONCEPTOEXO, FORMATOEXO, NODEDUCIBLE, ASUMIDA_PRACTICADA, CTACIERRECOSTOS,  CTACREDITOCOSTOS, CORRIENTE, CUEESPEJO, RUBRO_ID, CONCEPTO_ACREENCIA
FROM #F WHERE NOT EXISTS(SELECT * FROM CUE WHERE #F.CUENTA=CUE.CUENTA)

SELECT * FROM CUE

SELECT *FROM CUE WHERE CUENTA_SUMA<>LEFT(CUENTA,LEN(CUENTA)-2) AND LEN(CUENTA)>2

UPDATE  CUE SET CUENTA_SUMA=LEFT(CUENTA,LEN(CUENTA)-2) WHERE CUENTA_SUMA<>LEFT(CUENTA,LEN(CUENTA)-2) AND LEN(CUENTA)>2

SELECT * FROM CUE INNER JOIN #A ON CUE.CUENTA=#A.CUENTA
WHERE CUE.NOMCUENTA<>LEFT(#A.NOMCUENTA,60)

UPDATE CUE SET NOMCUENTA=LEFT(#A.NOMCUENTA,60)
FROM CUE INNER JOIN #A ON CUE.CUENTA=#A.CUENTA
WHERE CUE.NOMCUENTA<>LEFT(#A.NOMCUENTA,60)

UPDATE CUE SET NOMCUENTA=UPPER(NOMCUENTA),CUENTANIIF=NUL

UPDATE CUE SET CUENTA_HOMOLOGA=CUENTA

SELECT * FROM TTEC WHERE NOT EXISTS(SELECT * FROM KPRUEBAS.DBO.TTEC X WHERE TTEC.TIPO=X.TIPO)

DELETE TTEC

INSERT INTO TTEC
SELECT * FROM KPRUEBAS.DBO.TTEC

UPDATE TTEC SET CUEDIFCOB=#A.CUENTA 
FROM TTEC INNER JOIN #A ON TTEC.CUEDIFCOB=#A.CUENTAA

DELETE KCDE

INSERT INTO KCDE
SELECT * FROM KPRUEBAS.DBO.KCDE

UPDATE KCDE SET CUENTA=#A.CUENTA 
FROM KCDE INNER JOIN #A ON KCDE.CUENTA=#A.CUENTAA

DELETE KMCOMS

INSERT INTO KMCOMS
SELECT * FROM KPRUEBAS.DBO.KMCOMS

UPDATE KMCOMS SET CUENTA=#A.CUENTA 
FROM KMCOMS INNER JOIN #A ON KMCOMS.CUENTA=#A.CUENTAA

DELETE FDISD

INSERT INTO FDISD
SELECT * FROM KPRUEBAS.DBO.FDISD

UPDATE FDISD SET CUENTA=#A.CUENTA 
FROM FDISD INNER JOIN #A ON FDISD.CUENTA=#A.CUENTAA


SELECT *FROM CAJ WHERE NOT EXISTS(SELECT * FROM KPRUEBAS.DBO.CAJ X WHERE CAJ.CODCAJA=X.CODCAJA)

UPDATE CPCJ SET CUENTA=X.CUENTA
FROM CPCJ INNER JOIN KPRUEBAS.DBO.CPCJ X ON CPCJ.CODIGO=X.CODIGO

UPDATE CPCJ SET CUENTA=#A.CUENTA 
FROM CPCJ INNER JOIN #A ON CPCJ.CUENTA=#A.CUENTAA

UPDATE FPA SET CUENTA=X.CUENTA
FROM FPA Y INNER JOIN KPRUEBAS.DBO.FPA X ON Y.FORMAPAGO =X.FORMAPAGO

UPDATE FPA SET CUENTA=#A.CUENTA 
FROM FPA INNER JOIN #A ON FPA.CUENTA=#A.CUENTAA

UPDATE OFIN SET CUENTA=X.CUENTA
FROM OFIN Y INNER JOIN KPRUEBAS.DBO.OFIN X ON Y.IDOPERACION =X.IDOPERACION

UPDATE OFIN SET CUENTA=#A.CUENTA 
FROM OFIN INNER JOIN #A ON OFIN.CUENTA=#A.CUENTAA

UPDATE CPNT SET CUENTA=X.CUENTA
FROM CPNT Y INNER JOIN KPRUEBAS.DBO.CPNT X ON Y.CODIGO =X.CODIGO

UPDATE CPNT SET CUENTA=#A.CUENTA 
FROM CPNT INNER JOIN #A ON CPNT.CUENTA=#A.CUENTAA

UPDATE FNT SET CUENTA=X.CUENTA
FROM FNT Y INNER JOIN KPRUEBAS.DBO.FNT X ON Y.IDNOTA =X.IDNOTA

UPDATE FNT SET CUENTA=#A.CUENTA 
FROM FNT INNER JOIN #A ON FNT.CUENTA=#A.CUENTAA

UPDATE FTR SET CUENTACXC=TTEC.CUENTA,CUENTACXC_RAD=TTEC.CUENTARAD
FROM FTR INNER JOIN TTEC ON FTR.TIPOTTEC=TTEC.TIPO

UPDATE BCT SET COD_CONTABLE=X.COD_CONTABLE
FROM BCT Y INNER JOIN KPRUEBAS.DBO.BCT X ON Y.CTA_BCO =X.CTA_BCO

UPDATE BCT SET COD_CONTABLE=#A.CUENTA 
FROM BCT INNER JOIN #A ON BCT.COD_CONTABLE=#A.CUENTAA


UPDATE MCP SET ESTADO=1 WHERE NROCOMPROBANTE='0191000004844804'

UPDATE PRI SET CERRADO=0 WHERE ANOMES='202312'

DELETE MCH WHERE NROCOMPROBANTE='0191000004844804'

SELECT * FROM MCPE

SELECT * FROM MCHE WHERE NROCOMPROBANTE='0103744221'

SELECT * FROM KMCOM WHERE IDTIPOCONT='MOV_INVENTARIO' AND PREFIJO='01'

SELECT * FROM KMCOMS WHERE IDTIPOCONT='MOV_INVENTARIO' AND PREFIJO='02' AND TIPO='CR'

DELETE  KMCOMS WHERE IDTIPOCONT='MOV_INVENTARIO'  AND PREFIJO='02' AND TIPO='CR'


SELECT  *
FROM IMOV INNER JOIN IZSOL ON IMOV.NODOCUMENTO=IZSOL.CNSIZSOL
          INNER JOIN HHAB ON IZSOL.SECTOR=HHAB.HABCAMA --AND TIPO='SECTOR'
WHERE COALESCE(IMOV.CCOSTO,'')=''
--AND COALESCE(HHAB.CCOSTO,'')<>''
AND FECHACONF>='01/01/2024'
AND IMOV.PROCEDENCIA='CM_SOL'

UPDATE IMOV SET CCOSTO=HHAB.CCOSTO,IDAREA=HHAB.IDAREA
FROM IMOV INNER JOIN IZSOL ON IMOV.NODOCUMENTO=IZSOL.CNSIZSOL
          INNER JOIN HHAB ON IZSOL.SECTOR=HHAB.HABCAMA --AND TIPO='SECTOR'
WHERE COALESCE(IMOV.CCOSTO,'')=''
AND COALESCE(HHAB.CCOSTO,'')<>''
AND FECHACONF>='01/01/2024'
AND IMOV.PROCEDENCIA='CM_SOL'

SELECT  * INTO #H FROM HHAB WHERE COALESCE(CCOSTO,'')<>''

UPDATE HHAB SET IDAREA=#H.IDAREA,CCOSTO=#H.CCOSTO
FROM HHAB INNER JOIN #H ON HHAB.HABCAMA=#H.SECTOR
WHERE COALESCE(HHAB.CCOSTO,'')=''