use CEM

SELECT IDARTICULO,IDSERVICIO, * FROM IART WHERE IDARTICULO LIKE '%-%' AND IDSERVICIO <>LEFT(IDARTICULO,CHARINDEX('-',IDARTICULO,0)-1)

UPDATE IART SET IDSERVICIO=LEFT(IDARTICULO,CHARINDEX('-',IDARTICULO,0)-1) WHERE IDARTICULO LIKE '%-%' AND IDSERVICIO <>LEFT(IDARTICULO,CHARINDEX('-',IDARTICULO,0)-1)