SELECT TOP 10 * FROM API_LOG WHERE USUARIO='TEST' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FCXC_COL","METODO":"SALIR_FCXCD","PARAMETROS":{"CNSCXC":"0100000011"},"USUARIO":"TEST"}'

SELECT  * FROM F

SELECT  FTR.N_FACTURA,CASE WHEN COALESCE(FTR.MARCA,0)=1 THEN 'X-'+FTR.EQUIMARCA ELSE '' END MARCA,TER.NIT AS IDTERCERO, TER.RAZONSOCIAL,CONVERT(VARCHAR,FTR.F_FACTURA,103)F_FACTURA,FTR.PROCEDENCIA,FTR.IDPLAN,PLN.DESCPLAN   FROM [dbo].[FTR] INNER JOIN  TER ON FTR.IDTERCERO=TER.IDTERCERO INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN WHERE ( FTR.N_FACTURA LIKE '%%%%') AND  FTR.ESTADO='P' AND COALESCE(CLASEANULACION,'')<>'NC' AND COALESCE(VR_TOTAL,0)>0 AND COALESCE(CONTABILIZADA,0)<>0                   AND NOT EXISTS(SELECT * FROM FCXCD WHERE FCXCD.N_FACTURA=FTR.N_FACTURA)                   AND COALESCE(INDCARTERA,0)=1 AND IDDEP=DBO.FNK_VALORVARIABLE('IDFDEPCARTERA')                   AND NOT EXISTS(SELECT * FROM ENT INNER JOIN ENTD ON ENT.CNSENTREGA=ENTD.CNSENTREGA WHERE ENT.PROCESO='DEVFACT'                   AND ENT.ESTADO=0 AND ENTD.NODOCUMENTO=FTR.N_FACTURA) AND CONVERT(DATE, F_fACTURA) <=  '2024-08-21' AND FTR.IDTERCERO  =  '010000000037'  ORDER BY  FTR.CNSFCT  OFFSET (1-1)*7 ROWS  FETCH NEXT 7 ROWS ONLY 


SELECT  * FROM FTR WHERE 

UPDATE FTR SET  CONTABILIZADA=1 WHERE COALESCE(CONTABILIZADA,0)<>1