IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_PROCESA_INCAPACIDAD' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_PROCESA_INCAPACIDAD
END
GO
CREATE PROCEDURE DBO.SPK_PROCESA_INCAPACIDAD 
@CNSPAGO  VARCHAR(20),
@NUMDOC   VARCHAR(20),
@IDEVENTO VARCHAR(20),
@PROCESO  INT,
@ITEM     INT
WITH ENCRYPTION
AS  
DECLARE @CNSLIQ VARCHAR(20)
DECLARE @DIASLIMI INT
DECLARE @DIASNOVE INT
DECLARE @DIASNOV1 INT
DECLARE @DIASNOV2 INT
DECLARE @IDEVENTO1 VARCHAR(20)
DECLARE @IDEVENTO2 VARCHAR(20)
DECLARE @VLRSMLV  DECIMAL(14,2)
DECLARE @VLRDIASMLV   DECIMAL(14,2)
DECLARE @BASICO   DECIMAL(14,2)
DECLARE @VLRDIABASICO DECIMAL(14,2)
BEGIN  
   IF @PROCESO = 1
   BEGIN
      PRINT 'Estoy insertando'
      SELECT @DIASLIMI=NDIASEG,@IDEVENTO1=MAYORDIAS,@IDEVENTO2=CODNOVSMLV FROM NEVE WHERE IDEVENTO=@IDEVENTO 
      SELECT @DIASNOVE=DIAS FROM NEDIA WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC AND IDEVENTO=@IDEVENTO AND ITEM=@ITEM

      IF @DIASNOVE > @DIASLIMI
      BEGIN
         UPDATE NEDIA SET 

      END


   END   

END 