--CREATE   FUNCTION [dbo].[RPT_MEDICAMENTO] (@1FINI    DATETIME, @2FFIN    DATETIME, @3NIT     VARCHAR(20), @4SOLOBIO varchar(5))    
--RETURNS TABLE    
--AS    
--return     
declare @1FINI date ='20250501',
@2FFIN date=  getdate(),
@3NIT varchar(20)='060000001020',
@4SOLOBIO varchar(10)='No'
SELECT AFI.TIPO_DOC AS TIPO_IDENTIFICADO, AFI.DOCIDAFILIADO NRO_IDENTIFICACION,      
       REPLACE(REPLACE(TRIM(AFI.PNOMBRE)  ,CHAR(13) + CHAR(10), ' '),CHAR(9), ' ') NOMBRE1,     
       REPLACE(REPLACE(TRIM(AFI.SNOMBRE)  ,CHAR(13) + CHAR(10), ' '),CHAR(9), ' ') NOMBRE2,     
       REPLACE(REPLACE(TRIM(AFI.PAPELLIDO),CHAR(13) + CHAR(10), ' '),CHAR(9), ' ') APELLIDO1,     
       REPLACE(REPLACE(TRIM(AFI.SAPELLIDO),CHAR(13) + CHAR(10), ' '),CHAR(9), ' ') APELLIDO2,     
       PLN.TIPOSISTEMA REGIMEN_CONTRATO, TER.RAZONSOCIAL,    
               CASE WHEN AFI.TIPOAFILIADO = 'A' THEN 'ADICIONAL'    
                    WHEN AFI.TIPOAFILIADO = 'SB'THEN 'SUBSIDIADO'    
                    WHEN AFI.TIPOAFILIADO = 'J' THEN 'JUBILADO'    
                    WHEN AFI.TIPOAFILIADO = 'C' THEN 'CONTRIBUTIVO'    
                    WHEN AFI.TIPOAFILIADO = 'TA'THEN 'TOMADOR/AMPARADO'    
                    WHEN AFI.TIPOAFILIADO = 'S' THEN 'SUSTITUCIÓN PENSIONAL'    
                    WHEN AFI.TIPOAFILIADO = 'RE'THEN 'RÉGIMEN ESPECIALES O DE EXCEPCIÓN'    
                    WHEN AFI.TIPOAFILIADO = 'B' THEN 'BENEFICIARIO'    
                    WHEN AFI.TIPOAFILIADO = 'SR'THEN 'SIN RÉGIMEN'    
                    ELSE 'SIN DATO'    
               END AS REGIMEN_AFILIADO,    
       AFI.SEXO SEXO, DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, HCA.FECHA, 'A') AS EDAD,    
       SED.DESCRIPCION SEDE, MES.DESCRIPCION AS ESPECIALIDAD, CAST (HCA.FECHA AS DATE) AS F_CONSULTA, COALESCE(HCA.IDDX,'') AS COD_CIE10, COALESCE(MDX.DESCRIPCION,'') AS NOMBRE_CIE10,     
       IART.DESCRIPCION AS NOM_MEDICAMENTO, CAST (HCA.FECHA AS DATE) AS F_ORDEN, HCATD.PRESCRIPCION PRESCRIPCION,     
    CAST(HCATD.TOTALUNIDADES AS DECIMAL(8,2)) CANTIDAD,  CAST(CASE WHEN HCATD.TIPODURACION = 'D' THEN HCATD.DURACION/24 ELSE HCATD.DURACION END AS DECIMAL(8,2)) DURACION,      
   CASE WHEN HCATD.TIPODURACION = 'M' THEN 'Meses'    
         WHEN HCATD.TIPODURACION = 'S' THEN 'Semanas'    
         WHEN HCATD.TIPODURACION = 'D' THEN 'Dias'    
         ELSE 'Horas'    
        end TIPODURACION,      
       AFI.CIUDAD AS COD_CIUDAD, CIU.NOMBRE AS NOMBRE_CIUDAD, MED.NOMBRE AS PROFESIONAL, AFI.TELEFONORES AS CELULAR, AFI.CELULAR AS OTROCELULAR, COALESCE(DEF_RUTA,'Modelo NO Definido') MODEL,    
       CASE WHEN HCA.PROCEDENCIA = 'QX' THEN 'HOSPITALARIA' ELSE 'AMBULATORIO' END AS PROCEDENCIA, HCA.PROCEDENCIA AS AMBITO,    
       CASE WHEN IART.IDITAR = '11' THEN 'MED NO PBS' ELSE 'MED PBS' END AS CLASF_MEDICAMENTO,    
       CASE WHEN IART.IDITAR = '12' THEN 'SI' ELSE 'NO' END AS MED_CONTROLADO,    
       CASE WHEN IART.IDITAR = '13' THEN 'SI' ELSE 'NO' END AS MED_UNIRS,   MED_BIOLOGICO='0' 
   --    CASE WHEN COALESCE(IART.BIOLOGICO,0) <> 0 THEN 'SI' ELSE 'NO' END AS MED_BIOLOGICO,IART.IDPRINACTIVO,IGEN.DESCRIPCION AS GENERICO  
FROM HCATD INNER JOIN SER  ON HCATD.IDSERVICIO = SER.IDSERVICIO    
           INNER JOIN IART ON SER.IDARTICULO   = IART.IDARTICULO    
           LEFT  JOIN IPAC ON IART.IDPRINACTIVO=IPAC.IDPRINACTIVO  
           LEFT  JOIN IGEN ON IART.IDGENERICO=IGEN.IDGENERICO  
           INNER JOIN HCA  ON HCA.CONSECUTIVO  = HCATD.CONSECUTIVO    
           LEFT  JOIN MDX  ON HCA.IDDX         = MDX.IDDX    
           INNER JOIN AFI  ON HCA.IDAFILIADO   = AFI.IDAFILIADO    
           LEFT  JOIN CIT  ON CIT.CONSECUTIVO  = HCA.CONSECUTIVOCIT    
           LEFT  JOIN PLN  ON PLN.IDPLAN       = CIT.IDPLAN    
           LEFT  JOIN SED  ON CIT.IDSEDE       = SED.IDSEDE    
           LEFT  JOIN MES  ON CIT.IDEMEDICA    = MES.IDEMEDICA    
           LEFT  JOIN CIU  ON CIU.CIUDAD       = AFI.CIUDAD    
           LEFT  JOIN MED  ON CIT.IDMEDICO     = MED.IDMEDICO    
           LEFT  JOIN TER  ON TER.IDTERCERO    = COALESCE(CIT.IDTERCEROCA, AFI.IDADMINISTRADORA)    
            LEFT JOIN (SELECT IDAFILIADO, AFIPE.IDPESPECIAL, PROT.ID, PROT.DESCRIPCION,     
                 CASE WHEN AFIPE.IDPESPECIAL = '000' THEN CASE WHEN AFIPE.IDPROT = 18 THEN 'Paciente en Estudio' else 'Paciente Cohorte'END    
                                                                  ELSE 'Otro Modelo'    
            END DEF_RUTA    
            FROM AFIPE INNER JOIN PROT ON AFIPE.IDPROT = PROT.ID     
            ) X ON X.IDAFILIADO = HCA.IDAFILIADO    
WHERE CAST(HCA.FECHA AS DATE) BETWEEN @1FINI AND @2FFIN AND CIT.IDTERCEROCA = CASE WHEN @3NIT= '' THEN CIT.IDTERCEROCA ELSE @3NIT ENd    
      AND COALESCE(IART.BIOLOGICO,0) = 1-- CASE WHEN COALESCE(@4SOLOBIO,'')='SI' THEN 1 ELSE COALESCE(IART.BIOLOGICO,0) END 
      AND HCATD.CODOM IN ('01')     
      AND HCA.PROCEDENCIA <> 'QX'    
--ORDER BY CAST (HCA.FECHA AS DATE), DOCIDAFILIADO    
GROUP BY AFI.TIPO_DOC , AFI.DOCIDAFILIADO ,      
       REPLACE(REPLACE(TRIM(AFI.PNOMBRE)  ,CHAR(13) + CHAR(10), ' '),CHAR(9), ' '),     
       REPLACE(REPLACE(TRIM(AFI.SNOMBRE)  ,CHAR(13) + CHAR(10), ' '),CHAR(9), ' '),     
       REPLACE(REPLACE(TRIM(AFI.PAPELLIDO),CHAR(13) + CHAR(10), ' '),CHAR(9), ' '),     
       REPLACE(REPLACE(TRIM(AFI.SAPELLIDO),CHAR(13) + CHAR(10), ' '),CHAR(9), ' '),     
       PLN.TIPOSISTEMA,     
               CASE WHEN AFI.TIPOAFILIADO = 'A' THEN 'ADICIONAL'    
                    WHEN AFI.TIPOAFILIADO = 'SB'THEN 'SUBSIDIADO'    
                    WHEN AFI.TIPOAFILIADO = 'J' THEN 'JUBILADO'    
                    WHEN AFI.TIPOAFILIADO = 'C' THEN 'CONTRIBUTIVO'    
                    WHEN AFI.TIPOAFILIADO = 'TA'THEN 'TOMADOR/AMPARADO'    
                    WHEN AFI.TIPOAFILIADO = 'S' THEN 'SUSTITUCIÓN PENSIONAL'    
                    WHEN AFI.TIPOAFILIADO = 'RE'THEN 'RÉGIMEN ESPECIALES O DE EXCEPCIÓN'    
                    WHEN AFI.TIPOAFILIADO = 'B' THEN 'BENEFICIARIO'    
                    WHEN AFI.TIPOAFILIADO = 'SR'THEN 'SIN RÉGIMEN'    
                    ELSE 'SIN DATO'    
               END,    
       AFI.SEXO, DBO.FNK_EDAD_ARS(AFI.FNACIMIENTO, HCA.FECHA, 'A') ,    
       SED.DESCRIPCION, MES.DESCRIPCION , CAST (HCA.FECHA AS DATE) , COALESCE(HCA.IDDX,'') , COALESCE(MDX.DESCRIPCION,'') ,     
       IART.DESCRIPCION , CAST (HCA.FECHA AS DATE) , HCATD.PRESCRIPCION ,     
    CAST(HCATD.TOTALUNIDADES AS DECIMAL(8,2)) ,  CAST(CASE WHEN HCATD.TIPODURACION = 'D' THEN HCATD.DURACION/24 ELSE HCATD.DURACION END AS DECIMAL(8,2)) ,      
   CASE WHEN HCATD.TIPODURACION = 'M' THEN 'Meses'    
         WHEN HCATD.TIPODURACION = 'S' THEN 'Semanas'    
         WHEN HCATD.TIPODURACION = 'D' THEN 'Dias'    
         ELSE 'Horas'    
        end ,      
       AFI.CIUDAD , CIU.NOMBRE , MED.NOMBRE , AFI.TELEFONORES , AFI.CELULAR , COALESCE(DEF_RUTA,'Modelo NO Definido'), IART.IDITAR, HCA.PROCEDENCIA,--COALESCE(IART.BIOLOGICO,0),     
       TER.RAZONSOCIAL ,IART.IDPRINACTIVO,IGEN.DESCRIPCION 