IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_PROCESO_VACACIONES' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_PROCESO_VACACIONES
END
GO
CREATE PROCEDURE DBO.SPK_PROCESO_VACACIONES 
@CNSPAGO  VARCHAR(20),
@PROCESO  VARCHAR(10),
@NUMDOCR   VARCHAR(20)=NULL
WITH ENCRYPTION
AS  
DECLARE @EXISTE INT
DECLARE @NUMDOC     VARCHAR(20)
DECLARE @CODCARGO   VARCHAR(20)
DECLARE @NIVEL      VARCHAR(10)
DECLARE @GRADO      VARCHAR(10)
DECLARE @FECHAING   DATETIME
DECLARE @FFINAL     DATETIME
DECLARE @FINICIAL   DATETIME
DECLARE @NPERIODOS  SMALLINT
DECLARE @ANOS       SMALLINT
DECLARE @MAX        SMALLINT
DECLARE @FECHARET   DATETIME
DECLARE @FECHACORTE DATETIME
DECLARE @F_ACTUALIZA DATETIME
BEGIN 
   SELECT @FECHACORTE=NULL
   IF COALESCE(@CNSPAGO,'')<>''
   BEGIN
      DECLARE PG_VACANOMI CURSOR FOR  
      SELECT NEMP.NUMDOC,CODCARGO,NIVEL,GRADO,FECHAINGRESO,NEDIA.FECHAFIN
      FROM NEMP INNER JOIN NEDIA ON NEMP.NUMDOC=NEDIA.NUMDOC
      WHERE EXISTS(SELECT * FROM NIEPE WHERE NEMP.NUMDOC=NIEPE.NUMDOC AND CNSPAGO=@CNSPAGO)
      AND NEDIA.CNSPAGO=@CNSPAGO
      AND NEDIA.IDEVENTO='RET'
      AND NEMP.NUMDOC=@NUMDOCR
   END
   ELSE
   BEGIN 
      DECLARE PG_VACANOMI CURSOR FOR  
      SELECT NUMDOC,CODCARGO,NIVEL,GRADO,FECHAINGRESO,COALESCE(FECHARETIRO,GETDATE())
      FROM NEMP
      WHERE ESTADO='Activo'
      AND COALESCE(FECHARETIRO,GETDATE()+1)>GETDATE()
      AND NUMDOC=CASE WHEN @NUMDOCR IS NULL THEN NUMDOC ELSE @NUMDOCR END
   END    
	OPEN PG_VACANOMI    
	FETCH NEXT FROM PG_VACANOMI    
	INTO @NUMDOC,@CODCARGO,@NIVEL,@GRADO,@FECHAING,@FECHARET
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
      PRINT '@NUMDOC='+@NUMDOC+ '@FECHARET='+CONVERT(VARCHAR,@FECHARET,103)
      SELECT  @F_ACTUALIZA=MAX(FECHAFIN)
      FROM NPER INNER JOIN NIEPE ON NPER.CNSPAGO=NIEPE.CNSPAGO
      WHERE NIEPE.NUMDOC=@NUMDOC
      AND NPER.CERRADO=1

      IF ISDATE(@FECHARET)=0
      BEGIN 
         SELECT @FECHACORTE=FECHAFIN FROM NPER WHERE CNSPAGO=@CNSPAGO
      END
      ELSE
      BEGIN
         SELECT @FECHACORTE=@FECHARET
      END
      IF ISDATE(@FECHACORTE)=0
      BEGIN 
         SELECT @FECHACORTE=@F_ACTUALIZA
      END
      PRINT '@FECHACORTE ='+CONVERT(VARCHAR,@FECHACORTE,103)
      IF EXISTS(SELECT * FROM NEMPV WHERE NUMDOC=@NUMDOC AND F_INICAL>@FECHACORTE)
      BEGIN
         PRINT 'Borramos periodos posteriores a la fecha de corte'
         DELETE NEMPV WHERE NUMDOC=@NUMDOC AND F_INICAL>=@FECHACORTE
      END
      SELECT @NPERIODOS=NVACACIONES FROM NCARNG WHERE CODCARGO=@CODCARGO AND NIVEL=@NIVEL AND GRADO=@GRADO
      SELECT @MAX=MAX(ITEM) FROM NEMPV WHERE NUMDOC=@NUMDOC
      IF NOT EXISTS(SELECT * FROM NEMPV WHERE NUMDOC=@NUMDOC) OR (SELECT MAX(F_FINAL) FROM NEMPV WHERE NUMDOC=@NUMDOC)<COALESCE(@FECHACORTE,GETDATE())
      BEGIN
         IF COALESCE(@NPERIODOS,0)>0
         BEGIN
            SELECT @ANOS=(DATEDIFF(DAY,@FECHAING,@FECHACORTE)/360.00)
            IF NOT EXISTS(SELECT * FROM NEMPV WHERE NUMDOC=@NUMDOC)
            BEGIN
               PRINT 'COLOCAMOS EL ULTIMO PERIODO'
               SELECT @FINICIAL= CASE WHEN CAST(CAST(DAY(@FECHAING) AS VARCHAR(2))+'/'+CAST(MONTH(@FECHAING) AS VARCHAR(2))+'/'+CAST(YEAR(GETDATE())AS VARCHAR(4)) AS datetime)>GETDATE() THEN
                     CAST(CAST(DAY(@FECHAING) AS VARCHAR(2))+'/'+CAST(MONTH(@FECHAING) AS VARCHAR(2))+'/'+CAST(YEAR(GETDATE())-1 AS VARCHAR(4)) AS datetime) ELSE
                     @FECHAING END
               SELECT @FFINAL=DATEADD(YEAR,1,@FINICIAL)       
            END
            ELSE
            BEGIN
               SELECT @FINICIAL=(F_FINAL+1) FROM NEMPV WHERE NUMDOC=@NUMDOC AND ITEM=@MAX
               SELECT @FFINAL=DATEADD(YEAR,1,@FINICIAL)
            END
            SELECT @MAX=COALESCE(@MAX,0)+1   
            INSERT INTO NEMPV(NUMDOC, ITEM, CONCEPTO, F_CUMPLE, NDIAS, F_INICAL, F_FINAL, CNSPAGO, ESTADO, DIASG, DIASP)
            SELECT @NUMDOC, @MAX, NULL, DATEADD(YEAR,@ANOS,@FECHAING), 15*@NPERIODOS, @FINICIAL, @FFINAL, NULL, 'Proceso', 0, 0

            UPDATE NEMPV SET DIASG=CASE WHEN F_FINAL<@FECHACORTE THEN 15 ELSE ((( 15*@NPERIODOS)*DATEDIFF(DAY,F_INICAL,CASE WHEN F_INICAL<=COALESCE(@FECHARET,@FECHACORTE) THEN F_INICAL ELSE COALESCE(@FECHARET,@FECHACORTE)END))/360.00) END
            WHERE NUMDOC=@NUMDOC AND ITEM=@MAX
         END
         IF COALESCE(@CNSPAGO,'')<>'' AND COALESCE(@NPERIODOS,0)>0
         BEGIN
            SELECT @MAX=MAX(ITEM) FROM NEMPV WHERE NUMDOC=@NUMDOC
            IF @PROCESO='CIERRE'
            BEGIN
               UPDATE NEMPV SET DIASG=DIASG+(NDIAS/12.00) WHERE NUMDOC=@NUMDOC AND ITEM=@MAX
            END
            IF @PROCESO='ABRE'
            BEGIN
               UPDATE NEMPV SET DIASG=DIASG-(NDIAS/12.00) WHERE NUMDOC=@NUMDOC AND ITEM=@MAX
            END
         END
      END
	  ELSE
	  BEGIN
		IF EXISTS( SELECT * FROM NEMPV WHERE NUMDOC=@NUMDOC AND ESTADO='Proceso')
		BEGIN
         PRINT 'VOY A ACTUALIZAR EL ITEM EN PROCESO...'
         PRINT '@FECHARET='+CONVERT(VARCHAR,@FECHARET,103)
         PRINT '@FECHACORTE'+CONVERT(VARCHAR,@FECHACORTE,103)

			UPDATE NEMPV SET DIASG= CASE WHEN F_FINAL<@FECHACORTE THEN 15 ELSE ((( 15.00*@NPERIODOS)*DATEDIFF(DAY,F_INICAL,CASE WHEN F_INICAL>=COALESCE(@FECHARET,@FECHACORTE) THEN F_INICAL ELSE COALESCE(@FECHARET,@FECHACORTE)END  ))/360) END,
         ESTADO=CASE WHEN F_FINAL<@FECHACORTE  THEN CASE WHEN  DIASP<NDIAS  THEN 'Cumplidas' ELSE 'Pagado' END  ELSE 'Proceso' END
			WHERE NUMDOC=@NUMDOC AND ESTADO='Proceso'
		END	
	  END
     IF COALESCE(@NPERIODOS,0)<=0
     BEGIN
        UPDATE NEMPV SET DIASG=0 WHERE NUMDOC=@NUMDOC AND ESTADO='Proceso'
     END
	FETCH NEXT FROM PG_VACANOMI    
	INTO @NUMDOC,@CODCARGO,@NIVEL,@GRADO,@FECHAING,@FECHARET
	END
	CLOSE PG_VACANOMI
	DEALLOCATE PG_VACANOMI   
END




