
UPDATE FTR SET FACTEP=NULL WHERE N_FACTURA='F002-00000017'

SELECT NOREFERENCIA,IDAFILIADO,* FROM FTR WHERE N_FACTURA='F002-00000017'

EXEC SPQ_JSON '{"MODELO":"FTR_PERU","METODO":"SOPORTES_FTREPE","PARAMETROS":{"N_FACTURA":"F002-00000017"}}'


SELECT * FROM CIT WHERE CONSECUTIVO='010496936231'
SELECT * FROM AUT WHERE CONSECUTIVOCIT='010496936231' AND EXISTS(SELECT * FROM LING WHERE NOPRESTACION=AUT.IDAUT)

SELECT * FROM HCA WHERE CONSECUTIVOCIT='010496936231' AND IDAFILIADO='0100002110'

SELECT  * FROM LING WHERE NOPRESTACION='0100000741'

SELECT  * FROM LORD WHERE NOINGRESO='0100000119'

SELECT * FROM USVGS WHERE DESCRIPCION LIKE '%PRODUCCION%'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"USVGS_COL","METODO":"VALORVARIABLE","PARAMETROS":{"IDVARIABLE":"FACTSEDE"},"USUARIO":"JJIMENEZ"}'


SELECT COALESCE(FTR.FACTEP,''), FTR.N_FACTURA,FTR.LINKFACTURA,FTR.IDTERCERO,TER.TIPO_ID,TER.NIT,TER.RAZONSOCIAL,FTR.F_FACTURA,FTR.F_VENCE,FTR.PROCEDENCIA,
FTR.NOREFERENCIA,FTR.IDPLAN,FTR.VALORSERVICIOS,CASE COALESCE(COPAPROPIO,0) WHEN 1 THEN CP_VLR_COPAGOS ELSE VALORCOPAGO END VALORCOPAGO,
VALORMODERADORA,FTR.VR_TOTAL,FTR.ESTADO,COALESCE(FTR.TIPOANULACION,'') NC,
CASE COALESCE(FACTE,0) WHEN 0 THEN 'Sin Notificar' WHEN 1 THEN 'En Cola' WHEN 2 THEN 'Notificada' WHEN 3  
THEN 'Con Errores' WHEN 4 THEN  'Procesando' END ESTDIAN,FTR.CONTABILIZADA,FTR.CNSFCT AS CNSFTR,FTR.VR_ABONOS AS ABONOS ,
FTR.CAPITADA,CP_CONVENIO AS CONVENIO,COPAGOP = COALESCE(COPAPROPIO,0),VLRCOPAPRO = COALESCE(CP_VLR_COPAGOS,0),DESCUENTO,
F_INICIAL = FECHACAP_INI,F_FINAL = FECHACAP_FIN,FTR.IDSEDE,CP_MES AS MES,MODALIDAD = CP_MODALIDAD,FTR.OBSERVACION,
TIPOFINAN = TIPOFIN,PLN.DESCPLAN,USUARIOFACTURA,CP_VLR_SERVICIOS,CP_VLR_COPAGOS,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,AFI.EDAD,
COALESCE(FTR.NROCOMPROBANTE,'')NROCOMPROBANTE,CASE WHEN EXISTS(SELECT 1 FROM FTRAUD WHERE FTRAUD.N_FACTURA = FTR.N_FACTURA) THEN 'Con Nota' 
ELSE 'Sin Nota' END AS ESTNOTAUD,FACTEP =
CASE COALESCE(FACTEP,'') WHEN '' THEN 'Sin Notificar' WHEN '103' THEN 'Error Valida' WHEN '104' THEN 'Rechazado' WHEN '104A' THEN 'Rechazado-api' WHEN '105' THEN 'Anulada' WHEN '108' THEN 'Baja' ELSE 'OK' END,
SINCNT=COALESCE(SINCNT,0),COALESCE(FTR.ULRPTAAPI,'')ULRPTAAPI,FTR.TIPOVENTA,FTR.CUOTAS,FTR.N_FACT_EXTERNO,FTR.TIPOFIN  
FROM [dbo].[FTR] INNER JOIN  TER ON FTR.IDTERCERO=TER.IDTERCERO  LEFT JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO 
LEFT JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN WHERE (FTR.N_FACTURA LIKE '%%%%' OR  TER.RAZONSOCIAL LIKE '%%%%') 
AND 1=1 AND CONVERT(DATE, FTR.F_FACTURA) >=  '2024-09-02' AND CONVERT(DATE, FTR.F_FACTURA) <= '2024-12-27' 
AND COALESCE(FTR.FACTEP,'')='101'  AND COALESCE(FTR.IDSEDE,'')='01'  
ORDER BY  FTR.FECHAFAC DESC, FTR.N_FACTURA DESC  OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 