USE KPCEM


SELECT  * FROM ACJ WHERE CODCAJA='C001'

UPDATE USUSU SET IDDEPURAR=1 WHERE USUARIO='JJIMENEZ'

 EXISTS(SELECT * FROM TGEN WHERE A.FORMAPAGO=TGEN.CODIGO AND CAMPO='FORMAPAGO' AND TABLA='')

  EXISTS(SELECT * FROM TGEN WHERE A.FORMAPAGO=TGEN.CODIGO AND CAMPO='FORMAPAGO' AND TABLA='')