CREATE OR ALTER PROCEDURE DBO.SPQ_TURNOS_NOMINA @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
DECLARE @ANO VARCHAR(4)                   ,@MES SMALLINT                  ,@IDUSUARIO VARCHAR(20)

BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='TRAER_DATOS'     
   BEGIN         
      SELECT @ANO=ANO,@MES=MES,@IDUSUARIO=IDUSUARIO      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      ANO VARCHAR(4) '$.ANO',
      MES INT   '$.MES',
      IDUSUARIO VARCHAR(20) '$.IDUSUARIO'
      )
      
      BEGIN TRY           
          EXEC SPK_RESUMEN_TURNOS @ANO,@MES,@IDUSUARIO                
      END TRY
      BEGIN CATCH
              INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 

   END  

END