CREATE OR ALTER VIEW DBO.VWK_ESTADODIAN_FTRE
AS
SELECT FTR.CNSFCT,PREFIJODIANFE,CNSDIANFE, FTR.N_FACTURA,CONVERT(VARCHAR,FTR.F_FACTURA,103)F_FACTURA,FTR.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,FTR.FACTE,
CASE COALESCE(FTR.FACTE,0) WHEN 0 THEN 'Pendiente' WHEN 1 THEN 'EnCola' WHEN 2 THEN 'Notificada' WHEN 3 THEN 'Errores' WHEN 4 THEN 'Revision' ELSE 'NoDefinido' END ESTDIAN,
TIPODOC='FACTURA',FTR.MARCA,COALESCE(EQUIMARCA,'')EQUIMARCA,FTR.IDSEDE,FTR.IDPLAN,FTR.VR_TOTAL,FTR.PROCEDENCIA,COALESCE(CONVERT(VARCHAR,FTRE.FECHA,103),'')FECHANOTI,
CASE WHEN COALESCE(FTRE.NOTIFICADO,0) =1 THEN 'Enviada' ELSE 'SinEnviar' END NOTICLIENTE,FTR.F_FACTURA AS FECHADOC,FTR.USUARIOFACTURA,FTR.TIPOANULACION,
CASE WHEN COALESCE(FTR.CUV,'')='' THEN 'SinValidar' ELSE 'Validado' END ESTRIPS
FROM FTR INNER JOIN FDIAN ON FTR.CNSRESOL=FDIAN.CNSRESOL
           INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
           LEFT  JOIN FTRE ON FTR.N_FACTURA=FTRE.FTRN_FACTURA AND FTR.CNSDIANFE=FTRE.N_FACTURA AND FTR.PREFIJODIANFE=FTRE.PREFIJO
WHERE COALESCE(FDIAN.FTRELECTRONICA,0)=1
AND FDIAN.PROCEDENCIA IN('FTR','FPOS')
AND COALESCE(FTR.SI,0)=0
AND COALESCE(FTR.ESTADO,'')='P'
AND COALESCE(FTR.CONTABILIZADA,0)<>0 
--AND COALESCE(FTR.TIPOANULACION,'')<>'NC' --storres
AND COALESCE(FTR.VR_TOTAL,0)>0
UNION ALL 
SELECT FNOT.CNSFNOT, FTR.PREFIJODIANFE,FTR.CNSDIANFE, FTR.N_FACTURA,CONVERT(VARCHAR,FNOT.F_NOTA,103)F_FACTURA,FTR.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,COALESCE(FNOT.FACTE,0)FACTE,
CASE COALESCE(FNOT.FACTE,0) WHEN 0 THEN 'Pendiente' WHEN 1 THEN 'EnCola' WHEN 2 THEN 'Notificada' WHEN 3 THEN 'Errores' WHEN 4 THEN 'Revision' ELSE 'NoDefinido' END ESTDIAN,
TIPODOC='NOTACR',FTR.MARCA,COALESCE(EQUIMARCA,'')EQUIMARCA,FTR.IDSEDE,FTR.IDPLAN,FNOT.VR_TOTAL,FTR.PROCEDENCIA,COALESCE(CONVERT(VARCHAR,FTRE.FECHA,103),'')FECHANOTI,
CASE WHEN COALESCE(FTRE.NOTIFICADO,0) =1 THEN 'Enviada' ELSE 'SinEnviar' END NOTICLIENTE,FNOT.F_NOTA AS FECHADOC,FNOT.USUARIO,FTR.TIPOANULACION,
CASE WHEN COALESCE(FTR.CUV,'')='' THEN 'SinValidar' ELSE 'Validado' END ESTRIPS
FROM FNOT INNER JOIN FTR  ON FNOT.N_FACTURA=FTR.N_FACTURA
           INNER JOIN FDIAN ON FTR.CNSRESOL=FDIAN.CNSRESOL
           INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
           LEFT  JOIN FTRE ON FTR.N_FACTURA=FTRE.FTRN_FACTURA AND FNOT.CNSFNOT=FTRE.N_FACTURA
WHERE COALESCE(FDIAN.FTRELECTRONICA,0)=1
AND FDIAN.PROCEDENCIA='FTR'
AND FNOT.ESTADO='O'
AND FNOT.CLASE='C'
AND COALESCE(FTR.SI,0)=0
AND COALESCE(FNOT.VR_TOTAL,0)>0
UNION ALL 
SELECT FNOT.CNSFNOT, FTR.PREFIJODIANFE,FTR.CNSDIANFE, FTR.N_FACTURA,CONVERT(VARCHAR,FNOT.F_NOTA,103)F_FACTURA,FTR.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,COALESCE(FNOT.FACTE,0)FACTE,
CASE COALESCE(FNOT.FACTE,0) WHEN 0 THEN 'Pendiente' WHEN 1 THEN 'EnCola' WHEN 2 THEN 'Notificada' WHEN 3 THEN 'Errores' WHEN 4 THEN 'Revision' ELSE 'NoDefinido' END ESTDIAN,
TIPODOC='NOTADB',FTR.MARCA,COALESCE(EQUIMARCA,'')EQUIMARCA,FTR.IDSEDE,FTR.IDPLAN,FNOT.VR_TOTAL,FTR.PROCEDENCIA,COALESCE(CONVERT(VARCHAR,FTRE.FECHA,103),'')FECHANOTI,
CASE WHEN COALESCE(FTRE.NOTIFICADO,0) =1 THEN 'Enviada' ELSE 'SinEnviar' END NOTICLIENTE,FNOT.F_NOTA AS FECHADOC,FNOT.USUARIO,FTR.TIPOANULACION,
CASE WHEN COALESCE(FTR.CUV,'')='' THEN 'SinValidar' ELSE 'Validado' END ESTRIPS
FROM FNOT INNER JOIN FTR  ON FNOT.N_FACTURA=FTR.N_FACTURA
           INNER JOIN FDIAN ON FTR.CNSRESOL=FDIAN.CNSRESOL
           INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
           LEFT  JOIN FTRE ON FTR.N_FACTURA=FTRE.FTRN_FACTURA AND FNOT.CNSFNOT=FTRE.N_FACTURA
WHERE COALESCE(FDIAN.FTRELECTRONICA,0)=1
AND FDIAN.PROCEDENCIA='FTR'
AND FNOT.ESTADO='O'
AND FNOT.CLASE='D'
AND COALESCE(FTR.SI,0)=0
AND COALESCE(FNOT.VR_TOTAL,0)>0


