SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC


EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"ASFE93790"},"USUARIO":"JJIMENEZ"}'

SELECT FTRD.IDCIRUGIA,SER.DESCSERVICIO,REFERENCIA,ANEXO,SUM(FTRD.VLR_SERVICI) VLR_SERVICI
FROM FTRD INNER JOIN SER ON FTRD.IDCIRUGIA=SER.IDSERVICIO 
WHERE N_FACTURA='ASFE93790' AND FTRD.PREFIJO='00'
GROUP BY FTRD.IDCIRUGIA,SER.DESCSERVICIO,REFERENCIA,ANEXO

SELECT  * FROM USVGS WHERE DESCRIPCION LIKE '%PREFIJO%CIRUGIA%'