               DECLARE @NUMDOC VARCHAR(20)='0600012986'
               DECLARE @NUMDOCVAC VARCHAR(20)
               DECLARE @ITEMVAC INT
               DECLARE @CNSPAGO VARCHAR(20)='02202309P30-1'
               DECLARE @DIASR SMALLINT
               DECLARE PG_CURSOR CURSOR FOR 
               SELECT NUMDOC,ITEM FROM NEMPV 
               WHERE NUMDOC=@NUMDOC 
               GROUP BY NUMDOC,ITEM
               ORDER BY NUMDOC,ITEM
               OPEN PG_CURSOR    
               FETCH NEXT FROM PG_CURSOR    
               INTO @NUMDOCVAC,@ITEMVAC
               WHILE @@FETCH_STATUS = 0    
               BEGIN 
                  IF EXISTS(SELECT * FROM NEMPVD WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMVAC AND EVENTO='RET' )
                  BEGIN
                     SELECT @DIASR=NDIAS FROM NEMPVD WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMVAC AND CNSPAGO=@CNSPAGO  AND EVENTO='RET'  
                     DELETE NEMPVD WHERE NUMDOC=@NUMDOC AND   CNSPAGO=@CNSPAGO AND ITEM=@ITEMVAC AND EVENTO='RET'
                     UPDATE NEMPV SET DIASP=DIASP-@DIASR WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMVAC
                     UPDATE NEMPV SET ESTADO=CASE WHEN DIASG=DIASP THEN 'Cumplidas' else 'Proceso' END WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMVAC
                  END                   
                  FETCH NEXT FROM PG_CURSOR    
                  INTO @NUMDOCVAC,@ITEMVAC
               END
               CLOSE PG_CURSOR
               DEALLOCATE PG_CURSOR

               EXEC SPK_PROCESO_VACACIONES '','ACTULIZA','0100000924'

               EXEC SPK_PROCESO_VACACIONES '02202309P30-1','ACTUALIZA','0600012986'

               EXEC SPK_CALCULAR_RETIROS '02202309P30-1','0100000924'

               SELECT * FROM NEMP

               SELECT * FROM NEMPV WHERE NUMDOC='0600012986'
               SELECT * FROM NEMPVD WHERE NUMDOC='0600012986'

               SELECT DATEDIFF(DAY,'10/08/2023','30/09/2023')

               SELECT (1682000/30)*34.12

               SELECT 1969622/ 56066

               SELECT  * FROM PTPAG

               SELECT NUMDOC,ITEM,SUM((DIASG-COALESCE(DIASP,0)))  FROM NEMPV 
               WHERE NUMDOC='0100000924' 
               GROUP BY NUMDOC,ITEM
               HAVING SUM(DIASG-COALESCE(DIASP,0)) >0
               ORDER BY NUMDOC,ITEM

              -- UPDATE NEMPV SET DIASP=0  WHERE NUMDOC='0600012809' AND ITEM>1

              --UPDATE NEMPV SET DIASP=0 WHERE NUMDOC='0600012986' AND ITEM=1