CREATE OR ALTER PROCEDURE DBO.SPK_GENERA_JSON_PERU_FTR_INTEGRA 
@N_FACTURA  VARCHAR(20)
WITH ENCRYPTION
AS 
DECLARE @JSON VARCHAR(MAX)
DECLARE @JSOND VARCHAR(MAX)
DECLARE @CODDOC VARCHAR(4)
DECLARE @PREFACT VARCHAR(4)
DECLARE @NFACTURA VARCHAR(20)
DECLARE @F_EMISION VARCHAR(10)
DECLARE @H_EMISION VARCHAR(8)
DECLARE @F_VENCE   VARCHAR(10)
DECLARE @TIPODOC   VARCHAR(2)
DECLARE @CODPAIS1  VARCHAR(3)
DECLARE @PERINICIAL  VARCHAR(10)
DECLARE @PERFINAL  VARCHAR(10)
DECLARE @NOADMISION  VARCHAR(20)
DECLARE @GUIA1  VARCHAR(20)
DECLARE @TGUIA1 VARCHAR(2)
DECLARE @GUIA2  VARCHAR(20)
DECLARE @TGUIA2 VARCHAR(2)
DECLARE @NITEMISOR VARCHAR(20)
DECLARE @DVEMISIOR VARCHAR(1)
DECLARE @RAZONSOCIALEMI VARCHAR(125)
DECLARE @CODPOSTALEMI VARCHAR(10)
DECLARE @DIRECCIOEMI VARCHAR(255)
DECLARE @CIUDADEMI   VARCHAR(45)
DECLARE @DEPAREMI   VARCHAR(45)
DECLARE @DISTRIEMI   VARCHAR(45)
DECLARE @PAISEMI   VARCHAR(2)
DECLARE @NITRECEP VARCHAR(20)
DECLARE @DVRECEP VARCHAR(1)
DECLARE @RAZONSOCIALRECEP VARCHAR(125)
DECLARE @CODPOSTALRECEP VARCHAR(10)
DECLARE @DIRECCIORECEP VARCHAR(255)
DECLARE @CIUDADRECEP   VARCHAR(45)
DECLARE @DEPARRECEP   VARCHAR(45)
DECLARE @DISTRIRECEP  VARCHAR(45)
DECLARE @PAISRECEP   VARCHAR(2)
DECLARE @CODSUNAT   VARCHAR(4)
DECLARE @VR_BRUTO DECIMAL(14,2)
DECLARE @VR_AFECTO DECIMAL(14,2)
DECLARE @VR_INAFECTO DECIMAL(14,2)
DECLARE @VR_COPAFECTO DECIMAL(14,2)
DECLARE @VR_COPINAFECTO DECIMAL(14,2)
DECLARE @VR_IVA DECIMAL(14,2)
DECLARE @NOMBREI VARCHAR(1)
DECLARE @CODIMP  VARCHAR(4)
DECLARE @IMP     VARCHAR(4)
DECLARE @CODINTER VARCHAR(4)
DECLARE @VR_BRUTO1 DECIMAL(14,2)
DECLARE @VR_NETO DECIMAL(14,2)
DECLARE @VR_IVA1 DECIMAL(14,2)
DECLARE @PVIVA   DECIMAL(7,2)
DECLARE @VR_LETRAS VARCHAR(2048)
DECLARE @DNI   VARCHAR(20)
DECLARE @NOMBEPTE VARCHAR(120)
DECLARE @VRCOPAGO DECIMAL(14,2)
DECLARE @LEYENDA VARCHAR(520)
DECLARE @BOLETA TABLE(N_FACTURA VARCHAR(20), VALOR DECIMAL(14,2),ID INT IDENTITY(1,1))
DECLARE @OBSERVACION VARCHAR(255)
DECLARE @NBOLE INT
DECLARE @B     INT
DECLARE @PORCO DECIMAL(7,4)
DECLARE @PORCOAFE DECIMAL(7,4)
DECLARE @PORCOINA DECIMAL(7,4)
DECLARE @ITEM VARCHAR(4)
DECLARE @CANTIDAD VARCHAR(4)
DECLARE @VALOR1 VARCHAR(20)
DECLARE @VALOR2 VARCHAR(20)
DECLARE @VALOR3 VARCHAR(20)
DECLARE @VALOR4 VARCHAR(20)
DECLARE @VALOR5 VARCHAR(20)
DECLARE @VALOR6 VARCHAR(20)
DECLARE @ANEXO VARCHAR(255)
DECLARE @REFERENCIA VARCHAR(20)
DECLARE @VALOR7 VARCHAR(20)
DECLARE @RPTA TABLE(ID INT,DATOS VARCHAR(500))
DECLARE @OK VARCHAR(10)
DECLARE @AFECTA SMALLINT
DECLARE @MIXTA BIT
DECLARE @FACTEP VARCHAR(10)
DECLARE @ERFACTEP VARCHAR(60)
DECLARE @ESPAQ BIT
DECLARE @TIPOFACT VARCHAR(2) --INDIVIDUAL,MASIVA
DECLARE @CORRELATIVO VARCHAR(20)
DECLARE @MAILRECEPTOR VARCHAR(256)
DECLARE @USUARIOFACT VARCHAR(20)
DECLARE @NROITEM SMALLINT
DECLARE @TOKEN VARCHAR(50)
DECLARE @CODQR VARCHAR(100)
DECLARE @CODHASH VARCHAR(50)
DECLARE @ESTDOC  VARCHAR(10)
DECLARE @URLFACTEP VARCHAR(256)
DECLARE @DESCSUNAT VARCHAR(MAX)
DECLARE @ERRORES VARCHAR(MAX)
DECLARE @sUrl VARCHAR(MAX) 
DECLARE @obj INT
DECLARE @valorDeRegreso INT
DECLARE @response VARCHAR(8000)
DECLARE @src VARCHAR(255)
DECLARE @desc VARCHAR(255)
DECLARE @URLFACT VARCHAR(255)
DECLARE @BODY VARCHAR(MAX)
DECLARE @PAQUETE BIT
DECLARE @DIASVENCE SMALLINT
DECLARE @F_FACTURA DATETIME
DECLARE @MNT_PENDIENTE VARCHAR(20)
DECLARE @NCUOTAS SMALLINT
DECLARE @VLR_CUOTA DECIMAL(14,2)
DECLARE @VLR_PENDIENTE DECIMAL(14,2)
DECLARE @PROCEDENCIAFTR VARCHAR(20)
BEGIN  
   PRINT 'EXEC DBO.SPK_GENERA_JSON_PERU_FTR_INTEGRA '''+@N_FACTURA+''''

   SELECT @FACTEP=FTR.FACTEP,@ERFACTEP=RAZONANULACION,@CODDOC='0101',@PREFACT=REPLACE(FDIAN.PREFIJO,'-',''),@NFACTURA=FTR.N_FACTURA,@F_FACTURA=F_FACTURA,@F_EMISION=REPLACE(CONVERT(VARCHAR,F_FACTURA,102),'.','-'),
   @H_EMISION=REPLACE(CONVERT(VARCHAR,F_FACTURA,108),'.','-'),@F_VENCE= REPLACE(CONVERT(VARCHAR,F_VENCE,102),'.','-'),@TIPODOC= CASE WHEN TIPOFIN='N' THEN '03' ELSE '01' END,@CODPAIS1='PEN',
   @PERINICIAL=REPLACE(CONVERT(VARCHAR,CAST('01/'+CASE WHEN MONTH(F_FACTURA)<10 THEN '0' ELSE '' END+CAST(MONTH(F_FACTURA) AS VARCHAR(2))+'/'+CAST(YEAR(F_FACTURA) AS VARCHAR(4))AS DATETIME),102),'.','-'),
   @PERFINAL=REPLACE(CONVERT(VARCHAR,CAST('01/'+CASE WHEN MONTH(F_FACTURA)<10 THEN '0' ELSE '' END+CAST(MONTH(F_FACTURA) AS VARCHAR(2))+'/'+CAST(YEAR(F_FACTURA) AS VARCHAR(4)) AS DATETIME)+29,102),'.','-'),
   @NOADMISION=FTR.NOREFERENCIA,@GUIA1='T001-00000001',@TGUIA1='09',@GUIA2='T001-00000002',@TGUIA2='99',
   @DNI=CASE WHEN LEN( AFI.DOCIDAFILIADO)=8 THEN  AFI.DOCIDAFILIADO 
		     WHEN LEN(AFI.DOCIDAFILIADO)<8 THEN REPLACE(SPACE(8-LEN(AFI.DOCIDAFILIADO)),SPACE(1),0)+AFI.DOCIDAFILIADO
			 ELSE RIGHT(AFI.DOCIDAFILIADO,8)
	   END,
   @NOMBEPTE=dbo.FNK_LIMPIATEXTO(AFI.NOMBREAFI,'0-9 A-Z().;:,'),
   @VRCOPAGO=FTR.VALORCOPAGO,@AFECTA=CASE WHEN FTR.VIVA>0 THEN 1 ELSE 0 END,
   @TIPOFACT=FTR.TIPOFAC,@PAQUETE=COALESCE(PAQUETE,0),@USUARIOFACT=FTR.USUARIOFACTURA,
   @NCUOTAS=COALESCE(FTR.CUOTAS,1),@PROCEDENCIAFTR=FTR.PROCEDENCIA
   FROM FTR INNER JOIN FDIAN ON FTR.CNSRESOL=FDIAN.CNSRESOL
            LEFT  JOIN AFI  ON FTR.IDAFILIADO=AFI.IDAFILIADO
   WHERE FTR.N_FACTURA=@N_FACTURA
   AND FDIAN.PROCEDENCIA=CASE WHEN FTR.TIPOFIN='N' THEN 'BOLE' ELSE 'FTR' END

   IF EXISTS(SELECT * FROM FTRE WHERE FTRN_FACTURA=@N_fACTURA)
   BEGIN
	   PRINT 'Ya fue enviada mi factura'
      RETURN
   END

   SELECT @CORRELATIVO= RIGHT(@N_FACTURA,LEN(@N_FACTURA)-(LEN(@PREFACT)+1))
   SELECT @NITEMISOR= NIT,@DVEMISIOR=6,@RAZONSOCIALEMI=dbo.FNK_LIMPIATEXTO(RAZONSOCIAL,'0-9 A-Z().;:,'),@CODPOSTALEMI='150101',@DIRECCIOEMI=DIRECCION,@CIUDADEMI=CIU.NOMBRE,
   @DEPAREMI=DEP.NOMBRE,@DISTRIEMI='',@PAISEMI='PE',@MAILRECEPTOR=COALESCE(TER.EMAIL,'')
   FROM TER LEFT JOIN CIU ON TER.CIUDAD=CIU.CIUDAD
           LEFT JOIN DEP ON CIU.DPTO =DEP.DPTO
   WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')


   SELECT @NITRECEP=CASE WHEN FTR.IDTERCERO=FTR.IDAFILIADO AND COALESCE(TER.RUC,'')<> '' AND FTR.TIPOFIN='C' THEN RUC ELSE NIT END ,
          @DVRECEP=CASE WHEN FTR.IDTERCERO=FTR.IDAFILIADO AND COALESCE(TER.RUC,'')<> '' AND FTR.TIPOFIN='C'  THEN 6 ELSE CONVERT(VARCHAR(1),CONVERT(INT,COALESCE(TGEN.VALOR1,0))) END,
          @RAZONSOCIALRECEP=dbo.FNK_LIMPIATEXTO(RAZONSOCIAL,'0-9 A-Z().;:,'),@CODPOSTALRECEP='150101',@DIRECCIORECEP= dbo.FNK_LIMPIATEXTO(DIRECCION,'0-9 A-Z().;:,'),@CIUDADRECEP=CIU.NOMBRE,
   @DEPARRECEP=DEP.NOMBRE,@DISTRIRECEP='',@PAISRECEP='PE',@CODSUNAT='0000'
   FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
            LEFT JOIN CIU ON TER.CIUDAD=CIU.CIUDAD
            LEFT JOIN DEP ON CIU.DPTO =DEP.DPTO
            LEFT JOIN TGEN ON TER.TIPO_ID =TGEN.CODIGO AND TGEN.TABLA='General' AND TGEN.CAMPO='TIPOIDSUNAT'
   WHERE FTR.N_FACTURA=@N_FACTURA

   IF @DVRECEP='1' AND LEN(@NITRECEP)<>8
   BEGIN
	  SELECT @NITRECEP=CASE WHEN LEN(@NITRECEP)=8 THEN  @NITRECEP
		     WHEN LEN(@NITRECEP)<8 THEN REPLACE(SPACE(8-LEN(@NITRECEP)),SPACE(1),0)+@NITRECEP
			 ELSE RIGHT(@NITRECEP,8) END
   END

   SELECT @LEYENDA='SITEDS:'+CAST(COALESCE(dbo.FNK_LIMPIATEXTO(VENDEDOR,'0-9 A-Z'),'') AS VARCHAR(20)) 
   FROM FTR WHERE N_FACTURA=@N_FACTURA

   SELECT @ESPAQ= CASE WHEN COUNT(*)>0 THEN 1 ELSE 0 END FROM FTRD WHERE N_FACTURA=@N_FACTURA AND COALESCE(PAQUETE,0)=2


	SELECT @LEYENDA=@LEYENDA+CASE WHEN COALESCE(PPT.PSEDEAT,0)=1 THEN '  // TIPO CONVENIO:'+ CASE WHEN @ESPAQ= 1 THEN  CAST(SUBSTRING(PPT.RESUMEN,1,50)  AS VARCHAR(50)) ELSE 'PAGO POR SERVICIO' END+' // SEDE ATENCION: '+COALESCE(SEDEAT,'00') ELSE '' END,
         @DIASVENCE=CASE WHEN @TIPODOC='01' THEN CASE WHEN COALESCE(PPT.DIASVTO,0)<=0 THEN 30 ELSE PPT.DIASVTO END ELSE 0 END
         FROM FTR LEFT JOIN HADMAUT ON FTR.VENDEDOR=HADMAUT.AUTORIZACION 
			 LEFT JOIN PPT ON FTR.IDTERCERO=PPT.IDTERCERO AND FTR.IDPLAN=PPT.IDPLAN
	WHERE FTR.N_FACTURA=@N_FACTURA
	AND HADMAUT.NOADMISION=@NOADMISION

   IF COALESCE(@ESPAQ,0)=1 
   BEGIN
      DECLARE @DATOSERPAQ VARCHAR(255)
      DECLARE @IDSERPAQ    VARCHAR(20)
      SELECT @DATOSERPAQ=LTRIM(RTRIM(OBS)),@IDSERPAQ=IDSERVICIOPAQUETE FROM HADM WHERE NOADMISION=@NOADMISION
      IF @DATOSERPAQ IS NULL OR LEN(COALESCE(@DATOSERPAQ,''))=0
      BEGIN
         SELECT @DATOSERPAQ=NULL
      END
   END

   SELECT @VR_IVA=VIVA,@NOMBREI='S',@CODIMP='1000',@IMP='IGV',@CODINTER='VAT'
   FROM FTR 
   WHERE FTR.N_FACTURA=@N_FACTURA

   SELECT  @VR_BRUTO=SUM((COALESCE(VALOR,0)*COALESCE(CANTIDAD,0))),@VR_BRUTO1=SUM((COALESCE(VALOR,0)*COALESCE(CANTIDAD,0))+CASE WHEN COALESCE(PIVA,0)>0 THEN  (COALESCE(VALOR,0)*COALESCE(CANTIDAD,0))*(PIVA/100)ELSE 0 END)
   FROM FTRD 
   WHERE FTRD.N_FACTURA=@N_FACTURA
   AND COALESCE(PAQUETE,0)<>2

   SELECT
   @VR_AFECTO=SUM(CASE WHEN COALESCE(PIVA,0)>0 THEN VLRIMPUESTO ELSE 0 END),
   @VR_INAFECTO=SUM(CASE WHEN COALESCE(PIVA,0)=0 THEN (COALESCE(VALOR,0)*COALESCE(CANTIDAD,0))-(COALESCE(FTRD.VLR_COPAGOS,0)) ELSE 0 END),
	@VR_COPAFECTO=SUM(CASE WHEN COALESCE(PIVA,0)>0 THEN COALESCE(FTRD.VLR_COPAGOS,0) ELSE 0 END ),
	@VR_COPINAFECTO=SUM(CASE WHEN COALESCE(PIVA,0)=0 THEN COALESCE(FTRD.VLR_COPAGOS,0) ELSE 0 END )
   FROM FTRD 
   WHERE FTRD.N_FACTURA=@N_FACTURA
   AND COALESCE(PAQUETE,0)<>2

   IF COALESCE(@VR_AFECTO,0)+COALESCE(@VR_INAFECTO,0)<=0
   BEGIN
      PRINT 'Sin valores Me devuelvo'
      RETURN
   END


   IF COALESCE(@VR_AFECTO,0)>0 AND COALESCE(@VR_INAFECTO,0)>0
   BEGIN
      SELECT @MIXTA=1
      SELECT @PORCOAFE=(@VR_COPAFECTO*100/@VR_AFECTO)/100,@PORCOINA=(@VR_COPINAFECTO*100/@VR_INAFECTO)/100
   END
   ELSE
   BEGIN
      SELECT @MIXTA=0,@PORCOAFE=0,@PORCOINA=0
   END


   SELECT @VR_NETO=VR_TOTAL,@VR_IVA1=COALESCE(VIVA,0),@VR_LETRAS= DBO.FNK_DE_VALORES_A_LETRAS(VR_TOTAL)
   FROM FTR 
   WHERE FTR.N_FACTURA=@N_FACTURA

   IF COALESCE(@VRCOPAGO,0)>0
   BEGIN
      SELECT @PORCO=(@VRCOPAGO*100/@VR_BRUTO)/100
      IF @PAQUETE=1
      BEGIN
         SELECT @VR_AFECTO=@VR_AFECTO-@VRCOPAGO
      END
   END
   ELSE
   BEGIN
      SELECT @PORCO=0.00
   END
   SELECT @MNT_PENDIENTE=''
   IF @TIPODOC='01' --FACTURA
   BEGIN
      IF COALESCE(@VR_IVA,0)>0
      BEGIN
         IF COALESCE(@VR_NETO,0)>=700
         BEGIN
            SELECT @MNT_PENDIENTE=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),ROUND(@VR_NETO-(@VR_NETO*0.12),2)))
            SELECT @VLR_PENDIENTE=ROUND(@VR_NETO-(@VR_NETO*0.12),2)
         END
         ELSE
         BEGIN
            SELECT @MNT_PENDIENTE=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),ROUND(@VR_NETO,2)))
            SELECT @VLR_PENDIENTE=ROUND(@VR_NETO,2)
         END
      END
      IF COALESCE(@NCUOTAS,1)>1 
      BEGIN
         SELECT @VLR_CUOTA=ROUND((@VLR_PENDIENTE/@NCUOTAS),2)
      END
   END
   
   IF NOT EXISTS (SELECT * FROM FTR WHERE FTR.TIPOFIN='N' AND N_FACTURA=@N_FACTURA)
   BEGIN
      INSERT INTO @BOLETA(N_FACTURA,VALOR)
      SELECT HPRED.N_FACTURAH,SUM(COALESCE(HPRED.VALORCOPAGO,0))
      FROM FTRD INNER JOIN HPRED ON FTRD.NOPRESTACION=HPRED.NOPRESTACION AND HPRED.NOITEM=FTRD.NOITEM AND HPRED.N_FACTURA=FTRD.N_FACTURA
      WHERE FTRD.N_FACTURA=@N_FACTURA
      AND COALESCE(HPRED.N_FACTURAH,'')<>'' AND COALESCE(HPRED.VALORCOPAGO,0)>0
      GROUP BY HPRED.N_FACTURAH

      SELECT @OBSERVACION=''
      IF(SELECT COUNT(*) FROM @BOLETA)>0
      BEGIN
         SELECT @NBOLE=COUNT(*), @B=1 FROM @BOLETA

         SELECT @OBSERVACION='Boletas de Venta:'
         WHILE(@B<=@NBOLE)
         BEGIN
            SELECT @OBSERVACION=@OBSERVACION+' '+N_FACTURA+'  Valor: s/'+CONVERT(VARCHAR(20),VALOR)  FROM @BOLETA WHERE ID=@B AND  N_FACTURA<>'B001-ACEPTA'
            SELECT @B=@B+1
         END
      END
      ELSE
      BEGIN
         SELECT @OBSERVACION='Factura sin Boleta '
      END
   END
   IF COALESCE(@TIPODOC,'')='01' 
   BEGIN
      IF @PROCEDENCIAFTR<>'FINANCIERO'
      BEGIN
         SELECT @OBSERVACION=AFI.TIPO_DOC+': '+AFI.DOCIDAFILIADO+' NOMBRE: '+AFI.NOMBREAFI+' '+@OBSERVACION
         FROM  FTR INNER JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
         WHERE FTR.N_FACTURA=@N_FACTURA
      END
      ELSE
      BEGIN
         SELECT @OBSERVACION=OBSERVACION FROM  FTR WHERE FTR.N_FACTURA=@N_FACTURA
      END
   END
   
   SELECT @VR_LETRAS=@VR_LETRAS+' SOLES'
   IF DB_NAME()=DBO.FNK_VALORVARIABLE('BDATA_PRODUCCION')
   BEGIN
      SELECT @URLFACT=DBO.FNK_VALORVARIABLE('URLFACT_ELE_PRODJSON')
      SELECT @TOKEN=dbo.FNK_VALORVARIABLE('TOKEN_FACTU_ELE_PERU')
   END
   ELSE
   BEGIN
      SELECT @URLFACT=DBO.FNK_VALORVARIABLE('URLFACT_ELE_PRUEJSON')
      SELECT @NITEMISOR='20100100100',@TOKEN='gN8zNRBV+/FVxTLwdaZx0w=='
   END
   IF LEN(COALESCE(@TOKEN,''))<20
   BEGIN
      PRINT 'No existe el token de seguridad'
      RETURN
   END
   SELECT @JSON='{ '
   SELECT @JSON=@JSON+'"TOKEN":"'+@TOKEN+'",'
   SELECT @JSON=@JSON+'"COD_TIP_NIF_EMIS": "'+@DVEMISIOR+'",'
   SELECT @JSON=@JSON+'"NUM_NIF_EMIS": "'+@NITEMISOR+'",'
   SELECT @JSON=@JSON+'"NOM_RZN_SOC_EMIS": "'+@RAZONSOCIALEMI+'",'
   SELECT @JSON=@JSON+'"NOM_COMER_EMIS": "'+@RAZONSOCIALEMI+'",'
   SELECT @JSON=@JSON+'"COD_UBI_EMIS": "'+COALESCE(@CODPOSTALEMI,'')+'",'
   SELECT @JSON=@JSON+'"TXT_DMCL_FISC_EMIS": "'+COALESCE(@DIRECCIOEMI,'')+'",'
   SELECT @JSON=@JSON+'"COD_TIP_NIF_RECP": "'+COALESCE(@DVRECEP,'')+'",'
   SELECT @JSON=@JSON+'"NUM_NIF_RECP": "'+COALESCE(@NITRECEP,'')+'",'
   SELECT @JSON=@JSON+'"NOM_RZN_SOC_RECP": "'+REPLACE(@RAZONSOCIALRECEP,CHAR(13),'')+'",'
   SELECT @JSON=@JSON+'"TXT_DMCL_FISC_RECEP": "'+COALESCE(@DIRECCIORECEP,'')+'",'
   SELECT @JSON=@JSON+'"FEC_EMIS": "'+@F_EMISION+'",'
   IF @TIPODOC='01'
   BEGIN
      SELECT @JSON=@JSON+'"FEC_VENCIMIENTO": "'+@F_VENCE+'",'
   END

   SELECT @JSON=@JSON+'"COD_TIP_CPE": "'+@TIPODOC+'",'
   SELECT @JSON=@JSON+'"NUM_SERIE_CPE": "'+@PREFACT+'",'
   SELECT @JSON=@JSON+'"NUM_CORRE_CPE": "'+@CORRELATIVO+'",'
   SELECT @JSON=@JSON+'"COD_TIP_OPE_SUNAT": "0101",'
   SELECT @JSON=@JSON+'"COD_TIP_PAGO": "001",'
   IF COALESCE(@DIASVENCE,0)=0
   BEGIN
      SELECT @JSON=@JSON+'"COD_FRM_PAGO": "EFECTIVO",'
   END
   ELSE
   BEGIN
      SELECT @JSON=@JSON+'"COD_FRM_PAGO": "CREDITO",'
   END
   SELECT @JSON=@JSON+'"COD_MND": "PEN",'
   SELECT @JSON=@JSON+'"TIP_CAMBIO":"1",' 
   SELECT @JSON=@JSON+'"MailEnvio": "'+COALESCE(@MAILRECEPTOR,'')+'",'
   SELECT @JSON=@JSON+'"COD_PRCD_CARGA": "001",'
   IF COALESCE(@VR_AFECTO,0)>0
   BEGIN
      SELECT @JSON=@JSON+'"MNT_TOT_GRAVADO": "'+CONVERT(VARCHAR(20),@VR_AFECTO)+'",' 
      SELECT @JSON=@JSON+'"MNT_TOT_TRIB_IGV": "'+CONVERT(VARCHAR(20),@VR_IVA)+'",' 
   END
   IF COALESCE(@VR_INAFECTO,0)>0
   BEGIN
      IF COALESCE(@VR_AFECTO,0)<=0
      BEGIN
         SELECT @JSON=@JSON+'"MNT_TOT_GRAVADO": "0.00",' 
         SELECT @JSON=@JSON+'"MNT_TOT_TRIB_IGV": "0.00",' 
      END
      SELECT @JSON=@JSON+'"MNT_TOT_EXONERADO":"'+CONVERT(VARCHAR(20),@VR_INAFECTO)+'",'
   END
	DECLARE @MNT_TOT DECIMAL(14,2)
	SELECT @MNT_TOT=COALESCE(@VR_AFECTO,0)+COALESCE(@VR_IVA,0)+COALESCE(@VR_INAFECTO,0)+ABS((COALESCE(@VR_AFECTO,0)+COALESCE(@VR_IVA,0)+COALESCE(@VR_INAFECTO,0)-COALESCE(@VR_NETO,0)))
	PRINT '@MNT_TOT='+CONVERT(VARCHAR(20),COALESCE(@MNT_TOT,0))
	SELECT @JSON=@JSON+'"MNT_TOT": "'+CONVERT(VARCHAR(20),@MNT_TOT)+'",' 
   SELECT @JSON=@JSON+'"COD_PTO_VENTA": "'+@USUARIOFACT+'",'
   SELECT @JSON=@JSON+'"ENVIAR_A_SUNAT": "true",'
   SELECT @JSON=@JSON+'"RETORNA_XML_ENVIO": "false",'
   SELECT @JSON=@JSON+'"RETORNA_XML_CDR": "false",'
   SELECT @JSON=@JSON+'"RETORNA_PDF": "false",'
   SELECT @JSON=@JSON+'"COD_FORM_IMPR":"001",'
	SELECT @JSON=@JSON+'"TXT_VERS_UBL":"2.1",'
	SELECT @JSON=@JSON+'"TXT_VERS_ESTRUCT_UBL":"2.0",'
	SELECT @JSON=@JSON+'"COD_ANEXO_EMIS":"0000",'
   IF  @TIPODOC='01'
   BEGIN
      IF COALESCE(@MNT_PENDIENTE,'')<>'' 
      BEGIN
         SELECT @JSON=@JSON+'"MNT_PENDIENTE":"'+@MNT_PENDIENTE+'",'
      END
	END
   SELECT @JSON=@JSON+'"items": ['
   SELECT @JSOND=''
   PRINT 'DETALLES DE LA FACTURA' --FTRD
   IF @TIPOFACT<>'M' AND COALESCE(@PAQUETE,0)<>1
   BEGIN
      DECLARE @N_CUOTA INT 
	   DECLARE XMLFTRD_CURSOR CURSOR FOR
      SELECT N_CUOTA FROM FTRD WHERE N_FACTURA=@N_FACTURA AND COALESCE(FTRD.PAQUETE,0)<>2
      AND COALESCE(VR_TOTAL,0)>0
      ORDER BY N_CUOTA ASC
	   OPEN XMLFTRD_CURSOR    
	   FETCH NEXT FROM XMLFTRD_CURSOR    
	   INTO @N_CUOTA
	   WHILE @@FETCH_STATUS = 0    
	   BEGIN 
         SELECT @ITEM=CONVERT(varchar(3),N_CUOTA),@CANTIDAD=CONVERT(varchar(4),CONVERT(INT,CEILING(FTRD.CANTIDAD))),
                @VALOR1=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,4),ROUND(COALESCE(VALOR,0),2))),
                @VALOR2=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,4),ROUND((VLR_SERVICI/FTRD.CANTIDAD),2))),
                @VALOR3=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),ROUND(CASE WHEN COALESCE(VIVA,0)>0 THEN VLRIMPUESTO+VIVA ELSE VLR_SERVICI END,2))),
                @VALOR4=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),CASE WHEN COALESCE(FTRD.VLR_COPAGOS,0)>0 THEN CASE WHEN COALESCE(PIVA,0)>0 THEN FTRD.VLR_COPAGOS/(1+(PIVA/100)) ELSE  FTRD.VLR_COPAGOS END ELSE 0 END  )),
                @VALOR5=CONVERT(VARCHAR(20),CONVERT(INT,COALESCE(PIVA,0))),
                @VALOR6=CASE WHEN COALESCE(VIVA,0)>0 THEN  CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),COALESCE(VIVA,0)*FTRD.CANTIDAD,0)) ELSE '0.00' END,
                --@VALOR7=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),ROUND((COALESCE(VALOR,0)*COALESCE(FTRD.CANTIDAD,0))+CASE WHEN COALESCE(VIVA,0)>0 THEN VIVA ELSE 0 END -CASE WHEN COALESCE(FTRD.VLR_COPAGOS,0)>0 THEN FTRD.VLR_COPAGOS ELSE 0 END ,2))),
                @VALOR7=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),CASE WHEN COALESCE(VIVA,0)>0 THEN VLRIMPUESTO ELSE VALOR END)),
				    @ANEXO= dbo.FNK_LIMPIATEXTO(CASE WHEN @PROCEDENCIAFTR='FINANCIERO' THEN FTRD.ANEXO ELSE CASE WHEN COALESCE(SER.DESCRIPCION_CUPS,'')='' THEN SER.DESCSERVICIO ELSE SER.DESCRIPCION_CUPS END END,'0-9 A-Z'), 
                @REFERENCIA=dbo.FNK_LIMPIATEXTO(COALESCE(SER.CODCUPS,FTRD.REFERENCIA),'0-9 A-Z '),
                @AFECTA=CASE WHEN COALESCE(PIVA,0)>0 AND COALESCE(VIVA,0)>0 THEN 1 ELSE 0 END
         FROM FTRD LEFT JOIN SER ON FTRD.REFERENCIA=SER.IDSERVICIO
         WHERE N_FACTURA=@N_FACTURA
         AND N_CUOTA=@N_CUOTA

			IF @NROITEM>0 
			BEGIN
				SELECT @JSOND=@JSOND+','
			END
			SELECT @NROITEM =@N_CUOTA
			
         SELECT @JSOND=@JSOND+' { '
         SELECT @JSOND=@JSOND+'   '
         SELECT @JSOND=@JSOND+'    "COD_ITEM": "'+@REFERENCIA+'",'
         SELECT @JSOND=@JSOND+'   "COD_UNID_ITEM": "NIU",'
         SELECT @JSOND=@JSOND+'   "CANT_UNID_ITEM": "'+@CANTIDAD+'",'
         SELECT @JSOND=@JSOND+'   "VAL_UNIT_ITEM": "'+@VALOR1+'",' 
         IF @AFECTA=1
         BEGIN
            SELECT @JSOND=@JSOND+'   "PRC_VTA_UNIT_ITEM": "'+@VALOR2+'",'
            SELECT @JSOND=@JSOND+'   "VAL_VTA_ITEM": "'+@VALOR7+'",'  
            SELECT @JSOND=@JSOND+'   "MNT_PV_ITEM": "'+@VALOR3+'", ' 
            SELECT @JSOND=@JSOND+'   "MNT_DSCTO_ITEM": "'+@VALOR4+'",'
            SELECT @JSOND=@JSOND+'   "COD_TIP_PRC_VTA": "01",'
            SELECT @JSOND=@JSOND+'   "COD_TIP_AFECT_IGV_ITEM":"10",'
            SELECT @JSOND=@JSOND+'   "COD_TRIB_IGV_ITEM": "1000",'
            SELECT @JSOND=@JSOND+'   "POR_IGV_ITEM": "'+@VALOR5+'",'
            SELECT @JSOND=@JSOND+'   "MNT_IGV_ITEM": "'+@VALOR6+'", '              
         END
         ELSE
         BEGIN     
            SELECT @JSOND=@JSOND+' "PRC_VTA_UNIT_ITEM": "'+@VALOR1+'",'
            SELECT @JSOND=@JSOND+' "VAL_VTA_ITEM": "'+@VALOR7+'",'      
            SELECT @JSOND=@JSOND+' "MNT_PV_ITEM": "'+@VALOR3+'",'
            SELECT @JSOND=@JSOND+'   "MNT_DSCTO_ITEM": "'+@VALOR4+'",'
            SELECT @JSOND=@JSOND+' "COD_TIP_PRC_VTA": "01",'
            SELECT @JSOND=@JSOND+' "COD_TIP_AFECT_IGV_ITEM":"20",'
            SELECT @JSOND=@JSOND+' "COD_TRIB_IGV_ITEM": "9997",'
            SELECT @JSOND=@JSOND+' "POR_IGV_ITEM": "0.00",'
            SELECT @JSOND=@JSOND+' "MNT_IGV_ITEM": "0.00",'
         END
         SELECT @JSOND=@JSOND+'   "TXT_DESC_ITEM": "'+COALESCE(REPLACE(@ANEXO,CHAR(13),''),'')+'" '             
         SELECT @JSOND=@JSOND+'   '
         SELECT @JSOND=@JSOND+' } '
         PRINT @JSOND
	   FETCH NEXT FROM XMLFTRD_CURSOR    
	   INTO @N_CUOTA
	   END
	   CLOSE XMLFTRD_CURSOR
	   DEALLOCATE XMLFTRD_CURSOR
   END
   ELSE
   BEGIN
      PRINT 'VOY POR EL PAQUETE...'
      SELECT @ITEM=CONVERT(varchar(3),1),@CANTIDAD=CONVERT(varchar(4),1),
               @VALOR1=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),COALESCE(VALORSERVICIOS-COALESCE(VIVA,0),0))),
               @VALOR2=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),ROUND(COALESCE(VALORSERVICIOS,0)-COALESCE(VIVA,0)+CASE WHEN COALESCE(PIVA,0)>0 THEN (COALESCE(VALORSERVICIOS,0)-COALESCE(VIVA,0))*(PIVA/100) ELSE 0 END,2))),
               @VALOR3=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),ROUND((COALESCE(VALORSERVICIOS,0)-COALESCE(VIVA,0))-COALESCE(FTR.VALORCOPAGO,0),2))),
               @VALOR4=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),COALESCE(FTR.VALORCOPAGO,0))),
               @VALOR5=CONVERT(VARCHAR(20),CONVERT(INT,COALESCE(PIVA,0))),
               @VALOR6=CASE WHEN COALESCE(VIVA,0)>0 THEN  CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),COALESCE(VIVA,0))) ELSE '0.00' END,
               @VALOR7=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),ROUND((VR_TOTAL),2))),
               @ANEXO=COALESCE(dbo.FNK_LIMPIATEXTO(CASE WHEN COALESCE(OBSERVACION,'')='' 
               THEN (SELECT DESCSERVICIO FROM SER WHERE IDSERVICIO=@IDSERPAQ)
               ELSE OBSERVACION END,'0-9 A-Z '),PLN.DESCPLAN),
               @REFERENCIA=dbo.FNK_LIMPIATEXTO(COALESCE(@IDSERPAQ,FTR.IDPLAN),'0-9 A-Z '),
               @AFECTA=CASE WHEN COALESCE(PIVA,0)>0 AND COALESCE(VIVA,0)>0 THEN 1 ELSE 0 END
      FROM FTR INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN   
      WHERE N_FACTURA=@N_FACTURA

      SELECT @JSOND=@JSOND+' { '
      SELECT @JSOND=@JSOND+'   '
      SELECT @JSOND=@JSOND+'    "COD_ITEM": "'+@REFERENCIA+'",'
      SELECT @JSOND=@JSOND+'   "COD_UNID_ITEM": "NIU",'
      SELECT @JSOND=@JSOND+'   "CANT_UNID_ITEM": "'+@CANTIDAD+'",'
      SELECT @JSOND=@JSOND+'   "VAL_UNIT_ITEM": "'+@VALOR1+'",' 
      IF @AFECTA=1
      BEGIN
         PRINT 'AFECTA'
         SELECT @JSOND=@JSOND+'   "PRC_VTA_UNIT_ITEM": "'+@VALOR2+'",'
         SELECT @JSOND=@JSOND+'   "VAL_VTA_ITEM": "'+@VALOR3+'",'  
         SELECT @JSOND=@JSOND+'   "MNT_PV_ITEM": "'+@VALOR7+'", ' 
         SELECT @JSOND=@JSOND+'   "MNT_DSCTO_ITEM": "'+@VALOR4+'",'
         SELECT @JSOND=@JSOND+'   "COD_TIP_PRC_VTA": "01",'
         SELECT @JSOND=@JSOND+'   "COD_TIP_AFECT_IGV_ITEM":"10",'
         SELECT @JSOND=@JSOND+'   "COD_TRIB_IGV_ITEM": "1000",'
         SELECT @JSOND=@JSOND+'   "POR_IGV_ITEM": "'+@VALOR5+'",'
         SELECT @JSOND=@JSOND+'   "MNT_IGV_ITEM": "'+@VALOR6+'", '  
            
      END
      ELSE
      BEGIN     
         SELECT @JSOND=@JSOND+' "PRC_VTA_UNIT_ITEM": "'+@VALOR1+'",'
         SELECT @JSOND=@JSOND+' "VAL_VTA_ITEM": "'+@VALOR7+'",'      
         SELECT @JSOND=@JSOND+' "MNT_PV_ITEM": "'+@VALOR3+'",'
         SELECT @JSOND=@JSOND+' "MNT_DSCTO_ITEM": "'+@VALOR4+'",'
         SELECT @JSOND=@JSOND+' "COD_TIP_PRC_VTA": "01",'
         SELECT @JSOND=@JSOND+' "COD_TIP_AFECT_IGV_ITEM":"20",'
         SELECT @JSOND=@JSOND+' "COD_TRIB_IGV_ITEM": "9997",'
         SELECT @JSOND=@JSOND+' "POR_IGV_ITEM": "0.00",'
         SELECT @JSOND=@JSOND+' "MNT_IGV_ITEM": "0.00",'
      END
      SELECT @JSOND=@JSOND+'   "TXT_DESC_ITEM": "'+COALESCE(REPLACE(@ANEXO,CHAR(13),''),'')+'" '             
      SELECT @JSOND=@JSOND+'   '
      SELECT @JSOND=@JSOND+' } '
 
   END

   SELECT @JSON=LTRIM(RTRIM(@JSON))+LTRIM(RTRIM(@JSONd))


   IF COALESCE(@TIPODOC,'')='01'
   BEGIN
	   SELECT @JSON=@JSON +' ], '
	   SELECT @JSON=@JSON +' "datos_adicionales": [ '
	   SELECT @JSON=@JSON +'  { '
	   SELECT @JSON=@JSON +'	"COD_TIP_ADIC_SUNAT": "01", '
	   SELECT @JSON=@JSON +'	"TXT_DESC_ADIC_SUNAT": "CREDITO '+CONVERT(VARCHAR(20),COALESCE(@DIASVENCE,30))+ ' DIAS" '
	   SELECT @JSON=@JSON +'  } '
      SELECT @JSON=@JSON +',{ '
      SELECT @JSON=@JSON +'"COD_TIP_ADIC_SUNAT": "05",'
      SELECT @JSON=@JSON +'"TXT_DESC_ADIC_SUNAT": "'+LTRIM(RTRIM(COALESCE(@OBSERVACION,'')))+'" '
      SELECT @JSON=@JSON +' } '
      SELECT @JSON=@JSON +' ] '
   END
   ELSE
   BEGIN
	   SELECT @JSON=@JSON +' ], '
	   SELECT @JSON=@JSON +' "datos_adicionales": [ '
	   SELECT @JSON=@JSON +'  { '
	   SELECT @JSON=@JSON +'	"COD_TIP_ADIC_SUNAT": "01", '
	   SELECT @JSON=@JSON +'	"TXT_DESC_ADIC_SUNAT": "CONTADO" '
	   SELECT @JSON=@JSON +'  } '
      SELECT @JSON=@JSON +' ] '
   END

   IF COALESCE(@TIPODOC,'')='01' AND COALESCE(@NCUOTAS,0)>1
   BEGIN
      SELECT @JSON=@JSON +','
      SELECT @JSON=@JSON +'  "cuotas": ['
      SELECT @JSON=@JSON +'  {'
      SELECT @JSON=@JSON +'          "NRO_CUOTA":"1",'
      SELECT @JSON=@JSON +'          "FECHA_CUOTA":"'+REPLACE(CONVERT(VARCHAR,(@F_FACTURA+COALESCE(@DIASVENCE,30)),102),'.','-')+'",'
      SELECT @JSON=@JSON +'          "MONTO_CUOTA":"'+CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),@VLR_CUOTA))+'"'
      SELECT @JSON=@JSON +'      } '
      IF COALESCE(@NCUOTAS,0)>=2
      BEGIN
         SELECT @JSON=@JSON +'          ,{'
         SELECT @JSON=@JSON +'          "NRO_CUOTA":"2",'
         SELECT @JSON=@JSON +'          "FECHA_CUOTA":"'+REPLACE(CONVERT(VARCHAR,(@F_FACTURA+(COALESCE(@DIASVENCE,30)*2)),102),'.','-')+'",'
         SELECT @JSON=@JSON +'          "MONTO_CUOTA":"'+CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),@VLR_CUOTA))+'"'
         SELECT @JSON=@JSON +'      }'
      END
      IF COALESCE(@NCUOTAS,0)>=3
      BEGIN
         SELECT @JSON=@JSON +'          ,{'
         SELECT @JSON=@JSON +'          "NRO_CUOTA":"3",'
         SELECT @JSON=@JSON +'          "FECHA_CUOTA":"'+REPLACE(CONVERT(VARCHAR,(@F_FACTURA+(COALESCE(@DIASVENCE,30)*3)),102),'.','-')+'",'
         SELECT @JSON=@JSON +'          "MONTO_CUOTA":"'+CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),@VLR_CUOTA))+'"'
         SELECT @JSON=@JSON +'      }'
      END
      IF COALESCE(@NCUOTAS,0)>=4
      BEGIN
         SELECT @JSON=@JSON +'          ,{'
         SELECT @JSON=@JSON +'          "NRO_CUOTA":"4",'
         SELECT @JSON=@JSON +'          "FECHA_CUOTA":"'+REPLACE(CONVERT(VARCHAR,(@F_FACTURA+(COALESCE(@DIASVENCE,30)*4)),102),'.','-')+'",'
         SELECT @JSON=@JSON +'          "MONTO_CUOTA":"'+CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),@VLR_CUOTA))+'"'
         SELECT @JSON=@JSON +'      }'
      END
      IF COALESCE(@NCUOTAS,0)>=5
      BEGIN
         SELECT @JSON=@JSON +'          ,{'
         SELECT @JSON=@JSON +'          "NRO_CUOTA":"5",'
         SELECT @JSON=@JSON +'          "FECHA_CUOTA":"'+REPLACE(CONVERT(VARCHAR,(@F_FACTURA+(COALESCE(@DIASVENCE,30)*5)),102),'.','-')+'",'
         SELECT @JSON=@JSON +'          "MONTO_CUOTA":"'+CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),@VLR_CUOTA))+'"'
         SELECT @JSON=@JSON +'      }'
      END
      IF COALESCE(@NCUOTAS,0)>=6
      BEGIN
         SELECT @JSON=@JSON +'          ,{'
         SELECT @JSON=@JSON +'          "NRO_CUOTA":"6",'
         SELECT @JSON=@JSON +'          "FECHA_CUOTA":"'+REPLACE(CONVERT(VARCHAR,(@F_FACTURA+(COALESCE(@DIASVENCE,30)*6)),102),'.','-')+'",'
         SELECT @JSON=@JSON +'          "MONTO_CUOTA":"'+CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),@VLR_CUOTA))+'"'
         SELECT @JSON=@JSON +'      }'
      END
      IF COALESCE(@NCUOTAS,0)>=7
      BEGIN
         SELECT @JSON=@JSON +'          ,{'
         SELECT @JSON=@JSON +'          "NRO_CUOTA":"7",'
         SELECT @JSON=@JSON +'          "FECHA_CUOTA":"'+REPLACE(CONVERT(VARCHAR,(@F_FACTURA+(COALESCE(@DIASVENCE,30)*7)),102),'.','-')+'",'
         SELECT @JSON=@JSON +'          "MONTO_CUOTA":"'+CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),@VLR_CUOTA))+'"'
         SELECT @JSON=@JSON +'      }'
      END
      IF COALESCE(@NCUOTAS,0)>=8
      BEGIN
         SELECT @JSON=@JSON +'          ,{'
         SELECT @JSON=@JSON +'          "NRO_CUOTA":"8",'
         SELECT @JSON=@JSON +'          "FECHA_CUOTA":"'+REPLACE(CONVERT(VARCHAR,(@F_FACTURA+(COALESCE(@DIASVENCE,30)*8)),102),'.','-')+'",'
         SELECT @JSON=@JSON +'          "MONTO_CUOTA":"'+CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),@VLR_CUOTA))+'"'
         SELECT @JSON=@JSON +'      }'
      END
      SELECT @JSON=@JSON +'          ]'
   END
   SELECT @JSON=@JSON +' } '
   IF LEN(@JSON)<10
   BEGIN
      PRINT 'NO TENGO DATOS'
      RETURN
   END

   IF DB_NAME()=DBO.FNK_VALORVARIABLE('BDATA_PRODUCCION')
   BEGIN
      SELECT @URLFACT=DBO.FNK_VALORVARIABLE('URLFACT_ELE_PRODJSON')
   END
   ELSE
   BEGIN
      SELECT @URLFACT=DBO.FNK_VALORVARIABLE('URLFACT_ELE_PRUEJSON')
   END
  --SELECT @URLFACT='http://demo.mifact.net.pe/api/invoiceService.svc/SendInvoice'
  IF LEN(@URLFACT)<30
  BEGIN
     PRINT 'No existe api valida para el envio '
     RETURN
  END

  PRINT 'DEFINITIVO'
  PRINT @JSON
  SELECT @sUrl =@URLFACT
  SELECT @BODY=@JSON

   PRINT '@sUrl='+@sUrl
	PRINT '@JSON='
   PRINT SUBSTRING(@BODY,1,8000)
   IF LEN(@BODY)>8000
   BEGIN
	   PRINT SUBSTRING(@BODY,8001,16000)
      IF LEN(@BODY)>16000
      BEGIN
	      PRINT SUBSTRING(@BODY,16001,24000)
         IF LEN(@BODY)>24000
         BEGIN
	         PRINT SUBSTRING(@BODY,24001,32000)
               IF LEN(@BODY)>32000
               BEGIN
	               PRINT SUBSTRING(@BODY,32001,40000)
                  IF LEN(@BODY)>40000
                  BEGIN
	                  PRINT SUBSTRING(@BODY,40001,48000)
                     IF LEN(@BODY)>48000 
                     BEGIN
	                     PRINT SUBSTRING(@BODY,48001,56000)
                        IF LEN(@BODY)>56000
                        BEGIN
	                        PRINT SUBSTRING(@BODY,56001,64000)
                           BEGIN
	                           PRINT SUBSTRING(@BODY,64001,72000)
                              IF LEN(@BODY)>72000
                              BEGIN
	                              PRINT SUBSTRING(@BODY,72001,80000)
                              END
                           END
                        END
                     END
                  END
               END
            END
         END
      END

   IF COALESCE(@FACTEP,'')='ERROR' OR COALESCE(@FACTEP,'')IN('104','104A') OR( COALESCE(@FACTEP,'')=''  AND @ERFACTEP NOT LIKE '%no existe%' AND @ERFACTEP NOT LIKE '%se encontro errores%')
   BEGIN
      PRINT 'INGRESO A CONSULTAR LOS DATOS EN MI FACT'
      EXEC DBO.SPK_CONSULTA_DOCUMENTO_ELECTRONICA @N_FACTURA

      IF EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTURA AND FACTEP IN('101','102','103'))
      BEGIN
         UPDATE FTRE SET SOLICITUDJSON=@JSON WHERE FTRN_FACTURA=@N_FACTURA
         RETURN
      END
   END
   --RETURN
   EXEC sys.sp_OACreate 'MSXML2.ServerXMLHttp', @obj OUT
   EXEC sys.sp_OAMethod @obj, 'Open', NULL, 'POST', @sUrl, false
   Exec sp_OAMethod @obj, 'setRequestHeader', null, 'Content-Type', 'application/json'
   Exec sp_OAMethod @obj, 'send', null, @body
   Exec sp_OAMethod @obj, 'responseText', @Response OUTPUT
   Exec sp_OADestroy @obj
   IF ISJSON(@Response)=1
   BEGIN
      SELECT @CODQR=CODQR,@CODHASH=CODHASH,@ESTDOC=ESTDOC,@URLFACTEP=URLFACTEP,@DESCSUNAT=DESCSUNAT,@ERRORES=ERRORES
      FROM OPENJSON(@Response)
      WITH(
             CODQR       VARCHAR(100) '$.cadena_para_codigo_qr'
            ,CODHASH    VARCHAR(50) '$.codigo_hash'
            ,ESTDOC     VARCHAR(10) '$.estado_documento'
            ,URLFACTEP  VARCHAR(256) '$.url'
            ,ERRORES    VARCHAR(MAX) '$.errors'
            ,DESCSUNAT  VARCHAR(MAX) '$.sunat_description'
      )

      INSERT INTO FTRAPILOG(N_FACTURA,CNSFNOT, TIPODOC, ESTADOC, ERRORES, DESCSUNAT,METODO, JSONSOLICITUD, JSONRESPUESTA)
      SELECT @N_FACTURA,NULL,  @TIPODOC, @ESTDOC, @ERRORES, @DESCSUNAT,'ENVIO',@body , @Response

      IF @ESTDOC IN('101','102','103')
      BEGIN
         -- SE CAMBIA Y SE DEJA EN OK -- SEGUN REUNION CON EL GRUPO DE EXPERTTA
         --SELECT @FACTEP=CASE WHEN @ESTDOC='101' THEN 'PEND' ELSE 'OK' END
         SELECT @FACTEP=@ESTDOC
         UPDATE FTR SET FACTEP=@FACTEP,LINKFACTURA=@URLFACTEP WHERE N_FACTURA=@N_FACTURA

         INSERT INTO FTRE(N_FACTURA,FTRN_FACTURA,PREFIJO,RESPUESTA,FECHA,CUFE,NOMBREARCHIVO,CNSRESOL,SOLICITUDJSON) 
         SELECT CNSFCT,N_FACTURA,@PREFACT,@response,GETDATE(),@CODQR,@CODHASH,CNSRESOL,@JSON FROM FTR
         WHERE N_FACTURA=@N_FACTURA
      END
      ELSE
      BEGIN
          UPDATE FTR SET FACTEP=CASE WHEN COALESCE(@ESTDOC,'')=''THEN '104A' ELSE @ESTDOC END,ULRPTAAPI=SUBSTRING(@ERRORES,1,255) WHERE N_FACTURA=@N_FACTURA
      END
   END
   ELSE
   BEGIN
      UPDATE FTR SET FACTEP=@ESTDOC,ULRPTAAPI='Factura no Recibida en MiFact, Error de estructura' WHERE N_FACTURA=@N_FACTURA
   END
END