
SELECT  TB.CUENTA,NOMCUENTA,TB.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,CCOSTO,N_FACTURA,SI,DB,CR,SM,SF,NTZ,TIPO
FROM TBALANCETERFAC TB LEFT JOIN TER ON TB.IDTERCERO=TER.IDTERCERO WHERE CNSPRO='0600000994'


SELECT * FROM VWK_CXCDIASVTO