IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_NC_CONTAB_CAJA_ING' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_NC_CONTAB_CAJA_ING
END
GO
CREATE  PROCEDURE DBO.SPK_NC_CONTAB_CAJA_ING 
@CNSFACJ            VARCHAR(20), 
@CODCAJA            VARCHAR(4), 
@USUARIO            VARCHAR(12),
@SYS_COMPUTERNAME   VARCHAR(254),
@COMPANIA           VARCHAR(2), 
@SEDE               VARCHAR(5),
@NROCOMPROBANTE     VARCHAR(20)
WITH ENCRYPTION
AS 
DECLARE @COM              VARCHAR(6)
DECLARE @NOREFERENCIA     VARCHAR(20)
DECLARE @ANO		        VARCHAR(4)
DECLARE @MES              INT
DECLARE @IDMODELOCONT	  VARCHAR(2)
DECLARE @IDPLAN           VARCHAR(6) 
DECLARE @TIPOTERCONTABLE  VARCHAR(10) 
DECLARE @ESTADO           VARCHAR(1)
DECLARE @PREFIJO_USCXS    VARCHAR(10)
DECLARE @FECHATRA         DATETIME
DECLARE @SALDO            DECIMAL(15,6)   
DECLARE @TOTAL_CRUCE      DECIMAL(15,6)
DECLARE @TOTAL_ORIGINAL   DECIMAL(15,6) 
DECLARE @VALORIMPUESTOS	  DECIMAL(14,2)
DECLARE @VLRAJUSTEPESO    DECIMAL(14,2)
DECLARE @CNSFPAG          VARCHAR(20)
DECLARE @CNSFCXP          VARCHAR(20)
DECLARE @IDTERCERO_CXP    VARCHAR(20)
DECLARE @N_FACTURA_CXP    VARCHAR(20)
DECLARE @F_FACTURA_CXP    DATETIME
DECLARE @F_VENCE_CXP      DATETIME
DECLARE @OBSERVACION_CXP  VARCHAR(255)
DECLARE @VALOR_CXP        DECIMAL(14,2)     
DECLARE @CCOSTO_CXP       VARCHAR(20)
DECLARE @IDAREA_CXP       VARCHAR(20)
DECLARE @CUENTA_CXP       VARCHAR(16)
DECLARE @CLASE_GENERA_CXP VARCHAR(10)
DECLARE @IDAFILIADO       VARCHAR(20)
DECLARE @IDCATEGORIA      VARCHAR(20)
DECLARE @PROCESO          VARCHAR(10)    
/*CAJA DE COMPENSACION*/
DECLARE @PROCEDENCIA      VARCHAR(10)
DECLARE @CUENTACXC        VARCHAR(16)
DECLARE @IDTERCERO        VARCHAR(20)
DECLARE @N_FACTURA        VARCHAR(16), @CNSCXC VARCHAR(20), @VEZFCXCDV INT
DECLARE @ESLEGDEPO         INT
DECLARE @DOCIDAFILIADO	  VARCHAR(20) --EZERPA 13/09/2018 
DECLARE @IDTERCEROAFI	  VARCHAR(20) 

BEGIN
   /* PROCEDENCIA DEL RECIBO */
   SELECT @COMPANIA = COALESCE(UBEQ.COMPANIA,'01'), @SEDE = COALESCE(USUSU.IDSEDE,'01') FROM USUSU 
      INNER JOIN UBEQ ON USUSU.SYS_ComputerName = UBEQ.SYS_ComputerName
   WHERE  USUSU.USUARIO = @USUARIO

   SELECT @PROCEDENCIA = PROCEDENCIA 
   FROM   FCJ 
   WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
   PRINT ''
   PRINT '     **************************************'
   PRINT '     ** ENVIO DE CAJA.ING A CONTABILIDAD **'
   PRINT '     **************************************'
   PRINT 'Seleccionando Informacion de : '+@CNSFACJ+' '+@CODCAJA

   PRINT 'Actualizaci? Temporal... Mientras se arregla lo del Saco en TFCJ'
   UPDATE FCJD SET VALORTOTAL = PCJ.VALOR
   FROM   FCJD INNER JOIN FCJ ON FCJD.CODCAJA=FCJ.CODCAJA 
                             AND FCJD.CNSFACJ=FCJ.CNSFACJ 
               INNER JOIN ( SELECT CODCAJA, CNSFACJ, CANT=COUNT(*), VALORTOTAL=SUM(VALORTOTAL) 
                            FROM   FCJD 
                            GROUP BY CODCAJA, CNSFACJ
                          ) FCJD_X ON FCJ.CODCAJA=FCJD_X.CODCAJA 
                                  AND FCJ.CNSFACJ=FCJD_X.CNSFACJ 
                LEFT JOIN ( SELECT CODCAJA, CNSFACJ, VALOR=SUM(VALOR) 
                          FROM   PCJ 
                          GROUP BY CODCAJA, CNSFACJ
                        ) PCJ ON FCJ.CODCAJA=PCJ.CODCAJA 
                             AND FCJ.CNSFACJ=PCJ.CNSFACJ
   WHERE PCJ.VALOR   <> FCJD.VALORTOTAL 
   AND   FCJD_X.CANT  = 1 
   AND   FCJD.CODCAJA = @CODCAJA 
   AND   FCJD.CNSFACJ = @CNSFACJ
   IF (SELECT TOP 1 CONCEPTO FROM FCJD WHERE  FCJD.CODCAJA = @CODCAJA  AND   FCJD.CNSFACJ = @CNSFACJ) = DBO.FNK_VALORVARIABLE('CPCJ_REEMB')  
   BEGIN
      RETURN
   END 
   IF EXISTS(SELECT * FROM CAJ WHERE CODCAJA=@CODCAJA AND COALESCE(NOCONTAB,0)=1)
   BEGIN
      PRINT 'No se Genera comprobante'
      UPDATE FCJ SET CONTABILIZADA=1,NROCOMPROBANTE='NOCONTAB',NOCONTAB=1 WHERE CODCAJA=CODCAJA AND CNSFACJ=@CNSFACJ
      RETURN
   END
   SELECT * INTO #T FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA=@CODCAJA
   SELECT * INTO #TH FROM FCJD WHERE CNSFACJ = @CNSFACJ AND CODCAJA=@CODCAJA
   SELECT * INTO #THD FROM PCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA=@CODCAJA

   SELECT  @ESLEGDEPO=COUNT(*) FROM #THD  WHERE TIPOPAGO = DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO')  
   IF (SELECT TOP 1 CONCEPTO FROM #TH) = DBO.FNK_VALORVARIABLE('IDCJRECEPCIONTRAS') AND LEFT(@NROCOMPROBANTE,2)<>'IX' 
   BEGIN
      RETURN
   END   
   
   SELECT @ESTADO = #T.ESTADO FROM #T
   UPDATE #T SET CCOSTO='' WHERE NOT CCOSTO IN (SELECT CCOSTO FROM CEN WHERE COMPANIA=@COMPANIA)
   SELECT @ANO = YEAR(FECHA),
          @MES = MONTH(FECHA),
          @FECHATRA = FECHA
   FROM #T
   
   --SELECT @ANO =  (SELECT YEAR(GETDATE()))
   --SELECT @MES =  (SELECT MONTH(GETDATE()))
   
   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)
   BEGIN
      RAISERROR('PERIODO NO EXISTE.',16,1)
      RETURN
   END
   
   
   IF EXISTS (SELECT 1 FROM MCP WHERE PROCEDENCIA='CAJA' AND REFERENCIA1=@CNSFACJ AND REFERENCIA2=@CODCAJA AND COALESCE(ANULADO,0)=0)
   BEGIN
		PRINT '@PROCEDENCIA=CAJA, MCP.PROCEDENCIA'
		PRINT '@CODCAJA='+@CODCAJA+ ', MCP.REFERENCIA1'
		PRINT '@CNSFACJ='+@CNSFACJ+ ', MCP.REFERENCIA2'
		RAISERROR('Recibo ya se encuentra en contabilidad, Posible duplicidad', 16, 1)
		RETURN
   END
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
    
   IF ISNULL(@NROCOMPROBANTE,'') = '' OR LEFT(@NROCOMPROBANTE,2)='IX'
   BEGIN
      SET @PROCESO='Nuevo'  
      IF LEFT(@NROCOMPROBANTE,2)='IX'
      BEGIN
         SET @COM = 'IX'   
         SET @NOREFERENCIA = @NROCOMPROBANTE
      END
      ELSE
      BEGIN
         SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
         PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
         SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) 
         END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
         PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
									PRINT '@ESLEGDEPO :'+STR(@ESLEGDEPO)
         IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
         BEGIN
            IF @ESLEGDEPO>=1
            BEGIN 
               SELECT @COM = COMPROBANTE FROM COMMS WHERE IDSEDE = @SEDE  AND CLASE = 'CAJAING' AND TIPO = 'IDCJLEGDEPOSITO'
            END
            ELSE
            BEGIN
               SELECT @COM  = RTRIM(LTRIM(CASE WHEN EXISTS (SELECT TOP 1 COMMS.COMPROBANTE
                                                                     FROM   #TH INNER JOIN COMMS   ON #TH.CONCEPTO = COMMS.TIPO
                                                                     WHERE  COMMS.IDSEDE = @SEDE
                                                                     AND    COMMS.CLASE  = 'CAJAING')
                                               THEN (SELECT TOP 1 COMMS.COMPROBANTE
                                                     FROM   #TH INNER JOIN COMMS   ON #TH.CONCEPTO = COMMS.TIPO
                                                     WHERE  COMMS.IDSEDE = @SEDE
                                                     AND    COMMS.CLASE  = 'CAJAING')
                                               ELSE (CASE WHEN EXISTS (SELECT TOP 1 COM.COMPROBANTE FROM CPCJ,COM,#TH 
                                                                       WHERE  CPCJ.CODIGO      = #TH.CONCEPTO 
                                                                       AND    CPCJ.COMPROBANTE = COM.COMPROBANTE AND COM.COMPANIA=@COMPANIA) 
																          THEN (SELECT TOP 1 COM.COMPROBANTE FROM CPCJ,COM,#TH WHERE CPCJ.CODIGO=#TH.CONCEPTO 
                                                          AND 
																                CPCJ.COMPROBANTE=COM.COMPROBANTE AND COM.COMPANIA=@COMPANIA) 
																	       ELSE
																			      CASE WHEN DBO.FNK_VALORVARIABLE('IDCON_TCOM_ICAJ')<>'' OR NOT 
                                                               DBO.FNK_VALORVARIABLE('IDCON_TCOM_ICAJ') IS NULL 
																				        THEN DBO.FNK_VALORVARIABLE('IDCON_TCOM_ICAJ')
																					     ELSE DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT') 
																					END 
													              END)
                                          END))
            END
         END
         ELSE
         BEGIN
            IF @ESLEGDEPO>=1
            BEGIN 
			      SELECT @COM=COMPROBANTE_EGR FROM FPA WHERE  FORMAPAGO= DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO')
			   END
			   ELSE
			   BEGIN            
               SET @COM = RTRIM(LTRIM((SELECT (CASE WHEN EXISTS 
																			      (SELECT TOP 1 COM.COMPROBANTE FROM CPCJ,COM,#TH 
                                                                WHERE  CPCJ.CODIGO      = #TH.CONCEPTO 
                                                                AND    CPCJ.COMPROBANTE = COM.COMPROBANTE AND COM.COMPANIA=@COMPANIA) 
																	      THEN (SELECT TOP 1 COM.COMPROBANTE FROM CPCJ,COM,#TH WHERE CPCJ.CODIGO=#TH.CONCEPTO 
                                                         AND 
																							      CPCJ.COMPROBANTE=COM.COMPROBANTE AND COM.COMPANIA=@COMPANIA) 
																	      ELSE
																							      CASE WHEN DBO.FNK_VALORVARIABLE('IDCON_TCOM_ICAJ')<>'' OR 
                                                         NOT DBO.FNK_VALORVARIABLE('IDCON_TCOM_ICAJ') IS NULL 
																										      THEN DBO.FNK_VALORVARIABLE('IDCON_TCOM_ICAJ')
																										      ELSE DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT') 
																							      END 
													      END))))
      	   END
         END
         SET @PREFIJO_USCXS='@COM'+@COM
         SET @NOREFERENCIA=SPACE(20)
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@COMPANIA,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
         SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
      END
      PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
      PRINT 'Comprobante Contable (MCP)'
      PRINT 'Comprobante Contable = '+@NROCOMPROBANTE
      --SELECT @NROCOMPROBANTE
      INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                       TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                       COMPROBANTE, IDTERCERO, ANULADO)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'CAJA', @NOREFERENCIA, @ANO, @MES, CAST(STR(DAY(FECHA))+'/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME),
             0, 0, @CNSFACJ, CODCAJA, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, LEFT(OBSERVACION,512) OBSERVACION, @SEDE, 1,
             @COM, (CASE WHEN #T.IDTERCERO IS NULL THEN '' ELSE #T.IDTERCERO END), CASE WHEN #T.ESTADO='A' THEN 1 ELSE 0 END
      FROM   #T
      IF (SELECT TOP 1 CONCEPTO FROM #TH) = DBO.FNK_VALORVARIABLE('IDCJRECEPCIONTRAS')
      BEGIN
         RETURN
      END         

   END
   ELSE
   BEGIN
      SET @PROCESO='Viejo'  
      PRINT 'DEPOSITOS DE CLIENTES A TERCEROS VIEJO'
      DECLARE CUR_CXP CURSOR FOR
      SELECT DISTINCT CNSFCXCXP
      FROM MCHE 
      WHERE MCHE.NROCOMPROBANTE = @NROCOMPROBANTE AND MCHE.PROCEDENCIA='CAJA' AND MCHE.REFERENCIA_PRO=@CNSFACJ 
      AND   MCHE.REFERENCIA2    = @CODCAJA AND MCHE.PROCESO='CXP_XDEPCLITER' AND MCHE.CLASE_GENERA='Contab'               
      OPEN CUR_CXP               
      FETCH NEXT FROM CUR_CXP
      INTO @CNSFCXP
      WHILE @@FETCH_STATUS = 0
      BEGIN   
         PRINT 'Eliminando CXP con CNS='+@CNSFCXP
         EXEC SPK_ADMIN_CXP_CONTAB @CNSFCXP,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'DELETE',NULL,NULL,NULL
         FETCH NEXT FROM CUR_CXP
         INTO @CNSFCXP
      END
      CLOSE CUR_CXP
      DEALLOCATE CUR_CXP 
     
      SELECT @COM=COMPROBANTE,@NOREFERENCIA=NOREFERENCIA FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
      IF @ESTADO<>'A'
      BEGIN
         DELETE MCHE 
         WHERE  NROCOMPROBANTE=@NROCOMPROBANTE AND PROCEDENCIA='CAJA' AND REFERENCIA_PRO=@CNSFACJ AND REFERENCIA2=@CODCAJA  
         UPDATE MCPE SET OBSERVACION=#T.OBSERVACION FROM #T   
         WHERE  MCPE.NROCOMPROBANTE=@NROCOMPROBANTE AND MCPE.PROCEDENCIA='CAJA' 
         AND    MCPE.REFERENCIA1=@CNSFACJ AND MCPE.REFERENCIA2=@CODCAJA  
      END
   END
   
   IF @ESTADO='A' AND LEFT(@NROCOMPROBANTE,2)<>'IX'  
   BEGIN   
      PRINT 'ANULADA.'  
      PRINT 'Borrando Registros de MCH...'
      UPDATE MCPE SET ESTADO='2', ANULADO=1, TOTALDEBITO=0, TOTALCREDITO=0 
      WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE  
      PRINT 'Actualizando FCJ...'
      UPDATE FCJ SET CONTABILIZADA=1, MARCACONT = 0, NROCOMPROBANTE = @NROCOMPROBANTE 
      FROM #T WHERE FCJ.CNSFACJ=#T.CNSFACJ AND FCJ.CODCAJA=#T.CODCAJA  
      IF @PROCESO='Viejo'  
      BEGIN
         RETURN  
      END
   END  
      
   IF @@ERROR<>0
   BEGIN 
      PRINT 'Errores...'
      RETURN
   END
   
   PRINT '************************* @PROCEDENCIA: ' + @PROCEDENCIA
   --POR QUE SE PUSO ESTA CONDICION, SE RETIRA JJIMENEZ 20230516 .. PILAS AVISE
   --IF @PROCEDENCIA <> 'CAJA'
   --BEGIN   
      PRINT 'Crea el Afiliado como Tercero con la categoria de Afiliado'
      SELECT TOP 1 @IDAFILIADO = IDAFILIADO FROM #T
      SET @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
       
      PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '''+@IDAFILIADO+''','''+@IDCATEGORIA+''''
      EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA

	   PRINT 'Termine de configurar AFI'
   --END
   SELECT TOP 1 @IDTERCEROAFI = IDTERCERO FROM TER WHERE NIT=(SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO=@IDAFILIADO) AND ESTADO='Activo'
   PRINT '************************@IDTERCEROAFI: ' + COALESCE(@IDTERCEROAFI,'')
   --SELECT @DOCIDAFILIADO=IDAFILIADO FROM AFI WHERE (IDAFILIADO=@IDAFILIADO OR DOCIDAFILIADO=@IDAFILIADO) 
   --AND EXISTS(SELECT IDTERCERO FROM TER WHERE IDTERCERO=AFI.IDAFILIADO)

   SELECT  @DOCIDAFILIADO=AFI.IDAFILIADO
   FROM #T LEFT JOIN AFI ON #T.IDAFILIADO=AFI.IDAFILIADO
   WHERE EXISTS(SELECT * FROM TER WHERE (#T.IDTERCERO=TER.IDTERCERO OR AFI.DOCIDAFILIADO=TER.NIT))
   PRINT '*************************@DOCIDAFILIADO: '+ISNULL(@DOCIDAFILIADO,'')

   PRINT 'Insertando Asiento del Concepto de Caja. (DB)'  
   IF (SELECT TIPO FROM #T) = 'EXTERNO' AND (SELECT CLASER FROM #T) = 'C'
   BEGIN
      PRINT ' -Insertando Registro MCH Con Conceptos (DB)'
      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
                       REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,
                       IDAREA,CLASECONT,ESTADO,PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO,
                       N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
      SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',
			CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
			          CASE WHEN FPA.REQBCO = 1 THEN BCT.COD_CONTABLE ELSE CAJ.CUENTA END
			          ELSE 
			          FPA.CUENTA 
			 END,
             CASE WHEN FPA.CXC=1 THEN 
                  #THD.IDTERCERO 
             ELSE
               (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
				CASE WHEN COALESCE(@IDTERCEROAFI,'')='' THEN  
					CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END ELSE @IDTERCEROAFI END 
				END)
              END
              , #T.CCOSTO,
             'INGRESO POR '+UPPER(CPCJ.DESCRIPCION)+', CAJA No.'+@CODCAJA+ ', RECIBO No.'+#T.CNSFACJ+', FORMAPAGO: '+UPPER(FPA.DESCRIPCION),
             SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),
             #T.CNSFACJ, #T.CODCAJA, CPCJ.CODIGO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
             NULL, #T.AREAPRESTACION, 'S', 1, 'INGRESO_CAJ', 'Movimiento','CAJA',@CNSFACJ,
             CASE WHEN DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO')=FPA.FORMAPAGO 
                  THEN LTRIM(RTRIM(#THD.CODCAJADEP))+#THD.CNSFACJDEP 
                  ELSE LTRIM(RTRIM(#T.CODCAJA))+ #T.CNSFACJ 
             END,
             CASE WHEN DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO')=FPA.FORMAPAGO THEN 
                   (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CODCAJA=#THD.CODCAJADEP AND CNSFACJ=#THD.CNSFACJDEP) 
                  ELSE DBO.FNK_FECHA_SIN_HORA(#T.FECHA) 
             END,
             CASE WHEN DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO')=FPA.FORMAPAGO THEN 
                   (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CODCAJA=#THD.CODCAJADEP AND CNSFACJ=#THD.CNSFACJDEP) 
                  ELSE DBO.FNK_FECHA_SIN_HORA(#T.FECHA) 
             END, 
             CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM #T INNER JOIN #TH  ON #T.CODCAJA    = #TH.CODCAJA 
                             AND #T.CNSFACJ    = #TH.CNSFACJ 
              INNER JOIN #THD ON #TH.CODCAJA   = #THD.CODCAJA 
                             AND #TH.CNSFACJ   = #THD.CNSFACJ 
              INNER JOIN CAJ  ON #T.CODCAJA    = CAJ.CODCAJA 
              INNER JOIN CPCJ ON CPCJ.CODIGO   = #TH.CONCEPTO 
              INNER JOIN FPA  ON #THD.TIPOPAGO = FPA.FORMAPAGO
			  LEFT JOIN   BCT  ON #THD.BANCO=BCT.BANCO AND #THD.SUCURSAL=BCT.SUCURSAL AND #THD.CTA_BCO=BCT.CTA_BCO 

      GROUP BY CAJ.CUENTA, FPA.CUENTA, BCT.COD_CONTABLE, #T.IDTERCERO, #T.CCOSTO, #T.CNSFACJ, #T.AREAPRESTACION, #T.CODCAJA,
               CPCJ.DESCRIPCION, FPA.DESCRIPCION, CPCJ.CODIGO,             
			    CASE WHEN FPA.CXC=1 THEN 
                  #THD.IDTERCERO 
             ELSE
               (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
				CASE WHEN COALESCE(@IDTERCEROAFI,'')='' THEN  
					CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END ELSE @IDTERCEROAFI END 
				END)
              END, FPA.USAR_CUENTACAJA, FPA.FORMAPAGO, FPA.REQBCO,
               #THD.CNSFACJDEP, #THD.CODCAJADEP, #T.FECHA, #T.CODUNG, #T.CODPRG
      HAVING SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100)<>0



      PRINT 'TERMINO INSERT DB........'
   END
   ELSE
   IF (SELECT TIPO FROM #T)='CREDITO'
   BEGIN
     PRINT ' -Insertando Registro MCH Sin Conceptos A DEBITO  TIPO CREDITO'
     INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR, REFERENCIA1, REFERENCIA2, 
                      ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, 
                      N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE,@COMPANIA,'DB',TER.CUENTA,
            (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
			CASE WHEN COALESCE(@IDTERCEROAFI,'')='' THEN 	CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END ELSE @IDTERCEROAFI END
			END),#T.CCOSTO,
  	         'VTA CREDITO: '+RTRIM(TER.RAZONSOCIAL)+', CAJA: '+@CODCAJA+', RECIBO: '+#T.CNSFACJ,
  	         SUM(#TH.VALORTOTAL),#T.CNSFACJ,#T.CODCAJA,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),
  	         NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'INGRESO_CAJ', 'Movimiento','CAJA',@CNSFACJ,
            CASE WHEN COALESCE(#T.N_FACTURA,'')<>'' THEN COALESCE(#T.N_FACTURA,'') ELSE  RTRIM(#T.CODCAJA)+#T.CNSFACJ END,
            DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
     FROM   #TH,#T,TER
     WHERE  #T.IDTERCERO = TER.IDTERCERO
     GROUP BY TER.CUENTA,#T.IDTERCERO,#T.CCOSTO,#T.CNSFACJ,LEFT(#T.AREAPRESTACION,10),#T.CODCAJA,
              TER.RAZONSOCIAL, #T.IDAFILIADO, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.CODUNG, #T.CODPRG
     HAVING SUM(#TH.VALORTOTAL)<>0
   
     PRINT ' -Insertando Registro MCH Con Error... (El Tercero no existe en TER)'
     INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                      REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO, GENERA,
                      PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE,@COMPANIA,'DB','NO DEF.TER',
            (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
				CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END
			END),#T.CCOSTO,
            'VTA CREDITO: '+#T.IDTERCERO+', CAJA: '+@CODCAJA+', RECIBO: '+#T.CNSFACJ,
            SUM(#TH.VALORTOTAL),#T.CNSFACJ,#T.CODCAJA,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),
            NULL,LEFT(#T.AREAPRESTACION,10),'S',1,'INGRESO_CAJ', 'Movimiento','CAJA',@CNSFACJ,
            RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
     FROM   #TH,#T
     WHERE NOT #T.IDTERCERO IN (SELECT IDTERCERO FROM TER WHERE TER.IDTERCERO=#T.IDTERCERO)
     GROUP BY #T.IDTERCERO,#T.CCOSTO,#T.CNSFACJ,LEFT(#T.AREAPRESTACION,10),#T.CODCAJA, 
              #T.IDAFILIADO, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.CODUNG, #T.CODPRG
     HAVING SUM(#TH.VALORTOTAL)<>0
   END
   ELSE  
   BEGIN
      IF @PROCEDENCIA = 'CAJA'
      BEGIN
         PRINT 'INGRESO PROCEDENCIA CAJA'
         INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
                          REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,
                          IDAREA,CLASECONT,ESTADO,PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO,
                          N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
         SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 
					CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
						CASE WHEN FPA.REQBCO = 1 THEN BCT.COD_CONTABLE ELSE CAJ.CUENTA END
			        ELSE 
			          FPA.CUENTA 
					END,
             CASE WHEN FPA.CXC=1 THEN 
                  #THD.IDTERCERO 
             ELSE
                (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
					CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END
				END) END, #T.CCOSTO,
                UPPER(FPA.DESCRIPCION)+', CAJA No.'+@CODCAJA+', RECIBO No.'+#T.CNSFACJ, SUM(#THD.VALOR),  
                #T.CNSFACJ, #T.CODCAJA, FPA.FORMAPAGO, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                NULL, #T.AREAPRESTACION, 'S' , 1, 'INGRESO_CAJ', 'Movimiento', 'CAJA', @CNSFACJ,
                RTRIM(#T.CODCAJA)+#T.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(#T.FECHA),  DBO.FNK_FECHA_SIN_HORA(#T.FECHA),
                CASE WHEN #T.CODUNG = '' 
                     THEN NULL 
                     ELSE #T.CODUNG 
                END, 
                CASE WHEN #T.CODPRG = '' 
                     THEN NULL 
                     ELSE #T.CODPRG 
                END
         FROM   #T INNER JOIN #THD ON #T.CODCAJA    = #THD.CODCAJA AND #T.CNSFACJ = #THD.CNSFACJ 
                   INNER JOIN CAJ  ON #T.CODCAJA    = CAJ.CODCAJA 
                   INNER JOIN FPA  ON #THD.TIPOPAGO = FPA.FORMAPAGO 
				   LEFT JOIN   BCT  ON #THD.BANCO=BCT.BANCO AND #THD.SUCURSAL=BCT.SUCURSAL AND #THD.CTA_BCO=BCT.CTA_BCO 

       --  WHERE  FPA.FISICO = 1 /*Se comentariza ya que debe aplicar para todas las formas de pago */
         GROUP BY CAJ.CUENTA, FPA.CUENTA, BCT.COD_CONTABLE, #T.IDTERCERO, #T.CCOSTO, #T.CNSFACJ, #T.AREAPRESTACION, #T.CODCAJA,
              FPA.DESCRIPCION, FPA.FORMAPAGO,CASE WHEN FPA.CXC=1 THEN 
                  #THD.IDTERCERO 
             ELSE
                (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
					CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END
				END) END, FPA.USAR_CUENTACAJA, FPA.FORMAPAGO,FPA.REQBCO, #THD.CNSFACJDEP,
              #THD.CODCAJADEP, #T.FECHA, #T.CODUNG, #T.CODPRG
         HAVING SUM(#THD.VALOR) <> 0 
      END
      ELSE
      BEGIN
         PRINT ' -Insertando Registro MCH Sin Conceptos de Contado NO KAJA'
         INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
                         REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,
                         IDAREA,CLASECONT,ESTADO,PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO,
                         N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
         SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', CASE WHEN FPA.USAR_CUENTACAJA = 1 THEN
					CASE WHEN FPA.REQBCO = 1 THEN BCT.COD_CONTABLE ELSE CAJ.CUENTA END
			        ELSE 
			          FPA.CUENTA 
					END,
             CASE WHEN FPA.CXC=1 OR #THD.TIPOPAGO=DBO.FNK_VALORVARIABLE('IDCJFPADESCUENT_NOMI') THEN 
                  #THD.IDTERCERO 
             ELSE
                (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' 
					  THEN #T.IDTERCERO 
					  ELSE 
					  CASE WHEN COALESCE(@IDTERCEROAFI,'')='' THEN	
								CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDTERCERO END 
								ELSE @IDTERCEROAFI END 
					  END) END, #T.CCOSTO,
                UPPER(FPA.DESCRIPCION)+', CAJA No.'+@CODCAJA+', RECIBO No.'+#T.CNSFACJ,
                SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),
                #T.CNSFACJ,#T.CODCAJA,FPA.FORMAPAGO,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                NULL,#T.AREAPRESTACION, 'S', 1, 'INGRESO_CAJ', 'Movimiento', 'CAJA', @CNSFACJ,
                CASE WHEN DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO')=FPA.FORMAPAGO 
                     THEN LTRIM(RTRIM(#THD.CODCAJADEP))+#THD.CNSFACJDEP 
                     ELSE RTRIM(#T.CODCAJA)+#T.CNSFACJ 
                END,
                CASE WHEN DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO')=FPA.FORMAPAGO 
                     THEN (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CODCAJA=#THD.CODCAJADEP AND CNSFACJ=#THD.CNSFACJDEP) 
                     ELSE DBO.FNK_FECHA_SIN_HORA(#T.FECHA) 
                END,
                CASE WHEN DBO.FNK_VALORVARIABLE('IDCJLEGDEPOSITO')=FPA.FORMAPAGO 
                     THEN (SELECT DBO.FNK_FECHA_SIN_HORA(FECHA) FROM FCJ WHERE CODCAJA=#THD.CODCAJADEP AND CNSFACJ=#THD.CNSFACJDEP) 
                     ELSE DBO.FNK_FECHA_SIN_HORA(#T.FECHA) 
                END, 
                CASE WHEN #T.CODUNG = '' 
                     THEN NULL 
                     ELSE #T.CODUNG 
                END, 
                CASE WHEN #T.CODPRG = '' 
                     THEN NULL 
                     ELSE #T.CODPRG 
                END
         FROM #T INNER JOIN 
              #TH ON #T.CODCAJA=#TH.CODCAJA AND #T.CNSFACJ=#TH.CNSFACJ INNER JOIN
              #THD ON #TH.CODCAJA=#THD.CODCAJA AND #TH.CNSFACJ=#THD.CNSFACJ INNER JOIN
              CAJ ON #T.CODCAJA=CAJ.CODCAJA INNER JOIN 
              FPA ON #THD.TIPOPAGO=FPA.FORMAPAGO 
			  LEFT JOIN   BCT  ON #THD.BANCO=BCT.BANCO AND #THD.SUCURSAL=BCT.SUCURSAL AND #THD.CTA_BCO=BCT.CTA_BCO 
         GROUP BY CAJ.CUENTA, FPA.CUENTA, BCT.COD_CONTABLE, #T.IDTERCERO, #T.CCOSTO, #T.CNSFACJ, #T.AREAPRESTACION, #T.CODCAJA,
              FPA.DESCRIPCION, FPA.FORMAPAGO,CASE WHEN FPA.CXC=1  OR #THD.TIPOPAGO=DBO.FNK_VALORVARIABLE('IDCJFPADESCUENT_NOMI') THEN 
                  #THD.IDTERCERO 
             ELSE
                (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
					 CASE WHEN COALESCE(@IDTERCEROAFI,'')='' THEN	
								CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDTERCERO END 
								ELSE @IDTERCEROAFI END 
				END) END, FPA.USAR_CUENTACAJA, FPA.FORMAPAGO, FPA.REQBCO, #THD.CNSFACJDEP,
              #THD.CODCAJADEP, #T.FECHA, #T.CODUNG, #T.CODPRG
         HAVING SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100)<>0
      END
   END
 
   PRINT 'Insetardo Asiento del Concepto de Caja. (CR)' 
   IF (SELECT COUNT(*) FROM FCJPCXC A,#T WHERE A.CODCAJA=#T.CODCAJA AND A.CNSFACJ=#T.CNSFACJ AND COALESCE(#T.N_FACTURAPOS,'')='')>0
   BEGIN
      UPDATE FCJ SET RECAUDO=1 FROM #T WHERE FCJ.CODCAJA=#T.CODCAJA AND FCJ.CNSFACJ=#T.CNSFACJ AND COALESCE(#T.N_FACTURAPOS,'')=''
      UPDATE #T SET RECAUDO=1 
   END

 IF (SELECT RECAUDO FROM #T)=1
 BEGIN
  PRINT 'Recaudos...'
  IF EXISTS(SELECT COMPANIA FROM PAR WHERE COMPANIA=@COMPANIA)
  BEGIN
     IF NOT EXISTS(SELECT A.CNSFACJ FROM FCJPCXC A,#T WHERE A.CODCAJA=#T.CODCAJA AND A.CNSFACJ=#T.CNSFACJ AND #T.N_FACTURA=A.N_FACTURA )
     BEGIN
        PRINT 'Sin CxC'
        INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                         REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO, 
                         PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
        SELECT @NROCOMPROBANTE,@COMPANIA,'CR',
               (CASE WHEN FPA.CXC=1 THEN (SELECT CUENTA FROM TTEC WHERE TIPO= DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART'))
                     WHEN COALESCE(FPA.CXC,0)=0  AND UPPER(DBO.FNK_VALORVARIABLE('USARCUEPUENTE'))='SI' THEN   PAR.CTA_CAJ_REC_NOLEG 
					 WHEN  COALESCE(#THD.CUENTA,'')='' AND #T.IDPLAN IN (SELECT DATO FROM USVGS WHERE IDVARIABLE LIKE 'IDPLANPART%')   
                THEN   (SELECT CUENTA FROM TTEC WHERE TIPO= DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART'))
					 ELSE #THD.CUENTA 
                END),
               (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
					CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END
				END),#T.CCOSTO,
               UPPER(FPA.DESCRIPCION)+(CASE WHEN #THD.NUMERODOCUMENTO IS NULL THEN '' ELSE ', DOC.:'+#THD.NUMERODOCUMENTO END)+
               ', CLIENTE: '+UPPER(#T.NOMBRECLIENTE),
               SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),#T.CNSFACJ,#T.CODCAJA,
               'CTA_CAJ_REC_NOLEG',NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,
               LEFT(#T.AREAPRESTACION,10),'S',1,'DEP_CLIENTES', 'Movimiento',
               CASE WHEN COALESCE(#T.N_FACTURA,'')<>'' THEN COALESCE(#T.N_FACTURA,'') ELSE  RTRIM(#T.CODCAJA)+#T.CNSFACJ END
,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',
               @CNSFACJ, 
                CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
        FROM #T,#TH,#THD,FPA,PAR
        WHERE PAR.COMPANIA=@COMPANIA AND #THD.TIPOPAGO=FPA.FORMAPAGO
        GROUP BY #T.IDTERCERO,#T.CCOSTO,#T.CNSFACJ,#T.N_FACTURA,#T.PROCEDENCIA,
                 LEFT(#T.AREAPRESTACION,10),#T.CODCAJA,FPA.DESCRIPCION,
                 #THD.NUMERODOCUMENTO,#T.NOMBRECLIENTE,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),
                 FPA.CXC,PAR.CTA_CAJ_REC_NOLEG, #T.IDAFILIADO, #THD.CUENTA, #T.CODUNG, #T.CODPRG, #T.IDPLAN 
     END
     ELSE
     BEGIN
      PRINT 'Con CxC'
      
      PRINT 'Actualizando pagos '--jalfaro 30/03/2012
      IF (SELECT COUNT(*) FROM FCJPCXC WHERE CNSFACJ=@CNSFACJ AND CODCAJA=@CODCAJA)>0
      BEGIN
         UPDATE FCJ SET ENPAGOS=1 WHERE CNSFACJ=@CNSFACJ AND CODCAJA=@CODCAJA
      END   
      
      DECLARE CUR_PAGOS CURSOR FOR
      SELECT CNSFPAG FROM FCJPCXC WHERE CNSFACJ=@CNSFACJ AND CODCAJA=@CODCAJA
        
      OPEN CUR_PAGOS
        
      FETCH NEXT FROM CUR_PAGOS
      INTO @CNSFPAG
      WHILE @@FETCH_STATUS = 0
      BEGIN
         SELECT * INTO #P FROM FPAG WHERE CNSFPAG=@CNSFPAG
         SELECT * INTO #PH FROM FPAGD WHERE CNSFPAG=@CNSFPAG
         
         SELECT   @VALORIMPUESTOS = VLRIMPUESTOS,
                  @VLRAJUSTEPESO  = VLRAJUSTEPESO
         FROM #P
           
         PRINT 'Contabilizando Impuestos...' 
         IF @VALORIMPUESTOS>0
         BEGIN 
          INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                           REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                           CLASECONT, VALOR_PORCIMP,BASE_IMP, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, 
                           REFERENCIA_PRO, CODUNG, CODPRG)
          SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', FIMPDV.CUENTA, #P.IDTERCERO, '' AS CCOSTO, 
                 'IMP POR '+FIMPDV.IDIMPUESTO+' CLASE '+FIMPDV.IDCLASE+' FA '+#PH.N_FACTURA, 
                 SUM(FPAGDI.VLRIMPUESTO), FIMPDV.IDIMPUESTO, FIMPDV.IDCLASE, FIMPDV.ITEM, NULL, @USUARIO, 
                 DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_IMPUESTOS', 
                 'Movimiento','S', FIMPDV.VALOR,FPAGDI.BASE,#PH.N_FACTURA,
                 DBO.FNK_FECHA_SIN_HORA(#P.FECHA),DBO.FNK_FECHA_SIN_HORA(#P.FECHA),'CAJA',@CNSFACJ, 
                 CASE WHEN #PH.CODUNG = '' THEN NULL ELSE #PH.CODUNG END, CASE WHEN #PH.CODPRG = '' THEN NULL ELSE #PH.CODPRG END
          FROM #P,#PH,FPAGDI,FIMPDV  
          WHERE #PH.CNSFPAG=FPAGDI.CNSFPAG AND #PH.N_FACTURA=FPAGDI.N_FACTURA AND
                FPAGDI.IDIMPUESTO=FIMPDV.IDIMPUESTO AND FPAGDI.IDCLASE=FIMPDV.IDCLASE AND
                FPAGDI.ITEMFIMPDV=FIMPDV.ITEM AND FPAGDI.VLRIMPUESTO>0   
          GROUP BY FIMPDV.CUENTA, IDTERCERO, #PH.N_FACTURA,#P.IDTERCERO,#PH.N_FACTURA,
                   FIMPDV.IDIMPUESTO,FIMPDV.IDCLASE,FIMPDV.ITEM,FIMPDV.VALOR,FPAGDI.BASE,
                   DBO.FNK_FECHA_SIN_HORA(#P.FECHA), #PH.CODUNG, #PH.CODPRG
        
          INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                          REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, 
                          GENERA, CLASECONT, VALOR_PORCIMP, BASE_IMP, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA,
                          REFERENCIA_PRO, CODUNG, CODPRG)
          SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 'NO DEF.IMP', #P.IDTERCERO, '' AS CCOSTO, 
                 'IMPUESTO NO EXISTE EN TABLA DE IMPUESTO: '+FPAGDI.IDIMPUESTO+' CLASE '+FPAGDI.IDCLASE+
                 ' FA '+#PH.N_FACTURA, 
                 SUM(FPAGDI.VLRIMPUESTO), FPAGDI.IDIMPUESTO, FPAGDI.IDCLASE, FPAGDI.ITEMFIMPDV, NULL, @USUARIO, 
                 DBO.FNK_FECHA_SIN_MLS(GETDATE()), '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_IMPUESTOS',
                 'Movimiento', 'S', (SUM(FPAGDI.VLRIMPUESTO)*100)/FPAGDI.BASE, FPAGDI.BASE,
                 #PH.N_FACTURA,DBO.FNK_FECHA_SIN_HORA(#P.FECHA),DBO.FNK_FECHA_SIN_HORA(#P.FECHA),'CAJA',@CNSFACJ, 
                 CASE WHEN #PH.CODUNG = '' THEN NULL ELSE #PH.CODUNG END, CASE WHEN #PH.CODPRG = '' THEN NULL ELSE #PH.CODPRG END
          FROM #P,#PH,FPAGDI
          WHERE #PH.CNSFPAG=FPAGDI.CNSFPAG AND #PH.N_FACTURA=FPAGDI.N_FACTURA AND FPAGDI.VLRIMPUESTO>0 AND
        	   NOT FPAGDI.IDIMPUESTO IN (SELECT FIMPDV.IDIMPUESTO FROM FIMPDV 
                                       WHERE  FPAGDI.IDIMPUESTO=FIMPDV.IDIMPUESTO AND
                                              FPAGDI.IDCLASE=FIMPDV.IDCLASE AND
                                              FPAGDI.ITEMFIMPDV=FIMPDV.ITEM)
          GROUP BY IDTERCERO, #PH.N_FACTURA,#P.IDTERCERO,#PH.N_FACTURA,FPAGDI.IDIMPUESTO,
                   FPAGDI.IDCLASE,FPAGDI.ITEMFIMPDV,FPAGDI.BASE, DBO.FNK_FECHA_SIN_HORA(#P.FECHA), #PH.CODUNG, #PH.CODPRG
         END
     
         IF @VLRAJUSTEPESO>0
         BEGIN
          IF EXISTS(SELECT TIPO FROM KCDE WHERE TIPO='CXC_AJ_AFAVOR')
          BEGIN
           PRINT 'Contabilizando Ajuste al Peso a Favor...' 
           INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                            CLASECONT, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
           SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', KCDE.CUENTA, #P.IDTERCERO,'' AS CCOSTO, 
                  'AJUSTE AL PESO ', ABS(#P.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                  '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_AFAVOR', 'Movimiento','S','CXC',@CNSFPAG,
                  RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 
                  CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
           FROM #P,KCDE,#T
           WHERE KCDE.IDMODELOCONT=@IDMODELOCONT AND KCDE.TIPO='CXC_AJ_AFAVOR' AND #P.VLRAJUSTEPESO>0
          END
          ELSE
          BEGIN
           PRINT 'Contabilizando Ajueste con Error... (No Existe KCDE=CXC_AJ_AFAVOR)' 
           INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                            REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                            CLASECONT, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
           SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 'NO DEF.KCDE', #P.IDTERCERO,'' AS CCOSTO, 
                  'AJUSTE AL PESO ', ABS(#P.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                  '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_AFAVOR', 'Movimiento','S','CAJA',@CNSFACJ,
                  CASE WHEN COALESCE(#T.N_FACTURA,'')<>'' THEN COALESCE(#T.N_FACTURA,'') ELSE  RTRIM(#T.CODCAJA)+#T.CNSFACJ END,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 
                  CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
           FROM #P,#T
           WHERE #P.VLRAJUSTEPESO>0
          END
         END
         ---------------------------QUERY2
  IF @VLRAJUSTEPESO<0
         BEGIN
          IF EXISTS(SELECT TIPO FROM KCDE WHERE TIPO='CXC_AJ_ENCONTRA')
          BEGIN
           PRINT 'Contabilizando Ajuste al Peso En Contra...' 
           INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                           REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                           CLASECONT, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
           SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', KCDE.CUENTA, #P.IDTERCERO,'' AS CCOSTO, 
                  'AJUSTE AL PESO ', ABS(#P.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                  '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_ENCONTRA', 'Movimiento','S','CXC',@CNSFPAG,
                  RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 
                  CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
           FROM #P,KCDE,#T
           WHERE KCDE.IDMODELOCONT=@IDMODELOCONT AND KCDE.TIPO='CXC_AJ_ENCONTRA' AND #P.VLRAJUSTEPESO<0
          END
          ELSE
          BEGIN
           PRINT 'Contabilizando Ajueste con Error... (No Existe KCDE=CXC_AJ_ENCONTRA)' 
           INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR ,REFERENCIA1,
                           REFERENCIA2, ITEMREF, USUARIO, FECHA, IDAREA, PREFIJO, ESTADO, PROCESO, GENERA, 
                           CLASECONT, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
           SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 'NO DEF.KCDE', #P.IDTERCERO,'' AS CCOSTO, 
                  'AJUSTE AL PESO ', ABS(#P.VLRAJUSTEPESO), NULL, NULL, NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                  '' AS IDAREA, '' AS PREFIJO, 1, 'CXC_AJ_ENCONTRA', 'Movimiento','S','CAJA',@CNSFACJ,
                  RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 
                  CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
           FROM #P,#T
           WHERE #P.VLRAJUSTEPESO>0
          END
         END
        
        DROP TABLE #P
        DROP TABLE #PH
           
        FETCH NEXT FROM CUR_PAGOS
        INTO @CNSFPAG
      END
      CLOSE CUR_PAGOS
      DEALLOCATE CUR_PAGOS
      SELECT @VEZFCXCDV = 0
      IF (SELECT COUNT(*) FROM FCJPCXC WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA) = 1 AND
         (( SELECT PROCEDENCIA FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA) = 'CE' OR
          ( SELECT PROCEDENCIA FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA) = 'CITAS')
      BEGIN
         SELECT @N_FACTURA = N_FACTURA, @CNSCXC = CNSCXC FROM FCJPCXC WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
         SELECT @VEZFCXCDV = COUNT(*) FROM FCXCDV WHERE N_FACTURA = @N_FACTURA AND @CNSCXC = @CNSCXC
      END

	  PRINT 'TERCERO AFI :'+ @IDTERCEROAFI
        
      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                       REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO, 
                       PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
      SELECT DISTINCT @NROCOMPROBANTE,@COMPANIA,'CR',FCXCD.CUENTA,
             (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
				CASE WHEN COALESCE(@IDTERCEROAFI,'')='' THEN   CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDTERCERO END ELSE @IDTERCEROAFI END 
			 END),#T.CCOSTO,
             'FA '+FCJPCXC.N_FACTURA+', CXC '+FCJPCXC.CNSCXC+', NIT '+FCJPCXC.IDTERCERO,
             FCJPCXC.VALOR,#T.CNSFACJ,#T.CODCAJA,'PAGO_CXC_CAJA',NULL,@USUARIO,
             DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#T.AREAPRESTACION,10),'S',1,
             'PAGO_CXC_CAJA', 'Movimiento', FCJPCXC.N_FACTURA, 
             DBO.FNK_FECHA_SIN_HORA(FCXCDV.FECHA),DBO.FNK_FECHA_SIN_HORA(FCXCDV.F_VENCE),'CAJA',@CNSFACJ, 
             CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
      FROM   #T,FCXCD,FCXCDV,FCJPCXC
      WHERE  FCJPCXC.CODCAJA  = #T.CODCAJA 
      AND    FCJPCXC.CNSFACJ  = #T.CNSFACJ 
      AND    FCXCD.CNSCXC     = FCJPCXC.CNSCXC 
      AND    FCXCD.N_FACTURA  = FCJPCXC.N_FACTURA 
      AND    FCXCDV.CNSCXC    = FCJPCXC.CNSCXC 
      AND    FCXCDV.N_FACTURA = FCJPCXC.N_FACTURA
      AND    FCXCDV.ITEM      = CASE WHEN COALESCE(@VEZFCXCDV,0) = 1 THEN  FCXCDV.ITEM ELSE  FCJPCXC.ITEM_FCXCDV END
   
      SELECT @TOTAL_CRUCE=SUM(VALOR) FROM FCJPCXC WHERE CNSFACJ=@CNSFACJ AND CODCAJA=@CODCAJA
     
      IF (SELECT VALORTOTAL FROM #T)>@TOTAL_CRUCE
      BEGIN
       SELECT @SALDO          = VALORTOTAL - @TOTAL_CRUCE,
              @TOTAL_ORIGINAL = VALORTOTAL
       FROM #T
   
       UPDATE #T SET VALORTOTAL  = @SALDO
       UPDATE #TH SET VALORTOTAL = (VALORTOTAL*100/@TOTAL_ORIGINAL)*@SALDO/100
       UPDATE #THD SET VALOR     = (VALOR*100/@TOTAL_ORIGINAL)*@SALDO/100
   
       PRINT 'Contabiliza Excedente en el Pago a favor del Cliente.' 
       INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                   REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO, 
                   PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
       SELECT @NROCOMPROBANTE,@COMPANIA,'CR',
             (CASE WHEN FPA.CXC=1 THEN (SELECT CUENTA FROM TTEC WHERE TIPO=DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART'))
                                  ELSE CASE WHEN UPPER(DBO.FNK_VALORVARIABLE('USARCUEPUENTE'))='SI' THEN 
                                        PAR.CTA_CAJ_REC_NOLEG ELSE #THD.CUENTA END
              END),
             (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
				CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END
			 END),#T.CCOSTO,
             UPPER(FPA.DESCRIPCION)+  
             (CASE WHEN #THD.NUMERODOCUMENTO IS NULL THEN '' ELSE ', DOC.:'+#THD.NUMERODOCUMENTO END)+
             ', CLIENTE: '+UPPER(#T.NOMBRECLIENTE),
             SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),#T.CNSFACJ,#T.CODCAJA,
             'CTA_CAJ_REC_NOLEG',NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,
             LEFT(#T.AREAPRESTACION,10),'S',1,'DEP_CLIENTES', 'Movimiento',
             CASE WHEN COALESCE(#T.N_FACTURA,'')<>'' THEN COALESCE(#T.N_FACTURA,'') ELSE  RTRIM(#T.CODCAJA)+#T.CNSFACJ END,
             DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
             CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
       FROM #T,#TH,#THD,FPA,PAR
       WHERE PAR.COMPANIA=@COMPANIA AND #THD.TIPOPAGO=FPA.FORMAPAGO
       GROUP BY #T.IDTERCERO,#T.CCOSTO,#T.CNSFACJ,
               LEFT(#T.AREAPRESTACION,10),#T.CODCAJA,FPA.DESCRIPCION,
               #THD.NUMERODOCUMENTO,#T.NOMBRECLIENTE,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),
               FPA.CXC,PAR.CTA_CAJ_REC_NOLEG, #T.IDAFILIADO, #THD.CUENTA, #T.CODUNG, #T.CODPRG,
               CASE WHEN COALESCE(#T.N_FACTURA,'')<>'' THEN COALESCE(#T.N_FACTURA,'') ELSE  RTRIM(#T.CODCAJA)+#T.CNSFACJ END
      END
     END
    END  
    ELSE 
    BEGIN 
     PRINT ' -Insertando Registro MCH Con Error... (No se encontrCuenta Puente de CAJA)'
     INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                     REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO, 
                     PROCESO,GENERA, N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE,@COMPANIA,'CR','NO DEF.PAR',
            (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
				CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END 
			END),#T.CCOSTO,#T.CNSFACJ,
            SUM(#TH.VALORTOTAL),#T.CNSFACJ,#T.CODCAJA,'CTA_CAJ_REC_NOLEG',NULL,@USUARIO,
            DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#T.AREAPRESTACION,10),'S',0,
            'DEP_CLIENTES', 'Movimiento', RTRIM(#T.CODCAJA)+#T.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 
            DBO.FNK_FECHA_SIN_HORA(#T.FECHA),'CAJA',@CNSFACJ, 
            CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
     FROM #T,#TH
     GROUP BY #T.IDTERCERO,#T.CCOSTO,#T.CNSFACJ,LEFT(#T.AREAPRESTACION,10),#T.CODCAJA, 
              DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #T.IDAFILIADO, #T.CODUNG, #T.CODPRG
    END
 END
 ELSE
  -- #T.RECAUDO = 0
 BEGIN
    PRINT 'No es Recaudo...' 
    -- IF EXISTS(SELECT CPCJ.CODIGO FROM CPCJ,#TH WHERE CPCJ.CODIGO = #TH.CONCEPTO)
    BEGIN
       IF (SELECT CLASER FROM #T) = 'S' OR (SELECT TIPO FROM #T)='CREDITO'
       BEGIN
          IF @PROCEDENCIA = 'CAJA'
          BEGIN
             SELECT @IDTERCERO = IDTERCERO, @IDPLAN = IDPLAN, @N_FACTURA = N_FACTURA 
             FROM   FCJ 
             WHERE  CNSFACJ = @CNSFACJ 
             AND    CODCAJA = @CODCAJA
             
             SELECT @CUENTACXC = TTEC.CUENTA
             FROM   TTEC INNER JOIN PPT ON TTEC.TIPO = PPT.TIPOTERCONTABLE
             WHERE  PPT.IDTERCERO = DBO.FNK_VALORVARIABLE('IDTERCEROCAJACOM')
             AND    PPT.IDPLAN    = @IDPLAN
                      
             INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                             REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA, 
                             PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
             SELECT @NROCOMPROBANTE, @COMPANIA,'CR', @CUENTACXC, @IDTERCERO, #T.CCOSTO, 'PAGO N_FACTURA:'+@N_FACTURA, 
                    SUM(#THD.VALOR), @CNSFACJ, @CODCAJA, @N_FACTURA, NULL, @USUARIO, DBO.FNK_FECHA_SIN_HORA(GETDATE()), NULL, 
                    #T.AREAPRESTACION, 'S', 1, '', 'Movimiento', 'CAJA', @CNSFACJ, @N_FACTURA, DBO.FNK_FECHA_SIN_HORA(GETDATE()),
                    DBO.FNK_FECHA_SIN_HORA(GETDATE()),  CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, 
                    CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
             FROM   #T INNER JOIN #THD ON #T.CNSFACJ = #THD.CNSFACJ AND #T.CODCAJA = #THD.CODCAJA
                       INNER JOIN  FPA ON #THD.TIPOPAGO = FPA.FORMAPAGO
             WHERE  FPA.FISICO = 1 
             GROUP BY #T.CCOSTO, #T.AREAPRESTACION, #T.CODUNG, #T.CODPRG, DBO.FNK_FECHA_SIN_HORA(#T.FECHA)
          END
          ELSE
          BEGIN
             PRINT ' -Insertando Registro MCH por Servicios por Prefijo.'
             INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                             REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA, 
                             PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, CODUNG, CODPRG)
             SELECT @NROCOMPROBANTE, @COMPANIA,'CR',
                    DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'VENTAS', 'CR', SER.PREFIJO, #T.CCOSTO, 'S', #TH.IDSERVICIO,0),
                    (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
						CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDAFILIADO END
					END),#T.CCOSTO,
                    'VENTA DE SERVICIOS: '+UPPER(PRE.NOM_PREFIJO),
                    SUM(#TH.VALORTOTAL),#T.CNSFACJ,#T.CODCAJA,'',NULL,@USUARIO,
                    DBO.FNK_FECHA_SIN_MLS(GETDATE()),SER.PREFIJO,#T.AREAPRESTACION,'S',1,
                    'COBRO_KMCOM', 'Movimiento','CAJA',@CNSFACJ,
                    RTRIM(#T.CODCAJA)+#T.CNSFACJ,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 
                    CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
             FROM   #T INNER JOIN #TH ON #T.CNSFACJ     = #TH.CNSFACJ 
                       LEFT JOIN  SER ON #TH.IDSERVICIO = SER.IDSERVICIO 
                       LEFT JOIN  PRE ON SER.PREFIJO    = PRE.PREFIJO
             GROUP BY #T.IDTERCERO,#T.CCOSTO,#T.CNSFACJ,#T.AREAPRESTACION,#T.CODCAJA,SER.PREFIJO,
                      PRE.NOM_PREFIJO, #T.IDAFILIADO, DBO.FNK_FECHA_SIN_HORA(#T.FECHA), #TH.IDSERVICIO, #T.CODUNG, #T.CODPRG
          END
       END    
       ELSE
       BEGIN
          PRINT ' -Insertando Registro MCH por Conceptos... ojo para depositos.........@DOCIDAFILIADO ='+@DOCIDAFILIADO
          INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                          REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA, 
                          N_FACTURA, F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO, CLASE_GENERA, CODUNG, CODPRG)
          SELECT @NROCOMPROBANTE,@COMPANIA,'CR',
                 (SELECT CASE WHEN DBO.FNK_VALORVARIABLE('IDCJAPERTURACAJA')=CPCJ.CODIGO THEN (SELECT CUENTA 
                                        FROM CAJ 
                                        WHERE CODCAJA=#T.CODCAJA) 
               ELSE CPCJ.CUENTA 
               END),
                 CASE WHEN #TH.CONCEPTO=DBO.FNK_VALORVARIABLE('IDCJDEPCLIATER') THEN
                  #TH.IDSERVICIO
                 ELSE
                  (CASE WHEN #T.IDAFILIADO IS NULL OR #T.IDAFILIADO='' THEN #T.IDTERCERO ELSE 
					CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE #T.IDTERCERO END
				  END)
                 END,
                 #T.CCOSTO,
                 'PAGO CON '+UPPER(FPA.DESCRIPCION)+' '+(CASE WHEN #THD.NUMERODOCUMENTO IS NULL THEN '' ELSE #THD.NUMERODOCUMENTO END)+
                 ', CONCEPTO: '+UPPER(CPCJ.DESCRIPCION)+', EN CAJA No.'+#T.CODCAJA+', POR '+UPPER(#T.NOMBRECLIENTE)+', RECIBO No.'+#T.CNSFACJ,
                 SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100),#T.CNSFACJ,#T.CODCAJA,CPCJ.CODIGO,NULL,
                  @USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,LEFT(#T.AREAPRESTACION,10),'S',1, 
                 CASE WHEN #TH.CONCEPTO=DBO.FNK_VALORVARIABLE('IDCJDEPCLIATER') THEN 'CXP_XDEPCLITER' ELSE 'COBRO_CPCJ' END, 
                 CASE WHEN #TH.CONCEPTO=DBO.FNK_VALORVARIABLE('IDCJDEPCLIATER') THEN 'Obligacion' ELSE 'Movimiento' END,
                 CASE CPCJ.CODIGO
                  WHEN DBO.FNK_VALORVARIABLE('IDCJCOPA') THEN #T.NOADMISION
                  WHEN DBO.FNK_VALORVARIABLE('IDCJABONOCP') THEN #T.NOADMISION
                  WHEN DBO.FNK_VALORVARIABLE('IDCJBONO') THEN #T.NOADMISION
                  WHEN DBO.FNK_VALORVARIABLE('IDCJMODE') THEN #T.NOADMISION
                  WHEN DBO.FNK_VALORVARIABLE('IDCJPACO') THEN #T.NOADMISION
                 ELSE
                  RTRIM(#T.CODCAJA)+#T.CNSFACJ
                 END,
                 DBO.FNK_FECHA_SIN_HORA(#T.FECHA),DBO.FNK_FECHA_SIN_HORA(#T.FECHA), 'CAJA',@CNSFACJ,
                 CASE WHEN #TH.CONCEPTO=DBO.FNK_VALORVARIABLE('IDCJDEPCLIATER') THEN 'Contab' ELSE NULL END, 
                 CASE WHEN #T.CODUNG = '' THEN NULL ELSE #T.CODUNG END, CASE WHEN #T.CODPRG = '' THEN NULL ELSE #T.CODPRG END
          FROM #T INNER JOIN 
               #TH ON #T.CNSFACJ=#TH.CNSFACJ INNER JOIN
               #THD ON #TH.CNSFACJ=#THD.CNSFACJ LEFT JOIN
               FPA ON #THD.TIPOPAGO=FPA.FORMAPAGO LEFT JOIN
               CPCJ ON  #TH.CONCEPTO=CPCJ.CODIGO
          GROUP BY CPCJ.CUENTA,#T.IDTERCERO,#T.CCOSTO,#T.CNSFACJ,LEFT(#T.AREAPRESTACION,10),#T.CODCAJA,
                   FPA.DESCRIPCION,#THD.NUMERODOCUMENTO,#T.NOMBRECLIENTE,CPCJ.CODIGO,CPCJ.DESCRIPCION,
                   #T.IDAFILIADO,DBO.FNK_FECHA_SIN_HORA(#T.FECHA),#T.NOADMISION,#TH.IDSERVICIO,#TH.CONCEPTO, 
                   #T.CODUNG, #T.CODPRG
          HAVING SUM((#THD.VALOR*100/#T.VALORTOTAL)*#TH.VALORTOTAL/100)<>0
          
          PRINT 'DEPOSITOS DE CLIENTES A TERCEROS JOSE'
          DECLARE CUR_CXP CURSOR FOR
          SELECT MCHE.IDTERCERO, MCHE.N_FACTURA, MCHE.F_FACTURAREF, MCHE.F_VENCE, 
                 LEFT('CXP POR DEPOSITO A '+RTRIM(LTRIM(TER.RAZONSOCIAL))+' NIT. '+RTRIM(LTRIM(TER.NIT)),255),
                 MCHE.CCOSTO, MCHE.IDAREA, MCHE.CUENTA, MCHE.CLASE_GENERA, SUM(MCHE.VALOR)
          FROM   MCHE LEFT JOIN TER ON MCHE.IDTERCERO = TER.IDTERCERO
          WHERE  MCHE.NROCOMPROBANTE = @NROCOMPROBANTE 
          AND    MCHE.PROCESO        = 'CXP_XDEPCLITER' 
          AND    MCHE.CLASE_GENERA   = 'Contab' 
          AND    MCHE.REFERENCIA1    = @CNSFACJ 
          AND    MCHE.REFERENCIA2    = @CODCAJA
          GROUP BY MCHE.IDTERCERO, MCHE.N_FACTURA, MCHE.F_FACTURAREF, MCHE.F_VENCE, 
                  LEFT('CXP POR DEPOSITO A '+RTRIM(LTRIM(TER.RAZONSOCIAL))+' NIT. '+RTRIM(LTRIM(TER.NIT)),255),
                  MCHE.CCOSTO, MCHE.IDAREA, MCHE.CUENTA, MCHE.CLASE_GENERA
                 
          OPEN CUR_CXP
                  
          FETCH NEXT FROM CUR_CXP
          INTO @IDTERCERO_CXP, @N_FACTURA_CXP, @F_FACTURA_CXP, @F_VENCE_CXP, @OBSERVACION_CXP, 
               @CCOSTO_CXP, @IDAREA_CXP, @CUENTA_CXP, @CLASE_GENERA_CXP, @VALOR_CXP
          WHILE @@FETCH_STATUS = 0
          BEGIN   
             SET @CNSFCXP=SPACE(20)
             EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FCXP',@CNSFCXP OUTPUT
             SELECT @CNSFCXP = @SEDE + REPLACE(SPACE(8 - LEN(@CNSFCXP))+LTRIM(RTRIM(@CNSFCXP)),SPACE(1),0)
                   
             PRINT 'Insertando CXP con CNS='+@CNSFCXP
             EXEC SPK_ADMIN_CXP_CONTAB 
                            @CNSFCXP,
                            @IDTERCERO_CXP,
                            @N_FACTURA_CXP,
                            @F_FACTURA_CXP,
                            @F_VENCE_CXP,
                            @USUARIO,
                            @OBSERVACION_CXP,
                            @COMPANIA,
                            @SYS_COMPUTERNAME,
                            @NROCOMPROBANTE,
                            @VALOR_CXP,     
                            @CCOSTO_CXP,
                            @IDAREA_CXP,  
                            'INSERT',
                            @CUENTA_CXP,
                            1,
                            @CLASE_GENERA_CXP
             PRINT 'Actualizando Consecutivo de CXP en MCH.' 
             
             UPDATE MCHE SET CNSFCXCXP = @CNSFCXP 
             WHERE MCHE.NROCOMPROBANTE=@NROCOMPROBANTE AND MCHE.PROCESO='CXP_XDEPCLITER' AND MCHE.CLASE_GENERA='Contab' AND
                   MCHE.REFERENCIA1=@CNSFACJ AND MCHE.REFERENCIA2=@CODCAJA AND MCHE.IDTERCERO=@IDTERCERO_CXP AND 
                   MCHE.N_FACTURA=@N_FACTURA_CXP
              
              
             FETCH NEXT FROM CUR_CXP
             INTO @IDTERCERO_CXP, @N_FACTURA_CXP, @F_FACTURA_CXP, @F_VENCE_CXP, @OBSERVACION_CXP, 
                  @CCOSTO_CXP, @IDAREA_CXP, @CUENTA_CXP, @CLASE_GENERA_CXP, @VALOR_CXP
          END
          CLOSE CUR_CXP
          DEALLOCATE CUR_CXP 
       END
    END
 END
 
-- COSTO MATERIALES Y MEDICAMENTOS
     PRINT 'Inserta por Servicio COSTO.'
     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                     ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE, @COMPANIA, KMCOM.TIPO,DBO.FNK_NC_CUENTA_KMCOM('01',KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,
                                                    KMCOM.CCOSTO,KMCOM.CLASECONT,FCJD.IDSERVICIO,0),
            CASE WHEN FCJ.IDAFILIADO IS NULL OR FCJ.IDAFILIADO='' THEN FCJ.IDTERCERO ELSE 
				CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE FCJ.IDAFILIADO END
			END, 
            KMCOM.CCOSTO, 'COSTO DE '+UPPER(IART.IDARTICULO)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
   	    (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, FCJD.CONCEPTO, NULL, @USUARIO, 
   	    DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
   	    'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
     FROM #TH FCJD, KMCOM, IART, #T FCJ
     WHERE IART.IDARTICULO=FCJD.IDSERVICIO AND IART.IDITAR=KMCOM.PREFIJO AND
   	   KMCOM.IDAREA=FCJ.AREAPRESTACION AND KMCOM.CCOSTO=FCJ.CCOSTO AND KMCOM.IDTIPOCONT='COSTOS' AND 
   	   KMCOM.CLASECONT='S' AND KMCOM.TIPO='DB' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD)>0
   
     PRINT 'Inserta Costo NO Configurado por Servicio.'
     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                     ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 'NO DEF.KMCOM',
            CASE WHEN FCJ.IDAFILIADO IS NULL OR FCJ.IDAFILIADO='' THEN FCJ.IDTERCERO ELSE 
				CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE FCJ.IDAFILIADO END 
			END, 
            KMCOM.CCOSTO, 'COSTO DE '+UPPER(IART.IDARTICULO)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
   	    (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, FCJD.CONCEPTO, NULL, @USUARIO, 
   	    DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
   	    'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
     FROM #TH FCJD, KMCOM, IART, #T FCJ
     WHERE IART.IDARTICULO=FCJD.IDSERVICIO AND IART.IDITAR=KMCOM.PREFIJO AND
   	   KMCOM.IDAREA=FCJ.AREAPRESTACION AND KMCOM.CCOSTO=FCJ.CCOSTO AND KMCOM.IDTIPOCONT='COSTOS' AND 
   	   KMCOM.CLASECONT='S' AND KMCOM.TIPO='CR' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD)>0 AND
   	   NOT KMCOM.PREFIJO IN 
   	    (SELECT PREFIJO FROM KMCOM X WHERE X.IDAREA=FCJ.AREAPRESTACION AND X.CCOSTO=FCJ.CCOSTO AND 
   	                               X.IDTIPOCONT='COSTOS' AND X.CLASECONT='S' AND X.TIPO='DB')
   
     PRINT 'Inserta Agrupado por Prefijo COSTO.'
     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                     ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE, @COMPANIA, KMCOM.TIPO,DBO.FNK_NC_CUENTA_KMCOM('01',KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,
                                                    KMCOM.CCOSTO,KMCOM.CLASECONT,'',0),
            CASE WHEN FCJ.IDAFILIADO IS NULL OR FCJ.IDAFILIADO='' THEN FCJ.IDTERCERO ELSE 
				CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE FCJ.IDAFILIADO END
			END, 
            KMCOM.CCOSTO, 'COSTO DE '+UPPER(ITAR.DESCRIPCION)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
   	    SUM(FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, '', NULL, @USUARIO, 
   	    DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
   	    'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
     FROM #TH FCJD, KMCOM, IART, #T FCJ, ITAR
     WHERE IART.IDARTICULO=FCJD.IDSERVICIO AND IART.IDITAR=ITAR.IDITAR AND IART.IDITAR=KMCOM.PREFIJO AND
   	   KMCOM.IDAREA=FCJ.AREAPRESTACION AND KMCOM.CCOSTO=FCJ.CCOSTO AND KMCOM.IDTIPOCONT='COSTOS' AND 
   	   KMCOM.CLASECONT='P' AND KMCOM.TIPO='DB' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD)>0
     GROUP BY KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,KMCOM.IDAREA,KMCOM.CCOSTO,KMCOM.CLASECONT,
            FCJ.IDAFILIADO, FCJ.IDTERCERO,ITAR.DESCRIPCION,FCJ.CODCAJA,FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA),
            FCJ.CODUNG, FCJ.CODPRG
   
     PRINT 'Inserta Costo NO Configurado por Servicio.'
     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                     ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', 'NO DEF.KMCOM',
            CASE WHEN FCJ.IDAFILIADO IS NULL OR FCJ.IDAFILIADO='' THEN FCJ.IDTERCERO ELSE 
				CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE FCJ.IDAFILIADO END
			END, 
            KMCOM.CCOSTO, 'COSTO DE '+UPPER(ITAR.DESCRIPCION)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
   	    SUM(FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, '', NULL, @USUARIO, 
   	    DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
   	    'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
     FROM #TH FCJD, KMCOM, IART, #T FCJ, ITAR
     WHERE IART.IDARTICULO=FCJD.IDSERVICIO AND IART.IDITAR=ITAR.IDITAR AND IART.IDITAR=KMCOM.PREFIJO AND
   	   KMCOM.IDAREA=FCJ.AREAPRESTACION AND KMCOM.CCOSTO=FCJ.CCOSTO AND KMCOM.IDTIPOCONT='COSTOS' AND 
   	   KMCOM.CLASECONT='P' AND KMCOM.TIPO='CR' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD)>0 AND 
           NOT KMCOM.PREFIJO IN 
   	   (SELECT PREFIJO FROM KMCOM X WHERE X.IDAREA=FCJ.AREAPRESTACION AND X.CCOSTO=FCJ.CCOSTO AND 
   	                                      X.IDTIPOCONT='COSTOS' AND X.CLASECONT='P' AND X.TIPO='DB')
     GROUP BY KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,KMCOM.IDAREA,KMCOM.CCOSTO,KMCOM.CLASECONT,
              FCJ.IDAFILIADO, FCJ.IDTERCERO,ITAR.DESCRIPCION,FCJ.CODCAJA,FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
              FCJ.CODUNG, FCJ.CODPRG
   --
     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                     ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE, @COMPANIA, KMCOM.TIPO,DBO.FNK_NC_CUENTA_KMCOM('01',KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,
                                                    KMCOM.CCOSTO,KMCOM.CLASECONT,FCJD.IDSERVICIO,0),
            CASE WHEN FCJ.IDAFILIADO IS NULL OR FCJ.IDAFILIADO='' THEN FCJ.IDTERCERO ELSE 
				CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE FCJ.IDAFILIADO END
			END, 
            KMCOM.CCOSTO, 'COSTO DE '+UPPER(IART.IDARTICULO)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
   	    (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, FCJD.CONCEPTO, NULL, @USUARIO, 
   	    DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
   	    'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
     FROM #TH FCJD, KMCOM, IART, #T FCJ
     WHERE IART.IDARTICULO=FCJD.IDSERVICIO AND IART.IDITAR=KMCOM.PREFIJO AND
   	   KMCOM.IDAREA=FCJ.AREAPRESTACION AND KMCOM.CCOSTO=FCJ.CCOSTO AND KMCOM.IDTIPOCONT='COSTOS' AND 
   	   KMCOM.CLASECONT='S' AND KMCOM.TIPO='CR' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD)>0
   
     PRINT 'Inserta Costo NO Configurado por Servicio.'
     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                      REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                      ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                      CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 'NO DEF.KMCOM',
            CASE WHEN FCJ.IDAFILIADO IS NULL OR FCJ.IDAFILIADO='' THEN FCJ.IDTERCERO ELSE 
				CASE WHEN ISNULL(@DOCIDAFILIADO,'')<>'' THEN @DOCIDAFILIADO ELSE FCJ.IDAFILIADO END
			END, 
            KMCOM.CCOSTO, 'COSTO DE '+UPPER(IART.IDARTICULO)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
   	    (FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, FCJD.CONCEPTO, NULL, @USUARIO, 
   	    DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
   	    'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
     FROM #TH FCJD, KMCOM, IART, #T FCJ
     WHERE IART.IDARTICULO=FCJD.IDSERVICIO AND IART.IDITAR=KMCOM.PREFIJO AND
   	   KMCOM.IDAREA=FCJ.AREAPRESTACION AND KMCOM.CCOSTO=FCJ.CCOSTO AND KMCOM.IDTIPOCONT='COSTOS' AND 
   	   KMCOM.CLASECONT='S' AND KMCOM.TIPO='DB' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD)>0 AND
   	   NOT KMCOM.PREFIJO IN 
   	    (SELECT PREFIJO FROM KMCOM X WHERE X.IDAREA=FCJ.AREAPRESTACION AND X.CCOSTO=FCJ.CCOSTO AND 
   	                               X.IDTIPOCONT='COSTOS' AND X.CLASECONT='S' AND X.TIPO='CR')
   
     PRINT 'Inserta Agrupado por Prefijo COSTO.'
     INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                     ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     CODUNG, CODPRG)
     SELECT @NROCOMPROBANTE, @COMPANIA, KMCOM.TIPO,DBO.FNK_NC_CUENTA_KMCOM('01',KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,
                                                    KMCOM.CCOSTO,KMCOM.CLASECONT,'',0),
            CASE WHEN FCJ.IDAFILIADO IS NULL OR FCJ.IDAFILIADO='' THEN FCJ.IDTERCERO ELSE FCJ.IDAFILIADO END, 
            KMCOM.CCOSTO, 'COSTO DE '+UPPER(ITAR.DESCRIPCION)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
   	    SUM(FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, '', NULL, @USUARIO, 
   	    DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
   	    'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
     FROM #TH FCJD, KMCOM, IART, #T FCJ, ITAR
     WHERE IART.IDARTICULO=FCJD.IDSERVICIO AND IART.IDITAR=ITAR.IDITAR AND IART.IDITAR=KMCOM.PREFIJO AND
   	   KMCOM.IDAREA=FCJ.AREAPRESTACION AND KMCOM.CCOSTO=FCJ.CCOSTO AND KMCOM.IDTIPOCONT='COSTOS' AND 
   	   KMCOM.CLASECONT='P' AND KMCOM.TIPO='CR' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD)>0
     GROUP BY KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,KMCOM.IDAREA,KMCOM.CCOSTO,KMCOM.CLASECONT,
            FCJ.IDAFILIADO, FCJ.IDTERCERO,ITAR.DESCRIPCION,FCJ.CODCAJA,FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            FCJ.CODUNG, FCJ.CODPRG
   
   PRINT 'Inserta Costo NO Configurado por Servicio.'
   INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, 
                     REFERENCIA1, REFERENCIA2, REFERENCIA3, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 
                     ESTADO, PROCESO, GENERA, PROCEDENCIA, REFERENCIA_PRO, N_FACTURA, F_FACTURAREF, F_VENCE, 
                     CODUNG, CODPRG)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 'NO DEF.KMCOM',
          CASE WHEN FCJ.IDAFILIADO IS NULL OR FCJ.IDAFILIADO='' THEN FCJ.IDTERCERO ELSE FCJ.IDAFILIADO END, 
          KMCOM.CCOSTO, 'COSTO DE '+UPPER(ITAR.DESCRIPCION)+' RECIBO No. '+LTRIM(RTRIM(FCJ.CODCAJA))+LTRIM(RTRIM(FCJ.CNSFACJ)),  
   	    SUM(FCJD.PCOSTOUNIT*FCJD.CANTIDAD) AS COSTO, FCJ.CNSFACJ, FCJ.CODCAJA, '', NULL, @USUARIO, 
   	    DBO.FNK_FECHA_SIN_MLS(GETDATE()), KMCOM.PREFIJO, KMCOM.IDAREA, KMCOM.CLASECONT, 1, 'COSTOS', 'Movimiento',
   	    'CAJA', FCJ.CNSFACJ, RTRIM(FCJ.CODCAJA)+FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
          DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
          CASE WHEN FCJ.CODUNG = '' THEN NULL ELSE FCJ.CODUNG END, CASE WHEN FCJ.CODPRG = '' THEN NULL ELSE FCJ.CODPRG END
   FROM   #TH FCJD, KMCOM, IART, #T FCJ, ITAR
   WHERE  IART.IDARTICULO=FCJD.IDSERVICIO AND IART.IDITAR=ITAR.IDITAR AND IART.IDITAR=KMCOM.PREFIJO 
   AND    KMCOM.IDAREA=FCJ.AREAPRESTACION AND KMCOM.CCOSTO=FCJ.CCOSTO AND KMCOM.IDTIPOCONT='COSTOS' 
   AND    KMCOM.CLASECONT='P' AND KMCOM.TIPO='DB' AND (FCJD.PCOSTOUNIT*FCJD.CANTIDAD)>0 
   AND    NOT KMCOM.PREFIJO IN 
   	                        (SELECT PREFIJO FROM KMCOM X 
                               WHERE  X.IDAREA = FCJ.AREAPRESTACION AND X.CCOSTO=FCJ.CCOSTO 
                               AND    X.IDTIPOCONT='COSTOS' AND X.CLASECONT='P' AND X.TIPO='CR')
   GROUP BY KMCOM.IDTIPOCONT,KMCOM.TIPO,KMCOM.PREFIJO,KMCOM.IDAREA,KMCOM.CCOSTO,KMCOM.CLASECONT,
            FCJ.IDAFILIADO, FCJ.IDTERCERO,ITAR.DESCRIPCION,FCJ.CODCAJA,FCJ.CNSFACJ, DBO.FNK_FECHA_SIN_HORA(FCJ.FECHA), 
            FCJ.CODUNG, FCJ.CODPRG
-- FIN DEL COSTO
 
   EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME
   EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''
   IF EXISTS(SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ AND COALESCE(N_FACTURAPOS,'')<>'')
   BEGIN
      DECLARE @FACTUPOS VARCHAR(20)
      SELECT @FACTUPOS=N_FACTURAPOS FROM FCJ WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ AND COALESCE(N_FACTURAPOS,'')<>''
      UPDATE FTR SET CONTABILIZADA=1,NROCOMPROBANTE=@NROCOMPROBANTE WHERE N_FACTURA=@FACTUPOS AND PROCEDENCIA='CAJA'
   END
   DROP TABLE #THD
   DROP TABLE #TH
   DROP TABLE #T
END

