USE CEM

SELECT FCOM.IDBODEGA, * FROM FCXP INNER JOIN FCOM ON FCXP.CNSFCOM=FCOM.CNSFCOM
WHERE FCXP.PROCEDENCIA='COMPRAS' AND CUECREDITO LIKE '%NO%'
AND FCXP.ESTADO='N'
AND IDBODEGA='0416'

UPDATE FCXP SET CUECREDITO='22050101'
FROM FCXP INNER JOIN FCOM ON FCXP.CNSFCOM=FCOM.CNSFCOM
WHERE FCXP.PROCEDENCIA='COMPRAS' AND CUECREDITO LIKE '%NO%'
AND FCXP.ESTADO='N'
AND IDBODEGA='0416'

UPDATE USUSU SET IDDEPURAR=1-COALESCE(IDDEPURAR,0) WHERE USUARIO='JJIMENEZ'
SELECT NROCOMPROBANTE, * FROM FTR WHERE N_FACTURA='FVCO3898'
SELECT NROCOMPROBANTE,* FROM MCP WHERE NOREFERENCIA='FVSF1'

SELECT  * FROM IMOV WHERE N_FACTURA='FVSF1'
SELECT  * FROM FCJ WHERE N_FACTURA='FVSF1'

UPDATE FTR SET NROCOMPROBANTE='0217000000012087' WHERE N_FACTURA='FVCO3898'

SELECT *
FROM MCP INNER JOIN FTR ON MCP.NOREFERENCIA=FTR.N_FACTURA
WHERE MCP.PROCEDENCIA='FACTURA'
AND MCP.NROCOMPROBANTE<>FTR.NROCOMPROBANTE
AND MCP.ESTADO=2
AND FTR.F_FACTURA>='01/07/2025'
AND FTR.PROCEDENCIA='CAJA'

UPDATE FTR SET NROCOMPROBANTE=MCP.NROCOMPROBANTE
FROM MCP INNER JOIN FTR ON MCP.NOREFERENCIA=FTR.N_FACTURA
WHERE MCP.PROCEDENCIA='FACTURA'
AND MCP.NROCOMPROBANTE<>FTR.NROCOMPROBANTE
AND MCP.ESTADO=2
AND FTR.F_FACTURA>='01/07/2025'
AND FTR.PROCEDENCIA='CAJA'


    SELECT @CNSFTR, ROW_NUMBER() OVER ( ORDER BY A.CNSMOV) , 
           A.FECHAMOV, 'DB', A.IDAREA, NULL, 
           DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, E.IDARTICULO, '', A.FECHAMOV,E.PCOSTO) * E.CANTIDAD, 
           NULL, A.CCOSTO, PREFIJO=D.PREFIJO, 
		   CASE WHEN dbo.FNK_VALORVARIABLE('CLASE_IPS') = 'OPTICA' THEN  CASE WHEN COALESCE(F.GARANTIA, 0) = 0 THEN COALESCE(C.DESCRIPCION, '')+' '+'Producto sin Garantia'
																											   ELSE COALESCE(C.DESCRIPCION, '')+' '+COALESCE(F.COMENTARIOS, '')
																											   END
																			  ELSE C.DESCRIPCION
																			  END,
		   E.IDARTICULO, IDCIRUGIA=NULL, E.CANTIDAD, 
           DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, E.IDARTICULO, '', A.FECHAMOV,E.PCOSTO), 
           DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, E.IDARTICULO, '', A.FECHAMOV,E.PCOSTO) * E.CANTIDAD, 
           VALORCOPAGO = 0, VALORPCOMP = 0, IDPROVEEDOR = NULL, NOADMISION=A.CNSMOV, NOPRESTACION = A.CNSMOV, NOITEM=NULL,
           --AREAFUNCONT = A.IDAREA, @FACT, SUBCCOSTO = NULL, C.PCOSTO, 0,0, NULL, NULL, NULL,E.IDARTICULO, A.FECHAMOV, E.NOLOTE --EZERPA 14/06/2018 Para tomar el costo del lote (IEXI) en lugar del promedio (IART), Pendiente discutir para otros proyectos
           AREAFUNCONT = A.IDAREA, @FACT, SUBCCOSTO = NULL, E.PCOSTO, 0,0, NULL, NULL, NULL,E.IDARTICULO, A.FECHAMOV, E.NOLOTE,'',''
    FROM   IMOV A INNER JOIN ISAL  E ON A.CNSMOV     = E.CNSMOV 
	              LEFT JOIN IART  C ON E.IDARTICULO = C.IDARTICULO 
                  LEFT JOIN ITAR  D ON C.IDITAR     = D.IDITAR
				  LEFT JOIN SER   F ON C.IDSERVICIO = F.IDSERVICIO
    WHERE  A.CNSMOV = @CNSMOV