--EXEC SPK_GENERA_JSON_PERU_FTR_INTEGRA  'F002-00000001'


--SELECT  * FROM HADM

SELECT PROCEDENCIA,TIPOFIN, * FROM FTR WHERE N_FACTURA='F002-00000001'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC


EXEC SPQ_JSON '{"MODELO":"FTR_COL","METODO":"ENVIA_CONTAB","PARAMETROS":{"N_FACTURA":"F002-00000001"},"USUARIO":"JJIMENEZ"}'


         SELECT ITEM=CONVERT(varchar(3),N_CUOTA),CANTIDAD=CONVERT(varchar(4),CONVERT(INT,CEILING(FTRD.CANTIDAD))),
                VALOR1=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,4),COALESCE(VALOR,0))),
                VALOR2=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,4),ROUND((VLR_SERVICI/FTRD.CANTIDAD),2))),
                VALOR3=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),ROUND(CASE WHEN COALESCE(VIVA,0)>0 THEN VLRIMPUESTO+VIVA ELSE VLR_SERVICI END,2))),
                VALOR4=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),CASE WHEN COALESCE(FTRD.VLR_COPAGOS,0)>0 THEN CASE WHEN COALESCE(PIVA,0)>0 THEN FTRD.VLR_COPAGOS/(1+(PIVA/100)) ELSE  FTRD.VLR_COPAGOS END ELSE 0 END  )),
                VALOR5=CONVERT(VARCHAR(20),CONVERT(INT,COALESCE(PIVA,0))),
                VALOR6=CASE WHEN COALESCE(VIVA,0)>0 THEN  CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),COALESCE(VIVA,0)*FTRD.CANTIDAD,0)) ELSE '0.00' END,
                --VALOR7=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),ROUND((COALESCE(VALOR,0)*COALESCE(FTRD.CANTIDAD,0))+CASE WHEN COALESCE(VIVA,0)>0 THEN VIVA ELSE 0 END -CASE WHEN COALESCE(FTRD.VLR_COPAGOS,0)>0 THEN FTRD.VLR_COPAGOS ELSE 0 END ,2))),
                VALOR7=CONVERT(VARCHAR(20),CONVERT(DECIMAL(14,2),CASE WHEN COALESCE(VIVA,0)>0 THEN VLRIMPUESTO ELSE VALOR END)),
				    ANEXO= dbo.FNK_LIMPIATEXTO(CASE WHEN 'xx'='FINANCIERO' THEN FTRD.ANEXO ELSE CASE WHEN COALESCE(SER.DESCRIPCION_CUPS,'')='' THEN SER.DESCSERVICIO ELSE SER.DESCRIPCION_CUPS END END,'0-9 A-Z'), 
                REFERENCIA=dbo.FNK_LIMPIATEXTO(COALESCE(SER.CODCUPS,FTRD.REFERENCIA),'0-9 A-Z '),
                AFECTA=CASE WHEN COALESCE(PIVA,0)>0 AND COALESCE(VIVA,0)>0 THEN 1 ELSE 0 END
         FROM FTRD LEFT JOIN SER ON FTRD.REFERENCIA=SER.IDSERVICIO
         WHERE N_FACTURA= 'F002-00000001'
         AND N_CUOTA=N_CUOTA


         SELECT  * FROM FTRD WHERE N_FACTURA= 'F002-00000001'