CREATE OR ALTER PROCEDURE DBO.SPK_FAC_VENTA_INV
	@CNSMOV   VARCHAR(20), 
	@COMPANIA VARCHAR(2), 
	@SEDE     VARCHAR(5),
	@USUARIO  VARCHAR(12),
	@PROCE	  VARCHAR(12) = null
WITH ENCRYPTION
AS       
DECLARE @CNSFTR           VARCHAR(20),    @PRE              VARCHAR(20),   @FACT             VARCHAR(16),    @VALCOPAGO        DECIMAL(14,2)
DECLARE @VALPCOMP         DECIMAL(14,2),  @VALSERV          DECIMAL(14,2), @VALEXCE          DECIMAL(14,2),  @IDTERCERO        VARCHAR(20)
DECLARE @A_INT            VARCHAR(20),    @PREFIJOFAC       VARCHAR(20),   @OBSERVACION      VARCHAR(255),   @VALABONOS        DECIMAL(14,2)
DECLARE @VALORTOTAL       DECIMAL(14,2),  @PROPIETARIO      VARCHAR(20),   @HOY              DATETIME,       @IDDEP            VARCHAR(80)
DECLARE @DATOCCOSTO       VARCHAR(80),    @TTEC             VARCHAR(10),   @CUENTACXC        VARCHAR(16),    @SYS_COMPUTERNAME VARCHAR(254)
DECLARE @IDPLAN           VARCHAR(6),     @VIVA             DECIMAL(14,2), @FACTURADA        SMALLINT,       @GENFACTURA       SMALLINT
DECLARE @VLRANTEIVA       DECIMAL(14,2),  @CNSFACT          VARCHAR(20),   @N_FACLIBERADA     VARCHAR(20),    @CNSRESOL VARCHAR(50)
DECLARE @COMENTARIOS	  VARCHAR(2048)
BEGIN
   SELECT @FACTURADA=FACTURADA, @GENFACTURA=GENFACTURA,@CNSFACT=COALESCE(NODOCUMENTO,''),@N_FACLIBERADA=COALESCE(N_FACTURA,'') FROM IMOV WHERE CNSMOV=@CNSMOV
   
   IF ISNULL(@FACTURADA,0) = 1
   BEGIN
      RAISERROR('ERROR: Este Movimiento ya se encuentra Facturado.',16,1)
      RETURN
   END
      
   IF ISNULL(@GENFACTURA,0) = 0
   BEGIN
      RAISERROR('ERROR: Este Movimiento NO esta Configurado para ser Facturado.',16,1)
      RETURN
   END

   DECLARE @IMPUESTOS_VIGENTES BIT = 1
   SELECT B.IDARTICULO, VIGENTE = CASE WHEN D.IVA='SER' THEN DBO.FNK_IMP_VIGENCIA (D.IDIMPUESTO,D.IDCLASE)
                         WHEN D.IVA='PRE' THEN IIF( E.IVA='SI',DBO.FNK_IMP_VIGENCIA (E.IDIMPUESTO,E.IDCLASE),'')
                         ELSE '' END
	INTO  #IMPUESTOS_VIGENTES
	FROM   IMOV A INNER JOIN  ISAL B ON A.CNSMOV=B.CNSMOV
				  INNER  JOIN IART C ON B.IDARTICULO = C.IDARTICULO
				  INNER JOIN  SER  D ON C.IDSERVICIO = D.IDSERVICIO
				  INNER JOIN  PRE  E ON D.PREFIJO =E.PREFIJO
	WHERE  A.CNSMOV = @CNSMOV

	IF EXISTS(SELECT TOP 1 IDARTICULO FROM #IMPUESTOS_VIGENTES WHERE VIGENTE='NO') SET @IMPUESTOS_VIGENTES = 0

	DROP TABLE #IMPUESTOS_VIGENTES

   IF @IMPUESTOS_VIGENTES = 0
   BEGIN
      RAISERROR('ERROR: Contiene artículos afectado por impuestos pero los impuestos no tienen vigencia.',16,1)
      RETURN
   END


   SELECT @IDTERCERO = IDTERCERO, @OBSERVACION = OBSERVACION, @IDPLAN=IDPLAN
   FROM   IMOV 
   WHERE  CNSMOV = @CNSMOV 

  
   IF ( SELECT COUNT(*)
          FROM   ( 
                   SELECT B.IDARTICULO, COALESCE(DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, (SELECT TOP 1 IDSERVICIO FROM SER WHERE SER.IDARTICULO = B.IDARTICULO), 
                          '', A.FECHAMOV, B.PCOSTO),0) VALOR
                   FROM   IMOV A INNER JOIN  ISAL B ON A.CNSMOV     = B.CNSMOV 
	                              LEFT  JOIN  IART C ON B.IDARTICULO = C.IDARTICULO 
                                 LEFT  JOIN  ITAR D ON C.IDITAR     = D.IDITAR
                   WHERE  A.CNSMOV = @CNSMOV
                  ) X
          WHERE VALOR <= 0.0
       ) > 0
    BEGIN
       DECLARE @DESCARTICULO VARCHAR(512)
       DECLARE @ERRORMSG VARCHAR(1000)

       SELECT @DESCARTICULO=IDARTICULO+' - '+ARTICULO
          FROM   ( 
                   SELECT B.IDARTICULO, C.DESCRIPCION AS ARTICULO, COALESCE(DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, (SELECT TOP 1 IDSERVICIO FROM SER WHERE SER.IDARTICULO = B.IDARTICULO), 
                          '', A.FECHAMOV, B.PCOSTO),0) VALOR
                   FROM   IMOV A INNER JOIN  ISAL B ON A.CNSMOV     = B.CNSMOV 
	                              LEFT  JOIN  IART C ON B.IDARTICULO = C.IDARTICULO 
                                 LEFT  JOIN  ITAR D ON C.IDITAR     = D.IDITAR
                   WHERE  A.CNSMOV = @CNSMOV
                  ) X
          WHERE VALOR <= 0.0
       --RAISERROR('ERROR: Existen Valores en Cero para la Venta.',16,1)
       SELECT @ERRORMSG='ERROR: El artículo '+ISNULL(@DESCARTICULO,'')+' no tiene precio.'
       RAISERROR(@ERRORMSG,16,1)--EZERPA 20180619
       RETURN
    END
    --RAISERROR('Se ha generado con exito una Factura para ?ste Movimiento',0,1)

      SELECT @SEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),  
      @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())   
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
      WHERE USUSU.USUARIO=@USUARIO
    -- SACAR DE DONDE SE TOMA EL CCOSTO
    
    IF  DBO.FNK_VALORVARIABLE('FACTSEDE') = 'SI'
    BEGIN      
       IF DBO.FNK_VALORVARIABLE('FACTSEDEEQUIPO') = 'SI'
       BEGIN         
          IF COALESCE(@SYS_COMPUTERNAME,'') = ''
          BEGIN
             SELECT @SYS_COMPUTERNAME = HOST_NAME()
          END
          SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_COMPUTERNAME = @SYS_COMPUTERNAME
       END
    END   
    PRINT '@SEDE='+@SEDE
    IF EXISTS(SELECT * FROM FDIAN WHERE IDENTIFICADOR=@SEDE AND PROCEDENCIA='FPOS')
    BEGIN
       SELECT @PROCE='FPOS'
    END

    SELECT @IDTERCERO = IDTERCERO, @OBSERVACION = OBSERVACION, @IDPLAN=IDPLAN
    FROM   IMOV 
    WHERE  CNSMOV = @CNSMOV 

    SELECT @VALCOPAGO = 0, @VALPCOMP  = 0,
           @VALSERV   = SUM(PVENTA*CANTIDAD), @VALEXCE   = 0, @VIVA = SUM(VLRIVA*CANTIDAD)
    FROM   IMOVH WHERE CNSMOV=@CNSMOV 
    
    SET @VALABONOS = 0
    
    SET @VALORTOTAL = @VALSERV
    SELECT @IDDEP = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'   
    
    SELECT @TTEC = TTEC.TIPO, @CUENTACXC = TTEC.CUENTA 
    FROM   IMOV INNER JOIN
           PPT  ON PPT.IDTERCERO = IMOV.IDTERCERO AND PPT.IDPLAN = IMOV.IDPLAN INNER JOIN
           TTEC ON PPT.TIPOTERCONTABLE = TTEC.TIPO
    WHERE  IMOV.CNSMOV=@CNSMOV

    IF NOT  EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACLIBERADA AND CNSFCT=@CNSFACT AND ESTADO='L')
    BEGIN
       PRINT 'AQUI LLAMO A GENCONSECUTIVO' 
       


       SET @CNSFTR = SPACE(20)
       EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@CNSFTR',  @CNSFTR OUTPUT  
       SELECT @CNSFTR = @SEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0)

       PRINT 'AQUI LLAMO A NUMFACTURA @PROCE='+@PROCE         
       SET @FACT = SPACE(20)
       EXEC SPK_GENNUMEROFACTURA @COMPANIA, @SEDE, NULL, @FACT OUTPUT   , @PROCE
 	    PRINT 'REGRESE DE NUMFACTURA'
       PRINT '@FACT='+@FACT
       --SET @PRE = SPACE(20)
       --EXEC SPK_PREFIJOFACTURA @COMPANIA, @SEDE, @PRE OUTPUT
       
      IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
      BEGIN
         IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
         BEGIN
            SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE IDENTIFICADOR=@SEDE AND VENCIDA=0 AND PROCEDENCIA = IIF(COALESCE(@PROCE,'') = '' , 'FTR', @PROCE)
         END
         ELSE
         BEGIN
            SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = IIF(COALESCE(@PROCE,'') = '' , 'FTR', @PROCE)
         END
      END        

       INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
                      VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
                      IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
                      VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
                      INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
                      IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA,
                      FECHAFAC, MIVA, PIVA, VIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC,
                      TIPOFIN, CNSFMAS, IDDEP, TIPOTTEC, CUENTACXC, IDSEDE,RDIAN, CNSRESOL,TIPO_OPERACION,TIPO_DOCUMENTO,TIPOVENTA) 
       SELECT @CNSFTR, @COMPANIA, 'C', @IDTERCERO, @FACT, DBO.FNK_FECHA_SIN_MLS(GETDATE()), DBO.FNK_FECHA_SIN_MLS(GETDATE() + 30),
              @VALORTOTAL, '01', '01', '01', NULL, 'P', NULL, @IDTERCERO, @USUARIO, @CNSMOV,
              'INVENTARIO', 'I', @OBSERVACION, NULL, @VALCOPAGO, 0, @VALPCOMP, 0, 0, 0, 0, 0,
               0, 0, 0, @VALSERV, NULL, NULL, @USUARIO, GETDATE(), 0, 0, @VIVA, 
              @VALABONOS, @IDPLAN, NULL, 'C', CNSFMAS=NULL, @IDDEP, @TTEC, @CUENTACXC, @SEDE,
              CASE COALESCE(@CNSRESOL,'') WHEN '' THEN 0 ELSE 1 END, COALESCE(@CNSRESOL,''),'10','01','Credito'
    END    
    ELSE
    BEGIN
       PRINT 'Es Factura Liberada'
       SELECT @CNSFTR=@CNSFACT,@FACT=@N_FACLIBERADA  
       UPDATE FTR SET ESTADO='P' WHERE N_fACTURA=@FACT
    END	
    -- INGRESO DE LOS DETALLES
	 PRINT '@FACT'+@FACT

    INSERT INTO FTRD( CNSFTR, N_CUOTA, 
                      FECHA, DB_CR, AREAPRESTACION, UBICACION, 
                      VR_TOTAL,
                      IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                      VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                      NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, PIVA, VIVA, 
                      IDIMPUESTO, IDCLASE, CUENTA_FIMPDV,IDARTICULO, FECHAPREST, NOLOTE) 
    SELECT @CNSFTR, ROW_NUMBER() OVER ( ORDER BY A.CNSMOV) , 
           A.FECHAMOV, 'DB', A.IDAREA, NULL, 
           DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, E.IDARTICULO, '', A.FECHAMOV,E.PCOSTO) * E.CANTIDAD, 
           NULL, A.CCOSTO, PREFIJO=D.PREFIJO, 
		   CASE WHEN dbo.FNK_VALORVARIABLE('CLASE_IPS') = 'OPTICA' THEN  CASE WHEN COALESCE(F.GARANTIA, 0) = 0 THEN COALESCE(C.DESCRIPCION, '')+' '+'Producto sin Garantia'
																											   ELSE COALESCE(C.DESCRIPCION, '')+' '+COALESCE(F.COMENTARIOS, '')
																											   END
																			  ELSE C.DESCRIPCION
																			  END,
		   E.IDARTICULO, IDCIRUGIA=NULL, E.CANTIDAD, 
           DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, E.IDARTICULO, '', A.FECHAMOV,E.PCOSTO), 
           DBO.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, E.IDARTICULO, '', A.FECHAMOV,E.PCOSTO) * E.CANTIDAD, 
           VALORCOPAGO = 0, VALORPCOMP = 0, IDPROVEEDOR = NULL, NOADMISION=A.CNSMOV, NOPRESTACION = A.CNSMOV, NOITEM=NULL,
           --AREAFUNCONT = A.IDAREA, @FACT, SUBCCOSTO = NULL, C.PCOSTO, 0,0, NULL, NULL, NULL,E.IDARTICULO, A.FECHAMOV, E.NOLOTE --EZERPA 14/06/2018 Para tomar el costo del lote (IEXI) en lugar del promedio (IART), Pendiente discutir para otros proyectos
           AREAFUNCONT = A.IDAREA, @FACT, SUBCCOSTO = NULL, E.PCOSTO, 0,0, NULL, NULL, NULL,E.IDARTICULO, A.FECHAMOV, E.NOLOTE
    FROM   IMOV A INNER JOIN ISAL  E ON A.CNSMOV     = E.CNSMOV 
	              LEFT JOIN IART  C ON E.IDARTICULO = C.IDARTICULO 
                  LEFT JOIN ITAR  D ON C.IDITAR     = D.IDITAR
				  LEFT JOIN SER   F ON C.IDSERVICIO = F.IDSERVICIO
    WHERE  A.CNSMOV = @CNSMOV
    
    UPDATE IMOV SET F_FACTURA = DBO.FNK_FECHA_SIN_MLS(GETDATE()), F_VENCE=DBO.FNK_FECHA_SIN_MLS(GETDATE() + 30), FACTURADA = 1,
                    NODOCUMENTO = @FACT,NOCONSECUTIVO=@CNSFTR,N_FACTURA=@FACT
    WHERE  CNSMOV = @CNSMOV   
     
    -- COLOCANDO EL IVA
    DECLARE @IDSERVICIOIVA VARCHAR(20)
    DECLARE @N_CUOTA       INT
    DECLARE @FECHAVENTA    DATETIME
    DECLARE @VR_VENTA      DECIMAL(14,2)
    DECLARE @VALOR         DECIMAL(14,2)
    DECLARE @IDIMPUESTO    VARCHAR(10)
    DECLARE @IDCLASE       VARCHAR(10)
    DECLARE @CUENTAIMP     VARCHAR(20)
    DECLARE PG_CURSOR CURSOR FOR 
    SELECT FTRD.N_CUOTA, FTRD.REFERENCIA,FTRD.FECHAPREST,(FTRD.VALOR*FTRD.CANTIDAD)
    FROM FTRD INNER JOIN SER ON FTRD.REFERENCIA=SER.IDARTICULO
    WHERE N_FACTURA=@FACT
    AND COALESCE(SER.IVA,'')='SER'           
    OPEN PG_CURSOR    
    FETCH NEXT FROM PG_CURSOR    
    INTO @N_CUOTA,@IDSERVICIOIVA,@FECHAVENTA,@VR_VENTA
    WHILE @@FETCH_STATUS = 0    
    BEGIN 
       SELECT @VALOR=VALOR, @IDIMPUESTO=IDIMPUESTO, @IDCLASE=IDCLASE, @CUENTAIMP=CUENTA 
       FROM DBO.FNK_PIVA_SER(@IDSERVICIOIVA,@FECHAVENTA,@VR_VENTA)

       UPDATE FTRD SET IDIMPUESTO = @IDIMPUESTO, IDCLASE=@IDCLASE,CUENTA_FIMPDV=@CUENTAIMP,PIVA=@VALOR ,VIVA =ROUND(((@VALOR/100)*@VR_VENTA),2),
              VR_TOTAL = VR_TOTAL +  ROUND(((@VALOR/100)*@VR_VENTA),0), FTRD.VLR_SERVICI = VLR_SERVICI + ROUND(((@VALOR/100)*@VR_VENTA),0)
       WHERE  CNSFTR  = @CNSFTR
       AND    N_CUOTA = @N_CUOTA
       FETCH NEXT FROM PG_CURSOR    
       INTO @N_CUOTA, @IDSERVICIOIVA, @FECHAVENTA, @VR_VENTA
    END
    CLOSE PG_CURSOR
    DEALLOCATE PG_CURSOR


  --SELECT * FROM SER WHERE IDSERVICIO='15109_'
  
    SELECT @VALCOPAGO = 0, @VALPCOMP  = 0,
           @VALSERV   = SUM(FTRD.VLR_SERVICI), @VALEXCE   = 0, @VIVA = SUM(COALESCE(FTRD.VIVA,0)), @VALORTOTAL = SUM(FTRD.VR_TOTAL)
    FROM   FTRD WHERE N_FACTURA = @FACT
    --SELECT @VALSERV = @VALSERV - @VIVA
    UPDATE FTR SET VR_TOTAL = @VALORTOTAL, VALORSERVICIOS = @VALSERV,VIVA=@VIVA WHERE N_FACTURA = @FACT

    -- REVISO IMPUESTOS ASUMIDOS -- SELECT * FROM FIMXT
    IF EXISTS(SELECT  * FROM FIMXT WHERE IDTERCERO=@IDTERCERO AND TIPO='D')
    BEGIN
       SELECT @VLRANTEIVA=@VALORTOTAL-@VIVA 
       EXEC SPK_FAC_IMPDEDUC  @IDTERCERO, @CNSFTR, @FACT, @VLRANTEIVA  
    END

        
    EXEC SPK_NC_CONTAB_FTR @FACT, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE, ''

END






