

SELECT TOP 10 *  FROM VWK_CARGOS_HADMAUTCIT WHERE PROCEDENCIA='CIT' AND VALORCOPAGO>0 AND ENCAJA=0

SELECT  * FROM FTR WHERE N_FACTURA='ASFE68024'
SELECT  * FROM FTRDC WHERE CNSFTR='0200569271' AND VLR_COPAGO>0


SELECT  * FROM FTRDC INNER JOIN VWK_CARGOS_HADMAUTCIT B ON FTRDC.NOADMISION=B.NOADMISION  
                                 AND FTRDC.PROCEDENCIA=B.PROCEDENCIA 
                               
WHERE CNSFTR='0200569271' 
AND B.VALORCOPAGO>0
AND B.N_FACTURA='ASFE68024'


SELECT TOP 1 IMOV.CNSMOV, CONVERT(DECIMAL(14,2),PCOSTO)
FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
WHERE IMOV.IDTIPOMOV=DBO.FNK_VALORVARIABLE('IDINVMOV_COMPRAS')
AND IMOV.ESTADO=1
AND IMOVH.IDARTICULO='MED0006 LAFRANCOL'
ORDER BY IMOV.FECHACONF DESC

SELECT  * FROM IART WHERE IDARTICULO='MED006%'
SELECT  * FROM IMOVH WHERE IDARTICULO='ACT-AD 0024'

SELECT  * FROM IMOV WHERE CNSMOV='0201630496'
SELECT  * FROM IMOVH WHERE CNSMOV='0201630496'

SELECT * FROM IMOV WHERE CNSMOV='0201794686'

