IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_FACTURACE_N' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_FACTURACE_N
END

GO
CREATE  PROCEDURE DBO.SPK_FACTURACE_N
@NOAUT        VARCHAR(16),
@NIT          VARCHAR(20),
@COMPANIA     VARCHAR(2),
@IDSEDE       VARCHAR(5),
@USUARIO      VARCHAR(12),
@PRE1         VARCHAR(6),
@PRE2         VARCHAR(6),
@PRE3         VARCHAR(6),
@PRE4         VARCHAR(6),
@PRE5         VARCHAR(6),
@PROC         VARCHAR(2),
@IDTERCEROCA1 VARCHAR(20),
@CETIPOHOSP   VARCHAR(6) = FALSE,  -- PARAM. Que Especifica el tipo de manejo de Planes - Contratos 
@IDPLANPAR    VARCHAR(6) = NULL,    -- EL PLAN EN CEHOSP
@FECHAFAC     DATETIME   = NULL
WITH ENCRYPTION
AS 
DECLARE @IDAUT       VARCHAR(13), @PRE VARCHAR(20), @CONSECFTR INT, @CNSRESOL VARCHAR(50)
DECLARE @NVOCONSEC   VARCHAR(20)
DECLARE @CNSFTR      VARCHAR(20)
DECLARE @CERRADA     SMALLINT
DECLARE @FACTURADA   SMALLINT
DECLARE @FACTURABLE  SMALLINT
DECLARE @TIPOADM     VARCHAR(2)
DECLARE @IDTERCERO   VARCHAR(20)
DECLARE @IDPLAN      VARCHAR(6)
DECLARE @MONEDA      VARCHAR(20)
DECLARE @DATO1       VARCHAR(80)
DECLARE @IDTERCERO1  VARCHAR(20)  
DECLARE @OK          INT
DECLARE @CA          VARCHAR(15)
DECLARE @IDAFILIADO  VARCHAR(20)
DECLARE @IDAFILIADOTER VARCHAR(20)
DECLARE @DV          SMALLINT
DECLARE @TV          VARCHAR(10)
DECLARE @CCOSTO      VARCHAR(20)
DECLARE @IDAREA      VARCHAR(20)
DECLARE @EC          SMALLINT
DECLARE @IDTERCEROF  VARCHAR(20)
DECLARE @IDTERPART   VARCHAR(20)
DECLARE @DESCUENTO   DECIMAL(14,2)
DECLARE @TIPODTO     VARCHAR(1)
DECLARE @VRTOTAL     DECIMAL(14,2)
DECLARE @VRSERV      DECIMAL(14,2)
DECLARE @VRCOPA      DECIMAL(14,2)
DECLARE @VRPACO      DECIMAL(14,2)
DECLARE @VRDTO       DECIMAL(14,2)
DECLARE @VRABONO     DECIMAL(14,2)
DECLARE @VEZ         INT
DECLARE @DATO3             VARCHAR(20)
DECLARE @TTEC              VARCHAR(10)
DECLARE @TIPOFACTURACION   VARCHAR(1)
DECLARE @NODESCUENTACOPAGO SMALLINT
DECLARE @CUENTACXC         VARCHAR(16)
DECLARE @DATOCCOSTO        VARCHAR(80)
DECLARE @SOAT              SMALLINT
DECLARE @CNSHACTRAN        VARCHAR(20)
DECLARE @IDTERCEROCA       VARCHAR(20)
DECLARE @SANDER            DECIMAL (14,2) 
DECLARE @SYS_COMPUTERNAME  VARCHAR(254)
DECLARE @CODUNG VARCHAR(2)
DECLARE @CODPRG VARCHAR(2)
DECLARE @CUENTACXC_RAD     VARCHAR(16)
DECLARE @LIBERADA          SMALLINT
DECLARE @VENCIDA           SMALLINT
DECLARE @IDAFIAUX          VARCHAR(20)
DECLARE @IDCATEGORIA       VARCHAR(10)--CAT
DECLARE @IDFORMATOFTR      VARCHAR(20)
DECLARE @MIVA              SMALLINT
DECLARE @PIVA              DECIMAL(14,2)
DECLARE @VIVA              DECIMAL(14,2)
DECLARE @N_FACTURAORI      VARCHAR(20)
DECLARE @VLRAUTDTOTAL      DECIMAL(14,2)
DECLARE @VARIOS            INT
DECLARE @BASE_IVA_SER      VARCHAR(20)
DECLARE @LIBERTER		   VARCHAR(20)
DECLARE @ESOPTICA		   VARCHAR(2)
DECLARE @OBSERVACION	   VARCHAR(2040)
DECLARE @MONTO             DECIMAL(14,2)
BEGIN
	SELECT  @SYS_COMPUTERNAME = HOST_NAME(),@LIBERADA=0
	-- SACAR DE DONDE SE TOMA EL CCOSTO
	IF @EC IS NULL
			SELECT @EC = 0
         
	SELECT @DATOCCOSTO = DATO FROM USVGS WHERE IDVARIABLE = 'CCOSTOENPRESTACION'
	SELECT @MONEDA = DATO FROM USVGS WHERE IDVARIABLE = 'IDMONEDABASE'
	SELECT @BASE_IVA_SER = DATO FROM USVGS WHERE IDVARIABLE='BASE_IVA_SERVICIOS'
	SELECT @LIBERTER=DATO FROM USVGS WHERE IDVARIABLE='LIBERTER'
	SELECT @ESOPTICA=DATO FROM USVGS WHERE IDVARIABLE='IPS_MAN_OPTICA'
	PRINT 'INGRESE' 

	SELECT @VARIOS=COUNT(*)
	FROM(
		SELECT DISTINCT AUTD.IDTERCEROCA  FROM AUTD INNER JOIN AUT ON AUTD.IDAUT=AUT.IDAUT WHERE AUT.NOAUT=@NOAUT 
	)X
     
	PRINT '@VARIOS ='+STR(@VARIOS)

	IF @PROC = 'CE'
	BEGIN
		IF(SELECT COALESCE(IDTERCEROCA,'') FROM  AUT WHERE NOAUT=@NOAUT)=''
		BEGIN 
		PRINT 'ACTUALIZO AUT.IDTERCEROCA'
			UPDATE AUT SET IDTERCEROCA=IDCONTRATANTE WHERE  NOAUT=@NOAUT
			UPDATE AUTD SET AUTD.IDTERCEROCA=AUT.IDTERCEROCA 
			FROM AUT INNER JOIN AUTD ON AUTD.IDAUT=AUT.IDAUT WHERE AUT.NOAUT=@NOAUT
		END

		SELECT @IDAUT  = IDAUT,@CODUNG=CODUNG, @CODPRG =CODPRG FROM AUT WHERE NOAUT = @NOAUT

		IF @CETIPOHOSP = 'CEHOSP'
		BEGIN
			SELECT  @FACTURABLE = FACTURABLE,
					@IDAFILIADO = AUT.IDAFILIADO, @DESCUENTO = DESCUENTO, @TIPODTO = TIPODTO, 
					@CCOSTO=CCOSTO,@N_FACTURAORI=AUT.N_fACTURA,
					@CA = AUT.IMPUTABLE_A, @SOAT = SOAT,
					@CNSHACTRAN = CNSHACTRAN
			FROM AUT INNER JOIN AFI ON AUT.IDAFILIADO=AFI.IDAFILIADO WHERE NOAUT = @NOAUT                
            
			SELECT DISTINCT @IDTERCERO = AUTD.IDTERCEROCA, @IDTERCERO1 = AUTD.IDTERCEROCA, @IDTERCEROF = AUTD.IDTERCEROCA
			FROM   AUTD, AUT
			WHERE  AUTD.IDAUT  = AUT.IDAUT
			AND    AUT.NOAUT   = @NOAUT
			AND    AUTD.IDPLAN = @IDPLANPAR
         
			SELECT @IDPLAN    = @IDPLANPAR
			SELECT @FACTURADA = 0
		END
		ELSE
		BEGIN
			SELECT  @FACTURADA = FACTURADA,  @FACTURABLE = FACTURABLE,
					@IDTERCERO = IDCONTRATANTE,  @IDPLAN = IDPLAN,
					@IDAFILIADO = IDAFILIADO, @DESCUENTO = DESCUENTO, @TIPODTO = TIPODTO, 
					@CCOSTO=CCOSTO, 
					@IDTERCERO1 = AUT.IDCONTRATANTE, @CA = AUT.IMPUTABLE_A, @SOAT = SOAT,
					@CNSHACTRAN = CNSHACTRAN
			FROM AUT WHERE NOAUT = @NOAUT        
		END
	END   
	ELSE
	BEGIN
		PRINT 'CITAS'
		PRINT '@NOAUT ='+@NOAUT

		IF COALESCE(@LIBERTER,'')<>'SI'
		BEGIN 
				IF EXISTS(SELECT * FROM FTR WHERE NOREFERENCIA=@NOAUT AND PROCEDENCIA='CI' AND ESTADO='L')
				BEGIN
					PRINT 'SI TENGO LIBREACION'
					SELECT @LIBERADA=1,@NVOCONSEC=N_FACTURA , @CNSFTR=CNSFCT FROM FTR WHERE NOREFERENCIA=@NOAUT AND PROCEDENCIA='CI' AND ESTADO='L'
				END
				SELECT  @FACTURADA = FACTURADA,  @FACTURABLE = FACTURABLE,
						@IDTERCERO = IDTERCEROCA,  @IDPLAN = CIT.IDPLAN,
						@IDAFILIADO = CIT.IDAFILIADO, @DESCUENTO = DESCUENTO, @TIPODTO = TIPODTO, 
						@CCOSTO=CCOSTO, @IDTERCERO1 =IDTERCEROCA, @SOAT = SOAT,
						@CNSHACTRAN = CNSHACTRAN 
				FROM    CIT INNER JOIN AFI ON AFI.IDAFILIADO=CIT.IDAFILIADO WHERE CONSECUTIVO = @NOAUT 
				print 'terceroca' + @IDTERCERO 
				PRINT   'facturada='+STR(@FACTURADA)+' - '+@NOAUT
		END 
		ELSE 
		BEGIN
				IF EXISTS(SELECT * FROM FTR WHERE IDTERCERO=@IDTERCEROCA1 AND ESTADO='L')
				BEGIN
	   				PRINT 'SI TENGO LIBREACION POR TERCERO'
				
					SELECT TOP 1  @LIBERADA=1,@NVOCONSEC=N_FACTURA , @CNSFTR=CNSFCT FROM FTR WHERE IDTERCERO=@IDTERCEROCA1 
					AND ESTADO='L'
				END 
				IF @PROC='CI'
				BEGIN
				SELECT  @FACTURADA = FACTURADA,  @FACTURABLE = FACTURABLE,
						@IDTERCERO = IDTERCEROCA,  @IDPLAN = CIT.IDPLAN,
						@IDAFILIADO = CIT.IDAFILIADO, @DESCUENTO = DESCUENTO, @TIPODTO = TIPODTO, 
						@CCOSTO=CCOSTO, @IDTERCERO1 =IDTERCEROCA, @SOAT = SOAT,
						@CNSHACTRAN = CNSHACTRAN 
				FROM    CIT INNER JOIN AFI ON AFI.IDAFILIADO=CIT.IDAFILIADO WHERE CONSECUTIVO = @NOAUT 
					print 'terceroca' + @IDTERCERO 
					PRINT   'facturada='+STR(@FACTURADA)+' - '+@NOAUT
				END 


		END 
	END

	SELECT @DATO3 = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'     
	IF @FACTURADA = 1
	BEGIN
		PRINT 'ME DEVUELVO POR QUE YA ESTA FACTURADA'
		RETURN 
	END 
	PRINT 'No esta Facturada'
	IF @FACTURABLE = 0
	BEGIN
		PRINT 'ME DEVUELVO NO ES FACTURABLE'
		RETURN
	END

   IF @PROC = 'CI'  --JEDM 20240209   COLOCO ESTE IF PQ ESTABA HACIEN UPDATE A CIT A SI NO VINIERA CON PROCEDENCIA CIT
	   UPDATE CIT SET CANTIDADC=1 WHERE CONSECUTIVO=@NOAUT AND COALESCE(CANTIDADC,0)=0     
   
	CREATE TABLE #FTRD1(CNSFTR VARCHAR(40), N_CUOTA	int IDENTITY, FECHA datetime,
				DB_CR varchar(2), AREAPRESTACION varchar(20), UBICACION varchar(16),
				VR_TOTAL float, IMPUTACION varchar(16), CCOSTO varchar (20),
				PREFIJO varchar(6), ANEXO varchar(1024), REFERENCIA varchar(40), 
				IDCIRUGIA varchar(20), CANTIDAD smallint, VALOR decimal(14,2),
				VLR_SERVICI decimal(14,2), VLR_COPAGOS decimal(14,2),
				VLR_PAGCOMP decimal(14,2), IDPROVEEDOR varchar(20),
				NOADMISION varchar(16), NOPRESTACION	varchar(16), NOITEM int,	
				AREAFUNCONT varchar(20), N_FACTURA varchar(16),
				SUBCCOSTO varchar(4), PCOSTO	decimal(14,2), FECHAPREST datetime, IDPLAN VARCHAR(6),
				IDIMPUESTO VARCHAR(10),
				IDCLASE    VARCHAR(10),
				ITEM       SMALLINT,
				VLRIMPUESTO DECIMAL(14,2),
				PIVA        DECIMAL(14,2),
				VIVA        DECIMAL(14,2),
				CUENTA_FIMPDV VARCHAR(20)
				) --FTRD
   
	IF @PROC = 'CE'
	BEGIN           
		IF @CETIPOHOSP = 'CEHOSP' 
		BEGIN
			DECLARE CUR_FTR CURSOR FOR
			SELECT @IDTERCEROF, @IDPLAN,@N_FACTURAORI 
		END  
		ELSE 
		BEGIN
			IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART') OR
			@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART2') OR
			@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART3') OR
			@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART4') OR
			@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART5')
			BEGIN
				DECLARE CUR_FTR CURSOR FOR
				SELECT DISTINCT  AUTD.IDTERCEROCA, AUTD.IDPLAN,COALESCE(AUTD.N_FACTURA,'') FROM AUTD INNER JOIN AUT ON AUT.IDAUT=AUTD.IDAUT WHERE AUT.NOAUT = @NOAUT
			END
			ELSE
			BEGIN
				print 'ingrese por el tercero'
				DECLARE CUR_FTR CURSOR FOR
				SELECT DISTINCT (CASE WHEN TER.IDTERCERO IS NULL THEN @IDTERCEROF ELSE AUTD.IDTERCEROCA END), AUTD.IDPLAN,AUTD.N_fACTURA
				FROM AUT INNER JOIN AUTD ON AUTD.IDAUT       = AUT.IDAUT 
							LEFT JOIN  TER ON AUTD.IDTERCEROCA = TER.IDTERCERO
				WHERE AUT.NOAUT = @NOAUT AND (AUT.FACTURADA = 0 OR AUT.FACTURADA IS NULL OR AUT.FACTURADA=2) 
						AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL) 
						AND (COALESCE(TER.IDTERCERO,'') = CASE WHEN COALESCE(@IDTERCEROCA1,'')='' THEN COALESCE(TER.IDTERCERO,'')  ELSE @IDTERCEROCA1 END OR
						(TER.IDTERCERO IS NULL AND @IDTERCEROF = @IDTERCEROCA1 AND @IDTERCEROCA1<>'') OR
						(TER.IDTERCERO IS NULL AND @IDTERCEROCA1=''))
			END
		END
	END
	ELSE
		IF @PROC = 'CI'
		BEGIN
			DECLARE CUR_FTR CURSOR FOR
			SELECT CASE WHEN TER.IDTERCERO IS NULL THEN @IDTERCEROF ELSE CIT.IDTERCEROCA END,CIT.IDPLAN,N_FACTURA
			FROM   CIT LEFT JOIN 
					TER ON CIT.IDTERCEROCA=TER.IDTERCERO
			WHERE  CIT.CONSECUTIVO = @NOAUT AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND 
					(TER.IDTERCERO = (CASE WHEN @IDTERCEROCA1='' THEN TER.IDTERCERO ELSE @IDTERCEROCA1 END) OR
					(TER.IDTERCERO IS NULL AND @IDTERCEROF=@IDTERCEROCA1 AND @IDTERCEROCA1<>'') OR
					(TER.IDTERCERO IS NULL AND @IDTERCEROCA1=''))
		END
   
	OPEN CUR_FTR
   
	FETCH NEXT FROM CUR_FTR
	INTO @IDTERCEROCA,@IDPLAN,@N_FACTURAORI
	PRINT 'INICIO EL CURSOR @IDTERCEROCA='+@IDTERCEROCA
	WHILE @@FETCH_STATUS = 0  
	BEGIN  

		PRINT 'INGRESE EL CURSOR PARA FACTURAR.................'
		PRINT '@IDTERCEROCA='+COALESCE(@IDTERCEROCA,'NO TENGO TERCERO')
		PRINT '@IDPLAN='+@IDPLAN

		TRUNCATE TABLE  #FTRD1 

		PRINT @NOAUT + ' ' +CASE WHEN @IDTERCEROCA IS NULL THEN '?' ELSE @IDTERCEROCA END
		PRINT @PROC
		PRINT @NODESCUENTACOPAGO
		PRINT @DATOCCOSTO


		IF @PROC = 'CE'
		BEGIN   
			PRINT 'ES DE CE'
			IF @CETIPOHOSP = 'CEHOSP' 
			BEGIN
				PRINT '@CETIPOHOSP ='+@CETIPOHOSP
				SELECT @VLRAUTDTOTAL=SUM(AUTD.CANTIDAD * AUTD.VALOR),@DESCUENTO = CASE WHEN @ESOPTICA = 'SI' OR COALESCE(@VARIOS,0)>1 THEN  SUM(COALESCE(AUTD.DESCUENTO,0)) ELSE @DESCUENTO END, -- STORRES SE QUITA SUMA GENERAL Y SOLO SE COLOCA EN EL THEN
				@TIPODTO=CASE WHEN @ESOPTICA = 'SI' OR COALESCE(@VARIOS,0)>1 THEN AUTD.TIPODTO  ELSE @TIPODTO END
				FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT = AUT.IDAUT 
							INNER JOIN SER ON SER.IDSERVICIO = AUTD.IDSERVICIO 
							LEFT JOIN  TER ON TER.IDTERCERO = AUTD.IDTERCEROCA
				WHERE  AUT.NOAUT = @NOAUT
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE1,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE2,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE3,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE4,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE5,'')                  
					AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL OR AUTD.FACTURADA=2)
					--AND (TER.IDTERCERO = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCEROF=@IDTERCEROCA)) 
					AND AUTD.IDTERCEROCA=@IDTERCEROCA
					AND AUTD.IDPLAN = @IDPLAN
					GROUP BY CASE WHEN @ESOPTICA = 'SI' OR COALESCE(@VARIOS,0)>1 THEN AUTD.TIPODTO  ELSE @TIPODTO END

				INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, IDPLAN,IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
				SELECT @CNSFTR, GETDATE(), 'DB', AUT.IDAREA, NULL, 
						(AUTD.CANTIDAD * AUTD.VALOR) - IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0) - CASE WHEN @NODESCUENTACOPAGO = 1 THEN 0 ELSE ROUND(((AUTD.CANTIDAD * AUTD.VALOR) * COALESCE(AUT.VALORCOPAGO,0)) / @VLRAUTDTOTAL,0) END, 
						NULL, CASE WHEN @DATOCCOSTO = 'SER:CCOSTO' THEN AUTD.CCOSTO ELSE AUT.CCOSTO END, SER.PREFIJO,
						CASE WHEN dbo.FNK_VALORVARIABLE('MANEJA_GARANTIA_SER') = 'SI' THEN 
							CASE WHEN dbo.FNK_VALORVARIABLE('CLASE_IPS') = 'OPTICA' THEN  CASE WHEN COALESCE(SER.GARANTIA, 0) = 0 THEN COALESCE(SER.DESCSERVICIO, '')+' '+'Producto sin Garantia'
																																ELSE COALESCE(SER.DESCSERVICIO, '')+' '+COALESCE(SER.COMENTARIOS, '')
																																END
																				
																						ELSE SER.DESCSERVICIO
																						END
																					ELSE SER.DESCSERVICIO
																					END, 
						AUTD.IDSERVICIO, NULL, AUTD.CANTIDAD, AUTD.VALOR-CASE WHEN @ESOPTICA='SI' AND COALESCE(AUTD.DESCUENTO,0)>0 THEN COALESCE(AUTD.DESCUENTO,0)/AUTD.CANTIDAD ELSE 0 END, 
						--(AUTD.CANTIDAD * CASE WHEN @ESOPTICA='SI' THEN AUTD.VALOR-CASE WHEN COALESCE(DESCUENTO,0)>0 THEN COALESCE(DESCUENTO,0)/AUTD.CANTIDAD ELSE 0 END ELSE AUTD.VALOR END), 
						(AUTD.CANTIDAD * AUTD.VALOR) - IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0),
						CASE WHEN @NODESCUENTACOPAGO = 1 THEN 0 ELSE 
																CASE WHEN ISNULL(DBO.FNK_VALORVARIABLE('CECOPAGOREDONDEO'),'REDONDEO') = 'REDONDEO' 
																	THEN ROUND(((AUTD.CANTIDAD * AUTD.VALOR) * COALESCE(AUT.VALORCOPAGO,0)) /  @VLRAUTDTOTAL,0)
																	ELSE ((AUTD.CANTIDAD * AUTD.VALOR) * COALESCE(AUT.VALORCOPAGO,0)) / @VLRAUTDTOTAL
																END
						END,  
						0, AUT.IDPROVEEDOR, @NOAUT,AUTD.IDAUT, AUTD.NO_ITEM, NULL, 
						@NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO,AUT.FECHA, AUT.IDPLAN,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.CANTIDAD * AUTD.VALOR) - IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0) ELSE NULL END ,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0))) ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  CASE WHEN @BASE_IVA_SER='CONIVA' 
																		THEN  (SELECT (AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0)-ROUND(((AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0))/((VALOR+100)/100),0) 
																		FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0)))
																	ELSE
																	(SELECT ROUND((AUTD.CANTIDAD * AUTD.VALOR)*(VALOR/100),0) 
																	FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) END ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0))) ELSE NULL END
				FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT = AUT.IDAUT 
							INNER JOIN SER ON SER.IDSERVICIO = AUTD.IDSERVICIO 
							LEFT JOIN  TER ON TER.IDTERCERO = AUTD.IDTERCEROCA
				WHERE  AUT.NOAUT = @NOAUT
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE1,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE2,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE3,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE4,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE5,'')                  
					AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL OR AUTD.FACTURADA=2)
					--AND (TER.IDTERCERO = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCEROF=@IDTERCEROCA)) 
					AND AUTD.IDTERCEROCA=@IDTERCEROCA
					AND AUTD.IDPLAN = @IDPLAN

					

			END
			ELSE
			BEGIN
				PRINT '@EC Y NO ES CEHOSP'+STR(@EC)
				IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART') OR 
					@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART2') OR 
					@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART3') OR 
					@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART4') OR 
					@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART5') OR 
					@EC = 1
				BEGIN
					PRINT 'PARTICULAR'

					SELECT  @DESCUENTO =  CASE WHEN @ESOPTICA = 'SI' OR COALESCE(@VARIOS,0)>1 THEN  SUM(COALESCE(AUTD.DESCUENTO,0)) ELSE @DESCUENTO END, -- STORRES SE QUITA SUMA GENERAL Y SOLO SE COLOCA EN EL THEN
							@TIPODTO=CASE WHEN @ESOPTICA = 'SI' OR  COALESCE(@VARIOS,0)>1 THEN AUTD.TIPODTO  ELSE @TIPODTO END
					FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT     = AUT.IDAUT 
								INNER JOIN SER  ON SER.IDSERVICIO = AUTD.IDSERVICIO 
								LEFT  JOIN TER  ON TER.IDTERCERO  = AUTD.IDTERCEROCA
					WHERE  AUT.NOAUT = @NOAUT
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE1,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE2,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE3,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE4,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE5,'')                 
						AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL OR AUTD.FACTURADA=2)
						AND AUTD.IDTERCEROCA=@IDTERCEROCA
						AND AUTD.IDPLAN=@IDPLAN
					GROUP BY  CASE WHEN @ESOPTICA = 'SI' OR COALESCE(@VARIOS,0)>1 THEN AUTD.TIPODTO  ELSE @TIPODTO END
					PRINT '@IDAFILIADO ANTES DEL INSERT=  :::::::::'+ @IDAFILIADO 

					print 'OMAR'
					INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
							IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
							VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
							NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, IDPLAN,IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
					SELECT @CNSFTR, GETDATE(), 'DB', AUT.IDAREA, NULL, 
							(AUTD.CANTIDAD * AUTD.VALOR) - IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0), 
							NULL, CASE WHEN @DATOCCOSTO = 'SER:CCOSTO' THEN AUTD.CCOSTO ELSE AUT.CCOSTO END, SER.PREFIJO,
							CASE WHEN dbo.FNK_VALORVARIABLE('MANEJA_GARANTIA_SER') = 'SI' THEN
								CASE WHEN dbo.FNK_VALORVARIABLE('CLASE_IPS') = 'OPTICA' THEN  CASE WHEN COALESCE(SER.GARANTIA, 0) = 0 THEN COALESCE(SER.DESCSERVICIO, '')+' '+'Producto sin Garantia'
																																ELSE COALESCE(SER.DESCSERVICIO, '')+' '+COALESCE(SER.COMENTARIOS, '')
																																END
																						ELSE SER.DESCSERVICIO
																						END
																					ELSE SER.DESCSERVICIO
																					END,
							AUTD.IDSERVICIO, NULL, AUTD.CANTIDAD, AUTD.VALOR-CASE WHEN @ESOPTICA='SI' AND COALESCE(AUTD.DESCUENTO,0)>0 THEN COALESCE(AUTD.DESCUENTO,0)/AUTD.CANTIDAD ELSE 0 END, 
							--(AUTD.CANTIDAD * CASE WHEN @ESOPTICA='SI' THEN AUTD.VALOR-CASE WHEN COALESCE(DESCUENTO,0)>0 THEN COALESCE(DESCUENTO,0)/AUTD.CANTIDAD ELSE 0 END ELSE AUTD.VALOR END), 
							(AUTD.CANTIDAD * AUTD.VALOR) - IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0),  
							0, --AUTD.VALORCOPAGO,
							0, AUT.IDPROVEEDOR, @NOAUT, AUTD.IDAUT, AUTD.NO_ITEM, NULL, 
							@NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO, AUT.FECHA, AUT.IDPLAN,
							CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END,
							CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
							CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) ELSE NULL END,
							CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.CANTIDAD * AUTD.VALOR) - IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0) ELSE NULL END ,
							CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0))) ELSE NULL END,
							CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  CASE WHEN @BASE_IVA_SER='CONIVA' 
																			THEN  (SELECT (AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0)-ROUND(((AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0))/((VALOR+100)/100),0) 
																			FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0)))
																		ELSE
																		(SELECT ROUND((AUTD.CANTIDAD * AUTD.VALOR)*(VALOR/100),0) 
																		FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) END ELSE NULL END,
							CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)- IIF(@ESOPTICA='SI',COALESCE(AUTD.DESCUENTO,0),0))) ELSE NULL END
					FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT     = AUT.IDAUT 
								INNER JOIN SER  ON SER.IDSERVICIO = AUTD.IDSERVICIO 
								LEFT  JOIN TER  ON TER.IDTERCERO  = AUTD.IDTERCEROCA
					WHERE  AUT.NOAUT = @NOAUT
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE1,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE2,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE3,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE4,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE5,'')                 
						AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL OR AUTD.FACTURADA=2)
						AND AUTD.IDTERCEROCA=@IDTERCEROCA
						AND AUTD.IDPLAN=@IDPLAN

				END	
				ELSE
				BEGIN
					PRINT 'NO PART'
					SELECT @VLRAUTDTOTAL=SUM(AUTD.CANTIDAD * AUTD.VALOR),@DESCUENTO = CASE WHEN COALESCE(@VARIOS,0)>1 THEN  SUM(COALESCE(AUTD.DESCUENTO,0)) ELSE @DESCUENTO END, -- STORRES SE QUITA SUMA GENERAL Y SOLO SE COLOCA EN EL THEN
						@TIPODTO=CASE WHEN COALESCE(@VARIOS,0)>1 THEN AUTD.TIPODTO  ELSE @TIPODTO END
					FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT     = AUT.IDAUT 
								INNER JOIN SER  ON SER.IDSERVICIO = AUTD.IDSERVICIO 
								LEFT JOIN TER  ON TER.IDTERCERO  = AUTD.IDTERCEROCA
					WHERE  AUT.NOAUT = @NOAUT
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE1,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE2,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE3,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE4,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE5,'')                
						AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL OR AUTD.FACTURADA=2)
						-- AND (TER.IDTERCERO = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCEROF=@IDTERCEROCA)) 
						AND AUTD.IDTERCEROCA=@IDTERCEROCA
						AND AUTD.IDPLAN=@IDPLAN
						GROUP BY AUTD.TIPODTO

					INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
							IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
							VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
							NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, IDPLAN,IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
					SELECT @CNSFTR, GETDATE(), 'DB', AUT.IDAREA, NULL, 
							(AUTD.CANTIDAD * AUTD.VALOR) - CASE WHEN @NODESCUENTACOPAGO = 1 THEN 0 ELSE ROUND(((AUTD.CANTIDAD * AUTD.VALOR) * COALESCE(AUT.VALORCOPAGO,0)) / @VLRAUTDTOTAL,0) END, 
							NULL, CASE WHEN @DATOCCOSTO = 'SER:CCOSTO' THEN AUTD.CCOSTO ELSE AUT.CCOSTO END, SER.PREFIJO,
							CASE WHEN dbo.FNK_VALORVARIABLE('MANEJA_GARANTIA_SER') = 'SI' THEN 
								CASE WHEN dbo.FNK_VALORVARIABLE('CLASE_IPS') = 'OPTICA' THEN  CASE WHEN COALESCE(SER.GARANTIA, 0) = 0 THEN COALESCE(SER.DESCSERVICIO, '')+' '+'Producto sin Garantia'
																																	ELSE COALESCE(SER.DESCSERVICIO, '')+' '+COALESCE(SER.COMENTARIOS, '')
																																	END
																							ELSE SER.DESCSERVICIO
																							END
																					ELSE SER.DESCSERVICIO
																					END,
							AUTD.IDSERVICIO, NULL, AUTD.CANTIDAD, AUTD.VALOR, (AUTD.CANTIDAD * AUTD.VALOR), 
							CASE WHEN @NODESCUENTACOPAGO = 1 THEN 0 ELSE ROUND(((AUTD.CANTIDAD * AUTD.VALOR) * COALESCE(AUT.VALORCOPAGO,0)) /  @VLRAUTDTOTAL,1) END, --AUTD.VALORCOPAGO,
							0, AUT.IDPROVEEDOR, @NOAUT, AUTD.IDAUT, AUTD.NO_ITEM, NULL, 
							@NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO,AUT.FECHA, AUT.IDPLAN,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.CANTIDAD * AUTD.VALOR) ELSE NULL END ,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  CASE WHEN @BASE_IVA_SER='CONIVA' 
																		THEN  (SELECT (AUTD.CANTIDAD * AUTD.VALOR) -ROUND((AUTD.CANTIDAD * AUTD.VALOR)/((VALOR+100)/100),0) 
																		FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)))
																	ELSE
																	(SELECT ROUND((AUTD.CANTIDAD * AUTD.VALOR)*(VALOR/100),0) 
																	FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR))) END ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(AUTD.CANTIDAD * AUTD.VALOR)))  ELSE NULL END
					FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT     = AUT.IDAUT 
								INNER JOIN SER  ON SER.IDSERVICIO = AUTD.IDSERVICIO 
								LEFT JOIN TER  ON TER.IDTERCERO  = AUTD.IDTERCEROCA
					WHERE  AUT.NOAUT = @NOAUT
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE1,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE2,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE3,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE4,'')
						AND COALESCE(SER.PREFIJO,'')       <>COALESCE( @PRE5,'')                
						AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL OR AUTD.FACTURADA=2)
						-- AND (TER.IDTERCERO = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCEROF=@IDTERCEROCA)) 
						AND AUTD.IDTERCEROCA=@IDTERCEROCA
						AND AUTD.IDPLAN=@IDPLAN
				END
			END
		END
		ELSE
		BEGIN
			PRINT 'ES DE CITAS'
			INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
					IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
					VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
					NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, IDPLAN,IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
			SELECT @CNSFTR, GETDATE(), 'DB', CIT.IDAREA, NULL, 
				CASE WHEN @IDTERCEROCA = 'PARTN' THEN COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL ELSE -- ADD: JREYES 20090810 CORREC:209
					CASE WHEN @NODESCUENTACOPAGO = 1 THEN COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL ELSE (COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL) - COALESCE(CIT.VALORCOPAGO,0) END END, 
				NULL, CIT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, CIT.IDSERVICIO, NULL,
				COALESCE(CIT.CANTIDADC,1) CANTIDAD, CIT.VALORTOTAL, COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL, CASE WHEN @NODESCUENTACOPAGO = 1 THEN 0 ELSE COALESCE(CIT.VALORCOPAGO,0) END,
				0, CIT.IDMEDICO, @NOAUT, @NOAUT, 1, NULL, 
				@NVOCONSEC, CIT.SUBCCOSTO, CIT.VALORTOTALCOS, CIT.FECHA, CIT.IDPLAN,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL))) ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL) ELSE NULL END ,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL))) ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  CASE WHEN @BASE_IVA_SER='CONIVA' 
																		THEN  (SELECT (COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL) -ROUND((COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL)/((VALOR+100)/100),0) 
																		FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL)))
																	ELSE
																	(SELECT ROUND((COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL)*(VALOR/100),0) 
																	FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL))) END ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),(COALESCE(CIT.CANTIDADC,1)*CIT.VALORTOTAL)))  ELSE NULL END            
			FROM   CIT INNER JOIN SER ON SER.IDSERVICIO = CIT.IDSERVICIO 
						LEFT JOIN TER ON TER.IDTERCERO = CIT.IDTERCEROCA
			WHERE  CIT.CONSECUTIVO   = @NOAUT
			AND    SER.PREFIJO       <> @PRE1
			AND    SER.PREFIJO       <> @PRE2
			AND    SER.PREFIJO       <> @PRE3
			AND    SER.PREFIJO       <> @PRE4
			AND    SER.PREFIJO       <> @PRE5                 
			AND    (CIT.FACTURADA=0 OR CIT.FACTURADA IS NULL)
			AND    (TER.IDTERCERO  = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCEROF=@IDTERCEROCA)) 
		END
      
		SELECT @OK = COUNT(*) FROM #FTRD1

		SELECT @DV = DIASVTO, @TTEC = TIPOTERCONTABLE
		FROM   PPT 
		WHERE  IDTERCERO = @IDTERCEROCA AND IDPLAN = @IDPLAN
		
		IF ISNULL(@DV,0) <= 0
			SET @DV = 30
		
		SELECT @CUENTACXC = CUENTA, @CUENTACXC_RAD=CUENTARAD FROM TTEC
		WHERE TIPO = @TTEC 

		IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART')
			OR @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART2') OR @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART3')
			OR @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART4') OR @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART5')
		BEGIN   
			PRINT 'ES PARTICULAR REVISION 01.02.2008' 
			SELECT @TV = 'Contado'  
			SELECT @IDAFIAUX=DOCIDAFILIADO, @IDAFILIADO=IDAFILIADO FROM AFI WHERE IDAFILIADO= @IDAFILIADO   
			SELECT @EC = 1
			SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
			PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
			EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA, @PROC, @NOAUT		 
		END
		ELSE
		BEGIN
			SELECT @TV = 'Credito'  
		END  

		--SELECT * FROM #FTRD1
		--PRINT 'ME DEVUELVO'
		--RETURN
      
       PRINT 'Valido el Moto Permitido'
      SELECT @MONTO=SUM(COALESCE(VLR_SERVICI,0))  FROM #FTRD1
       IF DBO.FNK_VALIDA_TOPE_FACTURA(CASE WHEN @PROC='CI' THEN 'CITAS' ELSE 'CE' END,@MONTO)=0
      BEGIN
			RAISERROR('El monto a Facturar Sobrepasa el Valor Autorizado, No se Puede Generar la Factura ',16,1)
			FETCH NEXT FROM CUR_FTR
		   INTO @IDTERCEROCA,@IDPLAN,@N_FACTURAORI       
         CONTINUE
      END

		IF @OK > 0 
		BEGIN
			IF @PROC = 'CE'
			BEGIN
				IF COALESCE(@LIBERTER,'')<>'SI'
				BEGIN 
					IF EXISTS(SELECT * FROM FTR WHERE NOREFERENCIA=@NOAUT AND PROCEDENCIA='CE' AND ESTADO='L')
					BEGIN
						SELECT @LIBERADA=1,@NVOCONSEC=N_FACTURA , @CNSFTR=CNSFCT FROM FTR 
						WHERE NOREFERENCIA=@NOAUT 
						AND PROCEDENCIA='CE' AND ESTADO='L' AND N_FACTURA= CASE WHEN COALESCE(@N_FACTURAORI,'')<>'' THEN COALESCE(@N_FACTURAORI,'') ELSE FTR.N_fACTURA END
					END
					ELSE
					BEGIN
						SELECT @LIBERADA=0
					END
				END
				ELSE
				BEGIN 
					IF EXISTS(SELECT * FROM FTR WHERE IDTERCERO=@IDTERCEROCA1 AND ESTADO='L')
					BEGIN
						SELECT TOP 1  @LIBERADA=1,@NVOCONSEC=N_FACTURA , @CNSFTR=CNSFCT FROM FTR WHERE IDTERCERO=@IDTERCEROCA1 
						AND ESTADO='L' 
					END 
				END 
			END
			IF  COALESCE(@LIBERADA,0)=0
			BEGIN        
				SET @NVOCONSEC = SPACE(20)
				EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
				PRINT ' N_FACTURA = '+ CASE WHEN @NVOCONSEC IS NULL THEN '' ELSE @NVOCONSEC END         
				EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
				SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0)         
				PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
			END
			IF @PROC = 'CE'
			BEGIN
				SELECT @IDFORMATOFTR=IDFORFTRCE FROM PPT WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLAN
			END
			IF @PROC = 'CI'
			BEGIN
				SELECT @IDFORMATOFTR=IDFORFTRCIT FROM PPT WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLAN
			END
			IF COALESCE(@IDFORMATOFTR,'')=''
			BEGIN
				SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
			END
			/* SE REVISA SI EL PARAMETRO @FECHAFAC VIENE CON FECHA PARA COLOCARLE ESA FECHA A LA FACTURA SI NO SE COLOCA GETDATE()*/
			IF ISNULL(@FECHAFAC,'') = ''
			BEGIN
				SELECT @FECHAFAC = GETDATE()
			END
			PRINT ' N_FACTURA = '+ CASE WHEN @NVOCONSEC IS NULL THEN 'NO FACTURA' ELSE @NVOCONSEC END
			PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
			IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
			BEGIN
				IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
				BEGIN
					SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA = 'FTR' 
				END
				ELSE
				BEGIN
					SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = 'FTR'
				END
			END
			IF  COALESCE(@LIBERADA,0)=0
			BEGIN
				PRINT 'VOY A INSERTAR FTR...'
				PRINT '@DESCUENTO ANTES DEL INSERT=  :::::::::'+STR(@DESCUENTO)
			
				IF (@IDTERCEROCA = dbo.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') AND EXISTS (SELECT * FROM TER WHERE ESTADO='Activo' AND NIT=@IDAFIAUX ))
				BEGIN
						SELECT @IDAFILIADOTER= IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=@IDAFIAUX 
				END 
				PRINT '@IDAFILIADOTER '+ @IDAFILIADOTER
				INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
							VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
							IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
							TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
							INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
							IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
							MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
							CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CAPITADA,CODUNG, CODPRG, IDSEDE, RDIAN,CNSRESOL,IDFORMATO)
				SELECT @CNSFTR, @COMPANIA, 'C', CASE WHEN @TV='Contado' AND @EC=1 THEN (CASE @IDTERCEROCA WHEN dbo.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') 
																										THEN @IDAFILIADOTER  
																										ELSE @IDTERCERO END) ELSE  @IDTERCEROCA END, 
						@NVOCONSEC, @FECHAFAC, @FECHAFAC + @DV,
						0, NULL, NULL, LEFT(@MONEDA,2), NULL, 'P', NULL, 
						@IDAFILIADO, @USUARIO, @NOAUT,
						@PROC, 'I', REPLACE(COALESCE(@OBSERVACION,''),'@N_FACTURA',@NVOCONSEC), @TV, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO,
						GETDATE(), 0, 0, 0, @IDPLAN, NULL, 'C', NULL, @IDAREA, @CCOSTO, @DATO3, @TTEC,
						@CUENTACXC,@CUENTACXC_RAD, 0 ,@CODUNG, @CODPRG, @IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''),@IDFORMATOFTR
			END
			ELSE
			BEGIN
				PRINT 'ACTUALIZO FTR FACTURA LIBERADA...........'
				UPDATE FTR SET ESTADO='P',CONTABILIZADA=0,NROCOMPROBANTE=NULL,NOREFERENCIA=@NOAUT, IDAFILIADO=@IDAFILIADO,PROCEDENCIA=@PROC,
					IDTERCERO=@IDTERCEROCA,IDPLAN=@IDPLAN,CUENTACXC= @CUENTACXC, CUENTACXC_RAD=@CUENTACXC_RAD,
					TIPOTTEC=@TTEC, F_FACTURA=@FECHAFAC, F_VENCE=@FECHAFAC + @DV,FECHAFAC=GETDATE(), DESCUENTO = @DESCUENTO --  STORRES SE AGREGA CAMPO DE DESCUENTOPARA QUE SE ACTUALIZE
				WHERE N_FACTURA=@NVOCONSEC AND CNSFCT=@CNSFTR AND ESTADO='L'
			END
			
			UPDATE #FTRD1 SET 
			CANTIDAD    = CASE WHEN CANTIDAD    IS NULL THEN 0 ELSE CANTIDAD    END,
			VALOR       = CASE WHEN VALOR       IS NULL THEN 0 ELSE VALOR       END,
			VLR_SERVICI = CASE WHEN VLR_SERVICI IS NULL THEN 0 ELSE VLR_SERVICI END,
			VR_TOTAL    = CASE WHEN VR_TOTAL    IS NULL THEN 0 ELSE VR_TOTAL    END,
			VLR_COPAGOS = CASE WHEN VLR_COPAGOS IS NULL THEN 0 ELSE VLR_COPAGOS END,
			VLR_PAGCOMP = CASE WHEN VLR_PAGCOMP IS NULL THEN 0 ELSE VLR_PAGCOMP END
         
			UPDATE #FTRD1 SET VLR_SERVICI=VLR_COPAGOS, VALOR=VLR_COPAGOS/CANTIDAD, VR_TOTAL=0
			WHERE VLR_COPAGOS>VLR_SERVICI
         
         
			INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
						IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
			SELECT @CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
				IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
				VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
				NOPRESTACION, NOITEM, AREAFUNCONT, @NVOCONSEC, SUBCCOSTO, PCOSTO, FECHAPREST,
				IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV        
			FROM #FTRD1
			
			TRUNCATE TABLE #FTRD1 
         
			SELECT @VIVA=SUM(COALESCE(VIVA,0)) FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  
			IF @VIVA>0
			BEGIN
				SELECT TOP 1 @PIVA=PIVA ,@MIVA=1 FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  AND COALESCE(PIVA,0)<>0            
				UPDATE FTR SET MIVA=@MIVA,PIVA=@PIVA,VIVA=@VIVA WHERE N_FACTURA = @NVOCONSEC
			END

			IF @PROC='CE' AND @CETIPOHOSP= 'CEHOSP' 
			BEGIN 
				SELECT @VRTOTAL = SUM(VR_TOTAL), @VRSERV = SUM(VLR_SERVICI),@VRCOPA = MAX(AUT.VALORCOPAGO) ,
						@VRPACO  = SUM(VLR_PAGCOMP)
				FROM FTRD INNER JOIN AUT ON AUT.IDAUT=FTRD.NOPRESTACION
				WHERE FTRD.N_FACTURA = @NVOCONSEC

				UPDATE FTRD SET 
				VLR_COPAGOS =@VRCOPA/(SELECT COUNT(1) FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  ),  
				VR_TOTAL    =(VALOR*CANTIDAD)-COALESCE((@VRCOPA/(SELECT COUNT(1) FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC )), 0)+ 
							(CASE WHEN COALESCE(FTRD.VIVA, 0) <> 0 
									THEN CASE WHEN @BASE_IVA_SER='CONIVA' 
										THEN 0 ELSE  COALESCE(VIVA,0) 
										END
								ELSE 0 END)
				WHERE FTRD.N_FACTURA = @NVOCONSEC AND FTRD.VALOR>0
			END
			ELSE
				SELECT @VRTOTAL = SUM(VR_TOTAL), @VRSERV = SUM(VLR_SERVICI),@VRCOPA = SUM(VLR_COPAGOS)  ,
					@VRPACO  = SUM(VLR_PAGCOMP)
				FROM FTRD WHERE N_FACTURA = @NVOCONSEC

			PRINT '***********************************VALOR ***********************'
			PRINT @VRTOTAL    
			PRINT @VRSERV 
			IF @VRTOTAL < 0
			BEGIN
				SELECT @VRTOTAL = 0
			END
         
			IF @DESCUENTO IS NULL
				SELECT @DESCUENTO = 0
          
			PRINT '@DESCUENTO=  :::::::::'+STR(@DESCUENTO)

			IF @DESCUENTO > 0
			BEGIN
				IF @TIPODTO = 'P'
					SELECT @VRDTO = ROUND(@VRTOTAL * (COALESCE(@DESCUENTO,0)/100),0)
				ELSE 
					SELECT @VRDTO = COALESCE(@DESCUENTO,0) 
				END           
			ELSE
			BEGIN
				SELECT @VRDTO = 0
			END
         
			IF COALESCE(@VRABONO,0)=0
			BEGIN
				SELECT @VRABONO = 0
			END
         
			UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = ROUND(@VRCOPA,0), VALORPCOMP = @VRPACO,
					--VR_TOTAL = @VRTOTAL+CASE WHEN @BASE_IVA_SER='CONIVA' THEN 0 ELSE  COALESCE(@VIVA,0) END, //SE VUELVE A ACTUALIZAR ABAJO
					DESCUENTO = IIF(@ESOPTICA='SI',0,@VRDTO), VR_ABONOS = @VRABONO
			WHERE N_FACTURA = @NVOCONSEC
         
			--IF @PROC= 'CE'
			--BEGIN
			--   IF @VRCOPA = 0 AND @EC <> 1 AND ( @IDPLAN <> DBO.FNK_VALORVARIABLE('IDPLANPART')  OR
			--                                     @IDPLAN <> DBO.FNK_VALORVARIABLE('IDPLANPART2')  OR
			--                                     @IDPLAN <> DBO.FNK_VALORVARIABLE('IDPLANPART3')  OR
			--                                     @IDPLAN <> DBO.FNK_VALORVARIABLE('IDPLANPART4')  OR
			--                                     @IDPLAN <> DBO.FNK_VALORVARIABLE('IDPLANPART5') )
			--   BEGIN
			--      SELECT @VRCOPA = VALORCOPAGO FROM AUT WHERE NOAUT = @NOAUT
			--      UPDATE FTR SET VALORCOPAGO = @VRCOPA WHERE N_FACTURA = @NVOCONSEC
			--   END   
			--END        
         
			UPDATE FTR SET VR_TOTAL = COALESCE(VALORSERVICIOS,0) - COALESCE(VALORCOPAGO,0) - COALESCE(VALORPCOMP,0) - COALESCE(DESCUENTO,0) - COALESCE(VR_ABONOS,0)+CASE WHEN @BASE_IVA_SER='CONIVA' THEN 0 ELSE  COALESCE(@VIVA,0) END
			WHERE  N_FACTURA = @NVOCONSEC  
         
			IF (SELECT SIIF FROM TER WHERE IDTERCERO = @IDTERCEROCA)=1
			BEGIN
				SELECT @OBSERVACION='#$'+COALESCE(SIIFCODIGOPCI,'')+';'+COALESCE(SIIFCONTRATO,@NVOCONSEC)+';'+COALESCE(SIIFCORREOSUPER,'')+'#$'
				FROM TER WHERE IDTERCERO = @IDTERCEROCA
				UPDATE FTR SET OBSERVACION=@OBSERVACION WHERE N_FACTURA=@NVOCONSEC
			END
            
			UPDATE FTR SET VR_TOTAL = 0
			WHERE  VR_TOTAL < 0
			AND    N_FACTURA = @NVOCONSEC      
      
			IF @EC <> 1
				EXEC SPK_FAC_IMPDEDUC @NIT, @CNSFTR, @NVOCONSEC, @VRSERV
   
			IF @PROC = 'CE'      
			BEGIN
				IF @CETIPOHOSP = 'CEHOSP'
				BEGIN
					UPDATE AUTD SET N_FACTURA=@NVOCONSEC, FACTURADA=1, CNSFCT=@CNSFTR
					FROM   AUTD INNER JOIN 
						AUT ON AUTD.IDAUT = AUT.IDAUT INNER JOIN 
						SER ON SER.IDSERVICIO = AUTD.IDSERVICIO LEFT JOIN
						TER ON TER.IDTERCERO = AUTD.IDTERCEROCA
					WHERE  AUT.NOAUT = @NOAUT
						AND SER.PREFIJO       <> @PRE1
						AND SER.PREFIJO       <> @PRE2
						AND SER.PREFIJO       <> @PRE3
						AND SER.PREFIJO       <> @PRE4
						AND SER.PREFIJO       <> @PRE5                 
						AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL OR AUTD.FACTURADA=2)
						AND (TER.IDTERCERO  = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCEROF=@IDTERCEROCA))                
						AND AUTD.IDPLAN = @IDPLANPAR
				END
				ELSE
				BEGIN
					IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART2') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART3') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART4') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART5') OR 
						@EC = 1
					BEGIN
						UPDATE AUTD SET N_FACTURA=@NVOCONSEC, FACTURADA=1, CNSFCT=@CNSFTR
						FROM   AUTD INNER JOIN 
							AUT ON AUTD.IDAUT = AUT.IDAUT INNER JOIN 
							SER ON SER.IDSERVICIO = AUTD.IDSERVICIO LEFT JOIN
							TER ON TER.IDTERCERO = AUTD.IDTERCEROCA
						WHERE  AUT.NOAUT = @NOAUT                
							AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL OR AUTD.FACTURADA=2)
							AND (TER.IDTERCERO  = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCEROF=@IDTERCEROCA))                
					END
					ELSE
					BEGIN   
						UPDATE AUTD SET N_FACTURA=@NVOCONSEC, FACTURADA=1, CNSFCT=@CNSFTR
						FROM   AUTD INNER JOIN 
							AUT ON AUTD.IDAUT = AUT.IDAUT INNER JOIN 
							SER ON SER.IDSERVICIO = AUTD.IDSERVICIO LEFT JOIN
							TER ON TER.IDTERCERO = AUTD.IDTERCEROCA
						WHERE  AUT.NOAUT = @NOAUT
							AND SER.PREFIJO       <> @PRE1
							AND SER.PREFIJO       <> @PRE2
							AND SER.PREFIJO       <> @PRE3
							AND SER.PREFIJO       <> @PRE4
							AND SER.PREFIJO       <> @PRE5                 
							AND (AUTD.FACTURADA=0 OR AUTD.FACTURADA IS NULL OR AUTD.FACTURADA=2)
							AND (TER.IDTERCERO  = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCEROF=@IDTERCEROCA)) 
					END
				END
			END
			ELSE
			BEGIN
				UPDATE CIT SET CIT.FACTURADA = 1,       CIT.N_FACTURA = @NVOCONSEC,
						CIT.CNSFCT    = @CNSFTR, CIT.VFACTURAS = 0,
							CIT.MARCAFAC  = 0
				WHERE CONSECUTIVO = @NOAUT
				IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART') OR 
					@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART2') OR 
					@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART3') OR 
					@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART4') OR 
					@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART5') OR 
					@EC = 1
				BEGIN 
					UPDATE TFCJ SET VALORTOTAL =( CIT.VALORTOTAL-COALESCE(CIT.DESCUENTO,0))  FROM TFCJ INNER JOIN CIT ON CIT.CONSECUTIVO =TFCJ.NOADMISION 
					WHERE TFCJ.PROCEDENCIA='CITAS' AND CIT.CONSECUTIVO= @NOAUT
						
					UPDATE TFCJD SET VALORTOTAL =( CIT.VALORTOTAL-COALESCE(CIT.DESCUENTO,0)) , VALORUNITARIO=( CIT.VALORTOTAL-COALESCE(CIT.DESCUENTO,0))
													FROM TFCJ INNER JOIN CIT ON CIT.CONSECUTIVO =TFCJ.NOADMISION 
															INNER JOIN TFCJD ON TFCJ.CNSFACJ=TFCJD.CNSFACJ
					WHERE TFCJ.PROCEDENCIA='CITAS' AND CIT.CONSECUTIVO= @NOAUT
				END 
			END
			IF @SOAT = 1
			BEGIN
				IF @PROC = 'CE'
				BEGIN
					UPDATE HACTRAND SET N_FCT_ASEG = @NVOCONSEC WHERE PROCEDENCIA = 'CE' AND CNSHACTRAN = @CNSHACTRAN
					AND NOREFERENCIA = @NOAUT
				END
				ELSE
				BEGIN
					UPDATE HACTRAND SET N_FCT_ASEG = @NVOCONSEC WHERE PROCEDENCIA = 'CI' AND CNSHACTRAN = @CNSHACTRAN
					AND NOREFERENCIA = @NOAUT
				END
			END
		END
		IF @PROC = 'CE'
		BEGIN
			IF (SELECT DBO.FNK_VALORVARIABLE('CEMANEJA_FXP') ) = 'SI'
			BEGIN
				EXEC SPK_CREACXP_CE @NOAUT, @COMPANIA, @IDSEDE, @USUARIO, @NVOCONSEC
			END
		END  
		IF @PROC = 'CI'
		BEGIN
			IF (SELECT DBO.FNK_VALORVARIABLE('CIMANEJA_FXP') ) = 'SI'
			BEGIN
				EXEC SPK_CREACXP_CI @NOAUT, @COMPANIA, @IDSEDE,@USUARIO
			END
		END
   
		--CONTABILIZA FACTURA
		--EXEC SPK_NC_CONTAB_FTR @NVOCONSEC, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''

		PRINT 'REVISO PRESUPUESTO'
		IF DBO.FNK_VALORVARIABLE('PRESUP_CXC_ACTIVADO')= 'SI'  
		BEGIN 
			PRINT 'ESTOY ACTIVADO'
			IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'  
			BEGIN
				PRINT 'ENVIO AUTOMATICO A PRESUPUESTO FACURA EN PPTO'
				EXEC DBO.SPK_ENTREGA_FACTURA_PTTO @NVOCONSEC,@IDSEDE
			END
		END
		FETCH NEXT FROM CUR_FTR
		INTO @IDTERCEROCA,@IDPLAN,@N_FACTURAORI
	END
	CLOSE CUR_FTR
	DEALLOCATE CUR_FTR
	DROP TABLE #FTRD1
	IF @PROC = 'CE'      
	BEGIN
		UPDATE AUT 
		SET AUT.FACTURADA = 1, AUT.N_FACTURA = @NVOCONSEC,
			AUT.CNSFCT    = @CNSFTR, AUT.VFACTURAS = 0,
			AUT.MARCAFAC  = 0, IDPLAN = COALESCE((SELECT IDPLAN FROM FTR WHERE  N_FACTURA=@NVOCONSEC),@IDPLAN)
		WHERE NOAUT = @NOAUT  
	END     
END


