 SELECT TER.TIPO_ID,COALESCE(TER.NIT,  TER.IDTERCERO)IDTERCERO  ,TER.DV,
                      COALESCE(CASE WHEN TER.TIPO_ID<>'NIT' THEN  DBO.FNK_SEPARA_NOMBRES(REPLACE(REPLACE(REPLACE(TER.RAZONSOCIAL,CHAR(13),''),CHAR(10),''),'"',''),1) ELSE '' END,'')PAPELLIDO,
                      COALESCE(CASE WHEN TER.TIPO_ID<>'NIT' THEN  DBO.FNK_SEPARA_NOMBRES(REPLACE(REPLACE(REPLACE(TER.RAZONSOCIAL,CHAR(13),''),CHAR(10),''),'"',''),2) ELSE '' END,'')SAPELLIDO,
                      COALESCE(CASE WHEN TER.TIPO_ID<>'NIT' THEN  DBO.FNK_SEPARA_NOMBRES(REPLACE(REPLACE(REPLACE(TER.RAZONSOCIAL,CHAR(13),''),CHAR(10),''),'"',''),3) ELSE '' END,'')PNOMBRE,
                      COALESCE(CASE WHEN TER.TIPO_ID<>'NIT' THEN  DBO.FNK_SEPARA_NOMBRES(REPLACE(REPLACE(REPLACE(TER.RAZONSOCIAL,CHAR(13),''),CHAR(10),''),'"',''),4) ELSE '' END,'')SNOMBRE,
                      COALESCE(CASE WHEN TER.TIPO_ID='NIT' THEN REPLACE(REPLACE(REPLACE(TER.RAZONSOCIAL,CHAR(13),''),CHAR(10),''),'"','') ELSE '' END,'' )RAZONSOCIAL,
                      REPLACE(REPLACE(REPLACE(TER.DIRECCION,CHAR(13),''),CHAR(10),''),',','')DIRECCION,CIU.DPTO,
                      RIGHT(CIU.CIUDAD,LEN(CIU.CIUDAD)-LEN(CIU.DPTO))CIUDAD,'044'PAIS,COD_RESP_FISCAL,TER.IDACTIVIDAD,AEC.DESCRIPCION
FROM TER LEFT JOIN CIU ON TER.CIUDAD=CIU.CIUDAD
         LEFT JOIN AEC ON TER.IDACTIVIDAD=AEC.IDACTIVIDAD