USE PESPERANZA
SELECT FTR.N_FACTURA,FTR.F_FACTURA,TER.NIT,TER.RAZONSOCIAL,FTR.IDPLAN,PLN.DESCPLAN,PLN.TIPOSISTEMA,FTR.TIPOTTEC,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,
FTR.VALORSERVICIOS,FTR.VALORCOPAGO,CASE WHEN COALESCE(FTR.ESTADO,'')<>'P' OR COALESCE(TIPOANULACION,'')='NC' THEN 0 ELSE FTR.VR_TOTAL END VR_TOTAL,FTR.ESTADO,COALESCE(FTR.TIPOANULACION,'')TIPOANULACION,INDCARTERA,INDCXC,IDDEP,
YEAR(F_FACTURA)ANOS,
MONTH(F_FACTURA)MES,
DATENAME(MONTH,F_FACTURA)NMES
FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
         LEFT  JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
         LEFT  JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
ORDER BY F_FACTURA ASC
