IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNK_VALORCONCEPTO_NEMPFD_RUN' AND XTYPE='TF')
BEGIN
   DROP FUNCTION DBO.FNK_VALORCONCEPTO_NEMPFD_RUN
END  

GO
CREATE FUNCTION DBO.FNK_VALORCONCEPTO_NEMPFD_RUN(     
	@NUMDOC      VARCHAR(20),  
	@CODCONCEPTO VARCHAR(20),     
	@FECHAINI    DATETIME,     
	@FECHAFIN    DATETIME,  
	@CNSPAGO     VARCHAR(20),  
	@VALHORASLAB SMALLINT,  
	@HORAS_COMP   INT,  
	@DIAS_LAB     INT)     
RETURNS @TABLA    
	TABLE (DETALLE           VARCHAR(100)  COLLATE database_default,  
		CANTIDAD          DECIMAL(15,6),  
		VALOR_EMPLEADO    DECIMAL(15,6),   
		VALOR_EMPRESA     DECIMAL(15,6),  
		VALOR100P         DECIMAL(15,6),  
		FILA              INT IDENTITY,   
		IDTRANSPRESTAMO   VARCHAR(6)   COLLATE database_default,   
		NUMDOCPRESTAMO    VARCHAR(20)  COLLATE database_default,   
		NUMCUOTA          SMALLINT,  
		CODPRF            VARCHAR(20)  COLLATE database_default,  
		IDTERCERO         VARCHAR(20)  COLLATE database_default,  
		BASE_PRESTACIONES VARCHAR(2)   COLLATE database_default,  
		ITEMCONCEPTO      DECIMAL(14,0),  
		GENERANOVEFU      SMALLINT,   
		CODNOVEFU         VARCHAR(10)  COLLATE database_default,   
		BASE_CALCULO      DECIMAL(15,6),  
		MOSTRARHORAS      VARCHAR(12)   COLLATE database_default)   
AS      
BEGIN      
	DECLARE @CODCARGO              VARCHAR(20)     
	DECLARE @NIVEL                 VARCHAR(10)  
	DECLARE @GRADO                 VARCHAR(10)      
	DECLARE @CODPLANTA             VARCHAR(20)      
	DECLARE @BASE                  VARCHAR(20)     
	DECLARE @BASICO                DECIMAL(15,6)    
	DECLARE @HORASXCARGO           DECIMAL(15,6)    
	DECLARE @HORAS_SUMARESTA       DECIMAL(15,6)  
	DECLARE @HORAS_LABORADAS       DECIMAL(15,6)  
	DECLARE @TIPOCALCULO           VARCHAR(10)    
	DECLARE @VALOR                 DECIMAL(15,6)    
	DECLARE @VALOR_EMPRESA         DECIMAL(15,6)    
	DECLARE @VALOR_CALCULO         DECIMAL(15,6) 
	DECLARE @VALOR_CALCULOMAX      DECIMAL(15,6)     
	DECLARE @VALOR_HORA            DECIMAL(15,6)    
	DECLARE @CONCEPTO_CON_EVENTO   SMALLINT    
	DECLARE @CONDICION             VARCHAR(2)    
	DECLARE @EVALUAR               VARCHAR(20)    
	DECLARE @ITEM_NCOND            SMALLINT    
	DECLARE @TIPODEPENDENCIA       VARCHAR(20)    
	DECLARE @CODDEPENDENCIA        VARCHAR(20)    
	DECLARE @FACTOR                DECIMAL(15,6) 
	DECLARE @FACTORMAX             DECIMAL(15,6)  
	DECLARE @VALORMAXIMO           DECIMAL(14,2)     
	DECLARE @OPERACION             VARCHAR(2)    
	DECLARE @VALOR_DEPENDENCIA     DECIMAL(15,6)    
	DECLARE @VALOR_EVALUAR         DECIMAL(15,6)    
	DECLARE @PORCLABORADO          DECIMAL(15,6)    
	DECLARE @CANTIDAD  DECIMAL(15,6)  
	DECLARE @MOSTRARHORAS  VARCHAR(12)  
	DECLARE @CODPRF  VARCHAR(20)  
	DECLARE @IDTERCERO  VARCHAR(20)  
	DECLARE @GENERA_CXP  VARCHAR(2)  
	DECLARE @IDTERCERO_DEFAULT VARCHAR(20)  
	DECLARE @DETALLE  VARCHAR(10)  
	DECLARE @CLASE   VARCHAR(20)  
	DECLARE @IDPARENTESCO  VARCHAR(20)  
	DECLARE @SEXO   VARCHAR(12)  
	DECLARE @EDADMIN  DECIMAL(15,6)  
	DECLARE @EDADMAX  DECIMAL(15,6)  
	DECLARE @ESTADO_PARIENTE VARCHAR(20)  
	DECLARE @MAXIMO  DECIMAL(15,6)  
	DECLARE @VALOR_PARIENTES DECIMAL(15,6)  
	DECLARE @CANT_PARIENTES DECIMAL(15,6)  
	DECLARE @NIVELESTUDIOS  VARCHAR(12)  
	DECLARE @ESTUDIANTE  VARCHAR(2)  
	DECLARE @VALOR100P  DECIMAL(15,6)  
	DECLARE @CVALOR100P  VARCHAR(2)  
	DECLARE @VALOR_CALCULO100P  DECIMAL(15,6)  
	DECLARE @TIPO   VARCHAR(20)  
	DECLARE @TIPOLIQ  VARCHAR(12)  
	DECLARE @DIASXPERIODO  DECIMAL(15,6)  
	DECLARE @DIASXCARGO  DECIMAL(15,6)  
	DECLARE @HORAS_A_LABORAR DECIMAL(15,6)  
	DECLARE @BASE_PRESTACIONES VARCHAR(2)  
	DECLARE @CODNOMINA  VARCHAR(2)   
	DECLARE @CODCONCEPTO_CUR VARCHAR(20)  
	DECLARE @CNSPAGO_CUR  VARCHAR(20)  
	DECLARE @FECHAINI_CUR  DATETIME  
	DECLARE @FECHAFIN_CUR  DATETIME  
	DECLARE @PRIORIDAD_CUR  INT  
	DECLARE @VALOR_CONCEPTO DECIMAL(15,6)  
	--DECLARE @FORMULA  VARCHAR(2048)  
	DECLARE @FACTOR_CUR  DECIMAL(15,6)  
	DECLARE @FECHAING  DATETIME  
	DECLARE @PARAMETRO  VARCHAR(20)  
	DECLARE @VALOR_PARAMETRO DECIMAL(15,6)  
	DECLARE @MESES   INT  
	DECLARE @DIAS   INT  
	DECLARE @FECHA   DATETIME  
--- VARIABLES PARA PRESTAMOS    
	DECLARE @CUOTASPGR             SMALLINT    
	DECLARE @NUMDOCPRESTAMO_CUR    VARCHAR(29)    
	DECLARE @IDTRANSPRESTAMO_CUR   VARCHAR(29)    
	DECLARE @NUMCUOTA_CUR          VARCHAR(29)    
	DECLARE @VLRCUOTA_CUR          DECIMAL(15,6)    
	DECLARE @DIAS1                 INT  
	DECLARE @DIAS2                 INT  
	DECLARE @BASICO1               DECIMAL(15,6)  
	DECLARE @BASICO2               DECIMAL(15,6)  
	DECLARE @VF                    VARCHAR(20)  
	DECLARE @VALOR_TABLA           DECIMAL(15,6)  
	DECLARE @FACTOR_NEMPT          DECIMAL(15,6)  
	DECLARE @VALIDA_ANTIGUEDAD     VARCHAR(2)  
	DECLARE @DIAS_ANTIGUEDAD       INT  
	DECLARE @CONDICION_ANTIGUEDAD  VARCHAR(2)  
	DECLARE @VALIDA_FINGRESO       VARCHAR(2)  
	DECLARE @FINGRESO              DATETIME  
	DECLARE @CONDICION_FINGRESO    VARCHAR(2)  
	DECLARE @SW                    INT  
	DECLARE @SOLICITA_CNSPAGO      VARCHAR(2)  
	DECLARE @SALARIOBASICO         DECIMAL(15,6)  
	DECLARE @VALIDATABLA           VARCHAR(20)  
	DECLARE @DMATABLA              VARCHAR(1)  
	DECLARE @DMAANTIGUEDAD         VARCHAR(1)  
	DECLARE @VALOR_A               DECIMAL(15,6)  
	DECLARE @VALOR_B               DECIMAL(15,6)  
	DECLARE @VALOR_C               DECIMAL(15,6)  
	DECLARE @EDAD                  DECIMAL(15,6)  
	DECLARE @ANTIGUEDAD            DECIMAL(15,6)  
	DECLARE @FNACIMIENTO           DATETIME  
	DECLARE @TIPOCALCULO2          VARCHAR(12)  
	DECLARE @FRECUENCIA            VARCHAR(12)  
	DECLARE @VALORFRECUENCIA       INT   
	DECLARE @DMAFRECUENCIA         VARCHAR(1)  
	DECLARE @RELFREQFECHA          VARCHAR(12)   
	DECLARE @FECHABASEFREQ         DATETIME   
	DECLARE @FECHA_BASE            DATETIME  
	DECLARE @REQUIERELIQ_NCONDF    SMALLINT  
	DECLARE @VALHORASLAB_NCONDF    SMALLINT  
	DECLARE @REQUIERELIQ_NCONDD    SMALLINT   
	DECLARE @VALHORASLAB_NCONDD    SMALLINT  
	DECLARE @HORAS_NCONDD          SMALLINT 
	DECLARE @DIAS_NCONDD           SMALLINT
	DECLARE @HORAS_NCONDF          SMALLINT
	DECLARE @DIAS_NCONDF           SMALLINT
	DECLARE @CONT                  INT  
	DECLARE @MAS_REDONDEO          DECIMAL(14,3)
	DECLARE @REDONDEO              DECIMAL(14,2)  
	DECLARE @HORAS_NPPAG           INT  
	DECLARE @DIAS_NPPAG            INT  
	DECLARE @GENERANOVEFU          SMALLINT  
	DECLARE @CODNOVEFU             VARCHAR(10)  
	DECLARE @ANT DECIMAL(14,2)  

	DECLARE @VALIDA_TLABORADOPER VARCHAR(2)
	DECLARE @CONDICION_TLABORADOPER VARCHAR(2)
	DECLARE @HORAS_TLABORADOPER SMALLINT
	DECLARE @DMATLABORADOPER VARCHAR(1)
	DECLARE @HORAS_TCOMPLETO  SMALLINT
	DECLARE @FTL              SMALLINT
	DECLARE @HORASLAB       DECIMAL(14,4)
	DECLARE @FECHAINGSIGMES DATETIME
	DECLARE @FECHAINISIGMES DATETIME
	DECLARE @FECHARETIRO    DATETIME
	DECLARE @RESTARETIRO    DECIMAL(14,4)
	DECLARE @HORADIA        DECIMAL(14,4)
	DECLARE @FNPER           DATETIME
	DECLARE @FNOV            DATETIME
	DECLARE @DNOV            SMALLINT
	DECLARE @X1             INT
	DECLARE @DIAINGPRENOMI  VARCHAR(10)
	--VARIABLE PARA SABER COMO SE CALCULA EL VALOR HORA MES SI POR EL NUMERO DE HORAS QUE TIENE EL CARGO  O POR EL DE UN MES NORMAL (240)
	DECLARE @TIPOVALORHORA VARCHAR(10)

 
DECLARE @FECHAINILIQ DATETIME
DECLARE @FECHAFINLIQ DATETIME
DECLARE @FECHAFINPER DATETIME 
SET @FECHAFINPER=@FECHAFIN
DECLARE @VALORD		 DECIMAL(15,6)
DECLARE @DIASCAL	 INT  
	SET @DIAS_LAB  = ISNULL(@DIAS_LAB,0)  
	SELECT @FNPER= @FECHAFIN
	SELECT  @FNACIMIENTO = FNACIMIENTO,@FECHARETIRO= COALESCE(FECHARETIRO,@FECHAFIN+30)
	FROM NEMP 
	WHERE NUMDOC=@NUMDOC  
	IF DAY(@FECHAFIN)=31
	BEGIN
		SELECT @FECHAFIN=DATEADD(DAY,-1,@FECHAFIN)
	END

	SET @DIAINGPRENOMI=DBO.FNK_VALORVARIABLE('DIAINGPRENOMI')
   

	SELECT   
	@BASICO      = H.BASICO,    
	@HORASXCARGO = H.HORASXCARGO,  
	@DIASXCARGO  = H.DIASXCARGO,  
	@FECHAING    = CASE @DIAINGPRENOMI WHEN 'SI' THEN DATEADD(DAY,-1,H.FECHAING) ELSE H.FECHAING END,
	@CODCARGO    = H.CODCARGO,  
	@NIVEL       = H.NIVEL,  
	@GRADO       = H.GRADO,  
	@CODPLANTA   = H.CODPLANTA  
	FROM FNK_INFO_NEMPHIS_NEMP(@FECHAFIN,@NUMDOC) AS H 
 
	IF DBO.FNK_VALORVARIABLE('NOMINA_EN_DIASCALEN')='SI'
	BEGIN
		IF (DAY(@FECHAING)>30 OR DAY(@FECHARETIRO)>30)
		BEGIN 
			SELECT @FNOV=@FNPER,@DNOV=1
		END
		ELSE
		BEGIN
			SELECT @FNOV=@FECHAFIN,@DNOV=0
		END
	END
	ELSE
	BEGIN 
		SELECT @FNOV=@FECHAFIN,@DNOV=0
	END	
 
	SELECT @HORADIA=@HORASXCARGO/@DIASXCARGO 
	SET @SALARIOBASICO  = @BASICO  
	SET @ANTIGUEDAD     = DATEDIFF(DAY,@FECHAING,@FECHAFIN)  
	SET @EDAD           = DATEDIFF(DAY,@FNACIMIENTO,@FECHAFIN)  
  
	IF @FECHAING>@FNPER  
	BEGIN  
		INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
		SELECT @DETALLE,0,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
		RETURN    
	END  
  
	SELECT @TIPOLIQ       = NPER.TIPOLIQ,   
		@HORAS_NPPAG   = NPPAG.HORASDELABOR,  
		@DIAS_NPPAG    = NPPAG.DIAS,  
		@CODNOMINA     = NPER.CODNOMINA  
	FROM NPER INNER JOIN  NPPAG ON NPER.CNSPAGO=@CNSPAGO AND NPER.CODPPAG=NPPAG.CODPPAG   
  
	IF @BASICO IS NULL OR @BASICO = 0  
	BEGIN  
		INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
		SELECT 'BASICO=0',0,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
		RETURN    
	END  
 
 
	SELECT TOP 1    
		@VALOR                = NCOND.VALOR,    
		@VALOR_EMPRESA        = NCOND.VALOR_EMPRESA,    
		@TIPOCALCULO          = NCOND.TIPOCALCULO,    
		@BASE                 = NCOND.BASE,    
		@CONDICION            = NCOND.CONDICION,    
		@EVALUAR              = NCOND.EVALUAR,    
		@ITEM_NCOND           = NCOND.ITEM,  
		@CODPRF               = NCOND.CODPRF,  
		@GENERA_CXP           = NCOND.GENERA_CXP,  
		@IDTERCERO_DEFAULT    = NCOND.IDTERCERO,  
		@DETALLE              = NCOND.DETALLE,  
		@BASE_PRESTACIONES    = NCOND.BASE_PRESTACIONES,  
		@CLASE                = NCON.CLASE,  
		@CVALOR100P           = NCON.CVALOR100P,  
		@TIPO                 = NCON.TIPO,  
		@MOSTRARHORAS         = NCON.MOSTRARHORAS,  
		@VALIDA_ANTIGUEDAD    = NCOND.VALIDA_ANTIGUEDAD,  
		@DIAS_ANTIGUEDAD      = NCOND.DIAS_ANTIGUEDAD,  
		@CONDICION_ANTIGUEDAD = NCOND.CONDICION_ANTIGUEDAD,  
		@DMAANTIGUEDAD        = NCOND.DMAANTIGUEDAD,  
		@VALIDA_FINGRESO      = NCOND.VALIDA_FINGRESO,  
		@FINGRESO             = NCOND.FINGRESO,  
		@CONDICION_FINGRESO   = NCOND.CONDICION_FINGRESO,  
		@VALIDATABLA          = NCOND.VALIDATABLA,  
		@DMATABLA               = NCOND.DMATABLA,   
		@FRECUENCIA             = NCOND.FRECUENCIA,  
		@VALORFRECUENCIA        = NCOND.VALORFRECUENCIA,  
		@DMAFRECUENCIA          = NCOND.DMAFRECUENCIA,  
		@RELFREQFECHA           = NCOND.RELFREQFECHA,  
		@FECHABASEFREQ          = NCOND.FECHABASEFREQ,  
		@REDONDEO               = NCOND.REDONDEO,  
		@VALIDA_TLABORADOPER    = NCOND.VALIDA_TLABORADOPER,
		@CONDICION_TLABORADOPER = NCOND.CONDICION_TLABORADOPER,
		@HORAS_TLABORADOPER     = NCOND.HORAS_TLABORADOPER,
		@DMATLABORADOPER        = NCOND.DMATLABORADOPER,
		@HORAS_TCOMPLETO      = CASE WHEN ISNULL(@HORAS_COMP,0) > 0 THEN @HORAS_COMP ELSE ISNULL(NCOND.HORAS,0) END,
		@DIASXPERIODO         = CASE WHEN @DIAS_LAB  = -1 THEN   
								CASE WHEN ISNULL(NCOND.DIAS,0)=0  THEN @DIAS_NPPAG ELSE NCOND.DIAS END   
								ELSE   
								CASE WHEN @DIAS_LAB>0  THEN @DIAS_LAB ELSE   
								CASE WHEN ISNULL(NCOND.DIAS,0)=0 THEN @DIAS_NPPAG ELSE NCOND.DIAS END   
								END   
								END,  
		@GENERANOVEFU          = NCOND.GENERANOVEFU,  
		@CODNOVEFU             = NCOND.CODNOVEFU,
		@TIPOVALORHORA         = NCOND.TIPOVALORHORA
	FROM NCOND INNER JOIN  NCON ON NCOND.CODCONCEPTO=NCON.CODCONCEPTO AND  
		NCON.CODCONCEPTO=@CODCONCEPTO AND NCOND.FECHAINI<=@FECHAFIN 
	ORDER BY FECHAINI DESC
  
	IF @REDONDEO=2
		SET @MAS_REDONDEO=0.004
	ELSE IF @REDONDEO=1
		SET @MAS_REDONDEO=0.04
	ELSE IF @REDONDEO=0
		SET @MAS_REDONDEO=0.4
	ELSE IF @REDONDEO=-1
		SET @MAS_REDONDEO=4.0
	ELSE IF @REDONDEO=-2
		SET @MAS_REDONDEO=40.0
	ELSE IF @REDONDEO=-3
		SET @MAS_REDONDEO=400.0
	ELSE 
		SET @MAS_REDONDEO=0.0
 


	-- Validar Frecuencia  
	SET @FECHA_BASE = CASE WHEN @RELFREQFECHA = 'Ingreso' THEN @FECHAING ELSE @FECHABASEFREQ END  
	IF @FRECUENCIA = 'Periodica' AND @VALHORASLAB = 1  
	BEGIN  
		SET @CONT = 0  
		WHILE @FECHA_BASE < @FECHAFIN  
		BEGIN   
			SET @CONT = @CONT + @VALORFRECUENCIA  
			SET @FECHA_BASE =   
			CASE @DMAFRECUENCIA   
				WHEN 'D' THEN DATEADD(DAY, @VALORFRECUENCIA, @FECHA_BASE )  
				WHEN 'M' THEN DATEADD(MONTH, @VALORFRECUENCIA, @FECHA_BASE)  
				WHEN 'A' THEN DATEADD(YEAR, @VALORFRECUENCIA, @FECHA_BASE)  
			END  
		END  

		IF @FECHA_BASE > @FECHAFIN  
		BEGIN   
			SET @FECHA_BASE =   
			CASE @DMAFRECUENCIA   
				WHEN 'D' THEN DATEADD(DAY, @VALORFRECUENCIA*-1, @FECHA_BASE )  
				WHEN 'M' THEN DATEADD(MONTH, @VALORFRECUENCIA*-1, @FECHA_BASE)  
				WHEN 'A' THEN DATEADD(YEAR, @VALORFRECUENCIA*-1, @FECHA_BASE)  
			END  
		END  

		IF NOT (@FECHA_BASE BETWEEN @FECHAINI AND @FECHAFIN) OR @CONT<@VALORFRECUENCIA OR @FECHAING>=@FECHAINI
		BEGIN  
			INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
			SELECT CONVERT(VARCHAR(10),@FECHA_BASE,103),0,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
			RETURN    
		END  
	END  
	ELSE  
		IF @FRECUENCIA = 'UnaVez' AND @VALHORASLAB = 1  
		BEGIN  
			SET @FECHA_BASE =   
			CASE @DMAFRECUENCIA   
				WHEN 'D' THEN DATEADD(DAY, @VALORFRECUENCIA, @FECHA_BASE )  
				WHEN 'M' THEN DATEADD(MONTH, @VALORFRECUENCIA, @FECHA_BASE)  
				WHEN 'A' THEN DATEADD(YEAR, @VALORFRECUENCIA, @FECHA_BASE)  
			END  
			IF NOT @FECHA_BASE BETWEEN @FECHAINI AND @FECHAFIN  
			BEGIN  
				INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
				SELECT CONVERT(VARCHAR(10),@FECHA_BASE,103),0,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
				RETURN    
			END    
		END  
  
	-- Validar Antiguedad  
	SET @SW = 0  
	IF @VALIDA_ANTIGUEDAD = 'Si'  
	BEGIN  
		SET @ANT = DBO.FNK_ANTIGUEDAD(@FECHAING,@FECHAFIN+1,@DMAANTIGUEDAD)
		SET @SW =  
		CASE @CONDICION_ANTIGUEDAD  
			WHEN '<'  THEN (CASE WHEN @ANT <  @DIAS_ANTIGUEDAD THEN 1 ELSE 0 END)  
			WHEN '<=' THEN (CASE WHEN @ANT <= @DIAS_ANTIGUEDAD THEN 1 ELSE 0 END)  
			WHEN '='  THEN (CASE WHEN @ANT =  @DIAS_ANTIGUEDAD THEN 1 ELSE 0 END)  
			WHEN '>'  THEN (CASE WHEN @ANT >  @DIAS_ANTIGUEDAD THEN 1 ELSE 0 END)  
			WHEN '>=' THEN (CASE WHEN @ANT >= @DIAS_ANTIGUEDAD THEN 1 ELSE 0 END)  
			WHEN '<>' THEN (CASE WHEN @ANT <> @DIAS_ANTIGUEDAD THEN 1 ELSE 0 END)  
		END  
		IF @SW = 0  
		BEGIN  
			INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
			SELECT 'ANTIGUEDAD',@ANT,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
			RETURN    
		END    
	END  

	-- Validar Fecha Ingreso del Empleado  
	SET @SW = 0  
	IF @VALIDA_FINGRESO = 'Si'  
	BEGIN  
		SET @SW =  
		CASE @CONDICION_FINGRESO  
			WHEN '<'  THEN (CASE WHEN @FECHAING <  @FINGRESO THEN 1 ELSE 0 END)  
			WHEN '<=' THEN (CASE WHEN @FECHAING <= @FINGRESO THEN 1 ELSE 0 END)  
			WHEN '='  THEN (CASE WHEN @FECHAING =  @FINGRESO THEN 1 ELSE 0 END)  
			WHEN '>'  THEN (CASE WHEN @FECHAING >  @FINGRESO THEN 1 ELSE 0 END)  
			WHEN '>=' THEN (CASE WHEN @FECHAING >= @FINGRESO THEN 1 ELSE 0 END)  
			WHEN '<>' THEN (CASE WHEN @FECHAING <> @FINGRESO THEN 1 ELSE 0 END)  
		END  
		IF @SW = 0  
		BEGIN  
			INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
			SELECT 'FECHA ING.',0,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
			RETURN    
		END    
	END  
  
	-- BUSCAR SALARIO BASICO  
	DECLARE CUR_NCONDB CURSOR FOR    
	SELECT PRIORIDAD, DIAS1, DIAS2, CONDICION  
	FROM NCONDB  
	WHERE CODCONCEPTO=@CODCONCEPTO AND ITEM=@ITEM_NCOND  
	ORDER BY PRIORIDAD  
  
	OPEN CUR_NCONDB    
  
	FETCH NEXT FROM CUR_NCONDB  
	INTO @PRIORIDAD_CUR, @DIAS1, @DIAS2, @OPERACION  
	SET @VF = 'Falso'  
	WHILE @@FETCH_STATUS = 0 AND @VF = 'Falso'  
	BEGIN      
		-- Busca El valor del Basico No 1 en la fecha correspondiente a Actual menos Dias1  
		SET @MESES = @DIAS1/30  
		SET @DIAS  = @DIAS1 - (@MESES*30)  
		SET @FECHA = DATEADD(MONTH,@MESES*-1,@FECHAFIN+1)  
		SET @FECHA = DATEADD(DAY,@DIAS*-1,@FECHA)  
		SET @BASICO1 = 0  
		SELECT TOP 1 @BASICO1=BASICO   
		FROM NEMPHIS WHERE NUMDOC=@NUMDOC AND FECHAMOV>=@FECHA ORDER BY FECHAMOV ASC  
		-- Busca El valor del Basico No 2 en la fecha correspondiente a Actual menos Dias2  
		SET @MESES = @DIAS2/30  
		SET @DIAS  = @DIAS2 - (@MESES*30)  
		SET @FECHA = DATEADD(MONTH,@MESES*-1,@FECHAFIN+1)  
		SET @FECHA = DATEADD(DAY,@DIAS*-1,@FECHA)  
		SET @BASICO2 = 0  
		SELECT TOP 1 @BASICO2=BASICO   
		FROM NEMPHIS WHERE NUMDOC=@NUMDOC AND FECHAMOV>=@FECHA ORDER BY FECHAMOV ASC  
		-- Hace la respectiva comparaci? entre Basico1 y Basico2  
		SET @VF =  
		CASE @OPERACION    
			WHEN '<'  THEN (SELECT CASE WHEN @BASICO1 <  @BASICO2 THEN 'Verdadero' Else 'Falso' END)  
			WHEN '<=' THEN (SELECT CASE WHEN @BASICO1 <= @BASICO2 THEN 'Verdadero' Else 'Falso' END)  
			WHEN '='  THEN (SELECT CASE WHEN @BASICO1 =  @BASICO2 THEN 'Verdadero' Else 'Falso' END)  
			WHEN '>=' THEN (SELECT CASE WHEN @BASICO1 >= @BASICO2 THEN 'Verdadero' Else 'Falso' END)  
			WHEN '>'  THEN (SELECT CASE WHEN @BASICO1 >  @BASICO2 THEN 'Verdadero' Else 'Falso' END)  
			WHEN '<>' THEN (SELECT CASE WHEN @BASICO1 <> @BASICO2 THEN 'Verdadero' Else 'Falso' END)  
			WHEN 'DE' THEN 'Verdadero'   
		END  
		IF @VF = 'Verdadero'  
		BEGIN  
			-- Calcula El Basico Segun parametros de Calculo  
			DECLARE CUR_NCONDBD CURSOR FOR    
			SELECT FACTOR, OPERACION, PARAMETRO, VALOR   
			FROM NCONDBD  
			WHERE CODCONCEPTO=@CODCONCEPTO AND ITEM=@ITEM_NCOND AND PRIORIDAD_CONDICION=@PRIORIDAD_CUR  
			ORDER BY PRIORIDAD
			
			OPEN CUR_NCONDBD    
     
			FETCH NEXT FROM CUR_NCONDBD  
			INTO @FACTOR, @OPERACION, @PARAMETRO, @VALOR_PARAMETRO  
			SET @VALOR_DEPENDENCIA=0    
			WHILE @@FETCH_STATUS = 0     
			BEGIN      
				IF @PARAMETRO='Dias'  
				BEGIN  
					SET @MESES = @VALOR_PARAMETRO/30  
					SET @DIAS  = @VALOR_PARAMETRO - (@MESES*30)  
					SET @FECHA = DBO.FNK_DIA_DEL_MES(YEAR(@FECHAFIN),MONTH(@FECHAFIN),'ULTIMO')   --DATEADD(MONTH,@MESES*-1,@FECHAFIN+1)  
					SET @FECHA = DATEADD(MONTH, @MESES*-1, @FECHA)                                        -- DATEADD(DAY,@DIAS*-1,@FECHA)  
					SET @VALOR_PARAMETRO = 0  

					SELECT @VALOR_PARAMETRO = X.BASICO FROM FNK_INFO_NEMPHIS_NEMMP(@FECHA,@NUMDOC) X 

					IF ISNULL(@VALOR_PARAMETRO,0) = 0
						SET @VALOR_PARAMETRO=@BASICO  
				END  
      
				IF @VALOR_PARAMETRO<>0  
					SET @VALOR_DEPENDENCIA =  
					CASE @OPERACION    
						WHEN '+' THEN @VALOR_DEPENDENCIA+(@VALOR_PARAMETRO*@FACTOR)  
						WHEN '-' THEN @VALOR_DEPENDENCIA-(@VALOR_PARAMETRO*@FACTOR)  
						WHEN '*' THEN @VALOR_DEPENDENCIA*(@VALOR_PARAMETRO*@FACTOR)  
						WHEN '/' THEN @VALOR_DEPENDENCIA/(@VALOR_PARAMETRO*@FACTOR)  
					END    
  
				FETCH NEXT FROM CUR_NCONDBD  
				INTO @FACTOR, @OPERACION, @PARAMETRO, @VALOR_PARAMETRO  
			END    
			CLOSE CUR_NCONDBD  
			DEALLOCATE CUR_NCONDBD  
		END  
		FETCH NEXT FROM CUR_NCONDB  
		INTO @PRIORIDAD_CUR, @DIAS1, @DIAS2, @OPERACION  
	END  
	CLOSE CUR_NCONDB  
	DEALLOCATE CUR_NCONDB  
  
	IF @VALOR_DEPENDENCIA>0  
	SET @BASICO=@VALOR_DEPENDENCIA  
  
	-- Verifica que el Concepto No se Liquida por Empleado, si no tiene el empleado lo busca por el Cargo.  
	IF @BASE=NULL OR EXISTS(SELECT CODCONCEPTO FROM NEMPE WHERE NUMDOC=@NUMDOC AND CODCONCEPTO=@CODCONCEPTO)  
	BEGIN    
		INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
		SELECT @DETALLE,0,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
		RETURN    
	END    
	ELSE  
		IF EXISTS(SELECT CODCONCEPTO FROM NCARNGE   
			WHERE CODCARGO=@CODCARGO AND NIVEL=@NIVEL AND GRADO=@GRADO AND CODCONCEPTO=@CODCONCEPTO)  
		BEGIN  
			INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
			SELECT @DETALLE,0,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
			RETURN    
		END  
  
	-- Estableciendo Tercero...  
	-- Asigna El Tercero segun el que tiene Empleado asignado con el concepto de Aporte
	SELECT TOP 1 @IDTERCERO = IDTERCERO  
	FROM NPRFED WHERE NUMDOC=@NUMDOC AND CODPRF=@CODPRF AND FECHAINI<=@FECHAFIN ORDER BY FECHAINI DESC  
	IF @CLASE = 'Aporte' AND @IDTERCERO IS NULL
	BEGIN
		INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
		SELECT 'Ap.No.Conf',0,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
		RETURN      
	END
	-- Asigna El Tercero segun el que tiene el concepto por default  
	IF ISNULL(@IDTERCERO,'')=''  
		SET @IDTERCERO = @IDTERCERO_DEFAULT  
	-- Asigna El Tercero segun el que tiene el grupo de concepto por default  
	IF ISNULL(@IDTERCERO,'')=''  
		SELECT TOP 1 @IDTERCERO = IDTERCERO    
		FROM NPRFD WHERE CODPRF=@CODPRF AND FECHAINI<=@FECHAFIN ORDER BY FECHAINI DESC  
	-- Asigna El Tercero como el Empleado  
	IF ISNULL(@IDTERCERO,'')=''  
		SET @IDTERCERO = @NUMDOC --NULL  
  
	SET @IDTRANSPRESTAMO_CUR = ''    
	SET @NUMDOCPRESTAMO_CUR  = ''    
	SET @NUMCUOTA_CUR        = 0    
	SET @CUOTASPGR           = 0    
	SET @CONCEPTO_CON_EVENTO = (SELECT COUNT(1) FROM NEVEC WHERE IDCONCEPTO=@CODCONCEPTO AND COALESCE(ACCION,'NA')='NA')
	IF ISNULL(@CONCEPTO_CON_EVENTO,0)=0
		SET @CONCEPTO_CON_EVENTO = (SELECT COUNT(1) FROM NEVE WHERE CODCONCEPTO=@CODCONCEPTO)
--  SET @HORAS_A_LABORAR     = @HORASXCARGO * (@DIASXPERIODO/@DIASXCARGO)  

	SET @HORAS_A_LABORAR     = @HORASXCARGO * (@DIAS_NPPAG/@DIASXCARGO)  


	/*JEDM  CALCULO DE VALOR HORA DE ACUERDO A NUEVO CAMPO EN NCOND TIPOVALORHORA*/
	IF @TIPOVALORHORA = 'Mes'
	BEGIN
		SET @VALOR_HORA          = @BASICO / 240.00    
	END
	ELSE
	BEGIN
		SET @VALOR_HORA          = @BASICO / @HORASXCARGO    
	END

	SET @VALOR_CALCULO100P   = @HORASXCARGO*@VALOR_HORA  
	SET @HORAS_SUMARESTA     = 0  

	-- Determinando las Horas Laboradsas  
	IF @VALHORASLAB = 1  
	BEGIN 
		IF @TIPOLIQ='PorNomina'    
			SELECT @HORAS_SUMARESTA = SUM(V.HORAS_DESCONTADAS) 
			FROM   
				(SELECT DISTINCT NEDIA.ITEM, HORAS_DESCONTADAS =   
					CASE WHEN NOT NOMIEVE.AFECTAHORAS IS NULL THEN   
						(NEDIA.HORAS+((NEDIA.MINUTOS+0.00)/60))*NOMIEVE.AFECTAHORAS ELSE  
						(NEDIA.HORAS+((NEDIA.MINUTOS+0.00)/60))*NEVE.AFECTAHORAS
					END
				 FROM NEDIA INNER JOIN   
					NEVE ON NEDIA.IDEVENTO=NEVE.IDEVENTO AND NEDIA.NUMDOC=@NUMDOC AND   
					((NEDIA.CNSPAGO=@CNSPAGO AND NEDIA.FORMALIQUIDACION='PorPago') OR  
					(NEDIA.FECHAINI>=@FECHAINI AND NEDIA.FECHAFIN<@FECHAFIN+1+CASE WHEN DAY(@FNPER)>30 THEN 1 ELSE 0 END AND  NEDIA.FORMALIQUIDACION='PorFecha')) LEFT JOIN  
					NOMIEVE ON NOMIEVE.IDEVENTO=NEVE.IDEVENTO AND NOMIEVE.CODNOMINA=@CODNOMINA  
					) AS V  
		ELSE  
			SELECT @HORAS_SUMARESTA = SUM(V.HORAS_DESCONTADAS)
			FROM   
			(SELECT DISTINCT NEDIA.ITEM, HORAS_DESCONTADAS = 
				CASE WHEN NOT NOMIEVE.AFECTAHORAS IS NULL THEN   
					(NEDIA.HORAS+((NEDIA.MINUTOS+0.00)/60))*NOMIEVE.AFECTAHORAS ELSE  
					(NEDIA.HORAS+((NEDIA.MINUTOS+0.00)/60))*NEVE.AFECTAHORAS
				END  
			FROM NPER INNER JOIN   
				NEDIA ON NPER.FECHAINI>=@FECHAINI AND NPER.FECHAFIN<@FECHAFIN+1+CASE WHEN DAY(@FNPER)>30 THEN 1 ELSE 0 END AND NEDIA.NUMDOC=@NUMDOC AND   
				((NEDIA.CNSPAGO=NPER.CNSPAGO AND NEDIA.FORMALIQUIDACION='PorPago') OR  
				(NEDIA.FECHAINI>=NPER.FECHAINI AND NEDIA.FECHAFIN<NPER.FECHAFIN+1 AND NEDIA.FORMALIQUIDACION='PorFecha')) INNER JOIN  
				NEVE ON NEDIA.IDEVENTO=NEVE.IDEVENTO LEFT JOIN  
				NOMIEVE ON NOMIEVE.IDEVENTO=NEVE.IDEVENTO AND NOMIEVE.CODNOMINA=@CODNOMINA  
				) AS V   

		SELECT @X1=0
		IF @HORAS_SUMARESTA IS NULL   
			SET @HORAS_SUMARESTA=0    
				--- OJO ACA FECHA DE RETIRO
			IF COALESCE(@FECHARETIRO,'01/01/2001')>=@FECHAINI
			BEGIN
				IF @FECHARETIRO<@FECHAFIN
				BEGIN			
					SELECT @X1=1 --,  @FECHARETIRO=DATEADD(DAY,1,@FECHARETIRO)
					SELECT @RESTARETIRO = ((DATEDIFF(DAY,@FECHARETIRO,@FECHAFIN) + CASE WHEN DAY(@FECHAFIN) <@DIAS_NPPAG THEN @DIAS_NPPAG-DAY(@FECHAFIN) ELSE 0 END) *@HORADIA)
					SELECT @HORAS_SUMARESTA = @HORAS_SUMARESTA+(@RESTARETIRO *-1)
				END
			END
			--REVISO NOVEDAD DE RETIRO
         
			IF EXISTS(SELECT * FROM NEDIA WHERE NUMDOC=@NUMDOC AND IDEVENTO='RET' AND CNSPAGO=@CNSPAGO) AND @X1=0
			BEGIN
				SELECT @HORAS_SUMARESTA=COALESCE(@HORAS_SUMARESTA,0)+CASE WHEN DAY(FECHAFIN)<>DAY(@FECHAFIN) THEN COALESCE(@HORAS_SUMARESTA,0)+(((DATEDIFF(DAY,FECHAFIN,@FECHAFIN) + CASE WHEN DAY(@FECHAFIN) <@DIAS_NPPAG THEN @DIAS_NPPAG-DAY(@FECHAFIN) ELSE 0 END) *@HORADIA)*-1) ELSE 0 END
				FROM NEDIA WHERE NUMDOC=@NUMDOC AND IDEVENTO='RET'
				AND  CNSPAGO=@CNSPAGO
			END
        
		DECLARE @HORASXDIA DECIMAL(14,2)
		SELECT TOP 1 @HORASXDIA =  (HORASDELABOR*1.00)/DIAS 
		FROM NCARNGV WHERE CODCARGO = @CODCARGO AND NIVEL = @NIVEL AND GRADO = @GRADO
		ORDER BY FECHA DESC

		IF @FECHAING>=@FECHAINI
		BEGIN
			SELECT TOP 1 @HORASXDIA =  (HORASDELABOR*1.00)/DIAS 
			FROM NCARNGV WHERE CODCARGO = @CODCARGO AND NIVEL = @NIVEL AND GRADO = @GRADO
			ORDER BY FECHA DESC
    
			SET @FECHAINGSIGMES = DATEADD(MONTH,1,@FECHAING)
			SET @FECHAINISIGMES = CAST('01/'+STR(MONTH(@FECHAINGSIGMES))+'/'+STR(YEAR(@FECHAINGSIGMES)) AS DATETIME)
      
			IF @FECHAINISIGMES > @FECHAFIN
				-- SET @HORASLAB = ((IIF(@DIAS_NPPAG<30,@DIAS_NPPAG,31)+@DNOV)-(DAY(@FECHAING))) *@HORADIA
				SET @HORASLAB=((DATEDIFF(DAY,@FECHAING-1,@FECHAFIN) + CASE WHEN DAY(@FECHAFIN) <@DIAS_NPPAG THEN @DIAS_NPPAG-DAY(@FECHAFIN) ELSE 0 END) *@HORADIA)

			ELSE
				SET @HORASLAB = (((@DIAS_NPPAG+@DNOV)-(DAY(@FECHAING)) + ((DATEDIFF(MONTH, @FECHAINISIGMES, @FECHAFIN)+1)*@DIAS_NPPAG))*@HORADIA)
		END
		ELSE
			SET @HORASLAB = @HORAS_A_LABORAR
     
			IF @HORAS_A_LABORAR - @HORASLAB > 0
				SET @HORAS_SUMARESTA = @HORAS_SUMARESTA - @HORAS_A_LABORAR + @HORASLAB 

	END  

	SET @HORAS_LABORADAS = @HORAS_A_LABORAR + @HORAS_SUMARESTA

	IF @HORAS_LABORADAS < 0
		SET @HORAS_LABORADAS = 0

	IF @HORAS_TCOMPLETO>0
		SET @HORAS_LABORADAS = CAST(@HORAS_LABORADAS / @HORAS_TCOMPLETO AS SMALLINT)*@HORAS_TCOMPLETO

   IF  @HORASXCARGO-@HORAS_LABORADAS <=1
   BEGIN
      SELECT @HORAS_LABORADAS=@HORASXCARGO
   END

	IF @BASE = 'Laborado'
		SELECT @PORCLABORADO  = (100*@HORAS_LABORADAS)/(@HORAS_NPPAG/(@HORAS_NPPAG/@HORAS_A_LABORAR))
	ELSE
		SET @PORCLABORADO  = 100


    
/*
	RETURN PARA HACER PRUEBAS Y REVISAR LOS DIAS LABORADOS Y LOS DIAS A LIQUIDAR
	OJO
*/
--INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
--SELECT '@HORASLAB  ='+CONVERT(VARCHAR,@HORASLAB),@PORCLABORADO,@HORAS_LABORADAS,@HORAS_NPPAG,NULL,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
--RETURN   
  
	-- Validar Tiempo Laborado del Periodo
	SET @SW = 0  
	IF @VALIDA_TLABORADOPER = 'Si'  
	BEGIN  
		SELECT @FTL =
		CASE @DMATLABORADOPER
			WHEN 'H' THEN 1
			WHEN 'D' THEN 8
			WHEN 'M' THEN 240
			WHEN 'A' THEN 2880
		END

		SET @SW =  
		CASE @CONDICION_TLABORADOPER
			WHEN '<'  THEN (CASE WHEN @HORAS_LABORADAS <  @HORAS_TLABORADOPER*@FTL THEN 1 ELSE 0 END)  
			WHEN '<=' THEN (CASE WHEN @HORAS_LABORADAS <= @HORAS_TLABORADOPER*@FTL THEN 1 ELSE 0 END)  
			WHEN '='  THEN (CASE WHEN @HORAS_LABORADAS =  @HORAS_TLABORADOPER*@FTL THEN 1 ELSE 0 END)  
			WHEN '>'  THEN (CASE WHEN @HORAS_LABORADAS >  @HORAS_TLABORADOPER*@FTL THEN 1 ELSE 0 END)  
			WHEN '>=' THEN (CASE WHEN @HORAS_LABORADAS >= @HORAS_TLABORADOPER*@FTL THEN 1 ELSE 0 END)  
			WHEN '<>' THEN (CASE WHEN @HORAS_LABORADAS <> @HORAS_TLABORADOPER*@FTL THEN 1 ELSE 0 END)  
		END

		IF @SW = 0  
		BEGIN  
			INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
			SELECT 'T.Laborado',@ANT,0,0,0,NULL,NULL,NULL,NULL,NULL,@ITEM_NCOND  
			RETURN    
		END    
	END  

	IF @CLASE='Manual'  
	BEGIN  
		INSERT INTO @TABLA(DETALLE, CANTIDAD, VALOR_EMPLEADO, VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
							NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES, ITEMCONCEPTO, BASE_CALCULO,   
							GENERANOVEFU, CODNOVEFU, MOSTRARHORAS)    
		SELECT V.DETALLE, V.CANTIDAD, ROUND(SUM(V.VALOR),@REDONDEO), ROUND(SUM(V.VALOR_EMPRESA),@REDONDEO),  
				CASE WHEN @TIPO='Ingreso' THEN ROUND(SUM(V.VALOR100P),@REDONDEO) ELSE 0 END,   
			V.IDTRANSPRESTAMO, V.NUMDOCPRESTAMO, V.NUMCUOTA, V.CODPRF, @IDTERCERO, @BASE_PRESTACIONES, @ITEM_NCOND,   
				ROUND(SUM(V.VALOR),@REDONDEO), @GENERANOVEFU, @CODNOVEFU, @MOSTRARHORAS  
		FROM NPERC AS V WHERE CNSPAGO=@CNSPAGO AND CODCONCEPTO=@CODCONCEPTO AND NUMDOC=@NUMDOC  
		GROUP BY V.DETALLE, V.CANTIDAD, V.IDTRANSPRESTAMO, V.NUMDOCPRESTAMO, V.NUMCUOTA ,V.CODPRF  
		RETURN  
	END  
  
	IF @BASE='Laborado'     
	BEGIN    
		SET @VALOR_CALCULO = @HORAS_LABORADAS*@VALOR_HORA
		SET @VALOR_CALCULO = @DIASXPERIODO*(@HORASXCARGO/@DIASXCARGO)*@VALOR_HORA*@PORCLABORADO*0.01
		SET @CANTIDAD      = @HORAS_LABORADAS
		SET @VALOR_HORA    = @VALOR_CALCULO/@HORASXCARGO
		   
		IF NOT (@CONCEPTO_CON_EVENTO IS NULL OR @CONCEPTO_CON_EVENTO=0 )  
		BEGIN    
			SELECT @VALOR_CALCULO     = VALOR_CALCULO,   
					@CANTIDAD          = CANTIDAD,   
					@VALOR_CALCULO100P = VALOR_CALCULO100P  
			FROM FNK_CALCULO_VLR_NOVEDAD_NOM(@CNSPAGO, @CODCONCEPTO, @NUMDOC, @FECHAINI, @FNOV, @VALOR_HORA)  
		END
  
		IF @TIPOCALCULO <> 'Porcentaje'  
		BEGIN  
			SET @VALOR         = @VALOR         * (@DIASXPERIODO/@DIASXCARGO)  
			SET @VALOR_EMPRESA = @VALOR_EMPRESA * (@DIASXPERIODO/@DIASXCARGO)  
		END
	END    
	ELSE    
	IF @BASE='Basico'    
	BEGIN    
		IF ISNULL(@CONCEPTO_CON_EVENTO,0) = 0  
		BEGIN    
			SET @VALOR_CALCULO    = @HORASXCARGO * @VALOR_HORA  
			SET @CANTIDAD         = @HORAS_NPPAG--@HORASXCARGO  
		END    
		ELSE    
		BEGIN    
			IF @TIPOLIQ='PorFechas' --Liquida Conceptos ya liquidados en un rango de fechas   
			BEGIN
				SELECT @VALOR_CALCULO = SUM(NEMPFD.VALOR)   
				FROM NCON INNER JOIN   
						NEMPF ON NCON.CODCONCEPTO=@CODCONCEPTO AND NEMPF.NUMDOC=@NUMDOC AND NCON.TIPO='Ingreso' INNER JOIN   
						NEMPFD ON NEMPF.CNSPAGO=NEMPFD.CNSPAGO AND NEMPFD.ITEM=NEMPF.ITEM AND NEMPF.NUMDOC=NEMPFD.NUMDOC AND  
								NEMPFD.CODCONCEPTO=NCON.CODCONCEPTO AND NEMPFD.BASE_PRESTACIONES='Si' AND NEMPFD.INFO='No' AND   
								NEMPFD.LIQUIDAR='Si' INNER JOIN  
						NPER ON NPER.CERRADO = 1 AND NEMPFD.CNSPAGO=NPER.CNSPAGO AND NPER.FECHAINI>=@FECHAINI AND NPER.FECHAFIN<=@FECHAFIN  
			END
			ELSE
			BEGIN
				SELECT @VALOR_CALCULO     = VALOR_CALCULO,   
						@CANTIDAD          = CANTIDAD,   
						@VALOR_CALCULO100P = VALOR_CALCULO100P  
				FROM FNK_CALCULO_VLR_NOVEDAD_NOM(@CNSPAGO, @CODCONCEPTO, @NUMDOC, @FECHAINI, @FNOV, @VALOR_HORA)  
 			END
		END  
      IF EXISTS(SELECT * FROM NEVEC INNER JOIN NEVE ON NEVEC.IDEVENTO=NEVE.IDEVENTO  WHERE IDCONCEPTO=@CODCONCEPTO AND COALESCE(ACCION,'NA')<>'NA' )
      BEGIN
         DECLARE @CODNEVEC VARCHAR(20)
         DECLARE @ACCIONEC VARCHAR(20)
         DECLARE @VALORNEC DECIMAL(14,2)
         SELECT @CODNEVEC=IDCONCEPTO,@ACCIONEC=ACCION FROM NEVEC INNER JOIN NEVE ON NEVEC.IDEVENTO=NEVE.IDEVENTO  WHERE IDCONCEPTO=@CODCONCEPTO AND COALESCE(ACCION,'NA')<>'NA'
         
         SELECT @VALORNEC     = VALOR_CALCULO 
		   FROM FNK_CALCULO_VLR_NOVEDAD_NOM(@CNSPAGO, @CODNEVEC, @NUMDOC, @FECHAINI, @FNOV, @VALOR_HORA) 
         IF @ACCIONEC='Suma'
         BEGIN
            SELECT @VALOR_CALCULO=@VALOR_CALCULO+COALESCE(@VALORNEC,0)
         END
         ELSE
         BEGIN
            SELECT @VALOR_CALCULO=@VALOR_CALCULO+COALESCE(@VALORNEC,0)
         END
      END      
		SET @PORCLABORADO = 100  
	END    
	ELSE    
	IF @BASE='BasePrestaciones'     
	BEGIN    
		IF @TIPOLIQ='PorNomina' --Liquida solo conceptos de la Nomina   
			SELECT @VALOR_CALCULO = SUM(NEMPFD_RUN.VALOR)   
			FROM NCON INNER JOIN   
				NEMPF ON NCON.CODCONCEPTO<>@CODCONCEPTO AND NEMPF.CNSPAGO=@CNSPAGO AND NEMPF.NUMDOC=@NUMDOC AND   
							NCON.TIPO='Ingreso' INNER JOIN   
				NEMPFD_RUN ON NEMPF.CNSPAGO=NEMPFD_RUN.CNSPAGO AND NEMPFD_RUN.ITEM=NEMPF.ITEM AND NEMPF.NUMDOC=NEMPFD_RUN.NUMDOC AND  
							NEMPFD_RUN.CODCONCEPTO=NCON.CODCONCEPTO AND NEMPFD_RUN.BASE_PRESTACIONES='Si' AND NEMPFD_RUN.INFO='No' AND   
							NEMPFD_RUN.LIQUIDAR='Si' AND NEMPFD_RUN.SYS_COMPUTERNAME=HOST_NAME() 
		ELSE  
		IF @TIPOLIQ='PorFechas' --Liquida Conceptos ya liquidados en un rango de fechas   
			SELECT @VALOR_CALCULO = SUM(NEMPFD_RUN.VALOR)   
			FROM NCON INNER JOIN   
				NEMPF ON NCON.CODCONCEPTO<>@CODCONCEPTO AND NEMPF.NUMDOC=@NUMDOC AND NCON.TIPO='Ingreso' INNER JOIN   
				NEMPFD_RUN ON NEMPF.CNSPAGO=NEMPFD_RUN.CNSPAGO AND NEMPFD_RUN.ITEM=NEMPF.ITEM AND NEMPF.NUMDOC=NEMPFD_RUN.NUMDOC AND  
							NEMPFD_RUN.CODCONCEPTO=NCON.CODCONCEPTO AND NEMPFD_RUN.BASE_PRESTACIONES='Si' AND NEMPFD_RUN.INFO='No' AND   
							NEMPFD_RUN.LIQUIDAR='Si' AND NEMPFD_RUN.SYS_COMPUTERNAME=HOST_NAME() INNER JOIN  
				NPER ON NEMPFD_RUN.CNSPAGO=NPER.CNSPAGO AND NPER.FECHAINI>=@FECHAINI AND NPER.FECHAFIN<=@FECHAFIN  
  
		IF ISNULL(@VALOR_CALCULO,0) = 0   
			SET @VALOR_HORA = 0  
		ELSE  
			SET @VALOR_HORA = @VALOR_CALCULO/@HORASXCARGO    
  
		IF ISNULL(@CONCEPTO_CON_EVENTO,0) = 0  
		BEGIN   
			SET @CANTIDAD          = @HORAS_LABORADAS  
			SET @VALOR_CALCULO100P = @VALOR_CALCULO  
		END  
		ELSE  
			SELECT @VALOR_CALCULO     = VALOR_CALCULO,   
					@CANTIDAD          = CANTIDAD,   
					@VALOR_CALCULO100P = VALOR_CALCULO100P  
			FROM FNK_CALCULO_VLR_NOVEDAD_NOM(@CNSPAGO, @CODCONCEPTO, @NUMDOC, @FECHAINI, @FNOV, @VALOR_HORA)  
  
		--SET @PORCLABORADO  = (100*@HORAS_LABORADAS)/@HORASXPERIODO  
  
		IF @TIPOCALCULO <> 'Porcentaje'  
		BEGIN  
			SET @VALOR         = @VALOR         * (@DIASXPERIODO/@DIASXCARGO)  
			SET @VALOR_EMPRESA = @VALOR_EMPRESA * (@DIASXPERIODO/@DIASXCARGO)  
		END 

	END  
	ELSE  
	IF @BASE='SalarioNeto'     
	BEGIN    
		IF @TIPOLIQ='PorNomina' --Liquida solo conceptos de la Nomina   
			SELECT @VALOR_CALCULO = SUM(CASE WHEN NCON.TIPO='Ingreso' THEN NEMPFD_RUN.VALOR ELSE NEMPFD_RUN.VALOR*-1 END)   
			FROM NCON INNER JOIN   
				NEMPF ON NCON.CODCONCEPTO<>@CODCONCEPTO AND NEMPF.CNSPAGO=@CNSPAGO AND NEMPF.NUMDOC=@NUMDOC INNER JOIN   
				NEMPFD_RUN ON NEMPF.CNSPAGO=NEMPFD_RUN.CNSPAGO AND NEMPFD_RUN.ITEM=NEMPF.ITEM AND NEMPF.NUMDOC=NEMPFD_RUN.NUMDOC AND  
							NEMPFD_RUN.CODCONCEPTO=NCON.CODCONCEPTO AND NEMPFD_RUN.INFO='No' AND NEMPFD_RUN.LIQUIDAR='Si' AND 
							NEMPFD_RUN.SYS_COMPUTERNAME=HOST_NAME() 
		ELSE  
		IF @TIPOLIQ='PorFechas' --Liquida Conceptos ya liquidados en un rango de fechas   
			SELECT @VALOR_CALCULO = SUM(CASE WHEN NCON.TIPO='Ingreso' THEN NEMPFD_RUN.VALOR ELSE NEMPFD_RUN.VALOR*-1 END)   
			FROM NCON INNER JOIN   
				NEMPF ON NCON.CODCONCEPTO<>@CODCONCEPTO AND NEMPF.NUMDOC=@NUMDOC INNER JOIN   
				NEMPFD_RUN ON NEMPF.CNSPAGO=NEMPFD_RUN.CNSPAGO AND NEMPFD_RUN.ITEM=NEMPF.ITEM AND NEMPF.NUMDOC=NEMPFD_RUN.NUMDOC AND  
							NEMPFD_RUN.CODCONCEPTO=NCON.CODCONCEPTO AND NEMPFD_RUN.INFO='No' AND NEMPFD_RUN.LIQUIDAR='Si' AND 
							NEMPFD_RUN.SYS_COMPUTERNAME=HOST_NAME() INNER JOIN  
				NPER ON NEMPFD_RUN.CNSPAGO=NPER.CNSPAGO AND NPER.FECHAINI>=@FECHAINI AND NPER.FECHAFIN<=@FECHAFIN 
  
		IF ISNULL(@VALOR_CALCULO,0) = 0   
			SET @VALOR_HORA = 0  
		ELSE  
			SET @VALOR_HORA = @VALOR_CALCULO/@HORASXCARGO
		IF ISNULL(@CONCEPTO_CON_EVENTO,0) = 0  
		BEGIN   
			SET @CANTIDAD          = @HORAS_LABORADAS  
			SET @VALOR_CALCULO100P = @VALOR_CALCULO  
		END  
		ELSE  
			SELECT @VALOR_CALCULO     = VALOR_CALCULO,   
					@CANTIDAD          = CANTIDAD,   
					@VALOR_CALCULO100P = VALOR_CALCULO100P  
			FROM FNK_CALCULO_VLR_NOVEDAD_NOM(@CNSPAGO, @CODCONCEPTO, @NUMDOC, @FECHAINI, @FNOV, @VALOR_HORA) 
		IF @TIPOCALCULO <> 'Porcentaje'  
		BEGIN  
			SET @VALOR         = @VALOR         * (@DIASXPERIODO/@DIASXCARGO)  
			SET @VALOR_EMPRESA = @VALOR_EMPRESA * (@DIASXPERIODO/@DIASXCARGO)  
		END  
	END  
	ELSE 

	--query2  
	IF @BASE='Conceptos'  
	BEGIN  
		SELECT @VALOR_CALCULO = DBO.FNK_VALOR_NCONDC_RUN(@NUMDOC, @CODCONCEPTO, @ITEM_NCOND, @FECHAINI, @FNPER, @CNSPAGO)  
  
		IF ISNULL(@VALOR_CALCULO,0) = 0   
			SET @VALOR_HORA = 0  
		ELSE  
			SET @VALOR_HORA = @VALOR_CALCULO/@HORASXCARGO    
  
		IF ISNULL(@CONCEPTO_CON_EVENTO,0) = 0  
		BEGIN   
			SET @CANTIDAD          = @HORAS_LABORADAS  
			SET @VALOR_CALCULO100P = @VALOR_CALCULO  
		END  
		ELSE  
			SELECT @VALOR_CALCULO     = VALOR_CALCULO,   
					@CANTIDAD          = CANTIDAD,   
					@VALOR_CALCULO100P = VALOR_CALCULO100P  
			FROM FNK_CALCULO_VLR_NOVEDAD_NOM(@CNSPAGO, @CODCONCEPTO, @NUMDOC, @FECHAINI, @FNOV, @VALOR_HORA)  
  
		--SET @PORCLABORADO  = (100*@HORAS_LABORADAS)/@HORASXPERIODO  
  
		IF @TIPOCALCULO <> 'Porcentaje'  
		BEGIN  
			SET @VALOR         = @VALOR         * (@DIASXPERIODO/@DIASXCARGO)  
			SET @VALOR_EMPRESA = @VALOR_EMPRESA * (@DIASXPERIODO/@DIASXCARGO)  
		END  
	END  
	ELSE  
	IF @BASE='Formula'  
	BEGIN
		DECLARE CUR_NCONDF CURSOR FOR  
		SELECT CODCONCEPTO_OPE,   
				CASE WHEN NPER.CNSPAGO IS NULL THEN @CNSPAGO ELSE NPER.CNSPAGO END,   
				CASE WHEN NPER.CNSPAGO IS NULL THEN @FECHAINI ELSE NPER.FECHAINI END,  
				CASE WHEN NPER.CNSPAGO IS NULL THEN @FECHAFINPER ELSE NPER.FECHAFIN END,   
				PRIORIDAD, FACTOR, OPERACION, SOLICITA_CNSPAGO, ISNULL(REQUIERELIQ,0), ISNULL(VALHORASLAB,0), NCONDF.HORAS, ISNULL(NCONDF.DIAS,0)
		FROM NCONDF LEFT JOIN   
			NPER ON NPER.CNSPAGO=NCONDF.CNSPAGO   
		WHERE NCONDF.CODCONCEPTO=@CODCONCEPTO AND NCONDF.ITEM=@ITEM_NCOND  
		ORDER BY NCONDF.PRIORIDAD  
  
		OPEN CUR_NCONDF  
  
		SET @VALOR_CALCULO=0  
  
		FETCH NEXT FROM CUR_NCONDF  
		INTO @CODCONCEPTO_CUR, @CNSPAGO_CUR, @FECHAINI_CUR, @FECHAFIN_CUR, @PRIORIDAD_CUR,   
			@FACTOR_CUR, @OPERACION, @SOLICITA_CNSPAGO, @REQUIERELIQ_NCONDF, @VALHORASLAB_NCONDF, @HORAS_NCONDF, @DIAS_NCONDF  
		WHILE @@FETCH_STATUS = 0  
		BEGIN  
			SET @VALOR_CONCEPTO = 0  
			IF ISNULL(@CODCONCEPTO_CUR,'')<>''
			BEGIN
				IF @SOLICITA_CNSPAGO='Si'  
				BEGIN  
					SELECT @VALOR_CONCEPTO = ISNULL(SUM(VALOR),0)    
					FROM NEMPFD   
					WHERE CODCONCEPTO=@CODCONCEPTO_CUR AND CNSPAGO=@CNSPAGO_CUR AND NUMDOC=@NUMDOC AND  
						INFO='No' AND LIQUIDAR='Si'  
					IF @VALHORASLAB_NCONDF = 1
						SET @VALOR_CONCEPTO = @PORCLABORADO * @VALOR_CONCEPTO * 0.01
				END  
				ELSE   
				BEGIN  
					IF @REQUIERELIQ_NCONDF = 1  
					BEGIN  
						IF @TIPOLIQ='PorNomina' --Liquida solo conceptos de la Nomina   
							SELECT @VALOR_CONCEPTO = SUM(NEMPFD.VALOR)   
							FROM NEMPFD_RUN NEMPFD INNER JOIN
								NPER ON NEMPFD.CNSPAGO = NPER.CNSPAGO
							WHERE NEMPFD.CNSPAGO=@CNSPAGO AND NEMPFD.NUMDOC=@NUMDOC AND NEMPFD.INFO='No' AND NEMPFD.LIQUIDAR='Si' AND
									NEMPFD.CODCONCEPTO = @CODCONCEPTO_CUR AND NEMPFD.SYS_COMPUTERNAME=HOST_NAME()
						ELSE  
							IF @TIPOLIQ='PorFechas' --Liquida Conceptos ya liquidados en un rango de fechas   
								SELECT @VALOR_CONCEPTO = SUM(NEMPFD.VALOR)   
								FROM NEMPFD INNER JOIN
									NPER ON NEMPFD.CNSPAGO = NPER.CNSPAGO
								WHERE NEMPFD.NUMDOC=@NUMDOC AND NEMPFD.INFO='No' AND NEMPFD.LIQUIDAR='Si' AND
									NEMPFD.CODCONCEPTO = @CODCONCEPTO_CUR AND NPER.CERRADO = 1 AND 
									NPER.FECHAFIN BETWEEN @FECHAINI AND @FECHAFIN                --NPER.FECHAINI>=@FECHAINI AND NPER.FECHAFIN<=@FECHAFIN  
					END  
					ELSE  
						SELECT @VALOR_CONCEPTO = V.VALOR_EMPLEADO  
						FROM FNK_VALORCONCEPTO_NEMPFD_RUN(@NUMDOC,@CODCONCEPTO_CUR,@FECHAINI_CUR,@FECHAFIN_CUR,@CNSPAGO_CUR,@VALHORASLAB_NCONDF, @HORAS_NCONDF, @DIAS_NCONDF) AS V  
				END  
			END
			ELSE
				SET @VALOR_CONCEPTO = 1

			IF @VALOR_CONCEPTO IS NULL   
				SET @VALOR_CONCEPTO = 0  
  
			SET @VALOR_CALCULO =   
				CASE @OPERACION    
					WHEN '+' THEN @VALOR_CALCULO+(@VALOR_CONCEPTO*@FACTOR_CUR)  
					WHEN '-' THEN @VALOR_CALCULO-(@VALOR_CONCEPTO*@FACTOR_CUR)  
					WHEN '*' THEN @VALOR_CALCULO*(@VALOR_CONCEPTO*@FACTOR_CUR)  
					WHEN '/' THEN @VALOR_CALCULO/(@VALOR_CONCEPTO*@FACTOR_CUR)  
				END    
  
			FETCH NEXT FROM CUR_NCONDF  
			INTO @CODCONCEPTO_CUR, @CNSPAGO_CUR, @FECHAINI_CUR, @FECHAFIN_CUR, @PRIORIDAD_CUR,   
				@FACTOR_CUR, @OPERACION, @SOLICITA_CNSPAGO, @REQUIERELIQ_NCONDF, @VALHORASLAB_NCONDF, @HORAS_NCONDF, @DIAS_NCONDF
		END  
		CLOSE CUR_NCONDF  
		DEALLOCATE CUR_NCONDF  

		IF ISNULL(@VALOR_CALCULO,0) = 0   
			SET @VALOR_HORA = 0  
		ELSE  
			SET @VALOR_HORA = @VALOR_CALCULO/@HORASXCARGO    
  
		IF ISNULL(@CONCEPTO_CON_EVENTO,0) = 0  
		BEGIN   
			SET @CANTIDAD          = @HORAS_LABORADAS  
			SET @VALOR_CALCULO100P = @VALOR_CALCULO  
		END  
		ELSE  
			SELECT @VALOR_CALCULO     = VALOR_CALCULO,   
					@CANTIDAD          = CANTIDAD,   
					@VALOR_CALCULO100P = VALOR_CALCULO100P  
			FROM FNK_CALCULO_VLR_NOVEDAD_NOM(@CNSPAGO, @CODCONCEPTO, @NUMDOC, @FECHAINI, @FNOV, @VALOR_HORA)  
  
		IF @TIPOCALCULO <> 'Porcentaje'  
		BEGIN  
			SET @VALOR         = @VALOR         * (@DIASXPERIODO/@DIASXCARGO)  
			SET @VALOR_EMPRESA = @VALOR_EMPRESA * (@DIASXPERIODO/@DIASXCARGO)  
		END  
  
		--  INSERT INTO @TABLA(DETALLE, CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
		--       NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES)    
		--  SELECT 'HORAS', @HORAS_LABORADAS, @VALOR_CALCULO ,@PORCLABORADO, 0, 0, 0, 0, 0, 0, 0  
		--  RETURN   
  
	END  
	ELSE  
	IF @BASE='Cuota' --AND @CLASE='Prestamo'  
	BEGIN ---10    
		SET @CUOTASPGR     = 0    
		SET @VALOR_CALCULO = 0    
		SET @CANTIDAD      = 0  
	-------------------------------------------------------------------------------------------    
	--- VERIFICAR SI HAY PRESTAMOS POR PAGAR    
	------------------------------------------------------------------------------------------    
		SELECT @CUOTASPGR = COUNT(*) FROM PRSD INNER JOIN PRS ON    
			PRS.NUMDOCUMENTO=PRSD.NUMDOCUMENTO AND PRS.IDTRANSACCION=PRSD.IDTRANSACCION    
		WHERE PRS.IDDEUDOR=@NUMDOC AND PRS.ESTADO='PorPagar' AND PRS.CODCONCEPTO=@CODCONCEPTO AND     
			PRSD.FECHAPAGO>=@FECHAINI AND PRSD.FECHAPAGO<=@FECHAFIN AND  PRSD.ESTADO='PorPagar'    
	-------------------------------------------------------------------------------------------    
	--- SI HAY COUTAS    
	------------------------------------------------------------------------------------------    
		IF @CUOTASPGR > 0     
		BEGIN  
			DECLARE CUR_NPRES CURSOR FOR    
			SELECT PRSD.IDTRANSACCION, PRSD.NUMDOCUMENTO, PRSD.VLRCUOTA, PRSD.NUMCUOTA, PRS.IDPRESTADOR  
			FROM PRSD INNER JOIN PRS ON    
				PRS.NUMDOCUMENTO=PRSD.NUMDOCUMENTO AND PRS.IDTRANSACCION=PRSD.IDTRANSACCION    
			WHERE PRS.IDDEUDOR=@NUMDOC AND PRS.ESTADO='PorPagar' AND PRS.CODCONCEPTO=@CODCONCEPTO AND     
				PRSD.FECHAPAGO>=@FECHAINI AND PRSD.FECHAPAGO<=@FECHAFIN AND PRSD.ESTADO='PorPagar'    
			OPEN CUR_NPRES    
			FETCH NEXT FROM CUR_NPRES    
			INTO @IDTRANSPRESTAMO_CUR, @NUMDOCPRESTAMO_CUR, @VLRCUOTA_CUR, @NUMCUOTA_CUR, @IDTERCERO  
			WHILE @@FETCH_STATUS = 0    
			BEGIN      
				INSERT INTO @TABLA(DETALLE, CANTIDAD, VALOR_EMPLEADO, VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO,   
									NUMDOCPRESTAMO, NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES, ITEMCONCEPTO ,BASE_CALCULO,  
									GENERANOVEFU, CODNOVEFU, MOSTRARHORAS)    
				SELECT @DETALLE, 0, ROUND((@VLRCUOTA_CUR*@VALOR*0.01),@REDONDEO), ROUND((@VLRCUOTA_CUR*@VALOR_EMPRESA*0.01),@REDONDEO),   
						CASE WHEN @TIPO='Ingreso' THEN ROUND(@VLRCUOTA_CUR,0) ELSE 0 END, @IDTRANSPRESTAMO_CUR,   
						@NUMDOCPRESTAMO_CUR, @NUMCUOTA_CUR ,@CODPRF, @IDTERCERO, @BASE_PRESTACIONES, @ITEM_NCOND,   
						ROUND((@VLRCUOTA_CUR*@VALOR*0.01),@REDONDEO), @GENERANOVEFU, @CODNOVEFU, @MOSTRARHORAS  
				FETCH NEXT FROM CUR_NPRES    
				INTO @IDTRANSPRESTAMO_CUR, @NUMDOCPRESTAMO_CUR, @VLRCUOTA_CUR, @NUMCUOTA_CUR, @IDTERCERO  
			END       
			CLOSE CUR_NPRES    
			DEALLOCATE CUR_NPRES    
		END    
		RETURN    
	END ---10
  
  
  /**
  JJIMENEZ 17/02/2024
   SE COMENTARIZA, DEBIDO A QUE NO HACIA LA VALIDACION DEL CONCEPTO SI DA NEGATIVO Y ES FORMULA SE NECESITA LA VALIDACION

	--IF ISNULL(@VALOR_CALCULO,0)<=0  
	--BEGIN  
	--	INSERT INTO @TABLA(DETALLE,CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,ITEMCONCEPTO)    
	--	SELECT 'Valor<=0',0,@VALOR_CALCULO,0,0,NULL,NULL,NULL,NULL,@CODCONCEPTO,@ITEM_NCOND  
	--	RETURN    
	--END   
  **/
-------------------------------------------------------------------------------------------    
--- CALCULOS DEL SUBSIDIO SEGUN PARIENTES  
------------------------------------------------------------------------------------------    
	IF @CLASE='Familiares'
	BEGIN  
		DECLARE CUR_NCONDS CURSOR FOR    
		SELECT IDPARENTESCO,SEXO,EDADMIN,EDADMAX,ESTADO_PARIENTE,FACTOR,OPERACION,MAXIMO,ESTUDIANTE,NIVELESTUDIOS  
		FROM NCONDS    
		WHERE CODCONCEPTO=@CODCONCEPTO AND ITEM_NCOND=@ITEM_NCOND    
		SET @VALOR_DEPENDENCIA=0    
  
		OPEN CUR_NCONDS    
  
		FETCH NEXT FROM CUR_NCONDS    
		INTO @IDPARENTESCO,@SEXO,@EDADMIN,@EDADMAX,@ESTADO_PARIENTE,@FACTOR,@OPERACION,@MAXIMO,@ESTUDIANTE,@NIVELESTUDIOS  
		SET @VALOR_PARIENTES=0  
		SET @CANT_PARIENTES=0  
		WHILE @@FETCH_STATUS = 0     
		BEGIN      
			SELECT @CANT_PARIENTES=COUNT(*) FROM NEMPP   
			WHERE NUMDOC=@NUMDOC AND IDPARENTESCO=@IDPARENTESCO AND SEXO=(CASE WHEN @SEXO='Ambos' THEN SEXO ELSE @SEXO END) AND  
				DATEDIFF(YEAR,FNACIMIENTO,@FECHAINI)>=@EDADMIN AND DATEDIFF(YEAR,FNACIMIENTO,@FECHAFIN)<(CASE WHEN @EDADMAX=0 THEN 150 ELSE @EDADMAX END) AND  
				ESTADO=@ESTADO_PARIENTE AND ESTUDIANTE=(CASE WHEN @ESTUDIANTE='NA' THEN ESTUDIANTE ELSE @ESTUDIANTE END) AND  
				NIVELESTUDIOS=@NIVELESTUDIOS

			IF @MAXIMO>0 AND @CANT_PARIENTES>@MAXIMO  
				SET @CANT_PARIENTES=@MAXIMO
				
			SET @VALOR_PARIENTES=  
			CASE @OPERACION    
				WHEN '+' THEN @VALOR_PARIENTES+(@VALOR*@CANT_PARIENTES*@FACTOR)  
				WHEN '-' THEN @VALOR_PARIENTES-(@VALOR*@CANT_PARIENTES*@FACTOR)  
				WHEN '*' THEN @VALOR_PARIENTES*(@VALOR*@CANT_PARIENTES*@FACTOR)  
				WHEN '/' THEN @VALOR_PARIENTES/(@VALOR*@CANT_PARIENTES*@FACTOR)  
			END    
			FETCH NEXT FROM CUR_NCONDS    
			INTO @IDPARENTESCO,@SEXO,@EDADMIN,@EDADMAX,@ESTADO_PARIENTE,@FACTOR,@OPERACION,@MAXIMO,@ESTUDIANTE,@NIVELESTUDIOS  
		END    
		CLOSE CUR_NCONDS    
		DEALLOCATE CUR_NCONDS  
		SET @VALOR             = @VALOR_PARIENTES  
		SET @VALOR_EMPRESA     = 0  
		SET @VALOR_CALCULO100P = @VALOR  
	END  
  
	IF @CLASE='Particular'   
	BEGIN ---10    
		DECLARE @VALOR_PART       DECIMAL(15,6)  
		DECLARE @TIPOCALCULO_PART VARCHAR(12)  
		DECLARE @IDTERCERO_PART   VARCHAR(20)  
		DECLARE @VALOR_BK         DECIMAL(15,6)  
		DECLARE @VALOR100P_BK     DECIMAL(15,6)  
  
		DECLARE CUR_PART CURSOR FOR    
		SELECT VALOR, TIPOCALCULO, IDTERCERO  
		FROM NEMPDA 
		WHERE NUMDOC=@NUMDOC AND CODCONCEPTO = @CODCONCEPTO AND 
				@FECHAFIN BETWEEN ISNULL(FECHAINI,@FECHAFIN) AND ISNULL(FECHAFIN,@FECHAFIN)
  
		OPEN CUR_PART  
  
		SET @VALOR_BK     = @VALOR  
		SET @VALOR100P_BK = @VALOR100P  
  
		FETCH NEXT FROM CUR_PART  
		INTO @VALOR_PART, @TIPOCALCULO_PART, @IDTERCERO_PART  
		WHILE @@FETCH_STATUS = 0    
		BEGIN      
			SET @VALOR     = @VALOR_BK  
			SET @VALOR100P = @VALOR100P_BK  
			IF @TIPOCALCULO_PART = 'Valor'  
				SET @VALOR = (@PORCLABORADO / @VALOR_CALCULO) * @VALOR_PART  
			ELSE    
				IF @TIPOCALCULO = 'Porcentaje'  
				SET @VALOR     = @VALOR_PART * @VALOR * 0.01  
  
			GOTO CALCULOS  
			INST_PARTICULAR:  
  
			INSERT INTO @TABLA(DETALLE, CANTIDAD, VALOR_EMPLEADO, VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
								NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES, ITEMCONCEPTO, BASE_CALCULO, GENERANOVEFU,   
								CODNOVEFU, MOSTRARHORAS)    
			SELECT @DETALLE, @CANTIDAD, ROUND(@VALOR+(CASE WHEN @VALOR>0.00 THEN @MAS_REDONDEO ELSE 0 END) ,@REDONDEO) ,ROUND(@VALOR_EMPRESA+(CASE WHEN @VALOR_EMPRESA>0.00 THEN @MAS_REDONDEO ELSE 0 END) ,@REDONDEO), @VALOR100P,   
					@IDTRANSPRESTAMO_CUR, @NUMDOCPRESTAMO_CUR, @NUMCUOTA_CUR, @CODPRF,   
					CASE WHEN ISNULL(@IDTERCERO_PART,'')='' THEN @IDTERCERO ELSE @IDTERCERO_PART END,   
					@BASE_PRESTACIONES, @ITEM_NCOND, @VALOR_CALCULO, @GENERANOVEFU, @CODNOVEFU, @MOSTRARHORAS  
  
			FETCH NEXT FROM CUR_PART  
			INTO @VALOR_PART, @TIPOCALCULO_PART, @IDTERCERO_PART  
		END    
		CLOSE CUR_PART  
		DEALLOCATE CUR_PART  
  
		RETURN    
	END ---10    
 
 
	SELECT @FECHAINILIQ=DATEADD(YEAR,-1,NPER.FECHAINI), @FECHAFINLIQ=NPER.FECHAINI, @DIASCAL=NEDIA.DIAS
	FROM NEMPVD
		INNER JOIN NEMPV ON NEMPV.NUMDOC=NEMPVD.NUMDOC AND NEMPV.ITEM=NEMPVD.ITEM
		INNER JOIN NPER ON NPER.CNSPAGO=NEMPVD.CNSPAGO
		INNER JOIN NEDIA ON NEDIA.CNSPAGO=NEMPVD.CNSPAGO AND NEMPVD.CNSNEMPVD=NEDIA.CNSVAC
	WHERE NEDIA.CNSPAGO=@CNSPAGO AND NEDIA.NUMDOC=@NUMDOC AND NEDIA.IDEVENTO IN (SELECT IDEVENTO FROM NEVE WHERE CODCONCEPTO=@CODCONCEPTO)

 
	IF EXISTS (SELECT 1 FROM TGEN WHERE TABLA='NOMINA' AND CAMPO='EVENTOVACA' AND CODIGO IN (SELECT IDEVENTO FROM NEVE WHERE CODCONCEPTO=@CODCONCEPTO))
	BEGIN
		IF DBO.FNK_VALORVARIABLE('PERIODO_PRESTA_NOM')='FECHAS'
		BEGIN
			SELECT @VALORD=(COALESCE(SUM(NIEPED.VALOR),0)/360)*@DIASCAL
			FROM NIEPE INNER JOIN NIEPED ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC
			WHERE NIEPE.NUMDOC=@NUMDOC 
				AND  CAST('01/'+MES+'/'+ANO AS DATETIME)>=@FECHAINILIQ
				AND  CAST('01/'+MES+'/'+ANO AS DATETIME)<@FECHAFINLIQ
				AND COALESCE(NIEPED.PAGADO,0)=0 
				AND NIEPED.CODCONCEPTO IN(SELECT CODCONCEPTOA FROM NCONDA WHERE CODCONCEPTO=@CODCONCEPTO)
			
			SELECT @VALOR_CALCULO+=	@VALORD,@VALOR_CALCULO100P+=@VALORD
		END
	END

	DECLARE @IDNOVEDADVACSIGMES AS VARCHAR(10)
	SELECT @IDNOVEDADVACSIGMES=DBO.FNK_VALORVARIABLE('IDNOVEDADVACSIGMES')

	IF (SELECT TOP 1 IDEVENTO FROM NEVE WHERE CODCONCEPTO=@CODCONCEPTO)=@IDNOVEDADVACSIGMES
	BEGIN
		SELECT @DIASCAL=NEDIA.DIAS FROM NEDIA WHERE CNSPAGO=@CNSPAGO AND NEDIA.NUMDOC=@NUMDOC AND NEDIA.IDEVENTO=@IDNOVEDADVACSIGMES
		IF DBO.FNK_VALORVARIABLE('PERIODO_PRESTA_NOM')='FECHAS'
		BEGIN
			SELECT @VALORD=(COALESCE(SUM(NIEPED.VALOR),0)/360)*@DIASCAL
			FROM NIEPE INNER JOIN NIEPED ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC
			WHERE NIEPE.NUMDOC=@NUMDOC 
			AND  CAST('01/'+MES+'/'+ANO AS DATETIME)>=@FECHAINILIQ
			AND  CAST('01/'+MES+'/'+ANO AS DATETIME)<@FECHAFINLIQ
			AND COALESCE(NIEPED.PAGADO,0)=0 
			AND NIEPED.CODCONCEPTO IN(SELECT CODCONCEPTOA FROM NCONDA WHERE CODCONCEPTO=@CODCONCEPTO)
			
			SELECT @VALOR_CALCULO+=	@VALORD,@VALOR_CALCULO100P+=@VALORD
		END
	END



	CALCULOS:  
-------------------------------------------------------------------------------------------    
--- INICIO DE CALCULOS    
------------------------------------------------------------------------------------------    
--  INSERT INTO @TABLA(DETALLE, CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA, IDTRANSPRESTAMO, NUMDOCPRESTAMO, NUMCUOTA, CODPRF, IDTERCERO)    
--  SELECT @DETALLE, @CANTIDAD, @VALOR_CALCULO ,@VALOR, @IDTRANSPRESTAMO_CUR, @NUMDOCPRESTAMO_CUR, @NUMCUOTA_CUR, @CODPRF, @IDTERCERO  
--  RETURN    
  
	-- Busca valores o Porcentaje para aplicar deacuerdo a @VALOR   
	IF @CLASE='Tabla'    
	BEGIN    
		SET @VALOR_A =   
		CASE @VALIDATABLA  
			WHEN 'Base' THEN @VALOR_CALCULO  
			WHEN 'Basico' THEN @BASICO  
			WHEN 'Antiguedad' THEN DBO.FNK_ANTIGUEDAD(@FECHAING,@FECHAFIN+1,@DMATABLA)  
			WHEN 'Edad' THEN DBO.FNK_ANTIGUEDAD(@FNACIMIENTO,@FECHAFIN+1,@DMATABLA)  
			WHEN 'Horas' THEN @HORAS_LABORADAS  
			WHEN 'Conceptos' THEN DBO.FNK_VALOR_NCONDTC_RUN(@NUMDOC, @CODCONCEPTO, @ITEM_NCOND, @FECHAINI, @FECHAFINPER, @CNSPAGO)  
		END  
  
		SELECT TOP 1   
		@VALOR_TABLA  = ISNULL(CASE NCONTDV.TIPOCALCULO  
								WHEN 'Porcentaje' THEN NCONTDV.PORCENTAJE  
								WHEN 'Valor'      THEN NCONTDV.VALOR    
								END,0),  
		@TIPOCALCULO2 = NCONTDV.TIPOCALCULO  
		FROM NCOND INNER JOIN   
			NCONTD ON NCONTD.TIPOTABLA=NCOND.TIPOTABLA INNER JOIN   
			NCONTDV ON NCONTD.TIPOTABLA=NCONTDV.TIPOTABLA AND NCONTD.ITEM=NCONTDV.ITEM  
		WHERE NCONTD.FECHAINI<=@FECHAINI AND NCONTDV.VALORINICIAL<=@VALOR_A AND   
			NCOND.CODCONCEPTO=@CODCONCEPTO AND NCOND.ITEM=@ITEM_NCOND   
		ORDER BY NCONTD.FECHAINI DESC, NCONTDV.VALORINICIAL DESC  
  
	  --INSERT INTO @TABLA(DETALLE, CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
	  --     NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES)    
	  --SELECT 'TABLA 1', @VALOR_A, @VALOR_TABLA ,@VALOR, @VALOR_CALCULO, 0, 0, 0, 0, 0, 0  
	  --RETURN   
  
		SET @VALOR =   
			CASE @TIPOCALCULO2  
				WHEN 'Porcentaje' THEN @VALOR*@VALOR_TABLA*0.01  
				WHEN 'Valor'      THEN  @VALOR_TABLA  
			END  
		--INSERT INTO @TABLA(DETALLE, CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
		--     NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES)    
		--SELECT 'TABLA FIN', @VALOR_A, @VALOR_TABLA ,@VALOR, 0, 0, 0, 0, 0, 0, 0     
	END    -- TERMINA TABLA
  
--  INSERT INTO @TABLA(DETALLE, CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
--       NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES)    
--  SELECT 'TABLA 2', @VALOR_A, @VALOR_TABLA ,@VALOR, 0, 0, 0, 0, 0, 0, 0  
-- RETURN   
 
	IF @TIPO='Ingreso'  
	BEGIN  
		SET @VALOR100P =     
			CASE @TIPOCALCULO     
				WHEN 'Valor'      THEN @VALOR  
				WHEN 'Porcentaje' THEN @VALOR_CALCULO100P*@VALOR*0.01  
			END    
	END  
	ELSE  
		SET @VALOR100P = 0  
  
	--INSERT INTO @TABLA(DETALLE, CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
	--     NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES)    
	--SELECT 'ANTES UPDATE '+@TIPOCALCULO, @VALOR_A, @VALOR_TABLA ,@VALOR, 0, 0, 0, 0, 0, 0, 0  

	SET @VALOR =     
		CASE @TIPOCALCULO     
			WHEN 'Valor'      THEN @VALOR * @PORCLABORADO  * 0.01  
			WHEN 'Porcentaje' THEN @VALOR * @VALOR_CALCULO * 0.01   
		END    

	--INSERT INTO @TABLA(DETALLE, CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
	--     NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES)    
	--SELECT 'SEGUNDO UPDATE '+@TIPOCALCULO, @VALOR_A, @VALOR_TABLA ,@VALOR, 0, 0, 0, 0, 0, 0, 0     
  
	SET @VALOR_EMPRESA =     
		CASE @TIPOCALCULO     
			WHEN 'Valor'      THEN @VALOR_EMPRESA*@PORCLABORADO*0.01    
			WHEN 'Porcentaje' THEN @VALOR_EMPRESA*@VALOR_CALCULO*0.01    
		END    
  
--  INSERT INTO @TABLA(DETALLE, CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
--       NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES)    
--  SELECT 'TABLA', @VALOR_A, @VALOR_TABLA ,@VALOR, 0, 0, 0, 0, 0, 0, 0  
--  RETURN   

  
	IF @CONDICION<>'NA'    
	BEGIN  ---20    
		IF @EVALUAR='Resultado'
			SET @VALOR_EVALUAR=@VALOR    
		IF @EVALUAR='Basico'    
			SET @VALOR_EVALUAR=@SALARIOBASICO  
		ELSE    
			SET @VALOR_EVALUAR=@VALOR_CALCULO    
  

		DECLARE CUR_NCONDD CURSOR FOR    
		SELECT TIPODEPENDENCIA, CODDEPENDENCIA, FACTOR, OPERACION, ISNULL(REQUIERELIQ,0), ISNULL(VALHORASLAB,0), HORAS, DIAS,FACTORMAX
		FROM NCONDD 
		WHERE CODCONCEPTO=@CODCONCEPTO AND ITEM_NCOND=@ITEM_NCOND
		
		SELECT @VALOR_DEPENDENCIA=0, @VALORMAXIMO=0
		OPEN CUR_NCONDD    
		FETCH NEXT FROM CUR_NCONDD    
		INTO @TIPODEPENDENCIA, @CODDEPENDENCIA, @FACTOR, @OPERACION, @REQUIERELIQ_NCONDD, @VALHORASLAB_NCONDD, @HORAS_NCONDD, @DIAS_NCONDD,@FACTORMAX 
		WHILE @@FETCH_STATUS = 0     
		BEGIN      
			IF @TIPODEPENDENCIA='Parametro'    
			BEGIN    
				SELECT @VALOR_DEPENDENCIA= CASE @OPERACION    
												WHEN '+' THEN @VALOR_DEPENDENCIA+(DBO.FNK_CALCULO_VALORPARAMETRO_NOM( @CODDEPENDENCIA,@FECHAINI,@FECHAFIN)*@FACTOR)    
												WHEN '-' THEN @VALOR_DEPENDENCIA-(DBO.FNK_CALCULO_VALORPARAMETRO_NOM( @CODDEPENDENCIA,@FECHAINI,@FECHAFIN)*@FACTOR)    
												WHEN '*' THEN @VALOR_DEPENDENCIA*(DBO.FNK_CALCULO_VALORPARAMETRO_NOM( @CODDEPENDENCIA,@FECHAINI,@FECHAFIN)*@FACTOR)    
												WHEN '/' THEN @VALOR_DEPENDENCIA/(DBO.FNK_CALCULO_VALORPARAMETRO_NOM( @CODDEPENDENCIA,@FECHAINI,@FECHAFIN)*@FACTOR)    
											END 
				IF COALESCE(@FACTORMAX,0)>0
				BEGIN
					SELECT @VALORMAXIMO=CASE @OPERACION    
												WHEN '+' THEN @VALORMAXIMO+(DBO.FNK_CALCULO_VALORPARAMETRO_NOM( @CODDEPENDENCIA,@FECHAINI,@FECHAFIN)*@FACTORMAX)    
												WHEN '-' THEN @VALORMAXIMO-(DBO.FNK_CALCULO_VALORPARAMETRO_NOM( @CODDEPENDENCIA,@FECHAINI,@FECHAFIN)*@FACTORMAX)    
												WHEN '*' THEN @VALORMAXIMO*(DBO.FNK_CALCULO_VALORPARAMETRO_NOM( @CODDEPENDENCIA,@FECHAINI,@FECHAFIN)*@FACTORMAX)    
												WHEN '/' THEN @VALORMAXIMO/(DBO.FNK_CALCULO_VALORPARAMETRO_NOM( @CODDEPENDENCIA,@FECHAINI,@FECHAFIN)*@FACTORMAX)    
											END 
            
				END   
			END    
			ELSE 
			BEGIN   
				IF @TIPODEPENDENCIA='Concepto'
				BEGIN    
					SELECT @VALOR_CALCULO = 0  
					IF @REQUIERELIQ_NCONDD = 1  
					BEGIN  
						IF (SELECT COUNT(*) FROM NEMPFD WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC AND CODCONCEPTO=@CODDEPENDENCIA)>0
						BEGIN  
							SELECT @VALOR_CALCULO = V.VALOR_EMPLEADO*@FACTOR     
							FROM FNK_CALCULO_VALORCONCEPTO_NOM(@NUMDOC,@CODDEPENDENCIA,@FECHAINI,@FECHAFIN,@CNSPAGO,@VALHORASLAB_NCONDD, @HORAS_NCONDD, @DIAS_NCONDD) AS V    
							IF COALESCE(@FACTORMAX,0)>0
							BEGIN
								SELECT @VALOR_CALCULOMAX = V.VALOR_EMPLEADO*@FACTORMAX     
								FROM FNK_CALCULO_VALORCONCEPTO_NOM(@NUMDOC,@CODDEPENDENCIA,@FECHAINI,@FECHAFIN,@CNSPAGO,@VALHORASLAB_NCONDD, @HORAS_NCONDD, @DIAS_NCONDD) AS V    
							END
						END
					END  
					ELSE
					BEGIN  
						SELECT @VALOR_CALCULO = V.VALOR_EMPLEADO*@FACTOR     
						FROM FNK_CALCULO_VALORCONCEPTO_NOM(@NUMDOC,@CODDEPENDENCIA,@FECHAINI,@FECHAFIN,@CNSPAGO,@VALHORASLAB_NCONDD, @HORAS_NCONDD, @DIAS_NCONDD) AS V  
						IF COALESCE(@FACTORMAX,0)>0
						BEGIN
							SELECT @VALOR_CALCULOMAX = V.VALOR_EMPLEADO*@FACTORMAX    
							FROM FNK_CALCULO_VALORCONCEPTO_NOM(@NUMDOC,@CODDEPENDENCIA,@FECHAINI,@FECHAFIN,@CNSPAGO,@VALHORASLAB_NCONDD, @HORAS_NCONDD, @DIAS_NCONDD) AS V  
						END
					END  
					SELECT  @VALOR_DEPENDENCIA=CASE @OPERACION    
											WHEN '+' THEN @VALOR_DEPENDENCIA+@VALOR_CALCULO    
											WHEN '-' THEN @VALOR_DEPENDENCIA-@VALOR_CALCULO    
											WHEN '*' THEN @VALOR_DEPENDENCIA*@VALOR_CALCULO     
											WHEN '/' THEN @VALOR_DEPENDENCIA/@VALOR_CALCULO    
										END  
					IF COALESCE(@FACTORMAX,0)>0
					BEGIN
						SELECT @VALORMAXIMO=CASE @OPERACION    
													WHEN '+' THEN @VALORMAXIMO+@VALOR_CALCULOMAX    
													WHEN '-' THEN @VALORMAXIMO-@VALOR_CALCULOMAX    
													WHEN '*' THEN @VALORMAXIMO*@VALOR_CALCULOMAX     
													WHEN '/' THEN @VALORMAXIMO/@VALOR_CALCULOMAX    
												END  
					END                                         
				END
			END    
			FETCH NEXT FROM CUR_NCONDD    
			INTO @TIPODEPENDENCIA, @CODDEPENDENCIA, @FACTOR, @OPERACION, @REQUIERELIQ_NCONDD, @VALHORASLAB_NCONDD, @HORAS_NCONDD, @DIAS_NCONDD,@FACTORMAX   
		END    
		CLOSE CUR_NCONDD    
		DEALLOCATE CUR_NCONDD     
		-- ojo revizar esto 18.dic.2005  
		-- SET @VALOR_DEPENDENCIA = @VALOR_DEPENDENCIA * (@DIASXPERIODO/@DIASXCARGO)  
		IF COALESCE(@VALORMAXIMO,0)=0 OR COALESCE(@FACTORMAX,0)=0
		BEGIN
			SELECT @VALORMAXIMO=@VALOR_EVALUAR+1
		END

		SELECT @VALOR=CASE @CONDICION    
					WHEN '>'  THEN (CASE WHEN @VALOR_EVALUAR>@VALOR_DEPENDENCIA  AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR ELSE 0 END)     
					WHEN '>=' THEN (CASE WHEN @VALOR_EVALUAR>=@VALOR_DEPENDENCIA AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR ELSE 0 END)     
					WHEN '='  THEN (CASE WHEN @VALOR_EVALUAR=@VALOR_DEPENDENCIA  AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR ELSE 0 END)     
					WHEN '<'  THEN (CASE WHEN @VALOR_EVALUAR<@VALOR_DEPENDENCIA  AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR ELSE 0 END)     
					WHEN '<=' THEN (CASE WHEN @VALOR_EVALUAR<=@VALOR_DEPENDENCIA AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR ELSE 0 END)     
					WHEN '<>' THEN (CASE WHEN @VALOR_EVALUAR<>@VALOR_DEPENDENCIA AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR ELSE 0 END)     
		END        
		SELECT @VALOR_EMPRESA= CASE @CONDICION    
									WHEN '>'  THEN (CASE WHEN @VALOR_EVALUAR>@VALOR_DEPENDENCIA  AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR_EMPRESA ELSE 0 END)     
									WHEN '>=' THEN (CASE WHEN @VALOR_EVALUAR>=@VALOR_DEPENDENCIA AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR_EMPRESA ELSE 0 END)     
									WHEN '='  THEN (CASE WHEN @VALOR_EVALUAR=@VALOR_DEPENDENCIA  AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR_EMPRESA ELSE 0 END)     
									WHEN '<'  THEN (CASE WHEN @VALOR_EVALUAR<@VALOR_DEPENDENCIA  AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR_EMPRESA ELSE 0 END)     
									WHEN '<=' THEN (CASE WHEN @VALOR_EVALUAR<=@VALOR_DEPENDENCIA AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR_EMPRESA ELSE 0 END)     
									WHEN '<>' THEN (CASE WHEN @VALOR_EVALUAR<>@VALOR_DEPENDENCIA AND @VALORMAXIMO> @VALOR_EVALUAR  THEN @VALOR_EMPRESA ELSE 0 END)     
							END   
		IF @VALOR = 0  
		SET @VALOR100P = 0  
	END ---20    
  
	IF @CLASE='Particular' GOTO INST_PARTICULAR  
  
	/*IMPORTANTE TENER TODA LA CONFIGURACION COMO SI EL EMPLEADO TRABAJARA LOS 30 DIAS
	--PROPOSITO PROVISIONAR EXACTAMENTE LOS DIAS TRABAJADOS Y QUE NO PROVISIONE SOBRE 30 DIAS COMO ACTUALMENTE LO HACE, QUE ES LO RECOMENDADO
	--SOGAMOSO $-> JJIMENEZ 2021.03.31
	*/
	IF EXISTS(SELECT * FROM DBO.FNK_EXPLODE(DBO.FNK_VALORVARIABLE('CODNOM_NOMILIQUIXDIA'),',') WHERE WORD=@CODCONCEPTO ) AND @HORAS_LABORADAS<@HORASXCARGO
	BEGIN 
		SELECT @VALOR=((@VALOR/@HORAS_A_LABORAR)*@HORAS_LABORADAS),@VALOR_EMPRESA=((@VALOR_EMPRESA/@HORAS_A_LABORAR)*@HORAS_LABORADAS),@VALOR100P=((@VALOR100P/@HORAS_A_LABORAR)*@HORAS_LABORADAS)

		IF EXISTS(SELECT * FROM TGEN WHERE TABLA='NOMINA' AND CAMPO='ProvICesan' AND CODIGO=@CODCONCEPTO)
		BEGIN
			SELECT @VALOR=((@VALOR/@HORAS_A_LABORAR)*@HORAS_LABORADAS),@VALOR_EMPRESA=((@VALOR_EMPRESA/@HORAS_A_LABORAR)*@HORAS_LABORADAS),@VALOR100P=((@VALOR100P/@HORAS_A_LABORAR)*@HORAS_LABORADAS)
		END
	END

	INSERT INTO @TABLA(DETALLE, CANTIDAD, VALOR_EMPLEADO, VALOR_EMPRESA, VALOR100P, IDTRANSPRESTAMO, NUMDOCPRESTAMO,   
					NUMCUOTA, CODPRF, IDTERCERO, BASE_PRESTACIONES, ITEMCONCEPTO, BASE_CALCULO, GENERANOVEFU, CODNOVEFU,  
					MOSTRARHORAS)    
	SELECT @DETALLE, @CANTIDAD, ROUND(@VALOR+(CASE WHEN @VALOR>0.00 THEN @MAS_REDONDEO ELSE 0 END),@REDONDEO) ,ROUND(@VALOR_EMPRESA+(CASE WHEN @VALOR_EMPRESA>0.00 THEN @MAS_REDONDEO ELSE 0 END),@REDONDEO), @VALOR100P, @IDTRANSPRESTAMO_CUR,   
		@NUMDOCPRESTAMO_CUR, @NUMCUOTA_CUR, @CODPRF, @IDTERCERO, @BASE_PRESTACIONES, @ITEM_NCOND, @VALOR_CALCULO,  
		@GENERANOVEFU, @CODNOVEFU, @MOSTRARHORAS  
	RETURN    
END



