CREATE OR ALTER PROCEDURE DBO.SPQ_RECAUDO_PE
@JSON  NVARCHAR(MAX) 
WITH
ENCRYPTION
AS
DECLARE  @PARAMETROS   NVARCHAR(MAX) ,@MODELO           VARCHAR(100) ,@METODO           VARCHAR(100)  ,@USUARIO        VARCHAR(12),
			@GRUPO        VARCHAR(8)    ,@SYS_COMPUTERNAME VARCHAR(254) ,@IDSEDE             VARCHAR(5)    ,@USUNOMBRE     VARCHAR(100), @SEDE VARCHAR(5),
			@FECHA        VARCHAR(10)   ,@IDEMEDICA        VARCHAR(4)	,@FECHA1           DATETIME		,@SQL            VARCHAR(MAX),
			@CODCAJERO	  VARCHAR(20),@COMPANIA		VARCHAR(10)	,@IDAFILIADO VARCHAR(20)	,@IDMEDICO	VARCHAR(20)	,@FECHAINI DATE	,
			@FECHAFIN	  DATE	,@CONSECUTIVOS	NVARCHAR(MAX)	,@MARCAR BIT	,@NOAUTORIZACION VARCHAR(50)	,@CONSECUTIVO VARCHAR(20),
			@OBSERVACION  VARCHAR (200)	,@IDCAUSAL VARCHAR(20)	,@IDSERVICIO VARCHAR(20)	,@CONT INT		,@CNSIZSOL VARCHAR(20)
		  ,@CONSECUTIVOCAN VARCHAR(20)	,@GRUPAL BIT	,@IDAUT VARCHAR(20)		,@VR_TOTAL DECIMAL(14,2)   ,@VLRDEPOSITOS DECIMAL(14,2) 
		  ,@MENSAJE      VARCHAR(500)		,@PROCESO VARCHAR(50)	,@PROCEDENCIA VARCHAR(20), @ITEM INT		,@TIPOFAC VARCHAR(20)
		  ,@FECHAFACT	  DATE		,@CUMPLIDA	SMALLINT			,@FACTURADA BIT		,@VLRCOPAGO		DECIMAL(14,2)	,@DPR	VARCHAR(20)	,@CNSFACJ VARCHAR(20)
		  ,@FECHAFCJ	  DATE		,@PART	BIT=0	,@CNSACJ	 VARCHAR(20)	,@TOTAL	DECIMAL(12,4)	,@CODCAJA	VARCHAR(6)	,@NOADMISION VARCHAR(20)
		  ,@TIPOCAJA	  VARCHAR(10)	,@N_FACTURA VARCHAR(20)	,@NORECIBOCAJA	VARCHAR(20)	,@IDTERCERO	VARCHAR(20)	,@NROCOMPROBANTE VARCHAR(20)
		  ,@VALORTOTAL	  DECIMAL(14,2)	,@ESTADO VARCHAR(10)	,@FECHALLEGA DATETIME,	@FACTURABLE BIT	,@IDPLAN VARCHAR(10)	,@IDTERCEROCA VARCHAR(20)
		  ,@RUC          VARCHAR(20)	,@dataTER NVARCHAR(MAX)	,@VIVA DECIMAL(14,2)	,@MIVA	SMALLINT	,@IDFORMATOFTR VARCHAR(20)
		  ,@EMAIL VARCHAR(MAX)	,@NOTIFICADO BIT = 0		,@CONSECUTIVOCIT VARCHAR(20)
DECLARE @MONEDA VARCHAR(20), @DATO3 VARCHAR(20), @DESCUENTO DECIMAL(14,2), @CUENTACXC VARCHAR(16), @IDTERPART VARCHAR(20), @VENTAPRT     BIT=0
				, @DV SMALLINT, @TV VARCHAR(10), @EC SMALLINT, @IDTERCEROF VARCHAR(20), @IDCATEGORIA VARCHAR(10)	, @ESPART BIT
				, @ESPARTPERU   BIT, @CUENTACXC_RAD VARCHAR(16), @NOAUT VARCHAR(20), @OK INT, @CNSFTR VARCHAR(20), @NVOCONSEC VARCHAR(20)
				, @FECHAFAC DATETIME   = NULL, @CNSRESOL VARCHAR(50), @PREFIJOFAC VARCHAR(20), @TTEC VARCHAR(10)	, @VALORCOPAGO DECIMAL(14,2)
				, @IDAREA VARCHAR(20), @CCOSTO VARCHAR(20), @PREFIJO VARCHAR(20), @DESCSERVICIO VARCHAR(500), @IDCLASE VARCHAR(20)	,@PROCEDENCIA_2 VARCHAR(20)
				, @PIVA DECIMAL(14,2),	@CUENTA_FIMPDV VARCHAR(16), @IDIMPUESTO VARCHAR(10)	, @VRTOTAL DECIMAL(14,2),  @VRSERV DECIMAL(14,2),  @VRCOPA DECIMAL(14,2) ,  @VRPACO DECIMAL(14,2)
				, @IDKPAGE INT	,@ESTADO_KPAGE VARCHAR(20)	,@TABLA VARCHAR(20), @VALOR DECIMAL(14,2), @F_EXPIRA DATETIME, @LINKPAGO VARCHAR(500)	,@FIRMA VARCHAR(500), @FIRMA_2 VARCHAR(500)
				, @MOVILAFI VARCHAR(13)	,@PACIENTE VARCHAR(500)	, @SMS VARCHAR(8000)	,@VALOR_TEXTO VARCHAR(20)	, @CELULAR VARCHAR(20)	,@NOM_PREFIJO VARCHAR(150),@IDPROVEEDOR VARCHAR(20), @VALOR_SERVICIOS_SIN_IGV  DECIMAL(14,2)
DECLARE @TABLERRR		TABLE (ERROR VARCHAR(MAX)) --@VALOR_TEXTO

BEGIN 
	SET LANGUAGE Spanish;  
	SET DATEFORMAT dmy
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(MAX));
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO), @USUNOMBRE = NOMBRE FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME, @COMPANIA = COMPANIA, @CODCAJERO= CODCAJERO FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @IDSEDE = IDSEDE, @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
	PRINT '@USUARIO='+@USUARIO

    IF @METODO = 'VALIDA_INGRESO'
	BEGIN 
	/* VALIDACIONES DE CAJA */
		SELECT @CONSECUTIVO = CONSECUTIVO, @PROCEDENCIA = PROCEDENCIA, @CODCAJA = CODCAJA
		FROM OPENJSON(@PARAMETROS)
		WITH(	CONSECUTIVO		VARCHAR(20)		'$.CONSECUTIVO'		,CODCAJA	VARCHAR(20)		'$.CODCAJA'
				,PROCEDENCIA	VARCHAR(20)		'$.PROCEDENCIA')
		/* FTR.TIPOFIN = C: Factura  -  N: Boleta */
		IF @PROCEDENCIA = 'HADM' AND EXISTS (SELECT * FROM HADM WHERE HADM.NOADMISION = @CONSECUTIVO AND COALESCE(HADM.N_FACTURA,'') <> '')
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'Ya cuenta con Numero de Documento.'
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		BEGIN TRY
			SELECT @CNSACJ =  CAJ.CNSACJ, @CODCAJERO = USUSU.CODCAJERO, @CODCAJA = UBEQ.CAJA,@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA) 
			FROM  USUSU 
				INNER JOIN UBEQ ON USUSU.SYS_ComputerName = UBEQ.SYS_ComputerName
				INNER JOIN CAJ ON UBEQ.CAJA = CAJ.CODCAJA
			WHERE  USUARIO = @USUARIO

			IF @PROCEDENCIA = 'MAD'
			BEGIN
				IF NOT EXISTS (SELECT * FROM CIT WHERE  CONSECUTIVO = @CONSECUTIVO AND COALESCE(GENEROCAJA,0) = 1)
				BEGIN
					PRINT 'PRIMERA VALIDACION ...............'
					IF (SELECT DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR')) = @IDTERCEROCA
					BEGIN
						SELECT @PART=1
					END
					SET @COMPANIA ='01'
					SELECT @SYS_COMPUTERNAME=COALESCE(SYS_COMPUTERNAME,HOST_NAME())
					FROM USUSU WHERE USUARIO=@USUARIO
					SELECT @SEDE=IDSEDE FROM CIT WHERE CONSECUTIVO=@CONSECUTIVO

					PRINT 'INGRESA A SPK_PAGOSCAJA_CIT'
					EXEC SPK_PAGOSCAJA_CIT @CONSECUTIVO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@USUARIO,@PART

					UPDATE TFCJ SET TFCJ.VALORTOTAL = CIT.VALORCOPAGO FROM TFCJ, CIT WHERE TFCJ.NOADMISION = @CONSECUTIVO AND CIT.CONSECUTIVO = @CONSECUTIVO AND TFCJ.PROCEDENCIA = 'MAD' 
				END
				IF NOT EXISTS(SELECT  * FROM FCJ WHERE  NOADMISION = @CONSECUTIVO AND PROCEDENCIA='CITAS' AND COALESCE(FCJ.ESTADO,'') = 'P' ) 
					AND EXISTS (SELECT  * FROM TFCJ WHERE  NOADMISION = @CONSECUTIVO AND PROCEDENCIA='CITAS')
				BEGIN
					PRINT 'SEGUNDA VALIDACION ...............'
					SELECT @PROCEDENCIA_2 = TFCJ.PROCEDENCIA, @IDPLAN = TFCJ.IDPLAN ,@NOADMISION = NOADMISION, @CNSFACJ = CNSFACJ 
					FROM TFCJ WHERE  NOADMISION = @CONSECUTIVO

					EXEC SPK_TRAERECIB_CAJA @CNSFACJ,@CNSACJ, @SYS_COMPUTERNAME, '01',@IDSEDE,@USUARIO , 'COBRO'    
				END
			END
			IF @PROCEDENCIA = 'HADM'
			BEGIN

				IF NOT EXISTS (SELECT * FROM FCJ WHERE NOADMISION = @CONSECUTIVO AND PROCEDENCIA = 'HADM')
				BEGIN
					SET @CNSFACJ=NULL
					EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJ',@CNSFACJ OUTPUT
					SELECT @CNSFACJ =  REPLACE(SPACE(8 - LEN(@CNSFACJ))+LTRIM(RTRIM(@CNSFACJ)),SPACE(1),0)
				
					INSERT INTO FCJ (CNSFACJ,TIPO,CODCAJA,COMPANIA, CLASE_FAC,CNSACJ,ESTADO,USUARIO,SYS_ComputerName,IDTERCERO, FECHA, TIPOEGRESO, OBSERVACION, PROCEDENCIA, VALORTOTAL , USUARIOLOG
					,BANCO, SUCURSAL, CTA_BCO, NOADMISION, CERRADA, ARCHIVADO, IDPLAN, IDAFILIADO, NOMBRECLIENTE)
			 
					SELECT @CNSFACJ, 'INTERNO', @CODCAJA, @COMPANIA, 'COBRO', @CNSACJ, 'P', @CODCAJERO, @SYS_COMPUTERNAME, HADM.IDTERCERO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), null, '', 'HADM',HADM.COPAGOVALOR, @USUARIO
					, null,null,null, @CONSECUTIVO, 0, 0, HADM.IDPLAN, HADM.IDAFILIADO, AFI.NOMBREAFI
					FROM HADM 
					INNER JOIN AFI ON HADM.IDAFILIADO = AFI.IDAFILIADO
					WHERE NOADMISION = @CONSECUTIVO

					INSERT INTO FCJD (CODCAJA, CNSFACJ, ITEM, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, TIPODCTO)
					SELECT @CODCAJA, @CNSFACJ, 1, DBO.FNK_VALORVARIABLE ('IDCJCOPA'), HADM.COPAGOVALOR, 1, HADM.COPAGOVALOR, 'N'
					FROM HADM 
					WHERE NOADMISION = @CONSECUTIVO
				END
			END
			IF @PROCEDENCIA = 'AUT'
			BEGIN
				IF NOT EXISTS (SELECT * FROM FCJ WHERE NOADMISION = @CONSECUTIVO AND PROCEDENCIA = 'CE')
				BEGIN
					SET @CNSFACJ=NULL
					EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJ',@CNSFACJ OUTPUT
					SELECT @CNSFACJ =  REPLACE(SPACE(8 - LEN(@CNSFACJ))+LTRIM(RTRIM(@CNSFACJ)),SPACE(1),0)
				--VALORTOTAL
					INSERT INTO FCJ (CNSFACJ,TIPO,CODCAJA,COMPANIA, CLASE_FAC,CNSACJ,ESTADO,USUARIO,SYS_ComputerName,IDTERCERO, FECHA, TIPOEGRESO, OBSERVACION, PROCEDENCIA, VALORTOTAL , USUARIOLOG
					,BANCO, SUCURSAL, CTA_BCO, NOADMISION, NOPRESTACION, CERRADA, ARCHIVADO, IDPLAN, IDAFILIADO, NOMBRECLIENTE)
					SELECT @CNSFACJ, 'INTERNO', @CODCAJA, @COMPANIA, 'COBRO', @CNSACJ, 'P', @CODCAJERO, @SYS_COMPUTERNAME, AUT.IDPROVEEDOR, DBO.FNK_FECHA_SIN_MLS(GETDATE()), null, '', 'CE',AUT.VALORTOTAL, @USUARIO
					, null,null,null, @CONSECUTIVO, @CONSECUTIVO, 0, 0, AUT.IDPLAN, AUT.IDAFILIADO, AFI.NOMBREAFI
					FROM AUT 
					INNER JOIN AFI ON AUT.IDAFILIADO = AFI.IDAFILIADO
					WHERE AUT.IDAUT = @CONSECUTIVO

					INSERT INTO FCJD (CODCAJA, CNSFACJ, ITEM, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, TIPODCTO)
					SELECT @CODCAJA, @CNSFACJ, AUTD.NO_ITEM, DBO.FNK_VALORVARIABLE ('IDCJCOPA'), AUTD.VALOR, AUTD.CANTIDAD, AUTD.VALORCOPAGO, 'N'
					FROM AUTD 
					WHERE AUTD.IDAUT = @CONSECUTIVO 
					UPDATE AUT SET NORECIBOCAJA = @CNSFACJ, CODCAJA = @CODCAJA, TIPOCAJA = 'FCJ' WHERE AUT.IDAUT = @CONSECUTIVO
				END
			END
			IF @PROCEDENCIA = 'LIST'
			BEGIN
				IF NOT EXISTS (SELECT * FROM FCJ WHERE NOADMISION = @CONSECUTIVO AND PROCEDENCIA = 'CE' AND ESTADO = 'P')
				BEGIN
					SET @CNSFACJ=NULL
					EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJ',@CNSFACJ OUTPUT
					SELECT @CNSFACJ =  REPLACE(SPACE(8 - LEN(@CNSFACJ))+LTRIM(RTRIM(@CNSFACJ)),SPACE(1),0)
				--VALORTOTAL
					INSERT INTO FCJ (CNSFACJ,TIPO,CODCAJA,COMPANIA, CLASE_FAC,CNSACJ,ESTADO,USUARIO,SYS_ComputerName,IDTERCERO, FECHA, TIPOEGRESO, OBSERVACION, PROCEDENCIA, VALORTOTAL , USUARIOLOG
					,BANCO, SUCURSAL, CTA_BCO, NOADMISION, NOPRESTACION, CERRADA, ARCHIVADO, IDPLAN, IDAFILIADO, NOMBRECLIENTE)
					SELECT @CNSFACJ, 'INTERNO', @CODCAJA, @COMPANIA, 'COBRO', @CNSACJ, 'P', @CODCAJERO, @SYS_COMPUTERNAME, AUT.IDPROVEEDOR, DBO.FNK_FECHA_SIN_MLS(GETDATE()), null, '', 'CE',AUT.VALORCOPAGO, @USUARIO
					, null,null,null, @CONSECUTIVO, @CONSECUTIVO, 0, 0, AUT.IDPLAN, AUT.IDAFILIADO, AFI.NOMBREAFI
					FROM AUT 
					INNER JOIN AFI ON AUT.IDAFILIADO = AFI.IDAFILIADO
					WHERE AUT.IDAUT = @CONSECUTIVO

					INSERT INTO FCJD (CODCAJA, CNSFACJ, ITEM, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, TIPODCTO)
					SELECT @CODCAJA, @CNSFACJ, AUTD.NO_ITEM, DBO.FNK_VALORVARIABLE ('IDCJCOPA'), AUTD.VALOR, AUTD.CANTIDAD, AUTD.VALORCOPAGO, 'N'
					FROM AUTD 
					WHERE AUTD.IDAUT = @CONSECUTIVO AND COALESCE(AUTD.VALORCOPAGO,0) > 0
					UPDATE AUT SET NORECIBOCAJA = @CNSFACJ, CODCAJA = @CODCAJA, TIPOCAJA = 'FCJ' WHERE AUT.IDAUT = @CONSECUTIVO
				END
			END

			/* LOS SELECTs A MOSTRAR */
			IF @PROCEDENCIA = 'AUT'
			BEGIN
				SELECT 'OK'OK, AUT.VALORTOTAL COPAGOVALOR, 0 MONTOPAGADO, 0 COPA_VAR_PORC, AUT.N_FACTURA, '' NFACTURA, AUT.NOADMISION, AUT.IDAFILIADO, AFI.TIPO_DOC, AFI.DOCIDAFILIADO, AFI.NOMBREAFI 
				, AUT.FECHA, AUT.IDSEDE, SED.DESCRIPCION, AUT.IDPLAN, PLN.DESCPLAN, AUT.IDPROVEEDOR IDTERCERO, TER.RAZONSOCIAL ,AUT.ESTADO, AUT.CERRADA, FCJ.N_FACTURA, FCJ.CNSFACJ, FCJ.CODCAJA, FCJ.CNSACJ

				FROM AUT 
				INNER JOIN AFI ON AUT.IDAFILIADO = AFI.IDAFILIADO
				INNER JOIN PLN ON AUT.IDPLAN = PLN.IDPLAN
				INNER JOIN TER ON AUT.IDPROVEEDOR = TER.IDTERCERO
				INNER JOIN FCJ ON AUT.IDAUT = FCJ.NOADMISION AND FCJ.PROCEDENCIA = 'CE'
				LEFT JOIN SED ON AUT.IDSEDE = SED.IDSEDE
				WHERE  AUT.IDAUT = @CONSECUTIVO
			END
			IF @PROCEDENCIA =  'LIST'
			BEGIN
				SELECT 'OK'OK, AUT.VALORCOPAGO COPAGOVALOR, 0 MONTOPAGADO, 0 COPA_VAR_PORC, AUT.N_FACTURA, '' NFACTURA, AUT.NOADMISION, AUT.IDAFILIADO, AFI.TIPO_DOC, AFI.DOCIDAFILIADO, AFI.NOMBREAFI 
				, AUT.FECHA, AUT.IDSEDE, SED.DESCRIPCION, AUT.IDPLAN, PLN.DESCPLAN, AUT.IDPROVEEDOR IDTERCERO, TER.RAZONSOCIAL ,AUT.ESTADO, AUT.CERRADA, FCJ.N_FACTURA, FCJ.CNSFACJ, FCJ.CODCAJA, FCJ.CNSACJ

				FROM AUT 
				INNER JOIN AFI ON AUT.IDAFILIADO = AFI.IDAFILIADO
				INNER JOIN PLN ON AUT.IDPLAN = PLN.IDPLAN
				INNER JOIN TER ON AUT.IDPROVEEDOR = TER.IDTERCERO
				INNER JOIN FCJ ON AUT.IDAUT = FCJ.NOADMISION AND FCJ.PROCEDENCIA = 'CE' AND FCJ.ESTADO = 'P'
				LEFT JOIN SED ON AUT.IDSEDE = SED.IDSEDE
				WHERE  AUT.IDAUT = @CONSECUTIVO
			END
			IF @PROCEDENCIA = 'HADM'
			BEGIN
				SELECT 'OK'OK, HADM.COPAGOVALOR, 0 MONTOPAGADO, HADM.COPA_VAR_PORC, HADM.N_FACTURA, HADM.NFACTURA, HADM.NOADMISION, HADM.IDAFILIADO, AFI.TIPO_DOC, AFI.DOCIDAFILIADO, AFI.NOMBREAFI 
				, HADM.FECHA, HADM.IDSEDE, SED.DESCRIPCION, HADM.IDPLAN, PLN.DESCPLAN, HADM.IDTERCERO, TER.RAZONSOCIAL ,HADM.ESTADO, HADM.CERRADA, FCJ.N_FACTURA, FCJ.CNSFACJ, FCJ.CODCAJA, FCJ.CNSACJ
				FROM HADM 
				INNER JOIN AFI ON HADM.IDAFILIADO = AFI.IDAFILIADO
				INNER JOIN PLN ON HADM.IDPLAN = PLN.IDPLAN
				INNER JOIN TER ON HADM.IDTERCERO = TER.IDTERCERO
				INNER JOIN SED ON HADM.IDSEDE = SED.IDSEDE
				INNER JOIN FCJ ON HADM.NOADMISION = FCJ.NOADMISION AND FCJ.PROCEDENCIA = 'HADM' AND FCJ.ESTADO = 'P'
				WHERE  HADM.NOADMISION = @CONSECUTIVO
			END
			IF @PROCEDENCIA = 'MAD'
			BEGIN
				SELECT 'OK'OK, CIT.VALORCOPAGO COPAGOVALOR, 0 MONTOPAGADO,  FCJ.N_FACTURA, FCJ.CNSFACJ, FCJ.CODCAJA, FCJ.CNSACJ 
				FROM CIT 
				INNER JOIN AFI ON CIT.IDAFILIADO = AFI.IDAFILIADO
				INNER JOIN FCJ ON CIT.CONSECUTIVO = FCJ.NOADMISION AND FCJ.PROCEDENCIA = 'CITAS' AND COALESCE(FCJ.ESTADO,'') = 'P'
				WHERE CIT.CONSECUTIVO = @CONSECUTIVO
			END
			IF @PROCEDENCIA IN ( 'FCJ','INVENTARIO', 'APOYO')
			BEGIN 
				SELECT 'OK'OK, VALORTOTAL COPAGOVALOR, 0 MONTOPAGADO,  FCJ.N_FACTURA, FCJ.CNSFACJ, FCJ.CODCAJA, FCJ.CNSACJ
				FROM FCJ WHERE FCJ.CNSFACJ = @CONSECUTIVO AND FCJ.CODCAJA = @CODCAJA 
			END
			
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK
		
	END
	IF @METODO = 'COBRAR'
	BEGIN
	   SELECT @PROCEDENCIA = PROCEDENCIA, @CONSECUTIVO = CONSECUTIVO , @CNSFACJ = CNSFACJ , @CODCAJA = CODCAJA  , @IDTERCERO = IDTERCERO, @TIPOFAC = TIPOFAC
	   FROM OPENJSON(@PARAMETROS)
	   WITH( PROCEDENCIA			VARCHAR(20)		'$.PROCEDENCIA'
			,CONSECUTIVO			VARCHAR(20)		'$.CONSECUTIVO'
			,CNSFACJ				VARCHAR(20)		'$.CNSFACJ'
			,CODCAJA				VARCHAR(20)		'$.CODCAJA'
			,IDTERCERO				VARCHAR(20)		'$.IDTERCERO'
			,TIPOFAC				VARCHAR(20)		'$.TIPOFAC'
		)
		SELECT @TOTAL = VALORTOTAL FROM FCJ WHERE CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ
	
		IF (SELECT COALESCE(SUM (VALOR),0) FROM PCJ WHERE PCJ.CODCAJA = @CODCAJA AND PCJ.CNSFACJ = @CNSFACJ ) = 0
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El recibo no tiene detalles de pago.....'
		END
		IF  (SELECT COALESCE(SUM (VALOR),0) FROM PCJ WHERE PCJ.CODCAJA = @CODCAJA AND PCJ.CNSFACJ = @CNSFACJ ) > 0
		BEGIN
			IF (SELECT COALESCE(SUM (VALOR),0) FROM PCJ WHERE PCJ.CODCAJA = @CODCAJA AND PCJ.CNSFACJ = @CNSFACJ ) <>  @TOTAL
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'El valor del detalle de pago, es diferente al valor del Recibo'
			END
		END
		IF @PROCEDENCIA IN ( 'INVENTARIO'  , 'APOYO')
		BEGIN
			SELECT @IDAFILIADO= AUT.IDAFILIADO, @IDPLAN = AUT.IDPLAN,@DESCUENTO = AUT.DESCUENTO,@CCOSTO=  AUT.CCOSTO
				, @IDAREA = AUT.IDAREA, @VR_TOTAL= FCJ.VALORTOTAL , @FECHA1=FCJ.FECHA  , @IDAUT = AUT.IDAUT, @NOAUT = AUT.NOAUT
				, @ESPART = CASE WHEN AUT.IDTERCEROCA = DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') AND AUT.IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART') THEN 1 ELSE 0 END
			FROM AUT 
				INNER JOIN FCJ ON AUT.NORECIBOCAJA = FCJ.CNSFACJ AND AUT.CODCAJA = FCJ.CODCAJA
			WHERE AUT.NORECIBOCAJA = @CNSFACJ AND AUT.CODCAJA = @CODCAJA

			IF @ESPART = 1 AND NOT EXISTS (SELECT  * FROM AUTD WHERE AUTD.IDAUT = @IDAUT AND  COALESCE(AUTD.N_FACTURA,'') = '' AND COALESCE(AUTD.VALOREXCEDENTE,0) >0 )
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'No se encontraron Items pendientes por facturar.'
			END
			IF @ESPART = 0 AND NOT EXISTS (SELECT  * FROM AUTD WHERE AUTD.IDAUT = @IDAUT AND  COALESCE(AUTD.NFACTURA,'') = '' AND COALESCE(AUTD.VALORCOPAGO,0) >0 )
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'No se encontraron Items pendientes por facturar.'
			END
		END

		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				PRINT 'INGRESO RECAUDO - COBRAR'
				SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
				SELECT @MONEDA = DATO FROM USVGS WHERE IDVARIABLE = 'IDMONEDABASE'
				SELECT @DATO3 = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'    
				SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR_BOLETA')

				IF @TIPOFAC ='Boleta'
				BEGIN
					SELECT @IDTERCERO = NULL
				END

				IF @PROCEDENCIA = 'HADM'
				BEGIN
					SELECT @IDAFILIADO = IDAFILIADO, @DESCUENTO = DESCUENTO, @IDAREA = IDAREA_ALTA, @CCOSTO = CCOSTO_ALTA 
					, @VR_TOTAL = HADM.COPAGOVALOR, @FECHA1 = HADM.FECHA
					FROM HADM WHERE  NOADMISION = @CONSECUTIVO

					SELECT @PREFIJO = SER.PREFIJO, @IDSERVICIO = SER.IDSERVICIO, @DESCSERVICIO = SER.DESCSERVICIO 
					,@IDIMPUESTO = COALESCE(SER.IDIMPUESTO,NULL), @IDCLASE = COALESCE(SER.IDCLASE,NULL)
					,@PIVA = CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL)) ELSE NULL END
					,@CUENTA_FIMPDV =  CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL))  ELSE NULL END            
					FROM SER WHERE SER.IDSERVICIO = DBO.FNK_VALORVARIABLE('SER_HOSPI_AUT')

					SELECT @CUENTACXC = CUENTA, @CUENTACXC_RAD=CUENTARAD,@TTEC=TIPO FROM TTEC
					WHERE TIPO = DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART') 
					SELECT @IDTERPART = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJTERCEROEXTERNO'

					IF ISNULL(@DV,0) <= 0
						SET @DV = 30

					SELECT @TV = 'Contado' 
					SELECT @EC = 1
					SELECT @IDTERCEROF = @IDAFILIADO
					SELECT @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
					PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
					EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA,@PROCEDENCIA,@NOAUT
					PRINT 'SALGO DE SPK_INSERT_TERDEAFI 001 ==>'

					SELECT @ESPARTPERU = 1
					SELECT @IDTERCEROF=IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=( 
					SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO=@IDAFILIADO ) 
					IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCEROF)
					BEGIN
						SELECT @IDTERCEROF=RUC FROM AFI WHERE IDAFILIADO=@IDAFILIADO
					END

					SELECT @OK = COALESCE(COUNT(*),0) FROM TER WHERE IDTERCERO = @IDTERCEROF
					PRINT 'ANTES DE IF OK = 0'       
					IF @OK = 0
					BEGIN
						SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
						PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
						EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
						PRINT 'SALGO DE SPK_INSERT_TERDEAFI 002 ==>'
					END

					/* GENERO CORRELATIVO DE BOLETA - FACTURA */
					EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
					SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0) 
					IF @TV = 'Contado'  AND @ESPARTPERU = 1 AND @TIPOFAC='Boleta'
					BEGIN
						PRINT 'AQUI LLAMO A BOLETA @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMERO_BOLETA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE BOLETA'
					END
					ELSE
					BEGIN
						PRINT 'AQUI LLAMO A NUMFACTURA  @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE NUMFACTURA'
					END
					PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
					PRINT '@NVOCONSEC='+@NVOCONSEC  

					IF ISNULL(@FECHAFAC,'') = ''
					BEGIN
						SELECT @FECHAFAC = GETDATE()
					END

					IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
					BEGIN
						IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA= CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
						ELSE
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
					END
					/* VALIDA SI EL CORRELATIVO ESTA OK */
					IF @PREFIJOFAC<>LEFT(@NVOCONSEC,LEN(@PREFIJOFAC))
					BEGIN
						PRINT 'Inconsistencia entre el prefijo de factura y el nro generado'
						RAISERROR('Inconsistencia entre el prefijo de factura y el nro generado',16,1)
						RETURN			
					END  
					/* Inserta a FTR TIPOFAC*/
					PRINT 'VOY A INSERTAR A FTR'
					INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
						VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
						IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
						TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
						INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
						IMPRESO, VALORSERVICIOS, VIVA, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
						MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
						CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CAPITADA,CODUNG, CODPRG, IDSEDE, RDIAN,CNSRESOL,IDFORMATO,CP_CONVENIO)
					SELECT @CNSFTR, @COMPANIA, 'C', CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  @IDTERCEROF END, 
						@NVOCONSEC, @FECHAFAC, @FECHAFAC + @DV,
						HADM.COPAGOVALOR, NULL, NULL, LEFT(@MONEDA,2), NULL, 'P', NULL, 
						@IDAFILIADO, @USUARIO, @CONSECUTIVO,
						@PROCEDENCIA, 'I', '', @TV, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0,  HADM.COPAGOVALOR - ROUND(HADM.COPAGOVALOR*0.18,2), ROUND(HADM.COPAGOVALOR*0.18,2), NULL, NULL, @USUARIO,
						DBO.FNK_GETDATE(), 1, 18, 0, HADM.IDPLAN, NULL, CASE WHEN @ESPARTPERU = 1 AND @TIPOFAC='Boleta' THEN 'N' ELSE 'C' END, NULL, NULL, NULL, @DATO3, @TTEC,
						@CUENTACXC,@CUENTACXC_RAD, 0 ,HADM.CODUNG, NULL, HADM.IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''),@IDFORMATOFTR,'Boleta'
					FROM HADM
					WHERE HADM.NOADMISION = @CONSECUTIVO

					PRINT 'VOY A INSERTAR A FTRD ===>'
					INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
						IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
					SELECT @CNSFTR, 1, DBO.FNK_GETDATE(), 'DB', @IDAREA, NULL, @VR_TOTAL,
						NULL, @CCOSTO, @PREFIJO, @DESCSERVICIO, @IDSERVICIO, NULL, 1,
						 ROUND(@VR_TOTAL / 1.18,2), @VR_TOTAL, 0, 0, @USUARIO, @CONSECUTIVO,
						@CONSECUTIVO, 1, NULL, @NVOCONSEC, NULL, 0, @FECHA1,
						@IDIMPUESTO, @IDCLASE,1 , @VR_TOTAL, COALESCE(@PIVA,0), @VR_TOTAL - ROUND(@VR_TOTAL / 1.18,2),@CUENTA_FIMPDV  
					
					INSERT INTO HADMF (NOADMISION, N_FACTURA, CNSFCT, ESTADO, N_FACTURAR, ANEXOUNICO, IDTERCERO, IDPLAN,  DESCRIPCION, ITFC, CNSITFC)
					SELECT @CONSECUTIVO,  @NVOCONSEC, @CNSFTR, 'P', NULL, NULL,HADM.IDTERCERO, HADM.IDPLAN, 'TODAS', 0, NULL
					FROM HADM WHERE HADM.NOADMISION = @CONSECUTIVO

					UPDATE FCJ SET N_FACTURA = @NVOCONSEC, RECAUDO = 1, USURECAUDO = @USUARIO WHERE FCJ.NOADMISION = @CONSECUTIVO AND FCJ.CNSFACJ = @CNSFACJ AND FCJ.CODCAJA = @CODCAJA

					UPDATE HADM SET N_FACTURA = @NVOCONSEC WHERE NOADMISION = @CONSECUTIVO
				END /* FIN ==> PROCEDENCIA HADM */
				IF @PROCEDENCIA = 'FCJ' --VR_TOTAL
				BEGIN
					SELECT @IDAFILIADO= AUT.IDAFILIADO, @IDPLAN = AUT.IDPLAN,@DESCUENTO = AUT.DESCUENTO,@CCOSTO=  AUT.CCOSTO
						, @IDAREA = AUT.IDAREA, @VR_TOTAL= FCJ.VALORTOTAL , @FECHA1=FCJ.FECHA  , @IDAUT = AUT.IDAUT
					FROM AUT 
						INNER JOIN FCJ ON AUT.NORECIBOCAJA = FCJ.CNSFACJ AND AUT.CODCAJA = FCJ.CODCAJA
					WHERE AUT.NORECIBOCAJA = @CNSFACJ AND AUT.CODCAJA = @CODCAJA

					SELECT @PREFIJO = SER.PREFIJO, @IDSERVICIO = SER.IDSERVICIO, @DESCSERVICIO = SER.DESCSERVICIO 
					,@IDIMPUESTO = COALESCE(SER.IDIMPUESTO,NULL), @IDCLASE = COALESCE(SER.IDCLASE,NULL)
					,@PIVA = CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL)) ELSE NULL END
					,@CUENTA_FIMPDV =  CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL))  ELSE NULL END            
					FROM SER WHERE SER.IDSERVICIO = DBO.FNK_VALORVARIABLE('SER_HOSPI_AUT')

					SELECT @CUENTACXC = CUENTA, @CUENTACXC_RAD=CUENTARAD,@TTEC=TIPO FROM TTEC
					WHERE TIPO = DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART') 

					IF ISNULL(@DV,0) <= 0
						SET @DV = 30

					SELECT @TV = 'Contado' 
					SELECT @EC = 1
					SELECT @IDTERCEROF = @IDAFILIADO
					SELECT @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
					PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
					EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA,@PROCEDENCIA,@NOAUT
					PRINT 'SALGO DE SPK_INSERT_TERDEAFI 001 ==>'

					SELECT @ESPARTPERU = 1
					SELECT @IDTERCEROF=IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=(SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO=@IDAFILIADO ) 
					IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCEROF)
					BEGIN
						SELECT @IDTERCEROF=RUC FROM AFI WHERE IDAFILIADO=@IDAFILIADO
					END

					SELECT @OK = COALESCE(COUNT(*),0) FROM TER WHERE IDTERCERO = @IDTERCEROF
					PRINT 'ANTES DE IF OK = 0'       
					IF @OK = 0
					BEGIN
						SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
						PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
						EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
						PRINT 'SALGO DE SPK_INSERT_TERDEAFI 002 ==>'
					END

					/* GENERO CORRELATIVO DE BOLETA - FACTURA */
					EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
					SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0) 
					IF @TV = 'Contado'  AND @ESPARTPERU = 1 AND @TIPOFAC='Boleta'
					BEGIN
						PRINT 'AQUI LLAMO A BOLETA @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMERO_BOLETA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE BOLETA'
					END
					ELSE
					BEGIN
						PRINT 'AQUI LLAMO A NUMFACTURA  @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE NUMFACTURA'
					END
					PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
					PRINT '@NVOCONSEC='+@NVOCONSEC  

					IF ISNULL(@FECHAFAC,'') = ''
					BEGIN
						SELECT @FECHAFAC = GETDATE()
					END

					IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
					BEGIN
						IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA= CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
						ELSE
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
					END
					/* VALIDA SI EL CORRELATIVO ESTA OK */
					IF @PREFIJOFAC<>LEFT(@NVOCONSEC,LEN(@PREFIJOFAC))
					BEGIN
						PRINT 'Inconsistencia entre el prefijo de factura y el nro generado'
						RAISERROR('Inconsistencia entre el prefijo de factura y el nro generado',16,1)
						RETURN			
					END  

					/* Inserta a FTR TIPOFAC*/
					PRINT 'VOY A INSERTAR A FTR'
					INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
						VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
						IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
						TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
						INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
						IMPRESO, VALORSERVICIOS, VIVA, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
						MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
						CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CAPITADA,CODUNG, CODPRG, IDSEDE, RDIAN,CNSRESOL,IDFORMATO,CP_CONVENIO)
					SELECT @CNSFTR, @COMPANIA, 'C', CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  @IDTERCEROF END, 
						@NVOCONSEC, @FECHAFAC, @FECHAFAC + @DV,
						AUT.VALORTOTAL, NULL, NULL, LEFT(@MONEDA,2), NULL, 'P', NULL, 
						@IDAFILIADO, @USUARIO, @CONSECUTIVO,
						@PROCEDENCIA, 'I', '', @TV, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0,  AUT.VALORTOTAL - ROUND(AUT.VALORTOTAL*0.18,2), ROUND(AUT.VALORTOTAL*0.18,2), NULL, NULL, @USUARIO,
						DBO.FNK_GETDATE(), 1, 18, 0, AUT.IDPLAN, NULL, CASE WHEN @ESPARTPERU = 1 AND @TIPOFAC='Boleta' THEN 'N' ELSE 'C' END, NULL, NULL, NULL, @DATO3, @TTEC,
						@CUENTACXC,@CUENTACXC_RAD, 0 ,AUT.CODUNG, NULL, AUT.IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''),@IDFORMATOFTR,'Boleta'
					FROM AUT
					WHERE AUT.IDAUT = @IDAUT

					PRINT 'VOY A INSERTAR A FTRD ===>'
					INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
						IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
					SELECT @CNSFTR, ROW_NUMBER() OVER(ORDER BY AUTD.IDSERVICIO DESC)  , DBO.FNK_GETDATE(), 'DB', AUT.IDPLAN, NULL, AUTD.VALORTOTALCOSTO,
						NULL, AUT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, SER.IDSERVICIO, NULL, AUTD.CANTIDAD,
						 ROUND(AUTD.VALORTOTALCOSTO / 1.18,2), AUTD.VALOR, 0, 0, @USUARIO, @IDAUT,
						@IDAUT, 1, NULL, @NVOCONSEC, NULL, 0, @FECHA1,
						@IDIMPUESTO, @IDCLASE,1 , AUTD.VALORTOTALCOSTO, COALESCE(@PIVA,0), AUTD.VALORTOTALCOSTO - ROUND(AUTD.VALORTOTALCOSTO / 1.18,2),@CUENTA_FIMPDV 
					FROM AUTD  
					INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT
					INNER JOIN SER ON AUTD.IDSERVICIO = SER.IDSERVICIO
					WHERE
					AUTD.IDAUT = @IDAUT
					IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='MIFACT'
					BEGIN
						EXEC SPK_GENERA_JSON_PERU_FACTURA @NVOCONSEC
					END
					UPDATE FCJ SET N_FACTURA = @NVOCONSEC, RECAUDO = 1, USURECAUDO = @USUARIO WHERE FCJ.CNSFACJ = @CNSFACJ AND FCJ.CODCAJA = @CODCAJA

					UPDATE AUT SET N_FACTURA = @NVOCONSEC WHERE IDAUT = @IDAUT
					UPDATE AUTD SET NFACTURA = @NVOCONSEC WHERE IDAUT = @IDAUT
				END
				
				IF @PROCEDENCIA = 'AUT' --VR_TOTAL
				BEGIN
					SELECT @IDAFILIADO= AUT.IDAFILIADO, @IDPLAN = AUT.IDPLAN,@DESCUENTO = AUT.DESCUENTO,@CCOSTO=  AUT.CCOSTO
						, @IDAREA = AUT.IDAREA, @VR_TOTAL= FCJ.VALORTOTAL , @FECHA1=FCJ.FECHA  , @IDAUT = AUT.IDAUT
						, @ESPART = CASE WHEN AUT.IDTERCEROCA = DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') THEN 1 ELSE 0 END
					FROM AUT 
						INNER JOIN FCJ ON AUT.NORECIBOCAJA = FCJ.CNSFACJ AND AUT.CODCAJA = FCJ.CODCAJA
					WHERE AUT.NORECIBOCAJA = @CNSFACJ AND AUT.CODCAJA = @CODCAJA

					IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART2') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART3') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART4') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART5') OR 
						@EC = 1
					BEGIN
						PRINT 'PARTICULAR'
						SELECT @VENTAPRT=1
					END
					ELSE
					BEGIN
						SELECT @VENTAPRT=0
					END

					SELECT @PREFIJO = SER.PREFIJO, @IDSERVICIO = SER.IDSERVICIO, @DESCSERVICIO = SER.DESCSERVICIO 
					,@IDIMPUESTO = COALESCE(SER.IDIMPUESTO,NULL), @IDCLASE = COALESCE(SER.IDCLASE,NULL)
					,@PIVA = CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL)) ELSE NULL END
					,@CUENTA_FIMPDV =  CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL))  ELSE NULL END            
					FROM SER WHERE SER.IDSERVICIO = DBO.FNK_VALORVARIABLE('SER_HOSPI_AUT')

					SELECT @CUENTACXC = CUENTA, @CUENTACXC_RAD=CUENTARAD,@TTEC=TIPO FROM TTEC
					WHERE TIPO = DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART') 

					IF ISNULL(@DV,0) <= 0
						SET @DV = 30

					SELECT @TV = 'Contado' 
					SELECT @EC = 1
					SELECT @IDTERCEROF = @IDAFILIADO
					SELECT @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
					PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
					EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA,@PROCEDENCIA,@NOAUT
					PRINT 'SALGO DE SPK_INSERT_TERDEAFI 001 ==>'

					SELECT @ESPARTPERU = 1
					SELECT @IDTERCEROF=IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=(SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO=@IDAFILIADO ) 
					IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCEROF)
					BEGIN
						SELECT @IDTERCEROF=RUC FROM AFI WHERE IDAFILIADO=@IDAFILIADO
					END

					SELECT @OK = COALESCE(COUNT(*),0) FROM TER WHERE IDTERCERO = @IDTERCEROF
					PRINT 'ANTES DE IF OK = 0'       
					IF @OK = 0
					BEGIN
						SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
						PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
						EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
						PRINT 'SALGO DE SPK_INSERT_TERDEAFI 002 ==>'
					END

					/* GENERO CORRELATIVO DE BOLETA - FACTURA */
					EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
					SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0) 
					IF @TV = 'Contado'  AND @ESPARTPERU = 1 AND @TIPOFAC='Boleta'
					BEGIN
						PRINT 'AQUI LLAMO A BOLETA @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMERO_BOLETA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE BOLETA'
					END
					ELSE
					BEGIN
						PRINT 'AQUI LLAMO A NUMFACTURA  @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE NUMFACTURA'
					END
					PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
					PRINT '@NVOCONSEC='+@NVOCONSEC  

					IF ISNULL(@FECHAFAC,'') = ''
					BEGIN
						SELECT @FECHAFAC = GETDATE()
					END

					IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
					BEGIN
						IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA= CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
						ELSE
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
					END
					/* VALIDA SI EL CORRELATIVO ESTA OK */
					IF @PREFIJOFAC<>LEFT(@NVOCONSEC,LEN(@PREFIJOFAC))
					BEGIN
						PRINT 'Inconsistencia entre el prefijo de factura y el nro generado'
						RAISERROR('Inconsistencia entre el prefijo de factura y el nro generado',16,1)
						RETURN			
					END  

					/* Inserta a FTR TIPOFAC*/--VALORSERVICIOS IDSEDE PREFIJODIANFE CNSFCT
					PRINT 'VOY A INSERTAR A FTR'
					INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
						VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
						IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
						TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
						INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
						IMPRESO, VALORSERVICIOS, VIVA, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
						MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
						CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CAPITADA,CODUNG, CODPRG, IDSEDE, RDIAN,CNSRESOL,IDFORMATO,CP_CONVENIO
						,CNSRESOLFE, PREFIJODIANFE, CNSDIANFE)
					SELECT @CNSFTR, @COMPANIA, 'C', CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  @IDTERCEROF END, 
						@NVOCONSEC, @FECHAFAC, @FECHAFAC + @DV,
						AUT.VALORTOTAL, NULL, NULL, LEFT(@MONEDA,2), NULL, 'P', NULL, 
						@IDAFILIADO, @USUARIO, @CONSECUTIVO,
						'CE', 'I', '', @TV, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0,  AUT.VALORTOTAL
						--, ROUND(AUT.VALORTOTAL*0.18,2)
						,CASE COALESCE(@VENTAPRT,0) WHEN 1 THEN AUT.VALORTOTAL - (AUT.VALORTOTAL/1.18)
                                                                                      ELSE AUT.VALORCOPAGO - (VALORCOPAGO/1.18 )
																  END
						, NULL, NULL, @USUARIO,
						DBO.FNK_GETDATE(), 1, 18, 0, AUT.IDPLAN, NULL, CASE WHEN @ESPARTPERU = 1 AND @TIPOFAC='Boleta' THEN 'N' ELSE 'C' END, NULL, NULL, NULL, @DATO3, @TTEC,
						@CUENTACXC,@CUENTACXC_RAD, 0 ,AUT.CODUNG, NULL, @IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''),@IDFORMATOFTR,'Boleta'
						,COALESCE(@CNSRESOL,''), @PREFIJOFAC, @CNSFTR
					FROM AUT
					WHERE AUT.IDAUT = @IDAUT
					--VLRIMPUESTO VALOR
					PRINT 'VOY A INSERTAR A FTRD ===>'
					INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
						IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
					SELECT @CNSFTR, ROW_NUMBER() OVER(ORDER BY AUTD.IDSERVICIO DESC)  , DBO.FNK_GETDATE(), 'DB', AUT.IDPLAN, NULL, AUTD.VALOR,
						NULL, AUT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, SER.IDSERVICIO, NULL, AUTD.CANTIDAD,
						 ROUND(AUTD.VALOR/1.18,2), AUTD.VALOR, 0, 0, @USUARIO, @IDAUT,
						@IDAUT, 1, NULL, @NVOCONSEC, NULL, 0, @FECHA1,
						@IDIMPUESTO, @IDCLASE,AUTD.NO_ITEM , NULL, COALESCE(@PIVA,0), AUTD.VALOR - ROUND(AUTD.VALOR/1.18,2) ,@CUENTA_FIMPDV 
					FROM AUTD  
					INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT
					INNER JOIN SER ON AUTD.IDSERVICIO = SER.IDSERVICIO
					WHERE
					AUTD.IDAUT = @IDAUT

					UPDATE FCJ SET N_FACTURA = @NVOCONSEC, RECAUDO = 1, USURECAUDO = @USUARIO WHERE FCJ.CNSFACJ = @CNSFACJ AND FCJ.CODCAJA = @CODCAJA

					UPDATE AUT SET N_FACTURA = @NVOCONSEC, FACTURADA = 1 WHERE IDAUT = @IDAUT
					UPDATE AUTD SET NFACTURA = @NVOCONSEC WHERE IDAUT = @IDAUT
					IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='MIFACT'
					BEGIN
						EXEC SPK_GENERA_JSON_PERU_FACTURA @NVOCONSEC
					END IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP'
					BEGIN
						EXEC SPK_JSON_FTR_PERU_INTERFAX @NVOCONSEC
					END
				END
				IF @PROCEDENCIA = 'LIST'
				BEGIN
					SELECT @IDAFILIADO= AUT.IDAFILIADO, @IDPLAN = AUT.IDPLAN,@DESCUENTO = AUT.DESCUENTO,@CCOSTO=  AUT.CCOSTO
						, @IDAREA = AUT.IDAREA, @VR_TOTAL= FCJ.VALORTOTAL , @FECHA1=FCJ.FECHA  , @IDAUT = AUT.IDAUT
						, @ESPART = CASE WHEN AUT.IDTERCEROCA = DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') THEN 1 ELSE 0 END
					FROM AUT 
						INNER JOIN FCJ ON AUT.NORECIBOCAJA = FCJ.CNSFACJ AND AUT.CODCAJA = FCJ.CODCAJA
					WHERE AUT.NORECIBOCAJA = @CNSFACJ AND AUT.CODCAJA = @CODCAJA
					--IDTERCERO
					IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART2') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART3') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART4') OR 
						@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART5') OR 
						@EC = 1
					BEGIN
						PRINT 'PARTICULAR'
						SELECT @VENTAPRT=1
					END
					ELSE
					BEGIN
						SELECT @VENTAPRT=0
					END


					--SELECT @PREFIJO = SER.PREFIJO, @IDSERVICIO = SER.IDSERVICIO, @DESCSERVICIO = SER.DESCSERVICIO 
					--,@IDIMPUESTO = COALESCE(SER.IDIMPUESTO,NULL), @IDCLASE = COALESCE(SER.IDCLASE,NULL)
					--,@PIVA = CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL)) ELSE NULL END
					--,@CUENTA_FIMPDV =  CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL))  ELSE NULL END            
					--FROM SER WHERE SER.IDSERVICIO = DBO.FNK_VALORVARIABLE('SER_HOSPI_AUT')
					SELECT @PIVA = 18

					SELECT @CUENTACXC = CUENTA, @CUENTACXC_RAD=CUENTARAD,@TTEC=TIPO FROM TTEC
					WHERE TIPO = DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART') 

					IF ISNULL(@DV,0) <= 0
						SET @DV = 30

					SELECT @TV = 'Contado' 
					SELECT @EC = 1
					SELECT @IDTERCEROF = @IDAFILIADO
					SELECT @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
					PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
					EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA,@PROCEDENCIA,@NOAUT
					PRINT 'SALGO DE SPK_INSERT_TERDEAFI 001 ==>'

					SELECT @ESPARTPERU = 1
					SELECT @IDTERCEROF=IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=(SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO=@IDAFILIADO ) 
					IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCEROF)
					BEGIN
						SELECT @IDTERCEROF=RUC FROM AFI WHERE IDAFILIADO=@IDAFILIADO
					END

					SELECT @OK = COALESCE(COUNT(*),0) FROM TER WHERE IDTERCERO = @IDTERCEROF
					PRINT 'ANTES DE IF OK = 0'       
					IF @OK = 0
					BEGIN
						SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
						PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
						EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
						PRINT 'SALGO DE SPK_INSERT_TERDEAFI 002 ==>'
					END

					/* GENERO CORRELATIVO DE BOLETA - FACTURA */
					EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
					SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0) 
					IF @TV = 'Contado'  AND @ESPARTPERU = 1 AND @TIPOFAC='Boleta'
					BEGIN
						PRINT 'AQUI LLAMO A BOLETA @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMERO_BOLETA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE BOLETA'
					END
					ELSE
					BEGIN
						PRINT 'AQUI LLAMO A NUMFACTURA  @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE NUMFACTURA'
					END
					PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
					PRINT '@NVOCONSEC='+@NVOCONSEC  

					IF ISNULL(@FECHAFAC,'') = ''
					BEGIN
						SELECT @FECHAFAC = GETDATE()
					END

					IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
					BEGIN
						IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA= CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
						ELSE
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
					END
					/* VALIDA SI EL CORRELATIVO ESTA OK */
					IF @PREFIJOFAC<>LEFT(@NVOCONSEC,LEN(@PREFIJOFAC))
					BEGIN
						PRINT 'Inconsistencia entre el prefijo de factura y el nro generado'
						RAISERROR('Inconsistencia entre el prefijo de factura y el nro generado',16,1)
						RETURN			
					END  

					/* Inserta a FTR TIPOFAC*/--VALORSERVICIOS IDSEDE PREFIJODIANFE CNSFCT
					PRINT 'VOY A INSERTAR A FTR'
					INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
						VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
						IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
						TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
						INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
						IMPRESO, VALORSERVICIOS, VIVA, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
						MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
						CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CAPITADA,CODUNG, CODPRG, IDSEDE, RDIAN,CNSRESOL,IDFORMATO,CP_CONVENIO
						,CNSRESOLFE, PREFIJODIANFE, CNSDIANFE)
					SELECT @CNSFTR, @COMPANIA, 'C', CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  @IDTERCEROF END, 
						@NVOCONSEC, @FECHAFAC, @FECHAFAC + @DV,
						AUT.VALORCOPAGO, NULL, NULL, LEFT(@MONEDA,2), NULL, 'P', NULL, 
						@IDAFILIADO, @USUARIO, @CONSECUTIVO,
						'CE', 'I', '', @TV, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0,  AUT.VALORCOPAGO
						--, ROUND(AUT.VALORTOTAL*0.18,2)
						--,CASE COALESCE(@VENTAPRT,0) WHEN 1 THEN AUT.VALORTOTAL - (AUT.VALORTOTAL/1.18)
      --                                                                                ELSE AUT.VALORCOPAGO - (VALORCOPAGO/1.18 )
						--										  END
						,AUT.VALORCOPAGO - ROUND(AUT.VALORCOPAGO/1.18,2)
						, NULL, NULL, @USUARIO,
						DBO.FNK_GETDATE(), 1, 18, 0, AUT.IDPLAN, NULL, CASE WHEN @ESPARTPERU = 1 AND @TIPOFAC='Boleta' THEN 'N' ELSE 'C' END, NULL, NULL, NULL, @DATO3, @TTEC,
						@CUENTACXC,@CUENTACXC_RAD, 0 ,AUT.CODUNG, NULL, @IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''),@IDFORMATOFTR,'Boleta'
						,COALESCE(@CNSRESOL,''), @PREFIJOFAC, @CNSFTR
					FROM AUT
					WHERE AUT.IDAUT = @IDAUT
					--IDIMPUESTO VALOR
					IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP'
					BEGIN
						PRINT 'VOY A INSERTAR A FTRD ===>'
						INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
							IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
							VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
							NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
							IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV,
                  VALOR_UNITARIO_SIN_IGV, VALOR_IGV_UNITARIO, VALOR_UNITARIO_CON_IGV, VALOR_COPAGO_UNIT_SIN_IGV, VALOR_COPAGO_IGV_UNIT, VALOR_COPAGO_TOTAL_SIN_IGV)
						SELECT @CNSFTR, ROW_NUMBER() OVER(ORDER BY AUTD.IDSERVICIO DESC)  , DBO.FNK_GETDATE(), 'DB', AUT.IDPLAN, NULL, AUTD.VALORCOPAGO,
							NULL, AUT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, SER.IDSERVICIO, NULL, AUTD.CANTIDAD,
							 ROUND(AUTD.VALORCOPAGO/1.18,2), AUTD.VALORCOPAGO, 0, 0, @USUARIO, @IDAUT,
							@IDAUT, 1, NULL, @NVOCONSEC, NULL, 0, @FECHA1,
							SER.IDIMPUESTO, SER.IDCLASE,AUTD.NO_ITEM , AUTD.VALORCOPAGO - (AUTD.VALORCOPAGO - ROUND(AUTD.VALORCOPAGO/1.18,2)) 
							, CASE WHEN COALESCE(SER.IVA,'')='SER' THEN @PIVA ELSE NULL END, AUTD.VALORCOPAGO - ROUND(AUTD.VALORCOPAGO/1.18,2) ,@CUENTA_FIMPDV,
                     AUTD.VALOR_UNITARIO_SIN_IGV, AUTD.VALOR_IGV_UNITARIO, AUTD.VALOR_UNITARIO_CON_IGV, AUTD.VALOR_COPAGO_UNIT_SIN_IGV, AUTD.VALOR_COPAGO_IGV_UNIT, AUTD.VALOR_COPAGO_TOTAL_SIN_IGV
						FROM AUTD  
							INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT
							INNER JOIN SER ON AUTD.IDSERVICIO = SER.IDSERVICIO
						WHERE
						AUTD.IDAUT = @IDAUT AND COALESCE(AUTD.VALORCOPAGO,0) > 0

						SELECT @VRTOTAL = SUM(VR_TOTAL), @VRSERV = SUM(VLR_SERVICI),@VRCOPA = SUM(VLR_COPAGOS)  ,
							@VRPACO  = SUM(VLR_PAGCOMP)
						FROM FTRD WHERE N_FACTURA = @NVOCONSEC

						SELECT @VALOR_SERVICIOS_SIN_IGV = CONVERT(DECIMAL(14,2), SUM(VALOR_COPAGO_TOTAL_SIN_IGV)) FROM FTRD WHERE N_FACTURA = @NVOCONSEC

						UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = ROUND(@VRCOPA,0), VALORPCOMP = @VRPACO,
								DESCUENTO = 0, VALOR_SERVICIOS_SIN_IGV =@VALOR_SERVICIOS_SIN_IGV                
						WHERE N_FACTURA = @NVOCONSEC

						SELECT @VIVA = CONVERT(DECIMAL(14,2), (@VALOR_SERVICIOS_SIN_IGV * 0.18))
         
						UPDATE FTR SET VR_TOTAL = CONVERT(DECIMAL(14,2), @VALOR_SERVICIOS_SIN_IGV + @VIVA), VIVA = @VIVA
							WHERE  N_FACTURA = @NVOCONSEC
					END
					ELSE
					BEGIN
						PRINT 'VOY A INSERTAR A FTRD ===>'
						INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
							IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
							VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
							NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
							IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
						SELECT @CNSFTR, ROW_NUMBER() OVER(ORDER BY AUTD.IDSERVICIO DESC)  , DBO.FNK_GETDATE(), 'DB', AUT.IDPLAN, NULL, AUTD.VALORCOPAGO,
							NULL, AUT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, SER.IDSERVICIO, NULL, AUTD.CANTIDAD,
							 ROUND(AUTD.VALORCOPAGO/1.18,2), AUTD.VALORCOPAGO, 0, 0, @USUARIO, @IDAUT,
							@IDAUT, 1, NULL, @NVOCONSEC, NULL, 0, @FECHA1,
							SER.IDIMPUESTO, SER.IDCLASE,AUTD.NO_ITEM , AUTD.VALORCOPAGO - (AUTD.VALORCOPAGO - ROUND(AUTD.VALORCOPAGO/1.18,2)) 
							, CASE WHEN COALESCE(SER.IVA,'')='SER' THEN @PIVA ELSE NULL END, AUTD.VALORCOPAGO - ROUND(AUTD.VALORCOPAGO/1.18,2) ,@CUENTA_FIMPDV 
						FROM AUTD  
						INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT
						INNER JOIN SER ON AUTD.IDSERVICIO = SER.IDSERVICIO
						WHERE
						AUTD.IDAUT = @IDAUT AND COALESCE(AUTD.VALORCOPAGO,0) > 0
					END

					UPDATE FCJ SET N_FACTURA = @NVOCONSEC, RECAUDO = 1, USURECAUDO = @USUARIO WHERE FCJ.CNSFACJ = @CNSFACJ AND FCJ.CODCAJA = @CODCAJA

					--SELECT @ESPART
					UPDATE AUT SET  FACTURADA = 1 WHERE IDAUT = @IDAUT
					UPDATE AUTD SET NFACTURA = @NVOCONSEC WHERE IDAUT = @IDAUT AND COALESCE(AUTD.VALORCOPAGO,0) > 0
					
					IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='MIFACT'
					BEGIN
						EXEC SPK_GENERA_JSON_PERU_FACTURA @NVOCONSEC
					END
					ELSE IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP'
					BEGIN
						EXEC SPK_JSON_FTR_PERU_INTERFAX @NVOCONSEC
					END
				END
				IF @PROCEDENCIA IN ( 'INVENTARIO' , 'APOYO')
				BEGIN
					SELECT @IDAFILIADO= AUT.IDAFILIADO, @IDPLAN = AUT.IDPLAN,@DESCUENTO = AUT.DESCUENTO,@CCOSTO=  AUT.CCOSTO
						, @IDAREA = AUT.IDAREA, @VR_TOTAL= FCJ.VALORTOTAL , @FECHA1=FCJ.FECHA  , @IDAUT = AUT.IDAUT, @NOAUT = AUT.NOAUT
						, @ESPART = CASE WHEN AUT.IDTERCEROCA = DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') AND AUT.IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART') THEN 1 ELSE 0 END
					FROM AUT 
						INNER JOIN FCJ ON AUT.NORECIBOCAJA = FCJ.CNSFACJ AND AUT.CODCAJA = FCJ.CODCAJA
					WHERE AUT.NORECIBOCAJA = @CNSFACJ AND AUT.CODCAJA = @CODCAJA

					SELECT @PREFIJO = SER.PREFIJO, @IDSERVICIO = SER.IDSERVICIO, @DESCSERVICIO = SER.DESCSERVICIO 
					,@IDIMPUESTO = COALESCE(SER.IDIMPUESTO,NULL), @IDCLASE = COALESCE(SER.IDCLASE,NULL)
					,@PIVA = CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL)) ELSE NULL END
					,@CUENTA_FIMPDV =  CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),@VR_TOTAL))  ELSE NULL END            
					FROM SER WHERE SER.IDSERVICIO = DBO.FNK_VALORVARIABLE('SER_HOSPI_AUT')

					SELECT @CUENTACXC = CUENTA, @CUENTACXC_RAD=CUENTARAD,@TTEC=TIPO FROM TTEC
					WHERE TIPO = DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART') 

					IF ISNULL(@DV,0) <= 0
						SET @DV = 30

					SELECT @TV = 'Contado' 
					SELECT @EC = 1
					SELECT @IDTERCEROF = @IDAFILIADO
					SELECT @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
					PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
					EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA,@PROCEDENCIA,@NOAUT
					PRINT 'SALGO DE SPK_INSERT_TERDEAFI 001 ==>'

					SELECT @ESPARTPERU = @ESPART
					SELECT @IDTERCEROF=IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=( 
						SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO=@IDAFILIADO ) 
					IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCEROF)
					BEGIN
						SELECT @IDTERCEROF=RUC FROM AFI WHERE IDAFILIADO=@IDAFILIADO
					END

					SELECT @OK = COALESCE(COUNT(*),0) FROM TER WHERE IDTERCERO = @IDTERCEROF
					PRINT 'ANTES DE IF OK = 0'       
					IF @OK = 0
					BEGIN
						SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
						PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
						EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
						PRINT 'SALGO DE SPK_INSERT_TERDEAFI 002 ==>'
					END

					/* GENERO CORRELATIVO DE BOLETA - FACTURA */
					EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
					SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0) 
					IF @TV = 'Contado'  AND @ESPARTPERU = 0 AND @TIPOFAC='Boleta'
					BEGIN
						PRINT 'AQUI LLAMO A BOLETA @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMERO_BOLETA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE BOLETA'
					END
					ELSE
					BEGIN
						PRINT 'AQUI LLAMO A NUMFACTURA  @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
						SET @NVOCONSEC = SPACE(20)
						EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
						PRINT 'REGRESE DE NUMFACTURA'
					END
					PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
					PRINT '@NVOCONSEC='+@NVOCONSEC  

					IF ISNULL(@FECHAFAC,'') = ''
					BEGIN
						SELECT @FECHAFAC = GETDATE()
					END


--query2
--query2
					IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
					BEGIN
						IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA= CASE WHEN @ESPARTPERU= 0 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
						ELSE
						BEGIN
							SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = CASE WHEN @ESPARTPERU= 0 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
						END
					END
					/* VALIDA SI EL CORRELATIVO ESTA OK */
					IF @PREFIJOFAC<>LEFT(@NVOCONSEC,LEN(@PREFIJOFAC))
					BEGIN
						PRINT 'Inconsistencia entre el prefijo de factura y el nro generado'
						RAISERROR('Inconsistencia entre el prefijo de factura y el nro generado',16,1)
						RETURN			
					END  

					/* Inserta a FTR TIPOFAC*/
					PRINT 'VOY A INSERTAR A FTR' --VIVA--VR_TOTAL
					INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
						VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
						IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
						TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
						INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
						IMPRESO, VALORSERVICIOS, VIVA, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
						MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
						CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CAPITADA,CODUNG, CODPRG, IDSEDE, RDIAN,CNSRESOL,IDFORMATO,CP_CONVENIO)
					SELECT @CNSFTR, @COMPANIA, 'C', CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  @IDTERCEROF END, 
						@NVOCONSEC, @FECHAFAC, @FECHAFAC + @DV,
						AUT.VALORTOTAL, NULL, NULL, LEFT(@MONEDA,2), NULL, 'P', NULL, 
						@IDAFILIADO, @USUARIO, @NOAUT,
						'CE', 'I', '', @TV, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0,  AUT.VALORTOTAL - ROUND(AUT.VALORTOTAL*0.18,2), 0, NULL, NULL, @USUARIO,
						DBO.FNK_GETDATE(), 1, 18, 0, AUT.IDPLAN, NULL, CASE WHEN @ESPARTPERU = 0 AND @TIPOFAC='Boleta' THEN 'N' ELSE 'C' END, NULL, NULL, NULL, @DATO3, @TTEC,
						@CUENTACXC,@CUENTACXC_RAD, 0 ,AUT.CODUNG, NULL, AUT.IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''),@IDFORMATOFTR,'Boleta'
					FROM AUT
					WHERE AUT.IDAUT = @IDAUT

					PRINT 'VOY A INSERTAR A FTRD ===>'
					INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
						IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
					SELECT @CNSFTR, ROW_NUMBER() OVER(ORDER BY AUTD.IDSERVICIO DESC)  , DBO.FNK_GETDATE(), 'DB', AUT.IDPLAN, NULL,
					CASE @ESPART WHEN 0 THEN (CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.VALORCOPAGO + AUTD.VALORCOPAGO*0.18) ELSE (AUTD.VALORCOPAGO ) END )  
										ELSE ( CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.VALOREXCEDENTE + AUTD.VALOREXCEDENTE*0.18) ELSE (AUTD.VALOREXCEDENTE ) END  ) END  ,
						NULL, AUT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, SER.IDSERVICIO, NULL, AUTD.CANTIDAD,
						  AUTD.VALORCOPAGO, CASE @ESPART WHEN 0 THEN (CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.VALORCOPAGO + AUTD.VALORCOPAGO*0.18) ELSE (AUTD.VALORCOPAGO ) END )  
																ELSE ( CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.VALOREXCEDENTE + AUTD.VALOREXCEDENTE*0.18) ELSE (AUTD.VALOREXCEDENTE ) END  ) END
						  , 0, 0, @USUARIO, @IDAUT,
						@IDAUT, COALESCE(AUTD.NO_ITEM, 0) , NULL, @NVOCONSEC, NULL, 0, @FECHA1,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDIMPUESTO ELSE NULL END, 
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  SER.IDCLASE ELSE NULL END,
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT ITEM FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),AUTD.VALORCOPAGO)) ELSE 0 END , 
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  AUTD.VALORCOPAGO  ELSE 0 END, 
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT VALOR FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(), AUTD.VALORCOPAGO)) ELSE 0 END, 
						CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (AUTD.VALORCOPAGO*0.18) ELSE 0 END
						,CASE WHEN COALESCE(SER.IVA,'')='SER' THEN  (SELECT CUENTA FROM  DBO.FNK_VALOR_IMPUESTO(SER.IDIMPUESTO,SER.IDCLASE,GETDATE(),AUTD.VALORCOPAGO)) ELSE NULL END 
					FROM AUTD  
					INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT
					INNER JOIN SER ON AUTD.IDSERVICIO = SER.IDSERVICIO
					WHERE
					AUTD.IDAUT = @IDAUT 
					--AND COALESCE( CASE WHEN @ESPART = 1 THEN AUTD.VALOREXCEDENTE ELSE   AUTD.VALORCOPAGO END   ,0) > 0

					IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='MIFACT'
					BEGIN
						EXEC SPK_GENERA_JSON_PERU_FACTURA @NVOCONSEC
					END

					UPDATE FCJ SET N_FACTURA = @NVOCONSEC, RECAUDO = 1, USURECAUDO = @USUARIO WHERE FCJ.CNSFACJ = @CNSFACJ AND FCJ.CODCAJA = @CODCAJA
					IF @ESPART = 0
						UPDATE AUTD SET NFACTURA = @NVOCONSEC WHERE IDAUT = @IDAUT AND COALESCE(AUTD.VALORCOPAGO,0)>0
					IF @ESPART = 1
					BEGIN
						UPDATE AUTD SET N_FACTURA = @NVOCONSEC, FACTURADA = 1 WHERE IDAUT = @IDAUT
						UPDATE AUT SET N_FACTURA = @NVOCONSEC, FACTURADA = 1  WHERE IDAUT = @IDAUT
					END

					SELECT @VRTOTAL = SUM(VR_TOTAL), @VRSERV = SUM(VLR_SERVICI),@VRCOPA = MAX(AUT.VALORCOPAGO) ,
							@VRPACO  = SUM(VLR_PAGCOMP)
					FROM FTRD INNER JOIN AUT ON AUT.IDAUT=FTRD.NOPRESTACION
					WHERE FTRD.N_FACTURA = @NVOCONSEC
					SELECT @VIVA=SUM(COALESCE(VIVA,0)) FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  

					IF @VIVA>0
					BEGIN
						SELECT TOP 1 @PIVA=PIVA ,@MIVA=1 FROM FTRD WHERE FTRD.N_FACTURA = @NVOCONSEC  AND COALESCE(PIVA,0)<>0            
						UPDATE FTR SET MIVA=@MIVA,PIVA=@PIVA,VIVA=@VIVA WHERE N_FACTURA = @NVOCONSEC
					END
					UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = ROUND(@VRCOPA,0), VALORPCOMP = @VRPACO, DESCUENTO = 0
					WHERE N_FACTURA = @NVOCONSEC
					IF @PROCEDENCIA = 'INVENTARIO'
					BEGIN
						UPDATE FTR SET VR_TOTAL = COALESCE(VALORSERVICIOS,0) - COALESCE(VALORCOPAGO,0) - COALESCE(VALORPCOMP,0) - COALESCE(DESCUENTO,0) - COALESCE(VR_ABONOS,0)--+CASE WHEN @BASE_IVA_SER='CONIVA' THEN 0 ELSE  COALESCE(@VIVA,0) END                      
						WHERE  N_FACTURA = @NVOCONSEC 
					END
					IF @PROCEDENCIA = 'APOYO'
					BEGIN
						SELECT @VALORCOPAGO = SUM(FTRD.VALOR) FROM FTRD WHERE  N_FACTURA = @NVOCONSEC 
						UPDATE FTR SET VR_TOTAL = VALORSERVICIOS, VALORCOPAGO = @VALORCOPAGO WHERE  N_FACTURA = @NVOCONSEC 
					END

				END
				IF @PROCEDENCIA = 'MAD'
				BEGIN
					PRINT 'VOY A FACTURA PERU ===>'
					EXEC SPK_FACTURACE_PERU_COPA @CONSECUTIVO, @DPR,'01',@SEDE,@USUARIO,'', '', '', '', '','CI','','FALSE', NULL, @FECHAFACT,@TIPOFAC,  @IDTERCERO, @CNSFACJ, @CODCAJA

					IF DBO.FNK_VALORVARIABLE('FCJ_AUTOMATICO') = 'SI'
					BEGIN
						EXEC SPK_CIERRERECIBO_CAJA @CODCAJA, @CNSFACJ, @COMPANIA, @IDSEDE, @USUARIO, @SYS_COMPUTERNAME
						EXEC SPK_ACTUALIZA_SALDO_BANCO @CNSFACJ, @CODCAJA
						EXEC SPK_NC_CONTAB_CAJA_ING @CNSFACJ, @CODCAJA, @USUARIO, @SYS_COMPUTERNAME, @COMPANIA, @IDSEDE, @NROCOMPROBANTE
					END

				END
				IF @PROCEDENCIA = 'HPREP'
				BEGIN
               PRINT 'VOY A SPK_FACTURAPHD_PERU_COPA ===>'
               EXEC SPK_FACTURAPHD_PERU_COPA @CONSECUTIVO, @DPR,'01',@SEDE,@USUARIO,'HPREP', @FECHAFACT,@TIPOFAC,  @IDTERCERO, @CNSFACJ, @CODCAJA

					--SELECT @IDAFILIADO= HADM.IDAFILIADO, @IDPLAN = HADM.IDPLAN,@DESCUENTO = HADM.DESCUENTO,@CCOSTO=  FCJ.CCOSTO
					--	, @IDAREA = '', @VR_TOTAL= FCJ.VALORTOTAL , @FECHA1=FCJ.FECHA  , @IDAUT = HPREP.NOPRESUPUESTO
					--	, @ESPART = CASE WHEN HADM.IDTERCERO = DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') THEN 1 ELSE 0 END
     --             , @IDPROVEEDOR = COALESCE(HCA.IDMEDICO, DBO.FNK_VALORVARIABLE('EPI_MEDICODEFAULT'))
					--FROM HPREP
					--	INNER JOIN HADM ON HPREP.NOADMISION = HADM.NOADMISION
					--	INNER JOIN AFI ON HADM.IDAFILIADO = AFI.IDAFILIADO
					--	INNER JOIN FCJ ON HPREP.NORECIBOCAJA = FCJ.CNSFACJ AND HPREP.CODCAJA = FCJ.CODCAJA
     --             LEFT JOIN HCA ON HPREP.CONSECUTIVOHCA=HCA.CONSECUTIVO
					--WHERE HPREP.NORECIBOCAJA = @CNSFACJ AND HPREP.CODCAJA = @CODCAJA
					----IDTERCERO
					--IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART') OR 
					--	@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART2') OR 
					--	@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART3') OR 
					--	@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART4') OR 
					--	@IDPLAN = DBO.FNK_VALORVARIABLE('IDPLANPART5') OR 
					--	@EC = 1
					--BEGIN
					--	PRINT 'PARTICULAR'
					--	SELECT @VENTAPRT=1
					--END
					--ELSE
					--BEGIN
					--	SELECT @VENTAPRT=0
					--END

					--SELECT @PIVA = 18

					--SELECT @CUENTACXC = CUENTA, @CUENTACXC_RAD=CUENTARAD,@TTEC=TIPO FROM TTEC
					--WHERE TIPO = DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART') 

					--IF ISNULL(@DV,0) <= 0
					--	SET @DV = 30

					--SELECT @TV = 'Contado' 
					--SELECT @EC = 1
					--SELECT @IDTERCEROF = @IDAFILIADO
					--SELECT @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
					--PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
					--EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA,@PROCEDENCIA,@NOAUT
					--PRINT 'SALGO DE SPK_INSERT_TERDEAFI 001 ==>'

					--SELECT @ESPARTPERU = 1
					--SELECT @IDTERCEROF=IDTERCERO FROM TER WHERE ESTADO='Activo' AND NIT=(SELECT DOCIDAFILIADO FROM AFI WHERE IDAFILIADO=@IDAFILIADO ) 
					--IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCEROF)
					--BEGIN
					--	SELECT @IDTERCEROF=RUC FROM AFI WHERE IDAFILIADO=@IDAFILIADO
					--END

					--SELECT @OK = COALESCE(COUNT(*),0) FROM TER WHERE IDTERCERO = @IDTERCEROF
					--PRINT 'ANTES DE IF OK = 0'       
					--IF @OK = 0
					--BEGIN
					--	SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
					--	PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
					--	EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
					--	PRINT 'SALGO DE SPK_INSERT_TERDEAFI 002 ==>'
					--END

					--/* GENERO CORRELATIVO DE BOLETA - FACTURA */
					--EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
					--SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0) 
					--IF @TV = 'Contado'  AND @ESPARTPERU = 1 AND @TIPOFAC='Boleta'
					--BEGIN
					--	PRINT 'AQUI LLAMO A BOLETA @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
					--	SET @NVOCONSEC = SPACE(20)
					--	EXEC SPK_GENNUMERO_BOLETA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
					--	PRINT 'REGRESE DE BOLETA'
					--END
					--ELSE
					--BEGIN
					--	PRINT 'AQUI LLAMO A NUMFACTURA  @COMPANIA='+COALESCE(@COMPANIA,'SIN COMPANIA')+' @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')         
					--	SET @NVOCONSEC = SPACE(20)
					--	EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
					--	PRINT 'REGRESE DE NUMFACTURA'
					--END
					--PRINT 'CNSFCT ='+@CNSFTR+' - N_FACTURA = ' + @NVOCONSEC
					--PRINT '@NVOCONSEC='+@NVOCONSEC  

					--IF ISNULL(@FECHAFAC,'') = ''
					--BEGIN
					--	SELECT @FECHAFAC = GETDATE()
					--END

					--IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
					--BEGIN
					--	IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
					--	BEGIN
					--		SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA= CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
					--	END
					--	ELSE
					--	BEGIN
					--		SELECT  @CNSRESOL=CNSRESOL,@PREFIJOFAC=PREFIJO  FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = CASE WHEN @ESPARTPERU= 1 AND @TIPOFAC='Boleta' THEN 'BOLE' ELSE 'FTR' END
					--	END
					--END
					--/* VALIDA SI EL CORRELATIVO ESTA OK */
					--IF @PREFIJOFAC<>LEFT(@NVOCONSEC,LEN(@PREFIJOFAC))
					--BEGIN
					--	PRINT 'Inconsistencia entre el prefijo de factura y el nro generado'
					--	RAISERROR('Inconsistencia entre el prefijo de factura y el nro generado',16,1)
					--	RETURN			
					--END  
					----VR_TOTAL, VALORSERVICIOS, PIVA, VIVA
					--/* Inserta a FTR TIPOFAC*/--VALORSERVICIOS IDSEDE PREFIJODIANFE CNSFCT
					--PRINT 'VOY A INSERTAR A FTR'
					--INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
					--	VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
					--	IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
					--	TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
					--	INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
					--	IMPRESO, VALORSERVICIOS, VIVA, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
					--	MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
					--	CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CAPITADA,CODUNG, CODPRG, IDSEDE, RDIAN,CNSRESOL,IDFORMATO,CP_CONVENIO
					--	,CNSRESOLFE, PREFIJODIANFE, CNSDIANFE)
					--SELECT @CNSFTR, @COMPANIA, 'C', CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  @IDTERCEROF END, 
					--	@NVOCONSEC, @FECHAFAC, @FECHAFAC + @DV,
					--	HPREP.VALORCOPAGO, NULL, NULL, LEFT(@MONEDA,2), NULL, 'P', NULL, 
					--	@IDAFILIADO, @USUARIO, @CONSECUTIVO,
					--	'HPREP', 'I', '', @TV, 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0,  HPREP.VALORCOPAGO
					--	,HPREP.VALORCOPAGO - ROUND(HPREP.VALORCOPAGO/1.18,2)
					--	, NULL, NULL, @USUARIO,
					--	DBO.FNK_GETDATE(), 1, 18, 0, HADM.IDPLAN, NULL, CASE WHEN @ESPARTPERU = 1 AND @TIPOFAC='Boleta' THEN 'N' ELSE 'C' END, NULL, NULL, NULL, @DATO3, @TTEC,
					--	@CUENTACXC,@CUENTACXC_RAD, 0 ,HADM.CODUNG, NULL, @IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''),@IDFORMATOFTR, @TIPOFAC
					--	,COALESCE(@CNSRESOL,''), @PREFIJOFAC, @CNSFTR
					--FROM HPREP
					--INNER JOIN HADM ON HPREP.NOADMISION = HADM.NOADMISION
					--INNER JOIN AFI ON HADM.IDAFILIADO = AFI.IDAFILIADO
					--WHERE HPREP.NOPRESUPUESTO = @IDAUT
					----VR_TOTAL, CANTIDAD, VALOR, VLR_SERVICI, IDIMPUESTO, IDCLASE, VLRIMPUESTO, PIVA, VIVA
					--PRINT 'VOY A INSERTAR A FTRD ===>'
					--INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
					--	IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
					--	VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
					--	NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
					--	IDIMPUESTO, IDCLASE,ITEM , VLRIMPUESTO, PIVA, VIVA,CUENTA_FIMPDV)
					--SELECT @CNSFTR, ROW_NUMBER() OVER(ORDER BY HPREPD.IDSERVICIO DESC)  , DBO.FNK_GETDATE(), 'DB', HADM.IDPLAN, NULL, HPREPD.VALORCOPAGO,
					--	NULL, NULL, SER.PREFIJO, SER.DESCSERVICIO, SER.IDSERVICIO, NULL, HPREPD.CANTIDAD,
					--	 ROUND(HPREPD.VALORCOPAGO/HPREPD.CANTIDAD,2), HPREPD.VALORCOPAGO, 0, 0, @IDPROVEEDOR, @IDAUT,
					--	@IDAUT, 1, NULL, @NVOCONSEC, NULL, 0, @FECHA1,
					--	SER.IDIMPUESTO, SER.IDCLASE,HPREPD.NO_ITEM , HPREPD.VALORCOPAGO - (HPREPD.VALORCOPAGO - ROUND(HPREPD.VALORCOPAGO/1.18,2)) 
					--	, CASE WHEN COALESCE(SER.IVA,'')='SER' THEN @PIVA ELSE NULL END, HPREPD.VALORCOPAGO - ROUND(HPREPD.VALORCOPAGO/1.18,2) ,@CUENTA_FIMPDV 
					--FROM HPREPD  
					--INNER JOIN SER ON HPREPD.IDSERVICIO = SER.IDSERVICIO
					--INNER JOIN HPREP ON HPREPD.NOPRESUPUESTO = HPREP.NOPRESUPUESTO
					--INNER JOIN HADM ON HPREP.NOADMISION = HADM.NOADMISION
					--INNER JOIN AFI ON HADM.IDAFILIADO = AFI.IDAFILIADO
					--WHERE
					--HPREPD.NOPRESUPUESTO = @IDAUT AND COALESCE(HPREPD.VALORCOPAGO,0) > 0

					--UPDATE FCJ SET N_FACTURA = @NVOCONSEC, RECAUDO = 1, USURECAUDO = @USUARIO WHERE FCJ.CNSFACJ = @CNSFACJ AND FCJ.CODCAJA = @CODCAJA

					--UPDATE HPREP SET  FACTURADA = 1, NFACTURA = @NVOCONSEC WHERE NOPRESUPUESTO = @IDAUT

					--IF EXISTS (SELECT * FROM HPREP, KPAGE WHERE HPREP.IDKPAGE = KPAGE.IDKPAGE AND KPAGE.TABLA = 'HPREP')
					--BEGIN
					--	UPDATE KPAGE SET KPAGE.REF_PAGO = @NVOCONSEC FROM HPREP, KPAGE WHERE HPREP.IDKPAGE = KPAGE.IDKPAGE AND KPAGE.TABLA = 'HPREP' AND HPREP.NOPRESUPUESTO = @IDAUT
					--END

     --          EXEC SPK_NC_CONTAB_FTR @NVOCONSEC, '01', @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''
     --          IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP'
			  --    BEGIN
					--   PRINT 'ENVIO A SAP'
					--   EXEC SPK_JSON_FTR_PERU_INTERFAX @NVOCONSEC
			  --    END				
				END
			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
		END 
	END
	IF @METODO = 'GES_LINK_PAGO'
	BEGIN
		SELECT @PROCESO = PROCESO, @TABLA = TABLA, @PROCEDENCIA = PROCEDENCIA, @CONSECUTIVO = CONSECUTIVO, @IDAFILIADO = IDAFILIADO, @CELULAR = CELULAR, @TIPOFAC = TIPOFAC
			,@EMAIL = EMAIL
		FROM OPENJSON(@PARAMETROS)
		WITH(	PROCESO			VARCHAR(20)		'$.PROCESO'		,TABLA	VARCHAR(20)			'$.TABLA' ,PROCEDENCIA	VARCHAR(20)		'$.PROCEDENCIA'
				,CONSECUTIVO	VARCHAR(20)		'$.CONSECUTIVO'	,IDAFILIADO	VARCHAR(20)		'$.IDAFILIADO',CELULAR	VARCHAR(20)		'$.CELULAR'
            ,TIPOFAC				VARCHAR(20)		'$.TIPOFAC'
			,EMAIL 	VARCHAR(MAX)		'$.EMAIL'
			)
		IF @TABLA = 'CIT'
		BEGIN
			SELECT @IDKPAGE = COALESCE(IDKPAGE,0), @VALOR = CASE WHEN DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') = CIT.IDTERCEROCA THEN CIT.VALORTOTAL ELSE CIT.VALORCOPAGO END 
			FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO
			IF @PROCESO = 'CREAR' AND EXISTS (SELECT * FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO AND CIT.FECHA < GETDATE())
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'No se puede generar un link, la Fecha de la Cita es anterior.' 
			END
		END
		IF @TABLA = 'HADM'
		BEGIN
			SELECT @IDKPAGE = COALESCE(IDKPAGE,0), @VALOR = COALESCE(HADM.COPAGOVALOR,0)
			FROM HADM WHERE NOADMISION = @CONSECUTIVO
		END
		IF @TABLA = 'AUT'
		BEGIN
			SELECT @IDKPAGE = COALESCE(IDKPAGE,0), @VALOR = COALESCE(AUT.VALORCOPAGO,0)
			FROM AUT WHERE IDAUT = @CONSECUTIVO
		END
		IF @TABLA = 'MAD'
		BEGIN
			SELECT @IDKPAGE = COALESCE(IDKPAGE,0), @VALOR = COALESCE(MAD.COPAGO_FIJO,0)
			FROM MAD WHERE ID = @CONSECUTIVO
		END
		IF @TABLA = 'HPREP'
		BEGIN
			SELECT @IDKPAGE = COALESCE(IDKPAGE,0), @VALOR = COALESCE(HPREP.VALORCOPAGO,0)
			FROM HPREP WHERE NOPRESUPUESTO = @CONSECUTIVO
		END
		IF COALESCE(@VALOR,0) < 1 AND @PROCESO = 'CREAR'
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El valor a generar link de pago, debe de ser mayor igual a 1' 
		END
	
		IF @TABLA = 'AUT' AND @PROCESO = 'CREAR'
		BEGIN
			IF NOT EXISTS (SELECT * FROM AUTD WHERE IDAUT = @CONSECUTIVO AND AUTD.GENERADO = 1 AND AUTD.VALORCOPAGO > 0 AND COALESCE(NFACTURA,'')='')
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'No existen items por cobrar, favor de revisar. ' 
			END
		END
		IF @TABLA = 'CIT' AND  @PROCESO <> 'ENVIA'
		BEGIN
			IF (SELECT
				CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY') = 'PERU'  AND (EXISTS (SELECT  * FROM PCJ WHERE PCJ.CODCAJA = CIT.CODCAJA AND PCJ.CNSFACJ = CIT.NORECIBOCAJA) 
								OR (CASE WHEN DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') = CIT.IDTERCEROCA THEN  COALESCE(CIT.VALORTOTAL,0) ELSE COALESCE(CIT.VALORCOPAGO,0) END ) = 0   )     THEN 'Pago'  
								WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY') <> 'PERU' AND COALESCE(CIT.N_FACTURA, '') <> '' THEN 'Pago'  ELSE 'Sin Pagar' END 
				 FROM  CIT WHERE  CONSECUTIVO = @CONSECUTIVO) = 'Pago'
			BEGIN
				SELECT 'OK'OK,  ESTADO, LINKPAGO, F_EXPIRA, VALOR
				, CASE	WHEN ESTADO IN ('RUNNING', 'SEND', 'CREATED', 'REFUSED', 'ERROR') THEN 'El pago aun no ha sido realizado'  
						WHEN ESTADO = 'PAID' THEN 'El pago, ya se encuetra recaudado' END [VALIDA_ESTADO]
				FROM KPAGE WHERE  IDKPAGE = @IDKPAGE
				RETURN
			END
		END
		--IF @TABLA = 'AUT' AND  @PROCESO <> 'ENVIA'
		--BEGIN
		--	IF EXISTS(SELECT * FROM AUT WHERE IDAUT = @CONSECUTIVO AND COALESCE(IDKPAGE,0) = 0 )
		--	BEGIN
		--		PRINT 'ACA SE QUEDAAAAAA'
		--		SELECT 'OK'OK,  ESTADO, LINKPAGO, F_EXPIRA, VALOR
		--		, CASE	WHEN ESTADO IN ('RUNNING', 'SEND', 'CREATED') THEN 'El pago aun no ha sido realizado'  
		--				WHEN ESTADO = 'PAID' THEN 'El pago, ya se encuetra recaudado' END [VALIDA_ESTADO]
		--		FROM KPAGE WHERE  IDKPAGE = @IDKPAGE
		--		RETURN
		--	END
		--END
		--IF @TABLA = 'MAD' AND  @PROCESO <> 'ENVIA'
		--BEGIN
		--	IF NOT EXISTS(SELECT * FROM MAD WHERE ID = @CONSECUTIVO AND COALESCE(IDKPAGE,'') = '' )
		--	BEGIN
		--		SELECT 'OK'OK,  ESTADO, LINKPAGO, F_EXPIRA, VALOR
		--		, CASE	WHEN ESTADO IN ('RUNNING', 'SEND', 'CREATED') THEN 'El pago aun no ha sido realizado'  
		--				WHEN ESTADO = 'PAID' THEN 'El pago, ya se encuetra recaudado' END [VALIDA_ESTADO]
		--		FROM KPAGE WHERE  IDKPAGE = @IDKPAGE
		--		RETURN
		--	END
		--END
		IF @IDKPAGE >0
		BEGIN
			SELECT @ESTADO_KPAGE = ESTADO, @F_EXPIRA = COALESCE(F_EXPIRA,''), @LINKPAGO = COALESCE(LINKPAGO,'') FROM KPAGE WHERE IDKPAGE = @IDKPAGE AND CONSECUTIVO = @CONSECUTIVO
		END
		IF @PROCESO = 'CREAR'
		BEGIN
			IF @IDKPAGE >0 AND @F_EXPIRA > DBO.FNK_GETDATE() AND @ESTADO_KPAGE IN ('RUNNING','SEND', 'CREATED') AND COALESCE(@F_EXPIRA,'')<>''
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'Existe un Link vigente ya generado, no se puede generar otro. ' +  @LINKPAGO
			END
			IF @IDKPAGE >0 AND @ESTADO_KPAGE IN ('RUNNING','SEND', 'CREATED') AND COALESCE(@F_EXPIRA,'') = ''
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'Existe un Link ya generado, no se puede generar otro. ' +  @LINKPAGO
			END
			IF @IDKPAGE >0  AND @ESTADO_KPAGE IN ('PAID')
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'El codigo ya fue usado y pagado.'
			END
		END
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				PRINT 'INGRESAAAAA'
            PRINT @PROCESO
				IF @PROCESO = 'CREAR'
				BEGIN
					PRINT 'ENTRA A ==> SPK_GENERA_ORDENPAGO_IZIPAY'
					--SELECT @CONSECUTIVO,@TABLA,@PROCEDENCIA,@IDAFILIADO,@VALOR,'',@USUARIO,@IDKPAGE,@PROCESO	
							
					EXEC DBO.SPK_GENERA_ORDENPAGO_IZIPAY @CONSECUTIVO,@TABLA,@PROCEDENCIA,@IDAFILIADO,@VALOR,'',@USUARIO,@IDKPAGE,@PROCESO
				
					SELECT  @IDKPAGE = IDKPAGE, @F_EXPIRA = F_EXPIRA, @LINKPAGO = LINKPAGO 
               FROM KPAGE WHERE CONSECUTIVO = @CONSECUTIVO AND TABLA = @TABLA AND PROCEDENCIA = @PROCEDENCIA
					
				END
				IF @PROCESO IN ('CREAR', 'ENVIA')
				BEGIN
               PRINT 'ACA VITY '+STR(@IDKPAGE)
					IF NOT EXISTS (SELECT  * FROM KPAGE WHERE  ESTADO IN ('RUNNING','SEND' ) AND IDKPAGE = @IDKPAGE)
					BEGIN
						SELECT 'OK' OK, 'No se genero link de pago correctamente.' ESTADO, LINKPAGO, F_EXPIRA, VALOR   FROM KPAGE WHERE  IDKPAGE = @IDKPAGE
                  PRINT 'ME REGRESO'
						RETURN
					END


					IF @PROCESO = 'ENVIA'
					BEGIN
						SELECT @F_EXPIRA = F_EXPIRA, @LINKPAGO = LINKPAGO, @VALOR = VALOR FROM KPAGE WHERE IDKPAGE = @IDKPAGE
						SELECT @PACIENTE =PNOMBRE+' '+PAPELLIDO, @MOVILAFI = @CELULAR
							,@EMAIL = IIF(COALESCE(@EMAIL, '')='', dbo.FNK_EMAILVALIDO(DBO.FNK_PrimerEmailTercero(AFI.IDAFILIADO)), @EMAIL)
						FROM   AFI 
						WHERE  IDAFILIADO = @IDAFILIADO
					END
					IF @PROCESO = 'CREAR'
					BEGIN
						SELECT @PACIENTE =PNOMBRE+' '+PAPELLIDO, @MOVILAFI = DBO.FNK_PrimerMovilTercero(@IDAFILIADO)
						FROM   AFI 
						WHERE  IDAFILIADO = @IDAFILIADO
					END
					IF @MOVILAFI = ''
					BEGIN
                  IF COALESCE(@EMAIL,'')=''
                  BEGIN
						   SELECT 'OK' OK, 'No se envio, Whatsapp, por que no tiene numero registrado el paciente.' ESTADO, LINKPAGO, F_EXPIRA, VALOR   FROM KPAGE WHERE  IDKPAGE = @IDKPAGE
						   RETURN
                  END
					END
					PRINT 'NOTIFICA'
					SELECT @VALOR_TEXTO = CONVERT(VARCHAR,@VALOR)
					SELECT @FIRMA = DBO.FNK_VALORVARIABLE('NOMBRE_COMERCIAL')
					SELECT @FIRMA_2 = DBO.FNK_VALORVARIABLE('FIRMA_COMERCIAL')
					IF @TABLA = 'AUT'
					BEGIN
						SELECT @NOM_PREFIJO = PRE.NOM_PREFIJO FROM AUT LEFT JOIN PRE ON AUT.PREFIJO = PRE.PREFIJO WHERE IDAUT = @CONSECUTIVO
						SELECT @SMS = 'Estimado(a) paciente *'+ @PACIENTE + '*, gracias por preferir a '+@FIRMA+'. Le hacemos llegar el link de pago por el monto de S/'+@VALOR_TEXTO+' soles, correspondiente a '+COALESCE(@NOM_PREFIJO,'')+' .\n\n *Link de Pago:* '
									+@LINKPAGO + '\n\n*Fecha Vence:* '+ DBO.FNK_GET_STR_FECHA(@F_EXPIRA,NULL,NULL) + ' a las '+RIGHT(CONVERT(VARCHAR,@F_EXPIRA, 100),7)+ '\n\nAtte.\n'+@FIRMA+'\n'+COALESCE(@FIRMA_2,'')
					END
					IF @TABLA <> 'AUT'
					BEGIN
						SELECT @SMS = 'Estimado(a) paciente *'+ @PACIENTE + '*, gracias por preferir a '+@FIRMA+'. Le hacemos llegar el link de pago por el monto de S/'+@VALOR_TEXTO+' soles.\n\n *Link de Pago:* '
									+@LINKPAGO + '\n\n*Fecha Vence:* '+ DBO.FNK_GET_STR_FECHA(@F_EXPIRA,NULL,NULL) + ' a las '+RIGHT(CONVERT(VARCHAR,@F_EXPIRA, 100),7)+ '\n\nAtte.\n'+@FIRMA+'\n'+COALESCE(@FIRMA_2,'')
					END

					

					IF NOT EXISTS(SELECT * FROM KPAGE WHERE TABLA='CIT' AND IDKPAGE = @IDKPAGE)
					BEGIN
						EXEC SPK_SENDSMS @NUMERO = @MOVILAFI, @MENSAJE = @SMS, @METHOD = 'POST', @COPIA_WHATSAPP = 0
						EXEC SPK_SEND_WHATSAPP @NUMERO = @MOVILAFI, @MENSAJE = @SMS, @LINK = @LINKPAGO
					END
					ELSE 
					BEGIN

						DECLARE @NOMBREAFI VARCHAR(MAX)
						DECLARE @NOMBRE_MED VARCHAR(MAX)
						DECLARE @NOMBRE_SER VARCHAR(MAX)
						DECLARE @FECHA_STRING VARCHAR(MAX)

						SELECT @CONSECUTIVO = CONSECUTIVO FROM KPAGE WHERE IDKPAGE = @IDKPAGE

						SELECT  @NOMBREAFI = AFI.NOMBREAFI
							, @NOMBRE_MED = dbo.FNK_CAPITALIZAR_TEXTO(TRIM(MED.NOMBRE))
							, @NOMBRE_SER = SER.DESCSERVICIO
							, @FECHA_STRING = CONCAT(
								''
								,FORMAT(CIT.FECHA, 'dddd', 'es-ES')
								,' '
								,DAY(CIT.FECHA)
								,' de '
								,FORMAT(CIT.FECHA, 'MMMM', 'es-ES') 
								,' de '
								,YEAR(CIT.FECHA) 
								,' a las '
								,FORMAT(CIT.FECHA, 'h:mmtt', 'es-ES')
								,' '
								,IIF(DATEPART(HOUR, CIT.FECHA) < 12,'am', 'pm')
							)
						FROM CIT INNER JOIN AFI ON AFI.IDAFILIADO = CIT.IDAFILIADO
							LEFT JOIN MED ON MED.IDMEDICO=CIT.IDMEDICO
							LEFT JOIN SER ON SER.IDSERVICIO = CIT.IDSERVICIO
						WHERE CONSECUTIVO = @CONSECUTIVO

						SELECT @SMS = DATO FROM USVGS WHERE IDVARIABLE = 'TMPL_SMS_LINK_PAGO'
						SELECT @NOMBREAFI = dbo.FNK_CAPITALIZAR_TEXTO(TRIM(@NOMBREAFI))
						IF CHARINDEX('{{NOMBRE_AFI}}', @SMS)> 0 AND COALESCE(@NOMBREAFI, '')<>''
							SELECT @SMS = REPLACE(@SMS, '{{NOMBRE_AFI}}', @NOMBREAFI)
				
						IF CHARINDEX('{{FECHA_CIT}}', @SMS) > 0 AND COALESCE(@FECHA_STRING, '')<>''
							SELECT @SMS = REPLACE(@SMS, '{{FECHA_CIT}}', @FECHA_STRING)

						IF CHARINDEX('{{NOMBRE_MED}}', @SMS) > 0 AND COALESCE(@NOMBRE_MED, '')<>''
							SELECT @SMS = REPLACE(@SMS, '{{NOMBRE_MED}}', @NOMBRE_MED)

						IF CHARINDEX('{{NOMBRE_SER}}', @SMS) > 0 AND COALESCE(@NOMBRE_SER, '')<>''
							SELECT @SMS = REPLACE(@SMS, '{{NOMBRE_SER}}', @NOMBRE_SER)

						IF CHARINDEX('{{MONTO}}', @SMS) > 0 AND COALESCE(@VALOR_TEXTO, '')<>''
							SELECT @SMS = REPLACE(@SMS, '{{MONTO}}', @VALOR_TEXTO)
						
						IF CHARINDEX('{{LINK}}', @SMS) > 0 AND COALESCE(@LINKPAGO, '')<>''
							SELECT @SMS = REPLACE(@SMS, '{{LINK}}', @LINKPAGO)

						IF CHARINDEX('{{FECHA_VENCE}}', @SMS) > 0 
							SELECT @SMS = REPLACE(@SMS, '{{FECHA_VENCE}}', DBO.FNK_GET_STR_FECHA(@F_EXPIRA,NULL,NULL)+' a las '+RIGHT(CONVERT(VARCHAR,@F_EXPIRA, 100),7))

						EXEC SPK_SEND_WHATSAPP @NUMERO = @MOVILAFI, @MENSAJE = @SMS, @LINK = @LINKPAGO
						EXEC DBO.SPK_SENDSMS @MOVILAFI, @SMS, 'POST', @COPIA_WHATSAPP = 0

					END

					UPDATE KPAGE SET ESTADO = 'SEND' WHERE IDKPAGE = @IDKPAGE
               PRINT 'ANTES DE ENVIAR'
					IF (SELECT LEN(DATO) FROM USVGS WHERE IDVARIABLE = 'TMPL_EMAIL_LINKPAGO')> 20 AND @TABLA IN ('CIT', 'MAD')
					BEGIN
						SELECT @CONSECUTIVOCIT = @CONSECUTIVO
						SELECT @CONSECUTIVOCIT = CONSECUTIVOCIT FROM MAD WHERE ID = @CONSECUTIVO AND @TABLA = 'MAD'
						
						PRINT 'ENTRA A ENVIAR POR CORREO ====>>>>>>>>>>> @CONSECUTIVOCIT='+@CONSECUTIVOCIT+'  @EMAIL='+@EMAIL+' @LINKPAGO='+@LINKPAGO
						EXEC  DBO.SPK_NOTIFICA_CITA_EMAIL 'ENVIA_LINK_PAGO', @CONSECUTIVOCIT, @EMAIL, @LINKPAGO

						SELECT @NOTIFICADO = 1
					END

				END
				IF @PROCESO IN ('VALIDA')
				BEGIN
					PRINT 'VALIDA'
					SELECT @F_EXPIRA = F_EXPIRA, @LINKPAGO = LINKPAGO, @VALOR = VALOR FROM KPAGE WHERE IDKPAGE = @IDKPAGE
					SELECT @CNSACJ =  CAJ.CNSACJ, @CODCAJERO = USUSU.CODCAJERO, @CODCAJA = UBEQ.CAJA,@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA) 
					FROM  USUSU 
						INNER JOIN UBEQ ON USUSU.SYS_ComputerName = UBEQ.SYS_ComputerName
						INNER JOIN CAJ ON UBEQ.CAJA = CAJ.CODCAJA
					WHERE  USUARIO = @USUARIO
					--SELECT @IDKPAGE, @CODCAJA, @USUARIO
					PRINT 'INGRESA A   SPK_VALIDAR_IZIPAY_JOB '
					EXEC SPK_VALIDAR_IZIPAY_JOB @IDKPAGE, @CODCAJA, @USUARIO, @TIPOFAC
					SELECT 'OK'OK,  ESTADO, LINKPAGO, F_EXPIRA, VALOR
					, CASE	WHEN ESTADO IN ('RUNNING', 'SEND', 'CREATED', 'REFUSED','ERROR') THEN 'El pago aun no ha sido realizado'  
							WHEN ESTADO = 'PAID' THEN 'Se valido el pago.'
							WHEN ESTADO = 'EXPIRED' THEN 'El link Generado ya EXPIRO, genere uno nuevo.'END [VALIDA_ESTADO], KPAGE.REF_PAGO [N_FACTURA]
					FROM KPAGE WHERE  IDKPAGE = @IDKPAGE
					RETURN
				END

			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK, 'OK' ESTADO, LINKPAGO, F_EXPIRA, VALOR 
				,NOTIFICADO = @NOTIFICADO
			FROM KPAGE 
			WHERE  IDKPAGE = @IDKPAGE
		END 
	END
END





