IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_A_RECIBIR_IENF' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_A_RECIBIR_IENF
END

GO
CREATE PROCEDURE DBO.SPK_A_RECIBIR_IENF
	@CNSRPDX	  VARCHAR(20),
	@TIPO		  VARCHAR(10),
	@NOREFERENCIA VARCHAR(20)
WITH ENCRYPTION
AS
/* 
Fecha:		 2018-09-28
Descripción: Procedimiento que generará a RPDX los que se debe recibir
*/
DECLARE 
	@IDINVITMOVENF VARCHAR(20),
	@DEINVNODESER  VARCHAR(20),
	@INSUMOSCONMED VARCHAR(20),
	@OMCODMEZCLA   VARCHAR(20),
	@OMCODNUTRI    VARCHAR(20),
	@OMCODHEMO     VARCHAR(20),
    @IENF_MEZCLA   VARCHAR(20),
    @IENF_NUTP     VARCHAR(20),
	@FINI_VERSION  DATETIME
BEGIN
	PRINT 'EXEC SPK_A_RECIBIR_IENF '''+ISNULL(@CNSRPDX,'')+''', '''+ISNULL(@TIPO,'')+''', '''+ISNULL(@NOREFERENCIA,'')+''''
	SELECT @IDINVITMOVENF=DATO FROM USVGS WHERE IDVARIABLE='IDINVITMOVENF'
	SELECT @DEINVNODESER =DATO FROM USVGS WHERE IDVARIABLE='DEINVNODESER'
	SELECT @INSUMOSCONMED=DATO FROM USVGS WHERE IDVARIABLE='PIDE_INSUMOSCON_MEDI'
	SELECT @FINI_VERSION =CONVERT(DATETIME,(CASE ISDATE(DATO) WHEN 1 THEN DATO ELSE '01/01/1800' END)) FROM USVGS WHERE IDVARIABLE='F_INIVERSION180'
    SELECT @OMCODMEZCLA  =DATO FROM USVGS WHERE IDVARIABLE='OMCODMEZCLA'
    SELECT @OMCODNUTRI   =DATO FROM USVGS WHERE IDVARIABLE='OMCODNUTRICIONP'
	SELECT @IENF_MEZCLA  =DATO FROM USVGS WHERE IDVARIABLE='IENF_MEZCLA'
    SELECT @IENF_NUTP    =DATO FROM USVGS WHERE IDVARIABLE='IENF_NUTP'
    SELECT @OMCODHEMO    =(CASE ISNULL(DATO,'') WHEN '' THEN 'XX' ELSE DATO END) FROM USVGS WHERE IDVARIABLE='OMCODHEMODERIVADOS'
   
    SELECT IZSOL.CNSIZSOL, IMOV.CNSMOV, IMOV.NODOCUMENTO, IZSOL.NOADMISION, IZSOL.CLASE, IZSOL.CONSECUTIVOHCA, IMOV.FECHACONF
    INTO #IMOV
    FROM IZSOL INNER JOIN IMOV ON IMOV.NODOCUMENTO=IZSOL.CNSIZSOL 
    WHERE IZSOL.CLASE IN ('OMEDICA','24HORAS','SENFER')
        AND IMOV.IDTIPOMOV=@IDINVITMOVENF AND COALESCE(IMOV.PROCEDENCIA,'')='CM_SOL' 
        AND IMOV.FECHACONF >= @FINI_VERSION AND COALESCE(IMOV.ESTADO,0)=1
		AND EXISTS (SELECT 1 FROM HHAB WHERE HHAB.NOADMISION=IZSOL.NOADMISION
					AND @NOREFERENCIA=CASE @TIPO WHEN 'NOADMISION' THEN ISNULL(HHAB.NOADMISION,'') WHEN 'SECTOR' THEN ISNULL(HHAB.SECTOR,'') ELSE '' END
				   )

	INSERT INTO RPDX (CNS, IDTERCERO, ID1, ID2, ID3, ID4, ID5, ID6, ID7, ID8, ID9, ID10, STRINGMEDIO9, FECHA1, VALOR1, VALOR2, CANTIDAD, STRINGGRANDE1)
	SELECT DISTINCT
		@CNSRPDX, --CNS
        ROW_NUMBER() OVER (ORDER BY SER.DESCSERVICIO), --ORDEN
		IMOVH.CNSMOV, --ID1
		IMOVH.IDARTICULO, --ID2
		IMOVH.NOLOTE, --ID3
		IMOVH.NOLOTEPEDIDO, --ID4
		I.NODOCUMENTO, --ID5
		I.NOADMISION, --ID6
		I.CLASE, --ID7
        IZSOLD.CODOM, --ID8
        IZSOLD.IDSERVICIO, --ID9
        I.CONSECUTIVOHCA, --ID10
        (SELECT DESCRIPCION FROM HCCOM WHERE HCCOM.CODOM=IZSOLD.CODOM), --STRINGMEDIO9
		I.FECHACONF, --FECHA1
		IZSOLDT.CANTIDADSOL-ISNULL(IMOVH.CANTREP,0), --VALOR1
		IZSOLDT.CANTIDADSOL-ISNULL(IMOVH.CANTREP,0), --VALOR2
		0 CANTIDAD, --CANTIDAD
		LEFT(IART.DESCRIPCION,512) --STRINGGRANDE1
	FROM #IMOV I
		INNER JOIN IMOVH   ON IMOVH.CNSMOV=I.CNSMOV
		INNER JOIN IZSOLD  ON I.CNSIZSOL=IZSOLD.CNSIZSOL AND IMOVH.IDSERVICIO=IZSOLD.IDSERVICIO
		INNER JOIN IZSOLDT ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD AND IZSOLDT.IDARTICULOREAL=IMOVH.IDARTICULO 
         AND IZSOLDT.CNSMOV=I.CNSMOV AND IZSOLDT.NOLOTE=IMOVH.NOLOTE
		INNER JOIN IART    ON IMOVH.IDARTICULO=IART.IDARTICULO 
		INNER JOIN SER     ON IART.IDSERVICIO=SER.IDSERVICIO 
	WHERE ISNULL(IMOVH.RENFER,0) IN (0,2)
        AND (IZSOLDT.CANTIDADSOL-ISNULL(IMOVH.CANTREP,0))>0
		AND IART.IDITAR<>@DEINVNODESER 
		AND ISNULL(SER.MEDICAMENTOS,0)=CASE WHEN @INSUMOSCONMED='SI' THEN ISNULL(SER.MEDICAMENTOS,0) 
                                     ELSE (CASE IZSOLD.CODOM WHEN @OMCODHEMO THEN ISNULL(SER.MEDICAMENTOS,0) ELSE 1 END) END 
		AND 1=(CASE WHEN @IENF_MEZCLA<>'SI' AND ISNULL(IZSOLD.CODOM,'')=@OMCODMEZCLA THEN 0 ELSE 1 END)
		AND 1=(CASE WHEN @IENF_NUTP  <>'SI' AND ISNULL(IZSOLD.CODOM,'')=@OMCODNUTRI  THEN 0 ELSE 1 END)
END

