
SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC
SELECT  * FROM TGEN WHERE CAMPO LIKE '%FORMAT%'

SELECT  IDFORMATO,IDSEDE FROM FTR WHERE N_FACTURA='UV11403'

SELECT * FROM DBO.FNK_SPLIT_PMA('CONSULTA DE PRIMERA VEZ POR ESPECIALISTA EN PSIQUIATRIA   ',' ',55,'') WHERE VEZ=2

UPDATE FTR SET IDFORMATO='06E' WHERE N_FACTURA='UV11403'

EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"UV11403"},"USUARIO":"JJIMENEZ"}'


SELECT  NOAUTORIZACION, * FROM CIT WHERE CONSECUTIVO='0200031630'

UPDATE CIT SET NOAUTORIZACION='12345678910111112000' WHERE CONSECUTIVO='0200031630'

SELECT * FROM SED