SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC


EXEC SPQ_JSON '{"MODELO":"KMCOM_COL","METODO":"TRAER_KTCO","PARAMETROS":{},"USUARIO":"JJIMENEZ"}'

SELECT ROW_NUMBER() OVER(ORDER  BY IDTIPOCONT  ASC) 
FROM KMCOM


SELECT *  FROM [dbo].[KMCOM] INNER JOIN  AFU ON KMCOM.IDAREA=AFU.IDAREA INNER JOIN CEN ON KMCOM.CCOSTO=CEN.CCOSTO INNER JOIN CUE ON KMCOM.CUENTA=CUE.CUENTA WHERE (KMCOM.PREFIJO LIKE '%%%%' OR KMCOM.CUENTA  LIKE '%%%%' OR KMCOM.CCOSTO LIKE '%%%%') AND IDTIPOCONT='undefined'  ORDER BY [dbo].[KMCOM].[IDMODELOCONT] OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 