TRUNCATE TABLE RPDX2

DROP TABLE #A
DROP TABLE #B

SELECT *FROM RPDX2

SELECT ID1 CUENTA,ID3 IDTERCERO,ID4 N_FACTURA,VALOR2 DB,VALOR3 CR,STRINGMEDIO3 RAZONSOCIAL INTO #A FROM RPDX2 WHERE CNS='0100101736'


SELECT CUENTA,IDTERCERO,N_FACTURA,SUM(DB)DB,SUM(CR)CR,SUM(DB-CR) SALDO,RAZONSOCIAL INTO #B FROM #A
GROUP BY CUENTA,IDTERCERO,N_FACTURA,RAZONSOCIAL

SELECT  * FROM #B

SELECT IDTERCERO,N_FACTURA,SUM(SALDONETO)SALDO INTO #C
FROM VWK_CXCDIASVTO WHERE CLASEINFO='SINGLO' AND RAD='SI'
GROUP BY  IDTERCERO,N_FACTURA

SELECT * FROM #B LEFT JOIN #C ON #B.N_FACTURA=#C.N_FACTURA AND #B.IDTERCERO=#C.IDTERCERO
WHERE #B.SALDO<>COALESCE(#C.SALDO,0)
AND #B.IDTERCERO='900156264'


SELECT SUM(VLRGLOSA) FROM FGLO WHERE CERRADA=0
AND FGLO.IDTERCERO='900156264'


SELECT  * FROM FCXC WHERE CNSCXC='0200000105'
SELECT  * FROM MCP WHERE REFERENCIA1='0200000105'


SELECT  * INTO #E FROM MCH WHERE  NROCOMPROBANTE='0226800000015394'

UPDATE #E SET NROCOMPROBANTE='0200056078'


SELECT DBO.FNK_COLUMNAS_TABLAS('MCH')

INSERT INTO MCH(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG, CODPRG, ERROR, IDOPERACION,  FECHACONCILIACION, IDPROVEEDOR, ENPRESUPUESTO, ESTADOIMP, IDSEDE)
SELECT NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG, CODPRG, ERROR, IDOPERACION,  FECHACONCILIACION, IDPROVEEDOR, ENPRESUPUESTO, ESTADOIMP, IDSEDE
FROM #E

SELECT  * FROM MCHE WHERE NROCOMPROBANTE='0298000000056062'

UPDATE MCHE SET CUENTA='5136950103',ERROR='',DETALLE='' WHERE NROCOMPROBANTE='0298000000056062' AND NROASIENTO='832608'

UPDATE MCPE SET ANO='2023',MES=12,FECHACONTABLE='31/12/2023' WHERE NROCOMPROBANTE='0298000000056062'