IF EXISTS (SELECT NAME FROM SYSOBJECTS 
   WHERE NAME = 'SPK_COPAGO_AUT_CEHOSP' AND TYPE = 'P')
   DROP PROCEDURE SPK_COPAGO_AUT_CEHOSP

GO
CREATE PROCEDURE DBO.SPK_COPAGO_AUT_CEHOSP
@IDAFILIADO       VARCHAR(20),
@IDAUT            VARCHAR(20), 
@NO_ITEM          SMALLINT,
@IDSERVICIO       VARCHAR(20),
@PYP              SMALLINT,
@ALTOCOSTO        SMALLINT,
@VALORAUTD        DECIMAL(14,2),
@PROCEDENCIA      VARCHAR(2),
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA         VARCHAR(2),
@IDSEDE           VARCHAR(5),
@USUARIO          VARCHAR(12),
@IDPROVEEDOR      VARCHAR(20) = NULL,
@IDAREA           VARCHAR(20) = NULL,
@FECHAAUT         DATETIME    = NULL,
@COPAGOPROPIO     SMALLINT    = 0,
@SOAT             SMALLINT    = 0
WITH ENCRYPTION
AS
DECLARE @TIPOAFILIADO     VARCHAR(1)  
DECLARE @IDADMINISTRADORA VARCHAR(20)
DECLARE @GRUPOETNICO      VARCHAR(1)
DECLARE @EDAD             DECIMAL(14,2)
DECLARE @TIPOAFILIADO2    VARCHAR(12)
DECLARE @NIVELSOCIOEC     VARCHAR(2)
DECLARE @IDPLAN           VARCHAR(6) 
DECLARE @PREFIJO          VARCHAR(6)
DECLARE @NIVELATENCION    VARCHAR(5)      
DECLARE @IDMODELOPCA      VARCHAR(5)
DECLARE @COBRARCOPA       VARCHAR(12)
DECLARE @EXPYP            SMALLINT
DECLARE @TIPODEPAGO       VARCHAR(10)
DECLARE @EXALTOCOSTO      SMALLINT
DECLARE @EXGRUPOETNICO    VARCHAR(1)
DECLARE @FORMACOBRO       VARCHAR(10)
DECLARE @REDONDEO         VARCHAR(10)
DECLARE @VALOR            DECIMAL(14,2)
DECLARE @VALORCOPAGO      DECIMAL(14,2)
DECLARE @MESES            DECIMAL(14,2)
DECLARE @FNACIM           DATETIME
DECLARE @EXEDAD           SMALLINT
DECLARE @VALORTOTAL1      DECIMAL(14,2)
DECLARE @AUXN             INT
DECLARE @IDTERCEROCA      VARCHAR(20)
DECLARE @IDTERCEROCAD     VARCHAR(20)
DECLARE @DATOCONT         VARCHAR(20)
DECLARE @VLRSERVICIO      DECIMAL(14,2)
DECLARE @VALORTOTALCOSTO  DECIMAL(14,2) 
DECLARE @CALCULARPOR      VARCHAR(5)
DECLARE @OK               INT
DECLARE @PART             SMALLINT
DECLARE @AQUIENCOBRO      VARCHAR(1)
DECLARE @NOAUTORIZACIONCIT VARCHAR(45)
DECLARE @DESCSERVICIO      VARCHAR(255) -- Utilizado para enviar el mensaje de texto - EZERPA 10.03.2018
DECLARE @PACIENTE          VARCHAR(60) -- Nombre y Apellido del Afiliado - EZERPA 10.03.2018
DECLARE @SMS               VARCHAR(1000)
DECLARE @RAZONSOCIAL       VARCHAR(255) -- Nombre de la institución donde esta instalado Krystalos
DECLARE @MOVILAFI          VARCHAR(13)
DECLARE @RECAUDADO		   SMALLINT=0
DECLARE @NOCOBRAR          BIT
DECLARE @TIPOCALCULO	   VARCHAR(1)
BEGIN      
   SELECT @TIPOAFILIADO = TIPOAFILIADO, @GRUPOETNICO  = GRUPOETNICO,  
   @EDAD =  DATEDIFF(DAY, FNACIMIENTO, GETDATE())/365.25,
   @NIVELSOCIOEC = NIVELSOCIOEC, @FNACIM = FNACIMIENTO
   ,@PACIENTE=PNOMBRE+' '+PAPELLIDO -- EZERPA 10.03.2018
   FROM   AFI 
   WHERE  IDAFILIADO = @IDAFILIADO
      
   SELECT @IDTERCEROCAD = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'CEHOSPENTEGUB'
   PRINT 'INGRESE'
   IF @PROCEDENCIA = 'CE'
   BEGIN  
      SELECT @IDADMINISTRADORA = IDTERCEROCA, @IDPLAN = IDPLAN, @IDTERCEROCA = IDTERCEROCA,
      @AQUIENCOBRO      = AQUIENCOBRO
      FROM   AUTD  
      WHERE  IDAUT   = @IDAUT
      AND    NO_ITEM = @NO_ITEM
        
      SELECT @SOAT = ISNULL(SOAT,0) FROM AUT WHERE IDAUT = @IDAUT     
        
      /*SELECT @FECHAAUT = FECHA, @IDPROVEEDOR = IDPROVEEDOR, @IDAREA = IDAREA 
      FROM AUT WHERE IDAUT = @IDAUT*/
   END
   ELSE
   BEGIN
      SELECT @IDADMINISTRADORA = IDTERCEROCA, @IDPLAN = IDPLAN, @IDTERCEROCA = IDTERCEROCA,
             @FECHAAUT = FECHA , @IDPROVEEDOR = IDMEDICO, @IDAREA = IDAREA, @NOAUTORIZACIONCIT = NOAUTORIZACION,
			 @RECAUDADO = COALESCE(GENEROCAJA,0)
      FROM   CIT
      WHERE  CONSECUTIVO   = @IDAUT
   END
   
   /* SE COLOCA EL CALCULO DE VALORES */
   /* BEGIN JEDM_001_14092005         */
   --PRINT 'IDADMINISTRADORA='+@IDADMINISTRADORA
   --PRINT 'IDPLAN='+ @IDPLAN
   --PRINT 'IDSERVICIO=' + @IDSERVICIO
   --PRINT 'IDAREACA = '+@IDAREA
   IF @PROCEDENCIA = 'CE'
   BEGIN   
	  SET DATEFORMAT dmy
      IF @IDPLAN = DBO.FNK_VALORVARIABLE('IDCJPLANEXTERNO') AND @IDADMINISTRADORA=DBO.FNK_VALORVARIABLE('IDCJTERCEROEXTERNO')
      BEGIN
         SELECT @VLRSERVICIO = DBO.FNK_VLRAUTORIZACION(@IDAUT, @NO_ITEM, DBO.FNK_VALORVARIABLE('IDCJTERCEROEXTERNO'), @IDPLAN, @IDAREA, @FECHAAUT) 
      END
      ELSE
      BEGIN
         SELECT @VLRSERVICIO = DBO.FNK_VLRAUTORIZACION(@IDAUT, @NO_ITEM, @IDADMINISTRADORA, @IDPLAN, @IDAREA, @FECHAAUT) 
      END
   END
   ELSE
   BEGIN
      SELECT @VLRSERVICIO = DBO.FNK_VLRCITA(@IDAUT)
   END
   
   SELECT @VALORTOTALCOSTO = 0
   IF dbo.FNK_VALORVARIABLE('ESFARMACIA') <> 'SI'
   BEGIN
      SELECT TOP 1 @VALORTOTALCOSTO = VLRCXP 
      FROM   VW_NOMBAS1 
      WHERE  IDPROVEEDOR = @IDPROVEEDOR
      AND IDADMINISTRADORA = @IDADMINISTRADORA
      AND IDPLAN           = @IDPLAN 
      AND IDSERVICIO       = @IDSERVICIO
      AND @FECHAAUT BETWEEN FECHAINIADM AND FECHAFINADM
      AND @FECHAAUT BETWEEN FECHAINIPRO AND FECHAFINPRO
      AND @FECHAAUT BETWEEN FECHAINIADMSER AND FECHAFINADMSER
      AND @FECHAAUT BETWEEN FECHAINIPROSER AND FECHAFINPROSER
      AND IDAREACA   = @IDAREA   
   END

   /*END JEDM_001_14092005         */
   
   IF @PROCEDENCIA = 'CE'
   BEGIN
      UPDATE AUTD SET VALOR = @VLRSERVICIO, VALORTOTALCOSTO = @VALORTOTALCOSTO, VALORPROV = @VALORTOTALCOSTO
      WHERE  IDAUT   = @IDAUT 
      AND    NO_ITEM = @NO_ITEM
      SELECT @VALORTOTAL1 = (AUTD.CANTIDAD * AUTD.VALOR) FROM AUTD WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM
   END 
   ELSE
   BEGIN
      UPDATE CIT SET VALORTOTAL = @VLRSERVICIO, VALORPROV = @VALORTOTALCOSTO, @NOCOBRAR=COALESCE(NOCOBRAR,0) WHERE CONSECUTIVO = @IDAUT
      SELECT @VALORTOTAL1 = @VLRSERVICIO
      IF @VLRSERVICIO = 0
      BEGIN
         UPDATE CIT SET NOCOBRAR = 1 WHERE CONSECUTIVO  = @IDAUT  -- 09.JUN.2007 
      END
      IF @NOCOBRAR=1
      BEGIN
         UPDATE CIT SET VALORCOPAGO=0, GENEROCAJA=0, TIPOCAJA=NULL WHERE CONSECUTIVO=@IDAUT
         RETURN
      END
   END
   PRINT 'REVISO NO COBRABLES CITAS..........'
   IF @PROCEDENCIA = 'CI'
   BEGIN
      IF EXISTS(SELECT * FROM CIT WHERE CONSECUTIVO=@IDAUT AND EXISTS(SELECT * FROM PPTD WHERE PPTD.IDTERCERO=CIT.IDTERCEROCA AND PPTD.IDPLAN=CIT.IDPLAN 
                                                                      AND PPTD.IDSERVICIO=CIT.IDSERVICIO AND PPTD.IDAREA=CIT.IDAREA AND PPTD.CCOSTO=CIT.CCOSTO)
      )
      BEGIN
         UPDATE CIT SET FACTURABLE=0, NOCOBRAR=1, VALORCOPAGO=0, GENEROCAJA=0, TIPOCAJA=NULL WHERE CONSECUTIVO=@IDAUT
         RETURN
      END
      ELSE IF EXISTS(SELECT 1 FROM CIT WHERE CONSECUTIVO=@IDAUT AND UPPER(TIPOCITA) IN ('PQ','QX'))
      BEGIN
         UPDATE CIT SET FACTURABLE=0, NOCOBRAR=1, VALORCOPAGO=0, GENEROCAJA=0, TIPOCAJA=NULL WHERE CONSECUTIVO=@IDAUT
         RETURN
      END
      ELSE
      BEGIN
         UPDATE CIT SET FACTURABLE=1, NOCOBRAR=0 WHERE CONSECUTIVO=@IDAUT
      END
   END 
   IF @SOAT = 1
   BEGIN
      IF @PROCEDENCIA = 'CE'
      BEGIN
         EXEC SPK_CONCEPTOCAJA_AUT @IDAUT, @NO_ITEM, @IDADMINISTRADORA, @IDPLAN 
      END
      ELSE
      BEGIN
         PRINT 'VOY A SPK_PAGOSCAJA_CIT' 
         EXEC SPK_PAGOSCAJA_CIT @IDAUT, @SYS_COMPUTERNAME, @COMPANIA, @IDSEDE, @USUARIO, 0
      END
      RETURN
   END
     
   SELECT @VALORAUTD = @VALORTOTAL1         
   
   PRINT 'IDPLAN=' + @IDPLAN
   PRINT 'IDTERCEROCA=' + @IDTERCEROCA   
   --BEGIN JEDM_001_17012007         
   SELECT @PART = ISNULL(ENVIODICAJA,0)
   FROM   TER
   WHERE  IDTERCERO = @IDTERCEROCA
   
   -- END JEDM_001_17012007           
   --BEGIN JEDM_001_24072007      
   IF @PROCEDENCIA = 'CE'
   BEGIN
      IF @PART = 0
      BEGIN
         IF @AQUIENCOBRO = 'P'
         BEGIN
            SELECT @PART = 1
         END
         ELSE
            SELECT @PART = 0
         END
      END
   END
   IF @IDPLAN =  DBO.FNK_VALORVARIABLE('IDPLANPART') OR
      @IDPLAN =  DBO.FNK_VALORVARIABLE('IDPLANPART2') OR
      @IDPLAN =  DBO.FNK_VALORVARIABLE('IDPLANPART3') OR
      @IDPLAN =  DBO.FNK_VALORVARIABLE('IDPLANPART4') OR
      @IDPLAN =  DBO.FNK_VALORVARIABLE('IDPLANPART5') 
   BEGIN
      SELECT @PART = 1
   END
   ELSE
   BEGIN
      SELECT @PART = 0
   END
   -- SI ES PARTICULAR EL VALOR COPAGO ES IGUAL AL VALOR DEL SERVICIO
   PRINT '@PART='+STR(@PART)
   IF @PART = 1 AND @PROCEDENCIA = 'CE'
   BEGIN
      /* JEDM: 16.FEB.2011   CUANDO ESTAMOS SEGUROS QUE ES PARTICULAR COLOCAMOS DIRECTAMENTE
      EL CODIGOCPCJ (CONCEPTO DE CAJA) QUE ES EL PARTICULAR Y QUITAMOS
      EL LLAMADO AL SPK ANTERIOR, QUE SIGUE FUNCIONANDO PARA CUANDO NO ES
      PARTICULAR */
      UPDATE AUTD SET VALORCOPAGO = @VALORAUTD , CODIGOCPCJ = DBO.FNK_VALORVARIABLE('IDCJPART'), VALOREXCEDENTE=@VALORTOTAL1
      WHERE  IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
      
      --EXEC SPK_CONCEPTOCAJA_AUT @IDAUT, @NO_ITEM, @IDADMINISTRADORA, @IDPLAN          
      
      RETURN
   END
   --END JEDM_001_24072007
   PRINT '@PART=' +STR(@PART) 
      
   IF @FNACIM IS NULL OR @FNACIM = ''
   BEGIN
      SELECT @MESES = 5000
      SELECT @FNACIM = NULL
   END
   ELSE     
   BEGIN
      SELECT @MESES = @EDAD * 12
   END
   SELECT @TIPOAFILIADO2 = CASE @TIPOAFILIADO
                              WHEN 'C' THEN 'COTIZANTE'
                              WHEN 'B' THEN 'BENEFICIARIO'
                              WHEN 'A' THEN 'ADICIONAL' 
                           END
      
   SELECT @PREFIJO = PREFIJO, @NIVELATENCION = NIVELATENCION
   FROM   SER
   WHERE  IDSERVICIO = @IDSERVICIO
   --PRINT 'PREFIJO='+@PREFIJO
   --PRINT 'NIVEL='+@NIVELATENCION      
   --PRINT 'IDADMINISTRADORA='+@IDADMINISTRADORA
   --PRINT '@IDPLAN='+@IDPLAN
   --PRINT '@TIPOAFILIADO2='+@TIPOAFILIADO2
   SELECT @IDMODELOPCA = IDMODELOPCA FROM PPT WHERE IDTERCERO = @IDADMINISTRADORA AND IDPLAN = @IDPLAN      
    
   --PRINT 'IDMODELO='+@IDMODELOPCA
   SELECT @TIPODEPAGO = TIPODEPAGO FROM MOCPS WHERE IDMODELOPC = @IDMODELOPCA AND IDSERVICIO = @IDSERVICIO
   --PRINT 'TIPOPAGO(1)='+@TIPODEPAGO
   
   IF @TIPODEPAGO IS NULL
   BEGIN
      SELECT @TIPODEPAGO   = TIPODEPAGO FROM MOCP
      WHERE  IDMODELOPC    = @IDMODELOPCA
      AND    PREFIJO       = @PREFIJO
      AND    NIVELATENCION = @NIVELATENCION      
   END 
   PRINT '@RECAUDADO='+CONVERT(VARCHAR, @RECAUDADO)
   IF @RECAUDADO = 0
   BEGIN
	   IF COALESCE(@COPAGOPROPIO,0) = 0
	   BEGIN
		  --MNKR
		  SELECT @TIPOCALCULO=TIPOCALCULO, @VALOR=CANTNOCOBRABLE FROM PPTD 
		  WHERE IDTERCERO=@IDADMINISTRADORA AND IDPLAN=@IDPLAN AND IDSERVICIO=@IDSERVICIO AND TIPORESTRICCION='C'
		  
		  IF COALESCE(@TIPOCALCULO,'')='' AND ISNULL(@VALOR,0)=0
		  BEGIN
			  PRINT 'TIPOPAGO(2)='+@TIPODEPAGO   
			  IF @TIPODEPAGO IS NULL OR @VLRSERVICIO = 0           --09.JUN.2007 NO ENVIE A CAJA SI VLRSERVICIO = 0
			  BEGIN
				 IF @PROCEDENCIA = 'CE'
				 BEGIN
					UPDATE  AUTD SET VALORCOPAGO = 0, AUTD.AUTORIZADO = 1, AUTD.MARCAPAGO = 0, IDTERCEROCA = @IDTERCEROCA 
					WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
				 END
				 ELSE
				 BEGIN
					UPDATE CIT SET VALORCOPAGO=0 WHERE CONSECUTIVO = @IDAUT
				 END
			  END
			  ELSE
			  BEGIN   
				 PRINT 'ENTRE A CALCULO'
				 SELECT @AUXN = ISNULL(COUNT(*),0) FROM MOCC
				 WHERE  IDMODELOPC = @IDMODELOPCA AND TIPODEPAGO = @TIPODEPAGO         
				 print '@idmodelopca='+@IDMODELOPCA+'--@TIPODEPAGO='+@TIPODEPAGO+'@auxn='+str(@auxn)
				 IF @AUXN = 0
				 BEGIN
					IF @PROCEDENCIA = 'CE'
					BEGIN
					   UPDATE  AUTD SET VALORCOPAGO = 0, AUTD.AUTORIZADO = 1, AUTD.MARCAPAGO = 0, IDTERCEROCA = @IDTERCEROCA
					   WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
					END
					ELSE
					BEGIN
					   UPDATE  CIT SET VALORCOPAGO = 0 WHERE CONSECUTIVO = @IDAUT
					   PRINT 'VOY A SPK_PAGOSCAJA_CIT' 
					   EXEC SPK_PAGOSCAJA_CIT @IDAUT, @SYS_COMPUTERNAME, @COMPANIA, @IDSEDE, @USUARIO, @PART
					END
					RETURN
				 END
         
				 SELECT @EXPYP      = EXPYP,      @COBRARCOPA = COBRARCOPA, @EXALTOCOSTO = EXALTOCOSTO, @EXGRUPOETNICO = EXGRUPOETNICO,
						@FORMACOBRO = FORMACOBRO, @REDONDEO   = REDONDEO,   @EXEDAD      = EXEDAD,      @CALCULARPOR   = CALCULARPOR
				 FROM   MOCC 
				 WHERE  IDMODELOPC = @IDMODELOPCA AND TIPODEPAGO = @TIPODEPAGO         
         
				 IF @EXPYP = 1 AND @PYP = 1
				 BEGIN
					PRINT 'EXCEP DE PYP'
					IF @PROCEDENCIA = 'CE'
					BEGIN
					   UPDATE  AUTD SET VALORCOPAGO = 0, AUTD.AUTORIZADO = 1, AUTD.MARCAPAGO = 0, IDTERCEROCA = @IDTERCEROCA
					   WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
					END
					ELSE
					BEGIN
					   UPDATE  CIT SET VALORCOPAGO = 0 WHERE CONSECUTIVO = @IDAUT
					END
					RETURN
				 END
				 IF @EXALTOCOSTO = 1 AND @ALTOCOSTO = 1
				 BEGIN
					PRINT 'EXCEP DE ALTO'
					IF @PROCEDENCIA = 'CE'
					BEGIN
					   UPDATE  AUTD SET VALORCOPAGO = 0, AUTD.AUTORIZADO = 1, AUTD.MARCAPAGO = 0, IDTERCEROCA = @IDTERCEROCA
					   WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
					END
					ELSE
					BEGIN
					   UPDATE  CIT SET VALORCOPAGO = 0 WHERE CONSECUTIVO = @IDAUT
					END
					RETURN
				 END         
				 PRINT '@EXGRUPO=' + @EXGRUPOETNICO
				 PRINT '@GRUPOETNICO='+@GRUPOETNICO
				 IF @EXGRUPOETNICO <> 'N' AND @EXGRUPOETNICO = @GRUPOETNICO
				 BEGIN
					PRINT 'EXCEP GRUPO'
					IF @PROCEDENCIA = 'CE'
					BEGIN
					   UPDATE  AUTD SET VALORCOPAGO = 0, AUTD.AUTORIZADO = 1, AUTD.MARCAPAGO = 0, IDTERCEROCA = @IDTERCEROCA
					   WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
					END
					ELSE
					BEGIN
					   UPDATE  CIT SET VALORCOPAGO = 0 WHERE CONSECUTIVO = @IDAUT
					END
					RETURN
				 END         
				 IF @FNACIM IS NOT NULL
				 BEGIN
					PRINT '@EXEDAD='+ CAST(@EXEDAD AS VARCHAR(20))
					PRINT '@MESES='+ CAST(@MESES AS VARCHAR(20))
					IF @EXEDAD >= @MESES
					BEGIN
					   PRINT 'EXCEP EDAD'
					   IF @PROCEDENCIA = 'CE'
					   BEGIN
						  UPDATE  AUTD SET VALORCOPAGO = 0, AUTD.AUTORIZADO = 1, AUTD.MARCAPAGO = 0, IDTERCEROCA = @IDTERCEROCA
						  WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
					   END
					   ELSE
					   BEGIN
						  UPDATE  CIT SET VALORCOPAGO = 0 WHERE CONSECUTIVO = @IDAUT
					   END
					   RETURN   
					END
				 END
				 PRINT '@TIPOAFILIADO2='+@TIPOAFILIADO2
				 PRINT '@COBRARCOPA='+@COBRARCOPA
				 IF @COBRARCOPA = 'AMBOS' OR @COBRARCOPA = @TIPOAFILIADO2
				 BEGIN
					PRINT 'TIPOAFILIADO'
					SELECT @VALOR = ISNULL(VALOR, 0)
					FROM   MOCCD 
					WHERE  IDMODELOPC      = @IDMODELOPCA
					AND    TIPODEPAGO      = @TIPODEPAGO
					AND    CLASIFPC        = 'NA'
					AND    IDAGRUPACIONSER = 'NA'
					AND    ESCALASE        = @NIVELSOCIOEC         
					PRINT 'VALOR='+CAST(@VALOR AS VARCHAR(20))

					SELECT @VALORCOPAGO = CASE @FORMACOBRO
											   WHEN 'PORCENTAJE' THEN (@VALORAUTD * @VALOR / 100 )
											   WHEN 'VALOR' THEN @VALOR
											END
					SELECT @VALORCOPAGO = CASE @REDONDEO
											   WHEN 'UNIDAD'  THEN ROUND(@VALORCOPAGO,0)
											   WHEN 'DECENA'  THEN ROUND(@VALORCOPAGO,-1)
											   WHEN 'CENTENA' THEN ROUND(@VALORCOPAGO,-2)
											   WHEN 'MILLAR'  THEN ROUND(@VALORCOPAGO,-3)
											END
					PRINT 'VALORCOPAGO='+CAST(@VALORCOPAGO AS VARCHAR(20))
					IF @PROCEDENCIA = 'CE'
					BEGIN
					   UPDATE AUTD SET VALORCOPAGO = @VALORCOPAGO WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
					   IF @VALORCOPAGO > 0
					   BEGIN 
						  IF @VALORCOPAGO = @VALORAUTD
						  BEGIN
							 UPDATE AUTD SET AUTORIZADO = 0, AUTD.MARCAPAGO = 1, AUTD.IDTERCEROCA = @IDTERCEROCAD
							 WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
						  END
						  ELSE
						  BEGIN
							 UPDATE AUTD SET AUTORIZADO = 0, AUTD.MARCAPAGO = 1, AUTD.IDTERCEROCA = @IDTERCEROCA
							 WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM                  
						  END
					   END
					END
					ELSE
					BEGIN
					   UPDATE CIT SET VALORCOPAGO = @VALORCOPAGO WHERE CONSECUTIVO = @IDAUT
					END
				 END
				 ELSE
				 BEGIN
					UPDATE  AUTD SET VALORCOPAGO = 0, AUTD.AUTORIZADO = 1, AUTD.MARCAPAGO = 0, IDTERCEROCA = @IDTERCEROCA 
					WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
				 END 
			  END
			  IF UPPER(@CALCULARPOR) = 'ORDEN'
			  BEGIN
				 IF @PROCEDENCIA = 'CE'
				 BEGIN
					SELECT @OK = ISNULL(COUNT(*),0) FROM AUTD WHERE IDAUT = @IDAUT AND MARCACOPAGOORDEN = 1
					IF @OK = 0
					BEGIN
					   UPDATE AUTD SET MARCACOPAGOORDEN = 1 WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM
					END
					ELSE
					BEGIN
					   UPDATE AUTD SET MARCACOPAGOORDEN = 2 WHERE IDAUT = @IDAUT AND NO_ITEM = @NO_ITEM 
					END
				 END 
			  END
		  END
		  ELSE
		  BEGIN
			PRINT 'Entré por no coberturado'
			SELECT @VALORCOPAGO=CASE IIF(COALESCE(@TIPOCALCULO,'')='','P',@TIPOCALCULO) WHEN 'P' THEN (@VALORAUTD*@VALOR/100) ELSE @VALOR END

			IF @PROCEDENCIA = 'CE'
				UPDATE AUTD SET VALORCOPAGO=@VALORCOPAGO WHERE IDAUT=@IDAUT AND NO_ITEM=@NO_ITEM
			ELSE
				UPDATE CIT SET VALORCOPAGO=@VALORCOPAGO WHERE CONSECUTIVO=@IDAUT
		  END
	   END


	   IF @PROCEDENCIA = 'CE'
	   BEGIN
		  PRINT 'VOY A SPK_CONCEPTOCAJA_AUT'
		  EXEC SPK_CONCEPTOCAJA_AUT @IDAUT, @NO_ITEM, @IDADMINISTRADORA, @IDPLAN 
	   END
	   ELSE
	   BEGIN
		  PRINT 'VOY A SPK_PAGOSCAJA_CIT' 
		  IF DBO.FNK_VALORVARIABLE('GENERA_COPAGO_CITAS')<>'LLEGA'
		  BEGIN
			 EXEC SPK_PAGOSCAJA_CIT @IDAUT, @SYS_COMPUTERNAME, @COMPANIA, @IDSEDE, @USUARIO, @PART
		  END
		  ELSE IF EXISTS (SELECT 1 FROM CIT WHERE CONSECUTIVO=@IDAUT AND FECHALLEGA IS NOT NULL) AND DBO.FNK_VALORVARIABLE('CAMBIA_COPAGO_PROP')='SI'
        BEGIN
			 EXEC SPK_PAGOSCAJA_CIT @IDAUT, @SYS_COMPUTERNAME, @COMPANIA, @IDSEDE, @USUARIO, @PART
		  END
		  ELSE 
        BEGIN
			 PRINT 'Genero el Pago Cuando llegue el Paciente'
		  END
	   END
	   /*MOD.01 20090305 - INI - JQUIROGA */
	   IF DBO.FNK_VALORVARIABLE('MAN_NO_COBRABLES_CE') = 'SI' 
	   BEGIN  
	   IF @PROCEDENCIA = 'CE'
	   BEGIN
		  SELECT @OK = ISNULL(COUNT(*),0) FROM PPTD 
		  WHERE	IDTERCERO = @IDADMINISTRADORA 
		  AND IDPLAN = @IDPLAN 
		  AND IDSERVICIO = @IDSERVICIO 
		  AND IDAREA = DBO.FNK_VALORVARIABLE('IDAREACE')
		  IF @OK <> 0
		  BEGIN
			 UPDATE AUTD SET VALOR = 0, VALORCOPAGO = 0, VALOREXCEDENTE = 0, NOCOBRABLE = 1, VALORCOPAGOCOSTO = 0
			 WHERE	IDAUT   = @IDAUT 
			 AND    NO_ITEM = @NO_ITEM
		  END
	   END
	END ----@RECAUDADO
END

