IF EXISTS (SELECT name FROM sysobjects 
   WHERE name = 'SPK_DEVUELVERECIB_CAJA' AND type = 'P')
BEGIN
   DROP PROCEDURE SPK_DEVUELVERECIB_CAJA
END
GO
CREATE PROCEDURE DBO.SPK_DEVUELVERECIB_CAJA 
@CODCAJA VARCHAR(4), 
@CNSFACJ VARCHAR(20),
@COMPANIA VARCHAR(2),
@SEDE VARCHAR(5) 
WITH ENCRYPTION
AS  
DECLARE @OK SMALLINT
DECLARE @PREFCAJA SMALLINT
DECLARE @NVOCONSEC VARCHAR(20)
DECLARE @DATO VARCHAR(80)
DECLARE @TIPOCOPAGO VARCHAR(1)
DECLARE @PREFIJO VARCHAR(6)
DECLARE @DEVUELTO SMALLINT
DECLARE @ESTADO VARCHAR (3)
DECLARE @PROCEDENCIA VARCHAR(10)
DECLARE @NOADMISION VARCHAR(20)
BEGIN
   --IF EXISTS(SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ AND (CLASE_FAC='PAGO' OR CERRADA=1 OR ESTADO='A'))
   --BEGIN
   --   RAISERROR('Recibo de Caja no Aplica Para Devolución',16,1)
   --   RETURN
   --END
   SELECT   @OK = COUNT(*) FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
   
   IF @OK IS NULL
      SELECT @OK= 0
     
   IF @OK = 0
      RETURN
   
   SELECT @OK = COUNT(*) FROM CAJ WHERE CODCAJA = @CODCAJA
   
   IF @OK IS NULL
      SELECT @OK = 0
   
   IF @OK = 0
      RETURN  

   SELECT @DEVUELTO = ISNULL(DEVUELTO,0),@PROCEDENCIA=PROCEDENCIA,@NOADMISION=NOADMISION 
   FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
     
   INSERT INTO TFCJ (CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,
                     IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, CERRADA, FECHA, 
                     PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE, CNSACJ, TIPO, 
                     ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE,
                     AREAPRESTACION, CCOSTO, SUBCCOSTO, CLASER, IDENTIFICADOR, 
                     USUARIO, SYS_COMPUTERNAME, OBSERVACION)
   SELECT TCNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,
          IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, 0, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 
          PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE, NULL, 
          TIPO, 'P', 0, 0, 0, '',AREAPRESTACION, CCOSTO, SUBCCOSTO, CLASER, IDENTIFICADOR, 
          USUARIO, HOST_NAME(),LEFT(OBSERVACION,99)
   FROM   FCJ 
   WHERE  CNSFACJ = @CNSFACJ
   AND    CODCAJA = @CODCAJA
          
   SELECT @NVOCONSEC = TCNSFACJ FROM FCJ WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
   INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
                            TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
   SELECT N_RECIBO, @NVOCONSEC, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
                            TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO
   FROM   FCJD
   WHERE  CNSFACJ = @CNSFACJ    
   AND    CODCAJA = @CODCAJA 

    SELECT @ESTADO = ESTADO FROM FCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA

    PRINT '@PROCEDENCIA='+@PROCEDENCIA
    PRINT '@NOADMISION='+@NOADMISION
    IF @PROCEDENCIA='CE'
    BEGIN
       UPDATE AUT SET  NORECIBOCAJA=@NVOCONSEC,CODCAJA='',TIPOCAJA='TFCJ',GENEROCAJA=1  WHERE NOAUT=@NOADMISION
    END
    IF @PROCEDENCIA='CITAS'
    BEGIN
       PRINT 'ACTUALIZO LA CITA'
       UPDATE CIT SET  NORECIBOCAJA=@NVOCONSEC,CODCAJA='',TIPOCAJA='TFCJ',GENEROCAJA=1  WHERE CONSECUTIVO=@NOADMISION
    END
 
    IF @ESTADO <> 'A'
    BEGIN
       IF @DEVUELTO = 0
	   BEGIN
		   DELETE FROM PCJ WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA  
		   DELETE FROM FCJDD WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA  
		   DELETE FROM FCJD  WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
		   UPDATE FCJ SET ESTADO = 'D', ARCHIVADO = 1, NOADMISION = '', VALORTOTAL = 0 
	      WHERE CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
	   END
   END
  
   /*UPDATE USCXS SET CONSECUTIVO = CONSECUTIVO - 1 WHERE PREFIJO = '@FCJ' AND IDSEDE = @CODCAJA*/
  
END



