SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"FVCD1"},"USUARIO":"JJIMENEZ"}'

SELECT IDFORMATO,PROCEDENCIA, * FROM FTR WHERE N_FACTURA='FVCD1'

UPDATE FTR SET IDFORMATO='06E' WHERE N_FACTURA='FVCD1'

SELECT USUARIOCONF,IDAREA,CCOSTO,IDBODEGA, * FROM IMOV WHERE N_FACTURA='FVSF1'

UPDATE FTRD SET CCOSTO='10180102',AREAPRESTACION='4110'  WHERE N_FACTURA='FVSF1' 


SELECT * FROM UBEQ WHERE SYS_ComputerName=''