
SELECT
D.IDTIPOMOV,C.RUBRO,PTRUB.NOMRUBRO,B.CDP,COALESCE(D.VIGENCIA,'Actual')VIGENCIA, 
            B.RP,B.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,B.FECHARP,C.VALOR,C.SALDO, 
            B.ESTADO,B.CCOSTO,CEN.DESCRIPCION,B.OBJETIVO,C.RUBRO_ID,D.RUBRO_ID
FROM PTRP INNER JOIN PTRPD ON  B.COMPANIA=C.COMPANIA AND B.CONSECUTIVO=C.CONSECUTIVO 
                              AND B.CDP=C.CDP AND B.RP=C.RP
          INNER JOIN PTRUB ON C.RUBRO=PTRUB.RUBRO AND PTRUB.CONSECUTIVO=PTRUB.CONSECUTIVO AND PTRUB.CLASE=PTRUB.CLASE
          INNER JOIN TER ON B.IDTERCERO=TER.IDTERCERO
          INNER JOIN CEN ON B.CCOSTO=CEN.CCOSTO
          LEFT JOIN PTCDPD ON C.COMPANIA=D.COMPANIA AND D.CONSECUTIVO=C.CONSECUTIVO 
                              AND C.CDP=D.CDP AND C.CLASE=D.CLASE 
                              AND C.RUBRO=D.RUBRO AND C.ITEMCDPD=D.ITEM
WHERE 

SELECT D.IDTIPOMOV, C.RUBRO,PTRUB.NOMRUBRO,A.CDP,D.VIGENCIA,A.RP,A.CNSCXP,B.IDTERCERO, 
            TER.NIT,TER.RAZONSOCIAL,A.FECHA,C.VALOR,C.SALDO,A.ESTADO, 
            A.CCOSTO,CEN.DESCRIPCION,A.OBSERVACION
FROM PTCXP A INNER JOIN PTRP B ON A.CONSECUTIVO=B.CONSECUTIVO AND A.COMPANIA=B.COMPANIA 
                                  AND A.CDP=B.CDP AND A.RP=B.RP
             INNER JOIN TER ON B.IDTERCERO=TER.IDTERCERO
             INNER JOIN CEN ON B.CCOSTO=CEN.CCOSTO
             INNER JOIN PTCXPD C ON A.COMPANIA=C.COMPANIA AND A.CONSECUTIVO=C.CONSECUTIVO
                                    AND A.CDP=C.CDP AND A.RP=C.RP AND A.CNSCXP=C.CNSCXP
             INNER JOIN PTRUB ON C.RUBRO=PTRUB.RUBRO AND PTRUB.CONSECUTIVO=PTRUB.CONSECUTIVO AND PTRUB.CLASE=PTRUB.CLASE
             LEFT JOIN PTCDPD D ON C.COMPANIA  = D.COMPANIA AND C.CONSECUTIVO = D.CONSECUTIVO 
                                 AND C.CDP = D.CDP AND C.RUBRO = D.RUBRO AND C.RUBRO_ID = D.RUBRO_ID 
                                 AND C.ITEMCDPD = D.ITEM

SELECT B.RECO,B.FECHA,A.RUBRO,C.RECURSO, A.VIGENCIA,C.NOMRUBRO,TER.NIT,TER.RAZONSOCIAL,B.CNSFCXC,
            B.N_FACTURA,A.VALOR,A.SALDO,B.ESTADO,B.CCOSTO,CEN.DESCRIPCION,
            B.OBJETIVO,A.RUBRO_ID
FROM PTRECOD A INNER JOIN PTRECO B ON A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO 
                                      AND A.RECO=B.RECO
               INNER JOIN PTRUB C ON A.RUBRO_ID=C.RUBRO_ID
               INNER JOIN TER ON B.IDTERCERO=TER.IDTERCERO
               INNER JOIN CEN ON B.CCOSTO=CEN.CCOSTO

SELECT A.RECO,D.NIT IDTERCERO,D.RAZONSOCIAL, A.CNSPAGO,B.FECHA,A.RUBRO,E.RECURSO,COALESCE(F.VIGENCIA,'Actual')VIGENCIA,E.NOMRUBRO, 
            A.VALOR,B.ESTADO,B.CCOSTO,CEN.DESCRIPCION,A.OBSERVACION,A.RUBRO_ID
FROM PTRECAD A INNER JOIN PTRECA B ON A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO
                                      AND A.RECO=B.RECO AND A.CNSPAGO=B.CNSPAGO
               INNER JOIN PTRECO C ON B.COMPANIA=C.COMPANIA AND B.CONSECUTIVO=C.CONSECUTIVO 
                                      AND B.RECO=C.RECO
               INNER JOIN TER D    ON  C.IDTERCERO=D.IDTERCERO
               INNER JOIN PTRUB E  ON A.RUBRO_ID=E.RUBRO_ID
               INNER JOIN CEN ON B.CCOSTO=CEN.CCOSTO
               LEFT JOIN PTRECOD F ON A.COMPANIA=F.COMPANIA AND A.CONSECUTIVO=F.CONSECUTIVO 
                                      AND A.RECO=F.RECO AND A.RUBRO=F.RUBRO

SELECT A.IDTIPOMOV,A.RUBRO,A.RECURSO, PTRUB.NOMRUBRO,B.CDP,A.VIGENCIA,B.FECHAEXPEDICION,A.VALOR,
            A.VALOR_RP,A.SALDO,B.CCOSTO,CEN.DESCRIPCION,B.OBJETIVO
FROM PTCDPD A INNER JOIN PTCDP B ON A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO  AND A.CDP=B.CDP
              INNER JOIN PTRUB ON A.RUBRO_ID=PTRUB.RUBRO_ID
              INNER JOIN CEN ON B.CCOSTO=CEN.CCOSTO


SELECT A.COMPANIA,A.CONSECUTIVO, A.MES,A.RUBRO,A.IDTIPOMOV,A.RECURSO,  A.RUBRO_ID,A.ORDEN,A.NOMRUBRO,A.TIPO, 
            A.PPT_INICIAL,A.VLR_INICIAL,A.VLR_TDB_ACU, A.VLR_TDB,A.VLR_TRC_ACU,A.VLR_TCR,A.VLR_MDB_ACU, 
            A.VLR_MDB,A.VLR_MCR_ACU,A.VLR_MCR,A.VLR_FINAL, A.VLR_CDP_ACU,A.VLR_CDP_MES,A.VLR_CDPA_MES,
            A.VLR_CDP_TOT,A.VLR_CDP_POR,A.VLR_RP_ACU, A.VLR_RP_MES,A.VLR_RPA_MES,A.VLR_RP_TOT, 
            A.VLR_RP_POR,A.VLR_CXP_ACU,A.VLR_CXP_MES, A.VLR_CXPA_MES,A.VLR_CXP_TOT,A.VLR_CXP_POR, 
            A.VLR_PAG_ACU,A.VLR_PAG_MES,A.VLR_PAGA_MES,A.VLR_PAG_TOT,A.VLR_PAG_POR,A.VLR_APROPIACION,
            A.VLR_PORPAGAR
FROM VWK_PTOG_EJEXRUBRO A


SELECT LEN('VALIDACITAVSAFILIADO')

SELECT COUNT(*)
FROM CIT INNER JOIN AFI ON CIT.IDAFILIADO=AFI.IDAFILIADO
WHERE CIT.IDTERCEROCA=AFI.IDADMINISTRADORA
AND CIT.IDPLAN=AFI.IDPLAN
AND CIT.CONSECUTIVO=