USE KUHEMOONC

SELECT IDFORMATO,  * FROM FTR WHERE N_FACTURA='U4904'

UPDATE FTR SET IDFORMATO='03GS' WHERE N_FACTURA='U4904'
SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"U4904"},"USUARIO":"JJIMENEZ"}'

SELECT TIPOFIN, * FROM FTR 