 SELECT *
FROM PTCDPD INNER JOIN PTRPD ON PTCDPD.CDP=PTRPD.CDP AND PTCDPD.RUBRO=PTRPD.RUBRO AND PTCDPD.CONSECUTIVO=PTRPD.CONSECUTIVO
WHERE PTCDPD.CONSECUTIVO='2023'

ALTER TABLE PTRPD ENABLE TRIGGER ALL

UPDATE PTRPD SET ITEMCDPD=PTCDPD.ITEM
FROM PTCDPD INNER JOIN PTRPD ON PTCDPD.CDP=PTRPD.CDP AND PTCDPD.RUBRO=PTRPD.RUBRO AND PTCDPD.CONSECUTIVO=PTRPD.CONSECUTIVO
WHERE PTCDPD.CONSECUTIVO='2023'

ALTER TABLE PTCXPD ENABLE TRIGGER ALL

UPDATE PTCXPD SET ITEMCDPD=PTCDPD.ITEM
FROM PTCDPD INNER JOIN PTCXPD ON PTCDPD.CDP=PTCXPD.CDP AND PTCDPD.RUBRO=PTCXPD.RUBRO AND PTCDPD.CONSECUTIVO=PTCXPD.CONSECUTIVO
WHERE PTCDPD.CONSECUTIVO='2023'

ALTER TABLE PTPAGD ENABLE TRIGGER ALL

UPDATE PTPAGD SET ITEMCDPD=PTCDPD.ITEM
FROM PTCDPD INNER JOIN PTPAGD ON PTCDPD.CDP=PTPAGD.CDP AND PTCDPD.RUBRO=PTPAGD.RUBRO AND PTCDPD.CONSECUTIVO=PTPAGD.CONSECUTIVO
WHERE PTCDPD.CONSECUTIVO='2023'
 
 ALTER TABLE PTCDPD enable TRIGGER ALL
 ALTER TABLE PTCDP enable TRIGGER ALL
 UPDATE PTCDPD  
 SET VALOR_RP = ISNULL(B.VALOR,0)  
 FROM PTCDPD A  LEFT JOIN (SELECT A.COMPANIA, A.CONSECUTIVO, A.CDP, A.CLASE, A.RUBRO, B.CCOSTO,A.ITEMCDPD, SUM(A.VALOR-COALESCE(A.VLR_LIBERADO,0)) VALOR   
                          FROM   PTRPD A INNER JOIN PTRP  B ON A.COMPANIA=B.COMPANIA 
                                                           AND A.CONSECUTIVO=B.CONSECUTIVO 
                                                           AND A.CDP=B.CDP 
                                                           AND A.RP=B.RP  
                          WHERE B.ESTADO = 'Confirmado'
                          AND B.CONSECUTIVO='2023'
                          GROUP BY A.COMPANIA, A.CONSECUTIVO, A.CDP, A.CLASE, A.RUBRO, B.CCOSTO,A.ITEMCDPD) B ON A.COMPANIA=B.COMPANIA 
                                                                                                  AND A.CONSECUTIVO=B.CONSECUTIVO 
                                                                                                  AND A.CDP=B.CDP 
                                                                                                  AND A.CLASE=B.CLASE 
                                                                                                  AND A.RUBRO=B.RUBRO                                                                                           
                                                                                                  AND A.ITEM=B.ITEMCDPD
      WHERE A.CONSECUTIVO='2023'


		UPDATE PTCDPD SET SALDO = A.VALOR - A.VALOR_RP-COALESCE(A.VLR_LIBERADO,0)
		FROM PTCDPD A INNER JOIN PTCDP B ON A.COMPANIA = B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO AND A.CDP=B.CDP 
      WHERE B.ESTADO='Confirmado'
      AND B.CONSECUTIVO='2023'

		UPDATE PTCDP SET VALOR = ISNULL(P2.VALOR,0), SALDO = ISNULL(P2.SALDO,0)
		FROM PTCDP P1	INNER JOIN (SELECT COMPANIA, CONSECUTIVO, CDP, SUM(VALOR) AS VALOR, SUM(SALDO) AS SALDO
									FROM PTCDPD WHERE CONSECUTIVO='2023' GROUP BY COMPANIA, CONSECUTIVO, CDP ) P2 ON P1.COMPANIA = P2.COMPANIA AND P1.CONSECUTIVO=P2.CONSECUTIVO AND P1.CDP=P2.CDP
		WHERE P1.CONSECUTIVO='2023'
      AND P1.ESTADO='Confirmado'


ALTER TABLE PTRPD ENABLE TRIGGER ALL
 UPDATE PTRPD
 SET VALOR_CXP = ISNULL(B.VALOR,0)
 FROM PTRPD A INNER JOIN
      PTCXP C ON A.COMPANIA=C.COMPANIA AND A.CONSECUTIVO=C.CONSECUTIVO AND A.CDP=C.CDP AND A.RP=C.RP  LEFT JOIN
      (SELECT A.COMPANIA, A.CONSECUTIVO, A.CDP, A.RP, A.CLASE, A.RUBRO, B.CCOSTO,A.ITEMCDPD, SUM(A.VALOR) VALOR 
       FROM PTCXPD A INNER JOIN
            PTCXP  B ON A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO AND A.CDP=B.CDP AND A.RP=B.RP AND 
                        A.CNSCXP=B.CNSCXP
       WHERE B.ESTADO = 'Confirmado'
       GROUP BY A.COMPANIA, A.CONSECUTIVO, A.CDP, A.RP, A.CLASE, A.RUBRO, B.CCOSTO,A.ITEMCDPD) B ON
        A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO AND A.CDP=B.CDP AND A.RP=B.RP AND
        A.CLASE=B.CLASE AND A.RUBRO=B.RUBRO AND C.CCOSTO = B.CCOSTO AND A.ITEMCDPD=B.ITEMCDPD
    WHERE A.CONSECUTIVO='2023'

ALTER TABLE PTCXPD ENABLE TRIGGER ALL
 UPDATE PTCXPD
 SET VALOR_PAG = ISNULL(B.VALOR,0)
 FROM PTCXPD A INNER JOIN
      PTPAG C ON A.COMPANIA=C.COMPANIA AND A.CONSECUTIVO=C.CONSECUTIVO AND A.CDP=C.CDP AND A.RP=C.RP AND 
                    A.CNSCXP = C.CNSCXP LEFT JOIN
      (SELECT A.COMPANIA, A.CONSECUTIVO, A.CDP, A.RP, A.CNSCXP, A.CLASE, A.RUBRO, B.CCOSTO,A.ITEMCDPD, SUM(A.VALOR) VALOR 
       FROM PTPAGD A INNER JOIN
            PTPAG  B ON A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO AND A.CDP=B.CDP AND A.RP=B.RP AND 
                        A.CNSCXP=B.CNSCXP AND A.CNSPAGO=B.CNSPAGO
       WHERE B.ESTADO = 'Confirmado'
       GROUP BY A.COMPANIA, A.CONSECUTIVO, A.CDP, A.RP, A.CNSCXP, A.CLASE, A.RUBRO, B.CCOSTO,A.ITEMCDPD) B ON
        A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO AND A.CDP=B.CDP AND A.RP=B.RP AND A.CNSCXP = B.CNSCXP AND
        A.CLASE=B.CLASE AND A.RUBRO=B.RUBRO AND C.CCOSTO = B.CCOSTO AND A.ITEMCDPD =B.ITEMCDPD
        WHERE A.CONSECUTIVO='2023'

ALTER TABLE PTRPD ENABLE TRIGGER ALL
  UPDATE PTRPD SET SALDO = PTRPD.VALOR - PTRPD.VALOR_CXP
  FROM PTRPD  INNER JOIN
       PTRP B ON PTRPD.COMPANIA = B.COMPANIA AND PTRPD.CONSECUTIVO=B.CONSECUTIVO AND PTRPD.CDP=B.CDP AND 
                     PTRPD.RP=B.RP --AND A.CLASE=B.CLASE AND A.RUBRO=B.RUBRO
      WHERE B.ESTADO='Confirmado'
      AND B.CONSECUTIVO='2023'


ALTER TABLE PTRP ENABLE TRIGGER ALL 
  UPDATE PTRP SET VALOR = ISNULL(PTRPD.VALOR,0), SALDO = ISNULL(PTRPD.SALDO,0)
  FROM PTRP LEFT JOIN
       (SELECT COMPANIA, CONSECUTIVO, CDP, RP, SUM(VALOR) VALOR, SUM(SALDO) SALDO
        FROM PTRPD 
        GROUP BY COMPANIA, CONSECUTIVO, CDP, RP) PTRPD ON 
         PTRP.COMPANIA = PTRPD.COMPANIA AND PTRP.CONSECUTIVO=PTRPD.CONSECUTIVO AND 
         PTRP.CDP=PTRPD.CDP AND PTRP.RP=PTRPD.RP 
   WHERE PTRP.CONSECUTIVO='2023'
   AND PTRP.ESTADO='Confirmado'

   ALTER TABLE PTCXPD ENABLE TRIGGER ALL
  UPDATE PTCXPD SET SALDO = PTCXPD.VALOR - PTCXPD.VALOR_PAG
  FROM PTCXPD   INNER JOIN
       PTCXP B ON PTCXPD.COMPANIA = B.COMPANIA AND PTCXPD.CONSECUTIVO=B.CONSECUTIVO AND PTCXPD.CDP=B.CDP AND 
                     PTCXPD.RP=B.RP AND PTCXPD.CNSCXP=B.CNSCXP -- AND A.CLASE=B.CLASE AND A.RUBRO=B.RUBRO
   WHERE B.CONSECUTIVO='2023'
   AND B.ESTADO='Confirmado'

  ALTER TABLE PTCXP ENABLE TRIGGER ALL
  UPDATE PTCXP SET VALOR = ISNULL(PTCXPD.VALOR,0), SALDO = ISNULL(PTCXPD.SALDO,0)
  FROM PTCXP LEFT JOIN
       (SELECT COMPANIA, CONSECUTIVO, CDP, RP, CNSCXP, SUM(VALOR) VALOR, SUM(SALDO) SALDO
        FROM PTCXPD 
        GROUP BY COMPANIA, CONSECUTIVO, CDP, RP, CNSCXP) PTCXPD ON 
         PTCXP.COMPANIA = PTCXPD.COMPANIA AND PTCXP.CONSECUTIVO=PTCXPD.CONSECUTIVO AND 
         PTCXP.CDP=PTCXPD.CDP AND PTCXP.RP=PTCXPD.RP AND PTCXP.CNSCXP=PTCXPD.CNSCXP 
   WHERE PTCXP.CONSECUTIVO='2023'
   AND PTCXP.ESTADO='Confirmado'

 ALTER TABLE PTPAG ENABLE TRIGGER ALL
 UPDATE PTPAG SET VALOR = ISNULL(PTPAGD.VALOR,0)
 FROM PTPAG LEFT JOIN
      (SELECT COMPANIA, CONSECUTIVO, CDP, RP, CNSCXP, CNSPAGO, SUM(VALOR) VALOR
       FROM PTPAGD 
       GROUP BY COMPANIA, CONSECUTIVO, CDP, RP, CNSCXP, CNSPAGO) PTPAGD ON 
        PTPAG.COMPANIA = PTPAGD.COMPANIA AND PTPAG.CONSECUTIVO=PTPAGD.CONSECUTIVO AND 
        PTPAG.CDP=PTPAGD.CDP AND PTPAG.RP=PTPAGD.RP AND PTPAG.CNSCXP=PTPAGD.CNSCXP AND PTPAG.CNSPAGO=PTPAGD.CNSPAGO
   WHERE PTPAG.CONSECUTIVO='2023'
   AND PTPAG.ESTADO='Confirmado'