
DROP TABLE #A
DROP TABLE #B
SELECT  MCP.NROCOMPROBANTE,MCP.NOREFERENCIA,MCH.NROASIENTO,MCH.IDTERCERO,MCH.TIPO,MCH.PREFIJO,MCH.VALOR INTO #A
FROM MCP INNER JOIN MCH ON MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE
WHERE MCP.PROCEDENCIA='NOMINA' AND ANO='2023'AND MCP.ESTADO=2
AND MCH.PREFIJO='CN42'
AND MCH.TIPO='DB'
AND MCH.IDTERCERO<>'0100000053'

SELECT  MCP.NROCOMPROBANTE,MCP.NOREFERENCIA,MCH.NROASIENTO,MCH.IDTERCERO,MCH.TIPO,MCH.PREFIJO,MCH.VALOR,CONVERT(DECIMAL(14,0),(MCH.VALOR*0.12))VL_PROVI INTO #B
FROM MCP INNER JOIN MCH ON MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE
WHERE MCP.PROCEDENCIA='NOMINA' AND ANO='2023'AND MCP.ESTADO=2
AND MCH.PREFIJO='CN40'
AND MCH.TIPO='DB'
AND MCH.IDTERCERO<>'0100000053'


SELECT * FROM #A 
SELECT * FROM #B 

UPDATE #A SET VALOR=#B.VL_PROVI
FROM #A INNER JOIN #B ON #A.NROCOMPROBANTE=#B.NROCOMPROBANTE

UPDATE MCP SET ESTADO=1 
FROM MCP INNER JOIN #A ON MCP.NROCOMPROBANTE=#A.NROCOMPROBANTE

-- REVISO VALORES

SELECT 'EXEC SPK_SUMA_DBCR '''+NROCOMPROBANTE+'''' FROM #B

UPDATE MCH SET VALOR=#A.VALOR
FROM MCH INNER JOIN #A ON MCH.NROCOMPROBANTE=#A.NROCOMPROBANTE AND MCH.NROASIENTO=#A.NROASIENTO

ALTER TABLE MCH ENABLE TRIGGER ALL
UPDATE MCH SET ESTADO=2
FROM MCH INNER JOIN #A ON MCH.NROCOMPROBANTE=#A.NROCOMPROBANTE

UPDATE MCP SET ESTADO=2
FROM MCP INNER JOIN #A ON MCP.NROCOMPROBANTE=#A.NROCOMPROBANTE




SELECT  * FROM TER WHERE NIT='1048018938'

SELECT * FROM MCH WHERE NROCOMPROBANTE='0611500000008845'



SELECT  * FROM NIEPED WHERE NROCOMPROBANTE IN(SELECT NROCOMPROBANTE FROM #A)

SELECT * FROM NIEPED


SELECT  * FROM BMOV WHERE CNSFACJ='E00002142'

SELECT  * FROM PCJ WHERE CTA_BCO='16163448740'

SELECT * FROM BMOV WHERE ITEM=2163

UPDATE BMOV SET ESTADO='O' WHERE ITEM=2163


SELECT * FROM NIEPED INNER JOIN #A ON NIEPED.NROCOMPROBANTE=#A.NROCOMPROBANTE AND NIEPED.NOREFERENCIA=#A.NOREFERENCIA AND NIEPED.IDTERCERO_PRF=#A.IDTERCERO AND NIEPED.CODCONCEPTO=#A.PREFIJO
WHERE NIEPED.RAZONSOCIAL_PRF LIKE '%JIMENEZ GOMEZ CRISTIAN CAMILO%'

UPDATE NIEPED SET VALOR_APORTES=#A.VALOR,TOTAL_NOMINA=#A.VALOR
FROM NIEPED INNER JOIN #A ON NIEPED.NROCOMPROBANTE=#A.NROCOMPROBANTE AND NIEPED.NOREFERENCIA=#A.NOREFERENCIA AND NIEPED.IDTERCERO_PRF=#A.IDTERCERO AND NIEPED.CODCONCEPTO=#A.PREFIJO