

SELECT  * FROM HCA WHERE NOADMISION='0200000031' AND CLASEPLANTILLA='OMEDICA'  ORDER BY FECHA DESC

SELECT DISTINCT HCATD.CONSECUTIVO,HCATD.ITEMRED 
FROM HCATD INNER JOIN HCA ON HCA.CONSECUTIVO=HCATD.CONSECUTIVO
WHERE HCA.NOADMISION='0200000031'
AND HCA.CLASEPLANTILLA='OMEDICA'
AND HCATD.CODOM NOT IN('001','002','005')



SELECT DISTINCT NOADMISION INTO #NM FROM HCA WHERE NOT EXISTS(SELECT * FROM HCATD WHERE CODOM IN('001','002','005') AND HCATD.CONSECUTIVO=HCA.CONSECUTIVO)
AND HCA.CLASEPLANTILLA='OMEDICA'




SELECT  * INTO #X FROM #NM WHERE EXISTS(SELECT  * FROM HADM WHERE HADM.NOADMISION=#NM.NOADMISION AND HADM.CERRADA=0)

select  * INTO #B from hcatd where CONSECUTIVo='01002633' AND CODOM IN('001','002','005')

SELECT  *  INTO #C FROM HCAPM WHERE CONSECUTIVO='01002633' AND CLAMED IN('001','002','005')

SELECT  * FROM HCATD WHERE CONSECUTIVO='0200000031_11'



DROP TABLE #A
SELECT  * FROM #X ORDER BY NOADMISION
SELECT  CONSECUTIVO,ITEMRED INTO #A FROM HCA WHERE NOT EXISTS(SELECT * FROM HCATD WHERE CODOM IN('001','002','005') AND HCATD.CONSECUTIVO=HCA.CONSECUTIVO)
AND HCA.CLASEPLANTILLA='OMEDICA'
AND HCA.NOADMISION IN(SELECT * FROM #X)

DELETE #X WHERE NOADMISION='0100000029'

      INSERT INTO HCATD (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, CLASE, ENCARGOS, NOPRESTACION, 
                          APLICADA, CONSECUTIVONE, NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION,  TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR,
                          CANTIDADNOCC, CNSHJNOPOS, DESCRIPTIVA, DESTINO, OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, 
                          CANTIDADORI, FRECUENCIAORI,  DURACIONORI, DOSISUNICA, FECHAINI, IDSERVICIOMEZCLA, QMEZCLA, QIMPSERVICIO, QIMPMEZCLA, 
                          DURACIONIMP, RAZONNEC, ORDEN, HORAAM, QAM, HORAPM, QPM, HORASMAX, FECHAMAX, GOTEO,  GENHORARIO, LUNES, MARTES, MIERCOLES,
                          JUEVES, VIERNES, SABADO, DOMINGO, FFINALDOSIS, TIPOSOLBS, BSCAPACIDAD, IDBODEGA, CODPAQUETE, VERIFICA, LATERALIDAD, 
                          TIPOFRECUENCIA, DOSIF,  ESTADOCALL, FECHACALL, USUARIO, NOADMISION, OBS_CALL, IDCAUSAL, AUTORIZADO, HBALINI, RUTA, 
                          TOTALUNIDADES, PRESCRIPCION, TIPODURACION)
      SELECT #A.CONSECUTIVO, #A.ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, 'C', ENCARGOS, NOPRESTACION, APLICADA, 
             CONSECUTIVONE, NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION,  TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR, CANTIDADNOCC, 
             CNSHJNOPOS, DESCRIPTIVA, DESTINO, OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, CANTIDADORI, 
             FRECUENCIAORI,  DURACIONORI, DOSISUNICA, FECHAINI, IDSERVICIOMEZCLA, QMEZCLA, QIMPSERVICIO, QIMPMEZCLA, DURACIONIMP, 
             RAZONNEC, ORDEN, HORAAM, QAM, HORAPM, QPM, HORASMAX, FECHAMAX, GOTEO,  GENHORARIO, LUNES, MARTES, MIERCOLES, JUEVES, 
             VIERNES, SABADO, DOMINGO, FFINALDOSIS, TIPOSOLBS, BSCAPACIDAD, IDBODEGA, CODPAQUETE, VERIFICA, LATERALIDAD, TIPOFRECUENCIA, 
             DOSIF,  ESTADOCALL, FECHACALL, USUARIO, NOADMISION, OBS_CALL, IDCAUSAL, AUTORIZADO, HBALINI, RUTA, TOTALUNIDADES, PRESCRIPCION,
             TIPODURACION
      FROM #A,#B

      INSERT INTO HCAPM(CONSECUTIVO, ORDEN, CLASE, OBSERVACION, IDSERVICIO, CLAMED, SECOPIA)
      SELECT #A.CONSECUTIVO,COALESCE((SELECT MAX(ORDEN) FROM HCAPM WHERE CONSECUTIVO=#A.CONSECUTIVO),0)+ROW_NUMBER() OVER(ORDER  BY #A.CONSECUTIVO  DESC) ORDEN,
      CLASE, OBSERVACION, IDSERVICIO, CLAMED, SECOPIA
      FROM #A,#C