--DIFERENCIA 
DECLARE @N_FACTURA VARCHAR(20)
DECLARE @CBTE   VARCHAR(20)
DECLARE @MES    INT
DECLARE @COMPROBANTE VARCHAR(4)
DECLARE @COMPANIA    VARCHAR(2)
DECLARE @ANO         VARCHAR(4)
DECLARE @SEDE        VARCHAR(5)


SET @COMPANIA='01'
SET @COMPROBANTE='42'
SET @ANO='2014'
SET @MES=6

DECLARE @DIFERENCIA DECIMAL(14,2)
DECLARE CXC_CURSOR CURSOR FOR
SELECT NROCOMPROBANTE FROM MCPE 
WHERE COMPROBANTE = @COMPROBANTE AND COMPANIA=@COMPANIA
AND MES =@MES AND ANO = @ANO  AND TOTALDEBITO <> TOTALCREDITO 
OPEN CXC_CURSOR
FETCH NEXT FROM CXC_CURSOR
INTO @N_FACTURA
WHILE @@FETCH_STATUS = 0
BEGIN
		 SELECT @DIFERENCIA = TOTALDEBITO - TOTALCREDITO 
		 FROM  MCPE 
		 WHERE COMPROBANTE = @COMPROBANTE AND COMPANIA=@COMPANIA
   AND MES =@MES AND ANO = @ANO
   AND NROCOMPROBANTE = @N_FACTURA
		 IF @DIFERENCIA < 0
		 BEGIN
		    SELECT @CBTE = MIN( MCHE.NROASIENTO) FROM MCHE WHERE TIPO = 'DB'
		    AND COMPANIA =@COMPANIA AND MCHE.NROCOMPROBANTE = @N_FACTURA
		 
 	    UPDATE  MCHE
		    SET MCHE.VALOR = MCHE.VALOR + (@DIFERENCIA * -1)
		    WHERE MCHE.COMPANIA =@COMPANIA 
      AND MCHE.NROASIENTO      IN (@CBTE)
		 END
		 IF @DIFERENCIA > 0
		 BEGIN
		    SELECT @CBTE = MIN(MCHE.NROASIENTO) FROM MCHE WHERE TIPO = 'CR'
		    AND COMPANIA =@COMPANIA AND MCHE.NROCOMPROBANTE = @N_FACTURA
		
		    UPDATE  MCHE
		    SET MCHE.VALOR = MCHE.VALOR + (@DIFERENCIA)
		    WHERE MCHE.COMPANIA =@COMPANIA 
      AND MCHE.NROASIENTO      IN (@CBTE)
		 END
		 SELECT @SEDE=IDSEDE FROM MCPE WHERE NROCOMPROBANTE=@N_FACTURA
		 EXEC SPK_NC_REVISAMCPE  @N_FACTURA,'01','SOPORTE',@SEDE,'IXSOPORTE'
		 FETCH NEXT FROM CXC_CURSOR
	  INTO @N_FACTURA
END
CLOSE CXC_CURSOR
DEALLOCATE CXC_CURSOR


