
DELETE Evo_Export_det 
DELETE Evo_Export_par
DELETE Evo_Rep_usu
DELETE Evo_Exportacion

ALTER TABLE TEXCA DISABLE TRIGGER ALL
DELETE TEXCA
GO
ALTER TABLE TEXCA ENABLE TRIGGER ALL
GO
ALTER TABLE USGRUA DISABLE TRIGGER ALL
DELETE USGRUA
GO
ALTER TABLE USGRUA ENABLE TRIGGER ALL
GO

