	--BUSCAR DATOS EN TEXTOS
   
   DECLARE @POS1 INT, @POS2 INT
	SELECT @POS1 =CHARINDEX(' INDEX ',ORDEN,1) FROM INDEXS WHERE NRO=6
	SELECT @POS2 =CHARINDEX(' ON ',ORDEN,@POS1+7) FROM INDEXS WHERE NRO=6
	SELECT @POS1, @POS2
	SELECT SUBSTRING(ORDEN,@POS1+7,@POS2-@POS1-7) FROM INDEXS WHERE NRO=6
		SELECT * FROM INDEXS WHERE NRO=2