SELECT NIT, COUNT(*) NRO INTO #C FROM TER WHERE ESTADO='Activo'
GROUP BY NIT
HAVING COUNT(*)>1

SELECT CASE WHEN IDTERCERO LIKE '0%' THEN  'SISTEMA' ELSE 'OTRO' END PROCE, * INTO #D FROM TER WHERE NIT IN(SELECT NIT FROM #C)


SELECT * FROM #D WHERE PROCE='SISTEMA'
SELECT * FROM #D WHERE PROCE<>'SISTEMA'

UPDATE TER SET ESTADO='Inactivo' WHERE IDTERCERO IN(SELECT IDTERCERO FROM #D WHERE PROCE<>'SISTEMA')
