USE CEM
SELECT ROW_NUMBER() OVER(PARTITION BY CODCARGO,NIVEL,GRADO ORDER BY CODCARGO,NIVEL,GRADO DESC)NRO,* 
--INTO #A 
FROM NCARNGV WHERE HORASDELABOR=235

SELECT  * INTO #B FROM #A WHERE NRO=2

DELETE #A WHERE EXISTS(SELECT * FROM #B WHERE #A.CODCARGO=#B.CODCARGO  AND #A.NIVEL=#B.NIVEL AND #A.GRADO=#B.GRADO) AND NRO=1


SELECT * FROM #A

UPDATE #A SET HORASDELABOR=235,FECHA='15/07/2023',CNSAJUSTE='AJ20230715'

ALTER TABLE #A DROP COLUMN NRO
INSERT INTO NCARNGV
SELECT * FROM #A

DECLARE @NUMDOC VARCHAR(20)
DECLARE @CODCARGO VARCHAR(20)
DECLARE @NIVEL VARCHAR(10)
DECLARE @GRADO VARCHAR(10)
DECLARE @FECHA DATETIME ='01/07/2023'
DECLARE @BASICO DECIMAL(14,2)

	DECLARE AJUSTE_CURSOR CURSOR FOR 
   SELECT NUMDOC,CODCARGO,NIVEL,GRADO,BASICO FROM NEMP  
   WHERE ESTADO='Activo'
   AND COALESCE(FECHARETIRO ,GETDATE()+1)>GETDATE()
   AND FECHAINGRESO<='15/08/2023'
   AND COALESCE(HORASDELABOR,0)=240
	OPEN AJUSTE_CURSOR    
	FETCH NEXT FROM AJUSTE_CURSOR    
	INTO @NUMDOC,@CODCARGO,@NIVEL,@GRADO,@BASICO
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
		PRINT'EXISTE SOLO ACTUALIZO HORAS LABORALES'
		UPDATE NEMP SET HORASDELABOR=(SELECT TOP 1 HORASDELABOR FROM NCARNGV 
      WHERE CODCARGO=@CODCARGO AND NIVEL=@NIVEL AND GRADO=@GRADO  
      AND DBO.FNK_FECHA(FECHA)>=DBO.FNK_FECHA(@FECHA) ORDER BY HORASDELABOR)
		WHERE  NUMDOC=@NUMDOC 

	    
      PRINT 'EMPIEZO INSERT HISTORICO'
      DECLARE @ITEM INT 
      --SELECT MAX(ITEM)+1 FROM NEMPHIS WHERE NUMDOC=@NUMDOC
      INSERT INTO NEMPHIS(NUMDOC, FECHAMOV, SEXO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR, DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO, 
                           TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL, FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50, 
                           ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, USUARIOMOD, FECHAMOD, SYS_COMPUTERNAME, OPERACION)
      SELECT NUMDOC, @FECHA, SEXO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, @BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR, DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO, 
             TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL, FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50, 
            ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, 'Soporte', GETDATE(), 'SOPORTE', 'CAMBIA' 
      FROM NEMP WHERE NUMDOC=@NUMDOC


	FETCH NEXT FROM AJUSTE_CURSOR    
	INTO @NUMDOC,@CODCARGO,@NIVEL,@GRADO,@BASICO
	END
	CLOSE AJUSTE_CURSOR
	DEALLOCATE AJUSTE_CURSOR  


   SELECT HORASDELABOR,CODCARGO,NIVEL,GRADO, * FROM NEMP WHERE NUMDOC='0200000491'   
   SELECT HORASDELABOR,CODCARGO,NIVEL,GRADO, * FROM NEMPHIS WHERE NUMDOC='0200000491'

   SELECT  * FROM NEMP WHERE COALESCE(HORASDELABOR,0)<=0

   DELETE NEMPHIS WHERE HORASDELABOR IS NULL


   SELECT * FROM  NEMPHIS WHERE HORASDELABOR>235 AND FECHAMOV>='15/07/2023'

   UPDATE NEMPHIS SET HORASDELABOR=235 WHERE HORASDELABOR>235 AND FECHAMOV>='15/07/2023'

   SELECT  * FROM NEMP WHERE COALESCE(HORASDELABOR,0)<=0

   SELECT * FROM NEMPFD WHERE CNSPAGO IN('02202308P30-1','01202308P30-1')

   SELECT  * FROM NEDIA WHERE NUMDOC='0600009589'
   --, FECHAINI=DATEADD(DAY,-1,FECHAINI)

   --UPDATE NEDIA SET  FECHAFIN=DATEADD(DAY,1,FECHAFIN) WHERE NUMDOC='0600009589' AND ITEM=4335

   UPDATE NEMP SET HORASDELABOR=C.HORASDELABOR
   FROM NEMP INNER JOIN NCARNGV C ON NEMP.CODCARGO=C.CODCARGO AND NEMP.NIVEL=C.NIVEL AND NEMP.GRADO=C.GRADO
   WHERE NEMP.HORASDELABOR IS NULL


      NUMDOC='0100000053' AND CNSPAGO='01202308P30-1'