IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'CLD_VENCETOTAL' AND TYPE='V')
BEGIN
 DROP VIEW [CLD_VENCETOTAL]
END
GO
CREATE VIEW [dbo].[CLD_VENCETOTAL]  
AS
SELECT  V.IDTERCERO,V.RAZONSOCIAL,COALESCE(FTR.IDPLAN,'')IDPLAN, V.N_FACTURA,COALESCE(F.CNSCXC,'')CNSCXC,DBO.FNK_FECHA(FTR.F_FACTURA)F_FACTURA, COALESCE(DBO.FNK_FECHA(D.F_RAD),'') F_RAD, 
         COALESCE(FTR.VR_TOTAL,0) VR_TOTAL, COALESCE(V.NORADICADA,0) NORADICADA, COALESCE(V.PORVENCER, 0) PORVENCER, COALESCE(V.SALDO,0) SALDO, 
         COALESCE(V.D0_30,0) D0_30, COALESCE(V.D31_60,0) D31_60, COALESCE(V.D61_90,0) D61_90, COALESCE(V.D91_120,0) D91_120, 
         COALESCE(V.D121_150,0) D121_150, COALESCE(V.D151_180,0) D151_180, 
         COALESCE(V.D181_360,0) D181_360, COALESCE(V.D361_MAS,0) D361_MAS, COALESCE(F.VLRNOTADB,0) NOT_DB, COALESCE(F.VLRNOTACR,0) NOT_CR, 
         COALESCE(F.DEDUCCIONES,0) DEDUCCIONES, COALESCE(F.VLRPAGOS,0) VLRPAGOS, COALESCE(F.VLRGLOSAS,0) VLRGLOSAS, 
         COALESCE(F.VLRGLOSAS_R,0) VLRGLOSAS_R,CASE WHEN COALESCE(V.CONCILIADA,0)=COALESCE(F.VLRLEVANTADO,0) THEN 0 WHEN COALESCE(V.CONCILIADA,0)<=0 THEN COALESCE(F.VLRLEVANTADO,0) ELSE 0  END  VLRLEVANTADO ,
         COALESCE(V.CONCILIADA,0)CONCILIADA,
         COALESCE(D.G,0) G, COALESCE(D.R,0) R, COALESCE(D.C,0) C, FTR.TIPOTTEC,CASE WHEN PAGO_LEVANTADO>F.VLRLEVANTADO THEN F.VLRLEVANTADO ELSE PAGO_LEVANTADO END PAGO_LEVANTADO,V.ESTADOCONTA
FROM   (
         SELECT V.IDTERCERO,COALESCE(TER.RAZONSOCIAL,'')RAZONSOCIAL, V.N_FACTURA,  SUM(V.NORADICADA) NORADICADA, SUM(V.PORVENCER) PORVENCER, SUM(V.SALDONETO) SALDO, SUM(V.D0_30) D0_30, 
                  SUM(V.D31_60) D31_60, SUM(V.D61_90) D61_90, SUM(V.D91_120) D91_120, SUM(V.D121_150) D121_150, SUM(V.D151_180) D151_180, 
                  SUM(V.D181_360) D181_360, SUM(V.D361_MAS) D361_MAS,SUM(CASE WHEN V.TIPO='C' THEN V.SALDOINICIAL ELSE 0 END) CONCILIADA,--,
				  (SELECT SUM(FPAGD.VALORPAGO+FPAGD.VLRIMPUESTO) FROM FPAG INNER JOIN FPAGD ON FPAG.CNSFPAG=FPAGD.CNSFPAG
					 WHERE FPAG.IDTERCERO=V.IDTERCERO AND FPAGD.N_FACTURA=V.N_FACTURA AND FPAGD.CLASE IN('G','R')
					 AND EXISTS(SELECT * FROM FCXCDV WHERE FPAGD.N_FACTURA=FCXCDV.N_FACTURA    AND FPAGD.CLASE=FCXCDV.TIPO
					 AND FPAGD.CNSGLO=FCXCDV.CNSGLO AND  FCXCDV.VLRLEVANTADO>0  AND FCXCDV.TIPO IN('G','R')) AND FPAG.INGRESO='BANCOS' AND FPAG.CERRADO=1)PAGO_LEVANTADO,CASE WHEN COALESCE(FTR.CASTIGADA,0)=1 THEN 'CASTIGADA' ELSE 'NORMAL' END ESTADOCONTA
         FROM   DBO.VWK_CXCDIASVTO V  LEFT JOIN TER ON V.IDTERCERO=TER.IDTERCERO 
                                      LEFT JOIN  FTR ON V.N_FACTURA=FTR.N_FACTURA       
         GROUP BY V.IDTERCERO,TER.RAZONSOCIAL, V.N_FACTURA,CASE WHEN COALESCE(FTR.CASTIGADA,0)=1 THEN 'CASTIGADA' ELSE 'NORMAL' END 

         ) V LEFT JOIN DBO.FCXCD F ON V.N_FACTURA = F.N_FACTURA
            LEFT JOIN DBO.FTR     ON V.N_FACTURA = FTR.N_FACTURA
            LEFT JOIN DBO.FNK_DATFACTURAS() D ON V.N_FACTURA = D.N_FACTURA
      WHERE  COALESCE(V.SALDO,0)>0
      UNION  ALL
      SELECT FCXC.IDTERCERO,TER.RAZONSOCIAL,FTR.IDPLAN,FCXCD.N_FACTURA,FCXC.CNSCXC,DBO.FNK_FECHA(FTR.F_FACTURA),DBO.FNK_FECHA(FCXC.F_RECIBIDO),FTR.VR_TOTAL,FCXCD.VLRGLOSAS AS NORADICADA ,0 AS PORVENCER,FCXCD.VLRGLOSAS AS  SALDO,0,0,0,0,0,0,0,0,0,0,FCXCD.DEDUCCIONES,FCXCD.VLRPAGOS,
      FCXCD.VLRGLOSAS,FCXCD.VLRGLOSAS_R,COALESCE(FCXCD.VLRLEVANTADO,0),0,0,0,0,FTR.TIPOTTEC,0,CASE WHEN COALESCE(FTR.CASTIGADA,0)=1 THEN 'CASTIGADA' ELSE 'NORMAL' END ESTADOCONTA
      FROM FCXCD INNER JOIN FCXC  ON FCXCD.CNSCXC=FCXC.CNSCXC
                 INNER JOIN TER   ON FCXC.IDTERCERO=TER.IDTERCERO
                 INNER JOIN FTR   ON FCXCD.N_FACTURA=FTR.N_FACTURA
				 LEFT  JOIN FGLO  ON FCXCD.CNSCXC=FGLO.CNSGLO AND FCXCD.N_FACTURA=FGLO.N_FACTURA
      WHERE FCXCD.SALDO=0 AND FCXCD.VLRGLOSAS>0
GO


