DROP VIEW DBO.CLD_MOVI_INVENTARIOS
AS
SELECT IMOV.IDBODEGA,ITMO.TIPO,IMOV.CNSMOV,IMOV.FECHACONF,IMOV.IDTIPOMOV,ITMO.DESCRIPCION AS DESCTIPOMOV,IART.IDITAR,ITAR.DESCRIPCION AS TIPOART,IMOVH.IDARTICULO,IART.DESCRIPCION,SUM(IMOVH.CANTIDAD)CANTIDAD,AVG(IMOVH.PCOSTO)PCOSTO
FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
          INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
          LEFT  JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
          LEFT  JOIN ITAR  ON IART.IDITAR=ITAR.IDITAR
WHERE IMOV.ESTADO=1
AND IMOV.IDBODEGA IN('B6','B7')
AND COALESCE(ITMO.SECONTABILIZA,0)=1
AND ITMO.TIPO='Credito'
GROUP BY IMOV.IDBODEGA,ITMO.TIPO,IMOV.CNSMOV,IMOV.FECHACONF,IMOV.IDTIPOMOV,ITMO.DESCRIPCION ,IART.IDITAR,ITAR.DESCRIPCION,IMOVH.IDARTICULO,IART.DESCRIPCION
UNION ALL 
SELECT IMOV.IDBODEGA,ITMO.TIPO,IMOV.CNSMOV,IMOV.FECHACONF,IMOV.IDTIPOMOV,ITMO.DESCRIPCION AS DESCTIPOMOV,IART.IDITAR,ITAR.DESCRIPCION AS TIPOART,ISAL.IDARTICULO,IART.DESCRIPCION,SUM(ISAL.CANTIDAD)CANTIDAD,AVG(ISAL.PCOSTO)PCOSTO
FROM IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV
          INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
          LEFT  JOIN IART  ON ISAL.IDARTICULO=IART.IDARTICULO
          LEFT  JOIN ITAR  ON IART.IDITAR=ITAR.IDITAR
WHERE IMOV.ESTADO=1
AND IMOV.IDBODEGA IN('B6','B7')
AND COALESCE(ITMO.SECONTABILIZA,0)=1
AND ITMO.TIPO='Debito'
GROUP BY IMOV.IDBODEGA,ITMO.TIPO,IMOV.CNSMOV,IMOV.FECHACONF,IMOV.IDTIPOMOV,ITMO.DESCRIPCION ,IART.IDITAR,ITAR.DESCRIPCION,ISAL.IDARTICULO,IART.DESCRIPCION