SELECT *
FROM (

SELECT CASE WHEN IART.IDSERVICIO<>DBO.FNK_VALORVARIABLE('DEINVNODESER') THEN IART.IDSERVICIO ELSE IART.IDARTICULO END IDARTICULO,
(SELECT X.DESCRIPCION FROM IART X WHERE X.IDARTICULO=CASE WHEN IART.IDSERVICIO<>DBO.FNK_VALORVARIABLE('DEINVNODESER') THEN IART.IDSERVICIO ELSE IART.IDARTICULO END)DESCRIPCION,
SUM(CONVERT(INT,IMOVH.CANTIDAD))CANT,CONVERT(DECIMAL(14,2),AVG(IMOVH.PCOSTO))PCOSTO
FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
          INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
WHERE (IMOV.IDTIPOMOV=DBO.FNK_VALORVARIABLE('IDINVMOV_COMPRAS') OR  IMOV.IDTIPOMOV=DBO.FNK_VALORVARIABLE('IDINVMOV_REMISION_EN'))
AND IMOV.ESTADO=1
AND YEAR(IMOV.FECHACONF)='2018'
AND IART.IDITAR IN('01','02')
GROUP BY CASE WHEN IART.IDSERVICIO<>DBO.FNK_VALORVARIABLE('DEINVNODESER') THEN IART.IDSERVICIO ELSE IART.IDARTICULO END ) IART INNER JOIN
(
SELECT FTRD.REFERENCIA AS IDSERVICIO,SER.DESCSERVICIO,CONVERT(INT,SUM(FTRD.CANTIDAD))CANTIDAD,CONVERT(DECIMAL(14,2),AVG(FTRD.VALOR))VALOR
FROM FTR INNER JOIN FTRD ON FTR.N_FACTURA=FTRD.N_FACTURA
         INNER JOIN SER  ON FTRD.REFERENCIA=SER.IDSERVICIO
WHERE FTR.ESTADO='P'
AND COALESCE(FTR.TIPOANULACION,'')<>'NC'
AND COALESCE(SER.MEDICAMENTOS,0)=1
AND YEAR(FTR.F_FACTURA)='2018'
GROUP BY FTRD.REFERENCIA,SER.DESCSERVICIO) SER ON IART.IDARTICULO=SER.IDSERVICIO