
EXEC sp_configure FILESTREAM_ACCESS_LEVEL,2

RECONFIGURE
ALTER DATABASE SCOCOPLINDA ADD  FILEGROUP PLAYALINDA_FS CONTAINS FILESTREAM 

ALTER DATABASE SCOCOPLINDA ADD FILE(NAME = 'PLAYALINDA_FS', FILENAME ='C:\BDATOS\BDATA\PLAYALINDA_FS')
TO FILEGROUP PLAYALINDA_FS