 SELECT HCA.NOADMISION,HADM.TIPOADM,HTAD.DESCRIPCION,AFI.DOCIDAFILIADO,AFI.TIPO_DOC,(AFI.PNOMBRE+' '+COALESCE(AFI.SNOMBRE,'')+' '+AFI.PAPELLIDO+' '+COALESCE(AFI.SAPELLIDO,'')) NOMBRE,
 AFI.SEXO,CONVERT(DECIMAL(14,2),ROUND(DATEDIFF(DAY,AFI.FNACIMIENTO,HADM.FECHA)/365.25,1)) EDAD,AFI.DIRECCION,AFI.TELEFONORES,CIU.NOMBRE,HADM.FECHA AS F_INGRESO,HADM.FECHAALTAMED AS F_EGRESO,
 HCA.DIAGNOSTICOS,HCA.TRATAMIENTO
 FROM(
   
      SELECT NOADMISION,IDAFILIADO,PROCEDENCIA, STUFF((SELECT DISTINCT HCA.IDDX+' '+MDX.DESCRIPCION+' ' FROM HCA INNER JOIN  MDX  ON HCA.IDDX=MDX.IDDX  WHERE HCA.NOADMISION=HCA1.NOADMISION   FOR XML PATH('')),1,1,'') DIAGNOSTICOS,
      STUFF((SELECT DISTINCT HCATD.IDSERVICIO+'  '+SER.DESCSERVICIO+' '  FROM HCA INNER JOIN  HCATD ON HCA.CONSECUTIVO=HCATD.CONSECUTIVO
                                                                                  INNER JOIN SER ON HCATD.IDSERVICIO=SER.IDSERVICIO 
                                                                         WHERE HCA.NOADMISION=HCA1.NOADMISION AND COALESCE(SER.MEDICAMENTOS,0)=1 FOR XML PATH('')),1,1,'') TRATAMIENTO  
      FROM HCA HCA1
      WHERE PROCEDENCIA ='QX'
      AND HCA1.CLASE='HC'
      GROUP BY NOADMISION,IDAFILIADO,PROCEDENCIA
   ) HCA INNER JOIN HADM ON HCA.NOADMISION=HADM.NOADMISION
         INNER JOIN TER  ON HADM.IDTERCERO=TER.IDTERCERO
         INNER JOIN AFI  ON HADM.IDAFILIADO=AFI.IDAFILIADO
         INNER JOIN HTAD ON HADM.TIPOADM=HTAD.TIPOADM
         INNER JOIN CIU  ON AFI.CIUDAD=CIU.CIUDAD
   WHERE HADM.CLASEING='A'
   AND YEAR(HADM.FECHA)='2018'
   UNION ALL
 SELECT HCA.NOADMISION,'Cita','Atencio Citas',AFI.DOCIDAFILIADO,AFI.TIPO_DOC,(AFI.PNOMBRE+' '+COALESCE(AFI.SNOMBRE,'')+' '+AFI.PAPELLIDO+' '+COALESCE(AFI.SAPELLIDO,'')) NOMBRE,
 AFI.SEXO,CONVERT(DECIMAL(14,2),ROUND(DATEDIFF(DAY,AFI.FNACIMIENTO,CIT.FECHA)/365.25,1)) EDAD,AFI.DIRECCION,AFI.TELEFONORES,CIU.NOMBRE,CIT.FECHA,CIT.FECHA,
 HCA.DIAGNOSTICOS,HCA.TRATAMIENTO
 FROM(
      SELECT NOADMISION,IDAFILIADO,PROCEDENCIA, STUFF((SELECT DISTINCT HCA.IDDX+' '+MDX.DESCRIPCION+' ' FROM HCA INNER JOIN  MDX  ON HCA.IDDX=MDX.IDDX  WHERE HCA.NOADMISION=HCA1.NOADMISION   FOR XML PATH('')),1,1,'') DIAGNOSTICOS,
      STUFF((SELECT DISTINCT AUTD.IDSERVICIO+'  '+SER.DESCSERVICIO+' '  FROM HCA INNER JOIN  AUT ON HCA.CONSECUTIVO=AUT.CONSECUTIVOHCA  INNER JOIN AUTD ON AUT.IDAUT=AUTD.IDAUT  INNER JOIN SER ON AUTD.IDSERVICIO=SER.IDSERVICIO WHERE HCA.NOADMISION=HCA1.NOADMISION FOR XML PATH('')),1,1,'')  TRATAMIENTO
      FROM HCA HCA1
      WHERE PROCEDENCIA ='IPS'
      AND HCA1.CLASE='HC'
      GROUP BY NOADMISION,IDAFILIADO,PROCEDENCIA
   ) HCA INNER JOIN CIT ON HCA.NOADMISION=CIT.CONSECUTIVO
         INNER JOIN TER  ON CIT.IDTERCEROCA=TER.IDTERCERO
         INNER JOIN AFI  ON CIT.IDAFILIADO=AFI.IDAFILIADO
         INNER JOIN CIU  ON AFI.CIUDAD=CIU.CIUDAD
   WHERE YEAR(CIT.FECHA)='2018'

