 SELECT FTR.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,FTR.IDPLAN,PLN.DESCPLAN,FTR.TIPOTTEC,TTEC.DETALLE,MCH.CUENTA,CUE.NOMCUENTA,
 CASE WHEN MCH.PROCEDENCIA='FACTURA' AND MCH.PROCESO<>'REVERSION' THEN MCH.PROCEDENCIA ELSE MCH.PROCESO END PROCESO
 FROM FTR INNER JOIN MCH ON FTR.N_FACTURA=MCH.N_FACTURA
          INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
          LEFT  JOIN CUE ON MCH.CUENTA=CUE.CUENTA
          LEFT  JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
          LEFT  JOIN TTEC ON FTR.TIPOTTEC=TTEC.TIPO
 WHERE FTR.F_FACTURA>='01/01/2024'
 AND COALESCE(FTR.N_FACTURA,'')<>''
 AND FTR.F_FACTURA<='01/01/2025'
 AND MCH.PROCESO<>'CXC_IMPUESTOS'
 AND MCH.CUENTA LIKE '13%'
 --AND MCH.PROCESO='MANUAL'
 --AND MCH.CUENTA='2301050101'
-- AND FTR.N_FACTURA='CSI87842'
 AND MCH.TIPO=CASE WHEN MCH.PROCESO='REVERSION' THEN CASE WHEN MCH.PROCEDENCIA='NOTDBCR' THEN 'DB' ELSE 'CR' END ELSE  'DB' END
 AND EXISTS(SELECT * FROM MCP WHERE MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE AND ANO='2024' AND MCP.ESTADO=2 AND COALESCE(ANULADO,0)<>1)
 GROUP BY FTR.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,FTR.IDPLAN,PLN.DESCPLAN,FTR.TIPOTTEC,TTEC.DETALLE,MCH.CUENTA,CUE.NOMCUENTA,
 CASE WHEN MCH.PROCEDENCIA='FACTURA'  AND MCH.PROCESO<>'REVERSION' THEN MCH.PROCEDENCIA ELSE MCH.PROCESO END
 ORDER BY FTR.IDTERCERO


  SELECT FTR.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,FTR.IDPLAN,PLN.DESCPLAN,FTR.TIPOTTEC,TTEC.DETALLE, FTR.N_FACTURA,MCH.CUENTA,CUE.NOMCUENTA,
 CASE WHEN MCH.PROCEDENCIA='FACTURA' AND MCH.PROCESO<>'REVERSION' THEN MCH.PROCEDENCIA ELSE MCH.PROCESO END PROCESO
 FROM FTR INNER JOIN MCH ON FTR.N_FACTURA=MCH.N_FACTURA
          INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
          LEFT  JOIN CUE ON MCH.CUENTA=CUE.CUENTA
          LEFT  JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
          LEFT  JOIN TTEC ON FTR.TIPOTTEC=TTEC.TIPO
 WHERE FTR.F_FACTURA>='01/01/2024'
 AND COALESCE(FTR.N_FACTURA,'')<>''
 AND FTR.F_FACTURA<='01/01/2025'
 AND MCH.PROCESO<>'CXC_IMPUESTOS'
 AND MCH.CUENTA LIKE '13%'
 --AND MCH.PROCESO='MANUAL'
 --AND MCH.CUENTA='2301050101'
-- AND FTR.N_FACTURA='CSI87842'
 AND MCH.TIPO=CASE WHEN MCH.PROCESO='REVERSION' THEN CASE WHEN MCH.PROCEDENCIA='NOTDBCR' THEN 'DB' ELSE 'CR' END ELSE  'DB' END
 AND EXISTS(SELECT * FROM MCP WHERE MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE AND ANO='2024' AND MCP.ESTADO=2 AND COALESCE(ANULADO,0)<>1)
 GROUP BY FTR.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,FTR.IDPLAN,PLN.DESCPLAN,FTR.TIPOTTEC,TTEC.DETALLE,FTR.N_FACTURA,MCH.CUENTA,CUE.NOMCUENTA,
 CASE WHEN MCH.PROCEDENCIA='FACTURA'  AND MCH.PROCESO<>'REVERSION' THEN MCH.PROCEDENCIA ELSE MCH.PROCESO END
 ORDER BY FTR.N_FACTURA
