
DECLARE @PROCESO SMALLINT
DECLARE @BASE INT
DECLARE @BASEB VARCHAR(120)
DECLARE @COSIENTE INT
DECLARE @COSIENTEB VARCHAR(120)
DECLARE @RESIDUO INT
DECLARE @RESIDUOB VARCHAR(120)
DECLARE @FIN BIT
DECLARE @ITEMS INT
DECLARE @ITEM INT
DECLARE @ITEM1 VARCHAR(5)
DECLARE @RES  TABLE (ID INT IDENTITY(1,1),RESIDUO INT)
DECLARE @RESB  TABLE (ID INT IDENTITY(1,1),RESIDUO VARCHAR(5))
DECLARE @HEXA TABLE (NRO INT, HEXA VARCHAR(1))
DECLARE @HEXA1 TABLE (NRO VARCHAR(5), HEXA VARCHAR(1))
DECLARE @RESUL VARCHAR(20)
SELECT @COSIENTE= 1,@BASEB='11100101',@PROCESO=2,@COSIENTEB='1'

/*
1.DECIMAL A HEXADECIMAL
2.BINARIO A HEXADECIMAL
*/


IF @PROCESO=1
BEGIN
   INSERT INTO @HEXA(NRO,HEXA)
   SELECT 1,'1' UNION ALL
   SELECT 2,'2' UNION ALL
   SELECT 3,'3' UNION ALL
   SELECT 4,'4' UNION ALL
   SELECT 5,'5' UNION ALL
   SELECT 6,'6' UNION ALL
   SELECT 7,'7' UNION ALL
   SELECT 8,'8' UNION ALL
   SELECT 9,'9' UNION ALL
   SELECT 10,'A' UNION ALL
   SELECT 11,'B' UNION ALL
   SELECT 12,'C' UNION ALL
   SELECT 13,'D' UNION ALL
   SELECT 14,'E' UNION ALL
   SELECT 15,'F' 


   WHILE @COSIENTE >0
   BEGIN
      SELECT @COSIENTE=@BASE/16
      PRINT '@COSIENTE='+LTRIM(RTRIM(STR(@COSIENTE)))
      SELECT @RESIDUO=@BASE%16
      PRINT '@RESIDUO='+LTRIM(RTRIM(STR(@RESIDUO)))
      IF @RESIDUO>0
      BEGIN
         INSERT INTO @RES(RESIDUO)
         SELECT @RESIDUO
      END
      SELECT @BASE=@COSIENTE

      IF @COSIENTE=0
      BEGIN
         SELECT @ITEMS=COUNT(*) FROM @RES
         WHILE @ITEMS>0
         BEGIN
            SELECT @ITEM=RESIDUO FROM @RES WHERE ID=@ITEMS
            SELECT @RESUL=COALESCE(@RESUL,'')+HEXA FROM @HEXA WHERE NRO=@ITEM
            PRINT '@RESUL='+@RESUL
            SELECT @ITEMS=@ITEMS-1
         END
      END
   END
END
IF @PROCESO=2
BEGIN
   INSERT INTO @HEXA1(NRO,HEXA)
   SELECT '0000','1' UNION ALL
   SELECT '0001','2' UNION ALL
   SELECT '0011','3' UNION ALL
   SELECT '0100','4' UNION ALL
   SELECT '0101','5' UNION ALL
   SELECT '0110','6' UNION ALL
   SELECT '0111','7' UNION ALL
   SELECT '1000','8' UNION ALL
   SELECT '1001','9' UNION ALL
   SELECT '1010','A' UNION ALL
   SELECT '1011','B' UNION ALL
   SELECT '1100','C' UNION ALL
   SELECT '1101','D' UNION ALL
   SELECT '1110','E' UNION ALL
   SELECT '1111','F' 


   WHILE LEN(COALESCE(@COSIENTEB,''))>0
   BEGIN
      IF LEN(@BASEB)>4
      BEGIN 
         SELECT @RESIDUOB=LEFT(@BASEB,LEN(@BASEB)-4)
         SELECT @COSIENTEB=RIGHT(@BASEB,4)
         PRINT '@COSIENTE='+LTRIM(RTRIM(@COSIENTEB))
         PRINT '@RESIDUO='+LTRIM(RTRIM(@RESIDUOB))
      END
      ELSE
      BEGIN
         PRINT 'SE ACABO'
         SELECT @RESIDUOB=@BASEB,@COSIENTEB=NULL,@FIN=1
      END
      IF LEN(@RESIDUOB)>0
      BEGIN
         INSERT INTO @RESB(RESIDUO)
         SELECT @RESIDUOB
      END
      SELECT @BASEB=@COSIENTEB

      PRINT '@BASEB='+LTRIM(RTRIM(@BASEB))

      IF COALESCE(@FIN,0)=1
      BEGIN
         SELECT @ITEMS=COUNT(*) FROM @RESB
         WHILE @ITEMS>0
         BEGIN
            SELECT @ITEM1=RESIDUO FROM @RESB WHERE ID=@ITEMS
            SELECT @RESUL=COALESCE(@RESUL,'')+HEXA FROM @HEXA1 WHERE NRO=@ITEM1
            SELECT @ITEMS=@ITEMS-1
         END
      END
   END

END
PRINT 'RESULTADO: '+COALESCE(@RESUL,'NADA')
      --      SELECT * FROM @RESB