
--IMOV.IDAREA, IMOV.CCOSTO

--CENTRO DE COSTO EN BLANCO O INEXISTENTE
SELECT IMOV.NROCOMPROBANTE, IMOV.NODOCUMENTO, IMOV.CCOSTO, IMOV.IDAREA, COALESCE(HADM.HABCAMA,'UCI_A_07') CAMA, HHAB.CCOSTO, CEN.IDAREA
FROM IMOV INNER JOIN MCPE ON IMOV.NROCOMPROBANTE = MCPE.NROCOMPROBANTE 
          INNER JOIN IZSOL ON IMOV.NODOCUMENTO = IZSOL.CNSIZSOL
          INNER JOIN HADM ON IZSOL.NOADMISION = HADM.NOADMISION
          INNER JOIN HHAB ON COALESCE(HADM.HABCAMA,'UCI_A_07') = HHAB.HABCAMA
          INNER JOIN CEN ON HHAB.CCOSTO = CEN.CCOSTO
WHERE MCPE.COMPROBANTE = '17'
AND NOT EXISTS (SELECT * FROM CEN WHERE CEN.CCOSTO = COALESCE(IMOV.CCOSTO,''))


BEGIN TRAN
UPDATE IMOV
SET IDAREA = CEN.IDAREA,  CCOSTO =  HHAB.CCOSTO
FROM IMOV INNER JOIN MCPE ON IMOV.NROCOMPROBANTE = MCPE.NROCOMPROBANTE 
          INNER JOIN IZSOL ON IMOV.NODOCUMENTO = IZSOL.CNSIZSOL
          INNER JOIN HADM ON IZSOL.NOADMISION = HADM.NOADMISION
          INNER JOIN HHAB ON COALESCE(HADM.HABCAMA,'UCI_A_07') = HHAB.HABCAMA
          INNER JOIN CEN ON HHAB.CCOSTO = CEN.CCOSTO
WHERE MCPE.COMPROBANTE = '17'
AND NOT EXISTS (SELECT * FROM CEN WHERE CEN.CCOSTO = COALESCE(IMOV.CCOSTO,''))
ROLLBACK
COMMIT

--PCOSTO DE  INVENTARIO EN CERO
SELECT ITMO.TIPO, IMOV.IDTIPOMOV, IMOV.NROCOMPROBANTE, IMOV.NODOCUMENTO, IMOVH.IDARTICULO, IMOVH.PCOSTO PCOSTO_IMOVH, ISAL.PCOSTO PCOSTO_ISAL, 
       CASE WHEN IEXI.PCOSTO = 0 
            THEN CASE WHEN (SELECT PRINCIPAL FROM IART WHERE IART.IDARTICULO = IEXI.IDARTICULO)= 0 
                      THEN CASE WHEN (SELECT PCOSTO FROM IART WHERE IART.IDARTICULO = IEXI.IDARTICULO) = 0
                                THEN CASE WHEN (SELECT PCOSTO FROM IART A WHERE EXISTS (SELECT * FROM IART B WHERE B.IDARTICULO = IEXI.IDARTICULO AND B.IDSERVICIO = A.IDARTICULO))= 0
                                          THEN 99999
                                          ELSE (SELECT PCOSTO FROM IART A WHERE EXISTS (SELECT * FROM IART B WHERE B.IDARTICULO = IEXI.IDARTICULO AND B.IDSERVICIO = A.IDARTICULO))
                                     END
                                ELSE (SELECT PCOSTO FROM IART WHERE IART.IDARTICULO = IEXI.IDARTICULO)
                           END
                       ELSE (SELECT MAX(PCOSTO) FROM IART A WHERE EXISTS (SELECT * FROM IART B WHERE B.IDARTICULO = IEXI.IDARTICULO AND B.IDSERVICIO = A.IDSERVICIO))
                       END
            ELSE IEXI.PCOSTO 
       END PCOSTO_IEXI
  --     (SELECT PCOSTO FROM IART A WHERE EXISTS (SELECT * FROM IART B WHERE B.IDARTICULO = IEXI.IDARTICULO AND B.IDSERVICIO = A.IDARTICULO)) AS PCOSTO_PRIN
FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV = IMOVH.CNSMOV
          INNER JOIN MCPE ON IMOV.NROCOMPROBANTE = MCPE.NROCOMPROBANTE
          INNER JOIN ISAL ON IMOV.CNSMOV = ISAL.CNSMOV AND IMOVH.IDARTICULO = ISAL.IDARTICULO
          INNER JOIN IEXI ON IMOVH.IDARTICULO = IEXI.IDARTICULO AND IMOV.IDBODEGA = IEXI.IDBODEGA AND ISAL.NOLOTE = IEXI.NOLOTE
          INNER JOIN ITMO ON IMOV.IDTIPOMOV = ITMO.IDTIPOMOV
WHERE MCPE.COMPROBANTE = '04'

BEGIN TRAN
UPDATE ISAL
SET PCOSTO = CASE WHEN IEXI.PCOSTO = 0 
            THEN CASE WHEN (SELECT PRINCIPAL FROM IART WHERE IART.IDARTICULO = IEXI.IDARTICULO)= 0 
                      THEN CASE WHEN (SELECT PCOSTO FROM IART WHERE IART.IDARTICULO = IEXI.IDARTICULO) = 0
                                THEN CASE WHEN (SELECT PCOSTO FROM IART A WHERE EXISTS (SELECT * FROM IART B WHERE B.IDARTICULO = IEXI.IDARTICULO AND B.IDSERVICIO = A.IDARTICULO))= 0
                                          THEN 99999
                                          ELSE (SELECT PCOSTO FROM IART A WHERE EXISTS (SELECT * FROM IART B WHERE B.IDARTICULO = IEXI.IDARTICULO AND B.IDSERVICIO = A.IDARTICULO))
                                     END
                                ELSE (SELECT PCOSTO FROM IART WHERE IART.IDARTICULO = IEXI.IDARTICULO)
                           END
                       ELSE (SELECT MAX(PCOSTO) FROM IART A WHERE EXISTS (SELECT * FROM IART B WHERE B.IDARTICULO = IEXI.IDARTICULO AND B.IDSERVICIO = A.IDSERVICIO))
                       END
            ELSE IEXI.PCOSTO 
       END
FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV = IMOVH.CNSMOV
          INNER JOIN MCPE ON IMOV.NROCOMPROBANTE = MCPE.NROCOMPROBANTE
          INNER JOIN ISAL ON IMOV.CNSMOV = ISAL.CNSMOV AND IMOVH.IDARTICULO = ISAL.IDARTICULO
          INNER JOIN IEXI ON IMOVH.IDARTICULO = IEXI.IDARTICULO AND IMOV.IDBODEGA = IEXI.IDBODEGA AND ISAL.NOLOTE = IEXI.NOLOTE
WHERE MCPE.COMPROBANTE = '17'
COMMIT



/*
Casos especiales de sectores malos
*/

SELECT MCPE.NROCOMPROBANTE, IMOV.CNSMOV, IZSOL.CNSIZSOL, IZSOL.SECTOR, HHAB.CCOSTO, IMOV.CCOSTO, CEN.IDAREA
FROM MCPE INNER JOIN IMOV ON MCPE.REFERENCIA1 = IMOV.CNSMOV
          LEFT JOIN IZSOL ON IMOV.NODOCUMENTO = IZSOL.CNSIZSOL
          LEFT JOIN HHAB  ON IZSOL.SECTOR = HHAB.HABCAMA
          LEFT JOIN CEN   ON HHAB.CCOSTO = CEN.CCOSTO
WHERE COMPROBANTE = '22' AND HHAB.CLASE = 'SECTOR'


BEGIN TRAN
UPDATE IMOV
SET IDAREA = CEN.IDAREA,  CCOSTO =  HHAB.CCOSTO
FROM MCPE INNER JOIN IMOV ON MCPE.REFERENCIA1 = IMOV.CNSMOV
          LEFT JOIN IZSOL ON IMOV.NODOCUMENTO = IZSOL.CNSIZSOL
          LEFT JOIN HHAB  ON IZSOL.SECTOR = HHAB.HABCAMA
          LEFT JOIN CEN   ON HHAB.CCOSTO = CEN.CCOSTO
WHERE COMPROBANTE = '22' AND HHAB.CLASE = 'SECTOR'
COMMIT


-- ENTRADAS CON VALOR CERO
SELECT ITMO.DESCRIPCION, ITMO.TIPO, IMOVH.PCOSTO, IART.PCOSTO
FROM IMOV INNER JOIN MCPE ON IMOV.NROCOMPROBANTE = MCPE.NROCOMPROBANTE
          INNER JOIN ITMO ON IMOV.IDTIPOMOV = ITMO.IDTIPOMOV
          INNER JOIN IMOVH ON IMOV.CNSMOV = IMOVH.CNSMOV
          INNER JOIN IART ON IMOVH.IDARTICULO = IART.IDARTICULO
WHERE MCPE.COMPROBANTE = '04'

BEGIN TRAN
UPDATE IMOVH
SET PCOSTO = IART.PCOSTO
FROM IMOV INNER JOIN MCPE ON IMOV.NROCOMPROBANTE = MCPE.NROCOMPROBANTE
         -- INNER JOIN ITMO ON IMOV.IDTIPOMOV = ITMO.IDTIPOMOV
          INNER JOIN IMOVH ON IMOV.CNSMOV = IMOVH.CNSMOV
          INNER JOIN IART ON IMOVH.IDARTICULO = IART.IDARTICULO
WHERE MCPE.COMPROBANTE = '11'
COMMIT


--PRECIO DE IMVENTARIO EN CERO NUEVA FORMA


SELECT ISAL.IDARTICULO, ISAL.IDARTICULO_IMOVH, IMOVH.IDARTICULO, ISAL.PCOSTO, IMOVH.PCOSTO, (SELECT PCOSTO FROM IART WHERE ISAL.IDARTICULO = IDARTICULO), *
FROM ISAL INNER JOIN IMOVH ON ISAL.CNSMOV = IMOVH.CNSMOV AND ISAL.IDARTICULO_IMOVH = IMOVH.IDARTICULO
          INNER JOIN IMOV  ON ISAL.CNSMOV = IMOV.CNSMOV

WHERE ISAL.PCOSTO <= 0 AND EXISTS(SELECT * FROM MCPE WHERE ISAL.CNSMOV= MCPE.REFERENCIA1 AND IMOV.IDBODEGA =MCPE.REFERENCIA2)

BEGIN TRAN
UPDATE ISAL
SET PCOSTO = CASE WHEN IMOVH.PCOSTO = 0 THEN (SELECT PCOSTO FROM IART WHERE ISAL.IDARTICULO = IDARTICULO) ELSE IMOVH.PCOSTO END
FROM ISAL INNER JOIN IMOVH ON ISAL.CNSMOV = IMOVH.CNSMOV AND ISAL.IDARTICULO_IMOVH = IMOVH.IDARTICULO
          INNER JOIN IMOV  ON ISAL.CNSMOV = IMOV.CNSMOV
WHERE ISAL.PCOSTO <= 0 AND EXISTS(SELECT * FROM MCPE WHERE ISAL.CNSMOV= MCPE.REFERENCIA1 AND IMOV.IDBODEGA =MCPE.REFERENCIA2)
ROLLBACK
COMMIT
