DECLARE 
@N_FACTURA           VARCHAR(16),
@COMPANIA            VARCHAR(2),
@USUARIO             VARCHAR(12),
@SYS_COMPUTERNAME    VARCHAR(254),
@SEDE                VARCHAR(5),
@NROCOMPROBANTE      VARCHAR(20) 
 


   DECLARE MCP_RECONSTRUYE CURSOR FOR
   SELECT NOREFERENCIA,COMPANIA,USUARIO,'SOPORTE','01',NROCOMPROBANTE  FROM MCPE WHERE COMPROBANTE='07'
   GROUP BY NOREFERENCIA,COMPANIA,USUARIO,NROCOMPROBANTE 
   OPEN MCP_RECONSTRUYE    
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @N_FACTURA,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,@SEDE,@NROCOMPROBANTE
   WHILE @@FETCH_STATUS = 0    
   BEGIN
       PRINT 'EMPEZANDO....'+@N_FACTURA
       EXEC DBO.SPK_NC_CONTAB_FTR @N_FACTURA,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,@SEDE,@NROCOMPROBANTE
    
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @N_FACTURA,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,@SEDE,@NROCOMPROBANTE
   END
   CLOSE MCP_RECONSTRUYE
   DEALLOCATE MCP_RECONSTRUYE
   
   
 