DECLARE @SECUENCIA INT
DECLARE @SECUN     INT
SET @SECUN=70
DECLARE PG_CURSOR CURSOR FOR  
SELECT SECUENCIA FROM MPLD WHERE CLASEPLANTILLA='PYP_022'
GROUP BY SECUENCIA
ORDER BY SECUENCIA DESC    
OPEN PG_CURSOR    
FETCH NEXT FROM PG_CURSOR    
INTO @SECUENCIA
WHILE @@FETCH_STATUS = 0    
BEGIN 
   UPDATE MPLD SET CAMPO='PYP22_'+CAST(CASE WHEN @SECUN<10 THEN '0'+CAST(@SECUN AS VARCHAR(2))ELSE @SECUN END AS VARCHAR(3))
                   ,SECUENCIA=@SECUN WHERE CLASEPLANTILLA ='PYP_022' AND SECUENCIA=@SECUENCIA
   SELECT @SECUN=@SECUN-10
FETCH NEXT FROM PG_CURSOR    
INTO @SECUENCIA
END
CLOSE PG_CURSOR
DEALLOCATE PG_CURSOR

