
DECLARE 
		@IDBODEGA         VARCHAR(20),
		@CNSMOV           VARCHAR(20),
		@USUARIO          VARCHAR(12),
		@COMPANIA         VARCHAR(2),
		@SEDE             VARCHAR(5),
		@SYS_COMPUTERNAME VARCHAR(255)

--SELECT IDBODEGA,CNSMOV,IDFUNCIONARIO,'01','01',SYS_cOMPUTERNAME 
--FROM IMOV  WHERE IDBODEGA='101' AND IDTIPOMOV='09' AND FECHAMOV<='20130208'

   DECLARE PG_CURSOR CURSOR FOR 
   SELECT IDBODEGA,CNSMOV,IDFUNCIONARIO,'01','01',SYS_cOMPUTERNAME 
   FROM IMOV  WHERE IDBODEGA='101' AND IDTIPOMOV='09' AND FECHAMOV<='20130209' 
   GROUP BY  IDBODEGA,CNSMOV,IDFUNCIONARIO,SYS_cOMPUTERNAME   
   OPEN PG_CURSOR    
   FETCH NEXT FROM PG_CURSOR    
   INTO @IDBODEGA,@CNSMOV,@USUARIO,@COMPANIA,@SEDE,@SYS_COMPUTERNAME
   WHILE @@FETCH_STATUS = 0    
   BEGIN 
		EXEC SPK_CONFIRMARENTRADAS  @IDBODEGA,@CNSMOV,@USUARIO,@COMPANIA,@SEDE,@SYS_COMPUTERNAME
   FETCH NEXT FROM PG_CURSOR    
   INTO @IDBODEGA,@CNSMOV,@USUARIO,@COMPANIA,@SEDE,@SYS_COMPUTERNAME
   END
   CLOSE PG_CURSOR
   DEALLOCATE PG_CURSOR


 
 
 