
DECLARE 
		 @CNSMOV            VARCHAR(20),   
		 @USUARIO           VARCHAR(12),  
		 @SYS_COMPUTERNAME  VARCHAR(254),  
		 @COMPANIA          VARCHAR(2),   
		 @SEDE              VARCHAR(5),  
		 @NROCOMPROBANTE    VARCHAR(20)  

--SELECT IDBODEGA,CNSMOV,IDFUNCIONARIO,'01','01',SYS_cOMPUTERNAME 
--FROM IMOV  WHERE IDBODEGA='101' AND IDTIPOMOV='09' AND FECHAMOV<='20130208'

   DECLARE PG_CURSOR CURSOR FOR 
   SELECT  REFERENCIA1, USUARIO,'SOPORTEIX',COMPANIA,'01', NROCOMPROBANTE FROM MCP  WHERE COMPROBANTE='30' AND ANO='2012' AND MES=12 AND ESTADO=0
   OPEN PG_CURSOR    
   FETCH NEXT FROM PG_CURSOR    
   INTO @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   WHILE @@FETCH_STATUS = 0    
   BEGIN 
		EXEC SPK_CONTAB_INV  @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   FETCH NEXT FROM PG_CURSOR    
   INTO @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   END
   CLOSE PG_CURSOR
   DEALLOCATE PG_CURSOR
  


SELECT * FROM ISAL

UPDATE ISAL SET PCOSTO=A.PCOSTO
FROM IART A INNER JOIN ISAL B ON A.IDARTICULO=B.IDARTICULO
