DECLARE 
 @CNSMOV            VARCHAR(20),   
 @USUARIO           VARCHAR(12),  
 @SYS_COMPUTERNAME  VARCHAR(254),  
 @COMPANIA          VARCHAR(2),   
 @SEDE              VARCHAR(5),  
 @NROCOMPROBANTE    VARCHAR(20)


   DECLARE MCP_RECONSTRUYE CURSOR FOR
   SELECT CNSFPAG,USUARIO,HOST_NAME(),COMPANIA,'001',''  FROM FPAG  WHERE NOT EXISTS(SELECT * FROM MCP WHERE MCP.NROCOMPROBANTE=FPAG.NROCOMPROBANTE)
   OPEN MCP_RECONSTRUYE    
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   WHILE @@FETCH_STATUS = 0    
   BEGIN
       PRINT 'EMPEZANDO....'+@CNSMOV
       EXEC SPK_NC_CONTAB_CXC  @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
       EXEC SPK_REVISAR_COMPROBANTE '01',@NROCOMPROBANTE
       EXEC SPK_SUMA_DBCR @NROCOMPROBANTE    
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @CNSMOV,@COMPANIA,@SEDE,@USUARIO,@SYS_COMPUTERNAME,@NROCOMPROBANTE
   END
   CLOSE MCP_RECONSTRUYE
   DEALLOCATE MCP_RECONSTRUYE
   
   
 