DECLARE 
      @CNSGLO           VARCHAR(20), 
      @USUARIO          VARCHAR(12),
      @SYS_COMPUTERNAME VARCHAR(254),
      @COMPANIA         VARCHAR(2), 
      @SEDE             VARCHAR(5),
      @NROCOMPROBANTE   VARCHAR(20)
 


   DECLARE MCP_RECONSTRUYE CURSOR FOR
   SELECT REFERENCIA1,USUARIO,'SOPORTEIX',COMPANIA,IDSEDE,NROCOMPROBANTE FROM MCP WHERE PROCEDENCIA='RGLO' AND ANO='2015' AND MES=11
   OPEN MCP_RECONSTRUYE    
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @CNSGLO,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   WHILE @@FETCH_STATUS = 0    
   BEGIN
       PRINT 'EMPEZANDO....'+@CNSGLO
       EXEC DBO.SPK_CONTAB_FGLO  @CNSGLO,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @CNSGLO,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   END
   CLOSE MCP_RECONSTRUYE
   DEALLOCATE MCP_RECONSTRUYE
   
   
 
