DECLARE @RAW VARCHAR(20)
DECLARE @LETRA VARCHAR(1)
DECLARE @I INT
SET @I=1
SET @RAW=' 71772671'
WHILE LEN(@RAW)>@I
BEGIN
   SELECT ASCII(SUBSTRING(@RAW,@I,1)),SUBSTRING(@RAW,@I,1),UNICODE(SUBSTRING(@RAW,@I,1))
   --SELECT @I=@I+1

   IF UNICODE(SUBSTRING(@RAW, @i, 1)) NOT BETWEEN 48 AND 57 -- dígitos
      AND UNICODE(SUBSTRING(@RAW, @i, 1)) NOT BETWEEN 65 AND 90 -- mayúsculas
      AND UNICODE(SUBSTRING(@RAW, @i, 1)) NOT BETWEEN 97 AND 122 -- minúsculas
      AND UNICODE(SUBSTRING(@RAW, @i, 1)) NOT IN (32) -- espacio
   BEGIN
      select SUBSTRING(@RAW, @i, 1)
   END
   SET @i = @i + 1;
    
END


select * 
from SALDOMESTERFAC 
where IDTERCERO like '%[^!-~&]%' 

SELECT * FROM SALDOMESTERFAC 
WHERE EXISTS (
  SELECT 1 FROM STRING_SPLIT(IDTERCERO,' ') 
  WHERE UNICODE(value) > 127
)
AND ANOMES='202501'

SELECT * FROM TER WHERE NIT LIKE '%[!@#$%^&*()]%';

SELECT * FROM TER 
WHERE NIT LIKE '%[^a-zA-Z0-9 ]%' COLLATE SQL_Latin1_General_CP1_CS_AS;

UPDATE TER SET NIT=REPLACE(NIT,' ','')
WHERE NIT LIKE '%[^a-zA-Z0-9 ]%' COLLATE SQL_Latin1_General_CP1_CS_AS;

ALTER TABLE MCH DISABLE TRIGGER ALL

UPDATE MCH SET IDTERCERO=REPLACE(IDTERCERO,CHAR(31),'&') WHERE IDTERCERO like '%[^!-~]%' 
UPDATE SALDOMESTERFAC SET IDTERCERO=REPLACE(IDTERCERO,CHAR(31),'') WHERE IDTERCERO like '%[^!-~ ]%' 

ALTER TABLE MCH ENABLE TRIGGER ALL


SELECT * FROM CUE WHERE CUENTA_SUMA NOT IN(SELECT CUENTA FROM CUE WHERE TIPO='Suma')

EXEC SPK_BALANCE 'BP','JOSEMANUEL','2025','01','2025','01','1','9999999999999999',1,10,'','','01','01','','',0,0

SELECT * FROM TBALANCETERFAC WHERE CNSPRO='JOSEMANUEL' AND (DB<>0 OR CR<>0) AND CUENTA<>'TOTAL GENERAL'
SELECT * FROM SALDOMES WHERE ANO='2025' AND MES=1 AND (DB<>0 OR CR<>0)

DELETE TBALANCETERFAC WHERE CNSPRO<>'JOSEMANUEL'

SELECT SUM(DB),SUM(CR) FROM TBALANCETERFAC WHERE CNSPRO='0600008473' AND (DB<>0 OR CR<>0) AND CUENTA<>'TOTAL GENERAL' AND TIPO='Detalle'
SELECT SUM(DB),SUM(CR) FROM TBALANCETERFAC WHERE CNSPRO='0600008473'  AND CUENTA<>'TOTAL GENERAL' AND CUENTA IN('1','2','3','4','5','6') AND NIVE
SELECT SUM(DB),SUM(CR)  FROM SALDOMES WHERE ANO='2025' AND MES=1 AND (DB<>0 OR CR<>0)


   SELECT  'TOTAL GENERAL', '', '', '', '',
            SUM(CASE T.NTZ WHEN 'DB' THEN SI ELSE (SI * -1) END) SI, 
            SUM(COALESCE(DB,0)) DB, 
            SUM(CR) CR,             
            SUM(CASE T.NTZ WHEN 'DB' THEN SF ELSE (SF * -1) END),
            SUM(CASE T.NTZ WHEN 'DB' THEN DB - CR ELSE CR -DB END),
            '',
            'Total_General'
   FROM   TBALANCETERFAC T    LEFT JOIN CUE ON T.CUENTA = CUE.CUENTA
   WHERE  CUE.NIVEL = 1
   AND    T.CNSPRO = '0600008473'
   AND DB<0

      WHERE LEN(CUENTA)=1
   AND    T.CNSPRO = '0600008473'

   SELECT * FROM CUE WHERE NIVEL IS NULL

   UPDATE CUE SET NIVEL=1 WHERE LEN(CUENTA)=1
   UPDATE CUE SET NIVEL=2 WHERE LEN(CUENTA)=2
   UPDATE CUE SET NIVEL=3 WHERE LEN(CUENTA)=4
   UPDATE CUE SET NIVEL=4 WHERE LEN(CUENTA)=6
   UPDATE CUE SET NIVEL=5 WHERE LEN(CUENTA)=8
   UPDATE CUE SET NIVEL=6 WHERE LEN(CUENTA)=10
   UPDATE CUE SET NIVEL=7 WHERE LEN(CUENTA)=12

SELECT SUM(DB),SUM(CR) FROM TBALANCETERFAC WHERE CNSPRO='0600008473'  AND CUENTA='TOTAL GENERAL'
SELECT 22822814239.62-22822814239.62

SELECT * FROM TBALANCETERFAC WHERE CNSPRO<>'JOSEMANUEL' AND NOT EXISTS(SELECT * FROM SALDOMES X WHERE TBALANCETERFAC.CUENTA=X.CUENTA AND X.ANO='2025' AND X.MES=1)

SELECT *  FROM SALDOMES LEFT JOIN TBALANCETERFAC X ON SALDOMES.CUENTA=X.CUENTA
WHERE X.CNSPRO='JOSEMANUEL'
AND ANO='2025' AND MES=1


SELECT SALDOMES.CUENTA, SUM(SALDOMES.DB),SUM(SALDOMES.CR),SUM(X.DB),SUM(X.CR) FROM SALDOMES LEFT JOIN TBALANCETERFAC X ON SALDOMES.CUENTA=X.CUENTA
WHERE X.CNSPRO='JOSEMANUEL'
AND ANO='2025' AND MES=1
GROUP BY SALDOMES.CUENTA
HAVING SUM(SALDOMES.CR)-SUM(X.CR)<>0


SELECT 114114071198.10-114114071198.10,114114071198.10-114114071198.10