DECLARE @CUANTAS INT
DECLARE @DEVOL   INT

SELECT @CUANTAS=COUNT(*)FROM HTX WHERE SOLICITADO=1 AND APLICADO=1 AND ENCARGOS=0 AND MDOSIF=1 AND CANTIDADINV=0

PRINT 'ESTE ES EL NUMERO'+' '+CAST(@CUANTAS AS VARCHAR(20))

IF @CUANTAS>0
BEGIN 
UPDATE HTX SET ENCARGOS=1 WHERE SOLICITADO=1 AND APLICADO=1 AND ENCARGOS=0 AND MDOSIF=1 AND CANTIDADINV=0
END

SELECT @DEVOL=COUNT(*) FROM HPRED A INNER JOIN HTX B ON A.NOPRESTACION=B.NOPRESTACION
WHERE A.CNSMOV IS NULL

IF @DEVOL>0
BEGIN 

UPDATE HPRED SET CNSMOV=B.CNSMOV
FROM HPRED A INNER JOIN HTX B ON A.NOPRESTACION=B.NOPRESTACION
WHERE A.CNSMOV IS NULL AND B.ENCARGOS=1

UPDATE IMOV SET NOPRESTACION=B.NOPRESTACION
FROM IMOV A INNER JOIN HTX B ON A.CNSMOV=B.CNSMOV
WHERE B.SOLICITADO=1 AND ENCARGOS=1 AND CANTIDADINV>0

END
