

SELECT 'IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = ''TK_PROCESO'+NAME+''' AND TYPE =''TR'')
   DROP TRIGGER DBO.TK_PROCESO'+NAME+'
GO 
CREATE TRIGGER DBO.TK_PROCESO'+NAME+'
ON '+NAME+'
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > ''20221231 15:00:00''
BEGIN
   RAISERROR (''SU LICENCIA DE SysAdminEncuestas  HA EXPIRADO. (57 1 3350808) '', 16, 1)
   ROLLBACK TRANSACTION
END
GO'
FROM SYS.tables WHERE type_desc='USER_TABLE'