
CREATE FUNCTION DBO.FNK_NOMBRE_AFI(@IDAFILIADO VARCHAR(20))
RETURNS VARCHAR(50)
AS
BEGIN 
DECLARE @NOMBRE VARCHAR(50)
SET @NOMBRE=(SELECT PAPELLIDO+' '+ISNULL(SAPELLIDO,'')+' '+PNOMBRE+' '+ISNULL(SNOMBRE,'') FROM AFI
WHERE IDAFILIADO=@IDAFILIADO)

RETURN @NOMBRE
END