IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNK_FECHA' AND XTYPE='FN')
BEGIN
   DROP FUNCTION FNK_FECHA
END
GO
CREATE FUNCTION [dbo].[FNK_FECHA](@FECHA DATETIME)
RETURNS VARCHAR(10)
WITH ENCRYPTION
AS 
BEGIN 
   DECLARE @FECHA2 VARCHAR(10)
   SET @FECHA2=
   CAST(YEAR(@FECHA)AS VARCHAR(4))+'/'+
   CASE WHEN MONTH(@FECHA)<=9 THEN '0'+CAST(MONTH(@FECHA)AS VARCHAR(2))
   ELSE CAST(MONTH(@FECHA)AS VARCHAR(2)) END+'/'+
   CASE WHEN DAY(@FECHA)<=9 THEN '0'+CAST(DAY(@FECHA)AS VARCHAR(2))
   ELSE CAST(DAY(@FECHA)AS VARCHAR(2)) END

   RETURN @FECHA2
END
