
DECLARE @ANO VARCHAR(4)
DECLARE @SEMFIN INT
DECLARE @FSEMUNO DATETIME
DECLARE @FECHAINI DATETIME
DECLARE @FECHAFIN DATETIME
DECLARE @SEM_C   INT
DECLARE @SEM_A   INT
DECLARE @SEM_D   INT
DECLARE @TABLA TABLE(SEMANA VARCHAR(10),FECHAINI DATETIME,FECHAFIN DATETIME, DATOS VARCHAR(100))

SELECT  @ANO='2022',@SEM_C=0,@SEM_A=-1,@SEM_D=0
SET @FSEMUNO=CONVERT(DATETIME,'01/01/'+@ANO)

SELECT @SEMFIN= DATEPART(WEEK,CONVERT(DATE,'31/12/'+@ANO))

WHILE @SEM_D<=@SEMFIN
BEGIN
   SELECT @SEM_C=DATEPART(WEEK,CONVERT(DATE,@FSEMUNO))
   SELECT @SEM_D=@SEM_C
   SELECT @SEM_A= CASE WHEN DATEPART(DW,@FSEMUNO+6)<>7 THEN 7- DATEPART(DW,@FSEMUNO) ELSE 6 END
   SELECT @FECHAFIN=@FSEMUNO+@SEM_A
   INSERT INTO @TABLA(SEMANA,FECHAINI,FECHAFIN,DATOS)
   SELECT CAST(@SEM_C AS VARCHAR(2))+'-'+@ANO,@FSEMUNO,@FECHAFIN,'SEMANA NRO '+LTRIM(RTRIM(STR(@SEM_C)))+' DESDE '+CONVERT(VARCHAR,@FSEMUNO,103)+' HASTA '+CONVERT(VARCHAR,@FECHAFIN,103)

   SELECT @FSEMUNO=FECHAFIN+1 FROM @TABLA WHERE SEMANA=CAST(@SEM_C AS VARCHAR(2))+'-'+@ANO
   IF YEAR(@FSEMUNO)<>@ANO
   BEGIN
      BREAK
   END
END
INSERT INTO TSEMA
SELECT * FROM @TABLA
ORDER BY CONVERT(INT,LEFT(SEMANA,CHARINDEX('-',SEMANA,1)-1))

--SELECT * FROM TSEMA

--SELECT CHARINDEX('-','1-2021',1)

UPDATE TSEMA SET OBSERVACION=REPLACE(OBSERVACION,':','') WHERE  CHARINDEX(':',OBSERVACION,1)>0