IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_GENCXP_NOMINA_1' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_GENCXP_NOMINA_1
END
GO
CREATE PROCEDURE DBO.SPK_GENCXP_NOMINA_1 
@CNSPAGO          VARCHAR(20),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@IDTERCERO        VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @CNSFCXP VARCHAR(20)
DECLARE @CODPRF_CUR VARCHAR(20)
DECLARE @DESCRIPCION_CUR VARCHAR(100)
DECLARE @IDTERCERO_CUR VARCHAR(20)
DECLARE @FECHA_CUR DATETIME
DECLARE @CODCONCEPTO_CUR VARCHAR(20)
DECLARE @NOMBRE_CONCEPTO_CUR VARCHAR(255)
DECLARE @VALOR_CUR DECIMAL(14,2)
DECLARE @NUMDOC_CUR2 VARCHAR(20)
DECLARE @CANTIDAD_CUR2 DECIMAL(14,2)
DECLARE @VALOR_CUR2 DECIMAL(14,2)
DECLARE @CCOSTO_CUR2 VARCHAR(20)
DECLARE @IDAREA_CUR2 VARCHAR(20)
DECLARE @CUENTA_CUR2 VARCHAR(20)
DECLARE @CNSNIEPE_CUR2 VARCHAR(20)
DECLARE @ITEMNIEPE_CUR2 DECIMAL(14,0)
DECLARE @ITEM INT
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @IDMODELOCONT VARCHAR(2)
DECLARE @CODNOMINA VARCHAR(20)

BEGIN
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
   --PRINT 'Eliminando CXP generadas anteriormente para este Pago.'
   --DELETE FCXPD 
   --FROM   FCXPD INNER JOIN FCXP  ON FCXPD.CNSFCXP = FCXP.CNSFCXP 
   --              LEFT JOIN FCXPP ON  FCXP.CNSFCXP = FCXPP.CNSFCXP
   --WHERE  FCXP.PROCEDENCIA  = 'Nomina' 
   --AND    FCXP.NOREFERENCIA = @CNSPAGO 
   --AND    FCXPP.CNSFCXP IS NULL

   --DELETE FCXP 
   --FROM   FCXP LEFT JOIN FCXPP ON FCXP.CNSFCXP = FCXPP.CNSFCXP
   --WHERE  FCXP.PROCEDENCIA  = 'Nomina' 
   --AND    FCXP.NOREFERENCIA = @CNSPAGO 
   --AND    FCXPP.CNSFCXP IS NULL
 
   DECLARE CUR CURSOR FOR
 --  SELECT B.CODNOMINA, C.CODPRF, C.DESCRIPCION, A.NUMDOC, DBO.FNK_FECHA_SIN_HORA(B.FECHAFIN), 
 --         A.VALOR_NETO
 --  FROM   NEMPF A INNER JOIN NPER B ON A.CNSPAGO = B.CNSPAGO, NPRF C
 --  WHERE  A.CNSPAGO    = @CNSPAGO 
 --  AND    C.CLASE      = 'Salario' 
 --  AND    A.VALOR_NETO > 0
	--AND 

 --  UNION ALL
   SELECT B.CODNOMINA, C.CODPRF, C.DESCRIPCION, A.IDTERCERO, DBO.FNK_FECHA_SIN_HORA(B.FECHAFIN), 
          SUM(A.VALOR+A.VALOR_EMPRESA)
   FROM   NEMPFD A INNER JOIN NPER   B ON A.CNSPAGO     = B.CNSPAGO 
                   INNER JOIN NPRF   C ON A.CODPRF      = C.CODPRF 
                    LEFT JOIN NCOND  D ON A.CODCONCEPTO = D.CODCONCEPTO AND A.ITEMCONCEPTO = D.ITEM 
                    LEFT JOIN NEMPF  E ON A.CNSPAGO     = E.CNSPAGO     AND A.NUMDOC       = E.NUMDOC AND A.ITEM = E.ITEM
   WHERE  A.CNSPAGO = @CNSPAGO AND D.GENERA_CXP = 'Si' AND C.CLASE <> 'Salario'
	AND A.IDTERCERO=@IDTERCERO
   GROUP BY B.CODNOMINA, C.CODPRF, C.DESCRIPCION, A.IDTERCERO, A.CNSPAGO, DBO.FNK_FECHA_SIN_HORA(B.FECHAFIN)
   OPEN CUR
   
   FETCH NEXT FROM CUR
   INTO @CODNOMINA, @CODPRF_CUR, @DESCRIPCION_CUR, @IDTERCERO_CUR, @FECHA_CUR, @VALOR_CUR
 
   WHILE @@FETCH_STATUS = 0
   BEGIN
      SET @CNSFCXP=SPACE(20)
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FCXPNM',@CNSFCXP OUTPUT   
      SELECT @CNSFCXP = @SEDE + 'NM'+REPLACE(SPACE(6 - LEN(@CNSFCXP))+LTRIM(RTRIM(@CNSFCXP)),SPACE(1),0)
      
      SELECT TOP 1 @NROCOMPROBANTE=NIEPED.NROCOMPROBANTE 
      FROM NIEPE INNER JOIN 
           NIEPED ON NIEPE.CNSNIEPE = NIEPED.CNSNIEPE
      WHERE NIEPE.CNSPAGO=@CNSPAGO AND NIEPED.CODPRF=@CODPRF_CUR AND NIEPED.IDTERCERO_PRF=@IDTERCERO_CUR
      
      PRINT 'FCXP.'
		PRINT 'CONSECUTIVO CXP= = = '+@FECHA_CUR
      INSERT INTO FCXP (CNSFCXP,FECHA,CNSFCOM,IDTERCERO,NOREFERENCIA,F_FACTURAREF,F_VENCE,VALOR,ESTADO,F_CANCELADO,USUARIO,
                        PROCEDENCIA,OBSERVACION,COMPANIA,SYS_COMPUTERNAME,USUARIOMOD,FECHAMOD,NUMCUOTA,MARCACONT,
                        CONTABILIZADA,NROCOMPROBANTE,SALDO,IDCLASEIMP,VLR_DESCUENTO,VLR_IVA,VLR_NETO,VLR_IMPUESTOS,
                        VLR_NOTASDEBITO,VLR_COMISION,CUEDEBITO,CUECREDITO,CNSFCXPPM)
      SELECT @CNSFCXP, DBO.FNK_FECHA_SIN_MLS(GETDATE()),@CODNOMINA,@IDTERCERO_CUR, @CNSPAGO, @FECHA_CUR, 
             @FECHA_CUR, @VALOR_CUR, 'N', NULL, @USUARIO, 
             'Nomina', @DESCRIPCION_CUR+', Nómina No. '+@CNSPAGO, @COMPANIA, @SYS_COMPUTERNAME, NULL, NULL, NULL, 0, 1, 
             @NROCOMPROBANTE, @VALOR_CUR, NULL, 0, 0, @VALOR_CUR, 0, 0, 0, NULL, NULL, NULL
      
      DECLARE CUR2 CURSOR FOR 
      --SELECT A.NUMDOC, CANTIDAD = 1, VALOR = (A.VALOR / H.VALOR_INGRESOS) * H.VALOR_NETO, F.CCOSTO, F.IDAREA,
      --       CUENTA = DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', 'DB', A.CODCONCEPTO, F.IDAREA, F.CCOSTO,'S',B.CODNOMINA),
      --       A.CNSPAGO, A.LINEA, A.CODCONCEPTO, G.DESCRIPCION
      --FROM   NEMPFD A INNER JOIN NPER   B ON A.CNSPAGO     = B.CNSPAGO 
      --                 LEFT JOIN NPRF   C ON A.CODPRF      = C.CODPRF 
      --                 LEFT JOIN NCOND  D ON A.CODCONCEPTO = D.CODCONCEPTO AND A.ITEMCONCEPTO = D.ITEM 
      --                 LEFT JOIN TER    E ON A.IDTERCERO   = E.IDTERCERO 
      --                 LEFT JOIN NEMP   F ON F.NUMDOC      = A.NUMDOC 
      --                 LEFT JOIN NCON   G ON G.CODCONCEPTO = A.CODCONCEPTO 
      --                 LEFT JOIN NEMPF  H ON A.CNSPAGO     = H.CNSPAGO     
      --                                   AND A.NUMDOC      = H.NUMDOC 
      --                                   AND A.ITEM        = H.ITEM
      --WHERE  A.CNSPAGO = @CNSPAGO    
      --AND    D.GENERA_CXP = 'Si'      
      --AND    A.INFO       = 'No'           
      --AND    A.VALOR + A.VALOR_EMPRESA <> 0 
      --AND    A.CODPRF     = @CODPRF_CUR 
      --AND    C.CLASE      = 'Salario' 
      --AND    A.IDTERCERO  = @IDTERCERO_CUR 
      --AND NOT C.CODPRF IS NULL 
      --AND NOT E.IDTERCERO IS NULL
      --UNION ALL
      SELECT A.NUMDOC, CANTIDAD = 1, 
             VALOR = CASE WHEN A.NUMDOC = A.IDTERCERO THEN (A.VALOR / H.VALOR_INGRESOS) * H.VALOR_NETO
                          ELSE A.VALOR+A.VALOR_EMPRESA
                     END, 
             F.CCOSTO, F.IDAREA, 
             CUENTA = DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', 'DB', A.CODCONCEPTO, F.IDAREA, F.CCOSTO,'S',B.CODNOMINA),
             A.CNSPAGO, A.LINEA, A.CODCONCEPTO, G.DESCRIPCION
      FROM   NEMPFD A INNER JOIN NPER  B ON A.CNSPAGO     = B.CNSPAGO 
                       LEFT JOIN NPRF  C ON A.CODPRF      = C.CODPRF 
                       LEFT JOIN NCOND D ON A.CODCONCEPTO = D.CODCONCEPTO AND A.ITEMCONCEPTO=D.ITEM 
                       LEFT JOIN TER   E ON A.IDTERCERO   = E.IDTERCERO 
                       LEFT JOIN NEMP  F ON F.NUMDOC      = A.NUMDOC 
                       LEFT JOIN NCON  G ON G.CODCONCEPTO = A.CODCONCEPTO 
                       LEFT JOIN NEMPF H ON A.CNSPAGO     = H.CNSPAGO AND A.NUMDOC = H.NUMDOC AND A.ITEM = H.ITEM
      WHERE  A.CNSPAGO    = @CNSPAGO 
      AND    D.GENERA_CXP = 'Si' 
      AND    A.INFO       = 'No' 
      AND    A.VALOR + A.VALOR_EMPRESA <>0 
      AND    A.CODPRF  = @CODPRF_CUR 
      AND    C.CLASE  <> 'Salario' 
      AND    A.IDTERCERO=@IDTERCERO_CUR 
      AND    NOT C.CODPRF IS NULL 
      AND    NOT E.IDTERCERO IS NULL
    
    OPEN CUR2
    FETCH NEXT FROM CUR2
    INTO @NUMDOC_CUR2, @CANTIDAD_CUR2, @VALOR_CUR2, @CCOSTO_CUR2, @IDAREA_CUR2, @CUENTA_CUR2, @CNSNIEPE_CUR2, 
         @ITEMNIEPE_CUR2, @CODCONCEPTO_CUR, @NOMBRE_CONCEPTO_CUR
    
    SET @ITEM = 1
    WHILE @@FETCH_STATUS = 0
    BEGIN
       PRINT 'FCXPD.'
       INSERT INTO FCXPD(CNSFCXP,ITEM,IDSERVICIO,CANTIDAD,VALOR,ESTADO,N_PRESUP,ITEM_PRESUP,IDCLASEIMP,VLR_DESCUENTO,
                         VLR_IVA,VLR_NETO,NOLOTE,PREFIJO,CCOSTO,IDAREAH,IDAREA,NROCOMPROBANTE,PROCEDENCIA, CUENTA_SER)
       SELECT @CNSFCXP CNSFCXP, @ITEM ITEM, @CODCONCEPTO_CUR IDSERVICIO, @CANTIDAD_CUR2 CANTIDAD, @VALOR_CUR2 VALOR, 'P' ESTADO, 
              @CNSNIEPE_CUR2 N_PRESUP, @ITEMNIEPE_CUR2 ITEM_PRESUP, NULL IDCLASEIMP, 0 VLR_DESCUENTO,
              0 VLR_IVA, @VALOR_CUR2 VLR_NETO, @NUMDOC_CUR2 NOLOTE, @CODCONCEPTO_CUR PREFIJO, @CCOSTO_CUR2 CCOSTO, 
              NULL IDAREAH, @IDAREA_CUR2 IDAREA,NULL NROCOMPROBANTE, 'Nomina', '0'
--------------------------------aqui toca adicionar  el spk de nota debito credito  JHONATAN STEVEN ------------------------------------------------              
              EXEC SPK_CALCULOVALORESCXP @CNSFCXP
------------------------------------------------------------YA RECALCULA EN CXP---------------------------------------------------------------------------------       

       FETCH NEXT FROM CUR2
       INTO @NUMDOC_CUR2, @CANTIDAD_CUR2, @VALOR_CUR2, @CCOSTO_CUR2, @IDAREA_CUR2, @CUENTA_CUR2, @CNSNIEPE_CUR2, 
            @ITEMNIEPE_CUR2, @CODCONCEPTO_CUR, @NOMBRE_CONCEPTO_CUR
       SET @ITEM = @ITEM + 1
    END
    CLOSE CUR2
    DEALLOCATE CUR2
    FETCH NEXT FROM CUR
    INTO @CODNOMINA, @CODPRF_CUR, @DESCRIPCION_CUR, @IDTERCERO_CUR, @FECHA_CUR, @VALOR_CUR
 END 
 CLOSE CUR
 DEALLOCATE CUR
END
