CREATE OR ALTER PROC GENERA_PRESTACION_TAREA @NOADMISION VARCHAR(20),@NOPRESTACIONB VARCHAR(20),@FECHAINI DATETIME, @FECHAFIN DATETIME

AS
SET DATEFORMAT dmy
DECLARE @NUEVAPRSTA VARCHAR(20)

SELECT @FECHAFIN=COALESCE(FECHAALTAMED,@FECHAFIN) FROM HADM WHERE NOADMISION=@NOADMISION 


WHILE @FECHAINI<=@FECHAFIN
BEGIN
   PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE('01','SIN SEDE')+' COMPANIA '+COALESCE('01','CIA') 
   SELECT @NUEVAPRSTA=''
	EXEC SPK_GENCONSECUTIVO '01','01', '@HPRE', @NUEVAPRSTA OUTPUT  
   PRINT '@CNSCXC='+COALESCE(@NUEVAPRSTA,'')   
	SELECT @NUEVAPRSTA = '01' + REPLACE(SPACE(8 - LEN(@NUEVAPRSTA))+LTRIM(RTRIM(@NUEVAPRSTA)),SPACE(1),0)
	PRINT '@CNSCXC='+COALESCE(@NUEVAPRSTA,'') 

   INSERT INTO HPRE(NOPRESTACION, NOADMISION, FECHA, IDPLAN, IDAREAH, NIVELATENCION, IDAREA, IDSEDE, ALTOCOSTO, NO_ITEMES, VALORTOTAL, VALORCOPAGO, VALOREXEDENTE, IMPRESO, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA,  AUTORIZADO, USUARIO, CERRADA, VALORPCOMP, CIRUGIA, PCUBRIMIENTO, CLASEORDEN, CONSECUTIVO, ESDEINV, PEDIDOINV, CNSMOV, INDDEVOLUCION, PREFIJO, CCOSTO, SUBCCOSTO, FINALIDAD,  AMBITO, PERSONAL_AT, DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX, ESCONSULTA, IDAREAEQUIPO, IMPRESOP, IDMEDICO, COBRARA, IDTERCEROCA, CONSECUTIVOHCA, ITEMRED, ENLAB, ITFC,  CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, CODEVAL, IDAREAAUX, INDLABCORE, CCOSTOAUX, CONTABILIZADA, NROCOMPROBANTE, MARCACONT, NOPLANTILLA, SINCRONIZADO, ANULADO, PROCEDENCIA, VALIDADO,  TIPOHISTORIA, CODOM, CONTABNIIF, NROCOMPROBANTENIIF, REVAUD, USUREVAUD, F_REVAUD, FECHA_SH, COMERCIAL)
   SELECT @NUEVAPRSTA, @NOADMISION, @FECHAINI, IDPLAN, IDAREAH, NIVELATENCION, IDAREA, IDSEDE, ALTOCOSTO, NO_ITEMES, VALORTOTAL, VALORCOPAGO, VALOREXEDENTE, IMPRESO, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA,  AUTORIZADO, 'SOPORTEX', CERRADA, VALORPCOMP, CIRUGIA, PCUBRIMIENTO, CLASEORDEN, CONSECUTIVO, ESDEINV, PEDIDOINV, CNSMOV, INDDEVOLUCION, PREFIJO, CCOSTO, SUBCCOSTO, FINALIDAD,  AMBITO, PERSONAL_AT, DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX, ESCONSULTA, IDAREAEQUIPO, IMPRESOP, IDMEDICO, COBRARA, IDTERCEROCA, CONSECUTIVOHCA, ITEMRED, ENLAB, ITFC,  CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, CODEVAL, IDAREAAUX, INDLABCORE, CCOSTOAUX, CONTABILIZADA, NROCOMPROBANTE, MARCACONT, NOPLANTILLA, SINCRONIZADO, ANULADO, PROCEDENCIA, VALIDADO,  TIPOHISTORIA, CODOM, CONTABNIIF, NROCOMPROBANTENIIF, REVAUD, USUREVAUD, F_REVAUD, FECHA_SH, COMERCIAL
   FROM HPRE 
   WHERE NOPRESTACION=@NOPRESTACIONB

   INSERT INTO HPRED (NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALOREXCEDENTE, IDPLAN, IMPRESO, AUTORIZADO, COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, AMBITO, FINALIDAD, PERSONAL_AT,  DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX, VALORPCOMP, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT, CONSECUTIVOCX, ITEMCIRUGIA, IDCIRUGIA, TIPOSERCIRUGIA, FACTURADA, N_FACTURA, VLRAPLICADO1,  VLRAPLICADO2, CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION, INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, PCOSTO, CXP, FECHA, VIA, IDAREAH, IDAREA, NIVELATENCION,  PEDIDOINV, NOLOTE, COBRARA, IDTERCEROCA, PCUBRIMIENTO, TIPODTO, DESCUENTO, NORDEN, VALORTOTALCOSTO, CCOSTO, ENLAB, CNSMOV, AUTORIZACION, AQUIENCOBRO, NOAUTORIZACION, CODPRG, IDCONTRATO,  ITFC, CNSITFC, IDTARIFA, CODIFICACION, GRUPOQX_UVR_CX, CODCUPS, CODUNG, SINCRONIZADO, ANULADO, MANUAL, APOYODG_AMBITO, PAQUETE, ITEM_RPDX, ENCARGOS, VALORCOPAGONORMAL, VALORCOPAGOEXTERNO,  MARCA, USUARIOMARCA, ITEM_HCASER, NUM_ORDEN, IDARTICULO, CNSHBALI, NCONSECUTIVO, NTIPO, CLASEOM, ESTADOAPLICACION, HORA, AUDITADO, AUDITOR, IDSERVICIOH, VLRSERVICIOH,  N_FACTURAH, CANTIDADH, NPRESTACIONH, NOITEMH, NOPOSHOM, IDTERCEROH, CODCUMIPRES, FECHASOL, CODIGOCUM, EQUIPOMUES, DESC_EQUIPOMUES, CNSCONTENEDOR, VIVACOPA, VIVATCOPA, VIVATVENTA,  PVENTAT, CNSPRELIQ)
   SELECT @NUEVAPRSTA, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALOREXCEDENTE, IDPLAN, IMPRESO, AUTORIZADO, COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, AMBITO, FINALIDAD, PERSONAL_AT,  DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX, VALORPCOMP, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT, CONSECUTIVOCX, ITEMCIRUGIA, IDCIRUGIA, TIPOSERCIRUGIA, FACTURADA, N_FACTURA, VLRAPLICADO1,  VLRAPLICADO2, CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION, INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, PCOSTO, CXP, FECHA, VIA, IDAREAH, IDAREA, NIVELATENCION,  PEDIDOINV, NOLOTE, COBRARA, IDTERCEROCA, PCUBRIMIENTO, TIPODTO, DESCUENTO, NORDEN, VALORTOTALCOSTO, CCOSTO, ENLAB, CNSMOV, AUTORIZACION, AQUIENCOBRO, NOAUTORIZACION, CODPRG, IDCONTRATO,  ITFC, CNSITFC, IDTARIFA, CODIFICACION, GRUPOQX_UVR_CX, CODCUPS, CODUNG, SINCRONIZADO, ANULADO, MANUAL, APOYODG_AMBITO, PAQUETE, ITEM_RPDX, ENCARGOS, VALORCOPAGONORMAL, VALORCOPAGOEXTERNO,  MARCA, USUARIOMARCA, ITEM_HCASER, NUM_ORDEN, IDARTICULO, CNSHBALI, NCONSECUTIVO, NTIPO, CLASEOM, ESTADOAPLICACION, HORA, AUDITADO, AUDITOR, IDSERVICIOH, VLRSERVICIOH,  N_FACTURAH, CANTIDADH, NPRESTACIONH, NOITEMH, NOPOSHOM, IDTERCEROH, CODCUMIPRES, FECHASOL, CODIGOCUM, EQUIPOMUES, DESC_EQUIPOMUES, CNSCONTENEDOR, VIVACOPA, VIVATCOPA, VIVATVENTA,  PVENTAT, CNSPRELIQ
   FROM HPRED 
   WHERE NOPRESTACION=@NOPRESTACIONB

   SELECT @FECHAINI=DATEADD(DAY,1,@FECHAINI)

END