ALTER TABLE [dbo].[FPA]     NOCHECK CONSTRAINT [FK_FPA_FPACUENTA]
ALTER TABLE [dbo].[PAR]     NOCHECK CONSTRAINT [FK_PAR_PARCTACRUCECAJA]
ALTER TABLE [dbo].[OFIN]    NOCHECK CONSTRAINT [FK_OFIN_OFINCUENTA]
ALTER TABLE [dbo].[TTEC]    NOCHECK CONSTRAINT [FK_TTEC_TTECCUENTA]
ALTER TABLE [dbo].[FTRCXC]  NOCHECK CONSTRAINT [FK_FTRCXC_FTRCXCCUENTA]
ALTER TABLE [dbo].[FNT]     NOCHECK CONSTRAINT [FK_FNT_FNTCUENTA]
ALTER TABLE [dbo].[KPRES]   NOCHECK CONSTRAINT [FK_KPRES_KPRESCUENTA_PER]
ALTER TABLE [dbo].[KPRES]   NOCHECK CONSTRAINT [FK_KPRES_KPRESCUENTA_UTI]
ALTER TABLE [dbo].[FDISD]   NOCHECK CONSTRAINT [FK_FDISD_FDISDCUENTA]

SELECT  * FROM PRI WHERE ANO='2023'

UPDATE PRI SET CERRADO=0 WHERE ANOMES='202312'

EXEC SPK_CIERRE_MES_CONTABLE '2023',12,'JJIMENEZ'

SELECT  * FROM MCP WHERE ANOMES='202312'

SELECT CUENTA,IDTERCERO,N_FACTURA,SUM(SF) SF INTO #A FROM SALDOMESTERFAC WHERE ANO='2023' AND MES=12
GROUP BY CUENTA,IDTERCERO,N_FACTURA
HAVING SUM(SF)<>0

SELECT  TOP 10 * FROM #A
SELECT  TOP 10 * FROM NTZ

ALTER TABLE #A ADD NTZ VARCHAR(2)

UPDATE #A SET NTZ=NTZ.TIPO FROM #A INNER JOIN NTZ ON LEFT(#A.CUENTA,1)=NTZ.N_INICIAL

UPDATE #A SET TIPO=CASE WHEN SF>0 THEN NTZ ELSE CASE WHEN NTZ='DB' THEN 'CR' ELSE 'DB' END END

SELECT * FROM NTZ


SELECT  X.CUENTA, X.NOMCUENTA, 0 SI, 
          SUM(CASE MCH.TIPO WHEN 'DB' THEN MCH.VALOR ELSE 0 END) DB, 
          SUM(CASE MCH.TIPO WHEN 'CR' THEN MCH.VALOR ELSE 0 END) CR,
          0 SF,
          0 SM, 	       
          NTZ.TIPO, 0 SI_DB, 0 SI_CR, 0 SF_DB, 0 SF_CR
   FROM   MCP INNER JOIN MCH            ON MCP.NROCOMPROBANTE = MCH.NROCOMPROBANTE 
              INNER JOIN #GENEALOGICO X ON X.CUENTA_DETALLE = MCH.CUENTA
              INNER JOIN NTZ  ON  LEFT(MCH.CUENTA,1) = NTZ.N_INICIAL
   WHERE  MCP.ESTADO = 2 AND ISNULL(MCP.ANULADO,0) = 0
   AND    MCP.ANO =  '2023'
   AND    MCP.MES =  12
   GROUP BY X.CUENTA, X.NOMCUENTA, NTZ.TIPO	       
   ORDER BY X.CUENTA  

   SELECT SUM(CASE WHEN TIPO='DB' THEN ABS(SF)  ELSE 0 END),SUM(CASE WHEN TIPO='CR' THEN ABS(SF)  ELSE 0 END)  FROM #A
    SELECT 2237388447548.90-2237388447548.90

    0191000004844804

    SELECT  * INTO #B FROM KRYFAS.DBO.MCH WHERE NROCOMPROBANTE='0191000004844804'

    DELETE KRYFAS.DBO.MCH WHERE NROCOMPROBANTE='0191000004844804'

    UPDATE #A SET SF=ABS(SF)

    SELECT  * FROM #B
    SELECT DBO.FNK_COLUMNAS_TABLAS('MCH')
    INSERT INTO KRYFAS.DBO.MCH(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG, CODPRG, ERROR, IDOPERACION,  FECHACONCILIACION, IDPROVEEDOR, ENPRESUPUESTO, ESTADOIMP, IDSEDE)
    SELECT NROCOMPROBANTE, COMPANIA, #A.TIPO, #A.CUENTA, #A.IDTERCERO, CCOSTO, DETALLE, #A.SF, REFERENCIA1, REFERENCIA2, REFERENCIA3, #A.N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG, CODPRG, ERROR, IDOPERACION,  FECHACONCILIACION, IDPROVEEDOR, ENPRESUPUESTO, ESTADOIMP, IDSEDE
    FROM #A,#B