CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFTR 
ON FTR 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME =  GETDATE() 
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOHADM 
ON HADM 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOHPRE 
ON HPRE 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOHPRED 
ON HPRED 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOAUT 
ON AUT 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOAUTD 
ON AUTD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOMCP 
ON MCP 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOMCH 
ON MCH 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOHCA 
ON HCA 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOHCAD 
ON HCAD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOLING 
ON LING 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOLORD 
ON LORD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO  
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOLORDD 
ON LORDD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFTRD 
ON FTRD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFCJ 
ON FCJ 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFCJD 
ON FCJD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOPCJ 
ON PCJ 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFCXP 
ON FCXP 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFCXPD 
ON FCXPD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOIMOV 
ON IMOV 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOIMOVH 
ON IMOVH 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOITRA 
ON ITRA 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOITRAH 
ON ITRAH 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOSER 
ON SER 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOTAR 
ON TAR 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOTARD 
ON TARD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOTARDV 
ON TARDV 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOTER 
ON TER 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOTEXCA 
ON TEXCA 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOCUE 
ON CUE 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOKMCOM 
ON KMCOM 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOCPPAF 
ON CPPAF 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOCIT 
ON CIT 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_AFI_IDAFILIADO 
ON AFI 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO   
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK1_PROCESOAFI' AND TYPE = 'TR') 
   DROP TRIGGER DBO.TK1_PROCESOAFI 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOAFI 
ON AFI 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO  
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFNOT 
ON FNOT 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFNOTD 
ON FNOTD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFCXC 
ON FCXC 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFCXCD 
ON FCXCD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFCXCDV 
ON FCXCDV 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFGLO 
ON FGLO 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOFPAG 
ON FPAG 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOHADMAD 
ON HADMAD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOHADMDX 
ON HADMDX 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END
GO  
CREATE OR ALTER TRIGGER DBO.TK1_PROCESOUSUSU 
ON USUSU WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00' 
BEGIN 
	RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
	ROLLBACK TRANSACTION 
END 
GO 
/*SEGUNDA PARTE*/
CREATE OR ALTER TRIGGER DBO.TK_PROCESOFTR 
ON FTR 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHADM 
ON HADM 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHPRE 
ON HPRE 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHPRED 
ON HPRED 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOAUT 
ON AUT 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOAUTD 
ON AUTD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOMCP 
ON MCP 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOMCH 
ON MCH 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHCA 
ON HCA 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHCAD 
ON HCAD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOLING 
ON LING 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOLORD 
ON LORD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOLORDD 
ON LORDD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOFTRD 
ON FTRD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOFCJ 
ON FCJ 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOFCJD 
ON FCJD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOPCJ 
ON PCJ 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOFCXP 
ON FCXP 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOFCXPD 
ON FCXPD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOIMOV 
ON IMOV 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOIMOVH 
ON IMOVH 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOITRA 
ON ITRA 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOITRAH 
ON ITRAH 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOSER 
ON SER 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOTAR 
ON TAR 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOTARD 
ON TARD 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOTARDV 
ON TARDV 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO  
CREATE OR ALTER TRIGGER DBO.TK_PROCESOTER 
ON TER 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOTEXCA 
ON TEXCA 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()

IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOCUE 
ON CUE 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOKMCOM 
ON KMCOM 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOCPPAF 
ON CPPAF 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOCIT 
ON CIT 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PERIODO_CONTB_FNOT 
ON AFI 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOAFI 
ON HADM 
WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > CONVERT(DATETIME,'20251231 15:00:00') 
BEGIN 
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
   ROLLBACK TRANSACTION 
END 
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOUSUSU 
ON USUSU WITH ENCRYPTION 
FOR INSERT, UPDATE, DELETE 
AS 
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00' 
BEGIN
	RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO', 16, 1) 
	ROLLBACK TRANSACTION 
END	 
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOFNOT
ON FNOT
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO 
CREATE OR ALTER TRIGGER DBO.TK_PROCESOFNOTD
ON FNOTD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOAPLIM
ON APLIM
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOAPLIMG
ON APLIMG
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOMAD
ON MAD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOMADNOT
ON MADNOT
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOPHDNOT
ON PHDNOT
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOPHDNOT
ON PHDNOT
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOCEOM
ON CEOM
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHCATDPT
ON HCATDPT
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOCAP
ON CAP
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOCAPD
ON CAPD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESONIEPEG
ON NIEPEG
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOAUTDF
ON AUTDF
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHPREP
ON HPREP
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHPREPD
ON HPREPD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESORUTA
ON RUTA
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESORUTAD
ON RUTAD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESORUTAAGENDA
ON RUTAAGENDA
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOIEXIF
ON IEXIF
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOAUTPG
ON AUTPG
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHCATD_STAFF
ON HCATD_STAFF
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOFTR_MAS_LOG
ON FTR_MAS_LOG
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOHADMSER
ON HADMSER
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_PROCESOAPLIMG
ON APLIMG
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME = GETDATE()
IF @FECHA > '20251231 15:00:00'
BEGIN
	RAISERROR ('INTENTO DE VIOLACION DE LICENCIA KRYSTALOS', 16, 1)
	ROLLBACK TRANSACTION
END
GO
CREATE OR ALTER TRIGGER DBO.TK_AFI_IDAFILIADO
ON AFI
WITH ENCRYPTION
FOR  UPDATE 
AS   
	SET DATEFORMAT dmy
	DECLARE @ANTIDAFILIADO VARCHAR(20)
	DECLARE @NUEIDAFILIADO VARCHAR(20)
	SELECT @NUEIDAFILIADO = INSERTED.IDAFILIADO FROM INSERTED 
	SELECT @ANTIDAFILIADO = DELETED.IDAFILIADO FROM DELETED
	IF @ANTIDAFILIADO <> @NUEIDAFILIADO
	BEGIN
		UPDATE FTR SET IDAFILIADO = @NUEIDAFILIADO
		WHERE  IDAFILIADO = @ANTIDAFILIADO
	END

