DECLARE @N  INT
DECLARE @D  INT
SET @N=0
WHILE @N<=100
BEGIN
   SELECT @D= ((20 - 1) * RAND(CONVERT(VARBINARY, NEWID())) + 1)
   PRINT 'NUMERO ALEATORIO:::'+ CAST(@D AS VARCHAR(20))
    SELECT @N=+@N+1

END


SELECT GETDATE()+1
SELECT GETDATE(),DATEADD([minute], -10, GETDATE()) AS dt