SELECT  A.CONSECUTIVO,A.FECHA,B.IDSERVICIO,C.DESCSERVICIO,
CONVERT(NUMERIC(10,2),CASE WHEN C.MDOSIF=1 THEN B.CANTIDADNOCC ELSE B.CANTIDAD*(B.FRECUENCIA/B.DURACION)  END) CANT,
 IDTIPOCONC,C.EQUICC,B.CANTIDADINV
FROM HRED A INNER JOIN HCATD B ON A.CONSECUTIVO=B.CONSECUTIVO AND A.ITEMRED=B.ITEMRED
            INNER JOIN SER   C ON B.IDSERVICIO=C.IDSERVICIO
WHERE A.NOADMISION='0100000109' AND B.CODOM IN('01','02') AND CLASE='I' AND TIPO='HORARIA'



SELECT  A.CONSECUTIVO,B.IDSERVICIO,C.DESCSERVICIO,
SUM(CONVERT(NUMERIC(10,2),CASE WHEN C.MDOSIF=1 THEN B.CANTIDADNOCC ELSE B.CANTIDAD*(B.FRECUENCIA/B.DURACION)  END)) CANT,
 IDTIPOCONC,C.EQUICC,SUM(CONVERT(INT,CASE WHEN C.MDOSIF=1 THEN B.CANTIDADINV ELSE B.CANTIDAD*(B.FRECUENCIA/B.DURACION) END ))CANTIDADINV
FROM HRED A INNER JOIN HCATD B ON A.CONSECUTIVO=B.CONSECUTIVO AND A.ITEMRED=B.ITEMRED
            INNER JOIN SER   C ON B.IDSERVICIO=C.IDSERVICIO
WHERE A.NOADMISION='0100000109' AND B.CODOM IN('01','02') AND CLASE='I' AND TIPO='HORARIA'
GROUP BY A.CONSECUTIVO,B.IDSERVICIO,C.DESCSERVICIO,IDTIPOCONC,C.EQUICC

SELECT  A.CONSECUTIVO,A.FECHA,B.IDSERVICIO,C.DESCSERVICIO,
CONVERT(NUMERIC(10,2),CASE WHEN C.MDOSIF=1 THEN B.CANTIDADNOCC ELSE B.CANTIDAD*(B.FRECUENCIA/B.DURACION)  END) CANT,
 IDTIPOCONC,C.EQUICC,B.CANTIDADINV
FROM HRED A INNER JOIN HCATD B ON A.CONSECUTIVO=B.CONSECUTIVO AND A.ITEMRED=B.ITEMRED
            INNER JOIN SER   C ON B.IDSERVICIO=C.IDSERVICIO
WHERE A.NOADMISION='0100000109' AND B.CODOM IN('01','02') AND CLASE='I' AND TIPO='HORARIA'
AND B.IDSERVICIO='MEDNOPOS008'

