SELECT * FROM JFNOTI

CREATE TABLE JCONCI(N_FACTUTURA VARCHAR(20),VLR_GLOSA DECIMAL(14,2),	ACEPTADA DECIMAL(14,2),	VLR_RECUPERADO DECIMAL(14,2))





SELECT * FROM JCONCI WHERE N_FACTUTURA  NOT LIKE '%CSI%' AND N_FACTUTURA<'320731'

SELECT  MAX(N_FACTURA) FROM FTR WHERE N_FACTURA  LIKE '00%' AND N_FACTURA>'300000'
ORDER BY N_FACTURA

UPDATE JCONCI SET N_FACTUTURA='00'+LTRIM(RTRIM(N_FACTUTURA)) WHERE N_FACTUTURA NOT LIKE '%CSI%' AND N_FACTUTURA<'320731'


SELECT * FROM VWK_CXCDIASVTO 

SELECT * FROM JCONCI  WHERE NOT EXISTS(SELECT * FROM FTR VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA)  AND N_FACTUTURA NOT LIKE '%CSI%'

DELETE JCONCI

SELECT N_FACTUTURA,SUM(VLR_GLOSA)VLR_GLOSA,SUM(ACEPTADA)ACEPTADA,SUM(VLR_RECUPERADO)VLR_RECUPERADO INTO #E  FROM JCONCI
GROUP BY N_FACTUTURA

INSERT INTO JCONCI
SELECT * FROM #E
UPDATE JCONCI SET N_FACTUTURA=LEFT(N_FACTUTURA,3)+'000'+RIGHT(N_FACTUTURA,5)  WHERE NOT EXISTS(SELECT * FROM FTR VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA)  AND N_FACTUTURA NOT LIKE '%CSI%'


SELECT * FROM JCONCI WHERE  EXISTS(SELECT * FROM VWK_CXCDIASVTO VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA AND TIPO='G' AND VK.SALDONETO=VLR_GLOSA) 
SELECT * INTO #A FROM JCONCI WHERE NOT EXISTS(SELECT * FROM FTR VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA) 
ORDER BY N_FACTUTURA

BEGIN TRAN 
UPDATE JCONCI SET N_FACTUTURA=RIGHT(N_FACTUTURA,6)
 WHERE NOT EXISTS(SELECT * FROM FTR VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA) 
AND N_FACTUTURA>'00319891'
AND LEN(N_FACTUTURA)>6

COMMIT


SELECT * FROM #A

ALTER TABLE #A ADD N_FACTURA VARCHAR(20)

UPDATE #A SET N_FACTURA=REPLACE(N_FACTUTURA,'00','')

BEGIN TRAN
DELETE FROM JCONCI WHERE NOT EXISTS(SELECT * FROM FTR VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA ) 

ROLLBACK

COMMIT

SELECT * FROM JCONCI WHERE NOT EXISTS(SELECT * FROM FTR VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA AND IDTERCERO='818000140' ) 

DELETE JCONCI WHERE NOT EXISTS(SELECT * FROM FTR VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA AND IDTERCERO='800250119' ) 
SELECT * FROM JCONCI WHERE NOT EXISTS(SELECT * FROM VWK_CXCDIASVTO VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA ) 

DELETE JCONCI WHERE NOT EXISTS(SELECT * FROM VWK_CXCDIASVTO VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA ) 

SELECT * FROM JCONCI WHERE  EXISTS(SELECT * FROM VWK_CXCDIASVTO VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA AND TIPO='G') 
SELECT * FROM JCONCI WHERE NOT EXISTS(SELECT * FROM VWK_CXCDIASVTO VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA AND TIPO='G') 

SELECT * FROM JCONCI WHERE  EXISTS(SELECT * FROM VWK_CXCDIASVTO VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA AND TIPO='G' AND VK.SALDONETO=ROUND(VLR_GLOSA,0)) 
SELECT * FROM JCONCI WHERE  EXISTS(SELECT * FROM VWK_CXCDIASVTO VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA AND TIPO='G' AND VK.SALDONETO<>ROUND(VLR_GLOSA,0)) 

-- TODA CONCILIA -- 1065
-- SIN GLOSA --10
--TODAS GLOSAS 1055
--IGUAL GLOSA  1045
-- DIFERENTE GLOSA --10

SELECT * FROM VWK_CXCDIASVTO WHERE N_FACTURA='00317476' AND TIPO='G'

SELECT * FROM FTR WHERE N_FACTURA='CSI00018127'
SELECT * FROM FTR WHERE N_FACTURA='CSI18127'

SELECT * FROM FCONCID WHERE  FCONCID.IDFCONCI='0100000357'



SELECT N_FACTUTURA AS N_FACTURA,VLR_GLOSA,ACEPTADA INTO #B FROM JCONCI WHERE  EXISTS(SELECT * FROM VWK_CXCDIASVTO VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA AND TIPO='G' AND VK.SALDONETO=ROUND(VLR_GLOSA,0)) 
AND NOT EXISTS(SELECT * FROM FCONCID WHERE FCONCID.N_FACTURA=JCONCI.N_FACTUTURA AND FCONCID.IDFCONCI='0100000359')

DROP TABLE #B

SELECT N_fACTURA FROM #B 
GROUP BY N_fACTURA
HAVING COUNT(*)>1

SELECT * FROM #B

DROP TABLE #C

SELECT '0100000359'IDFCONCI,ROW_NUMBER() OVER(ORDER  BY B.N_FACTURA  DESC) NRO,B.CNSCXC,B.N_FACTURA,C.ITEM,B.TIPO,B.CNSGLO,B.SALDONETO,A.ACEPTADA,B.SALDONETO-A.ACEPTADA VLR_RECUPERA,''CNSFNOT,'C'CLASE,'INGRESADA'ESTADO,'Subida por sql....'OBSERVACION INTO #C
FROM #B A INNER JOIN VWK_CXCDIASVTO B ON A.N_FACTURA=B.N_FACTURA AND ROUND(A.VLR_GLOSA,0)=B.SALDONETO AND  B.TIPO='G'
          INNER JOIN FCXCDV C ON B.N_FACTURA=C.N_FACTURA AND B.CNSCXC=C.CNSCXC AND B.CNSGLO=C.CNSGLO AND C.TIPO=C.TIPO

SELECT N_FACTURA FROM #C
GROUP BY N_FACTURA
HAVING COUNT(*)>1


INSERT INTO FCONCID
SELECT * FROM #C


SELECT * FROM JCONCI WHERE  EXISTS(SELECT * FROM VWK_CXCDIASVTO VK WHERE VK.N_FACTURA=JCONCI.N_FACTUTURA AND TIPO='G' AND VK.SALDONETO<>ROUND(VLR_GLOSA,0))


SELECT B.CNSCXC,B.N_FACTURA,B.TIPO,B.CNSGLO,A.VLR_GLOSA VALOR_SALUDCOOP,B.SALDONETO,(A.VLR_GLOSA-B.SALDONETO)DIFERENCIA,A.ACEPTADA
FROM JCONCI A INNER JOIN VWK_CXCDIASVTO B ON A.N_FACTUTURA=B.N_FACTURA AND ROUND(A.VLR_GLOSA,0)<>B.SALDONETO AND  B.TIPO='G'


DELETE JCONCI


