DECLARE @NOADMISION VARCHAR(20)
DECLARE @FECHAINI DATETIME
DECLARE @FECHAMAX DATETIME
DECLARE @CONSECUTIVO VARCHAR(20)
DECLARE @NRO SMALLINT

SELECT @FECHAINI='04/11/2022',@FECHAMAX='05/11/2022'


	DECLARE PG_CURSOR CURSOR FOR   
   SELECT  NOADMISION FROM HADM WHERE COALESCE(FECHAALTAMED,GETDATE())>=@FECHAINI AND FECHA<@FECHAMAX
	OPEN PG_CURSOR    
	FETCH NEXT FROM PG_CURSOR    
	INTO @NOADMISION
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
      IF EXISTS(SELECT * FROM HCA WHERE NOADMISION=@NOADMISION AND CLASEPLANTILLA='OMEDICA' AND FECHA>=@FECHAINI AND FECHA<@FECHAMAX)
      BEGIN 
          FETCH NEXT FROM PG_CURSOR    
	       INTO @NOADMISION
          CONTINUE
      END
      SELECT TOP 1 @CONSECUTIVO=CONSECUTIVO FROM HCA WHERE NOADMISION=@NOADMISION 
      AND CLASEPLANTILLA='OMEDICA' 
      AND FECHA<@FECHAINI 
      AND CONSECUTIVO NOT LIKE '%_%'

      SELECT @NRO=COUNT(*) FROM HCA WHERE NOADMISION=@NOADMISION AND CONSECUTIVO LIKE @CONSECUTIVO+'_%'

      SELECT DBO.FNK_COLUMNAS_TABLAS('HCATD')

      INSERT INTO HCA(CONSECUTIVO, CLASEPLANTILLA, FECHA, IDMEDICO, IDAFILIADO, NOADMISION, IDDX, TIPODX, IMPRESO, EDAD, FINALIDAD, DX1, 
                      DX2, DX3, IDMEDICODILIGENCIA, IDDXEG, N_HISTORIA, PROCEDENCIA, REVISAESP,  IDMEDICOESP, PIDEDX, PIDESV, TAS, TAD, 
                      FC, FR, TEMP, TALLA, PULSO, PESO, GLASGOW, TIPOGLASGOW, HIDRATACION, ALTA, CLASE, ITEMHADM, IDAREA, ANULADA, USUARIOANU, 
                      FECHA_ANU,  OBSERVAANU, AMBITO, MED_ESPEC, CAUSA_EXT, SINCRONIZADO, IDPLAN, CCOSTO, ENEPICRISIS, CERRADA, EVOLUCION, 
                      ITEMRED, PLANDEMANEJO, RESUMEN, EVOLSUB, ANALISIS, ESTANCIA, RESPARACLINI,  JUSTESTANCIA, TAM, SOAT, BOLO, 
                      CONSECUTIVO_RED_ORI, ITEMRED_RED_ORI, DIURESIS, CNSNESIGVIT_SV, CNSNESIGVIT_GC, CNSNESIGVIT_GA, TIPOSV, PLANDEMANEJOMED, 
                      CNSNESIGVIT_GV, CNSNESIGVIT_PV,  CNSNESIGVIT_IO, TIPOPM, COPIADA, CONSECUTIVOCOPIA, REVISADO, FECHAREV, USUARIOREV, 
                      ESTADOCIERRE, CONSECUTIVOCIERRE, CREADAEN, SOFA, NOCOPIAOM, RIESGO, DX4, USUARIO, CODAZUL,  IDAFILIADO_RN, CNSWEB, 
                      CONSECUTIVOP, CONSECUTIVOCIT, COVID, FECHAATIENDE, CHECK1, CHECK2, CHECK3, NECPAL, N_S1, N_S2, N_S3, N_S4, N_S5, N_S6, 
                      ESTADOAUD, IDMEDICO_AUD, FECHA_AUD,  CODIGO_AUD, OBSERVACIONAUD, NOTA_ACLARA, CNSHCA_NOTA)
      SELECT CONSECUTIVO+'_'+LTRIM(RTRIM(STR(@NRO))), CLASEPLANTILLA, DATEADD(HOUR,10,@FECHAINI), IDMEDICO, IDAFILIADO, NOADMISION, IDDX, TIPODX, IMPRESO, EDAD, 
                  FINALIDAD, DX1, DX2, DX3, IDMEDICODILIGENCIA, IDDXEG, N_HISTORIA, PROCEDENCIA, REVISAESP,  IDMEDICOESP, PIDEDX, PIDESV, TAS, TAD, FC, 
                  FR, TEMP, TALLA, PULSO, PESO, GLASGOW, TIPOGLASGOW, HIDRATACION, ALTA, CLASE, ITEMHADM, IDAREA, ANULADA, USUARIOANU, FECHA_ANU,  OBSERVAANU,
                  AMBITO, MED_ESPEC, CAUSA_EXT, SINCRONIZADO, IDPLAN, CCOSTO, ENEPICRISIS, CERRADA, EVOLUCION, ITEMRED, PLANDEMANEJO, RESUMEN, EVOLSUB, 
                  ANALISIS, ESTANCIA, RESPARACLINI,  JUSTESTANCIA, TAM, SOAT, BOLO, CONSECUTIVO_RED_ORI, ITEMRED_RED_ORI, DIURESIS, CNSNESIGVIT_SV, 
                  CNSNESIGVIT_GC, CNSNESIGVIT_GA, TIPOSV, PLANDEMANEJOMED, CNSNESIGVIT_GV, CNSNESIGVIT_PV,  CNSNESIGVIT_IO, TIPOPM, COPIADA, CONSECUTIVOCOPIA, 
                  REVISADO, FECHAREV, USUARIOREV, ESTADOCIERRE, CONSECUTIVOCIERRE, CREADAEN, SOFA, NOCOPIAOM, RIESGO, DX4, USUARIO, CODAZUL,  IDAFILIADO_RN, 
                  CNSWEB, CONSECUTIVOP, CONSECUTIVOCIT, COVID, FECHAATIENDE, CHECK1, CHECK2, CHECK3, NECPAL, N_S1, N_S2, N_S3, N_S4, N_S5, N_S6, ESTADOAUD, 
                  IDMEDICO_AUD, FECHA_AUD,  CODIGO_AUD, OBSERVACIONAUD, NOTA_ACLARA, CNSHCA_NOTA 
      FROM HCA 
      WHERE CONSECUTIVO=@CONSECUTIVO

      INSERT INTO HCAD(CONSECUTIVO, CLASEPLANTILLA, CAMPO, SECUENCIA, NADA, NORMAL, ANORMAL, DETALLAR, NOTAS, TIPOCAMPO, ALFANUMERICO, FECHA, 
                        MEMO, OBS, LISTA, ENEPICRISIS, SINCRONIZADO, MINIMO, MAXIMO, PROMEDIO,  VALORGRAFICA, NUMERICO)
      SELECT CONSECUTIVO+'_'+LTRIM(RTRIM(STR(@NRO))), CLASEPLANTILLA, CAMPO, SECUENCIA, NADA, NORMAL, ANORMAL, DETALLAR, NOTAS, TIPOCAMPO, ALFANUMERICO, FECHA, MEMO, OBS, 
             LISTA, ENEPICRISIS, SINCRONIZADO, MINIMO, MAXIMO, PROMEDIO,  VALORGRAFICA, NUMERICO
      FROM HCAD WHERE CONSECUTIVO=@CONSECUTIVO

      INSERT INTO HCADL(CONSECUTIVO, SECUENCIA, ITEM, VALORLISTA, CHECKM, DESCRIPCION, SINCRONIZADO)
      SELECT CONSECUTIVO+'_'+LTRIM(RTRIM(STR(@NRO))), SECUENCIA, ITEM, VALORLISTA, CHECKM, DESCRIPCION, SINCRONIZADO
      FROM HCADL WHERE CONSECUTIVO=@CONSECUTIVO

      INSERT INTO HCATD (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, CLASE, ENCARGOS, NOPRESTACION, 
                          APLICADA, CONSECUTIVONE, NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION,  TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR,
                          CANTIDADNOCC, CNSHJNOPOS, DESCRIPTIVA, DESTINO, OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, 
                          CANTIDADORI, FRECUENCIAORI,  DURACIONORI, DOSISUNICA, FECHAINI, IDSERVICIOMEZCLA, QMEZCLA, QIMPSERVICIO, QIMPMEZCLA, 
                          DURACIONIMP, RAZONNEC, ORDEN, HORAAM, QAM, HORAPM, QPM, HORASMAX, FECHAMAX, GOTEO,  GENHORARIO, LUNES, MARTES, MIERCOLES,
                          JUEVES, VIERNES, SABADO, DOMINGO, FFINALDOSIS, TIPOSOLBS, BSCAPACIDAD, IDBODEGA, CODPAQUETE, VERIFICA, LATERALIDAD, 
                          TIPOFRECUENCIA, DOSIF,  ESTADOCALL, FECHACALL, USUARIO, NOADMISION, OBS_CALL, IDCAUSAL, AUTORIZADO, HBALINI, RUTA, 
                          TOTALUNIDADES, PRESCRIPCION, TIPODURACION)
      SELECT CONSECUTIVO+'_'+LTRIM(RTRIM(STR(@NRO))), ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, CLASE, ENCARGOS, NOPRESTACION, APLICADA, 
             CONSECUTIVONE, NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION,  TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR, CANTIDADNOCC, 
             CNSHJNOPOS, DESCRIPTIVA, DESTINO, OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, CANTIDADORI, 
             FRECUENCIAORI,  DURACIONORI, DOSISUNICA, FECHAINI, IDSERVICIOMEZCLA, QMEZCLA, QIMPSERVICIO, QIMPMEZCLA, DURACIONIMP, 
             RAZONNEC, ORDEN, HORAAM, QAM, HORAPM, QPM, HORASMAX, FECHAMAX, GOTEO,  GENHORARIO, LUNES, MARTES, MIERCOLES, JUEVES, 
             VIERNES, SABADO, DOMINGO, FFINALDOSIS, TIPOSOLBS, BSCAPACIDAD, IDBODEGA, CODPAQUETE, VERIFICA, LATERALIDAD, TIPOFRECUENCIA, 
             DOSIF,  ESTADOCALL, FECHACALL, USUARIO, NOADMISION, OBS_CALL, IDCAUSAL, AUTORIZADO, HBALINI, RUTA, TOTALUNIDADES, PRESCRIPCION,
             TIPODURACION
      FROM HCATD 
      WHERE CONSECUTIVO=@CONSECUTIVO


      ORDER BY FECHA DESC
	FETCH NEXT FROM PG_CURSOR    
	INTO @NOADMISION
	END
	CLOSE PG_CURSOR
	DEALLOCATE PG_CURSOR