 SELECT DATEADD(MONTH, DATEDIFF(MONTH, 0,GETDATE()), 0)-1 AS 'Primer Dia del Mes'

SELECT DATEADD(MM, DATEDIFF(MM,0,GETDATE()), 0) AS 'Primer Dia del Mes'

SELECT CONVERT(VARCHAR(10),DATEADD(dd,-(DAY(GETDATE())-1),GETDATE()),103) AS 'Primer Dia del Mes'