
DELETE IZSOL

INSERT INTO MOP
SELECT * FROM [BDATOS\SQL2017].KCIELD.DBO.MOP
WHERe IDCONCENTRA NOT IN('ç0','ñ1','')

SELECT * FROM MED

INSERT INTO  HADM(NOADMISION, IDAFILIADO, FECHA, IDSEDE, IDPLAN, IDTERCERO, TIPOADM, HABCAMA, VIAINGRESO, CAUSAEXTERNA, CONDUSUARIA, DXINGRESO, DXEGRESO, COMPLICACION, TIPODISCAP, GRADODISCAP, NOPOLIZA,  NOCARNET, NOAUTORIZACION, FECHAVCEAUT, FECHAALTA, FECHASALIDA, CAUSASALIDA, ESTADOPSALIDA, VRDEPOSITO, RESPCUENTA, ESTADO, URG_NOMBRE, URG_TELE, URG_DIR, IDMEDICOING, IDMEDICOTRA,  CAUSABMUERTE, ENFSOBREAG, OBS, FACTURADA, N_FACTURA, CNSFCT, CERRADA, PCUBRIMIENTO, USUARIO, DXSALIDA1, DXSALIDA2, DXSALIDA3, DESTINO, ESTADOSALIDA, RIPS, NIVELSOCIOEC, TIPOPOLIZA,  IDMEDICOTRA2, IDMEDICOTRA3, ENVIO, FACTURABLE, COPAGO, COPAGONOAUTORIZACION, COPAGOVALOR, TIPOFAC, VFACTURAS, DESCUENTO, TIPODTO, USUARIOALTA, TIPOCREDITO, CREDITO, INDDEVOLUCION,  INDPROCESARDEV, MARCA, ENVIOMARCA, VENCEAUT, MTOPE, TIPOTOPE, FECHATOPE, VALORTOPE, TOPEOTROTERCERO, CONTINUACION, NOADMISIONCONT, FECHATRASHOS, CXP, VLRUTOTRAHADM, IDPROVEEDOR,  TIPOCONT, IDCONTRATO, IDAREA_ALTA, PREADMISION, IDCIRUGIA, PYP, CLASENOPROC, URG_VINCULO, A24H, A2448H, A4872H, A72H30D, CCOSTO_ALTA, FECHAPRE, LIQESTANCIA, FACTURADAPARCIAL,  TIPOCOPAGO, PROCEDENCIA, CNSHACTRAN, DECLARIESGOS, IDMEDICOALTA, CLASEING, PASADACENTRAL, CNSENTREGA, CODUNG, FECHAALTAMED, ITFC, CNSITFC, EMBARAZADA, CNSTRIAGE, TTRIAGE, IDDXULTIMO,  CCOSTOULTIMO, UATENINIURG, ESINSTPROV, ESEINST, FECHAESEINST, MARCAATRASO, REVESPECIALISTA, REFERIDO, IDREFERIDO, MANCOPAGOEXT, NOAUTORIZACIONEXT, VLR_COPAGOEXTERNO, DIASHOSPITALIZACION,  HORASQUIROFANO, TITULARPOLIZA, SINCRONIZADO, NOCOTIZACION, USUALTAMED, IDPLAN_AFI, IDTERCERO_AFI, PAQUETE, TOPECOPAGO_ANX6, TIPOCAJA, CNSFACJ, CODCAJA, USACTC, IDSERVICIOPAQUETE,  VLRSERVICIOPAQ, FECHAALTAENF, IDUSUARIOALTAENF, MDATEXC, NOMBRERESPO, TELEFONORESPO, PARENTESCORESPO, ACTADEFUNCION, TIPOESTANCIA, TIPOHTX, IDSERVICIOPAQUETE2, VLRSERVICIOPAQ2,  USUARIONOP, FECHANOP, ENHISTORICOS, TLABORADO, TIPOADMINI, CAUSARET, USUIMPSAL, FIMPSALIDA, IDTERCEROREMITE, CIUREMITE, IDEMEDICAREMITE, IDFIRMAPTE, IDFIRMARESP, TIPOAFILIADO,  DIA_ADICIONAL, VALORTTO, NROSESIONES, ESTADIO, COVID, CONSECUTIVOHCA)
SELECT NOADMISION, IDAFILIADO, FECHA, IDSEDE, IDPLAN, IDTERCERO, TIPOADM, HABCAMA, VIAINGRESO, CAUSAEXTERNA, CONDUSUARIA, DXINGRESO, DXEGRESO, COMPLICACION, TIPODISCAP, GRADODISCAP, NOPOLIZA,  NOCARNET, NOAUTORIZACION, FECHAVCEAUT, FECHAALTA, FECHASALIDA, CAUSASALIDA, ESTADOPSALIDA, VRDEPOSITO, RESPCUENTA, ESTADO, URG_NOMBRE, URG_TELE, URG_DIR, IDMEDICOING, IDMEDICOTRA,  CAUSABMUERTE, ENFSOBREAG, OBS, FACTURADA, N_FACTURA, CNSFCT, CERRADA, PCUBRIMIENTO, USUARIO, DXSALIDA1, DXSALIDA2, DXSALIDA3, DESTINO, ESTADOSALIDA, RIPS, NIVELSOCIOEC, TIPOPOLIZA,  IDMEDICOTRA2, IDMEDICOTRA3, ENVIO, FACTURABLE, COPAGO, COPAGONOAUTORIZACION, COPAGOVALOR, TIPOFAC, VFACTURAS, DESCUENTO, TIPODTO, USUARIOALTA, TIPOCREDITO, CREDITO, INDDEVOLUCION,  INDPROCESARDEV, MARCA, ENVIOMARCA, VENCEAUT, MTOPE, TIPOTOPE, FECHATOPE, VALORTOPE, TOPEOTROTERCERO, CONTINUACION, NOADMISIONCONT, FECHATRASHOS, CXP, VLRUTOTRAHADM, IDPROVEEDOR,  TIPOCONT, IDCONTRATO, IDAREA_ALTA, PREADMISION, IDCIRUGIA, PYP, CLASENOPROC, URG_VINCULO, A24H, A2448H, A4872H, A72H30D, CCOSTO_ALTA, FECHAPRE, LIQESTANCIA, FACTURADAPARCIAL,  TIPOCOPAGO, PROCEDENCIA, CNSHACTRAN, DECLARIESGOS, IDMEDICOALTA, CLASEING, PASADACENTRAL, CNSENTREGA, CODUNG, FECHAALTAMED, ITFC, CNSITFC, EMBARAZADA, CNSTRIAGE, TTRIAGE, IDDXULTIMO,  CCOSTOULTIMO, UATENINIURG, ESINSTPROV, ESEINST, FECHAESEINST, MARCAATRASO, REVESPECIALISTA, REFERIDO, IDREFERIDO, MANCOPAGOEXT, NOAUTORIZACIONEXT, VLR_COPAGOEXTERNO, DIASHOSPITALIZACION,  HORASQUIROFANO, TITULARPOLIZA, SINCRONIZADO, NOCOTIZACION, USUALTAMED, IDPLAN_AFI, IDTERCERO_AFI, PAQUETE, TOPECOPAGO_ANX6, TIPOCAJA, CNSFACJ, CODCAJA, USACTC, IDSERVICIOPAQUETE,  VLRSERVICIOPAQ, FECHAALTAENF, IDUSUARIOALTAENF, MDATEXC, NOMBRERESPO, TELEFONORESPO, PARENTESCORESPO, ACTADEFUNCION, TIPOESTANCIA, TIPOHTX, IDSERVICIOPAQUETE2, VLRSERVICIOPAQ2,  USUARIONOP, FECHANOP, ENHISTORICOS, TLABORADO, TIPOADMINI, CAUSARET, USUIMPSAL, FIMPSALIDA, IDTERCEROREMITE, CIUREMITE, IDEMEDICAREMITE, IDFIRMAPTE, IDFIRMARESP, TIPOAFILIADO,  DIA_ADICIONAL, VALORTTO, NROSESIONES, ESTADIO, COVID, CONSECUTIVOHCA
FROM [BDATOS\SQL2017].KCIELD.DBO.HADM HADM
WHERE EXISTS(SELECT  * FROM AFI WHERE HADM.IDAFILIADO COLLATE Modern_Spanish_CI_AS =AFI.IDAFILIADO)
AND NOT EXISTS(SELECT  * FROM HADM X WHERE X.NOADMISION COLLATE Modern_Spanish_CI_AS =HADM.NOADMISION)


WHERE EXISTS(SELECT  * FROM PLN WHERE AFI.IDPLAN COLLATE Modern_Spanish_CI_AS =PLN.IDPLAN )


SELECT * FROM hadm

INSERT INTO PLN(IDPLAN,DESCPLAN)
SELECT '','PLAN DE CONTINGENCIA'


INSERT INTO AFI(IDAFILIADO, PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE, TIPO_DOC, DOCIDAFILIADO, IDALTERNA, IDAFILIADOPPAL, GRUPO_SANG, ESTADO_CIVIL, GRUPOETNICO, SEXO, IDPARENTESCO, LOCALIDAD, DIRECCION,  TELEFONORES, CIUDAD, ZONA, CODENTIDADANTERIOR, ESTADO, FECHAULTESTADO, IDSEDE, IDPROVEEDOR, FNACIMIENTO, FECHAAFILSGSSS, ACT_ECONO, IDESCOLARIDAD, INDCOTIZANTE, ULTIMOANOAPROBADO,  INCAPACIDADLABORAL, TIPODISCAPACIDAD, TIPOAFILIADO, GRUPOATESPECIAL, CABEZADEFAMILIA, ASOCIADO, TIENEOBS, CAMPOUSUARIO1, FECHAUVISITA, CONSANGUINIDAD, IDADMINISTRADORA, IDCAUSAL,  FECHACAUSAL, CLASIFPC, NIVELSOCIOEC, IDPLAN, FECHAAFILIACION, NUMCARNET, CIUDADDOC, IDEMPLEADOR, SEMANASCOT, CARNETIZADO, FECHACARNET, CONSCERTIFICADO, CIUDADNAC, IDOCUPACION,  NACIONALIDAD, CELULAR, DIRECCIONLAB, TELEFONOLAB, CNSAFIAA, SISBENNUMFICHA, SISBENFECHAFICHA, SISBENPUNTAJE, SISBENNUCLEOFAM, SISBENGRUPOB, IDCONTRATO, IDBARRIO, CLASEAFILIACIONARS,  FORMULARIO, EMAIL, NORADICACION, FECHARADICACION, IDTIPOAFILIACION, IDCLASEAFILIACION, V_FORMULARIO, SISBENNIVEL, CNSXCPA, FESTADO, OKBD, USUARIOBD, NACIMIENTO, ITFC, CNSITFC,  TIPOSUBSIDIO, COBERTURA_SALUD, TIPOAFILIADO2, IDAFI_TITULAR, ES_NN, IDESPECIAL, MTRIAGE, FTRIAGE, GRUPOPOB, IDSEDETRIAGE, F_ACTUALIZA, PRIORIDAD, URG_NOMBRE, URG_TELE, URG_DIR,  URG_VINCULO, RAIPOSITIVO, RAIFECHA, RAIUSU, USUARIOATIENDE, OBSERVACION, PORTABILIDAD, FIPORT, FFPORT, CORREGIMIENTO, IDFOTO, IDBARRIO_L, CIUDAD_L, CORREGIMIENTO_L, DIR_PPAL, LAT_DIR,  LNG_DIR, LAT_DIR_L, LNG_DIR_L, CLAVE, PIN, PROCEDENCIA, FECHACTIVACION, REFDIRPRINC, REFDIRLAB, PLANSALUD, USUPRORROGA, FECHAPRORROGA, CLASEPRORROGA, CRONICO, IDPAIS, RUC)
SELECT IDAFILIADO, PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE, TIPO_DOC, DOCIDAFILIADO, IDALTERNA, IDAFILIADOPPAL, GRUPO_SANG, ESTADO_CIVIL, GRUPOETNICO, SEXO, IDPARENTESCO, LOCALIDAD, DIRECCION,  TELEFONORES, CIUDAD, ZONA, CODENTIDADANTERIOR, ESTADO, FECHAULTESTADO, IDSEDE, IDPROVEEDOR, FNACIMIENTO, FECHAAFILSGSSS, ACT_ECONO, IDESCOLARIDAD, INDCOTIZANTE, ULTIMOANOAPROBADO,  INCAPACIDADLABORAL, TIPODISCAPACIDAD, TIPOAFILIADO, GRUPOATESPECIAL, CABEZADEFAMILIA, ASOCIADO, TIENEOBS, CAMPOUSUARIO1, FECHAUVISITA, CONSANGUINIDAD, IDADMINISTRADORA, IDCAUSAL,  FECHACAUSAL, CLASIFPC, NIVELSOCIOEC, IDPLAN, FECHAAFILIACION, NUMCARNET, CIUDADDOC, IDEMPLEADOR, SEMANASCOT, CARNETIZADO, FECHACARNET, CONSCERTIFICADO, CIUDADNAC, IDOCUPACION,  NACIONALIDAD, CELULAR, DIRECCIONLAB, TELEFONOLAB, CNSAFIAA, SISBENNUMFICHA, SISBENFECHAFICHA, SISBENPUNTAJE, SISBENNUCLEOFAM, SISBENGRUPOB, IDCONTRATO, IDBARRIO, CLASEAFILIACIONARS,  FORMULARIO, EMAIL, NORADICACION, FECHARADICACION, IDTIPOAFILIACION, IDCLASEAFILIACION, V_FORMULARIO, SISBENNIVEL, CNSXCPA, FESTADO, OKBD, USUARIOBD, NACIMIENTO, ITFC, CNSITFC,  TIPOSUBSIDIO, COBERTURA_SALUD, TIPOAFILIADO2, IDAFI_TITULAR, ES_NN, IDESPECIAL, MTRIAGE, FTRIAGE, GRUPOPOB, IDSEDETRIAGE, F_ACTUALIZA, PRIORIDAD, URG_NOMBRE, URG_TELE, URG_DIR,  URG_VINCULO, RAIPOSITIVO, RAIFECHA, RAIUSU, USUARIOATIENDE, OBSERVACION, PORTABILIDAD, FIPORT, FFPORT, CORREGIMIENTO, IDFOTO, IDBARRIO_L, CIUDAD_L, CORREGIMIENTO_L, DIR_PPAL, LAT_DIR,  LNG_DIR, LAT_DIR_L, LNG_DIR_L, CLAVE, PIN, PROCEDENCIA, FECHACTIVACION, REFDIRPRINC, REFDIRLAB, PLANSALUD, USUPRORROGA, FECHAPRORROGA, CLASEPRORROGA, CRONICO, IDPAIS, RUC
FROM [BDATOS\SQL2017].KCIELD.DBO.AFI X
WHERE NOT EXISTS(SELECT * FROM  AFI WHERE X.IDAFILIADO COLLATE Modern_Spanish_CI_AS=AFI.IDAFILIADO )

INSERT INTO HHAB(HABCAMA, DESCRIPCION, ESTADOHAB, FECHA, TIPO, NOADMISION, IDAFILIADO, TEMPORAL, CLASE, PISO, SECTOR, HABITACION, CAMA, NIVEL, IDALTERNA, TIPOESTANCIA, IDAREA, CCOSTO, IDSEDE, CODCUPS,  CENTRAL, CLASETRAS, CIERRETURNO, USUARIOMT, MTRASLADO, COSTODIA, EQUIPOATIENDE, USUARIOATIENDE, COLOR, SEXO, HORARIO)
SELECT HABCAMA, DESCRIPCION, ESTADOHAB, FECHA, TIPO, NOADMISION, IDAFILIADO, TEMPORAL, CLASE, PISO, SECTOR, HABITACION, CAMA, NIVEL, IDALTERNA, TIPOESTANCIA, IDAREA, CCOSTO, IDSEDE, CODCUPS,  CENTRAL, CLASETRAS, CIERRETURNO, USUARIOMT, MTRASLADO, COSTODIA, EQUIPOATIENDE, USUARIOATIENDE, COLOR, SEXO, HORARIO
FROM [BDATOS\SQL2017].KCIELD.DBO.HHAB

INSERT INTO HTHA(TIPO, DESCRIPCION, CARACTERISTICAS, CLASE)
SELECT TIPO, DESCRIPCION, CARACTERISTICAS, CLASE
FROM [BDATOS\SQL2017].KCIELD.DBO.HTHA

INSERT INTO HHAB_EST(HABCAMA, ESTADO, FECHA, NOADMISION, EQUIPO)
SELECT HABCAMA, ESTADO, FECHA, NOADMISION, EQUIPO
FROM [BDATOS\SQL2017].KCIELD.DBO.HHAB_EST

INSERT INTO HHABCNF(HABCAMA, TIPOCNF, OPCION, CODIGO, CCOSTO)
SELECT HABCAMA, TIPOCNF, OPCION, CODIGO, CCOSTO
FROM [BDATOS\SQL2017].KCIELD.DBO.HHABCNF

INSERT INTO HBALI(CNSHBALI, NOADMISION, FECHA, TIPO, PESO, TBALANT, TBALING, TBALEGR, PROMGTOURI, OBSERVACIONES, SINAPLI, APLI, NOAPLI)
SELECT CNSHBALI, NOADMISION, FECHA, TIPO, PESO, TBALANT, TBALING, TBALEGR, PROMGTOURI, OBSERVACIONES, SINAPLI, APLI, NOAPLI
FROM [BDATOS\SQL2017].KCIELD.DBO.HBALI

INSERT INTO HBALID(CNSHBALI, NTIPO, NCONSECUTIVO, TIPO, CLASE, IDSERVICIO, H07, H07EST, H08, H08EST, H09, H09EST, H10, H10EST, H11, H11EST, H12, H12EST, H13, H13EST, H14, H14EST, H15, H15EST, H16, H16EST,  H17, H17EST, H18, H18EST, H19, H19EST, H20, H20EST, H21, H21EST, H22, H22EST, H23, H23EST, H00, H00EST, H01, H01EST, H02, H02EST, H03, H03EST, H04, H04EST, H05, H05EST, H06,  H06EST, TOTAL, NOTA, IDSERVICIOMED, EG_IN, CLAMED)
SELECT CNSHBALI, NTIPO, NCONSECUTIVO, TIPO, CLASE, IDSERVICIO, H07, H07EST, H08, H08EST, H09, H09EST, H10, H10EST, H11, H11EST, H12, H12EST, H13, H13EST, H14, H14EST, H15, H15EST, H16, H16EST,  H17, H17EST, H18, H18EST, H19, H19EST, H20, H20EST, H21, H21EST, H22, H22EST, H23, H23EST, H00, H00EST, H01, H01EST, H02, H02EST, H03, H03EST, H04, H04EST, H05, H05EST, H06,  H06EST, TOTAL, NOTA, IDSERVICIOMED, EG_IN, CLAMED
FROM [BDATOS\SQL2017].KCIELD.DBO.HBALID

INSERT INTO HBALIDD(CNSHBALI, NTIPO, NCONSECUTIVO, IDSERVICIO, HORA, IDAPLICA, FECHAAPLICA, FECREG, OBSERVACION, QAPLICADA, MARCA, FECHA, CLASENOAPLICA, F_ULTIMA, CLASEAPLI, CNSIENF)
SELECT CNSHBALI, NTIPO, NCONSECUTIVO, IDSERVICIO, HORA, IDAPLICA, FECHAAPLICA, FECREG, OBSERVACION, QAPLICADA, MARCA, FECHA, CLASENOAPLICA, F_ULTIMA, CLASEAPLI, CNSIENF
FROM [BDATOS\SQL2017].KCIELD.DBO.HBALIDD
WHERE  EXISTS(SELECT  * FROM HBALID WHERE HBALIDD.CNSHBALI COLLATE Modern_Spanish_CI_AS =HBALID.CNSHBALI AND HBALIDD.NCONSECUTIVO=HBALID.NCONSECUTIVO AND HBALIDD.NTIPO=HBALID.NTIPO)

INSERT INTO IENF(TIPO, NOREFERENCIA, CNSMOV, FECHA, IDSERVICIO, IDARTICULO, NOLOTE, EQUICC, PRESUNI, APLICADO, DEVUELTO, DESECHADO, USUARIO, CNSIDEV, ENTREGADO, F_INICIO, CODOM, CONSECUTIVOHCA, COBRADO,  CNSIENF_INI, CLASE)
SELECT TIPO, NOREFERENCIA, CNSMOV, FECHA, IDSERVICIO, IDARTICULO, NOLOTE, EQUICC, PRESUNI, APLICADO, DEVUELTO, DESECHADO, USUARIO, CNSIDEV, ENTREGADO, F_INICIO, CODOM, CONSECUTIVOHCA, COBRADO,  CNSIENF_INI, CLASE
FROM [BDATOS\SQL2017].KCIELD.DBO.IENF

INSERT INTO IENFD(CNSIENF, CNSMOV, FECHA, IDSERVICIO, IDARTICULO, NOLOTE, EQUICC, APLICADO, DEVUELTO, DESECHADO)
SELECT CNSIENF, CNSMOV, FECHA, IDSERVICIO, IDARTICULO, NOLOTE, EQUICC, APLICADO, DEVUELTO, DESECHADO
FROM [BDATOS\SQL2017].KCIELD.DBO.IENFD IENFD
WHERE  EXISTS(SELECT  * FROM IENF WHERE IENF.CNSIENF=IENFD.CNSIENF)


INSERT INTO HBALINI(CNSHBALINI, NOADMISION, CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, ESTADO, FECHA, USUASIGNA, FASIGNA)
SELECT CNSHBALINI, NOADMISION, CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, ESTADO, FECHA, USUASIGNA, FASIGNA
FROM [BDATOS\SQL2017].KCIELD.DBO.HBALINI

INSERT INTO IZSOLD(CNSIZSOLD, CNSIZSOL, IDARTICULO, CANTIDADSOL, ESTADO, CODOM, CANTIDAD, FRECUENCIA, NUMDOSIS, CANTIDADBOLO, QIMPREGNACION, DURACION, IDSERVICIO, TIPOENT, CNSHBALI, TIPOM, IDPRINCIPIO,  COBRADODY, APROVADOENF, CANT_APRO, BSCAPACIDAD, OBSERVACION, OPTI, CNSFMED)
SELECT CNSIZSOLD, CNSIZSOL, IDARTICULO, CANTIDADSOL, ESTADO, CODOM, CANTIDAD, FRECUENCIA, NUMDOSIS, CANTIDADBOLO, QIMPREGNACION, DURACION, IDSERVICIO, TIPOENT, CNSHBALI, TIPOM, IDPRINCIPIO,  COBRADODY, APROVADOENF, CANT_APRO, BSCAPACIDAD, OBSERVACION, OPTI, CNSFMED
FROM [BDATOS\SQL2017].KCIELD.DBO.IZSOLD
WHERE EXISTS(SELECT * FROM IZSOL WHERE IZSOL.CNSIZSOL COLLATE SQL_1xCompat_CP850_CI_AS =IZSOLD.CNSIZSOL)

INSERT INTO IZSOLDT(CNSIZSOLDT, CNSIZSOLD, IDARTICULO, CANTIDADSOL, ESTADO, NOLOTE, IDARTICULOREAL, CNSMOV, COBRADOINS, LIBERADO, BSCAPACIDAD)
SELECT  CNSIZSOLDT, CNSIZSOLD, IDARTICULO, CANTIDADSOL, ESTADO, NOLOTE, IDARTICULOREAL, CNSMOV, COBRADOINS, LIBERADO, BSCAPACIDAD
FROM [BDATOS\SQL2017].KCIELD.DBO.IZSOLDT
WHERE EXISTS(SELECT * FROM IZSOLD WHERE IZSOLD.CNSIZSOLD COLLATE SQL_1xCompat_CP850_CI_AS =IZSOLDT.CNSIZSOLD)

SELECT  MIN(FECHA) FROM HBALI 

SELECT DISTINCT CNSHBALI FROM HBALI  WHERE FECHA<='01/01/20216'

INSERT INTO USLOG(CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName, TABLA)
SELECT CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_ComputerName, TABLA
FROM [BDATOS\SQL2017].KCIELD.DBO.USLOG

INSERT INTO USLOGH(CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO)
SELECT CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO
FROM [BDATOS\SQL2017].KCIELD.DBO.USLOGH


INSERT INTO PXS(IDSEDE, IDPLAN, PREFIJO, PRIORIDAD, IDTERCERO, UMBRAL, EXCOBROPC, IDADMINISTRADORA, LIQUIDARPC, COBRARPC, TIPOTARIFA, IDTARIFA, FACTOR)
SELECT IDSEDE, IDPLAN, PREFIJO, PRIORIDAD, IDTERCERO, UMBRAL, EXCOBROPC, IDADMINISTRADORA, LIQUIDARPC, COBRARPC, TIPOTARIFA, IDTARIFA, FACTOR
FROM [BDATOS\SQL2017].KCIELD.DBO.PXS

INSERT INTO PXSE(IDTERCERO, IDADMINISTRADORA, IDPLAN, IDSEDE, PREFIJO, IDSERVICIO, TIPORESTRICCION, IDTARIFA, FACTOR, VALOR)
SELECT  IDTERCERO, IDADMINISTRADORA, IDPLAN, IDSEDE, PREFIJO, IDSERVICIO, TIPORESTRICCION, IDTARIFA, FACTOR, VALOR
FROM [BDATOS\SQL2017].KCIELD.DBO.PXSE

INSERT INTO PXSN(IDTERCERO, IDADMINISTRADORA, IDPLAN, IDTARIFA, FACTOR, IDCONTRATO, NIVELATENCION, TIPOCONTRATO, TIPORECOBRO)
SELECT IDTERCERO, IDADMINISTRADORA, IDPLAN, IDTARIFA, FACTOR, IDCONTRATO, NIVELATENCION, TIPOCONTRATO, TIPORECOBRO
FROM [BDATOS\SQL2017].KCIELD.DBO.PXSN

INSERT INTO SED(IDSEDE, DESCRIPCION, DIRECCION, TELEFONOS, CIUDAD, IDREGIONAL, RESPONSABLE, MONTO_MAX, MONTO_MIN, MONTO_REE, NIT, DV, REPRESENTANTELEGAL, TIPO_DOC, NITREP, IDMODELODSS, IDTARIFA, NIVELSEDE,  NIVELVISTA, CATEGORIA, ATIENDEOTRASSEDES, LOGO, LINEA, LINEA2, LINEA3, GRANCONT1, GRANCONT2, LEGAL, LEGAL2, LEGAL3, LEGAL4, CODUNG, CODPRG, HOMOLOGO, TERCERIZADA, IDBODEGALOG,  IDBODEGACM, IDBODEGA24H, CODHABILITA, IDBODHEMO, IDSGSSS, IPS)
SELECT IDSEDE, DESCRIPCION, DIRECCION, TELEFONOS, CIUDAD, IDREGIONAL, RESPONSABLE, MONTO_MAX, MONTO_MIN, MONTO_REE, NIT, DV, REPRESENTANTELEGAL, TIPO_DOC, NITREP, IDMODELODSS, IDTARIFA, NIVELSEDE,  NIVELVISTA, CATEGORIA, ATIENDEOTRASSEDES, LOGO, LINEA, LINEA2, LINEA3, GRANCONT1, GRANCONT2, LEGAL, LEGAL2, LEGAL3, LEGAL4, CODUNG, CODPRG, HOMOLOGO, TERCERIZADA, IDBODEGALOG,  IDBODEGACM, IDBODEGA24H, CODHABILITA, IDBODHEMO, IDSGSSS, IPS
FROM [BDATOS\SQL2017].KCIELD.DBO.SED

INSERT INTO MDS(IDMODELODSS, DESCMODELODSS, NOCITAS, NOCITASINC)
SELECT IDMODELODSS, DESCMODELODSS, NOCITAS, NOCITASINC
FROM [BDATOS\SQL2017].KCIELD.DBO.MDS

INSERT INTO LING(NOINGRESO, TIPOINGRESO, IDAFILIADO, IDTERCERO, IDPLAN, FECHA, NOADMISION, NOPRESTACION, FINALIDAD, AMBITO, PERSONAL_AT, IDMEDICO, COBRARA, IDTERCEROCA, IMPRESO, ESTADO, RECIBE, IDRECIBE,  NOMRECIBE, FALTAENTREGA, CONSECUTIVOHCA, AMBITOTR, USUARIO, FECHA_PRES, CCOSTO, IDAREA, INTERFACE, MARCA, SYS_COMPUTERNAME_MARCA, DOCUMENTOID)
SELECT NOINGRESO, TIPOINGRESO, IDAFILIADO, IDTERCERO, IDPLAN, FECHA, NOADMISION, NOPRESTACION, FINALIDAD, AMBITO, PERSONAL_AT, IDMEDICO, COBRARA, IDTERCEROCA, IMPRESO, ESTADO, RECIBE, IDRECIBE,  NOMRECIBE, FALTAENTREGA, CONSECUTIVOHCA, AMBITOTR, USUARIO, FECHA_PRES, CCOSTO, IDAREA, INTERFACE, MARCA, SYS_COMPUTERNAME_MARCA, DOCUMENTOID
FROM [BDATOS\SQL2017].KCIELD.DBO.LING

INSERT INTO LORD(NORDEN, NOINGRESO, IDSERVICIO, FECHA, ESTADO, CNSTRA, IMPRESO, RECIBE, IDRECIBE, NOMRECIBE, PEDIDOINV, NOITEM, CONSECUTIVOHCA, ITEMRED, CODOM, REALIZADO, LISTOENTREGA, ENTREGADO, OBSERVACION,  FECHARES, USUARIORES, RESPMUESTRA, FECHAMUESTRA, MUESTRA, IDMEDICO, OPORTUNIDAD, RESULTADO, CONCLUSION, MARCA, SYS_COMPUTERNAME_MARCA, NUM_ORDEN, SERIAL, FENTREGA, QUIENRECIBE,  USUENTREGA, SELLOCALIDAD, CNSIZSOLDT, USULIBERA, USUARIOTRAE)
SELECT NORDEN, NOINGRESO, IDSERVICIO, FECHA, ESTADO, CNSTRA, IMPRESO, RECIBE, IDRECIBE, NOMRECIBE, PEDIDOINV, NOITEM, CONSECUTIVOHCA, ITEMRED, CODOM, REALIZADO, LISTOENTREGA, ENTREGADO, OBSERVACION,  FECHARES, USUARIORES, RESPMUESTRA, FECHAMUESTRA, MUESTRA, IDMEDICO, OPORTUNIDAD, RESULTADO, CONCLUSION, MARCA, SYS_COMPUTERNAME_MARCA, NUM_ORDEN, SERIAL, FENTREGA, QUIENRECIBE,  USUENTREGA, SELLOCALIDAD, CNSIZSOLDT, USULIBERA, USUARIOTRAE
FROM [BDATOS\SQL2017].KCIELD.DBO.LORD

INSERT INTO LORDD(NORDEN, NOITEM, IDDATO, MEMO, ALFANUMERICO, FECHA, OBS, IDSERVICIO, TIPOCAMPO, SEXO, TIPORANGO, RANGOINI, RANGOFIN, MINIMO, MAXIMO, NOTA, IDIMG, VR_MINIMO, VR_MAXIMO, UNIDADES, COD_ANALITO,  SERIE, URL_VISOR)
SELECT NORDEN, NOITEM, IDDATO, MEMO, ALFANUMERICO, FECHA, OBS, IDSERVICIO, TIPOCAMPO, SEXO, TIPORANGO, RANGOINI, RANGOFIN, MINIMO, MAXIMO, NOTA, IDIMG, VR_MINIMO, VR_MAXIMO, UNIDADES, COD_ANALITO,  SERIE, URL_VISOR
FROM [BDATOS\SQL2017].KCIELD.DBO.LORDD
WHERE EXISTS(SELECT  * FROM LORD WHERE LORD.NORDEN COLLATE SQL_1xCompat_CP850_CI_AS =LORDD.NORDEN)

INSERT INTO LORDDM(NORDEN, IDDATO, NOITEM, OPCION, MULTICHECK, OBS, SEXO, TIPORANGO, RANGOINI, RANGOFIN, MINIMO, MAXIMO, NOTA)
SELECT NORDEN, IDDATO, NOITEM, OPCION, MULTICHECK, OBS, SEXO, TIPORANGO, RANGOINI, RANGOFIN, MINIMO, MAXIMO, NOTA
FROM [BDATOS\SQL2017].KCIELD.DBO.LORDDM
WHERE EXISTS(SELECT  * FROM LORD WHERE LORD.NORDEN COLLATE SQL_1xCompat_CP850_CI_AS =LORDDM.NORDEN)

INSERT INTO  LDAT(IDDATO, DESCRIPCION, IDCONCENTRA, TIPOCAMPO, CONVALOR, ALTURACAMPO)
SELECT IDDATO, DESCRIPCION, IDCONCENTRA, TIPOCAMPO, CONVALOR, ALTURACAMPO
FROM [BDATOS\SQL2017].KCIELD.DBO.LDAT 

INSERT  LDATD(IDDATO, OPCION, CONVALOR, TIPO, VALOR)
SELECT IDDATO, OPCION, CONVALOR, TIPO, VALOR
FROM [BDATOS\SQL2017].KCIELD.DBO.LDATD


INSERT INTO CUE(COMPANIA, CUENTA, NOMCUENTA, TIPO, NEMONICO, CENTRO, PRODUCTO, REFERENCIA, TERCERO, RETENCION, CPTORETENCION, AJUSTE, CIERRE, CUENTAFISCAL, IMPUESTO, ESTADO, NIVEL, CUENTA_SUMA, CLASE,  RUBRO, TIPOTESORERO, BANCO, SUCURSAL, CTA_BCO, CODCAJA, DETALLEXTERCERO, RESPONSABLE, CUENTA_HOMOLOGA, CUENTANIIF, ESEXOGENA, FORMATO1001, FORMATO1011, CONCEPTOEXO, FORMATOEXO,  NODEDUCIBLE, ASUMIDA_PRACTICADA, CTACIERRECOSTOS, CTACREDITOCOSTOS, CORRIENTE, CUEESPEJO, RUBRO_ID, CONCEPTO_ACREENCIA)
SELECT COMPANIA, CUENTA, NOMCUENTA, TIPO, NEMONICO, CENTRO, PRODUCTO, REFERENCIA, TERCERO, RETENCION, CPTORETENCION, AJUSTE, CIERRE, CUENTAFISCAL, IMPUESTO, ESTADO, NIVEL, CUENTA_SUMA, CLASE,  RUBRO, TIPOTESORERO, BANCO, SUCURSAL, CTA_BCO, CODCAJA, DETALLEXTERCERO, RESPONSABLE, CUENTA_HOMOLOGA, CUENTANIIF, ESEXOGENA, FORMATO1001, FORMATO1011, CONCEPTOEXO, FORMATOEXO,  NODEDUCIBLE, ASUMIDA_PRACTICADA, CTACIERRECOSTOS, CTACREDITOCOSTOS, CORRIENTE, CUEESPEJO, RUBRO_ID, CONCEPTO_ACREENCIA
FROM [BDATOS\SQL2017].KCIELD.DBO.CUE

INSERT INTO CUENIIF(CUENTA, NOMCUENTA, TIPO, NEMONICO, CENTRO, PRODUCTO, REFERENCIA, TERCERO, IMPUESTO, ESTADO, NIVEL, CUENTA_SUMA, CLASE, CORRIENTE)
SELECT CUENTA, NOMCUENTA, TIPO, NEMONICO, CENTRO, PRODUCTO, REFERENCIA, TERCERO, IMPUESTO, ESTADO, NIVEL, CUENTA_SUMA, CLASE, CORRIENTE
FROM [BDATOS\SQL2017].KCIELD.DBO.CUENIIF

INSERT INTO TTEC(TIPO, DETALLE, CUENTA, TIPOMOV, CUEORDENGLOSADB, CUEORDENGLOSACR, CTAGLOSADB, CUENTARAD, CUENTALG, CUENTACG, CXC_ESTIMADA, PASIVO_EST, CREEDB, CREECR, INGRESOEST, CUEDIFCOB, CUECOJURI,  TASEGU)
SELECT TIPO, DETALLE, CUENTA, TIPOMOV, CUEORDENGLOSADB, CUEORDENGLOSACR, CTAGLOSADB, CUENTARAD, CUENTALG, CUENTACG, CXC_ESTIMADA, PASIVO_EST, CREEDB, CREECR, INGRESOEST, CUEDIFCOB, CUECOJURI,  TASEGU
FROM [BDATOS\SQL2017].KCIELD.DBO.TTEC

INSERT INTO USVGS(IDVARIABLE, DESCRIPCION, TP_VARIABLE, DATO, INDVIGENCIA, OBSERVACION, TABLA, CAMPO_CODIGO, CAMPO_DESC, MDATOOBS)
SELECT IDVARIABLE, DESCRIPCION, TP_VARIABLE, DATO, INDVIGENCIA, OBSERVACION, TABLA, CAMPO_CODIGO, CAMPO_DESC, MDATOOBS
FROM [BDATOS\SQL2017].KCIELD.DBO.USVGS

INSERT INTO COM(COMPANIA, COMPROBANTE, NOMCOMPROBANTE, COM_EXT, HOMOLOGO)
SELECT COMPANIA, COMPROBANTE, NOMCOMPROBANTE, COM_EXT, HOMOLOGO
FROM [BDATOS\SQL2017].KCIELD.DBO.COM

INSERT INTO COMMS(IDSEDE, CLASE, TIPO, COMPROBANTE, NOMCOMPROBANTE, COM_EXT, HOMOLOGO)
SELECT IDSEDE, CLASE, TIPO, COMPROBANTE, NOMCOMPROBANTE, COM_EXT, HOMOLOGO
FROM [BDATOS\SQL2017].KCIELD.DBO.COMMS

INSERT INTO PRI(COMPANIA, ANO, MES, NOMPERIODO, FECHA_INI, CERRADO, FECHA_FIN, AJUSTADO, PAAG, COMPROBANTE, DOCUMENTO, NROCOMPROBANTE, TIPO_AJ, CERRADO_INV, NROCOMPROBANTE_AJI, COMPROBANTE_AJI, NOREFERENCIA_AJI,  CERRADO_CARTERA, DESALDOSINICIALES, CERRADO_FAC, SI, CIERREFISCAL, EJERCICIOMES, BDATOS, CIERRECOSTOS, CIERREIMP, CERRADO_PPTO, CERRADONIIF, DETCARTERANIIF, DETINVENTARIONIIF,  COMP_DETCARTERA, COMP_DETINVENTARIO, SINIIF, MCIERRECOSTOS, NROCOMTRASCOSTO, CIERRE_TRASCOSTOS, CERRADO_CXP, CIEFISNIIF, TCAMBIOFINAL, KARDEXHISTO)
SELECT COMPANIA, ANO, MES, NOMPERIODO, FECHA_INI, CERRADO, FECHA_FIN, AJUSTADO, PAAG, COMPROBANTE, DOCUMENTO, NROCOMPROBANTE, TIPO_AJ, CERRADO_INV, NROCOMPROBANTE_AJI, COMPROBANTE_AJI, NOREFERENCIA_AJI,  CERRADO_CARTERA, DESALDOSINICIALES, CERRADO_FAC, SI, CIERREFISCAL, EJERCICIOMES, BDATOS, CIERRECOSTOS, CIERREIMP, CERRADO_PPTO, CERRADONIIF, DETCARTERANIIF, DETINVENTARIONIIF,  COMP_DETCARTERA, COMP_DETINVENTARIO, SINIIF, MCIERRECOSTOS, NROCOMTRASCOSTO, CIERRE_TRASCOSTOS, CERRADO_CXP, CIEFISNIIF, TCAMBIOFINAL, KARDEXHISTO
FROM [BDATOS\SQL2017].KCIELD.DBO.PRI

INSERT INTO MND(IDMONEDA, DESCRIPCION, SIMBOLO, CODIFICACION)
SELECT IDMONEDA, DESCRIPCION, SIMBOLO, CODIFICACION
FROM [BDATOS\SQL2017].KCIELD.DBO.MND

INSERT INTO MNDV(IDMONEDA, ITEM, FECHA, VALOR)
SELECT IDMONEDA, ITEM, FECHA, VALOR
FROM [BDATOS\SQL2017].KCIELD.DBO.MNDV
--SELECT  * FROM FIMPD
--DELETE FIMPDV
INSERT INTO FIMP(IDIMPUESTO, DESCRIPCION, TIPO, HOMOLOGODIAN)
SELECT IDIMPUESTO, DESCRIPCION, TIPO, HOMOLOGODIAN
FROM [BDATOS\SQL2017].KCIELD.DBO.FIMP

INSERT INTO FIMPDV(IDIMPUESTO, IDCLASE, ITEM, VALOR, FECHAINI, FECHAFIN, VALOR_INICIAL, VALOR_FINAL, CUENTA, CUENTA_ASUM, MUVT, VLRUTV)
SELECT IDIMPUESTO, IDCLASE, ITEM, VALOR, FECHAINI, FECHAFIN, VALOR_INICIAL, VALOR_FINAL, CUENTA, CUENTA_ASUM, MUVT, VLRUTV
FROM [BDATOS\SQL2017].KCIELD.DBO.FIMPDV

INSERT INTO FCTSER(IDTIPOSER, CUENTA, DESCRIPCION, IDGRUPOIMP, DECONSUMO, RUBRO, RUBRO_ID)
SELECT IDTIPOSER, CUENTA, DESCRIPCION, IDGRUPOIMP, DECONSUMO, RUBRO, RUBRO_ID
FROM [BDATOS\SQL2017].KCIELD.DBO.FCTSER

INSERT INTO FCTSERD(IDSERVICIO, IDTIPOSER, DESCRIPCION, ENBRIGADA, CLASECOBRO, VALOR)
SELECT IDSERVICIO, IDTIPOSER, DESCRIPCION, ENBRIGADA, CLASECOBRO, VALOR
FROM [BDATOS\SQL2017].KCIELD.DBO.FCTSERD

INSERT INTO FDEP(COMPANIA, IDDEP, NOMBRE, CCOSTO, SUBCCOSTO, TIPO, CIUDAD, RESPONSABLE)
SELECT COMPANIA, IDDEP, NOMBRE, CCOSTO, SUBCCOSTO, TIPO, CIUDAD, RESPONSABLE
FROM [BDATOS\SQL2017].KCIELD.DBO.FDEP

INSERT INTO PAR(COMPANIA, CTA_CAJ_REC_NOLEG, MCUEORDEN_GLOSAS, MCUEORDEN_CXC, MCUEORDEN_CXP, MCUEORDEN_INGRESOS, MCUEORDEN_EGRESOS, MESDECIERRE, CIERRECOSTOS, CIERREIMP)
SELECT COMPANIA, CTA_CAJ_REC_NOLEG, MCUEORDEN_GLOSAS, MCUEORDEN_CXC, MCUEORDEN_CXP, MCUEORDEN_INGRESOS, MCUEORDEN_EGRESOS, MESDECIERRE, CIERRECOSTOS, CIERREIMP
FROM [BDATOS\SQL2017].KCIELD.DBO.PAR

--

INSERT INTO CAJ(CODCAJA, DESCRIPCION, TIPO, CLASE, FOFI, FECHACREACION, ESTADO, ABIERTA, CNSACJ, INVTIPOMOV, IDBODEGA, INVTIPODOCU, CUENTA, RECIBETRASLADO, ACEPTARECAUDO, MAXPAGOCM, CUENTACXP_CM, COMPROBANTE_CM,  TIPOEGRESO, RESPONSABLE, ANTICIPOS, COMPROBANTE_ANT, CUENTA_ANT, REEMBOLSO)
SELECT CODCAJA, DESCRIPCION, TIPO, CLASE, FOFI, FECHACREACION, ESTADO, ABIERTA, CNSACJ, INVTIPOMOV, IDBODEGA, INVTIPODOCU, CUENTA, RECIBETRASLADO, ACEPTARECAUDO, MAXPAGOCM, CUENTACXP_CM, COMPROBANTE_CM,  TIPOEGRESO, RESPONSABLE, ANTICIPOS, COMPROBANTE_ANT, CUENTA_ANT, REEMBOLSO
FROM [BDATOS\SQL2017].KCIELD.DBO.CAJ

INSERT INTO TUR(CODTURNO, DESCRIPCION, FECHAINICIAL, FECHAFINAL, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, FESTIVO, ESTADO, DIASIGUIENTE, CLASE, HDIA, HNOCHE, HDIAFIN, HNOCHEFIN)
SELECT CODTURNO, DESCRIPCION, FECHAINICIAL, FECHAFINAL, LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO, FESTIVO, ESTADO, DIASIGUIENTE, CLASE, HDIA, HNOCHE, HDIAFIN, HNOCHEFIN
FROM [BDATOS\SQL2017].KCIELD.DBO.TUR 

INSERT INTO CJR(CODCAJERO, DESCRIPCION, CLASE, FECHACREACION, ESTADO)
SELECT CODCAJERO, DESCRIPCION, CLASE, FECHACREACION, ESTADO
FROM [BDATOS\SQL2017].KCIELD.DBO.CJR

INSERT INTO CPCJ(CODIGO, DESCRIPCION, CUENTA, TIPO, TIPORECIBO, UNICO, COMPROBANTE, GENERAFACTURA, PIDEIMPTO, ESTADO, DECAJAMENOR, HOMOLOGODIAN)
SELECT CODIGO, DESCRIPCION, CUENTA, TIPO, TIPORECIBO, UNICO, COMPROBANTE, GENERAFACTURA, PIDEIMPTO, ESTADO, DECAJAMENOR, HOMOLOGODIAN
FROM [BDATOS\SQL2017].KCIELD.DBO.CPCJ

INSERT INTO CXT(CODCAJA, CODTURNO, CODCAJERO)
SELECT CODCAJA, CODTURNO, CODCAJERO
FROM [BDATOS\SQL2017].KCIELD.DBO.CXT


INSERT INTO CJTE(TIPOEGRESO, DESCRIPCION, GENCPAUT, CODIGO, MTERCERO, IDCATEGORIA, CUENTA, COMPROBANTE)
SELECT TIPOEGRESO, DESCRIPCION, GENCPAUT, CODIGO, MTERCERO, IDCATEGORIA, CUENTA, COMPROBANTE
FROM [BDATOS\SQL2017].KCIELD.DBO.CJTE

INSERT INTO BCO(BANCO, DESCRIPCION, CODACH, IDTERCERO)
SELECT BANCO, DESCRIPCION, CODACH, IDTERCERO
FROM [BDATOS\SQL2017].KCIELD.DBO.BCO 

INSERT INTO BSU(BANCO, SUCURSAL, DESCRIPCION, DIRECCION, TELEFONO1, TELEFONO2, FAX, CONTACTO, CARGO)
SELECT BANCO, SUCURSAL, DESCRIPCION, DIRECCION, TELEFONO1, TELEFONO2, FAX, CONTACTO, CARGO
FROM [BDATOS\SQL2017].KCIELD.DBO.BSU

INSERT INTO FPA(FORMAPAGO, DESCRIPCION, FISICO, REQBCO, REQDOC, REQAUT, CXC, AUTINT, MEDIOPAGO, TEDEVOLUCION, CUENTA, CEROENAPERTURA, USAR_CUENTACAJA, REQCTA_BCO_DEP, GENCHEQUE, COMPROBANTE_EGR, DATAFONO )
SELECT FORMAPAGO, DESCRIPCION, FISICO, REQBCO, REQDOC, REQAUT, CXC, AUTINT, MEDIOPAGO, TEDEVOLUCION, CUENTA, CEROENAPERTURA, USAR_CUENTACAJA, REQCTA_BCO_DEP, GENCHEQUE, COMPROBANTE_EGR, DATAFONO 
FROM [BDATOS\SQL2017].KCIELD.DBO.FPA

INSERT INTO CPNT(CODIGO, DESCRIPCION, CUENTA, MODULO, TIPORESPUESTA, HOMOLOGODIANDB, HOMOLOGODIANCR)
SELECT CODIGO, DESCRIPCION, CUENTA, MODULO, TIPORESPUESTA, HOMOLOGODIANDB, HOMOLOGODIANCR
FROM [BDATOS\SQL2017].KCIELD.DBO.CPNT

INSERT INTO FNT(IDNOTA, DESCRIPCION, TIPO, COMPROBANTE, CUENTA, DECRUCES, AFCOSTO, HOMOLOGODIAN)
SELECT IDNOTA, DESCRIPCION, TIPO, COMPROBANTE, CUENTA, DECRUCES, AFCOSTO, HOMOLOGODIAN
FROM [BDATOS\SQL2017].KCIELD.DBO.FNT

INSERT INTO FUSU(IDFUNCIONARIO, PNOMBRE, SNOMBRE, PAPELLIDO, SAPELLIDO, USUARIO, COMPANIA, TIPO, CIUDAD)
SELECT IDFUNCIONARIO, PNOMBRE, SNOMBRE, PAPELLIDO, SAPELLIDO, USUARIO, COMPANIA, TIPO, CIUDAD
FROM [BDATOS\SQL2017].KCIELD.DBO.FUSU


INSERT INTO FDIAN(CNSRESOL, F_RESOLUCION, CNSINICIAL, CNSFINAL, DESCRIPCION, FECHAVEN, TIPO, IDENTIFICADOR, TITULO, VENCIDA, PREFIJO, FECHAINI, CLAVETECNICA, CNSACTUAL, FTRELECTRONICA, LONGFTR, AMBIENTE,  TIPO_OPERACION, TIPO_DOCUMENTO, PROCEDENCIA)
SELECT CNSRESOL, F_RESOLUCION, CNSINICIAL, CNSFINAL, DESCRIPCION, FECHAVEN, TIPO, IDENTIFICADOR, TITULO, VENCIDA, PREFIJO, FECHAINI, CLAVETECNICA, CNSACTUAL, FTRELECTRONICA, LONGFTR, AMBIENTE,  TIPO_OPERACION, TIPO_DOCUMENTO, PROCEDENCIA
FROM [BDATOS\SQL2017].KCIELD.DBO.FDIAN

INSERT INTO ACJ(CNSACJ, CODCAJA, CODTURNO, ITEM, CODCAJERO, FECHAAPERTURA, FECHACIERRE, ABIERTA, SALDOINICIAL, SALDOFINAL)
SELECT CNSACJ, CODCAJA, CODTURNO, ITEM, CODCAJERO, FECHAAPERTURA, FECHACIERRE, ABIERTA, SALDOINICIAL, SALDOFINAL
FROM [BDATOS\SQL2017].KCIELD.DBO.ACJ

INSERT INTO ACJD(CNSACJ, FORMAPAGO, TIPO, SALDO, CODCAJERO)
SELECT CNSACJ, FORMAPAGO, TIPO, SALDO, CODCAJERO
FROM [BDATOS\SQL2017].KCIELD.DBO.ACJD


INSERT INTO FCJ(CNSFACJ, N_RECIBO, CODCAJA, CODTURNO_GEN, CODTURNO_TRA, CLASE_FAC, NOADMISION, NOPRESTACION, IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO, CERRADA, FECHA, PROCEDENCIA, N_FACTURA, IDTERCERO,  NOMBRECLIENTE, CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO, SUBCCOSTO, CLASER, IDCAUSALANUL, USUARIOANUL, SYS_COMPUTERNAMEANUL,  FECHAANU, TCNSFACJ, IDENTIFICADOR, SYS_ComputerName, OBSERVACION, RECAUDO, ENPAGOS, TIPOEGRESO, IMPRESOTRAS, BANCO, SUCURSAL, CTA_BCO, USUARIO, DEAPERTURA, IMPRESOCHEQUE, DOCORIGEN,  VLRLEGALIZADO, CODUNG, CODPRG, ENPRESUPUESTO, ARCHIVADO, DEVUELTO, DETALLEANULACION, CNSCMREE, ESPART, USUARIOLOG, GEN_DEVOLUCION, TIPOCAJA_DEV, CODCAJA_DEV, CNSFACJ_DEV,  CLASENVA, SUBCLASENVA, ESNVA, TIPO_DOC, GCXC, PPTO, CNSRECO, ENTREGADO, RNOMI, CNSRESOL, IDKPAGE, USURECAUDO, FECHAPAGO, CONCEPTO, MOTORIZADO, FECHACONFIRMA, FECHAAPRUEBA, FECHATFCJ,  DEUDACONFIRMADO, PAGOCONFIRMADO)
SELECT CNSFACJ, N_RECIBO, CODCAJA, CODTURNO_GEN, CODTURNO_TRA, CLASE_FAC, NOADMISION, NOPRESTACION, IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO, CERRADA, FECHA, PROCEDENCIA, N_FACTURA, IDTERCERO,  NOMBRECLIENTE, CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO, SUBCCOSTO, CLASER, IDCAUSALANUL, USUARIOANUL, SYS_COMPUTERNAMEANUL,  FECHAANU, TCNSFACJ, IDENTIFICADOR, SYS_ComputerName, OBSERVACION, RECAUDO, ENPAGOS, TIPOEGRESO, IMPRESOTRAS, BANCO, SUCURSAL, CTA_BCO, USUARIO, DEAPERTURA, IMPRESOCHEQUE, DOCORIGEN,  VLRLEGALIZADO, CODUNG, CODPRG, ENPRESUPUESTO, ARCHIVADO, DEVUELTO, DETALLEANULACION, CNSCMREE, ESPART, USUARIOLOG, GEN_DEVOLUCION, TIPOCAJA_DEV, CODCAJA_DEV, CNSFACJ_DEV,  CLASENVA, SUBCLASENVA, ESNVA, TIPO_DOC, GCXC, PPTO, CNSRECO, ENTREGADO, RNOMI, CNSRESOL, IDKPAGE, USURECAUDO, FECHAPAGO, CONCEPTO, MOTORIZADO, FECHACONFIRMA, FECHAAPRUEBA, FECHATFCJ,  DEUDACONFIRMADO, PAGOCONFIRMADO
FROM [BDATOS\SQL2017].KCIELD.DBO.FCJ

INSERT INTO FCJD(CODCAJA, N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO, PCOSTOUNIT, ESIMPTOGEN, CUENTACM,  CCOSTO, IDAREA, IDTERCERO, UNSPSC)
SELECT CODCAJA, N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO, PCOSTOUNIT, ESIMPTOGEN, CUENTACM,  CCOSTO, IDAREA, IDTERCERO, UNSPSC
FROM [BDATOS\SQL2017].KCIELD.DBO.FCJD

INSERT INTO FCJDD(CODCAJA, CNSFACJ, ITEM, RENGLON, PREFIJO, AREAFUNCIONAL, CCOSTO, N_RECIBO, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
SELECT CODCAJA, CNSFACJ, ITEM, RENGLON, PREFIJO, AREAFUNCIONAL, CCOSTO, N_RECIBO, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO
FROM [BDATOS\SQL2017].KCIELD.DBO.FCJDD

INSERT INTO PCJ(CODCAJA, CNSPCJ, CNSFACJ, TIPOPAGO, VALOR, BANCO, SUCURSAL, CTA_BCO, CNSDOC, NUMERODOCUMENTO, NUMEROAUTORIZA, FECHA, CNSACJ, IDTERCERO, IMPRESO, CODCAJADEP, CNSFACJDEP, DOCORIGEN, BANCO_DEP,  CTA_BCO_DEP, CUENTA, VLR_DEVUELTO, VARIOS, TRASLADADO, TRASLADO_CNSFACJ, VALORREINTEGRO, POSFECHADO, FECHAPOST, CNSCXC, N_FACTURA)
SELECT CODCAJA, CNSPCJ, CNSFACJ, TIPOPAGO, VALOR, BANCO, SUCURSAL, CTA_BCO, CNSDOC, NUMERODOCUMENTO, NUMEROAUTORIZA, FECHA, CNSACJ, IDTERCERO, IMPRESO, CODCAJADEP, CNSFACJDEP, DOCORIGEN, BANCO_DEP,  CTA_BCO_DEP, CUENTA, VLR_DEVUELTO, VARIOS, TRASLADADO, TRASLADO_CNSFACJ, VALORREINTEGRO, POSFECHADO, FECHAPOST, CNSCXC, N_FACTURA
FROM [BDATOS\SQL2017].KCIELD.DBO.PCJ

INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION, IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO, CERRADA, FECHA, PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE, CNSACJ, TIPO, ESTADO,  IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO, SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_ComputerName, OBSERVACION, TIPO_DOC, IDKPAGE, USURECAUDO,  VLRPENDIENTE, DEUDA, REVISANDO, FECHACONFIRMADO)
SELECT CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION, IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO, CERRADA, FECHA, PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE, CNSACJ, TIPO, ESTADO,  IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO, SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_ComputerName, OBSERVACION, TIPO_DOC, IDKPAGE, USURECAUDO,  VLRPENDIENTE, DEUDA, REVISANDO, FECHACONFIRMADO
FROM [BDATOS\SQL2017].KCIELD.DBO.TFCJ

INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO, CONSECUTIVO)
SELECT N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO, CONSECUTIVO
FROM [BDATOS\SQL2017].KCIELD.DBO.TFCJD

INSERT INTO TFCJDD(CNSFACJ, ITEM, RENGLON, CODCAJA, PREFIJO, AREAFUNCIONAL, CCOSTO, N_RECIBO, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
SELECT CNSFACJ, ITEM, RENGLON, CODCAJA, PREFIJO, AREAFUNCIONAL, CCOSTO, N_RECIBO, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO, TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO
FROM [BDATOS\SQL2017].KCIELD.DBO.TFCJDD

INSERT INTO FCJPCXC(CNSFACJ, CODCAJA, CNSCXC, N_FACTURA, ITEM_FCXCDV, IDTERCERO, VALOR, ESTADO, CNSFPAG, TIPOCXC, VLR_IMPUESTOS)
SELECT CNSFACJ, CODCAJA, CNSCXC, N_FACTURA, ITEM_FCXCDV, IDTERCERO, VALOR, ESTADO, CNSFPAG, TIPOCXC, VLR_IMPUESTOS
FROM [BDATOS\SQL2017].KCIELD.DBO.FCJPCXC


INSERT INTO FCXC(CNSCXC, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT,  ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA,  ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA,  NOPOS, FRADICAEPS, FENVIO, SUCURSAL)
SELECT CNSCXC, FECHACXC, IDTERCERO, IDMENSAJERO, F_VENCE, INDRECIBIDO, F_RECIBIDO, QUIENRECIBIO, NOREFERENCIAEXT, USUARIO, COMPANIA, VALORDEVUELTO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, CNSANT,  ANTIGUA, VALORCXC, DEDUCCIONES, VALORCXCNETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, OBSERVACION, NROCOMPROBANTE, PROCEDENCIA,  ENPRESUPUESTO, MARCAFAC, ITFC, CNSITFC, CONTABILIZADA, OBSCARTA, IDSEDE, MODALIDAD, ATENCION, MES, ANO, REGIMEN, NROGUIA, USUCIERRA, F_CIERRA, ESTADO, COORFACTURACION, COORCARTERA,  NOPOS, FRADICAEPS, FENVIO, SUCURSAL
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXC

INSERT INTO FPAG(CNSFPAG, FECHAPAGO, IDTERCERO, IDMENSAJERO, FORMAPAGO, BANCO, NUMERODOCUMENTO, NUMEROAUTORIZA, VALORPAGO, VLRITEMS, VLRIMPUESTOS, CERRADO, USUARIO, COMPANIA, VLRAJUSTEPESO, AJUSTADAPESO,  VLRGLOSAS, VLRDTOFINAN, VLRTOTAL, DTOFNCIERO, CNSFACJ, CODCAJA, CONTABILIZADO, INGRESO, SUCURSAL, CTA_BCO, ITEM, RENGLON, BANCODOC, NROCOMPROBANTE, MARCACONT, NOCONTABILIZA,  FECHA, ENPRESUPUESTO, VALORLEGALIZADO, OBSERVACION, VIGENCIAPTO, ESTADO, IDSEDE)
SELECT CNSFPAG, FECHAPAGO, IDTERCERO, IDMENSAJERO, FORMAPAGO, BANCO, NUMERODOCUMENTO, NUMEROAUTORIZA, VALORPAGO, VLRITEMS, VLRIMPUESTOS, CERRADO, USUARIO, COMPANIA, VLRAJUSTEPESO, AJUSTADAPESO,  VLRGLOSAS, VLRDTOFINAN, VLRTOTAL, DTOFNCIERO, CNSFACJ, CODCAJA, CONTABILIZADO, INGRESO, SUCURSAL, CTA_BCO, ITEM, RENGLON, BANCODOC, NROCOMPROBANTE, MARCACONT, NOCONTABILIZA,  FECHA, ENPRESUPUESTO, VALORLEGALIZADO, OBSERVACION, VIGENCIAPTO, ESTADO, IDSEDE
FROM [BDATOS\SQL2017].KCIELD.DBO.FPAG

INSERT INTO TER(IDTERCERO, RAZONSOCIAL, NIT, DV, TIPO_ID, IDALTERNA1, IDALTERNA2, DIRECCION, NATJURIDICA, CIUDAD, TELEFONOS, FAX, APA, F_INSCRIPTO, F_RENOVACION, F_VENCIMIENT, R_LEGAL, TIPO_ID_R, NIT_R,  ESTADO, REQAUTORIZA, CUENTA, ZONA, CIA, ACT_ECONOMICA, ENVIODICAJA, MODOCOPAGO, EMPIDMODELOPC, DIASVTO, ESEXTRANJERO, CLASIFICADOR, IDGRUPOIMP, AUTORETENEDOR, GRANCONTRIBUYENTE,  EMAIL, URL, NOMBRES_R_LEGAL, P_APELLIDO_R_LEGAL, S_APELLIDO_R_LEGAL, DE_NIT_R_LEGAL, IDACTIVIDAD, TIPOREGIMEN, MSUCURSALES, FORMAPRE, CODIGO_ARP, NORAD, TIPOAPORTANTE, CODOPERADOR,  CODIGO_AFP, CODIGO_CCF, ASESOR_AFI, ASESOR_MTO, FNAC_RLEGAL, HOBBIE_RL, PROF_RL, EMAIL_RL, TIPOID_TH, NID_TH, DE_NIT_TH, NOMBRES_TH, P_APELLIDO_TH, S_APELLIDO_TH, FNAC_TH,  HOBBIE_TH, PROF_TH, EMAIL_TH, ITFC, CNSITFC, HOMOLOGO, PNOMBRE, SNOMBRE, PAPELLIDO, SAPELLIDO, CUE_BANCARIA, TIPO_CUE, BANCO, SUCURSAL, NIIF_VTAEQUIEFECTIVOS, MANFACT, CTAVIGENCIAANTE,  EMAILRECIBOFE, COD_RESP_FISCAL, MANEXO, PREFIJOXML, SUFIJOXML, SIIF, SIIFCODIGOPCI, SIIFCONTRATO, SIIFCORREOSUPER, MEDIOPAGO, RUC, USUCREA, FECHACREA, CRONICO)
SELECT IDTERCERO, RAZONSOCIAL, NIT, DV, TIPO_ID, IDALTERNA1, IDALTERNA2, DIRECCION, NATJURIDICA, CIUDAD, TELEFONOS, FAX, APA, F_INSCRIPTO, F_RENOVACION, F_VENCIMIENT, R_LEGAL, TIPO_ID_R, NIT_R,  ESTADO, REQAUTORIZA, CUENTA, ZONA, CIA, ACT_ECONOMICA, ENVIODICAJA, MODOCOPAGO, EMPIDMODELOPC, DIASVTO, ESEXTRANJERO, CLASIFICADOR, IDGRUPOIMP, AUTORETENEDOR, GRANCONTRIBUYENTE,  EMAIL, URL, NOMBRES_R_LEGAL, P_APELLIDO_R_LEGAL, S_APELLIDO_R_LEGAL, DE_NIT_R_LEGAL, IDACTIVIDAD, TIPOREGIMEN, MSUCURSALES, FORMAPRE, CODIGO_ARP, NORAD, TIPOAPORTANTE, CODOPERADOR,  CODIGO_AFP, CODIGO_CCF, ASESOR_AFI, ASESOR_MTO, FNAC_RLEGAL, HOBBIE_RL, PROF_RL, EMAIL_RL, TIPOID_TH, NID_TH, DE_NIT_TH, NOMBRES_TH, P_APELLIDO_TH, S_APELLIDO_TH, FNAC_TH,  HOBBIE_TH, PROF_TH, EMAIL_TH, ITFC, CNSITFC, HOMOLOGO, PNOMBRE, SNOMBRE, PAPELLIDO, SAPELLIDO, CUE_BANCARIA, TIPO_CUE, BANCO, SUCURSAL, NIIF_VTAEQUIEFECTIVOS, MANFACT, CTAVIGENCIAANTE,  EMAILRECIBOFE, COD_RESP_FISCAL, MANEXO, PREFIJOXML, SUFIJOXML, SIIF, SIIFCODIGOPCI, SIIFCONTRATO, SIIFCORREOSUPER, MEDIOPAGO, RUC, USUCREA, FECHACREA, CRONICO
FROM [BDATOS\SQL2017].KCIELD.DBO.TER
WHERE NOT EXISTS(SELECT * FROM TER X WHERE X.IDTERCERO COLLATE SQL_1xCompat_CP850_CI_AS=TER.IDTERCERO)

INSERT INTO FCXP(CNSFCXP, FECHA, CNSFCOM, IDTERCERO, NOREFERENCIA, F_FACTURAREF, F_VENCE, VALOR, ESTADO, F_CANCELADO, USUARIO, TIPOCXP, PROCEDENCIA, OBSERVACION, COMPANIA, SYS_ComputerName, USUARIOMOD,  FECHAMOD, NUMCUOTA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, SALDO, IDCLASEIMP, VLR_DESCUENTO, VLR_IVA, VLR_NETO, VLR_IMPUESTOS, SALDO_IMPUESTO, VLR_NOTASDEBITO, VLR_COMISION,  VLR_GLOSAS, VLR_FLETE, CUEDEBITO, CUECREDITO, CNSFCXPPM, MODALIDAD, SUBSIDIO, IDCONTRATO, VLR_NOTASCREDITO, VLR_ABONOS, IDSEDE, PERIODO_ANO, PERIODO_MES, CODUNG, CODPRG, CIUDAD,  ENPRESUPUESTO, SEAMORTIZA, NUMPERAMORT, IDPROPIETARIO, FACCONTROL, USUARIOMARCA, FECHAMARCA, CNSCDP, CNSRP, RUBRO, CNSPPTO, DOCEQUIVALENTE, DIASEQ, CNSENVIOFIN, N_FACTURA, VARIOSTER,  VLR_TDOLAR, TCAMBIO, CONTAAJUSCAMBIO, NROCOMPROCAMBIO, NROCOMPROESPEJO, AUDITADO, USUAUDITA, CNSRESOL, CAJAMENOR, RUBRO_ID, ESTADODIAN, ZIPKEY, CUDS)
SELECT CNSFCXP, FECHA, CNSFCOM, IDTERCERO, NOREFERENCIA, F_FACTURAREF, F_VENCE, VALOR, ESTADO, F_CANCELADO, USUARIO, TIPOCXP, PROCEDENCIA, OBSERVACION, COMPANIA, SYS_ComputerName, USUARIOMOD,  FECHAMOD, NUMCUOTA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, SALDO, IDCLASEIMP, VLR_DESCUENTO, VLR_IVA, VLR_NETO, VLR_IMPUESTOS, SALDO_IMPUESTO, VLR_NOTASDEBITO, VLR_COMISION,  VLR_GLOSAS, VLR_FLETE, CUEDEBITO, CUECREDITO, CNSFCXPPM, MODALIDAD, SUBSIDIO, IDCONTRATO, VLR_NOTASCREDITO, VLR_ABONOS, IDSEDE, PERIODO_ANO, PERIODO_MES, CODUNG, CODPRG, CIUDAD,  ENPRESUPUESTO, SEAMORTIZA, NUMPERAMORT, IDPROPIETARIO, FACCONTROL, USUARIOMARCA, FECHAMARCA, CNSCDP, CNSRP, RUBRO, CNSPPTO, DOCEQUIVALENTE, DIASEQ, CNSENVIOFIN, N_FACTURA, VARIOSTER,  VLR_TDOLAR, TCAMBIO, CONTAAJUSCAMBIO, NROCOMPROCAMBIO, NROCOMPROESPEJO, AUDITADO, USUAUDITA, CNSRESOL, CAJAMENOR, RUBRO_ID, ESTADODIAN, ZIPKEY, CUDS
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXP 

INSERT INTO FCXPD(CNSFCXP, ITEM, IDSERVICIO, CANTIDAD, VALOR, ESTADO, N_PRESUP, ITEM_PRESUP, IDCLASEIMP, VLR_DESCUENTO, VLR_IVA, VLR_NETO, NOLOTE, IDGRUPOSER, PREFIJO, CCOSTO, CCOSTO2, IDAREAH, IDAREA,  NROCOMPROBANTE, CUENTA_SER, VLR_GLOSAS, CUENTA_GLO, PROCEDENCIA, CODUNG, CODPRG, IDIMPUESTO, IDCLASE, ITEM_FIMPDV, CUENTA_IVA, REDONDEO, RUBRO, MIMPCONSUMO, VLRIMPCONSUMO, CTAIMPCONSUMO,  IDTERCERO, VLRCOPAGO, TIPOCOPAGO, VLR_DOLARES, RUBRO_ID, UNSPSC)
SELECT CNSFCXP, ITEM, IDSERVICIO, CANTIDAD, VALOR, ESTADO, N_PRESUP, ITEM_PRESUP, IDCLASEIMP, VLR_DESCUENTO, VLR_IVA, VLR_NETO, NOLOTE, IDGRUPOSER, PREFIJO, CCOSTO, CCOSTO2, IDAREAH, IDAREA,  NROCOMPROBANTE, CUENTA_SER, VLR_GLOSAS, CUENTA_GLO, PROCEDENCIA, CODUNG, CODPRG, IDIMPUESTO, IDCLASE, ITEM_FIMPDV, CUENTA_IVA, REDONDEO, RUBRO, MIMPCONSUMO, VLRIMPCONSUMO, CTAIMPCONSUMO,  IDTERCERO, VLRCOPAGO, TIPOCOPAGO, VLR_DOLARES, RUBRO_ID, UNSPSC
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXPD 

INSERT INTO FCXPPM(CNSFCXPPM, FECHA, OBSERVACION, USUARIO, USUARIOCONF, FECHACONF, SYS_COMPUTERNAME, N_RECIBO, ESTADO, VALOR, PROCEDENCIA, CODCAJA, IDTERCERO_AFAVOR, CODUNG, CODPRG, CUENTA_RUBRO, F_CONTABLE,  RUBRO_ID)
SELECT CNSFCXPPM, FECHA, OBSERVACION, USUARIO, USUARIOCONF, FECHACONF, SYS_COMPUTERNAME, N_RECIBO, ESTADO, VALOR, PROCEDENCIA, CODCAJA, IDTERCERO_AFAVOR, CODUNG, CODPRG, CUENTA_RUBRO, F_CONTABLE,  RUBRO_ID
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXPPM 

INSERT INTO FCXPP(CNSFCXPP, CNSFCXP, FECHA, OBSERVACION, SALDOANTERIOR, ABONO, SALDONUEVO, FECHAPPAGO, VALORPPAGO, USUARIO, USUARIOCONF, FECHACONF, SYS_COMPUTERNAME, CODCAJA, CNSFACJ, N_RECIBO, ESTADO,  IDTERCERO, IDCLASEIMP, VLR_IMPUESTOS, VLR_NETO, PROCEDENCIA, CNSFCXPPM)
SELECT CNSFCXPP, CNSFCXP, FECHA, OBSERVACION, SALDOANTERIOR, ABONO, SALDONUEVO, FECHAPPAGO, VALORPPAGO, USUARIO, USUARIOCONF, FECHACONF, SYS_COMPUTERNAME, CODCAJA, CNSFACJ, N_RECIBO, ESTADO,  IDTERCERO, IDCLASEIMP, VLR_IMPUESTOS, VLR_NETO, PROCEDENCIA, CNSFCXPPM
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXPP

INSERT INTO FCXPDBCR(CNSFCXP, IDNOTA, ITEM, VALOR, TIPO, FECHA, OBSERVACION, ESTADO, PROCEDENCIA, CUENTA_DB, CUENTA_CR, USUARIO, SYS_COMPUTERNAME, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, CODUNG, CODPRG,  ENPRESUPUESTO, CCOSTO, NOREFERENCIA, DECRUCES, VLR_IMPUESTOS, VLR_NETO, PORCENTAJEIVA, VALORIVA, FACTURADA, N_FACTURA, GIMPUESTOS, GENCXP, CNSCXP, IDTERCEROGENCXP, IDSERVICIO,  NODOCUMENTO, CAMTER, GIVA, ESTADODIAN, CUDS, ZIPKEY, CNSRESOL)
SELECT CNSFCXP, IDNOTA, ITEM, VALOR, TIPO, FECHA, OBSERVACION, ESTADO, PROCEDENCIA, CUENTA_DB, CUENTA_CR, USUARIO, SYS_COMPUTERNAME, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, CODUNG, CODPRG,  ENPRESUPUESTO, CCOSTO, NOREFERENCIA, DECRUCES, VLR_IMPUESTOS, VLR_NETO, PORCENTAJEIVA, VALORIVA, FACTURADA, N_FACTURA, GIMPUESTOS, GENCXP, CNSCXP, IDTERCEROGENCXP, IDSERVICIO,  NODOCUMENTO, CAMTER, GIVA, ESTADODIAN, CUDS, ZIPKEY, CNSRESOL
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXPDBCR

INSERT INTO FCXPI(CNSFCXPI, CNSFCXP, IDIMPUESTO, IDCLASE, ITEM, VALOR, VALORIMP, BASE, CUENTA, FECHAINI, FECHAFIN, IDCATEGORIA, PROCEDENCIA, CONCEPTO, TIPOCALCULO, CUENTA_ASUM, IMPUESTO_ASUM, SUSTRAENDO,  MUVT, VRLUVT)
SELECT CNSFCXPI, CNSFCXP, IDIMPUESTO, IDCLASE, ITEM, VALOR, VALORIMP, BASE, CUENTA, FECHAINI, FECHAFIN, IDCATEGORIA, PROCEDENCIA, CONCEPTO, TIPOCALCULO, CUENTA_ASUM, IMPUESTO_ASUM, SUSTRAENDO,  MUVT, VRLUVT
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXPI

--
INSERT INTO ENT(CNSENTREGA, PROCESO, USUARIOENTREGA, FECHAENTREGA, USUARIORECIBE, USUARIO, COMPANIA, ESTADO, ENT_ENTREGA, ENT_RECIBE, FECHARECIBE, IDSEDE, CERRADO, IDTERCERO, IDPLAN)
SELECT CNSENTREGA, PROCESO, USUARIOENTREGA, FECHAENTREGA, USUARIORECIBE, USUARIO, COMPANIA, ESTADO, ENT_ENTREGA, ENT_RECIBE, FECHARECIBE, IDSEDE, CERRADO, IDTERCERO, IDPLAN
FROM [BDATOS\SQL2017].KCIELD.DBO.ENT

INSERT INTO ENTD(CNSENTREGA, NODOCUMENTO, PROCESO, ESTADO, USUARIOVERIFICA, MARCA, VALORENTREGA, OBSERVACION, ENDEVO, CNSDEVOL)
SELECT CNSENTREGA, NODOCUMENTO, PROCESO, ESTADO, USUARIOVERIFICA, MARCA, VALORENTREGA, OBSERVACION, ENDEVO, CNSDEVOL
FROM [BDATOS\SQL2017].KCIELD.DBO.ENTD 

INSERT INTO FCXCD(CNSCXC, N_FACTURA, USUARIO, COMPANIA, VALORFACTURA, DEDUCCIONES, VALORFACTURANETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, MARCAPAGO,  NT_MARCAP, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, NROCOMPROBANTE, CUENTA, DESCRIPCION, NOREFERENCIAEXT, ENCOBROJUR, IDPLAN, ITFC, CNSITFC, VLRFCES, VLRLEVANTADO, MARCA, USURESP, RESPUESTA,  RAZONDEVOL)
SELECT CNSCXC, N_FACTURA, USUARIO, COMPANIA, VALORFACTURA, DEDUCCIONES, VALORFACTURANETO, VLRPAGOS, VLRNOTADB, VLRNOTACR, SALDO, SALDONETO, CERRADA, TIENEGLOSAS, TIENEDEVOLUCION, MARCAPAGO,  NT_MARCAP, VLRGLOSAS, VLRGLOSAS_R, VLREXTRA, NROCOMPROBANTE, CUENTA, DESCRIPCION, NOREFERENCIAEXT, ENCOBROJUR, IDPLAN, ITFC, CNSITFC, VLRFCES, VLRLEVANTADO, MARCA, USURESP, RESPUESTA,  RAZONDEVOL
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXCD

INSERT INTO FCXCR(CNSCXC, N_FACTURA, COMPANIA, VALORFACTURA, OBSERVACION, USUARIO, FECHA, ITFC, CNSITFC, CONTABILIZADA, NROCOMPROBANTE, USURESP, RESPUESTA, ESTADO, PROCESO, MOTIVO1, MOTIVO2, COD_RESPUESTA,  COD_REP1, COD_REP2)
SELECT CNSCXC, N_FACTURA, COMPANIA, VALORFACTURA, OBSERVACION, USUARIO, FECHA, ITFC, CNSITFC, CONTABILIZADA, NROCOMPROBANTE, USURESP, RESPUESTA, ESTADO, PROCESO, MOTIVO1, MOTIVO2, COD_RESPUESTA,  COD_REP1, COD_REP2
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXCR

INSERT INTO FCXCDV(CNSCXC, N_FACTURA, CNSGLO, TIPO, SALDOINICIAL, SALDONETO, FECHA, F_RECIBIDO, F_VENCE, MARCAPAGO, IDFCONCI, LEVANTADO, VLRLEVANTADO, MARCA, EQUIMARCA, CASTIGADA, NROCOMPROBANTE, TCOBRO,  AMONIIF)
SELECT CNSCXC, N_FACTURA, CNSGLO, TIPO, SALDOINICIAL, SALDONETO, FECHA, F_RECIBIDO, F_VENCE, MARCAPAGO, IDFCONCI, LEVANTADO, VLRLEVANTADO, MARCA, EQUIMARCA, CASTIGADA, NROCOMPROBANTE, TCOBRO,  AMONIIF
FROM [BDATOS\SQL2017].KCIELD.DBO.FCXCDV

INSERT INTO FPAGD(CNSFPAG, ITEM, CNSCXC, N_FACTURA, CERRADO, USUARIO, COMPANIA, PAGOTOTAL, CLASEPAG, TIPOGLOSA, VLRFACTURA, VLRGLOSA, GLOSAAFECTAIMP, VLRIMPUESTO, VLRCOPAGO, BASE, VLRPAGOSIN, VLRDTOFIN,  VALORPAGO, VLRAJUSTEPESO, VLRFACTURANDNC, CNSRPDX, SINPAGO, CNSGLO, CLASE, VLREXTRA, VLRIMPGLOBAL, TIPOTTEC, CODUNG, CODPRG, RESTAVLR_IVA, VLROTROSDCTOS, BASEMANUAL, USUBASEMANUAL,  ENPRESUPUESTO, CONSECUTIVOPTO, RECO, CNSPAGOPTO, OBSERVACION, ESTADO, CONTABILIZADA_R, NROCOMPROBANTE_R, LEVANTADO, CODGLOSA, MOTIVO1, MOTIVO2)
SELECT CNSFPAG, ITEM, CNSCXC, N_FACTURA, CERRADO, USUARIO, COMPANIA, PAGOTOTAL, CLASEPAG, TIPOGLOSA, VLRFACTURA, VLRGLOSA, GLOSAAFECTAIMP, VLRIMPUESTO, VLRCOPAGO, BASE, VLRPAGOSIN, VLRDTOFIN,  VALORPAGO, VLRAJUSTEPESO, VLRFACTURANDNC, CNSRPDX, SINPAGO, CNSGLO, CLASE, VLREXTRA, VLRIMPGLOBAL, TIPOTTEC, CODUNG, CODPRG, RESTAVLR_IVA, VLROTROSDCTOS, BASEMANUAL, USUBASEMANUAL,  ENPRESUPUESTO, CONSECUTIVOPTO, RECO, CNSPAGOPTO, OBSERVACION, ESTADO, CONTABILIZADA_R, NROCOMPROBANTE_R, LEVANTADO, CODGLOSA, MOTIVO1, MOTIVO2
FROM [BDATOS\SQL2017].KCIELD.DBO.FPAGD 

INSERT INTO FPAGDI(CNSFPAG, N_FACTURA, IDIMPUESTO, IDCLASE, FACTOR, VLRIMPUESTO, USUARIO, CNSCXC, BASE, ITEM, ITEMFIMPDV)
SELECT CNSFPAG, N_FACTURA, IDIMPUESTO, IDCLASE, FACTOR, VLRIMPUESTO, USUARIO, CNSCXC, BASE, ITEM, ITEMFIMPDV
FROM [BDATOS\SQL2017].KCIELD.DBO.FPAGDI

INSERT INTO FCONCI(IDFCONCI, IDTERCERO, FECHACONC, CNSEXTERNO, USUARIO, FECHADIG, ESTADO, VALOR, FUNCIONARIOADMIN, OBSERVACION, FECHA_PAGCONC, TIPO, PORCENTAJE, CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA,  IDSEDE)
SELECT IDFCONCI, IDTERCERO, FECHACONC, CNSEXTERNO, USUARIO, FECHADIG, ESTADO, VALOR, FUNCIONARIOADMIN, OBSERVACION, FECHA_PAGCONC, TIPO, PORCENTAJE, CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA,  IDSEDE
FROM [BDATOS\SQL2017].KCIELD.DBO.FCONCI

INSERT INTO FCONCID(IDFCONCI, ITEM_FCONCID, CNSCXC, N_FACTURA, ITEM_FCXCDV, TIPO, CNSGLO, SALDONETO, VLRACEPTADO, VLRRECUPERAR, CNSFNOT, CLASE, ESTADO, OBSERVACION, CONDCONCEPTO, CNSFCGLO, CNSNOTADB, NROCOMPROBANTE_A )
SELECT IDFCONCI, ITEM_FCONCID, CNSCXC, N_FACTURA, ITEM_FCXCDV, TIPO, CNSGLO, SALDONETO, VLRACEPTADO, VLRRECUPERAR, CNSFNOT, CLASE, ESTADO, OBSERVACION, CONDCONCEPTO, CNSFCGLO, CNSNOTADB, NROCOMPROBANTE_A 
FROM [BDATOS\SQL2017].KCIELD.DBO.FCONCID

INSERT INTO FGLO(CNSGLO, CNSCXC, N_FACTURA, F_FACTURA, TIPO, VLRGLOSA, VLRACEPTADO, VLRRECUPERAR, OBSERVACION, CERRADA, USUARIO, ASIGENT, CNSENTREGA, MARCAENT, CNSMARCA, ENAUDITORIA, FECHAAUD, IDTERCERO,  FECHARESP, USURESPONRTA, OBSERVACIONRTA, USUARIOINGRTA, TIPORESPUESTA, CNSFPAG, ASIGDEV, CNSENTDEV, IDDEP, CNSFNOT, ESTADO, ABONADO, SALDO, CNSGLO_O, RADICADO, CNSGLOI, ASIGNADAIMP,  IDCONCEPTO, PROCEDENCIA, GENERANOTA, CONTABILIZADA, FECHAGEN, NROCOMPROBANTE, MARCACONT, RAZONANULA, USUARIOANULA, FECHAANU, CODUNG, CODPRG, ENPRESUPUESTO, TCONCILIACION,  FECHACONC, OBSCONCILIACION, TIPOCONCILIACION, VALORCONC, CNSFNOTCONC, ASIGNADOA, FASIGNA, FLIMITE, CODNDIAN, FCIERRE, CNSRMASIVO)
SELECT CNSGLO, CNSCXC, N_FACTURA, F_FACTURA, TIPO, VLRGLOSA, VLRACEPTADO, VLRRECUPERAR, OBSERVACION, CERRADA, USUARIO, ASIGENT, CNSENTREGA, MARCAENT, CNSMARCA, ENAUDITORIA, FECHAAUD, IDTERCERO,  FECHARESP, USURESPONRTA, OBSERVACIONRTA, USUARIOINGRTA, TIPORESPUESTA, CNSFPAG, ASIGDEV, CNSENTDEV, IDDEP, CNSFNOT, ESTADO, ABONADO, SALDO, CNSGLO_O, RADICADO, CNSGLOI, ASIGNADAIMP,  IDCONCEPTO, PROCEDENCIA, GENERANOTA, CONTABILIZADA, FECHAGEN, NROCOMPROBANTE, MARCACONT, RAZONANULA, USUARIOANULA, FECHAANU, CODUNG, CODPRG, ENPRESUPUESTO, TCONCILIACION,  FECHACONC, OBSCONCILIACION, TIPOCONCILIACION, VALORCONC, CNSFNOTCONC, ASIGNADOA, FASIGNA, FLIMITE, CODNDIAN, FCIERRE, CNSRMASIVO
FROM [BDATOS\SQL2017].KCIELD.DBO.FGLO

INSERT INTO FGLOD(CNSGLO, ITEM, CNSCXC, N_FACTURA, USUARIO, FECHANOVEDAD, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO, VLRGLOSA, VLRACEPTADO, VLRRECUPERAR, OBSERVACION, CERRADA, RESPUESTA, FECHARESP,  CONCEPTO, ASIGRESP, RESPONSABLE, OBSRESPON, VALORFINAL, AUTORIZA, ESTADO, N_CUOTAS, USUARIOCE, F_CIERRE, CONTABILIZADA, NROCOMPROBANTE, IDAREA, CCOSTO, CODUNG, CODPRG, TIPOTEC,  N_CUOTA)
SELECT CNSGLO, ITEM, CNSCXC, N_FACTURA, USUARIO, FECHANOVEDAD, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO, VLRGLOSA, VLRACEPTADO, VLRRECUPERAR, OBSERVACION, CERRADA, RESPUESTA, FECHARESP,  CONCEPTO, ASIGRESP, RESPONSABLE, OBSRESPON, VALORFINAL, AUTORIZA, ESTADO, N_CUOTAS, USUARIOCE, F_CIERRE, CONTABILIZADA, NROCOMPROBANTE, IDAREA, CCOSTO, CODUNG, CODPRG, TIPOTEC,  N_CUOTA
FROM [BDATOS\SQL2017].KCIELD.DBO.FGLOD

INSERT INTO FCGLO(CNSFCGLO, DESCRIPCION, TIPO, CLASE)
SELECT CNSFCGLO, DESCRIPCION, TIPO, CLASE
FROM [BDATOS\SQL2017].KCIELD.DBO.FCGLO

INSERT INTO FGLOCG(CNSGLO, CNSFCGLO, VALOR)
SELECT CNSGLO, CNSFCGLO, VALOR
FROM [BDATOS\SQL2017].KCIELD.DBO.FGLOCG

INSERT INTO FGLOI(CNSGLOI, IDTERCERO, USUARIO, FECHA, OBSERVACION, IMPRESIONES, RADICADO, FECHARAD, USUARIORAD, CONTABILIZADA, NROCOMPROBANTE, FECHADIG)
SELECT CNSGLOI, IDTERCERO, USUARIO, FECHA, OBSERVACION, IMPRESIONES, RADICADO, FECHARAD, USUARIORAD, CONTABILIZADA, NROCOMPROBANTE, FECHADIG
FROM [BDATOS\SQL2017].KCIELD.DBO.FGLOI

INSERT INTO FGLOID(CNSGLOI, CNSGLO, N_FACTURA, ITEM)
SELECT CNSGLOI, CNSGLO, N_FACTURA, ITEM
FROM [BDATOS\SQL2017].KCIELD.DBO.FGLOID

INSERT INTO FNOT(CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, CERRADA, ESTADO, USUARIOANU,  USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO, IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO, TIPOCONCEPTO,  VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS, CONSECUTIVOPPTO, RECO, FACTE, CNSRESOLFE, PREFIJODIANFE, CNSDIANFE, CNSMASIVO, ZIPKEY, CUDE, FACTEP, RUTARPTA, DOCUMENTOID, DOCUXMLXZIPID,  XMLZIPID, SOLICITUDJSON, RESPUESTAJSON, PDF)
SELECT CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, MARCA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, CERRADA, ESTADO, USUARIOANU,  USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, ENPRESUPUESTO, IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO, TIPOCONCEPTO,  VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS, CONSECUTIVOPPTO, RECO, FACTE, CNSRESOLFE, PREFIJODIANFE, CNSDIANFE, CNSMASIVO, ZIPKEY, CUDE, FACTEP, RUTARPTA, DOCUMENTOID, DOCUXMLXZIPID,  XMLZIPID, SOLICITUDJSON, RESPUESTAJSON, PDF
FROM [BDATOS\SQL2017].KCIELD.DBO.FNOT

INSERT INTO FNOTD(CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA, CCOSTO, IDAREA, PREFIJO, CUENTA )
SELECT CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO, VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA, CCOSTO, IDAREA, PREFIJO, CUENTA 
FROM [BDATOS\SQL2017].KCIELD.DBO.FNOTD

INSERT INTO MCP(COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE,  ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO, CLASECONT, ENVNIIF,  NROCOMPROBANTENIIF, TREVERSION, NROCOMPROBANTEREVER)
SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE,  ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO, CLASECONT, ENVNIIF,  NROCOMPROBANTENIIF, TREVERSION, NROCOMPROBANTEREVER
FROM [BDATOS\SQL2017].KCIELD.DBO.MCP

INSERT INTO MCH(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG, CODPRG, ERROR, IDOPERACION,  FECHACONCILIACION, IDPROVEEDOR, ENPRESUPUESTO, ESTADOIMP)
SELECT NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG, CODPRG, ERROR, IDOPERACION,  FECHACONCILIACION, IDPROVEEDOR, ENPRESUPUESTO, ESTADOIMP
FROM [BDATOS\SQL2017].KCIELD.DBO.MCH