  
  
  SELECT V.CODCONCEPTO,
  'SELECT '''+NEMPF.NUMDOC+''' , '''+NPER.CNSPAGO+''','''+NEMPF.ITEM+''','''+ V.CODCONCEPTO +''', V.DETALLE, V.CANTIDAD, V.VALOR_EMPLEADO,   
                V.VALOR_EMPRESA, V.VALOR100P, V.IDTRANSPRESTAMO, V.NUMDOCPRESTAMO, V.NUMCUOTA, V.CODPRF, V.IDTERCERO,   
                ''Automatica'', ''Si'','''+V.INFO+''', V.BASE_PRESTACIONES, V.ITEMCONCEPTO, 1, V.GENERANOVEFU, V.CODNOVEFU, V.BASE_CALCULO, ''Ingreso'',HOST_NAME()
         FROM DBO.FNK_VALORCONCEPTO_NEMPFD_RUN('''+NEMPF.NUMDOC+''','''+V.CODCONCEPTO+''','''+CONVERT(VARCHAR,NPER.FECHAINI,103)+''','''+CONVERT(VARCHAR,NPER.FECHAFIN,103)+''','''+NPER.CNSPAGO+''',1, 1, 1) AS V  
         WHERE ( V.VALOR_EMPLEADO + V.VALOR_EMPRESA ) > 0  '
   FROM NEMPF,NPER,(SELECT NCON.CODCONCEPTO, Z.CODPLANTA, NEMPF.NUMDOC, NEMPF.ITEM, NCON.TIPO, NCON.INFO,   
                   PRIORIDAD=CASE WHEN ISNULL(NCON.PRIORIDAD,0)=0 THEN 999999 ELSE NCON.PRIORIDAD END  
            FROM   RPDX X INNER JOIN RPDX Y ON X.CNS='NCON' 
                                           AND Y.CNS='NCAR' 
                          INNER JOIN FNK_INFO_NEMPHIS('31/08/2019') Z ON Z.CODCARGO = Y.ID1 
                                                                  AND Z.NIVEL    = Y.ID2 
                                                                  AND Z.GRADO    = Y.ID3 
                          INNER JOIN NCON   ON X.ID1       = NCON.CODCONCEPTO 
                                           AND NCON.TIPO   = 'Ingreso' 
                                           AND NCON.ESTADO = 'Activo' 
                          INNER JOIN NEMPF  ON NEMPF.CNSPAGO = '01201908P30-1' 
                                           AND NEMPF.NUMDOC  = Z.NUMDOC 
            WHERE  NCON.CODCONCEPTO <> 'RET') AS V
      WHERE NEMPF.NUMDOC=V.NUMDOC
      AND NEMPF.CNSPAGO=NPER.CNSPAGO
      AND NEMPF.CNSPAGO='01201908P30-1' 
      AND NPER.CNSPAGO='01201908P30-1' 
      ORDER BY NEMPF.NUMDOC




  
         SELECT @NUMDOC, @CNSPAGO, @ITEM, @CODCONCEPTO_CUR, V.DETALLE, V.CANTIDAD, V.VALOR_EMPLEADO,   
                V.VALOR_EMPRESA, V.VALOR100P, V.IDTRANSPRESTAMO, V.NUMDOCPRESTAMO, V.NUMCUOTA, V.CODPRF, V.IDTERCERO,   
                'Automatica', 'Si', @INFO, V.BASE_PRESTACIONES, V.ITEMCONCEPTO, 1, V.GENERANOVEFU, V.CODNOVEFU, V.BASE_CALCULO, 'Ingreso',HOST_NAME()
         FROM DBO.FNK_VALORCONCEPTO_NEMPFD_RUN(@NUMDOC,@CODCONCEPTO_CUR,@FECHAINI,@FECHAFIN,@CNSPAGO,1, @HORAS_LAB, @DIAS_LAB) AS V  
         WHERE ( V.VALOR_EMPLEADO + V.VALOR_EMPRESA ) > 0  