
--EXA00990
--EXA0681

DROP TABLE #A
SELECT HPRE.NOADMISION,HPRED.IDSERVICIO INTO #A
FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
WHERE HPRED.IDSERVICIO='EXA0681'
AND HPRED.FACTURADA=0
AND COALESCE(HPRED.NOCOBRABLE,0)=0
AND COALESCE(HPRED.ANULADO,0)=0
GROUP BY HPRE.NOADMISION,HPRED.IDSERVICIO
HAVING COUNT(*)>1

DROP TABLE #B

SELECT HPRE.NOADMISION,MIN(HPRED.NOPRESTACION)NOPRESTACION INTO #B
FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
WHERE EXISTS(SELECT * FROM #A WHERE #A.NOADMISION=HPRE.NOADMISION AND HPRED.IDSERVICIO=#A.IDSERVICIO)
AND HPRED.FACTURADA=0
AND HPRED.IDSERVICIO='EXA0681'
AND COALESCE(HPRED.NOCOBRABLE,0)=0
AND COALESCE(HPRED.ANULADO,0)=0
GROUP BY HPRE.NOADMISION
ORDER BY NOADMISION

DROP TABLE #C

SELECT NOPRESTACION,MIN(NOITEM)NOITEM INTO #C
FROM HPRED 
WHERE EXISTS(SELECT * FROM #B WHERE #B.NOPRESTACION=HPRED.NOPRESTACION)
AND HPRED.FACTURADA=0
AND HPRED.IDSERVICIO='EXA0681'
AND COALESCE(HPRED.NOCOBRABLE,0)=0
AND COALESCE(HPRED.ANULADO,0)=0
GROUP BY NOPRESTACION


BEGIN TRAN 
UPDATE HPRED SET NOCOBRABLE=1,ANULADO=1
FROM HPRED  INNER JOIN #C ON HPRED.NOPRESTACION=#C.NOPRESTACION AND HPRED.NOITEM=#C.NOITEM
COMMIT

ROLLBACK

SELECT  * FROM HPRE WHERE NOADMISION IS NULL

BEGIN TRAN 
DELETE HPRED FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
WHERE HPRE.NOADMISION IS NULL

COMMIT

DELETE HPRE WHERE NOADMISION IS NULL