DECLARE 
 @CNSMOV            VARCHAR(20),
 @CODCAJA           VARCHAR(10),   
 @USUARIO           VARCHAR(12),  
 @SYS_COMPUTERNAME  VARCHAR(254),  
 @COMPANIA          VARCHAR(2),   
 @SEDE              VARCHAR(5),  
 @NROCOMPROBANTE    VARCHAR(20),
 @ANO               VARCHAR(4),
 @MES               INT
 
--EXEC SPK_CONTAB_CAJA_ING  '00000060','002','SOPORTE','SOPORTE','01','01','0184000001139096'


   DECLARE MCP_RECONSTRUYE CURSOR FOR
   SELECT REFERENCIA1,REFERENCIA2,USUARIO,HOST_NAME(),COMPANIA,'01',NROCOMPROBANTE FROM MCP
   WHERE PROCEDENCIA='CAJA'  AND ESTADO=0 AND ANULADO<>1  AND ANO='2013'-- AND MES=1
   GROUP BY REFERENCIA1,REFERENCIA2,USUARIO,COMPANIA,NROCOMPROBANTE        
   OPEN MCP_RECONSTRUYE    
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @CNSMOV,@CODCAJA,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   WHILE @@FETCH_STATUS = 0    
   BEGIN
       PRINT 'EMPEZANDO....'+@CNSMOV+'CAJA'+@CODCAJA
       EXEC SPK_CONTAB_CAJA_ING  @CNSMOV,@CODCAJA,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE 
       EXEC SPK_REVISAR_COMPROBANTE '01',@NROCOMPROBANTE
       EXEC SPK_SUMA_DBCR @NROCOMPROBANTE    
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @CNSMOV,@CODCAJA,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   END
   CLOSE MCP_RECONSTRUYE
   DEALLOCATE MCP_RECONSTRUYE
   