BEGIN TRAN 
DECLARE @CNSFCXPCJM VARCHAR(20)   --REEMBOLSO CAJA MENOR
DECLARE @RESPONCJM  VARCHAR(20)   --REEMBOLSO CAJA MENOR
DECLARE @CAJAMENOR  VARCHAR(4)    --REEMBOLSO CAJA MENOR
DECLARE @VLRPAGOCJM DECIMAL(14,2) --REEMBOLSO CAJA MENOR
DECLARE @CNSFCXPPM  VARCHAR(20)   --REEMBOLSO CAJA MENOR
DECLARE @ABIERTA BIT
DECLARE @CNSACJ VARCHAR(20)
DECLARE @NVOCONSEC2  VARCHAR(20)
DECLARE @CPRECTRAS VARCHAR(10)
DECLARE @CNSPCJ VARCHAR(20)
DECLARE @DATOEFE VARCHAR(10)
DECLARE
@CODCAJA          VARCHAR(4)='001' ,
@CNSFACJ          VARCHAR(20)='E00004916',
@COMPANIA         VARCHAR(2)='01',
@SEDE             VARCHAR(5)='01', 
@USUARIO          VARCHAR(12)='74084788',
@SYS_COMPUTERNAME VARCHAR(254)='CONTABILIDAD'

              PRINT ' INICIO EL PROCESO DE REEMBOLSO AUTOMATICO'
	            DECLARE PAG_CAJMENOR_CURSOR CURSOR FOR 
               SELECT DISTINCT  FCXP.CNSFCXP,FCXP.IDTERCERO,FCXPP.ABONO,FCXPP.CNSFCXPP, FCXP.CAJAMENOR
               FROM   FCJD INNER JOIN FCXPP ON FCXPP.CNSFCXPP = FCJD.IDSERVICIO
                           INNER JOIN FCXP ON FCXPP.CNSFCXP=FCXP.CNSFCXP
               WHERE  FCJD.CODCAJA   = @CODCAJA   
               AND    FCJD.CNSFACJ   = @CNSFACJ    
               AND FCXP.PROCEDENCIA='CAJAMENOR'                    
	            OPEN PAG_CAJMENOR_CURSOR    
	            FETCH NEXT FROM PAG_CAJMENOR_CURSOR    
	            INTO @CNSFCXPCJM,@RESPONCJM,@VLRPAGOCJM,@CNSFCXPPM, @CAJAMENOR
	            WHILE @@FETCH_STATUS = 0    
	            BEGIN 
                  PRINT 'Busco caja menor'
                  --SELECT @CAJAMENOR=CODCAJA FROM CAJ WHERE RESPONSABLE=@RESPONCJM AND CLASE='Menor'

                  SELECT @ABIERTA = COALESCE(ABIERTA,0) FROM CAJ
                  WHERE  CODCAJA=@CAJAMENOR
                  IF @ABIERTA=0
                  BEGIN
                     PRINT 'CAJA NO ESTA ABIERTA'
                     CONTINUE
	                  FETCH NEXT FROM PAG_CAJMENOR_CURSOR    
	                  INTO @CNSFCXPCJM,@RESPONCJM,@VLRPAGOCJM,@CNSFCXPPM
                  END
                  SELECT @CNSACJ = CNSACJ FROM ACJ WHERE   CODCAJA  = @CAJAMENOR AND ABIERTA = 1                
                           
                  EXEC SPK_GENCONSECUTIVO @COMPANIA, @CAJAMENOR, '@FCJ',  @NVOCONSEC2 OUTPUT  

                  SELECT @NVOCONSEC2 = REPLACE(SPACE(8 - LEN(@NVOCONSEC2))+LTRIM(RTRIM(@NVOCONSEC2)),SPACE(1),0)
                             
                  INSERT INTO FCJ(CNSFACJ, CODCAJA, CLASE_FAC, NOADMISION, NOPRESTACION, 
                                    IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO, CERRADA, 
                                    FECHA, TIPO, PROCEDENCIA, N_FACTURA, IDTERCERO, 
                                    NOMBRECLIENTE, CNSACJ, N_RECIBO, ESTADO, IMPRESO, MARCACONT,
                                    CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO, 
                                    SUBCCOSTO, CLASER, IDCAUSALANUL, USUARIOANUL, 
                                    SYS_COMPUTERNAMEANUL, FECHAANU, TCNSFACJ, IDENTIFICADOR, 
                                    SYS_COMPUTERNAME, OBSERVACION, RECAUDO, ENPAGOS,
                                    TIPOEGRESO, IMPRESOTRAS, BANCO, SUCURSAL, CTA_BCO, USUARIO, 
                                    DEAPERTURA)
                  SELECT @NVOCONSEC2, @CAJAMENOR, 'COBRO', NOADMISION, NOPRESTACION, IDPLAN, VALORTOTAL, COMPANIA, @CODCAJA,1 CERRADA, 
                           FECHA, 'EXTERNO', PROCEDENCIA, N_FACTURA, @CODCAJA, NOMBRECLIENTE, @CNSACJ, N_RECIBO, 'P', IMPRESO, MARCACONT,
                           CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO, SUBCCOSTO, CLASER, IDCAUSALANUL, USUARIOANUL, 
                           SYS_COMPUTERNAMEANUL, FECHAANU, TCNSFACJ, IDENTIFICADOR, SYS_COMPUTERNAME, OBSERVACION, RECAUDO, ENPAGOS,
                           TIPOEGRESO, IMPRESOTRAS, BANCO, SUCURSAL, CTA_BCO, USUARIO, 3
                  FROM   FCJ
                  WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA

                  SELECT @CPRECTRAS = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJRECEPCIONTRAS'

                  INSERT INTO FCJD(CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, 
                                    CANTIDAD, VALORTOTAL, IDSERVICIO, CODCAJA, N_RECIBO, 
                                    TDESCUENTO, TIPODCTO, VLRDESCUENTO, DCTO)
                  SELECT    @NVOCONSEC2, 1, @CPRECTRAS, AREAFUNCIONAL, VALORUNITARIO, 
                           CANTIDAD,    VALORTOTAL,  IDSERVICIO, @CAJAMENOR, N_RECIBO, 
                           TDESCUENTO,  TIPODCTO,    VLRDESCUENTO, DCTO
                  FROM FCJD
                  WHERE  CNSFACJ = @CNSFACJ AND CODCAJA = @CODCAJA
                  AND IDSERVICIO=@CNSFCXPPM
                           
                           
                  SELECT @CNSPCJ = NULL
                  EXEC SPK_GENCONSECUTIVO @COMPANIA, @CAJAMENOR, '@PCJ', @CNSPCJ OUTPUT  
                     SELECT @CNSPCJ = REPLACE(SPACE(8 - LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)
                              
                     INSERT INTO PCJ(CNSPCJ, CNSFACJ, TIPOPAGO, VALOR, BANCO, 
                                       NUMERODOCUMENTO,
                                       NUMEROAUTORIZA, FECHA, CNSACJ, IDTERCERO, CODCAJA,
                                       IMPRESO, CODCAJADEP, CNSFACJDEP, SUCURSAL, CTA_BCO, 
                                       CNSDOC)
                  SELECT @CNSPCJ, @NVOCONSEC2, @DATOEFE, @VLRPAGOCJM, NULL, NULL, NULL, NULL,
                           @CNSACJ , NULL, @CAJAMENOR, 0, NULL, NULL, NULL, NULL, NULL  
								  
		            UPDATE CAJR SET VALOR=COALESCE(VALOR,0)+@VLRPAGOCJM   WHERE   FORMAPAGO=DBO.FNK_VALORVARIABLE('IDCJFPAEFECTIVO') AND CODCAJA=@CAJAMENOR
		            UPDATE FCJ SET IDTERCERO = DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO') WHERE CNSFACJ=@NVOCONSEC2 AND CODCAJA=@CAJAMENOR
                    UPDATE ACJD SET SALDO= (SELECT COALESCE(VALOR,0) FROM CAJR WHERE   FORMAPAGO=DBO.FNK_VALORVARIABLE('IDCJFPAEFECTIVO') AND CODCAJA=@CAJAMENOR)
                    WHERE CNSACJ=@CNSACJ AND TIPO='Saldo Inicial' AND FORMAPAGO=DBO.FNK_VALORVARIABLE('IDCJFPAEFECTIVO')
	            FETCH NEXT FROM PAG_CAJMENOR_CURSOR    
	            INTO @CNSFCXPCJM,@RESPONCJM,@VLRPAGOCJM,@CNSFCXPPM, @CAJAMENOR
	            END
	            CLOSE PAG_CAJMENOR_CURSOR
	            DEALLOCATE PAG_CAJMENOR_CURSOR 

--COMMIT
--SELECT  * FROM FCJ WHERE CODCAJA='008' AND CLASE_FAC='COBRO' 