DECLARE @CNSMOV VARCHAR(20) =''
DECLARE @CNSFCOM VARCHAR(20)
DECLARE @CNSFCXP VARCHAR(20)
DECLARE @COMPANIA VARCHAR(20)='01'
DECLARE @SEDE VARCHAR(20)='01'
DECLARE @CNSANT VARCHAR(20)
DECLARE @T_ANTICIPOS DECIMAL(14,2)
DECLARE @VLR_ANT_LEGAL DECIMAL(14,2)
DECLARE @VL_SALDO DECIMAL(14,2)
DECLARE @ESTADO_ANT VARCHAR(20)
DECLARE @USUARIO VARCHAR(20)

		SELECT @CNSFCOM = CNSFCOM,@USUARIO=USUARIOCONF FROM IMOV WHERE CNSMOV = @CNSMOV
		SELECT @T_ANTICIPOS = COALESCE(SUM(VALOR), 0) FROM FCXP WHERE CNSFCOM = @CNSFCOM AND PROCEDENCIA = 'Anticipos' AND ESTADO<>'A'
      SELECT @VLR_ANT_LEGAL =COALESCE(SUM(VALOR_LEG),0) FROM ANT WHERE CNSFCOM=@CNSFCOM AND ESTADO<>'A'
      SELECT @VL_SALDO=COALESCE(SALDO,0) FROM FCXP WHERE CNSFCXP=@CNSFCXP
      IF @VLR_ANT_LEGAL IS NULL
      SET @VLR_ANT_LEGAL=0
      IF @VL_SALDO IS NULL
      SET @VL_SALDO=0


      SELECT @T_ANTICIPOS=COALESCE(@T_ANTICIPOS,0)-COALESCE(@VLR_ANT_LEGAL,0)

      IF @VL_SALDO<@T_ANTICIPOS
      BEGIN
         SELECT @T_ANTICIPOS=@VL_SALDO
      END



      IF @T_ANTICIPOS IS NULL
      BEGIN 
         SELECT @T_ANTICIPOS=0
      END
		UPDATE FCXP SET VLR_ABONOS = VLR_ABONOS+@T_ANTICIPOS WHERE CNSFCXP = @CNSFCXP
        
		IF @T_ANTICIPOS > 0
		BEGIN
			SET @CNSANT=SPACE(20)  
			EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@NAT',@CNSANT OUTPUT
			SELECT @CNSANT = @SEDE + 'CM' + REPLACE(SPACE(6 - LEN(@CNSANT))+LTRIM(RTRIM(@CNSANT)),SPACE(1),0)


			INSERT INTO ANT (CNSANT, CNSFCOM, DESCRIPCION, FECHA, VALORCXP, VALOR_LEG, NOREFERENCIA, F_FACTURAREF, F_VENCE, USUARIO, 
							ESTADO, CNSFCXP, CONTABILIZADO, NROCOMPROBANTE)
			SELECT @CNSANT, @CNSFCOM, 'Legalización A: '+TER.RAZONSOCIAL+' Ref. '+FCXP.NOREFERENCIA, GETDATE(), @T_ANTICIPOS, @T_ANTICIPOS, FCXP.NOREFERENCIA,
					FCXP.F_FACTURAREF, FCXP.F_VENCE, @USUARIO, 'I', @CNSFCXP, 0, ''
			FROM FCXP INNER JOIN TER ON TER.IDTERCERO = FCXP.IDTERCERO
			WHERE FCXP.CNSFCXP = @CNSFCXP
          
			SELECT @ESTADO_ANT = ESTADO FROM ANT WHERE CNSANT = @CNSANT


			IF @ESTADO_ANT = 'I'
			BEGIN
				EXEC SPK_ANTICIPO_LEG_CXP @CNSFCOM, @CNSANT, @COMPANIA, @USUARIO, @SEDE
			END
		END
      EXEC SPK_CALCULOVALORESCXP @CNSFCXP
