
   DECLARE @CNSCXC VARCHAR(20)
	DECLARE RELIQUIDACART_CURSOR CURSOR FOR    
   SELECT DISTINCT CNSCXC FROM FCXC  
	OPEN RELIQUIDACART_CURSOR    
	FETCH NEXT FROM RELIQUIDACART_CURSOR    
	INTO @CNSCXC
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
      EXEC SPK_RELIQUIDACXCQX @CNSCXC
	FETCH NEXT FROM RELIQUIDACART_CURSOR    
	INTO @CNSCXC
	END
	CLOSE RELIQUIDACART_CURSOR
	DEALLOCATE RELIQUIDACART_CURSOR
