SELECT E.NOADMISION,A.NORDEN,A.IDSERVICIO,D.DESCSERVICIO,A.NOITEM,A.IDDATO,B.NOMBRE,ALFANUMERICO,B.UNIMED,DBO.FNK_FECHA(C.FECHARES)FECHARES
FROM LORDD A INNER JOIN LSER B ON A.IDDATO=B.IDDATO AND A.NOITEM=B.NOITEM AND A.IDSERVICIO=B.IDSERVICIO
			 INNER JOIN LORD C ON A.NORDEN=C.NORDEN
			 INNER JOIN SER  D ON A.IDSERVICIO=D.IDSERVICIO
			 INNER JOIN LING E ON C.NOINGRESO=E.NOINGRESO
WHERE A.TIPOCAMPO='LISTA' AND C.ESTADO='R' AND E.AMBITOTR='LX' AND E.NOADMISION='$noadmision' AND C.IDSERVICIO='$idservicio'
UNION ALL 
SELECT E.NOADMISION,A.NORDEN,A.IDSERVICIO,D.DESCSERVICIO,A.NOITEM,A.IDDATO,B.NOMBRE,ALFANUMERICO,B.UNIMED,DBO.FNK_FECHA(C.FECHARES)FECHARES
FROM LORDD A INNER JOIN LSER B ON A.IDDATO=B.IDDATO AND A.NOITEM=B.NOITEM AND A.IDSERVICIO=B.IDSERVICIO
	         INNER JOIN LORD C ON A.NORDEN=C.NORDEN
	         INNER JOIN SER  D ON A.IDSERVICIO=D.IDSERVICIO
	         INNER JOIN LING E ON C.NOINGRESO=E.NOINGRESO
WHERE A.TIPOCAMPO='Alfanumerico' AND C.ESTADO='R' AND E.AMBITOTR='LX' AND E.NOADMISION='$noadmision' AND C.IDSERVICIO='$idservicio'
UNION ALL 
SELECT E.NOADMISION,A.NORDEN,A.IDSERVICIO,D.DESCSERVICIO,A.NOITEM,A.IDDATO,B.NOMBRE,MEMO,B.UNIMED,DBO.FNK_FECHA(C.FECHARES)FECHARES
FROM LORDD A INNER JOIN LSER B ON A.IDDATO=B.IDDATO AND A.NOITEM=B.NOITEM AND A.IDSERVICIO=B.IDSERVICIO
			 INNER JOIN LORD C ON A.NORDEN=C.NORDEN
			 INNER JOIN SER  D ON A.IDSERVICIO=D.IDSERVICIO
			 INNER JOIN LING E ON C.NOINGRESO=E.NOINGRESO
WHERE A.TIPOCAMPO='MEMO' AND C.ESTADO='R' AND E.AMBITOTR='LX' AND E.NOADMISION='$noadmision' AND C.IDSERVICIO='$idservicio'
UNION ALL 
SELECT E.NOADMISION,A.NORDEN,A.IDSERVICIO,D.DESCSERVICIO,A.NOITEM,A.IDDATO,B.NOMBRE,'',B.UNIMED,DBO.FNK_FECHA(C.FECHARES)FECHARES
FROM LORDD A INNER JOIN LSER B ON A.IDDATO=B.IDDATO AND A.NOITEM=B.NOITEM AND A.IDSERVICIO=B.IDSERVICIO
			 INNER JOIN LORD C ON A.NORDEN=C.NORDEN
			 INNER JOIN SER  D ON A.IDSERVICIO=D.IDSERVICIO
			 INNER JOIN LING E ON C.NOINGRESO=E.NOINGRESO
WHERE A.TIPOCAMPO='Titulo' AND C.ESTADO='R' AND E.AMBITOTR='LX' AND E.NOADMISION='$noadmision' AND C.IDSERVICIO='$idservicio'
UNION ALL 
SELECT E.NOADMISION,A.NORDEN,A.IDSERVICIO,D.DESCSERVICIO,A.NOITEM,A.IDDATO,B.NOMBRE,'',B.UNIMED,DBO.FNK_FECHA(C.FECHARES)FECHARES
FROM LORDD A INNER JOIN LSER B ON A.IDDATO=B.IDDATO AND A.NOITEM=B.NOITEM AND A.IDSERVICIO=B.IDSERVICIO
			 INNER JOIN LORD C ON A.NORDEN=C.NORDEN
			 INNER JOIN SER  D ON A.IDSERVICIO=D.IDSERVICIO
			 INNER JOIN LING E ON C.NOINGRESO=E.NOINGRESO
WHERE A.TIPOCAMPO='Subtitulo' AND C.ESTADO='R' AND E.AMBITOTR='LX' AND E.NOADMISION='$noadmision' AND C.IDSERVICIO='$idservicio'
UNION ALL
SELECT F.NOADMISION,A.NORDEN,A.IDSERVICIO,E.DESCSERVICIO,A.NOITEM,A.IDDATO,B.NOMBRE,C.OPCION,C.OBS,DBO.FNK_FECHA(D.FECHARES)FECHARES
FROM LORDD A INNER JOIN LSER B ON A.IDDATO=B.IDDATO AND A.NOITEM=B.NOITEM AND A.IDSERVICIO=B.IDSERVICIO
		     INNER JOIN LORDDM C ON A.NORDEN=C.NORDEN AND A.IDDATO=C.IDDATO AND A.NOITEM=C.NOITEM AND C.MULTICHECK=1
		     INNER JOIN LORD D ON A.NORDEN=D.NORDEN
		     INNER JOIN SER  E ON A.IDSERVICIO=E.IDSERVICIO
		     INNER JOIN LING F ON D.NOINGRESO=F.NOINGRESO
WHERE A.TIPOCAMPO='MultiCheck' AND D.ESTADO='R' AND F.AMBITOTR='LX' AND F.NOADMISION='$noadmision' AND E.IDSERVICIO='$idservicio'
ORDER BY A.NORDEN,A.NOITEM