

SELECT * FROM USVGS WHERE IDVARIABLE='IDBOD_HEMODERIVADOS'

DROP TABLE #A

SELECT IMOV.IDBODEGA, IMOVH.IDARTICULO,CONVERT(INT,SUM(CANTIDAD))CANTIDAD INTO #ENTR
FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
			 INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
WHERE IMOV.FECHAMOV>='26/06/2022'
AND ITMO.TIPO='Credito'
AND IMOV.ESTADO=1
GROUP BY IMOV.IDBODEGA, IMOVH.IDARTICULO


SELECT IMOV.IDBODEGA, ISAL.IDARTICULO,CONVERT(INT,SUM(CANTIDAD))CANTIDAD INTO #SALI
FROM IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV
			 INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
WHERE IMOV.FECHAMOV>='26/06/2022'
AND ITMO.TIPO='Debito'
AND IMOV.ESTADO<>2
GROUP BY IMOV.IDBODEGA, ISAL.IDARTICULO

SELECT * FROM IEXI_26062022_0008  WHERE IDARTICULO='FAR01195-2'
SELECT * FROM #ENTR  WHERE IDARTICULO='FAR01195-2'
SELECT * FROM #SALI  WHERE IDARTICULO='FAR01195-2'
SELECT * FROM IEXI  WHERE IDARTICULO='FAR01195-2' AND EXISLOTE>0 AND IDBODEGA='18'


SELECT IDBODEGA,IDARTICULO,SUM(EXISTENCIA)EXISLOTE INTO #I FROM IEXI_26062022_0008
GROUP BY IDBODEGA,IDARTICULO

SELECT IDBODEGA,IDARTICULO,SUM(EXISLOTE)EXISLOTE INTO #X FROM IEXI
GROUP BY IDBODEGA,IDARTICULO

DROP TABLE #ENTR
DROP TABLE #SALI
DROP TABLE #I
DROP TABLE #X

SELECT IEXI.IDBODEGA, IEXI.IDARTICULO,SUM(IEXI.EXISLOTE) TENGO ,
SUM(IEXI.EXISLOTE)-(SUM(COALESCE(A.EXISLOTE,0))+SUM(COALESCE(E.CANTIDAD,0))-SUM(COALESCE(S.CANTIDAD,0)))FORMULA,
(SUM(COALESCE(A.EXISLOTE,0))+SUM(COALESCE(E.CANTIDAD,0))-SUM(COALESCE(S.CANTIDAD,0)))DEBESER
,SUM(COALESCE(A.EXISLOTE,0)) SI,SUM(COALESCE(E.CANTIDAD,0)) ENTRADA,SUM(COALESCE(S.CANTIDAD,0))SALIDA
FROM #X IEXI LEFT JOIN #I A ON IEXI.IDBODEGA=A.IDBODEGA AND IEXI.IDARTICULO=A.IDARTICULO --AND IEXI.NOLOTEPEDIDO=A.NOLOTEPEDIDO
			 LEFT JOIN #ENTR E ON IEXI.IDBODEGA=E.IDBODEGA AND IEXI.IDARTICULO=E.IDARTICULO
			 LEFT JOIN #SALI S ON IEXI.IDBODEGA=S.IDBODEGA AND IEXI.IDARTICULO=S.IDARTICULO
WHERE  IEXI.IDBODEGA='18' --AND IEXI.IDARTICULO='FAR01346-4'
GROUP BY IEXI.IDBODEGA,IEXI.IDARTICULO
HAVING  SUM(IEXI.EXISLOTE)-(SUM(COALESCE(A.EXISLOTE,0))+SUM(COALESCE(E.CANTIDAD,0))-SUM(COALESCE(S.CANTIDAD,0)))<>0




SELECT * FROM IEXI WHERE IDARTICULO='DIS00132-1' AND EXISLOTE>0
SELECT * FROM #x WHERE IDARTICULO='DIS00132-1' AND EXISLOTE>0
SELECT * FROM IEXI_26062022_0008 WHERE IDARTICULO='DIS00132-1' AND EXISTENCIA>0

SELECT * FROM #x WHERE IDARTICULO='DIS00132-1'  AND IDBODEGA='18' AND EXISLOTE>0

SELECT * FROM #I WHERE IDARTICULO='DIS00132-1' AND EXISLOTE>0

SELECT * FROM #ENTR WHERE IDARTICULO='DIS00132-1'
SELECT * FROM #SALI WHERE IDARTICULO='DIS00132-1'

SELECT *
FROM #X IEXI LEFT JOIN #I A ON IEXI.IDBODEGA=A.IDBODEGA AND IEXI.IDARTICULO=A.IDARTICULO --AND IEXI.NOLOTEPEDIDO=A.NOLOTEPEDIDO
			 LEFT JOIN #ENTR E ON IEXI.IDBODEGA=E.IDBODEGA AND IEXI.IDARTICULO=E.IDARTICULO
			 LEFT JOIN #SALI S ON IEXI.IDBODEGA=S.IDBODEGA AND IEXI.IDARTICULO=S.IDARTICULO
WHERE  IEXI.IDBODEGA='18' AND IEXI.IDARTICULO='FAR01346-4'


SELECT IMOV.IDBODEGA,IMOV.CNSMOV, ISAL.IDARTICULO--,CONVERT(INT,SUM(CANTIDAD))CANTIDAD --INTO #SALI
FROM IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV
			 INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
WHERE IMOV.FECHAMOV>='26/06/2022'
AND ITMO.TIPO='Debito'
AND ISAL.IDARTICULO='DIS00132-1'
AND IMOV.ESTADO<>2
GROUP BY IMOV.IDBODEGA, ISAL.IDARTICULO