

SELECT E.IDARTICULO,E.DESCRIPCION,CONVERT(INT,SUM(E.CANTIDAD))CANTIDADE,CONVERT(DECIMAL(14,2),SUM(E.PCOSTO))PCOSTO,
CONVERT(DECIMAL(14,2),MAX(E.PIVA))PIVA,
CONVERT(DECIMAL(14,4),SUM(CASE WHEN COALESCE(E.PIVA,0)>0 THEN E.PCOSTO*(E.PIVA/100) ELSE 0 END)) VLR_IGV,
CONVERT(DECIMAL(14,2),SUM(E.PCOSTO)-SUM(CASE WHEN COALESCE(E.PIVA,0)>0 THEN E.PCOSTO*(E.PIVA/100) ELSE 0 END))VLR_ANTES,
CONVERT(INT,SUM(COALESCE(S.CANTIDAD,0)))CANTIDADS
FROM (
SELECT IMOVH.IDARTICULO,IART.DESCRIPCION,SUM(IMOVH.CANTIDAD)CANTIDAD,AVG(CASE WHEN COALESCE(IMOVH.PCOSTO,0)>0 THEN IMOVH.PCOSTO ELSE 1 END   )PCOSTO,
MAX(COALESCE(PIVA,0))PIVA,AVG(COALESCE(VLRIVA,0))VLRIVA,
SUM(IMOVH.PCOSTO-CASE WHEN COALESCE(VLRIVA,0)>0 THEN VLRIVA/CANTIDAD ELSE 0 END) PANTIVA
FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
			 INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
			 INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
WHERE IMOV.ESTADO=1
AND ITMO.TIPO='Credito'
AND IART.ESTADO='Activo'
AND IMOV.IDBODEGA='01'
AND COALESCE(IMOVH.PIVA,0)>0
AND IMOV.FECHACONF>='01/01/2020'
AND IMOV.FECHACONF<'01/01/2021'
GROUP BY IMOVH.IDARTICULO,IART.DESCRIPCION 
UNION ALL
SELECT IMOVH.IDARTICULO,IART.DESCRIPCION,SUM(IMOVH.CANTIDAD)CANTIDAD,AVG(CASE WHEN COALESCE(IMOVH.PCOSTO,0)>0 THEN IMOVH.PCOSTO ELSE 1 END   )PCOSTO,
0,0,AVG(IMOVH.PCOSTO) AS PANTIVA
FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
			 INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
			 INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
WHERE IMOV.ESTADO=1
AND ITMO.TIPO='Credito'
AND IART.ESTADO='Activo'
AND IMOV.IDBODEGA='01'
AND COALESCE(IMOVH.PIVA,0)=0
AND IMOV.FECHACONF>='01/01/2020'
AND IMOV.FECHACONF<'01/01/2021'
GROUP BY IMOVH.IDARTICULO,IART.DESCRIPCION 
)E LEFT JOIN (
SELECT IMOVH.IDARTICULO,IART.DESCRIPCION,SUM(IMOVH.CANTIDAD)CANTIDAD
FROM IMOV INNER JOIN ISAL IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
			 INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
			 INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
WHERE IMOV.ESTADO=1
AND ITMO.TIPO='Debito'
AND IART.ESTADO='Activo'
AND IMOV.FECHACONF>='01/01/2020'
AND IMOV.FECHACONF<'01/01/2021'
AND IMOV.IDBODEGA='01'
GROUP BY IMOVH.IDARTICULO,IART.DESCRIPCION )S ON E.IDARTICULO=S.IDARTICULO
WHERE CONVERT(INT,(E.CANTIDAD-COALESCE(S.CANTIDAD,0)))>0
GROUP BY  E.IDARTICULO,E.DESCRIPCION


