DECLARE @CNSPAGO VARCHAR(20)='01201911P30-1'

--select* 
update NEMPFD set VALOR_EMPRESA=az.vr_justar
from NEMPFD
inner join 
 (
 --pension---

SELECT CNSPAGO,NUMDOC, NOMBRE,COALESCE([001],0) SUELDO_BASICO,COALESCE([002],0) AUXILIO_DE_TRANSPORTE,
   round([006]+[007]+49,-2) total,round([006]+[007]+49 ,-2)-[006] vr_justar,'007' CODCONCEPTO
FROM (
   SELECT n.CNSPAGO,NEMP.NUMDOC,ISNULL(PRIMERAPELLIDO,'')+' '+ISNULL(SEGUNDOAPELLIDO,'')+' '+NEMP.PRIMERNOMBRE+' '+ISNULL(SEGUNDONOMBRE,'') NOMBRE,
      NCAR.DESCRIPCION CARGO, N.CODCONCEPTO, CONVERT(DECIMAL(14,1),COALESCE(VALOR,0)+COALESCE(VALOR_EMPRESA,0)) VALOR
   FROM NEMP INNER JOIN NCAR ON NEMP.CODCARGO=NCAR.CODCARGO
      INNER JOIN NEMPFD N ON NEMP.NUMDOC=N.NUMDOC AND N.CNSPAGO=@CNSPAGO
   WHERE ESTADO='ACTIVO' AND N.CODCONCEPTO IN ('001','002','006','007')
)SOURCE PIVOT(
   SUM(VALOR) FOR CODCONCEPTO IN ([001],[002],[006],[007])
)P
union all
--salud
--__________________________________________________________________
SELECT CNSPAGO,NUMDOC, NOMBRE,COALESCE([001],0) SUELDO_BASICO,COALESCE([002],0) AUXILIO_DE_TRANSPORTE,
   round([004]+[004-1]+49,-2) total,round([004]+[004-1]+49 ,-2)-[004] vr_justar,'004-1' CODCONCEPTO
FROM (
   SELECT n.CNSPAGO,NEMP.NUMDOC,ISNULL(PRIMERAPELLIDO,'')+' '+ISNULL(SEGUNDOAPELLIDO,'')+' '+NEMP.PRIMERNOMBRE+' '+ISNULL(SEGUNDONOMBRE,'') NOMBRE,
      NCAR.DESCRIPCION CARGO, N.CODCONCEPTO, CONVERT(DECIMAL(14,1),COALESCE(VALOR,0)+COALESCE(VALOR_EMPRESA,0)) VALOR
   FROM NEMP INNER JOIN NCAR ON NEMP.CODCARGO=NCAR.CODCARGO
      INNER JOIN NEMPFD N ON NEMP.NUMDOC=N.NUMDOC AND N.CNSPAGO=@CNSPAGO
   WHERE ESTADO='ACTIVO' AND N.CODCONCEPTO IN ('001','002','004','004-1')
)SOURCE PIVOT(
   SUM(VALOR) FOR CODCONCEPTO IN ([001],[002],[004],[004-1])
)P
union all

--arl
--__________________________________________________________________
SELECT CNSPAGO,NUMDOC, NOMBRE,COALESCE([001],0) SUELDO_BASICO,COALESCE([002],0) AUXILIO_DE_TRANSPORTE,
   round([013]+49,-2) total,round([013]+49 ,-2) vr_justar,'013' CODCONCEPTO
FROM (
   SELECT n.CNSPAGO,NEMP.NUMDOC,ISNULL(PRIMERAPELLIDO,'')+' '+ISNULL(SEGUNDOAPELLIDO,'')+' '+NEMP.PRIMERNOMBRE+' '+ISNULL(SEGUNDONOMBRE,'') NOMBRE,
      NCAR.DESCRIPCION CARGO, N.CODCONCEPTO, CONVERT(DECIMAL(14,1),COALESCE(VALOR,0)+COALESCE(VALOR_EMPRESA,0)) VALOR
   FROM NEMP INNER JOIN NCAR ON NEMP.CODCARGO=NCAR.CODCARGO
      INNER JOIN NEMPFD N ON NEMP.NUMDOC=N.NUMDOC AND N.CNSPAGO=@CNSPAGO
   WHERE ESTADO='ACTIVO' AND N.CODCONCEPTO IN ('001','002','013')
)SOURCE PIVOT(
   SUM(VALOR) FOR CODCONCEPTO IN ([001],[002],[013])
)P
union all

--ccf
--__________________________________________________________________
SELECT CNSPAGO,NUMDOC, NOMBRE,COALESCE([001],0) SUELDO_BASICO,COALESCE([002],0) AUXILIO_DE_TRANSPORTE,
   round([012]+49,-2) total,round([012]+49 ,-2) vr_justar,'012' CODCONCEPTO
FROM (
   SELECT n.CNSPAGO,NEMP.NUMDOC,ISNULL(PRIMERAPELLIDO,'')+' '+ISNULL(SEGUNDOAPELLIDO,'')+' '+NEMP.PRIMERNOMBRE+' '+ISNULL(SEGUNDONOMBRE,'') NOMBRE,
      NCAR.DESCRIPCION CARGO, N.CODCONCEPTO, CONVERT(DECIMAL(14,1),COALESCE(VALOR,0)+COALESCE(VALOR_EMPRESA,0)) VALOR
   FROM NEMP INNER JOIN NCAR ON NEMP.CODCARGO=NCAR.CODCARGO
      INNER JOIN NEMPFD N ON NEMP.NUMDOC=N.NUMDOC AND N.CNSPAGO=@CNSPAGO
   WHERE ESTADO='ACTIVO' AND N.CODCONCEPTO IN ('001','002','012')
)SOURCE PIVOT(
   SUM(VALOR) FOR CODCONCEPTO IN ([001],[002],[012])
)P
union all

--sena
--__________________________________________________________________
SELECT CNSPAGO,NUMDOC, NOMBRE,COALESCE([001],0) SUELDO_BASICO,COALESCE([002],0) AUXILIO_DE_TRANSPORTE,
   round([044]+49,-2) total,round([044]+49 ,-2) vr_justar,'044' CODCONCEPTO
FROM (
   SELECT n.CNSPAGO,NEMP.NUMDOC,ISNULL(PRIMERAPELLIDO,'')+' '+ISNULL(SEGUNDOAPELLIDO,'')+' '+NEMP.PRIMERNOMBRE+' '+ISNULL(SEGUNDONOMBRE,'') NOMBRE,
      NCAR.DESCRIPCION CARGO, N.CODCONCEPTO, CONVERT(DECIMAL(14,1),COALESCE(VALOR,0)+COALESCE(VALOR_EMPRESA,0)) VALOR
   FROM NEMP INNER JOIN NCAR ON NEMP.CODCARGO=NCAR.CODCARGO
      INNER JOIN NEMPFD N ON NEMP.NUMDOC=N.NUMDOC AND N.CNSPAGO=@CNSPAGO
   WHERE ESTADO='ACTIVO' AND N.CODCONCEPTO IN ('001','002','044')
)SOURCE PIVOT(
   SUM(VALOR) FOR CODCONCEPTO IN ([001],[002],[044])
)P
union all

--icbf
--__________________________________________________________________
SELECT CNSPAGO,NUMDOC, NOMBRE,COALESCE([001],0) SUELDO_BASICO,COALESCE([002],0) AUXILIO_DE_TRANSPORTE,
   round([045]+49,-2) total,round([045]+49 ,-2) vr_justar,'045' CODCONCEPTO
FROM (
   SELECT n.CNSPAGO,NEMP.NUMDOC,ISNULL(PRIMERAPELLIDO,'')+' '+ISNULL(SEGUNDOAPELLIDO,'')+' '+NEMP.PRIMERNOMBRE+' '+ISNULL(SEGUNDONOMBRE,'') NOMBRE,
      NCAR.DESCRIPCION CARGO, N.CODCONCEPTO, CONVERT(DECIMAL(14,1),COALESCE(VALOR,0)+COALESCE(VALOR_EMPRESA,0)) VALOR
   FROM NEMP INNER JOIN NCAR ON NEMP.CODCARGO=NCAR.CODCARGO
      INNER JOIN NEMPFD N ON NEMP.NUMDOC=N.NUMDOC AND N.CNSPAGO=@CNSPAGO
   WHERE ESTADO='ACTIVO' AND N.CODCONCEPTO IN ('001','002','045')
)SOURCE PIVOT(
   SUM(VALOR) FOR CODCONCEPTO IN ([001],[002],[045])
)P
) az
 on az.NUMDOC=NEMPFD.NUMDOC and az.CNSPAGO=NEMPFD.CNSPAGO and az.CODCONCEPTO=NEMPFD.CODCONCEPTO


