   INSERT INTO INVIHIS(CNSCIERRE, ANO, MES, FECHA, OBSERVACION, IDUSUARIO, ESTADO)
   SELECT '0100000002','2021',2,DBO.FNK_DIA_DEL_MES('2021',2,'ULTIMO'),'Historicos inventario periodo '+'2021'+' - '+CAST(2 as VARCHAR(2)),'JJIMENEZ','Abierto'

   ALTER TABLE INVIHISD DROP CONSTRAINT FK_INVIHISD_INVIHISDIDARTICULO

 --  INSERT INTO INVIHISD(CNSCIERRE,IDARTICULO, DESCARTICULO, FECHAMOV, IDTIPOMOV, DOCUMENTO, PCOSTO, EXISTANTES, ENTRADAS, SALIDAS, EXISTENCIA, PCOSTOFIN)
	--SELECT 'SI000001',IFISH.IDARTICULO,IART.DESCRIPCION,FECHA3,'SI','SALDOINI',IFISH.PCOSTO,0,CONTEO3,0,0,0
	--FROM IFISH INNER JOIN IART ON IFISH.IDARTICULO=IART.IDARTICULO WHERE CNSIFIS='0100000028'
	--AND CONTEO3>0

	INSERT INTO INVIHISD(CNSCIERRE,IDARTICULO, DESCARTICULO, FECHAMOV, IDTIPOMOV, DOCUMENTO, PCOSTO, EXISTANTES, ENTRADAS, SALIDAS, EXISTENCIA, PCOSTOFIN)
   SELECT '0100000002', MOV.IDARTICULO,MOV.DESCRIPCION,MOV.FECHAMOV,MOV.IDTIPOMOV,MOV.NODOCUMENTO,MOV.PCOSTO,EXISANTES,MOV.ENTRADAS,MOV.SALIDAS,MOV.EXISTENCIA,PCOSTOFIN
   FROM(
   SELECT IMOVH.IDARTICULO,IART.DESCRIPCION,IMOV.FECHAMOV,IMOV.IDTIPOMOV,NODOCUMENTO,IMOVH.PCOSTO,0 EXISANTES,IMOVH.CANTIDAD AS ENTRADAS,0 SALIDAS,0 EXISTENCIA,0 PCOSTOFIN
   FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
			    INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
			    INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
   WHERE IMOV.ESTADO=1
   AND IART.ESTADO='Activo'
   AND ITMO.TIPO='Credito'
   AND YEAR(IMOV.FECHAMOV)='2021'
   AND MONTH(IMOV.FECHAMOV)=2
   UNION ALL 
   SELECT ISAL.IDARTICULO,IART.DESCRIPCION,IMOV.FECHAMOV,IMOV.IDTIPOMOV,NODOCUMENTO,ISAL.PCOSTO,0,0,ISAL.CANTIDAD,0,0
   FROM IMOV INNER JOIN ISAL  ON IMOV.CNSMOV=ISAL.CNSMOV
			    INNER JOIN IART  ON ISAL.IDARTICULO=IART.IDARTICULO
			    INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV
   WHERE IMOV.ESTADO=1
   AND IART.ESTADO='Activo'
   AND ITMO.TIPO='Debito'
   AND YEAR(IMOV.FECHAMOV)='2021'
   AND MONTH(IMOV.FECHAMOV)=2
   )MOV
	WHERE  EXISTS(SELECT  * FROM IART WHERE IART.IDARTICULO=MOV.IDARTICULO)
	ORDER BY MOV.FECHAMOV ASC



   	DECLARE @IDARTICULO VARCHAR(20)

		DECLARE @MINITEM INT=1
		DECLARE @MAXITEM INT=0

		DECLARE @NOITEM INT
		DECLARE @PCOSTON DECIMAL(14,2)
		DECLARE @PCOSTOPM DECIMAL(14,2)
		DECLARE @CUMULADO INT=0
		DECLARE @CANTI INT
		DECLARE @TIPOMOV VARCHAR(10)
		DECLARE @ID INT
		

	DECLARE PG_CUR_INHIS CURSOR FOR   
	 SELECT IDARTICULO FROM INVIHISD WHERE CNSCIERRE= 'SI000001'
	 GROUP BY IDARTICULO
	 ORDER BY IDARTICULO 	
	OPEN PG_CUR_INHIS    
	FETCH NEXT FROM PG_CUR_INHIS    
	INTO @IDARTICULO
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
		DECLARE @ITEMS TABLE (ID INT IDENTITY(1,1),NOITEM INT,PCOSTO DECIMAL(14,2),TIPOMOV VARCHAR(4),CANTIDAD INT)--SELECT * FROM INVIHISD
		INSERT INTO @ITEMS
		SELECT NOITEM,PCOSTO,CASE WHEN ENTRADAS>0 THEN 'ENT' ELSE 'SALI' END, CASE WHEN ENTRADAS>0 THEN ENTRADAS ELSE SALIDAS END
		FROM INVIHISD
		WHERE CNSCIERRE='SI000001'
		AND IDARTICULO=@IDARTICULO
		ORDER BY  NOITEM
		SELECT @MAXITEM=MAX(ID),@MINITEM=1 FROM @ITEMS

		WHILE @MINITEM<=@MAXITEM
		BEGIN 
			SELECT @NOITEM=NOITEM,@PCOSTON=PCOSTO,@CANTI=CANTIDAD,@TIPOMOV=TIPOMOV FROM @ITEMS WHERE ID=@MINITEM
			IF @MINITEM=1
			BEGIN 
				SELECT @PCOSTOPM=@PCOSTON,@CUMULADO=@CANTI
				UPDATE INVIHISD SET EXISTANTES=0,EXISTENCIA=CASE WHEN @TIPOMOV='ENT' THEN @CUMULADO ELSE @CUMULADO END, PCOSTOFIN=@PCOSTOPM WHERE NOITEM=@NOITEM
			END
			ELSE 
			BEGIN
				UPDATE INVIHISD SET EXISTANTES=@CUMULADO,EXISTENCIA=CASE WHEN @TIPOMOV='ENT' THEN @CUMULADO+ENTRADAS ELSE @CUMULADO-SALIDAS END,
				PCOSTOFIN=CASE WHEN @TIPOMOV='ENT' THEN (((@CUMULADO*@PCOSTOPM)+(ENTRADAS*PCOSTO))/@CUMULADO+ENTRADAS) ELSE @PCOSTOPM END
				WHERE NOITEM=@NOITEM

				SELECT @PCOSTOPM=PCOSTOFIN,@CUMULADO=EXISTENCIA FROM INVIHISD WHERE  NOITEM=@NOITEM

			END
			SELECT @MINITEM=@MINITEM+1
		END
	FETCH NEXT FROM PG_CUR_INHIS    
	INTO @IDARTICULO
	END
	CLOSE PG_CUR_INHIS
	DEALLOCATE PG_CUR_INHIS
