IF EXISTS ( SELECT * FROM SYSOBJECTS WHERE name = 'SPK_NHC_ABANDONAR_HC' AND type = 'P')
BEGIN
   DROP PROCEDURE SPK_NHC_ABANDONAR_HC
END
GO
CREATE PROCEDURE DBO.SPK_NHC_ABANDONAR_HC
@CONSECUTIVO    VARCHAR(13)  
WITH ENCRYPTION
AS
DECLARE @ITEMRED INT , @CODOM VARCHAR(10), @IDSERVICIO VARCHAR(20)
BEGIN
   INSERT INTO JHC(CONSECUTIVO,FECHA,EQUIPO,SESION,PROCEDENCIA)
   SELECT @CONSECUTIVO,GETDATE(),HOST_NAME(),SUSER_NAME(),'KRYSTALOS'
   DECLARE TD_C CURSOR FOR
   SELECT ITEMRED, CODOM, IDSERVICIO FROM HCATD WHERE CONSECUTIVO = @CONSECUTIVO
   OPEN TD_C
   FETCH NEXT FROM TD_C
   INTO  @ITEMRED, @CODOM, @IDSERVICIO
   WHILE @@FETCH_STATUS = 0             
   BEGIN       
      DELETE HCATD WHERE CONSECUTIVO = @CONSECUTIVO AND ITEMRED = @ITEMRED AND CODOM = @CODOM AND IDSERVICIO = @IDSERVICIO
      FETCH NEXT FROM TD_C
      INTO  @ITEMRED, @CODOM, @IDSERVICIO
   END
   CLOSE TD_C
   DEALLOCATE TD_C
   DELETE HCAT WHERE CONSECUTIVO = @CONSECUTIVO
   DELETE HCADL WHERE CONSECUTIVO = @CONSECUTIVO
   --ALTER TABLE HCAD DISABLE TRIGGER ALL
   DELETE HCAD WHERE CONSECUTIVO = @CONSECUTIVO
   DELETE HCASER WHERE CONSECUTIVO = @CONSECUTIVO
   DELETE HCAPM WHERE CONSECUTIVO = @CONSECUTIVO
   DELETE HCA WHERE CONSECUTIVO = @CONSECUTIVO
   ALTER TABLE HCAD ENABLE TRIGGER ALL
END

---TRIGGER 

/***********************************************************************************/
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_JHCAD_BORRADO' AND TYPE = 'TR')
   DROP TRIGGER TK_JHCAD_BORRADO
GO
/***********************************************************************************/
CREATE TRIGGER DBO.TK_JHCAD_BORRADO
ON HCAD
FOR DELETE
AS
   DECLARE @CONSECUTIVO VARCHAR(20) 
   DECLARE @PROCEDENCIA VARCHAR (10)
   
   SELECT @CONSECUTIVO=CONSECUTIVO FROM INSERTED 
   SELECT @PROCEDENCIA=PROCEDENCIA FROM JHC WHERE CONSECUTIVO=@CONSECUTIVO
   IF @PROCEDENCIA<>'KRYSTALOS'
   BEGIN 
      INSERT INTO JHCAD
      SELECT * FROM HCAD WHERE CONSECUTIVO=@CONSECUTIVO
      INSERT INTO JHCA
      SELECT * FROM HCA WHERE CONSECUTIVO=@CONSECUTIVO      
   END
GO 
/***********************************************************************************/
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_JHCADL_BORRADO' AND TYPE = 'TR')
   DROP TRIGGER TK_JHCADL_BORRADO
GO
/***********************************************************************************/
CREATE TRIGGER DBO.TK_JHCADL_BORRADO
ON HCADL
FOR DELETE
AS
   DECLARE @CONSECUTIVO VARCHAR(20) 
   DECLARE @PROCEDENCIA VARCHAR (10)
   
   SELECT @CONSECUTIVO=CONSECUTIVO FROM INSERTED 
   SELECT @PROCEDENCIA=PROCEDENCIA FROM JHC WHERE CONSECUTIVO=@CONSECUTIVO
   IF @PROCEDENCIA<>'KRYSTALOS'
   BEGIN 
      INSERT INTO JHCADL
      SELECT * FROM HCADL WHERE CONSECUTIVO=@CONSECUTIVO      
   END
GO 