SELECT 
   '2' TIPO,
   ROW_NUMBER() OVER (ORDER BY X.MES, X.IDARTICULO) CNS,
   RIGHT('0'+CONVERT(VARCHAR(2),X.MES),2) MES,
      COALESCE((CASE WHEN COALESCE(IART.CODCUM,'')='' OR LEN(REPLACE(IART.CODCUM,' ',''))<6  THEN NULL ELSE IART.CODCUM END),
               (CASE WHEN COALESCE( SER.CODCUM,'')='' OR LEN(REPLACE( SER.CODCUM,' ',''))<6  THEN NULL ELSE  SER.CODCUM END),
               '') CODCUM,
   X.VLR_MIN, 
   X.VLR_MAX, 
   X.VLR_TOTAL,
   X.CANTIDAD,
   (SELECT MAX(FCOM.N_FACTURA)
   FROM IMOV 
      INNER JOIN FCOMD ON FCOMD.CNSFCOM=IMOV.CNSFCOM
      INNER JOIN FCOM  ON FCOMD.CNSFCOM=FCOM.CNSFCOM
   WHERE COALESCE(IMOV.ESTADO,0)=1 AND CONVERT(DATE,IMOV.FECHACONF) BETWEEN @1FINI AND @2FFIN
      AND IMOV.IDTIPOMOV=DBO.FNK_VALORVARIABLE('IDINVMOV_COMPRAS')
      AND FCOMD.VR_UNITMASIVA=X.VLR_MIN
   ) FMIN,
   (SELECT MAX(FCOM.N_FACTURA)
   FROM IMOV 
      INNER JOIN FCOMD ON FCOMD.CNSFCOM=IMOV.CNSFCOM
      INNER JOIN FCOM  ON FCOMD.CNSFCOM=FCOM.CNSFCOM
   WHERE COALESCE(IMOV.ESTADO,0)=1 AND CONVERT(DATE,IMOV.FECHACONF) BETWEEN @1FINI AND @2FFIN
      AND IMOV.IDTIPOMOV=DBO.FNK_VALORVARIABLE('IDINVMOV_COMPRAS')
      AND FCOMD.VR_UNITMASIVA=X.VLR_MAX
   ) FMAX,
   X.IDARTICULO,
   IART.DESCRIPCION
FROM (
   SELECT IMOVH.IDARTICULO, SUM(IMOVH.CANTIDAD) CANTIDAD, MIN(IMOVH.PCOSTO) VLR_MIN, MAX(IMOVH.PCOSTO) VLR_MAX, SUM(IMOVH.PCOSTO) VLR_TOTAL, MONTH(IMOV.FECHACONF) MES
   FROM IMOV INNER JOIN IMOVH ON IMOVH.CNSMOV=IMOV.CNSMOV
   WHERE COALESCE(IMOV.ESTADO,0)=1 AND COALESCE(IMOVH.ESTADO,0)<>2
      AND CONVERT(DATE,IMOV.FECHACONF) BETWEEN @1FINI AND @2FFIN
      AND IMOV.IDTIPOMOV=DBO.FNK_VALORVARIABLE('IDINVMOV_COMPRAS')
   GROUP BY IMOVH.IDARTICULO, MONTH(IMOV.FECHACONF)
)X LEFT JOIN IART ON IART.IDARTICULO=X.IDARTICULO
   LEFT JOIN SER  ON IART.IDSERVICIO=SER.IDSERVICIO
   LEFT JOIN (SELECT ROW_NUMBER() OVER (PARTITION BY IDSERVICIO ORDER BY IDARTICULO) CNS, IDARTICULO IDARTICULOP, IDSERVICIO 
               FROM IART WHERE PRINCIPAL=1
               )I ON I.IDSERVICIO=IART.IDSERVICIO AND I.CNS=1
WHERE IART.IDSERVICIO<>DBO.FNK_VALORVARIABLE('DEINVNODESER') AND COALESCE(SER.MEDICAMENTOS,0)=1
ORDER BY TIPO, CNS