DECLARE @1FECHAINI DATETIME ='01/09/2019'
DECLARE @2FECHAFIN DATETIME ='30/09/2019'


SELECT '2',ROW_NUMBER() OVER(ORDER  BY ENTREGAS.CODCUM   DESC) NRO,MONTH(CAST(@1FECHAINI AS DATETIME) ),'INS','SI', ENTREGAS.CODCUM,ENTREGAS.VLRMIN,ENTREGAS.VLRMAX,ENTREGAS.VLVENTA,
ENTREGAS.CANTIDAD,
(SELECT TOP 1 FTRD.N_FACTURA
		FROM IMOVH INNER JOIN HPRED ON IMOVH.NOPRESTACION=HPRED.NOPRESTACION 
										AND IMOVH.IDARTICULO=HPRED.IDARTICULO
					INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
					INNER JOIN FTRD  ON HPRED.NOPRESTACION=FTRD.NOPRESTACION 
										AND HPRED.NOITEM=FTRD.NOITEM
					INNER JOIN FTR   ON FTRD.N_FACTURA=FTR.N_FACTURA
					INNER JOIN SER   ON HPRED.IDSERVICIO=SER.IDSERVICIO
		WHERE FTR.F_FACTURA>=@1FECHAINI 
		AND FTR.F_FACTURA<@2FECHAFIN 
		AND COALESCE(SER.MEDICAMENTOS,0)=1
		AND IMOVH.IDARTICULO=ENTREGAS.IDARTICULO
		AND IART.CODCUM=ENTREGAS.CODCUM
		ORDER BY FTRD.VALOR ASC ) FACTURAMIN,
      (SELECT TOP 1 FTRD.N_FACTURA
		FROM IMOVH INNER JOIN HPRED ON IMOVH.NOPRESTACION=HPRED.NOPRESTACION 
										AND IMOVH.IDARTICULO=HPRED.IDARTICULO
					INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
					INNER JOIN FTRD  ON HPRED.NOPRESTACION=FTRD.NOPRESTACION 
										AND HPRED.NOITEM=FTRD.NOITEM
					INNER JOIN FTR   ON FTRD.N_FACTURA=FTR.N_FACTURA
					INNER JOIN SER   ON HPRED.IDSERVICIO=SER.IDSERVICIO
		WHERE FTR.F_FACTURA>=@1FECHAINI 
		AND FTR.F_FACTURA<@2FECHAFIN 
		AND COALESCE(SER.MEDICAMENTOS,0)=1
		AND imovh.IDARTICULO=ENTREGAS.IDARTICULO
		AND IART.CODCUM=ENTREGAS.CODCUM
		ORDER BY FTRD.VALOR DESC ) 		FTRMAX,ENTREGAS.IDARTICULO,IART.DESCRIPCION
FROM (
SELECT SALIDAS.IDARTICULO,SALIDAS.CODCUM,MINMAX.VLRMIN,MINMAX.VLRMAX,SALIDAS.CANTIDAD,SALIDAS.CANTIDAD*PVENTA.PVENTA AS VLVENTA
FROM
	(SELECT IMOVH.IDARTICULO, IART.CODCUM,CONVERT(INT,SUM(IMOVH.CANTIDAD))CANTIDAD
	FROM IMOVH INNER JOIN HPRED ON IMOVH.NOPRESTACION=HPRED.NOPRESTACION 
								AND IMOVH.IDARTICULO=HPRED.IDARTICULO
		   INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
	       INNER JOIN FTRD  ON HPRED.NOPRESTACION=FTRD.NOPRESTACION 
						     AND HPRED.NOITEM=FTRD.NOITEM
		   INNER JOIN FTR   ON FTRD.N_FACTURA=FTR.N_FACTURA
		   INNER JOIN SER   ON HPRED.IDSERVICIO=SER.IDSERVICIO
WHERE FTR.F_FACTURA>=@1FECHAINI  
AND FTR.F_FACTURA<@2FECHAFIN  
AND COALESCE(SER.MEDICAMENTOS,0)=1
GROUP BY IMOVH.IDARTICULO, IART.CODCUM 
) SALIDAS INNER JOIN (
							SELECT IMOVH.IDARTICULO, IART.CODCUM,MIN(FTRD.VALOR)VLRMIN,MAX(FTRD.VALOR)VLRMAX
							FROM IMOVH INNER JOIN HPRED ON IMOVH.NOPRESTACION=HPRED.NOPRESTACION 
															AND IMOVH.IDARTICULO=HPRED.IDARTICULO
									   INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
									   INNER JOIN FTRD  ON HPRED.NOPRESTACION=FTRD.NOPRESTACION 
														 AND HPRED.NOITEM=FTRD.NOITEM
									   INNER JOIN FTR   ON FTRD.N_FACTURA=FTR.N_FACTURA
									   INNER JOIN SER   ON HPRED.IDSERVICIO=SER.IDSERVICIO
							WHERE FTR.F_FACTURA>=@1FECHAINI  
							AND FTR.F_FACTURA<@2FECHAFIN 
							AND COALESCE(SER.MEDICAMENTOS,0)=1
							AND FTRD.VALOR>0
							GROUP BY IMOVH.IDARTICULO, IART.CODCUM ) MINMAX ON SALIDAS.IDARTICULO=MINMAX.IDARTICULO
			INNER JOIN (
							SELECT IMOVH.IDARTICULO, IART.CODCUM,CONVERT(DECIMAL(14,2),AVG(HPRED.VALOR))PVENTA
							FROM IMOVH INNER JOIN HPRED ON IMOVH.NOPRESTACION=HPRED.NOPRESTACION 
															AND IMOVH.IDARTICULO=HPRED.IDARTICULO
									   INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
									   INNER JOIN FTRD  ON HPRED.NOPRESTACION=FTRD.NOPRESTACION 
														 AND HPRED.NOITEM=FTRD.NOITEM
									   INNER JOIN FTR   ON FTRD.N_FACTURA=FTR.N_FACTURA
									   INNER JOIN SER   ON HPRED.IDSERVICIO=SER.IDSERVICIO
							WHERE FTR.F_FACTURA>=@1FECHAINI  
							AND FTR.F_FACTURA<@2FECHAFIN 
							AND COALESCE(SER.MEDICAMENTOS,0)=1
							AND FTRD.VALOR>0
							GROUP BY IMOVH.IDARTICULO, IART.CODCUM
							) PVENTA ON SALIDAS.IDARTICULO=PVENTA.IDARTICULO
							) ENTREGAS INNER JOIN IART ON ENTREGAS.IDARTICULO=IART.IDARTICULO
ORDER BY ROW_NUMBER() OVER(ORDER  BY  ENTREGAS.CODCUM   DESC)
