IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SPK_CIERRERECIBO_CAJA_PPTO' AND type = 'P')
   DROP PROCEDURE SPK_CIERRERECIBO_CAJA_PPTO

GO
CREATE PROCEDURE  DBO.SPK_CIERRERECIBO_CAJA_PPTO  
@CODCAJA          VARCHAR(4),
@CNSFACJ          VARCHAR(20),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5), 
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)
WITH ENCRYPTION
AS  
DECLARE @OK               INT
DECLARE @CLASER           VARCHAR(1)
DECLARE @TIPOPAGO         VARCHAR(3)
DECLARE @VALOR            DECIMAL(14,2)
DECLARE @TIPO             VARCHAR(7)
DECLARE @PROCEDENCIA      VARCHAR(10)
DECLARE @DATO             VARCHAR(80)
DECLARE @DATO1            VARCHAR(80)
DECLARE @ESTADO           VARCHAR(1) 
DECLARE @IDAFILIADO       VARCHAR(20)
DECLARE @NVOVONSEC        VARCHAR(20)
DECLARE @NVOCONSEC1       VARCHAR(20)
DECLARE @NVOCONSEC2       VARCHAR(20)
DECLARE @CNSACJ           VARCHAR(20)
DECLARE @CNSPCJ           VARCHAR(20)
DECLARE @ABIERTA          SMALLINT
DECLARE @VALORTOTAL       DECIMAL(14,2)
DECLARE @DOC1             VARCHAR(16)
DECLARE @DOC2             VARCHAR(16) 
DECLARE @CLASE_FAC        VARCHAR(5)
DECLARE @IDTERCERO        VARCHAR(20)
DECLARE @TIPOEGRESO       VARCHAR(8)
DECLARE @DATO2            VARCHAR(80)
DECLARE @DATO3            VARCHAR(80)
DECLARE @DATO4            VARCHAR(80)
DECLARE @DATO5            VARCHAR(80)
DECLARE @DATO6            VARCHAR(80)
DECLARE @DATO7            VARCHAR(80)
DECLARE @CPRECTRAS        VARCHAR(80)
DECLARE @DATOCHQ          VARCHAR(80)
DECLARE @DATOEFE          VARCHAR(80)
DECLARE @DATOAPE          VARCHAR(80)
DECLARE @DATON            VARCHAR(80)
DECLARE @DATOCATCAJA      VARCHAR(80)
DECLARE @BANCO            VARCHAR(3)
DECLARE @SUCURSAL         VARCHAR(2)
DECLARE @CTA_BCO          VARCHAR(40)
DECLARE @CSGBANCO         VARCHAR(3)
DECLARE @CSGSUCURSAL      VARCHAR(2)
DECLARE @CSGCTA_BCO       VARCHAR(40)
DECLARE @CNSDOC           VARCHAR(20)
DECLARE @NUMERODOCUMENTO  VARCHAR(20)   
DECLARE @NODOCUMENTO      VARCHAR(20)   
DECLARE @N_RECIBO         VARCHAR(20)
DECLARE @CODCAJADEP       VARCHAR(5)
DECLARE @CNSFACJDEP       VARCHAR(20)
DECLARE @DEAPERTURA       SMALLINT
DECLARE @ITEMBMOV         INT 
DECLARE @IDOPERACION      VARCHAR(20)
DECLARE @RENGLON          SMALLINT
DECLARE @CCOSTO           VARCHAR(20)
DECLARE @IDAREA           VARCHAR(20)
DECLARE @CUENTA           VARCHAR(16)
DECLARE @FECHA            DATETIME
DECLARE @CNSFCXP          VARCHAR(20)
DECLARE @CNSCXC           VARCHAR(20)
DECLARE @CONCEPTO         VARCHAR(10)
DECLARE @IDTERCERO_CXP    VARCHAR(20)
DECLARE @VALOR_CXP        DECIMAL (14,2)
DECLARE @F_VENCE          DATETIME
DECLARE @NOMBRECLIENTE    VARCHAR(40)
DECLARE @OBSERVACION      VARCHAR(255) 
DECLARE @DOCORIGEN        INT 
DECLARE @NVOCONSEC        VARCHAR(20)
DECLARE @ITEM             INT
DECLARE @CODIGOCPCJ       VARCHAR(20)
DECLARE @DATOCEHOSP       VARCHAR(80)
DECLARE @DEVDOC           VARCHAR(20)
DECLARE @NROCOMPROBANTE   VARCHAR(20)
DECLARE @RECBCO           INT
DECLARE @BANCO2           VARCHAR(3)
DECLARE @SUCURSAL2        VARCHAR(2)
DECLARE @CTA_BCO2         VARCHAR(20)
DECLARE @DEVREC           VARCHAR(20)
DECLARE @CODCAJA_DEV      VARCHAR(4)
DECLARE @CNSFACJ_DEV      VARCHAR(20)
DECLARE @PROC_DEV         VARCHAR(10)
DECLARE @NOADMISION_DEV   VARCHAR(20)
DECLARE @NOPRESTACION_DEV VARCHAR(20)
DECLARE @CONSECUTIVOCAN   VARCHAR (20)
DECLARE @VALORTOTAL1      DECIMAL(14,2)
DECLARE @IDTERCERO1       VARCHAR(20)
DECLARE @NOINGRESODEPORI  VARCHAR(16)
DECLARE @VALORDEPORI      DECIMAL(14,2)
DECLARE @TRASACAJA        VARCHAR(80) 
DECLARE @VALORREINTEGRO   DECIMAL(14,2)
DECLARE @G_REINT          SMALLINT
DECLARE @NVOCONSECTFCJ    VARCHAR(20)
DECLARE @CNSPCJAUX        VARCHAR(20)  
DECLARE @TOTREINTEGRO     DECIMAL(14,2)
DECLARE @CNSCXP           VARCHAR(20) --PPTO
DECLARE @CNSPPTO          VARCHAR(20) --PPTO
DECLARE @CNSCDP           VARCHAR(20) --PPTO
DECLARE @CNSRP            VARCHAR(20) --PPTO
DECLARE @CNSPAGO          VARCHAR(20) --PPTO
DECLARE @FPAGO            DATETIME    --PPTO
DECLARE @PBANCO           VARCHAR(20) --PPTO
DECLARE @PCUENTA          VARCHAR(20) --PPTO
DECLARE @PSUCURSAL        VARCHAR(20) --PPTO
DECLARE @PFORMA           VARCHAR(20) --PPTO
DECLARE @PCCOSTO          VARCHAR(20) --PPTO
DECLARE @DESFORMA         VARCHAR(50) --PPTO
DECLARE @PDOCUMENTO       VARCHAR(20) --PPTO
DECLARE @ESPART           BIT          --PPTO
DECLARE @PABONO           DECIMAL(14,2) --PPTO
DECLARE @OBSERVACIONPPTO  VARCHAR(500)  --PPTO
DECLARE @CONSECUTIVO      VARCHAR(20)
DECLARE @RUBRO            VARCHAR(20)
DECLARE @RECO             VARCHAR(20)
DECLARE @CCOSTOPRESUP     VARCHAR(20)
DECLARE @RECA             VARCHAR(20)
DECLARE @SI               SMALLINT
DECLARE @DATOPAGARE       VARCHAR (80)
DECLARE @CNSFCXPCJM VARCHAR(20)   --REEMBOLSO CAJA MENOR
DECLARE @RESPONCJM  VARCHAR(20)   --REEMBOLSO CAJA MENOR
DECLARE @CAJAMENOR  VARCHAR(4)    --REEMBOLSO CAJA MENOR
DECLARE @VLRPAGOCJM DECIMAL(14,2) --REEMBOLSO CAJA MENOR
DECLARE @CNSFCXPPM  VARCHAR(20)   --REEMBOLSO CAJA MENOR
DECLARE @AUX INT
DECLARE @PCJTERCERO  VARCHAR(20) --PGA.CXC=1
DECLARE @PCJTIPOPAGO VARCHAR(10) --PGA.CXC=1
DECLARE @VALORTPAGO  DECIMAL(14,2) --PGA.CXC=1
DECLARE @CNSDOCPCJ   VARCHAR(20) --PGA.CXC=1
DECLARE @FACTURADOC  VARCHAR(20) --PGA.CXC=1
DECLARE @CNSPCJPAGO  VARCHAR(20) --PGA.CXC=1
DECLARE @CUENTAPCJ   VARCHAR(20) --PGA.CXC=1
BEGIN
   PRINT 'REVISO SI ES COPAGO ENVIO A PRESUPUESTO'
   PRINT 'VOY A PRESUPUESTO'
   SELECT @ESPART=0
	IF DBO.FNK_VALORVARIABLE('PRESUP_CXC_ACTIVADO')='SI'
	BEGIN
      IF DBO.FNK_VALORVARIABLE('PPTO_CUOTASCOPAGO')='SI' AND @ESPART=0
      BEGIN
         PRINT 'Empiezo...........'
         IF (SELECT COUNT(*) FROM MOCC INNER JOIN FCJD ON MOCC.CODIGOCPCJ=FCJD.CONCEPTO 
               WHERE FCJD.CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ)>0
         BEGIN
            SELECT @CCOSTOPRESUP = DBO.FNK_VALORVARIABLE('PRESUP_CCOSTO')
            SELECT @CONSECUTIVO=CONSECUTIVO FROM PTPTO WHERE FECHAINI<=GETDATE() AND FECHAFIN>GETDATE()
            SELECT @RUBRO=RUBRO FROM MOCC INNER JOIN FCJD ON MOCC.CODIGOCPCJ=FCJD.CONCEPTO 
               WHERE FCJD.CODCAJA=@CODCAJA AND CNSFACJ=@CNSFACJ
                  
            PRINT 'SE REALIZA EL INSERT DE LOS COPAGOS Y CUOTAS MODERADORAS' 
            SELECT @RECO = ISNULL(CONTADOR_RR,0) + 1 
            FROM   PTPTO 
            WHERE  COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO
		           
            SELECT @RECO = @SEDE + REPLACE(SPACE(8 - LEN(@RECO))+LTRIM(RTRIM(@RECO)),SPACE(1),0) 

            PRINT '@RECO :::: '+@RECO
		                     
            INSERT INTO PTRECO(COMPANIA, CONSECUTIVO, RECO, OBJETIVO, VALOR, CNSFCXC, IDTERCERO, FECHA, ESTADO, CCOSTO, N_FACTURA, CNSFTR,TIPO)
            SELECT DISTINCT '01', @CONSECUTIVO, @RECO, 'RECUDOS DE CUOTAS MODERADORAS Y COPAGOS ' +
		            ' DURANTE  EL MES DE ' + CASE MONTH(FCJ.FECHA) WHEN 1  THEN 'ENERO'   WHEN 2  THEN 'FEBRERO'   WHEN 3  THEN 'MARZO'
				   										            WHEN 4  THEN 'ABRIL'   WHEN 5  THEN 'MAYO'      WHEN 6  THEN 'JUNIO'
				   										            WHEN 7  THEN 'JULIO'   WHEN 8  THEN 'AGOSTO'    WHEN 9  THEN 'SEPTIEMBRE'
				   										            WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE'
				   				            END,
		            FCJD.VALORTOTAL, FCJD.CNSFACJ, FCJ.IDAFILIADO,FCJ.FECHA, 'NoConfirmado', @CCOSTOPRESUP, FCJ.CNSFACJ, FCJ.CODCAJA,'Suma'
            FROM   FCJ  INNER JOIN FCJD ON FCJ.CNSFACJ=FCJD.CNSFACJ AND FCJ.CODCAJA=FCJD.CODCAJA
                           INNER JOIN MOCC ON MOCC.CODIGOCPCJ=FCJD.CONCEPTO 
            WHERE  FCJD.CNSFACJ = @CNSFACJ 
            AND    FCJD.CODCAJA = @CODCAJA
		           
            UPDATE PTPTO SET CONTADOR_RR = ISNULL(CONTADOR_RR,0) + 1 
            WHERE  COMPANIA    = @COMPANIA 
            AND    CONSECUTIVO = @CONSECUTIVO
		           
            INSERT INTO PTRECOD (COMPANIA, CONSECUTIVO, RECO, CLASE, RUBRO, OBJETIVO, VALOR ) 
            SELECT DISTINCT @COMPANIA, @CONSECUTIVO, @RECO, 'Ingreso', @RUBRO,' RECUDOS DE CUOTAS MODERADORAS Y COPAGOS DURANTE  EL MES DE  ' + CASE MONTH(FCJ.FECHA) WHEN 1  THEN 'ENERO'   
                                                         WHEN 2  THEN 'FEBRERO'   WHEN 3  THEN 'MARZO'
				   										            WHEN 4  THEN 'ABRIL'   WHEN 5  THEN 'MAYO'      WHEN 6  THEN 'JUNIO'
				   										            WHEN 7  THEN 'JULIO'   WHEN 8  THEN 'AGOSTO'    WHEN 9  THEN 'SEPTIEMBRE'
				   										            WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE'
				   				            END +' DEL A?O:'+ CAST(YEAR(FCJ.FECHA) AS VARCHAR (5)),
		            FCJD.VALORTOTAL 
            FROM   FCJ  INNER JOIN FCJD ON FCJ.CNSFACJ=FCJD.CNSFACJ AND FCJ.CODCAJA=FCJD.CODCAJA
                           INNER JOIN MOCC ON MOCC.CODIGOCPCJ=FCJD.CONCEPTO 
            WHERE  FCJD.CNSFACJ = @CNSFACJ 
            AND    FCJD.CODCAJA = @CODCAJA  
 
            UPDATE PTRECO SET ESTADO = 'Confirmado' 
            WHERE  RECO        = @RECO
            AND    COMPANIA    = @COMPANIA
            AND    CONSECUTIVO = @CONSECUTIVO   

            SELECT @RECA = ISNULL(CONTADOR_RRR,0) + 1 
            FROM   PTPTO 
            WHERE  COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO
                  
            SELECT @RECA = @SEDE + REPLACE(SPACE(8 - LEN(@RECA))+LTRIM(RTRIM(@RECA)),SPACE(1),0) 
            PRINT '@RECA .... .'+@RECA
            INSERT INTO PTRECA (COMPANIA, CONSECUTIVO, RECO, CNSPAGO, OBSERVACION, VALOR, FECHA, ORIGENPAGO, CODCAJA, CNSFACJ,
							            BANCO, SUCURSAL, CTA_BCO, ITEM_BMOV, ESTADO, CCOSTO)
            SELECT DISTINCT @COMPANIA, @CONSECUTIVO, @RECO, @RECA,FCJ.OBSERVACION, FCJD.VALORTOTAL, FCJ.FECHA, 
                     'CAJA',@CODCAJA,@CNSFACJ,'','','','', 'NoConfirmado', @CCOSTOPRESUP
            FROM   FCJ  INNER JOIN FCJD ON FCJ.CNSFACJ=FCJD.CNSFACJ AND FCJ.CODCAJA=FCJD.CODCAJA
                           INNER JOIN MOCC ON MOCC.CODIGOCPCJ=FCJD.CONCEPTO 
            WHERE  FCJD.CNSFACJ = @CNSFACJ 
            AND    FCJD.CODCAJA = @CODCAJA  
                  
            UPDATE PTPTO SET CONTADOR_RRR = ISNULL(CONTADOR_RRR,0) + 1 
            WHERE  COMPANIA    = @COMPANIA
            AND    CONSECUTIVO = @CONSECUTIVO
                                                       
            INSERT INTO PTRECAD (COMPANIA, CONSECUTIVO, RECO, CNSPAGO, CLASE, RUBRO, OBSERVACION, VALOR )
            SELECT DISTINCT @COMPANIA, @CONSECUTIVO, @RECO, @RECA, 'Ingreso', @RUBRO, FCJ.OBSERVACION, FCJD.VALORTOTAL
            FROM   FCJ  INNER JOIN FCJD ON FCJ.CNSFACJ=FCJD.CNSFACJ AND FCJ.CODCAJA=FCJD.CODCAJA
                           INNER JOIN MOCC ON MOCC.CODIGOCPCJ=FCJD.CONCEPTO 
            WHERE  FCJD.CNSFACJ = @CNSFACJ 
            AND    FCJD.CODCAJA = @CODCAJA         

            UPDATE PTRECA SET ESTADO = 'Confirmado' 
            WHERE  RECO        = @RECO
            AND    COMPANIA    = @COMPANIA
            AND    CONSECUTIVO = @CONSECUTIVO 
            AND    CNSPAGO     = @RECA

         END
      END
   END              
END