/*********************************************************************/
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_CONTAB_RADICACXC_1' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_CONTAB_RADICACXC_1
END
GO
-- ------------------------------------------------------------------------------------
CREATE PROCEDURE DBO.SPK_CONTAB_RADICACXC_1 
@CNSCXC            VARCHAR(20),
@COMPANIA          VARCHAR(2),
@SEDE              VARCHAR(5),
@USUARIO           VARCHAR(12),
@SYS_COMPUTERNAME  VARCHAR(512),
@NROCOMPROBANTE    VARCHAR(20)
--WITH ENCRYPTION
AS
DECLARE @ANO    VARCHAR(5)
DECLARE @MES    INT
DECLARE @COM     VARCHAR(5)
DECLARE @IDMODELOCONT    VARCHAR(2)
DECLARE @PREFIJO_USCXS   VARCHAR(10)
DECLARE @NOREFERENCIA    VARCHAR(20)
DECLARE @PROCEDENCIA     VARCHAR(20)
DECLARE @OBSERVACION     VARCHAR(255)
DECLARE @IDTERCERO       VARCHAR(50)
DECLARE @N_FACTURA1      VARCHAR(16)
DECLARE @DONDE           INT
BEGIN
 --CAPTURO DATOS PARA MCP --SELECT TOP 10 * FROM FCXC WHERE INDRECIBIDO=1
 
   SELECT @ANO=YEAR(F_RECIBIDO),@MES=MONTH(F_RECIBIDO),@IDTERCERO=IDTERCERO FROM FCXC WHERE CNSCXC=@CNSCXC
   SELECT  @COM=DBO.FNK_VALORVARIABLE('IDCON_TCOM_RADICA')
   SELECT @OBSERVACION='REGISTRAMOS RADICACION DE FACTURAS A: '+RAZONSOCIAL+' CXC No.: '+@CNSCXC FROM TER WHERE IDTERCERO=@IDTERCERO
   
 --  SELECT FCXCD.N_FACTURA,ISNULL(TTEC.CUENTARAD,'CUE NO DEF')CUENTARAD INTO #TTEC
	--FROM FCXCD INNER JOIN FTR  ON FCXCD.N_FACTURA=FTR.N_FACTURA
	--           INNER JOIN TTEC ON FTR.TIPOTTEC=TTEC.TIPO		         
	--WHERE  FCXCD.CNSCXC=@CNSCXC 
	--GROUP BY FCXCD.N_FACTURA,TTEC.CUENTARAD
	
   PRINT 'CREANDO NUEVO MCP'            
   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA = @COMPANIA AND ANO=@ANO AND MES=@MES)
   BEGIN
      PRINT CAST(@ANO AS VARCHAR(4))+CAST(@MES AS VARCHAR(3))
      RAISERROR('EL PERIODO CONTABLE NO EXISTEN', 16, 1)
      RETURN
   END
   IF EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA = @COMPANIA AND ANO=@ANO AND MES=@MES AND COALESCE(CERRADO,0)=1)
   BEGIN
      PRINT CAST(@ANO AS VARCHAR(4))+CAST(@MES AS VARCHAR(3))
      RAISERROR('EL PERIODO ACTUAL CERRADO', 16, 1)
      RETURN
   END
   /***************************************************************************************************************/
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
   /***************************************************************************************************************/
   PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   IF ISNULL(@NROCOMPROBANTE,'') = '' -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   BEGIN
   	   
      SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	  PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	  SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	  PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	  --GENERO EL CONSECUTIVO DEL TIPO DE COMPROBANTE
   	  SET @PREFIJO_USCXS='@COM'+@COM
   	  SET @NOREFERENCIA=SPACE(20)
        
   	  EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
   	  SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
   	  PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
   	  PRINT 'Comprobante Contable (MCP)'
   	  
      INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                    TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                    COMPROBANTE, IDTERCERO, ANULADO )
      SELECT @NROCOMPROBANTE, @COMPANIA, 'RAD CXC', @NOREFERENCIA, @ANO, @MES,DBO.FNK_FECHA_SIN_HORA(F_RECIBIDO) ,
             0, 0,@CNSCXC, LEFT(QUIENRECIBIO,19), @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL,@OBSERVACION, 
             @SEDE, 0, @COM, IDTERCERO,0 FROM FCXC WHERE CNSCXC=@CNSCXC
   	  
   END	 
   SELECT @DONDE=COUNT(*) FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   IF @DONDE>0
   BEGIN
      INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
      SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                       REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                       RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
      FROM   MCP 
      WHERE NROCOMPROBANTE = @NROCOMPROBANTE
      --se borran de mcp, mch
      DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
      DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE   
   END
   DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   PRINT 'INSERTANDO MCHE CR'
      
   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA, TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
   	  					    REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
      					    N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
      SELECT @NROCOMPROBANTE,@COMPANIA,'CR', B.CUENTACXC, B.IDTERCERO,'',@OBSERVACION,B.VR_TOTAL,A.CNSCXC,
	  	       NULL,0,@USUARIO,dbo.FNK_FECHA_SIN_MLS(GETDATE()),NULL,NULL,'P',0,'RADCXC_CR','Movimiento',A.N_FACTURA,
	   	       B.F_FACTURA,B.F_VENCE,'RADCXC_CR','RADCXC_CR',NULL,B.CODUNG,B.CODPRG
	  FROM   FCXCD A INNER JOIN FTR    B ON A.N_FACTURA=B.N_FACTURA
	  WHERE  A.CNSCXC = @CNSCXC
      
   PRINT 'INSERTANDO MCHE DB'
	  	
   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
	  					    REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
	  					    N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
	  SELECT @NROCOMPROBANTE,@COMPANIA,'DB',B.CUENTACXC_RAD,B.IDTERCERO,'',@OBSERVACION,B.VR_TOTAL,A.CNSCXC,
	  	       NULL,0,@USUARIO,dbo.FNK_FECHA_SIN_MLS(GETDATE()),NULL,NULL,'P',0,'RADCXC_CR','Movimiento',A.N_FACTURA,
	  	       B.F_FACTURA,B.F_VENCE,'RADCXC_DB','RADCXC_DB',NULL,B.CODUNG,B.CODPRG
	  FROM   FCXCD A INNER JOIN FTR B ON A.N_FACTURA=B.N_FACTURA
	  WHERE  A.CNSCXC = @CNSCXC 
	 	--BORRAMOS LA TEMPORAL	
   
   EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME 	    
   EXEC SPK_SUMA_DBCR @NROCOMPROBANTE
        	
   UPDATE FCXC SET CONTABILIZADA=1,NROCOMPROBANTE=@NROCOMPROBANTE WHERE CNSCXC=@CNSCXC   
   

        
END
GO