DECLARE 
 @CNSMOV            VARCHAR(20),   
 @USUARIO           VARCHAR(12),  
 @SYS_COMPUTERNAME  VARCHAR(254),  
 @COMPANIA          VARCHAR(2),   
 @SEDE              VARCHAR(5),  
 @NROCOMPROBANTE    VARCHAR(20),
 @ANO               VARCHAR(4),
 @MES               INT
 
--SELECT TOP 10 SEDE, * FROM IMOV

   DECLARE MCP_RECONSTRUYE CURSOR FOR
   SELECT CNSMOV,USUARIOCONF,SYS_COMPUTERNAME,'01','01',COALESCE(NROCOMPROBANTE,'') FROM IMOV
   WHERE SECONTABILIZA=1 AND COALESCE(NROCOMPROBANTE,'')=''  AND ESTADO=1 AND
   YEAR(FECHACONF)='2013' AND MONTH(FECHACONF)=5
   GROUP BY  CNSMOV,USUARIOCONF,SYS_COMPUTERNAME,COALESCE(NROCOMPROBANTE,'')   
   OPEN MCP_RECONSTRUYE    
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   WHILE @@FETCH_STATUS = 0    
   BEGIN
       PRINT 'EMPEZANDO....'+@CNSMOV
       EXEC SPK_NC_CONTAB_INV  @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE 
       EXEC SPK_REVISAR_COMPROBANTE '01',@NROCOMPROBANTE
       EXEC SPK_SUMA_DBCR @NROCOMPROBANTE    
   FETCH NEXT FROM MCP_RECONSTRUYE    
   INTO @CNSMOV,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@SEDE,@NROCOMPROBANTE
   END
   CLOSE MCP_RECONSTRUYE
   DEALLOCATE MCP_RECONSTRUYE