IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SPK_BALANCEO_CENTAVOS_MCH' AND type = 'P')
BEGIN
   DROP PROCEDURE SPK_BALANCEO_CENTAVOS_MCH
END
GO
CREATE PROCEDURE  DBO.SPK_BALANCEO_CENTAVOS_MCH
@NROCOMPROBANTE VARCHAR(20)
AS
DECLARE @N_FACTURA VARCHAR(20)
DECLARE @CBTE   VARCHAR(20)
DECLARE @MES    INT
DECLARE @COMPROBANTE VARCHAR(4)
DECLARE @COMPANIA    VARCHAR(2)
DECLARE @ANO         VARCHAR(4)
DECLARE @SEDE        VARCHAR(5)
DECLARE @DIFERENCIA DECIMAL(14,2)
BEGIN
   SELECT @COMPANIA=COMPANIA,@COMPROBANTE=COMPROBANTE,@ANO=ANO,@MES=MES 
   FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTE

   SELECT @DIFERENCIA = TOTALDEBITO - TOTALCREDITO 
   FROM  MCPE 
   WHERE COMPROBANTE = @COMPROBANTE AND COMPANIA=@COMPANIA
   AND MES =@MES AND ANO = @ANO
   AND NROCOMPROBANTE = @NROCOMPROBANTE

   IF @DIFERENCIA < 0
   BEGIN
      SELECT @CBTE = MIN( MCHE.NROASIENTO) FROM MCHE WHERE TIPO = 'DB'
      AND COMPANIA =@COMPANIA AND MCHE.NROCOMPROBANTE = @NROCOMPROBANTE
		 
      UPDATE  MCHE
      SET MCHE.VALOR = MCHE.VALOR + (@DIFERENCIA * -1)
      WHERE MCHE.COMPANIA =@COMPANIA 
      AND MCHE.NROASIENTO      IN (@CBTE)
   END
   IF @DIFERENCIA > 0
   BEGIN
      SELECT @CBTE = MIN(MCHE.NROASIENTO) FROM MCHE WHERE TIPO = 'CR'
      AND COMPANIA =@COMPANIA AND MCHE.NROCOMPROBANTE = @NROCOMPROBANTE
		
      UPDATE  MCHE
      SET MCHE.VALOR = MCHE.VALOR + (@DIFERENCIA)
      WHERE MCHE.COMPANIA =@COMPANIA 
      AND MCHE.NROASIENTO      IN (@CBTE)
   END
END
