IF OBJECT_ID('SPK_RECONTRUYE_CXP_COMPRAS','P') IS NOT NULL DROP PROCEDURE SPK_RECONTRUYE_CXP_COMPRAS
GO
CREATE PROCEDURE DBO.SPK_RECONTRUYE_CXP_COMPRAS
	@CNSMOV           VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @ENCONTRADO    DECIMAL(9,2)
DECLARE @AFECTACOSTO   SMALLINT
DECLARE @CNSITRA       VARCHAR(20)
DECLARE @S             VARCHAR(1)
DECLARE @CNS           VARCHAR(20)
DECLARE @LONG          SMALLINT
DECLARE @P             SMALLINT
DECLARE @CONTADOR      SMALLINT  
DECLARE @CNSFCOM       VARCHAR(20)
DECLARE @CNSCTZ        VARCHAR(20)
DECLARE @IDTERCERO     VARCHAR(20)
DECLARE @IDITAR        VARCHAR(2)
DECLARE @IDTIPOMOV     VARCHAR(2)
DECLARE @SECONTABILIZA SMALLINT
DECLARE @CNSFCXP       VARCHAR(20)
DECLARE @CNSFNOT       VARCHAR(20)
DECLARE @IDCATEGORIA   VARCHAR(10) 

DECLARE @NOLOTE_CUR_DETALLE       VARCHAR(20)
DECLARE @IDARTICULO_CUR_DETALLE   VARCHAR(20)
DECLARE @CANTIDAD_CUR_DETALLE     DECIMAL(14,2)
DECLARE @PCOSTO_CUR_DETALLE       DECIMAL(16,3)
DECLARE @FECHAVENCE_CUR_DETALLE   DATETIME
DECLARE @NOLOTEPEDIDO_CUR_DETALLE VARCHAR(20)
DECLARE @DETALLE_CUR_DETALLE      VARCHAR(254)    
DECLARE @CNSFCOM_CUR_DETALLE      VARCHAR(20)  
DECLARE @TIPOACTIVO        VARCHAR(80)    
DECLARE @IDACTIVO          VARCHAR(20)    
DECLARE @VECES             DECIMAL(14,2)    
DECLARE @CANTIDAD          DECIMAL(14,2)    
DECLARE @IDARTICULO        VARCHAR(20)    
DECLARE @DESCRIPCION       VARCHAR(512)    
DECLARE @PCOSTO            DECIMAL(16,3)    
DECLARE @IDEVENTO          VARCHAR(10)    
DECLARE @CNSIACTH          VARCHAR(20)    
DECLARE @IDESTADOPENDIENTE VARCHAR(20)
DECLARE @NOLOTE            VARCHAR(20)
DECLARE @CCOSTO            VARCHAR(20) 
DECLARE @IDAREA            VARCHAR(20)
DECLARE @VIDAUTIL          INT
DECLARE @NODOCUMENTO       VARCHAR(20)
DECLARE @CUENTA            VARCHAR(16)
DECLARE @ESTADO            INT
DECLARE @NROCOMPROBANTE    VARCHAR(20)
DECLARE @FECHAMOV          DATETIME
DECLARE @TIPOBODEGA        VARCHAR(20)
DECLARE @ANO               VARCHAR(10) 
DECLARE @MES               VARCHAR(10) 
DECLARE @CERRADO           VARCHAR(10)       
DECLARE @EXCEPCION_CONT    INT
DECLARE @T_ANTICIPOS       DECIMAL(14,2)
DECLARE @CNSANT            VARCHAR(20)
DECLARE @ESTADO_ANT        VARCHAR(1)
DECLARE @RINVIMA           VARCHAR(20)
DECLARE @SELLOCALIDAD      VARCHAR(20)
DECLARE @CAPACIDAD         DECIMAL(14,2)
DECLARE @VLR_ANT_LEGAL	   DECIMAL(14,2)
DECLARE @VL_SALDO		   DECIMAL(14,2)
DECLARE 	
   @IDBODEGA         VARCHAR(20),
	@USUARIO          VARCHAR(12),
	@COMPANIA         VARCHAR(2),
	@SEDE             VARCHAR(5),
	@SYS_COMPUTERNAME VARCHAR(255)
DECLARE @IDINVMOV_COMPRAS VARCHAR(20) 
DECLARE @IDINVMOV_REMISION_EN VARCHAR(20) 
DECLARE @IDINVMOV_SI VARCHAR(20) 
DECLARE @CODBARRAS_AUT_ENT VARCHAR(20)
DECLARE @DEPURAR BIT
BEGIN
   SELECT @IDINVMOV_COMPRAS = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVMOV_COMPRAS'


	SELECT @AFECTACOSTO = ITMO.AFECTACOSTO, @IDTIPOMOV=IMOV.IDTIPOMOV, @SECONTABILIZA=IIF(ISNULL(IBOD.NOCONTABILIZA,0)=1,0,ITMO.SECONTABILIZA),
			@NROCOMPROBANTE = IMOV.NROCOMPROBANTE,  @TIPOBODEGA = IBOD.TIPOBODEGA
			,@IDTERCERO=IMOV.IDTERCERO,@FECHAMOV = FECHAMOV, @ESTADO=IMOV.ESTADO, @IDTIPOMOV=IMOV.IDTIPOMOV,
         @IDBODEGA=IMOV.IDBODEGA,
         @USUARIO=IMOV.FECHACONF,
         @COMPANIA='01',
         @SEDE='01',
         @SYS_COMPUTERNAME=IMOV.SYS_COMPUTERNAME
	FROM IMOV 
	INNER JOIN IBOD ON IBOD.IDBODEGA  = IMOV.IDBODEGA 
	INNER JOIN ITMO ON ITMO.IDTIPOMOV = IMOV.IDTIPOMOV
	WHERE  IMOV.CNSMOV=@CNSMOV

	IF @IDTIPOMOV = @IDINVMOV_COMPRAS -- AND @SECONTABILIZA=1 --JEDM 28.06.2010
	BEGIN
		SET @CNSFCXP=SPACE(20)  
		EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FCXPCM',@CNSFCXP OUTPUT
		SELECT @CNSFCXP = @SEDE + 'CM' + REPLACE(SPACE(6 - LEN(@CNSFCXP))+LTRIM(RTRIM(@CNSFCXP)),SPACE(1),0)
        
		SELECT TOP 1 @IDITAR = IART.IDITAR 
		FROM   IMOVH INNER JOIN IART ON IMOVH.IDARTICULO = IART.IDARTICULO
		WHERE  IMOVH.CNSMOV  = @CNSMOV

       
		INSERT INTO FCXP (CNSFCXP, FECHA, CNSFCOM, IDTERCERO, NOREFERENCIA, F_FACTURAREF, F_VENCE, VALOR, ESTADO,
	  						F_CANCELADO, USUARIO, PROCEDENCIA, OBSERVACION, COMPANIA, SYS_ComputerName, USUARIOMOD,
  							FECHAMOD, NUMCUOTA, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, SALDO, IDCLASEIMP,
						VLR_DESCUENTO, VLR_IVA,VLR_NETO,VLR_IMPUESTOS,CUEDEBITO,CUECREDITO,TIPOCXP,VLR_GLOSAS,VLR_FLETE,
						MODALIDAD, SUBSIDIO, CODUNG, CODPRG, DOCEQUIVALENTE)
		SELECT @CNSFCXP,IMOV.FECHAMOV,IMOV.CNSFCOM,IMOV.IDTERCERO,IMOV.NODOCUMENTO,IMOV.F_FACTURA,IMOV.F_VENCE,
				0,'N',NULL,@USUARIO,'Compras','Compra a '+TER.RAZONSOCIAL+' Ref. '+IMOV.NODOCUMENTO,
				@COMPANIA,@SYS_COMPUTERNAME, NULL, NULL, 0, 0, 0, '', 0, NULL, 0, 0, 0, 0, NULL,
				DBO.FNK_CUENTA_KMCOM(DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE'),'CXP_COMPRAS','CR', @IDITAR,IMOV.IDAREA,IMOV.CCOSTO,'P',''),
				DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT'), 0, IMOV.VLR_FLETE, 'Evento', 'Total', IMOV.CODUNG, IMOV.CODPRG,
				CASE WHEN TER.TIPOREGIMEN='S' THEN 1 ELSE 0 END
		FROM   IMOV INNER JOIN TER ON TER.IDTERCERO = IMOV.IDTERCERO
		WHERE  IMOV.CNSMOV=@CNSMOV 
     
		SET @IDCATEGORIA=(SELECT DBO.FNK_VALORVARIABLE('TERCATPROVEEDOR'))
      
      UPDATE IMOVH SET ESTADO=9 WHERE CNSMOV=@CNSMOV 

		EXEC SPK_INSERT_CXP_INV @CNSFCXP, @CNSMOV,'COMPRAS'
		EXEC SPK_IMPUESTOS_CXP @CNSFCXP,'PRO',@COMPANIA,@SEDE

		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- ACTUALIZACION DE CXP CON ANTICIPO'

       UPDATE IMOVH SET ESTADO=1 WHERE CNSMOV=@CNSMOV 

      EXEC SPK_CALCULOVALORESCXP @CNSFCXP

		SELECT @CNSFCOM = CNSFCOM FROM IMOV WHERE CNSMOV = @CNSMOV
		SELECT @T_ANTICIPOS = COALESCE(SUM(VALOR), 0) FROM FCXP WHERE CNSFCOM = @CNSFCOM AND PROCEDENCIA = 'Anticipos' AND ESTADO<>'A'
      SELECT @VLR_ANT_LEGAL =COALESCE(SUM(VALOR_LEG),0) FROM ANT WHERE CNSFCOM=@CNSFCOM AND ESTADO<>'A'
      SELECT @VL_SALDO=COALESCE(SALDO,0) FROM FCXP WHERE CNSFCXP=@CNSFCXP
      IF @VLR_ANT_LEGAL IS NULL
      SET @VLR_ANT_LEGAL=0
      IF @VL_SALDO IS NULL
      SET @VL_SALDO=0


      PRINT '@T_ANTICIPOS='+STR(@T_ANTICIPOS)
      PRINT '@VLR_ANT_LEGAL='+STR(@VLR_ANT_LEGAL)
      PRINT '@VL_SALDO='+STR(@VL_SALDO)

      SELECT @T_ANTICIPOS=COALESCE(@T_ANTICIPOS,0)-COALESCE(@VLR_ANT_LEGAL,0)

      IF @VL_SALDO<@T_ANTICIPOS
      BEGIN
         SELECT @T_ANTICIPOS=@VL_SALDO
      END

		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @CNSFCOM = '+@CNSFCOM
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @T_ANTICIPOS = '+CONVERT(VARCHAR(20),@T_ANTICIPOS)
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @CNSFCXP = '+@CNSFCXP

      IF @T_ANTICIPOS IS NULL
      BEGIN 
         SELECT @T_ANTICIPOS=0
      END
		UPDATE FCXP SET VLR_ABONOS = VLR_ABONOS+@T_ANTICIPOS WHERE CNSFCXP = @CNSFCXP
        
		IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- RECALCULO VALORES DE CXP'


		IF @T_ANTICIPOS > 0
		BEGIN
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- LEGALIZANDO ANTICIPO '
			SET @CNSANT=SPACE(20)  
			EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@NAT',@CNSANT OUTPUT
			SELECT @CNSANT = @SEDE + 'CM' + REPLACE(SPACE(6 - LEN(@CNSANT))+LTRIM(RTRIM(@CNSANT)),SPACE(1),0)
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @CNSANT = '+@CNSANT

			INSERT INTO ANT (CNSANT, CNSFCOM, DESCRIPCION, FECHA, VALORCXP, VALOR_LEG, NOREFERENCIA, F_FACTURAREF, F_VENCE, USUARIO, 
							ESTADO, CNSFCXP, CONTABILIZADO, NROCOMPROBANTE)
			SELECT @CNSANT, @CNSFCOM, 'Legalización A: '+TER.RAZONSOCIAL+' Ref. '+FCXP.NOREFERENCIA, GETDATE(), @T_ANTICIPOS, @T_ANTICIPOS, FCXP.NOREFERENCIA,
					FCXP.F_FACTURAREF, FCXP.F_VENCE, @USUARIO, 'I', @CNSFCXP, 0, ''
			FROM FCXP INNER JOIN TER ON TER.IDTERCERO = FCXP.IDTERCERO
			WHERE FCXP.CNSFCXP = @CNSFCXP
          
			SELECT @ESTADO_ANT = ESTADO FROM ANT WHERE CNSANT = @CNSANT
			IF @DEPURAR = 1 PRINT CONVERT(VARCHAR,GETDATE(),108)+'.- @ESTADO_ANT = '+@ESTADO_ANT

			IF @ESTADO_ANT = 'I'
			BEGIN
				EXEC SPK_ANTICIPO_LEG_CXP @CNSFCOM, @CNSANT, @COMPANIA, @USUARIO, @SEDE
			END
		END
      EXEC SPK_CALCULOVALORESCXP @CNSFCXP
	END
END
