CREATE OR ALTER PROCEDURE DBO.SPK_GENHPRE_DIARIO
@NOADMISION    VARCHAR(16),
@FECHAINI      DATETIME,
@FECHAFIN      DATETIME,
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA         VARCHAR(2),
@SEDE		         VARCHAR(5)
AS
DECLARE @NOPRESTACION_NUEVA VARCHAR(16)
DECLARE @CONSECUTIVO VARCHAR(16)
DECLARE @CONSECUTIVO_NUEVO VARCHAR(16)
DECLARE @NVO_NOITEM  SMALLINT
DECLARE @FECHAA DATETIME
DECLARE @HPRED TABLE (
	[NOPRESTACION] [varchar](16) NOT NULL,
	[NOITEM] [smallint] NOT NULL,
	[IDSERVICIO] [varchar](20) NULL,
	[CANTIDAD] [decimal](18, 6) NULL,
	[VALOR] [decimal](18, 6) NULL,
	[VALORCOPAGO] [decimal](14, 2) NULL,
	[VALOREXCEDENTE] [decimal](18, 6) NULL,
	[IDPLAN] [varchar](6) NULL,
	[IMPRESO] [smallint] NULL,
	[AUTORIZADO] [smallint] NULL,
	[COMENTARIOS] [varchar](2048) NULL,
	[IDPROVEEDOR] [varchar](20) NULL,
	[IDCONCEPTORIPS] [varchar](2) NULL,
	[AMBITO] [varchar](1) NULL,
	[FINALIDAD] [varchar](2) NULL,
	[PERSONAL_AT] [varchar](1) NULL,
	[DXPPAL] [varchar](10) NULL,
	[DXRELACIONADO] [varchar](10) NULL,
	[COMPLICACION] [varchar](10) NULL,
	[FORMAQX] [varchar](1) NULL,
	[VALORPCOMP] [decimal](14, 2) NULL,
	[USUARIO] [varchar](12) NULL,
	[UTISOAT] [smallint] NULL,
	[VLRFALTAAPLICARSOAT] [decimal](18, 6) NULL,
	[CONSECUTIVOCX] [varchar](13) NULL,
	[ITEMCIRUGIA] [smallint] NULL,
	[IDCIRUGIA] [varchar](20) NULL,
	[TIPOSERCIRUGIA] [varchar](13) NULL,
	[FACTURADA] [smallint] NULL,
	[N_FACTURA] [varchar](16) NULL,
	[VLRAPLICADO1] [decimal](18, 6) NULL,
	[VLRAPLICADO2] [decimal](18, 6) NULL,
	[CANTIDADORIGINAL] [decimal](18, 6) NULL,
	[CANTIDADDEVUELTA] [decimal](18, 6) NULL,
	[CNSIDEV] [varchar](20) NULL,
	[INDDEVOLUCION] [smallint] NULL,
	[INDDEVAPLICADA] [smallint] NULL,
	[USUARIODEV] [varchar](8) NULL,
	[NOCOBRABLE] [smallint] NULL,
	[PCOSTO] [decimal](18, 6) NULL,
	[CXP] [smallint] NULL,
	[FECHA] [datetime] NULL,
	[VIA] [varchar](2) NULL,
	[IDAREAH] [varchar](20) NULL,
	[IDAREA] [varchar](20) NULL,
	[NIVELATENCION] [varchar](5) NULL,
	[PEDIDOINV] [smallint] NULL,
	[NOLOTE] [varchar](20) NULL,
	[COBRARA] [varchar](1) NULL,
	[IDTERCEROCA] [varchar](20) NULL,
	[PCUBRIMIENTO] [decimal](7, 2) NULL,
	[TIPODTO] [varchar](1) NULL,
	[DESCUENTO] [decimal](14, 2) NULL,
	[NORDEN] [varchar](20) NULL,
	[VALORTOTALCOSTO] [decimal](14, 2) NULL,
	[CCOSTO] [varchar](20) NULL,
	[ENLAB] [smallint] NULL,
	[CNSMOV] [varchar](20) NULL,
	[AUTORIZACION] [varchar](20) NULL,
	[AQUIENCOBRO] [varchar](1) NULL,
	[NOAUTORIZACION] [varchar](20) NULL,
	[CODPRG] [varchar](20) NULL,
	[IDCONTRATO] [varchar](20) NULL,
	[ITFC] [smallint] NULL,
	[CNSITFC] [varchar](20) NULL,
	[IDTARIFA] [varchar](5) NULL,
	[CODIFICACION] [varchar](20) NULL,
	[GRUPOQX_UVR_CX] [decimal](14, 2) NULL,
	[CODCUPS] [varchar](20) NULL,
	[CODUNG] [varchar](2) NULL,
	[SINCRONIZADO] [smallint] NULL,
	[ANULADO] [smallint] NULL,
	[MANUAL] [smallint] NULL,
	[APOYODG_AMBITO] [varchar](2) NULL,
	[PAQUETE] [smallint] NULL,
	[ITEM_RPDX] [int] NULL,
	[ENCARGOS] [tinyint] NULL,
	[VALORCOPAGONORMAL] [decimal](14, 2) NULL,
	[VALORCOPAGOEXTERNO] [decimal](14, 2) NULL,
	[MARCA] [tinyint] NULL,
	[USUARIOMARCA] [varchar](12) NULL,
	[ITEM_HCASER] [int] NULL,
	[NUM_ORDEN] [int] NULL,
	[IDARTICULO] [varchar](20) NULL,
	[CNSHBALI] [varchar](20) NULL,
	[NCONSECUTIVO] [int] NULL,
	[NTIPO] [int] NULL,
	[CLASEOM] [varchar](20) NULL,
	[ESTADOAPLICACION] [smallint] NULL,
	[HORA] [smallint] NULL,
	[AUDITADO] [smallint] NULL,
	[AUDITOR] [varchar](20) NULL,
	[IDSERVICIOH] [varchar](20) NULL,
	[VLRSERVICIOH] [decimal](14, 2) NULL,
	[N_FACTURAH] [varchar](16) NULL,
	[CANTIDADH] [decimal](14, 2) NULL,
	[NPRESTACIONH] [varchar](20) NULL,
	[NOITEMH] [smallint] NULL,
	[NOPOSHOM] [smallint] NULL,
	[IDTERCEROH] [varchar](20) NULL,
	[CODCUMIPRES] [varchar](20) NULL,
	[FECHASOL] [datetime] NULL,
	[CODIGOCUM] [varchar](20) NULL,
	[EQUIPOMUES] [varchar](10) NULL,
	[DESC_EQUIPOMUES] [varchar](100) NULL,
	[CNSCONTENEDOR] [varchar](16) NULL,
	[VIVACOPA] [decimal](14, 2) NULL,
	[VIVATCOPA] [decimal](14, 2) NULL,
	[VIVATVENTA] [decimal](14, 2) NULL,
	[PVENTAT] [decimal](14, 2) NULL,
	[CNSPRELIQ] [varchar](20) NULL)
DECLARE @HPRE TABLE(
	[NOPRESTACION] [varchar](16) NOT NULL,
	[NOADMISION] [varchar](16) NULL,
	[FECHA] [datetime] NULL,
	[IDPLAN] [varchar](6) NULL,
	[IDAREAH] [varchar](20) NULL,
	[NIVELATENCION] [varchar](5) NULL,
	[IDAREA] [varchar](20) NULL,
	[IDSEDE] [varchar](5) NULL,
	[ALTOCOSTO] [varchar](2) NULL,
	[NO_ITEMES] [smallint] NULL,
	[VALORTOTAL] [decimal](14, 2) NULL,
	[VALORCOPAGO] [decimal](14, 2) NULL,
	[VALOREXEDENTE] [decimal](14, 2) NULL,
	[IMPRESO] [smallint] NULL,
	[AUTORIZADOPOR] [varchar](12) NULL,
	[NUMAUTORIZA] [varchar](16) NULL,
	[FECHAAUTORIZA] [datetime] NULL,
	[AUTORIZADO] [smallint] NULL,
	[USUARIO] [varchar](12) NULL,
	[CERRADA] [smallint] NULL,
	[VALORPCOMP] [decimal](14, 2) NULL,
	[CIRUGIA] [varchar](2) NULL,
	[PCUBRIMIENTO] [decimal](7, 2) NULL,
	[CLASEORDEN] [varchar](10) NULL,
	[CONSECUTIVO] [varchar](13) NULL,
	[ESDEINV] [smallint] NULL,
	[PEDIDOINV] [smallint] NULL,
	[CNSMOV] [varchar](20) NULL,
	[INDDEVOLUCION] [smallint] NULL,
	[PREFIJO] [varchar](6) NULL,
	[CCOSTO] [varchar](20) NULL,
	[SUBCCOSTO] [varchar](4) NULL,
	[FINALIDAD] [varchar](2) NULL,
	[AMBITO] [varchar](1) NULL,
	[PERSONAL_AT] [varchar](1) NULL,
	[DXPPAL] [varchar](10) NULL,
	[DXRELACIONADO] [varchar](10) NULL,
	[COMPLICACION] [varchar](10) NULL,
	[FORMAQX] [varchar](1) NULL,
	[ESCONSULTA] [smallint] NULL,
	[IDAREAEQUIPO] [varchar](20) NULL,
	[IMPRESOP] [smallint] NULL,
	[IDMEDICO] [varchar](12) NULL,
	[COBRARA] [varchar](1) NULL,
	[IDTERCEROCA] [varchar](20) NULL,
	[CONSECUTIVOHCA] [varchar](13) NULL,
	[ITEMRED] [int] NULL,
	[ENLAB] [smallint] NULL,
	[ITFC] [smallint] NULL,
	[CNSITFC] [varchar](20) NULL,
	[SYS_COMPUTERNAME] [varchar](254) NULL,
	[CNSLABCOR] [varchar](20) NULL,
	[CODEVAL] [varchar](20) NULL,
	[IDAREAAUX] [varchar](20) NULL,
	[INDLABCORE] [smallint] NULL,
	[CCOSTOAUX] [varchar](20) NULL,
	[CONTABILIZADA] [smallint] NULL,
	[NROCOMPROBANTE] [varchar](20) NULL,
	[MARCACONT] [smallint] NULL,
	[NOPLANTILLA] [varchar](10) NULL,
	[SINCRONIZADO] [smallint] NULL,
	[ANULADO] [smallint] NULL,
	[PROCEDENCIA] [varchar](20) NULL,
	[VALIDADO] [smallint] NULL,
	[TIPOHISTORIA] [varchar](1) NULL,
	[CODOM] [varchar](10) NULL,
	[CONTABNIIF] [smallint] NULL,
	[NROCOMPROBANTENIIF] [varchar](20) NULL,
	[REVAUD] [smallint] NULL,
	[USUREVAUD] [varchar](20) NULL,
	[F_REVAUD] [datetime] NULL,
	[FECHA_SH] [date] NULL,
	[COMERCIAL] [varchar](2) NULL)
BEGIN
   
INSERT INTO @HPRE(
	 NOPRESTACION, NOADMISION, FECHA, IDPLAN, IDAREAH, NIVELATENCION, IDAREA, IDSEDE, ALTOCOSTO, NO_ITEMES, VALORTOTAL, VALORCOPAGO, 
          VALOREXEDENTE, IMPRESO, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA,  AUTORIZADO, USUARIO, CERRADA, VALORPCOMP, CIRUGIA, PCUBRIMIENTO,
          CLASEORDEN, CONSECUTIVO, ESDEINV, PEDIDOINV, CNSMOV, INDDEVOLUCION, PREFIJO, CCOSTO, SUBCCOSTO, FINALIDAD,  AMBITO, PERSONAL_AT, DXPPAL,
          DXRELACIONADO, COMPLICACION, FORMAQX, ESCONSULTA, IDAREAEQUIPO, IMPRESOP, IDMEDICO, COBRARA, IDTERCEROCA, CONSECUTIVOHCA, ITEMRED, ENLAB,
          ITFC,  CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, CODEVAL, IDAREAAUX, INDLABCORE, CCOSTOAUX, CONTABILIZADA, NROCOMPROBANTE, MARCACONT, NOPLANTILLA,
          SINCRONIZADO, ANULADO, PROCEDENCIA, VALIDADO,  TIPOHISTORIA, CODOM, CONTABNIIF, NROCOMPROBANTENIIF, REVAUD, USUREVAUD, F_REVAUD, FECHA_SH, 
          COMERCIAL)
	SELECT NOPRESTACION, NOADMISION, FECHA, IDPLAN, IDAREAH, NIVELATENCION, IDAREA, IDSEDE, ALTOCOSTO, NO_ITEMES, VALORTOTAL, VALORCOPAGO, 
          VALOREXEDENTE, IMPRESO, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA,  AUTORIZADO, USUARIO, CERRADA, VALORPCOMP, CIRUGIA, PCUBRIMIENTO,
          CLASEORDEN, CONSECUTIVO, ESDEINV, PEDIDOINV, CNSMOV, INDDEVOLUCION, PREFIJO, CCOSTO, SUBCCOSTO, FINALIDAD,  AMBITO, PERSONAL_AT, DXPPAL,
          DXRELACIONADO, COMPLICACION, FORMAQX, ESCONSULTA, IDAREAEQUIPO, IMPRESOP, IDMEDICO, COBRARA, IDTERCEROCA, CONSECUTIVOHCA, ITEMRED, ENLAB,
          ITFC,  CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, CODEVAL, IDAREAAUX, INDLABCORE, CCOSTOAUX, CONTABILIZADA, NROCOMPROBANTE, MARCACONT, NOPLANTILLA,
          SINCRONIZADO, ANULADO, PROCEDENCIA, VALIDADO,  TIPOHISTORIA, CODOM, CONTABNIIF, NROCOMPROBANTENIIF, REVAUD, USUREVAUD, F_REVAUD, FECHA_SH, 
          COMERCIAL 
	FROM   HPRE 
   WHERE  NOADMISION ='0100000833' AND NOPRESTACION='0100088888'

   INSERT INTO @HPRED(
               NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALOREXCEDENTE, IDPLAN, IMPRESO, AUTORIZADO, COMENTARIOS, IDPROVEEDOR, 
                IDCONCEPTORIPS, AMBITO, FINALIDAD, PERSONAL_AT,  DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX, VALORPCOMP, USUARIO, UTISOAT, 
                VLRFALTAAPLICARSOAT, CONSECUTIVOCX, ITEMCIRUGIA, IDCIRUGIA, TIPOSERCIRUGIA, FACTURADA, N_FACTURA, VLRAPLICADO1,  VLRAPLICADO2, 
                CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION, INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, PCOSTO, CXP, FECHA, VIA, 
                IDAREAH, IDAREA, NIVELATENCION,  PEDIDOINV, NOLOTE, COBRARA, IDTERCEROCA, PCUBRIMIENTO, TIPODTO, DESCUENTO, NORDEN, VALORTOTALCOSTO,
                CCOSTO, ENLAB, CNSMOV, AUTORIZACION, AQUIENCOBRO, NOAUTORIZACION, CODPRG, IDCONTRATO,  ITFC, CNSITFC, IDTARIFA, CODIFICACION, 
                GRUPOQX_UVR_CX, CODCUPS, CODUNG, SINCRONIZADO, ANULADO, [MANUAL], APOYODG_AMBITO, PAQUETE, ITEM_RPDX, ENCARGOS, VALORCOPAGONORMAL, 
                VALORCOPAGOEXTERNO,  MARCA, USUARIOMARCA, ITEM_HCASER, NUM_ORDEN, IDARTICULO, CNSHBALI, NCONSECUTIVO, NTIPO, CLASEOM, ESTADOAPLICACION,
                HORA, AUDITADO, AUDITOR, IDSERVICIOH, VLRSERVICIOH,  N_FACTURAH, CANTIDADH, NPRESTACIONH, NOITEMH, NOPOSHOM, IDTERCEROH, CODCUMIPRES,
                FECHASOL, CODIGOCUM, EQUIPOMUES, DESC_EQUIPOMUES, CNSCONTENEDOR, VIVACOPA, VIVATCOPA, VIVATVENTA,  PVENTAT, CNSPRELIQ   )
   SELECT NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALOREXCEDENTE, IDPLAN, IMPRESO, AUTORIZADO, COMENTARIOS, IDPROVEEDOR, 
          IDCONCEPTORIPS, AMBITO, FINALIDAD, PERSONAL_AT,  DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX, VALORPCOMP, USUARIO, UTISOAT, 
          VLRFALTAAPLICARSOAT, CONSECUTIVOCX, ITEMCIRUGIA, IDCIRUGIA, TIPOSERCIRUGIA, FACTURADA, N_FACTURA, VLRAPLICADO1,  VLRAPLICADO2, 
          CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION, INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, PCOSTO, CXP, FECHA, VIA, 
          IDAREAH, IDAREA, NIVELATENCION,  PEDIDOINV, NOLOTE, COBRARA, IDTERCEROCA, PCUBRIMIENTO, TIPODTO, DESCUENTO, NORDEN, VALORTOTALCOSTO,
          CCOSTO, ENLAB, CNSMOV, AUTORIZACION, AQUIENCOBRO, NOAUTORIZACION, CODPRG, IDCONTRATO,  ITFC, CNSITFC, IDTARIFA, CODIFICACION, 
          GRUPOQX_UVR_CX, CODCUPS, CODUNG, SINCRONIZADO, ANULADO, [MANUAL], APOYODG_AMBITO, PAQUETE, ITEM_RPDX, ENCARGOS, VALORCOPAGONORMAL, 
          VALORCOPAGOEXTERNO,  MARCA, USUARIOMARCA, ITEM_HCASER, NUM_ORDEN, IDARTICULO, CNSHBALI, NCONSECUTIVO, NTIPO, CLASEOM, ESTADOAPLICACION,
          HORA, AUDITADO, AUDITOR, IDSERVICIOH, VLRSERVICIOH,  N_FACTURAH, CANTIDADH, NPRESTACIONH, NOITEMH, NOPOSHOM, IDTERCEROH, CODCUMIPRES,
          FECHASOL, CODIGOCUM, EQUIPOMUES, DESC_EQUIPOMUES, CNSCONTENEDOR, VIVACOPA, VIVATCOPA, VIVATVENTA,  PVENTAT, CNSPRELIQ
   FROM HPRED
   WHERE NOPRESTACION='0100088888'

   IF EXISTS(SELECT  * FROM HADM WHERE NOADMISION=@NOADMISION AND FECHA<=@FECHAINI)
   BEGIN
      UPDATE @HPRE SET FECHA =@FECHAINI WHERE 2=2
   END
   ELSE
   BEGIN
      SELECT @FECHAINI=FECHA FROM HADM WHERE NOADMISION=@NOADMISION
   END
   IF NOT EXISTS(SELECT * FROM HADM WHERE COALESCE(FECHAALTAMED,GETDATE())>@FECHAFIN OR FECHAALTAMED IS NULL)
   BEGIN
      SELECT @FECHAFIN=FECHAALTAMED FROM HADM WHERE NOADMISION=@NOADMISION
   END

   UPDATE @HPRE SET NOADMISION=@NOADMISION WHERE 1=1
   

   SET @FECHAA=@FECHAINI
   WHILE @FECHAA<=@FECHAFIN
   BEGIN
		SET @NOPRESTACION_NUEVA=SPACE(16)
		EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@HPRE',@NOPRESTACION_NUEVA OUTPUT   
		SELECT @NOPRESTACION_NUEVA = @SEDE + REPLACE(SPACE(8 - LEN(@NOPRESTACION_NUEVA))+
               LTRIM(RTRIM(@NOPRESTACION_NUEVA)),SPACE(1),0)
             
      PRINT 'NVA PRESTACION='+@NOPRESTACION_NUEVA    
      
      INSERT INTO HPRE(NOPRESTACION, NOADMISION, FECHA, IDPLAN, IDAREAH, NIVELATENCION, IDAREA, IDSEDE, ALTOCOSTO, NO_ITEMES, VALORTOTAL, VALORCOPAGO, 
          VALOREXEDENTE, IMPRESO, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA,  AUTORIZADO, USUARIO, CERRADA, VALORPCOMP, CIRUGIA, PCUBRIMIENTO,
          CLASEORDEN, CONSECUTIVO, ESDEINV, PEDIDOINV, CNSMOV, INDDEVOLUCION, PREFIJO, CCOSTO, SUBCCOSTO, FINALIDAD,  AMBITO, PERSONAL_AT, DXPPAL,
          DXRELACIONADO, COMPLICACION, FORMAQX, ESCONSULTA, IDAREAEQUIPO, IMPRESOP, IDMEDICO, COBRARA, IDTERCEROCA, CONSECUTIVOHCA, ITEMRED, ENLAB,
          ITFC,  CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, CODEVAL, IDAREAAUX, INDLABCORE, CCOSTOAUX, CONTABILIZADA, NROCOMPROBANTE, MARCACONT, NOPLANTILLA,
          SINCRONIZADO, ANULADO, PROCEDENCIA, VALIDADO,  TIPOHISTORIA, CODOM, CONTABNIIF, NROCOMPROBANTENIIF, REVAUD, USUREVAUD, F_REVAUD, FECHA_SH, 
          COMERCIAL)
      SELECT @NOPRESTACION_NUEVA, NOADMISION, @FECHAA, IDPLAN, IDAREAH, NIVELATENCION, IDAREA, @SEDE, ALTOCOSTO, NO_ITEMES, VALORTOTAL, VALORCOPAGO, 
          VALOREXEDENTE, IMPRESO, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA,  AUTORIZADO, @USUARIO, CERRADA, VALORPCOMP, CIRUGIA, PCUBRIMIENTO,
          CLASEORDEN, CONSECUTIVO, ESDEINV, PEDIDOINV, CNSMOV, INDDEVOLUCION, PREFIJO, CCOSTO, SUBCCOSTO, FINALIDAD,  AMBITO, PERSONAL_AT, DXPPAL,
          DXRELACIONADO, COMPLICACION, FORMAQX, ESCONSULTA, IDAREAEQUIPO, IMPRESOP, IDMEDICO, COBRARA, IDTERCEROCA, CONSECUTIVOHCA, ITEMRED, ENLAB,
          ITFC,  CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, CODEVAL, IDAREAAUX, INDLABCORE, CCOSTOAUX, CONTABILIZADA, NROCOMPROBANTE, MARCACONT, NOPLANTILLA,
          SINCRONIZADO, ANULADO, PROCEDENCIA, VALIDADO,  TIPOHISTORIA, CODOM, CONTABNIIF, NROCOMPROBANTENIIF, REVAUD, USUREVAUD, F_REVAUD, FECHA_SH, 
          COMERCIAL
      FROM @HPRE

      INSERT INTO HPRED (NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALOREXCEDENTE, IDPLAN, IMPRESO, AUTORIZADO, COMENTARIOS, IDPROVEEDOR, 
          IDCONCEPTORIPS, AMBITO, FINALIDAD, PERSONAL_AT,  DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX, VALORPCOMP, USUARIO, UTISOAT, 
          VLRFALTAAPLICARSOAT, CONSECUTIVOCX, ITEMCIRUGIA, IDCIRUGIA, TIPOSERCIRUGIA, FACTURADA, N_FACTURA, VLRAPLICADO1,  VLRAPLICADO2, 
          CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION, INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, PCOSTO, CXP, FECHA, VIA, 
          IDAREAH, IDAREA, NIVELATENCION,  PEDIDOINV, NOLOTE, COBRARA, IDTERCEROCA, PCUBRIMIENTO, TIPODTO, DESCUENTO, NORDEN, VALORTOTALCOSTO,
          CCOSTO, ENLAB, CNSMOV, AUTORIZACION, AQUIENCOBRO, NOAUTORIZACION, CODPRG, IDCONTRATO,  ITFC, CNSITFC, IDTARIFA, CODIFICACION, 
          GRUPOQX_UVR_CX, CODCUPS, CODUNG, SINCRONIZADO, ANULADO, [MANUAL], APOYODG_AMBITO, PAQUETE, ITEM_RPDX, ENCARGOS, VALORCOPAGONORMAL, 
          VALORCOPAGOEXTERNO,  MARCA, USUARIOMARCA, ITEM_HCASER, NUM_ORDEN, IDARTICULO, CNSHBALI, NCONSECUTIVO, NTIPO, CLASEOM, ESTADOAPLICACION,
          HORA, AUDITADO, AUDITOR, IDSERVICIOH, VLRSERVICIOH,  N_FACTURAH, CANTIDADH, NPRESTACIONH, NOITEMH, NOPOSHOM, IDTERCEROH, CODCUMIPRES,
          FECHASOL, CODIGOCUM, EQUIPOMUES, DESC_EQUIPOMUES, CNSCONTENEDOR, VIVACOPA, VIVATCOPA, VIVATVENTA,  PVENTAT, CNSPRELIQ)
      SELECT @NOPRESTACION_NUEVA, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALOREXCEDENTE, IDPLAN, IMPRESO, AUTORIZADO, COMENTARIOS, IDPROVEEDOR, 
          IDCONCEPTORIPS, AMBITO, FINALIDAD, PERSONAL_AT,  DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX, VALORPCOMP, USUARIO, UTISOAT, 
          VLRFALTAAPLICARSOAT, CONSECUTIVOCX, ITEMCIRUGIA, IDCIRUGIA, TIPOSERCIRUGIA, 0, NULL, VLRAPLICADO1,  VLRAPLICADO2, 
          CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION, INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, PCOSTO, CXP, FECHA, VIA, 
          IDAREAH, IDAREA, NIVELATENCION,  PEDIDOINV, NOLOTE, COBRARA, IDTERCEROCA, PCUBRIMIENTO, TIPODTO, DESCUENTO, NORDEN, VALORTOTALCOSTO,
          CCOSTO, ENLAB, CNSMOV, AUTORIZACION, AQUIENCOBRO, NOAUTORIZACION, CODPRG, IDCONTRATO,  ITFC, CNSITFC, IDTARIFA, CODIFICACION, 
          GRUPOQX_UVR_CX, CODCUPS, CODUNG, SINCRONIZADO, ANULADO, [MANUAL], APOYODG_AMBITO, PAQUETE, ITEM_RPDX, ENCARGOS, VALORCOPAGONORMAL, 
          VALORCOPAGOEXTERNO,  MARCA, USUARIOMARCA, ITEM_HCASER, NUM_ORDEN, IDARTICULO, CNSHBALI, NCONSECUTIVO, NTIPO, CLASEOM, ESTADOAPLICACION,
          HORA, AUDITADO, AUDITOR, IDSERVICIOH, VLRSERVICIOH,  NULL, CANTIDADH, NPRESTACIONH, NOITEMH, NOPOSHOM, IDTERCEROH, CODCUMIPRES,
          FECHASOL, CODIGOCUM, EQUIPOMUES, DESC_EQUIPOMUES, CNSCONTENEDOR, VIVACOPA, VIVATCOPA, VIVATVENTA,  PVENTAT, CNSPRELIQ
     FROM @HPRED

     SELECT @FECHAA=DATEADD(DAY,1,@FECHAA)

   END
END
RETURN
GO
SELECT 'EXEC SPK_GENHPRE_DIARIO '''+NOADMISION+''',''01/07/2025'',''31/07/2025'','''+USUARIO+''',''SOPORTE'',''01'','''+IDSEDE+''''  FROM HADM WHERE IDPLAN='NEPSNO' AND FECHA<'01/08/2025' AND FECHA>'01/03/2025'  AND (FECHAALTAMED IS NULL  OR (FECHAALTAMED>='01/07/2025' AND FECHAALTAMED<'01/08/2025'))
