IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPKBD_REACTIVA_HADM' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE DBO.SPKBD_REACTIVA_HADM
END
GO
CREATE PROCEDURE DBO.SPKBD_REACTIVA_HADM
@NOADMISION  VARCHAR(16)
WITH ENCRYPTION
AS  
DECLARE @NOMBD  VARCHAR(20)
DECLARE @LINEA  VARCHAR(6096)   
BEGIN  
   IF (DBO.FNK_VALORVARIABLE('BD_HISTORICAS'))= 'NO'
   BEGIN
      RAISERROR('BD Históricas No Activadas...',16,1)
      RETURN
   END
   IF (COALESCE(DBO.FNK_VALORVARIABLE('BD_HISTORICA01'),''))= ''
   BEGIN
      RAISERROR('BD Históricas No Configuradas...',16,1)
      RETURN
   END
   SELECT @NOMBD = DBO.FNK_VALORVARIABLE('BD_HISTORICA01')
   --if db_id(@NOMBD) is null
   --begin
   --   RAISERROR('BD Históricas: Nombre 01 NO Existe...',16,1)
   --   RETURN
   --end
   PRINT '@NOMBD = '+@NOMBD
   PRINT 'HADM'
   
   SELECT @LINEA =  '   INSERT INTO HADM (NOADMISION, IDAFILIADO, FECHA, IDSEDE, IDPLAN, IDTERCERO, TIPOADM, HABCAMA, VIAINGRESO, CAUSAEXTERNA, 
                                          CONDUSUARIA, DXINGRESO, DXEGRESO, COMPLICACION, TIPODISCAP, GRADODISCAP, NOPOLIZA, NOCARNET, NOAUTORIZACION,
                                          FECHAVCEAUT, FECHAALTA, FECHASALIDA, CAUSASALIDA, ESTADOPSALIDA, VRDEPOSITO, RESPCUENTA, ESTADO, URG_NOMBRE,
                                          URG_TELE, URG_DIR, IDMEDICOING, IDMEDICOTRA, CAUSABMUERTE, ENFSOBREAG, OBS, FACTURADA, N_FACTURA, CNSFCT,
                                          CERRADA, PCUBRIMIENTO, USUARIO, DXSALIDA1, DXSALIDA2, DXSALIDA3, DESTINO, ESTADOSALIDA, RIPS, NIVELSOCIOEC,
                                          TIPOPOLIZA, IDMEDICOTRA2, IDMEDICOTRA3, ENVIO, FACTURABLE, COPAGO, COPAGONOAUTORIZACION, COPAGOVALOR, TIPOFAC,
                                          VFACTURAS, DESCUENTO, TIPODTO, USUARIOALTA, TIPOCREDITO, CREDITO, INDDEVOLUCION, INDPROCESARDEV, MARCA,
                                          ENVIOMARCA, VENCEAUT, MTOPE, TIPOTOPE, FECHATOPE, VALORTOPE, TOPEOTROTERCERO, CONTINUACION, NOADMISIONCONT,
                                          FECHATRASHOS, CXP, VLRUTOTRAHADM, IDPROVEEDOR, TIPOCONT, IDCONTRATO, IDAREA_ALTA, PREADMISION, IDCIRUGIA,
                                          PYP, CLASENOPROC, URG_VINCULO, A24H, A2448H, A4872H, A72H30D, CCOSTO_ALTA, FECHAPRE, LIQESTANCIA, 
                                          FACTURADAPARCIAL, TIPOCOPAGO, PROCEDENCIA, CNSHACTRAN, DECLARIESGOS, IDMEDICOALTA, CLASEING, PASADACENTRAL,
                                          CNSENTREGA, CODUNG, FECHAALTAMED ,ITFC, CNSITFC, EMBARAZADA, CNSTRIAGE ,TTRIAGE, IDDXULTIMO, CCOSTOULTIMO,
                                          UATENINIURG, ESINSTPROV, ESEINST ,FECHAESEINST, REVESPECIALISTA, REFERIDO, IDREFERIDO, MANCOPAGOEXT, 
                                          NOAUTORIZACIONEXT, VLR_COPAGOEXTERNO, DIASHOSPITALIZACION, HORASQUIROFANO, TITULARPOLIZA, SINCRONIZADO,
                                          NOCOTIZACION, USUALTAMED, IDPLAN_AFI, IDTERCERO_AFI, PAQUETE, TOPECOPAGO_ANX6, TIPOCAJA, CNSFACJ, CODCAJA,
                                          USACTC, IDSERVICIOPAQUETE ,VLRSERVICIOPAQ, FECHAALTAENF, IDUSUARIOALTAENF, MDATEXC, MARCAATRASO) 
   SELECT A.NOADMISION, A.IDAFILIADO, A.FECHA, A.IDSEDE, A.IDPLAN, A.IDTERCERO, A.TIPOADM, A.HABCAMA, A.VIAINGRESO, A.CAUSAEXTERNA, 
          A.CONDUSUARIA, A.DXINGRESO, A.DXEGRESO, A.COMPLICACION, A.TIPODISCAP, A.GRADODISCAP, A.NOPOLIZA, A.NOCARNET, A.NOAUTORIZACION,
          A.FECHAVCEAUT, A.FECHAALTA, A.FECHASALIDA, A.CAUSASALIDA, A.ESTADOPSALIDA, A.VRDEPOSITO, A.RESPCUENTA, A.ESTADO, A.URG_NOMBRE,
          A.URG_TELE, A.URG_DIR, A.IDMEDICOING, A.IDMEDICOTRA, A.CAUSABMUERTE, A.ENFSOBREAG, A.OBS, A.FACTURADA, A.N_FACTURA, A.CNSFCT,
          A.CERRADA, A.PCUBRIMIENTO, A.USUARIO, A.DXSALIDA1, A.DXSALIDA2, A.DXSALIDA3, A.DESTINO, A.ESTADOSALIDA, A.RIPS, A.NIVELSOCIOEC,
          A.TIPOPOLIZA, A.IDMEDICOTRA2, A.IDMEDICOTRA3, A.ENVIO, A.FACTURABLE, A.COPAGO, A.COPAGONOAUTORIZACION, A.COPAGOVALOR, A.TIPOFAC,
          A.VFACTURAS, A.DESCUENTO, A.TIPODTO, A.USUARIOALTA, A.TIPOCREDITO, A.CREDITO, A.INDDEVOLUCION, A.INDPROCESARDEV, A.MARCA,
          A.ENVIOMARCA, A.VENCEAUT, A.MTOPE, A.TIPOTOPE, A.FECHATOPE, A.VALORTOPE, A.TOPEOTROTERCERO, A.CONTINUACION, A.NOADMISIONCONT,
          A.FECHATRASHOS, A.CXP, A.VLRUTOTRAHADM, A.IDPROVEEDOR, A.TIPOCONT, A.IDCONTRATO, A.IDAREA_ALTA, A.PREADMISION, A.IDCIRUGIA,
          A.PYP, A.CLASENOPROC, A.URG_VINCULO, A.A24H, A.A2448H, A.A4872H, A.A72H30D, A.CCOSTO_ALTA, A.FECHAPRE, A.LIQESTANCIA, 
          A.FACTURADAPARCIAL, A.TIPOCOPAGO, A.PROCEDENCIA, A.CNSHACTRAN, A.DECLARIESGOS, A.IDMEDICOALTA, A.CLASEING, A.PASADACENTRAL,
          A.CNSENTREGA, A.CODUNG, A.FECHAALTAMED ,A.ITFC, A.CNSITFC, A.EMBARAZADA, A.CNSTRIAGE ,A.TTRIAGE, A.IDDXULTIMO, A.CCOSTOULTIMO,
          A.UATENINIURG, A.ESINSTPROV, A.ESEINST ,A.FECHAESEINST, A.REVESPECIALISTA, A.REFERIDO, A.IDREFERIDO, A.MANCOPAGOEXT, 
          A.NOAUTORIZACIONEXT, A.VLR_COPAGOEXTERNO, A.DIASHOSPITALIZACION, A.HORASQUIROFANO, A.TITULARPOLIZA, A.SINCRONIZADO,
          A.NOCOTIZACION, A.USUALTAMED, A.IDPLAN_AFI, A.IDTERCERO_AFI, A.PAQUETE, A.TOPECOPAGO_ANX6, A.TIPOCAJA, A.CNSFACJ, A.CODCAJA,
          A.USACTC, A.IDSERVICIOPAQUETE ,A.VLRSERVICIOPAQ, A.FECHAALTAENF, A.IDUSUARIOALTAENF, A.MDATEXC, A.MARCAATRASO
   FROM   ' + @NOMBD + '.dbo.HADM A
   WHERE A.NOADMISION = '''+@NOADMISION+'''
   AND   NOT EXISTS (SELECT * FROM HADM X WHERE A.NOADMISION COLLATE database_default = X.NOADMISION COLLATE database_default)'
   --PRINT @LINEA 
   EXEC (@LINEA)
   PRINT 'HPRE'
   SELECT @LINEA =  '   INSERT INTO HPRE 
   SELECT DISTINCT A.*
   FROM   ' + @NOMBD + '.dbo.HPRE A
   WHERE  NOT EXISTS ( SELECT * FROM HPRE WHERE HPRE.NOPRESTACION COLLATE database_default = A.NOPRESTACION COLLATE database_default)
   AND    EXISTS     ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+''''
   EXEC (@LINEA)
   PRINT 'HPRED'
   SELECT @LINEA =  '   INSERT INTO HPRED (NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALOREXCEDENTE, IDPLAN, IMPRESO, AUTORIZADO,
                                           COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, AMBITO, FINALIDAD, PERSONAL_AT, DXPPAL, DXRELACIONADO, COMPLICACION,
                                           FORMAQX, VALORPCOMP, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT, CONSECUTIVOCX, ITEMCIRUGIA, IDCIRUGIA, 
                                           TIPOSERCIRUGIA, FACTURADA, N_FACTURA, VLRAPLICADO1, VLRAPLICADO2, CANTIDADORIGINAL, CANTIDADDEVUELTA, 
                                           CNSIDEV, INDDEVOLUCION, INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, PCOSTO, CXP, FECHA, VIA, IDAREAH, IDAREA,
                                           NIVELATENCION, PEDIDOINV, NOLOTE, COBRARA, IDTERCEROCA, PCUBRIMIENTO ,TIPODTO, DESCUENTO, NORDEN, 
                                           VALORTOTALCOSTO, CCOSTO, ENLAB, CNSMOV, AUTORIZACION, AQUIENCOBRO, NOAUTORIZACION, CODPRG, IDCONTRATO,
                                           ITFC, CNSITFC, IDTARIFA, CODIFICACION, GRUPOQX_UVR_CX ,CODCUPS, CODUNG, SINCRONIZADO, ANULADO, MANUAL,
                                           APOYODG_AMBITO, PAQUETE, ITEM_RPDX, ENCARGOS, VALORCOPAGONORMAL, MARCA, USUARIOMARCA)
   SELECT A.NOPRESTACION, A.NOITEM, A.IDSERVICIO, A.CANTIDAD, A.VALOR, A.VALORCOPAGO, A.VALOREXCEDENTE, A.IDPLAN, A.IMPRESO, A.AUTORIZADO,
          A.COMENTARIOS, A.IDPROVEEDOR, A.IDCONCEPTORIPS, A.AMBITO, A.FINALIDAD, A.PERSONAL_AT, A.DXPPAL, A.DXRELACIONADO, A.COMPLICACION,
          A.FORMAQX, A.VALORPCOMP, A.USUARIO, A.UTISOAT, A.VLRFALTAAPLICARSOAT, A.CONSECUTIVOCX, A.ITEMCIRUGIA, A.IDCIRUGIA, 
          A.TIPOSERCIRUGIA, A.FACTURADA, A.N_FACTURA, A.VLRAPLICADO1, A.VLRAPLICADO2, A.CANTIDADORIGINAL, A.CANTIDADDEVUELTA, 
          A.CNSIDEV, A.INDDEVOLUCION, A.INDDEVAPLICADA, A.USUARIODEV, A.NOCOBRABLE, A.PCOSTO, A.CXP, A.FECHA, A.VIA, A.IDAREAH, A.IDAREA,
          A.NIVELATENCION, A.PEDIDOINV, A.NOLOTE, A.COBRARA, A.IDTERCEROCA, A.PCUBRIMIENTO ,A.TIPODTO, A.DESCUENTO, A.NORDEN, 
          A.VALORTOTALCOSTO, A.CCOSTO, A.ENLAB, A.CNSMOV, A.AUTORIZACION, A.AQUIENCOBRO, A.NOAUTORIZACION, A.CODPRG, A.IDCONTRATO,
          A.ITFC, A.CNSITFC, A.IDTARIFA, A.CODIFICACION, A.GRUPOQX_UVR_CX ,A.CODCUPS, A.CODUNG, A.SINCRONIZADO, A.ANULADO, A.MANUAL,
          A.APOYODG_AMBITO, A.PAQUETE, A.ITEM_RPDX, A.ENCARGOS, A.VALORCOPAGONORMAL, A.MARCA, A.USUARIOMARCA
   FROM   ' + @NOMBD + '.dbo.HPRED A INNER JOIN ' + @NOMBD + '.dbo.HPRE B ON A.NOPRESTACION COLLATE database_default = B.NOPRESTACION COLLATE database_default 
   WHERE  NOT EXISTS ( SELECT * FROM HPRED 
                       WHERE  HPRED.NOPRESTACION COLLATE database_default = A.NOPRESTACION COLLATE database_default
                       AND    HPRED.NOITEM        = A.NOITEM )
   AND    EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = B.NOADMISION COLLATE database_default)
   AND    B.NOADMISION = '''+@NOADMISION+''''
   EXEC (@LINEA)

   PRINT 'HCA'    
   SELECT @LINEA =  '   INSERT INTO HCA (CONSECUTIVO, CLASEPLANTILLA, FECHA, IDMEDICO, IDAFILIADO, NOADMISION, IDDX, TIPODX, IMPRESO, EDAD, FINALIDAD, DX1,
                                         DX2, DX3, IDMEDICODILIGENCIA ,IDDXEG, N_HISTORIA ,PROCEDENCIA ,REVISAESP, IDMEDICOESP, PIDEDX, PIDESV, TAS, TAD,
                                         FC, FR, TEMP, TALLA, PULSO ,PESO, GLASGOW, TIPOGLASGOW, HIDRATACION, ALTA, CLASE, ITEMHADM ,IDAREA, ANULADA, USUARIOANU,
                                         FECHA_ANU, OBSERVAANU, AMBITO ,MED_ESPEC ,CAUSA_EXT, SINCRONIZADO, IDPLAN, CCOSTO, ENEPICRISIS, CERRADA, EVOLUCION, 
                                         ITEMRED, PLANDEMANEJO, RESUMEN ,EVOLSUB ,ANALISIS, ESTANCIA, RESPARACLINI ,JUSTESTANCIA ,TAM, SOAT, BOLO, CONSECUTIVO_RED_ORI,
                                         ITEMRED_RED_ORI, CNSNESIGVIT_GV, CNSNESIGVIT_PV, CNSNESIGVIT_IO, TIPOPM)
   SELECT A.CONSECUTIVO, A.CLASEPLANTILLA, A.FECHA, A.IDMEDICO, A.IDAFILIADO, A.NOADMISION, A.IDDX, A.TIPODX, A.IMPRESO, A.EDAD, A.FINALIDAD, A.DX1,
                                         A.DX2, A.DX3, A.IDMEDICODILIGENCIA ,A.IDDXEG, A.N_HISTORIA ,A.PROCEDENCIA ,A.REVISAESP, A.IDMEDICOESP, A.PIDEDX, A.PIDESV, 
                                         A.TAS, A.TAD, A.FC, A.FR, A.TEMP, A.TALLA, A.PULSO ,A.PESO, A.GLASGOW, A.TIPOGLASGOW, A.HIDRATACION, A.ALTA, A.CLASE, 
                                         A.ITEMHADM ,A.IDAREA, A.ANULADA, A.USUARIOANU, A.FECHA_ANU, A.OBSERVAANU, A.AMBITO ,A.MED_ESPEC ,A.CAUSA_EXT, A.SINCRONIZADO,
                                         A.IDPLAN, A.CCOSTO, A.ENEPICRISIS, A.CERRADA, A.EVOLUCION, A.ITEMRED, A.PLANDEMANEJO, A.RESUMEN ,A.EVOLSUB ,A.ANALISIS, 
                                         A.ESTANCIA, A.RESPARACLINI ,A.JUSTESTANCIA ,A.TAM, A.SOAT, A.BOLO, A.CONSECUTIVO_RED_ORI, A.ITEMRED_RED_ORI,
                                         A.CNSNESIGVIT_GV, A.CNSNESIGVIT_PV, A.CNSNESIGVIT_IO, A.TIPOPM
   FROM   ' + @NOMBD + '.DBO.HCA A 
   WHERE  NOT EXISTS ( SELECT CONSECUTIVO FROM HCA WHERE HCA.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default)
   AND    EXISTS     ( SELECT NOADMISION FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    A.PROCEDENCIA = ''QX''
   AND    A.NOADMISION = '''+@NOADMISION+''''
   --PRINT @LINEA
   EXEC (@LINEA)
   
   PRINT 'HCAD'
   SELECT @LINEA =  '   INSERT INTO HCAD
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HCAD A INNER JOIN ' + @NOMBD + '.DBO.HCA  B ON A.CONSECUTIVO COLLATE database_default = B.CONSECUTIVO COLLATE database_default
   WHERE  EXISTS( SELECT CONSECUTIVO FROM HCA WHERE HCA.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default)
   AND    NOT EXISTS ( SELECT * FROM HCAD WHERE HCAD.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                                            AND HCAD.SECUENCIA   = A.SECUENCIA )
   AND    B.NOADMISION = '''+@NOADMISION+''''                                         
   EXEC (@LINEA)

   PRINT 'HCASV'
   SELECT @LINEA =  '   INSERT INTO HCASV
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HCASV A INNER JOIN ' + @NOMBD + '.DBO.HCA  B ON A.CONSECUTIVO COLLATE database_default = B.CONSECUTIVO COLLATE database_default
   WHERE  EXISTS ( SELECT CONSECUTIVO FROM HCA WHERE HCA.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default)
   AND    NOT EXISTS (SELECT * FROM HCASV WHERE HCASV.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                                            AND HCASV.CODIGOSV    COLLATE database_default = A.CODIGOSV COLLATE database_default)
   AND    B.NOADMISION = '''+@NOADMISION+''''                          
   EXEC (@LINEA)

   PRINT 'HCADL'
   SELECT @LINEA =  '   INSERT INTO HCADL
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HCADL A INNER JOIN ' + @NOMBD + '.DBO.HCA  B ON A.CONSECUTIVO COLLATE database_default = B.CONSECUTIVO COLLATE database_default
   WHERE  EXISTS ( SELECT * FROM HCAD 
                   WHERE  HCAD.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                   AND    HCAD.SECUENCIA   = A.SECUENCIA )
   AND    NOT EXISTS( SELECT * FROM HCADL
                      WHERE  HCADL.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                      AND    HCADL.SECUENCIA   = A.SECUENCIA
                      AND    HCADL.VALORLISTA COLLATE database_default = A.VALORLISTA COLLATE database_default)
   AND    B.NOADMISION = '''+@NOADMISION+''''                          
   EXEC (@LINEA)
   
   PRINT 'HCASER'
   SELECT @LINEA = ' INSERT INTO HCASER (CONSECUTIVO, IDSERVICIO, CANTIDAD, NOPRESTACION, NOITEM_HPRED, AUTOMATICO)
   SELECT A.CONSECUTIVO, IDSERVICIO, CANTIDAD, NOPRESTACION,NOITEM_HPRED, AUTOMATICO
   FROM  '+ @NOMBD + '.DBO.HCASER A INNER JOIN ' + @NOMBD + '.DBO.HCA  B ON A.CONSECUTIVO COLLATE database_default = B.CONSECUTIVO COLLATE database_default
   WHERE  EXISTS     ( SELECT * FROM HCA WHERE HCA.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default )
   AND    NOT EXISTS ( SELECT * FROM HCASER WHERE HCASER.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                                            AND   HCASER.ITEM_HCASER = A.ITEM_HCASER)
   AND    B.NOADMISION = '''+@NOADMISION+''''                          
   EXEC (@LINEA)

   PRINT 'HCATD'
   SELECT @LINEA =  '   INSERT INTO HCATD (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA,OBSERVACION,CLASE,ENCARGOS, NOPRESTACION,
                                           APLICADA, CONSECUTIVONE, NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION, TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR,
                                           CANTIDADNOCC, CANTIDADINV, CNSHJNOPOS, DESCRIPTIVA, DESTINO, OBSDESCRIPTIVA, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER)
   SELECT A.CONSECUTIVO, A.ITEMRED, A.CODOM, A.IDSERVICIO, A.CANTIDAD, A.IDTIPOCONC, A.VIA,A.OBSERVACION,A.CLASE,A.ENCARGOS, A.NOPRESTACION,
          A.APLICADA, A.CONSECUTIVONE, A.NOITEM, A.NOINGRESO, A.NORDEN, A.FRECUENCIA, A.DURACION, A.TIPO, A.AVISADOENF, A.FECHAGA, A.IDPROVEEDOR,
         A.CANTIDADNOCC, A.CANTIDADINV, A.CNSHJNOPOS, A.DESCRIPTIVA, A.DESTINO, A.OBSDESCRIPTIVA, A.IDPERFIL, A.COPIADO, A.CANTIDADBOLO, A.PRIMER
   FROM   ' + @NOMBD + '.DBO.HCATD A INNER JOIN ' + @NOMBD + '.DBO.HCA B ON A.CONSECUTIVO COLLATE database_default = B.CONSECUTIVO COLLATE database_default
                                                                         AND A.ITEMRED     = B.ITEMRED                                     
   WHERE  NOT EXISTS (SELECT * FROM HCATD 
                      WHERE  HCATD.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                      AND    HCATD.ITEMRED     = A.ITEMRED
                      AND    HCATD.CODOM      COLLATE database_default  = A.CODOM COLLATE database_default
                      AND    HCATD.IDSERVICIO COLLATE database_default  = A.IDSERVICIO COLLATE database_default)
   AND    B.NOADMISION = '''+@NOADMISION+''''                          
   EXEC (@LINEA)

   PRINT 'HBLIQ'  
   SELECT @LINEA =  '   INSERT INTO HBLIQ (NOADMISION, CNSHBLIQ, FECHA, IDMEDICO, CONSECUTIVOHCA, ITEMRED, TIPOHISTORIA, PAR_IND, ORA_IND,SON_IND,
                                           IDENFERMERIA, PAR_PORAD, ORA_PORAD, SON_PORAD, PAR_REC, ORA_REC, SON_REC, TOTAD_ITEM,TOTAD_ACU,MAFE,
                                           ORINA, VOMITO, DRENAJE, OTROS, TOTELI_ITEM,TOTELI_ACU, TOTAL_ITEM, TOTAL_ACUM, OBSERV, TOTREC_ITEM,
                                           TOTREC_ACUM, TIPOREG, CNSHTX, NOINDICADO, BALCORTE, DESCNOINDICADO, IDSERVICIO)
                        SELECT A.NOADMISION, A.CNSHBLIQ, A.FECHA, A.IDMEDICO, A.CONSECUTIVOHCA, A.ITEMRED, A.TIPOHISTORIA, A.PAR_IND, A.ORA_IND,A.SON_IND,
                               A.IDENFERMERIA, A.PAR_PORAD, A.ORA_PORAD, A.SON_PORAD, A.PAR_REC, A.ORA_REC, A.SON_REC, A.TOTAD_ITEM,A.TOTAD_ACU,A.MAFE,
                               A.ORINA, A.VOMITO, A.DRENAJE, A.OTROS, A.TOTELI_ITEM,A.TOTELI_ACU, A.TOTAL_ITEM, A.TOTAL_ACUM, A.OBSERV, A.TOTREC_ITEM,
                               A.TOTREC_ACUM, A.TIPOREG, A.CNSHTX, A.NOINDICADO, A.BALCORTE, A.DESCNOINDICADO, A.IDSERVICIO
   FROM   ' + @NOMBD + '.DBO.HBLIQ A INNER JOIN ' + @NOMBD + '.DBO.HCA  B ON A.CONSECUTIVOHCA COLLATE database_default = B.CONSECUTIVO COLLATE database_default 
   WHERE  NOT EXISTS ( SELECT * FROM HBLIQ WHERE HBLIQ.CNSHBLIQ COLLATE database_default = A.CNSHBLIQ COLLATE database_default)
   AND    EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    B.NOADMISION = '''+@NOADMISION+''''                          
   EXEC (@LINEA)

   PRINT 'HTX'
   SELECT @LINEA =  '   INSERT INTO HTX (CNSHTX, CONSECUTIVOHCA, CODOM, ITEMRED, TIPOHISTORIA, IDSERVICIO, CANTIDAD,FECHAORDEN, IDTIPOCONC, VIA, FECHAREQ,
                                         CLASE, TIPO, IDENFERMERIA, FECHAAPLI, SOLICITADO, APLICADO, ENCARGOS, CNSMOV, NOPRESTACION, NOITEM,NOADMISION,
                                         ESTADO, CCOSTO, IDAREA, LISTOENTREGA, FECHALE, ENTREGADO, FECHAENTREGA, USUARIOENTREGA, CONSECUTIVORED, IDFUNCIONARIORECIBE,
                                         APROBADO, PEDIRINV, CARGOGENERADO, USUARIOPIDEI, FECHAPIDEI, TTOTRAIDOAFI, USUARIORECIBE, CNSHBLIQ, CANTIDADAPLI, FECHASUSPEN,
                                         SUSPENDER, OBSERVACIONES, NOCOBRAR, IDPAQUETE, REQUISICION, TIPOREQ, MARCAINV, MARCADEV, INDDEV, CNSMOVDEV, CLASEHTX,
                                         MDOSIF, EQUICC, QDOSIS, TIPOGCC, HOST_MPEDINV, HOST_MDEVINV, HOST_APLICA, CANTIDADNOCC, ANULADA, CLASEANULA, USUARIOANULA,
                                         CLASEANUINV, CANTIDADINV, CANTIDAD_CARGOS, CCFALT_LOCARGADO, FALTANCARGAR, CCDESECHADOS, CANTIDADDEV, FFINESTAB, CNSHDUXS,
                                         CNSHDUXS2, CNSDIRINV, ANT_UNICOMP, ANT_CC)
   SELECT A.CNSHTX, A.CONSECUTIVOHCA, A.CODOM, A.ITEMRED, A.TIPOHISTORIA, A.IDSERVICIO, A.CANTIDAD,A.FECHAORDEN, A.IDTIPOCONC, A.VIA, A.FECHAREQ,
            A.CLASE, A.TIPO, A.IDENFERMERIA, A.FECHAAPLI, A.SOLICITADO, A.APLICADO, A.ENCARGOS, A.CNSMOV, A.NOPRESTACION, A.NOITEM,A.NOADMISION,
            A.ESTADO, A.CCOSTO, A.IDAREA, A.LISTOENTREGA, A.FECHALE, A.ENTREGADO, A.FECHAENTREGA, A.USUARIOENTREGA, A.CONSECUTIVORED, A.IDFUNCIONARIORECIBE,
            A.APROBADO, A.PEDIRINV, A.CARGOGENERADO, A.USUARIOPIDEI, A.FECHAPIDEI, A.TTOTRAIDOAFI, A.USUARIORECIBE, A.CNSHBLIQ, A.CANTIDADAPLI, A.FECHASUSPEN,
            A.SUSPENDER, A.OBSERVACIONES, A.NOCOBRAR, A.IDPAQUETE, A.REQUISICION, A.TIPOREQ, A.MARCAINV, A.MARCADEV, A.INDDEV, A.CNSMOVDEV, A.CLASEHTX,
            A.MDOSIF, A.EQUICC, A.QDOSIS, A.TIPOGCC, A.HOST_MPEDINV, A.HOST_MDEVINV, A.HOST_APLICA, A.CANTIDADNOCC, A.ANULADA, A.CLASEANULA, A.USUARIOANULA,
            A.CLASEANUINV, A.CANTIDADINV, A.CANTIDAD_CARGOS, A.CCFALT_LOCARGADO, A.FALTANCARGAR, A.CCDESECHADOS, A.CANTIDADDEV, A.FFINESTAB, A.CNSHDUXS,
            A.CNSHDUXS2, A.CNSDIRINV, A.ANT_UNICOMP, A.ANT_CC
   FROM   ' + @NOMBD + '.DBO.HTX A INNER JOIN ' + @NOMBD + '.DBO.HCA  B ON A.CONSECUTIVOHCA COLLATE database_default = B.CONSECUTIVO COLLATE database_default 
   WHERE  NOT EXISTS ( SELECT * FROM HTX WHERE HTX.CNSHTX COLLATE database_default = A.CNSHTX COLLATE database_default) 
   AND    EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default) 
   AND    B.NOADMISION = '''+@NOADMISION+''''                          
   EXEC (@LINEA)

   PRINT 'QXRCN'
   SELECT @LINEA =  '   INSERT INTO QXRCN
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.QXRCN A 
   WHERE  NOT EXISTS ( SELECT * FROM QXRCN WHERE QXRCN.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default)
   AND    EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default) 
   AND    A.NOADMISION = '''+@NOADMISION+''''                          
   EXEC (@LINEA)
   
   PRINT 'QXPCX'
   SELECT @LINEA =  '   INSERT INTO QXPCX
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.QXPCX A 
   WHERE  NOT EXISTS ( SELECT * FROM QXPCX WHERE QXPCX.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default)
   AND    EXISTS (SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+''''                          
   EXEC (@LINEA)
   
   PRINT 'QXPCXD'
   SELECT @LINEA =  '   INSERT INTO QXPCXD
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.QXPCXD A INNER JOIN ' + @NOMBD + '.DBO.QXPCX B ON A.CONSECUTIVO COLLATE database_default = B.CONSECUTIVO COLLATE database_default
   WHERE  EXISTS ( SELECT CONSECUTIVO FROM QXPCX WHERE QXPCX.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default)
   AND    NOT EXISTS ( SELECT * FROM QXPCXD WHERE QXPCXD.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                                              AND QXPCXD.ITEM        = A.ITEM)
   AND    B.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA) 
   
   PRINT 'QXPCXI'
   SELECT @LINEA =  '   INSERT INTO QXPCXI
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.QXPCXI A INNER JOIN ' + @NOMBD + '.DBO.QXPCXD D ON A.CONSECUTIVO COLLATE database_default = D.CONSECUTIVO COLLATE database_default
                                                                          AND A.ITEM        = D.ITEM 
                                     INNER JOIN ' + @NOMBD + '.DBO.QXPCX  B ON D.CONSECUTIVO COLLATE database_default = B.CONSECUTIVO COLLATE database_default
   WHERE  EXISTS ( SELECT CONSECUTIVO FROM QXPCX WHERE QXPCX.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default)
   AND    NOT EXISTS ( SELECT * FROM QXPCXI 
                       WHERE  QXPCXI.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                       AND    QXPCXI.ITEM        = A.ITEM
                       AND    QXPCXI.ARTICULO COLLATE database_default   = A.ARTICULO COLLATE database_default
                       AND    QXPCXI.RENGLON     = A.RENGLON )
   AND    B.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)

   PRINT 'QXPCXR'
   SELECT @LINEA =  '   INSERT INTO QXPCXR
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.QXPCXR A INNER JOIN ' + @NOMBD + '.DBO.QXPCXD D ON A.CONSECUTIVO COLLATE database_default = D.CONSECUTIVO COLLATE database_default
                                                                          AND A.ITEM        = D.ITEM 
                                      INNER JOIN ' + @NOMBD + '.DBO.QXPCX  B ON D.CONSECUTIVO COLLATE database_default = B.CONSECUTIVO COLLATE database_default
   WHERE  EXISTS ( SELECT CONSECUTIVO FROM QXPCX WHERE QXPCX.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default )
   AND    NOT EXISTS (SELECT * FROM QXPCXR 
                      WHERE  QXPCXR.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                      AND    QXPCXR.ITEM        = A.ITEM
                      AND    QXPCXR.IDMEDICO    COLLATE database_default = A.IDMEDICO COLLATE database_default)
   AND    B.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'QXPCXS'
   SELECT @LINEA =  '   INSERT INTO QXPCXS
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.QXPCXS A INNER JOIN ' + @NOMBD + '.DBO.QXPCXD D ON A.CONSECUTIVO COLLATE database_default = D.CONSECUTIVO COLLATE database_default
                                                                          AND A.ITEM        = D.ITEM 
                                      INNER JOIN ' + @NOMBD + '.DBO.QXPCX  B ON D.CONSECUTIVO COLLATE database_default = B.CONSECUTIVO COLLATE database_default
   WHERE  EXISTS ( SELECT CONSECUTIVO FROM QXPCX WHERE QXPCX.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default)
   AND    NOT EXISTS (SELECT * FROM QXPCXS 
                      WHERE  QXPCXS.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default
                      AND    QXPCXS.ITEM        = A.ITEM
                      AND    QXPCXS.IDSERVICIO  COLLATE database_default = A.IDSERVICIO COLLATE database_default)
   AND    B.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'QXDING'
   SELECT @LINEA =  '   INSERT INTO QXDING
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.QXDING A 
   WHERE  NOT EXISTS( SELECT NOINGRESO FROM QXDING
                      WHERE  QXDING.NOINGRESO COLLATE database_default = A.NOINGRESO COLLATE database_default
                      AND    QXDING.CODCAJA   COLLATE database_default = A.CODCAJA COLLATE database_default
                      AND    QXDING.CNSFACJ   COLLATE database_default = A.CNSFACJ COLLATE database_default)
   AND    EXISTS ( SELECT NOADMISION FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOINGRESO COLLATE database_default)
   AND    A.NOINGRESO = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HREQ'
   SELECT @LINEA =  '   INSERT INTO HREQ
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HREQ A 
   WHERE  NOT EXISTS ( SELECT NOADMISION FROM HREQ 
                       WHERE  HREQ.NOADMISION      COLLATE database_default = A.NOADMISION COLLATE database_default
                       AND    HREQ.TIPOREQ         COLLATE database_default = A.TIPOREQ COLLATE database_default
                       AND    HREQ.IDREQUERIMIENTO COLLATE database_default = A.IDREQUERIMIENTO COLLATE database_default)
   AND    EXISTS (SELECT NOADMISION FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HNAT'
   SELECT @LINEA =  '   INSERT INTO HNAT
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HNAT A 
   WHERE  NOT EXISTS ( SELECT NOADMISION FROM HNAT 
                       WHERE  HNAT.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default
                       AND    HNAT.NOITEM     = A.NOITEM)
   AND    EXISTS (SELECT NOADMISION FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HCUCI'
   SELECT @LINEA =  '   INSERT INTO HCUCI
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HCUCI A 
   WHERE  NOT EXISTS ( SELECT * FROM HCUCI WHERE HCUCI.CONSECUTIVO COLLATE database_default = A.CONSECUTIVO COLLATE database_default)
   AND    EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default) 
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HADMDX'
   SELECT @LINEA =  '   INSERT INTO HADMDX
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HADMDX A 
   WHERE  EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    NOT EXISTS (SELECT * FROM HADMDX
                      WHERE  HADMDX.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default
                      AND    HADMDX.NOITEM     = A.NOITEM )
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HADMF'
   SELECT @LINEA =  '   INSERT INTO HADMF
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HADMF A 
   WHERE  EXISTS ( SELECT NOADMISION FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default )
   AND    NOT EXISTS (SELECT * FROM HADMF WHERE HADMF.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default 
                                            AND HADMF.N_FACTURA COLLATE database_default = A.N_FACTURA COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'FME'
   SELECT @LINEA =  '   INSERT INTO FME
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.FME A 
   WHERE  EXISTS ( SELECT NOADMISION FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    A.PROCEDENCIA = ''QX''
   AND    NOT EXISTS (SELECT * FROM FME WHERE FME.NOCONSECUTIVO COLLATE database_default = A.NOCONSECUTIVO COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'FMED'
   SELECT @LINEA =  '      INSERT INTO FMED
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.FMED A INNER JOIN ' + @NOMBD + '.DBO.FME B ON A.NOCONSECUTIVO COLLATE database_default = B.NOCONSECUTIVO COLLATE database_default 
   WHERE  EXISTS ( SELECT NOCONSECUTIVO FROM FME WHERE FME.NOCONSECUTIVO COLLATE database_default = A.NOCONSECUTIVO COLLATE database_default)
   AND    NOT EXISTS (SELECT * FROM FMED WHERE FMED.NOCONSECUTIVO COLLATE database_default = A.NOCONSECUTIVO COLLATE database_default 
                                           AND FMED.NOITEM = A.NOITEM)
   AND    B.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'IDEV'   
   SELECT @LINEA =  '   INSERT INTO IDEV
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.IDEV A 
   WHERE  NOT EXISTS ( SELECT * FROM IDEV WHERE IDEV.CNSIDEV COLLATE database_default = A.CNSIDEV COLLATE database_default)
   AND    EXISTS ( SELECT NOADMISION FROM IDEV WHERE IDEV.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default) 
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'IDEVD'
   SELECT @LINEA =  '   INSERT INTO IDEVD
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.IDEVD A INNER JOIN ' + @NOMBD + '.DBO.IDEV B ON A.CNSIDEV COLLATE database_default   = B.CNSIDEV COLLATE database_default
   WHERE  EXISTS ( SELECT CNSIDEV FROM IDEV WHERE IDEV.CNSIDEV COLLATE database_default = A.CNSIDEV COLLATE database_default)
   AND    NOT EXISTS ( SELECT * FROM IDEVD WHERE IDEVD.CNSIDEV COLLATE database_default = A.CNSIDEV COLLATE database_default
                                           AND   IDEVD.NOPRESTACION COLLATE database_default = A.NOPRESTACION COLLATE database_default
                                           AND   IDEVD.NOITEM       = A.NOITEM)
   AND    B.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HSOAT'
   SELECT @LINEA =  '   INSERT INTO HSOAT
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HSOAT A 
   WHERE  EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default )
   AND    NOT EXISTS (SELECT * FROM HSOAT WHERE HSOAT.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HADMDT'
   SELECT @LINEA =  '   INSERT INTO HADMDT
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HADMDT A 
   WHERE  EXISTS( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    NOT EXISTS (SELECT * FROM HADMDT 
                      WHERE  HADMDT.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default
                      AND    HADMDT.IDTERCERO  COLLATE database_default = A.IDTERCERO COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HADM_T'
   SELECT @LINEA =  '   INSERT INTO HADM_T
   SELECT A.*
   FROM   ' + @NOMBD + '.DBO.HADM_T A 
   WHERE  EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    NOT EXISTS (SELECT * FROM HADM_T 
                      WHERE  HADM_T.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default
                      AND    HADM_T.ITEM       = A.ITEM)
   AND    A.NOADMISION = '''+@NOADMISION+''''  
   EXEC (@LINEA)
   
   PRINT 'HADM_S'
   SELECT @LINEA =  '   INSERT INTO HADM_S (NOADMISION, FACTN, FECHA, DB_CR, AREAPRESTACION, AREAFUNCONT, UBICACION, VR_TOTAL, IMPUTACION,
                                            CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, VALOR, VLR_SERVICI, CANTIDAD, VLR_COPAGOS, VLR_PAGCOMP,
                                            IDPROVEEDOR, SUBCCOSTO, NOPRESTACION, NOITEM, PCOSTO)
   SELECT A.NOADMISION, A.FACTN, A.FECHA, A.DB_CR, A.AREAPRESTACION, A.AREAFUNCONT, A.UBICACION, A.VR_TOTAL, A.IMPUTACION,
          A.CCOSTO, A.PREFIJO, A.ANEXO, A.REFERENCIA, A.IDCIRUGIA, A.VALOR, A.VLR_SERVICI, A.CANTIDAD, A.VLR_COPAGOS, A.VLR_PAGCOMP,
          A.IDPROVEEDOR, A.SUBCCOSTO, A.NOPRESTACION, A.NOITEM, A.PCOSTO
   FROM   ' + @NOMBD + '.DBO.HADM_S A 
   WHERE  EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    NOT EXISTS (SELECT * FROM HADM_S 
                      WHERE  HADM_S.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default
                      AND    HADM_S.FACTN      = A.FACTN
                      )
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HCTC'
   SELECT @LINEA =  '   INSERT INTO HCTC ( CNSHCTC, F_SOLICITUD, F_ENVIADO, ESTADO, F_APROBADO, NOADMISION, USUARIO )
   SELECT A.CNSHCTC, A.F_SOLICITUD, A.F_ENVIADO, A.ESTADO, A.F_APROBADO, A.NOADMISION, A.USUARIO
   FROM   ' + @NOMBD + '.DBO.HCTC A 
   WHERE  EXISTS ( SELECT NOADMISION FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    NOT EXISTS (SELECT NOADMISION FROM HCTC WHERE HCTC.CNSHCTC COLLATE database_default = A.CNSHCTC COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'HCTCD'
   SELECT @LINEA =  '   INSERT INTO HCTCD ( CNSHCTC, IDSERVICIO, Q_TOTAL, Q_PRESCRITA, Q_APROBADA, Q_DADA, Q_PENDIENTE )
   SELECT A.CNSHCTC, A.IDSERVICIO, A.Q_TOTAL, A.Q_PRESCRITA, A.Q_APROBADA, A.Q_DADA, A.Q_PENDIENTE
   FROM   ' + @NOMBD + '.DBO.HCTCD A 
   WHERE  EXISTS ( SELECT * FROM HADM INNER JOIN HCTC ON HADM.NOADMISION COLLATE database_default = HCTC.NOADMISION COLLATE database_default
                   WHERE  HCTC.CNSHCTC COLLATE database_default = A.CNSHCTC COLLATE database_default
                   AND    HADM.NOADMISION = '''+@NOADMISION+''' )
   AND    NOT EXISTS (SELECT * FROM HCTCD WHERE HCTCD.CNSHCTC    COLLATE database_default = A.CNSHCTC COLLATE database_default
                                            AND HCTCD.IDSERVICIO COLLATE database_default = A.IDSERVICIO COLLATE database_default)'
   EXEC (@LINEA)
   
   PRINT 'HCTCDORD'
   SELECT @LINEA =  '   INSERT INTO HCTCDORD ( CNSHCTC, IDSERVICIO, CONSECUTIVOHCA, ITEMRED, CODOM, CANTIDAD, ESTADO )
   SELECT A.CNSHCTC, A.IDSERVICIO, A.CONSECUTIVOHCA, A.ITEMRED, A.CODOM, A.CANTIDAD, A.ESTADO
   FROM   ' + @NOMBD + '.DBO.HCTCDORD A 
   WHERE  EXISTS ( SELECT * FROM HADM INNER JOIN HCTC     ON HADM.NOADMISION COLLATE database_default = HCTC.NOADMISION COLLATE database_default
                                      INNER JOIN HCTCD    ON HCTC.CNSHCTC    COLLATE database_default = HCTC.CNSHCTC COLLATE database_default
                                      INNER JOIN HCTCDORD ON HCTCD.CNSHCTC   COLLATE database_default = HCTCDORD.CNSHCTC COLLATE database_default
                                                         AND HCTCD.IDSERVICIO COLLATE database_default= HCTCDORD.IDSERVICIO COLLATE database_default
                   WHERE  HCTCDORD.CNSHCTC COLLATE database_default = A.CNSHCTC COLLATE database_default
                   AND    HADM.NOADMISION = '''+@NOADMISION+''' )
   AND    NOT EXISTS (SELECT * FROM HCTCDORD WHERE HCTCDORD.CNSHCTC COLLATE database_default        = A.CNSHCTC COLLATE database_default
                                               AND HCTCDORD.IDSERVICIO COLLATE database_default     = A.IDSERVICIO COLLATE database_default
                                               AND HCTCDORD.CONSECUTIVOHCA COLLATE database_default = A.CONSECUTIVOHCA COLLATE database_default
                                               AND HCTCDORD.ITEMRED        = A.ITEMRED
                                               AND HCTCDORD.CODOM COLLATE database_default          = A.CODOM COLLATE database_default)'
   EXEC (@LINEA)
   
   PRINT 'HADMNOT'
   SELECT @LINEA =  '   INSERT INTO HADMNOT ( NOADMISION, ITEM, FECHA, OBS, USUARIO, CLASE, ESTADO, ITEMREF )
                        SELECT A.NOADMISION, A.ITEM, A.FECHA, A.OBS, A.USUARIO, A.CLASE, A.ESTADO, A.ITEMREF
                        FROM   ' + @NOMBD + '.DBO.HADMNOT A 
                        WHERE  EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
                        AND    NOT EXISTS (SELECT * FROM HADMNOT 
                                           WHERE  HADMNOT.NOADMISION COLLATE database_default      = A.NOADMISION COLLATE database_default
                                           AND    HADMNOT.ITEM             = A.ITEM )
                        AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
   
   PRINT 'NOTXDET'
   SELECT @LINEA =  '   INSERT INTO NOTXDET ( ITEM, NOADMISION, GRUPO, USUARIO, GENERAL)
                        SELECT A.ITEM, A.NOADMISION, A.GRUPO, A.USUARIO, A.GENERAL
                        FROM   ' + @NOMBD + '.DBO.NOTXDET A
                        WHERE  EXISTS (SELECT * FROM HADMNOT WHERE HADMNOT.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default
                                                             AND   HADMNOT.ITEM = A.ITEM
                                                             AND   HADMNOT.NOADMISION = '''+@NOADMISION+''' )
                        AND    NOT EXISTS (SELECT * FROM NOTXDET WHERE NOTXDET.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default
                                                                 AND   NOTXDET.ITEM = A.ITEM
                                                                 AND   NOTXDET.GRUPO COLLATE database_default = A.GRUPO
                                                                 AND   NOTXDET.USUARIO COLLATE database_default = A.USUARIO)'
   EXEC (@LINEA)

   PRINT 'HEVEN'
   SELECT @LINEA =  '   INSERT INTO HEVEN ( NOADMISION, EVENTO, USUARIO, SYS_COMPUTERNAME, CONSECUTIVOGEN, REFERENCIA1,
                                            REFERENCIA2, FECHA, CLASE )
   SELECT A.NOADMISION, A.EVENTO, A.USUARIO, A.SYS_COMPUTERNAME, A.CONSECUTIVOGEN, A.REFERENCIA1,
          A.REFERENCIA2, A.FECHA, A.CLASE
   FROM   ' + @NOMBD + '.DBO.HEVEN A 
   WHERE  EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default
                   AND    A.NOADMISION = '''+@NOADMISION+''' )
   AND    NOT EXISTS (SELECT * FROM HEVEN 
                      WHERE  HEVEN.NOADMISION COLLATE database_default      = A.NOADMISION COLLATE database_default
                      AND    HEVEN.ITEM             = A.ITEM )'
   EXEC (@LINEA)
   
   PRINT 'APAG'
   SELECT @LINEA =  '   INSERT INTO APAG ( IDPAGARE, IDTERCERO, FECHA, VALOR_NUM, FECHAVENCE, FECHAVENCE_FATE, FORMA_PAGO,
                                           CONFIRMACION, DESCRIPCION, NOADMISION )
   SELECT A.IDPAGARE, A.IDTERCERO, A.FECHA, A.VALOR_NUM, A.FECHAVENCE, A.FECHAVENCE_FATE, A.FORMA_PAGO,
                                           A.CONFIRMACION, A.DESCRIPCION, A.NOADMISION
   FROM   ' + @NOMBD + '.DBO.APAG A 
   WHERE  EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    NOT EXISTS (SELECT * FROM APAG
                      WHERE  APAG.IDPAGARE COLLATE database_default      = A.IDPAGARE COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)
     
   PRINT 'SAUT'
   SELECT @LINEA =  '   INSERT INTO SAUT ( NOADMISION, IDSERVICIO, CANTIDAD )
   SELECT A.NOADMISION, A.IDSERVICIO, A.CANTIDAD
   FROM   ' + @NOMBD + '.DBO.SAUT A 
   WHERE  NOT EXISTS ( SELECT * FROM SAUT WHERE SAUT.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default
                                      AND   SAUT.IDSERVICIO COLLATE database_default = A.IDSERVICIO COLLATE database_default)
   AND    EXISTS (SELECT * FROM HADM
                           WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
   AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)

   PRINT 'HAUT'
   SELECT @LINEA =  ' INSERT INTO HAUT (  CNSHAUT, NOADMISION, TIPO, CLASE, FECHA, IDTERCERO, IDPLAN, NOAUTORIZACION, DESTINO, ORIGEN, ESTADO, USUARIO,
                                          SYS_ComputerName, TIPOINCONSISTENCIA, PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE, TIPO_DOC, DOCIDAFILIADO,
                                          FNACIMIENTO, OBSERVACION, TIPOADM, DXINGRESO, DXSALIDA1, DXSALIDA2, CAUSAEXTERNA,DECLARIESGOS, URG_NOMBRE,
                                          HABCAMA, N_FACTURA, CONCEPTO, VLR_RECAUDADO, RAZON_NO_PAGO,IDMEDICOREPOR)    
                      SELECT CNSHAUT, NOADMISION, TIPO, CLASE, FECHA, IDTERCERO, IDPLAN, NOAUTORIZACION, DESTINO, ORIGEN, ESTADO, USUARIO,
                             SYS_ComputerName, TIPOINCONSISTENCIA, PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE, TIPO_DOC, DOCIDAFILIADO,
                             FNACIMIENTO, OBSERVACION, TIPOADM, DXINGRESO, DXSALIDA1, DXSALIDA2, CAUSAEXTERNA,DECLARIESGOS, URG_NOMBRE,
                             HABCAMA, N_FACTURA, CONCEPTO, VLR_RECAUDADO, RAZON_NO_PAGO,IDMEDICOREPOR
                      FROM   ' + @NOMBD + '.DBO.HAUT A
                      WHERE  NOT EXISTS ( SELECT * FROM HAUT WHERE HAUT.CNSHAUT COLLATE database_default = A.CNSHAUT COLLATE database_default)
                      AND    EXISTS     ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
                      AND    A.NOADMISION = '''+@NOADMISION+'''' 
   EXEC (@LINEA)

   PRINT 'HAUTD'
   SELECT @LINEA = ' INSERT INTO HAUTD (CNSHAUT, ITEM, EVENTO, FECHA, USUARIO, SYS_ComputerName,MEDIO,CAUSAL, OBSERVACIONES)
                     SELECT CNSHAUT, ITEM, EVENTO, FECHA, USUARIO, SYS_ComputerName,MEDIO,CAUSAL, OBSERVACIONES
                     FROM   ' + @NOMBD + '.DBO.HAUTD A
                     WHERE  NOT EXISTS (SELECT * FROM HAUTD WHERE HAUTD.CNSHAUT COLLATE database_default = A.CNSHAUT COLLATE database_default 
                                                            AND   HAUTD.ITEM = A.ITEM)
                     AND    EXISTS     (SELECT * FROM HAUT WHERE HAUT.CNSHAUT COLLATE database_default = A.CNSHAUT COLLATE database_default 
                                        AND    HAUT.NOADMISION = '''+@NOADMISION+''' )'
   EXEC (@LINEA) 

   PRINT 'HAUTSER' 
   SELECT @LINEA = ' INSERT INTO HAUTSER (CNSHAUT, IDSERVICIO, CANTIDADSER)
                     SELECT CNSHAUT, IDSERVICIO, CANTIDADSER
                     FROM ' + @NOMBD + '.DBO.HAUTSER A
                     WHERE  NOT EXISTS (SELECT * FROM HAUTSER WHERE HAUTSER.CNSHAUT COLLATE database_default = A.CNSHAUT COLLATE database_default
                                                              AND   HAUTSER.IDSERVICIO COLLATE database_default = A.IDSERVICIO COLLATE database_default)
                     AND    EXISTS     (SELECT * FROM HAUT WHERE HAUT.CNSHAUT COLLATE database_default = A.CNSHAUT COLLATE database_default 
                                        AND    HAUT.NOADMISION = '''+@NOADMISION+''' )'
   EXEC (@LINEA) 

   PRINT 'HCANE'
   SELECT @LINEA = ' INSERT INTO HCANE (CNSANESTESIA, CONSECUTIVOQXPCXD, ITEMQXPCXD, NOADMISION, IDAFILIADO, IDMEDICO, AYUNOLIQ, AYUNOSOL,TANESTESIA, 
                                        CANESTESIA, ESPACIOESP, NIVEL, AGUJA, FECHAIND, FECHAPLANTILLA, USUARIO)
                     SELECT A.CNSANESTESIA, A.CONSECUTIVOQXPCXD, A.ITEMQXPCXD, A.NOADMISION, A.IDAFILIADO, A.IDMEDICO, A.AYUNOLIQ, A.AYUNOSOL,A.TANESTESIA, 
                                        A.CANESTESIA, A.ESPACIOESP, A.NIVEL, A.AGUJA, A.FECHAIND, A.FECHAPLANTILLA, A.USUARIO
                     FROM   ' + @NOMBD + '.DBO.HCANE A
                     WHERE  EXISTS ( SELECT * FROM HADM WHERE HADM.NOADMISION COLLATE database_default = A.NOADMISION COLLATE database_default)
                     AND    NOT EXISTS ( SELECT * FROM HCANE WHERE HCANE.CNSANESTESIA COLLATE database_default = A.CNSANESTESIA COLLATE database_default )
                     AND    A.NOADMISION = '''+@NOADMISION+''''
   EXEC (@LINEA)

   PRINT 'HCANED'
   SELECT @LINEA = ' INSERT INTO HCANED (CNSANESTESIA, ITEM, FECHAEVO, PSISTOLICA, PDIASTOLICA, FCARDIACA, SAT02,RESPIRACION,OBSERVACION)
                     SELECT A.CNSANESTESIA, A.ITEM, A.FECHAEVO, A.PSISTOLICA, A.PDIASTOLICA, A.FCARDIACA, A.SAT02,A.RESPIRACION,A.OBSERVACION   
                     FROM  ' + @NOMBD + '.DBO.HCANED A
                     WHERE  EXISTS ( SELECT * FROM HCANE WHERE HCANE.CNSANESTESIA COLLATE database_default = A.CNSANESTESIA COLLATE database_default
                                     AND    HCANE.NOADMISION = '''+@NOADMISION+''')
                     AND    NOT EXISTS (SELECT * FROM HCANED WHERE HCANED.CNSANESTESIA COLLATE database_default = A.CNSANESTESIA COLLATE database_default
                                                             AND   HCANED.ITEM = A.ITEM )'
   EXEC (@LINEA)

   PRINT 'HCANEDMED'
   SELECT @LINEA = ' INSERT INTO HCANEDMED ( CNSANESTESIA, ITEM, IDSERVICIO, CANTIDAD, OBSERVACION)
                     SELECT A.CNSANESTESIA, A.ITEM, A.IDSERVICIO, A.CANTIDAD, A.OBSERVACION
                     FROM  ' + @NOMBD + '.DBO.HCANEDMED A INNER JOIN '+@NOMBD+'.DBO.HCANE B ON A.CNSANESTESIA COLLATE database_default = A.CNSANESTESIA COLLATE database_default
                     WHERE EXISTS ( SELECT * FROM HCANED WHERE HCANED.CNSANESTESIA COLLATE database_default = A.CNSANESTESIA COLLATE database_default
                                                         AND   HCANED.ITEM = A.ITEM )
                     AND   NOT EXISTS ( SELECT * FROM HCANEDMED WHERE HCANEDMED.CNSANESTESIA COLLATE database_default = A.CNSANESTESIA COLLATE database_default
                                                               AND   HCANEDMED.ITEM         = A.ITEM
                                                               AND   HCANEDMED.IDSERVICIO   COLLATE database_default = A.IDSERVICIO COLLATE database_default)
                     AND   B.NOADMISION = '''+@NOADMISION+''''
   EXEC (@LINEA)
END
