 
 SELECT  * FROM #A

 ALTER TABLE #A ADD ID INT IDENTITY(1,1)

 ALTER TABLE #A ADD CNSFACTU VARCHAR(20)

 SELECT CNSFACUT='06SI'+REPLACE(SPACE(6-LEN(ID)),SPACE(1),0)+CAST(ID AS VARCHAR(4))
 FROM #A

 UPDATE #A SET CNSFACTU='06SI'+REPLACE(SPACE(6-LEN(ID)),SPACE(1),0)+CAST(ID AS VARCHAR(4))

 SELECT  * INTO #C FROM FTRD WHERE N_FACTURA='FV10'

 SELECT DBO.FNK_COLUMNAS_TABLAS('FTRD')

 INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE, VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO, IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA,  TIPOFAC, OBSERVACION, TIPOVENTA, TIPOCOPAGO, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA, INDCXC, MARCA, INDASIGCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, IMPRESO,  VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC, MIVA, PIVA, VIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA, CCOSTO_ALTA, IDDEP, VLRNOTADB,  VLRNOTACR, TIPOTTEC, RAZONANULACION, CUENTACXC, IDAREA_FTR, CCOSTO_FTR, INDASIGENT, PLANDEPAGO, CUOTAS, FECHA_PP, PERIODODIAS, BANCO, TIPO_CUENTA, CTA_BCO, TIPOANULACION, CODUNG,  CODPRG, CAPITADA, CP_CONVENIO, CP_MODALIDAD, CP_MES, CP_VLR_SERVICIOS, CP_VLR_COPAGOS, SYS_COMPUTERNAME, ITFC, CNSITFC, CP_VLR_PAGCOMP, PREFACTURA, COPAGO_INT, COPAGO_EXT, ALTOCOSTO,  NROCONTROL, PAQUETE, CUENTACXC_RAD, ENPRESUPUESTO, CONSECUTIVOPTO, RECO, N_FACTURA_REEMPLAZA, IDSEDE, EQUIMARCA, SI, RDIAN, CNSRESOL, CASTIGADA, FACTURA_R, ENFACTORING, IDFACTORING,  FECHACAP_INI, FECHACAP_FIN, CTAVIGENCIAANTE, FACTE, CNSRESOLFE, PREFIJODIANFE, CNSDIANFE, IDFORMATO, IDCONTRATO, TIPO_OPERACION, TIPO_DOCUMENTO, ZIPKEY, CUFE, COPAPROPIO,  RECORECA, PPTORECA, FACTEP, DOCUMENTOID, DOCUXMLXZIPID, RUTARPTA, LINKFACTURA, PDF, OBSERVACION1)
 SELECT CNSFACTU, COMPANIA, CLASE, #A.IDTERCERO, #A.N_FACTURA, #A.F_FACTURA, #A.F_FACTURA+30, #A.VALOR, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO, IDAFILIADO, EMPLEADO, 
 NOREFERENCIA, PROCEDENCIA,  TIPOFAC, 'Saldos Iniciales Facturacion', TIPOVENTA, TIPOCOPAGO, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, 0, 0, 0, 0, MARCACONT,
 CONTABILIZADA, NROCOMPROBANTE, 0,  #A.VALOR, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC, MIVA, PIVA, VIVA, VR_ABONOS, #A.IDPLAN, NULL, TIPOFIN, 
 CNSFMAS, IDAREA_ALTA, CCOSTO_ALTA,'01', VLRNOTADB,  VLRNOTACR,#A.TIPOTTEC, RAZONANULACION, CUENTACXC, IDAREA_FTR, CCOSTO_FTR, 0, PLANDEPAGO, CUOTAS, FECHA_PP, 
 PERIODODIAS, BANCO, TIPO_CUENTA, CTA_BCO, TIPOANULACION, CODUNG,  CODPRG, CAPITADA, CP_CONVENIO, CP_MODALIDAD, CP_MES, CP_VLR_SERVICIOS, CP_VLR_COPAGOS, SYS_COMPUTERNAME,
 ITFC, CNSITFC, CP_VLR_PAGCOMP, PREFACTURA, COPAGO_INT, COPAGO_EXT, ALTOCOSTO,  NROCONTROL, PAQUETE, #A.CUENTA, ENPRESUPUESTO, CONSECUTIVOPTO, RECO, N_FACTURA_REEMPLAZA, 
 '06', EQUIMARCA, SI, RDIAN, CNSRESOL, CASTIGADA, FACTURA_R, ENFACTORING, IDFACTORING,  FECHACAP_INI, FECHACAP_FIN, CTAVIGENCIAANTE, FACTE, CNSRESOLFE, PREFIJODIANFE, CNSDIANFE, 
 IDFORMATO, IDCONTRATO, TIPO_OPERACION, TIPO_DOCUMENTO, ZIPKEY, NULL, COPAPROPIO,  RECORECA, PPTORECA, FACTEP, DOCUMENTOID, DOCUXMLXZIPID, RUTARPTA, LINKFACTURA, PDF, OBSERVACION1
 FROM #A,#B

 
 INSERT INTO FTRD(CNSFTR, IDPROVEEDOR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, AREAFUNCONT, UBICACION, VR_TOTAL, IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD, VALOR, VLR_SERVICI,  VLR_COPAGOS, VLR_PAGCOMP, NOADMISION, NOPRESTACION, NOITEM, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, VLRNOTADB, VLRNOTACR, TIPO, IDIMPUESTO, IDCLASE, ITEM, VLRIMPUESTO, PIVA, VIVA,  TIPOCONTRATOARS, ARSTIPOCONTRATO, ANO, MES, NAFILIADOS, IDPLAN, CODUNG, CODPRG, CUENTA_FIMPDV, ITFC, CNSITFC, CODEVAL, IDEMEDICA, PAQUETE, CUENTACR, SALDO, IDARTICULO, NOLOTE,  PROCEDENCIA, COPAGOS_CP, TIPOUSUARIO)
 SELECT CNSFACTU, IDPROVEEDOR, N_CUOTA, FECHA, DB_CR, '5105', AREAFUNCONT, UBICACION, #A.VALOR, IMPUTACION, '50301', 'SI', 'SALDOS INIICALES DE FACTURACION', '004', 
 IDCIRUGIA, CANTIDAD, #A.VALOR, #A.VALOR,  0, 0, NOADMISION, NOPRESTACION, NOITEM, #A.N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST, VLRNOTADB, VLRNOTACR, TIPO, IDIMPUESTO, 
 IDCLASE, ITEM, VLRIMPUESTO, PIVA, VIVA,  TIPOCONTRATOARS, ARSTIPOCONTRATO, ANO, MES, NAFILIADOS, #A.IDPLAN, CODUNG, CODPRG, CUENTA_FIMPDV, ITFC, CNSITFC, CODEVAL, 
 IDEMEDICA, PAQUETE, CUENTACR, SALDO, IDARTICULO, NOLOTE,  PROCEDENCIA, COPAGOS_CP, TIPOUSUARIO
 FROM #A,#C

 UPDATE FTR SET CAPITADA=NULL WHERE CNSFCT LIKE '06SI%'


 SELECT  * FROM 


 SELECT  DISTINCT IDTERCEROCA FROM CIT WHERE IDPLAN='CORT' AND FECHA>='01/11/2022' AND FECHA<'30/11/2022'