

SELECT CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,BASE_PRESTACIONES,ITEMCONCEPTO,BASE_CALCULO FROM FNK_VALORCONCEPTO_NEMPFD_RUN('17827299','073','01/01/2025','31/01/2025','01202501P30-1', 1,0,0)

SELECT CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,BASE_PRESTACIONES,ITEMCONCEPTO,BASE_CALCULO FROM FNK_VALORCONCEPTO_NEMPFD_RUN('17827299','074','01/01/2025','31/01/2025','01202501P30-1', 1,0,0)

SELECT CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,BASE_PRESTACIONES,ITEMCONCEPTO,BASE_CALCULO FROM FNK_VALORCONCEPTO_NEMPFD_RUN('17827299','018','01/01/2025','31/01/2025','01202501P30-1', 1,0,0)

SELECT  * FROM NEMP WHERE NUMDOC IN(17)

DROP TABLE #D
SELECT DISTINCT NUMDOC INTO #D FROM NPRFE WHERE NOT EXISTS(SELECT * FROM #C WHERE #C.NUMDOC=NPRFE.NUMDOC)

SELECT * INTO #A FROM NEMPE

DELETE #D WHERE NUMDOC='17827299'

SELECT * FROM #C

DELETE #C

INSERT INTO NEMPE(NUMDOC,CODCONCEPTO)
SELECT #D.NUMDOC,#A.CODCONCEPTO FROM #D,#A


SELECT  * FROM NEMPFD WHERE CNSPAGO='01202401P30-1' AND NOT EXISTS(SELECT * FROM #H WHERE NEMPFD.CODCONCEPTO=#H.CODCONCEPTO AND NEMPFD.NUMDOC=#H.DOCUMENTO)

EXEC SPK_CALCULAR_NEMPF '01202401P30-1','' 

   UPDATE NPER SET 
   TOTAL_INGRESOS     = CASE WHEN V.TOTAL_INGRESOS IS NULL THEN 0 ELSE V.TOTAL_INGRESOS END, 
         TOTAL_EGRESOS      = CASE WHEN V.TOTAL_EGRESOS IS NULL THEN 0 ELSE V.TOTAL_EGRESOS END,  
         TOTAL_APORTES      = CASE WHEN V.TOTAL_APORTES IS NULL THEN 0 ELSE V.TOTAL_APORTES END,
   TOTAL_PARAFISCALES = CASE WHEN P.TOTAL_PARAFISCALES IS NULL THEN 0 ELSE P.TOTAL_PARAFISCALES END
   FROM NPER,
      (SELECT SUM(VALOR_INGRESOS) AS TOTAL_INGRESOS,SUM(VALOR_EGRESOS) AS TOTAL_EGRESOS,
         SUM(VALOR_APORTES) AS TOTAL_APORTES FROM NEMPF WHERE CNSPAGO= '01202401P30-1') V,
      (SELECT SUM(TOTAL_PARAFISCALES) AS TOTAL_PARAFISCALES
         FROM NPERP INNER JOIN NPRF ON NPRF.CODPRF=NPERP.CODPRF WHERE NPERP.CNSPAGO= '01202401P30-1' AND NPRF.CLASE='Parafiscal') P
   WHERE CNSPAGO= '01202401P30-1'

   UPDATE NPER SET TOTAL_NOMINA=TOTAL_INGRESOS+TOTAL_APORTES+TOTAL_PARAFISCALES 
   WHERE CNSPAGO= '01202401P30-1'

   SELECT * FROM NEMPF WHERE CNSPAGO='01202401P30-1' AND VALOR_NETO>0

UPDATE NPER SET CERRADO=1, CONTABILIZADA=1 WHERE CNSPAGO='02202501P30-1'

DELETE NEMPFD WHERE CNSPAGO='02202501P30-1' AND NOT EXISTS(SELECT * FROM #H WHERE NEMPFD.CODCONCEPTO=#H.CODCONCEPTO AND NEMPFD.NUMDOC=#H.DOCUMENTO)

SELECT * FROM #H WHERE NOT EXISTS(SELECT * FROM NEMPFD WHERE CNSPAGO='02202501P30-1' AND NEMPFD.CODCONCEPTO=#H.CODCONCEPTO AND NEMPFD.NUMDOC=#H.DOCUMENTO) AND #H.VALOR>0 AND NOMI='ope'

UPDATE NEMPFD SET VALOR=0,VALOR_EMPRESA=0,VALOR100P=0  WHERE CNSPAGO='02202501P30-1'

UPDATE NEMPFD SET VALOR=CASE WHEN NCOND.VALOR>0 THEN  #H.VALOR  ELSE 0 END,VALOR_EMPRESA=CASE WHEN NCOND.VALOR_EMPRESA>0 THEN  #H.VALOR  ELSE 0 END,VALOR100P=#H.VALOR
FROM NEMPFD INNER JOIN #H ON NEMPFD.NUMDOC=#H.DOCUMENTO AND  NEMPFD.CODCONCEPTO=#H.CODCONCEPTO
           INNER JOIN NCOND ON #H.CODCONCEPTO=NCOND.CODCONCEPTO
WHERE CNSPAGO='01202401P30-1'


SELECT * FROM #F

UPDATE #F SET CODCONCEPTO=REPLACE(REPLACE(CODCONCEPTO,'[',''),']','')

SELECT  DISTINCT DOCUMENTO INTO #G FROM XNOMI1

SELECT #G.DOCUMENTO,#F.CODCONCEPTO INTO #H
FROM #G,#F
ORDER BY #G.DOCUMENTO

ALTER TABLE #H ADD VALOR DECIMAL(14,2)
ALTER TABLE #H ADD NOMI VARCHAR(10)

SELECT * FROM #H


UPDATE #H SET VALOR =XNOMI1.[001]
FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO
WHERE #H.CODCONCEPTO='001'


UPDATE #H SET VALOR =XNOMI1.[002] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='002'
UPDATE #H SET VALOR =XNOMI1.[003] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='003'
UPDATE #H SET VALOR =XNOMI1.[004] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='004'
UPDATE #H SET VALOR =XNOMI1.[012] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='012'
UPDATE #H SET VALOR =XNOMI1.[014] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='014'
UPDATE #H SET VALOR =XNOMI1.[015] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='015'
UPDATE #H SET VALOR =XNOMI1.[016] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='016'
UPDATE #H SET VALOR =XNOMI1.[017] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='017'
UPDATE #H SET VALOR =XNOMI1.[018] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='018'
UPDATE #H SET VALOR =XNOMI1.[038] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='038'
UPDATE #H SET VALOR =XNOMI1.[005] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='005'
UPDATE #H SET VALOR =XNOMI1.[005-1] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='005-1'
UPDATE #H SET VALOR =XNOMI1.[006] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='006'
UPDATE #H SET VALOR =XNOMI1.[006-1] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='006-1'
UPDATE #H SET VALOR =XNOMI1.[008] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='008'
UPDATE #H SET VALOR =XNOMI1.[007] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='007'
UPDATE #H SET VALOR =XNOMI1.[009] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='009'
UPDATE #H SET VALOR =XNOMI1.[010] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='010'
UPDATE #H SET VALOR =XNOMI1.[011] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='011'
UPDATE #H SET VALOR =XNOMI1.[020] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='020'
UPDATE #H SET VALOR =XNOMI1.[021] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='021'
UPDATE #H SET VALOR =XNOMI1.[023] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='023'
UPDATE #H SET VALOR =XNOMI1.[024] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='024'
UPDATE #H SET VALOR =XNOMI1.[026] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='026'
UPDATE #H SET VALOR =XNOMI1.[031] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='031'
UPDATE #H SET VALOR =XNOMI1.[037] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='037'
UPDATE #H SET VALOR =XNOMI1.[032] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='032'
UPDATE #H SET VALOR =XNOMI1.[034] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='034'
UPDATE #H SET VALOR =XNOMI1.[035] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='035'
UPDATE #H SET VALOR =XNOMI1.[036] FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO WHERE #H.CODCONCEPTO='036'

UPDATE #H SET NOMI=XNOMI1.NOMI
FROM #H INNER JOIN XNOMI1 ON #H.DOCUMENTO=XNOMI1.DOCUMENTO