

SELECT CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,BASE_PRESTACIONES,ITEMCONCEPTO,BASE_CALCULO FROM FNK_VALORCONCEPTO_NEMPFD_RUN('17827299','073','01/01/2025','31/01/2025','01202501P30-1', 1,0,0)

SELECT CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,BASE_PRESTACIONES,ITEMCONCEPTO,BASE_CALCULO FROM FNK_VALORCONCEPTO_NEMPFD_RUN('17827299','074','01/01/2025','31/01/2025','01202501P30-1', 1,0,0)

SELECT CANTIDAD,VALOR_EMPLEADO,VALOR_EMPRESA,VALOR100P,IDTRANSPRESTAMO,NUMDOCPRESTAMO,NUMCUOTA,CODPRF,IDTERCERO,BASE_PRESTACIONES,ITEMCONCEPTO,BASE_CALCULO FROM FNK_VALORCONCEPTO_NEMPFD_RUN('17827299','018','01/01/2025','31/01/2025','01202501P30-1', 1,0,0)

SELECT  * FROM NEMP WHERE NUMDOC IN(17)

DROP TABLE #D
SELECT DISTINCT NUMDOC INTO #D FROM NPRFE WHERE NOT EXISTS(SELECT * FROM #C WHERE #C.NUMDOC=NPRFE.NUMDOC)

SELECT * INTO #A FROM NEMPE

SELECT  TOP 1 * INTO DBO.XNOMI2 FROM XNOMI1

DELETE XNOMI2
SELECT DBO.FNK_COLUMNAS_TABLAS('XNOMI2')

USE PRUEBAS

SELECT * FROM XNOMI2

DELETE #D WHERE NUMDOC='17827299'

SELECT * FROM #C

DELETE #C

INSERT INTO NEMPE(NUMDOC,CODCONCEPTO)
SELECT #D.NUMDOC,#A.CODCONCEPTO FROM #D,#A


SELECT  * FROM NEMPFD WHERE CNSPAGO='02202401P30-1' AND NOT EXISTS(SELECT * FROM #H WHERE NEMPFD.CODCONCEPTO=#H.CODCONCEPTO AND NEMPFD.NUMDOC=#H.DOCUMENTO)

EXEC SPK_CALCULAR_NEMPF '01202402P30-1','' 

   UPDATE NPER SET 
   TOTAL_INGRESOS     = CASE WHEN V.TOTAL_INGRESOS IS NULL THEN 0 ELSE V.TOTAL_INGRESOS END, 
         TOTAL_EGRESOS      = CASE WHEN V.TOTAL_EGRESOS IS NULL THEN 0 ELSE V.TOTAL_EGRESOS END,  
         TOTAL_APORTES      = CASE WHEN V.TOTAL_APORTES IS NULL THEN 0 ELSE V.TOTAL_APORTES END,
   TOTAL_PARAFISCALES = CASE WHEN P.TOTAL_PARAFISCALES IS NULL THEN 0 ELSE P.TOTAL_PARAFISCALES END
   FROM NPER,
      (SELECT SUM(VALOR_INGRESOS) AS TOTAL_INGRESOS,SUM(VALOR_EGRESOS) AS TOTAL_EGRESOS,
         SUM(VALOR_APORTES) AS TOTAL_APORTES FROM NEMPF WHERE CNSPAGO= '01202402P30-1') V,
      (SELECT SUM(TOTAL_PARAFISCALES) AS TOTAL_PARAFISCALES
         FROM NPERP INNER JOIN NPRF ON NPRF.CODPRF=NPERP.CODPRF WHERE NPERP.CNSPAGO= '01202402P30-1' AND NPRF.CLASE='Parafiscal') P
   WHERE CNSPAGO= '01202402P30-1'

   UPDATE NPER SET TOTAL_NOMINA=TOTAL_INGRESOS+TOTAL_APORTES+TOTAL_PARAFISCALES 
   WHERE CNSPAGO= '01202402P30-1'

   SELECT * FROM NEMPF WHERE CNSPAGO='01202402P30-1' AND VALOR_NETO>0

UPDATE NPER SET CERRADO=1, CONTABILIZADA=1 WHERE CNSPAGO='01202402P30-1'

SELECT TOP 1 * FROM NEMPFD WHERE CNSPAGO='01202402P30-1'

DELETE NEMPFD WHERE CNSPAGO='01202402P30-1' AND NOT EXISTS(SELECT * FROM #H WHERE NEMPFD.CODCONCEPTO=#H.CODCONCEPTO AND NEMPFD.NUMDOC=#H.DOCUMENTO)

SELECT * FROM #H WHERE NOT EXISTS(SELECT * FROM NEMPFD WHERE CNSPAGO='01202402P30-1' AND NEMPFD.CODCONCEPTO=#H.CODCONCEPTO AND NEMPFD.NUMDOC=#H.DOCUMENTO) AND #H.VALOR>0 AND NOMI='ADM'
SELECT DISTINCT DOCUMENTO INTO #X FROM #H WHERE NOT EXISTS(SELECT * FROM NEMPFD WHERE CNSPAGO='01202402P30-1' AND NEMPFD.NUMDOC=#H.DOCUMENTO) AND #H.VALOR>0 AND NOMI='ADM'

SELECT  * FROM NEMPF INNER JOIN NEMP ON NEMPF.NUMDOC=NEMP.NUMDOC
WHERE NOT EXISTS(SELECT * FROM #H WHERE NEMP.DOCIDEMPLEADO=#H.DOCUMENTO AND #H.NOMI='ADM')
AND NEMPF.CNSPAGO='02202501P30-1'

UPDATE NEMPFD SET VALOR=0,VALOR_EMPRESA=0,VALOR100P=0  WHERE CNSPAGO='01202402P30-1'

UPDATE NEMPFD SET VALOR=CASE WHEN NCOND.VALOR>0 THEN  #H.VALOR  ELSE 0 END,VALOR_EMPRESA=CASE WHEN NCOND.VALOR_EMPRESA>0 THEN  #H.VALOR  ELSE 0 END,VALOR100P=#H.VALOR
FROM NEMPFD INNER JOIN #H ON NEMPFD.NUMDOC=#H.DOCUMENTO AND  NEMPFD.CODCONCEPTO=#H.CODCONCEPTO
           INNER JOIN NCOND ON #H.CODCONCEPTO=NCOND.CODCONCEPTO
WHERE CNSPAGO='01202402P30-1'

SELECT '001'CODCONCEPTO INTO #F UNION ALL 
SELECT '002'UNION ALL 
SELECT '003'UNION ALL 
SELECT '004'UNION ALL 
SELECT '012'UNION ALL 
SELECT '014'UNION ALL 
SELECT '015'UNION ALL 
SELECT '016'UNION ALL 
SELECT '017'UNION ALL 
SELECT '018'UNION ALL 
SELECT '038'UNION ALL 
SELECT '005'UNION ALL 
SELECT '005-1'UNION ALL 
SELECT '006'UNION ALL 
SELECT '006-1'UNION ALL 
SELECT '008'UNION ALL 
SELECT '007'UNION ALL 
SELECT '009'UNION ALL 
SELECT '010'UNION ALL 
SELECT '011'UNION ALL 
SELECT '020'UNION ALL 
SELECT '021'UNION ALL 
SELECT '023'UNION ALL 
SELECT '024'UNION ALL 
SELECT '026'UNION ALL 
SELECT '031'UNION ALL 
SELECT '037'UNION ALL 
SELECT '032'UNION ALL 
SELECT '034'UNION ALL 
SELECT '035'UNION ALL 
SELECT '036'  


SELECT * FROM #F

UPDATE #F SET CODCONCEPTO=REPLACE(REPLACE(CODCONCEPTO,'[',''),']','')

SELECT  DISTINCT DOCUMENTO INTO #G FROM XNOMI2

SELECT #G.DOCUMENTO,#F.CODCONCEPTO INTO #H
FROM #G,#F
ORDER BY #G.DOCUMENTO

ALTER TABLE #H ADD VALOR DECIMAL(14,2)
ALTER TABLE #H ADD NOMI VARCHAR(10)

SELECT * FROM #H


UPDATE #H SET VALOR =XNOMI2.[001]
FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO
WHERE #H.CODCONCEPTO='001'


UPDATE #H SET VALOR =XNOMI2.[002] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='002'
UPDATE #H SET VALOR =XNOMI2.[003] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='003'
UPDATE #H SET VALOR =XNOMI2.[004] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='004'
UPDATE #H SET VALOR =XNOMI2.[012] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='012'
UPDATE #H SET VALOR =XNOMI2.[014] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='014'
UPDATE #H SET VALOR =XNOMI2.[015] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='015'
UPDATE #H SET VALOR =XNOMI2.[016] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='016'
UPDATE #H SET VALOR =XNOMI2.[017] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='017'
UPDATE #H SET VALOR =XNOMI2.[018] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='018'
UPDATE #H SET VALOR =XNOMI2.[038] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='038'
UPDATE #H SET VALOR =XNOMI2.[005] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='005'
UPDATE #H SET VALOR =XNOMI2.[005-1] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='005-1'
UPDATE #H SET VALOR =XNOMI2.[006] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='006'
UPDATE #H SET VALOR =XNOMI2.[006-1] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='006-1'
UPDATE #H SET VALOR =XNOMI2.[008] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='008'
UPDATE #H SET VALOR =XNOMI2.[007] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='007'
UPDATE #H SET VALOR =XNOMI2.[009] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='009'
UPDATE #H SET VALOR =XNOMI2.[010] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='010'
UPDATE #H SET VALOR =XNOMI2.[011] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='011'
UPDATE #H SET VALOR =XNOMI2.[020] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='020'
UPDATE #H SET VALOR =XNOMI2.[021] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='021'
UPDATE #H SET VALOR =XNOMI2.[023] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='023'
UPDATE #H SET VALOR =XNOMI2.[024] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='024'
UPDATE #H SET VALOR =XNOMI2.[026] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='026'
UPDATE #H SET VALOR =XNOMI2.[031] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='031'
UPDATE #H SET VALOR =XNOMI2.[037] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='037'
UPDATE #H SET VALOR =XNOMI2.[032] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='032'
UPDATE #H SET VALOR =XNOMI2.[034] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='034'
UPDATE #H SET VALOR =XNOMI2.[035] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='035'
UPDATE #H SET VALOR =XNOMI2.[036] FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO WHERE #H.CODCONCEPTO='036'

UPDATE #H SET NOMI=XNOMI2.NOMI
FROM #H INNER JOIN XNOMI2 ON #H.DOCUMENTO=XNOMI2.DOCUMENTO


SELECT #X.DOCUMENTO,TER.RAZONSOCIAL,TER.TIPO_ID FROM #X INNER JOIN TER ON #X.DOCUMENTO=TER.NIT

