USE KUNIPSSAM

DECLARE @NOADMISION VARCHAR(20)
DECLARE @FECHAINI DATETIME
DECLARE @FECHAMAX DATETIME
DECLARE @CONSECUTIVO VARCHAR(20)
DECLARE @CONSECUTIVO1 VARCHAR(20)
DECLARE @NRO SMALLINT

SELECT @FECHAINI='30/09/2023' --DBO.FNK_FECHA_SIN_MLS(GETDATE())
SELECT @FECHAMAX=@FECHAINI+1


	DECLARE PG_CURSOR CURSOR FOR   
   SELECT  NOADMISION FROM HADM WHERE COALESCE(FECHAALTAMED,GETDATE())>=@FECHAINI AND FECHA<@FECHAMAX 
	OPEN PG_CURSOR    
	FETCH NEXT FROM PG_CURSOR    
	INTO @NOADMISION
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
      IF EXISTS(SELECT * FROM HCA WHERE NOADMISION=@NOADMISION AND CLASEPLANTILLA='OMEDICA' AND FECHA>=@FECHAINI AND FECHA<@FECHAMAX)
      BEGIN 
         PRINT 'YA TIENE LA PLANTILLA...'
          FETCH NEXT FROM PG_CURSOR    
	       INTO @NOADMISION
          CONTINUE
      END
      PRINT '@NOADMISION = '+@NOADMISION
      SELECT @CONSECUTIVO=NULL
      SELECT TOP 1 @CONSECUTIVO=CONSECUTIVO FROM HCA WHERE NOADMISION=@NOADMISION 
      AND CLASEPLANTILLA='OMEDICA' 
      AND FECHA<@FECHAINI 
      ORDER BY FECHA DESC
      IF COALESCE(@CONSECUTIVO,'')=''
      BEGIN 
         PRINT 'NO TIENE LA PLANTILLA SOLICITADA...'
          FETCH NEXT FROM PG_CURSOR    
	       INTO @NOADMISION
          CONTINUE
      END

      SET @CONSECUTIVO1=SPACE(20)
      EXEC SPK_GENCONSECUTIVO '01','01','@HC',@CONSECUTIVO1 OUTPUT   
      SELECT @CONSECUTIVO1 = '01'+REPLACE(SPACE(8 - LEN(@CONSECUTIVO1))+LTRIM(RTRIM(@CONSECUTIVO1)),SPACE(1),0)



     --SELECT DBO.FNK_COLUMNAS_TABLAS('HCAPM')
      PRINT 'INSERTANDO HCA CONSECUTIVO '+@CONSECUTIVO1
      PRINT 'CONSECUTIVO ORIGINAL ='+@CONSECUTIVO

      INSERT INTO HCA(CONSECUTIVO, CLASEPLANTILLA, FECHA, IDMEDICO, IDAFILIADO, NOADMISION, IDDX, TIPODX, IMPRESO, EDAD, FINALIDAD, DX1, 
                      DX2, DX3, IDMEDICODILIGENCIA, IDDXEG, N_HISTORIA, PROCEDENCIA, REVISAESP,  IDMEDICOESP, PIDEDX, PIDESV, TAS, TAD, 
                      FC, FR, TEMP, TALLA, PULSO, PESO, GLASGOW, TIPOGLASGOW, HIDRATACION, ALTA, CLASE, ITEMHADM, IDAREA, ANULADA, USUARIOANU, 
                      FECHA_ANU,  OBSERVAANU, AMBITO, MED_ESPEC, CAUSA_EXT, SINCRONIZADO, IDPLAN, CCOSTO, ENEPICRISIS, CERRADA, EVOLUCION, 
                      ITEMRED, PLANDEMANEJO, RESUMEN, EVOLSUB, ANALISIS, ESTANCIA, RESPARACLINI,  JUSTESTANCIA, TAM, SOAT, BOLO, 
                      CONSECUTIVO_RED_ORI, ITEMRED_RED_ORI, DIURESIS, CNSNESIGVIT_SV, CNSNESIGVIT_GC, CNSNESIGVIT_GA, TIPOSV, PLANDEMANEJOMED, 
                      CNSNESIGVIT_GV, CNSNESIGVIT_PV,  CNSNESIGVIT_IO, TIPOPM, COPIADA, CONSECUTIVOCOPIA, REVISADO, FECHAREV, USUARIOREV, 
                      ESTADOCIERRE, CONSECUTIVOCIERRE, CREADAEN, SOFA, NOCOPIAOM, RIESGO, DX4, USUARIO, CODAZUL,  IDAFILIADO_RN, CNSWEB, 
                      CONSECUTIVOP, CONSECUTIVOCIT, COVID, FECHAATIENDE, CHECK1, CHECK2, CHECK3, NECPAL, N_S1, N_S2, N_S3, N_S4, N_S5, N_S6, 
                      ESTADOAUD, IDMEDICO_AUD, FECHA_AUD,  CODIGO_AUD, OBSERVACIONAUD)
      SELECT @CONSECUTIVO1, CLASEPLANTILLA, DATEADD(HOUR,10,@FECHAINI), IDMEDICO, IDAFILIADO, NOADMISION, IDDX, TIPODX, IMPRESO, EDAD, 
                  FINALIDAD, DX1, DX2, DX3, IDMEDICODILIGENCIA, IDDXEG, N_HISTORIA, PROCEDENCIA, REVISAESP,  IDMEDICOESP, PIDEDX, PIDESV, TAS, TAD, FC, 
                  FR, TEMP, TALLA, PULSO, PESO, GLASGOW, TIPOGLASGOW, HIDRATACION, ALTA, CLASE, ITEMHADM, IDAREA, ANULADA, USUARIOANU, FECHA_ANU,  OBSERVAANU,
                  AMBITO, MED_ESPEC, CAUSA_EXT, SINCRONIZADO, IDPLAN, CCOSTO, ENEPICRISIS, CERRADA, EVOLUCION, ITEMRED, PLANDEMANEJO, RESUMEN, EVOLSUB, 
                  ANALISIS, ESTANCIA, RESPARACLINI,  JUSTESTANCIA, TAM, SOAT, BOLO, CONSECUTIVO_RED_ORI, ITEMRED_RED_ORI, DIURESIS, CNSNESIGVIT_SV, 
                  CNSNESIGVIT_GC, CNSNESIGVIT_GA, TIPOSV, PLANDEMANEJOMED, CNSNESIGVIT_GV, CNSNESIGVIT_PV,  CNSNESIGVIT_IO, TIPOPM, COPIADA, CONSECUTIVOCOPIA, 
                  REVISADO, FECHAREV, USUARIOREV, ESTADOCIERRE, CONSECUTIVOCIERRE, CREADAEN, SOFA, NOCOPIAOM, RIESGO, DX4, USUARIO, CODAZUL,  IDAFILIADO_RN, 
                  CNSWEB, CONSECUTIVOP, CONSECUTIVOCIT, COVID, FECHAATIENDE, CHECK1, CHECK2, CHECK3, NECPAL, N_S1, N_S2, N_S3, N_S4, N_S5, N_S6, ESTADOAUD, 
                  IDMEDICO_AUD, FECHA_AUD,  CODIGO_AUD, OBSERVACIONAUD 
      FROM HCA 
      WHERE CONSECUTIVO=@CONSECUTIVO

      PRINT 'INSERTANDO EN HCAD'
      INSERT INTO HCAD(CONSECUTIVO, CLASEPLANTILLA, CAMPO, SECUENCIA, NADA, NORMAL, ANORMAL, DETALLAR, NOTAS, TIPOCAMPO, ALFANUMERICO, FECHA, 
                        MEMO, OBS, LISTA, ENEPICRISIS, SINCRONIZADO, MINIMO, MAXIMO, PROMEDIO,  VALORGRAFICA, NUMERICO)
      SELECT @CONSECUTIVO1, CLASEPLANTILLA, CAMPO, SECUENCIA, NADA, NORMAL, ANORMAL, DETALLAR, NOTAS, TIPOCAMPO, ALFANUMERICO, FECHA, MEMO, OBS, 
             LISTA, ENEPICRISIS, SINCRONIZADO, MINIMO, MAXIMO, PROMEDIO,  VALORGRAFICA, NUMERICO
      FROM HCAD WHERE CONSECUTIVO=@CONSECUTIVO

      INSERT INTO HCADL(CONSECUTIVO, SECUENCIA, ITEM, VALORLISTA, CHECKM, DESCRIPCION, SINCRONIZADO)
      SELECT CONSECUTIVO, SECUENCIA, ITEM, VALORLISTA, CHECKM, DESCRIPCION, SINCRONIZADO
      FROM HCADL WHERE CONSECUTIVO=@CONSECUTIVO

      INSERT INTO HCATD (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, CLASE, ENCARGOS, NOPRESTACION, 
                          APLICADA, CONSECUTIVONE, NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION,  TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR,
                          CANTIDADNOCC, CNSHJNOPOS, DESCRIPTIVA, DESTINO, OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, 
                          CANTIDADORI, FRECUENCIAORI,  DURACIONORI, DOSISUNICA, FECHAINI, IDSERVICIOMEZCLA, QMEZCLA, QIMPSERVICIO, QIMPMEZCLA, 
                          DURACIONIMP, RAZONNEC, ORDEN, HORAAM, QAM, HORAPM, QPM, HORASMAX, FECHAMAX, GOTEO,  GENHORARIO, LUNES, MARTES, MIERCOLES,
                          JUEVES, VIERNES, SABADO, DOMINGO, FFINALDOSIS, TIPOSOLBS, BSCAPACIDAD, IDBODEGA, CODPAQUETE, VERIFICA, LATERALIDAD, 
                          TIPOFRECUENCIA, DOSIF,  ESTADOCALL, FECHACALL, USUARIO, NOADMISION, OBS_CALL, IDCAUSAL, AUTORIZADO, HBALINI, RUTA, 
                          TOTALUNIDADES, PRESCRIPCION, TIPODURACION)
      SELECT @CONSECUTIVO1, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, 'C', 1, '0100000001', APLICADA, 
             CONSECUTIVONE, NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION,  TIPO, 1, FECHAGA, IDPROVEEDOR, CANTIDADNOCC, 
             CNSHJNOPOS, DESCRIPTIVA, DESTINO, OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, CANTIDADORI, 
             FRECUENCIAORI,  DURACIONORI, DOSISUNICA, FECHAINI, IDSERVICIOMEZCLA, QMEZCLA, QIMPSERVICIO, QIMPMEZCLA, DURACIONIMP, 
             RAZONNEC, ORDEN, HORAAM, QAM, HORAPM, QPM, HORASMAX, FECHAMAX, GOTEO,  GENHORARIO, LUNES, MARTES, MIERCOLES, JUEVES, 
             VIERNES, SABADO, DOMINGO, FFINALDOSIS, TIPOSOLBS, BSCAPACIDAD, IDBODEGA, CODPAQUETE, VERIFICA, LATERALIDAD, TIPOFRECUENCIA, 
             DOSIF,  ESTADOCALL, FECHACALL, USUARIO, NOADMISION, OBS_CALL, IDCAUSAL, AUTORIZADO, HBALINI, RUTA, TOTALUNIDADES, PRESCRIPCION,
             TIPODURACION
      FROM HCATD 
      WHERE CONSECUTIVO=@CONSECUTIVO
      AND HCATD.CLASE<>'S'

      INSERT INTO HCATDH(CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, HORA, CANTIDAD, IDSERVICIOD)
      SELECT @CONSECUTIVO1, ITEMRED, CODOM, IDSERVICIO, HORA, CANTIDAD, IDSERVICIOD
      FROM HCATDH
      WHERE CONSECUTIVO=@CONSECUTIVO

      INSERT INTO HCAPM(CONSECUTIVO, ORDEN, CLASE, OBSERVACION, IDSERVICIO, CLAMED, SECOPIA)
      SELECT @CONSECUTIVO1, ORDEN, CLASE, OBSERVACION, IDSERVICIO, CLAMED, SECOPIA
      FROM HCAPM
      WHERE CONSECUTIVO=@CONSECUTIVO
      AND EXISTS(SELECT * FROM HCATD WHERE HCATD.CODOM=HCAPM.CLAMED AND HCATD.IDSERVICIO=HCAPM.IDSERVICIO AND HCATD.CONSECUTIVO=@CONSECUTIVO1)

	FETCH NEXT FROM PG_CURSOR    
	INTO @NOADMISION
	END
	CLOSE PG_CURSOR
	DEALLOCATE PG_CURSOR