
PRINT 'EMPEZAMOS'
PRINT 'CAPTURA DE DATOS'
DECLARE @HORA INT
DECLARE @CUANTAS INT
DECLARE @ARREGLO INT
DECLARE @HOY     DATETIME

SELECT @HORA=DATEPART(HH,GETDATE())

PRINT 'CAMBIOS'

SELECT @CUANTAS=COUNT(*) FROM HHOM WHERE INFORMA IN (1, 3) 

IF COALESCE(@CUANTAS,0)>0
BEGIN
   PRINT 'REVISO QUE NO HAYAN FRECUENCIAS ERRADAS'
   IF (SELECT COUNT(*) FROM HHOM WHERE FRECUENCIA<1)>0
   BEGIN
      UPDATE HHOM SET FRECUENCIA=24 WHERE FRECUENCIA<1
   END

   EXEC SPK_CREA_ORDENTRAB_CM_CAMBIOS 'AUTOMATICO','01'

   PRINT 'Actualizo Izotpd'

   UPDATE IZOTPD SET CENTRAL='No' WHERE COALESCE(CENTRAL,'')=''

   PRINT 'Actualizo Izot'
   UPDATE IZOT SET ESTADO='Proceso' WHERE ESTADO='Generado'

   PRINT 'DATOS EN EL LOG'
   INSERT INTO KIXLOG.DBO.CENTRALOG(FECHA,PROCESO)
   SELECT GETDATE(),'CAMBIOS'
END
IF @HORA=11
BEGIN 
   IF (SELECT COUNT(*) FROM IZOT WHERE DBO.FNK_FECHA_SIN_HORA(IZOT.FECHA) =  DBO.FNK_FECHA_SIN_HORA(GETDATE())
       AND CLASE = '24HORAS' AND TIPO='CMEZCLA')<=0
   BEGIN 
      PRINT 'REVISO QUE NO HAYAN FRECUENCIAS ERRADAS'
      IF (SELECT COUNT(*) FROM HHOM WHERE FRECUENCIA<1)>0
      BEGIN
         UPDATE HHOM SET FRECUENCIA=24 WHERE FRECUENCIA<1
      END
      SELECT @HOY =  DBO.FNK_FECHA_SIN_HORA(GETDATE())
      EXEC SPK_CREAR_IZOT @HOY,'AUTOMATICO', '01'

      PRINT 'Actualizo Izotpd'

      UPDATE IZOTPD SET CENTRAL='No' WHERE COALESCE(CENTRAL,'')=''

      PRINT 'Actualizo Izot'
      UPDATE IZOT SET ESTADO='Proceso' WHERE ESTADO='Generado'
      
      PRINT 'DATOS EN EL LOG'
      INSERT INTO KIXLOG.DBO.CENTRALOG(FECHA,PROCESO)
      SELECT GETDATE(),'24 HORAS'

   END
   ELSE
   BEGIN
      PRINT 'YA SE GENERO'
      PRINT 'DATOS EN EL LOG'
      INSERT INTO KIXLOG.DBO.CENTRALOG(FECHA,PROCESO)
      SELECT GETDATE(),'24 YA GENERA'
   END
END 