
DROP TABLE #A

SELECT N_FACTURA,NOREFERENCIA,VR_TOTAL,PROCEDENCIA INTO #A
FROM FTR 
WHERE IDTERCERO='892115003' AND F_FACTURA>='20110101' AND F_FACTURA<='20140101'
AND PROCEDENCIA='CE' AND ESTADO='P' AND VR_TOTAL>=144700.00 AND VR_TOTAL<=1100000

DELETE #A WHERE VR_TOTAL<=0

SELECT N_FACTURA,VR_TOTAL INTO #F FROM FTRF WHERE VR_TOTAL<81000 AND COALESCE(NOADMISION,'')=''

SELECT * INTO #A1 FROM #A WHERE VR_TOTAL<=100000
SELECT * INTO #A2 FROM #A WHERE VR_TOTAL>100000 AND VR_TOTAL<=200000
SELECT * INTO #A3 FROM #A WHERE VR_TOTAL>200000 AND VR_TOTAL<=300000
SELECT * INTO #A4 FROM #A WHERE VR_TOTAL>300000 AND VR_TOTAL<=400000
SELECT * INTO #A5 FROM #A WHERE VR_TOTAL>400000 AND VR_TOTAL<=500000
SELECT * INTO #A6 FROM #A WHERE VR_TOTAL>500000 AND VR_TOTAL<=600000
SELECT * INTO #A7 FROM #A WHERE VR_TOTAL>600000 AND VR_TOTAL<=700000
SELECT * INTO #A8 FROM #A WHERE VR_TOTAL>700000 AND VR_TOTAL<=800000
SELECT * INTO #A9 FROM #A WHERE VR_TOTAL>800000 AND VR_TOTAL<=900000
SELECT * INTO #A10 FROM #A WHERE VR_TOTAL>900000 AND VR_TOTAL<=1000000
SELECT * INTO #A11 FROM #A WHERE VR_TOTAL>1000000 AND VR_TOTAL<=1100000
SELECT * INTO #A12 FROM #A WHERE VR_TOTAL>1100000 AND VR_TOTAL<=1200000
SELECT * INTO #A13 FROM #A WHERE VR_TOTAL>1200000 --AND VR_TOTAL<=1200000

   DECLARE @N_fACTURA VARCHAR(20)
   DECLARE @VALOR DECIMAL(14,2)
   DECLARE @NOADMISION VARCHAR(20)
   DECLARE @BASE DECIMAL(14,2)
   SET @BASE=10
   DECLARE PG_CURSOR CURSOR FOR 
   SELECT N_FACTURA,VR_TOTAL FROM FTRF WHERE COALESCE(NOADMISION,'')='' AND COALESCE(PROCEDENCIA,'')='SALUD' --AND VR_TOTAL<81000    
   OPEN PG_CURSOR    
   FETCH NEXT FROM PG_CURSOR    
   INTO @N_FACTURA,@VALOR
   WHILE @@FETCH_STATUS = 0    
   BEGIN
	  IF @VALOR<=100000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A1 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')  
	  END 
	  IF @VALOR>100000 AND @VALOR<=200000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A2 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF @VALOR>200000 AND @VALOR<=300000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A3 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF @VALOR>300000 AND @VALOR<=400000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A4 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF @VALOR>400000 AND @VALOR<=500000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A5 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF @VALOR>500000 AND @VALOR<=600000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A6 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF @VALOR>600000 AND @VALOR<=700000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A7 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')  
	  END 
	  IF @VALOR>700000 AND @VALOR<=800000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A8 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')
	  END 
	  IF @VALOR>800000 AND @VALOR<=900000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A9 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF @VALOR>900000 AND @VALOR<=1000000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A10 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF @VALOR>1000000 AND @VALOR<=1100000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A11 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF @VALOR>1100000 AND @VALOR<=1200000
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A12 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF @VALOR>1200000 
	  BEGIN
		  SELECT TOP 1 @NOADMISION=NOREFERENCIA FROM #A13 
		  WHERE VR_TOTAL>@VALOR-@BASE AND VR_TOTAL<@VALOR+@BASE	
		  AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE')	  
	  END 
	  IF COALESCE(@NOADMISION,'')<>''
	  BEGIN
		 PRINT 'SE ENCONTRO :::: '+@N_FACTURA +' VALOR: : :'+STR(@VALOR)
		 UPDATE FTRF SET NOADMISION=@NOADMISION,PROCEDENCIA='CE' WHERE N_FACTURA=@N_fACTURA
	  END
	  ELSE 
	  BEGIN 
		 PRINT 'NO SE ENCONTRO :::: '+@N_FACTURA+' VALOR: : :'+STR(@VALOR)
	  END
	  SELECT @NOADMISION=NULL
   FETCH NEXT FROM PG_CURSOR    
   INTO @N_FACTURA,@VALOR
   END
   CLOSE PG_CURSOR
   DEALLOCATE PG_CURSOR


   SELECT * FROM FTRF WHERE PROCEDENCIA='CE'

   SELECT PROCEDENCIA,ESTADO,VR_TOTAL FROM FTR WHERE NOREFERENCIA='0100547029' AND PROCEDENCIA='CE'
      SELECT * FROM FTRF WHERE NOADMISION='0100547029'

   SELECT N_FACTURA,NOADMISION INTO #V FROM FTRF WHERE COALESCE(PROCEDENCIA,'')='CE'

   SELECT NOADMISION,COUNT(*)
   FROM #V
   GROUP BY NOADMISION
   HAVING COUNT(*)>1

   SELECT * FROM FTRF WHERE COALESCE(PROCEDENCIA,'')=''
   --UPDATE FTRF SET NOADMISION=NULL,PROCEDENCIA=NULL WHERE COALESCE(N_FACTURAK,'')=''

   SELECT * FROM #A

   DROP TABLE #A
   --DROP TABLE #F
   DROP TABLE #A1
   DROP TABLE #A2
   DROP TABLE #A3
   DROP TABLE #A4
   DROP TABLE #A5
   DROP TABLE #A6
   DROP TABLE #A7
   DROP TABLE #A8
   DROP TABLE #A9
   DROP TABLE #A10
   DROP TABLE #A11
   DROP TABLE #A12
   DROP TABLE #A3


   UPDATE FTRF SET VLRADMI=B.VR_TOTAL
   FROM FTRF A INNER JOIN FTR B ON A.NOADMISION=B.NOREFERENCIA AND A.PROCEDENCIA=B.PROCEDENCIA
   WHERE A.PROCEDENCIA='CE'

   UPDATE FTRF SET DIFIERE=VR_TOTAL-VLRADMI WHERE PROCEDENCIA IN('CI','CE')

      SELECT * FROM FTRF WHERE PROCEDENCIA IN('CI','CE')

	  SELECT * FROM FTRF WHERE COALESCE(NOADMISION,'')=''

	  UPDATE FTRF SET NOADMISION=NULL,PROCEDENCIA=NULL WHERE PROCEDENCIA IN('CI','CE') AND VLRADMI=0


	  SELECT A.NOADMISION,SUM(A.VALOREXEDENTE) VALOR INTO #HADM
	  FROM HPRE A INNER JOIN HADM B ON A.NOADMISION=B.NOADMISION
	  WHERE B.IDTERCERO='892115003' AND B.FECHA>='20110101' AND B.FECHA<'20140101'
	  AND B.CLASEING='A' AND B.CERRADA=1 AND B.FACTURABLE=1
	  GROUP BY A.NOADMISION

	  UPDATE FTRF SET VLRADMI=B.VR_TOTAL
	  FROM FTRF A INNER JOIN #A B ON A.NOADMISION=B.NOREFERENCIA
	  WHERE A.PROCEDENCIA='SALUD'
	  
	  SELECT * FROM #A WHERE NOREFERENCIA='0100265296'

	  SELECT * FROM FTRF WHERE COALESCE(VLRADMI,0)=0
	  ORDER BY VR_TOTAL DESC

	  BEGIN TRAN
	  UPDATE FTRF SET NOADMISION=NULL,PROCEDENCIA=NULL WHERE COALESCE(N_FACTURAK,'')=''
	  COMMIT

	  ---
	  SELECT * FROM FTRF WHERE DIFIERE<>0

	  ALTER TABLE FTRF ADD N_FACTURAK VARCHAR(20)

	  UPDATE FTRF SET N_FACTURAK=B.N_FACTURA
	  FROM FTRF A INNER JOIN FTR B ON A.NOADMISION=B.NOREFERENCIA AND A.PROCEDENCIA=B.PROCEDENCIA
	  WHERE B.ESTADO='P' AND COALESCE(A.N_FACTURAK,'')=''

	  UPDATE FTRF SET N_FACTURAK='P'

	  SELECT * FROM FTRF WHERE COALESCE(N_FACTURAK,'')=''

	  SELECT A.NOADMISION AS NOREFERENCIA,SUM(A.VALOREXEDENTE) VR_TOTAL INTO #A
	  FROM HPRE A INNER JOIN HADM B ON A.NOADMISION=B.NOADMISION
	  WHERE B.IDTERCERO='892115003' AND B.FECHA>='20110101' AND B.FECHA<'20140101'
	  AND B.CLASEING='A' AND B.CERRADA=1 AND B.FACTURABLE=1
	  AND B.NOADMISION IN(SELECT NOREFERENCIA FROM FTR WHERE PROCEDENCIA='SALUD' AND ESTADO='P')
	  GROUP BY A.NOADMISION

	SELECT * FROM #HADM
	DROP TABLE #A

	SELECT * FROM FTRF WHERE COALESCE(NOADMISION,'')=''
	ORDER BY  VR_TOTAL ASC
	--80000
	--1199584.10

	SELECT PROCEDENCIA,ESTADO,* FROM FTR WHERE NOREFERENCIA='0100265296'

	DELETE #A WHERE NOREFERENCIA IN(SELECT NOREFERENCIA FROM FTR WHERE PROCEDENCIA='SALUD' AND ESTADO='P')

	SELECT * FROM FTRF WHERE ABS(DIFIERE)>10000

	 UPDATE FTRF SET NOADMISION=NULL,PROCEDENCIA=NULL WHERE ABS(DIFIERE)>10000

	 ALTER TABLE FTRF ADD VR_FTR DECIMAL(14,2)

	 UPDATE FTRF SET VR_FTR=B.VR_TOTAL
	 FROM FTRF A INNER JOIN FTR B ON A.N_FACTURAK=B.N_FACTURA

	 SELECT * FROM FTRF WHERE COALESCE(PROCEDENCIA,'')=''

SELECT A.N_FACTURA AS N_FACTURAR,B.* INTO #FTRD
FROM FTRF A INNER JOIN FTRD B ON A.N_FACTURAK=B.N_FACTURA


UPDATE #FTRD SET CNSFTR=B.CNSFCT
FROM #FTRD A INNER JOIN FTR B ON A.N_FACTURAR=B.N_fACTURA

UPDATE #FTRD SET N_FACTURA=N_FACTURAR

BEGIN TRAN
DELETE FTRD 
FROM FTRD A INNER JOIN FTRF B ON A.N_FACTURA=B.N_FACTURA AND CNSFTR NOT IN(SELECT CNSFTR FROM FTRDC)

COMMIT

ALTER TABLE #FTRD DROP COLUMN N_FACTURAR

INSERT INTO FTRD
SELECT  * FROM #FTRD WHERE N_FACTURA NOT IN(SELECT N_FACTURA FROM #RR)

SELECT * FROM FTRF WHERE N_FACTURA='HSJM01166434'


SELECT DISTINCT N_fACTURA FROM #RR

DELETE FTRD WHERE N_FACTURA='HSJM01166417'

SELECT * FROM #FTRD WHERE CNSFTR='0100514294'

SELECT CNSFTR,N_CUOTA  FROM #FTRD
GROUP BY CNSFTR,N_CUOTA
HAVING COUNT(*)>1

DELETE #FTRD WHERE CNSFTR='0100514294' AND N_CUOTA=1 AND VR_TOTAL=0

SELECT * INTO #S FROM FTR WHERE N_FACTURA IN(SELECT N_FACTURA FROM #RR)

UPDATE #S SET CNSFCT='I'+CNSFCT,N_FACTURA=

UPDATE FTR SET N_FACTURA=CHAR(10)+N_FACTURA WHERE N_FACTURA IN(SELECT N_FACTURA FROM #RR)


DROP TABLE #S

SELECT CHAR(43)

INSERT INTO FTR 
SELECT * FROM #S

PRINT 'JOSE'+CHAR(10)+'MANUEL'

SELECT * FROM FTR WHERE N_FACTURA IN(SELECT N_FACTURA FROM #S)

ALTER TABLE FTR DISABLE TRIGGER ALL

DELETE FTR WHERE N_FACTURA IN(SELECT N_FACTURA FROM #S)

ALTER TABLE FTR ENABLE TRIGGER ALL


UPDATE #S SET CNSFCT='I'+CNSFCT,PROCEDENCIA='XX'

INSERT INTO FTR 
SELECT * FROM #S WHERE N_FACTURA='HSJM01166421'
SELECT * FROM #FTRD WHERE N_FACTURA='HSJM01166421'

SELECT * INTO #Y  FROM #FTRD WHERE N_fACTURA IN(SELECT N_FACTURA FROM #RR) AND

UPDATE #Y SET CNSFTR='II'+CNSFTR


INSERT INTO FTRD 
SELECT * FROM  #Y

DROP TABLE #O

SELECT A.N_FACTURA, SUM(A.VLR_SERVICI)VLR_SERVICI,SUM(A.VLR_COPAGOS)VLR_COPAGOS INTO #O
FROM FTRD A INNER JOIN FTR B ON A.N_FACTURA=B.N_fACTURA AND A.CNSFTR=B.CNSFCT
 WHERE A.N_FACTURA IN(SELECT N_FACTURA FROM FTRF  ) --AND N_FACTURA='HSJM01166234'
GROUP BY A.N_FACTURA

--BEGIN TRAN 
UPDATE FTR SET VALORSERVICIOS=B.VLR_SERVICI,VALORCOPAGO=B.VLR_COPAGOS,VR_TOTAL=B.VLR_SERVICI-B.VLR_COPAGOS
FROM FTR A INNER JOIN #O B ON A.N_FACTURA=B.N_FACTURA

SELECT * FROM #O WHERE N_FACTURA='HSJM01166327'

SELECT N_FACTURA, SUM(VLR_SERVICI)VLR_SERVICI,SUM(VLR_COPAGOS)VLR_COPAGOS
FROM FTRD WHERE N_FACTURA ='HSJM01166327'
GROUP BY N_FACTURA
SELECT * FROM FTRF WHERE N_FACTURA='HSJM01166327'


UPDATE FTR SET NOREFERENCIA=B.NOADMISION,PROCEDENCIA=B.PROCEDENCIA,IDTERCERO='892115003',F_FACTURA=B.F_FACTURA,F_VENCE=B.F_FACTURA+30,ESTADO='P'
FROM FTR A INNER JOIN FTRF B ON A.N_FACTURA=B.N_FACTURA


SELECT * FROM FTRF

UPDATE FTRF SET VR_FTR=B.VR_TOTAL
FROM FTRF A INNER JOIN FTR B ON A.N_FACTURA=B.N_FACTURA

ALTER TABLE FTRF ADD DIFEK DECIMAL(14,2)

UPDATE FTRF SET DIFEK =VR_TOTAL-VR_FTR


--MAYOR QUE CERO
DECLARE @NCUOTA INT
DECLARE @DIFE DECIMAL(14,2)
DECLARE @N_FACTURA VARCHAR(20)
DECLARE PG_CURSOR CURSOR FOR 
 SELECT N_FACTURA,ABS(DIFEK)
FROM FTRF WHERE  COALESCE(N_FACTURAK,'')<>''
AND DIFEK<>0 
AND DIFEK<10000
GROUP BY  N_FACTURA,ABS(DIFEK)     
OPEN PG_CURSOR    
FETCH NEXT FROM PG_CURSOR    
INTO @N_FACTURA,@DIFE
WHILE @@FETCH_STATUS = 0    
BEGIN 
   print 'esta es la factura '+@n_factura
   print 'esta es el valor'+str(@dife)
   SELECT TOP 1 @NCUOTA= N_CUOTA FROM FTRD  WHERE N_FACTURA=@N_FACTURA AND VALOR>=@DIFE
   print 'esata es la cutoa'+str(@NCUOTA)
   UPDATE FTRD SET VR_TOTAL=VR_TOTAL+@DIFE,VALOR=VALOR+@DIFE ,VLR_SERVICI=VLR_SERVICI+@DIFE WHERE N_FACTURA=@N_FACTURA AND N_CUOTA=@NCUOTA
FETCH NEXT FROM PG_CURSOR    
INTO  @N_FACTURA,@DIFE
END
CLOSE PG_CURSOR
DEALLOCATE PG_CURSOR

--MENOR QUE CERO
DECLARE @NCUOTA INT
DECLARE @DIFE DECIMAL(14,2)
DECLARE @N_FACTURA VARCHAR(20)
DECLARE PG_CURSOR CURSOR FOR 
 SELECT N_FACTURA,ABS(DIFEK)
FROM FTRF WHERE  COALESCE(N_FACTURAK,'')<>''
AND DIFEK<0 
AND DIFEK>-10000
GROUP BY  N_FACTURA,ABS(DIFEK)     
OPEN PG_CURSOR    
FETCH NEXT FROM PG_CURSOR    
INTO @N_FACTURA,@DIFE
WHILE @@FETCH_STATUS = 0    
BEGIN 
   print 'esta es la factura '+@n_factura
   print 'esta es el valor'+str(@dife)
   SELECT TOP 1 @NCUOTA= N_CUOTA FROM FTRD  WHERE N_FACTURA=@N_FACTURA AND VALOR>=@DIFE
   print 'esata es la cutoa'+str(@NCUOTA)
   UPDATE FTRD SET VR_TOTAL=VR_TOTAL-@DIFE,VALOR=VALOR-@DIFE ,VLR_SERVICI=VLR_SERVICI-@DIFE WHERE N_FACTURA=@N_FACTURA AND N_CUOTA=@NCUOTA
FETCH NEXT FROM PG_CURSOR    
INTO  @N_FACTURA,@DIFE
END
CLOSE PG_CURSOR
DEALLOCATE PG_CURSOR


SELECT * FROM FTRF WHERE DIFEK<0

DECLARE @NCUOTA INT
DECLARE @DIFE DECIMAL(14,2)
DECLARE @N_FACTURA VARCHAR(20)
DECLARE @CUANTAS INT
DECLARE @VALOR DECIMAL(14,2)
DECLARE PG_CURSOR CURSOR FOR 
 SELECT N_FACTURA,ABS(DIFEK)
FROM FTRF WHERE DIFEK>10000 
GROUP BY  N_FACTURA,ABS(DIFEK)
OPEN PG_CURSOR    
FETCH NEXT FROM PG_CURSOR    
INTO @N_FACTURA,@DIFE
WHILE @@FETCH_STATUS = 0    
BEGIN 
   print 'esta es la factura '+@n_factura
   print 'esta es el valor'+str(@dife)
   --SELECT TOP 1 @NCUOTA= N_CUOTA FROM FTRD  WHERE N_FACTURA=@N_FACTURA AND VALOR>=@DIFE
   SELECT @CUANTAS=COUNT(*) FROM FTRD WHERE N_FACTURA=@N_FACTURA AND  VALOR>500
   SELECT @VALOR=@DIFE/@CUANTAS
   print 'esata es EL VALOR POR cuOoa'+str(@VALOR)
   UPDATE FTRD SET VR_TOTAL=VR_TOTAL+@VALOR,VALOR=VALOR+@VALOR ,VLR_SERVICI=VLR_SERVICI+@VALOR WHERE N_FACTURA=@N_FACTURA  AND  VALOR>500
FETCH NEXT FROM PG_CURSOR    
INTO  @N_FACTURA,@DIFE
END
CLOSE PG_CURSOR
DEALLOCATE PG_CURSOR


---
DECLARE @NCUOTA INT
DECLARE @DIFE DECIMAL(14,2)
DECLARE @N_FACTURA VARCHAR(20)
DECLARE @CUANTAS INT
DECLARE @VALOR DECIMAL(14,2)
DECLARE PG_CURSOR CURSOR FOR 
 SELECT N_FACTURA,ABS(DIFEK)
FROM FTRF WHERE DIFEK<-10000 
GROUP BY  N_FACTURA,ABS(DIFEK)
OPEN PG_CURSOR    
FETCH NEXT FROM PG_CURSOR    
INTO @N_FACTURA,@DIFE
WHILE @@FETCH_STATUS = 0    
BEGIN 
   print 'esta es la factura '+@n_factura
   print 'esta es el valor'+str(@dife)
   --SELECT TOP 1 @NCUOTA= N_CUOTA FROM FTRD  WHERE N_FACTURA=@N_FACTURA AND VALOR>=@DIFE
   SELECT @CUANTAS=COUNT(*) FROM FTRD WHERE N_FACTURA=@N_FACTURA AND  VALOR>9000
   SELECT @VALOR=@DIFE/@CUANTAS
   print 'esata es la cutoa'+str(@NCUOTA)
   UPDATE FTRD SET VR_TOTAL=VR_TOTAL-@VALOR,VALOR=VALOR-@VALOR ,VLR_SERVICI=VLR_SERVICI-@VALOR WHERE N_FACTURA=@N_FACTURA  AND  VALOR>9000
FETCH NEXT FROM PG_CURSOR    
INTO  @N_FACTURA,@DIFE
END
CLOSE PG_CURSOR
DEALLOCATE PG_CURSOR


SELECT A.N_FACTURA,A.NOADMISION,A.F_FACTURA,B.FECHA,B.IDAFILIADO,DATEDIFF(DAY,FECHA,FECHAALTAMED)DIAS INTO #A
FROM FTRF A INNER JOIN HADM B ON A.NOADMISION=B.NOADMISION
WHERE A.PROCEDENCIA='SALUD'

DROP TABLE #A

BEGIN TRAN
UPDATE HADM SET FECHA=B.F_FACTURA-DIAS,FECHAALTAMED=B.F_FACTURA
FROM HADM A INNER JOIN #A B ON A.NOADMISION=B.NOADMISION

SELECT DATEDIFF(DAY,FECHA,FECHAALTAMED) FROM HADM  WHERE NOADMISION IN(SELECT NOADMISION FROM #A)

UPDATE FTR SET IDAFILIADO=B.IDAFILIADO
FROM FTR A INNER JOIN #A B ON A.N_FACTURA=B.N_FACTURA

SELECT * FROM FTRF WHERE PROCEDENCIA='SALUD'

SELECT A.N_FACTURA,B.IDAFILIADO INTO #H
FROM FTRF A INNER JOIN FTR B ON A.N_FACTURAK=B.N_FACTURA


UPDATE FTR SET IDAFILIADO=B.IDAFILIADO
FROM FTR A INNER JOIN #H B ON A.N_FACTURA=B.N_FACTURA

COMMIT

SELECT A.* INTO #G
FROM HADMF A INNER JOIN FTRF B ON A.NOADMISION=B.NOADMISION AND A.N_FACTURA=B.N_FACTURAK


SELECT SUM(VR_TOTAL) FROM FTRF

SELECT * FROM #G


SELECT DBO.FNK_COLUMNAS_TABLAS('HADMF')

SELECT * FROM FTRF WHERE N_FACTURA='HSJM01166549'

SELECT NOADMISION , N_FACTURA , CNSFCT , ESTADO , N_FACTURAR , ANEXOUNICO ,
 IDTERCERO , IDPLAN , DESCRIPCION , ITFC , CNSITFC,ROW_NUMBER() OVER(PARTITION BY NOADMISION ORDER BY NOADMISION DESC)NRO INTO #U
 FROM #G


 DELETE #U WHERE NRO>1

 SELECT * FROM #U

 UPDATE #U SET N_FACTURA=B.N_FACTURA
 FROM #U A INNER JOIN FTRF B ON A.NOADMISION=B.NOADMISION
 AND B.PROCEDENCIA='SALUD'

 INSERT INTO HADMF( NOADMISION , N_FACTURA , CNSFCT , ESTADO ,
 IDTERCERO , IDPLAN , DESCRIPCION , ITFC , CNSITFC)
 SELECT  NOADMISION , N_FACTURA , CNSFCT , ESTADO , N_FACTURAR , ANEXOUNICO ,
 IDTERCERO , IDPLAN , DESCRIPCION , ITFC , CNSITFC FROM #U

 SELECT * FROM FTRF WHERE PROCEDENCIA='SALUD'

 SELECT * FROM #U WHERE N_fACTURA='HSJM00775905'


 INSERT INTO HADMF( NOADMISION , N_FACTURA , CNSFCT , ESTADO ,
 IDTERCERO , IDPLAN , DESCRIPCION )
 SELECT B.NOADMISION,A.N_FACTURA,A.CNSFCT,A.ESTADO,A.IDTERCERO,A.IDPLAN,'TODAS' DESCRIPCION
 FROM FTR A INNER JOIN FTRF B ON A.N_FACTURA=B.N_FACTURA
 WHERE A.N_FACTURA  IN (SELECT N_FACTURA FROM HADMF )
 AND A.PROCEDENCIA='SALUD'  AND B.PROCEDENCIA='SALUD'

 SELECT * FROM HADMF WHERE N_FACTURA='HSJM01166007'
  SELECT * FROM FTR WHERE N_FACTURA='HSJM01166007'

  UPDATE HADMF SET CNSFCT=A.CNSFCT
  FROM FTR A INNER JOIN HADMF B ON A.N_FACTURA=B.N_FACTURA
  WHERE A.N_FACTURA IN(SELECT N_FACTURA FROM FTRF)
  
  SELECT * FROM #A WHERE VR_TOTAL>=900000 AND VR_TOTAL<1100000 AND NOREFERENCIA NOT IN(SELECT NOADMISION FROM FTRF WHERE PROCEDENCIA='SALUD')
  
  
  ---
  UPDATE FTRD SET FECHA=B.FECHA,FECHAPREST=B.FECHA
FROM FTRD A INNER JOIN HPRE B ON A.NOPRESTACION=B.NOPRESTACION
			INNER JOIN FTRF C ON A.N_FACTURA=C.N_FACTURA
WHERE C.PROCEDENCIA='SALUD'