

--PRODUCTO, HADM --REFERIDO
--TIPOAFILIACION,AFI --IDTIPOAFILIACION
--NROAUTORIZACION
--TIPOCOBERTURA
--SUBTIPOCOBER
--DITRIBUCION-- 
--TIPOTRMA
   HONORARIOS COL 35
   EXAMENES COL 38
   FARMACIA   COL 40
   COPAGO     COL 46
   TOTAL SINING  48

   ------------------
   CODRUBRO

SELECT  * FROM HADM