CREATE VIEW DBO.VWJ_CARTERA_TOTAL
AS
   SELECT  V.IDTERCERO,TER.RAZONSOCIAL, FTR.IDPLAN, V.N_FACTURA, F.CNSCXC,DBO.FNK_FECHA(FTR.F_FACTURA)F_FACTURA,DBO.FNK_FECHA(COALESCE(D.F_RAD,NULL)) F_RAD, 
          COALESCE(FTR.VR_TOTAL,0) VR_TOTAL, COALESCE(V.NORADICADA,0) NORADICADA, COALESCE(V.PORVENCER, 0) PORVENCER, COALESCE(V.SALDO,0) SALDO, 
          COALESCE(V.D0_30,0) D0_30, COALESCE(V.D31_60,0) D31_60, COALESCE(V.D61_90,0) D61_90, COALESCE(V.D91_120,0) D91_120, 
          COALESCE(V.D121_150,0) D121_150, COALESCE(V.D151_180,0) D151_180, 
          COALESCE(V.D181_360,0) D181_360, COALESCE(V.D361_MAS,0) D361_MAS, COALESCE(F.VLRNOTADB,0) NOT_DB, COALESCE(F.VLRNOTACR,0) NOT_CR, 
          COALESCE(F.DEDUCCIONES,0) DEDUCCIONES, COALESCE(F.VLRPAGOS,0) VLRPAGOS, COALESCE(F.VLRGLOSAS,0) VLRGLOSAS, 
          COALESCE(F.VLRGLOSAS_R,0) VLRGLOSAS_R, COALESCE(F.VLRLEVANTADO,0) VLRLEVANTADO ,
          COALESCE(D.G,0) G, COALESCE(D.R,0) R, COALESCE(D.C,0) C, FTR.TIPOTTEC
   FROM   (
            SELECT V.IDTERCERO, V.N_FACTURA,  SUM(V.NORADICADA) NORADICADA, SUM(V.PORVENCER) PORVENCER, SUM(V.SALDONETO) SALDO, SUM(V.D0_30) D0_30, 
                   SUM(V.D31_60) D31_60, SUM(V.D61_90) D61_90, SUM(V.D91_120) D91_120, SUM(V.D121_150) D121_150, SUM(V.D151_180) D151_180, 
                   SUM(V.D181_360) D181_360, SUM(V.D361_MAS) D361_MAS
            FROM   DBO.VWK_CXCDIASVTO V         
            GROUP BY V.IDTERCERO, V.N_FACTURA
          ) V LEFT JOIN DBO.FCXCD F ON V.N_FACTURA = F.N_FACTURA
             LEFT JOIN DBO.FTR     ON V.N_FACTURA = FTR.N_FACTURA
             LEFT JOIN DBO.FNK_DATFACTURAS() D ON V.N_FACTURA = D.N_FACTURA
             LEFT JOIN DBO.TER TER ON V.IDTERCERO=TER.IDTERCERO
   WHERE  V.IDTERCERO  = CASE WHEN COALESCE('','') = '' THEN V.IDTERCERO                              
                              ELSE '' 
                          END
   AND    FTR.TIPOTTEC = CASE WHEN COALESCE('','') = '' THEN FTR.TIPOTTEC 
                              WHEN COALESCE('','') = 'Todos' THEN FTR.TIPOTTEC 
                              ELSE '' 
                         END
