/***************************************************************************************/
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'VWK_RPT_NOMINA_SALUS' AND TYPE='V')
BEGIN
 DROP VIEW VWK_RPT_NOMINA_SALUS
END
GO
/***************************************************************************************/
CREATE VIEW DBO.VWK_RPT_NOMINA_SALUS
AS
SELECT NIEPE.CNSPAGO, NIEPE.NUMDOC,NIEPE.NOMBRE_EMPLEADO,NIEPE.BASICO,NIEPED.CODCONCEPTO,NIEPED.NOMBRE_CONCEPTO,
CASE WHEN NIEPED.TIPO='Ingreso' THEN CONVERT(DECIMAL(14,2),NIEPED.VALOR) ELSE 0 END INGRESO ,
CASE WHEN NIEPED.TIPO='Egreso' THEN CONVERT(DECIMAL(14,2),NIEPED.VALOR) ELSE 0 END EGRESOS ,
NPRF.CLASE,CONVERT(DECIMAL(14,2),NEMPFD.BASE_CALCULO)BASE,NIEPED.TIPO,CONVERT(decimal(14,2),NIEPED.VALOR_APORTES)VLR_APORTES
FROM NIEPE INNER JOIN NIEPED ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC
           INNER JOIN NPRF   ON NIEPED.CODPRF=NPRF.CODPRF
           INNER JOIN NEMPFD ON NIEPE.CNSPAGO=NEMPFD.CNSPAGO AND NIEPED.NUMDOC=NEMPFD.NUMDOC AND NIEPED.CODCONCEPTO=NEMPFD.CODCONCEPTO
