
DELETE ANT WHERE CNSANT='0600000034'


COALESCE((SELECT SUM(VLR_ABONOS) FROM FCXP WHERE FCXP.CNSFCOM=FCOM.CNSFCOM AND ESTADO<>'A' AND FCXP.PROCEDENCIA='Anticipos'),0)

SELECT * FROM FCXP WHERE FCXP.CNSFCOM='0300000033' AND ESTADO<>'A' AND FCXP.PROCEDENCIA='Anticipos'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FCXP","METODO":"ANULAR_ANTICIPO","PARAMETROS":{"CNSANT":"0600000035"},"USUARIO":"JJIMENEZ"}'

EXEC SPQ_JSON '{"MODELO":"FCXP","METODO":"TRAER_VALORES_ANTI","PARAMETROS":{"CNSFCXP":"03SR001385","CNSFCOM":"0300000033","PROCESO":"Nuevo"},"USUARIO":"JJIMENEZ"}'


SELECT   FCOM.CNSFCOM, FCOM.FECHA, FCOM.IDTERCERO, TER.RAZONSOCIAL, FCOM.N_FACTURA, FCOM.VR_TOTAL,                         COALESCE((SELECT SUM(VLR_ABONOS) FROM FCXP WHERE FCXP.CNSFCOM=FCOM.CNSFCOM AND ESTADO<>'A' AND FCXP.PROCEDENCIA='Anticipos'),0)VLR_ANTICIPOS,                         COALESCE((SELECT SUM(VALOR_LEG) FROM ANT WHERE ANT.CNSFCOM=FCOM.CNSFCOM AND ANT.ESTADO='L'),0)VLR_LEGALIZA,                         F_FACTURA, FCOM.F_VENCE, FCOM.OBSERVACION, FCOM.IDTIPOSER, FCOM.TIPOANTICIPO , FCOM.ESTADO    FROM [dbo].[FCOM] LEFT JOIN  TER ON FCOM.IDTERCERO = TER.IDTERCERO WHERE (FCOM.CNSFCOM  LIKE '%%%%') AND  AND FCOM.IDTERCERO = '0100000013' AND FCOM.ESTADO = 'I'  ORDER BY FCOM.CNSFCOM ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 