
SELECT TIPO_OPERACION,TIPO_DOCUMENTO, * FROM FTR WHERE N_FACTURA='UV10747'
UNION ALL
SELECT  * FROM FTR WHERE N_FACTURA='UV7039'

SELECT DISTINCT TIPO_OPERACION FROM FTR WHERE TIPO_OPERACION ISNULL AND F_FACTURA>='01/01/2024'

UPDATE FTR SET TIPO_OPERACION = '10',TIPO_DOCUMENTO = '10' WHERE COALESCE(TIPO_OPERACION,'')='' AND F_FACTURA>='01/01/2024'

SELECT  * FROM TGEN WHERE CAMPO='TIPO_OPERACION'


UPDATE FTR SET TIPO_OPERACION = '10',TIPO_DOCUMENTO = '10'  WHERE COALESCE(TIPO_OPERACION,'')='' AND FACTE<>2


SELECT  * FROM FNOT WHERE CNSFNOT='02C00000667'

DROP TABLE #A
DROP TABLE #B
SELECT  * INTO #B FROM TARDV WHERE IDTARIFA='030'AND FECHAFIN>='01/01/2025'

UPDATE #B SET IDTARIFA='031' 

INSERT INTO TARDV
SELECT  * FROM #B

SELECT  * FROM TARD WHERE IDTARIFA='001'


SELECT IDFORMATO,OBSERVACION, * FROM FTR WHERE N_FACTURA='UV5252'

UPDATE  FTR SET IDFORMATO='03G1' WHERE N_FACTURA='UV15252'