USE CEM
SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

SELECT IDTERCERO,NIT,RAZONSOCIAL,DIRECCION,COALESCE(STUFF((SELECT DISTINCT ', '+IDCATEGORIA FROM DBO.TEXCA WHERE IDTERCERO=TER.IDTERCERO FOR XML PATH('')),1,1,''), '') CATEGORIAS  FROM [dbo].[TER] WHERE (RAZONSOCIAL LIKE '%%%%' OR NIT LIKE '%%%%' OR IDTERCERO LIKE '%%%%') AND TER.IDTERCERO IN (SELECT IDTERCERO FROM TEXCA WHERE IDCATEGORIA IN ('EMP'))  ORDER BY [dbo].[TER].[IDTERCERO] OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 