USE kmasmente

SELECT  * FROM FCJ WHERE FECHA>='01/04/2025' AND CERRADA=1 AND IDPLAN NOT IN (SELECT DATO FROM USVGS WHERE IDVARIABLE LIKE 'IDPLANPART%')


SELECT IDSEDE,IDPLAN, * FROM CIT WHERE CONSECUTIVO='010168212913'

SELECT * FROM USVGS WHERE DATO='EVOLUN'

SELECT * FROM FCJPCXC WHERE CODCAJA='005' AND CNSFACJ='00000215'

SELECT SYS_ComputerName,IDPLAN,  * FROM FCJ WHERE CODCAJA='005' AND CNSFACJ='00000215'

SELECT IDSEDE, * FROM UBEQ WHERE SYS_ComputerName='CAJAAUX5'

SELECT * FROM CAJ WHERE CODCAJA='005'

SELECT * FROM FCJ WHERE FECHA>'01/04/2025' 
AND IDPLAN NOT IN(SELECT DATO FROM USVGS WHERE IDVARIABLE LIKE'IDPLANPART%') 
AND PROCEDENCIA<>'CAJA' AND COALESCE(N_FACTURAPOS,'')=''
AND CERRADA=1
AND ESTADO='P'

SELECT  * FROM CIU WHERE NOMBRE LIKE '%DIFICIL%'