

SELECT  * FROM IZSOLD WHERE IDSERVICIO='MDP0701'

UPDATE IZSOLD SET IDARTICULO='MI070' WHERE IDSERVICIO='MDP0701' 

SELECT PRINCIPAL, * FROM IART WHERE IDARTICULO='MI070'

SELECT * INTO #A FROM IART WHERE IDARTICULO='MI070'

UPDATE  IART SET PRINCIPAL=0 WHERE IDARTICULO='MI070'
UPDATE #A SET IDARTICULO=IDSERVICIO

INSERT INTO IART 
SELECT * FROM #A

SELECT TOP 10 * FROM FNOT

SELECT  FNOT.CNSFNOT,FNOT.CLASE,DBO.FNK_FECHA_GRINGA(FNOT.F_NOTA)F_NOTA,
TER.NIT,TER.RAZONSOCIAL,FNOT.VR_TOTAL,FNOT.PROCEDENCIA,FNOT.IDCONCEPTO,
CPNT.DESCRIPCION,FNOT.OBSERVACION,FNOT.ESTADO,FNOT.CONTABILIZADA,FNOT.NROCOMPROBANTE,
FNOT.FACTE
FROM FNOT INNER JOIN TER ON FNOT.IDTERCERO=TER.IDTERCERO
          LEFT  JOIN CPNT ON FNOT.IDCONCEPTO=CPNT.CODIGO