SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

SELECT ROW_NUMBER()OVER(ORDER  BY CNSFPAG, N_FACTURA, ITEM  ASC)ID,FPAGD.CNSCXC,FPAGD.N_FACTURA,FPAGD.VLRFACTURA,FPAGD.VLRGLOSA,FPAGD.GLOSAAFECTAIMP,                              FPAGD.VLRCOPAGO,FPAGD.BASE,FPAGD.VLRIMPUESTO,  FPAGD.VLRPAGOSIN,FPAGD.VLRDTOFIN,FPAGD.SINPAGO,FPAGD.VLROTROSDCTOS,FPAGD.VLREXTRA,FPAGD.VALORPAGO,                              FPAGD.LEVANTADO,FPAGD.ESTADO   FROM [dbo].[FPAGD] WHERE (FPAGD.N_FACTURA LIKE '%%%%') AND  CNSFPAG='0200000138'   ORDER BY 1 ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 

SELECT ROW_NUMBER()OVER(ORDER  BY CNSFPAG, N_FACTURA, ITEM  ASC)ID,FPAGD.CNSCXC,FPAGD.N_FACTURA,FPAGD.VLRFACTURA, 
            FPAGD.VLRGLOSA,FPAGD.GLOSAAFECTAIMP,FPAGD.VLRCOPAGO,FPAGD.BASE,FPAGD.VLRIMPUESTO, 
            FPAGD.VLRPAGOSIN,FPAGD.VLRDTOFIN,FPAGD.SINPAGO,FPAGD.VLROTROSDCTOS,FPAGD.VLREXTRA, 
            FPAGD.VALORPAGO,FPAGD.LEVANTADO,FPAGD.ESTADO
FROM FPAGD 
WHERE CNSFPAG='0200000138'
<i class="fa-solid fa-file-invoice-dollar"></i>
<i class="fa-solid fa-delete-left"></i>
<i class="fa-solid fa-money-bill-transfer"></i>
<i class="fa-solid fa-magnifying-glass-dollar"></i>
<i class="fa-solid fa-dollar-sign"></i>
<i class="fa-solid fa-sack-xmark"></i>
<i class="fa-solid fa-eraser"></i>
<i class="fa-solid fa-print"></i>

SELECT * FROM FPAG

{ "CNSFPAG": "0200000138", "IDSEDE": "02", "INGRESO": "BANCOS", "F_PAGO": "2023-12-04", "F_LEGALIZA": "2023-12-04", "IDTERCERO": "800130907", "NIT": "800130907", "RAZONSOCIAL": "SALUD TOTAL EPS", "VALORPAGO": 1200000, "VLRTOTAL": 4651375, "VLRITEMS": 4651375, "VLRIMPUESTOS": 4900, "VLRAJUSTEPESO": -3451375, "VLRDTOFINAN": 0, "VLRGLOSAS": 0, "CONTABILIZADA": 0, "NROCOMPROBANTE": "", "ESTADO": "Activo", "DATOS": [] } 


SELECT ROW_NUMBER()OVER(ORDER  BY CNSCXC, N_FACTURA,TIPO  ASC)ID,IDSEDE,CNSCXC,N_FACTURA,CNSGLO,TIPO,SALDONETO,INDRECIBIDO  FROM VWK_CXC1

SELECT ROW_NUMBER()OVER(ORDER  BY CNSCXC, N_FACTURA,TIPO  ASC)ID,IDSEDE,CNSCXC,N_FACTURA,CNSGLO,TIPO,SALDONETO,                             CASE COALESCE(INDRECIBIDO,0) WHEN 1 THEN 'Si' ELSE 'No' END INDRECIBIDO  FROM [dbo].[VWK_CXC1] WHERE (TIPO LIKE '%%%%' OR N_FACTURA LIKE '%%%%' OR IDSEDE LIKE '%%%%' OR  CNSCXC LIKE '%%%%') AND  (IDTERCERO='800130907' OR (IDTERCERO IN (SELECT IDTERCEROFU FROM TERFU WHERE IDTERCERO = '800130907'))) AND SALDONETO > 0 AND MARCAPAGO = 0  AND  

select * FROM FTIMP

TRUNCATE TABLE RPDX
SELECT CNS,
RPDX.CNS1 N_FACTURA,RPDX.VALOR1 VLRFACTURA,RPDX.VALOR2 VLRGLOSA,RPDX.CANTIDAD AF,RPDX.VALOR7 VLRCOPAGO,RPDX.VALOR9 PAGOEXTRA,
RPDX.VALOR11 VLRIMP,RPDX.VALOR12 VLRDTO,RPDX.CANTIDAD1 SINPAGO,RPDX.GRUPOETAREO TIPO,RPDX.CNS5 CNSGLO,RPDX.CANTIDAD2 IVA,
RPDX.CANTIDAD3 LEVANTADO,RPDX.VALOR10 VLSERVICIOS,RPDX.VALOR30 SALDOORIGEN
FROM RPDX WHERE CNS='0200349294'

SELECT  * FROM RPDX

SELECT  * FROM FPAG