
SELECT * FROM FCXCD WHERE N_FACTURA='CEFE15726'
DELETE  FCXCD WHERE N_FACTURA='CEFE15726'

SELECT * FROM FPAGD WHERE N_FACTURA='CEFE15726'

SELECT  * FROM USVGS WHERE DESCRIPCION LIKE '%FACTURACION%'

UPDATE FTR SET INDCARTERA=0,INDCXC=0,INDASIGENT=0,INDASIGCXC=0,IDDEP='03' WHERE N_FACTURA='CEFE15726'