SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

SELECT IDTERCERO,IDPLAN, N_FACTURA,FACTURADA,GENFACTURA,ESTADO,CCOSTO,IDAREA, * FROM IMOV WHERE CNSMOV='0600000084'

SELECT * FROM IMOV WHERE CNSMOV='0600000084' AND ESTADO=1 AND COALESCE(GENFACTURA,0)=1 AND COALESCE(FACTURADA,0)=0

UPDATE IMOV SET IDPLAN='SUR02C'  WHERE CNSMOV='0600000084'

SELECT IDAREA,CCOSTO,GENFACTURA,FACTURADA,IDTERCERO,IDPLAN,USUARIOCONF,* FROM IMOV WHERE CNSMOV='2600000003'

UPDATE IMOV SET GENFACTURA=1,IDTERCERO='0600012826',IDPLAN='HGM25' WHERE CNSMOV='2600000003'

SELECT  * FROM TER WHERE NIT='890904646'
ERROR: El artículo MX1549-1 - AVIBACTAM 0.5G + CEFTAZIDIMA 2G POLVO LIOFILIZADO EN VIAL (ZAVICEFTA) (PFIZER) (REG) (AC) (INS) no tiene precio.
ROLLBACK

BEGIN TRAN
EXEC SPQ_JSON '{"MODELO":"IMOV","METODO":"FACTURAR_IMOV","PARAMETROS":{"CNSMOV":"2600000003"},"USUARIO":"1035875486"}'
ROLLBACK
SELECT * FROM SER WHERE IDSERVICIO='MX606'

SELECT * FROM FTRD WHERE N_FACTURA='FVCD2'

UPDATE FTRD SET N_FACTURA='FVCD2'  WHERE N_FACTURA='FVCD3'

UPDATE IMOV SET NODOCUMENTO='FVCD2' WHERE CNSMOV='2600000003'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"FVCD3"},"USUARIO":"JJIMENEZ"}'

    INSERT INTO FTRD( CNSFTR, N_CUOTA, 
                      FECHA, DB_CR, AREAPRESTACION, UBICACION, 
                      VR_TOTAL,
                      IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                      VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                      NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, PIVA, VIVA, 
                      IDIMPUESTO, IDCLASE, CUENTA_FIMPDV,IDARTICULO, FECHAPREST, NOLOTE,CODPRG,CODUNG) 

    SELECT '2600000004', ROW_NUMBER() OVER ( ORDER BY A.CNSMOV) , 
           A.FECHAMOV, 'DB', A.IDAREA, NULL, 
           DBO.FNK_VALORSERVICIO('0600012826', 'HGM25', E.IDARTICULO, '', A.FECHAMOV,E.PCOSTO) * E.CANTIDAD, 
           NULL, A.CCOSTO, PREFIJO=D.PREFIJO, 
		   CASE WHEN dbo.FNK_VALORVARIABLE('CLASE_IPS') = 'OPTICA' THEN  CASE WHEN COALESCE(F.GARANTIA, 0) = 0 THEN COALESCE(C.DESCRIPCION, '')+' '+'Producto sin Garantia'
																											   ELSE COALESCE(C.DESCRIPCION, '')+' '+COALESCE(F.COMENTARIOS, '')
																											   END
																			  ELSE C.DESCRIPCION
																			  END,
		   E.IDARTICULO, IDCIRUGIA=NULL, E.CANTIDAD, 
           DBO.FNK_VALORSERVICIO('0600012826', 'HGM25', E.IDARTICULO, '', A.FECHAMOV,E.PCOSTO), 
           DBO.FNK_VALORSERVICIO('0600012826', 'HGM25', E.IDARTICULO, '', A.FECHAMOV,E.PCOSTO) * E.CANTIDAD, 
           VALORCOPAGO = 0, VALORPCOMP = 0, IDPROVEEDOR = NULL, NOADMISION=A.CNSMOV, NOPRESTACION = A.CNSMOV, NOITEM=NULL,
           --AREAFUNCONT = A.IDAREA, @FACT, SUBCCOSTO = NULL, C.PCOSTO, 0,0, NULL, NULL, NULL,E.IDARTICULO, A.FECHAMOV, E.NOLOTE --EZERPA 14/06/2018 Para tomar el costo del lote (IEXI) en lugar del promedio (IART), Pendiente discutir para otros proyectos
           AREAFUNCONT = A.IDAREA, 'FVCD3', SUBCCOSTO = NULL, E.PCOSTO, 0,0, NULL, NULL, NULL,E.IDARTICULO, A.FECHAMOV, E.NOLOTE,'',''
    FROM   IMOV A INNER JOIN ISAL  E ON A.CNSMOV     = E.CNSMOV 
	              LEFT JOIN IART  C ON E.IDARTICULO = C.IDARTICULO 
                  LEFT JOIN ITAR  D ON C.IDITAR     = D.IDITAR
				  LEFT JOIN SER   F ON C.IDSERVICIO = F.IDSERVICIO
    WHERE  A.CNSMOV = '2600000003'