SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

SELECT  * FROM RETTER


SELECT RETEL.CNSLIQRET,DBO.FNK_FECHA_GRINGA(RETEL.FECHA)FECHA,RETEL.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,RETEL.NOREFERENCIA,RETEL.PROCEDENCIA,RETEL.DEVENGOS,RETEL.DEDUCCION,RETEL.RENTAEXEP,RETEL.BASERET,RETEL.VLRUVT,RETEL.UVTLIQ,RETEL.VLR_REFTE,DATOS = (         SELECT RETELD.CODIGO,RETELD.OBSERVACION,RETELD.CLASE,RETELD.VLR_ITEM          FROM RETELD WHERE RETELD.CNSLIQRET=RETEL.CNSLIQRET             FOR JSON PATH )  FROM [dbo].[RETEL] INNER JOIN TER ON RETEL.IDTERCERO=TER.IDTERCERO  WHERE (TER.RAZONSOCIAL LIKE '%%%%' OR TER.NIT LIKE '%%%%') AND  RETEL.NOREFERENCIA='02202404P30-1' AND  RETEL.IDTERCERO='0100000722'   ORDER BY RETEL.CNSLIQRET ASC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 