USE KSANIPERU

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC
<i class="fa-regular fa-circle-xmark"></i>

SELECT  ENT.CNSENTREGA,ENT.PROCESO,ENT.ENT_ENTREGA+' '+FDEP.NOMBRE DEPENDENCIA,ENT.USUARIOENTREGA+' '+USUSU.NOMBRE AS USENTREGA,CONVERT(VARCHAR,ENT.FECHAENTREGA,103) F_ENTREGA,                               ENT.ENT_RECIBE+' '+FDEP1.NOMBRE  AS USRECIBE,ENT.IDSEDE, COALESCE(ENT.MSEDE,0) REQSEDE, ENT.ENT_RECIBE,CASE COALESCE(ENT.ESTADO,0) WHEN 1 THEN 'Recibido' ELSE 'Pendiente' END ESTADO,                               CASE COALESCE(ENT.CERRADO,0) WHEN 1 THEN 'Cerrado' ELSE 'Abierto' END CERRADO,ENT.USUARIOENTREGA AS USUARIO    FROM [dbo].[ENT] INNER JOIN  FDEP ON ENT.ENT_ENTREGA=FDEP.IDDEP  LEFT JOIN  FDEP FDEP1 ON ENT.ENT_RECIBE=FDEP1.IDDEP  LEFT  JOIN USUSU ON ENT.USUARIOENTREGA=USUSU.USUARIO  WHERE ( CNSENTREGA LIKE '%%%%') AND  PROCESO='FACTURAS'  AND CONVERT(DATE,FECHAENTREGA)>='2024-10-02'  AND CONVERT(DATE,FECHAENTREGA)<='2024-10-01'  AND ENT.USUARIOENTREGA='JJIMENEZ'  ORDER BY  FECHAENTREGA DESC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


EXEC SPQ_JSON '{"MODELO":"ENT_COL","METODO":"CREARCXC_ENT","PARAMETROS":{"CNSENTREGA":"0100000003"},"USUARIO":"JJIMENEZ"}'

SELECT  * FROM ENT WHERE CNSENTREGA='0100000003'

SELECT  * FROM FCXCD WHERE N_FACTURA='F002-00000021'