CREATE OR ALTER PROCEDURE DBO.SPK_VALIDAR_IZIPAY_JOB
@IDKAPAGE INT = NULL,
@CODCAJA VARCHAR(4)= NULL,
@USUCAJA VARCHAR(20)=NULL
WITH ENCRYPTION
AS 
DECLARE  @IDKPAGE INT			,@paymentOrderId VARCHAR(20),@NOADMISION VARCHAR(20)
		,@DPR VARCHAR(20)		,@SEDE VARCHAR(6)			,@SEDEV VARCHAR(6) --SEDE FACTURA LINK
		,@USUARIO VARCHAR(20)	,@IDTERCERO VARCHAR(20)		
		,@TIPOFAC VARCHAR(10)	,@FECHAFACT  DATETIME
		,@COMPANIA VARCHAR(2)	,@PROCEDENCIA VARCHAR(20)
		,@TABLA VARCHAR(20)		,@VALOR  DECIMAL(14,2)		,@FACTURA     VARCHAR(20)
		,@ESTADO VARCHAR(20)	,@SQL VARCHAR(MAX)			,@CNSFACJ     VARCHAR(20)
		,@CNSACJ VARCHAR(20)	,@CNSPCJ VARCHAR(20)		,@BCO         VARCHAR(3)
		,@CTA    VARCHAR(40)	,@SUC VARCHAR(2)			,@DATOBCO     VARCHAR(100)
		,@DOCIDAFILIADO	VARCHAR(20)							,@NOMBREAFI VARCHAR(200)
		,@NOMBRE_SEDE VARCHAR(20)							,@SMS VARCHAR(MAX)
		,@MENSAJE VARCHAR(MAX)								,@RAZONSOCIAL	VARCHAR(200)	,@NOMBRE_SER VARCHAR(max)
		,@LINK VARCHAR(1000)	,@IDAFILIADO VARCHAR(20)	,@NUMERO VARCHAR(20)	,@NOMBRE_MED			VARCHAR(MAX)
		,@NOMBREMEDI VARCHAR(50),@MODALIDADCIT	VARCHAR(10)	,@FECHA	DATETIME, @FECHA1 	DATETIME	
		,@CODCAJERO VARCHAR(20)	,@SYS_COMPUTERNAME VARCHAR(255), @FECHA_STRING	VARCHAR(MAX)	,@DESCSERVICIO VARCHAR(200)
BEGIN
	SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@SEDEV=DBO.FNK_VALORVARIABLE('IDSEDE_FACTURA_LINK')
	SELECT @TIPOFAC='Boleta',@FECHAFACT=DBO.FNK_GETDATE()

	PRINT @IDKAPAGE

	IF @IDKAPAGE IS NOT NULL 
	BEGIN
		PRINT ''
		UPDATE FNPAG SET ESTADO=1 WHERE IDKPAGE=@IDKAPAGE
	END

	DECLARE PG_CURSOR CURSOR FOR 
		SELECT IDKPAGE,CONSECUTIVO,USUCOBRA,RESPONSABLEPAGO,PROCEDENCIA,TABLA,paymentOrderId,VALOR,ESTADO 
		FROM  KPAGE 
		WHERE IDKPAGE=COALESCE(@IDKAPAGE, IDKPAGE) 
		AND ESTADO IN('SEND','RUNNING','PAID','ERROR')
		AND 1=CASE WHEN ESTADO IN('SEND','RUNNING') THEN 1 ELSE CASE WHEN COALESCE(REF_PAGO,'')='' THEN 1 ELSE 0 END END
		ORDER BY IDKPAGE
	OPEN PG_CURSOR    
	FETCH NEXT FROM PG_CURSOR    
	INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
		PRINT 'Valido el kpage'
		IF @ESTADO<>'PAID'
		BEGIN
			BEGIN TRY           
			EXEC DBO.SPK_GENERA_ORDENPAGO_IZIPAY @NOADMISION,@TABLA,@PROCEDENCIA,@IDTERCERO,@VALOR,'',@USUARIO,@IDKPAGE,'VALIDAR'                 
			END TRY
			BEGIN CATCH
				FETCH NEXT FROM PG_CURSOR    
				INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO
				CONTINUE
			END CATCH
		END
		PRINT 'Valido el kpage'
		IF EXISTS(SELECT * FROM KPAGE WHERE IDKPAGE=@IDKPAGE AND ESTADO='PAID' AND COALESCE(REF_PAGO,'')='')
		BEGIN 
			PRINT 'Voy a Generar la Boleta'
			IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@SEDEV)
			BEGIN
				IF @TABLA='CIT'
				BEGIN
					SELECT @SEDE=IDSEDE,@SEDEV=IDSEDE,@IDTERCERO=IDAFILIADO FROM CIT WHERE CONSECUTIVO=@NOADMISION
				END
				IF @TABLA='AUT'
				BEGIN
					SELECT @SEDE=IDSEDE,@SEDEV=IDSEDE,@IDTERCERO=IDAFILIADO FROM AUT WHERE IDAUT=@NOADMISION
				END
			END
			ELSE
			BEGIN
				IF @TABLA='CIT'
				BEGIN
					SELECT @SEDE=IDSEDE,@IDTERCERO=IDAFILIADO  FROM CIT WHERE CONSECUTIVO=@NOADMISION
				END
				IF @TABLA='AUT'
				BEGIN
					SELECT @SEDE=IDSEDE,@SEDEV=IDSEDE,@IDTERCERO=IDAFILIADO FROM AUT WHERE IDAUT=@NOADMISION
				END
			END
			IF COALESCE(@CODCAJA,'')=''
			BEGIN
				SELECT @CODCAJA = DBO.FNK_VALORVARIABLE('CAJA_IZIPAY')
			END
			IF COALESCE(@USUCAJA,'')=''
			BEGIN
				SELECT @USUCAJA = DBO.FNK_VALORVARIABLE('USUARIO_IZIPAY')
			END
			IF @TABLA='CIT'
			BEGIN
				PRINT 'ENTRA SPK_FACTURACE_PERU_COPA ===================================>'
				EXEC SPK_FACTURACE_PERU_COPA @NOADMISION,@DPR,@COMPANIA,@SEDEV, @USUARIO,'','','','','','CI','', 'FALSE', NULL,@FECHAFACT,@TIPOFAC, @IDTERCERO   
				SELECT @FACTURA=NULL
				PRINT 'SALEEEEEEE SPK_FACTURACE_PERU_COPA ===================================>'

				SELECT @FACTURA=COALESCE(NFACTURA,N_FACTURA) FROM CIT WHERE CONSECUTIVO=@NOADMISION

				UPDATE FTR SET IDSEDE=@SEDE WHERE N_FACTURA=@FACTURA
				UPDATE KPAGE SET FACTURADO='Si',REF_PAGO=@FACTURA WHERE IDKPAGE=@IDKPAGE
			
				
		
				PRINT 'Voy a recaudar'
				IF COALESCE(@CODCAJA,'')<>'' AND EXISTS(SELECT * FROM CAJ WHERE CODCAJA=@CODCAJA)
				BEGIN
					SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"INFO_CITA_RECAUDAR","PARAMETROS":{"CONSECUTIVO":"'+@NOADMISION+'","CODCAJA":"'+@CODCAJA+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'
					EXEC SPQ_JSON @SQL

					--
					PRINT 'Verifico la creación del recibo'
					IF EXISTS(SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='CITAS')
					BEGIN
						SELECT @CNSFACJ=CNSFACJ,@CNSACJ=CNSACJ FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='CITAS'

						UPDATE FCJ SET RECAUDO=1,ENPAGOS=0,N_FACTURA=@FACTURA,IDKPAGE=@IDKPAGE WHERE CNSFACJ=@CNSFACJ AND CNSACJ=@CNSACJ AND CODCAJA=@CODCAJA

						EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@PCJ', @LONGITUD = 8, @LLAMADO = NULL, @NVOCONSEC = @CNSPCJ OUTPUT

						SELECT @CNSPCJ=@SEDE + REPLACE(SPACE(8 - LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)

						SELECT @DATOBCO=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('BCO_CTA_SUC_IZIPAY')))

						SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=1
						SELECT @CTA=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=2
						SELECT @SUC=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=3

						INSERT INTO PCJ(CODCAJA,CNSPCJ,CNSFACJ,TIPOPAGO,VALOR,FECHA,CNSACJ,BANCO,CTA_BCO,SUCURSAL)
						SELECT @CODCAJA,@CNSPCJ,@CNSFACJ,DBO.FNK_VALORVARIABLE('IDCJFPAIZIPAY'),@VALOR,DBO.FNK_GETDATE(),@CNSACJ,@BCO,@CTA,@SUC

						SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"CONFIRMAR_RECIBO","PARAMETROS":{"CNSFACJ":"'+@CNSFACJ+'","CODCAJA":"'+@CODCAJA+'","CNSACJ":"'+@CNSACJ+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'

						EXEC SPQ_JSON @SQL
					END
				END
					IF EXISTS (SELECT * FROM CIT WHERE CONSECUTIVO = @NOADMISION AND COALESCE(NFACTURA,'') <> '' AND COALESCE(CIT.MODALIDAD,'') = 'Virtual') 
					BEGIN
						/*ENVIA LINK DE VIDEO LLAMADA  */
						EXEC SPK_ASIGNA_CITA_LINK @NOADMISION, @USUARIO, 'SI'
					END
			END
			IF @TABLA='AUT'
			BEGIN
				EXEC SPK_FACTURACE_PERU_COPA @NOADMISION,@DPR,@COMPANIA,@SEDEV, @USUARIO,'','','','','','CE','', 'FALSE', NULL,@FECHAFACT,@TIPOFAC, @IDTERCERO   
				SELECT @FACTURA=NULL

				SELECT @FACTURA=COALESCE(NFACTURA,N_FACTURA) FROM AUTD WHERE IDAUT=@NOADMISION AND COALESCE(NOCOBRABLE,0)=0

				UPDATE FTR SET IDSEDE=@SEDE WHERE N_FACTURA=@FACTURA
				UPDATE KPAGE SET FACTURADO='Si',REF_PAGO=@FACTURA WHERE IDKPAGE=@IDKPAGE


				SELECT @CNSACJ =  CAJ.CNSACJ FROM CAJ WHERE CODCAJA=@CODCAJA  
				SELECT  @COMPANIA=COALESCE(USUSU.COMPANIA,'01'),@SYS_COMPUTERNAME=USUSU.SYS_ComputerName,@CODCAJERO=CODCAJERO
				FROM  USUSU 
				WHERE USUARIO=@USUCAJA

				IF NOT EXISTS (SELECT * FROM FCJ WHERE NOADMISION = @NOADMISION AND PROCEDENCIA = 'CE')
				BEGIN
					SET @CNSFACJ=NULL
					EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJ',@CNSFACJ OUTPUT
					SELECT @CNSFACJ =  REPLACE(SPACE(8 - LEN(@CNSFACJ))+LTRIM(RTRIM(@CNSFACJ)),SPACE(1),0)

					INSERT INTO FCJ (CNSFACJ,TIPO,CODCAJA,COMPANIA, CLASE_FAC,CNSACJ,ESTADO,USUARIO,SYS_ComputerName,IDTERCERO, FECHA, TIPOEGRESO, OBSERVACION, PROCEDENCIA, VALORTOTAL , USUARIOLOG
					,BANCO, SUCURSAL, CTA_BCO, NOADMISION, NOPRESTACION, CERRADA, ARCHIVADO, IDPLAN, IDAFILIADO, NOMBRECLIENTE)
					SELECT @CNSFACJ, 'INTERNO', @CODCAJA, @COMPANIA, 'COBRO', @CNSACJ, 'P', @CODCAJERO, @SYS_COMPUTERNAME, AUT.IDPROVEEDOR, DBO.FNK_FECHA_SIN_MLS(GETDATE()), null, '', 'CE',AUT.VALORCOPAGO, @USUARIO
					, null,null,null, @NOADMISION, @NOADMISION, 0, 0, AUT.IDPLAN, AUT.IDAFILIADO, AFI.NOMBREAFI
					FROM AUT 
					INNER JOIN AFI ON AUT.IDAFILIADO = AFI.IDAFILIADO
					WHERE AUT.IDAUT = @NOADMISION

					INSERT INTO FCJD (CODCAJA, CNSFACJ, ITEM, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, TIPODCTO)
					SELECT @CODCAJA, @CNSFACJ, AUTD.NO_ITEM, DBO.FNK_VALORVARIABLE ('IDCJCOPA'), AUTD.VALORCOPAGO, 1, AUTD.VALORCOPAGO, 'N'
					FROM AUTD 
					WHERE AUTD.IDAUT = @NOADMISION

					UPDATE AUT SET NORECIBOCAJA = @CNSFACJ, CODCAJA = @CODCAJA, TIPOCAJA = 'FCJ' WHERE AUT.IDAUT = @NOADMISION


				UPDATE FCJ SET RECAUDO=1,ENPAGOS=0,N_FACTURA=@FACTURA,IDKPAGE=@IDKPAGE WHERE CNSFACJ=@CNSFACJ AND CNSACJ=@CNSACJ AND CODCAJA=@CODCAJA

				EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@PCJ', @LONGITUD = 8, @LLAMADO = NULL, @NVOCONSEC = @CNSPCJ OUTPUT

				SELECT @CNSPCJ=@SEDE + REPLACE(SPACE(8-LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)

				SELECT @DATOBCO=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('BCO_CTA_SUC_IZIPAY')))

					SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=1
					SELECT @CTA=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=2
					SELECT @SUC=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=3

				INSERT INTO PCJ(CODCAJA,CNSPCJ,CNSFACJ,TIPOPAGO,VALOR,FECHA,CNSACJ,BANCO,CTA_BCO,SUCURSAL)
				SELECT @CODCAJA,@CNSPCJ,@CNSFACJ,DBO.FNK_VALORVARIABLE('IDCJFPAIZIPAY'),@VALOR,DBO.FNK_GETDATE(),@CNSACJ,@BCO,@CTA,@SUC

				SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"CONFIRMAR_RECIBO","PARAMETROS":{"CNSFACJ":"'+@CNSFACJ+'","CODCAJA":"'+@CODCAJA+'","CNSACJ":"'+@CNSACJ+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'

				EXEC SPQ_JSON @SQL

				UPDATE AUT SET TIPOPREVIO=2, AUT.FECHA_TIPOPREVIO = DBO.FNK_GETDATE() WHERE IDAUT=@NOADMISION

				END
			END
		END
		FETCH NEXT FROM PG_CURSOR    
		INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO
	END
	CLOSE PG_CURSOR
	DEALLOCATE PG_CURSOR

END




