IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_GENCXP_NOMINA' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_GENCXP_NOMINA
END

GO
CREATE   PROCEDURE DBO.SPK_GENCXP_NOMINA
@CNSPAGO          VARCHAR(20),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)
WITH ENCRYPTION
AS
DECLARE @CNSFCXP VARCHAR(20)
DECLARE @CODPRF_CUR VARCHAR(20)
DECLARE @DESCRIPCION_CUR VARCHAR(100)
DECLARE @IDTERCERO_CUR VARCHAR(20)
DECLARE @FECHA_CUR DATETIME
DECLARE @CODCONCEPTO_CUR VARCHAR(20)
DECLARE @NOMBRE_CONCEPTO_CUR VARCHAR(255)
DECLARE @VALOR_CUR DECIMAL(14,2)
DECLARE @NUMDOC_CUR2 VARCHAR(20)
DECLARE @CANTIDAD_CUR2 DECIMAL(14,2)
DECLARE @VALOR_CUR2 DECIMAL(14,2)
DECLARE @CCOSTO_CUR2 VARCHAR(20)
DECLARE @IDAREA_CUR2 VARCHAR(20)
DECLARE @CUENTA_CUR2 VARCHAR(20)
DECLARE @CNSNIEPE_CUR2 VARCHAR(20)
DECLARE @ITEMNIEPE_CUR2 DECIMAL(14,0)
DECLARE @ITEM INT
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @IDMODELOCONT VARCHAR(2)
DECLARE @CODNOMINA VARCHAR(20)
DECLARE @CUENTACR VARCHAR(20)
DECLARE @RUBRO    VARCHAR(20)
DECLARE @PPPTO    VARCHAR(20)
DECLARE @CDP      VARCHAR(20)
DECLARE @TIPOCXP   VARCHAR(20)
DECLARE @CNSRP     VARCHAR(20)
DECLARE @CCOSTOPPTO VARCHAR(20)
DECLARE @PORCENTAJE DECIMAL(14,6)
DECLARE @RUBRO_ID   INT
DECLARE @VLR_SINDTO DECIMAL(14,2)
DECLARE @SINDTO BIT
BEGIN
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
   PRINT 'Eliminando CXP generadas anteriormente para este Pago.'
   DELETE FCXPD 
   FROM   FCXPD INNER JOIN FCXP  ON FCXPD.CNSFCXP = FCXP.CNSFCXP 
                 LEFT JOIN FCXPP ON  FCXP.CNSFCXP = FCXPP.CNSFCXP
   WHERE  FCXP.PROCEDENCIA  = 'Nomina' 
   AND    FCXP.NOREFERENCIA = @CNSPAGO 
   AND    FCXPP.CNSFCXP IS NULL

   DELETE FCXP 
   FROM   FCXP LEFT JOIN FCXPP ON FCXP.CNSFCXP = FCXPP.CNSFCXP
   WHERE  FCXP.PROCEDENCIA  = 'Nomina' 
   AND    FCXP.NOREFERENCIA = @CNSPAGO 
   AND    FCXPP.CNSFCXP IS NULL


   SELECT @PPPTO=CNSPPTO,@CDP=CNSCDP,@TIPOCXP=DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT')  FROM NPER WHERE CNSPAGO=@CNSPAGO
 
	PRINT '@PPPTO='+@PPPTO
	PRINT '@CDP='+@CDP

   DECLARE GENCXP CURSOR FOR
   ---SE VERIFICA QUE LOS CONCEPTOS DE NEMPFD DE LA AGRUPACION DE CLASE=SALARIO PARA QUE NO GENERE CXP SIN DETALLE O DUPLICADA
   SELECT  CXP.CODNOMINA,CXP.CODPRF,CXP.DESCRIPCION,CXP.NUMDOC,CXP.FECHA,SUM(CXP.VALOR_NETO),SUM(SINDEDUC)
   FROM(
       SELECT B.CODNOMINA, C.CODPRF, C.DESCRIPCION, NEMP.TERCEROID AS NUMDOC, DBO.FNK_FECHA_SIN_HORA(B.FECHAFIN) FECHA, 
              A.VALOR_NETO,CASE WHEN EXISTS(SELECT *  
										FROM NEMPFD INNER JOIN NCOND ON NEMPFD.CODCONCEPTO=NCOND.CODCONCEPTO AND NEMPFD.ITEMCONCEPTO=NCOND.ITEM
                                             WHERE NEMPFD.CNSPAGO=@CNSPAGO AND C.CODPRF=NEMPFD.CODPRF
											 AND    COALESCE(NCOND.SINDEDUC,0)=1)
                            THEN (SELECT SUM(NEMPFD.VALOR)  
							FROM NEMPFD INNER JOIN NCOND ON NEMPFD.CODCONCEPTO=NCOND.CODCONCEPTO AND NEMPFD.ITEMCONCEPTO=NCOND.ITEM
                                             WHERE NEMPFD.CNSPAGO=@CNSPAGO AND C.CODPRF=NEMPFD.CODPRF AND    
                                             COALESCE(NCOND.SINDEDUC,0)=1
                                             AND NEMPFD.NUMDOC=A.NUMDOC
                                             ) ELSE 0 
                            END SINDEDUC
       FROM   NEMPF A INNER JOIN NPER B ON A.CNSPAGO = B.CNSPAGO
                      INNER JOIN NEMP ON A.NUMDOC=NEMP.NUMDOC, NPRF C
       WHERE  A.CNSPAGO    = @CNSPAGO
       AND    C.CLASE      = 'Salario' 
       AND    A.VALOR_NETO > 0 
       AND  EXISTS (SELECT *  FROM NEMPFD WHERE NEMPFD.CNSPAGO=@CNSPAGO AND C.CODPRF=NEMPFD.CODPRF)
       UNION ALL
       SELECT B.CODNOMINA,
         CASE WHEN F.TIPO='Ingreso' AND EXISTS(SELECT * FROM NEMP WHERE NUMDOC=A.IDTERCERO) THEN ( SELECT TOP 1 CODPRF FROM NPRF WHERE CLASE='Salario') ELSE C.CODPRF END,
         CASE WHEN F.TIPO='Ingreso' AND EXISTS(SELECT * FROM NEMP WHERE NUMDOC=A.IDTERCERO) THEN ( SELECT TOP 1 DESCRIPCION FROM NPRF WHERE CLASE='Salario') ELSE  C.DESCRIPCION END,
         A.IDTERCERO, DBO.FNK_FECHA_SIN_HORA(B.FECHAFIN), 
              SUM(A.VALOR+A.VALOR_EMPRESA),
			  SUM(CASE WHEN COALESCE(D.SINDEDUC,0)=1 THEN A.VALOR+A.VALOR_EMPRESA ELSE 0 END)
       FROM   NEMPFD A INNER JOIN NPER   B ON A.CNSPAGO     = B.CNSPAGO 
                       INNER JOIN NPRF   C ON A.CODPRF      = C.CODPRF 
                        LEFT JOIN NCOND  D ON A.CODCONCEPTO = D.CODCONCEPTO AND A.ITEMCONCEPTO = D.ITEM 
                        LEFT JOIN NCON   F ON D.CODCONCEPTO=F.CODCONCEPTO
                        LEFT JOIN NEMPF  E ON A.CNSPAGO     = E.CNSPAGO     AND A.NUMDOC       = E.NUMDOC AND A.ITEM = E.ITEM
       WHERE  A.CNSPAGO = @CNSPAGO AND D.GENERA_CXP = 'Si' AND C.CLASE <> 'Salario'
         AND A.LIQUIDAR='Si'
       GROUP BY B.CODNOMINA, C.CODPRF, C.DESCRIPCION, A.IDTERCERO, A.CNSPAGO, DBO.FNK_FECHA_SIN_HORA(B.FECHAFIN), F.TIPO,A.CODCONCEPTO
   )CXP
   GROUP BY CXP.CODNOMINA,CXP.CODPRF,CXP.DESCRIPCION,CXP.NUMDOC,CXP.FECHA
   ORDER BY CXP.CODPRF DESC,CXP.NUMDOC ASC

   OPEN GENCXP
   
   FETCH NEXT FROM GENCXP
   INTO @CODNOMINA, @CODPRF_CUR, @DESCRIPCION_CUR, @IDTERCERO_CUR, @FECHA_CUR, @VALOR_CUR,@VLR_SINDTO
 
   WHILE @@FETCH_STATUS = 0
   BEGIN
      PRINT '@IDTERCERO_CUR =  '+COALESCE(@IDTERCERO_CUR,'NO HAY TERCERO')
     SELECT @CNSRP=''
	  SET @CNSFCXP=SPACE(20)
	  IF EXISTS(SELECT * FROM NIEPE INNER JOIN NIEPED ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC 
		  WHERE NIEPE.CNSPAGO=@CNSPAGO AND COALESCE(NIEPED.CNSFCXP,'')<>'' 
        AND NIEPED.CODPRF=@CODPRF_CUR
        AND NIEPE.NUMDOC=@IDTERCERO_CUR)
	  BEGIN
		   SELECT @CNSFCXP=COALESCE(NIEPED.CNSFCXP,'') FROM NIEPE INNER JOIN NIEPED ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC 
		   WHERE  NIEPE.CNSPAGO=@CNSPAGO AND COALESCE(NIEPED.CNSFCXP,'')<>''  
         AND NIEPED.CODPRF=@CODPRF_CUR 
         AND NIEPE.NUMDOC=@IDTERCERO_CUR
	  END
	  IF COALESCE(@CNSFCXP,'')=''
	  BEGIN
		   EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@FCXPNM',@CNSFCXP OUTPUT   
		   SELECT @CNSFCXP = @SEDE + 'NM'+REPLACE(SPACE(6 - LEN(@CNSFCXP))+LTRIM(RTRIM(@CNSFCXP)),SPACE(1),0)
     END
     SELECT TOP 1 @NROCOMPROBANTE=NIEPED.NROCOMPROBANTE 
     FROM NIEPE INNER JOIN 
          NIEPED ON NIEPE.CNSNIEPE = NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC
     WHERE NIEPE.CNSPAGO=@CNSPAGO AND NIEPED.CODPRF=@CODPRF_CUR AND NIEPED.IDTERCERO_PRF=@IDTERCERO_CUR
      

      --SELECT @CNSRP FROM PTRP WHERE CONSECUTIVO=@PPPTO AND CDP=@CDP AND IDTERCERO=@IDTERCERO_CUR

	 IF(COALESCE(@NROCOMPROBANTE,'')='')
	 BEGIN 
	 	  SELECT TOP 1 @NROCOMPROBANTE= MCP.NROCOMPROBANTE FROM MCP
		  WHERE PROCEDENCIA='NOMINA' AND REFERENCIA2=@CNSPAGO AND  IDTERCERO=@IDTERCERO_CUR  AND ESTADO=2
		  AND COALESCE(ANULADO,0)=0
			
			IF(COALESCE(@NROCOMPROBANTE,'')='')
			 BEGIN 
			  SELECT TOP 1 @NROCOMPROBANTE= MCP.NROCOMPROBANTE FROM MCH INNER JOIN MCP ON MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE
			  WHERE MCP.PROCEDENCIA='NOMINA' AND MCP.REFERENCIA2=@CNSPAGO AND  MCH.IDTERCERO=@IDTERCERO_CUR  AND MCP.ESTADO=2 
			  AND COALESCE(ANULADO,0)=0
			 END 
	 END

	 

     PRINT 'FCXP.'
	  PRINT '@CNSFCXP =.'+@CNSFCXP
	  PRINT '@IDTERCERO_CUR ='+@IDTERCERO_CUR
	  PRINT '@CNSPAGO ='+@CNSPAGO
	  

      SELECT @PORCENTAJE=(CONVERT(DECIMAL(14,6),(VALOR_EGRESOS*100/(VALOR_INGRESOS-coalesce(@VLR_SINDTO,0))))/100) 
	  FROM NIEPE WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@IDTERCERO_CUR

	  PRINT '@PORCENTAJE='+CONVERT(VARCHAR(20),coalesce(@PORCENTAJE,0))

     INSERT INTO FCXP (CNSFCXP,FECHA,CNSFCOM,IDTERCERO,NOREFERENCIA,F_FACTURAREF,F_VENCE,VALOR,ESTADO,F_CANCELADO,USUARIO,
                        PROCEDENCIA,OBSERVACION,COMPANIA,SYS_COMPUTERNAME,USUARIOMOD,FECHAMOD,NUMCUOTA,MARCACONT,
                        CONTABILIZADA,NROCOMPROBANTE,SALDO,IDCLASEIMP,VLR_DESCUENTO,VLR_IVA,VLR_NETO,VLR_IMPUESTOS,
                        VLR_NOTASDEBITO,VLR_COMISION,CUEDEBITO,CUECREDITO,CNSFCXPPM,TIPOCXP,CNSPPTO,CNSCDP,CNSRP)
      SELECT @CNSFCXP, DBO.FNK_FECHA_SIN_MLS(GETDATE()),@CODNOMINA,@IDTERCERO_CUR, @CNSPAGO, @FECHA_CUR, 
             @FECHA_CUR, @VALOR_CUR, 'N', NULL, @USUARIO, 
             'Nomina', @DESCRIPCION_CUR+', Nómina No. '+@CNSPAGO, @COMPANIA, @SYS_COMPUTERNAME, NULL, NULL, NULL, 0, 1, 
             @NROCOMPROBANTE, @VALOR_CUR, NULL, 0, 0, @VALOR_CUR, 0, 0, 0, NULL, @CUENTACR, NULL,@TIPOCXP,@PPPTO,@CDP,@CNSRP
      


	  
	  PRINT 'ANTES DEL CURSOR 2'
      DECLARE CUR2 CURSOR FOR 

     SELECT NUMDOC,CANTIDAD,CASE WHEN EXISTS(SELECT * FROM NEMPF WHERE NUMDOC=@IDTERCERO_CUR AND CNSPAGO=@CNSPAGO) 
     AND EXISTS(SELECT * FROM NCON X WHERE X.CODCONCEPTO=FD.CODCONCEPTO AND X.TIPO='Ingreso') THEN
         CASE WHEN SINDEDUC=0 THEN 
              CONVERT(DECIMAL(14,2),VALOR-ROUND((VALOR*COALESCE(@PORCENTAJE,0)),2))
         ELSE
            VALOR 
         END
     ELSE
         CONVERT(DECIMAL(14,2),VALOR)
     END,CCOSTO,IDAREA,CUENTA,FD.CNSPAGO,LINEA,CODCONCEPTO,DESCRIPCION,RUBRO,RUBRO_ID,SINDEDUC
      FROM (
      SELECT A.IDTERCERO,A.NUMDOC, CANTIDAD = 1, A.VALOR,H.VALOR_EGRESOS,
			  F.CCOSTO, F.IDAREA,
             CUENTA = DBO.FNK_CUENTA_KMCOM('01', 'NOMINA', 'DB', A.CODCONCEPTO, F.IDAREA, F.CCOSTO,'S',B.CODNOMINA),
             A.CNSPAGO, A.LINEA, A.CODCONCEPTO, G.DESCRIPCION,D.RUBRO,C.CLASE,D.RUBRO_ID,COALESCE(D.SINDEDUC,0)SINDEDUC
      FROM   NEMPFD A INNER JOIN NPER   B ON A.CNSPAGO     = B.CNSPAGO 
                       LEFT JOIN NPRF   C ON A.CODPRF      = C.CODPRF 
                       LEFT JOIN NCOND  D ON A.CODCONCEPTO = D.CODCONCEPTO AND A.ITEMCONCEPTO = D.ITEM 
                       LEFT JOIN TER    E ON A.IDTERCERO   = E.IDTERCERO 
                       LEFT JOIN NEMP   F ON F.NUMDOC      = A.NUMDOC 
                       LEFT JOIN NCON   G ON G.CODCONCEPTO = A.CODCONCEPTO 
                       LEFT JOIN NEMPF  H ON A.CNSPAGO     = H.CNSPAGO   AND A.NUMDOC      = H.NUMDOC   AND A.ITEM        = H.ITEM
      WHERE  A.CNSPAGO = @CNSPAGO    
      AND    D.GENERA_CXP = 'Si'      
      AND    A.INFO       = 'No'           
      AND    A.VALOR + A.VALOR_EMPRESA <> 0 
      AND    A.CODPRF     = @CODPRF_CUR 
      AND    C.CLASE      = 'Salario' 
      AND    A.IDTERCERO  = @IDTERCERO_CUR 
      AND NOT C.CODPRF IS NULL 
      AND NOT E.IDTERCERO IS NULL
      AND A.LIQUIDAR='Si'    
      UNION ALL
      SELECT A.IDTERCERO,A.NUMDOC, CANTIDAD = 1, VALOR =  A.VALOR+A.VALOR_EMPRESA,
	  CASE WHEN G.TIPO='Ingreso' AND EXISTS(SELECT * FROM NEMP WHERE NUMDOC=@IDTERCERO_CUR) THEN  H.VALOR_EGRESOS ELSE 0 END  VALOR_EGRESOS,
	   F.CCOSTO, F.IDAREA, 
             CUENTA = DBO.FNK_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', 'DB', A.CODCONCEPTO, F.IDAREA, F.CCOSTO,'S',B.CODNOMINA),
             A.CNSPAGO, A.LINEA, A.CODCONCEPTO, G.DESCRIPCION,D.RUBRO,C.CLASE,D.RUBRO_ID,COALESCE(D.SINDEDUC,0)
      FROM   NEMPFD A INNER JOIN NPER  B ON A.CNSPAGO     = B.CNSPAGO 
                       LEFT JOIN NPRF  C ON A.CODPRF      = C.CODPRF 
                       LEFT JOIN NCOND D ON A.CODCONCEPTO = D.CODCONCEPTO AND A.ITEMCONCEPTO=D.ITEM 
                       LEFT JOIN TER   E ON A.IDTERCERO   = E.IDTERCERO 
                       LEFT JOIN NEMP  F ON F.NUMDOC      = A.NUMDOC 
                       LEFT JOIN NCON  G ON G.CODCONCEPTO = A.CODCONCEPTO 
                       LEFT JOIN NEMPF H ON A.CNSPAGO     = H.CNSPAGO AND A.NUMDOC = H.NUMDOC AND A.ITEM = H.ITEM
      WHERE  A.CNSPAGO    = @CNSPAGO 
      AND    D.GENERA_CXP = 'Si' 
      AND    A.INFO       = 'No' 
      AND    A.VALOR + A.VALOR_EMPRESA <>0 
      AND    C.CLASE  <> 'Salario' 
      AND    A.IDTERCERO=@IDTERCERO_CUR 
      AND    NOT C.CODPRF IS NULL 
      AND    NOT E.IDTERCERO IS NULL
      AND    A.LIQUIDAR='Si' 
      AND    A.CODPRF =CASE WHEN  G.TIPO='Ingreso' AND EXISTS(SELECT * FROM NPRF WHERE CODPRF=@CODPRF_CUR AND CLASE='Salario') THEN A.CODPRF ELSE @CODPRF_CUR END
       )FD 
	 ORDER BY FD.CODCONCEPTO


    
    OPEN CUR2
    FETCH NEXT FROM CUR2
    INTO @NUMDOC_CUR2, @CANTIDAD_CUR2, @VALOR_CUR2, @CCOSTO_CUR2, @IDAREA_CUR2, @CUENTA_CUR2, @CNSNIEPE_CUR2, 
         @ITEMNIEPE_CUR2, @CODCONCEPTO_CUR, @NOMBRE_CONCEPTO_CUR,@RUBRO,@RUBRO_ID,@SINDTO
    
    SET @ITEM = 1
    WHILE @@FETCH_STATUS = 0
    BEGIN
       PRINT 'FCXPD.'
       PRINT '@RUBRO=.'+@RUBRO
       INSERT INTO FCXPD(CNSFCXP,ITEM,IDSERVICIO,CANTIDAD,VALOR,ESTADO,N_PRESUP,ITEM_PRESUP,IDCLASEIMP,VLR_DESCUENTO,
                         VLR_IVA,VLR_NETO,NOLOTE,PREFIJO,CCOSTO,IDAREAH,IDAREA,NROCOMPROBANTE,PROCEDENCIA, CUENTA_SER,RUBRO,RUBRO_ID)
       SELECT @CNSFCXP CNSFCXP, @ITEM ITEM, @CODCONCEPTO_CUR IDSERVICIO, @CANTIDAD_CUR2 CANTIDAD, DBO.FNK_REDONDEA_MAS_EXCEL(@VALOR_CUR2,0) VALOR, 'P' ESTADO, 
              @CNSNIEPE_CUR2 N_PRESUP, @ITEMNIEPE_CUR2 ITEM_PRESUP, NULL IDCLASEIMP, 0 VLR_DESCUENTO,
              0 VLR_IVA, DBO.FNK_REDONDEA_MAS_EXCEL(@VALOR_CUR2,0) VLR_NETO, @NUMDOC_CUR2 NOLOTE, @CODCONCEPTO_CUR PREFIJO, @CCOSTO_CUR2 CCOSTO, 
              NULL IDAREAH, @IDAREA_CUR2 IDAREA,NULL NROCOMPROBANTE, 'Nomina', '0',@RUBRO,@RUBRO_ID
       

       --REVISO SI LA VARIABLE DEL RUBRO ES DISTINCTA
      IF COALESCE(DBO.FNK_VALORVARIABLE('TOMA_RUBROENVIO_NOMI'),'NCOND')='NPLTCO'
      BEGIN
         UPDATE FCXPD SET RUBRO=NPLTCO.RUBRO, RUBRO_ID=COALESCE(PTRUB.RUBRO_ID,NPLTCO.RUBRO_ID)
         FROM FCXPD INNER JOIN NPLTCO ON FCXPD.IDSERVICIO=NPLTCO.CODCONCEPTO
                    LEFT  JOIN PTRUB ON NPLTCO.RUBRO=PTRUB.RUBRO AND PTRUB.CONSECUTIVO=@PPPTO
         WHERE FCXPD.CNSFCXP=@CNSFCXP       

      END
       FETCH NEXT FROM CUR2
       INTO @NUMDOC_CUR2, @CANTIDAD_CUR2, @VALOR_CUR2, @CCOSTO_CUR2, @IDAREA_CUR2, @CUENTA_CUR2, @CNSNIEPE_CUR2, 
            @ITEMNIEPE_CUR2, @CODCONCEPTO_CUR, @NOMBRE_CONCEPTO_CUR,@RUBRO,@RUBRO_ID,@SINDTO
       SET @ITEM = @ITEM + 1
    END
    CLOSE CUR2
    DEALLOCATE CUR2
   PRINT 'BUSCANDO LA CUENTA CREDITO CXP'
   IF EXISTS(SELECT NROCOMPROBANTE FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)
   BEGIN
      SELECT TOP 1 @CUENTACR=CUENTA FROM MCH WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND IDTERCERO=@IDTERCERO_CUR AND TIPO='CR'
      AND PREFIJO IN(SELECT IDSERVICIO  FROM FCXPD WHERE CNSFCXP=@CNSFCXP)

   END
   ELSE
   BEGIN
      SELECT TOP 1 @CUENTACR=CUENTA FROM MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND IDTERCERO=@IDTERCERO_CUR AND TIPO='CR'
      AND PREFIJO IN(SELECT IDSERVICIO  FROM FCXPD WHERE CNSFCXP=@CNSFCXP)
   END
   UPDATE FCXP SET CUECREDITO=@CUENTACR WHERE CNSFCXP=@CNSFCXP
--------------------------------aqui toca adicionar  el spk de nota debito credito  JHONATAN STEVEN ------------------------------------------------              
              EXEC SPK_CALCULOVALORESCXP @CNSFCXP
------------------------------------------------------------YA RECALCULA EN CXP---------------------------------------------------------------------------------       

    IF DBO.FNK_VALORVARIABLE('PRESUP_CXP_ACTIVADO')='SI' AND  DBO.FNK_VALORVARIABLE('ENVIARNOMI_PPTO_AUTO')='SI'
    BEGIN
		 PRINT 'BUSCO LOS CDP Y PTTPTO'
       IF @CDP<>'' AND @PPPTO<>''
       BEGIN
          DECLARE @SOLICITANTE VARCHAR(20)
          SELECT @CCOSTOPPTO=DBO.FNK_VALORVARIABLE('PRESUP_CCOSTO')
         
			   SELECT @CNSRP = ISNULL(CONTADOR_RP,0) + 1 
			   FROM   PTPTO 
			   WHERE  COMPANIA = '01' AND CONSECUTIVO = @PPPTO
             
			   SELECT @CNSRP = @SEDE + REPLACE(SPACE(8 - LEN(@CNSRP))+LTRIM(RTRIM(@CNSRP)),SPACE(1),0) 

			   UPDATE PTPTO SET CONTADOR_RP = ISNULL(CONTADOR_RP,0) + 1 
			   WHERE  COMPANIA    = '01' 
			   AND    CONSECUTIVO = @PPPTO
         
			   SELECT @SOLICITANTE= AUTORIZADOR  FROM PTCDP  WHERE CONSECUTIVO=@PPPTO AND CDP=@CDP

            INSERT INTO PTRP(COMPANIA, CONSECUTIVO, CDP, RP, OBJETIVO, VALOR, SALDO, SOLICITANTE, CNSFCOM, CNSFCXP, IDTERCERO, NODOCUMENTO, FECHARP, FECHAPLAZO, ESTADO, CCOSTO, USUARIO, JEFEPTPTO)
            SELECT '01',@PPPTO,@CDP,@CNSRP,LEFT	(OBSERVACION,1000),FCXP.VALOR,FCXP.VALOR,@SOLICITANTE,CNSFCOM,CNSFCXP,FCXP.IDTERCERO,FCXP.NOREFERENCIA,FECHA,FECHA,'NoConfirmado',@CCOSTOPPTO,@USUARIO,DBO.FNK_VALORVARIABLE('JEFE_PRESUPUESTO_USU')
            FROM FCXP 
            WHERE CNSFCXP=@CNSFCXP

            INSERT INTO PTRPD(COMPANIA, CONSECUTIVO, CDP, RP, CLASE, RUBRO, VALOR, VALOR_CXP, SALDO, OBJETIVO,RUBRO_ID)
            SELECT '01',@PPPTO,@CDP,@CNSRP,'Gasto',RUBRO,SUM(VLR_NETO),0,SUM(VLR_NETO),'',RUBRO_ID
            FROM FCXPD 
            WHERE CNSFCXP=@CNSFCXP
            AND COALESCE(RUBRO,'')<>''
            GROUP BY RUBRO,RUBRO_ID

            UPDATE PTRPD SET ITEMCDPD=PTCDPD.ITEM
            FROM PTRPD INNER JOIN PTCDPD ON PTRPD.CONSECUTIVO=PTCDPD.CONSECUTIVO
            AND PTRPD.CDP=PTCDPD.CDP
            AND PTCDPD.RUBRO=PTRPD.RUBRO
            AND PTCDPD.RUBRO_ID=PTRPD.RUBRO_ID
            WHERE PTRPD.CONSECUTIVO=@PPPTO
            AND PTRPD.CDP=@CDP
            AND PTRPD.RP=@CNSRP

        
	        IF (SELECT ESTADO FROM  PTRP WHERE CONSECUTIVO=@PPPTO AND COMPANIA='01' AND CDP=@CDP AND IDTERCERO=@IDTERCERO_CUR AND RP=@CNSRP)='NoConfirmado'
	        BEGIN
              UPDATE PTRP SET ESTADO='Confirmado' WHERE COMPANIA='01' AND CONSECUTIVO=@PPPTO AND CDP=@CDP AND RP=@CNSRP AND CCOSTO=@CCOSTOPPTO        
	        END
           UPDATE FCXP SET CNSRP=@CNSRP WHERE CNSFCXP=@CNSFCXP

	        PRINT 'VOY A ENVIAR LA CXP'
           EXEC SPK_ENTREGA_CXP_PTTO @CNSFCXP, @USUARIO
		     PRINT 'REGRESO PRESUPUESTO'
       END
    END
    FETCH NEXT FROM GENCXP
    INTO @CODNOMINA, @CODPRF_CUR, @DESCRIPCION_CUR, @IDTERCERO_CUR, @FECHA_CUR, @VALOR_CUR,@VLR_SINDTO
   END 
   CLOSE GENCXP
   DEALLOCATE GENCXP

   UPDATE NIEPED SET CNSFCXP=FCXPD.CNSFCXP
   FROM NIEPE INNER JOIN NIEPED ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC
		      INNER JOIN FCXPD ON N_PRESUP=NIEPE.CNSPAGO AND FCXPD.NOLOTE=NIEPE.NUMDOC AND FCXPD.IDSERVICIO=NIEPED.CODCONCEPTO
   WHERE NIEPE.CNSPAGO=@CNSPAGO
   PRINT 'GENERACION DE CXP ADICIONALES....'
   IF ( SELECT COUNT(*) FROM DBO.FNK_TABLA_DESTRING(DBO.FNK_VALORVARIABLE('COD_NOMI_CXP_ADICION'),','))>0
   BEGIN 
      EXEC SPK_GENCXP_NOMINA_PROVI @CNSPAGO,@COMPANIA,@SEDE,@USUARIO,@SYS_COMPUTERNAME
   END
END

