IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_PROCESO_SOAT' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_PROCESO_SOAT
END

GO
CREATE PROC DBO.SPK_PROCESO_SOAT
@NOADMISION VARCHAR(16),
@TOPE1      DECIMAL(18,6),
@TOPE2      DECIMAL(18,6),
@CUANTAS    INT = 0,
@IDTERCERO1 VARCHAR(20) = NULL,
@IDTERCERO2 VARCHAR(20) = NULL
WITH ENCRYPTION
AS
DECLARE @TIPOCOSTO           VARCHAR(20)
DECLARE @IDSERVICIO          VARCHAR(20)
DECLARE @VALOREXCEDENTE      DECIMAL(14,2)
DECLARE @DESCSERVICIO        VARCHAR(255)
DECLARE @IDAREA              VARCHAR(20)       
DECLARE @IDCIRUGIA           VARCHAR(20)
DECLARE @CANTIDAD            DECIMAL(18,6)
DECLARE @VALOR               DECIMAL(18,6)
DECLARE @VALORCOPAGO         DECIMAL(14,2)
DECLARE @VALORPCOMP          DECIMAL(14,2)
DECLARE @PREFIJO             VARCHAR(6)
DECLARE @NOPRESTACION        VARCHAR(16)
DECLARE @NOITEM              SMALLINT
DECLARE @VLRFALTAAPLICARSOAT DECIMAL(18,6) 
DECLARE @IDPROVEEDOR         VARCHAR(20)
DECLARE @CCOSTO              VARCHAR(20)
DECLARE @SUBCCOSTO           VARCHAR(4) 
DECLARE @PCOSTO              DECIMAL(18,6)
DECLARE @FECHA               DATETIME
DECLARE @VALAUX              DECIMAL(18,6)
DECLARE @VALAUX1             DECIMAL(18,6)
BEGIN
   SELECT @TIPOCOSTO = DBO.FNK_VALORVARIABLE('CCOSTOENPRESTACION')
   DELETE HADM_S WHERE NOADMISION = @NOADMISION
   DELETE HADM_T WHERE NOADMISION = @NOADMISION
   IF @TIPOCOSTO = 'SER:CCOSTO'
   BEGIN
      IF DBO.FNK_VALORVARIABLE('ORDEN_GASTO_SOAT')='VALOR'
      BEGIN
         DECLARE TC_CURSOR CURSOR FOR
         SELECT HPRED.IDSERVICIO,  HPRED.VALOREXCEDENTE,      SER.DESCSERVICIO,  HPRE.IDAREA,               
                HPRED.IDCIRUGIA,   HPRED.CANTIDAD,            HPRED.VALOR, 
                HPRED.VALORCOPAGO, HPRED.VALORPCOMP,          SER.PREFIJO,       HPRED.NOPRESTACION, 
                HPRED.NOITEM,      HPRED.VLRFALTAAPLICARSOAT, HPRED.IDPROVEEDOR, 
                SER.CCOSTO,      HPRE.SUBCCOSTO,            HPRED.PCOSTO,      HPRE.FECHA 
         FROM   HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
                     INNER JOIN SER   ON HPRED.IDSERVICIO  = SER.IDSERVICIO
         WHERE  HPRE.NOADMISION = @NOADMISION
         AND   (HPRED.UTISOAT <> 1 OR HPRED.UTISOAT IS NULL) 
         AND    COALESCE(HPRED.FACTURADA,0) = 0
         ORDER BY HPRED.VALOREXCEDENTE DESC
      END
      ELSE
      BEGIN
         DECLARE TC_CURSOR CURSOR FOR
         SELECT HPRED.IDSERVICIO,  HPRED.VALOREXCEDENTE,      SER.DESCSERVICIO,  HPRE.IDAREA,               
                HPRED.IDCIRUGIA,   HPRED.CANTIDAD,            HPRED.VALOR, 
                HPRED.VALORCOPAGO, HPRED.VALORPCOMP,          SER.PREFIJO,       HPRED.NOPRESTACION, 
                HPRED.NOITEM,      HPRED.VLRFALTAAPLICARSOAT, HPRED.IDPROVEEDOR, 
                SER.CCOSTO,      HPRE.SUBCCOSTO,            HPRED.PCOSTO,      HPRE.FECHA 
         FROM   HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
                     INNER JOIN SER   ON HPRED.IDSERVICIO  = SER.IDSERVICIO
         WHERE  HPRE.NOADMISION = @NOADMISION
         AND   (HPRED.UTISOAT <> 1 OR HPRED.UTISOAT IS NULL) 
         AND    COALESCE(HPRED.FACTURADA,0) = 0
         ORDER BY HPRE.FECHA
      END
   END
   ELSE
   BEGIN
      IF DBO.FNK_VALORVARIABLE('ORDEN_GASTO_SOAT')='VALOR'
      BEGIN
         DECLARE TC_CURSOR CURSOR FOR
         SELECT HPRED.IDSERVICIO,  HPRED.VALOREXCEDENTE,      SER.DESCSERVICIO,  HPRE.IDAREA,         
                HPRED.IDCIRUGIA,   HPRED.CANTIDAD,            HPRED.VALOR, 
                HPRED.VALORCOPAGO, HPRED.VALORPCOMP,          SER.PREFIJO,       HPRED.NOPRESTACION, 
                HPRED.NOITEM,      HPRED.VLRFALTAAPLICARSOAT, HPRED.IDPROVEEDOR, 
                HPRE.CCOSTO,       HPRE.SUBCCOSTO,            HPRED.PCOSTO,      HPRE.FECHA 
         FROM   HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
                     INNER JOIN SER   ON HPRED.IDSERVICIO  = SER.IDSERVICIO
         WHERE  HPRE.NOADMISION = @NOADMISION
         AND    (HPRED.UTISOAT <> 1 OR HPRED.UTISOAT IS NULL) 
         AND    COALESCE(HPRED.FACTURADA,0) = 0
         ORDER BY HPRED.VALOREXCEDENTE DESC
      END
      ELSE
      BEGIN
         DECLARE TC_CURSOR CURSOR FOR
         SELECT HPRED.IDSERVICIO,  HPRED.VALOREXCEDENTE,      SER.DESCSERVICIO,  HPRE.IDAREA,         
                HPRED.IDCIRUGIA,   HPRED.CANTIDAD,            HPRED.VALOR, 
                HPRED.VALORCOPAGO, HPRED.VALORPCOMP,          SER.PREFIJO,       HPRED.NOPRESTACION, 
                HPRED.NOITEM,      HPRED.VLRFALTAAPLICARSOAT, HPRED.IDPROVEEDOR, 
                HPRE.CCOSTO,       HPRE.SUBCCOSTO,            HPRED.PCOSTO,      HPRE.FECHA 
         FROM   HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
                     INNER JOIN SER   ON HPRED.IDSERVICIO  = SER.IDSERVICIO
         WHERE  HPRE.NOADMISION = @NOADMISION
         AND    (HPRED.UTISOAT <> 1 OR HPRED.UTISOAT IS NULL) 
         AND    COALESCE(HPRED.FACTURADA,0) = 0
         ORDER BY HPRE.FECHA
      END
   END
   SELECT @VALAUX  = 0
   SELECT @VALAUX1 = 0
   OPEN TC_CURSOR  
   FETCH NEXT FROM TC_CURSOR  
   INTO  @IDSERVICIO,  @VALOREXCEDENTE, @DESCSERVICIO, @IDAREA,       @IDCIRUGIA, @CANTIDAD,            @VALOR,
         @VALORCOPAGO, @VALORPCOMP,     @PREFIJO,      @NOPRESTACION, @NOITEM,    @VLRFALTAAPLICARSOAT, @IDPROVEEDOR,
         @CCOSTO,      @SUBCCOSTO,      @PCOSTO,       @FECHA 
   WHILE @@FETCH_STATUS = 0  
   BEGIN        
      IF (@VALOREXCEDENTE + @VALAUX) < @TOPE1
      BEGIN 
         INSERT INTO HADM_S( NOADMISION, FACTN, FECHA, DB_CR, AREAPRESTACION, AREAFUNCONT, UBICACION, VR_TOTAL,
                              IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, VALOR, VLR_SERVICI,
                              CANTIDAD, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, SUBCCOSTO, NOPRESTACION,
                              NOITEM, PCOSTO)
         SELECT @NOADMISION, 1, @FECHA, 'DB', @IDAREA, NULL, '', @VALOREXCEDENTE,
                '', @CCOSTO, @PREFIJO, @DESCSERVICIO, @IDSERVICIO, @IDCIRUGIA, @VALOR, @VALOREXCEDENTE,
                @CANTIDAD,  0, 0, @IDPROVEEDOR, @SUBCCOSTO, @NOPRESTACION, @NOITEM, @PCOSTO
         
         SELECT @VALAUX = @VALAUX + @VALOREXCEDENTE
      END
      ELSE
      BEGIN              
         INSERT INTO HADM_S( NOADMISION, FACTN, FECHA, DB_CR, AREAPRESTACION, AREAFUNCONT, UBICACION, VR_TOTAL,
                             IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, VALOR, VLR_SERVICI,
                             CANTIDAD, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, SUBCCOSTO, NOPRESTACION,
                             NOITEM, PCOSTO)
         SELECT @NOADMISION, 3, @FECHA, 'DB', @IDAREA, NULL, '', @VALOREXCEDENTE,
                '', @CCOSTO, @PREFIJO, @DESCSERVICIO, @IDSERVICIO, @IDCIRUGIA, @VALOR, @VALOREXCEDENTE,
                @CANTIDAD,  0, 0, @IDPROVEEDOR, @SUBCCOSTO, @NOPRESTACION, @NOITEM, @PCOSTO                             
      END
      FETCH NEXT FROM TC_CURSOR  
      INTO  @IDSERVICIO,  @VALOREXCEDENTE, @DESCSERVICIO, @IDAREA,       @IDCIRUGIA, @CANTIDAD,            @VALOR,
            @VALORCOPAGO, @VALORPCOMP,     @PREFIJO,      @NOPRESTACION, @NOITEM,    @VLRFALTAAPLICARSOAT, @IDPROVEEDOR,
            @CCOSTO,      @SUBCCOSTO,      @PCOSTO,       @FECHA 
   END
   CLOSE TC_CURSOR  
   DEALLOCATE TC_CURSOR
   INSERT INTO HADM_T ( NOADMISION, ITEM, TOPE1, TOPE2, CUANTAS, IDTERCERO1, IDTERCERO2, USUARIO )
   SELECT @NOADMISION, 1, @TOPE1, @TOPE2, @CUANTAS, @IDTERCERO1, @IDTERCERO2, NULL
   
END

