SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"ANEXOS_HADMFTR","METODO":"ANEXO_NORMAL","PARAMETROS":{"TAB":"AFTR","TANEXO":"normal","ANEXO":"normal","NOADMISION":"0202475757","IDTERCERO":"839000495","IDPLAN":"AMBS25","N_FACTURA":"ASFE95743","CNSRPDX":null,"ITEM":null},"USUARIO":"JJIMENEZ"}'

SELECT  * FROM FTR WHERE TIPOFAC='M' ORDER BY F_FACTURA DESC