
SELECT * FROM #A WHERE NOT EXISTS(SELECT * FROM SER WHERE SER.IDSERVICIO COLLATE SQL_Latin1_General_CP1_CI_AS=#A.IDSERVICIO)

SELECT SER.IDSERVICIO INTO #B FROM SER WHERE  EXISTS(SELECT * FROM #A WHERE SER.IDSERVICIO COLLATE SQL_Latin1_General_CP1_CI_AS=#A.IDSERVICIO)

SELECT 'SELECT '''+SER.PREFIJO+''' PREFIJO,'''+PRE.NOM_PREFIJO+''' NOM_PREFIJO,'''+ IDSERVICIO+''' IDSERVICIO,'''+COALESCE(GRUPOQX,'')+''' GRUPOQX,'''+CAST(POS AS VARCHAR(1))+''' POS,'''+CAST(POSS AS VARCHAR(1))+''' POSS,'''+COALESCE(SEXO,'')+''' SEXO,'''+COALESCE(TIPORANGOE,'')+'''TIPORANGOE,'''+CAST(COALESCE(EDADINICIAL,1) AS  VARCHAR(3))+'''EDADINICIAL,'''+CAST(COALESCE(EDADFINAL,99) AS  VARCHAR(3))+'''EDADFINAL,'''+COALESCE(CODIGORIPS,'')+'''CODIGORIPS,'''+COALESCE(IDALTERNA,'')+'''IDALTERNA,'''+CAST(SER.CIRUGIA AS VARCHAR(2))+'''CIRUGIA,'''+   
COALESCE(IDSECCION,'')+'''IDSECCION,'''+COALESCE(IDPLANILLA,'')+'''IDPLANILLA,'''+COALESCE(CODCUPS,'')+'''CODCUPS,'''+COALESCE(DESCRIPCION_CUPS,'')+'''DESCRIPCION_CUPS,'''+COALESCE(AMBITO,'')+'''AMBITO,'''+COALESCE(CLASEHTX,'')+'''CLASEHTX,'''+COALESCE(VIA,'')+'''VIA  UNION ALL' FROM SER INNER JOIN PRE ON SER.PREFIJO=PRE.PREFIJO WHERE  EXISTS(SELECT * FROM #A WHERE SER.IDSERVICIO COLLATE SQL_Latin1_General_CP1_CI_AS=#A.IDSERVICIO)

SELECT IDTARIFA,COUNT(*) FROM TARDV WHERE IDSERVICIO IN(SELECT * FROM #B) AND IDTARIFA='002'
GROUP BY IDTARIFA



SELECT * FROM TARDV WHERE IDSERVICIO IN(SELECT * FROM #B) AND IDTARIFA='002'


SELECT * FROM TAR