SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

SELECT  ICTZ.CNSICTZ, ICTZ.FECHA, ICTZ.OBSERVACION, ICTZ.USUARIO, ICTZ.ESTADO  FROM [dbo].[ICTZ] WHERE (ICTZ.CNSICTZ LIKE '%%%%') AND  1 = 1 AND  CONVERT(DATE, ICTZ.FECHA) >= '2025-07-01' AND  CONVERT(DATE, ICTZ.FECHA) <= '2025-07-16'  ORDER BY FECHA DESC OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


EXEC SPQ_JSON '{"MODELO":"ILPRE","METODO":"DETALES_ICTZ","PARAMETROS":{"CNSICTZ":27},"USUARIO":"JJIMENEZ"}'

SELECT  * FROM ICTZD WHERE CNSICTZ=27 AND IDSERVICIO='DM19-5'

EXEC SPQ_JSON '{"MODELO":"ILPRE","METODO":"GUARDA_ICTZD","PARAMETROS":{"PROCESO":"Editar","IDSERVICIO":"DM19-5","CANTIDAD":300,"CNSICTZ":27,"CNSICTZD":54,"NOLOTEPEDIDO":null,"FECHAVENCE":"2026-03-31"},"USUARIO":"JJIMENEZ"}'


EXEC SPQ_JSON '{"MODELO":"EXISTENCIA","METODO":"IMPRIME_POR_SEDE","PARAMETROS":{"TIPO":"","ESTADO":"Activo","MAYOR0":true,"BODEGAACTUAL":false,"IDBODEGA":"045","SELECCIONADO":false,"BODEGASELECCIONADA":"046"},"USUARIO":"JJIMENEZ"}'


SELECT CEN.CCOSTO, CEN.DESCRIPCION, AFU.IDAREA, AFU.DESCRIPCION AS DESC_AREA  FROM [dbo].[CEN] INNER JOIN AFU ON AFU.IDAREA = CEN.IDAREA WHERE (CEN.CCOSTO LIKE '%%%%' OR  CEN.DESCRIPCION LIKE '%%%%') AND AFU.IDAREA = 5105  ORDER BY [dbo].[CEN].[COMPANIA] OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 