IF EXISTS (SELECT name FROM sysobjects WHERE NAME = 'SPK_CREARESOL' AND type = 'P')
BEGIN
   DROP PROCEDURE SPK_CREARESOL
END

GO
CREATE PROC DBO.SPK_CREARESOL
	@CODRES		VARCHAR(20),
	@IDAFILIADO VARCHAR(30),
	@FECHAR		VARCHAR(30),
	@ID			INT OUTPUT
WITH ENCRYPTION
AS 
/* 
Fecha:		 2018-10-18
Descripción: Procedimiento que creará RESAFI4505
*/
SET NOCOUNT ON
DECLARE 
	@PERIODO	   VARCHAR(6),
	@PERIODOANT	VARCHAR(6),
	@IDTERCERO	VARCHAR(20),
	@IDPLAN		VARCHAR(6),
	@REGIMEN	   VARCHAR(20),
	@FECHA      DATETIME,
   @IPS        VARCHAR(20)
BEGIN 
	PRINT 'EXEC SPK_CREARESOL '''+@CODRES+''', '''+@IDAFILIADO+''', '''+@FECHAR+''''
	
	SET @FECHA = CONVERT(DATETIME,REPLACE(@FECHAR,'-',''))

	SELECT @IDTERCERO=IDADMINISTRADORA, @IDPLAN=IDPLAN FROM AFI WHERE IDAFILIADO=@IDAFILIADO
	SELECT @REGIMEN=TIPOSISTEMA FROM PLN WHERE IDPLAN=@IDPLAN

	DECLARE @TABLE TABLE (ID INT IDENTITY(1,1), CAMPO VARCHAR(10), DATO VARCHAR(120))
	DECLARE @CAMPO VARCHAR(10), @DATO VARCHAR(255), @FIX INT, @FIX_TO INT

   SELECT @IPS=(CASE DATO WHEN '812005522' THEN 'FAS'
						  WHEN '839000145' THEN 'ASOCA' 
						 WHEN '800101022' THEN 'HNSP'
						 WHEN '825002525' THEN 'ALBA' ELSE DATO END) FROM USVGS WHERE IDVARIABLE='IDTERCEROINSTALADO' 

	IF COALESCE(@REGIMEN,'')=''
		SET @REGIMEN = 'Otro'

	SELECT @PERIODO = CONVERT(VARCHAR(4),YEAR(@FECHA)) + RIGHT('00'+CONVERT(VARCHAR(2),MONTH(@FECHA)),2)

	IF @CODRES = '4505'
	BEGIN
		SELECT @ID=IDRESAFI4505 FROM RESAFI4505 WHERE PERIODO=@PERIODO AND IDAFILIADO=@IDAFILIADO AND COALESCE(IDTERCERO,'')=@IDTERCERO

		IF COALESCE(@ID,'')=''
		BEGIN
			SELECT TOP 1 @ID=IDRESAFI4505 FROM RESAFI4505 WHERE IDAFILIADO=@IDAFILIADO AND PERIODO<=@PERIODO ORDER BY PERIODO DESC
			IF COALESCE(@ID,'')=''
			BEGIN
				INSERT INTO RESAFI4505 (PERIODO, IDAFILIADO, IDTERCERO, REGIMEN)
				SELECT @PERIODO, @IDAFILIADO, @IDTERCERO, @REGIMEN
				
				SET @ID=@@IDENTITY

				INSERT INTO @TABLE (CAMPO, DATO)
				SELECT CAMPO, LEFT(DATO_DEFAULT,ISNULL(LONGITUD,0)) DATO 
				FROM RESCAMPOS
				WHERE CODRES=@CODRES AND COALESCE(DATO_DEFAULT,'')<>''

				SELECT @FIX=1, @FIX_TO=COUNT(1) FROM @TABLE

				WHILE @FIX <= @FIX_TO
				BEGIN
					SELECT @CAMPO=CAMPO, @DATO=DATO FROM @TABLE WHERE ID=@FIX
					SET @FECHA= CASE WHEN ( @IPS='ASOCA' OR  @IPS='HNSP' OR @IPS='ALBA')THEN NULL ELSE @FECHA END
					EXEC SPK_ACTUALIZA_RESAFI4505 @ID, @CAMPO, @FECHA, @DATO, NULL
					--@FECHA, @DATO, NULL
					SET @FIX += 1
				END
			END
			ELSE
			BEGIN
            IF (@IPS='ASOCA' OR @IPS='HNSP'  OR @IPS='ALBA')
            BEGIN
				   INSERT INTO RESAFI4505 (PERIODO, IDAFILIADO, IDTERCERO, REGIMEN, GESTACION, FECHAPROBPARTO, CONTROLPRENAT1VEZ)
				   SELECT @PERIODO, IDAFILIADO, @IDTERCERO, @REGIMEN, GESTACION, FECHAPROBPARTO, CONTROLPRENAT1VEZ
				   FROM  RESAFI4505
				   WHERE IDRESAFI4505 = @ID
				
				   SET @ID=@@IDENTITY
               
				   INSERT INTO @TABLE (CAMPO, DATO)
				   SELECT CAMPO, LEFT(DATO_DEFAULT,ISNULL(LONGITUD,0)) DATO 
				   FROM RESCAMPOS
				   WHERE CODRES=@CODRES AND COALESCE(DATO_DEFAULT,'')<>''
                  --AND CAMPO NOT IN ('014','033','056')

				   SELECT @FIX=1, @FIX_TO=COUNT(1) FROM @TABLE
               
				   WHILE @FIX <= @FIX_TO
				   BEGIN
				   	SELECT @CAMPO=CAMPO, @DATO=DATO FROM @TABLE WHERE ID=@FIX
				   	EXEC SPK_ACTUALIZA_RESAFI4505 @ID, @CAMPO,  NULL, @DATO, NULL
					--@FECHA, @DATO, NULL
				   	SET @FIX += 1
				   END
            END
            ELSE
            BEGIN
				   INSERT INTO RESAFI4505 (
					   PERIODO, IDAFILIADO, IDTERCERO, REGIMEN, GESTACION, SIFILISGESTCONG, HIPERINDUGEST, HIPOTIROIDISMOCONGE, SINTOMATICORESP, 
					   TUBERCULOSISMULTIDROGORES, LEPAR, OBEDESNUTPROT, VICMALTRATO, VICVIOSEX, INFTRANMISEXUAL, ENFERMENTAL, CANCERCERVIX,
					   CANCERSENO, FLUOROSISDENTAL, FECHAPESO, PESO, FECHATALLA, TALLA, FECHAPROBPARTO, EDADGESTNACER, BCG, HEPATITISBMEN1ANO,
					   PENTAVALENTE, POLIO, DPTMEN5ANOS, ROTAVIRUS, NEUMOCOCO, INFLUENZANINOS, FIEBREAMARILLA1ANO, HEPATITISA, TRIPLEVIRALNINOS,
					   VPH, TDTTMUJER1549, CONTROLPLACABACTERIANA, FECHATENCIONPARTOCESAR, FECHASALIDAPARTOCES, FECHACONSEJLACMATERNA, CONTROLRECIENNACIDO,
					   PLANIFIFAMILIAR1VEZ, SUMINISTROMETODOANTICONC, FECHASUMMETANTICONCEP, CONTROLPRENAT1VEZ, CONTROLPRENATAL, ULTIMOCONTROLPRENATAL,
					   SUMINACIFOLICOULTCONTPRENAT, SUMSULFFERROSOULTCONTPREN, SUMCARBCALCIO, VALAGUDEZAVISUAL, CONSULTOFALMOLOGIA, FECHADXDESNUT,
					   CONSMUJMENORVICMALTRATO, CONSVICTVIOSEXUAL, CONSNUTRICION, CONSULTAPSICOLOGIA, CONSCRECYDESA1VEZ, SULFERROSOMENOR10,
					   VITAMINAAMENOR10, CONSJOVEN1VEZ, CONSADULTA1VEZ, PRESERVITS, ASEPRETESTVIH ,ASEPSTELISAVIH, DXANSIEDAD, FECHAANTIGHEPAB,
					   RESANTGHEPBDEST, FECSEROLOGSIFILIS, RESSERSIF, FECTOMAELISAVIH, RESELISAVIH, FECTSHNEO, RESTSHNEO, TAMISCANCERCUELLO,
					   CITOLCERVUTER, CITOBETHESDA, CALIDADMUESTRACITO, IPSCITO, FECCOLPOSCOPIA, IPSCOLPOSCOPIA, FECBIOPSIACERVICAL, RESBIOPSIACERVICAL,
					   IPSBIOPSIACERVIAL, FECMAMOGRAFI, RESMAMOGRAFIA, IPSMAMOGRAFIA, FECTOMABACAF, FECRESULTBACAF, BIOPSIABACAF, IPSBACAF, FECTOMAHEMOGLOBINA,
					   HEMOGLOBINA, FECTOMAGLICEMIABASAL, FECCREATININA, CREATININA, FECHEMOGLICOSILADA, HEMOGLOBINAGLICOSILADA, FECTOMAMICROALBUMINA,
					   FECTOMAHDL, FECTOMABACILODX, BACILOSCOPIADEDX, TRATHIPOTIROIDISMOCONGE, TRATSIFILISGEST, TRATSIFILISCONG, TRATLEPRA, 
					   FECTERMTRATLESHMANIASIS)
				   SELECT 
					   @PERIODO, IDAFILIADO, @IDTERCERO, @REGIMEN, GESTACION, SIFILISGESTCONG, HIPERINDUGEST, HIPOTIROIDISMOCONGE, SINTOMATICORESP, 
					   TUBERCULOSISMULTIDROGORES, LEPAR, OBEDESNUTPROT, VICMALTRATO, VICVIOSEX, INFTRANMISEXUAL, ENFERMENTAL, CANCERCERVIX,
					   CANCERSENO, FLUOROSISDENTAL, FECHAPESO, PESO, FECHATALLA, TALLA, FECHAPROBPARTO, EDADGESTNACER, BCG, HEPATITISBMEN1ANO,
					   PENTAVALENTE, POLIO, DPTMEN5ANOS, ROTAVIRUS, NEUMOCOCO, INFLUENZANINOS, FIEBREAMARILLA1ANO, HEPATITISA, TRIPLEVIRALNINOS,
					   VPH, TDTTMUJER1549, CONTROLPLACABACTERIANA, FECHATENCIONPARTOCESAR, FECHASALIDAPARTOCES, FECHACONSEJLACMATERNA, CONTROLRECIENNACIDO,
					   PLANIFIFAMILIAR1VEZ, SUMINISTROMETODOANTICONC, FECHASUMMETANTICONCEP, CONTROLPRENAT1VEZ, CONTROLPRENATAL, ULTIMOCONTROLPRENATAL,
					   SUMINACIFOLICOULTCONTPRENAT, SUMSULFFERROSOULTCONTPREN, SUMCARBCALCIO, VALAGUDEZAVISUAL, CONSULTOFALMOLOGIA, FECHADXDESNUT,
					   CONSMUJMENORVICMALTRATO, CONSVICTVIOSEXUAL, CONSNUTRICION, CONSULTAPSICOLOGIA, CONSCRECYDESA1VEZ, SULFERROSOMENOR10,
					   VITAMINAAMENOR10, CONSJOVEN1VEZ, CONSADULTA1VEZ, PRESERVITS, ASEPRETESTVIH ,ASEPSTELISAVIH, DXANSIEDAD, FECHAANTIGHEPAB,
					   RESANTGHEPBDEST, FECSEROLOGSIFILIS, RESSERSIF, FECTOMAELISAVIH, RESELISAVIH, FECTSHNEO, RESTSHNEO, TAMISCANCERCUELLO,
					   CITOLCERVUTER, CITOBETHESDA, CALIDADMUESTRACITO, IPSCITO, FECCOLPOSCOPIA, IPSCOLPOSCOPIA, FECBIOPSIACERVICAL, RESBIOPSIACERVICAL,
					   IPSBIOPSIACERVIAL, FECMAMOGRAFI, RESMAMOGRAFIA, IPSMAMOGRAFIA, FECTOMABACAF, FECRESULTBACAF, BIOPSIABACAF, IPSBACAF, FECTOMAHEMOGLOBINA,
					   HEMOGLOBINA, FECTOMAGLICEMIABASAL, FECCREATININA, CREATININA, FECHEMOGLICOSILADA, HEMOGLOBINAGLICOSILADA, FECTOMAMICROALBUMINA,
					   FECTOMAHDL, FECTOMABACILODX, BACILOSCOPIADEDX, TRATHIPOTIROIDISMOCONGE, TRATSIFILISGEST, TRATSIFILISCONG, TRATLEPRA, 
					   FECTERMTRATLESHMANIASIS
				   FROM  RESAFI4505
				   WHERE IDRESAFI4505 = @ID
				END
				SET @ID=@@IDENTITY
			END
		END
		ELSE
		BEGIN
			UPDATE RESAFI4505 SET REGIMEN=@REGIMEN WHERE IDRESAFI4505=@ID AND COALESCE(REGIMEN,'')<>@REGIMEN
		END
	END
END



