   DECLARE @SERA INT
   SELECT @SERA = 1
   DECLARE @CNSCXC1 VARCHAR(20)
   DECLARE G_C CURSOR FOR    
   SELECT CNSCXC FROM FCXC WHERE CNSCXC > '0400000133'
   OPEN G_C    
   FETCH NEXT FROM G_C    
   INTO @CNSCXC1
   WHILE @@FETCH_STATUS = 0    
   BEGIN            
      EXEC SPK_RELIQUIDACXCQX @CNSCXC1
      PRINT '@CNSCXC1 RECALCULADA='+@CNSCXC1
      SELECT @SERA = @SERA +1
      IF @SERA = 2000
      BEGIN
         BREAK
      END
      FETCH NEXT FROM G_C
      INTO @CNSCXC1
   END
   CLOSE G_C    
   DEALLOCATE G_C

   