SELECT SUM(HPRED.CANTIDAD) FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
WHERE  HPRE.NOADMISION = '0100005487' AND    HPRED.IDSERVICIO = 'MEDPOS00006'
--SELECT * FROM SER WHERE DESCSERVICIO LIKE '%ENOXA%'
SELECT IMOV.IDTIPOMOV, SUM(IMOVH.CANTIDAD)
FROM   IMOVH INNER JOIN IMOV ON IMOVH.CNSMOV = IMOV.CNSMOV 
WHERE  NODOCUMENTO = '0100005487' AND    IMOV.ESTADO = 1
AND    IDARTICULO  = 'MEDPOS00006'
GROUP BY IMOV.IDTIPOMOV

SELECT HPRED.* FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
WHERE  HPRE.NOADMISION  = '0100005487'
AND    HPRED.IDSERVICIO = 'MEDPOS00006'
ORDER BY HPRED.NOPRESTACION

DELETE HPRED WHERE NOPRESTACION = '0100156031' AND NOITEM IN (2)
--UPDATE HPRED SET CANTIDAD = 2 WHERE NOPRESTACION = '0100155457' AND NOITEM = 14

DECLARE @VT DECIMAL(14,2) DECLARE @VE DECIMAL(14,2) DECLARE @VC DECIMAL(14,2) DECLARE @VP DECIMAL(14,2)
SELECT @VT = SUM(HPRED.VALOR * HPRED.CANTIDAD), @VE = SUM(HPRED.VALOREXCEDENTE), @VC = SUM(HPRED.VALORCOPAGO), @VP = SUM(HPRED.VALORPCOMP)
FROM   HPRED WHERE  HPRED.NOPRESTACION = '0100156031'
   
UPDATE HPRE SET VALORTOTAL  = @VT,VALOREXEDENTE = @VE, VALORCOPAGO = @VC,VALORPCOMP    = @VP 
WHERE HPRE.NOPRESTACION = '0100156031'

--------------------------------------------------------------------------------------------------------
SELECT * 
FROM   HPRE
WHERE  HPRE.NOADMISION = '0100005487'
AND    NOT EXISTS (SELECT * FROM HPRED WHERE HPRED.NOPRESTACION = HPRE.NOPRESTACION)

DELETE HPRE WHERE NOPRESTACION = '0100155259'
DELETE HPRE WHERE NOPRESTACION = '0100154627'



SELECT CANTIDAD, FRECUENCIA, DURACION, * 
FROM   HCATD INNER JOIN HCA ON HCATD.CONSECUTIVO = HCA.CONSECUTIVO 
WHERE  NOADMISION = '0100005568'
AND    IDSERVICIO = 'MEDNOPOS261'


FNVALORVARIABLE('MAXDURACIONOM')