SELECT C.N_FACTURA, C.VLR_CARGOS, F.VLR_FACTURADO, P.VLR_PAGAR, (C.VLR_CARGOS - P.VLR_PAGAR) DIF_CARGOS_CXP
FROM   (
         SELECT N_FACTURA, SUM(VALOREXCEDENTE) VLR_CARGOS 
         FROM   HPRED 
         WHERE  IDPROVEEDOR = 'J298729147'  
         AND    N_FACTURA IN (SELECT N_FACTURA FROM FTR WHERE ESTADO <> 'A' AND COALESCE(TIPOANULACION,'') <> 'NC')
         GROUP  BY N_FACTURA
       ) C LEFT JOIN (      
                        SELECT N_FACTURA, SUM(VLR_SERVICI) VLR_FACTURADO 
                        FROM   FTRD 
                        WHERE  IDPROVEEDOR = 'J298729147'  
                        AND    N_FACTURA IN (SELECT N_FACTURA FROM FTR WHERE ESTADO <> 'A' AND COALESCE(TIPOANULACION,'') <> 'NC')
                        GROUP  BY N_FACTURA
                      ) F ON C.N_FACTURA = F.N_FACTURA
           LEFT JOIN ( SELECT N_FACTURA, CAST (SUM(VR_TOTAL) AS DECIMAL(14,2)) VLR_PAGAR 
                        FROM   FXPD 
                        WHERE  IDTERCERO = 'J298729147'
                        AND    N_FACTURA IN (SELECT N_FACTURA FROM FTR WHERE ESTADO <> 'A' AND COALESCE(TIPOANULACION,'') <> 'NC')
                        GROUP  BY N_FACTURA
                      ) P ON C.N_FACTURA = P.N_FACTURA