DROP TABLE FTR_INSPECTOR 
GO
CREATE TABLE DBO.FTR_INSPECTOR (CNSFCT VARCHAR(40), N_FACTURA VARCHAR(16), SYS_COMPUTERNAME VARCHAR(254), FECHA DATETIME)
GO
 
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_FTR_INSPECTOR' AND TYPE = 'TR')
   DROP TRIGGER TK_FTR_INSPECTOR
GO
CREATE TRIGGER DBO.TK_FTR_INSPECTOR
ON FTR
FOR INSERT, UPDATE
AS 
  DECLARE @VT_DET DECIMAL(14,2)
  DECLARE @NF VARCHAR(16)

  IF UPDATE(VR_TOTAL) 
  BEGIN
     
     SELECT @VT_DET = SUM(VR_TOTAL) 
     FROM   FTRD 
     WHERE  CNSFTR = (SELECT INSERTED.CNSFCT FROM INSERTED)
     
     IF (SELECT INSERTED.VR_TOTAL FROM INSERTED ) <> @VT_DET
     BEGIN
        SELECT @nf = N_FACTURA FROM INSERTED
  	     INSERT INTO FTR_INSPECTOR 
  	     SELECT INSERTED.CNSFCT, INSERTED.N_FACTURA, HOST_NAME(), GETDATE()
  	     FROM   INSERTED  
  	        	
  	     RAISERROR(N'SE ESTA DAÑANDO EL VALOR TOTAL DE LA FACTURA. %s',10,1,@NF)
     END
  END
GO
