SELECT * FROM IMOVH WHERE CNSMOV = '0100141316' ORDER BY IDARTICULO
SELECT * FROM IMOV WHERE CNSMOV = '0100141316' 


SELECT DBO.FNK_VALORVARIABLE('IDINV_HTX_ENT_UNICA')

SELECT CNSDIRINV, IART.IDITAR, HTX.CANTIDADINV, HTX.IDSERVICIO, HTX.NOADMISION, HTX.CNSMOV, HTX.* FROM HTX INNER JOIN SER ON HTX.IDSERVICIO = SER.IDSERVICIO
                             INNER JOIN IART ON SER.IDARTICULO = IART.IDARTICULO 
WHERE CNSHTX IN ('0100279540','0100279541','0100279542','0100279543','0100279544','0100279545','0100279546','0100279547','0100279548','0100279549','0100279550')





     SELECT '@NVOCONSEC', SER.IDARTICULO, IART.EXISTOTAL, 0, 
             SUM(CASE COALESCE(SER.MDOSIF,0) WHEN 1 THEN HTX.CANTIDADINV
                                             ELSE HTX.CANTIDAD
                 END), 
             IART.PCOSTO,  
             'CNSHTX', NULL ,0, NULL, NULL, NULL, NULL, NULL, 0, 
             '@USUARIO', NULL, NULL, 0, NULL, NULL, NULL, 0, IART.IDITAR--, HTX.CNSHTX
      FROM   HTX INNER JOIN SER ON HTX.IDSERVICIO   = SER.IDSERVICIO , IART 
      WHERE  HTX.CNSDIRINV = '0100095723' --AND ISNULL(HTX.MARCAINV,0) = 1 AND ISNULL(HTX.SOLICITADO,0) = 0 AND ISNULL(HTX.CNSMOV,'') = ''
           --AND    HTX.HOST_MPEDINV = @USUARIO
      AND    HTX.CLASEHTX     = 'NE'
      AND    SER.IDARTICULO   <> '' 
      AND    SER.IDARTICULO   <> 'NA'
      AND    SER.IDARTICULO   = IART.IDARTICULO
      AND    HTX.CNSHTX       = CASE WHEN COALESCE(HTX.MDOSIF,0) = 0 THEN  HTX.CNSHTX
                                     WHEN COALESCE(HTX.MDOSIF,0) = 1 THEN  CASE WHEN COALESCE(HTX.CANTIDADINV,0) > 0 THEN HTX.CNSHTX
                                                                                ELSE 'KRYSTALOS9('
                                                                           END
                                END      
      AND    IART.IDITAR     = CASE WHEN DBO.FNK_VALORVARIABLE('IDINV_HTX_ENT_UNICA') = 'SI' THEN IART.IDITAR ELSE '01' END     
      GROUP BY SER.IDARTICULO, IART.EXISTOTAL, IART.PCOSTO, HTX.IDSERVICIO, IART.IDITAR

BEGIN TRAN  ROLLBACK COMMIT
DELETE ISAL  WHERE CNSMOV =  '0100141316'
DELETE IMOVH WHERE CNSMOV =  '0100141316'
DELETE IMOV WHERE CNSMOV =  '0100141316'
UPDATE HTX SET HTX.MARCAINV = 1, HTX.SOLICITADO = 0, HTX.CNSMOV = '' WHERE CNSDIRINV = '0100095699'

EXEC SPK_PEDIDOINVHTX '0100005360', '01', '01', 'LPORTO', 'UCI1'

SELECT CNSMOV, CANTIDADINV, * FROM HTX WHERE CNSDIRINV = '0100095699'
SELECT * FROM IMOVH WHERE CNSMOV = '0100141567' ORDER BY IDARTICULO


BEGIN TRAN  
DECLARE @CNSMOV VARCHAR(20), @CNSDIRINV VARCHAR(20), @NOADMISION VARCHAR(16)
DECLARE P_C CURSOR FOR  
SELECT DISTINCT CNSDIRINV, CNSMOV, NOADMISION FROM HTX
WHERE  CNSMOV IN (
                  SELECT CNSMOV FROM IMOV
                  WHERE  ESTADO = 0 
                  AND    EXISTS (SELECT IMOVH.CNSMOV, IMOVH.IDARTICULO, COUNT(*) FROM IMOVH 
                                 WHERE  IMOV.CNSMOV = IMOVH.CNSMOV
                                 GROUP BY IMOVH.CNSMOV, IMOVH.IDARTICULO
                                 HAVING COUNT(*) > 1)
                  AND   IMOV.FECHAMOV >= '18/09/2013'
                  --ORDER BY CNSMOV
                  )
OPEN P_C  
FETCH NEXT FROM P_C
INTO @CNSDIRINV, @CNSMOV, @NOADMISION 
WHILE @@FETCH_STATUS = 0  
BEGIN  
   DELETE ISAL  WHERE CNSMOV =  @CNSMOV
   DELETE IMOVH WHERE CNSMOV =  @CNSMOV
   DELETE IMOV WHERE CNSMOV =   @CNSMOV
   UPDATE HTX SET HTX.MARCAINV = 1, HTX.SOLICITADO = 0, HTX.CNSMOV = '' WHERE CNSDIRINV = @CNSDIRINV
   EXEC SPK_PEDIDOINVHTX @NOADMISION, '01', '01', 'LPORTO', 'UCI1'
   FETCH NEXT FROM P_C
   INTO @CNSDIRINV, @CNSMOV, @NOADMISION 
END
CLOSE P_C
DEALLOCATE P_C
COMMIT ROLLBACK


SELECT * FROM HTX WHERE CNSDIRINV = '0100095699'