IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFTR' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFTR
GO 
CREATE TRIGGER DBO.TK_PROCESOFTR
ON FTR
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOHADM' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOHADM
GO 
CREATE TRIGGER DBO.TK_PROCESOHADM
ON HADM
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOHPRE' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOHPRE
GO 
CREATE TRIGGER DBO.TK_PROCESOHPRE
ON HPRE
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOHPRED' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOHPRED
GO 
CREATE TRIGGER DBO.TK_PROCESOHPRED
ON HPRED
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOAUT' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOAUT
GO 
CREATE TRIGGER DBO.TK_PROCESOAUT
ON AUT
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOAUTD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOAUTD
GO 
CREATE TRIGGER DBO.TK_PROCESOAUTD
ON AUTD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOMCP' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOMCP
GO 
CREATE TRIGGER DBO.TK_PROCESOMCP
ON MCP
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOMCH' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOMCH
GO 
CREATE TRIGGER DBO.TK_PROCESOMCH
ON MCH
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOHCA' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOHCA
GO 
CREATE TRIGGER DBO.TK_PROCESOHCA
ON HCA
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOHCAD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOHCAD
GO 
CREATE TRIGGER DBO.TK_PROCESOHCAD
ON HCAD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION

END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOLING' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOLING
GO 
CREATE TRIGGER DBO.TK_PROCESOLING
ON LING
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOLORD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOLORD
GO 
CREATE TRIGGER DBO.TK_PROCESOLORD
ON LORD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOLORDD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOLORDD
GO 
CREATE TRIGGER DBO.TK_PROCESOLORDD
ON LORDD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFTRD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFTRD
GO 
CREATE TRIGGER DBO.TK_PROCESOFTRD
ON FTRD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFCJ' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFCJ
GO 
CREATE TRIGGER DBO.TK_PROCESOFCJ
ON FCJ
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFCJD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFCJD
GO 
CREATE TRIGGER DBO.TK_PROCESOFCJD
ON FCJD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOPCJ' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOPCJ
GO 
CREATE TRIGGER DBO.TK_PROCESOPCJ
ON PCJ
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFCXP' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFCXP
GO 
CREATE TRIGGER DBO.TK_PROCESOFCXP
ON FCXP
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFCXPD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFCXPD
GO 
CREATE TRIGGER DBO.TK_PROCESOFCXPD
ON FCXPD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOIMOV' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOIMOV
GO 
CREATE TRIGGER DBO.TK_PROCESOIMOV
ON IMOV
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOIMOVH' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOIMOVH
GO 
CREATE TRIGGER DBO.TK_PROCESOIMOVH
ON IMOVH
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOITRA' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOITRA
GO 
CREATE TRIGGER DBO.TK_PROCESOITRA
ON ITRA
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOITRAH' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOITRAH
GO 
CREATE TRIGGER DBO.TK_PROCESOITRAH
ON ITRAH
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOSER' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOSER
GO 
CREATE TRIGGER DBO.TK_PROCESOSER
ON SER
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOTAR' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOTAR
GO 
CREATE TRIGGER DBO.TK_PROCESOTAR
ON TAR
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOTARD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOTARD
GO 
CREATE TRIGGER DBO.TK_PROCESOTARD
ON TARD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOTARDV' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOTARDV
GO 
CREATE TRIGGER DBO.TK_PROCESOTARDV
ON TARDV
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOTER' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOTER
GO 
CREATE TRIGGER DBO.TK_PROCESOTER
ON TER
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOTEXCA' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOTEXCA
GO 
CREATE TRIGGER DBO.TK_PROCESOTEXCA
ON TEXCA
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOCUE' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOCUE
GO 
CREATE TRIGGER DBO.TK_PROCESOCUE
ON CUE
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOKMCOM' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOKMCOM
GO 
CREATE TRIGGER DBO.TK_PROCESOKMCOM
ON KMCOM
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOCPPAF' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOCPPAF
GO 
CREATE TRIGGER DBO.TK_PROCESOCPPAF
ON CPPAF
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOCIT' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOCIT
GO 
CREATE TRIGGER DBO.TK_PROCESOCIT
ON CIT
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_AFI_IDAFILIADO' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_AFI_IDAFILIADO
GO 
CREATE TRIGGER DBO.TK_AFI_IDAFILIADO
ON AFI
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO  

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOAFI' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOAFI
GO 
CREATE TRIGGER DBO.TK_PROCESOAFI
ON AFI
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
------------------------------
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFNOT' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFNOT
GO 
CREATE TRIGGER DBO.TK_PROCESOFNOT
ON FNOT
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO 
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFNOTD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFNOTD
GO 
CREATE TRIGGER DBO.TK_PROCESOFNOTD
ON FNOTD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFCXC' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFCXC
GO 
CREATE TRIGGER DBO.TK_PROCESOFCXC
ON FCXC
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFCXCD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFCXCD
GO 
CREATE TRIGGER DBO.TK_PROCESOFCXCD
ON FCXCD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFCXCDV' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFCXCDV
GO 
CREATE TRIGGER DBO.TK_PROCESOFCXCDV
ON FCXCDV
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFGLO' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFGLO
GO 
CREATE TRIGGER DBO.TK_PROCESOFGLO
ON FGLO
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOFPAG' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOFPAG
GO 
CREATE TRIGGER DBO.TK_PROCESOFPAG
ON FPAG
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOHADMAD' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOHADMAD
GO 
CREATE TRIGGER DBO.TK_PROCESOHADMAD
ON HADMAD
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PROCESOHADMDX' AND TYPE = 'TR')
   DROP TRIGGER DBO.TK_PROCESOHADMDX
GO 
CREATE TRIGGER DBO.TK_PROCESOHADMDX
ON HADMDX
WITH ENCRYPTION
FOR INSERT, UPDATE, DELETE
AS
DECLARE @FECHA AS DATETIME
SELECT @FECHA = GETDATE()
IF @FECHA > '20100701 12:00:00'
BEGIN
   RAISERROR ('SU LICENCIA DE KRYSTALOS HA EXPIRADO. (57 1 3350808) ', 16, 1)
   ROLLBACK TRANSACTION
END
GO