SELECT COM.COMPROBANTE, X.CUENTA, X.NOMCUENTA, COM.NOMCOMPROBANTE, 
       DEBITOS=SUM(CASE WHEN MCH.TIPO='DB' THEN VALOR ELSE 0 END), 
       CREDITOS=SUM(CASE WHEN MCH.TIPO='CR' THEN VALOR ELSE 0 END), 
       X.NIVEL 
FROM   COM INNER JOIN MCP ON COM.COMPROBANTE=MCP.COMPROBANTE AND COM.COMPANIA=MCP.COMPANIA 
           INNER JOIN MCH ON MCP.COMPANIA=MCH.COMPANIA AND MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE 
           INNER JOIN FNK_GENEALOGICO_CUE('01') X ON MCH.CUENTA = X.CUENTA_DETALLE 
WHERE  MCP.ESTADO   = 2 AND ISNULL(MCP.ANULADO,0)=0 
AND    MCP.COMPANIA = '01' 
AND    MCP.ANO      = '2011' 
AND    MCP.MES      = 12 
AND    MCH.CUENTA>='1'  
AND    MCH.CUENTA<='99999999999999' 
AND    X.NIVEL BETWEEN 2 AND 3
GROUP BY COM.COMPROBANTE, X.CUENTA, X.NOMCUENTA, COM.NOMCOMPROBANTE, X.NIVEL 
ORDER BY COM.COMPROBANTE, X.CUENTA 

SELECT X.COMPROBANTE, SUM(X.DEBITOS), SUM(X.CREDITOS)
FROM  (
         SELECT MCP.COMPROBANTE, MCH.CUENTA,
                DEBITOS=SUM(CASE WHEN MCH.TIPO='DB' THEN VALOR ELSE 0 END), 
                CREDITOS=SUM(CASE WHEN MCH.TIPO='CR' THEN VALOR ELSE 0 END)
         FROM   MCP INNER JOIN MCH ON MCP.COMPANIA=MCH.COMPANIA AND MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE 
         WHERE  MCP.ESTADO   = 2 AND ISNULL(MCP.ANULADO,0)=0 
         AND    MCP.COMPANIA = '01' 
         AND    MCP.ANO      = '2011' 
         AND    MCP.MES      = 3
         GROUP BY MCP.COMPROBANTE, MCH.CUENTA
         --ORDER BY MCP.COMPROBANTE, MCH.CUENTA
      ) X
GROUP BY X.COMPROBANTE
HAVING SUM(X.DEBITOS) <> SUM(X.CREDITOS)
ORDER BY X.COMPROBANTE

SELECT 3314504678.90 - 3316527457.92

SELECT SUM(DB), SUM(CR) FROM SALDOMESTERFAC WHERE ANO = '2011' AND MES = 3

SELECT MCH.CUENTA, SDMTF.CUENTA, MCH.DEBITOS, SDMTF.DB, MCH.CREDITOS, SDMTF.CR
FROM   (
         SELECT MCH.CUENTA, DEBITOS=SUM(CASE WHEN MCH.TIPO='DB' THEN VALOR ELSE 0 END), 
                CREDITOS=SUM(CASE WHEN MCH.TIPO='CR' THEN VALOR ELSE 0 END)
         FROM   MCP INNER JOIN MCH ON MCP.COMPANIA=MCH.COMPANIA AND MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE 
         WHERE  MCP.ESTADO   = 2 AND ISNULL(MCP.ANULADO,0)=0 
         AND    MCP.ANO      = '2011' 
         AND    MCP.MES      = 4
         GROUP BY MCH.CUENTA
        ) MCH LEFT JOIN (
                           SELECT CUENTA, SUM(DB) DB, SUM(CR) CR
                           FROM   SALDOMESTERFAC 
                           WHERE  ANO = '2011' 
                           AND    MES = 4
                           GROUP BY CUENTA
                         ) SDMTF ON MCH.CUENTA = SDMTF.CUENTA
WHERE DEBITOS <> DB
OR    CREDITOS <> CR
ORDER BY MCH.CUENTA

SELECT * 
FROM   MCH INNER JOIN MCP ON MCP.COMPANIA=MCH.COMPANIA 
                         AND MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE 
WHERE  MCH.CUENTA = '13050605' AND TIPO = 'CR'
AND    ANO = '2011'
AND    MES = 3

SELECT MCH.NROCOMPROBANTE, SUM(CASE TIPO WHEN 'DB' THEN VALOR ELSE 0 END) DB, 
                           SUM(CASE TIPO WHEN 'CR' THEN VALOR ELSE 0 END) CR 
FROM   MCH INNER JOIN (
                        SELECT DISTINCT MCP.NROCOMPROBANTE
                        FROM   MCH INNER JOIN MCP ON MCP.COMPANIA=MCH.COMPANIA 
                                                 AND MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE 
                        WHERE  MCH.CUENTA = '13050605' AND TIPO = 'CR'
                        AND    ANO = '2011'
                        AND    MES = 3 ) X ON MCH.NROCOMPROBANTE = X.NROCOMPROBANTE
GROUP BY MCH.NROCOMPROBANTE
HAVING SUM(CASE TIPO WHEN 'DB' THEN VALOR ELSE 0 END) <> SUM(CASE TIPO WHEN 'CR' THEN VALOR ELSE 0 END) 


SELECT * FROM MCP  WHERE NROCOMPROBANTE = '0100288266'
SELECT SUM(CASE TIPO WHEN 'DB' THEN VALOR ELSE 0 END) DB, SUM(CASE TIPO WHEN 'CR' THEN VALOR ELSE 0 END) CR FROM MCH WHERE NROCOMPROBANTE = '0100288266'

SELECT MCH.* 
FROM   MCH INNER JOIN MCP ON MCP.COMPANIA=MCH.COMPANIA 
                         AND MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE 
WHERE  MCH.TIPO = 'CR'
AND    ANO = '2011'
AND    MES = 3
AND    MCH.NROCOMPROBANTE = '0100288266'

SELECT * INTO MCH_CORR FROM MCH WHERE NROCOMPROBANTE = '0100288266'
INSERT INTO MCH_CORR (NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, 
                      N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO,
                      PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG, CODPRG, ERROR, IDOPERACION, FECHACONCILIACION,
                      IDPROVEEDOR, ENPRESUPUESTO, ESTADOIMP)
SELECT NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, 
                      N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO,
                      PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP, CODUNG, CODPRG, ERROR, IDOPERACION, FECHACONCILIACION,
                      IDPROVEEDOR, ENPRESUPUESTO, ESTADOIMP
FROM MCH WHERE NROASIENTO IN (11571994,11571996)

select * from MCH_CORR WHERE NROCOMPROBANTE = '0101204619'

ALTER TABLE MCH DISABLE TRIGGER ALL
BEGIN TRAN
DELETE MCH WHERE NROASIENTO IN (6106703, 6106699)
DELETE MCH WHERE NROASIENTO IN (6330495, 6330498)
DELETE MCH WHERE NROASIENTO IN (7127885, 7127891)
DELETE MCH WHERE NROASIENTO IN (7456359, 7680473, 7680481, 7680480)
DELETE MCH WHERE NROASIENTO IN (8798519,8394540)
DELETE MCH WHERE NROASIENTO IN (7680466, 7680464, 7680472, 7680471)
DELETE MCH WHERE NROASIENTO IN (8201210)
DELETE MCH WHERE NROASIENTO IN (7971492)
DELETE MCH WHERE NROASIENTO IN (8796159, 8798527, 8798534, 8798537, 8798535, 8589477, 8612638, 8589474, 8579309, 8585700)
DELETE MCH WHERE NROASIENTO IN (8798523, 8798525)
DELETE MCH WHERE NROASIENTO IN (8796138, 8798524)
DELETE MCH WHERE NROASIENTO IN (8572577)
DELETE MCH WHERE NROASIENTO IN (8575253)
UPDATE MCH SET VALOR = VALOR -16 WHERE NROASIENTO = 8652648
DELETE MCH WHERE NROASIENTO IN (10536244, 10347159)
DELETE MCH WHERE NROASIENTO IN (11571994,11571996)
ROLLBACK
COMMIT




SELECT MCH.NROCOMPROBANTE, SUM(CASE TIPO WHEN 'DB' THEN VALOR ELSE 0 END) DB, 
                           SUM(CASE TIPO WHEN 'CR' THEN VALOR ELSE 0 END) CR 
FROM   MCH INNER JOIN MCP ON MCP.COMPANIA=MCH.COMPANIA 
                         AND MCP.NROCOMPROBANTE=MCH.NROCOMPROBANTE 
AND    MCP.ANO = '2011'
AND    MCP.MES = 3 
AND    MCP.ESTADO   = 2 
AND    COALESCE(MCP.ANULADO,0)=0
GROUP BY MCH.NROCOMPROBANTE
HAVING SUM(CASE TIPO WHEN 'DB' THEN VALOR ELSE 0 END) <> SUM(CASE TIPO WHEN 'CR' THEN VALOR ELSE 0 END) 
