09   KrystalosIPSBOYACA    ---OK  MALO
33   KrystalosNuevaIPS     ---OK  OK
--
SELECT * FROM MCP WHERE FECHACONTABLE <= '01/09/2010'  --100777
SELECT * FROM kRYSTALOSipsboyaca.DBO.MCP WHERE  FECHACONTABLE <= '01/09/2010'                  --100791
-- 001
   ALTER TABLE MCH DISABLE TRIGGER ALL
   ALTER TABLE MCP DISABLE TRIGGER ALL
   ALTER TABLE SXT2008MA DISABLE TRIGGER ALL
   ALTER TABLE SAC DISABLE TRIGGER ALL
   --     SXT2008MA
   DELETE SXT2008MA WHERE ANO = '2010'
   --     SAC
   DELETE SAC WHERE ANO = '2010'
   -- ENERO
   DELETE MCH
   FROM   MCH INNER JOIN MCP ON MCH.NROCOMPROBANTE = MCP.NROCOMPROBANTE
   WHERE  MCP.FECHACONTABLE >= '01/01/2010'
   AND    MCP.FECHACONTABLE < '01/02/2010'
   --
   DELETE MCP
   WHERE  MCP.FECHACONTABLE >= '01/01/2010'
   AND    MCP.FECHACONTABLE < '01/02/2010'
   -- FEBRERO
   DELETE MCH
   FROM   MCH INNER JOIN MCP ON MCH.NROCOMPROBANTE = MCP.NROCOMPROBANTE
   WHERE  MCP.FECHACONTABLE >= '01/02/2010'
   AND    MCP.FECHACONTABLE < '01/03/2010'
   --
   DELETE MCP
   WHERE  MCP.FECHACONTABLE >= '01/02/2010'
   AND    MCP.FECHACONTABLE < '01/03/2010'
   -- MARZO
   DELETE MCH
   FROM   MCH INNER JOIN MCP ON MCH.NROCOMPROBANTE = MCP.NROCOMPROBANTE
   WHERE  MCP.FECHACONTABLE >= '01/03/2010'
   AND    MCP.FECHACONTABLE < '01/04/2010'
   --
   DELETE MCP
   WHERE  MCP.FECHACONTABLE >= '01/03/2010'
   AND    MCP.FECHACONTABLE < '01/04/2010'
   -- ABRIL
   DELETE MCH
   FROM   MCH INNER JOIN MCP ON MCH.NROCOMPROBANTE = MCP.NROCOMPROBANTE
   WHERE  MCP.FECHACONTABLE >= '01/04/2010'
   AND    MCP.FECHACONTABLE < '01/05/2010'
   --
   DELETE MCP
   WHERE  MCP.FECHACONTABLE >= '01/04/2010'
   AND    MCP.FECHACONTABLE < '01/05/2010'
   -- MAYO
   DELETE MCH
   FROM   MCH INNER JOIN MCP ON MCH.NROCOMPROBANTE = MCP.NROCOMPROBANTE
   WHERE  MCP.FECHACONTABLE >= '01/05/2010'
   AND    MCP.FECHACONTABLE < '01/06/2010'
   --
   DELETE MCP
   WHERE  MCP.FECHACONTABLE >= '01/05/2010'
   AND    MCP.FECHACONTABLE < '01/06/2010'-- JUNIO
   -- JUNIO
   DELETE MCH
   FROM   MCH INNER JOIN MCP ON MCH.NROCOMPROBANTE = MCP.NROCOMPROBANTE
   WHERE  MCP.FECHACONTABLE >= '01/06/2010'
   AND    MCP.FECHACONTABLE < '01/07/2010'
   --
   DELETE MCP
   WHERE  MCP.FECHACONTABLE >= '01/06/2010'
   AND    MCP.FECHACONTABLE < '01/07/2010'-- JUNIO-- AGOSTO
   -- JULIO
   DELETE MCH
   FROM   MCH INNER JOIN MCP ON MCH.NROCOMPROBANTE = MCP.NROCOMPROBANTE
   WHERE  MCP.FECHACONTABLE >= '01/07/2010'
   AND    MCP.FECHACONTABLE < '01/08/2010'
   --
   DELETE MCP
   WHERE  MCP.FECHACONTABLE >= '01/07/2010'
   AND    MCP.FECHACONTABLE < '01/08/2010'-- JUNIO-- AGOSTO
   -- AGOSTO
   DELETE MCH
   FROM   MCH INNER JOIN MCP ON MCH.NROCOMPROBANTE = MCP.NROCOMPROBANTE
   WHERE  MCP.FECHACONTABLE >= '01/08/2010'
   AND    MCP.FECHACONTABLE < '01/09/2010'
   --
   DELETE MCP
   WHERE  MCP.FECHACONTABLE >= '01/08/2010'
   AND    MCP.FECHACONTABLE < '01/09/2010'  
   -- 002 PROCEDENCIAS   
   SELECT PROCEDENCIA, COUNT(*) 
   FROM   MCP
   GROUP BY PROCEDENCIA
   /* SE ENCONTRARON ESTAS PROCEDENCIAS
      CAJA
      CAJAMENOR
      REVCAJAEGR
      REVCAJAING      
      FACTURA
      INV
      BMOV          
      CXC
      CXP     
      IACT
      NOTDBCR
      NOTDBCRCXP
      REVNOTDBCR
      RGLO      
      MANUAL
      NOMINA
   */
-- 003 PROCEDENCIA CAJA FCJ
   -- ENERO 
   -- COBRO
   UPDATE FCJ SET CONTABILIZADA = 0, NROCOMPROBANTE = NULL 
   WHERE  COALESCE(FCJ.DEAPERTURA,0) = 0
   AND    FCJ.ESTADO    <> 'A'
   AND    FCJ.CERRADA   =  1
   AND    FCJ.CLASE_FAC = 'COBRO'
   AND    FCJ.FECHA     >= '01/01/2010'
   AND    FCJ.FECHA     < '01/09/2010'
   -- PAGO
   UPDATE FCJ SET CONTABILIZADA = 0, NROCOMPROBANTE = NULL 
   WHERE  COALESCE(FCJ.DEAPERTURA,0) = 0
   AND    FCJ.ESTADO    <> 'A'
   AND    FCJ.CERRADA   =  1
   AND    FCJ.CLASE_FAC = 'PAGO'
   AND    FCJ.FECHA     >= '01/01/2010'
   AND    FCJ.FECHA     < '01/09/2010'   
   -- CONTABILIZACION
   EXEC SPKH_CONTABILIZA_PROC_FECHAS 'CAJA', '01/01/2010', '01/02/2010', 'TATIANAG', 'IPSBOYACA', '01', '01'
   --
   EXEC SPKH_CONTABILIZA_PROC_FECHAS 'CAJA', '01/02/2010', '01/03/2010', 'TATIANAG', 'IPSBOYACA', '01', '01'
   --
   EXEC SPKH_CONTABILIZA_PROC_FECHAS 'CAJA', '01/03/2010', '01/04/2010', 'TATIANAG', 'IPSBOYACA', '01', '01'
   --
   EXEC SPKH_CONTABILIZA_PROC_FECHAS 'CAJA', '01/04/2010', '01/05/2010', 'TATIANAG', 'IPSBOYACA', '01', '01'
   --
   EXEC SPKH_CONTABILIZA_PROC_FECHAS 'CAJA', '01/05/2010', '01/06/2010', 'TATIANAG', 'IPSBOYACA', '01', '01'
   --
   EXEC SPKH_CONTABILIZA_PROC_FECHAS 'CAJA', '01/06/2010', '01/07/2010', 'TATIANAG', 'IPSBOYACA', '01', '01'
   --
   EXEC SPKH_CONTABILIZA_PROC_FECHAS 'CAJA', '01/07/2010', '01/08/2010', 'TATIANAG', 'IPSBOYACA', '01', '01'
   --
-- FACTURAS
   --
   UPDATE FTR SET CONTABILIZADA = 0, MARCACONT = 0, NROCOMPROBANTE = NULL 
   WHERE  F_FACTURA >= '01/01/2010' 
   AND    F_FACTURA <  '01/09/2010'
   --
   UPDATE FTR SET MARCACONT =1 
   WHERE  F_FACTURA >= '01/01/2010' 
   AND F_FACTURA     < '01/09/2010' 
   --
   EXEC SPK_CONTAB_MASIVA 2010, 1, '01', 'TATIANAG', 'IPSBOYACA', '01', 'FACTURA', '',''
   --
   EXEC SPK_CONTAB_MASIVA 2010, 2, '01', 'TATIANAG', 'IPSBOYACA', '01', 'FACTURA', '',''
   --
   EXEC SPK_CONTAB_MASIVA 2010, 3, '01', 'TATIANAG', 'IPSBOYACA', '01', 'FACTURA', '',''
   --
   EXEC SPK_CONTAB_MASIVA 2010, 4, '01', 'TATIANAG', 'IPSBOYACA', '01', 'FACTURA', '',''
   --
   EXEC SPK_CONTAB_MASIVA 2010, 5, '01', 'TATIANAG', 'IPSBOYACA', '01', 'FACTURA', '',''
   --
   EXEC SPK_CONTAB_MASIVA 2010, 6, '01', 'TATIANAG', 'IPSBOYACA', '01', 'FACTURA', '',''
   --
   EXEC SPK_CONTAB_MASIVA 2010, 7, '01', 'TATIANAG', 'IPSBOYACA', '01', 'FACTURA', '',''
   --
   EXEC SPK_CONTAB_MASIVA 2010, 8, '01', 'TATIANAG', 'IPSBOYACA', '01', 'FACTURA', '',''
-- INVENTARIO
   --
   UPDATE IMOV SET CONTABILIZADA = 0, NROCOMPROBANTE = NULL, MARCACONT = 0
   WHERE  FECHAMOV >= '01/01/2010'
   AND    FECHAMOV <  '01/09/2010' 
   AND    SECONTABILIZA = 1
   AND    ESTADO        = 1
   AND    NOT IDTIPOMOV IN ((SELECT DBO.FNK_VALORVARIABLE('IDINVMOV_VENTAS') WHERE DBO.FNK_VALORVARIABLE('IDINVMOV_CONTVENTAS')='No') UNION 
                             SELECT DBO.FNK_VALORVARIABLE('IDINVMOV_COMPRAS') WHERE DBO.FNK_VALORVARIABLE('IDINVMOV_CONTCOMPRAS')='No')
   -- 
   UPDATE IMOV SET MARCACONT=1 
   WHERE (CONTABILIZADA=0 OR CONTABILIZADA IS NULL) 
   AND    YEAR(FECHAMOV)  = 2010
   AND    MONTH(FECHAMOV) < 9
   AND    IDBODEGA        IN ( '01', '02', '03', '04' )
   AND    SECONTABILIZA   = 1 
   AND    ESTADO          = 1 
   AND    NOT IDTIPOMOV IN ((SELECT DBO.FNK_VALORVARIABLE('IDINVMOV_VENTAS') WHERE DBO.FNK_VALORVARIABLE('IDINVMOV_CONTVENTAS')='No') UNION 
                             SELECT DBO.FNK_VALORVARIABLE('IDINVMOV_COMPRAS') WHERE DBO.FNK_VALORVARIABLE('IDINVMOV_CONTCOMPRAS')='No')
   --
   EXEC SPK_CONTAB_MASIVA 2010, 1, '01', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 1, '02', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 1, '03', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 1, '04', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   --
   EXEC SPK_CONTAB_MASIVA 2010, 2, '01', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 2, '02', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 2, '03', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 2, '04', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   --   
   EXEC SPK_CONTAB_MASIVA 2010, 3, '01', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 3, '02', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 3, '03', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 3, '04', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   --   
   EXEC SPK_CONTAB_MASIVA 2010, 4, '01', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 4, '02', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 4, '03', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 4, '04', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   --   
   EXEC SPK_CONTAB_MASIVA 2010, 5, '01', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 5, '02', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 5, '03', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 5, '04', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   --   
   EXEC SPK_CONTAB_MASIVA 2010, 6, '01', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 6, '02', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 6, '03', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 6, '04', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   --   
   EXEC SPK_CONTAB_MASIVA 2010, 7, '01', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 7, '02', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 7, '03', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 7, '04', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   --   
   EXEC SPK_CONTAB_MASIVA 2010, 8, '01', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 8, '02', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 8, '03', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   EXEC SPK_CONTAB_MASIVA 2010, 8, '04', 'TATIANAG', 'IPSBOYACA', '01', 'INV', '', '01'
   --   
-- BANCOS 
   UPDATE BMOV SET ESTADO = 'O', CONTABILIZADA = 0, MARCACONT = 1 
   WHERE  FECHAOPERACION >= '01/01/2010'
   AND    FECHAOPERACION <  '01/09/2010'

   EXEC SPK_CONTAB_MASIVA '2010', '1', '01', 'TATIANAG', 'IPSBOYACA', '01', 'BMOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '2', '01', 'TATIANAG', 'IPSBOYACA', '01', 'BMOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '3', '01', 'TATIANAG', 'IPSBOYACA', '01', 'BMOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '4', '01', 'TATIANAG', 'IPSBOYACA', '01', 'BMOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '5', '01', 'TATIANAG', 'IPSBOYACA', '01', 'BMOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '6', '01', 'TATIANAG', 'IPSBOYACA', '01', 'BMOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '7', '01', 'TATIANAG', 'IPSBOYACA', '01', 'BMOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '8', '01', 'TATIANAG', 'IPSBOYACA', '01', 'BMOV', '', ''
-- 'CXP'
   UPDATE FCXP SET CONTABILIZADA=0, MARCACONT = 1
   WHERE  F_FACTURAREF >= '01/01/2010' 
   AND    F_FACTURAREF <  '01/09/2010' 

   EXEC SPK_CONTAB_MASIVA '2010', '1', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXP', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '2', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXP', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '3', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXP', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '4', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXP', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '5', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXP', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '6', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXP', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '7', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXP', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '8', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXP', '', ''
-- 'CXC'
   UPDATE FPAG SET MARCACONT=1,  CONTABILIZADO = 0
   WHERE  FECHA >= '01/01/2010'
   AND    FECHA <  '01/09/2010'
   AND    CERRADO = 1
   
   EXEC SPK_CONTAB_MASIVA '2010', '1', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXC', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '2', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXC', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '3', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXC', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '4', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXC', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '5', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXC', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '6', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXC', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '7', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXC', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '8', '01', 'TATIANAG', 'IPSBOYACA', '01', 'CXC', '', ''
   
-- 'RGLO'
   UPDATE FGLO SET CONTABILIZADA = 0, MARCACONT=1 
   WHERE  FECHARESP <= '01/01/2010'
   AND    FECHARESP <  '01/09/2010'
   AND    VLRRECUPERAR > 0
   AND    CERRADA   = 1
   
   EXEC SPK_CONTAB_MASIVA '2010', '1', '01', 'TATIANAG', 'IPSBOYACA', '01', 'RGLO', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '2', '01', 'TATIANAG', 'IPSBOYACA', '01', 'RGLO', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '3', '01', 'TATIANAG', 'IPSBOYACA', '01', 'RGLO', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '4', '01', 'TATIANAG', 'IPSBOYACA', '01', 'RGLO', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '5', '01', 'TATIANAG', 'IPSBOYACA', '01', 'RGLO', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '6', '01', 'TATIANAG', 'IPSBOYACA', '01', 'RGLO', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '7', '01', 'TATIANAG', 'IPSBOYACA', '01', 'RGLO', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '8', '01', 'TATIANAG', 'IPSBOYACA', '01', 'RGLO', '', ''
  
-- 'NOTDBCR'
   UPDATE FNOT SET  CONTABILIZADA = 0, MARCACONT = 1 
   WHERE  CERRADA = 1                                  
   AND    ESTADO  = 'O'           
   AND    F_NOTA >= '01/01/2010'
   AND    F_NOTA <  '01/09/2010'
   
   EXEC SPK_CONTAB_MASIVA '2010', '1', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'D'
   EXEC SPK_CONTAB_MASIVA '2010', '2', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'D'
   EXEC SPK_CONTAB_MASIVA '2010', '3', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'D'
   EXEC SPK_CONTAB_MASIVA '2010', '4', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'D'
   EXEC SPK_CONTAB_MASIVA '2010', '5', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'D'
   EXEC SPK_CONTAB_MASIVA '2010', '6', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'D'
   EXEC SPK_CONTAB_MASIVA '2010', '7', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'D'
   EXEC SPK_CONTAB_MASIVA '2010', '8', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'D'

   EXEC SPK_CONTAB_MASIVA '2010', '1', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'C'
   EXEC SPK_CONTAB_MASIVA '2010', '2', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'C'
   EXEC SPK_CONTAB_MASIVA '2010', '3', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'C'
   EXEC SPK_CONTAB_MASIVA '2010', '4', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'C'
   EXEC SPK_CONTAB_MASIVA '2010', '5', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'C'
   EXEC SPK_CONTAB_MASIVA '2010', '6', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'C'
   EXEC SPK_CONTAB_MASIVA '2010', '7', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'C'
   EXEC SPK_CONTAB_MASIVA '2010', '8', '01', 'TATIANAG', 'IPSBOYACA', '01', 'NOTDBCR', '', 'C'
   
-- 'ACTIVOS_MOV'  
   UPDATE IACTH SET CONTABILIZADA = 0, MARCACONT = 1
   FROM   IACTH INNER JOIN IACTE ON IACTH.IDEVENTO = IACTE.IDEVENTO
   WHERE  IACTE.MUEVECONTABILIDAD = 'Si'
   AND    IACTH.FECHAEVENTO >= '01/01/2010'
   AND    IACTH.FECHAEVENTO <  '01/09/2010'
   
   EXEC SPK_CONTAB_MASIVA '2010', '1', '01', 'TATIANAG', 'IPSBOYACA', '01', 'ACTIVOS_MOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '2', '01', 'TATIANAG', 'IPSBOYACA', '01', 'ACTIVOS_MOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '3', '01', 'TATIANAG', 'IPSBOYACA', '01', 'ACTIVOS_MOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '4', '01', 'TATIANAG', 'IPSBOYACA', '01', 'ACTIVOS_MOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '5', '01', 'TATIANAG', 'IPSBOYACA', '01', 'ACTIVOS_MOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '6', '01', 'TATIANAG', 'IPSBOYACA', '01', 'ACTIVOS_MOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '7', '01', 'TATIANAG', 'IPSBOYACA', '01', 'ACTIVOS_MOV', '', ''
   EXEC SPK_CONTAB_MASIVA '2010', '8', '01', 'TATIANAG', 'IPSBOYACA', '01', 'ACTIVOS_MOV', '', ''

-- NOMINA
------
   DECLARE @CNSPAGO        VARCHAR(20)
   DECLARE NPER_CURSOR CURSOR FOR
   SELECT CNSPAGO FROM NPER WHERE ANO = '2010' AND MES >= '01' AND MES < '09'
   ORDER BY ANO, MES
   OPEN NPER_CURSOR
   FETCH NEXT FROM NPER_CURSOR
   INTO @CNSPAGO
   WHILE @@FETCH_STATUS = 0 
   BEGIN   
      UPDATE NIEPE SET CONTABILIZADA = 0, NROCOMPROBANTE = '' 
      WHERE  CNSPAGO = @CNSPAGO      
      
      FETCH NEXT FROM NPER_CURSOR
      INTO @CNSPAGO
   END
   CLOSE NPER_CURSOR
   DEALLOCATE NPER_CURSOR
------

   DECLARE @CNSPAGO        VARCHAR(20)
   DECLARE @FECHACONTABLE  DATETIME
   DECLARE @NUMDOC         VARCHAR(20)
   DECLARE @CNSNIEPE       VARCHAR(20)
   DECLARE @NROCOMPROBANTE VARCHAR(20)
   DECLARE NPER_CURSOR CURSOR FOR
   SELECT CNSPAGO, FECHAFIN FROM NPER WHERE ANO = '2010' AND MES >= '01' AND MES < '09'
   ORDER BY ANO, MES
   OPEN NPER_CURSOR
   FETCH NEXT FROM CUR_CONTAB
   INTO @CNSPAGO, @FECHACONTABLE
   WHILE @@FETCH_STATUS = 0 
   BEGIN   
      DECLARE NIEPE_CURSOR CURSOR FOR
      SELECT NUMDOC, CNSNIEPE, NROCOMPROBANTE FROM NIEPE WHERE CNSPAGO = @CNSPAGO      
      OPEN NIEPE_CURSOR
      FETCH NEXT NIEPE_CURSOR
      INTO @NUMDOC, @CNSNIEPE, @NROCOMPROBANTE
      WHILE @@FETCH_STATUS = 0
      BEGIN

         EXEC SPK_CONTAB_NOMINA @CNSPAGO, @NUMDOC, @CNSNIEPE, 'TATIANAG', 'IPSBOYACA', '01', '01', @NROCOMPROBANTE, @FECHACONTABLE

         FETCH NEXT NIEPE_CURSOR
         INTO @NUMDOC, @CNSNIEPE, @NROCOMPROBANTE      
      END
      CLOSE NIEPE_CURSOR
      DEALLOCATE NIEPE_CURSOR
      
      FETCH NEXT FROM CUR_CONTAB
      INTO @CNSPAGO, @FECHACONTABLE
   END
   CLOSE NPER_CURSOR
   DEALLOCATE NPER_CURSOR
   
