CREATE STATISTICS [_dta_stat_68195293_2_35_18_1_6] ON [dbo].[HCA]([CLASEPLANTILLA], [CLASE], [PROCEDENCIA], [CONSECUTIVO], [NOADMISION])
CREATE STATISTICS [_dta_stat_68195293_2_6_35] ON [dbo].[HCA]([CLASEPLANTILLA], [NOADMISION], [CLASE])
CREATE STATISTICS [_dta_stat_68195293_46_6] ON [dbo].[HCA]([SINCRONIZADO], [NOADMISION])
CREATE STATISTICS [_dta_stat_68195293_2_1_6_35] ON [dbo].[HCA]([CLASEPLANTILLA], [CONSECUTIVO], [NOADMISION], [CLASE])

CREATE NONCLUSTERED INDEX [_dta_index_HCA_8_68195293__K6_K18_K35_K1_K2_3_4_5_7] ON [dbo].[HCA] 
(
	[NOADMISION] ASC,
	[PROCEDENCIA] ASC,
	[CLASE] ASC,
	[CONSECUTIVO] ASC,
	[CLASEPLANTILLA] ASC
)
INCLUDE ( [FECHA],
[IDMEDICO],
[IDAFILIADO],
[IDDX]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]


CREATE NONCLUSTERED INDEX [_dta_index_HCA_8_68195293__K6_K1_2_3_4_5_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_34_35_] ON [dbo].[HCA] 
(
	[NOADMISION] ASC,
	[CONSECUTIVO] ASC
)
INCLUDE ( [CLASEPLANTILLA],
[FECHA],
[IDMEDICO],
[IDAFILIADO],
[IDDX],
[TIPODX],
[IMPRESO],
[EDAD],
[FINALIDAD],
[DX1],
[DX2],
[DX3],
[IDMEDICODILIGENCIA],
[IDDXEG],
[N_HISTORIA],
[PROCEDENCIA],
[REVISAESP],
[IDMEDICOESP],
[PIDEDX],
[PIDESV],
[TAS],
[TAD],
[FC],
[FR],
[TEMP],
[TALLA],
[PULSO],
[PESO],
[GLASGOW],
[TIPOGLASGOW],
[HIDRATACION],
[ALTA],
[CLASE],
[ITEMHADM],
[IDAREA],
[ANULADA],
[USUARIOANU],
[FECHA_ANU],
[OBSERVAANU],
[AMBITO],
[MED_ESPEC],
[CAUSA_EXT],
[IDPLAN]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]


CREATE STATISTICS [_dta_stat_68195293_18_6_35_2] ON [dbo].[HCA]([PROCEDENCIA], [NOADMISION], [CLASE], [CLASEPLANTILLA])
