DROP PROC SPKH_RECONSTRUYE_CAJAINGRESOS_DESCUADRADOS
GO
CREATE PROC DBO.SPKH_RECONSTRUYE_CAJAINGRESOS_DESCUADRADOS
AS
DECLARE @NROCOMPROBANTE VARCHAR(20)
DECLARE @REFERENCIA1    VARCHAR(40)
DECLARE @REFERENCIA2    VARCHAR(20)
DECLARE @ANO            VARCHAR(4)
DECLARE @MES            VARCHAR(2)
DECLARE @PROCEDENCIA    VARCHAR(20)
DECLARE @NOREFERENCIA   VARCHAR(20)
BEGIN
   DECLARE FCJ_CURSOR CURSOR FOR
   SELECT FCJ.NROCOMPROBANTE, MCP.REFERENCIA1, MCP.REFERENCIA2, MCP.ANO, MCP.MES, 
          MCP.PROCEDENCIA, MCP.NOREFERENCIA
   FROM   FCJ LEFT JOIN MCP ON FCJ.NROCOMPROBANTE = MCP.NROCOMPROBANTE
   WHERE  COALESCE(FCJ.DEAPERTURA,0) = 0 AND FCJ.CLASE_FAC = 'COBRO' AND FCJ.CERRADA = 1 AND FCJ.ESTADO <> 'A'
   AND    FCJ.FECHA >= '01/01/2010'
   AND    FCJ.FECHA <  '01/09/2010'
   AND    FCJ.CONTABILIZADA = 1
   AND    FCJ.VALORTOTAL   <> MCP.TOTALDEBITO
   AND    FCJ.CODCAJA       = MCP.REFERENCIA2
   AND    FCJ.CNSFACJ       = MCP.REFERENCIA1 
   ORDER BY MCP.ANO, MCP.MES
     
   OPEN FCJ_CURSOR
   FETCH NEXT FROM FCJ_CURSOR
   INTO @NROCOMPROBANTE, @REFERENCIA1, @REFERENCIA2, @ANO, @MES, @PROCEDENCIA, @NOREFERENCIA
   
   WHILE @@FETCH_STATUS = 0
   BEGIN
      PRINT 'NROCOMPROBANTE='+@NROCOMPROBANTE

      EXEC SPK_CONFIRMAR_CONTAB @NROCOMPROBANTE,'TATIANAG','01', '01','IPSBOYACA', @ANO, @MES, @PROCEDENCIA, @NOREFERENCIA, 'DESCONTABILIZAR'


      EXEC SPK_CONTAB_CAJA_ING @REFERENCIA1, @REFERENCIA2, 'TATIANAG' ,'IPSBOYACA', '01', '01', @NROCOMPROBANTE

      FETCH NEXT FROM FCJ_CURSOR
      INTO @NROCOMPROBANTE, @REFERENCIA1, @REFERENCIA2, @ANO, @MES, @PROCEDENCIA, @NOREFERENCIA
   END
   CLOSE FCJ_CURSOR
   DEALLOCATE FCJ_CURSOR
   
END
GO   
