UPDATE IMOVH SET VLRDTO = X.VLRDTO, VLRIVA = X.VLRIVA, PDTO = X.PDTO, PIVA = X.PIVA, PVENTA = X.PVENTA, IDIMPUESTO = X.IDIMPUESTO, 
                 IDCLASE = X.IDCLASE, IDITAR = X.IDITAR
FROM   IMOVH INNER JOIN (SELECT  ITRAH.IDARTICULO, FCOMD.VR_DESCUENTO AS VLRDTO, ITRAH.CANTIDADDES  * FCOMD.VLR_UNITARIO * (FCOMD.FACTORIVA/100.00) AS VLRIVA,
                                 (FCOMD.VR_DESCUENTO*100)/FCOMD.VR_ANTESIVA PDTO, FCOMD.FACTORIVA AS PIVA, X.PVENTA, 
                                 FCOMD.IDIMPUESTO, FCOMD.IDCLASE, IART.IDITAR
                         FROM    ITRAH LEFT  JOIN FNK_PVENTA_IART_XTAR('MAX') X ON ITRAH.IDARTICULO = X.IDARTICULO 
                                       INNER JOIN ITRA  ON ITRA.CNSITRA       = ITRAH.CNSITRA 
                                       INNER JOIN IART  ON ITRAH.IDARTICULO   = IART.IDARTICULO 
                                        LEFT JOIN FCOMD ON ITRA.CNSFCOM       = FCOMD.CNSFCOM 
                                                       AND FCOMD.IDARTICULO   = ITRAH.IDARTICULO 
                                                       AND ITRAH.NOLOTE       = FCOMD.NOLOTE
                         WHERE   ITRA.CNSITRA = '0100012632' AND ITRAH.INICIAL=1
                         ) X ON IMOVH.IDARTICULO = X.IDARTICULO
WHERE  IMOVH.CNSMOV = '0102078942'

DELETE FCXPD WHERE CNSFCXP =  '01CM010354'
UPDATE IMOVH SET ESTADO = 9 WHERE CNSMOV = '0102078942'
EXEC DBO.SPK_INSERT_CXP_INV '01CM010354' , '0102078942'
