SELECT HPRED.* 
FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
WHERE  HPRE.NOADMISION = '0100007630'
AND    (HPRE.CIRUGIA = 'NO' OR HPRE.CIRUGIA = '')
AND    HPRED.NOCOBRABLE = 0
AND    HPRED.VALOR      = 0

DECLARE @NOPRESTACION VARCHAR(16)
DECLARE @NOITEM       SMALLINT   
DECLARE @VEZ          INT
SELECT  @VEZ = 1
DECLARE GG_C CURSOR FOR
SELECT HPRED.NOPRESTACION, HPRED.NOITEM
FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
WHERE  HPRE.NOADMISION = '0100007630'
AND    (HPRE.CIRUGIA = 'NO' OR HPRE.CIRUGIA = '')
AND    HPRED.NOCOBRABLE = 0
AND    HPRED.VALOR      = 0
OPEN GG_C
FETCH NEXT FROM GG_C
INTO  @NOPRESTACION, @NOITEM   
WHILE @@FETCH_STATUS = 0  
BEGIN 
   IF @VEZ = 300
   BEGIN
      BREAK
   END
   PRINT '@NOPRESTACION='+@NOPRESTACION+' - @NOITEM='+STR(@NOITEM)+' - @VEZ='+STR(@VEZ)
   
   UPDATE HPRED SET VALOR = SERTOT1.VLRSERVICIO, VALOREXCEDENTE = SERTOT1.VLRSERVICIO * CANTIDAD
   --SELECT SERTOT1.VLRSERVICIO, HPRED.*
   FROM   HPRED INNER JOIN HPRE    ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
                INNER JOIN SERTOT1 ON HPRED.IDTERCEROCA  = SERTOT1.IDTERCERO
                                  AND HPRED.IDPLAN       = SERTOT1.IDPLAN
                                  AND HPRED.IDSERVICIO   = SERTOT1.IDSERVICIO
                                  AND HPRE.IDAREA        = SERTOT1.IDAREACA
                                  AND FECHAINIFD        <= HPRE.FECHA
                                  AND FECHAFINFD        >= HPRE.FECHA
                                  AND FECHAINI          <= HPRE.FECHA
                                  AND FECHAFIN          >= HPRE.FECHA                           
   WHERE  HPRE.NOADMISION = '0100007083'
   AND    COALESCE(HPRE.CIRUGIA,'') <> 'SI'
   AND    HPRED.NOCOBRABLE = 0
   
   AND    HPRED.NOPRESTACION = @NOPRESTACION
   AND    HPRED.NOITEM       = @NOITEM
   
   SELECT @VEZ = @VEZ + 1
   FETCH NEXT FROM GG_C
   INTO  @NOPRESTACION, @NOITEM   
END 
CLOSE GG_C
DEALLOCATE GG_C

UPDATE HPRE SET HPRE.VALORTOTAL = X.VALORTOTAL, HPRE.VALOREXEDENTE = X.VALOREXCEDENTE
FROM   HPRE INNER JOIN ( SELECT HPRED.NOPRESTACION,  SUM(VALOR*CANTIDAD) VALORTOTAL, SUM(VALOREXCEDENTE) VALOREXCEDENTE
                         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
                         WHERE  HPRE.NOADMISION = '0100007630'
                         GROUP BY HPRED.NOPRESTACION
                       ) X ON HPRE.NOPRESTACION = X.NOPRESTACION
WHERE  HPRE.NOADMISION = '0100007630'

                         
select * from HPRE where NOADMISION = '0100006677'