--EXEC SPKH_GENERA_IMPFTR_DEANULADA 'FH73316'
-- SELECT ESTADO, NOREFERENCIA FROM FTR WHERE N_FACTURA = 'FH73316'
-- SELECT * FROM IMPFTR WHERE NOADMISION = '0100000552'
-- ----------------------------------------------------
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPKH_GENERA_IMPFTR_DEANULADA' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPKH_GENERA_IMPFTR_DEANULADA
END
GO 
-- ----------------------------------------------------
CREATE PROCEDURE DBO.SPKH_GENERA_IMPFTR_DEANULADA
@N_FACTURA       VARCHAR(16)

AS      
DECLARE @NOADMISION VARCHAR(16)
DECLARE @ESTADO     VARCHAR(1) 
DECLARE @VEZ INT
DECLARE @RENGLON_1   INT
DECLARE @RENGLON_2   INT
DECLARE @RENGLON_AUX INT
DECLARE @FACN        INT
DECLARE @GRUPO VARCHAR(2)
DECLARE @TIPO  VARCHAR(20)
DECLARE @TIPO2 VARCHAR(20)
DECLARE @COD1  VARCHAR(20)
DECLARE @DESC1 VARCHAR(255)
DECLARE @COD2  VARCHAR(20)
DECLARE @DESC2 VARCHAR(255)
DECLARE @COD3  VARCHAR(20)
DECLARE @DESC3 VARCHAR(255)
DECLARE @COD4  VARCHAR(20)
DECLARE @DESC4 VARCHAR(255)
DECLARE @VALOR DECIMAL(14,2)
DECLARE @TMP1  VARCHAR(20)
DECLARE @TMP2  SMALLINT
DECLARE @ITFC  SMALLINT
DECLARE @AGRU  INT
DECLARE @AUX1  INT
DECLARE @AUX2  INT
DECLARE @GRUPO_D VARCHAR(2)
DECLARE @TIPO_D VARCHAR(20)
DECLARE @TIPO2_D VARCHAR(20)
DECLARE @COD1_D VARCHAR(20)
DECLARE @DESC1_D VARCHAR(255)
DECLARE @COD2_D VARCHAR(20)
DECLARE @DESC2_D VARCHAR(255)
DECLARE @COD3_D VARCHAR(20)
DECLARE @DESC3_D VARCHAR(255)
DECLARE @COD4_D VARCHAR(20)
DECLARE @DESC4_D VARCHAR(255)
DECLARE @VALOR_D DECIMAL(14,2)
DECLARE @TMP1_D VARCHAR(20)
DECLARE @TMP2_D SMALLINT
DECLARE @ITFC_D SMALLINT
DECLARE @CANT_FACTURA SMALLINT
DECLARE @VR_FTR       DECIMAL(14,2)
DECLARE @TITULO1 VARCHAR(255)
BEGIN 
-------  JEDM.09.07.2009_INICIO CONTEO DE FACTURAS
   SELECT @ESTADO = ESTADO FROM FTR WHERE N_FACTURA = @N_FACTURA
   IF @ESTADO <> 'A'
   BEGIN
      PRINT 'FACTURA NO ANULADA'
      RETURN
   END
   SELECT @NOADMISION = NOREFERENCIA FROM FTR WHERE N_FACTURA = @N_FACTURA
   CREATE TABLE #IMPFTR(
    NOADMISION  VARCHAR(20)  COLLATE database_default, 
    GRUPO       VARCHAR(2) COLLATE database_default, 
    TIPO        VARCHAR(20) COLLATE database_default, 
    TIPO2       VARCHAR(20) COLLATE database_default,
    COD1        VARCHAR(20) COLLATE database_default, 
    DESC1       VARCHAR(255) COLLATE database_default,
    COD2        VARCHAR(20) COLLATE database_default, 
    DESC2       VARCHAR(255) COLLATE database_default, 
    COD3        VARCHAR(20) COLLATE database_default, 
    DESC3       VARCHAR(255) COLLATE database_default,
    COD4        VARCHAR(20) COLLATE database_default, 
    DESC4       VARCHAR(255) COLLATE database_default, 
    VALOR       DECIMAL(18,6), 
    TMP1        VARCHAR(20) COLLATE database_default,
    TMP2        SMALLINT, 
    ITFC        SMALLINT
)  
--tabla para ingreso de titulos en cortes de pagina
CREATE TABLE #IMPFTR2(
    NOADMISION  VARCHAR(20)  COLLATE database_default, 
    GRUPO       VARCHAR(2) COLLATE database_default, 
    TIPO        VARCHAR(20) COLLATE database_default, 
    TIPO2       VARCHAR(20) COLLATE database_default,
    COD1        VARCHAR(20) COLLATE database_default, 
    DESC1       VARCHAR(255) COLLATE database_default,
    COD2        VARCHAR(20) COLLATE database_default, 
    DESC2       VARCHAR(255) COLLATE database_default, 
    COD3        VARCHAR(20) COLLATE database_default, 
    DESC3       VARCHAR(255) COLLATE database_default,
    COD4        VARCHAR(20) COLLATE database_default, 
    DESC4       VARCHAR(255) COLLATE database_default, 
    VALOR       DECIMAL(18,6), 
    TMP1        VARCHAR(20) COLLATE database_default,
    TMP2        SMALLINT, 
    ITFC        SMALLINT
)  
   
   -- CREAMOS TIPO 1
   SELECT @TITULO1= DBO.FNK_VALORVARIABLE80('TIT1_FTR')
   
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, COD1, DESC1, ITFC)
   SELECT @NOADMISION, '01', '01_TITULO', '01', @TITULO1 , 999
      
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, COD2, DESC2, VALOR, ITFC)
   SELECT @NOADMISION, '01', '02_DETALLE', PRE.PREFIJO, PRE.NOM_PREFIJO,     
          SUM(VR_TOTAL), 999 --UNO
	FROM   FTRD INNER JOIN PRE  ON FTRD.PREFIJO = PRE.PREFIJO
   WHERE  FTRD.N_FACTURA = @N_FACTURA
   AND    (ISNULL(FTRD.IDPROVEEDOR,'') = '' OR ISNULL(FTRD.IDPROVEEDOR,'') = DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')) 
   AND    PRE.PREFIJO  <> '20'
   --AND    PRE.PREFIJO NOT IN (SELECT CODIGO FROM TGEN WHERE TABLA = 'General' AND CAMPO = 'PRE_PROV_CLINICA')
	GROUP BY PRE.PREFIJO, PRE.NOM_PREFIJO
       
       
	--CREAMOS TIPO 2 (Agrupaciones)
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, COD1, DESC1, ITFC)
   SELECT @NOADMISION, '02', '01_TITULO', '02', 'SERVICIOS Y HONORARIOS POR CUENTA DE TERCEROS', 999
   
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, TIPO2, COD2, DESC2, VALOR, ITFC)
   SELECT @NOADMISION, '02', '02_DETALLE', '01_DETALLE', PRE.PREFIJO, PRE.NOM_PREFIJO, 
          SUM(VR_TOTAL), 999 --UNO
	FROM   FTRD INNER JOIN PRE  ON FTRD.PREFIJO = PRE.PREFIJO
   WHERE  FTRD.N_FACTURA = @N_FACTURA
	AND    (ISNULL(FTRD.IDPROVEEDOR,'') <> '' AND ISNULL(FTRD.IDPROVEEDOR,'') <> DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'))
   AND    PRE.PREFIJO <> '20'
   AND    COALESCE(FTRD.IDCIRUGIA,'') <> 'SI'
   --AND    PRE.PREFIJO NOT IN (SELECT CODIGO FROM TGEN WHERE TABLA = 'General' AND CAMPO = 'PRE_PROV_CLINICA')
	GROUP BY PRE.PREFIJO, PRE.NOM_PREFIJO
   
   --CREAMOS TIPO 2 (Detalles)
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, TIPO2, COD2, COD3, DESC3, VALOR, ITFC)
   SELECT @NOADMISION, '02', '02_DETALLE', '02_DETALLE', PRE.PREFIJO, FTRD.IDPROVEEDOR, TER.RAZONSOCIAL, 
          SUM(VR_TOTAL), 999 --UNO
	FROM   FTRD INNER JOIN PRE  ON FTRD.PREFIJO = PRE.PREFIJO
	             LEFT JOIN TER  ON FTRD.IDPROVEEDOR  = TER.IDTERCERO
   WHERE  FTRD.N_FACTURA = @N_FACTURA
   AND    (ISNULL(FTRD.IDPROVEEDOR,'') <> '' AND ISNULL(FTRD.IDPROVEEDOR,'') <> DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'))
   AND    FTRD.IDCIRUGIA <> 'SI'
	AND    PRE.PREFIJO <> '20'
	GROUP BY PRE.PREFIJO, FTRD.IDPROVEEDOR, TER.RAZONSOCIAL
	
	--CREAMOS TIPO 3 CIRUGIAS (Agrupaciones)
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, COD1, DESC1, ITFC)
   --SELECT @NOADMISION, '03', '01_TITULO', '03', 'CIRUGIAS', 999
   SELECT @NOADMISION, '03', '01_TITULO', '03', 'SERVICIOS Y HONORARIOS POR CUENTA DE TERCEROS', 999
	
	INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, TIPO2, TMP1, TMP2, COD2, DESC2, VALOR, ITFC)
   SELECT @NOADMISION, '03', '02_DETALLE', '01_DETALLE', 'CONSECUTIVOCX', 1, 
          FTRD.IDCIRUGIA, SER.DESCSERVICIO, SUM(VR_TOTAL), 999
	FROM   FTRD INNER JOIN SER  ON COALESCE(FTRD.IDCIRUGIA,'') = SER.IDSERVICIO
	            INNER JOIN PRE  ON FTRD.PREFIJO = PRE.PREFIJO
	             LEFT JOIN TER  ON FTRD.IDPROVEEDOR  = TER.IDTERCERO
   WHERE  FTRD.N_FACTURA = @N_FACTURA
 	AND    (ISNULL(FTRD.IDPROVEEDOR,'') <> '' AND ISNULL(FTRD.IDPROVEEDOR,'') <> DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'))
   AND    COALESCE(FTRD.IDCIRUGIA,'') <> ''
	GROUP BY FTRD.IDCIRUGIA, SER.DESCSERVICIO
    
   --CREAMOS TIPO 3 CIRUGIAS (DETALLE) 
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, TIPO2, TMP1, TMP2, COD2, COD3, DESC3, COD4, DESC4, VALOR, ITFC)
   SELECT @NOADMISION, '03', '02_DETALLE', '02_DETALLE', 'CONSECUTIVOCX', 1, 
          FTRD.IDCIRUGIA, FTRD.IDPROVEEDOR, TER.RAZONSOCIAL, FTRD.REFERENCIA, SER.DESCSERVICIO,
         (FTRD.VR_TOTAL), 999 --UNO
	FROM   FTRD INNER JOIN PRE  ON FTRD.PREFIJO     = PRE.PREFIJO
	            INNER JOIN SER  ON FTRD.REFERENCIA  = SER.IDSERVICIO
	             LEFT JOIN TER  ON FTRD.IDPROVEEDOR = TER.IDTERCERO
   WHERE  FTRD.N_FACTURA = @N_FACTURA
 	AND    (ISNULL(FTRD.IDPROVEEDOR,'') <> '' AND ISNULL(FTRD.IDPROVEEDOR,'') <> DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'))
   AND    COALESCE(FTRD.IDCIRUGIA,'') <> ''   
   
   --CREAMOS TIPO 4 (Agrupaciones)
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, COD1, DESC1, ITFC)
   --   SELECT @NOADMISION, '04', '01_TITULO', '04', 'SERVICIOS TERCERIZADOS', 999
   SELECT @NOADMISION, '04', '01_TITULO', '04', 'SERVICIOS Y HONORARIOS POR CUENTA DE TERCEROS', 999
   
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, TIPO2, COD2, DESC2, VALOR, ITFC)
   SELECT @NOADMISION, '04', '02_DETALLE', '01_DETALLE', PRE.PREFIJO, PRE.NOM_PREFIJO, 
          SUM(VR_TOTAL), 999 -- UNO        
	FROM   FTRD INNER JOIN PRE  ON FTRD.PREFIJO    = PRE.PREFIJO
	            INNER JOIN SER  ON FTRD.REFERENCIA = SER.IDSERVICIO          
   WHERE  FTRD.N_FACTURA = @N_FACTURA
	AND    (ISNULL(FTRD.IDPROVEEDOR,'') <> '' AND ISNULL(FTRD.IDPROVEEDOR,'') <> DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'))
   AND    PRE.PREFIJO = '20'
   AND    COALESCE(FTRD.IDCIRUGIA,'')  = ''
	GROUP BY PRE.PREFIJO, PRE.NOM_PREFIJO
   
   --CREAMOS TIPO 4 (Detalles)
   
   -- MOD.JQUIROGA 20090714 - Se agrega LEFT JOIN SER y campo SER.DESCSERVICIO
   INSERT INTO #IMPFTR (NOADMISION, GRUPO, TIPO, TIPO2, COD2, COD3, DESC3, VALOR, ITFC)
   SELECT @NOADMISION, '04', '02_DETALLE', '02_DETALLE', PRE.PREFIJO, FTRD.IDPROVEEDOR, TER.RAZONSOCIAL + ' ' + SER.DESCSERVICIO , 
          SUM(VR_TOTAL), 999 --UNO
	FROM   FTRD INNER JOIN PRE  ON FTRD.PREFIJO      = PRE.PREFIJO
	             LEFT JOIN SER  ON FTRD.REFERENCIA   = SER.IDSERVICIO          
	             LEFT JOIN TER  ON FTRD.IDPROVEEDOR = TER.IDTERCERO
   WHERE  FTRD.N_FACTURA = @N_FACTURA
	AND    (ISNULL(FTRD.IDPROVEEDOR,'') <> '' AND ISNULL(FTRD.IDPROVEEDOR,'') <> DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'))
   AND    COALESCE(FTRD.IDCIRUGIA,'')  = ''
	AND    PRE.PREFIJO = '20'
	GROUP BY PRE.PREFIJO, FTRD.IDPROVEEDOR, TER.RAZONSOCIAL, SER.DESCSERVICIO
	
   SELECT @AUX1 = ISNULL(COUNT(*),0) FROM #IMPFTR
   WHERE  GRUPO = '02' 
   AND    ISNULL(COD1,'') = ''

   IF @AUX1 = 0
   BEGIN
      DELETE #IMPFTR WHERE GRUPO = '02'
   END
   
   SELECT @AUX1 = ISNULL(COUNT(*),0) FROM #IMPFTR
   WHERE  GRUPO = '03' 
   AND    ISNULL(COD1,'') = ''
   
   IF @AUX1 = 0
   BEGIN
      DELETE #IMPFTR WHERE GRUPO = '03'
   END
   
   SELECT @AUX1 = ISNULL(COUNT(*),0) FROM #IMPFTR
   WHERE  GRUPO = '04' 
   AND    ISNULL(COD1,'') = ''
   
   IF @AUX1 = 0
   BEGIN
      DELETE #IMPFTR WHERE GRUPO = '04'
   END
   
-- Inserción en IMPFTR
   INSERT INTO IMPFTR (NOADMISION, GRUPO, TIPO, TIPO2, COD1, DESC1, COD2 , DESC2, COD3, DESC3 ,COD4, DESC4, VALOR, TMP1, TMP2, ITFC, N_FACTURA)    
   SELECT NOADMISION, GRUPO, TIPO, TIPO2, COD1, DESC1, COD2 , DESC2, COD3, DESC3 ,COD4, DESC4, VALOR, TMP1, TMP2, 1, @N_FACTURA 
   FROM   #IMPFTR
   
   --Se recalculan los valores GRUPO 01
   
   UPDATE IMPFTR SET IMPFTR.VALOR = X.VALOR
   FROM   IMPFTR INNER JOIN (SELECT ITFC, SUM(VALOR) AS VALOR
                             FROM   IMPFTR
                             WHERE  IMPFTR.GRUPO            = '01'
                             AND    ISNULL(IMPFTR.COD1,'')  = ''
                             AND    ISNULL(IMPFTR.COD2,'') <> ''
                             AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
                             GROUP BY ITFC) X  ON IMPFTR.ITFC = X.ITFC
   WHERE  IMPFTR.GRUPO            = '01'
   AND    IMPFTR.NOADMISION       = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
   AND    ISNULL(IMPFTR.COD1,'') <> ''
   
   -- Se recalculan los valores GRUPO 02
   UPDATE IMPFTR SET IMPFTR.VALOR = X.VALOR
   FROM   IMPFTR INNER JOIN (SELECT  ITFC, COD2, SUM(VALOR) AS VALOR
                              FROM   IMPFTR
                              WHERE  IMPFTR.GRUPO            = '02'
                              AND    ISNULL(IMPFTR.COD1,'')  = ''
                              AND    ISNULL(IMPFTR.COD2,'') <> ''
                              AND    ISNULL(IMPFTR.COD3,'') <> ''
                              AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
                              GROUP BY ITFC, COD2) X  ON IMPFTR.ITFC = X.ITFC AND ISNULL(IMPFTR.COD2,'') = ISNULL(X.COD2,'')
   WHERE  IMPFTR.GRUPO            = '02'
   AND    ISNULL(IMPFTR.COD1,'') = ''
   AND    ISNULL(IMPFTR.COD2,'') <> ''
   AND    ISNULL(IMPFTR.COD3,'') = ''
   AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
   
   UPDATE IMPFTR SET IMPFTR.VALOR = X.VALOR
   FROM   IMPFTR INNER JOIN (SELECT  ITFC, SUM(VALOR) AS VALOR
                              FROM   IMPFTR
                              WHERE  IMPFTR.GRUPO            = '02'
                              AND    ISNULL(IMPFTR.COD1,'')  = ''
                              AND    ISNULL(IMPFTR.COD2,'') <> ''
                              AND    ISNULL(IMPFTR.COD3,'') = ''
                              AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
                              GROUP BY ITFC) X  ON IMPFTR.ITFC = X.ITFC 
   WHERE  IMPFTR.GRUPO            = '02'
   AND    ISNULL(IMPFTR.COD1,'') <> ''
   AND    ISNULL(IMPFTR.COD2,'') = ''
   AND    ISNULL(IMPFTR.COD3,'') = ''
   AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA

   --Se recalculan los valores GRUPO 03
   UPDATE IMPFTR SET IMPFTR.VALOR = X.VALOR
   FROM   IMPFTR INNER JOIN (SELECT  ITFC, COD2, TMP1, TMP2, SUM(VALOR) AS VALOR
                              FROM   IMPFTR
                              WHERE  IMPFTR.GRUPO            = '03'
                              AND    ISNULL(IMPFTR.COD1,'')  = ''
                              AND    ISNULL(IMPFTR.COD2,'') <> ''
                              AND    ISNULL(IMPFTR.COD3,'') <> ''  
                              AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
                              GROUP BY ITFC, COD2, TMP1, TMP2) X  ON IMPFTR.ITFC = X.ITFC AND ISNULL(IMPFTR.COD2,'') = ISNULL(X.COD2,'')
                                                                              AND ISNULL(IMPFTR.TMP1,'') = ISNULL(X.TMP1,'')
                                                                              AND ISNULL(IMPFTR.TMP2,'') = ISNULL(X.TMP2,'')
   WHERE  IMPFTR.GRUPO            = '03'
   AND    ISNULL(IMPFTR.COD1,'') = ''
   AND    ISNULL(IMPFTR.COD2,'') <> ''
   AND    ISNULL(IMPFTR.COD3,'') = ''
   AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA

   UPDATE IMPFTR SET IMPFTR.VALOR = X.VALOR
   FROM   IMPFTR INNER JOIN (SELECT  ITFC, SUM(VALOR) AS VALOR
                              FROM   IMPFTR
                              WHERE  IMPFTR.GRUPO            = '03'
                              AND    ISNULL(IMPFTR.COD1,'')  = ''
                              AND    ISNULL(IMPFTR.COD2,'') <> ''
                              AND    ISNULL(IMPFTR.COD3,'') = ''
                              AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
                              GROUP BY ITFC) X  ON IMPFTR.ITFC = X.ITFC 
   WHERE  IMPFTR.GRUPO           = '03'
   AND    ISNULL(IMPFTR.COD1,'') <> ''
   AND    ISNULL(IMPFTR.COD2,'') = ''
   AND    ISNULL(IMPFTR.COD3,'') = ''
   AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
   
   --Se recalculan los valores GRUPO 04
   UPDATE IMPFTR SET IMPFTR.VALOR = X.VALOR
   FROM   IMPFTR INNER JOIN (SELECT  ITFC, COD2, SUM(VALOR) AS VALOR
                              FROM   IMPFTR
                              WHERE  IMPFTR.GRUPO            = '04'
                              AND    ISNULL(IMPFTR.COD1,'')  = ''
                              AND    ISNULL(IMPFTR.COD2,'') <> ''
                              AND    ISNULL(IMPFTR.COD3,'') <> ''
                              AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
                              GROUP BY ITFC, COD2) X  ON IMPFTR.ITFC = X.ITFC AND ISNULL(IMPFTR.COD2,'') = ISNULL(X.COD2,'')
   WHERE  IMPFTR.GRUPO            = '04'
   AND    ISNULL(IMPFTR.COD1,'') = ''
   AND    ISNULL(IMPFTR.COD2,'') <> ''
   AND    ISNULL(IMPFTR.COD3,'') = ''
   AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
   
   UPDATE IMPFTR SET IMPFTR.VALOR = X.VALOR
   FROM   IMPFTR INNER JOIN (SELECT  ITFC, SUM(VALOR) AS VALOR
                              FROM   IMPFTR
                              WHERE  IMPFTR.GRUPO            = '04'
                              AND    ISNULL(IMPFTR.COD1,'')  = ''
                              AND    ISNULL(IMPFTR.COD2,'') <> ''
                              AND    ISNULL(IMPFTR.COD3,'') = ''
                              AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
                              GROUP BY ITFC) X  ON IMPFTR.ITFC = X.ITFC 
   WHERE  IMPFTR.GRUPO            = '04'
   AND    ISNULL(IMPFTR.COD1,'') <> ''
   AND    ISNULL(IMPFTR.COD2,'') = ''
   AND    ISNULL(IMPFTR.COD3,'') = ''
   AND    IMPFTR.NOADMISION = @NOADMISION AND IMPFTR.N_FACTURA = @N_FACTURA
   
   -- Actualizando los Gastos de Hospitalización  GRUPO '01'
  
   DROP TABLE #IMPFTR
   
END
GO 