SELECT TOP 100 * FROM API_LOG WHERE USUARIO='MMEJIA' ORDER BY ITEM DESC

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FTR_PERU","METODO":"SOPORTES_FTREPE","PARAMETROS":{"N_FACTURA":"F002-00000029"},"USUARIO":"JJIMENEZ"}'

EXEC SPQ_JSON '{"MODELO":"RECAUDO_PE","METODO":"GES_LINK_PAGO","PARAMETROS":{"PROCESO":"CREAR","TABLA":"CIT","PROCEDENCIA":"AGENDA","CONSECUTIVO":"010000002235","IDAFILIADO":"0100001640"},"USUARIO":"MMEJIA"}'

			SELECT IDKPAGE = COALESCE(IDKPAGE,0), VALOR = CASE WHEN DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR') = CIT.IDTERCEROCA 
               THEN CIT.VALORTOTAL ELSE CIT.VALORCOPAGO END 
			FROM CIT WHERE CONSECUTIVO = '010000002235'

         {"MODELO":"PASARELA_PAGOS","METODO":"ACTUALIZA_UNO","PARAMETROS":{"IDKPAGE":1209},"USUARIO":"JJIMENEZ"}

         SELECT  * FROM KPAGE WHERE CONSECUTIVO='010000002235'

      SELECT PROCEDENCIA=PROCEDENCIA,NOREFERENCIA=NOREFERENCIA,IDAFILIADO=IDAFILIADO
      FROM FTR WHERE N_FACTURA='F002-00000029'
      PRINT @PROCEDENCIA

      El nombre de objeto 'RIAS_CONTROLPRENATAL' no es válido.

      SELECT FACTURADA,N_FACTURA,NFACTURA, * FROM CIT WHERE CONSECUTIVO='010000002062' 

      SELECT * FROM CAU

      EXEC SPQ_JSON '{"MODELO":"HCA_COL","METODO":"CONSULTAR","PARAMETROS":{"CONSECUTIVO":"0100000516"},"USUARIO":"JJIMENEZ"}'



      SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

      SELECT CIT.CONSECUTIVO,DBO.FNK_FECHA_GRINGA(CIT.FECHA)FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,CIT.IDMEDICO,MED.NOMBRE,MES.DESCRIPCION,CIT.IDSERVICIO,SER.DESCSERVICIO,COALESCE(CIT.VALORTOTAL,0)VALORTOTAL,COALESCE(CIT.VALORCOPAGO,0)VALORCOPAGO,(COALESCE(CIT.VALORTOTAL,0)-COALESCE(CIT.VALORCOPAGO,0))VLR_EXCEDENTE,COALESCE(CIT.FACTURADA,0) FACTURADA,CIT.N_FACTURA,CIT.NFACTURA AS NBOLETA  FROM [dbo].[CIT] INNER JOIN  AFI ON CIT.IDAFILIADO=AFI.IDAFILIADO INNER JOIN  MED ON CIT.IDMEDICO=MED.IDMEDICO INNER JOIN  SER ON CIT.IDSERVICIO=SER.IDSERVICIO LEFT JOIN  MES ON CIT.IDEMEDICA=MES.IDEMEDICA WHERE (MED.NOMBRE LIKE '%%%%' OR CONSECUTIVO LIKE '%%%%' OR AFI.NOMBREAFI LIKE '%%%%') AND  COALESCE(CIT.CUMPLIDA,0)=1 AND CIT.IDAFILIADO IS NOT NULL             AND   1=CASE WHEN NOT EXISTS(SELECT * FROM AUT WHERE AUT.CONSECUTIVOCIT=CIT.CONSECUTIVO) THEN 1 ELSE            CASE WHEN  EXISTS(SELECT * FROM AUT WHERE AUT.CONSECUTIVOCIT=CIT.CONSECUTIVO AND COALESCE(GENERADO,0)<>3) THEN 0 ELSE 1 END END           AND COALESCE(CIT.FACTURADA,0)=0  AND CONVERT(DATE,CIT.FECHA)>='2024-10-24' AND CONVERT(DATE,CIT.FECHA)<='2024-10-24'  ORDER BY CONSECUTIVO DESC  OFFSET (1-1)*10 ROWS  FETCH NEXT 10 ROWS ONLY 


      UPDATE CIT SET FACTURADA=0,N_FACTURA=NULL WHERE N_FACTURA LIKE 'B%'

      EXEC SPQ_JSON '{"MODELO":"FTR_PERU","METODO":"FACTURAR_CITAUT","PARAMETROS":{"CONSECUTIVO":"010000001008"},"USUARIO":"LPILARES"}'

      SELECT IDPLAN, * FROM CIT WHERE CONSECUTIVO='010000001008'

      SELECT *
      					FROM   AUT INNER JOIN AUTD ON AUTD.IDAUT     = AUT.IDAUT 
								INNER JOIN SER  ON SER.IDSERVICIO = AUTD.IDSERVICIO 
								LEFT JOIN TER  ON TER.IDTERCERO  = AUTD.IDTERCEROCA
					WHERE  AUT.CONSECUTIVOCIT = '010000001008'             
						AND AUTD.IDPLAN='PAQ020'
                  AND COALESCE(AUTD.NOCOBRABLE,0)=0
                  AND COALESCE(AUTD.GENERADO,0)=1
                  AND COALESCE(AUTD.FACTURADA,0)=0
                  AND COALESCE(AUTD.VALOR,0)>0
                  AND COALESCE(AUTD.VALOREXCEDENTE,0)>0