IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_NC_CONTAB_NOMINA' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_NC_CONTAB_NOMINA
END
GO
CREATE PROCEDURE DBO.SPK_NC_CONTAB_NOMINA	 
@CNSPAGO          VARCHAR(20), 
@NUMDOC           VARCHAR(20),
@CNSNIEPE         VARCHAR(20),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA         VARCHAR(2), 
@SEDE             VARCHAR(5),
@NROCOMPROBANTE   VARCHAR(20),
@FECHACONTABLE    DATETIME
WITH ENCRYPTION   
AS
DECLARE @COM		           VARCHAR(6)
DECLARE @NOREFERENCIA        VARCHAR(20)
DECLARE @ANO                 VARCHAR(4)
DECLARE @MES                 VARCHAR(2)
DECLARE @IDMODELOCONT        VARCHAR(2)
DECLARE @IDPLAN              VARCHAR(6) 
DECLARE @TIPOTERCONTABLE     VARCHAR(10) 
DECLARE @VLR_IMPUESTOS       DECIMAL(14,2)
DECLARE @CXP_TIPO            VARCHAR(20) 
DECLARE @PREFIJO_CUR         VARCHAR(20)
DECLARE @CCOSTO_CUR          VARCHAR(20)
DECLARE @IDAREA_CUR          VARCHAR(20)
DECLARE @VLR_NETO_CUR        DECIMAL(14,2)
DECLARE @PREFIJO_USCXS       VARCHAR(10)
DECLARE @PROCEDENCIA         VARCHAR(10) 
DECLARE @ESTADO              VARCHAR(1)
DECLARE @PROC_MCP            VARCHAR(20) 
DECLARE @TIPOCONTABILIZACION VARCHAR(1) 
DECLARE @FECHATRA            DATETIME
DECLARE @CODUNG              VARCHAR(5)
DECLARE @MENSAJE             VARCHAR(254)
DECLARE @NDIS                INT
BEGIN

   --BEGIN TRANSACTION  
   SELECT * INTO #T FROM NIEPE WHERE CNSPAGO = @CNSPAGO AND NUMDOC=@NUMDOC
   
   SELECT NIEPED.* INTO #TH 
   FROM   NIEPE INNER JOIN NIEPED ON NIEPE.CNSNIEPE = NIEPED.CNSNIEPE 
                                 AND NIEPE.NUMDOC   = NIEPED.NUMDOC
   WHERE  NIEPE.CNSPAGO = @CNSPAGO 
   AND    NIEPE.NUMDOC  = @NUMDOC
   
   SELECT TOP 1 @CODUNG = #T.CODUNG 
   FROM NOMI INNER JOIN #T ON NOMI.CODNOMINA = #T.CODNOMINA
   
   SET @MENSAJE = CAST(@CNSPAGO AS VARCHAR) +'-' +CAST(@NUMDOC AS VARCHAR) +'-'+ CAST(@CNSNIEPE AS VARCHAR) 
     
   SELECT @ANO      = YEAR(@FECHACONTABLE),
          @MES      = MONTH(@FECHACONTABLE),
          @FECHATRA = @FECHACONTABLE
   
   IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)
   BEGIN
      RAISERROR('Periodo Contable NO Existe', 16, 1)
      RETURN
   END
   
   SET @IDMODELOCONT = DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
   SELECT @TIPOCONTABILIZACION= ISNULL(DBO.FNK_VALORVARIABLE('NOMINATIPOCONTAB'),'1')
   
   SELECT @NDIS         = ISNULL(COUNT(*),0)
   FROM NDIS WHERE NDIS.CNSPAGO = @CNSPAGO AND
                   NDIS.NUMDOC  = @NUMDOC
   IF @NDIS = 0
   BEGIN
      --SI NO TIENE CONTABILIZACION, HACE LA CONTABILIZACION NORMAL.
      SET @TIPOCONTABILIZACION ='1' 
   END
   
   IF ISNULL(@NROCOMPROBANTE,'') = '' -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   BEGIN
      SET @PROC_MCP='NOMINA'
      SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      
      --SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_CXP_NOM')))
      IF (SELECT DBO.FNK_VALORVARIABLE('COMPROBMULTISEDE')) = 'SI'
      BEGIN
         SELECT @COM = RTRIM(LTRIM(COMMS.COMPROBANTE)) 
         FROM   COMMS 
         WHERE  COMMS.IDSEDE = @SEDE 
         AND    COMMS.CLASE  = 'NOMINA' 
         AND    COMMS.TIPO   = 'NOMINA'
      END
      ELSE
      BEGIN
         SET @COM=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_NOMINA')))
      END
      IF @COM='' OR @COM IS NULL
         SET @COM = DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT')
      IF @COM='' OR @COM IS NULL
      BEGIN
         RAISERROR ('La variable de Sistemas IDCON_TCOM_DEFAULT está sin Definir.', 16, 1)
         --ROLLBACK
         RETURN
      END
  
      -- PRINT 'COM='+@COM
       
      SET @PREFIJO_USCXS='@COM'+@COM
      SET @NOREFERENCIA=SPACE(20)
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
      SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
      --   PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
      --   PRINT 'Comprobante Contable (MCP)'
      INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                       TOTALCREDITO, REFERENCIA1, REFERENCIA2, REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO,
                       COMPROBANTE, IDTERCERO )
      SELECT @NROCOMPROBANTE, @COMPANIA, 'NOMINA', @NOREFERENCIA, @ANO, @MES, @FECHATRA,
             0, 0, @NUMDOC, @CNSPAGO, @CNSNIEPE, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, 'PAGO DE NOMINA', 
             @SEDE, 0, @COM, @NUMDOC
   END
   ELSE
   BEGIN
      IF @ESTADO='A' 
      BEGIN 
         DELETE MCHE 
         WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND PROCEDENCIA='NOMINA' AND REFERENCIA_PRO=@NUMDOC
         IF (SELECT COUNT(*) FROM MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE)=0
         BEGIN
            UPDATE MCPE SET ESTADO='2', ANULADO=1, TOTALDEBITO=0, TOTALCREDITO=0, REFERENCIA3=@CNSNIEPE 
            WHERE COMPANIA=@COMPANIA AND NROCOMPROBANTE=@NROCOMPROBANTE
         END
         RETURN
      END
      ELSE
      BEGIN
         DELETE MCHE 
         WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND PROCEDENCIA='NOMINA' AND REFERENCIA_PRO=@NUMDOC
         UPDATE MCPE SET OBSERVACION='PAGO DE NOMINA'
         WHERE MCPE.NROCOMPROBANTE=@NROCOMPROBANTE AND MCPE.PROCEDENCIA='NOMINA' AND MCPE.REFERENCIA1=@NUMDOC
         SELECT @COM          = COMPROBANTE,
                @NOREFERENCIA = NOREFERENCIA
         FROM #T
      END
   END
     
   -- PRINT 'Insertando Asiento DB Para Conceptos de Empleados' 
   -----------------------** CONTABILIZACION NORMAL
   IF @TIPOCONTABILIZACION='1'
   BEGIN 
      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                      REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
                      N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG,IDSEDE)  
      SELECT @NROCOMPROBANTE, @COMPANIA, CASE WHEN NCON.TIPO = 'Ingreso' THEN 'DB' ELSE 'CR' END,   
             DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', CASE WHEN NCON.TIPO = 'Ingreso' THEN 'DB' ELSE 'CR' END,   
             NCON.CODCONCEPTO, #T.CCOSTO, 'S', #T.CODNOMINA,0), CASE  WHEN COALESCE(#TH.RECOBRO,0)=1 AND  NCON.TIPO = 'Ingreso'  THEN #TH.IDTERCERO_RECO 
                                                                WHEN COALESCE(#TH.RECOBRO,0)=1 AND  NCON.TIPO = 'Egreso' THEN @NUMDOC
                                                                ELSE #TH.IDTERCERO_PRF END, #T.CCOSTO, UPPER(NCON.DESCRIPCION), #TH.VALOR,  
             @CNSPAGO,@NUMDOC,NULL,@USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()),#TH.CODCONCEPTO, #T.IDAREA,'S', 1,  
             'NOMINA_NCON', 'Movimiento', @CNSPAGO, DBO.FNK_FECHA_SIN_HORA(@FECHATRA), DBO.FNK_FECHA_SIN_HORA(@FECHATRA),   
             'NOMINA','NOMINA', @NUMDOC, #T.CODUNG, NEMP.CODPRG,#T.IDSEDE
      FROM #T INNER JOIN #TH  ON #T.CNSNIEPE     = #TH.CNSNIEPE 
                             AND #T.NUMDOC       = #TH.NUMDOC 
              INNER JOIN NCON ON #TH.CODCONCEPTO = NCON.CODCONCEPTO 
              INNER JOIN NEMP ON #TH.NUMDOC      = NEMP.NUMDOC  
              INNER JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY CODCONCEPTO ORDER BY FECHAINI DESC) [RITEM],CODCONCEPTO,ITEM
                          FROM NCOND WHERE @FECHACONTABLE>=FECHAINI) X ON X.CODCONCEPTO=NCON.CODCONCEPTO AND X.RITEM=1
              INNER JOIN NCOND ON X.CODCONCEPTO=NCOND.CODCONCEPTO AND X.ITEM=NCOND.ITEM
      WHERE #TH.VALOR<>0 AND #TH.INFO='No'  
      ORDER BY NCON.NATURALEZA DESC  
   END
   -----------------------** CONTABILIZACION NORMAL
   IF @TIPOCONTABILIZACION='2'
   BEGIN 
      -----------------------** CONTABILIZACION POR AREA FUNCIONA Y CENTRO DE COSTO --CREDITOS
      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                       REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
                       N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG,IDSEDE)  
      SELECT @NROCOMPROBANTE, @COMPANIA, CASE WHEN NCON.TIPO = 'Ingreso' THEN 'DB' ELSE 'CR' END,   
             DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', CASE WHEN NCON.TIPO = 'Ingreso' THEN 'DB' ELSE 'CR' END,   
             NCON.CODCONCEPTO, CASE NDIS.CCOSTO WHEN NULL THEN #T.CCOSTO ELSE NDIS.CCOSTO END, 'S', #T.CODNOMINA,0),   
            CASE  WHEN COALESCE(#TH.RECOBRO,0)=1 AND  NCON.TIPO = 'Ingreso'  THEN #TH.IDTERCERO_RECO ELSE #TH.IDTERCERO_PRF END, NDIS.CCOSTO, UPPER(NCON.DESCRIPCION), #TH.VALOR * (CASE NDIS.PORCENTAJE WHEN NULL THEN 1 ELSE NDIS.PORCENTAJE / 100 END),  
             @CNSPAGO,@NUMDOC,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),#TH.CODCONCEPTO, NDIS.IDAREA,'S', 1,  
             'NOMINA_NCON', 'Movimiento', @CNSPAGO, DBO.FNK_FECHA_SIN_HORA(@FECHATRA), DBO.FNK_FECHA_SIN_HORA(@FECHATRA),   
             'NOMINA','NOMINA', @NUMDOC, #T.CODUNG, NEMP.CODPRG ,#T.IDSEDE
      FROM   #T INNER JOIN #TH  ON #T.CNSNIEPE = #TH.CNSNIEPE 
                               AND #T.NUMDOC   = #TH.NUMDOC 
                INNER JOIN NCON ON #TH.CODCONCEPTO = NCON.CODCONCEPTO 
                INNER JOIN NEMP ON #TH.NUMDOC      = NEMP.NUMDOC 
                 LEFT JOIN NDIS ON NDIS.CNSPAGO    = @CNSPAGO 
                               AND #TH.NUMDOC      = NDIS.NUMDOC 
                INNER JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY CODCONCEPTO ORDER BY FECHAINI DESC) [RITEM],CODCONCEPTO,ITEM
                            FROM NCOND WHERE @FECHACONTABLE>=FECHAINI) X ON X.CODCONCEPTO=NCON.CODCONCEPTO AND X.RITEM=1
                INNER JOIN NCOND ON X.CODCONCEPTO=NCOND.CODCONCEPTO AND X.ITEM=NCOND.ITEM
      WHERE  #TH.VALOR <> 0 
      AND    #TH.INFO   = 'No'  
      ORDER BY NCON.NATURALEZA DESC  
      -----------------------** CONTABILIZACION POR CENTRO DE COSTO
   END
        
   -- PRINT 'Insertando Asiento DB Para Conceptos de la Empresa'    
   IF @TIPOCONTABILIZACION='1'
   BEGIN
      --CONTABILIZACION NORMAL
      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                      REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
                      N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG,IDSEDE)  
      SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',   
             DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', 'DB', NCON.CODCONCEPTO, #T.CCOSTO,'S',#T.CODNOMINA,0),   
             CASE COALESCE(#TH.RECOBRO,0) WHEN 1 THEN #TH.IDTERCERO_RECO ELSE #TH.IDTERCERO_PRF END, #T.CCOSTO, UPPER(NCON.DESCRIPCION), #TH.VALOR_APORTES,  
             @CNSPAGO,@NUMDOC,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),#TH.CODCONCEPTO, #T.IDAREA,'S', 1,  
             'NOMINA_NCON', 'Movimiento', @CNSPAGO, DBO.FNK_FECHA_SIN_HORA(@FECHATRA), DBO.FNK_FECHA_SIN_HORA(@FECHATRA),   
             'NOMINA','NOMINA', @NUMDOC, #T.CODUNG, NEMP.CODPRG,#T.IDSEDE 
      FROM   #T INNER JOIN  #TH ON #T.CNSNIEPE = #TH.CNSNIEPE 
                               AND #T.NUMDOC   = #TH.NUMDOC 
                INNER JOIN NCON ON #TH.CODCONCEPTO = NCON.CODCONCEPTO 
                INNER JOIN NEMP ON #TH.NUMDOC      = NEMP.NUMDOC  
                INNER JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY CODCONCEPTO ORDER BY FECHAINI DESC) [RITEM],CODCONCEPTO,ITEM
                            FROM NCOND WHERE @FECHACONTABLE>=FECHAINI) X ON X.CODCONCEPTO=NCON.CODCONCEPTO AND X.RITEM=1
                INNER JOIN NCOND ON X.CODCONCEPTO=NCOND.CODCONCEPTO AND X.ITEM=NCOND.ITEM
      WHERE  #TH.VALOR_APORTES <> 0 
      AND    #TH.INFO = 'No'  
      ORDER BY NCON.NATURALEZA DESC  
   END
   --FIN CONTABILIZACION NORMAL
   IF @TIPOCONTABILIZACION='2'
   BEGIN
      --CONTABILIZACION POR AREA FUNCIONA Y CENTRO DE COSTO
      print 'DISTRIBUCION 2'
      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                       REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
                       N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG,IDSEDE)  
      SELECT @NROCOMPROBANTE, @COMPANIA, 'DB',   
             DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', 'DB', NCON.CODCONCEPTO, NDIS.CCOSTO,'S',#T.CODNOMINA,0),   
             CASE COALESCE(#TH.RECOBRO,0) WHEN 1 THEN #TH.IDTERCERO_RECO ELSE #TH.IDTERCERO_PRF END, NDIS.CCOSTO, UPPER(NCON.DESCRIPCION), 
             #TH.VALOR_APORTES * (CASE NDIS.PORCENTAJE WHEN NULL THEN 1 ELSE NDIS.PORCENTAJE / 100 END),  
             @CNSPAGO,@NUMDOC,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),#TH.CODCONCEPTO, NDIS.IDAREA,'S', 1,  
             'NOMINA_NCON', 'Movimiento', @CNSPAGO, DBO.FNK_FECHA_SIN_HORA(@FECHATRA), DBO.FNK_FECHA_SIN_HORA(@FECHATRA),   
             'NOMINA','NOMINA', @NUMDOC, #T.CODUNG, NEMP.CODPRG,#T.IDSEDE   
      FROM   #T INNER JOIN  #TH ON #T.CNSNIEPE = #TH.CNSNIEPE 
                               AND #T.NUMDOC   = #TH.NUMDOC 
                INNER JOIN NCON ON #TH.CODCONCEPTO = NCON.CODCONCEPTO 
                INNER JOIN NEMP ON #TH.NUMDOC      = NEMP.NUMDOC 
                 LEFT JOIN NDIS ON NDIS.CNSPAGO    = @CNSPAGO 
                               AND #TH.NUMDOC      = NDIS.NUMDOC
                INNER JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY CODCONCEPTO ORDER BY FECHAINI DESC) [RITEM],CODCONCEPTO,ITEM
                            FROM NCOND WHERE @FECHACONTABLE>=FECHAINI) X ON X.CODCONCEPTO=NCON.CODCONCEPTO AND X.RITEM=1
                INNER JOIN NCOND ON X.CODCONCEPTO=NCOND.CODCONCEPTO AND X.ITEM=NCOND.ITEM
      WHERE  #TH.VALOR_APORTES <> 0 
      AND    #TH.INFO='No' 
      ORDER BY NCON.NATURALEZA DESC  
   END
   --FIN CONTABILIZACION POR AREA FUNCIONA Y CENTRO DE COSTO
   -- PRINT 'Insertando Asiento CR Para Conceptos de la Empresa'  
   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,  
                    REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,  
                    N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG,IDSEDE)  
   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',   
          DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', 'CR', NCON.CODCONCEPTO, #T.CCOSTO,'S',#T.CODNOMINA,0), #TH.IDTERCERO_PRF, #T.CCOSTO,
          UPPER(NCON.DESCRIPCION), #TH.VALOR_APORTES,  
          @CNSPAGO,@NUMDOC,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),#TH.CODCONCEPTO, #T.IDAREA,'S', 1,  
          'NOMINA_NCON', 'Movimiento', @CNSPAGO, DBO.FNK_FECHA_SIN_HORA(@FECHATRA), DBO.FNK_FECHA_SIN_HORA(@FECHATRA),   
          'NOMINA','NOMINA', @NUMDOC, #T.CODUNG, NEMP.CODPRG,#T.IDSEDE 
   FROM   #T INNER JOIN  #TH ON #T.CNSNIEPE = #TH.CNSNIEPE 
                            AND #T.NUMDOC   = #TH.NUMDOC 
             INNER JOIN NCON ON #TH.CODCONCEPTO = NCON.CODCONCEPTO 
             INNER JOIN NEMP ON #TH.NUMDOC      = NEMP.NUMDOC  
             INNER JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY CODCONCEPTO ORDER BY FECHAINI DESC) [RITEM],CODCONCEPTO,ITEM
                         FROM NCOND WHERE @FECHACONTABLE>=FECHAINI) X ON X.CODCONCEPTO=NCON.CODCONCEPTO AND X.RITEM=1
             INNER JOIN NCOND ON X.CODCONCEPTO=NCOND.CODCONCEPTO AND X.ITEM=NCOND.ITEM
   WHERE  #TH.VALOR_APORTES <> 0 
   AND    #TH.INFO = 'No'  
   ORDER BY NCON.NATURALEZA DESC 

   --Reviso los conceptos que no son suceptibles de descuentos
   DECLARE @VLR_SINDTO DECIMAL(14,2)

   SELECT @VLR_SINDTO=SUM(#TH.VALOR)
   FROM   #T INNER JOIN  #TH ON #T.CNSNIEPE = #TH.CNSNIEPE 
                            AND #T.NUMDOC   = #TH.NUMDOC 
             INNER JOIN NCON ON #TH.CODCONCEPTO = NCON.CODCONCEPTO 
             INNER JOIN NEMP ON #TH.NUMDOC      = NEMP.NUMDOC
             INNER JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY CODCONCEPTO ORDER BY FECHAINI DESC) [RITEM],CODCONCEPTO,ITEM
                         FROM NCOND WHERE @FECHACONTABLE>=FECHAINI) X ON X.CODCONCEPTO=NCON.CODCONCEPTO AND X.RITEM=1
             INNER JOIN NCOND ON X.CODCONCEPTO=NCOND.CODCONCEPTO AND X.ITEM=NCOND.ITEM
   WHERE  NCON.TIPO = 'Ingreso' 
   AND    #TH.VALOR <> 0 
   AND    #TH.INFO = 'No' 
   AND    COALESCE(NCOND.SINDEDUC,0)=1

   
   -- PRINT ' -Insertando Registro MCH Neto a Pagar'
   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                    REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
                    N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG,IDSEDE)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 
          DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', 'CR', NCON.CODCONCEPTO, #T.CCOSTO,'S',#T.CODNOMINA,0), #TH.IDTERCERO_PRF, #T.CCOSTO, UPPER(NCON.DESCRIPCION),
          ((#TH.VALOR*100)/(#T.VALOR_INGRESOS-COALESCE(@VLR_SINDTO,0)))*(#T.VALOR_NETO-COALESCE(@VLR_SINDTO,0))*0.01,
          @CNSPAGO,@NUMDOC,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),#TH.CODCONCEPTO, #T.IDAREA,'S', 1,
          'NOMINA_NETO', 'Movimiento', @CNSPAGO, DBO.FNK_FECHA_SIN_HORA(@FECHATRA), DBO.FNK_FECHA_SIN_HORA(@FECHATRA), 
          'NOMINA','NOMINA', @NUMDOC, #T.CODUNG, NEMP.CODPRG,#T.IDSEDE
   FROM   #T INNER JOIN  #TH ON #T.CNSNIEPE = #TH.CNSNIEPE 
                            AND #T.NUMDOC   = #TH.NUMDOC 
             INNER JOIN NCON ON #TH.CODCONCEPTO = NCON.CODCONCEPTO 
             INNER JOIN NEMP ON #TH.NUMDOC      = NEMP.NUMDOC
             INNER JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY CODCONCEPTO ORDER BY FECHAINI DESC) [RITEM],CODCONCEPTO,ITEM
                         FROM NCOND WHERE @FECHACONTABLE>=FECHAINI) X ON X.CODCONCEPTO=NCON.CODCONCEPTO AND X.RITEM=1
             INNER JOIN NCOND ON X.CODCONCEPTO=NCOND.CODCONCEPTO AND X.ITEM=NCOND.ITEM
   WHERE  NCON.TIPO = 'Ingreso' 
   AND    #TH.VALOR <> 0 
   AND    #TH.INFO = 'No' 
   AND    COALESCE(NCOND.SINDEDUC,0)=0
   ORDER BY NCON.NATURALEZA DESC

   -- PRINT ' -Insertando Registro MCH Neto a Pagar'
   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,REFERENCIA1,
                    REFERENCIA2,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,ESTADO,PROCESO,GENERA,
                    N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG,IDSEDE)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 
          DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT, 'NOMINA', 'CR', NCON.CODCONCEPTO, #T.CCOSTO,'S',#T.CODNOMINA,0), #TH.IDTERCERO_PRF, #T.CCOSTO, UPPER(NCON.DESCRIPCION),
          #TH.VALOR,
          @CNSPAGO,@NUMDOC,NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),#TH.CODCONCEPTO, #T.IDAREA,'S', 1,
          'NOMINA_NETO', 'Movimiento', @CNSPAGO, DBO.FNK_FECHA_SIN_HORA(@FECHATRA), DBO.FNK_FECHA_SIN_HORA(@FECHATRA), 
          'NOMINA','NOMINA', @NUMDOC, #T.CODUNG, NEMP.CODPRG,#T.IDSEDE
   FROM   #T INNER JOIN  #TH ON #T.CNSNIEPE = #TH.CNSNIEPE 
                            AND #T.NUMDOC   = #TH.NUMDOC 
             INNER JOIN NCON ON #TH.CODCONCEPTO = NCON.CODCONCEPTO 
             INNER JOIN NEMP ON #TH.NUMDOC      = NEMP.NUMDOC
             INNER JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY CODCONCEPTO ORDER BY FECHAINI DESC) [RITEM],CODCONCEPTO,ITEM
                         FROM NCOND WHERE @FECHACONTABLE>=FECHAINI) X ON X.CODCONCEPTO=NCON.CODCONCEPTO AND X.RITEM=1
             INNER JOIN NCOND ON X.CODCONCEPTO=NCOND.CODCONCEPTO AND X.ITEM=NCOND.ITEM
   WHERE  NCON.TIPO = 'Ingreso' 
   AND    #TH.VALOR <> 0 
   AND    #TH.INFO = 'No' 
   AND    COALESCE(NCOND.SINDEDUC,0)=1
   ORDER BY NCON.NATURALEZA DESC
  
   UPDATE MCHE SET VALOR = MCHE.VALOR + (#T.VALOR_NETO-C.VALOR)
   FROM   (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCHE   
          WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='CR' AND PROCESO = 'NOMINA_NETO' AND REFERENCIA_PRO=@NUMDOC) AS B,  
          (SELECT SUM(VALOR) AS VALOR FROM MCHE   
          WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='CR' AND PROCESO = 'NOMINA_NETO' AND REFERENCIA_PRO=@NUMDOC) AS C,  
          #T  
   WHERE  MCHE.NROASIENTO=B.NROASIENTO AND (#T.VALOR_NETO-C.VALOR)<>0  


   IF EXISTS( SELECT NEDIA.NUMDOC, NEMPFD.CODCONCEPTO, NEDIA.IDTERCERO
             FROM NEDIA INNER JOIN NEMPFD ON NEDIA.CNSPAGO=NEMPFD.CNSPAGO AND NEDIA.NUMDOC=NEMPFD.NUMDOC          
                        INNER JOIN NEVE ON NEMPFD.CODCONCEPTO=NEVE.CODCONCEPTO
             WHERE NEDIA.CNSPAGO=@CNSPAGO
             AND NEDIA.NUMDOC=@NUMDOC
             AND NEDIA.RECOBRO=1
 )
 BEGIN
    UPDATE MCHE SET IDTERCERO=NEDIA.IDTERCERO
    FROM MCHE INNER JOIN (
     SELECT NEDIA.NUMDOC, NEMPFD.CODCONCEPTO, NEDIA.IDTERCERO
    FROM NEDIA INNER JOIN NEMPFD ON NEDIA.CNSPAGO=NEMPFD.CNSPAGO AND NEDIA.NUMDOC=NEMPFD.NUMDOC          
               INNER JOIN NEVE ON NEMPFD.CODCONCEPTO=NEVE.CODCONCEPTO
    WHERE NEDIA.CNSPAGO=@CNSPAGO
                AND NEDIA.NUMDOC=@NUMDOC
                AND NEDIA.RECOBRO=1
             ) NEDIA ON MCHE.IDTERCERO=NEDIA.IDTERCERO AND MCHE.PREFIJO=NEDIA.CODCONCEPTO AND MCHE.TIPO='DB'

 END
     
   -- PRINT 'Poniendo Estado de CONTABILIZADA 
   UPDATE NIEPE SET CONTABILIZADA=1, NROCOMPROBANTE=@NROCOMPROBANTE,COMPROBANTE=@COM,NOREFERENCIA=@NOREFERENCIA 
   WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC

   UPDATE NIEPED SET CONTABILIZADA=1, NROCOMPROBANTE=@NROCOMPROBANTE, COMPROBANTE=@COM, NOREFERENCIA=@NOREFERENCIA 
   FROM NIEPE INNER JOIN
        NIEPED ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC
   WHERE NIEPE.CNSPAGO = @CNSPAGO AND NIEPE.NUMDOC=@NUMDOC
     
   EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME  
   
   DROP TABLE #T
   DROP TABLE #TH
   EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''
   IF NOT EXISTS(SELECT * FROM NIEPE WHERE CNSPAGO=@CNSPAGO AND COALESCE(CONTABILIZADA,0)=0 AND COALESCE(NROCOMPROBANTE,'')='')    
   BEGIN
      UPDATE NPER SET CONTABILIZADA=1 WHERE CNSPAGO=@CNSPAGO
   END
END



