IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNK_INV_CONSUMOYPEDIDOART' AND XTYPE='TF')
BEGIN
   DROP FUNCTION FNK_INV_CONSUMOYPEDIDOART
END

GO
CREATE FUNCTION DBO.FNK_INV_CONSUMOYPEDIDOART(@FECHAINI DATETIME, @FECHAFIN DATETIME, @SOLOVENTAS INT, @IDARTICULO VARCHAR(20), @IDBODEGA VARCHAR(20))
RETURNS @RESULTADOS  
TABLE  (IDARTICULO     VARCHAR(20)    COLLATE database_default,  
        DESCARTICULO   VARCHAR(512)   COLLATE database_default,  
        IDBODEGA       VARCHAR(20)    COLLATE database_default,  
        DESCBODEGA     VARCHAR(100)   COLLATE database_default,  
        EXISTENCIA     DECIMAL(19,6),  
        SALIDAS        DECIMAL(19,6),  
        PROMEDIO       DECIMAL(19,6),  
        ENTRADAS       DECIMAL(19,6),  
        PROM_ENT       DECIMAL(19,6),  
        APEDIR         DECIMAL(19,6))  
AS    
BEGIN  
   DECLARE @VK TABLE (IDARTICULO VARCHAR(20), IDBODEGA VARCHAR(20), EXISTOTAL DECIMAL(14,2))
   DECLARE @IMOV TABLE (IDBODEGA VARCHAR(20), IDARTICULO VARCHAR(20), SALIDAS DECIMAL(14,2), 
                        ENTRADAS DECIMAL(14,2), PROM_SAL DECIMAL(14,2), PROM_ENT DECIMAL(14,2))
   DECLARE @MESES DECIMAL(14,2)  
   SET @MESES = DATEDIFF(DAY, @FECHAINI, @FECHAFIN)/30.0
   SET @FECHAINI=CONVERT(DATE,@FECHAINI)
   SET @FECHAFIN=CONVERT(DATE,@FECHAFIN)
   SET @IDARTICULO=COALESCE(@IDARTICULO,'')

   INSERT INTO @VK (IDARTICULO, IDBODEGA, EXISTOTAL)
   SELECT VK.HERMANO_MAYOR AS IDARTICULO, IDBODEGA, SUM(EXISLOTE) EXISTOTAL
   FROM VWK_HERMANOS_INVENTARIO VK 
		INNER JOIN IEXI ON IEXI.IDBODEGA=(CASE @IDBODEGA WHEN '' THEN IEXI.IDBODEGA ELSE @IDBODEGA END) AND IEXI.IDARTICULO=VK.IDARTICULO
	WHERE VK.HERMANO_MAYOR=CASE WHEN @IDARTICULO='' THEN VK.HERMANO_MAYOR ELSE @IDARTICULO END 
   GROUP BY VK.HERMANO_MAYOR, IDBODEGA

   INSERT INTO @IMOV (IDBODEGA, IDARTICULO, SALIDAS, ENTRADAS, PROM_SAL, PROM_ENT)
   SELECT IDBODEGA, IDARTICULO, SUM(SALIDAS) SALIDAS, SUM(ENTRADAS) ENTRADAS, 
      ROUND(SUM(SALIDAS)/@MESES,0) PROM_SAL, ROUND(SUM(ENTRADAS)/@MESES,0) PROM_ENT
	FROM (
		SELECT A.IDBODEGA, B.HERMANO_MAYOR IDARTICULO, ISNULL(A.NOPRESTACION,'') AS NOPRESTACION,
			SALIDAS =CASE WHEN ITMO.TIPO='Debito' AND ITMO.AFECTAPROM=1 THEN SUM(B.CANTIDAD) ELSE 0 END, 
			ENTRADAS=CASE WHEN ITMO.TIPO='Credito' THEN SUM(B.CANTIDAD) ELSE 0 END
		FROM VWK_IMOV A 
         INNER JOIN ITMO ON A.IDTIPOMOV=ITMO.IDTIPOMOV
         INNER JOIN VWK_IMOVH B ON A.CNSMOV=B.CNSMOV 
		WHERE CONVERT(DATE,FECHAMOV) BETWEEN @FECHAINI AND @FECHAFIN AND A.ESTADO=1 
         AND A.IDBODEGA=(CASE @IDBODEGA WHEN '' THEN A.IDBODEGA ELSE @IDBODEGA END)
			AND B.HERMANO_MAYOR=CASE WHEN @IDARTICULO='' THEN B.HERMANO_MAYOR ELSE @IDARTICULO END 
		GROUP BY A.IDBODEGA, B.HERMANO_MAYOR, ITMO.TIPO, ITMO.AFECTAPROM, ISNULL(A.NOPRESTACION,'')
	)Y 
   WHERE 1=(CASE @SOLOVENTAS WHEN 1 THEN (CASE NOPRESTACION WHEN '' THEN 0 ELSE 1 END) ELSE 1 END)
   GROUP BY IDBODEGA, IDARTICULO

   INSERT INTO @RESULTADOS  
	SELECT T.IDARTICULO, IART.DESCRIPCION AS ARTICULO, T.IDBODEGA, IBOD.DESCRIPCION AS BODEGA, T.EXISTOTAL, 
		COALESCE(X.SALIDAS,0), COALESCE(X.PROM_SAL,0), COALESCE(X.ENTRADAS,0), COALESCE(X.PROM_ENT,0), 
         COALESCE(ROUND(X.PROM_SAL-T.EXISTOTAL,0),0)  
	FROM (SELECT * FROM @VK) AS T
	INNER JOIN IART ON IART.IDARTICULO=T.IDARTICULO
	INNER JOIN IBOD ON IBOD.IDBODEGA=T.IDBODEGA
	LEFT JOIN (SELECT * FROM @IMOV) X ON T.IDBODEGA=X.IDBODEGA AND T.IDARTICULO=X.IDARTICULO 
	WHERE T.EXISTOTAL>=(CASE WHEN X.PROM_SAL<>0 OR X.SALIDAS<>0 THEN 0 ELSE 1 END)    

   RETURN  
END

