
SELECT * FROM HADMF WHERE N_FACTURA='UV18499'

UPDATE  HADMF SET ESTADO='L' WHERE N_FACTURA='UV18500'

DELETE HADMF WHERE N_FACTURA='UV18501'

UPDATE HPRED SET FACTURADA=0,N_FACTURA=NULL WHERE N_FACTURA='UV18501'