
SELECT TOP 10  * FROM HCA

SELECT HTRIAGE.CNSTRIAGE,HTRIAGE.TRIAGE,HTRIAGE.FMTRIAGE,HADM.FECHA,MIN(HCA.FECHA)FECHATEN,AFI.NOMBREAFI,AFI.DOCIDAFILIADO,
AFI.EDAD
FROM HTRIAGE INNER JOIN HADM ON HTRIAGE.CNSTRIAGE=HADM.CNSTRIAGE
             INNER JOIN HCA ON HADM.NOADMISION=HCA.NOADMISION
             INNER JOIN AFI ON HCA.IDAFILIADO=AFI.IDAFILIADO
WHERE HTRIAGE.FECHA>=''
AND HTRIAGE.FECHA<''
GROUP BY HTRIAGE.CNSTRIAGE,HTRIAGE.TRIAGE,HTRIAGE.FMTRIAGE,HADM.FECHA,AFI.NOMBREAFI,AFI.DOCIDAFILIADO,
AFI.EDAD