IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_SOL_REEMBOLSO_CAJAMENOR' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_SOL_REEMBOLSO_CAJAMENOR
END

GO
CREATE PROC DBO.SPK_SOL_REEMBOLSO_CAJAMENOR 
@CODCAJA          VARCHAR(4),
@SYS_COMPUTERNAME VARCHAR(254), 
@SEDE             VARCHAR(5),
@COMPANIA         VARCHAR(2),
@USUARIO          VARCHAR(12)
WITH ENCRYPTION
AS
DECLARE @FECHA          DATETIME
DECLARE @NVOCONSEC      VARCHAR(20)
DECLARE @NVOCONSEC1     VARCHAR(20)   
DECLARE @NVOCONSEC2     VARCHAR(20)
DECLARE @DETALLE        VARCHAR(80)  
DECLARE @OK             INT
DECLARE @FOFI           DECIMAL(14,2)
DECLARE @CODCAJERO      VARCHAR(20)
DECLARE @CCOSTO         VARCHAR(20)
DECLARE @IDAREA         VARCHAR(20)
DECLARE @ITEM           INT
DECLARE @CNSFACJ        VARCHAR(20)
DECLARE @CUENTACM       VARCHAR(16)
DECLARE @VALORTOTAL     DECIMAL(14,2)
DECLARE @ITEMFCJD       SMALLINT
DECLARE @CONCEPTO       VARCHAR(10)
DECLARE @VALORI         DECIMAL(14,2)
DECLARE @VALORT         DECIMAL(14,2)
DECLARE @CUECREDITO     VARCHAR(16)
DECLARE @COMPROBANTECM  VARCHAR(2)
DECLARE @COMPROBANTECM1 VARCHAR(20) 
DECLARE @CNSCMREE       VARCHAR(20)
DECLARE @IDTERCERO      VARCHAR(20)
DECLARE @CIUDAD         VARCHAR(5)
DECLARE @RESPONSABLE    VARCHAR(20)
DECLARE @N_FACTURA      VARCHAR(20) 
BEGIN  
   SELECT @CIUDAD = CIUDAD FROM SED WHERE IDSEDE = @SEDE
   SELECT @FECHA = DBO.FNK_FECHA_SIN_MLS(GETDATE())
   
   EXEC DBO.SPK_CIERRE_DE_CAJA @CODCAJA, @SYS_COMPUTERNAME, @SEDE, @COMPANIA
   
   SELECT @OK = COALESCE(COUNT(*), 0)
   FROM   FCJD INNER JOIN FCJ ON FCJD.CODCAJA = FCJ.CODCAJA AND FCJD.CNSFACJ = FCJ.CNSFACJ
   WHERE  FCJD.CODCAJA = @CODCAJA
   AND    COALESCE(FCJ.CONTABILIZADA,0) = 0 
   
   IF @OK <= 0
   BEGIN
      RETURN
   END
   
   
   SELECT @FOFI = FOFI , @CUECREDITO = CUENTACXP_CM, @COMPROBANTECM = COMPROBANTE_CM,
          @RESPONSABLE = RESPONSABLE
   FROM   CAJ
   WHERE  CODCAJA = @CODCAJA
   
   SELECT @CODCAJERO = CODCAJERO FROM USUSU WHERE USUARIO = @USUARIO
   
   EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@CMREE',  @CNSCMREE OUTPUT  
   SELECT @CNSCMREE = @SEDE + REPLACE(SPACE(8 - LEN(@CNSCMREE))+LTRIM(RTRIM(@CNSCMREE)),SPACE(1),0)
   
   INSERT INTO CMREE ( CNSCMREE, CODCAJA, DESCRIPCION, FECHA, ESTADO )
   SELECT @CNSCMREE, @CODCAJA, 'Reembolso ' + CAST(@FECHA AS VARCHAR(30)), @FECHA, 'S'
   
   UPDATE FCJ SET CNSCMREE = @CNSCMREE 
   WHERE  FCJ.CODCAJA = @CODCAJA
   AND    (FCJ.CONTABILIZADA = 0 OR FCJ.CONTABILIZADA IS NULL)
   
   EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@FCXP',  @NVOCONSEC OUTPUT  
   SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
   -- 002_BEGIN_JEDM.2010.JUN.02
   -- EL NUMERO DE FACTURA ANTES ERA EL CODCAJA, PERO COMO NECESITAMOS INGRESAR EN FTRCONT Y ALLI EL NUMERO DE FACTURA ES UNICO POR TERCERO,
   -- LO CAMBIAMOS A CAJA + A?O + MES + DIA
   SELECT @N_FACTURA = @CODCAJA + CAST(YEAR(@FECHA) AS VARCHAR(4)) + 
                                  CASE WHEN MONTH(@FECHA) > 9 THEN CAST(MONTH(@FECHA) AS VARCHAR(2)) 
                                       ELSE '0' + LTRIM(RTRIM(CAST(MONTH(@FECHA) AS VARCHAR(2))))
                                  END +
                                  CASE WHEN DAY(@FECHA) > 9 THEN CAST(DAY(@FECHA) AS VARCHAR(2))
                                       ELSE '0' + LTRIM(RTRIM(CAST(DAY(@FECHA) AS VARCHAR(2))))
                                  END + '_' + 
                                  CASE WHEN DATEPART(HH,@FECHA) > 9 THEN CAST(DATEPART(HH,@FECHA) AS VARCHAR(2))
                                       ELSE '0' + LTRIM(RTRIM(CAST(DATEPART(HH,@FECHA) AS VARCHAR(2)))) 
                                  END + 
                                  CASE WHEN DATEPART(MI, @FECHA) > 9 THEN CAST(DATEPART(MI, @FECHA) AS VARCHAR(2))
                                       ELSE '0' + LTRIM(RTRIM(CAST(DATEPART(MI, @FECHA) AS VARCHAR(2))))
                                  END     
                                  
   -- 002_END_JEDM.2010.JUN.02
   INSERT INTO FCXP( CNSFCXP, FECHA, CNSFCOM, IDTERCERO, NOREFERENCIA, F_FACTURAREF, F_VENCE, VALOR, ESTADO, F_CANCELADO,
                     USUARIO, TIPOCXP, PROCEDENCIA, OBSERVACION, COMPANIA, SYS_ComputerName, USUARIOMOD, FECHAMOD, NUMCUOTA,
                     MARCACONT, CONTABILIZADA, NROCOMPROBANTE, SALDO, VLR_DESCUENTO, VLR_IVA, VLR_NETO, VLR_IMPUESTOS,
                     SALDO_IMPUESTO, VLR_NOTASDEBITO, VLR_COMISION, VLR_GLOSAS, VLR_FLETE, CUEDEBITO, CUECREDITO ,CNSFCXPPM,
                     MODALIDAD, SUBSIDIO, IDCONTRATO, VLR_NOTASCREDITO, VLR_ABONOS, IDSEDE, PERIODO_ANO, PERIODO_MES, CODUNG,
                     CODPRG, CIUDAD, ENPRESUPUESTO, CAJAMENOR)  
   SELECT @NVOCONSEC, @FECHA, NULL, @RESPONSABLE, @N_FACTURA /*@CODCAJA*/, @FECHA, @FECHA, 0, 'N', NULL, @USUARIO, 
          DBO.FNK_VALORVARIABLE('IDTIPOCXP_DEFAULT'), 'CAJAMENOR', 'REEMBOLSO DE CAJA MENOR'+@CODCAJA, @COMPANIA, @SYS_COMPUTERNAME, NULL,
          NULL, NULL, 0, 1, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, @CUECREDITO, NULL, 'Evento',  'Total', '', 0, 0, @SEDE,
          YEAR(@FECHA), MONTH(@FECHA), NULL, NULL, @CIUDAD,0, @CODCAJA
   
   UPDATE CMREE SET CNSFCXP= @NVOCONSEC WHERE CNSCMREE=@CNSCMREE
   -- MOD.JQUIROGA 20090808
   EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@MCP',  @NVOCONSEC1 OUTPUT  
   SELECT @NVOCONSEC1 = @SEDE + REPLACE(SPACE(14- LEN(@NVOCONSEC1))+LTRIM(RTRIM(@NVOCONSEC1)),SPACE(1),0)
   SELECT @COMPROBANTECM1 = '@COM' + @COMPROBANTECM
   EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, @COMPROBANTECM1,  @NVOCONSEC2 OUTPUT  
   SELECT @NVOCONSEC2 = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC2))+LTRIM(RTRIM(@NVOCONSEC2)),SPACE(1),0)
   -- CONTABILIZACION
   INSERT INTO MCPE ( COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1,
                     REFERENCIA2, REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO, ANULADO, COMPROBANTE, IDTERCERO,
                     BANCO, NOCHEQUE, VALOR_CHEQUE, RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA )
   SELECT @COMPANIA, @NVOCONSEC1, 'CAJAMENOR', @NVOCONSEC2, YEAR(@FECHA), MONTH(@FECHA), @FECHA, 0, 0, @CNSCMREE, @N_FACTURA,@CODCAJA,
          @USUARIO, @FECHA, NULL, 'REEMBOLSO CAJA MENOR No. '+@CODCAJA, @SEDE, 0, NULL, @COMPROBANTECM, @RESPONSABLE, NULL, NULL, 0, NULL, NULL, 0, NULL
   
   SELECT @VALORI = 0
   SELECT @VALORT = 0
   SELECT @ITEM   = 0

   UPDATE CMREE SET NROCOMPROBANTE= @NVOCONSEC1 WHERE CNSCMREE=@CNSCMREE

   DECLARE CM_CURSOR CURSOR FOR      
   SELECT FCJD.CNSFACJ, FCJD.ITEM, CPCJ.CUENTA, ISNULL(FCJD.VALORTOTAL,0), FCJD.CONCEPTO, FCJD.AREAFUNCIONAL, ISNULL(FCJD.ESIMPTOGEN,0), -- MOD.JQUIROGA 20090808 (ISNULL(FCJD.ESIMPTOGEN,0))
          FCJ.CCOSTO, FCJ.IDTERCERO
   FROM   FCJD INNER JOIN FCJ  ON FCJD.CODCAJA  = FCJ.CODCAJA AND FCJD.CNSFACJ = FCJ.CNSFACJ
               INNER JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO   
   WHERE  FCJ.CNSCMREE  =  @CNSCMREE
   AND    FCJ.CLASE_FAC =  'PAGO'
   AND    FCJ.ESTADO    <> 'A'   
   --AND    FCJ.CONCEPTO<>DBO.FNK_VALORVARIABLE('IDCJTECXP') --SE ADICIONA VALIDACION POR LAS ORDENES DE PAGO
   AND NOT EXISTS(SELECT * FROM FCXPP WHERE CODCAJA=FCJ.CODCAJA AND CNSFACJ=FCJ.CNSFACJ)
   UNION ALL 
   SELECT FCJD.CNSFACJ, FCJD.ITEM, CPCJ.CUENTA, ISNULL(FCJD.VALORTOTAL,0), FCJD.CONCEPTO, FCJD.AREAFUNCIONAL, ISNULL(FCJD.ESIMPTOGEN,0), -- MOD.JQUIROGA 20090808 (ISNULL(FCJD.ESIMPTOGEN,0))
          (SELECT TOP 1 CCOSTO FROM FCXPD WHERE FCXPD.CNSFCXP=FCXP.CNSFCXP AND COALESCE(FCXPD.CCOSTO,'')<>''), FCXP.IDTERCERO
   FROM   FCJD INNER JOIN FCJ  ON FCJD.CODCAJA  = FCJ.CODCAJA AND FCJD.CNSFACJ = FCJ.CNSFACJ
               INNER JOIN CPCJ ON FCJD.CONCEPTO = CPCJ.CODIGO  
               INNER JOIN FCXPP ON FCXPP.CNSFCXPP=FCJD.IDSERVICIO AND FCXPP.CODCAJA=FCJD.CODCAJA AND FCXPP.CNSFACJ=FCJD.CNSFACJ
               INNER JOIN FCXP  ON FCXPP.CNSFCXP=FCXP.CNSFCXP
   WHERE  FCJ.CNSCMREE  =  @CNSCMREE
   AND    FCJ.CLASE_FAC =  'PAGO'
   AND    FCJ.ESTADO    <> 'A'  
   AND    FCJD.CONCEPTO=DBO.FNK_VALORVARIABLE('IDCJTECXP')
   
   OPEN CM_CURSOR  
   FETCH NEXT FROM CM_CURSOR  
   INTO @CNSFACJ, @ITEMFCJD, @CUENTACM, @VALORTOTAL, @CONCEPTO, @IDAREA, @OK, @CCOSTO, @IDTERCERO 
   WHILE @@FETCH_STATUS = 0  
   BEGIN        
      SELECT @ITEM = @ITEM +1
      SELECT @DETALLE = DESCRIPCION FROM CPCJ WHERE CODIGO = @CONCEPTO
      IF @OK = 1
      BEGIN
         SELECT @VALORI = @VALORI + @VALORTOTAL
      END
      
      IF @OK = 0
      BEGIN
         
         SELECT @VALORTOTAL = @VALORTOTAL - ISNULL(SUM(VALORTOTAL),0)
         FROM   FCJD 
         WHERE  CNSFACJ    = @CNSFACJ
         AND    ITEM       = @ITEMFCJD
         AND    ESIMPTOGEN = 1
         
         SELECT @VALORT = @VALORT + @VALORTOTAL      
         
         INSERT INTO FCXPD ( CNSFCXP, ITEM, IDSERVICIO, CANTIDAD, VALOR, ESTADO, N_PRESUP, ITEM_PRESUP, IDCLASEIMP, VLR_DESCUENTO,
                             VLR_IVA, VLR_NETO, NOLOTE, IDGRUPOSER, PREFIJO, CCOSTO, CCOSTO2, IDAREAH, IDAREA, NROCOMPROBANTE,
                             CUENTA_SER, VLR_GLOSAS, CUENTA_GLO, PROCEDENCIA, CODUNG, CODPRG,IDTERCERO )
         SELECT @NVOCONSEC, @ITEM, @CONCEPTO, 1, @VALORTOTAL, 'P', @CNSFACJ, @ITEMFCJD, CASE @OK WHEN 1 THEN '1' ELSE '0' END,
                0, 0, @VALORTOTAL, NULL, NULL, NULL, 
                @CCOSTO, NULL, NULL, @IDAREA, NULL, @CUENTACM, 0, NULL, 'CAJAMENOR', NULL, NULL,@IDTERCERO
      END
      -- TEMPORAL DE CONTABILIZACION
      INSERT INTO MCHE( NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, 
                       REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, USUARIO, FECHA, PREFIJO,
                       IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP,
                       CODUNG, CODPRG, ERROR, IDOPERACION, FECHACONCILIACION, IDPROVEEDOR, ENPRESUPUESTO )
      SELECT @NVOCONSEC1, @COMPANIA, CASE @OK WHEN 1 THEN 'CR' ELSE 'DB' END, @CUENTACM, @IDTERCERO, @CCOSTO,
             @DETALLE, @VALORTOTAL, @CNSFACJ, @ITEMFCJD, NULL, NULL, NULL, NULL, 'Movimiento', NULL, NULL, NULL, @USUARIO, @FECHA, 
             @CONCEPTO, @IDAREA, 'S', '0', 'REEMBOLSO_CM', NULL, NULL, 'CAJAMENOR', @CNSFACJ, 0, NULL, NULL, NULL, NULL, NULL,
             NULL, NULL, 0 
      
      FETCH NEXT FROM CM_CURSOR  
      INTO @CNSFACJ, @ITEMFCJD, @CUENTACM, @VALORTOTAL, @CONCEPTO, @IDAREA, @OK, @CCOSTO, @IDTERCERO  
   END
   CLOSE CM_CURSOR
   DEALLOCATE CM_CURSOR
   EXEC SPK_CALCULOVALORESCXP @NVOCONSEC
   --UPDATE FCXP SET SALDO = @VALORT, VLR_NETO = @VALORT, VLR_IMPUESTOS = @VALORI
   --WHERE  CNSFCXP = @NVOCONSEC   
   
   INSERT INTO MCHE( NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, 
                    REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, USUARIO, FECHA, PREFIJO,
                    IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, CNSFCXCXP,
                    CODUNG, CODPRG, ERROR, IDOPERACION, FECHACONCILIACION, IDPROVEEDOR, ENPRESUPUESTO )
   SELECT @NVOCONSEC1, @COMPANIA,  'CR', @CUECREDITO, @RESPONSABLE, @CCOSTO, 'CXP', @VALORT - @VALORI, @CNSCMREE, NULL, NULL, NULL,
          NULL, NULL, 'Movimiento', NULL, NULL, NULL, @USUARIO, @FECHA, NULL, NULL, 'S', '0', 'REEMBOLSO_CM', NULL, NULL, 'CAJAMENOR', 
          @CNSCMREE, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0 
   
   UPDATE FCJ  SET CONTABILIZADA = 1,NROCOMPROBANTE=@NVOCONSEC1 WHERE CNSCMREE = @CNSCMREE
   UPDATE FCXP SET CONTABILIZADA = 1,NROCOMPROBANTE=@NVOCONSEC1 WHERE CNSFCXP=@NVOCONSEC
   

   EXEC SPK_NC_REVISAR_COMPROBANTE @COMPANIA, @NVOCONSEC1
   EXEC SPK_NC_SUMA_DBCR @NVOCONSEC1
   EXEC SPK_NC_REVISAMCPE @NVOCONSEC1,@COMPANIA,@USUARIO,@SEDE,@SYS_COMPUTERNAME
   --001_BEGIN_JEDM.2010.JUN.02
   -- SE DEBE CREAR EN FTRCONT PARA LOS ANALISIS DE VTO
   INSERT INTO FTRCONT(IDTERCERO, N_FACTURA, CLASE, F_FACTURA, F_VENCE, VALOR, ESTADO )
   SELECT @RESPONSABLE, @N_FACTURA , 'CXP', @FECHA, @FECHA, 0, 'P'
   --001_END_JEDM.2010.JUN.02
      
END



