IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'FDIAN'  AND   C.NAME = 'LONGFTR')
BEGIN
   ALTER TABLE FDIAN  ADD LONGFTR 
END