SELECT PRE.NOM_PREFIJO, CIT.CONSECUTIVO, AUT.IDAUT,CONVERT(VARCHAR,AUT.FECHA,103)FECHA,CONVERT(VARCHAR,AUT.FECHA,108)HORA,  AFI.NOMBREAFI [PACIENTE], AFI.TIPO_DOC [TIPO DOCUMENTO], AFI.DOCIDAFILIADO [DOCUMENTO], AFI.FNACIMIENTO [F. NACIMIENTO], AFI.EDAD , AFI.EMAIL, AFI.CELULAR, MED.NOMBRE [MEDICO], MES.DESCRIPCION [ESPECIALIDAD], PLN.DESCPLAN [PLAN], AFI.DIRECCION , TGEN.DESCRIPCION [DISTRITO], SER.DESCSERVICIO [EXAMEN]
		,CASE WHEN LORD.ESTADO = 'I' THEN 'Ingresado' WHEN LORD.ESTADO = 'R' THEN 'Con Resultado' ELSE 'Pendiente' END [ESTADO_DESC] , LING.FECHA [FECHA INGRESO] , LORD.FECHARES [FECHA RESULTADO], LORDD.MEMO [RESULTADO],
      STUFF((
               SELECT DISTINCT ', '+ CONCAT('Fecha:',CONVERT(VARCHAR,FECHA,103),'  Motivo:',MOTIVO,'  NOTA :',NOTA) 
               FROM AUTNOT WHERE IDAUT=AUTD.IDAUT
               FOR XML PATH('')
            ),1,1,'') NOTAS
FROM AUTD
INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT
INNER JOIN PRE ON AUT.PREFIJO = PRE.PREFIJO
INNER JOIN SER ON AUTD.IDSERVICIO = SER.IDSERVICIO
INNER JOIN AFI ON AUT.IDAFILIADO = AFI.IDAFILIADO
LEFT JOIN CIT ON AUT.CONSECUTIVOCIT = CIT.CONSECUTIVO
LEFT JOIN MED ON CIT.IDMEDICO = MED.IDMEDICO
LEFT JOIN MES ON CIT.IDEMEDICA = MES.IDEMEDICA
LEFT JOIN PLN ON AUT.IDPLAN = PLN.IDPLAN
LEFT JOIN LING ON AUTD.IDAUT = LING.NOPRESTACION
LEFT JOIN LORD ON LING.NOINGRESO = LORD.NOINGRESO AND AUTD.IDSERVICIO = LORD.IDSERVICIO
LEFT JOIN LORDD ON LORD.NORDEN = LORDD.NORDEN AND LORD.IDSERVICIO = LORDD.IDSERVICIO AND LORDD.NOITEM = 1
LEFT JOIN TGEN ON TGEN.TABLA = 'CORREGIMIENTOS' AND AFI.CORREGIMIENTO = TGEN.CODIGO
WHERE AUT.PREFIJO IN ( DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO'), DBO.FNK_VALORVARIABLE('PREFIJOAPOYODX') )
AND CONVERT(DATE,AUT.FECHA)>= '20241101' AND CONVERT(DATE,AUT.FECHA)<= '20241130'
