SELECT * FROM #A

UPDATE FTRE SET NOTIFICADO=0 WHERE FTRN_FACTURA IN(SELECT * FROM #A)

UPDATE FTR SET PDF=0 WHERE N_FACTURA IN(SELECT * FROM #A)

SELECT * FROM ACJ WHERE CODCAJA='007'



SELECT  * FROM CJR WHERE CODCAJERO='37752280'