IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_AFACTURAR_COPAGOS' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_AFACTURAR_COPAGOS
END
GO
CREATE PROC DBO.SPK_AFACTURAR_COPAGOS
@NOADMISION VARCHAR(16),
@CNSRPDX    VARCHAR(20),
@USUARIO    VARCHAR(20)=NULL,
@CNSMOV     VARCHAR(20)=NULL
WITH ENCRYPTION
AS          
DECLARE @TIPOFACTURACION VARCHAR(1)
DECLARE @FACTPORAFU      SMALLINT
DECLARE @IDTERCEROCA     VARCHAR(20)
DECLARE @IDPLAN          VARCHAR(6)
DECLARE @DESCRIPCION     VARCHAR(80)
DECLARE @OK              INT
DECLARE @ITEM            INT
DECLARE @IDSEDE          VARCHAR(5)
DECLARE @ITEMRPDX        INT
DECLARE @PFACTURARIND    SMALLINT
DECLARE @TIPOTERCONTA    VARCHAR(10)
DECLARE @COPAGOPROPIO    SMALLINT
BEGIN
   PRINT '@CNSRPDX='+@CNSRPDX
   SELECT @COPAGOPROPIO=PPT.COPAGOIND
   FROM  HADM  INNER JOIN PPT ON PPT.IDTERCERO=HADM.IDTERCERO AND PPT.IDPLAN=HADM.IDPLAN
   WHERE NOADMISION=@NOADMISION

   PRINT 'INSERTO COPAGOS POR PREFIJO '
   SELECT @IDSEDE=HADM.IDSEDE,@IDTERCEROCA=AFI.DOCIDAFILIADO
   FROM HADM INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO
   WHERE NOADMISION=@NOADMISION
   --SELECT @IDTERCEROCA=DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR')
   SELECT @IDPLAN=DBO.FNK_VALORVARIABLE('IDPLANPART')
   SELECT @DESCRIPCION=PLN.DESCPLAN FROM PLN WHERE IDPLAN=@IDPLAN
   SELECT @TIPOTERCONTA=DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART')

   --IF COALESCE(@COPAGOPROPIO,0)=1
   --BEGIN
   --   UPDATE RPDX SET  IDTERCERO=@IDTERCEROCA, ID1=@IDPLAN, NOMBRE='Copago Fijo', CANTIDAD=1, CANTIDAD1=0, CANTIDAD2=1, ID2='CP', 
   --                     ID4=@IDSEDE,VALOR10=1,ID5=@TIPOTERCONTA,ID6='018'
   --   WHERE  CNS= @CNSRPDX
   --END
   --ELSE
   --BEGIN
      IF COALESCE(@CNSMOV,'')=''
      BEGIN
         INSERT INTO RPDX (CNS, IDTERCERO, ID1, NOMBRE, CANTIDAD, CANTIDAD1, CANTIDAD2, ID2, ID4,VALOR10,ID5,ID6) 
         SELECT @CNSRPDX, @IDTERCEROCA, @IDPLAN,NOM_PREFIJO ,ROW_NUMBER() OVER(ORDER  BY HPRE.PREFIJO  DESC), 0, COUNT(*), 'C',
                @IDSEDE,1,@TIPOTERCONTA,HPRE.PREFIJO
         FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                   INNER JOIN PRE   ON HPRE.PREFIJO=PRE.PREFIJO
         WHERE HPRE.NOADMISION=@NOADMISION
         AND COALESCE(HPRED.VALORCOPAGO,0)>0
         AND COALESCE(N_FACTURAH,'')=''
         GROUP BY HPRE.PREFIJO,PRE.NOM_PREFIJO
      END
      ELSE
      BEGIN 
         INSERT INTO RPDX (CNS, IDTERCERO, ID1, NOMBRE, CANTIDAD, CANTIDAD1, CANTIDAD2, ID2, ID4,VALOR10,ID5,ID6) 
         SELECT @CNSRPDX, @IDTERCEROCA, @IDPLAN,NOM_PREFIJO ,ROW_NUMBER() OVER(ORDER  BY HPRE.PREFIJO  DESC), 0, COUNT(*), 'C',
                @IDSEDE,1,@TIPOTERCONTA,HPRE.PREFIJO
         FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                   INNER JOIN PRE   ON HPRE.PREFIJO=PRE.PREFIJO
         WHERE HPRE.NOADMISION=@NOADMISION
         AND COALESCE(HPRED.VALORCOPAGO,0)>0
         AND COALESCE(N_FACTURAH,'')=''
         AND EXISTS(SELECT * FROM IMOVH WHERE CNSMOV=@CNSMOV AND NOPRESTACION=HPRE.NOPRESTACION)
         GROUP BY HPRE.PREFIJO,PRE.NOM_PREFIJO
      END   
   --END
END

