
SELECT  * FROM USUSU WHERE USUARIO='JJIMENEZ'
INSERT INTO USUSU
SELECT  * FROM KUNIPSSAM.DBO.USUSU WHERE USUARIO='JJIMENEZ'

SELECT TOP 10 * FROM UBEQ
SELECT TOP 10 * FROM MED

UPDATE USUSU SET SYS_ComputerName='ADMISIONES',IDMEDICO='1003230915' WHERE USUARIO='JJIMENEZ'

SELECT TOP 10 * FROM API_LOG WHERE USUARIO='JJIMENEZ' ORDER BY ITEM DESC

EXEC SPQ_JSON '{"MODELO":"FTR_IMPRESION","METODO":"DATOSFTR","PARAMETROS":{"N_FACTURA":"HAC51003"},"USUARIO":"JJIMENEZ"}'

SELECT  * FROM HPRED WHERE N_FACTURA='HAC51003'
SELECT  * FROM FTRD WHERE N_FACTURA='HAC51003'

SELECT PAQUETE,  * FROM FTR WHERE   N_FACTURA='HAC51003'

use KUNIPSSAM

UPDATE FTR SET F_fACTURA=DATEADD(DAY,4,F_FACTURA),F_VENCE=DATEADD(DAY,4,F_VENCE) WHERE N_FACTURA='UV18974'


SELECT  * FROM FTR WHERE N_FACTURA='UV18974'