use kcoc

SELECT  * FROM CAJR WHERE CODCAJA<>'C001'

UPDATE CAJR SET VALOR=0 WHERE CODCAJA<>'C001'

SELECT  * FROM ACJ WHERE ABIERTA=1 AND CODCAJA<>'C001'

UPDATE ACJ SET ABIERTA=0 WHERE ABIERTA=1 AND CODCAJA<>'C001'
UPDATE CAJ SET ABIERTA=0 WHERE ABIERTA=1 AND CODCAJA<>'C001'

---
use kcocut