


SELECT  * 
FROM HADM INNER JOIN  QXPCX ON HADM.NOADMISION=QXPCX.NOADMISION
          INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO
          INNER JOIN QXPCXD ON QXPCX.CONSECUTIVO=QXPCXD.CONSECUTIVO
          INNER JOIN SER ON QXPCXD.IDSERVICIO=SER.IDSERVICIO
WHERE HADM.FECHA>='01/01/2022' AND HADM.FECHA<'01/01/2023'
AND SER.DESCSERVICIO LIKE '%PARTO%'


SELECT  * 
FROM HADM INNER JOIN  HPRE ON HADM.NOADMISION=HPRE.NOADMISION
          INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
          INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
WHERE HADM.FECHA>='01/01/2022' AND HADM.FECHA<'01/01/2023'
AND SER.DESCSERVICIO LIKE '%PARTO%'
