CREATE OR ALTER PROCEDURE DBO.SPK_VALIDAR_IZIPAY_JOB
@IDKAPAGE INT = NULL,
@CODCAJA VARCHAR(10)= NULL,
@USUCAJA VARCHAR(20)=NULL,
@TIPOFAC VARCHAR(10)='Boleta'
WITH ENCRYPTION
AS 
DECLARE  @IDKPAGE INT			,@paymentOrderId VARCHAR(20),@NOADMISION VARCHAR(20)
		,@DPR VARCHAR(20)		,@SEDE VARCHAR(6)			,@SEDEV VARCHAR(6) --SEDE FACTURA LINK
		,@USUARIO VARCHAR(20)	,@IDTERCERO VARCHAR(20)		,@CODCAJA_2 VARCHAR(20)
		,@FECHAFACT  DATETIME		,@USUCAJA_2 VARCHAR(20)
		,@COMPANIA VARCHAR(2)	,@PROCEDENCIA VARCHAR(20)
		,@TABLA VARCHAR(20)		,@VALOR  DECIMAL(14,2)		,@FACTURA     VARCHAR(20)
		,@ESTADO VARCHAR(20)	,@SQL VARCHAR(MAX)			,@CNSFACJ     VARCHAR(20)
		,@CNSACJ VARCHAR(20)	,@CNSPCJ VARCHAR(20)		,@BCO         VARCHAR(3)
		,@CTA    VARCHAR(40)	,@SUC VARCHAR(2)			,@DATOBCO     VARCHAR(100)
		,@DOCIDAFILIADO	VARCHAR(20)							,@NOMBREAFI VARCHAR(200)
		,@NOMBRE_SEDE VARCHAR(20)							,@SMS VARCHAR(MAX)
		,@MENSAJE VARCHAR(MAX)								,@RAZONSOCIAL	VARCHAR(200)	,@NOMBRE_SER VARCHAR(max)
		,@LINK VARCHAR(1000)	,@IDAFILIADO VARCHAR(20)	,@NUMERO VARCHAR(20)	,@NOMBRE_MED			VARCHAR(MAX)
		,@NOMBREMEDI VARCHAR(50),@MODALIDADCIT	VARCHAR(10)	,@FECHA	DATETIME, @FECHA1 	DATETIME	
		,@CODCAJERO VARCHAR(20)	,@SYS_COMPUTERNAME VARCHAR(255), @FECHA_STRING	VARCHAR(MAX)	,@DESCSERVICIO VARCHAR(200)
BEGIN
	SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@SEDEV=DBO.FNK_VALORVARIABLE('IDSEDE_FACTURA_LINK')
	SELECT @FECHAFACT=DBO.FNK_GETDATE()

	PRINT @IDKAPAGE

	IF @IDKAPAGE IS NOT NULL 
	BEGIN
		PRINT ''
		UPDATE FNPAG SET ESTADO=1 WHERE IDKPAGE=@IDKAPAGE
	END

	DECLARE PG_CURSOR CURSOR FOR 
		SELECT IDKPAGE,CONSECUTIVO,USUCOBRA,RESPONSABLEPAGO,PROCEDENCIA,TABLA,paymentOrderId,VALOR,ESTADO 
		FROM  KPAGE 
		WHERE IDKPAGE=COALESCE(@IDKAPAGE, IDKPAGE) 
		AND 1=CASE WHEN @IDKAPAGE IS NOT NULL  THEN 1 ELSE CASE WHEN COALESCE(ESTADO,'SEND') IN('SEND','RUNNING','PAID','ERROR','REFUSED') THEN 1 ELSE 0 END END
		AND 1=CASE WHEN @IDKAPAGE IS NOT NULL THEN 1 ELSE CASE WHEN ESTADO IN('SEND', 'APPROVED','RUNNING','REFUSED') THEN 1 ELSE CASE WHEN COALESCE(REF_PAGO,'')='' THEN 1 ELSE 0 END END END
		ORDER BY IDKPAGE
	OPEN PG_CURSOR    
	FETCH NEXT FROM PG_CURSOR    
	INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
		PRINT 'Valido el kpage'
		IF COALESCE(@ESTADO,'') NOT IN ('PAID', 'APPROVED')
		BEGIN
			BEGIN TRY   
				--IF EXISTS(SELECT 1 FROM KPAGE WHERE IDKPAGE=@IDKPAGE AND COALESCE(ESTADO,'PEND')='ERROR')
				--BEGIN
				--	EXEC DBO.SPK_GENERA_ORDENPAGO_IZIPAY @NOADMISION,@TABLA,@PROCEDENCIA,@IDTERCERO,@VALOR,'',@USUARIO,@IDKPAGE,'CREAR' 
				--END
				--ELSE
				--BEGIN
               PRINT 'VOY A VALIDAR'
					--SELECT @NOADMISION,@TABLA,@PROCEDENCIA,@IDTERCERO,@VALOR,'',@USUARIO,@IDKPAGE,'VALIDAR' 
					EXEC DBO.SPK_GENERA_ORDENPAGO_IZIPAY @NOADMISION,@TABLA,@PROCEDENCIA,@IDTERCERO,@VALOR,'',@USUARIO,@IDKPAGE,'VALIDAR'                 
				--END
			END TRY
			BEGIN CATCH
				FETCH NEXT FROM PG_CURSOR    
				INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO
				CONTINUE
			END CATCH
		END
		PRINT 'Valido el kpage'
		IF EXISTS(SELECT 1 FROM KPAGE WHERE IDKPAGE=@IDKPAGE AND ESTADO='PAID' AND COALESCE(REF_PAGO,'')='')
		BEGIN 
         IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')<>'PERU'
         BEGIN
            PRINT 'Voy a Generar el Recibo de caja'
            IF @TABLA='CIT'
            BEGIN
               SELECT @CODCAJA = LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('CAJA_IZIPAY')))
				   SELECT @USUCAJA = LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('USUARIO_IZIPAY')))
               SELECT @SEDE=UBEQ.IDSEDE
               FROM USUSU INNER JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
               WHERE USUSU.USUARIO='JJIMENEZ'

					SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"INFO_CITA_RECAUDAR","PARAMETROS":{"CONSECUTIVO":"'+@NOADMISION+'","CODCAJA":"'+@CODCAJA+'","INFO":"NO","PASARELA":"WOMPI"}, "USUARIO":"'+@USUCAJA+'"}'
					EXEC SPQ_JSON @SQL

					PRINT 'Verifico la creación del recibo'
					IF EXISTS(SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='CITAS')
					BEGIN
                  PRINT 'RECIBO CREADO--- POR POR EL RECUADO AUTOMATICO'
						SELECT @CNSFACJ=CNSFACJ,@CNSACJ=CNSACJ FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='CITAS'

						UPDATE FCJ SET RECAUDO=1,ENPAGOS=0,N_FACTURA=@FACTURA,IDKPAGE=@IDKPAGE WHERE CNSFACJ=@CNSFACJ AND CNSACJ=@CNSACJ AND CODCAJA=@CODCAJA

						EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@PCJ', @LONGITUD = 8, @LLAMADO = NULL, @NVOCONSEC = @CNSPCJ OUTPUT

						SELECT @CNSPCJ=@SEDE + REPLACE(SPACE(8 - LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)

						SELECT @DATOBCO=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('BCO_CTA_SUC_IZIPAY')))

						SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=1
						SELECT @CTA=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=2
						SELECT @SUC=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=3

						INSERT INTO PCJ(CODCAJA,CNSPCJ,CNSFACJ,TIPOPAGO,VALOR,FECHA,CNSACJ,BANCO,CTA_BCO,SUCURSAL)
						SELECT @CODCAJA,@CNSPCJ,@CNSFACJ,DBO.FNK_VALORVARIABLE('IDCJFPAIZIPAY'),@VALOR,DBO.FNK_GETDATE(),@CNSACJ,@BCO,@CTA,@SUC

						SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"CONFIRMAR_RECIBO","PARAMETROS":{"CNSFACJ":"'+@CNSFACJ+'","CODCAJA":"'+@CODCAJA+'","CNSACJ":"'+@CNSACJ+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'

						EXEC SPQ_JSON @SQL
					END
		         FETCH NEXT FROM PG_CURSOR    
		         INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO

               CONTINUE
            END
         END
			PRINT 'Voy a Generar la Boleta'
			IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@SEDEV)
			BEGIN
				IF @TABLA='CIT'
				BEGIN
					SELECT @SEDE=IDSEDE,@SEDEV=IDSEDE,@IDTERCERO=IDAFILIADO FROM CIT WHERE CONSECUTIVO=@NOADMISION
				END
				IF @TABLA='MAD'
				BEGIN
					SELECT @SEDE = CIT.IDSEDE, @SEDEV = CIT.IDSEDE, @IDTERCERO = MAD.IDAFILIADO FROM MAD 
						INNER JOIN CIT ON MAD.CONSECUTIVOCIT = CIT.CONSECUTIVO
					WHERE MAD.ID = @NOADMISION
				END
				IF @TABLA='AUT'
				BEGIN
					SELECT @SEDE=IDSEDE,@SEDEV=IDSEDE,@IDTERCERO=IDAFILIADO FROM AUT WHERE IDAUT=@NOADMISION
				END
				IF @TABLA='HADM'
				BEGIN
					SELECT @SEDE=IDSEDE,@SEDEV=IDSEDE,@IDTERCERO=IDAFILIADO FROM HADM WHERE NOADMISION=@NOADMISION
				END
				IF @TABLA='HPREP'
				BEGIN
					SELECT @SEDE=HADM.IDSEDE,@SEDEV=HADM.IDSEDE,@IDTERCERO=HADM.IDAFILIADO FROM HPREP 
						INNER JOIN HADM ON HPREP.NOADMISION = HADM.NOADMISION
						INNER JOIN AFI ON HADM.IDAFILIADO = AFI.IDAFILIADO
					WHERE NOPRESUPUESTO=@NOADMISION
				END
			END
			ELSE
			BEGIN
				IF @TABLA='CIT'
				BEGIN
					SELECT @SEDE=IDSEDE,@IDTERCERO=IDAFILIADO  FROM CIT WHERE CONSECUTIVO=@NOADMISION
				END
				IF @TABLA='MAD'
				BEGIN
					SELECT @SEDE = CIT.IDSEDE, @SEDEV = CIT.IDSEDE, @IDTERCERO = MAD.IDAFILIADO FROM MAD 
						INNER JOIN CIT ON MAD.CONSECUTIVOCIT = CIT.CONSECUTIVO
					WHERE MAD.ID = @NOADMISION
				END
				IF @TABLA='AUT'
				BEGIN
					SELECT @SEDE=IDSEDE,@IDTERCERO=IDAFILIADO FROM AUT WHERE IDAUT=@NOADMISION
				END
				IF @TABLA='HADM'
				BEGIN
					SELECT @SEDE=IDSEDE,@IDTERCERO=IDAFILIADO FROM HADM WHERE NOADMISION=@NOADMISION
				END
				IF @TABLA='HPREP'
				BEGIN
					SELECT @SEDE=HADM.IDSEDE,@SEDEV=HADM.IDSEDE,@IDTERCERO=HADM.IDAFILIADO FROM HPREP 
						INNER JOIN HADM ON HPREP.NOADMISION = HADM.NOADMISION
						INNER JOIN AFI ON HADM.IDAFILIADO = AFI.IDAFILIADO
					WHERE NOPRESUPUESTO=@NOADMISION
				END
			END
			--IF @TABLA = 'HADM' AND COALESCE(@USUCAJA,'')<> ''
			--BEGIN
			--	SELECT @CNSACJ =  CAJ.CNSACJ, @CODCAJA = UBEQ.CAJA,@CODCAJERO = USUSU.CODCAJERO
			--	FROM  USUSU 
			--		INNER JOIN UBEQ ON USUSU.SYS_ComputerName = UBEQ.SYS_ComputerName
			--		INNER JOIN CAJ ON UBEQ.CAJA = CAJ.CODCAJA
			--	WHERE  USUARIO = @USUCAJA
			
			--	SELECT @CODCAJA_2 = DBO.FNK_VALORVARIABLE('CAJA_IZIPAY')
			--	SELECT @USUCAJA_2 = DBO.FNK_VALORVARIABLE('USUARIO_IZIPAY')
			--	IF EXISTS (SELECT * FROM FCJ WHERE CODCAJA= @CODCAJA AND NOADMISION = @NOADMISION AND CERRADA = 0 AND  ESTADO='P' AND USUARIO=@CODCAJERO AND PROCEDENCIA='HADM' )
			--	AND NOT EXISTS (SELECT TOP 100   * FROM FCJ WHERE CODCAJA= @CODCAJA_2 AND USUARIO = @USUCAJA_2)
			--	BEGIN
			--		PRINT 'HADM ACTUALIZA USUARIO ==>'
			--		UPDATE FCJ SET CODCAJA = @CODCAJA_2, USUARIO = @USUCAJA_2 WHERE  CODCAJA= @CODCAJA AND NOADMISION = @NOADMISION AND CERRADA = 0 AND  ESTADO='P' AND USUARIO=@CODCAJERO AND PROCEDENCIA='HADM'
			--	END
			--END
			IF DBO.FNK_VALORVARIABLE('IZIPAY_MED_DIFERENTE')='SI'
				AND (SELECT COALESCE(A.PREFIJO,'') FROM AUT A INNER JOIN KPAGE B ON A.IDAUT=B.CONSECUTIVO AND B.TABLA='AUT' WHERE B.IDKPAGE=@IDKPAGE)=DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS')
			BEGIN
				SELECT @CODCAJA = DBO.FNK_VALORVARIABLE('CAJA_IZIPAY_MED')
				SELECT @USUCAJA = DBO.FNK_VALORVARIABLE('USUARIO_IZIPAY_MED')
			END
			ELSE
			BEGIN
				SELECT @CODCAJA = DBO.FNK_VALORVARIABLE('CAJA_IZIPAY')
				SELECT @USUCAJA = DBO.FNK_VALORVARIABLE('USUARIO_IZIPAY')
			END

			IF @TABLA IN ('CIT','MAD')
			BEGIN
				IF @TABLA ='MAD'
				BEGIN
					SELECT @NOADMISION = MAD.CONSECUTIVOCIT FROM MAD 
					WHERE MAD.ID = @NOADMISION
				END

				PRINT 'ENTRA SPK_FACTURACE_PERU_COPA ===================================>'
				EXEC SPK_FACTURACE_PERU_COPA @NOADMISION,@DPR,@COMPANIA,@SEDEV, @USUARIO,'','','','','','CI','', 'FALSE', NULL,@FECHAFACT,@TIPOFAC, @IDTERCERO   
				SELECT @FACTURA=NULL
				PRINT 'SALEEEEEEE SPK_FACTURACE_PERU_COPA ===================================>'

				SELECT @FACTURA=COALESCE(NFACTURA,N_FACTURA) FROM CIT WHERE CONSECUTIVO=@NOADMISION

				UPDATE FTR SET IDSEDE=@SEDE WHERE N_FACTURA=@FACTURA
				UPDATE KPAGE SET FACTURADO='Si',REF_PAGO=@FACTURA WHERE IDKPAGE=@IDKPAGE
			
				
		
				PRINT 'Voy a recaudar'
				IF COALESCE(@CODCAJA,'')<>'' AND EXISTS(SELECT * FROM CAJ WHERE CODCAJA=@CODCAJA)
				BEGIN
					SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"INFO_CITA_RECAUDAR","PARAMETROS":{"CONSECUTIVO":"'+@NOADMISION+'","CODCAJA":"'+@CODCAJA+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'
					EXEC SPQ_JSON @SQL

					--
					PRINT 'Verifico la creación del recibo'
					IF EXISTS(SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='CITAS')
					BEGIN
						SELECT @CNSFACJ=CNSFACJ,@CNSACJ=CNSACJ FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='CITAS'

						UPDATE FCJ SET RECAUDO=1,ENPAGOS=0,N_FACTURA=@FACTURA,IDKPAGE=@IDKPAGE WHERE CNSFACJ=@CNSFACJ AND CNSACJ=@CNSACJ AND CODCAJA=@CODCAJA

						EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@PCJ', @LONGITUD = 8, @LLAMADO = NULL, @NVOCONSEC = @CNSPCJ OUTPUT

						SELECT @CNSPCJ=@SEDE + REPLACE(SPACE(8 - LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)

						SELECT @DATOBCO=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('BCO_CTA_SUC_IZIPAY')))

						SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=1
						SELECT @CTA=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=2
						SELECT @SUC=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=3

						INSERT INTO PCJ(CODCAJA,CNSPCJ,CNSFACJ,TIPOPAGO,VALOR,FECHA,CNSACJ,BANCO,CTA_BCO,SUCURSAL)
						SELECT @CODCAJA,@CNSPCJ,@CNSFACJ,DBO.FNK_VALORVARIABLE('IDCJFPAIZIPAY'),@VALOR,DBO.FNK_GETDATE(),@CNSACJ,@BCO,@CTA,@SUC

						SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"CONFIRMAR_RECIBO","PARAMETROS":{"CNSFACJ":"'+@CNSFACJ+'","CODCAJA":"'+@CODCAJA+'","CNSACJ":"'+@CNSACJ+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'

						EXEC SPQ_JSON @SQL



					END
				END
					IF EXISTS (SELECT * FROM CIT WHERE CONSECUTIVO = @NOADMISION AND COALESCE(NFACTURA,'') <> '' AND COALESCE(CIT.MODALIDAD,'') = 'Virtual') 
					BEGIN
						/*ENVIA LINK DE VIDEO LLAMADA  */
						EXEC SPK_ASIGNA_CITA_LINK @NOADMISION, @USUARIO, 'SI'
					END
			END
			IF @TABLA='AUT'
			BEGIN
				EXEC SPK_FACTURACE_PERU_COPA @NOADMISION,@DPR,@COMPANIA,@SEDEV, @USUARIO,'','','','','','CE','', 'FALSE', NULL,@FECHAFACT,@TIPOFAC, @IDTERCERO   
				SELECT @FACTURA=NULL

				SELECT @FACTURA=COALESCE(NFACTURA,N_FACTURA) FROM AUTD WHERE IDAUT=@NOADMISION AND COALESCE(NOCOBRABLE,0)=0

				UPDATE FTR SET IDSEDE=@SEDE WHERE N_FACTURA=@FACTURA
				UPDATE KPAGE SET FACTURADO='Si',REF_PAGO=@FACTURA WHERE IDKPAGE=@IDKPAGE


				SELECT @CNSACJ =  CAJ.CNSACJ FROM CAJ WHERE CODCAJA=@CODCAJA  
				SELECT  @COMPANIA=COALESCE(USUSU.COMPANIA,'01'),@SYS_COMPUTERNAME=USUSU.SYS_ComputerName,@CODCAJERO=CODCAJERO
				FROM  USUSU 
				WHERE USUARIO=@USUCAJA

				IF NOT EXISTS (SELECT * FROM FCJ WHERE NOADMISION = @NOADMISION AND PROCEDENCIA = 'CE')
				BEGIN
					SET @CNSFACJ=NULL
					EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJ',@CNSFACJ OUTPUT
					SELECT @CNSFACJ =  REPLACE(SPACE(8 - LEN(@CNSFACJ))+LTRIM(RTRIM(@CNSFACJ)),SPACE(1),0)

					INSERT INTO FCJ (CNSFACJ,TIPO,CODCAJA,COMPANIA, CLASE_FAC,CNSACJ,ESTADO,USUARIO,SYS_ComputerName,IDTERCERO, FECHA, TIPOEGRESO, OBSERVACION, PROCEDENCIA, VALORTOTAL , USUARIOLOG
					,BANCO, SUCURSAL, CTA_BCO, NOADMISION, NOPRESTACION, CERRADA, ARCHIVADO, IDPLAN, IDAFILIADO, NOMBRECLIENTE)
					SELECT @CNSFACJ, 'INTERNO', @CODCAJA, @COMPANIA, 'COBRO', @CNSACJ, 'P', @CODCAJERO, @SYS_COMPUTERNAME, AUT.IDPROVEEDOR, DBO.FNK_FECHA_SIN_MLS(GETDATE()), null, '', 'CE',AUT.VALORCOPAGO, @USUARIO
					, null,null,null, @NOADMISION, @NOADMISION, 0, 0, AUT.IDPLAN, AUT.IDAFILIADO, AFI.NOMBREAFI
					FROM AUT 
					INNER JOIN AFI ON AUT.IDAFILIADO = AFI.IDAFILIADO
					WHERE AUT.IDAUT = @NOADMISION

					INSERT INTO FCJD (CODCAJA, CNSFACJ, ITEM, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, TIPODCTO)
					SELECT @CODCAJA, @CNSFACJ, AUTD.NO_ITEM, DBO.FNK_VALORVARIABLE ('IDCJCOPA'), AUTD.VALORCOPAGO, 1, AUTD.VALORCOPAGO, 'N'
					FROM AUTD 
					WHERE AUTD.IDAUT = @NOADMISION

					UPDATE AUT SET NORECIBOCAJA = @CNSFACJ, CODCAJA = @CODCAJA, TIPOCAJA = 'FCJ' WHERE AUT.IDAUT = @NOADMISION


				    UPDATE FCJ SET RECAUDO=1,ENPAGOS=0,N_FACTURA=@FACTURA,IDKPAGE=@IDKPAGE WHERE CNSFACJ=@CNSFACJ AND CNSACJ=@CNSACJ AND CODCAJA=@CODCAJA

				    EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@PCJ', @LONGITUD = 8, @LLAMADO = NULL, @NVOCONSEC = @CNSPCJ OUTPUT

				    SELECT @CNSPCJ=@SEDE + REPLACE(SPACE(8-LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)

				    SELECT @DATOBCO=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('BCO_CTA_SUC_IZIPAY')))

					SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=1
					SELECT @CTA=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=2
					SELECT @SUC=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=3

				    INSERT INTO PCJ(CODCAJA,CNSPCJ,CNSFACJ,TIPOPAGO,VALOR,FECHA,CNSACJ,BANCO,CTA_BCO,SUCURSAL)
				    SELECT @CODCAJA,@CNSPCJ,@CNSFACJ,DBO.FNK_VALORVARIABLE('IDCJFPAIZIPAY'),@VALOR,DBO.FNK_GETDATE(),@CNSACJ,@BCO,@CTA,@SUC

				    SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"CONFIRMAR_RECIBO","PARAMETROS":{"CNSFACJ":"'+@CNSFACJ+'","CODCAJA":"'+@CODCAJA+'","CNSACJ":"'+@CNSACJ+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'

				    EXEC SPQ_JSON @SQL

				    UPDATE AUT SET TIPOPREVIO=IIF(PREFIJO=DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS'),1,2), AUT.FECHA_TIPOPREVIO = DBO.FNK_GETDATE() WHERE IDAUT=@NOADMISION

				END
			END
			
			IF @TABLA = 'HADM'
			BEGIN
				PRINT 'Voy a recaudar POR HADM'
				IF COALESCE(@CODCAJA,'')<>'' AND EXISTS(SELECT * FROM CAJ WHERE CODCAJA=@CODCAJA)
				BEGIN
					IF NOT EXISTS (SELECT * FROM FCJ WHERE NOADMISION = @NOADMISION AND PROCEDENCIA = 'HADM' AND CODCAJA = @CODCAJA)
					BEGIN
						SET @CNSFACJ=NULL
						EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJ',@CNSFACJ OUTPUT
						SELECT @CNSFACJ =  REPLACE(SPACE(8 - LEN(@CNSFACJ))+LTRIM(RTRIM(@CNSFACJ)),SPACE(1),0)

						SELECT @CNSACJ =  CAJ.CNSACJ, @CODCAJERO = USUSU.CODCAJERO, @SYS_COMPUTERNAME = UBEQ.SYS_ComputerName
						FROM  USUSU 
							INNER JOIN UBEQ ON USUSU.SYS_ComputerName = UBEQ.SYS_ComputerName
							INNER JOIN CAJ ON UBEQ.CAJA = CAJ.CODCAJA
						WHERE  USUARIO = @USUCAJA

						INSERT INTO FCJ (CNSFACJ,TIPO,CODCAJA,COMPANIA, CLASE_FAC,CNSACJ,ESTADO,USUARIO ,SYS_ComputerName,IDTERCERO, FECHA, TIPOEGRESO, OBSERVACION, PROCEDENCIA, VALORTOTAL , USUARIOLOG
						,BANCO, SUCURSAL, CTA_BCO, NOADMISION, CERRADA, ARCHIVADO, IDPLAN, IDAFILIADO, NOMBRECLIENTE)
			 
						SELECT @CNSFACJ, 'INTERNO', @CODCAJA, @COMPANIA, 'COBRO', @CNSACJ, 'P', @USUCAJA, @SYS_COMPUTERNAME, HADM.IDTERCERO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, '', 'HADM',HADM.COPAGOVALOR, @USUCAJA
						, null,null,null, @NOADMISION, 0, 0, HADM.IDPLAN, HADM.IDAFILIADO, AFI.NOMBREAFI
						FROM HADM 
						INNER JOIN AFI ON HADM.IDAFILIADO = AFI.IDAFILIADO
						WHERE NOADMISION = @NOADMISION

						INSERT INTO FCJD (CODCAJA, CNSFACJ, ITEM, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, TIPODCTO)
						SELECT @CODCAJA, @CNSFACJ, 1, DBO.FNK_VALORVARIABLE ('IDCJCOPA'), HADM.COPAGOVALOR, 1, HADM.COPAGOVALOR, 'N'
						FROM HADM 
						WHERE NOADMISION = @NOADMISION
					END
					--
					PRINT 'Verifico la creación del recibo'

					--IF EXISTS (SELECT * FROM HADM WHERE HADM.NOADMISION = @NOADMISION AND COALESCE(HADM.N_FACTURA,'') <> '')
					--RETURN
					IF EXISTS (SELECT * FROM HADM WHERE HADM.NOADMISION = @NOADMISION AND COALESCE(HADM.N_FACTURA,'') = '')
					BEGIN
						PRINT 'NO EXIST BOLETA AUN'
						IF EXISTS(SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='HADM')
						BEGIN
							PRINT 'RGISTRO EL DETALEEEEEE'
							SELECT @CNSFACJ=CNSFACJ,@CNSACJ=CNSACJ FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='HADM'

							UPDATE FCJ SET RECAUDO=1,ENPAGOS=0,N_FACTURA=@FACTURA,IDKPAGE=@IDKPAGE WHERE CNSFACJ=@CNSFACJ AND CNSACJ=@CNSACJ AND CODCAJA=@CODCAJA

							EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@PCJ', @LONGITUD = 8, @LLAMADO = NULL, @NVOCONSEC = @CNSPCJ OUTPUT

							SELECT @CNSPCJ=@SEDE + REPLACE(SPACE(8 - LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)

							SELECT @DATOBCO=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('BCO_CTA_SUC_IZIPAY')))

							SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=1
							SELECT @CTA=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=2
							SELECT @SUC=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=3

							IF NOT EXISTS (SELECT * FROM  PCJ WHERE CODCAJA = @CODCAJA AND CNSFACJ = @CNSFACJ)
							BEGIN
								INSERT INTO PCJ(CODCAJA,CNSPCJ,CNSFACJ,TIPOPAGO,VALOR,FECHA,CNSACJ,BANCO,CTA_BCO,SUCURSAL)
								SELECT @CODCAJA,@CNSPCJ,@CNSFACJ,DBO.FNK_VALORVARIABLE('IDCJFPAIZIPAY'),@VALOR,DBO.FNK_GETDATE(),@CNSACJ,@BCO,@CTA,@SUC
							END

							SELECT @SQL='{"MODELO":"RECAUDO_PE","METODO":"COBRAR","PARAMETROS":{"CONSECUTIVO":"'+@NOADMISION+'","CODCAJA":"'+@CODCAJA+'","CNSFACJ":"'+@CNSFACJ+'","PROCEDENCIA":"HADM","TIPOFAC":"'+@TIPOFAC+'"}, "USUARIO":"'+@USUCAJA+'"}'
							EXEC SPQ_JSON @SQL

							SELECT @FACTURA=COALESCE(N_FACTURA,NULL) FROM HADM WHERE NOADMISION=@NOADMISION AND IDKPAGE = @IDKPAGE

							UPDATE KPAGE SET FACTURADO='Si',REF_PAGO=@FACTURA WHERE IDKPAGE=@IDKPAGE

							--SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"CONFIRMAR_RECIBO","PARAMETROS":{"CNSFACJ":"'+@CNSFACJ+'","CODCAJA":"'+@CODCAJA+'","CNSACJ":"'+@CNSACJ+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'
							--EXEC SPQ_JSON @SQL
						END
					END
				END
			END
			IF @TABLA = 'HPREP'
			BEGIN
				PRINT 'VOY  RECAUDAR HPREP'
			
				IF COALESCE(@CODCAJA,'')<>'' AND EXISTS(SELECT * FROM CAJ WHERE CODCAJA=@CODCAJA)
				BEGIN
					IF NOT EXISTS (SELECT * FROM FCJ WHERE NOADMISION = @NOADMISION AND PROCEDENCIA = 'HPREP' AND CODCAJA = @CODCAJA)
					BEGIN
						SET @CNSFACJ=NULL
						EXEC SPK_GENCONSECUTIVO @COMPANIA,@CODCAJA,'@FCJ',@CNSFACJ OUTPUT
						SELECT @CNSFACJ =  REPLACE(SPACE(8 - LEN(@CNSFACJ))+LTRIM(RTRIM(@CNSFACJ)),SPACE(1),0)

						SELECT @CNSACJ =  CAJ.CNSACJ, @CODCAJERO = USUSU.CODCAJERO, @SYS_COMPUTERNAME = UBEQ.SYS_ComputerName
						FROM  USUSU 
							INNER JOIN UBEQ ON USUSU.SYS_ComputerName = UBEQ.SYS_ComputerName
							INNER JOIN CAJ ON UBEQ.CAJA = CAJ.CODCAJA
						WHERE  USUARIO = @USUCAJA

						INSERT INTO FCJ (CNSFACJ,TIPO,CODCAJA,COMPANIA, CLASE_FAC,CNSACJ,ESTADO,USUARIO ,SYS_ComputerName,IDTERCERO, FECHA, TIPOEGRESO, OBSERVACION, PROCEDENCIA, VALORTOTAL , USUARIOLOG
						,BANCO, SUCURSAL, CTA_BCO, NOADMISION, CERRADA, ARCHIVADO, IDPLAN, IDAFILIADO, NOMBRECLIENTE)
			 
						SELECT @CNSFACJ, 'INTERNO', @CODCAJA, @COMPANIA, 'COBRO', @CNSACJ, 'P', @USUCAJA, @SYS_COMPUTERNAME, HADM.IDTERCERO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, '', 'HPREP',HPREP.VALORCOPAGO, @USUCAJA
						, null,null,null, @NOADMISION, 0, 0, HADM.IDPLAN, HADM.IDAFILIADO, AFI.NOMBREAFI
						FROM HPREP 
							INNER JOIN HADM ON HPREP.NOADMISION = HADM.NOADMISION
							INNER JOIN AFI ON HADM.IDAFILIADO = AFI.IDAFILIADO
						WHERE HPREP.NOPRESUPUESTO = @NOADMISION

						INSERT INTO FCJD (CODCAJA, CNSFACJ, ITEM, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, TIPODCTO)
						SELECT @CODCAJA, @CNSFACJ,  ROW_NUMBER() OVER (ORDER BY HPREPD.IDSERVICIO), DBO.FNK_VALORVARIABLE ('IDCJCOPA'), HPREPD.VALORCOPAGO/ HPREPD.CANTIDAD, HPREPD.CANTIDAD, HPREPD.VALORCOPAGO, 'N'
						FROM HPREPD
						WHERE HPREPD.NOPRESUPUESTO = @NOADMISION

						UPDATE HPREP SET NORECIBOCAJA = @CNSFACJ, CODCAJA = @CODCAJA, TIPOCAJA = 'FCJ' WHERE HPREP.NOPRESUPUESTO = @NOADMISION


						UPDATE FCJ SET IDKPAGE=@IDKPAGE WHERE CNSFACJ=@CNSFACJ AND CNSACJ=@CNSACJ AND CODCAJA=@CODCAJA

						EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@PCJ', @LONGITUD = 8, @LLAMADO = NULL, @NVOCONSEC = @CNSPCJ OUTPUT

						SELECT @CNSPCJ=@SEDE + REPLACE(SPACE(8-LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)

						SELECT @DATOBCO=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('BCO_CTA_SUC_IZIPAY')))

							SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=1
							SELECT @CTA=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=2
							SELECT @SUC=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=3

						INSERT INTO PCJ(CODCAJA,CNSPCJ,CNSFACJ,TIPOPAGO,VALOR,FECHA,CNSACJ,BANCO,CTA_BCO,SUCURSAL)
						SELECT @CODCAJA,@CNSPCJ,@CNSFACJ,DBO.FNK_VALORVARIABLE('IDCJFPAIZIPAY'),@VALOR,DBO.FNK_GETDATE(),@CNSACJ,@BCO,@CTA,@SUC

						SELECT @SQL='{"MODELO":"RECAUDO_PE","METODO":"COBRAR","PARAMETROS":{"CONSECUTIVO":"'+@NOADMISION+'","CODCAJA":"'+@CODCAJA+'","CNSFACJ":"'+@CNSFACJ+'","PROCEDENCIA":"HPREP","TIPOFAC":"'+@TIPOFAC+'"}, "USUARIO":"'+@USUCAJA+'"}'
						EXEC SPQ_JSON @SQL
					END
				END
			END
				
			-- VALIDO SI SE ENVIO A SAP Y REINTENTO
			IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP'
			BEGIN
				IF EXISTS(SELECT 1 FROM FTR WHERE N_FACTURA = @FACTURA AND FACTEP = '104' AND ULRPTAAPI IS NULL)
				BEGIN
					PRINT 'REINTENTO ENVIO A SAP'
					EXEC SPK_JSON_FTR_PERU_INTERFAX @FACTURA
				END
			END
		END
		FETCH NEXT FROM PG_CURSOR    
		INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO
	END
	CLOSE PG_CURSOR
	DEALLOCATE PG_CURSOR

END


